### ISSUE TITLE
I want to catch mousehover or mouseleave event on tray on windows platform，Is there any Api can help me。

### ISSUE THREAD

**Issue by zhengw060024** [electron/electron#10006]
* Electron version:
* Operating system:

**Comment by zhengw060024** [comment]
No one can help me ???

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
