### ISSUE TITLE
Electron printToPDF pages content break in half

### ISSUE THREAD

**Issue by dcyFranck** [electron/electron#10013]
Hello guys,

I have a problem when I export pdf. The content of the generated pages is truncated incorrectly.

Is there a solution for this?

Thanks
![cattura](https://user-images.githubusercontent.com/30128541/28218596-55671fa0-68b9-11e7-99d4-d4e1f81681ce.PNG)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
