### ISSUE TITLE
Allow configuring the findInPage text match background color

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#10010]
*[From this StackOverflow question](https://stackoverflow.com/questions/44979911/change-webview-find-on-page-result-style-using-css/45093154#45093154)*

Using `findInPage`, text matches are styled yellow with the active match in orange:

![v9uwi](https://user-images.githubusercontent.com/12821956/28199421-5ccc90ee-681a-11e7-871b-29ecd069d3a0.png)

As far as I can tell, there is no way to change the background colors of these. Looking through the chromium source, these colors seem to be hardcoded: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/layout/LayoutTheme.cpp?dr=CSs&l=816

I'd like a way to change the background colors of these matches to better fit with the rest of our app

**Comment by rachelg** [comment]
More comments left on answer.. see https://www.squarefree.com/bookmarklets/color.html  .. it is suggested by Google as a way to change the background color. Perhaps it could be adapted?

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
