### ISSUE TITLE
Can't get device emulation to work on my system

### ISSUE THREAD

**Issue by matthew-dean** [electron/electron#10014]
* Electron version: 1.7.4
* Operating system: macOS High Sierra (although didn't work on Sierra either)

### Expected behavior

Clicking the devices icon in devtools should change the view to devices. 

### Actual behavior

Nothing happens. However, on another dev's computer on my team, it opens the device view which resizes the page and has the normal Chromium selector.

### How to reproduce

Could this possibly be a problem on multiple monitors? I've never had this problem on Chrome, so I don't see why, but that's one of the few differences between systems.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
