### ISSUE TITLE
SecurityError exception while using web-bluetooth APIs

### ISSUE THREAD

**Issue by nine-fox** [electron/electron#10022]
I can not run the following test web-bluetooth code in the latest electron releases:

    let options:any = {};

    options.acceptAllDevices = true;
    
    var nav: any = navigator;
    try {
        log('Requesting Bluetooth Device...');
        log('with ' + JSON.stringify(options));
        const device = await nav.bluetooth.requestDevice(options);

        log('> Name:             ' + device.name);
        log('> Id:               ' + device.id);
        log('> Connected:        ' + device.gatt.connected);
    } catch (error) {
        log('Argh! ' + error);
    }

* Electron version: 1.7.4 and 1.6.11
* Operating system:Windows10 and mac os 10.11.6

### Expected behavior

I can get the bluetooth device info lists

### Actual behavior

The following message is dumped:
SecurityError: Must be handling a user gesture to show a permission request.

### How to reproduce

Just run the code I pasted from the latest electron.

May I ask, how to avoid this SecurityError? Even I added app.commandLine.appendSwitch('enable-web-bluetooth'); it doesn't work.

Thanks very much.

**Comment by nine-fox** [comment]
BTW, I am using Typescript language, so the await keyword can be translated into js

**Comment by nine-fox** [comment]
Well, just found nw.js can do this without any issues. I will move to that...so I close this.....ooops

**Comment by Jip-Hop** [comment]
I'm still trying to find a workaround to use Web Bluetooth in Electron without a user gesture in 2020... 🌟🌟🌟 

Would love to know if there's a way to avoid the SecurityError.

**Comment by Carlitox7** [comment]
I am with the same problem.
I will have to find the solution in NWjs 😢

**Comment by Jip-Hop** [comment]
It's been a while since I looked into this, but I think I got this working in the end.

Bluetooth related code in my project:
https://github.com/Jip-Hop/Screen-Breach-Sensor/blob/e57eb95691a8b2f7a2bf52e99fe05c776517d91a/public/electron.js#L506-L524
https://github.com/Jip-Hop/Screen-Breach-Sensor/blob/e57eb95691a8b2f7a2bf52e99fe05c776517d91a/src/App.js#L134-L194

The key for me was to handle the "select-bluetooth-device" event from the main process. With Electron you won't get the Chrome Bluetooth device selection dialog (unless you make it yourself). With NWjs you do.
