### ISSUE TITLE
./node_modules/electron/dist/libffmpeg.so had a bug that it can read any file recently

### ISSUE THREAD

**Issue by adamearthhuang** [electron/electron#10031]
can you update ? thanks!
http://www.freebuf.com/vuls/138377.html

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
