### ISSUE TITLE
Contractions always appear as spelling errors

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#1005]
We're using the `spellchecker` module within the `preload` script of a renderer process, and have followed the basic steps for setting it up as the provider via [`web-frame`](https://github.com/atom/atom-shell/blob/master/docs/api/web-frame.md).

However, it seems to break words at the apostrophe mark rather than process the complete contraction. I'm not sure if this is an issue with the dictionary or the affix file, but the result is undesirable:

![](https://s3.amazonaws.com/f.cl.ly/items/3Z0g2b2b221K2R0A412z/Image%202015-01-13%20at%203.01.06%20PM.png)

Any ideas on what's happening?

**Comment by zcbenz** [comment]
When spell checking, `doesn` is first checked to be a wrong word, and then `doesn't` is checked to be correct, but somehow the mark is not removed after the check. In Chrome the word will not be checked when `'` is pressed, I think that is the difference that caused this problem.

Before this is fixed you can simply mark `doesn` as a correct word when spell checking to work around this.

**Comment by wenkaili** [comment]
Just want to see if there's a solution being worked on for this? Is there a recommended workaround besides marking all possible contractions as correct words?

**Comment by nirsmadar** [comment]
+1

**Comment by paulcbetts** [comment]
https://github.com/paulcbetts/electron-spellchecker solves / works around this problem

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
