### ISSUE TITLE
The title is in the middle in win2008R2

### ISSUE THREAD

**Issue by 123gogogo123** [electron/electron#10068]
* Electron version: 1.6.2
* Operating system: win 8.1

The character of title should be aligned to the left

The character of title is in the middle

1. Create electron app
2. Open the app in win 8.1
3. Actually, the character is aligned to left in win 7

**Comment by levrik** [comment]
In Windows 8(.1) window titles are centered.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
