### ISSUE TITLE
Colors in the App Menu Are Wrong in High Contrast Mode on Windows

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#10073]
* Electron version: 1.6.11
* Operating system: Windows 10

While in high contrast mode (in this case, I'm using High Contrast 1), here's how a menu should be themed:

![image](https://user-images.githubusercontent.com/21112697/28428357-0b9a4fe0-6d2e-11e7-9e29-2666edfb230f.png)

Notice the various font colors, the hover highlight color, etc.

The app menu does make an attempt to respond to Windows changing to high contrast, but many of the colors are off:

![image](https://user-images.githubusercontent.com/21112697/28428434-3fdad7f2-6d2e-11e7-9fa5-35517975bac9.png)

I have a feeling that this will end up being a Chromium bug and [this open issue on their issue tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=738292&q=component%3AUI%3EAccessibility&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) lends credence to that feeling, but I wanted to post an issue on here make sure that is the case/make it easier for others to find.

**Comment by Tyriar** [comment]
Looks like this is happening because the menu is using a Chromium view and the correct color is not being pulled in from when the Windows theme changes.

- Code that's run when a Windows theme changes: https://github.com/electron/electron/blob/0ad99444affc5bbf3341e69165a8c26474640bca/atom/browser/ui/views/menu_bar.cc#L166
- Additional colors being set on Linux https://github.com/electron/electron/blob/0ad99444affc5bbf3341e69165a8c26474640bca/atom/browser/ui/views/menu_bar.cc#L33-L45

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
