### ISSUE TITLE
Trigger the :visited state (by new event?)

### ISSUE THREAD

**Issue by flufo** [electron/electron#10083]
Electron does not have a real (browsing) history. I guess because of that, Electron also does not trigger the [`:visited`](https://developer.mozilla.org/en/docs/Web/CSS/:visited) state of `<a>` anchor tags.

So I would like to be able to [trigger the `:visited` state by myself](https://stackoverflow.com/q/44720787/793476). Sadly I can't find any solution to do it.

The DOM does not offer something and I expect that will not change (and that would be an issue for the upstream Chrome project?).

Another idea was, if Electron could offer something like a `check-visited-state` event? With a callback to set the state. 
Maybe Chrome offers already something like that internally that could be brought to the surface? 

What do you think? Would it be feasable?

Or are there any other ideas?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
