### ISSUE TITLE
Development mode Electron behaves unexpectedly with respect to process name and version number

### ISSUE THREAD

**Issue by johnmcdowall** [electron/electron#10087]
* Electron version: 1.16.11
* Operating system: OSX El Capitan 10.11.6

### Expected behavior

When developing Electron apps on my machine, I expect that starting the app should: 

- Use the App Icon as defined and configured in the package.json
- Report the application version as defined and configured in the package.json
- Use a process name that is the name of the application as defined and configured in the package.json

### Actual behavior

Starting Electron locally always results in the Electron process ignoring everything defined in the package.json. 

- It starts using the default Electron app icon
- Calls to `getAppVersion()` return the version of Electron being used
- The process name use is just 'Electron' - not the name of the application. 

### How to reproduce

Start any Electron application on your machine from `npm`. In my case I'm using the `electron-react-boilerplate` from here https://github.com/chentsulin/electron-react-boilerplate - I don't believe it is anything specific about this project as other electron projects behave similarly. 

As a developer I find it extremely surprising that this is the case, and is really unhelpful for various real world scenarios. 

For example, if I want to integrate `electron-updater` I'm obviously going to want to code that up locally, test it locally, and develop the UX locally too. 

This basic scenario is made extremely difficult because of the default way Electron is operating, for one reason because the call to `getAppVersion()` is not reporting the actual app version from `package.json`. So `electron-updater` thinks there's no updates to be had when developing locally, because the app version is `0.0.2` and not greater than Electron's own version number. 

Hopefully you can see why this is a strange and surprising behaviour to have as a default. I can't find any documentation that would explain why this is desirable or how to avoid it. 

Please consider a mechanism allowing developers to actually have Electron behave the following way during local development: 

- Use the actual configured app icon
- Report the actual configured app version
- Use the actual configured app name as the process name, not 'Electron'. 

Thanks!

**Comment by MarshallOfSound** [comment]
> Use the actual configured app icon

Electron doesn't have a formal spec for defining an applications icon, this is traditionally done through third party modules such as `electron-packager`, `electron-forge` or `electron-builder`.  Each of which provides multiple ways to define an application icon.  If you want the app to have your icon in development you need to use API's like `app.dock.setIcon` or the `icon` option when constructing your `BrowserWindow`'s

> Report the actual configured app version

Electron will report your version correctly if you provide the correct path when launching your app.  You can launch your app in two ways with electron, `electron path/to/entry.js` or `electron path/to/package.json`.  If you provide a path to a JS file Electron doesn't know your apps version so reports Electrons version.  If you provide a path to a package.json file Electron will correctly report the apps version because we now know what it is.

> Use the actual configured app name as the process name, not 'Electron'.

This isn't something that can be changed at run time, the process name is literally the name of the executable on disk and the `electron` prebuilt NPM module does not mutate the downloaded binary (otherwise the checksums wouldn't match and users wouldn't be able to validate the binary).  If you wish to do this you can rename the downloaded binaries yourself as part of a `prestart` script.

Also FWIW you won't be able to test the auto updater without your application being signed so you'll need to run your app through `electron-packager` to test the udpater anyway which will do all the things you listed (set the icon and such)

**Comment by MarshallOfSound** [comment]
FWIW I have this monkey patch script which runs `prestart` that sets things like bundle ID's and icons on the development electron binaries

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/vendor/patch_dev.js

**Comment by sandor** [comment]
@MarshallOfSound looking like something I should use. Any little steps for a dummie like me to install and use your script? Would be awesome!
