### ISSUE TITLE
Animations are stops when browser window is moving 

### ISSUE THREAD

**Issue by eVanilla** [electron/electron#10120]
Electron version: 1.6.11
OS: Windows 7
this is exactly what i wrote: https://github.com/EVOKE-LEKTRIQUE/YumiChan
i really don't know why when browser window is moving the Gif animation in DOM is stops & i waiting for 8 days to some one helps me.

**Comment by zeke** [comment]
@EVOKE-LEKTRIQUE do you see a similar behavior when you view this content in Chrome?

**Comment by EVOKE-LEKTRIQUE** [comment]
no ... i use setPosition() to moving the browser window ... so i think this is my problem and ... i really don't know what should am i do

**Comment by EVOKE-LEKTRIQUE** [comment]
no ... i use setPosition() to moving the window ... i think this is my problem ... and i really don't know what should am i doing right now to fixing this problem ...

**Comment by zeke** [comment]
I tried your code locally, and works for me with no lag. I'm on macOS.

![screen shot 2017-07-26 at 6 10 52 pm](https://user-images.githubusercontent.com/2289/28650034-c633f26c-722d-11e7-81a8-d8c52067fe56.png)

**Comment by EVOKE-LEKTRIQUE** [comment]
i know it, i don't mean it has lag ... i mean when window is moving the gif animations is stops !
i tried on different systems ... but still have this problem .

**Comment by EVOKE-LEKTRIQUE** [comment]
You can also change the Gif source and see it

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
