### ISSUE TITLE
React inside electron using HMR keeps requesting update from file:/// protocol even thought I've overridden it with registerFileProtocol

### ISSUE THREAD

**Issue by rw3iss** [electron/electron#10130]
* Electron version: 1.6.11
* Operating system: Mac OSX 10.12 64-bit
 
### Expected behavior

The objective is to load hot updates in both the browser environment and within the electron app, both of which are using the same React codebase.
Upon overriding the file protocol to use http:// to load hot module updates from http instead of file:///, it should make the request to http, however, the electron devtools are still showing a request to file:/// even thought the protocol response callback is passing http://localhost:3000/

### Actual behavior

You'll see the console.log below prints out:
> file request file:///hot/hot-update.json http://localhost:3000/hot/hot-update.json

to show that it is rewriting the file to localhost, but electron is still using file:/// and unable to find it.

### How to reproduce
(You can clone the small repository below to replicate the issue)
```
// before app.on('ready'):
protocol.registerStandardSchemes(['file']);

// Inside onReady handler:
 protocol.unregisterProtocol('file');
  protocol.registerFileProtocol('file', (request, callback) => {

    let url = request.url.substr(7);

    if (request.url.indexOf('hot-update') >= 0) {
      url = 'http://localhost:3000' + url;
    }

    console.log('file request', request.url, url);
    callback({path: url})
  }, (error) => {
    if (error) console.error('Failed to register protocol', error)
  })

```

**You can clone this small repository to replicate the issue:**
git clone https://github.com/rw3iss/react-router4-hmr-appshell-boilerplate

To run:
```
npm install
npm run dev (to start a local webpack-dev-server)
npm run electron (to start the electron)
```

The objective is to load hot updates in both the browser environment and within electron, using the same React codebase.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW I believe you are using the wrong `protocol` method, you probably want to use [`registerHttpProtocol`](https://electron.atom.io/docs/api/protocol/#protocolregisterhttpprotocolscheme-handler-completion) so that you can callback with a redirect request.  The `registerFileProtocol` method only allows you to callback with a file path not another URL, this is why your request is failing.

**Comment by rw3iss** [comment]
Thanks Marshall. I'll consult the community.
