### ISSUE TITLE
Value of min width smaller on Windows

### ISSUE THREAD

**Issue by aleki** [electron/electron#10165]
Hi there!

This is screenshot of Electron API Demos on Linux based system:
![screenshot from 2017-07-31 20-58-28](https://user-images.githubusercontent.com/4836709/28790984-953fb1fa-7633-11e7-8c1b-9f9be73a55d8.png)

and this is screenshot of Electron API Demos on Windows 10:
![2](https://user-images.githubusercontent.com/4836709/28791152-25ad3578-7634-11e7-95c1-b5b920308702.PNG)

We have two windows with different widths: 680px and 664px, but on [this](https://github.com/electron/electron-api-demos/blob/master/main.js#L24) line `minWidth` is set to 680px.

So, I think this is bug.

**Comment by felixrieseberg** [comment]
I'll be damned, I could repro. I'm shocked we didn't catch this earlier, but I'll investigate 🤔

**Comment by felixrieseberg** [comment]
Upon closer inspection, the `outerWidth` property of the window is, in fact, the correct size.

The difference here is that on macOS, we don't account for shadow, chrome, and border. On Windows, we do. The trouble is that fixing this behavior would be a breaking change, but I'd generally agree - people are probably expecting that a window with a given `width` has the same viewport availble across systems.

**Comment by felixrieseberg** [comment]
Upon _even closer_ inspection, everything is alright. Well, cross-platform development is still hard, but things are generally okay. Here's why:

On Windows, calling `window.resizeTo(400, 400)` will result in a window with an `outerWidth` and `outerHeight` of 400. The `innerHeight` and `innerWidth` deviate. I should have had more coffee, but I'm calling it - this is expected behavior. As such, I'm inclined to close this.

_Someone_ could probably make a module that works around this and offers a way of creating a window with an `innerWidth` as property.

@aleki sounds good to you?

**Comment by aleki** [comment]
@felixrieseberg I think that the behavior of this property should be the same on all platforms.
