### ISSUE TITLE
可以调用一些底层吗，比如可以弹出框选择文件，然后移动文件

### ISSUE THREAD

**Issue by s4812785** [electron/electron#10184]
可以调用一些底层吗，比如可以弹出框选择文件，然后移动文件

**Comment by cnBruceHong** [comment]
严格上讲这个不能叫『底层』，
应该是通过H5文件API调用原生文件操作，
可以看下文档：
https://electron.atom.io/docs/api/file-object/

**Comment by KagamiChan** [comment]
> GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the community or to the Slack Channel.

dialogs: https://github.com/electron/electron/blob/master/docs/api/dialog.md
fs: https://nodejs.org/api/fs.html

**Comment by groundwater** [comment]
Translation: 
Can you call some of the underlying, such as pop-up boxes can choose files, and then move the file

**Comment by sofianguy** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
