### ISSUE TITLE
If tooltip window gets stuck electron captures all mouse events

### ISSUE THREAD

**Issue by michalrousal** [electron/electron#10195]
* Electron version: 1.7.5
* Operating system: Windows 10

### Expected behavior

When I move mouse away tooltip window disappears and mouse events keep working as expected.

### Actual behavior

If the tooltip window gets stuck all mouse events are captured by either tooltip or electron window.

### How to reproduce

Run provided example (main.js+test.html) in electron (electron.exe main.js), trigger tooltip window over the button using mouse, let it appear/disappear until it gets stuck (this is relatively hard to repro, fastest for me is to move cursor just around button edge). When it gets stuck it will start to eat mouse events, only way to reset it is to hide the window.
This happens only on Windows, when the window has no frame and contains custom drag area (style="-webkit-app-region: drag")

[stuck-tooltip-eats-mouse-on-windows-repro.zip](https://github.com/electron/electron/files/1200329/stuck-tooltip-eats-mouse-on-windows-repro.zip)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by michalrousal** [comment]
Btw, this wasn't question but bug. I think it is quite clear from description. If you want to close it then it would make more sense to mark it as 'won't fix' since it is edge case so low priority rather than pretend it is question.
______________________________________________________________
> Od: Sofia Nguy <notifications@github.com>
> Komu: electron/electron <electron@noreply.github.com>
> Datum: 03.12.2017 03:09
> Předmět: Re: [electron/electron] If tooltip window gets stuck electron
>
Closed #10195 <https://github.com/electron/electron/issues/10195>.
