### ISSUE TITLE
app.relaunch doesn't work if app run on start (OSX)

### ISSUE THREAD

**Issue by devildant** [electron/electron#10201]
Hello,

i put the plist file for auto start my app on osx inside ~/Library/launchAgents and if i use app.relaunch and app.exit();, the application stop but not relaunch.
it's work perfectly if user launch app, the relaunch work fine but when the application launch by launchAgents doesn't work.

how correct this ?
best regards

plist exemple : 
`<?xml version="1.0" encoding="UTF-8"?>`
`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`
`<plist version="1.0">`
`<dict>`
`  <key>Label</key>`
`  <string>MyApp</string>`
`  <key>ProgramArguments</key>`
`  <array>`
`      <string>/Applications/MyApp/MyApp.app/Contents/MacOS/MyApp</string>`
`    <string>--hidden</string>`
`  </array>`
`  <key>RunAtLoad</key>`
`  <true/>`
`</dict>`
`</plist>`

**Comment by sofianguy** [comment]
@devildant Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by meekaah** [comment]
this was formulated as a question but it really is an issue...
