### ISSUE TITLE
PowerSaveBlocker does not prevent computer sleep

### ISSUE THREAD

**Issue by jakkan** [electron/electron#10212]
The powerSaveBlocker API does not prevent the computer from sleeping on Windows.

**Steps to reproduce**
System: Windows 10 Enterprise running in Bootcamp on Macbook Pro 2015

- In `Control Panel > Hardware and Sound > Power Options > Edit Plan Settings`, set `Put computer to sleep` to 1 minute
- Use ` powerBlockId = electron.remote.powerSaveBlocker.start("prevent-display-sleep");` in your application code
- Start your application
- Wait more than 1 minute

**Expected behavior**

- The computer does not sleep

**Actual behavior**

- The computer sleeps

Is this intended or a bug?

Either way, I would very much like to have prevention of sleep added to Electron. If you want I can try to add it myself to the `"prevent-display-sleep"` blocker type or to another blocker type like `"prevent-system-sleep"`.

I would like to hear what you think would be best.

**Comment by vanessayuenn** [comment]
@jakkan your expectation is correct -- `powerSaveBlocker.start("prevent-display-sleep")` should keep both the system and screen active. However, I am unable to reproduce the issue you described with electron v1.7.5. Which version of electron are you using?

**Comment by jakkan** [comment]
I'm using Electron 1.6.6. I didn't consider that I wasn't using the latest version, but of course it might have been fixed in later releases. I will close this ticket and open a new ticket when I reproduce it on the latest version.

**Comment by chaselal** [comment]
I am able to reproduce this using [Electron version 4.0.5](https://electronjs.org/releases/stable#4.0.5).

Repro steps:
- Windows 10
- Open Settings -> Power & sleep
- Set Sleep to 1 minute
- Run an Electron app that calls `remote.powerSaveBlocker.start("prevent-display-sleep")`
- Let the app idle for 1 minute

Expected behavior:
- The computer does not enter sleep mode

Actual behavior:
- The computer enters sleep mode

**Comment by chaselal** [comment]
I was able to reproduce the problem on Electron version 4.0.6, as well. I set up the Electron quick-start and added a call to `powerSaveBlocker` on app start.

Repro steps (same as above):

- Configure your Windows Settings -> Power & sleep settings as follows:
![Windows 10 power save settings one minute sleep](https://user-images.githubusercontent.com/3928875/53582957-2ff75a80-3b46-11e9-9720-92d16aa61b21.png)
- Clone https://github.com/chaselal/electron-10212/commit/9343948e053c10aa170babf95a8bbac2d42db4dc
- `cd` into the directory
- `npm install`
- `npm start`
- Let the app idle for 1 minute

Expected behavior:
* The computer does not enter sleep mode

Actual behavior:
* The computer enters sleep mode

Remember to reset your power & sleep settings when you're done.

**Comment by alexeykuzmin** [comment]
@chaselal Could you please check the issue on Electron 4.2.9 and the latest Electron 6.0.2?

**Comment by chaselal** [comment]
I was able to reproduce this on Windows 10 Pro version 1809 OS build 17763.678 using Electron versions:
- Electron 4.0.6
- Electron 4.2.9
- Electron 6.0.2

I used the same repro steps listed in https://github.com/electron/electron/issues/10212#issuecomment-468348381. I want to clarify one of them:

> Let the app idle for 1 minute

If I keep the app in focus, then my computer does not enter sleep mode, which is the expected behavior. This is true on all Electron versions tested.

If I unfocus the app, then my computer enters sleep mode after approximately one minute. This does not comply with the expected behavior. This is true on all Electron versions tested.

This bug is a problem for my company, because our app connects with fitness devices using Bluetooth Low Energy and records data from those devices. Our customers sometimes unfocus our app while they exercise. We need to keep the screen on when that happens. We work around this bug by not using powerSaveBlocker at all, and instead calling https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate to keep the screen on.

**Comment by sonhle** [comment]
It happens on Electron 11 as well. Anyone has a fix or workaround to this? Please advice. Thanks

**Comment by nornagon** [comment]
@sonhle please open a new issue with a standalone testcase, preferably using [Electron Fiddle](/electron/fiddle), that exhibits the behavior you're observing. Thanks!

**Comment by Topppy** [comment]
It happens on Electron 13 as well.

**Comment by bierzorutas** [comment]
This is still happening in MacOS totally reproducible, someone has found a solution or workaround ?

**Comment by enionsouza** [comment]
It still happens on Electron 21 (for Ubuntu 22.04 and Windows 10).

**Comment by Gstar123456** [comment]
tor. 24. nov. 2022 kl. 15:53 skrev Enio N. de Souza <
***@***.***>:

> It still happens on Electron 21 (for Ubuntu 22.04 and Windows 10).
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Gstar
