### ISSUE TITLE
Expose a property or emit an event on 'app' with debugger url if browser debugger is enabled via --inspect 

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#10216]
Sometimes I need to use devtools on the browser process on a production build and on OS X there is no console output so I don't know what the URL is.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by TimNZ** [comment]
This is an enhancement request

**Comment by TimNZ** [comment]
I discovered I can get console output from built OS X apps by running the executable in Contents/MacOS directly, so the need for this is reduced.

But it might be useful for programmatic debugging in the future for the app to emit a 'inspector' or similar named event with the URL

**Comment by MarshallOfSound** [comment]
You can obtain this information via `inspect.url()` (A node api)

https://nodejs.org/api/inspector.html#inspectorurl
