### ISSUE TITLE
Screen bounds and workarea Y coordinate shows negative for positive position and positive for negative position

### ISSUE THREAD

**Issue by dominicankev** [electron/electron#10237]
* Electron version: 1.7.5
* Operating system: Windows 10

### Expected behavior

On multi-monitor configuration where a second or third monitor is stacked above the primary display, the starting Y coordinate returned by screen.bounds.y or screen.workarea.y for the monitor above the primary should return a positive Y coordinate.  A screen below the primary monitor should return a negative Y coordinate.

### Actual behavior

screen.bounds.y and screen.workarea.y are returning negative Y coordinate when screen is above primary display and positive Y coordinate when screen is below primary display.

### How to reproduce

With at least two displays configured in the OS, stack the second display above or below the primary display.

console.log(screen.bounds.y)
console.log(screen.workarea.y)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by mrcex** [comment]
@sofianguy This is still a bug. I have 2 displays and when I open 2 electron windows, one on each display and maximize them, on `getBounds()` call I get this info 
`
0: 
height: 2128 width: 3856 x: 2552 y: -8
1: 
height: 1568 width: 2576 x: -8 y: -8` 

although my multi display setup goes from {0,0} coordinates and x and y can never be negative values. The same happens if I try getting info from `window` object where `screenX` and `screenY` return the same values as `getBounds` call.
