### ISSUE TITLE
Add an option to disable window menu with setApplicationMenu()

### ISSUE THREAD

**Issue by popod** [electron/electron#10270]
It will be very usfull to add an option (`onlyAppMenu`) in `setApplicationMenu(menu, onlyAppMenu)` to only show the provided `menu` if the OS accept application menu (like in macOS and Linux Ubuntu). And, with this option enabled, show nothing if the application menu in transformed to a window menu bar (as on Windows).

With this new option, we could now display a menu only if this is an application menu..

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
