### ISSUE TITLE
On screen keyboard

### ISSUE THREAD

**Issue by Hakim2014** [electron/electron#10276]
Hi,
I am building an application on raspberry pi. I need to get a keyboard open when user click on input field. As of now keyboard gets open but its always behind the electron app. I am using matchbox-keyboard and 'child-process' to open the keyboard on the click event of the input field but the keyboard never comes in foreground. Also its a kiosk app with no physical keyboard or mouse all things are touch events. Any help would be great help. Thanks

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
