### ISSUE TITLE
Detect and listen for hardware changes

### ISSUE THREAD

**Issue by njbmartin** [electron/electron#10309]
Audio hardware is just one of the hardware changes we would like to listen to:

https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioHardwareRouteChanges/HandlingAudioHardwareRouteChanges.html

But there could be others such as unplugging displays etc.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
