### ISSUE TITLE
event.preventDefault does not work in "new-window" event for webview with nativeWindowOpen enabled

### ISSUE THREAD

**Issue by steverandy** [electron/electron#10334]
I'm looking for a way to control the default behavior of `new-window` event of a `<webview>` when `nativeWindowOpen` is enabled using webPreferences option.
I've tried `event.preventDefault()` and `return false` but new window still opens.  

Is this a known limitation? Is there other way to prevent the default behavior?

* Electron version: 1.7.3
* Operating system: macOS 10.12.6

### Expected behavior

event.preventDefault should prevent opening new window.

### Actual behavior

event.preventDefault does nothing and new window always opens.

**Comment by f4n** [comment]
Same here, electron 1.7.5 and 1.7.6 beta on Linux

**Comment by DonaldChiang** [comment]
Same here, tested on macOS 10.12.6, electron 1.7.0, 1.7.1, 1.7.3 and 1.8.1
```
webContents.on('new-window', (e, url) => {
  webContents.executeJavaScript(`alert("text")`);
  e.preventDefault();
});
```
it will alert twice.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
