### ISSUE TITLE
webContents.session is broken

### ISSUE THREAD

**Issue by alphadijkstra** [electron/electron#10364]
* Electron version: 1.7.5, also tested and failing with 1.6.5 and 1.4.12 (randomly selected version numbers that were tested) 
* Operating system: Windows 10 Pro 64-bit

### Expected behavior

``windowObject.webContents.session.cookies`` should return all cookies associated with the BrowserWindow object

### Actual behavior

Returns `Session: {}`
Returns: `Cookies: {}` while it should contain all cookies from the browser window.

### How to reproduce

Create a simple electron app and place the following code inside main.js:
```
const electron = require('electron');
const app = electron.app;
const session = electron.session;

app.on('ready', function(){
  const Window = electron.BrowserWindow;
  var windowObject = new Window({show: true, webPreferences:{images:false}});
  windowObject.loadURL("https://www.tweakers.net");
  windowObject.webContents.on('dom-ready', function() {

    //This fails
    console.log(windowObject.webContents.session);
    console.log(windowObject.webContents.session.cookies);

    //This works
    session.defaultSession.cookies.get({}, (error, cookies) => {
      console.log(cookies)
    });

    //This works
    windowObject.webContents.executeJavaScript(`document.cookie;`, true).then(function(result){
      console.log(result);
    });
  });
});
```

**Comment by javan** [comment]
> `headlessLoginWindow.webContents.session`

Should that be `windowObject.webContents.session`?

**Comment by zanza54** [comment]
@javan You're correct, my bad. Fixed it in the original post. Issue still persists though.

**Comment by deepak1556** [comment]
@zanza54 `window.WebContents.session.cookies` will return an instance of [cookie](https://github.com/electron/electron/blob/master/docs/api/cookies.md#class-cookies) class. Did you find anywhere in the documentation that the statement returns all the cookies of a webContent ? Thanks!

**Comment by zanza54** [comment]
I managed to get all the cookies through:
```
windowObject.webContents.session.cookies.get({}, (error, cookies) => {
  console.log(cookies);
});
``` 
Which results in all cookies from all BrowserWindow objects like ``sessionObject.defaultSession.cookies`` does. I found this quite counter intuitive since I assume that it only returns the session object containing the cookies for that specific BrowserWindow. 
Line number 1344 on this page states it returns the session used by the webContents which put me on the wrong track assuming it was an unique instance of ``session`` tied to that BrowserWindow: https://github.com/electron/electron/blame/master/docs/api/web-contents.md

**Comment by codebytere** [comment]
As this seems to have been resolved, going to close out.
