### ISSUE TITLE
webview setting does not load images is invalid

### ISSUE THREAD

**Issue by milu2003** [electron/electron#10370]
code:
```
<webview webpreferences="allowRunningInsecureContent, javascript=no, images=no" partition="persist:user" id="my_webview" src="https://www.baidu.com" style="width:100%; height:100%"></webview>
```
and show：

![image](https://user-images.githubusercontent.com/15957433/29775930-947507f4-8c39-11e7-8eb5-ba86b1a9a576.png)

I don't want to load the picture. How should I set it?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by milu2003** [comment]
@sofianguy OK, the problem was settled later, I forgot to close it
