### ISSUE TITLE
The tray icon disappears after a period of time

### ISSUE THREAD

**Issue by Linbubin** [electron/electron#10382]
* Electron version: 1.6.11
* Operating system: debian9 and win7

I'm not sure whether I understand it or the code error.

this is my code for tray

```js
  let appIcon = null;

  appIcon = new Tray(path.resolve(`${__dirname}/`,'main_tray_white_s.png'));
  const contextMenu = Menu.buildFromTemplate([{
    label: 'update',
    click:  function(){console.log(‘update’);},
  }])
  appIcon.setToolTip('version： ' + app.getVersion());
  appIcon.setContextMenu(contextMenu);
```

I reuse a set of tray code before , it work is very good, 

but today I want to write a simple example, 

the runtime tray icon will appear, 
but after a period of time (about 2 minutes), 
the tray icon will disappear, 

what is the reason?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by Noitidart** [comment]
I am having this same problem. Except I'm on Windows 10, and the tray icon disappears after about 3 seconds after startup.

**Comment by enthooz** [comment]
For anyone else experiencing this issue, check out this FAQ entry: https://electronjs.org/docs/faq#my-apps-windowtray-disappeared-after-a-few-minutes
