### ISSUE TITLE
On Linux, returned position of fixed BrowserWindow gets unexpectedly modified

### ISSUE THREAD

**Issue by Mikaeru69** [electron/electron#10388]
* Electron version: 1.7.5
* Operating system: Linux Mint 18.2 Sonya / Ubuntu 16.04.3 LTS

### Expected behavior

On Linux, calling `mainWindow.getPosition ()` should always return the same x and y coordinates when the window is fixed (not moved by the user).

### Actual behavior

After creating a main window by `new BrowserWindow ()`, the x and y coordinates returned by `mainWindow.getPosition ()` get unexpectedly shifted by some constant value, depending on which place in the code the function is called from, notably at the end from the window `'close'` event handler.

This defeats the possibility of reliably keeping track of the current window state (position and size) between two consecutive runs of the application.

The vertical shift appears to correspond to the height of the window's title (25 pixels on Linux Mint; 28 pixels on Ubuntu).

The problem doesn't show up on Darwin.

### How to reproduce

  $ git clone https://github.com/Mikaeru69/BrowserWindow-Position-Bug-Linux
  $ cd BrowserWindow-Position-Bug-Linux
  $ npm install
  $ npm start || electron .

- Start the application from a Terminal using the above-mentioned instructions.
- Don't move the application's window, then quit the application.
- Check the various `console.log ()` outputs:

Linux Mint:

> init: [ 200, 100 ]
> new: [ 200, 100 ]
> show: [ 201, 125 ]
> close: [ 201, 125 ]

Ubuntu:

> init: [ 200, 100 ]
> new: [ 200, 100 ]
> show: [ 200, 100 ]
> close: [ 200, 128 ]

**main.js**:
```
const { app, BrowserWindow } = require ('electron');
let mainWindow = null;
function onAppReady ()
{
    let position = [ 200, 100 ];
    console.log ('init:', position);
    mainWindow = new BrowserWindow ({ x: position[0], y: position[1], width: 800, height: 600, show: false });
    console.log ('new:', mainWindow.getPosition ());
    mainWindow.loadURL (`file://${__dirname}/index.html`);
    mainWindow.on ('ready-to-show', () => { mainWindow.show (); console.log ('show:', mainWindow.getPosition ()); });
    mainWindow.on ('close', () => { console.log ('close:', mainWindow.getPosition ()); });
    mainWindow.on ('closed', () => { app.quit (); });
}
app.on ('ready', onAppReady);
```

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by kayahr** [comment]
Please reopen. Still reproducible with current Electron 3.0.2. On my Debian 9 it outputs this:

```
init: [ 200, 100 ]
new: [ 200, 100 ]
show: [ 200, 100 ]
close: [ 200, 137 ]
```

I made a screenshot and checked the size of the window title. It is exactly 37 pixels. When opening the window with option `frame: false`then the problem does not happen. So looks like the Electron window position has some problem with the window title bar

**Comment by yustnip** [comment]
Have this problem on the last VS Code version. Ubuntu 18.04.1 with a GNOME Shell session. After the app (not maximized) is closed a new window of the app is moved down (moving distance - window title bar height).

**Comment by ganthern** [comment]
This is still a problem in electron 4.0.4 on Ubuntu.

**Comment by yustnip** [comment]
@codebytere Maybe reopen?

**Comment by appurist** [comment]
I've been struggling with this issue for the last two days before finally finding this report. Is there anyone else who can reopen this besides @codebytere 

I'm actually seeing a completely unexpected `move` event come in just after startup, which I'm tracking and then all the window Bounds functions show the window unexpectedly moved lower.  That's probably a good clue since as I understand it the API-programmed methods don't trigger the event notifications. When that comes in, the Bounds functions return the larger value for `y`, even though I'm not moving the window through code or manually.  It doesn't seem to matter if I open the window with `useContentSize: true` in the options and use getContentBounds, or `useContentSize: false` and use getNormalBounds, the movement is present either way.

This may be a clue: if I use `useContentSize: false`, maximize my window, and use getBounds, it returns an (x,y) of (0, 57) which does not seem correct. Shouldn't it be (0,0) ?

**Comment by appurist** [comment]
Here is some specifics, the console output first:
```
Creating window at (200,200) of (1000x700)
Created window at (200,200) of (1000x700)
event (move): (200,237) of (1000x700)
event (leave-full-screen): (200,237) of (1000x700) ignored non-change
event (leave-full-screen): (200,237) of (1000x700) ignored non-change
event (leave-full-screen): (200,237) of (1000x700) ignored non-change
event (leave-full-screen): (200,237) of (1000x700) ignored non-change
event (leave-full-screen): (200,237) of (1000x700) ignored non-change
```
Some actual code below but the point is that the position (bounds in the options parameter) is dumped before `new BrowserWindow(windowOptions)` is called, then confirmed again afterwards with getNormalBounds on the window returning the same numbers.  Then an unexpected `move` event comes in and getNormalBounds returns the moved position.  After the window was created, it was not moved manually or by my code, something else is moving it.

Note that at no time is the window maximized, so the `leave-full-screen` events must be getting triggered by others such as when the window is _shown_ or gains focus.  The first 4 come out at at each startup, thereafter another is generated for each focus or blur on the window. (The 5th `leave-full-screen` above is when I clicked on the console to capture the output and the Electron window lost focus.)
```
app.on("ready", () => {
  mainWindow = createMainWindow();
... (inside createMainWindow()):
  console.log(`Creating window at (${windowOptions.x},${windowOptions.y}) of (${windowOptions.width}x${windowOptions.height})`)
  const window = new BrowserWindow(windowOptions);

(returns window saved as mainWindow)

  let temp = mainWindow.getNormalBounds();
  console.log(`Created window at (${temp.x},${temp.y}) of (${temp.width}x${temp.height})`)

 (shows no change in position)

  mainWindow.on('resize', () => { syncWindowState('resize'); });
  mainWindow.on('move', () => { syncWindowState('move'); });
  mainWindow.on('maximize', () => { syncWindowState('maximize'); });
  mainWindow.on('unmaximize', () => { syncWindowState('unmaximize'); });
  mainWindow.on('minimize', () => { syncWindowState('minimize'); });
  mainWindow.on('restore', () => { syncWindowState('restore'); });
  mainWindow.on('enter-full-screen', () => { syncWindowState('enter-full-screen'); });
  mainWindow.on('leave-full-screen', () => { syncWindowState('leave-full-screen'); });

function syncWindowState(ev)
{
  let bounds = mainWindow.getNormalBounds();
  let newState = {
    bounds: { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height },
    maximized: mainWindow.isMaximized(),
    fullscreen: mainWindow.isFullScreen()
  };

  if ((prevState.bounds.x == newState.bounds.x) && (prevState.bounds.y == newState.bounds.y) &&
      (prevState.bounds.width == newState.bounds.width) && (prevState.bounds.height == newState.bounds.height) &&
      (prevState.maximized == newState.maximized) && (prevState.fullscreen == newState.fullscreen))
  {
    console.log(`event (${ev}): (${bounds.x},${bounds.y}) of (${bounds.width}x${bounds.height}) ignored non-change`)
    return;
  }

  // window state has changed, send renderer process a notification so that it can save this in preferences
  console.log(`event (${ev}): (${bounds.x},${bounds.y}) of (${bounds.width}x${bounds.height})`)
  prevState = newState; 
}
```
Not the most beautiful code but it's about 20 debug variations in and some brute force attempts to validate my assumptions and confirm it wasn't a problem in my code.

**Comment by appurist** [comment]
Since @codebytere doesn't seem to be active anymore, perhaps @MarshallOfSound can reopen this one? Still a problem in Electron 4.1.3.

**Comment by appurist** [comment]
Oh mah gawd. I just put in a "workaround" to catch the first move and call setPosition to undo it (from a `setImmediate` callback).  Something is actually _fighting_ with me. I immediately get a second unexpected undo (move) of my undo:
```
Creating window at (132,122) of (1458x744)
Created window at (132,122) of (1458x744)
event (init): (132,122) of (1458x744)
event (move): (132,159) of (1458x744)
Undo move back to (132,122)
event (move): (132,122) of (1458x744)
event (move): (132,159) of (1458x744)
```
In this case the requested postion was `y==122` and it moved it to `y==159` so I caught that and called `setPosition(x,122)` again to undo that first move.  As a result, I received a second unsolicited move to `y==159` yet again.

That means even a _brute force_ workaround is not available. Nasty.

**Comment by codebytere** [comment]
I'm still active, we just have 1200 issues so this slipped by me :)

**Comment by appurist** [comment]
Thanks @codebytere ! I completely understand (I've been there myself recently) and I just wanted to make sure it wasn't getting overlooked as a closed issue.

Also this may be more serious that the report suggests: my attempts at a workaround by moving the window failed completely, which suggests that there's a problem with setPosition itself, since I wasn't able to move the window to a new desired location after startup.

Hmm. That gives me a brute force workaround idea.  Perhaps if I take the _difference_ between the target position and the result of that first move, and _subtract_ it from the target position... thus setting the window too _high_, the unwanted move will move it into the desired spot. I'll try that tomorrow. #kludge

**Comment by appurist** [comment]
For the record, that kludgey workaround was successful.  This was a showstopper probem for me, but by intentionally introducing the same bug inverted, it seems to negate the effects of the bug and at least allow me to release my code while this bug remains.  

If I specifically give it the wrong `y` coordinate, with _the difference from the desired position, observed in the first move_, it ends up at the correct coordinate:
```
// create main BrowserWindow when electron is ready
app.on("ready", () => {
  // create main window but wait for 'newPrefs' to show it (according to user prefs)
  mainWindow = createMainWindow();
  let temp = mainWindow.getNormalBounds();
  console.log(`Created window at (${temp.x},${temp.y}) of (${temp.width}x${temp.height})`)

  // Ugly workaround for Electron bug (closed but still a problem): https://github.com/electron/electron/issues/10388
  // Problem: unexpected window move after startup (on Linux only?)
  let firstMove = true;
  mainWindow.on('move', () => {
    let x = prevState.bounds.x;
    let y = prevState.bounds.y;
    syncWindowState('move');
    if (firstMove) {
      firstMove = false;
      setImmediate(() => {
        console.log(`Undo move back to (${x},${y})`);
        let wrongBounds = mainWindow.getNormalBounds();
        x -= (wrongBounds.x - x);
        y -= (wrongBounds.y - y);
        console.log(`Undo move using (${x},${y})`);
        mainWindow.setPosition(x, y);
      });
    }
  });
```
This produces the desired `y` (100 in this case):
```
Created window at (100,100) of (1450x850)
event (init): (100,100) of (1450x850)
event (move): (100,137) of (1450x850)
Undo move back to (100,100)
Undo move using (100,63)
event (move): (100,63) of (1450x850)
event (move): (100,100) of (1450x850)
```
Note that this means setPosition is failing here. I specifically need to tell it to use y=63 in order for it to end up at y=100.

**Comment by appurist** [comment]
It seems to be related to the position setting code in that is trying to force the window to be visible at startup.  If I move the window such that the bottom of it is below the Gnome task bar, the unexpected move is in the other direction.
```
Created window at (417,217) of (1450x850)
event (init): (417,217) of (1450x850)
event (move): (417,196) of (1450x850)
Undo move back to (417,217)
Undo move using (417,238)
event (move): (417,238) of (1450x850)
event (move): (417,196) of (1450x850)
```
In this case, the desired `y` is at 217 but the unexpected move adjusts that _up_ to 196 (and the bottom of the window ends up _exactly aligned_ with the _correct_ limits of the bottom of the visible desktop).  

My "correction kludge" sees the move and tries 217 again (using 238 since the first 217 failed) and once again something moves the window to 196.

So a couple of good clues here:
- It's not just one move, it will keep adjusting the window position as long as you call setPosition with part of it off-screen.
- The calculation for the visible screen area at the bottom seems _good_.
- The calculation for the top of the visible screen area seems _wrong_.

Since the taskbar area is at a specific position on the screen, it doesn't need to calculate the size of the taskbar.  However, to fit under the overhead areas at the top of the screen, it may need to calculate the size of that overhead loss of screen space.  Since it works when it's just a position (the bottom) but not when it's trying to fit under something, this could be related to the DPI scaling problem #10862 and it's just not calculating the top of the visible screen area correctly, or using the wrong units.

**Comment by filipesabella** [comment]
Hey there!

This seems to still be an issue on Ubuntu and Electron 8.2.5.

A simple test is to maximize any window and see that its `y` property on `getBounds()`, `getPosition()`, `getContentBounds()`, and `getNormalBounds()`, all return > 0 (30px in my case as it's the title bar's height), with and without `useContentSize`.

**Comment by appurist** [comment]
I'm _still_ seeing this problem in Electron 10.1.2 and it's a real problem for me again. Setting the window position should be a trivial process when you have the intended coordinates and they are valid for the window on the screen.

As a test, I've hard-coded a `mainWindow.setPosition({x: 200, y: 200})` and have an event handler on `'move'` to do a console report and it is forcing the y coordinate to 237, even if I wait for everything to settle down and then call `setPosition` or `setBounds` again.

The fact that my move handler is reporting the unwanted move tells me that something within Electron is calling the equivalent of `setPosition` or `setBounds`, to update the `y` position, as if some asynchronous process outside of setBounds detected an invalid position and is trying to force it to be valid.  Is there some form of off-screen or invalid window position test that could be falsely detect an error that tries to "fix" it?
```
main: prefs is: {"rememberPosition":true,"rememberMaximized":true,"maximized":false,"bounds":{"x":200,"y":200,"width":1700,"height":750},"fullscreen":false}
initPrefs: setBounds ((200,200) of (1700x750)
initPrefs: getBounds (({"x":200,"y":200,"width":1700,"height":750})
initPrefs: getNormalBounds (({"x":200,"y":200,"width":1700,"height":750})
(delay)
app.whenReady: getBounds (({"x":200,"y":237,"width":1700,"height":750})
app.whenReady: getNormalBounds (({"x":200,"y":237,"width":1700,"height":750})
// force position to y=200
setBounds({"x":200,"y":200,"width":1700,"height":750})
// My move handler gets invoked signaling that worked
event (move): getNormalBounds (200,200) of (1700x750)
// My move handler gets invoked signaling unsolicited move that I want to prevent
event (move): getNormalBounds (200,237) of (1700x750)
// My move handler tracks the first unwanted move and tries to reset it,
// via a setImmediate callback after the move handler exits.
Attempt undo move from (200,237) -> (200,200)
setImmediate: setPosition(200,200)
// My move handler gets invoked signaling that worked
event (move): getNormalBounds (200,200) of (1700x750)
// My move handler gets invoked signaling ANOTHER unsolicited move that I want to prevent
event (move): getNormalBounds (200,237) of (1700x750)
```
It has been 3 years now since this was reported. I saw lots of window position/sizing fixes in recent update so I was hopeful this was addressed. However, it seems that the fixes just broke my workaround (undo move) code now and with that undo code removed it's just the wrong position. With it, Electron positioning fights my `setPosition` call and refuses to accept it.

Is it not true that `setPosition({x: 200, y: 200})` should result in a y==200 when you then call `getBounds` or `getPosition`? Why does it result in TWO move events, one matching the `setPosition` request and one at y+37?

**Comment by appurist** [comment]
Some more specific numbers from the problem case:

This issue could be related to DPI scaling values returned from the system, since I just added debugging to monitor if getContentSize() is changing, and I noticed the difference is 25 on my machine, where the problem difference in y-offset is 37.

If the y-offset due to title/frame/menu is 25 and the DPI scaling of the display is 1.5, that might explain where the y-offset difference of 37 is coming from, given Math.floor(25 * 1.5) is 37.

Also I can confirm that I am _not_ seeing this problem under Windows (with the same monitor).

**Comment by appurist** [comment]
I thought I was thought I was done reporting on this but I have just noticed something very significant that I don't think has been mentioned.  In the problem case, **the window isn't actually moving**.

The problem symptom is that getBounds and getNormalBounds return a different y value in a move notification that doesn't actually seem to happen. Or the initial values weren't where the window actually was and then it sends a move to notify of a movement that didn't actually happen. Either the move didn't happen, or it was already there. At any rate, saving the result from getNormalBounds and using it to set the window position on app restart results in it moving to a lower position on each run, due to this inconsistency.

So this may be a problem only with the bounds position that Electron returns at some point. A move notification is being sent, but the window isn't moving. So if you use that position, it's inconsistent with the coordinates needed on the BrowserWindow constructor on the next run.

**Comment by appurist** [comment]
This is still a problem in Electron 11.4.10. (For the record, on this dev machine I'm required to use CentOS 7 with Gnome to match and enterprise production machine.)  One thing I've noticed that does not seem correct at all is that `getNormalBounds` and `getContentBounds` always seem to return the same `y` value, even with a titlebar. I would have thought that getContentBounds would provide an adjusted `y` position, and would only be the same on borderless windows and full-screen mode.  I've tried using `setContentBounds/getContentBounds` vs `setNormalBounds/getNormalBounds` and it seems to make no difference, even on a normal bordered window with a titlebar. The "wrong y by 37" problem I've seen above seems to be the right size for the titlebar offset.

**Comment by user896724** [comment]
I'm seeing this on electron 13.1.7.  `getBounds` and `getContentBounds` return the same coordinates for a window with standard titlebar and border.

**Comment by gushogg-blake** [comment]
Thought - could this be to do with the fact that Chrome by default doesn't show the system titlebar and border?

**Comment by Mikaeru69** [comment]
bump

still a problem in Electron 17.4.11

**Comment by gushogg-blake** [comment]
I'm still seeing this on version 22.1.0, Linux Mint 21.1 Mate.

The issue does seem to be the window border -- if you change it in Preferences -> Appearance -> Theme -> Customise -> Window Border, it changes the discrepancy. Using a border without any surround (Mint-Y-Legacy) "fixes" the issue entirely, at least on the x axis.

The `window.moveBy` function in the renderer is also affected: the window border seems to be added to the adjustments you give, so with a window border of 1px `window.moveBy(-1, 0)` has no effect at all, and with a larger border it actually moves the window to the right!

**Comment by Mikaeru69** [comment]
bump

**Comment by Mikaeru69** [comment]
Giving up...

**Comment by newable** [comment]
bump

**Comment by PawelSzpyt** [comment]
still there, without a fix or workaround

**Comment by Marvbudd** [comment]
I'm using Ubuntu 22.04.4 LTS, Electron 29 and this problem is plaguing me. Is anyone willing to get this fixed?
