### ISSUE TITLE
how can i build the code to loongson CPU?

### ISSUE THREAD

**Issue by o70078** [electron/electron#10392]
my computer is using loongson CPU,i want to use my computer to run electron,so i pull the code,but i can't build this.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
