### ISSUE TITLE
Is contextIsolation:true supposed to disable node integration?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#10405]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior

I turned on `contextIsolation` for the main window:
`new BrowserWindow({webPreferences: { contextIsolation: true }});`

I loaded a url:
`window.loadURL(url.format({
    pathname: path.join(__dirname, "./index.html"),
    protocol: "file:"
});`

My index.html page has a <script> tag from which I do a `require`. I expect it to require my script when the url is loaded.

### Actual behavior

I see an error in the console: "Uncaught ReferenceError: require is not defined".

Why can I not use `require`? I don't turn off node integration. If I set `contextIsolation` to false, `require` works. It was my understanding that contextIsolation simple forces the preload script to run in an isolated JS environment. Why does it appear that `nodeIntegration` is also turned off?

*Update:* One important note that may make all the difference, is that this window doesn't have a preload script (or a webview tag for the matter). I later load a url that points to a page with a preload script, but initially, it doesn't have one.

**Comment by pushkin-** [comment]
Any updates?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
