### ISSUE TITLE
Closing window while detach dev tool open is not working

### ISSUE THREAD

**Issue by zoonooz** [electron/electron#10437]
* Electron version: 1.8.0
* Operating system: OSX 10.12.4

### Expected behavior

Close window while devtools open would close window itself and devtools.

### Actual behavior

Close window while devtools open close only devtools and window becomes white. 

### How to reproduce

1. open devtools and make it detach from the window.
2. close window.

This happens since version 1.6.8

<img width="845" alt="screen shot 2017-09-04 at 11 35 20" src="https://user-images.githubusercontent.com/1230665/30009676-3767dee8-9165-11e7-9e2b-ebf7d140c1b8.png">
<img width="903" alt="screen shot 2017-09-04 at 11 35 33" src="https://user-images.githubusercontent.com/1230665/30009678-3a80f420-9165-11e7-9caf-b71465f749dc.png">

**Comment by codebytere** [comment]
Hmm ok so i replicated this and it closes the devtools window when you first click close on the main window, and then if you click close again the main window closes. I'll take a look into what might cause the need to click twice.

**Comment by alexeyv** [comment]
I have this problem, too. The way this looks to me is as follows:

Using only Electron APIs all the way through:
1. create a BrowserWindow with detached devTools
2. create another BrowserWindow with detached devTools
3. call .close() on the first window

Expected: both window and its devTools counterpart close
Actual: devTools closes, but window remains opened

4. Recreate the same situation, but instead of calling .close on the BrowserWindow instance, hit the OS close button on it. Same behaviour (deTools close, the window stays open)
5. Click the OS close button on the still open window again. This time, the window does close.

6. Modify the code to call .close() twice in a row. As it should, the second .close() call throws an exception along the lines of "the object is destroyed". As it shouldn't, the supposedly destroyed window is still visible.

OS X 10.13.3
Electron 1.7.9
Node 7.9.0

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
