### ISSUE TITLE
Minor electron.d.ts issues

### ISSUE THREAD

**Issue by bpasero** [electron/electron#10448]
Some issues I noticed while adopting the electron.d.ts from this repository for VS Code. Overall not a lot of things, great work!

```typescript
interface Event extends GlobalEvent {
	preventDefault: () => void;
	sender: WebContents;
	returnValue: any;
	ctrlKey?: boolean; // change
	metaKey?: boolean;
	shiftKey?: boolean;
	altKey?: boolean; // add
}
```

The `ctrlKey` is not lowercase, but camelcase. I also added `altKey`. 

`CrashReporterStartOptions`: I added `crashesDirectory` that can be used if the crash reporter is used in forked processes. I also declare `extra` as `any`. It should not implement an interface that is empty.

/cc @zeke (maybe let me know where this changes need to be done so I can do a PR instead)

**Comment by bpasero** [comment]
I also noticed that the first argument to the web-request event handlers are optional in the docs but not marked as optional in the d.ts file, e.g.: https://github.com/electron/electron/blob/3ec7900e6e72aeb2c273f47a97498a093580da94/docs/api/web-request.md#webrequestonbeforesendheadersfilter-listener

**Comment by MarshallOfSound** [comment]
@bpasero The `Event` interface is actually one of the few things statically declared.  See https://github.com/electron/electron-typescript-definitions/blob/master/base/base_inner.ts#L21

To fix the crash reporter options interface you just have to fix the documentation here: https://github.com/electron/electron/blob/3ec7900e6e72aeb2c273f47a97498a093580da94/docs/api/crash-reporter.md

The `crashesDirectory` property should be added to the formal documentation part instead of just being mentioned inside a paragraph.  The `extras` type just needs to change to `any` instead of `Object`

> I also noticed that the first argument to the web-request event handlers are optional in the docs but not marked as optional in the d.ts file

That's a weird bug (that shouldn't happen), can you raise an issue over on `electron-typescript-definitions`

**Comment by codebytere** [comment]
Looks like these errors have been corrected, so i'm going to go ahead and close this! let me know if i need to reopen for any reason :)
