### ISSUE TITLE
Users are redirected to a white screen after using Electron application

### ISSUE THREAD

**Issue by dsteegen** [electron/electron#10459]
Hi,

We created an Electron application that opens an external Angular 1 application. There is communication from both the main process to the render process and the other way around (e.g. opening new windows, sending/listening to event, etc.)
Our users noticed that after using the application for several hours, the browser redirects to 'about:blank' while navigating through the application. 
We inspected the blank page with the developer tools and noticed that Electron specific js files were imported (so no issue over there). It was also possible to call api's from the main process via developer tools (so also no issue over there). However, we did notice that the main process could not communicate with the render process anymore (we tried this by setting a listener on the render process and sending an event from the main process).

Some information that may be useful:
- the application is created with version 1.6.10 of Electron
- it's the Windows 32 bit version of Electron
- it's distributed via the msi on Windows 7 machines
- Updates of the application are pushed on a central update server on the client's network
- Crash reporter has been enabled in the application but no dumps are created meaning that no crash occurred
- Checking the Windows task manager also reveals that the both the main process and renderer process are still active

Unfortunately we can not provide you with an instance of our application to try to reproduce as the angular application runs on a corporate network.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
