### ISSUE TITLE
Suggestion: noop commands when OS support is missing

### ISSUE THREAD

**Issue by reviewher** [electron/electron#10451]
* Electron version: 1.7.5
* Operating system: windows 10 / macOS 10.12.6

### Expected behavior

The following should not throw an error:

```js
require('electron').app.setAboutPanelOptions()
```

### Actual behavior

Throws an error in windows because `require('electron').app.setAboutPanelOptions` is undefined

Suggestion: instead of leaving the OS-specific functions undefined when not supported, add stubs in other OS implementations.  For example, `setAboutPanelOptions` could be an empty function in Windows and Linux.

**Comment by MarshallOfSound** [comment]
@reviewher In theory, this makes the developer experience a bit nicer.  But what do you do with API's that return values, or are expected to perform certain actions.  In general, I think forcing developers to do OS checks (a) makes them more aware that certain things only work on certain platforms and (b) stops user error from expecting a function to call to work when it is just a noop

**Comment by reviewher** [comment]
Let's take the badge count as an example.  This involves [`setBadgeCount`](https://electron.atom.io/docs/all/#appsetbadgecountcount-linux-macos) and [`getBadgeCount`](https://electron.atom.io/docs/all/#appgetbadgecount-linux-macos).  This is an interesting case because Linux support depends on Unity.

`setBadgeCount` returns a boolean indicating whether the call succeeded.  On platforms where it is not available, like Windows, returning `false` neatly matches the API.

`getBadgeCount` returns the current value.  The docs state:

> Setting the count to `0` will hide the badge.

So having `getBadgeCount` return `0` on Windows and non-unity-Linux is consistent with the rest of the API.

Note: the developer check in this case is 
```js
(process.platform == 'darwin' || process.platform == 'linux' && app.isUnityRunning())
```

.

For the `setAboutPanelOptions` example, the [documentation does not specify a return value](https://electron.atom.io/docs/all/#appsetaboutpaneloptionsoptions-macos).  Explicitly making it noop on windows and linux would be consistent, although I would recommend changing it to returning `true` on success and `false` otherwise

**Comment by jsoref** [comment]
Fwiw, I find that making devs do OS checks results in brittle code.
On average, a dev will not be testing every corner of their app on all platforms.
And it's highly unlikely that they have instrumentation to get reports for when edges with missing implementations get found by users.

Sure, if they're lucky a user may try to report an issue to them. But if the user is used to being brushed off by devs, they might not bother.

And your average user can't do a particularly good job of articulating a problem -- unlike @reviewher who did a very good job here.

(Personally, I'd rather the stub implementation be a moderately good implementation instead of a NOP, but...)

Fwiw, you have some instances where you include a platform notice:
https://electron.atom.io/docs/api/accelerator/#platform-notice

And sometimes, you don't, as in: https://electron.atom.io/docs/api/app/#event-ready

Also, note that there's a precedent for having apis not crash when something's missing, as in:
https://electron.atom.io/docs/api/app/#appsetloginitemsettingssettings-macos-windows
> Note: This API has no effect on MAS builds.

(FWIW, I'm half considering whether it's worth it to contribute to this project, and I apologize to @reviewher for starting in this issue.)

**Comment by reviewher** [comment]
@jsoref the "platform notice" for the app page appears [later in the page, in the Methods block](https://electron.atom.io/docs/api/app/#methods):

> Note: Some methods are only available on specific operating systems and are labeled as such.

That note should also appear in the Events block.

**Comment by codebytere** [comment]
Closing in agreement with @MarshallOfSound above.
