### ISSUE TITLE
SSLKEYLOGFILE for log SSL KEYS and decrypt HTTPS traffic ? (like chromium or firefox)

### ISSUE THREAD

**Issue by yattamax** [electron/electron#10465]
Hi everyone,
I'm starting to develop an "app" for forensics use (if someone know DEFT Linux maybe can know the scope).

For my project, I need to log the SSL KEY for decrypt SSL/TLS traffic with wireshark after the acquisition activities for forensics use, being able to use it as a prove in legal context.

I have introduced this context to not mislead my words, my request is for a fair use and a good cause not for fraud :)

In chrome/chromium and Firefox is possible set a environment variable to set a file where saving the SSL Keys:

`export SSLKEYLOGFILE=/media/evidences/mywork/keys`

and when browser start to "surf", it save in this path all SSL Keys for any HTTPS request.

Can this be replicated in electron?
- if yes, how can use it ?
- if no, where can put my hands in the source code for try to implement it?

**Note:**
I know that it is possible to use a Man-In-The-Middle technique with a proxy that strips and replaces SSL certificate, but because I need to work in forensics mode, I can not change any data (not even a bit) , especially the certificate :)

Thanks and best regards :)

Massimiliano Dal Cero

**Comment by yattamax** [comment]
Hi :)
Someone can help me ?

can be enough a suggestion about where can find ssl/tls handshake in source code and I can try to edit by my self the source code :)

Thanks :)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by tacotime** [comment]
I am also looking for the answer to this question :/

**Comment by gautaz** [comment]
@yattamax Did you ask in one of the forums for answers on this particular subject? Did you receive any help?

**Comment by yattamax** [comment]
Hi :)
unfortunately I did not receive an answer, so I switched to https://nwjs.io/ which has this feature

Max :)

**Comment by gautaz** [comment]
@yattamax Thanks for your quick answer even if it is a bit disappointing ;-).

@sofianguy Hello, this issue was originally treated as if it were a question but I see it more as a missing functionality, sort of a must have for developers needing to investigate issues while using encrypted communications.

Would you mind to elaborate your decision or at least provide a link to an article explaining how the Electron's team envision the diagnosis of such issues?

**Comment by septatrix** [comment]
Would it be possible to reopen this issue? It is written like a question but the problem is that electron does not seem to support `SSLKEYLOGFILE`...

**Comment by jasonwilliams** [comment]
NodeJS now supports [--tls-keylog](https://nodejs.org/api/cli.html#--tls-keylogfile) and has done since version 12. So all Electron needs to do is allow the flag to be passed down into node.

(I don't know if you can already pass flags through to NodeJS)

Maybe this can be re-opened?
