### ISSUE TITLE
How to know if electron finished printing ?

### ISSUE THREAD

**Issue by larrypaul93** [electron/electron#10475]
I am using angular for one of my app and want to print same page 3 to 4 time with different data
like 
component.item = item[i];
webContent.print();

component.item = item[i+1];
webContent.print();

currently i am using setTimeout. but its not work always. is there any other way to do that ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
