### ISSUE TITLE
How do you mask the multi touch zoom gestures

### ISSUE THREAD

**Issue by govenlive** [electron/electron#10480]
How do you mask the multi touch zoom gestures? This Google is disgusting and the whole page is zooming.

Mobile terminal is a good solution, but now the project is multi touch on the PC side

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
