### ISSUE TITLE
NACL support requested

### ISSUE THREAD

**Issue by latel** [electron/electron#10504]
I'm trying to use nacl in electron, which needs `--allow-nacl-socket-api` switch, as I searched on [https://peter.sh/experiments/chromium-command-line-switches/#condition-4](https://peter.sh/experiments/chromium-command-line-switches/#condition-4), It requires ___The constant BUILDFLAG(ENABLE_PLUGINS) must be defined___， is there any solutions here?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
