### ISSUE TITLE
did-finish-load is not working properly for pdf files 

### ISSUE THREAD

**Issue by virendra038** [electron/electron#10512]
const PDFWindow = require('electron-pdf-window');

                        const win = new BrowserWindow({ width: 800, height: 600});

                        PDFWindow.addSupport(win);
                        win.loadURL('file://'+__dirname+'/screens/home/label.pdf');

                        var contents = win.webContents;
                        contents.on('did-finish-load', function(){
                              contents.print({ deviceName : 'HP LaserJet Pro MFP M225-M226 PCL 6 (Copy 1)'});
                        });
                    })

NOTE: contents.print commands fires before the window load the file successfully.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
