### ISSUE TITLE
Using Flash dll File after Packaging

### ISSUE THREAD

**Issue by puremana** [electron/electron#10530]
After referencing in my code
```
ppapi_flash_path = path.join(__dirname, 'pepflashplayer64.dll');
app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
app.commandLine.appendSwitch('ppapi-flash-version', '25.0.0.127');
```
It loads flash when I run my electron app. But after I package this app it fails to load when I open the .exe, no matter where I place the flash dll file.

Edit: Have run a check. Node can still find the file after it has been packaged, but for some reason the plugin is not loaded. Any ideas?

**Comment by KochiyaOcean** [comment]
You should extract flash from ASAR file.

**Comment by sofianguy** [comment]
@puremana Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
