### ISSUE TITLE
napi modules in beta(v1.8.0) version

### ISSUE THREAD

**Issue by charmer1989** [electron/electron#10533]
I want to use napi modules in beta(v1.8.0) version, how to use --napi-modules command-arguments when "electron ./"?

**Comment by charmer1989** [comment]
I have try to use "NODE_OPTIONS=--napi-modules" but failed

**Comment by facekapow** [comment]
Any update on this? I'm developing a native module with the NAPI and I'd like to use it with Electron, but Electron doesn't seem to want to accept `--napi-modules`.

**Comment by flexsurfer** [comment]
Any update on this?
```
Uncaught Error: The module '/nodejs/binding.node'
was compiled against the ABI-stable Node.js API (N-API).
This feature is experimental and must be enabled on the 
command-line by adding --napi-modules.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nathansobo** [comment]
It looks like N-API is enabled by default in the version of Node currently bundled with Electron master. I'm currently interacting with a simple N-API based module in a build of 781311aa3c59eeb5d6965cc8125821d0a194c645. It should be out as an official release in the next beta release for Electron 1.8.

I'm not sure if it will be Electron 1.8.2-beta4 or 1.8.3-beta1. @MarshallOfSound could you help me out with the versioning scheme to make this version number precise for future reference?
