### ISSUE TITLE
Web Bluetooth not working on Windows

### ISSUE THREAD

**Issue by dyachkovD** [electron/electron#10562]
* Electron version: 1.7.6
* Operating system: Windows 10

### Expected behavior
```javascript
webContents.on('select-bluetooth-device', (event, deviceList, callback) => { ... }) // Should work at all OS, but not emitted on Windows
```
### Actual behavior
This works on Linux (Ubuntu 16.04), but with a large delay
### How to reproduce
I try to connect my bluetooth device like this https://electron.atom.io/docs/api/web-contents/#event-select-bluetooth-device
In render process or console:
```javascript
navigator.bluetooth.requestDevice({acceptAllDevices: true}).then(device => console.log(device)).catch(error => console.warn(error))
```

**Comment by sai-kyaw** [comment]
+1 for the long delay.

- Electron version: 1.7.6

- Operating system: macOS Sierra 10.12.6

I am also playing around with the web-bluetooth and it is working fine on Mac but found out that the request took 1 minutes to get the device list even if I use the device name. It normally takes just a few seconds when the request is done from a dev console, Chromium browser.

`navigator.bluetooth.requestDevice({ 
       filters: [{ name: ['my_bluetooth'] }] 
  }).then(
     device => device.gatt.connect()
  )`

Using following GATT server as BLE service provider on Android [https://github.com/androidthings/sample-bluetooth-le-gattserver](url)

Could this be a performance issue? Thanks.

**Comment by sai-kyaw** [comment]
@Dyachkov did you manage to get it working on Windows?

IMHO, with regards to the long delay(60 seconds), it is because of the electron's bluetooth_chooser implementation. A few months ago the bluetooth device scanning duration time in chromium has been increased from 10 seconds to 60 seconds. [https://chromium.googlesource.com/chromium/src.git/+/acdbb3c267d8d4ea19d0faf4ef34b5179f3c58fa](url) 

And in bluetooth_chooser.cc [https://github.com/electron/electron/blob/master/atom/browser/lib/bluetooth_chooser.cc](url),

```c 
void BluetoothChooser::ShowDiscoveryState(DiscoveryState state)
```

`select-bluetooth-device` event will be emitted once we reach to `DiscoveryState::IDLE`, meaning that Electron will scan and wait until the timeout(60 sec) regardless of if there are discovered devices. I'm not sure if it is there for a reason.

I think we should be able to emit the event as soon as a new device has discovered  `void BluetoothChooser::AddOrUpdateDevice`, so we can release the resources if we found our device within a few seconds.  I do not have much experience in C++ but following/similar approach might fix the long delay issue. (Just an idea)

```c
void BluetoothChooser::ShowDiscoveryState(DiscoveryState state) {
  switch (state) {
    case DiscoveryState::FAILED_TO_START:
      event_handler_.Run(Event::CANCELLED, "");
      break;
    case DiscoveryState::IDLE:
      if (device_list_.empty()) {
        auto event = ++num_retries_ > kMaxScanRetries ? Event::CANCELLED
                                                      : Event::RESCAN;
        event_handler_.Run(event, "");
      }
      break;
    case DiscoveryState::DISCOVERING:
      break;
  }
}

void BluetoothChooser::AddOrUpdateDevice(const std::string& device_id,
                                         bool should_update_name,
                                         const base::string16& device_name,
                                         bool is_gatt_connected,
                                         bool is_paired,
                                         int signal_strength_level) {
  if (should_update_name) {
    auto iterator = device_map_.find(device_id);
    if (iterator == device_map_.end()) {
      DeviceInfo info = {device_id, device_name};
      device_map_.insert(std::pair<std::string, DeviceInfo>(device_id, info));
      std::transform(
        device_map_.begin(),
        device_map_.end(),
        back_inserter(device_list_),
        [](std::pair<const std::string, DeviceInfo> const & kv){
          return kv.second;
        });
      bool prevent_default =
        api_web_contents_->Emit("select-bluetooth-device",
                                device_list_,
                                base::Bind(&OnDeviceChosen,
                                           event_handler_));
      if (!prevent_default) {
        event_handler_.Run(Event::SELECTED, device_id);
      }
    }
  }
}

void BluetoothChooser::RemoveDevice(const std::string& device_id) {
  device_map_.erase(device_id);
  for (auto it = device_list_.begin(); it != device_list_.end(); ++it) {
    if (it->device_id == device_id) {
      device_list_.erase(it);
      return;
    }
  }
}
```

Can I get some expert opinion on this please?

Many thanks,

**Comment by Dyachkov** [comment]
@sai-kyaw on Windows still not working. Waiting for about 3 minutes and nothing happens.

**Comment by sai-kyaw** [comment]
@Dyachkov wish I could help but my windows VM doesn't seem to support BLE with host BT device. Did you check your device capability on windows? i.e. v.4 BLE support.

**Comment by julesjcraske** [comment]
@sai-kyaw Please can you remove your old pay4later.com email address from your account. Sorry there is no way to private message. Thanks.

**Comment by sai-kyaw** [comment]
@julesjcraske done. is it causing any issue?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
