### ISSUE TITLE
Downloads API

### ISSUE THREAD

**Issue by samsamm777** [electron/electron#10582]
Using the DownloadItem apis there doesn't seem to be a way to include any custom headers to the underlying GET HTTP request. I need to be able to do this for authentication.

https://electron.atom.io/docs/api/download-item/

**Comment by robinwassen** [comment]
DownloadItem is handled by the Download Manager, the only API that seems to work with the download manager is contents.downloadURL(url): https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsdownloadurlurl

Looking at the C++ binding only a URL is allowed to be passed into the function: 
https://github.com/electron/electron/blob/cc9771a3d0007e3db339399ea65e4ecbef207e69/atom/browser/api/atom_api_web_contents.cc#L1061

For allowing custom headers etc. to work an extension to the downloadURL function needs to be implemented.

**Comment by sofianguy** [comment]
@samsamm777 Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
