### ISSUE TITLE
Accelerator with l10n

### ISSUE THREAD

**Issue by SteeveDroz** [electron/electron#10606]
## Description

When using a menu accelerator, mutation take place. They are very usefull, unless the user's keyboard is not QWERTY (yes, we exist).

## My problem

I want a shortcut to be `Ctrl+?`, Electron turns it into `Ctrl+Shift+/`. My users' keyboard are QWERTZ, `?` is above `'` and `/` is above `7`. Nothing works like intended.

## Idea

Remove mutations altogether. Let the developers do what they want and recommand them to be precise in their accelerators.

## Related

#6731, #9743

**Comment by codebytere** [comment]
We currently follow Chromium's accelerator approach, in order to minimize maintenance burden and friction. As such, this isn't something the maintainer team will be working on, but I believe we would be willing to accept something that added support for alternative approaches without breakage to existing code. I'm going to label this a wontfix in that event.
