### ISSUE TITLE
"will-navigate" event not fired on form submit

### ISSUE THREAD

**Issue by ncortines** [electron/electron#10641]
* Electron version: 1.7.6
* Operating system: MAC 10.12.6

### Expected behavior

I would expect the `will-navigate` event to be emitted

### Actual behavior

In this particular scenario only the `did-navigate` is emitted

### How to reproduce

main.js:

```javascript
const {app, BrowserWindow} = require('electron')
const path = require('path')

app.on('ready', function() {
  const win = new BrowserWindow()

  const {webContents} = win
  webContents.on('will-navigate', () => {
    console.log('will-navigate')
  })
  webContents.on('did-navigate', () => {
    console.log('did-navigate')
  })

  win.loadURL('file://' + path.join(__dirname, 'index.html'))
})
```

index.html:

```html
<html>
  <head></head>
  <body onload="document.forms[0].submit()">
    <form action="https://github.com" method="post"></form>
  </body>
</html>
```

**Comment by ncortines** [comment]
Is it due to this?
https://issuetracker.google.com/issues/36918490

**Comment by sofianguy** [comment]
@ncortines Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
