### ISSUE TITLE
Dialog windows stay behind the app screen when AlwaysOnTop is true on Windows

### ISSUE THREAD

**Issue by AdrienFery** [electron/electron#10723]
* Electron version: 1.7.6
* Operating system: Windows 10

### Expected behavior

When `AlwaysOnTop` is enabled on a `BrowserWindow`, the dialog windows (such as `dialog.showOpenDialog(...)`) should be on top of the app screen.  

### Actual behavior

It is the case on MacOS but not Windows 10.
On Windows, dialog windows stay behind the app screen when `AlwaysOnTop` is enabled (making them invisible for the user).

### How to reproduce

```
  $ git clone https://github.com/AdrienFery/electron-dialog-always-on-top
  $ npm install
  $ npm start || electron .
```

**Comment by 0mnsium** [comment]
Electron version: v2.0.8
Operating system: Windows 7 Professional (64bit Operating System)

**Expected behavior**
When AlwaysOnTop is enabled on a BrowserWindow, the dialog windows (such as dialog.showOpenDialog(...)) should be on top of the app screen.

**Actual behavior**
On Windows, dialog windows stay behind the app screen when AlwaysOnTop is enabled (making them invisible for the user).

**How to reproduce**

- Launch electron application.
- Click to launch dialog window.
- Click on application window to focus back to application window.
- Click to launch dialog window once again, likewise you can launch multiple dialog windows.

**Comment by Hum4n01d** [comment]
This is still happening, any updates?

**Comment by Hum4n01d** [comment]
Electron version: `electron-compile` v6.4.3 (latest)
Operating system: macOS 10.14.1 (Mojave)

This might be a different issue, but I have a tray menu based app and I'm opening a dialog in response to to a tray option.

**Expected behavior**
The dialog appears in front of any other windows like all system dialogs do

**Actual behavior**
The dialog appears behind any other windows:

![electron dialog behind window](https://user-images.githubusercontent.com/17228477/48676757-0d55ae80-eb20-11e8-8fc4-8b5385a8dfb0.gif)

My dialog code:

```js
dialog.showOpenDialog({
  properties: ['openFile'],
  filters: [{
    name: 'Images',
    extensions: ['jpeg', 'jpg', 'webp', 'gif', 'png', 'apng', 'svg', 'tiff', 'bmp', 'ico']
  }]
})
```

I will add instructions to reproduce when I get a chance

**Comment by enthusapp** [comment]
On Ubuntu 18.0.4, Windows 7, and electron 3.0.4.
I tried `BrowserWindow.getFocusedWindow()` :
```
dialog.showOpenDialog(BrowserWindow.getFocusedWindow(), {
  properties: ['openFile'],
  filters: [{
    name: 'Images',
    extensions: ['jpeg', 'jpg', 'webp', 'gif', 'png', 'apng', 'svg', 'tiff', 'bmp', 'ico']
  }]
})
```
And works well.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by raphadko** [comment]
This is still happening. Electron Version 8.x.x
If alwaysOnTop is set to true, dialog windows will show underneath BrowserWindow.

**Comment by raphadko** [comment]
Little hack to solve this:

            win.setAlwaysOnTop(false); 
            this.newShortcut.link = dialog.showOpenDialog({ properties: ['openFile'] })[0];
            win.setAlwaysOnTop(true);

**Comment by Dmitra** [comment]
@raphadko, unfortunately this hack won't help in renderer process: `remote.dialog.showOpenDialogSync()`

Was able to solve the problem with ipc messaging and specifying mainWindow in the main process call:
```
      event.returnValue = dialog.showOpenDialogSync(mainWindow)
```
