### ISSUE TITLE
Electron memory limit ??

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10739]
Hi,

I'm using Electron to develop a browser allowing to open many tabs. Each tab contain two webviews that communicate between them using `ipcRenderer.sendToHost` and other EventListeners.

This works until the number of opened tabs exceeds 32 tabs. Beyond 32 tabs, there is no more communication between the two webviews.

Known that 32 is the limit of opened tabs tested on a first machine (windows) and 22 is the limit found on another machine (mac).

I would like to know if Electron has memory limits? and how can I fix this problem and allow to open tabs as well as we want.

I tried `"electron --js-flags='--max_old_space_size=8096' ."` and `app.commandLine.appendSwitch('js-flags', '--max-old-space-size=8096');` but it does not work...

Thanks

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
