### ISSUE TITLE
Bug systemPreferences.isAeroGlassEnabled() with not activated windows

### ISSUE THREAD

**Issue by marceloavf** [electron/electron#10745]
When I use `systemPreferences.isAeroGlassEnabled()` to create transparent screen window and Windows system is not activated, it'll answer true to this statement even if Aero Glass is disabled by Windows protection.

Is there a way to check if Windows is activated or not?

**What happen:**
When I create a transparent `BrowserWindow`, it becomes invisible/translucent, block every click that I do in the content that is behind that, it only become visible if I click to many times in the task bar icon.

![electron transparent bug](https://user-images.githubusercontent.com/5435657/31440081-04f854c0-ae65-11e7-8f8b-a491d8a504f4.gif)

**Electron**: v1.7.8
**Operating System:** Windows 10 Pro

Thanks!

**Comment by sofianguy** [comment]
@marceloavf Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
