### ISSUE TITLE
Fix "onbeforeunload" tests

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#10754]
_After Chromium 61 is merged._

**Problem**:
Starting from version 60 Chromium requires user gesture to be done on a page to show beforeunload dialogs, see https://www.chromestatus.com/feature/5082396709879808
Some of our tests got broken because of that change.

As a workaround that new check has been disabled via a libcc patch:
https://github.com/electron/libchromiumcontent/blob/upgrade-to-chromium-61/patches/047-disable-user-gesture-requirement-for-beforeunload-dialogs.patch

**What should be done**:
1) Remove libcc patch.
2) Fix failing "onbeforeuload"-related tests.

**Hint**
Use `webContents.executeJavaScript('', /* userGesture */ true)`?

**Comment by superddr** [comment]
actually, it blocks me now....
My page has a onbeforeunload hook, then when I try to close the electron window by clicking the close  button, the error about user gesture requirement came up .
So now I simply can not close my electron app.
Pls don't just fix the test, it's working. 
thanks for the great work

**Comment by alexeykuzmin** [comment]
@superddr 

> My page has an onbeforeunload hook, then when I try to close the electron window by clicking the close button, the error about user gesture requirement came up.

What Electron version do you use?

**Comment by HappyGod158** [comment]
> actually, it blocks me now....
> My page has an onbeforeunload hook, then when I try to close the electron window by clicking the close button, the error about user gesture requirement came up .
> So now I simply can not close my electron app.
> Pls don't just fix the test, it's working.
> thanks for the great work

Faced with the same confusion, have  any solutions?

**Comment by HappyGod158** [comment]
> @superddr
> 
> > My page has an onbeforeunload hook, then when I try to close the electron window by clicking the close button, the error about user gesture requirement came up.
> 
> What Electron version do you use?

the electron version i'm using  is 4.0.0-beta.8

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
