### ISSUE TITLE
Disable automatic touch context menu (text based editing for touch)

### ISSUE THREAD

**Issue by localo** [electron/electron#10751]
* Electron version: 1.4.13
* Operating system: Windows 7 64bit with touch screen

### Expected behavior

I do not want/need any context menu.

### Actual behavior

I get a automatic touch context menu (text based editing for touch) on input fields. Even though I haven't implemented any context menu.
Example: https://imgur.com/a/AQy7Z

### How to reproduce

I have a custom application build with electron. I haven't implemented any context menus (and do not need/want them). But when I use this application on a PC with a touch screen and open a page with an input field, I get an automatic touch context menu (text based editing for touch). 

How can I get rid of it. Any ideas, how to disable this?

**Comment by sofianguy** [comment]
@localo Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
