### ISSUE TITLE
errno 3221225477 ??

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10753]
Hi,

I use Electron to navigate on the web. I have always this error : 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! Browser@3.2.0 start: `electron .`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the Browser@3.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2017-10-11T12_41_24_274Z-debug.log
```

This is reproduced when I navigate in web, there is no specific site which reproduce this error. I still click on links and navigate until it crashes. 

Is it a memory problem?

Thank you

**Comment by felixrieseberg** [comment]
> I use Electron to navigate on the web

Please don't do that, Electron is not a browser.

**Comment by MarshallOfSound** [comment]
> npm ERR! Exit status 3221225477

This log doesn't tell us anything about Electron itself, this is the npm error number not an Electron crash / error log.

As @felixrieseberg said, please don't use Electron to navigate the web there are many security / safety concerns that Electron does not deal with out of the box.

**Comment by codebytere** [comment]
As this error originated with a use case that shouldn't be a use case, i'm going to go ahead and close this.

**Comment by Devhercule** [comment]
Hi,

I don't know if this will help you, but I finally managed to solve the problem.

This error appears when i use Electron v1.8.1

I migrated the code with an older version of Electron : Electron v1.7.9, and i have no more errors. it works perfectly now.

Have you an idea why this is produced with the new version of electron ( pre released version 1.8.1)?

Thank you

**Comment by mnemanja** [comment]
I'm getting this on 1.7.9.
I'm trying to perform some async operations in the main thread (cloning data from old database to a new one).

**Comment by pbaldridge** [comment]
Valid use case or not is no reason to close the thread to a common issue. How about explaining some common or potential causes for this problem, i.e. what situations may cause it to crash with this error? Ask for logs? Try and actually help?

**Comment by codebytere** [comment]
@pbaldridge you're more than welcome to open up a new issue if you see this occurring still and have all the necessary information required to fill out the issue template.

**Comment by briosheje** [comment]
Experienced that issue in 2019, the issue seems to be related to a browser window using `webContents.downloadURL`.
My use case scenario was like this:

```
    downloadWindow.webContents.downloadURL(fullUri);
    downloadWindow.webContents.session.once('will-download', () => {
      downloadWindow.close();
    });
```

Which isn't, of course, meant to be used (I guess so, which would also make sense to me, since the best scenario would be actually downloading through node rather than using BrowserWindow).

The process was opening the new window, prompting the download and crashing with:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
```

**Comment by jakerobb** [comment]
Exit status 3221225477 is the hex value `0xC0000005`, which [corresponds to Windows' STATUS_ACCESS_VIOLATION error](https://stackoverflow.com/a/17169463/535401). It's not, as MarshallOfSound said, "the npm error number." 

Due to the nature of Electron, the odds are high that the bug is part Chromium part of the tech stack, and that updating your version of Electron to one with the latest Chromium has a strong chance of fixing your issue.

If that doesn't work, then digging in to the nature of an access violation error tells us that you're accessing an invalid memory address -- usually either overrunning a buffer or dereferencing a null pointer. Translating that into Electron world, look for cases where you've allocated and then destroyed a system-level resource (e.g. a BrowserWindow) and then continued to use it. If there's a way for you to work around the issue, it's going to be that sort of thing.

For what it's worth, for my project, we only experience this issue when running in production mode (i.e. no Express server). It doesn't occur in dev mode. (And, of course, only on Windows.)
