### ISSUE TITLE
Using backspace AND Delete as accelarator not working

### ISSUE THREAD

**Issue by sandor** [electron/electron#10767]
hey guys, I am using this to define my delete eobjects feature in my main-menu:

>             {
>                 label: 'Delete',
>                 accelerator: 'Backspace',
>                 click: function () {
>                     var focusedWindow = BrowserWindow.getFocusedWindow();
>                     focusedWindow.webContents.send('remove', 'removing');
>                 }
>       },

How can I use both "Backspace" AND "Delete" for the same function?

**Comment by codebytere** [comment]
We're going to need a clearer understanding of what you're trying to accomplish and what your use case is before we can begin to look into this. Please also include:
- Electron Version
- Operating System

**Comment by sandor** [comment]
Sorry Guys,

electron version: 1.7.6
OSX: v. 10.11.2 (15C50)

thanks for patience

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
