### ISSUE TITLE
Preview multiple files using `win.previewFile` API

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#10789]
`win.previewFile` allows to send a single file to the quick look panel on macOS. Is it also possible to send multiple files?

For reference, if you select multiple files in Finder and press space, the quick look panel will show prev/next buttons to let you cycle through all selected files. Additionally, using arrow up/down lets you clear the selection and move to different files. I think it would be possible to achieve a similar behavior in Electron by registering global shortcuts, but it does not seem possible to send multiple files to the quick look panel, or did I miss something?

Many thanks!

**Comment by sofianguy** [comment]
@inukshuk Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
