### ISSUE TITLE
desktopCapturer api does not provide the app icon

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#10784]
* Electron version: 1.7.8
* Operating system: Mac & windows

### Expected behavior
When I use `desktopCapturer` api to get list of sources, I should also get the app **ICON**.

### Actual behavior
As of now the api only returns the thumbnail of the application

### How to reproduce
Use this api (https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md) in electron app

**Comment by MarshallOfSound** [comment]
We don't have it documented anywhere that you should get the apps icon?  Is this a feature request or a bug report 😕 ?

**Comment by Ajeey** [comment]
Not a bug for sure if its not documented. 

Would be glad if it was considered as a feature request as its helpful while implementing app sharing and with icons it is crystal clear which app I want to share, contrary to the thumbnail image.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this as a `wontfix`.
