### ISSUE TITLE
DownloadItem.setSavePath is not work in Renderer Env.

### ISSUE THREAD

**Issue by dii0711** [electron/electron#10794]
* Electron version: 1.4.15
* Operating system: mac

### Expected behavior

In the doc, it says "Set the save path, making Electron not to prompt a save dialog".

When I use this in renderer env, it doesn't work and report an error:
Uncaught Error: Could not call remote function 'getSavePath'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getSavePath'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction ...

here is my code?

```
const webCon = remote.getCurrentWebContents();
webCon.session.on('will-download', (event, item, webContents) => {
  item.setSavePath('./test.zip');
  item.getSavePath();
}
```

**Comment by MarshallOfSound** [comment]
@dii0711 `setSavePath` has to be called synchronously during the `will-download` event, the issue here is that two-way communication to the renderer process **must** be asynchronous (by design).  So the `item` will have been disposed of before you call `setSavePath`.  If you move this logic to the main process it will work fine 👍
