### ISSUE TITLE
Multiple electron instances with same IndexedDB

### ISSUE THREAD

**Issue by Tev-work** [electron/electron#10792]
* Electron version: 1.7.8 (and multiple older ones)
* Operating system: MacOS 10.12.6 (but it was reproduced on Win7 as well)

### Expected behavior - multiple browser tabs accessing same DB
Just open MDN IndexedDB example (https://mdn.mozillademos.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB$samples/Full_IndexedDB_example?revision=1317730, from https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB) in multiple tabs of your browser - you can change stuff in one and view it in other etc.

### Actual behavior - multiple electron instances accessing same DB

IndexedDB.open() throws error:
```
DOMException: Internal error opening backing store for indexedDB.open.
```

### How to reproduce

https://github.com/Tev-work/electron-quick-start.
Clone, `npm install` and `npm run` from two terminals, second instance will show error in console. When you place debugger there and inspect the event you'll see the error above.

It is the same for installation via `dmg` or `exe` (archive / installer built via `electron-builder`, multiple versions, newest one was 17.10.0)

This is apparently not just my own issue, see https://github.com/dfahlander/Dexie.js/issues/271

**Comment by MarshallOfSound** [comment]
@Tev-work Opening multiple Electron instances is not the same as multiple tabs in Chromium.  You should call `makeSingleInstance` and on launch of a second instance make a new window inside the original instance of the application.  This should allow both windows to access the indexeddb

**Comment by sofianguy** [comment]
Seems this issue is solved. Feel free to reopen if you are still having problems.

**Comment by fortinmike** [comment]
This is not an option for us. For various reasons, we absolutely *must* have multiple instances of the executable running at the same time, not multiple windows within a single executable, so the proposed solution isn't workable.

Is there any way to make indexeddb work across multiple processes? For our needs, using a separate DB for each process would be acceptable (and even preferred); no need for them all to access the same indexeddb database.

It seems like the first instance of Electron locks the on-disk indexeddb storage file, which prevents other instances of the executable from accessing it. If that's the case, I don't see how we can avoid the issue.

Ideas?

**Comment by JohannBlake** [comment]
I have the same issue. What I noticed is that you can open multiple instances of your Electron app and each can access different indexed dbs on the condition that no two databases are open at the same time. This means that you have to close the db immediately after you are done with it. In my app, I designed it from the start to keep the connection to the db open while the app is running. This prevents me from opening an second instance of the app. Had I known this up front, I might have opted to close the database after every use. Changing that at this point would be a significant upgrade.

If you do decide to go this route, I recommend that each app instance creates a unique database filename when it boots up in order to keep the data separate. Still, even with different database names, this does not solve the problem of one blocking the other. You still must close each database after every use. There is also in rare cases the possibility that both app instances attempt to open the database at the same time. The last one to attempt will fail. That means you need to add extra code to handle that and retry after a short wait period.

**Comment by trusktr** [comment]
Is this the problem? https://github.com/dfahlander/Dexie.js/issues/271#issuecomment-364038802

I just had that problem, so I made sure I had only one instance of Electron running and that did the trick.

Has this been fixed in newer versions of Electron? What will happen when multiple electron apps with different names are running? Maybe that's not a problem?

**Comment by xmedeko** [comment]
Problem still exists in Electron 8.
