### ISSUE TITLE
How much can I rip away from the bloated-by-default Electron distribution?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/electron#10802]
I was apparently able to delete the .\resources\default_app.asar file, and also all the many api-ms-win-*.dll files, while the EXE still caused my app to (apparently) run fine. Maybe that's just on my computer, and it cannot be guaranteed without all those weird files? Would be really nice to get a significantly smaller distribution size.

**Comment by robinwassen** [comment]
api-ms-win-*.dll, vc*140 files are probably for compatibility so the user does not need to install dependencies such as C++ Runtime Redistributable. If you want to try this out, spin up a clean Windows VM and test the app in it with and without the files.

They also only add 1.5MB to the install which is tiny compared to Electron itself.

The normal statement is that it is hard to reduce the distribution size since Electron bundles Chromium which is large by default. But if you want to give it a shot one thing would be to research out some executable / binary packers such as: https://upx.github.io/. I have not done any serious attempt at packing binaries and I do not know how bad the side effects are.

Another take is to check what node modules that you include in your distribution - I've bumped into modules that add 5MB to the dist and basically just contains a helper function.

**Comment by FjicdeiwFeiej** [comment]
Yeah, I suppose, like NW.js, most of it "has to be there". Still, it feels silly to have 100 MB overhead for a small JS script, really. I use a minimum of Node modules, too.

**Comment by MarshallOfSound** [comment]
See #673 for generic discussions on ways to make installed Electron apps smaller.  If you use a community packager `default_app.asar` should be deleted from the final bundle.  As @robinwassen mentioned those dlls are for people without certain C++ / .net redists installed and they are pretty tiny in the big scheme of things.
