### ISSUE TITLE
getting document of child window created using window.open (  webPreferences: {     nativeWindowOpen: true   })

### ISSUE THREAD

**Issue by mrudangit** [electron/electron#10824]
I am creating child window using window.open and writing angular 4 components dom element into document . it is working all fine however one of the ui element needs new window's document 
not sure how to get hold of new window's document 

there is my function to create child window. 

 public showComponent(component: ComponentRef<any>,element:any){

    let w = window.open('', 'AngularComponent', 'width=300,height=300,scrollbars=1,resizable=1', false);

    w.onload = function () {
     console.log('Child Window is Loaded Now ');
    };

    w.document.onload = function () {
      console.log('Child Window document is Loaded Now ');
    };

    w.document.write('<div id="root"></div>');

    const root = w.document.getElementById("root");

// element of Angular 2 component
    root.appendChild(element);

    this.addCss(w,'../node_modules/ag-grid/dist/styles/ag-grid.css');
    this.addCss(w,'../node_modules/ag-grid/dist/styles/compiled-icons.css');
    this.addCss(w,'../node_modules/ag-grid/dist/styles/theme-blue.css');

  }

**Comment by realsaraf** [comment]
Hi @mrudangit ,

When u try to access w.document, it will give u the document of the parentWindow that is creating the child window, instead of the document of the childWindow itself. It's sounds crazy but that the case.

You can apply this trick to solve this : 

**1. In the index file that is loaded in your child window add a global function something like this :** 

```
function getDocument() {
       return document;
}
```

**2. then in the above sample code you gave,** 

instead of try to access the document of childwindow as `w.document`

do 

`w.getDocument()`

let me know if this works for u

**Comment by realsaraf** [comment]
Another method is to simple wait for the childWindow to load then access the document object : 

```
w.onload = function () {
  w.document.write('<div id="root"></div>');
  const root = w.document.getElementById("root");
};
```

**Comment by mrudangit** [comment]
yes interesting is w.onload is not called tho

**Comment by realsaraf** [comment]
it won't be called if not url is specifed

**Comment by realsaraf** [comment]
**try this if u want to still get the document without having to pass a url :** 

```
w.webContents.on('dom-ready', ()=>{
  w.document.write('<div id="root"></div>');
  const root = w.document.getElementById("root");
 });
```

**Comment by mrudangit** [comment]
"electron": "^1.8.1",
platform Windows 7

**Comment by mrudangit** [comment]
@realsaraf  thanks seems it is going forward with URL i do get onload call back 
however component is still bound to parent window app base.

**Comment by sofianguy** [comment]
@mrudangit Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
