### ISSUE TITLE
app.setAsDefaultProtocolClient documentation needs to be updated for Linux

### ISSUE THREAD

**Issue by jkleinsc** [electron/electron#10837]
* Electron version: 1.8.2-beta.1
* Operating system: All

#10670 added support for `app.setAsDefaultProtocolClient` in Linux, but the corresponding documentation was not updated to reflect that this method now is available in Linux:
https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-path-args-macos-windows

To fix the documentation, please remove `_macOS_`  and `_Windows_` from this line: https://github.com/electron/electron/blame/master/docs/api/app.md#L546

**Comment by jkleinsc** [comment]
Closed as #10839 resolved this issue.

**Comment by jayarjo** [comment]
@jkleinsc does this really work on linux? It doesn't for us and it still feels like it requires some update in the description. Is it meant to handle internal uris only or external ones as well?

**Comment by jayarjo** [comment]
Ok, it works for `deb` and `rpm`, but not for `AppImage`, which might be obvious for some, but still worth mentioning in the docs, IMHO.

**Comment by brunolemos** [comment]
@jayarjo and how to make my `appschema://` work on linux `AppImage`? I see no guide about this :(

**Comment by jayarjo** [comment]
@brunolemos no idea. It doesn't work for us. Theoretically it probably can be done via manual manipulation of the system files, but that's obviously not an option. So we simply went on with `deb` and `rpm` packages (where it does work) and left `AppImage` as an optional (portable) format.

**Comment by jayarjo** [comment]
Ok, turns out `electron-builder` has a bug, where if app name has a space in it, it's `AppImage` fails to integrate with the system https://github.com/electron-userland/electron-builder/issues/3547. I don't know how deep it goes and whether other bundling solutions or electron itself have this problem as well. But it keeps AppImage from integrating with the system properly and thus breaks support for custom protocols.

@jkleinsc maybe this issue has to be revised once again.
