### ISSUE TITLE
text render behavior is not same as chrome do

### ISSUE THREAD

**Issue by miaulightouch** [electron/electron#10832]
* Electron version: 1.7.9 (Chrome/58.0.3029.110)
* Operating system: OS X 10.11 El Capitan

* compared Chrome version: 61.0.3163.100

### Expected behavior

text should render as same as chrome

### Actual behavior

blurry text rendered

there's compare:
![](https://imgur.com/woyVEe0.png)

1. electron rendered text is bolder than chrome
2. with `-webkit-font-smoothing: antialiased`, latin character corrupted but non-latin character work fine.
  * note: chrome using `-webkit-font-smoothing: subpixel-antialiased` by default

### How to reproduce

just loadURL in BrowserView/BrowserWindow with this url:
http://game.granbluefantasy.jp/
and you will see an article at page bottom.

**Comment by sorentycho** [comment]
Something very similar is happening on Linux. More specifically, it looks like Electron is using greyscale font antialiasing instead of subpixel, regardless of situation or system settings:
![2017-10-23-130950_324x76_scrot](https://user-images.githubusercontent.com/30617489/31985527-44e89b66-b91a-11e7-970b-4993df129934.png)

(on top is Electron 1.7.9, on the bottom, nwjs 0.26.0 (Chrome 62), purple border is a window manager border - these are running side-by-side on the same machine)

Instrumenting `atom/browser/native_window.cc` after line 88 shows that system-level font rendering settings are being picked up correctly (antialiasing is on, subpixel is set to RGB which is correct for my monitor, etc), indicating that the problem probably exists somewhere inside libchromiumcontent. Right now this is the only app on my systems affected this way, and it occurs on multiple machines and flavors of Linux including a freshly-installed Ubuntu VM. Significantly, installing a patched fontconfig/freetype/etc bundle (Infinality) has no effect on font rendering in Electron while working as expected everywhere else including Chromium.

**Comment by FishOrBear** [comment]
Using the link below to display Chinese also encountered similar problems.

https://www.google.com/search?q=%E6%B5%8B%E8%AF%95&oq=%E6%B5%8B%E8%AF%95&aqs=chrome..69i57j69i61l3j0j69i59.770j0j7&sourceid=chrome&ie=UTF-8

**Comment by FishOrBear** [comment]
> 这仍然发生在Electron 4.0.0-beta.7中吗？

Yes, the font display is different from Chrome.

**Comment by nornagon** [comment]
I'm also seeing differences in font rendering between Chrome 70 and Electron 4.0.0-beta.7 around subpixel antialiasing. I'm not seeing the "bold" artifacts that you are though.

<img width="946" alt="data_text_html__meta_charset_utf-8__div_style__font-family_sans-serif__ electron_4_0_0-beta_7 _png_and_hello_world__png" src="https://user-images.githubusercontent.com/172800/48582377-3801f600-e8d9-11e8-9762-3c833f653233.png">

These are both rendering with PingFang SC.

**Comment by sorentycho** [comment]
Possibly related: https://github.com/electron/electron/issues/10955#issuecomment-428635527
(see thread for an experiment to try around subpixel rendering)

**Comment by FishOrBear** [comment]
![image](https://user-images.githubusercontent.com/19372111/48595137-6db4e680-e98e-11e8-9aff-6a14d9a36955.png)

chrome 70  
vs  
2.0.13

**Comment by nornagon** [comment]
See also #15486. Not related to subpixel anti-aliasing, but could explain some other font choice differences.

**Comment by miniak** [comment]
Please create a new issue if you can still reproduce this problem on a supported Electron version.
