### ISSUE TITLE
How to build on Loongson(MIPS64EL) platform?

### ISSUE THREAD

**Issue by yunzhenhuan** [electron/electron#10833]
Why only ia32 (i686) 、 x64 (amd64) 、arm, But MIPS64?
```url
https://github.com/electron/electron/blob/master/docs-translations/zh-CN/development/build-instructions-linux.md
```

**Comment by sofianguy** [comment]
@yunzhenhuan Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
