### ISSUE TITLE
How to send a request with cookie in renderer process

### ISSUE THREAD

**Issue by faaaar** [electron/electron#10849]
- Electron version: 1.7.3
- Operating system: MacOS, Windows

Hi, all

In my app, I need to send request with fetch. And I need cookie. But now I don't know how to set cookie in my renderer process. `document.cookie` is not working and `electron-cookie` is not working too(I need cookie not localstorage.cookie).
What should I do.

Thanks.

**Comment by sethlu** [comment]
Hi @faaaar! Check if https://github.com/electron/electron/blob/master/docs/api/cookies.md offers any help; it's used in the main process.

A past example usage (built in an older version of Electron) can be found here: https://github.com/kevinold/graphiql-app/commit/9cd8d6d6f507892acea056476bf679175adb77a7#diff-7a9076d6d94e62c13d641aa71f19ae8eR26

**Comment by sofianguy** [comment]
@faaaar Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by jepperaskdk** [comment]
@sofianguy Could you then add a task about documenting how cookies are handled in the renderer process? E.g. cookies set server-side are not showing up after a `fetch`.. What is the correct way?
I've just been through a ton of threads, without luck.

**Comment by demo7up** [comment]
This is a good question as I cannot find any information to set cookies from the renderer process, and I feel this is more of an area where its needed?! Im going going to assume you may need to send the data from the renderer to main via 
IPC
