### ISSUE TITLE
Private project name sent over the network via Electron's User-agent...

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/electron#10843]
I was just shocked to learn that Electron sends your app's name in the user-agent string when making fetches... That was my internal project name that has now apparently been sent over the network numerous times while testing. Great. So much for keeping that name secret until release...

How can I turn this off without having to specify a whole custom user-agent string?

Anticipating the "ask in our chat room" response: it's completely dead. Nobody ever responds there. And Slack requires a bunch of "invitations" and registration nonsense, so I can't use that either. That's why I ask "help" questions (I see no difference, frankly) here -- not to be rude.

**Comment by MarshallOfSound** [comment]
> I was just shocked to learn that Electron sends your app's name in the user-agent string when making fetches

IMO this is pretty standard behavior (send the name of the thing making requests as the user agent), that's literally what the purpose of the user agent is.

From the spec of the `User-Agent` header:

> The User-Agent field-value consists of one or more product
   identifiers, each followed by zero or more comments (Section 3.2 of
   [RFC7230]), which together identify the user agent software and its
   significant subproducts.  By convention, the product identifiers are
   listed in decreasing order of their significance for identifying the
   user agent software.  Each product identifier consists of a name and
   optional version.

The most significant identifying factor in the case of Electron apps is the app itself.

> How can I turn this off without having to specify a whole custom user-agent string?

The only way to do this afaik is to override the user agent string yourself

> Anticipating the "ask in our chat room" response: it's completely dead. Nobody ever responds there.

This could not be further from the truth, there are almost 15000 people in that chat room and multiple conversations happen every single day.

> That's why I ask "help" questions (I see no difference, frankly) here -- not to be rude.

Every time you ask a "help" question here (and by the way clearly now in full knowledge it's not what we want people to be doing) someone has to close it, inform you to use actual help mediums, possible help you out and then get back to what they were doing, it wastes maintainers time that could be spent on more valuable things.  The only reason I have been answering your questions instead of blanket closing them is because that's just how I do things, in the future please direct your questions to the appropriate help channels (the slack room or the community forums), personally I would try Slack because there are quite a lot of active people who will more than likely be able to help you.

**Comment by FjicdeiwFeiej** [comment]
Again, Slack doesn't let me register. And the chat room (IRC) is completely dead. What do you expect me to do?

**Comment by MarshallOfSound** [comment]
What happens when you try register through http://atom-slack.herokuapp.com ?

**Comment by FjicdeiwFeiej** [comment]
It worked to register, but it just says "Welcome to Slack!" with a spinning animation; it never actually gets into any chat room. I've reloaded the page several times and only see that text: 
![dfddfdf](https://user-images.githubusercontent.com/32551165/31776247-455b6016-b4eb-11e7-95d5-1c08646774d7.png)

**Comment by FjicdeiwFeiej** [comment]
Worked now (later).
