### ISSUE TITLE
new MenuItem({role:'copy'}) have something confused

### ISSUE THREAD

**Issue by JackieLs** [electron/electron#10857]
`MenuItem({role:'copy'})`
* Electron version: 1.6.10
* Operating system: 10.12.6 (16G29)

![image](https://user-images.githubusercontent.com/14228179/31803988-5179e800-b51c-11e7-9ebd-ce5ddb0ac135.png)

Why here I got a Chinese 'Start Dictation' ? How could I fix this? Is there any place I could set the language?

**Comment by sofianguy** [comment]
@JackieLs Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by warpdesign** [comment]
I am having the same problem.
@JackieLs Isn't it a bug? Adding a single entry with the role `copy` shouldn't add two new entries. At least it doesn't seem to be mentioned in the docs.

@sofianguy did you find a way to fix this (or at least change the label)?
