### ISSUE TITLE
Old zlib(1.2.8 with security issue) used in electron-v1.7.9-win32-ia32.zip

### ISSUE THREAD

**Issue by zuoxiaofeng** [electron/electron#10869]
The electron.exe in the electron-v1.7.9-win32-ia32.zip was be scaned and used zlib_v1.2.8. 
I check the electron.exe.sym in electron-v1.7.9-win32-x64-symbols.zip found that the zlib_v1.2.8 is included in pdfium.lib a static lib in libchromiumcontent.

**Comment by jsnar** [comment]
Electron has far more security vulnerabilities than this: the latest version is still based on old Chromium (58 & 59) so it inherits many of the security vulnerabilities published in Chromium [60](https://chromereleases.googleblog.com/2017/07/stable-channel-update-for-desktop.html), [61](https://chromereleases.googleblog.com/2017/09/stable-channel-update-for-desktop.html) and [62](https://chromereleases.googleblog.com/2017/10/stable-channel-update-for-desktop.html)

**Comment by robinwassen** [comment]
**CVE:s:**
- https://www.cvedetails.com/cve/CVE-2016-9842/
- https://www.cvedetails.com/cve/CVE-2016-9843/

**zlib changelog:**
- https://zlib.net/ChangeLog.txt

In any case the step to resolve this is to upgrade the Chromium dependency since zlib has been updated there (https://bugs.chromium.org/p/chromium/issues/detail?id=691075), NodeJS who also uses zlib is using the latest version since 7.6.0: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#2017-02-21-version-760-current-italoacasas

**Comment by MarshallOfSound** [comment]
As per our [SECURITY](https://github.com/electron/electron/blob/master/SECURITY.md) document if Electron is exposed to third part vulnerabilities can you please report to the indicated email address and not to the public issue tracker.

**Comment by zuoxiaofeng** [comment]
I have try 1.8.2-beta1, it seems fixed the zlib1.2.8 security issue,  but there comes a new security issue for openjpeg, I have already send security issue email by the SECURITY document.
