### ISSUE TITLE
<img> taking too long to update on file src change

### ISSUE THREAD

**Issue by constantincerdan** [electron/electron#10879]
* Electron version: 1.7.5
* Operating system: OSX 10.10.5

I have a `<select>` element containing a list of _.tif_ files in a given folder on a network drive. Upon selection of each file, I create a small jpeg (thumbnail) of that file and save it into a _.thumbs_ folder within that folder. The thumbnail is displayed as an `<img>` in a 'preview panel' next to the `select` element and if the file the user selects has a newer modified date than the thumbnail, I delete the thumbnail and create a new one in its place and replace the `HTML` in the preview panel with a new `<img>` pointing to it.

### Expected behavior

The newly added `<img>` should display the newly created _jpeg._

### Actual behavior

The newly added `<img>` almost always still displays the old _jpeg_ for a while, even though that file has been deleted and replaced with another one. I currently use `ipcRenderer` to make the `main` process clear all caches but it doesn't work or seem to have an immediate effect. The new _jpeg_ will, however, display immediately if I reload the app/window.

### How to reproduce

1. Display a _jpeg_ file in a window using `<img>`
2. Make a change to that _jpeg_ file
3. Replace current `<img>` with new `<img>` pointing to _jpeg_ file
3. `<img>` does not display new jpeg immediately unless window/app is reloaded

**Comment by RedDuckss** [comment]
Just based on your reproduction steps it seems you misunderstand how `img` tags work. Once an `img` tag loads an image, it stays as that image even if the source file changes. `img` tags do not live-reload when the source file changes, at least not on their own, and require a refresh or restart to update. That isn't an Electron issue, that's just how `img` tags work.

**Comment by constantincerdan** [comment]
@RedDuckss Apologies. While I described replacing the `<img>` with a new one in my introductory paragraph, I did not detail that in my reproduction steps. I have updated my post.

**Comment by RedDuckss** [comment]
So if I understand your issue correctly what you're doing is dynamically rewriting the _same_ image file with a new image, then trying to create a new `img` tag with that same src path. That is, again, not an issue with Electron. It's just how browsers/`img` tags work. The issue you describe here is true in a normal browser as well. The image is saved to memory (if I remember correctly, been a while since I learned this stuff) and is reused even if the source file is changed.

Here is a basic example of what you're currently doing: https://hastebin.com/goyuyotifo.html

Try it in a normal browser. You'll have to generate a new image and reference that.

**Comment by constantincerdan** [comment]
Damn, just tested it and you're right. I had no idea that was the case, sorry. Thanks for the explanation, I'll close this thread now.

**Comment by RedDuckss** [comment]
Commenting back because I actually forgot, you _can_ do what you were trying to do, just not the way you were trying to do it. You need to provide the image source with a fresh url for the image to update. To do this, you can append a random set of characters to the end of the url as a parameter. The easiest way to do this is with `new Date()`

See here for an example of what you want to change to get this to work, without generating a new image: https://hastebin.com/nuniroyica.html

**Comment by constantincerdan** [comment]
Yup, I did some Googling after you opened my eyes as to how `img` tags actually work and found a similar solution here: https://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url/9943419#9943419. That said, I very much appreciate you coming back and recommending this solution, even after I'd closed the issue. Thank you :)
