### ISSUE TITLE
XSession available but electron does not start on BeagleBone (ARM)

### ISSUE THREAD

**Issue by acourdavault** [electron/electron#10884]
Hello I've seen issues like mine here https://github.com/electron/electron/issues/7199
I've followed the steps mentioned.
I have an X Session, that i forward on VNC most of the time, but I also tried with an simple HDMI screen.

My screen works, but electron does not do or say anything when it starts

![image](https://user-images.githubusercontent.com/27222128/31899913-30bc7638-b81d-11e7-8de3-c536577cec08.png)

I'm on Arm v7 with a Jessie.

Should I install a GTK backend?

thanks in advance

**Comment by sofianguy** [comment]
@acourdavault Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
