### ISSUE TITLE
print to Thermal printer failed

### ISSUE THREAD

**Issue by kennir** [electron/electron#10935]
Did electron support thermal printer ? I try the printer demo but output a blank paper

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
