### ISSUE TITLE
setPosition() and setBounds() not working when window is minimized.

### ISSUE THREAD

**Issue by JerryGoyal** [electron/electron#10949]
I can't change the position of window when it is minimized, after maximizing (win.show) it opens at the old position :(

Here's the sample code:

```
var clipboardWindow = new BrowserWindow({
        width:250, height: 600,
        backgroundThrottling: false, show: false, hasShadow: true,skipTaskbar: true,
        thickFrame: false,frame: false
        
    })
    clipboardWindow.setMenu(null)
    clipboardWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true
    }))

let point = electron.screen.getCursorScreenPoint();
        clipboardWindow.setPosition(point.x + 10, 20, false);
        clipboardWindow.show(); // it opens at the old position which should not be the case
```

**My Hack 1**
```
clipboardWindow.show(); //shows the window at position x and y for a brief period of time
clipboardWindow.setPosition(point.x + 10, 20, false);
 clipboardWindow.show(); // shows window at the disired cordinates
```

_But then it flicks the window from one position to another like a flashing window which is not a good user experience._

**My Hack 2**
before hiding the window i set the position to out of bounds of screen. 
```
let p = electron.screen.getPrimaryDisplay().size
    Window.setPosition(p.height, p.width, false);
```
It helped me preventing that brief flashing of window.

As these are just hacks which I don't like so tell me how to set the window position gracefully?

* Electron version: 1.7.9
* Operating system: Windows 10

**Comment by sofianguy** [comment]
@JerryGoyal Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
