### ISSUE TITLE
WebGl Unavailable

### ISSUE THREAD

**Issue by 694982827** [electron/electron#10983]
* Electron version:v1.8.2-beta.1-linux-x64
* Operating system:ubuntu16.04

    when I open chrome://gpu/,the WebGl is ok but the WebGl2 is unavailable .   
    when I visit https://get.webgl.org/" it shows "Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.".
    Is there anything wrong?

**Comment by sofianguy** [comment]
@694982827  Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by DandroidDeveloper** [comment]
I am experiencing this issue as well. I usually can run webGL in electron on older graphics  cards by adding the command line flag --ignore-gpu-blacklist. This is fine security wise because my apps don't connect to the internet. With the newest version, 3.0, it seems like that flag is being ignored or something because webgl immediately throws the 'cannot find extensions' error.
