### ISSUE TITLE
TypeError: Error processing argument at index 0

### ISSUE THREAD

**Issue by ue** [electron/electron#10982]
Hi I have this problem.
I tried everything as much I can.  I could not find any solution for that 
I create packages with use `gulp package ` and there is no image for app after than if I click the app its not working also I got this error. I don`t know what can I do. Same body please help me. 

![](https://media.giphy.com/media/3o6obR49zb2HefIEbC/giphy.gif)

And I`m shere with you my `index.js`

This my ` index.js ` content [index here](https://github.com/ue/electra/blob/master/src/index.js)

Also my app this one [app here](https://github.com/ue/electra/)

**Comment by felixrieseberg** [comment]
It's a bit unclear what your actual problem is. If you have trouble building, I would recommend using `electron-forge`, which you can find here: https://github.com/electron-userland/electron-forge

That said, I believe that your icon is not at the correct path. It seems like `nativeImage` can simply not find your image...?
