### ISSUE TITLE
Calling getUserMedia with a bluetooth headset connected degrades audio

### ISSUE THREAD

**Issue by justinIs** [electron/electron#10996]
* Electron version: 1.7.5 (also reproduced on 1.8.2-beta.1)
* Operating system: macOS Sierra 10.13

### Expected behavior

Calling getUserMedia while a bluetooth headset is connected should not degrade the quality of audio

### Actual behavior

Calling getUserMedia while a bluetooth headset is connected degrades the audio quality on the OS

### How to reproduce

have a bluetooth headset connected, then run code that calls `navigator.mediaDevices.getUserMedia`

As long as the headset is connected at the time of the API call, the audio quality degrades

**Comment by justinIs** [comment]
Any update on this? Is there anything I can do to help debug the problem?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by avi-antares** [comment]
I am not sure if this is still relevant in this thread, but the issue appears to be more generic and perhaps has nothing to do with Electron. Reproducing this issue is simple:

[on Mac, OSX Catalina 10.15.5 (19F101) and Safari Version 13.1.1 (15609.2.9.1.2)]
  1. Play a song or something (sound output defaulted to bluetooth
  2. Go to Google Meet and start an instant Meeting
  3. The moment you provide the permission to (any) microphone, the quality of the audio immediately degrades.

I hope this helps.
