### ISSUE TITLE
how to show browserWindow without the win taskbar

### ISSUE THREAD

**Issue by erricPl** [electron/electron#10991]
i create the browserWindow use the params {focusable: false}，the taskbar is not show ,but bring the new question that the  input text dom  in the browserWindow cannot focus,i cannot input any content. i want the browserWindow can focus that i can input content and not not show taskbar

**Comment by sofianguy** [comment]
@erricPl 
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful community members in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
