### ISSUE TITLE
allowing Geolocation in webview

### ISSUE THREAD

**Issue by fjsfelix** [electron/electron#11034]
I'm loading a website in my webview. Is there a way to allow Geoloaction when it is requested by the website inside my webview?

**Comment by felixrieseberg** [comment]
The API should just work (all the usual permissions are rigged to assume `Yes` as the default answer), but Electron is built with a default API key. The quota for that key is almost always rate-limited.

In order to use Geolocation, you will have to build Electron yourself and replace this key with your own: https://github.com/electron/electron/blob/9c19b4e3d5bd9a17d46b09e7ee1ebd6fc2fefc30/atom/common/google_api_key.h

**Comment by Nashorn** [comment]
Well, thats just not right
