### ISSUE TITLE
minimum BrowserWindow width can't be less than 120px on Windows10

### ISSUE THREAD

**Issue by ajantiss** [electron/electron#11031]
* Electron version: 1.7.9
* Operating system: Windows10

### Expected behavior

Be able to create a BrowserWindow of **70px** width on Windows 10.

### Actual behavior

Electron window opens with a default width of **120px**. It is possible to resize it **manually** with mouse, however call to _setSize_ or _setContentSize_ does not resize the window to **70px** once window is loaded.

### How to reproduce

Simply by creating a simple BrowserWindow on windows10
`win = new BrowserWindow({width: 70, maxWidth: 70, minWidth: 70, height: 900, show: true})`

By the way same code is working as expected on Linux.

**Comment by felixrieseberg** [comment]
You should not be able to resize the window manually to less than ~120px in width, because that's the size of the window controls. Do you have a gif? It sounds like a fascinating Windows bug.

Otherwise, set `frame: false`, which will allow you to create windows of any size.

**Comment by sofianguy** [comment]
@ajantiss Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
