### ISSUE TITLE
`navigator.languages` returns an empty array

### ISSUE THREAD

**Issue by kysely** [electron/electron#11053]
* Electron version: 1.7.9
* Operating system: macOS

### Expected behavior
`navigator.languages` should return array of user's preferred languages, e.g. `["en-US", "zh-CN", "ja-JP"]`

### Actual behavior
`navigator.languages` returns an empty array `[]`

### How to reproduce
Create a primitive HTML file that logs `navigator.languages` into console. Then try loading via `file://`, `http` and inside Electron's `renderer` process. The first two will give you actual results while `renderer` yields empty array.

**Comment by kysely** [comment]
Okay, so you can set the `navigator.languages` to your own custom value in `preload`, but this is still just a workaround.

```javascript
Object.defineProperty(navigator, 'languages', {
    value: ["en-US", "zh-CN", "ja-JP"],
    configurable: true
});
```

**Comment by felixrieseberg** [comment]
Yep, that's a legit bug (or at least a documentation issue).

**Comment by melvin-clickprofits** [comment]
Hi i'm kinda stuck on this issue, i have implemented skype `https://dev.skype.com/webcontrol` on web page, but i got an error on their js library due to a bad checking of the `navigator.languages`

![screenshot at 2017-11-10 10 47 29](https://user-images.githubusercontent.com/30608398/32640824-7e223be2-c605-11e7-8b96-1a1cfe419ee5.png)

is there any work around to set default value for `navigator.languages` ?

main issue is the skype sdk loaded by an iframe injected by the sdk, so even i set it in my page, it will no work. 

Thanks in advance.

**Comment by kysely** [comment]
@melvin-clickprofits Did you try [the solution I propose above](https://github.com/electron/electron/issues/11053#issuecomment-342610511)? It works for me. 

If you need to set `navigator.languages` for the iframed document, you can do it the same way, only instead `navigator` object, you'd need to pass the iframe document's `navigator`, like this:

```javascript
Object.defineProperty(document.querySelector("#iframeId").contentWindow.navigator, 'languages', {
    value: ["en-US", "zh-CN", "ja-JP"],
    configurable: true
});
```

**Comment by melvin-clickprofits** [comment]
@kysely tested tt works, ju Thanks :+1:, just have to make sure the iframe is already inserted

**Comment by haoRchen** [comment]
Hi, I'd love to tackle this if no one is working on it.

**Comment by nitsakh** [comment]
I'm working on it currently.

**Comment by tonyganch** [comment]
@ckerr, can this issue be closed? I see PR merged.

**Comment by nornagon** [comment]
Looks fixed to me!
