### ISSUE TITLE
Invisible app menu on Windows 10

### ISSUE THREAD

**Issue by willnickerson** [electron/electron#11070]
When running this electron app on Windows machine, main app menu does not appear to open when labels are clicked. However you can still access the menu items by clicking where the menu is expected to be. i.e. the app menu is invisible/transparent. We were not able to reproduce the bug on a Mac or our other computer running Windows 10. Unfortunately, we are working on a private repo, but it would be nice to know if others have encountered a similar issue.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment]
@willnickerson 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11070#issuecomment-343028095). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
