### ISSUE TITLE
referrer not being set when loading a URL through webview.loadURL

### ISSUE THREAD

**Issue by 7085** [electron/electron#11109]
* Electron version: 1.8.1
* Operating system: Ubuntu 16.04.3 LTS

This issue seems to be similar to https://github.com/electron/electron/issues/2445, but it happens in the webview.

### Expected behavior

The referrer header and the document.referrer property should be set to the provided value when using `webview.loadURL`.

### Actual behavior

The referrer header and the document.referrer are not set at all.

### How to reproduce

```
  $ git clone git@github.com:7085/electron-playground.git
  $ npm install
  $ npm start || electron .
```

And checking the developer console output. I have provided 4 different types of setting the referrer, all produce the same result.

**Comment by felixrieseberg** [comment]
Works just fine, you just have to use a proper URL. Internally, Chromium creates a `GURL`, which requires that the `httpReferrer` is set to a proper URL - a random string like `TEST` will result in the field being unset.

If I change all your `TEST*` values to a proper URL, I get the refererr logged. Does that work for you too?

**Comment by 7085** [comment]
Thanks, yes I can confirm that it works when providing a proper URL.

According to https://tools.ietf.org/html/rfc2616#page-140 a relative URI should also be possible. 
At least with curl this is possible (`curl -H "Referer: test" https://www.whatismyreferer.com/`).

So is it correct that this is not possible at all (because of Chromiums behaviour)?

**Comment by 7085** [comment]
Furthermore it does not work when the referrer is only set via extraHeaders and the httpReferrer field is not set (TEST2, TEST3).

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
