### ISSUE TITLE
How to add "quit" user task in windows task bar?

### ISSUE THREAD

**Issue by karthik-gumpu** [electron/electron#11113]
How to provide quit option in taskbar menu? Which command arguments I need to pass to setUserTasks?
![untitled](https://user-images.githubusercontent.com/20722112/32764518-e91ec3b0-c92b-11e7-889d-35cd82f3b319.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW you should use your own executable, `makeSingleInstance` and pass in a custom argument which indicates you should quit the original instance.  I.e.

MyApp is running, MyApp quit task launches `MyApp.exe --quit-please`, MyApp receives those arguments in the first instance (because of `makeSingleInstance`) and immediately quits 👍

**Comment by karthik-gumpu** [comment]
Thanks @MarshallOfSound . Your suggestion working fine 👍
