### ISSUE TITLE
when can upgrade chromium to fix the blob bug of chromium?

### ISSUE THREAD

**Issue by ziying0606** [electron/electron#11115]
* Electron version: 1.7.9
* Operating system: windows 7

### How to reproduce
My issue is when I want to upload big files in my electron app, I upload the slice of the whole file using new Blob() each time and chromium 53（the version of chromimum in electron 1.7.9）has 512M limitation for Blob. I cannot trigger blob's gc through blob.close() and I see chromium 57 has fixed the issue [https://bugs.chromium.org/p/chromium/issues/detail?id=375297](url), so I want to know when will upgrade chromium version in electron.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by ziying0606** [comment]
I see electron v1.8.1 has upgraded chromium to 58, but  I cannot use it through npm.

**Comment by MarshallOfSound** [comment]
@ziying0606 It's currently tagged as beta so you need to explicitly `npm i electron@1.8.2-beta.2`
