### ISSUE TITLE
executeJavaScript does not reject with the Error of the rejected eval result Promise

### ISSUE THREAD

**Issue by bughit** [electron/electron#11155]
* Electron version: 1.7.9 x86
* Operating system: Win7 x64

```js
  try {
    await web.executeJavaScript('new Promise(() => {throw new Error("exec error");});');
    // or
    await web.executeJavaScript('Promise.reject(new Error("exec error"));'); 
  } catch (e) {
    // e should be an Error('exec error')
  }
```
### Expected behavior

 e should be an Error('exec error')

### Actual behavior

e is an empty Object

**Comment by felixrieseberg** [comment]
Yep, that ain't intuitive. I'll fix that.

**Comment by MarshallOfSound** [comment]
@felixrieseberg The issue here is errors don't serialize well into JSON and therefore got lost over IPC.  The way around it is to define Error.prototype.toJSON but that would break lots of things

**Comment by felixrieseberg** [comment]
@MarshallOfSound Ooooor we just go off-script for this one use-case (which I do think is crazy confusing, because people won't study the IPC and innards of Error objects). See the PR for some implementation details, I think it'd be useful to make this accessible.

Most people won't even know that `executeJavaScript` has anything to do with the IPC 😢
