### ISSUE TITLE
any way to close electron savedialog when browserwindow dismiss?

### ISSUE THREAD

**Issue by vercha** [electron/electron#11179]
as titled, 
I create a showsavedialog to export file, while the browserwindow may be closed by other browserwindows's user operation;
so , is there any way to close electron savedialog when browserwindow dismiss? thanks!

**Comment by sofianguy** [comment]
@vercha Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
