### ISSUE TITLE
Use true web browser to render GUI, instead of Chromium

### ISSUE THREAD

**Issue by 0polar** [electron/electron#11183]
Nowadays Electron abuse computer resource, each Electron app ships with its own copy of Chromium, and if you have multiple Electron apps running you will have multiple instances of almost same runtime, but zero shared resources across apps – no shared executable segments, no shared RAM, nothing.

#673 is trying to deal this problem, but it still use private Chromium, not my favorite: I need Firefox, I need Grammarly… I need all my well-tuned setting and workflow for web, Electron use web technology to build GUI, why I can't do this?

Visit web GUI by `http://localhost...` in web browser, is a traditional and good solution, can Electron implement this?

**Comment by felixrieseberg** [comment]
...do you mean Node.js? Because what you're asking for might just be Node.js. Run a server in Node.js and open it in any browser of your choice.

**Comment by 0polar** [comment]
You are right, but I want this feature seamless: When app call Electron API to open new windows, Electron auto open a true web browser window instead of Electron private Chromium. Developer don't need to change app code.

**Comment by felixrieseberg** [comment]
I believe what you might be looking for would be a website - if you want your web app to run in any browser, you'll be far better off with a traditional web app. Chances are very high that progressive web apps and other strides made by modern browsers will already accommodate your needs.

Electron developers often choose Electron because they need tight control over the environment, including the ability to run native code that integrates with Chromium, Node, and the operating system.

I'm closing this issue now (mostly because Electron will likely never support the use case you're asking for). To implement what you are looking for, use Node.js and it's ability to open local urls. If you _desperately want to use Electron_, know that you're going down a path without much value - but you can open any url (including local files) using `shell.openExternal`.

**Comment by 0polar** [comment]
Yes, I believe *use (front-end) web technology in web browser, don't wrap it as "desktop/native" app*.
Electron GUI use web technology, so I think Electron GUI should run in web browser, at least provide the option.

I don't use Electron ever because I use `http://localhost...`. Thank your talk.
