### ISSUE TITLE
Opening  a electron app withing electron+React app

### ISSUE THREAD

**Issue by manas-hegde** [electron/electron#11214]
I have a Electron+react application . Inside this app on a particular page inside i need to open a separate electron  app (preferably on some button click should open a second electron app inside some <div>).

I came across using <webview> feature of electron, but how can i run second electron app on a button click and load it inside that webview?

Please help me

**Comment by codebytere** [comment]
We'll need more information from you before we can really do anything about this: please see [contributing guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
