### ISSUE TITLE
How can I add electron as a View in an existing Xcode Project?

### ISSUE THREAD

**Issue by dingyq** [electron/electron#11267]
Now I had an existing XCode Project，and I want extent it with electron as a view. How can I do it?

**Comment by sidneys** [comment]
@dingyq 

Interesting question.

However, attempting to describe and go about integrating Electron as a single View constitutes a problematic approach, as Electron is a much more encompassing framework, which integrates (apart from NodeJS) with many Cocoa lowlevel APIs, and thus is able to create and destroy related entites (e.g., NSWindows or NSViews) by itself (read more about the Electron build process [here](https://electronjs.org/blog/electron-internals-building-chromium-as-a-library)).

It's not simple a Browser webview which could replace `WebView` or `WKWebView`, there's a lot more going on. However, if one were to attempt this, the first step would be to compile Electron into a library, which can be done by changing the target type from executable to shared_library (within https://github.com/electron/electron/blob/master/electron.gyp).

May [Cordova Browser](https://www.raymondcamden.com/2016/03/22/the-cordova-browser-platform/) (which is in its infancy) would be a better fit for your requirements?

**Comment by dingyq** [comment]
@sidneys 
Thanks for your reply.
Would electron support this officially in the future?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by d4tocchini** [comment]
in case anyone is looking, here's an example using the undocumented API `webContents.getNativeView` (#10308) to embed in native macos UI  

https://github.com/zcbenz/electron_yue
