### ISSUE TITLE
In Electron env, buffer.transcode is undefined

### ISSUE THREAD

**Issue by forgxq** [electron/electron#11270]
I use electron 1.7.5 with node 7.9.0, OS is win10

I want use buffer.transcode. Code is as follows:
`
const buffer = require('buffer');
console.log(buffer.transcode);

// Prints: 'undefined'
`

but the same code run in cmd. the print result is '[Function: transcode]'.

![image](https://user-images.githubusercontent.com/11289236/33301274-e897fc22-d42f-11e7-8125-083412835c0e.png)

![image](https://user-images.githubusercontent.com/11289236/33301500-00028b6a-d431-11e7-8a44-7cd65096d47a.png)

**Comment by sofianguy** [comment]
@forgxq Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
