### ISSUE TITLE
navigator.onLine always returning true

### ISSUE THREAD

**Issue by zakawat** [electron/electron#11290]
* Electron version: 5.5.1
* Operating system: Windows 8.1 (64 bit)

### Expected behavior

It should return **true** if the machine is connected to Router/LAN
It should return **false** if machine is not connected to Router/LAN

### Actual behavior

It always return **true**, even if I turn on Airplane Mode in Laptop OR Shut Down my Router .

### How to reproduce

Just make a simple _HelloWorld_ app with single `index.html` file, open this app, Press `Ctrl+Shift+I` to open Dev Tools, then go to console, in console write `navigator.onLine` and press enter, then turn off WiFi and again give the same command you will see that it will still be returning **true**

**Comment by MarshallOfSound** [comment]
@zakawat Do you have something like Virtual Box or VMWare installed?  Even VPN applications act as virtual network adapters and will make `navigator.onLine === true`

**Comment by zakawat** [comment]
After a detailed analysis, I get to a conclusion that, if you have installed Virtual Box or VMWare (like @MarshallOfSound highlighted) then your Application will always return **true** on `navigator.onLine` 
But if your PC don't have these virtual networks etc then it will work fine.

Now my question is that, if problem is of Virtual Networks, then how does this same command (`navigator.onLine`) works fine in the Chrome Browser _(on the same machine that is having Virtual Networks)_ ...?
And how can I implement a robust solution in Application, because I would not know if any of my Clients have Virtual Networks or VPN ...?

**Comment by sethlu** [comment]
@zakawat Since `navigator.onLine` only shows a possible network connection and nothing more, you may need to manually create a solution to test network accessibility, as mentioned in [Online/Offline Event Detection](https://github.com/electron/electron/blob/32f92f7a90070bce3451edc623fc27b7d62b81f8/docs/tutorial/online-offline-events.md). It is also described here: https://www.w3.org/TR/html5/webappapis.html#the-navigator-object.

One solution is suggested in http://louisremi.com/2011/04/22/navigator-online-alternative-serverreachable/ where a `HEAD` request is performed on the server. (However, the server needs setting up to handle this request method.)

I don't think Electron overwrites the Navigator API written in Chromium, so the behavior in Chromium and in Electron should be the same when working with the `navigator` global object.

**Comment by codebytere** [comment]
The above is correct, Electron itself isn't responsible for `navigator` behavior as we don't overwrite any of those APIs.

**Comment by 01dkdhr** [comment]
My PC has installed VMWare, navigator's online event works good in my chrome browser, but works bad in my electron browser, it's unbelievable.

**Comment by xudafeng** [comment]
I have completed a npm module, hope to help you solve this problem.

https://github.com/xudafeng/network-interface

![image](https://user-images.githubusercontent.com/1011681/89703400-d58a3c80-d97c-11ea-94c6-bd58fd486b61.png)

**Comment by MiroslavPetrik** [comment]
My VPN Client causes onLine to be always truthy.

So it's not always some virtual machine as discussed in this thread.
