### ISSUE TITLE
[Feature request] Introduce LTS with Electron 2.x

### ISSUE THREAD

**Issue by thecodingdude** [electron/electron#11293]
With the upcoming [changes](https://github.com/electron/electron/pull/11032) to the release process I'd like to propose the idea of having an LTS for even numbered releases. I hopefully don't need to explain why/how this would be beneficial, and could work nicely with the semver policy.

My proposal: 

Even numbered releases match even numbered Node releases, which are always LTS (4/6/8).
Each is supported for the lifetime of that node version,
Backports could be accepted but should be non-breaking.

I'm not sure how plausible this is with the policy changes, but would be a welcome change to those who value stability whilst also getting security updates.

**Comment by popod** [comment]
Any plans for a LTS release?

@deepak1556 

As from now, I'm on 3.0.x and I've some bugs with printing. The bug I'm facing to is fixed on 4.0.x (no backport), but some others printing bugs appears on 4.0.x and will be fixed in 5.0.x. So I cannot update to 4 and should wait for the 5th version... This is really bad, because I cannot fix the bug I'm facing in 3.0.x which is fixed in 4.0.x...

With a LTS, I will be sure that the bugs will be backported! I think a lot of users will appreciate that...

Thanks

**Comment by codebytere** [comment]
At present, this is something we've chosen not to do as a function of Chromium and Node's release schedule: more information can be found in our [support](https://electronjs.org/docs/tutorial/support) doc.
