### ISSUE TITLE
Electron-vue打包一片空白

### ISSUE THREAD

**Issue by ChenRiliang** [electron/electron#11326]
Electron-vue
![tim 20171204113804](https://user-images.githubusercontent.com/30994257/33544303-3bceef4c-d915-11e7-9737-ca92407c2037.png)
项目 利用electron-package进行打包

命令 : electron-packager . app --win --out App --arch=x64 --version 1.0.0 --overwrite --ignore=node_modules

打开后一片空白

npm run dev 正常运行

![6tbi jwv 1 nj bwmgh 8](https://user-images.githubusercontent.com/30994257/33544339-6653e5b0-d915-11e7-9b8a-fd613864e754.png)
![tim 20171204113804](https://user-images.githubusercontent.com/30994257/33544340-66927d2a-d915-11e7-9ef0-0b0788f583d1.png)

已用 yarn 和 cnpm 都试过删除重装依赖包

npm: 5.5.1
node :6.11.5

请问这是什么情况？

**Comment by webrtcn** [comment]
use " npm run build " to build your app

**Comment by demopark** [comment]
首先确保你的所有资源已经附加在本地. 执行 `npm start` , 如果可以正常运行, 则不属于electron的问题. 请到electron-packager项目提出问题. electron-packager 打包命令参考: `electron-packager . 'Hosts' --platform=darwin --arch=x64 --icon=hosts.icns --out='./dist' --app-version=2.0.1 --ignore='node_modules'`

**Comment by wenxin3262** [comment]
check your errors in chrome debug console

**Comment by doramart** [comment]
同样的问题，代码什么都没改，打包出来 windows下一片空白

**Comment by wenxin3262** [comment]
Use electron builder, check your vue webpack

**Comment by rensiu** [comment]
@ChenRiliang 打开devTools，看看加载进来的html是不是你想要的

**Comment by dancinglone** [comment]
我也遇到同样的问题。
（I came across with the same issue too）

**Comment by lingfohn** [comment]
不要使用cnpm 使用npm 下载依赖包；
```
rm -rf node_modules
npm install 
npm run build
```

**Comment by shuiRong** [comment]
[Here is a temporary solution](https://github.com/SimulatedGREG/electron-vue/issues/515)
这是一个暂时性的解决方法，后期优化时还是需要解决掉这个问题。

**Comment by miniak** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by miniak** [comment]
If there is a bug in Electron >= 3 that you can reproduce, please file a bug report in English with the appropriate template filled out.

**Comment by tonyganch** [comment]
@ChenRiliang, thank you for taking the time to report this issue and helping to make Electron better.

This issue has been marked for closing because this series of Electron has reached end-of-life and is no longer supported.

If you're still experiencing this issue in the latest version of Electron and would like this issue to remain open, please add a comment specifying the version you're testing with and any other information that a maintainer needs to know to reproduce the issue.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
