### ISSUE TITLE
Cannot move a off-screen electron window back to screen

### ISSUE THREAD

**Issue by Misaka-0x447f** [electron/electron#11349]
*OS: Windows 10
All ways to move off-screen window back does not work on electron window. 

/it will happen when you remove a ext monitor.

is it possible to support, at least, "cascade windows"?
![image](https://user-images.githubusercontent.com/15797507/33641314-f6e8716c-da6f-11e7-8c23-bf3176912311.png)

*One solution: give this menu to user, then user can just click "maximize"
![image](https://user-images.githubusercontent.com/15797507/33641454-88b1b5d6-da70-11e7-9afa-884219b57f16.png)

**Comment by sofianguy** [comment]
@Misaka-0x447f Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by Seankps** [comment]
over 2 years with no fix

**Comment by pcopley** [comment]
> 2 years with no fix... Why close it?
> I found that hitting ALT+Space when the window is selected brings up the menu, press maximize, then you can grab the window

Wow thank you so much for this.

**Comment by annie-elequin** [comment]
Is there any solution other than these "workarounds" of how to get the screen back in the view? 

I would not like to just give users a workaround, but prevent the issue before it happens. Is this possible within electron?

**Comment by Fireclunge** [comment]
God damn this is such an obnoxious maintainer reply. There's a very clear task here. 

On my windows 10 laptop I had to use Win+Alt+Space to access the menu, if that helps anyone.
