### ISSUE TITLE
Test all relative links in docs

### ISSUE THREAD

**Issue by zeke** [electron/electron#11368]
We should add some automated testing that combs through the docs to make sure that all relative links are pointing to files that actually exist.

Example of how this is hard for humans: https://github.com/electron/electron/pull/11367

**Comment by joeydlee95** [comment]
Hi, new to contributing on electron. Would like to take a look at this if no one else is working on it!

**Comment by zeke** [comment]
Hey @joeydlee95, yeah feel free! I would suggest creating a new script, e.g. `/script/check-relative-doc-links.js` or similar, and Node's `path.relative` will probably be helpful.

**Comment by joeydlee95** [comment]
Hi @zeke, I went ahead to use regex to acquire a list of links to check if they exist and on error, print the file and the link name ( should I include the line of error?).

Checking for the relative links seems straightforward but there are links that point to actual website. Should I also include the tests for them? It is possible to get a false negative for this test then since if you run it without internet connection, there would be no way to see if the websites actually exist and the test would fail.

**Comment by zeke** [comment]
We should not check that remote links are resolving. We should just be checking relative links that are pointing to other docs in the Electron repo.

**Comment by joeydlee95** [comment]
#11420 
AHAH! That deep-linked with `some-doc#some-section` caught me off guard especially when considering the `../some-doc#some-section` links. 

I felt my code could be cleaned more but I went ahead to do a pull request, feel free to give feedbacks.

**Comment by zeke** [comment]
Fixed in https://github.com/electron/electron/pull/11420 -- thanks again, @joeydlee95
