### ISSUE TITLE
adding http protocol for firebase login support

### ISSUE THREAD

**Issue by denigada** [electron/electron#11366]
When trying to use **firebase UI** for login in my app, I come across this issue:

> This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled

But I cannot change the protocol in loadURL in main.js, do you have any idea how can I make the firebase UI think that the protocol is http?
`mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'login.html'),
    protocol: 'file:',
    slashes: true
  }))`

**Comment by sofianguy** [comment]
@denigada Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by marcibk** [comment]
@denigada what was your solution?
