### ISSUE TITLE
Using webview throws "Event is not a constructor"

### ISSUE THREAD

**Issue by natew** [electron/electron#11383]
* Electron version: 1.7 and 1.8
* Operating system: Mac High Sierra

### Actual behavior

```
Uncaught TypeError: Event is not a constructor
dispatchEvent | @ | /Users/nw/projects/motion/orbit/apps/electron/node_modules/electron/dist/Electron.app/Contents/Reso…:51
-- | -- | --
  | (anonymous) | @ | /Users/nw/projects/motion/orbit/apps/electron/node_modules/electron/dist/Electron.app/Contents/Reso…:72
  | emitMany | @ | events.js:127
  | emit | @ | events.js:204
```

Screenshot:
![image](https://user-images.githubusercontent.com/12100/33781313-f1b1d5b8-dc08-11e7-857e-637becfb8021.png)

### How to reproduce

Unfortunately would take a while to make a repro, so I may be yelling into wind. But thought it was odd I didn't see this anywhere else on the web. I tried downgrading Electron to 1.7. I am rendering the webview through React, though there seems to be plenty of webview React components, so I assume it should work.

Seems like it's looking for Event which should be on the window, but for some reason isn't. If I `console.log` Event in the console it's there just like normal.

**Comment by shreyneil** [comment]
It looks for variable declarations prior to rest of the code try using something like Event = {} and then use it further. Please verify and get back.

**Comment by natew** [comment]
@shreyneil not sure where I'd put that? I did try doing `window.Event = window.Event` in a file before require.

**Comment by sofianguy** [comment]
@natew Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
