### ISSUE TITLE
Failed to fetch extension

### ISSUE THREAD

**Issue by webkonglong** [electron/electron#11393]
`> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.renderer

Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
Error: net::ERR_TIMED_OUT`

**Comment by webkonglong** [comment]
When the terminal started the project

**Comment by shreyneil** [comment]
The warnings are due to the fact that the electron devtools installer is not able to connect to the chrome as mentioned earlier in the following issue.

https://github.com/SimulatedGREG/electron-vue/issues/37

For the error part it is mainly beacuse of some proxy issue, please reference the following issues and get back.

https://github.com/SimulatedGREG/electron-vue/issues/37
https://github.com/MarshallOfSound/electron-devtools-installer/issues/25

Moreover please follow the guidelines for posting an issue as mentioned by our bot.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

In this case @shreyneil has explained what is going on for you :)

**Comment by zoyopo** [comment]
> `> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.renderer
> 
> Failed to fetch extension, trying 4 more times Failed to fetch extension, trying 4 more times Failed to fetch extension, trying 3 more times Failed to fetch extension, trying 3 more times Failed to fetch extension, trying 2 more times Failed to fetch extension, trying 2 more times Failed to fetch extension, trying 1 more times Failed to fetch extension, trying 1 more times Failed to fetch extension, trying 0 more times Error: net::ERR_TIMED_OUT`

https://github.com/zoyopo/electron-skip-fetch-extension-after-failed  It may help
