### ISSUE TITLE
Window opened from webveiw, gets closed.

### ISSUE THREAD

**Issue by jayeonsu** [electron/electron#11400]
I have a webview in main window and window.open() gets called from the webview contents.
New window opens, but the window automatically will get closed when I navigate in the webview of main window.

I'm working on wrapping an already existing chat&messaging web proejct which can send a message to a certain person through new window of message-sender. However when the webview of main window loads new url, the message-sender window gets closed. 

Is there some way to prevent the window from automatically getting closed when webview loads new url?
That is, although WebContents gets destroyed, the windows opened from it shouldn't get closed.

* Electron version: 1.7.8
* Operating system: Windows 7 and 10

**Comment by sofianguy** [comment]
@jayeonsu Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by jayeonsu** [comment]
oh. I see. Sorry about that.
And thank you for guiding me. :)
