### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Fabiyo-90** [electron/electron#11410]
Help because I can't install electron and I don't know why !
When I use npm install -g electron --verbose
I have as result 
![ectron_issue](https://user-images.githubusercontent.com/26508533/33865160-c499fa3e-def0-11e7-92c2-c71a18f590b9.png)

**Comment by Fabiyo-90** [comment]
I use node v8.7.0 and 
npm v5.4.2

**Comment by Fabiyo-90** [comment]
I downloaded electron-v1.7.9-win32-ia32.zip but I'm wondering how to comment on the use to create an electronic application with a main.js file.
How to integrate nodes globally. I have a project that I have to develop and finish before this Thursday.
How to modify the windows window using electron-v1.7.9-win32-ia32.zip dont electron.exe?

**Comment by sofianguy** [comment]
@Fabiyo-90 Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
