### ISSUE TITLE
[NSApplication isHandlingSendEvent]: unrecognized selector sent to instance 0x7f8af1538110

### ISSUE THREAD

**Issue by malayladu** [electron/electron#11433]
When click on dropdown menu, application crashes and return [NSApplication isHandlingSendEvent]: unrecognized selector sent to instance 0x7f8af1538110 error.

* Electron version:
1.4.13
* Operating system:
MAC OSX EL Capitan - 10.11.6

### Expected behavior
When click on dropdown menu, it should open options to select

### Actual behavior

App Crashes when click on dropdown menu.

### How to reproduce

Create a select box and do "npm run dev" to build applcation

**Comment by sofianguy** [comment]
Thanks for contributing!

This is an old version that we are not supporting right now. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by bemipefe** [comment]
I still reproduce the problem by using electron 1.7.9 on macOS 10.13.6
The loaded page is very simple and it includes a <select> tag with 3 elements.
As soon as I click on the dropdown element the application crashes.

Can you please provide at least the minimum electron version where this problem is solved ?
