### ISSUE TITLE
Use "will-download", blocked the page

### ISSUE THREAD

**Issue by lif3ng** [electron/electron#11436]
I hope to detect the existence of this file in the download directory, if there is no normal download, if there is prompted to re-download and open the directory to choose from.

I use two promises, which are used to detect the existence of this file on the disk, and the prompt exists to allow users to choose to re-download or open.

In the end it did not work, but the main thread's log is the same as expected. I wrote a simple demo for testing:  https://github.com/lif3ng/electron-download-block-demo 

thanks very much 🙏

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
