### ISSUE TITLE
How can I attach to electron standalone window?

### ISSUE THREAD

**Issue by DenisChulkov** [electron/electron#11434]
I test application which consists of standalone electron windows. How can I attach to electron stanalone window using electron?

**Comment by sofianguy** [comment]
@DenisChulkov Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
