### ISSUE TITLE
Support for verticle scroolbar ???

### ISSUE THREAD

**Issue by hiteshsomani** [electron/electron#11473]
* Electron version:
* Operating system:

### How to reproduce

How to enable vertical scrollbar I tried this code in `main.dev.js`

       mainWindow = new BrowserWindow({
          show: false,
          width: 1024,
          height: 728,
          scrollBounce: true,
          icon: `${__dirname}/assets/icon.ico`
      });

**Comment by sofianguy** [comment]
@hiteshsomani Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
