### ISSUE TITLE
Building mksnapshot binary yourself

### ISSUE THREAD

**Issue by hypersad** [electron/electron#11475]
Is there any way to build mksnapshot binary yourself? Currently I'm on `Ubuntu 16.04.3` and `amd64` architecture, but I'd like to build it for `armv7l` (due to broken precompiled binaries that reported here too).

**Comment by sofianguy** [comment]
@hypersad Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
