### ISSUE TITLE
[feature requests]  nightly build version

### ISSUE THREAD

**Issue by chaoliu** [electron/electron#11483]
Now, electron development is very active and hopefully will have a nightly version

**Comment by MarshallOfSound** [comment]
-
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by chaoliu** [comment]
@MarshallOfSound  The Issue Template is mainly for bug report . I don't think the template is 
 applicable to  a new feature or a request for nightly build version of electron. 

Actually ，I tried it.   Closing  a issue without your mind is easy , but I don't think it's the right way !




* Electron version:
* Operating system:

### Expected behavior



### Actual behavior



### How to reproduce
