### ISSUE TITLE
CSS Grid with insertCSS is not working

### ISSUE THREAD

**Issue by developerpruthvi** [electron/electron#11496]
Electron Version: 1.7.9
Operating System: RHEL 7

Hi, recently I tried to inject Some CSS using insertCSS into a webview but it's not getting injected as expected. I'm sure that injection is happening but only CSS Grid styles are not parsed properly.
For example, the following CSS:

```
@media(min-width: 660px) {
  .main-nav {
    grid: 1fr / 100px 1fr 400px;
  }
}
```
was converted like this:

![image](https://user-images.githubusercontent.com/32162613/34249345-6e2fdce2-e65f-11e7-9cb1-9f151b592b06.png)

Any help is appreciated, Thanks.

**Comment by sofianguy** [comment]
@developerpruthvi Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
