### ISSUE TITLE
Images not re rendering on navigation after packaging.

### ISSUE THREAD

**Issue by pikvik** [electron/electron#11508]
Alls well off in dev build. The images are successfully loaded on the landing page. But after navigating through the app, the images are not re-rendered. Also the images for static components are perfectly rendered.
I read through the forum and could not find a solution to this specific problem. I tried using the require statement while loading the image path. But that seemed to pop some error.
Is it some issue with webpack?

![2017-12-22 12_32_33-asystguard](https://user-images.githubusercontent.com/18361946/34288836-790d296a-e715-11e7-813a-c7f15b571742.png)
![2017-12-22 12_32_59-asystguard](https://user-images.githubusercontent.com/18361946/34288838-793f8144-e715-11e7-896f-4863259acb2b.png)
![2017-12-22 12_33_20-asystguard](https://user-images.githubusercontent.com/18361946/34288840-796f83b2-e715-11e7-90f6-83cd3060ad11.png)

**Comment by sofianguy** [comment]
@pikvik Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
