### ISSUE TITLE
rhel6.4, window title is unnamed, <title> in index.html does not work, win.setTitle() does not work

### ISSUE THREAD

**Issue by skelly2015** [electron/electron#11518]
* Electron version: 1.7.9
* Operating system: rhel6.4 internal cut version

### Expected behavior
after set <title> in index.html, the app window title name should be the value
after run win.setTitle() in main.js, the app window title name should be the value

### Actual behavior
the app window title is 'Unnamed', none of the above works.

### How to reproduce
We have internal cut version for rhel6.4. I think it is a simplified version for rhel6.4. So we manually compile some libs for electron to launch on it successfully. My expectation is to change the window title as we need. Do you have any idea about this? Is it that some libs that setTitle() function need have been removed from our rhel6.4? What might they be?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
