### ISSUE TITLE
Printing an iframe shows a save dialog instead of a print dialog

### ISSUE THREAD

**Issue by EricG-Personal** [electron/electron#11580]
I have a sample app on the branch: https://github.com/EricG-Personal/electron_pdfkit_test/tree/feature/with_iframe

It is a very simple react based app that upon launch, dynamically creates a PDF and loads it into an iframe.

I have an iframe with contains PDF content. I try to print this iframe with:

    iframeloaded()
    {
        console.log( "iframe loaded - printing" );

        // window.frames[0].focus();
        // window.frames[0].print();
        
        var myWindow = remote.getCurrentWindow();

        myWindow.webContents.print();
    }

However, a save dialog appears instead of the expected print dialog. 

Is there a way I can get the print dialog to appear?

The PDF that is saved does contain the correct content. 

I am using the latest version of electron on the latest version of OS X.

**Comment by sofianguy** [comment]
@EricG-Personal Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
