### ISSUE TITLE
speechSynthesis only have native voice

### ISSUE THREAD

**Issue by shugen002** [electron/electron#11585]
* Electron version: 1.7.10 & 1.8.2-beta.3
* Operating system: windows 10 (16299.192)

I am trying to make a program which will automatic read the lasting comment .
so try to use the speechSynthesisAPI.
I use `speechSynthesis.getVoices()` to get the voices i can use . 

### Expected behavior

I expect I will get at least 5 voives just like in chrome

![a1](https://user-images.githubusercontent.com/10257291/34643705-d6648036-f363-11e7-9b08-7e651a0b2832.jpg)

the top five is local service .

### Actual behavior

but when do this in electron , i only get a voices .

![a2](https://user-images.githubusercontent.com/10257291/34643734-51686fea-f364-11e7-9fc8-175deb13afd8.jpg)

### How to reproduce

run `speechSynthesis.getVoices()` in the console of the page

**Comment by guest271314** [comment]
Chromium does not provide voices by default.

**Comment by guest271314** [comment]
@shugen002 Chromium does not provide voices by default. See https://github.com/electron/electron/issues/586

**Comment by shugen002** [comment]
@guest271314 Yes，so in the picture of the behavior of chrome the voice begin with google i don;t urge it appear in the list of voice in electron. But the voice begin with Microsoft should appear in the list . 

These are the speech syntheis engine are installed in my system .

in fact my system have not only 5 engines , it should be 11 .

![a3](https://user-images.githubusercontent.com/10257291/34754543-6b931040-f5f9-11e7-9603-92a5d04c4aa6.jpg)

but consider of the system may have some limition , so i just hope it can appear 5 local installed engines.

**Comment by guest271314** [comment]
@shugen002 If gather what you are attempting to convey accurately, Chromium does not ship with voices by default.

**Comment by codebytere** [comment]
There's not really anything we can do to solve this ourselves, but you're more than welcome to file an upstream feature request on Chromium.

**Comment by robinwassen** [comment]
The listing of OS installed voices work as intended in Chromium 67, but not in Electron 1.7.9 (not tested later versions).

**OS:** Windows 10, both screen shots are from the same machine

**Electron 1.7.9:**
![electron_voice](https://user-images.githubusercontent.com/302151/37337612-24ba5100-26b5-11e8-9a36-6f4937887674.png)

**Chromium 67:**
![chromiumvoice](https://user-images.githubusercontent.com/302151/37337671-4c0c9df8-26b5-11e8-98a4-8033479d4ecc.png)

The cause of this issue is a work around in Chromium for an old closed bug: https://github.com/electron/electron/blob/c18afc924b7218555e529c0583773f58e1015cbe/chromium_src/chrome/browser/speech/tts_win.cc#L174

Looking at the latest version of the source code this has been fixed: https://github.com/chromium/chromium/blob/master/chrome/browser/speech/tts_win.cc#L191

I have not pinpointed which version of Chromium that resolved this bug yet.

**Comment by robinwassen** [comment]
@codebytere I think this problem might be on the Electron side anyway, see: https://chromium.googlesource.com/chromium/src.git/+/61.0.3163.100/chrome/browser/speech/tts_win.cc#191

It has been fixed in a version prior to Chromium 61.0.3163.100 (not pinpointed the exact version yet), which is the version the current Electron beta uses.

But in the Electron beta source there seems to be a vendored version of this file, which has the old work around returning "native" instead of the actual speech languages: https://github.com/electron/electron/blob/2-0-x/chromium_src/chrome/browser/speech/tts_win.cc#L174

**Comment by AlbrechtStriffler** [comment]
Can we reopen this issues, since it is not yet fixed in the current electron version, but is actually fixable now (see comments above)?

**Comment by Achuan-2** [comment]
This problem still exists. How can it be resolved?
