### ISSUE TITLE
Cannot access to oAuth websites

### ISSUE THREAD

**Issue by TheRolfFR** [electron/electron#11602]
Hello,

In my project i'm working with external websites requiring oAuth connection unfortunately oAuth logins are not allowed in "web-views" : 

> This user-agent is not permitted to make OAuth authorisation request to Google as it is classified as an embedded user-agent (also known as a web-view).

Is there any way to solve this problem ?
Thanks in advance

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
