### ISSUE TITLE
Problems with location.pathname on initial load

### ISSUE THREAD

**Issue by daviddelusenet** [electron/electron#11600]
* Electron version: 1.7.10
* Operating system: macOS High Sierra
* React version: 16.2.0
* React Router DOM version: 4.2.2

### Expected behavior
I'm using Electron in combination with React and React Router DOM. 

When I open my packaged application initially no route is matched. So I logged the `location.pathname` which should be `/` on the initial load. Instead I get the entire path of where my `index.html` is placed (`blabla/dist/mac/ds-video-wall.app/Contents/Resources/app.asar/dist/index.html`).

I fixed this (temporary) by added the following code:

```
componentDidMount() {
  // Electron 'bugfix', feels dirty
  if (this.props.location.pathname !== '/') {
    this.props.history.push('/');
  }
}
```
After this fix I can start using the navigation and everything works fine from there. Every time I change routes I log the `location.pathname` and it's always correct. So this problem only occurs on initial load. 

I don't like the solution I'm using now so I'm wondering how I can solve this problem in a different way?

This user is experiencing the same issue: https://discuss.atom.io/t/window-location-pathname-inconsistency/20318

**Comment by sofianguy** [comment]
@daviddelusenet Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by MarshallOfSound** [comment]
@daviddelusenet This isn't a bug on Electron's side rather expected behavior, when using `react-router` everything after the initial URL load is virtualized using `pushState` and `popstate` so it's internal representation of the path is `/`.  When you initially load an HTML file though it's `pathname` is actually the full path to the file.  I.e.

```js
const filePath = url.format({
  protocol: 'file:'
  slashes: true,
  pathname: 'path/to/my/file.html'
})
```

If you wish to achieve your expected behavior you will have to use the [`HashRouter`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/HashRouter.js) from `react-router-dom` which does everything virtualized from the beginning instead of relying on the initially loaded URL 👍

**Comment by daviddelusenet** [comment]
@MarshallOfSound I found this solution on Stack Overflow and that works indeed :) Thanks for the help!
