### ISSUE TITLE
Electron + RobotJS: A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by UttakarshTikku** [electron/electron#11648]
I am unable to build an app using electron and robotjs. Here is the stacktrace: 
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\<dirname>\node_modules\robotjs\build\Release\robotjs.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by MarshallOfSound** [comment]
Check out our native module guide

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by edelCustodio** [comment]
Hi @MarshallOfSound how can I use this https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#using-npm?

because I tried with this: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#installing-modules-and-rebuilding-for-electron I didn't get any error and when use npm rebuild I did't get any error either.

this is how I have my scripts on package.json

`"scripts": {
    "start": "electron . --enable-logging --remote-debugging-port=6969",
    "publish": "node_modules/.bin/build --win -p always",
    "rebuild": "node_modules/.bin/electron-rebuild.cmd --runtime=electron --target=1.7.9 --disturl=https://atom.io/download/atom-shell --abi=51"
  }`

other question, I want to debug my app, how I can handle that?
