### ISSUE TITLE
The BrowserWindow size is not  the same as the webContents size

### ISSUE THREAD

**Issue by JackieLs** [electron/electron#11641]
* Electron version: 1.7.0
* Operating system: Mac OS 10.13.2

### The BrowserWindow size should be same as the webContents size

But actually:
![image](https://user-images.githubusercontent.com/14228179/34933011-3a09a7b2-fa10-11e7-93fc-8d50bd163d66.png)
How could I fix this?Is this a bug?
```
function loadMainWindow (){
	global.MainWindow = new BrowserWindow({
		show: false,
	})
	global.MainWindow.loadURL(global._winURL)
	global.MainWindow.on('closed', () => {
		global.MainWindow = null
	})
	global.MainWindow.once('ready-to-show', ()=>{
		global.MainWindow.show()
		global.MainWindow.webContents.openDevTools()
	})
}
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by MarcoMatta** [comment]
Same issue!
