### ISSUE TITLE
MenuItem: View -> Actual Size/Zoom In/Zoom out [Crash]

### ISSUE THREAD

**Issue by hacker112** [electron/electron#11645]
* Electron version: 1.7.10
* Operating system: Mac OS X 10.11.6 (15G18013)

### Expected behavior

Should zoom in/out or reset zoom on web page.

### Actual behavior

Crashes electron, see crash dump:
[Electron-Crash.txt](https://github.com/electron/electron/files/1631965/Electron-Crash.txt)

### How to reproduce

Click on Developer Tools (attached to main window) and then click on one of the three menu alternatives and the Electron app will mostly crash.

**Comment by sethlu** [comment]
From my test, the issue doesn't seem to occur in the latest build (https://github.com/electron/electron/commit/a6d3dee32152581a37139414702ed4cba904fd9c) on macOS High Sierra 10.13.2 Beta (17C76a).

**Comment by nordenmark** [comment]
Also getting the same crash behaviour on macOS High Sierra 10.13.2 (17C88).

[crash-log-electron.log](https://github.com/electron/electron/files/1634120/crash-log-electron.log)

**Comment by codebytere** [comment]
We are sorry that we do not always have the capacity to look at all reported issues in a timely manner. There have been many changes in Electron since this issue was reported and it may have been fixed in that time.

The version of Electron this issue was reported on, `1.7.10`, has been superseded by newer releases -- the latest in series is `1.8.4`. It would help us greatly if you could test this issue with the latest version.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by hacker112** [comment]
@codebytere: I totally forgot about this bug. Some weeks ago I upgraded to version `1.8.2` and the bug seems to be gone. 👍
