### ISSUE TITLE
How to call JavaScript function of webview‘s target website?

### ISSUE THREAD

**Issue by huangxianyi** [electron/electron#11659]
* Electron version:1.4.14
* Operating system:Windows 7

I want to call JavaScript like Android's webview.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
