### ISSUE TITLE
geolocation didn't work - Network location provider at 'https://www.googleapis.com/' : Returned error code 400.

### ISSUE THREAD

**Issue by TobyMosque** [electron/electron#11669]
- Electron version: 1.8.2-beta.3 and 1.7.10
- Operating system: Windows

I'm building a new app using Quasar and Electron, however, I'm getting the follow error while trying to get the current geolocation.:

```
navigator.geolocation.getCurrentPosition(console.log, console.error)
PositionError {
  code: 2, 
  message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 400."
}
```

I already seted the google key, id and secret in the main.js

```
process.env.GOOGLE_API_KEY = 'my_api_key'
process.env.GOOGLE_DEFAULT_CLIENT_ID = 'my_google_id.apps.googleusercontent.com'
process.env.GOOGLE_DEFAULT_CLIENT_SECRET = 'my_google_secret'
```

I tried to call the API directly using the Restman, that worked like a charm.

```
curl -H "Content-Type: application/json" -X POST -d '{}' https://www.googleapis.com/geolocation/v1/geolocate?key=my_api_key
{
    "location": {
        "lat": -x.fffffff,
        "lng": -y.fffffff
    },
    "accuracy": fff
}
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by SayanBasani** [comment]
please tell me for  google geolocation api, it need to pay
