### ISSUE TITLE
submodule url for 'vendor/depot_tools' points to wrong revision from master

### ISSUE THREAD

**Issue by labriola** [electron/electron#11663]
* Electron version: master branch
* Operating system: windows

### Expected behavior
Following the directions on this page should allow me to update chromium:

https://github.com/electron/electron/blob/master/docs/development/upgrading-chromium.md

### Actual behavior

Error: 1> dependency url must be either a string, None, or From() instead of dict

It's a failure do to an incompatibility with the version of gclient referenced via the submodule.

### How to reproduce

Follow the direction on this page...
https://github.com/electron/electron/blob/master/docs/development/upgrading-chromium.md

You only need to go so far as the bootstrap to see this:

$ ./script/bootstrap -v
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/depot_tools'
Submodule path 'vendor/depot_tools': checked out 'c55eecf76bdb96b904aaaee93fe4c6  

If you update the submodule_url to the current master for vendor/depot tools, it moves past this error.

**Comment by codebytere** [comment]
Hi, so upgrading chromium is a lengthy process undertaken by maintainers. 

See 
https://github.com/electron/electron/projects/6 and 
https://github.com/electron/electron/projects/7 
for current work.

This isn't something that you do locally, and trying to check out  a new submodule ref will produce the errors you see above. If you're interested in helping with ongoing work in upgrading chromium, feel free to reach out and help with remaining tasks in chromium development. In the meantime, i'm going to go ahead and close this.

**Comment by ckerr** [comment]
Hi @labriola,

As @codebytere says, upgrading Chromium is pretty involved work -- Electron inherits extensively from classed in libchromiumcontent, so upgrading it usually results in needed code refactoring in Electron --
 so `upgrading-chromium.md` is currently more of a WIP addressed to the Maintainers group.

That said, it's always good to make things more accessible to potential contributors and if I would have expected someone coming into this cold to get to reach compilation errors due to the code shear mentioned above, rather than erroring out sooner in git. If you're following the instructions and not getting that far, maybe the instructions are at fault. Could you make a PR to correct the error in the documentation as you see it?

**Comment by labriola** [comment]
To be clear. There is no documentation change that can correct this error. Following the instructions will yield the following error:

Error: 1> dependency url must be either a string, None, or From() instead of dict

And this is due to a mismatch of the version of gclient in the depot_tools referenced by the submodule (c55eecf76bdb96b904aaaee93fe4c6) versus a version of gclient that can read the configuration dependencies as present in the project source. The referenced version of gclient does not appear to use a compatible version of the dependencies.

I completely understand that everyone is busy, however, the error can be replicated by the first step of the document I referenced. (https://github.com/electron/electron/blob/master/docs/development/upgrading-chromium.md)

If I change the submodule url as I indicated, I can move forward into applying patches. I understand the issue is closed. So be it. Was pointing out a significant barrier (step 1) toward anyone helping

Mike
