### ISSUE TITLE
Can we forward native DOM events to the appropriate Electron event handlers?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#11675]
When I add a handler for the `context-menu` event, I want to be able to figure out what element is being right-clicked on and create different context menus depending on the element. In vanilla JS, I could just add a `contextmenu` handler on the body and filter on `e.target`. In Electron, the event that's passed into the handler is an Electron-style event that only has `preventDefault` and `sender` properties:

```
mainWindow.webContents.on("context-menu", (e, props) => {
     e.target === undefined
});
```

Can we forward the native DOM event to the handler? Or how else can we workaround this? I guess we could add handlers to native DOM events (`contextmenu`) in the renderer process, filter on `e.target` in those handlers, and create the appropriate Electron context menu in which case the Electron `context-menu` handler above is redundant.

Electron: 1.7.9
OS: Win 10

**Comment by brenca** [comment]
I don't see any feasible way to pass the DOM events to the electron handlers, so a proper solution to your problem would be something like what you suggested - using the renderer process events. The electron `context-menu` event still has a lot of information in `props` that is otherwise unavailable on the renderer side, so it's - generally speaking - not redundant, although for your usecase it might be unnecessary. 

I'm going to treat this as a feature request, and close it as wontfix.
