### ISSUE TITLE
While Linking .Net Stanadard2.0 Class library DLL to Electron

### ISSUE THREAD

**Issue by Sreerajesh** [electron/electron#11686]
Hi Sir,
       While Linking .Net Standard 2.0 Class library DLL to Electron Code having some error display like dll file could not load but i am paste the dll file to same folder ,I am just Attach that Error Message So Please give an idea of that....

![electron](https://user-images.githubusercontent.com/35681777/35212208-16ce6814-ff1f-11e7-87aa-55e23e7228b8.JPG)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
