### ISSUE TITLE
win.setIgnoreMouseEvents(true, { forward: true }); mouse can't get mouseEvent

### ISSUE THREAD

**Issue by weicracker** [electron/electron#11693]
* Electron version: 1.7.X
* Operating system:win64

i use electron BrowserWindow API:
> win.setIgnoreMouseEvents(true, { forward: true }); 

but: 
mouse move messages can't send  to Chromium

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
