### ISSUE TITLE
security question

### ISSUE THREAD

**Issue by kylepwarren** [electron/electron#11719]
I've used a handful of these html/web to desktop app frameworks - I don't specifically remember if I used electron, or one of it's predecessors. Anyhow, It seemed like most of them run a slimmed down web server to handle requests / ajax / etc.  It almost seems like that helps make it so easy / similar to web development, however, my question: doesn't this create a giant security concern? Unless you have firewall settings in what most people would consider extreme mode, then anyone on your LAN could access your desktop-web-app by ip... Maybe I'm wrong, is there a protocol it uses besides http / or not network accessible?  thanks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
