### ISSUE TITLE
Get Current Window to component angular 4

### ISSUE THREAD

**Issue by Ascolon** [electron/electron#11718]
Can not import electron

```
import { remote, BrowserWindow } from 'electron';

export class AppComponent {
  CloseWindow() {
    remote.getCurrentWindow().close();
  }
}
```
I get an error
`Uncaught TypeError: fs.existsSync is not a function`

Occurs in the index.is file in the folder node_modules / electron

Help pls!!!!!

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
