### ISSUE TITLE
Excuse me, is there any way to inherit Microsoft's sucface dail in Electron?

### ISSUE THREAD

**Issue by yueleiMaster** [electron/electron#11714]
Now I use NodeRT for Electron to use the API of the win10SDK, but the initialization RadialController will report the error, the thread is wrong, and may not find the correct UI thread.Please help me.
![image](https://user-images.githubusercontent.com/25242674/35321874-36ded8e0-0123-11e8-84fc-5f9c862acea2.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so. 

It's also a bit unclear here if this is a bug or feature request, so it would be great if you could make that more clear.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment https://github.com/electron/electron/issues/11714#issuecomment-360145346. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
