### ISSUE TITLE
navigator.mediaDevices.enumerateDevices does not return a complete list of devices

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#11720]
* Electron version: tested 1.6.x, 1.7.x 1.8.x
* Operating system: Windows 10 (1709)

### Expected behavior

```
navigator.mediaDevices.enumerateDevices()
```
should return the same list of audio and video devices as what a Chrome browser (v63) does.

### Actual behavior

The actual audio device list obtained contains only a default input device, all other audio devices are missing.
There is no video input device (camera) listed.

### Question

Is there some kind of permission settings that I don't know which will allow the retrieving of the complete list or this is a bug in electron?

I know that current version of Windows 10 has a setting related to the camera and microphone that contains a white list of applications that are allowed to access them, but electron applications are not listed in there. Any resolution to this problem?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
