### ISSUE TITLE
Why dont use Node Js new version? 

### ISSUE THREAD

**Issue by gandalius** [electron/electron#11725]
* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.
