### ISSUE TITLE
Dock should be a nullable type.

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#11734]
I'm on the latest everything. I'm using strict nullchecks with typescript and I just tried booting my app on windows and it said "cant call setBadge of undefined". Apparently `app.dock` is undefined on windows so it would be nice if the type indicate that.

I cloned this repo and tried to find it and submit a PR but I was helpless. Should be an easy fix if you know where all the typescript types are. 👍

**Comment by codebytere** [comment]
hey @ccorcos, the underlying issue here is that typescript doesn't really let us have platform dependent types, so it's only going to be an object on mac. It's documented to only be available on MacOS, but since we can't express that with Typescript this is the best we can do. Perhaps sometime in the future we'll have a more robust way for the type to indicate that, but for now it's not possible.
