### ISSUE TITLE
A problem about the Electron API webContents.savePage

### ISSUE THREAD

**Issue by lake2** [electron/electron#11748]
when I use the code to save a page, it always save to "D://test/1.html". When I try to modify the '/test/1.html' to 'e://test/1.html', it will create a directory under disk E but without the html and the corresponding resources file. Here is the code.
	
    mainWindow.loadURL('http://movie.douban.com/');
    mainWindow.webContents.on('did-finish-load', () => {
        mainWindow.webContents.savePage('/test/1.html', 'HTMLComplete', (error) => {
            if (!error) console.log('Save page successfully');
            console.log(error);
        })
    });

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by lake2** [comment]
I cannot click the edit button, I close this issue.
