### ISSUE TITLE
Electron doesn't detect windows scaling x2 on XFCE 4.13

### ISSUE THREAD

**Issue by nkkollaw** [electron/electron#11746]
XFCE4 used to implement hidpi by adjusting the font zoom. Since version 4.13, however, there is an option called "window scaling" that you can set to x2 for hidpi screens.

Unfortunately, Electron doesn't seem to pick up this setting, and all Electron apps I'm running (Hyper, VS Code) look comically zoomed out.

How can I tell Electron that I'm running on a hidpi monitor, and to start zoomed at 2x?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nkkollaw** [comment]
Well, this is a bug, though (or at least a feature requests).

"Electron doesn't detect windows scaling x2 on XFCE 4.13"

**Comment by kyleperik** [comment]
This is also an issue for me.

As far as reproduction steps go for me, I'm using Budgie desktop environment, but it's closely knit with gnome's suite of tools and infrastructure. So running this command with any gnome or gnome based environment should work (including the latest version of ubuntu). 

```
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <factor>}]"
```

Then like nkkollaw said, any election application you use retains the same scaling as if you didn't set this option. I thought this was odd, because chrome honors this option.

**Comment by nkkollaw** [comment]
I've been launching apps adding these parameters:
    
     --high-dpi-support=1 --force-device-scale-factor=2

It works. For instance, from the terminal:

    /opt/whatsapp-electron/whatsapp  --high-dpi-support=1 --force-device-scale-factor=2

**Comment by nkkollaw** [comment]
@sofianguy: I think you should reopen the issue. This IS DEFINITELY A BUG, not at all a question like you said.

**Comment by lee-dohm** [comment]
@nkkollaw Whether or not it is considered a bug, this isn't something that the maintainer team intends to take on as a work item in the reasonably near term. This is especially true since there appears to be a simple enough workaround that you've documented here. If the situation changes, we will definitely reopen the issue in order to prioritize it alongside other work. We would be willing to consider a well-written pull request if one was offered.

Thank you for the feedback.

**Comment by nkkollaw** [comment]
Well, OK.

It just seems a trivial fix, and the effect of having apps open like that looks like the project is half-baked. Lots of people have hidpi monitors nowadays.
