### ISSUE TITLE
Electron binary fails to run on Windows after debug build (WinRT dependency?)

### ISSUE THREAD

**Issue by cortx7** [electron/electron#11759]
* Electron version: Pulled source from the repository on 01/27/18
* Operating system: Windows 7 x64

### How to reproduce

I'm successfully building Electron from source on a Windows 7 x64 machine (Visual Studio 2015). The build runs fine and it produces the expected binaries. However, when I run "electron.exe" I get

![image](https://user-images.githubusercontent.com/2941129/35477870-f2c3161e-03b4-11e8-8266-86f638ed7952.png)

Strangely, it seems to be looking for a WinRT dependency, which is very weird because it's a Windows 7 machine.
Note: I don't run into this problem when doing the same steps on Windows 10.

These were the commands I executed:

`script\bootstrap.py -v`
`script\build.py -c D`

**Comment by felixrieseberg** [comment]
Hey! Sorry to say that Electron right now requires Windows 10 to be built – I do realize though that our documentation says otherwise.

It's a bit unclear to me if we should treat this as a bug in the documentation or our build process. Team, what do you think?

**Comment by felixrieseberg** [comment]
@cortx7 We talked about in the team and have for now decided that this is a bug in the documentation, not the build process. Here's what's happening: Electron has gained the ability to send you native notifications on Windows 10. As you know, we fully support running on Windows 7, but in order to build the Electron that has those Windows 10 features, we need to build it on a machine with the Windows 10 SDK.

Here's the crux: The [Windows 10 tools are only available for Windows 10](https://developer.microsoft.com/en-us/windows/downloads). That’s understandable though: When Windows 7 was released, Apple just announced their new iPhone 3GS _with a whopping 256MB of memory!_ The compass was a default app! iOS 3 was the hotness! Here was the headline feature: The SMS app started having support for MMS.

If you feel like the iPhone 3GS is somewhat ancient technology, you’ll understand why spending a great amount of time on building on Windows 7 seems less important than our other bugs.|

Electron built on Windows 10 runs just fine on Windows 7. If you are troubled finding a Windows 10 machine, know that Microsoft offers free VMs with Windows 10 pre-installed: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by ckerr** [comment]
@felixrieseberg I think you're right about this being a documentation bug.

**Comment by bughit** [comment]
> Electron right now requires Windows 10 to be built

This issue is not about building, but running the debug build. But lest focus on the above assertion for a moment. The windows 10 sdk is available on win7 and debug electron builds fine on win7. So why are you claiming win10 is required for building?

Are you suggesting that a debug electron built on win10 would not have this problem when run on win7?  I doubt it. It would still link to these dlls and still fail to find them on win7.

So are you actually trying to say is that running (as opposed to building) of the debug electron on win7 is not supported? But even that is not true.

The missing dlls:

- `api-ms-win-core-winrt-string-l1-1-0.dll`
- `api-ms-win-core-winrt-l1-1-0.dll`

are available in the [Microsoft.NETCore.Windows.ApiSets](https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/) nuget package

Here's the [direct link for win7](https://www.nuget.org/api/v2/package/runtime.win7-x64.Microsoft.NETCore.Windows.ApiSets/1.0.1) from which they can be extracted.

The proper fix to this issue, is not falsely documenting that electron can't be built on win7, but to:

- either not link with these dlls (as the release build presumably does not since they are not part of the distribution)
- or include them from Microsoft.NETCore.Windows.ApiSets

**Comment by miniak** [comment]
Please re-open if you can reproduce this issue with Electron >= 4. We are now linking the CRT statically and those API set DLLs should not be required anymore.

**Comment by miniak** [comment]
There is no more debug build, just testing. We are also linking the CRT statically now.
