### ISSUE TITLE
Is anyone need electron  windows xp version

### ISSUE THREAD

**Issue by thinkanyforever** [electron/electron#11760]
I have create a electron test version for windows xp based on v1.0.
I use nw.js for 15% windows xp users two years ago, but now it's possible for electron.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

Issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by thinkanyforever** [comment]
It's still lots of works to do, if you need it, please add issue to [https://github.com/thinkanyforever/electron-xp](https://github.com/thinkanyforever/electron-xp)

**Comment by thinkanyforever** [comment]
@MarshallOfSound sorry, please do not care, it's not a bug report.

**Comment by kerbymart** [comment]
@thinkanyforever where can we find the `electron-xp` the Github link does not contain anything?

**Comment by jetiny** [comment]
the windows xp version https://github.com/jetiny/electron-xp

**Comment by alainazpe** [comment]
need xp version please, no way to found it in the web :(

**Comment by gdl-888** [comment]
no archives of electron-xp?
