### ISSUE TITLE
'npm run lint' skips obj-c files

### ISSUE THREAD

**Issue by BoOpenfin** [electron/electron#11772]
* Electron version: All
* Operating system: All

### Expected behavior
Objective C file should also be processed by an automated checker.
Almost every .mm file has the style issues like [longer than 80 characters](https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L195), or [wired number of spaces at line-start](https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L202).

### Actual behavior
When run cpplint to check code styles, the ObjectiveC file(.mm) is ignored.

**Comment by ckerr** [comment]
The cpplint that Electron is using comes from Google and is for C++ files only, so including Obj-C there results in 

`Ignoring brightray/common/mac/main_application_bundle.mm; not a valid file name (cc, h, cpp, cu, cuh)`

We may want to investigate finding a similar tool for Obj-C

**Comment by ckerr** [comment]
["oclint"](http://oclint.org/) looks like the most commonly-used tool for this.

It also appears to inspect C++ and do some checks that our current linter doesn't, so using it in addition to our cpplint script might be another minor win.

It ships in binary form, apparently only for macOS and Linux, so we might want to do something like including an `oclint-linux64` and `oclint-mac` in our `vendor/depot_tools` in order to make this possible on those platforms

**Comment by BoOpenfin** [comment]
Cool, that would be awesome!
