### ISSUE TITLE
html5-tag video. Resets the video to the beginning when rewinding.

### ISSUE THREAD

**Issue by Ascolon** [electron/electron#11805]
hi. When using html5 video, I encountered such a problem that when I rewind the video. it is reset to the beginning and does not want to reproduce at all.
Someone has come across this and knows how to solve this problem.
In playback in the browser everything works fine

here is a piece of code.
I use angular.js version 1.6
```
<div class="row">
    <div class="current-film-video">
        <video poster="data/poster.jpg" controls preload="auto" class="video">
            <source src="{{film.Video}}">
        </video>
    </div>
    <div class="comments">
        <h2>Hello</h2>
    </div>
</div>
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by DomBugi** [comment]
No worries ;)

Just because I am looking doesn't mean at all I am lost ;)

An Environment at this proffesional level is something I am absolutely more than used to...

Startups are amazing in many ways, always, and upgrade from semi amateur cause driven society to fully functioning top-of the line corporate elite brings more challenges than anyone ever thinks...

i like Your style Guys, I feel in the bqckground thar lil big future question mark what now is not a good time to speak about, BUT You will be among the best, for sure.


Good night,

Dom
