### ISSUE TITLE
Specific Instance Event Issue!

### ISSUE THREAD

**Issue by dcflow** [electron/electron#11820]
Hello,

I think there is an issue with the `did-get-redirect-request` event instance.

* Electron version: 1.7.12
* Operating system: Windows 10

### Expected behavior
When you send messages from the main process inside an event listener 
like `will-navigate` the message is sent successfully.
```
mainWindow.webContents.on('will-navigate', () => {
    mainWindow.webContents.send('data')
})
```

### Actual behavior
When you try to send messages from the main process inside the `did-get-redirect-request`
event listener the message doesn't go through.
```
mainWindow.webContents.on('did-get-redirect-request', (a, b, c) => {
    mainWindow.webContents.send('data')
})
```

I have tried this scenario with many event instances and it seems that
only `did-get-redirect-request` is having the issue.

Thank You!

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on, 1.7.2, has been superseded by newer releases -- the latest in that series is 1.7.12. In addition, there are newer branches that supersede that series. It would help us greatly if you could test this issue with the latest version.

I'm setting the `more-information-needed` label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by dcflow** [comment]
Hey @ckerr ,

Thank you for your response.
Sorry about the version number, it was a typo. 
I am using the latest version `1.7.12`.
I also tested the beta version `1.8.2-beta.5` but still no luck.

Thank You!

**Comment by ckerr** [comment]
Thanks for the information! I've updated the issue's labels to show it affects both 1.7 and 1.8.

**Comment by MarshallOfSound** [comment]
@dcflow This is expected behavior, during the `did-get-redirect-request` event there is actually no renderer process ready (it is in a state of navigation) so when you send an IPC message to it your listener in JS land hasn't been set up yet.  To better explain this so that someone might be able to document this scenario.  Please not I am just using Google sign in as an example here 😄 

1. You load `http://www.google.com` in a `BrowserWindow`
1. Your JS runs and you start listening to IPC events
1. You try to log in to Google
1. The renderer starts a redirect through Google's sign in flow
1. The renderer process is unloaded, including your IPC event handlers in JS land
1. You get a `did-get-redirect-request` event in the main process
1. You try to send an IPC message immediately
1. Maybe a few hundred milliseconds later the next page starts loading
1. Your preload script is run and new IPC event hooks are added by your JS

Does it make sense now how your IPC message kind of "disappeared"?  Basically you need to ensure that your hook is ready on the renderer side before you send the message, or you will be firing messages into the void 👍 As a very old example (wrote this 2 years ago) here is how I managed this race problem [code](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/utils/Emitter.js#L23)

**Comment by codebytere** [comment]
Closing as @MarshallOfSound has provided more context and resolution for this issue.

**Comment by ckerr** [comment]
@MarshallOfSound excellent writeup, there :1st_place_medal:

**Comment by dcflow** [comment]
@MarshallOfSound Thank you for your thorough explanation. 
You are so right, checking the `state` of the renderer process is the first thing to do.

What tricked me into not checking this was the time gap (about 3 sec) between the 
call to send the `IPC message` and the actual `navigation` to the other page.
It turns out, as you said, the renderer process was `unloaded` even though the UI
remained unchanged.

As for the documentation, since there is more useful info for a project on its GitHub
issues than there is at StackOverflow, maybe adding a separate doc (not the FAQ) 
with distilled issues and solutions could be helpful for new comers. 
What do you think @codebytere?
