### ISSUE TITLE
Position of Chrome command-line switches changes application behavior

### ISSUE THREAD

**Issue by KevinEady** [electron/electron#11839]
* Electron version: 1.7.12
* Operating system: Windows 10

### Expected behavior

Chrome command-line switches are properly passed to the application. 

### Actual behavior

Application doesn't start depending on chrome switch location. This behavior was modified in 1.7.11, as it works properly in 1.7.10.

### How to reproduce

1. git clone https://github.com/KevinEady/electron-quick-start 
2. npm install
3. npm run-script build

4. Failure: `.\electron-quick-start-win32-ia32\electron-quick-start.exe http://www.google.com --inspect=1234`
5. Success: `.\electron-quick-start-win32-ia32\electron-quick-start.exe www.google.com --inspect=1234`
6. Success: `.\electron-quick-start-win32-ia32\electron-quick-start.exe --inspect=1234 http://www.google.com`

7. Modify `package.json` to use `"electron": "1.7.10"`, and re-run steps 2-4. You will see the application starts properly.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

You are correct, this behavior was changed in v1.7.11 as part of the fix for the [Protocol Handler Vulnerability](https://electronjs.org/blog/protocol-handler-fix). Because of this Electron will, for the most part, expect options to appear on the command line before positional arguments, like test case 6 in your examples. Because of the severity of the vulnerability in previous versions, we aren't going to be changing the default behavior back to be more flexible.

You may be able to implement your own command-line option parsing and handle exactly what gets passed to the Chrome engine using [the `app.commandLine.appendSwitch` function](https://electronjs.org/docs/all#supported-chrome-command-line-switches). At that point, the parsing of the command line would be completely up to your program.

I hope that helps!

**Comment by KevinEady** [comment]
Hi @lee-dohm ,

Thanks for your response! Yes, my application currently does exactly what you are suggesting: it loops through `process.argv` and appropriately calls `app.commandLine.appendSwitch` to add it to the Chrome switches.

However, the application doesn't even _start_ for me to process the arguments (in example test case 4 above). So, I was hoping there was a way that I could tell Electron to _completely bypass_ the arguments as Chrome switches, and _only_ send them as `process.argv`? If not, does this mean that every electron app can have Chrome switches passed to them? For example, when I pass the `--inspect` switch to my bundled application, it does the internal Chrome inspect activity... what if my application has some functionality with an `--inspect` switch, but I _do not_ want to whatever Chrome does with an `--inspect` switch passed?

I hope I'm explaining this properly.

**Comment by KevinEady** [comment]
I guess a better, concrete example is the `--proxy-server` switch. What if I don't want Chrome to actually use a proxy server, but my application has a configuration parameter called `--proxy-server`?

So, if i were to do something like this: `player.exe http://website.com --my-application-switch --proxy-server="..."` , my application completely fails to start, just because my application and Chrome share a switch name.

**Comment by groundwater** [comment]
Hi @KevinEady. Unfortunately this implementation will remain for 1.8.x and 2.0.x lines. Most of us disliked having to break CLI parsing for these specific cases, but it was the least invasive change to mitigate the original issue.

We would consider breaking changes for 3.0.x which won't be as long as 1.x -> 2.x because we now tie major version increments to chromium upgrades.

I think ideally we want folks to have any and all CLI arguments available for their app, without worrying about which might also be Chromium arguments.

Until then, I would suggest always ensuring your CLI options occur before any URL arguments.

> So, I was hoping there was a way that I could tell Electron to completely bypass the arguments as Chrome switches, and only send them as process.argv? 

In short, yes, these are the types of changes we're hoping to introduce as a longer-term fix.

**Comment by greggman** [comment]
You closed this issue but is there an issue tracking the feature of adding some delimiter or something to distinguish electron/chrome arguments from app arguments? I'm running into similar issue where my argument clashes with electron's. I had hoped maybe separating by "--" would work like it does in many apps but that doesn't help. Of course I can rename my argument but I have no reason to believe the next version of chrome/electron won't use my name so ideally I could pass some switch beyond which the arguments would be passed directly to my app and not parsed by electron
