### ISSUE TITLE
Can't request localhost:631 for mas

### ISSUE THREAD

**Issue by XRenSiu** [electron/electron#11872]
Electron app (for mac app store) can't connect localhost:631

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

You can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.
