### ISSUE TITLE
WebGL contextrestored event does not fire after GPU process respawn

### ISSUE THREAD

**Issue by anzorb** [electron/electron#11934]
* Electron version: 1.7.12
* Operating system: OSX 10.12.6

### Expected behavior

Ideally, once the GPU process crashes and is re-spawned, we should get a WebGL "contextrestored" event, which will cause the app/THREE.js to reload 3D resources without having to reload the page. Developers can listen for this event and re-instantiate their app too.

### Actual behavior

WebGL will no longer work until I quit/relaunch app. Reloading WebContents doesn't work either - shows WebGL is not supported.

### How to reproduce

1. Clone, setup repo
  $ git clone git@github.com:anzorb/electron-gpu-webgl-respawn.git
  $ npm install
  $ npm start

2.You should see a THREE.js example
3. In Activity monitor, kill GPU process (typically Electron Helper with fewer threads and idle wakes)
4. You should see "GPU process killed" in Terminal
5. DevTools console will show: 
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
three.js:21392 THREE.WebGLRenderer: Context Lost.
6. GPU process gets respawned, but no 'contextrestored' event is fired
7. Reloading the page displays "Your graphics card does not support WebGL"
The only way to get WebGL to load again is by quitting and relaunching

More on [context-restored event](https://www.khronos.org/registry/webgl/specs/1.0/#fire-a-webgl-context-event).

Edit: In Chrome, killing the GPU process shows the "Rats! WebGL hit a snag" and the only way to come back is by hitting the reload button to the right.

**Comment by lambone** [comment]
I have the same issue.

**Comment by brenca** [comment]
The default behavior that we inherit from chromium is to block the domain of the page that caused a GPU crash, that's why you won't get the contextrestored event. You can unlock this limitation, but even then after 3 GPU crashes chromium would switch to software compositing - luckily you can also disable this, so you can crash the GPU process repeatedly, and it would recover. The lines you need to add to your project are:
```
app.commandLine.appendSwitch('--disable-gpu-process-crash-limit')
app.disableDomainBlockingFor3DAPIs()
```

I tested running your example with these lines added, and it seems to recover properly this way (well, the three.js example that's opened by default loses the colors, but that seems to be a bug in the example, since the other examples fully recover).

**Comment by anzorb** [comment]
@brenca amazing, thank you!

**Comment by lambone** [comment]
@brenca thanks very much!
