### ISSUE TITLE
Error on "npm start"

### ISSUE THREAD

**Issue by saber-dev** [electron/electron#11943]
Hello,
I cloned "electron-quick-start" in my docker container with node 8 image,   I installed electron in devdep with "npm i --save-dev electron".
When I throw "npm start" I have this error message which displays.

```
> electron-quick-start@1.0.0 start /home/test/Test/Lab
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-18T13_12_14_707Z-debug.log
```

I'm blocked at this stage.
Thanks for your help

* Electron version: 1.7.8

**Comment by MarshallOfSound** [comment]
Electron is a GUI application, in order to run a GUI app headless inside a docker container you need to have a virtual frame buffer.  Something like `xvfb` will do the trick.  Check out this docker entry point for more ideas 👍 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/vendor/docker-entrypoint.sh

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
