### ISSUE TITLE
A confusing "Electron Security Warning" in Electron v1.8.2

### ISSUE THREAD

**Issue by AlexSHoffman** [electron/electron#12049]
Electron v1.8.2 shows a security warning that makes you think there's a serious security problem in your project and do not provide any details which makes the warning useless and more importantly confusing.

* Electron version: 1.8.2
* Operating system: Win10

### Actual behavior

Some people got confused by the following Electron Warning:

> Electron Security Warning This renderer process has Node.js integration enabled and attempted to load remote content. This exposes users of this app to severe security risks.

You can see it in the console as soon as you create and run a new Electron-Vue project.

Does Electron thinks that Webpack's `localhost` is attempting to download some remote content? What content? What attempt? How does that warning help anybody? 

### How to reproduce

- Create a new [Electron-Vue](https://github.com/SimulatedGREG/electron-vue) project
- `yarn run dev` (or `npm run dev`)
- See the console

**Comment by qazbnm456** [comment]
@AlexSHoffman Well, I think there's a misunderstanding in the original [thread](https://github.com/SimulatedGREG/electron-vue/issues/540). Sorry about that. 😕

These security warnings are actually forcing developers to pay more attention to https://github.com/electron/electron/blob/master/docs/tutorial/security.md, and they will only show up when you're under development mode (since the default binary name will be **electron**). You can find the reference [here](https://github.com/electron/electron/pull/11810).

There's no way to disable this feature in 1.8.2 in development mode though, you can switch them on and off in 2.0 series by setting `ELECTRON_ENABLE_SECURITY_WARNINGS` or `ELECTRON_DISABLE_SECURITY_WARNINGS` on either `process.env` or the `window` object.

**Comment by AlexSHoffman** [comment]
@qazbnm456 thanks for clarification, I edited the issue, the problem is still valid. The Electron Warning says Node is attempting to load remote content, that is not helpful to anybody. It made at least 7 people confused already (based on the feedback related to this issue on stackoverflow and Github)

**Comment by ckerr** [comment]
@felixrieseberg, any thoughts on this?

**Comment by felixrieseberg** [comment]
I do have thoughts! @AlexSHoffman The core issue is that too many developers, especially newcomers to Electron, assume that using `http://` with `nodeIntegration` enabled is okay. It's not - the warning is correct, that's a fairly severe security risk. 

From Electron 2.0 on, those warnings will link to the security document with more context (and also explain that the warning will not show up in production mode). It'll explain the cause for the warning, that ignoring it is acceptable in some cases (this would be one), and instructions on how to disable it.

It appears your core gripe here is the lack of context, which Electron 2.0 should fix with the inclusion of the link.

**Comment by AlexSHoffman** [comment]
@felixrieseberg thanks for clarifying it. 
It would be nice if the warning pointed to the exact file and line of code in the project. Right now the only `http://` VScode could find in this boilerplate is  `http://localhost:9080` in `src/main.index.js`. Is that why Electron throws this error? Or is it ignores all the `localhost` URLs ?

**Comment by IceApriler** [comment]
I have encountered similar problems, but our problems are different. I took a screenshot and the problem is shown in the package from. Can you help me?

![image](https://user-images.githubusercontent.com/29689307/43769039-66c9db0e-9a6b-11e8-85ae-3a1adc104ae8.png)

![image](https://user-images.githubusercontent.com/29689307/43769073-7c10a358-9a6b-11e8-9b6c-7dedcf87824d.png)

**Comment by ckerr** [comment]
I like the idea of including the offending URL with the warning. That should make it easier for developers to determine if it's a false positive, and if there is an issue, where in the codebase it is.

**Comment by IceApriler** [comment]
When my electron service was turned on for a long time, I found that my app had problems, and then I could not solve the problem by restarting the project. In the end, I can only restart the computer, so I will have no problem afterwards. This situation has appeared several times. Do you know why?
As shown below, I can't enter the app.
![image](https://user-images.githubusercontent.com/29689307/43769039-66c9db0e-9a6b-11e8-85ae-3a1adc104ae8.png)

**Comment by ckerr** [comment]
@IceApriler that appears to be something different -- open a new issue so that it can be discussed separately.

I'm closing this ticket now as the revised warning should resolve the original problem of the error message being confusing.

**Comment by newdarma** [comment]
This is a very stupid conf for Electron, for new users, this is extremely frustrating, security im my problem, no Electron problem, pls Stupid Electron Team, solve this.
