### ISSUE TITLE
Specifying proxyurl while using net requests

### ISSUE THREAD

**Issue by mm739521** [electron/electron#12071]
This might be a weird request because the net.requests already find the proxy if there is one, but is there a way to set the proxyurl prior to sending the request?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
