### ISSUE TITLE
Some error with requirejs(v2.1.15) and webview

### ISSUE THREAD

**Issue by Veiintc** [electron/electron#12090]
* Electron version: V1.8.2
* Operating system: win10

### Expected behavior
When I use webview to access the site, the target site has requirejs(v2.1.15),
When I type require([' /dd ']) in the devtool of webview, the electron app should do nothing.

### Actual behavior

When I type require([' /dd ']) in the devtool of webview, the electron app will pop up a dialog,
And I don't want that,
### How to reproduce
I had tried
Window. Noderequire = window. The require
Window. The require = null
But it doesn't work.

My English is not very good. If you can't understand it, please forgive me.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by Veiintc** [comment]
@sofianguy But this kind of webview can affect electron's problem, which I think is quite serious.
