### ISSUE TITLE
Electron installed globally and Visual Studio Code

### ISSUE THREAD

**Issue by genifycom** [electron/electron#12111]
So if you install electron globally on Windows 10.
npm install -g electron
The you will not find Electron in the .bin directory of the global location
When you install locally
npm install electron
you will find both electron and electron.cmd in the .bin directory.

The consequence of this is that when electron is installed globally, you cannot use Visual Studio Code to debug your electron app since debug requires the electron.cmd file to launch.

Is this working as intended? It is a nuisance to have to install electron in all apps just to enable debugging, so is there a way to just either set up the .bin items globally, or just get the .bin items locally?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
