### ISSUE TITLE
electron startDrag target OS path (Native File Drag & Drop)

### ISSUE THREAD

**Issue by mafar** [electron/electron#12144]
I have been playing around with the file system drag and drop functionality of Electron apps.

**What I want:**

 1. I need to know , if I drag a div out of electron app into OS , 
I just want to know target Os path.
 2. I am not interested in copying file operation to that path as i have my custom logic 

**Similar Solutions:**
I know about these solutions but I am not interested in as my goal is know target OS path. All these issues address drag and drop files out of electron app into OS .

 1. https://stackoverflow.com/questions/43209509/is-it-possible-to-drag-a-remote-file-out-of-electron-app-onto-the-file-system
 1. https://electronjs.org/docs/tutorial/native-file-drag-drop

I posted here as well.
https://stackoverflow.com/questions/49134283/electron-startdrag-target-os-path

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
