### ISSUE TITLE
webview.inspectElement(x,y) will call the devtools.How can I hide the devtools?

### ISSUE THREAD

**Issue by Mycaptain95** [electron/electron#12165]
I need to highlight HTML elements,but I want hide the devtools.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
