### ISSUE TITLE
LocalStorage doesn't persist in 2.x

### ISSUE THREAD

**Issue by duizabojul** [electron/electron#12175]
Since i upgraded electron from 1.8.2 to 2.0.0 beta 2, I have a weird behavior with firebase authentification : when i signOut with the firebase SDK, the signOut is effective (user is removed from localstorage, onAuthStateChanged is triggered with a null user, my app goes on login screen automatically), but when i reload the page the old user is found (onAuthStateChanged is triggered with oldUser and my app automatically load the user)...

It happens only on electron 2.0.0 beta 2, its ok on old versions of electron and on all browsers.

The repro should be pretty simple if you have a firebase project running on electron, just signout from firebase, refresh the page after signout and look if the user is still connected after the refresh.

**Comment by duizabojul** [comment]
Ok I had to clear all site data in devtools to eliminate that bug. I always don't understand why it happened btw... Like if some data was cached elsewhere and not cleaned with signOut function from firebase.

**Comment by deepak1556** [comment]
@duizabojul are you still facing the issue with 2.0 beta ? If so, can you provide a minimal example. Thanks!

**Comment by bpasero** [comment]
After some testing in VS Code we have learned that Chrome since version 61 seems to migrate local storage off SQLite into LevelDB on startup (https://bugs.chromium.org/p/chromium/issues/detail?id=225934 & https://bugs.chromium.org/p/chromium/issues/detail?id=586194).

For one user this migration was failing and it resulted in NO local storage getting persisted at all between restarts.

Checking for related Chrome issues I have found this one that could have an impact: https://bugs.chromium.org/p/chromium/issues/detail?id=765524

This fix (and any other if any) likely need to be backported before we can make the move to 2.0.x because we rely heavily on local storage for UI state persistence.

**Comment by alexeykuzmin** [comment]
According to https://crbug.com/765524 backporting [e8fdb3d5](https://chromium.googlesource.com/chromium/src/+/e8fdb3d52ab59c69baabcda544690100a2a136ea) should  fix the problem.
Review on: https://chromium-review.googlesource.com/678250

**Comment by deepak1556** [comment]
Fixed in https://github.com/electron/libchromiumcontent/pull/476

**Comment by grantcv1** [comment]
I think this problem is back with Electron 5.0.0

**Comment by jpolstre** [comment]
also not persistent in v8.2.0, I had to go back to v8.1.1
