### ISSUE TITLE
node-pre-gyp pulls iojs sources

### ISSUE THREAD

**Issue by pronebird** [electron/electron#12199]
* Electron version: 1.8.3
* Operating system: Travis/macOS

Hi,

trying to build a native module straight for electron based on the docs https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

However get some random stuff going on. My logs mention that electron downloaded this thing `/Users/travis/.electron-gyp/.node-gyp/iojs-1.8.3`. Surprisingly even tests pass.

Am I tripping or what's this blast from the past doing here?

My install script for Travis:

```
install:
  - export npm_config_target=1.8.3
  - export npm_config_arch=x64
  - export npm_config_target_arch=x64
  - export npm_config_disturl=https://atom.io/download/electron
  - export npm_config_runtime=electron
  - export npm_config_build_from_source=true
  - HOME=~/.electron-gyp npm install
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by pronebird** [comment]
So you are positive that’s not a bug?

**Comment by MarshallOfSound** [comment]
@pronebird It is not a bug
