### ISSUE TITLE
true images do not render on sidebar in spectacle editor

### ISSUE THREAD

**Issue by alongalor** [electron/electron#12206]
![image](https://user-images.githubusercontent.com/14210367/37236365-b19c5a52-23d4-11e8-8e97-105cb69af1ac.png)

* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

Issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.
