### ISSUE TITLE
String obfuscation

### ISSUE THREAD

**Issue by pjebs** [electron/electron#12220]
I am making an electron app and using ASAR to protect the source code.

However I need to obfuscate some sensitive authentication strings and an api endpoint.
Can I assume ASAR is adequate. It seems like the generated file is easily searched for embedded strings.

I'm ideally looking for something like this: https://github.com/pjebs/Obfuscator-iOS

**Comment by ckerr** [comment]
@pjebs Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by rocketlaunchr-cto** [comment]
If you do want to hide your secrets such as:

- OAuth credentials
- URLs not intended to be known to the public (i.e. private backend API endpoints)
- REST API credentials
- Any Keys and Secrets
- Passwords

I've created a FREE service to address this issue. I had to make it because I was making a commercial electron app and was worried about having my credentials stolen.

It works by creating a cross-platform helper application which launches your **actual** electron application IFF your application has not been tampered with. Once it launches the application, it will pass your credentials through the environment variables.

More information:

**Introduction:**
https://medium.com/@rocketlaunchr.cloud/introducing-electron-vault-d09ade2c2020

**Documentation:**
https://rocketlaunchr.github.io/electron-vault-docs/

**Comment by groundwater** [comment]
Hi @rocketlaunchr-cto.

This issue tracker is used for development of Electron, and we believe advertising for electron related services is better suited for community support places like [the Electron discuss](https://discuss.atom.io/c/electron), [StackOverflow](https://stackoverflow.com/questions/tagged/electron), or the [Atom.io Slack](https://discuss.atom.io/t/join-us-on-slack/16638) when appropriate.
