### ISSUE TITLE
Can't start electron

### ISSUE THREAD

**Issue by programmer5000-com** [electron/electron#12231]
* Electron version: (latest from npm)
* Operating system: Windows 10

### Expected behavior

An example electron app shows.

### Actual behavior

NPM complains and no window is opened.

### How to reproduce

Follow the startup instructions from the README.

```batch
C:\Users\programmer5000\Desktop>git clone https://github.com/electron/electron-quick-start
Cloning into 'electron-quick-start'...
remote: Counting objects: 270, done.
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 270R
Receiving objects: 100% (270/270), 45.61 KiB | 399.00 KiB/s, done.
Resolving deltas: 100% (124/124), done.

C:\Users\programmer5000\Desktop>cd electron-quick-start

C:\Users\programmer5000\Desktop\electron-quick-start>npm install

> electron@1.8.3 postinstall C:\Users\programmer5000\Desktop\electron-quick-start\node_modules\electron
> node install.js

npm start
npm notice created a lockfile as package-lock.json. You should commit this file.
added 153 packages from 118 contributors in 60.974s

C:\Users\programmer5000\Desktop\electron-quick-start>npm start

> electron-quick-start@1.0.0 start C:\Users\programmer5000\Desktop\electron-quick-start
> electron .

/bin/bash: electron: command not found
npm ERR! file bash
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\programmer5000\AppData\Roaming\npm-cache\_logs\2018-03-12T20_43_24_186Z-debug.log
```

What should I do?

**Comment by ckerr** [comment]
It looks like an error with npm not getting electron.

You may want to check `C:\Users\programmer5000\AppData\Roaming\npm-cache\_logs\2018-03-12T20_43_24_186Z-debug.log` for error messages and see if that's helpful.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
