### ISSUE TITLE
Place window above separated displays spaces

### ISSUE THREAD

**Issue by feronetick** [electron/electron#12248]
* Electron version: 1.7.9
* Operating system: macOS High Sierra 10.13.3

### Expected behavior

I'm playing with an electron my first time and I want to create an overlay on top of both monitors. Like a clarify screenshoter, for example

### Actual behavior

With enabled "Displays have separate spaces" in mission control settings, window always remains within only one of displays.

### How to reproduce

I tried to set "enableLargerThanScreen" and `window.setAlwaysOnTop(true, 'screen-saver', 1)` with `window.setVisibleOnAllWorkspaces(true)` with bounds that exceeding the display. Did not help.

### Questin

Is it real? If so, how?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
