### ISSUE TITLE
webRequest.onBeforeRequest() can't use "file://..." as redirectUrl

### ISSUE THREAD

**Issue by Pingze-github** [electron/electron#12242]
@:
Windows 7
Electron v1.8.3 x64

I hope to use webRequest to block an request and return a certain file to the window. So I use webRequest.onBeforeRequest(). 
It works, but:
 `webRequest.onBeforeRequest([filter, ]listener)`'s param `listener` is a function, and it's second param `callback` is a fucntion too. I use `callback({cancel: false, redirectUrl: 'file:///C:/a.js'})`, but it not work. I can see an error in devtools means connection failed.
I have to create a http server to give the file in format `http://...`.

I'm sure I'm using file:// in a right way.
file:// should be useful here, isn't it?

**Comment by arjndr** [comment]
What is the error you see in DevTools? It would be helpful if you post it here
I'm not sure you can return a certain file to the window with the `file://` protocol
Any pros that can back me up on this?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by pepijndevos** [comment]
This does not appear to be a question? It reports a bug that redirecting fails when the protocol is `file:`.
