### ISSUE TITLE
Display image from appData directory?

### ISSUE THREAD

**Issue by kinoli** [electron/electron#12277]
I have uploaded an image into the users appData directory (this.$electron.remote.app.getPath('appData')). 

I need to be able to display that image in an <img> tag or background-image style setting.

When I do a 'file://' + fileLocation, I get an error "Not allowed to load local resource".

Do I need to base64 it to show it? Is there a library out there that might do this?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by kinoli** [comment]
No problem. I found out how to do it. You convert to Base64.

```
const fs = require('fs')
const file = fs.readFileSync(fileLocation, 'base64')
return 'data:image/jpg;base64,' + file
```

put that response into an img src parameter or background-image style setting.

**Comment by aftabnaveed** [comment]
@kinoli  your solution works but is not great for Large file sizes.  The alternate solution is to keep the paths relative and it should work. Electron does not like to include files from different domains in this case file:/// is your local protocol and I guess your index.html is being served from a host or something.
