### ISSUE TITLE
Window z-order move to top without focus

### ISSUE THREAD

**Issue by MadfishDT** [electron/electron#12296]
* Electron version: 2.0.x
* Operating system: window 7, 10, mac  osx

### Expected behavior
renderer window z-order change to top but not change focus
if someone write somthing like writing email or play game, if renderer move top z-order with focus, this action interupt user 
some popup or message window do not need focus, they just show ui on top screen position

### Actual behavior
renderer move top screen position without focus

### How to reproduce

<!-- 

Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork https://github.com/electron/electron-quick-start and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.

branch "set-window-top-position"
on going...

**Comment by alexeykuzmin** [comment]
@MadfishDT Does it work the same way in Electron 1.8.4?

**Comment by KiranNiranjan** [comment]
- Electron version: 1.8.4
- Operating system: Window 10

**Note: This api `showInactive()` works perfectly on Mac OS** 

## Expected behaviour

![showinactiveworkaround](https://user-images.githubusercontent.com/13243259/38291009-759a8d04-37fb-11e8-8d02-e74ef568d541.gif)

## Actual behaviour
![showinactive](https://user-images.githubusercontent.com/13243259/38291247-7bc49098-37fc-11e8-8887-e51a96aacaf9.gif)


## How to reproduce

- Clone https://github.com/KiranNiranjan/electron-bugs/tree/electron-show-inactive
- `npm i`
- `npm run start`

Windows native API -> [SetWindowPos](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633545(v=vs.85).aspx) can be used by setting `SWP_NOACTIVATE with 0x0010`

**Comment by MadfishDT** [comment]
I made new pull request for master branch
https://github.com/electron/electron/pull/12480

mac version is same

but windows version different from showInactive function

moveTop function have different action from showInactive function, moveTop api do not touch minimized/maxmized window status. 

difference(Windows) 
1. moveTop API : minimize some window->call window.moveTop->window is still minimized
2. moveTop API : notepad occupied top position and have focus->call window.moveTop->window occupie top position and notepad have focus

moveTop api working in perfectly in windows... but mac and window little bit different windows status handling

**Comment by KiranNiranjan** [comment]
@MadfishDT You mean #12485 😄

**Comment by MadfishDT** [comment]
this function merged in master branch
