### ISSUE TITLE
Not able to run electron app(Local)  from electron app ( Local or Server)

### ISSUE THREAD

**Issue by niravk17** [electron/electron#12306]
Hi there 
Does any one know how to call another electron app from electron  app ?

For Example :  From main.js  we are trying to launch another Electron app( which was downloaded at local path ) ?

Thank you in advance

**Comment by arjndr** [comment]
You can try [execFile](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback), also it would be helpful if you provide more details. This doesn't really seem like an electron issue, next time try asking stuff like this [here](https://discuss.atom.io/c/electron)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
