### ISSUE TITLE
Electron.desktopCapturer.getSources and screen.getAllDisplays() ordering mismatch.

### ISSUE THREAD

**Issue by spicykoala** [electron/electron#12312]
The ordering of getSources and getAllDisplays no longer matches. On mac the id of the display matches between the two, so I'm able to match them up that way. However, on windows, the ids are different so I'm not sure how to get around it. Any suggestions? I'm stuck on 1.6.x for Windows until I can figure out a way around it :(

* Electron version:
1.8.3, 2.0.x
* Operating system: 
Windows 10 x64

### Expected behavior
In a two monitor situation where display #2 is the primary monitor, Electron.desktopCapturer.getSources returns with the same ordering as screen.getAllDisplays()

### Actual behavior
In a two monitor situation where display #2 is the primary monitor, the two calls return values in different orders with no discernible way to match them up.

**Comment by CapOM** [comment]
Indeed on Win7, 8 and 10, the desktopCapturer.getSources always returns source.id as "0.0" like on Linux. This does not match electron.screen.getPrimaryDisplay().id

**Comment by CapOM** [comment]
I found the reason and this is because 'getAllDisplays' uses the framework  A chromium/ui/display/ whereas ''getSources' uses the framework B chromium/third_party/webrtc .

On Mac, A and B use NSScreen.
On Linux, A uses xrandr, B always return 0.
On Win, A uses 'msdn / HMONITOR MonitorFromWindow',  B increments a local counter from 0 (then 1, 2 and so on)

Also on Linux and Windows, 'getSources' will postfix the ids above from B, with ':0' always (see file chromium/src/content/public/desktop_media_id.cc::DesktopMediaID::ToString() in the #ifdef defined(USE_AURA). (no aura on Mac)

**Comment by spicykoala** [comment]
Ahh, I see. Do you know why it works prior to 1.7.x? 

My use case is being able to put a toolbox (BrowserWindow) and other information onto the screen that the user is recording. So, I need a way to identify which screen they are recording from electron, so that I'm able to place the browser window correctly.

**Comment by CapOM** [comment]
Can you print the display.id for each display returned by screen.getAllDisplays() with electron-1.6.x ?

(for the record, it uses chromium 56.0.2924.87 and this webrtc https://chromium.googlesource.com/external/webrtc/+log/branch-heads/56)

**Comment by jkleinsc** [comment]
This issue may be due to the changes introduced in #11664/#11677.

I believe this PR will address the issue: #12417

**Comment by ajmacd** [comment]
This issue predates PRs #11664/#11677.

It was introduced in Electron 1.7.x when Chromium began using the DirectX capturer for getUserMedia. The aforementioned PRs ensure the thumbnails returned by desktopCapturer are associated with the correct IDs for getUserMedia. The more recent #12417 is indeed intended to fix the problem described here.

**Comment by codebytere** [comment]
@spicykoala @ajmacd as https://github.com/electron/electron/pull/12417 has been merged, i'm going to go ahead and close this. If the problem persists, please @ me for a reopen!

**Comment by clusterberries** [comment]
Hi @codebytere! Which version of Electron contains the fix? Thanks.

**Comment by clusterberries** [comment]
Thanks, @codebytere ! Unfortunately this page returns 404.

**Comment by codebytere** [comment]
oh oops it's an org board not a project board...anyways it's a candidate for one of the first `2-1-x` releases.

**Comment by levinunnink** [comment]
We're having problems with this too. When do you expect release to ship?

**Comment by aabuhijleh** [comment]
This is still an issue on Windows 7, "display_id" is empty. 

I highlight shared displays and cannot find a way to match displays from ```desktopCapture.getSources()```  with displays from ```screen.getAllDisplays()```

@spicykoala did you find a solution for this issue?

**Comment by ajmacd** [comment]
This occurs because Chrome doesn't use a DirectX capturer on Windows 7 (it may be that it's not actually available from the OS). If the `display_id` field is absent on Windows, you are safe to assume that the order of the displays provided by the `desktopCapture` and `screen` APIs matches.

Apologies for this OS-dependent complexity.
