### ISSUE TITLE
Can you tell when webContents is *done* painting?

### ISSUE THREAD

**Issue by countravioli** [electron/electron#12424]
Question:

Is there a way to accurately tell if the webContents is done painting? I've tried a variety of things but right the basic behavior of my OCR browserView goes like this

* instantiate browserView with all the offrscreen props
* webContents.stopPainting()
* Preload fonts, preload images, setup html / dom through JS.
* Everything hunky dory, okay call invalidate() and startPainting()

What I would hope at this point, would be to get one paint event, when that finishes I know I can capture the page and everything is good to go.

What happens, is sometimes I get 2-3 paint events. The first one might just have a blank screen, second one might show some stuff, maybe fonts aren't rendered sometimes. It's hard to reproduce and debug and I get a variety of things. Any wisdom on this subject would be much appreciated.

**Comment by YurySolovyov** [comment]
have you tried using `requestAnimationFrame` ?

**Comment by nornagon** [comment]
Does the [`did-stop-loading`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-did-stop-loading) event work for you? In general it's not possible to say with certainty that a page is "finished painting" (because there might be some pending XHR or other dynamic content), but there are a few signals that might work for your use-case. You might also try scheduling an idle callback in the page via `requestIdleCallback`.

Closing the issue because I don't think there's any well-defined API Electron could add to provide this behavior.
