### ISSUE TITLE
Dialog multiSelections do not allow contiguous selection under MacOS

### ISSUE THREAD

**Issue by dkadrios** [electron/electron#12425]
Using `showOpenDialog` with the properties `['openFile', 'multiSelections']` (or 'openDirectory') does allow for multiple selection of individual files if holding down the Command key or dragging with the mouse, however you are not able to selection a range by shift+clicking, and perhaps more annoyingly, you are not able to select all files by using CMD+A

* Electron version: 1.8.4
* Operating system: MacOS

### Expected behavior

Pressing CMD+A in a file open dialog should select all items

### Actual behavior

CMD+A is a no-op.  Additionally, selecting the first item and then SHIFT+Clicking another does not select the items in between.  The only way to select all items is to CMD+Click them each individually or to selection drag with the mouse/trackpad.   Too cumbersome when there are many items to select.

### How to reproduce

```
import { remote } from 'electron'

const options = {
  properties: ['openFile', 'multiSelections'], // same happens with openDirectory
  defaultPath,
  filters,
}

remote.dialog.showOpenDialog(options, (sourcePaths) => { ... })
```

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by dkadrios** [comment]
Issue has been updated to match the template.

**Comment by sethlu** [comment]
I was able to use `cmd+a` to select all files with the latest Electron build and 1.8.4 & macOS High Sierra 10.13.4.

```js
const {app, dialog} = require('electron');

app.on('ready', function () {

  dialog.showOpenDialog({
    properties: ['openFile', 'multiSelections']
  });

});
```

Wondering if this may be an macOS-version-related issue? @dkadrios does this test case work for you? I would suggest also trying to multi-select some files in Preview's open dialog and see how it responds to `cmd+a` and see if it works there?

**Comment by dkadrios** [comment]
Unfortunately, no it still is not working for me.

I've forked `electron-boilerplate` and have added your example code to it, to keep things to the bare minimum.  That fork is available at [dkadrios/electron-boilerplate](https://github.com/dkadrios/electron-boilerplate) 

It's using electron 1.8.4 and I'm also on High Sierra 10.13.4

I've tried changing the view modes in Finder and have tried in a number of folders, each containing different of files, but still no luck.  For what it's worth, my application will be selecting audio files.  

I've attached a screenshot of the open dlg.  Ideally pressing CMD+A there would select all the files in that folder.

![screen shot 2018-04-09 at 8 56 32 pm](https://user-images.githubusercontent.com/1223595/38535492-9401f5c0-3c38-11e8-9165-ef178ff9e3df.png)

CMD+A in Preview does work as expected.

**Comment by sethlu** [comment]
@dkadrios Thanks for providing the test case!
I think the issue comes from not having a matching role for the "select all" menu item.

In https://github.com/dkadrios/electron-boilerplate/blob/8e7d695fd573b92d66925ecd397119ab6764cc55/src/menu/edit_menu_template.js, rather than manually specifying the accelerator keys, I'd advise using the specific roles for special menu items. It may look like the following:

```js
export const editMenuTemplate = {
  label: "Edit",
  submenu: [
    { role: "undo" },
    { role: "redo" },
    { type: "separator" },
    { role: "cut" },
    { role: "copy" },
    { role: "paste" },
    { role: "selectall" }
  ]
};
```

I don't think the option `selector` does anything to the menu item.

**Comment by dkadrios** [comment]
Thanks, @sethlu, it's working perfectly now!
`role` was the answer
