### ISSUE TITLE
crypto.createHash() not work

### ISSUE THREAD

**Issue by danyadev** [electron/electron#12439]
Electron: 2.0.0-beta.5
Windows: 7 Ultimate x64

### Expected behavior
md5 hash

### Actual behavior
Error: `crypto.createHash is not a function`

### How to reproduce
```javascript
const crypto = require('crypto');

function md5(data) {
  return crypto.createHash('md5').update(data).digest();
}

md5('any text');
```

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by danyadev** [comment]
info added

**Comment by MarshallOfSound** [comment]
@danyadev I ran the code you provided in Electron 2.0.0-beta.5 and it worked without any errors, can you please ensure that you have no typos in your code.  Please also be aware that using tools like `webpack` can break node internals if not configured correctly.
