### ISSUE TITLE
after load extension, inspector.js got error

### ISSUE THREAD

**Issue by liguanpei** [electron/electron#12434]
[8928:0326/191156.598:ERROR:CONSOLE(7278)] "Skipping extension with invalid URL: chrome-extension://desktop-sharing-exte
nsion", source: chrome-devtools://devtools/bundled/inspector.js (7278)
extension id: lafaooeojkcadiliheobbkkpkbnmdhgh
extension name: Desktop Sharing Extension

can anybody help me?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
