### ISSUE TITLE
Feature request: adding item to the control strip of the touchbar

### ISSUE THREAD

**Issue by mdings** [electron/electron#12431]
It would be great to be able to also add an item to the control strip of the touchbar. In this case, the app wouldn't have focus per so to show some controls for it.

There is a project called [touch bär](https://github.com/a2/touch-baer) to be able do this. I am not sure if this can be easily extended to Electron though.

Love to hear some thought on this!

**Comment by MarshallOfSound** [comment]
@mdings This API that allows you to do this (put items in the control strip) is both private and undocumented.  I'm personally against adding usage of API's like this as they could break at any time resulting in millions of users having bricked installs of third party apps.

**Comment by codebytere** [comment]
While we could do this, it's not in our best interest to make it native as opposed to keeping it in userland because we don't traditionally expose experimental and undocumented APIs, and so we don't have a protocol around how we would do that and make clear to users its status. Sometime in the future, perhaps, but for now we'd prefer to not

**Comment by mdings** [comment]
Understood! Thanks anyway for looking into this.
