### ISSUE TITLE
Installing Electron Manually?

### ISSUE THREAD

**Issue by tpck** [electron/electron#12450]
Is there a "how to" guide anywhere on how I can manually download, install, and run Electron?

I can get Electron up and running at home no problem... but at work I get hit with the "Failed at the electron@1.8.4 postinstall script" error message. I've been searching around on a way to remedy this issue to no avail.

I would like to manually install Electron, and the installation instructions only contains the below snippet and nothing more: 
> You can also attempt to download Electron directly from electron/electron/releases if installing via npm is failing.

Electron: 1.8.4
OS: Windows 7 (64 bit)

**Comment by GhostlyDark** [comment]
The snippet points to: https://github.com/electron/electron/releases
For your OS: https://github.com/electron/electron/releases/download/v1.8.4/electron-v1.8.4-win32-x64.zip

These are prebuilt binaries, pretty much what portable apps are. No installation, they can run directly.
I hope this helps.

**Comment by tpck** [comment]
How would I get the _package.json_ to launch electron? I extracted the prebuilt binaries into a folder named "electron" and moved it inside of my project folder. Below is what I have (but isn't working):

```
{
  "name": "my-electron",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "./electron/electron ."
  }
}
```

**Comment by GhostlyDark** [comment]
Your app needs to be in: electron/resources/app/
Then executing electron.exe is enough to launch it. No need for "scripts" in package.json.

You can also launch your app with a .bat file from a different location, containing the following:
C:\Electron\electron.exe D:\My Electron\v1.0.0

Just as a side note: This way you can also parse command line arguments like this:
C:\Electron\electron.exe --enable-sandbox D:\My Electron\v1.0.0

**Comment by tpck** [comment]
I created a batch file to launch Electron with my app's location (and it works for simple apps with no dependencies):
```
cd c:\Users\<user>\Desktop\Dev\electron
start electron "C:\Users\<user>\Desktop\Dev\myApp\main.js"
```
How would I go about managing dependencies when launching my application this way? Wouldn't I need to configure a _package.json_? It looks like when launching an electron app this way, it ignores the _package.json_ and errors out when I require modules that need to be pulled from NPM.

**Comment by GhostlyDark** [comment]
`start electron "C:\Users\<user>\Desktop\Dev\myApp\"`
This is going to look for a package.json.

You can also put npm modules into a folder named node_modules (myApp\node_modules\). These can be required in main.js.

**Comment by tpck** [comment]
Hmm... I am getting an error that it cannot find the app when I use the above path with the below _package.json_ file.

```
{
  "name": "myApp",
  "version": "1.0.0",
  "main": "main.js",
  "dependencies": {
    "tedious": "^2.3.1"
  },
  "scripts": {
    "start": "electron ."
  }
}
```
Is there documentation on the site on setting up Electron this way?

**Comment by GhostlyDark** [comment]
I think the path "electron ." is wrong. It should be something like "electron ..\electron\" since it is in a different location than what your main.js is in.

I am not sure though if scripts in package.json are even working with a batch file. I personally never used the scripts tag in package.json during development and rather used what I already mentioned in my second post: (for a batch file)

`path\to\electron.exe` `path\to\app-folder`

`C:\Users\%username%\Desktop\Dev\electron\electron.exe` `C:\Users\%username%\Desktop\Dev\myApp\`

With variables like %cd% (=current directory) you could use relative paths. 
The below is assuming you have your batch file in Dev\myApp\.

`%cd%\..\electron\electron.exe` `%cd%`

Easiest solution is of course putting the app in electron\resources\app since it is going to be in that path once you distribute your app anyway.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
