### ISSUE TITLE
how increase kMaximumMessageSize

### ISSUE THREAD

**Issue by linuxpham** [electron/electron#12470]
* Electron version: 1.8.4
* Operating system: macOS

ERROR:channel.cc(592)] Invalid message size: 323442320

### Expected behavior
The app shouldn't crash

### Actual behavior
The app crashes

### How to reproduce
Load json files (about 180 MB)
The app will crash with error message : channel.cc(592)] Invalid message size
Is there any way to increase kMaximumMessageSize ?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
