### ISSUE TITLE
support for older kernels? ABI 2.6.18?

### ISSUE THREAD

**Issue by bsferrazza-avnera** [electron/electron#12487]
I am forced to use an older Linux distribution at my electrical engineering firm due to some legacy EDA software. It uses kernel 2.6.18. Fortunately I've been able to build a completely bootstrapped toolchain and environment with the latest glibc (2.19) supported by the kernel, and the very latest binutils, gcc, and dozens and dozens of libraries and binaries.

But I'm having trouble building Electron based apps, as they seem to build for ABI 2.6.26. Is there anyway to build against my toolchain to support 2.6.18? Thank you

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
