### ISSUE TITLE
How do I change the title on the download window?

### ISSUE THREAD

**Issue by kimyearho** [electron/electron#12494]
* Electron version: 1.8.4
* Operating system: Windows 10 (x64)

### Expected behavior
Download the file.

### Actual behavior
Download the file.

### How to reproduce
* When the download begins, the URL will appear in the title.
![image](https://trello-attachments.s3.amazonaws.com/5a5dfd3a30c0701da5a2ad08/5ac089e353aa1e1c43127ba9/6eb80351390bea56062f94a2c8bf42bd/downloadWindow.PNG)

this.. code..
![image2](https://trello-attachments.s3.amazonaws.com/5a5dfd3a30c0701da5a2ad08/5ac089e353aa1e1c43127ba9/cb729f36675cae36b1b3588b210a8e14/code.PNG)

I need help.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by liulinboyi** [comment]
The issue's answer is there!
https://github.com/electron/electron/issues/27601#issuecomment-773076625
