### ISSUE TITLE
Typing into textbox in an offscreen webivew crashes electron

### ISSUE THREAD

**Issue by ImOnALampshade** [electron/electron#12528]
# Description

* Electron version: 1.8.4
* Operating system: Windows 10

Calling `webContents.sendInputEvent` with type as `"char"` to a document containing a webview is rendered offscreen and an input panel is focused

# Expected result

Keyboard input should be placed into the input panel

# Actual result

Electron crashes

# Repro steps

[I have a repo set up that will demonstrate the issue.](https://github.com/ImOnALampshade/electron-webview-char-crash) Clone that to see. Read the readme in that for more information.

```bash
git clone https://github.com/ImOnALampshade/electron-webview-char-crash.git
npm install
npm start
```

**Comment by brenca** [comment]
This is related to the autofill popups actually, when `webview`s are used in OSR, it tries to create the popup for the wrong frame (the webview's instead of the main page's), which causes a crash when the `RenderWidgetHostView` is cast.

I'm going to fix this on master, but a proper fix depends on #12514 (the popup's position is also incorrect, and it's a much easier fix with that PR pulled).

**Comment by DeerMichel** [comment]
@ImOnALampshade do you know whether the issue still exists under Electron v5 or v6? At least on macOS it doesn't crash (but it also doesn't crash under v1.8 - so this seems to be a Windows bug).

**Comment by DeerMichel** [comment]
On Windows it doesn't crash for me as well - i think #13184 fixed it back then 👍
