### ISSUE TITLE
mac system menu icon

### ISSUE THREAD

**Issue by pjebs** [electron/electron#12525]
When you have multiple monitors, the top system menu icon only appears on the "main" screen and not all.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/12525#issuecomment-378702446). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
