### ISSUE TITLE
Why am I not able to load dependent file in Electron App? The same node application is working fine in Chrome and does not get any error.

### ISSUE THREAD

**Issue by mukeshthe93** [electron/electron#12569]
Using below code to load an URL.

 mainWindow = new BrowserWindow({width: 800, height: 600,webPreferences: {
        allowRunningInsecureContent: true,
        webSecurity: false
      }})

  mainWindow.loadURL("http://10.17.205.39:5000/")

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
