### ISSUE TITLE
Issue with Class 'DownloadItem'

### ISSUE THREAD

**Issue by jon-ryan** [electron/electron#12560]
Hello guys,

I'm fairly new to electron and playing around with an app which loads GMail/Google Inbox. 

Every time I want to download an attachment I can't download it. Everything that happens, is, that a new window appears, which is completely blank. There is nothing I can click on, no dialog, nothing.

I read the documentation for the 'DownloadItem' class but that doesn't work for me.
After creating a new Window (win = new BrowserWindow[...]) I call 'win.webContents.session.on('will-download', [...]' but this doesn't change anything. I still can't download files.

I appreciate every answer.

**Comment by keerthi16** [comment]
@jon-ryan 
Here's an [example](https://github.com/keerthi16/electron-download-manager-example) usage of `DownloadItem`
Hope this helps 😃

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by jon-ryan** [comment]
Please excuse my late answer.
Thank you, I'll head to the electron commuinty.
