### ISSUE TITLE
Build electron with proprietary codecs

### ISSUE THREAD

**Issue by hubuga** [electron/electron#12565]
I was wondering if it's possible to build electron with proprietary codecs and how to do that? I wanted to run a hevc video but I can't do that as it's not enabled by default.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by jomla97** [comment]
@hubuga Did you make any progress with this?

**Comment by JuanIrache** [comment]
@jomla97 Also trying this. Did you find ouy how? Thanks

**Comment by jomla97** [comment]
@JuanIrache Unfortunately not..
