### ISSUE TITLE
Electron writes \r\n to stdout when started as a subprocess on Windows

### ISSUE THREAD

**Issue by rosesandhello** [electron/electron#12578]
* Electron version: v1.8.4
* Operating system: Windows 10

### Expected behavior

When Electron is started as a subprocess, it should not write a carriage return and linefeed (\r\n) to stdout.

### Actual behavior

Electron does write a carriage return and linefeed when started as a subprocess.

### How to reproduce

Using Python 2.7:

```
import subprocess
import struct
import time

def testit():
    cmd = "c:\\[NPMPATH]\\electron.cmd c:\\wherever\\main.js";
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        stdin=subprocess.PIPE, shell=False)
    print("sleeping for 5...")
    time.sleep(5)
    print("done sleeping...")
    firstTwo = p.stdout.read(2)
    print("got it!!!",firstTwo)

testit()
```

Output is:
> sleeping for 5...
> done sleeping...
> ('got it!!!', '\r\n')

This may seem like an obscure problem, but in attempting to use Electron as a native messaging enabled application via a shim, it took an exceedingly long time to find the source of the errant line break.

**Comment by faressoft** [comment]
I am facing the same issue.

**Comment by rosesandhello** [comment]
This is still the case as of Electron v3.1.0.
No further information needs to be added.

**Comment by groundwater** [comment]
Hi @rosesandhello.

There may be some confusion about what this issue tracker is, and I want to ensure there are no ambiguitites moving foward.

By posting an issue here, you are looping other maintainers and contributors into your own investigation into bugs, features, etc. This has the often utilized benefit that others with similar problems can pool knowledge and resources to improve the project.

Issues do not represent a commitment, agreement, or priority by any other maintainer of the project. Understanding that, I hope you can see that this comment will not win many friends:

> Also, as opposed to affixing a blocked/need-info flag, running the sixteen lines of Python I gave you might have been the better call.

This is part of your responsibility.

Good news though, in many cases other maintainers _will_ address your priorities. It's give-and-take. Be a good community member and people will enjoy helping you out.

I hope this corrects any misunderstandings.

**Comment by rosesandhello** [comment]
I should have been more magnanimous: apologies.

**Comment by xmedeko** [comment]
The problem is still in v6.0.11.

## How to reproduce
Just simple `index.js`:
```js
require("console").log("Hello");
const { app } = require('electron');
if (app) app.quit();
```

1. Run `node index.js`.
2. Run `npx electron index.js`.

The electron prints extra blank characters at start.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by xmedeko** [comment]
I find closing bugs reported to old version by @electron-triage as inconvenient. Better way is to make some warning to the reporters: "check the issue with the newest version or we will close it" and close it if the reporters do not respond for some time only.

BTW. the bug is still in Electron v12.0.0
