### ISSUE TITLE
Pre-load script not executed when navigating windows with affinity to another domain

### ISSUE THREAD

**Issue by kirilpopov** [electron/electron#12587]
* Electron version: 2.0.0-beta.7
* Operating system: Windows

### Expected behavior

When I navigate a window that was created with pre-load script and affinity string to a domain different from it's original domain I expect the pre-load script to be executed

### Actual behavior

The pre-load script is not executed. Note that the pre-load script is executed if you navigate to a link in the same domain.

### How to reproduce

1. create a new window - specify affinity string and pre-load script. The pre-load script can be a simple console.log or assigning something to the window object.
2. wait for the window to load - the pre-load script should be executed
3. use document.location to change the window location to another domain.
4. the pre-load script is not executed

Note that the pre-load script is executed in the same scenario if you navigate to a link in the same domain, or execute the above steps for windows without affinity settings

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

If you have time, please consider writing a minimal Electron app -- for example, a fork of [electron-quick-start](https://github.com/electron/electron-quick-start) -- that a tester could run to reproduce this issue.

This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. Also, we are no longer supporting version 2.0.x. Please let us know if this bug is still present in version 4.2.x or later.

I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
