### ISSUE TITLE
command-line only "--version" flag does not work in GUI-less environment

### ISSUE THREAD

**Issue by eli-schwartz** [electron/electron#12621]
* Electron version:  1.8.4
* Operating system: Arch Linux

### Expected behavior

`electron --version` should *always* print the version to stdout.

`electron --abi` should *always* print the abi to stdout.

### Actual behavior

Both commands fail with:

`(electron:296): Gtk-WARNING **: 22:42:21.238: cannot open display: `

### How to reproduce

Enter a linux chroot or otherwise run without an X11 server, then try to run either command. This is useful for e.g. build environments which want to know which version of electron is installed. However, getting this text string on TTY stdout is impossible without first spinning up a temporary X11 server (in a build chroot???) to run via DISPLAY (or xvfb-run).

It seems kind of silly to require X11 for something which does not use it at all; maybe it would be possible to check for options and return the output for these flags, before trying to access the display?

**Comment by ckerr** [comment]
I agree this would be nice to have, but it's an edge case that would be complex to implement because of the way Electron was architected: it creates a browser window and then loads an app, and the default app is what actually does the --version and --abi parsing in JS code.

Because of this cost-to-reward, I'm closing this ticket as a `wontfix`.

If someone feels strongly enough about this feature to write a fairly clean PR, I'd be inclined to use it.
