### ISSUE TITLE
Electron 1.6.5 keep crashing on atom::api::Window::OnWindowClosed()

### ISSUE THREAD

**Issue by universeroc** [electron/electron#12632]
[74b0c1f9-0ebb-4410-abd4-df9a9d734e89.zip](https://github.com/electron/electron/files/1918450/74b0c1f9-0ebb-4410-abd4-df9a9d734e89.zip)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by universeroc** [comment]
@sofianguy @ckerr OK, in fact, I've deployed mini-breakpad-server to receive mini-dump reported from electron apps, and I don't know the very details about the steps even after I talked with app developers, they reply to me it's everything OK but crash-dump generated and reported. I debugged the mini-dumps and found nothing related about our code, and googled the stack info, found somebody already came across this kind of crash, so I post the minidump file here.

Sorry maybe I can't supply enough information but I'll try my best to make it. Just some minutes or hours :P

**Comment by codebytere** [comment]
We haven't gotten a follow-up to our questions in our comment above, and with only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
