### ISSUE TITLE
Application Error for slack invite

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [electron/electron#12644]
I get an error when I go to this URL to get a slack invite.
https://atom-slack.herokuapp.com/

**Comment by codebytere** [comment]
It's loading correctly for me, but also because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. 

There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
