### ISSUE TITLE
Accelerator Key § missing

### ISSUE THREAD

**Issue by mrgrauel** [electron/electron#12663]
Is it possible to use the key on macOS on the left of `1` ?

I use [hyper](hyper.is) and would like to open the app with the Keyboard Shortcut `CMD+§`. `§` is the key left to `1` on an English international layout for macOS.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
