### ISSUE TITLE
 How can I solve the problem of applying regular white screens?

### ISSUE THREAD

**Issue by onreadystatechange** [electron/electron#12693]
Thanks for opening an issue! A few things to keep in mind:

- The issue tracker is only for bugs and feature requests.
- Before reporting a bug, please try reproducing your issue against
  the latest version of Electron.
- If you need general advice, join our Slack: http://atom-slack.herokuapp.com
-->

* Electron version:1.6.17
* Operating system:windows 32 

Callstack

?OnMediaNotification@CLocalEndpointEnumerator@@UAGJPAUMEDIA_NOTIFICATION_BLOCK@@@Z
MMDevAPI.dll
?OnMediaNotificationWorkerHandler@CMediaNotifications@@QAEXPAU_TP_CALLBACK_INSTANCE@@@Z
MMDevAPI.dll
?MediaNotificationWorkerHandler@CMediaNotifications@@SGXPAU_TP_CALLBACK_INSTANCE@@PAX@Z
MMDevAPI.dll
TppSimplepExecuteCallback
ntdll.dll
TppWorkerThread
ntdll.dll
@BaseThreadInitThunk@12
kernel32.dll
__RtlUserThreadStart
ntdll.dll
__RtlUserThreadStart@8
ntdll.dll

### Expected behavior

No longer white screen

**Comment by onreadystatechange** [comment]
this is my log 
[13.dmp.zip](https://github.com/electron/electron/files/1941387/13.dmp.zip)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
