### ISSUE TITLE
[macOS] Click event is not triggered fron notification center if the user waits ~1 minute or more

### ISSUE THREAD

**Issue by ClaudiaStefan** [electron/electron#12690]
* Electron version: 1.8.4
* Operating system: macOS High Sierra (version 10.13.4)

* Last known working Electron version: idk

### Expected behavior
4. Click event is triggered

### Actual behavior
4. Only the app comes in focus, or nothing happens

### How to reproduce
1. Trigger a notification from main process
2. **Wait at least 1 minute**
3. Click in notification center, on the notification

### Clone this repository to test
git clone https://github.com/ClaudiaStefan/electron-notification-test.git
### Go into the repository
cd electron-notification-test
### Install dependencies and run the app
npm install && npm start

**Comment by codebytere** [comment]
I'll look into this shortly @ClaudiaStefan

**Comment by MarshallOfSound** [comment]
@codebytere @ClaudiaStefan This is known and somewhat expected behavior.  The issue here is that `notification` object is being garbage collected before the click event is emitted.  If you want it to persist you need to store it somewhere it won't be destructed.

For instance at a higher scope you can do

```js
const notifications = {};
```

and then after https://github.com/ClaudiaStefan/electron-notification-test/blob/master/app/main/main.js#L43 you should just do `notifications[Symbol()] = notification`.  Then it will be un garbage collectable 😄

**Comment by ClaudiaStefan** [comment]
@MarshallOfSound thanks a lot :). I totally missed that :D.
