### ISSUE TITLE
Is ChromeOS supported?

### ISSUE THREAD

**Issue by vicatcu** [electron/electron#12712]
Some apps I develop ate targeted for use in schools where Chromenook is the platform of choice.  Is it possible to build an Electron App with a ChromeOS target?  Any pointers to how to go about that, assuming it's possible?

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
Sadly no, Electron can't run on ChromeOS. You might look into creating a PWA: https://developers.google.com/web/progressive-web-apps/

**Comment by limeb** [comment]
I am adding to this because of crouton it should be feasible to run the application in crouton and display it in Chrome OS.  This would require the user to enable developer mode but would pull over all(well most of) the existing APIs with out well writing writing all everything.  There would be obivous limitations.

**Comment by bewood** [comment]
FWIW, regarding crouton, I have been happily using VS Code for a few months now using this approach. Though I have doubts about whether schools would permit enabling developer mode on student chromebooks.

**Comment by vicatcu** [comment]
@bewood no chance :)

**Comment by wanastasi** [comment]
https://github.com/codercom/code-server

**Comment by imagineeeinc** [comment]
You can use [Ionic](https://ionicframework.com/); mentioned in [this docs page](https://ionicframework.com/docs/core-concepts/cross-platform).

So, basically you can use the electron to make the Windows, MacOS version (and Linux if you want) , and then use the Ionic to make the android app as chromebooks supports android apps.

**Comment by msynk** [comment]
You can run Linux apps on ChromeOS (https://www.androidauthority.com/linux-on-chromebook-1139944/), so just build a Linux bundle and use it instead.

**Comment by imagineeeinc** [comment]
> You can run Linux apps on ChromeOS (https://www.androidauthority.com/linux-on-chromebook-1139944/), so just build a Linux bundle and use it instead.

but many can't switch on Linux (their school or organization blocked it) or they don't want to switch it on due to complexity; so, it's better to build for android as Chromebook's can run android

**Comment by Codetoil** [comment]
Schools can limit which android apps you can download, so an android app is not an option for some.
