### ISSUE TITLE
Is there an event that is activated while exe or dmg being extracted

### ISSUE THREAD

**Issue by devguysin** [electron/electron#12728]
Hi,

I need to know what is the file name of the exe / dmg that was executed

1. Is there any event that is fired while exe is being extracted to the AppData folder? and when dmg is being copied to the Application folder?

2. does the original file name is being recorded somewhere to the application folder?

If there isn't any option like that - is it possible to push an update to the exe and dmg before downloading it to the user (update json or text file) in a way it wont effect the application signing?

Thanks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
