### ISSUE TITLE
I want browser preview pdf。When setting BrowserWindow's plugins to true，Why did you comment out the ‘’print‘’ function?How can I use

### ISSUE THREAD

**Issue by chaoyue1217** [electron/electron#12811]
* Electron version:
* Operating system:

* Last known working Electron version:

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by rreimann** [comment]
Might be related to #9029 - printing is not yet implemented in the pdf plugin.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
