### ISSUE TITLE
electron app on mac is crashing, using node-ffi

### ISSUE THREAD

**Issue by sysleaf** [electron/electron#12813]
[Electron Helper_2018-05-03-173948_vikashs-MacBook-Pro.txt](https://github.com/electron/electron/files/1970834/Electron.Helper_2018-05-03-173948_vikashs-MacBook-Pro.txt)

I am using node-ffi, in one scenario where i am calling some api but after some time electron application on Mac is crashed. This crash does not happen if i do same thing through nodejs console app. Same crash is not seen for electron app on windows. I have attached below crash log. Please help me know what could be the reason of this crash and how can i solve it and where the fix required? 

I have attached the crash log file.

* Electron version: 2.0.0
* Operating system: MacOS 10.13.3

* Last known working Electron version: tried with some old electron version but same issue exit

### Expected behavior

application should not crash

### Actual behavior
application is crashing

**Comment by timfish** [comment]
Thanks for reaching out!

I've tried node-ffi on 2.0.0 and it works and you have the same issue on previous Electron versions so this native crash is likely down to usage.

Github issues are treated as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), so we close issues that are questions since they don't represent a task needing to be completed. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by sysleaf** [comment]
But this issue is only happening in electron renderer process. If i run same code in electron main process, i don't see the same crash. So basically its an issue with electron renderer. So can you please give some hint/suggestion at least  by looking at the crash logs.

Please this is very critical issue.

**Comment by timfish** [comment]
The error says `KERN_INVALID_ADDRESS at 0x0000000000000000` and looking at the call stack it seems like you're trying to dereference a null pointer. You should be handling this in your code.
