### ISSUE TITLE
Performance hit when processing large array of data

### ISSUE THREAD

**Issue by Nikola-Obreshkov** [electron/electron#12821]
I have an array A with about 40k objects. Every object has an **id** and a **logtime**. When I do in Electron 1.7.10 (Ubuntu 16.04):
```
console.log('Processing ' + A.length + ' enties...');
let t0 = performance.now();
let timeline = {};
for ( var i = 0, l = A.length; i < l; ++i ) {
    let entry = A[i];
    if ( timeline[entry.logtime] === undefined ) timeline[entry.logtime] = {};
    timeline[entry.logtime][entry.id] = entry;
}
let t1 = performance.now();
console.log('... done for ' + ( t1 - t0 ) + ' milliseconds.');
```
it prints:
```
Processing 40916 entries...
... done for 23222.775 milliseconds.
```
Exactly the same code in Firefox produces:
```
Processing 40916 entries...
... done for 26 milliseconds.
```
The result is almost the same if i loop with forEach or map. The same is with hasOwnProperty or typeof.

**Comment by MarshallOfSound** [comment]
@Nikola-Obreshkov Can you provide full repo code including your dataset?

Are you by any chance using the `remote` module to do anything here?

**Comment by MarshallOfSound** [comment]
Yup so when you use remote for this kind of stuff it gets really slow because it isn't some magic bridge, every get and set request is actually synxronous ipc behind the scenes which blocks both processes and isn't incredibly fast. 

This is fine for small units of work but doesn't what you describe you should use asycnronous ipc with ipcRenderer and ipcMain.
