### ISSUE TITLE
How can I drop folder and get the folder local path

### ISSUE THREAD

**Issue by carsonxu** [electron/electron#12827]
How can I drop folder and get the folder local path

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by carsonxu** [comment]
It's resolved!
`e.originalEvent.dataTransfer.items[0].path` is relative path
`e.originalEvent.dataTransfer.files[0].path` is absolute path
