### ISSUE TITLE
I cann't get system font list

### ISSUE THREAD

**Issue by jevian-ma** [electron/electron#12849]
I know that chrome extension api chrome.fontSettings can get system font list, but I can't use this api at electron.
Can you tell me other way to get system font list?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
