### ISSUE TITLE
app.setAccessibilitySupportEnabled is not a function

### ISSUE THREAD

**Issue by GMuthuraja** [electron/electron#12857]
I have used the below lines to enable accessbility setting in electron app, however it shows 'app.setAccessibilitySupportEnabled is not a function'

var app = require("electron")
app.setAccessibilitySupportEnabled(true);

Anyone can guide me to fix this issue?

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
