### ISSUE TITLE
localStorage/indexedDB created in 2.0.0 does not carry over to 1.8.x

### ISSUE THREAD

**Issue by mobitar** [electron/electron#12878]
I'm not sure if this is by design, but if you compile an app with Electron 2.0.0, add some entries to localStorage, compile the same app with Electron 1.8.4, the localStorage entries will be gone.

(I discovered this by creating some data on my app with Electron 2.0.0, then running an older version of my app, only to notice all my data had been deleted.)

You can replicate this easily with the quick start repo: https://github.com/electron/electron-quick-start

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

Then, open the Inspector, Application -> Local Storage, and add an entry manually: 

key: `foo`
value: `bar`

Quit the app, and  run`npm start` again and verify that the entry is still there. (It is)

Now, open package.json, and change electron to 1.8.4. Then, `npm install`, `npm start`, and you'll now notice that the localStorage entry is no longer present.

This applies to IndexedDB data as well. I've tested this on Mac 10.13.2, Windows 10, and Ubuntu 18.04 with the same effect.

**Comment by MarshallOfSound** [comment]
@mobitar This is currently expected behavior, Chromium changed their storage technique for `localStorage` between the chromium versions that `2.0` and `1.8` are based on.  Any data stored in a `1.8` app will be migrated automatically to the new storage format when you update to `2.0` but it doesn't go the other way.

I.e. If you store data in `2.0` and then downgrade to `1.8` no migration of data will occur

**Comment by Jocs** [comment]
@mobitar Does this mechanism also apply to indexDB? Is there a link to the description? thanks!

**Comment by mobitar** [comment]
@Jocs I don't recall tbh. I don't think so though, since I probably would have at least mentioned that as an aside if it were the case.
