### ISSUE TITLE
Support setting Content-Security-Policy when creating BrowserWindow

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12909]
**Is your feature request related to a problem? Please describe.**

I'd like to set the CSP directly in the BrowserWindow so it applies to anything loaded in there. In development, I use hot-reloading which uses eval and inline-styles internally, but in production I don't need that, so I want a different CSP for development and production. This is not really possible when setting it as meta tag in the HTML, unless I create multiple HTML files and conditionally load them, which causes extra boilerplate and complications. I also need to allow a port number I only know at runtime (randomly selected), so that's another reason this option would be useful.

**Describe the solution you'd like**

```js
const win = BrowserWindow({
	contentSecurityPolicy: `
		default-src 'none';
		script-src 'self';
		img-src 'self' data:;
		style-src 'self';
		font-src 'self';
	`
});
```

**Describe alternatives you've considered**

Can't think of a better solution than this.

**Additional context**

CSP is important for Electron security and it should be easy to set it.

**Comment by felixrieseberg** [comment]
Hey! Thanks for caring about security and for having a solid idea. I don't think that we'll add a CSP-specific API to the Electron core, for three main reasons:

1) Each API added has to be supported in the future, increasing the burned on our lovely engineers
2) There are non-trivial issues around conflicts (Who gets to override the CSP? What happens if the page defines a CSP?)?
3) You already do that with existing APIs (that's the most important one). They're not super convenient, but a Node module could make this easier. The few 👍 indicate that other people would be interested, so this might be an excellent opportunity for a lil' module!

If you want to have the last say regarding CSP on a page, use https://electronjs.org/docs/api/web-request#webrequestonheadersreceivedfilter-listener. It allows you to override headers before they're given to the page, and thus, also allows you to set custom CSP headers.
