### ISSUE TITLE
Is there a way to use electron with OSMesa?

### ISSUE THREAD

**Issue by daveying** [electron/electron#12933]
Hi, I want to use electron in headless server to generate thumbnail of 3D models.

My idea is: Draw 3D model in canvas using THREE(which essentially uses WebGL) and fetch the image out and store it into disk. I realized this idea in desktop with Graph card installed, but in headless server which has no graph card installed, the WebGLRenderer cannot be created. I found Chrome can run in headless mode with OSMesa as first answer said in [this question](https://stackoverflow.com/questions/39040370/how-do-i-enable-webgl-in-headless-chrome-in-ubuntu). So I'm wondering if electron also can run in headless mode with OSMesa([Mesa](http://www.mesa3d.org))?

Or has anybody knows better way to rendering 3D models in headless server?

**Comment by marcatec** [comment]
You could use Swiftshader
Command Line Switch
--swiftshader-path="<path_to_folder>"

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by daveying** [comment]
Hi @marcatec , would you please be more specific, I'm brand-new in this area, thank you very much.

**Comment by daveying** [comment]
Hi @marcatec , thanks for your direction & clue, and I found this [post](https://medium.com/@mohamedmansour/how-to-run-electron-js-in-software-rendering-headless-49601b87961e), basically the same idea as you said. Now I got sample code working on ubuntu server, thanks again.
