### ISSUE TITLE
Pointer events does not fire on elements positioned over a video element

### ISSUE THREAD

**Issue by albinekb** [electron/electron#12955]
* Electron Version: v2.0.0
* Operating System (Platform and Version): `macOS 10.13.4 (17E199)`
* Last known working Electron version: 1.x

**Expected Behavior**
Pointer evens such as hover and active should work on elements that are absolute positioned over an `<video />` element.

**Actual behavior**
If the video element does not have `pointer-events: none;` the elements that are absolute positioned over it does not fire `:hover` in css, nor click events etc.

**To Reproduce**
```sh
$ git clone git@github.com:albinekb/electron-quick-start.git -b video-pointer-events-bug
$ yarn
$ yarn start
```

**Additional Information**
It works if you set `pointer-events: none` on the underlying video.

**Comment by sethlu** [comment]
@albinekb This also exists as an issue in Chrome. Here are two current workarounds:

- Reorder the DOM elements so that the button comes after the video element,
- *OR* add a z-index (>0) for the absolute-positioned button.

I wouldn't recommend using `pointer-events: none` for the video in general though as user interactions really get suppressed.

**Comment by albinekb** [comment]
Thanks for the workaround, We're re-implementing the context menu so pointer-events: none; is fine in this case. Can you link to the issue in chrome so we can 👍 Should I close this issue here?

**Comment by sethlu** [comment]
@albinekb I should reword the *issue* in Chrome as a different implementation approach. Inspecting the shadow DOM for the video element in Chrome reveals that there are children elements with `position: relative`, since they are also positioned non-statically after your button:

```html
<button style="position: absolute;">button</button>
<video><!-- shadow DOM containing position: relative --></video>
```

Though the `<video>` itself doesn't seem to hide the button since it is statically positioned, it's what's inside that blocks user interaction to the button. The following setup could resolve the issue (so that the elements are no longer `position: relative`, but it's not that easy to do compared to the other options...

![screenshot 2018-05-20 11 54 11](https://user-images.githubusercontent.com/3168941/40282460-88950da6-5c24-11e8-8a81-8d9e689df154.png)
