### ISSUE TITLE
The first button's return value is same to the system close icon's return value of dialog.showMessageBox()

### ISSUE THREAD

**Issue by BruceAn1978** [electron/electron#13092]
* Electron Version:2.0.2
* Operating System (Platform and Version):Win 10 x64
* Last known working Electron version: 2.0.2

`dialog.showMessageBox({type: 'question', buttons: ['Yes', 'Cancel'], noLink: true}, function(btn)
{
  console.log(btn);
});`

**Actual behavior**
When I click the Yes button, the btn's value is 0, when I click the system close icon the btn's value is also 0.

**Expected Behavior**
The btn's value will be different by the click of two source.
How can I to hide the system close icon or to determine the first button and the system close icon click event?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by rizicn** [comment]
add {cancelId: 1} to your options, then close dialog will return 1
