### ISSUE TITLE
Module “iconv-lite” affects Tray

### ISSUE THREAD

**Issue by fdxmslx** [electron/electron#13117]
win7 Electron 2.0.0

Use the iconv-lite module

var ico = path.join(__dirname, 'app/tray/app.ico');
var tray = new Tray(ico);

var iconv = require('iconv-lite');
iconv.decode('', 'gbk');

After decode() is executed, the Tray is gone

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
