### ISSUE TITLE
webContents.printToPdf : Cannot create multiple pages 

### ISSUE THREAD

**Issue by Widus** [electron/electron#13126]
* Electron Version: 2.0.2 
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Generate pdf file including all webContents

**Actual behavior**
Only one page pdf file generated including few components in webContents 

**To Reproduce**
Using Electron-API-Demos sample code

Does anyone can help this? Please give me some advice.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
