### ISSUE TITLE
the web page doesn't display properly

### ISSUE THREAD

**Issue by ChenLongxi666** [electron/electron#13128]
the web page "https://docs.microsoft.com/en-us/dotnet/" doesn't display properly in the electron

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
