### ISSUE TITLE
Device emulation no longer have fitToView attribute !

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#13136]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS Sierra 10.12.6 
* Last known working Electron version: 1.8.0

**Expected Behavior**
Device Emulation should have the option/atrtibute fitToView in order to centralize the view in the webview.

**Actual behavior**
FitToView is no longer *correctly* described in the documentation and stopped working.

**To Reproduce**
Create a webview and try to emulate a device with fitToView option as true, it should no longer work.

**Screenshots**
![error_documentation](https://user-images.githubusercontent.com/4212200/40859925-d162ec26-65b9-11e8-9ca2-7c2956f604d1.png)

**Comment by 4eveRS** [comment]
Also offset parameter is no longer available.

**Comment by 4eveRS** [comment]
The commit that change it was 47d683f0ad406b4f9bc7568a90116885fe6a59ac.

DevTools: do not set visible size while emulating in case of device m… by @alexeykuzmin 

Please bring it back, it was fundamental for my app and probably many others that use the device emulation.

It removed both fitToView and Offset parameters.

**Comment by MarshallOfSound** [comment]
Chromium removed the underlying options, we can't bring it back.

https://chromium-review.googlesource.com/c/chromium/src/+/572222

**Comment by fortinmike** [comment]
Well, we also depended on this a lot!

Is there any alternative to display the page with "forced" dimensions, with good performance?

Performing scaling in the renderer process using CSS causes issues with touch events in certain cases, possibly with other side-effects lurking around the corner (performance issues?). Could content be manually scaled somehow, from the main process? Device emulation is not necessary for us; only the scaling feature is.

Our exact use case is this: We make apps for kiosks whose screens are (almost) always 1920x1080. We don't make our apps' UI responsive because it would be a waste of time (and often wouldn't make sense) in this scenario. Electron's (or Chromium's) previous "fitToView" option was perfect: we could open our apps in multiple smaller windows without messing up the app's 1920x1080 layout and without requiring dev tools to be open all the time, among other uses.

**Comment by willcalderbank** [comment]
We have pretty much exactly the same use case as @fortinmike
