### ISSUE TITLE
How to set round corners to a frameless window?

### ISSUE THREAD

**Issue by ke1vin666** [electron/electron#13179]
Is there any methods to set round corners to a frameless window?

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by DEDaniel** [comment]
@ke1vin666 have you tried using the [transparent](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) option? I created a quick repo, maybe this will fit your needs - check it here [electron-frameless-rounded](https://github.com/DEDaniel/electron-frameless-rounded)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
