### ISSUE TITLE
BrowserWindow.loadFile triggers save dialog

### ISSUE THREAD

**Issue by pronebird** [electron/electron#13170]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.4 (17E202)
* Last known working Electron version: not aplicable

**Expected Behavior**

Calling `BrowserWindow.loadFile('')` with invalid input should not trigger a save dialog.

**Actual behavior**

Calling `BrowserWindow.loadFile('')` with empty file name causes save dialog pre-filled with `default_app.asar` to appear 😱 .

**To Reproduce**

You can reproduce this issue using interactive shell.

```
$ electron -i
> var electron = require('electron');
> var BrowserWindow = electron.BrowserWindow;
> var window = new BrowserWindow({ width: 320, height: 480, show: false });
> window.loadFile('');
true
> objc[20375]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff92df3c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x112d92cd8). One of the two will be used. Which one is undefined.
```

**Screenshots**

Upon request.

**Additional Information**

None

**Comment by MarshallOfSound** [comment]
@pronebird I can't seem to repro this locally, `loadFile('')` just loads nothing on my machine (like it fails to load because it tries to load a directory).  To be honest this appears to just be "invalid input" but the `loadFile` method shouldn't be doing fs checks to see if the HTML path is valid, that is something users should be doing IMO
