### ISSUE TITLE
VoiceOver does not echo characters as input typed in to input fields in Electron apps

### ISSUE THREAD

**Issue by BrendanMcK** [electron/electron#13203]
* Electron Version: 2.0.0
* Operating System (Platform and Version): OSX High Sierra 10.13.5
* Last known working Electron version: None

**Expected Behavior**

On regular web pages (Chrome, Safari) and system apps (eg. Notes, Word), as you type into an input area with VoiceOver running, VoiceOver echoes characters as they are typed. For example, if you type in "the", VO will announce "t", "h", "e" as each key is pressed

**Actual behavior**

With input fields in electron-based apps, however, VO does _not_ echo the input as it is typed.

Simplest repro is to just add an <INPUT /> tag to the electron-quick-start index.html.

**To Reproduce**

This repros on any type of input field: INPUT, TEXTAREA, or contenteditable elements.

Repro available at https://github.com/BrendanMcK/electron-quick-start/tree/repro-vo-echo
clone, npm i, npm run start.

**Other information**

VoiceOver _does_ announce the current character as the cursor keys are used to move the caret within the already-entered text; this suggests that there's some support working here; but it's silent as the characters are initially entered. 

VoiceOver (like most screenreader) has user settings to control how it echoes typed input; have confirmed that this is set to echo characters as they are typed.
![image](https://user-images.githubusercontent.com/1754373/41185261-50a91dc6-6b3b-11e8-8530-2c1d1ce5b597.png)

**Comment by mshoho** [comment]
Is there any progress on this? The text input scenario is very broken for the screen reader users. The interesting part is that it works normally in Chrome.

**Comment by alexeykuzmin** [comment]
@mshoho Still broken in the Electron 3?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by SaadAttieh** [comment]
As far as I can tell, this is still broken.  In fact, when setting voiceover to echo entered text word by word, instead of character by character, the output is always the phrase "newline".  If this has been fixed then apologies but I have not observed any electron based app with which text entry is working correctly.  

Best way to test the word input is (with VO activated), press control option v to bring up settings, press "t" for typing echo,  use the up/down arrow keys to  move to words then press enter.  Now when you type, you should hear the entered word echoed every time a space is inserted.  However, instead, all that is heard is "newline".

**Comment by nornagon** [comment]
Thanks for the repro steps, @SaadAttieh. I can confirm this is still happening in Electron 7.1. However, I'm seeing the same issue in Chrome itself. It looks like this is being tracked upstream: https://crbug.com/869964, however that bug has been merged into another bug that's not publicly viewable.
