### ISSUE TITLE
How to open native windows conext menu for file/directory

### ISSUE THREAD

**Issue by PragmaticEd** [electron/electron#13224]
Is it possible to open windows native context menu for specific file/directory ?

Lets say, for example, i have app:

###### package.json
```json
{
  "name": "app-namer",
  "version": "0.0.1",
  "main": "app.js",
  "scripts": {
    "start": "electron app.js"
  },
  "devDependencies": {
    "electron": "^2.0.2"
  }
}

```

###### app.js
```js
const {app, BrowserWindow} = require('electron');

const ROOT = __dirname;

app.on('ready', function () {
 let win = new BrowserWindow({
    width:  1200,
    height: 600,
    show:   false
  });
  win.setMenu(null);
  win.loadURL('file://' + ROOT + '/main.html');
  win.on('ready-to-show', function () {
    win.show();
    win.focus();
  });
});

```
###### main.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
  </head>
  <body>
     <ul>
        <a href="C:/Users">Users</a>
        <a href="C:/Windows">Windows</a>
        <a href="C:/test file.txt">test file.txt</a>
     </ul>
  </body>
</html>
```

How do i open windows native context menu, when clicking on link of a file or directory?

By windows native context menu, i mean this:

![111](https://user-images.githubusercontent.com/19263525/41277984-62eaf3e4-6e31-11e8-94eb-1aeb06c94cfd.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by PragmaticEd** [comment]
@sofianguy can you covert this to feature request?

**Comment by aicioara** [comment]
+1
