### ISSUE TITLE
Render thread crashes when accessing stream from video element

### ISSUE THREAD

**Issue by card-b** [electron/electron#13242]
* Electron Version: latest
* Operating System (Platform and Version): MacOS 10.13.3
* Last known working Electron version: 

**Expected Behavior**
Accessing stream from video element for webrtc call should not crash (works in Chrome on web)

**Actual behavior**
Any call to videoElement.captureStreamI() causes white screen crash if video element is streaming webcam. Experimental Features is set to true already.

**To Reproduce**
Start electron, webcam will stream to video element, hit the "test" button. Page will start, call getusermedia to stream camera to video element, tapping the 'test' button will call captureStream on the video element, app will white screen with no errors and DevTools will disconnect. This does however work fine in Chrome.

https://github.com/adam-denny/electron-quick-start

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/adam-denny/electron-quick-start
$ npm install
$ npm start || electron .
```

**Comment by groundwater** [comment]
I tried working on this with @caramelmagic, and we can confirm this in the `2.0.x` release line.

This appears to be fixed in the `3.0.x` release line. Can you try your application with `3.0.0-beta.4`? There are a few outstanding instabilities with the latest 3.0.x beta, but at least your app would work when `3.0.0` becomes stable.
