### ISSUE TITLE
Select box near top of screen opens upwards, leaving little space for the items (and a scrollbar)

### ISSUE THREAD

**Issue by DanTup** [electron/electron#13279]
I [raised this against VS Code](https://github.com/Microsoft/vscode/issues/52194), but they advise it's Electron's doing. When I go to select a debug session and there are several, the dropdown menu grows upwards but there's limited space on the screen so it ends up being quite difficult to use.

* Electron Version: 1.7.12
* Operating System (Platform and Version): macOS High Seirra
* Last known working Electron version: Unknown

**Expected Behavior**
Drop-down lists near the edge of the screen should expand away from the edge of the screen.

**Actual behavior**
Drop-down renders upwards when at the top of the screen, making a tiny scrollable menu.

**To Reproduce**
Open VS Code; and start several debugging sessions, then open the drop-down that lets you select between them.

**Screenshots**
![screen shot 2018-06-18 at 1 03 26 pm](https://user-images.githubusercontent.com/1078012/41534917-3d68229c-72f8-11e8-98d9-bebdb9bc7428.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by DanTup** [comment]
I've edited my message to match the template. I didn't make the repro steps too detailed because really you can repro this with any project, so it makes sense to use whatever you already have.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by DanTup** [comment]
Sorry for the delay. This still happens in the latest version of VS Code:

<img width="412" alt="screenshot 2019-01-15 at 21 32 30" src="https://user-images.githubusercontent.com/1078012/51211338-19d26980-190d-11e9-95fa-a3a256248155.png">

I believe this is Electron v2:

<img width="631" alt="screenshot 2019-01-15 at 21 33 15" src="https://user-images.githubusercontent.com/1078012/51211373-3373b100-190d-11e9-9f30-e88083abee8d.png">

I recreated it in VS Code by creating a compound launch config that allows launching many debug sessions together, then this dropdown appears to switch between them during debugging.

**Comment by DanTup** [comment]
@sofianguy in case you missed it - this is still an issue (see above).

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by DanTup** [comment]
(Perhaps unsurprisingly), this still occurs in 4.2.7.

<img width="229" alt="Screenshot 2019-08-14 at 09 02 47" src="https://user-images.githubusercontent.com/1078012/63004477-67e32780-be72-11e9-9c6a-89029a084b08.png">

**Comment by jijowork2018** [comment]
Any solution for this? This issue also arises in case of auto-completes as well

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by DanTup** [comment]
@sofianguy I'm not sure what to do here. The bug keeps being ignored and then after a while "closed because this version is no longer supported". I confirmed it's still an issue in latest, it was ignored more and after a while, closed for the same reason.

I suspect that if I test it again and raise an issue, it will probably be ignored and then closed when that version is not supported. This doesn't seem like a good use of my time.

**Comment by nornagon** [comment]
@DanTup the best way to get something resolved is to produce a self-contained reproduction, preferably using [Electron Fiddle](/electron/fiddle). There are nearly 1,000 issues on this tracker, and at least 20 new ones per day, so you might find it understandable that it is a challenge to triage and address them all. We are a small team with limited resources. The more you can do to help us narrow down where the issue is, the more likely it is we will be able to address it.

I'm reopening and retagging this because you reported that it's still present on the latest version of Electron, but I'm adding the `blocked/need-repro` tag because VS Code is too large a project for us to be able to isolate the reported issue in a reasonable timeframe.

**Comment by bpasero** [comment]
@nornagon it reproduces in Electron's Fiddle app itself:

![image](https://user-images.githubusercontent.com/900690/111264946-adf10600-8628-11eb-93c4-8bbbf0426801.png)

Just place the window above the dock and right click.

**Comment by DanTup** [comment]
@nornagon @bpasero thanks! :-)

**Comment by bpasero** [comment]
This still reproduces for me in VSCode using Electron 11.4.1

![Uploading image.png…]()


//cc @deepak1556

**Comment by nornagon** [comment]
@bpasero do you have multiple monitors perchance?

**Comment by bpasero** [comment]
No, just a single external monitor with 2K resolution (2560x1440).

**Comment by scunliffe** [comment]
Just going to add my screenshot here... as I posted this frustration on Twitter: https://twitter.com/scunliffe/status/1456376064335286277 and in the replies I was prompted to file a bug with vscode, but it sounds like it is actually an electron issue still (Nov, 2021) 
![vscode-electron-menu-truncating](https://user-images.githubusercontent.com/1163989/140523190-a8da8a8e-dee0-43c1-81e6-b1e2a40026cf.jpg)

Its frustrating as I encounter this bug ~once a month~ when vscode updates :-(

**Comment by bpasero** [comment]
How can we move this forward?

//cc @deepak1556

**Comment by zcbenz** [comment]
@bpasero This seems to be the expected behavior on macOS, where the selected item is expected to appear just under the cursor.

You can try this html in Safari and Chrome:

 ```html
<body>
  <select name="select">
    <option value="value1">Value 1</option>
    <option value="value2">Value 2</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3">Value 3</option>
    <option value="value3" selected>Value 3</option>
</select>
</body>
```

<img width="344" alt="スクリーンショット 2022-08-02 10 02 35" src="https://user-images.githubusercontent.com/639601/182269926-c46cebbd-7a49-47e4-b52c-020ca2872a61.png">
<img width="203" alt="スクリーンショット 2022-08-02 10 04 05" src="https://user-images.githubusercontent.com/639601/182269951-11922070-f52c-44ac-a32e-0e46672a551e.png">

**Comment by bpasero** [comment]
@zcbenz there is nothing selected in our case though, and in fact the menu opens fully when VS Code window is fullscreen and scrolls otherwise:

**Fullscreen:**

<img width="366" alt="image" src="https://user-images.githubusercontent.com/900690/182293893-f3fe939c-662f-4534-be01-100eba3e5bf6.png">

**Normal**

<img width="367" alt="image" src="https://user-images.githubusercontent.com/900690/182293931-d4f9672f-f166-4d15-8902-562854bc97d4.png">

**Comment by bpasero** [comment]
Finder also does not reproduce in a similar case:
![Recording 2022-08-02 at 06 49 08](https://user-images.githubusercontent.com/900690/182294098-7df38bf1-a05e-45d8-b9ff-65b30f1ecb26.gif)

**Comment by zcbenz** [comment]
This issue is about select tag, which seems to be expected behavior on macOS and I intend to close it.

On the issue of VS Code's menu, I think it is a different problem and should be discussed in a separate issue.

Also I'm unable to reproduce with a simple context menu app:

```html
<body>
  <script type="text/javascript" charset="utf-8">
    const {ipcRenderer} = require('electron')
    window.addEventListener('contextmenu', (e) => {
      e.preventDefault()
      ipcRenderer.send('show-context-menu')
    })
  </script>
</body>
```

```js
const {app, ipcMain, BrowserWindow, Menu} = require('electron')

let win
app.on('ready', async () => {
  win = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      sandbox: false,
      contextIsolation: false,
    },
  })
  win.loadFile('index.html')
})

const template = []
for (let i = 0; i < 20; ++i)
  template.push({label: 'MenutItem ' + String(i)})
const menu = Menu.buildFromTemplate(template)

ipcMain.on('show-context-menu', (event) => {
  menu.popup(BrowserWindow.fromWebContents(event.sender))
})
```
<img width="255" alt="スクリーンショット 2022-08-02 14 10 15" src="https://user-images.githubusercontent.com/639601/182296513-038da819-56c5-448a-9beb-78dcbfd8f090.png">

**Comment by bpasero** [comment]
@zcbenz but my issue was closed as duplicate of this one: https://github.com/electron/electron/issues/14261

**Comment by zcbenz** [comment]
It was mistake, I have reopened https://github.com/electron/electron/issues/14261. But still we need a way to reproduce with minimal code, the issue seems to be related to how VS Code shows the context menu.

**Comment by bpasero** [comment]
Thanks, I will try to come up with a repro.
