### ISSUE TITLE
Google oauth in system browser

### ISSUE THREAD

**Issue by ivandroid** [electron/electron#13347]
Since Google blocks oauth requests made via embedded browsers, I would like to login to a Google account via the system browser and send the received access token to a running electron application. I tried the following:

1. Opened the Google authorization URL in my system browser via `shell.openExternal(<URL>)`.
2. Successfully logged in to a Google account and got an access token provided in the redirect_url.
3. The redirect_url is actually my localhost. So I cannot redirect the access token to the electron application.

How can I send the access token to a running electron app?

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
