### ISSUE TITLE
Should GPU acceleration be off by default?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#13368]
The [offscreen renderering](https://electronjs.org/docs/tutorial/offscreen-rendering) page says:

>Software output device
This mode uses a software output device for rendering in the CPU, so the frame generation is much faster, thus this mode is preferred over the GPU accelerated one.

>To enable this mode GPU acceleration has to be disabled by calling the `app.disableHardwareAcceleration()` API.

It seems kind of odd that GPU acceleration is on by default considering that the "Software output device" mode is preferred.

Should it be disabled by default, and should we replace `disableHardwareAcceleration` with `enableHardwareAcceleration`?

**Comment by pronebird** [comment]
How’s is CPU rendering can be faster than GPU?

**Comment by pronebird** [comment]
@pushkin- alright, well I think if you run some animations you'll see the entirely opposite effect.

**Comment by pushkin-** [comment]
@pronebird  Yeah, quite possibly. My app doesn't use many animations and doesn't benefit much from the GPU acceleration. I was wondering why the Electron team says that the CPU mode is faster, but then disables it by default. Seems like GPU acceleration should be opt-in.

**Comment by pronebird** [comment]
The wording is definitely wrong and documentation lacks explanation.

**Comment by thomasjo** [comment]
_Since I haven't studied the Chromium source code in detail I might be wrong, but the following explanation is based on the code I have seen, and from my daily experience with GPU programming._

@pushkin- That specific piece of documentation is specifically related to offscreen rendering, and the example is rendering a web page into a bitmap. All necessary information/data related to the web page, and potential changes happening due to scrolling, animations and so on, are located in CPU-bound RAM. Because of this, to render the page on the GPU, all data would need to be copied to and from the GPU for every single frame. This would lead to a drop in performance due to the data transfer dwarfing the actual computational effort. Note that this is different from the default GPU-acceleration in Chromium, since there is much less data transfer. The necessary data remains in GPU memory for longer periods of time, and the GPU acceleration is therefore no longer limited by the PCIe bus transfer speed, but is instead limited by the GPU and the kernel it is executing.

Hopefully this clears up the misunderstanding, and hints at why GPU acceleration is on by default.

**Comment by baconbrad** [comment]
Aside from the topic of speed we have found Hardware Acceleration to be glitchy. Especially with our Windows 7 machines. We don't know the root of the problem. It could be the OS, the video card, the drivers, whatever. But `app.disableHardwareAcceleration()` basically has to be set or we get reports of weird visual bugs. Any change in performance has not been noticed or reported to us from our end users.

**Comment by pushkin-** [comment]
@baconbrad Alright, but that doesn't exactly address my question (maybe you were responding to a comment above). If it has to be set, why not disable it by default and have an `enableHardwareAcceleration` API?

**Comment by brenca** [comment]
Hey guys!

I'd like to emphasize that the fact that `GPU` accelerated rendering is slower only applies to `offscreen` rendering, so as per why isn't hardware acceleration is opt-in instead of opt-out - `offscreen` rendering is an optional switch of the `BrowserWindow`, but `app.disableHardwareAcceleration()` affects the whole app, so in case of most people - who don't use `offscreen` rendering at all - this would be a possible performance downgrade.

As per why GPU rendering is slower - when you use the `BrowserWindows` with `offscreen` enabled, you get a `paint` event you can subscribe to - which gives you every rendered frame as a `NativeImage`. This means that the rendered frame has to leave the GPU memory at one point, which is a very costly operation, and makes GPU rendering rather slow. If you render with the CPU, the frames never have to go near the GPU (and GPU memory), so the rendering goes much faster.

**Comment by xgdgsc** [comment]
Another perspective regarding disable it by default might be people encounter hard to reason freezes with bad gpu drivers like this  https://github.com/signalapp/Signal-Desktop/issues/2442 .

**Comment by frochi42** [comment]
Please note that I'm also fighting with this problem (using "MS teams" and "slack" in an linux ubuntu 18.04 environment). These apps are simply not usable. The solution with app.disableHardwareAcceleration() obviously only works when this code is included in the app's code. But it must be also possible to switch it at startup time (e.g. via ENV-variable of configuration file).
