### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Tahawahid** [electron/electron#13419]
when I tried to add an image or any file from external CSS file using **url() method** file it gives me this error "Failed to load resource: net::ERR_FILE_NOT_FOUND", it gives me the **URL:file:///C:/Users/M.M/OneDrive/Documents/MyProtfolio/imagestaha.jpg**
instead of **"file:///C:/Users/M.M/OneDrive/Documents/MyProtfolio/images/taha.jpg"** which is the actual path, so please can anyone help me to solve this problem

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by Tahawahid** [comment]
what is meant by electron version?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
