### ISSUE TITLE
Error : Cannot find module './src/background/reducers/index'

### ISSUE THREAD

**Issue by saran481** [electron/electron#13424]
* Electron Version:2.0.1
* Operating System (Platform and Version):
* Last known working Electron version: 

iam trying to pass the function/variable from external js files to main.js 
main.js

````
const thunk = require('redux-thunk')
const { BrowserRouter } = require('react-router-dom')
const { routerMiddleware } = require('react-router-redux')`
const electron = require('electron')
const reducers = require('./src/background/reducers/index')

const logger = createLogger({
  collapsed: true,
})
const reduxRouterMiddleware = routerMiddleware(BrowserRouter)
const middlewares = [
  reduxRouterMiddleware,
  thunk,
  logger, 
]
console.log('coming in ')
const store = createStore(
  reducers,
  applyMiddleware(
    ...middlewares,
    forwardToRenderer 
  )
)

````

 i need to use reducers method in main.js which is in index.js ....for reducer i am using absolute path but it is showing module not found. Can someone help me out with this

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
