### ISSUE TITLE
How to disable esc button on windows

### ISSUE THREAD

**Issue by jefferybai** [electron/electron#13477]
* Electron Version: 2.0.0
* Operating System (Platform and Version):  windows 7
* Last known working Electron version: 2.0.0

**Expected Behavior**

When I run the following code：

`globalSortcut.register('Esc', function() {});
`

I want to not trigger any action when clicking the esc button

The code is normal on mac os

**Actual behavior**

But in windows will trigger the exit behavior

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
