### ISSUE TITLE
Electron.ContextMenuParams doesnt account for Zoom Factor

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#13471]
* Electron Version: 2.0.3
* Operating System (Platform and Version): MacOS
* Last known working Electron version: 2.0.3

**Expected Behavior**

I would expect to be able to create a "position: fixed" div at the `Electron.ContextMenuParams.x` `Electron.ContextMenuParams.y` location returned from the context menu and that div should appear right were I clicked.

```ts
electron
  .remote
  .getCurrentWebContents()
  .addListener(
    "context-menu",
    (event: Electron.Event, params: Electron.ContextMenuParams) => {
      event.preventDefault()
      const rect = {
        bottom: params.y,
        top: params.y,
        height: 0,
        left: params.x,
        right: params.x,
        width: 0,
      }
  })
```

**Actual behavior**
When I set the zoom factor on the webContents, this x-y position becomes offset by the zoom factor.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
`Electron.ContextMenuParams` will give you the x/y pixel coordinates in the window. It's up to you to convert those coordinates into something that makes sense in the document.
