### ISSUE TITLE
Notifications / Electron Architecture

### ISSUE THREAD

**Issue by pauljakobwhite** [electron/electron#13506]
Hello,

I'm hoping for some general guidance... it seems when using electron notifications (either with the html5 api in from within renderer process or the notification module inside the main process) each notification fires off three times, resulting in three identical notifications and an annoyed user. My best guess is this is due to electron's multi-process architecture (I can see three instances of my app running). 

Luckily on macOS (if using the html 5 api) the OS is smart enough to recognize the 3 notifications are identical and collapses them into one, not so lucky if the notifications are coming from the main process using the notification module, and likewise on windows from both main and render processes. 

I could get into the details of how I'm setting up notifications, but this doesn't seem directly related to notifications rather more to the electron architecture. Anyone have any thoughts or wisdom on how I can work around this?

* Electron version: 1.8.4
* Operating system: macOS/Windows (Build only)

### Expected behavior

Call notification... e.g.:

**Render Process**
```
let notify = new Notification('Notification Title', {
  body: 'notification body'
});
```

*or*

**Main Process**
```
let notify = new Notification({
  title: 'Notification Title',
  body: 'notification body'
});
```

... see one desktop notification.

### Actual behavior

Three desktop notifications are fired.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
It sounds like there might be an issue in your app causing duplicated notifications.
