### ISSUE TITLE
electron . exited with code 3221225477

### ISSUE THREAD

**Issue by manndave** [electron/electron#13518]
* Electron Version: 2.0.3
* Operating System (Platform and Version): Win 8.1
* Last known working Electron version: ?

**Expected Behavior**
Expect program to run without crashing :-)

**Actual behavior**
Intermittently, while developing my Electron-based application, launched from the VSCode terminal, it will just crash and the error message shown in the title will be displayed in the VSCode terminal window.  It happens maybe 1% of the time, but enough so that I can't release this product until I figure out what's going on and fix it.  

**Additional Information**
I've seen #10814, #6437, and #3570 but those are all related to missing network connections or something similar.  Mine is not.  Network connections all available at all times.  I can launch and run the app for a few seconds (5-10?) before it crashes.

Any ideas?

Thanks.

**Comment by aco7342** [comment]
* Electron Version:   electron-node-red@0.17.5 
                                Node-RED version: v0.18.7
                                Node.js  version: v8.2.1
                                Dashboard version 2.9.5 started at /ui

* Operating System (Platform and Version): Windows_NT 10.0.17134 ia32 LE
* Last known working Electron version: 

**Expected Behavior**
stand-by application does not fall

**Actual behavior**
Stand-by application after 10 minutes fall

**To Reproduce**


You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.


**Screenshots**
If applicable, add screenshots to help explain your problem.

C:\Developer\electron-node-red>
C:\Developer\electron-node-red>time
The current time is: 10:47:05,66
Enter the new time:

C:\Developer\electron-node-red>npm start

> electron-node-red@0.17.5 start C:\Developer\electron-node-red
> electron main.js


Setting UserDir to C:\Developer\electron-node-red

Setting httpStatic to C:\Developer\electron-node-red\public

24 Jul 10:47:24 - [info] Log App Version:1.8.7
24 Jul 10:47:24 - [info] Url:http://localhost:1880/ui/
24 Jul 10:47:25 - [info]

Welcome to Node-RED
===================

24 Jul 10:47:25 - [info] Node-RED version: v0.18.7
24 Jul 10:47:25 - [info] Node.js  version: v8.2.1
24 Jul 10:47:25 - [info] Windows_NT 10.0.17134 ia32 LE
24 Jul 10:47:26 - [info] Loading palette nodes
24 Jul 10:47:37 - [info] Dashboard version 2.9.5 started at /ui
24 Jul 10:47:39 - [warn] ------------------------------------------------------
24 Jul 10:47:39 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
24 Jul 10:47:39 - [warn] [node-red/tail] Not currently supported on Windows.
24 Jul 10:47:39 - [warn] ------------------------------------------------------
24 Jul 10:47:39 - [info] HTTP Static    : C:\Developer\electron-node-red\public
24 Jul 10:47:39 - [info] User directory : C:\Developer\electron-node-red
24 Jul 10:47:39 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
24 Jul 10:47:39 - [info] Flows file     : C:\Developer\electron-node-red\flows.json
24 Jul 10:47:39 - [warn] Existing credentials file is not valid json
24 Jul 10:47:39 - [debug] loaded flow revision: 00fa88ef4ea1d179d7ce5d13b9472c79
24 Jul 10:47:39 - [debug] red/runtime/nodes/credentials.load : no user key present
24 Jul 10:47:39 - [debug] red/runtime/nodes/credentials.load : using default key
24 Jul 10:47:39 - [debug] red/runtime/nodes/credentials.load : keyType=system
24 Jul 10:47:39 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

24 Jul 10:47:39 - [trace] runtime event: {"id":"runtime-state","retain":true}
24 Jul 10:47:39 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"00fa88ef4ea1d179d7ce5d13b9472c79"},"retain":true}
24 Jul 10:47:39 - [info] Starting flows
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : global
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : 41f61d2.fbe09e4
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : ea4d1fbb.86567
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : 92690cc.eb2d7f
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : 63617253.420c2c
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : e00afa13.e21c38
24 Jul 10:47:39 - [debug] red/nodes/flows.start : starting flow : 299fb3f4.a3daac
24 Jul 10:47:39 - [info] [socketio-config:16a92bda.91f634] Created server bind to Node-red port
24 Jul 10:47:39 - [trace] runtime event: {"id":"runtime-state","retain":true}
24 Jul 10:47:39 - [info] Started flows
[2018-07-24T14_15_47_219Z-debug.log](https://github.com/electron/electron/files/2224030/2018-07-24T14_15_47_219Z-debug.log)
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! electron-node-red@0.17.5 start: `electron main.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the electron-node-red@0.17.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\antonio carlos\AppData\Roaming\npm-cache\_logs\2018-07-24T14_15_47_219Z-debug.log

C:\Developer\electron-node-red>time
The current time is: 11:16:11,24
Enter the new time:
C:\Developer\electron-node-red>

**Additional Information**
[2018-07-24T13_31_33_001Z-debug.log](https://github.com/electron/electron/files/2223954/2018-07-24T13_31_33_001Z-debug.log)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
