### ISSUE TITLE
Close context menu for tray

### ISSUE THREAD

**Issue by pjebs** [electron/electron#13523]
I have a tray icon.

When the user is logged in, I have a context menu for the tray.
When the user is logged out, I don't have a context menu.

The user can get logged in/logged out at any time (asynchronously).
When that happens, I need to get rid of the context menu (in the case of user getting logged out).

Currently I pass `tray.setContextMenu(new Menu)` to remove the context menu. [NB: passing null does not remove the context menu].

The bug is that __if__ the context menu is open, then if I attempt to remove it, it crashed electron.

The workaround is to force the context menu closed before I attempt to remove it.

**There is no API that I am aware of to force the context menu closed.**

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. If you could go back and fill the fields of the "feature request" template that were deleted we can more efficiently determine what would need to be done.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
