### ISSUE TITLE
when debug in vscode, it gives an error

### ISSUE THREAD

**Issue by vfan** [electron/electron#13544]
I do not kown where the title comes from.

![image](https://user-images.githubusercontent.com/1477088/42204033-202bc1d4-7ed3-11e8-8944-8dce34a567b2.png)

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
