### ISSUE TITLE
onBeforeRequest details.webContentsId dissapears in release

### ISSUE THREAD

**Issue by ancodeUDW** [electron/electron#13547]
* Electron version: 2.0.3
* Operating system: release in Macintosh

### Expected behavior
onBeforeRequest should return the information of the webContent that has created the request. That information is inside details.webContentsId 

### Actual behavior
onBeforeRequest returns it when workign in development version and with the production on, however, when doing a package to create a release onBeforeRequest doesn't return the webContentsId of the webContent that did the request

### How to reproduce

Hello. 

I am working in a project in where I have several webviews to load different websites that share the same session (of the type "persist:id"). I have developed an adblock system that works at the level of the webview that works in the following way:

```
let mySession = session.fromPartition('persist:id');

session.webRequest.onBeforeRequest(['*://*./*'], (details, cb) => {
         if (adBlockActiveForSession(details.webContentsId)){
                  // adblock operations
         }
}

```
This works in the development and with production flag. However, when I create a realease, it doesnt work. I noticed that, in the release, details doesnt have "webContentsId". Also I have check the documentation https://electronjs.org/docs/api/web-request and it says that the webContentsId is optional

when webContentsId can be access in details and when it can't? why it works in development but not when I create a release?

Thank you

note: In order to insure that the webview has its webContent id, before loading an url I load an empty site, and after dom ready, I start to do the real url loadings.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
