### ISSUE TITLE
app.getName() don't set name in package.json when don't use `electron .` command

### ISSUE THREAD

**Issue by HyunmoAhn** [electron/electron#13552]
* Electron Version: v1.7.1
* Operating System (Platform and Version): Mac OS Sierra 10.12.5
* Last known working Electron version: v1.7.1 

**Expect behavior**
When I using `electron app/main.js` command.
`app.getName()` is `[name setting package.json]`

**Actual behavior**
When I using `electron app/main.js` command.
`app.getName()` is `electron`

**To Reproduce**

```
// package.json
"name": "oh-my-desk",
"main": "app/main.js"
```
When I run electron app using `electron .` command.
`app.getName()` that printed my app is "oh-my-desk" 

But, When I run electron app using `electorn app/main.js`.
`app.getName()` is "electron".

I think, In case `electron .` electron get `name` and `main` in `package.json`. 
Otherwise electron doesn't get anything in `package.json`.

**Is It Bug?**  
If not, thank you for recommending documentation related to the above

**Comment by MarshallOfSound** [comment]
@HyunmoAhn This is expected behavior.  In one case you are launching an app based on a JS file `app/main.js`, the other you are launching based on a directory.

In the case where you launch an Electron app from a directory the `package.json` file is located and used to identify the entry JS file into your app (the `main` field) and also identify some app metadata.  When you launch based on a JS file directly we don't load a package.json file as we have no idea where to look 👍 

This will never be a problem when packaged for production as most packagers will set things up so that Electron reads your package.json when loading `app.asar`
