### ISSUE TITLE
If i set a partition: 'name',The new window will couse crash;

### ISSUE THREAD

**Issue by suoc** [electron/electron#13572]
* Electron version: 2.0.2
* Operating system: win10

let win = new BrowserWindow({
    width: 800,
    height: 600,
    fullscreen: false,
    frame: true,
    webPreferences: {
        partition: '2'
    }
});

If i click an a tag that target="_blank" <a target="_blank">,the app will crash.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
