### ISSUE TITLE
Need help. webRequest.onCompleted listener. Remove the listener.

### ISSUE THREAD

**Issue by KorobkaVadim** [electron/electron#13579]
* Electron Version: 1.8.7
* Operating System (Platform and Version): Win32

**Expected Behavior**
I want to be able to remove the listener.

**Actual behavior**
I can't remove the listener.

**To Reproduce**
```js
const listener = session.defaultSession.webRequest.onCompleted(filter, (details, callback) => {
    console.log('url', details.url);
})

function clear() {
    console.log('listener', listener); // listener undefined
    listener();
}
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
