### ISSUE TITLE
New parameter for the app.GetFileIcon() method

### ISSUE THREAD

**Issue by rwnkl** [electron/electron#13590]
Because the app.getFileIcon () function runs asyncron,
please introduce a new parameter as a context, which will be passed to the callback function

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by rwnkl** [comment]
In a loop, if the app.getFileIcon () method is called multiple times under changing circumstances, its context is unknown in the callback function because the method is executed asynchronously.

It would be useful for the method to introduce another parameter, as a kind of user context, which is returned unchanged to the callback function. Thus, in the callback function, the user can uniquely identify the calling app.getFileIcon () method and its context.

**Comment by MarshallOfSound** [comment]
This is a problem you can solve yourself in JS

```js
for (const iconPath of items) {
  app.getFileIcon(iconPath, ((contextIconPath, error, icon) => {
    console.info(contextIconPath);
  }).bind(null, iconPath));
}
```

See the [`bind` documentation](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) for how to use this technique
