### ISSUE TITLE
Is there any issues for Electron to run inside IIS windows 10 ? (using Nightmare js). I am sorry not sure if this is a bug.

### ISSUE THREAD

**Issue by jubishkammily** [electron/electron#13606]
* Electron Version: Electron v1.8.7
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: v1.8.7

**Expected Behavior**

**Actual behavior**
The application should run with IIS.

**To Reproduce**
Host the electron application in .net core rest  API using node services with node js in the IIS

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
