### ISSUE TITLE
Unable to modify pdf_viewer_resources.pak

### ISSUE THREAD

**Issue by ThomasODev** [electron/electron#13676]
Hello,
I'm using electron for a web-based app (using React). One of the feature in the app is to print pdf.
Basically when you click on the print button, user's input (var) are filling an odt and then generates a pdf. The return of the function is the url of the pdf, then I'm using `window.open(url)` to show up the pdf. But actually with electron I can't print this pdf. (The print icon is missing)

I tried on Chrome and the print icon is present and works perfectly. I searched into electron files and found **pdf_viewer_ressources.pak**, I think the problem can be solved here.

Indeed I found this:

`          
`

I tried to uncomment this but the viewer doesn't work anymore.
I think there is something with checksum or something like that.

My questions are:
**- Is there a way to edit this file or remove checksum (if it exist)?**
**- If not, how can I manage that** (I tried addExtensions of pdf.js to change the viewer and it don't work either. Note that I changed my electron version for that test because addExtension is not included in v1.6.6)

_Note: I'm using Electron v1.6.6_

**Chrome:**
![chrome](https://user-images.githubusercontent.com/30237715/42758836-22a28402-8905-11e8-9d3e-f25a4d608e66.png)

**Electron**
![electron](https://user-images.githubusercontent.com/30237715/42758838-22faaa6a-8905-11e8-8d44-b2263d42e4bc.png)

**Comment by nornagon** [comment]
the `.pak` file is generated as part of the libcc build, so you'll need to regenerate it there.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by hendellacardoso** [comment]
Hello, did you find a solution? I'm with the same problem, if you solved please tell me how?
