### ISSUE TITLE
can not start-up application with no network

### ISSUE THREAD

**Issue by Neil-Pan** [electron/electron#13699]
* Electron Version:2.0.2
* Operating System (Platform and Version):winsows 7 64 / windows 8 64/window 10
* Last known working Electron version: 1.8.4

**Expected Behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by timfish** [comment]
@Neil-Pan You haven't filled out the issue template, you've just left the placeholders...

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
