### ISSUE TITLE
app paths not set, package.json not loaded when loading index.js

### ISSUE THREAD

**Issue by Lombra** [electron/electron#13719]
Running an app by providing `index.js` as the argument (as opposed to a folder) is supposed to be supported, but doing this fails to load the package.json file and set some app paths and other stuff. This seems to be due to Electron then looking for `index.js\package.json`.

https://github.com/electron/electron/blob/c8030a0f2aaf299f823f8a7dc68e29e69abb102f/default_app/main.js#L256

**Comment by MarshallOfSound** [comment]
> This seems to be due to Electron then looking for index.js\package.json.

This is not a bug, rather expected behavior.  If you want to load information from the `package.json` launch based on the directory not a JS file.  Given a JS file it's impossible to know which `package.json` to infer values from, especially considering lots of projects have multiple package.json files.

Basically just use `electron .` instead of `electron index.js`

**Comment by Lombra** [comment]
Alright, thanks for clearing that up.
