### ISSUE TITLE
webview can't navigate to other page

### ISSUE THREAD

**Issue by wellbeck190** [electron/electron#13712]
* Electron Version: 3.0.0-beta.3
* Operating System (Platform and Version): Mac OSX 
* Last known working Electron version: 2.0.4

**Expected Behavior**
Using webview normally
**Actual behavior**
When navigating to other page, everything is stopped, can't interacting with page

**Comment by sofianguy** [comment]
can you provide us with steps to reproduce this issue?

**Comment by felipemullen** [comment]
I have the same issue, noticed it after upgrading from <2.0 to 3.x latest. 

I have a `<webview>` tag in my page that acts as the main contents of my main app, and it loads sub applications that can be written with any framework.

Before upgrading, all I had to do was change the `src` tag of the webview and the page would change accordingly. Since the upgrade I noticed the DOM loads in the inspector when switching pages, but the actual rendering freezes completely.

To solve this, I started removing the existing `webview` and creating a new one instead. It's a workaround but it works.

However, today I tried to load an external page that is activated from a `form` and I had the same results. The DOM loads in the inspector, no errors in the console and no network issues.

This happens independent of `nodeintegration` (I have pages using both) for both `file://` and `http://` urls.

No solution yet

**Comment by felipemullen** [comment]
I will try to provide some steps to reproduce as soon as I get a chance, but it appears to be any time the `webview` tag has it's `src` value changed in >3.x

**Comment by felipemullen** [comment]
The issue may have something to do with VSCode or with the `electron.cmd` executable that comes bundled. I've been able to replicate the issue on a new project by creating it as follows:

1. `npm init -y`
2. `npm install electron@3.0.0-beta.2`
3. create `index.js` and make sure the `"main"` property of `package.json` matches
```javascript
const { app, BrowserWindow } = require('electron')
const path = require('path');

app.on('ready', () => {
    win = new BrowserWindow({ width: 800, height: 600 })
    win.loadURL(`file://${path.join(__dirname, 'index.html')}`);
})
```
4. create `index.html`
```html
<script>
    function changeSource() {
        const path = require('path');
        let src = path.join(__dirname, './page2.html');
        document.querySelector('webview').src = src;
    }
</script>
<webview allowpopups nodeintegration src="./page1.html"></webview>
<button onclick="changeSource()">change page</button>
```
5. create `page1.html`
```html
<div>This is page 1</div>
```
6. create `page2.html`
```html
<div>This is page 2</div>
```

If you run the app from the terminal with `electron .` the app will work as expected and changes pages just fine. 
However, using the following debugging configuration in VSCode somehow appears to interfere with the render after the first page:

```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Debug",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "args": ["main.js"]
        }
    ]
}
```

**Comment by PalmerAL** [comment]
I can't get this to work either running from the terminal or when the app is packaged, so I don't think it's specific to anythig VS Code is doing.

**Comment by wellbeck190** [comment]
I tried to add electron folder to search path ($PATH) and run:
```electron .```
This bug still exists, webview can't change or navigate other page or url

**Comment by felipemullen** [comment]
@PalmerAL did you try clearing your `node_modules` folder and installing again from npm? I feel like it should at least run from the terminal command

**Comment by PalmerAL** [comment]
@felipemullen Yeah, I tried that, it doesn't seem to work either way.

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/13503 since they are essentially the same bug.
