### ISSUE TITLE
Support for Xbox controller "Guide" button

### ISSUE THREAD

**Issue by wunderlink** [electron/electron#13768]
An Xbox controller has a special button called the "guide button". The majority of browsers do not support this button.

Chrome, however, does (this can be tested here: http://beej.us/blog/data/javascript-gamepad/).

I'd love to see this button supported in Electron, or some way to get it to work.

Anyone know how I can get my electron app to respond to this button?

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
The Xbox controller support should be the same in Electron as it is in Chromium. If it isn't, it'd be great to see a small example that shows the issue!
