### ISSUE TITLE
Add support for ASIO Driver

### ISSUE THREAD

**Issue by farebord** [electron/electron#13774]
**Is your feature request related to a problem? Please describe.**
Add support for ASIO Driver

**Describe the solution you'd like**
Support ASIO Driver natively

**Describe alternatives you've considered**
I've been using ASIO Bridge (VB-Audio)

**Comment by Julian-LiveEdit** [comment]
Any news about this case ? 👍

**Comment by baconbrad** [comment]
@Julian-LiveEdit While I would personally want this realistically I don't see a demand big enough for anyone to put into the work to implement/maintain this for Electron. Additionally many would see the ASIO SDK as bloat so I also don't see it being merged either. Your best bet would be to make a node module. It would have to be a [native module](https://electronjs.org/docs/tutorial/using-native-node-modules) since Node.js does not support ASIO either. Seems like one of the closer attempts is [node-audio-asio](https://github.com/distopik/node-audio-asio) but it is no longer maintained.

**Comment by MarshallOfSound** [comment]
This feature request belongs upstream in crbug, if Chromium adds support Electron will inherit it

**Comment by baconbrad** [comment]
> This feature request belongs upstream in crbug, if Chromium adds support Electron will inherit it

While ideal unfortunately this was suggested in 2015 and marked stale in 2021 on the upstream so I don't see it happening. There are a few possible native packages available now though. But they are untested by me and unsure how well they perform.

[Audify](https://www.npmjs.com/package/audify) seems to most supported and promising. I'd start here.
[node-audio-asio](https://github.com/distopik/node-audio-asio) is a proof of concept and severely outdated. But it focuses solely on ASIO support.
[node-audio-asio fork](https://github.com/AnClark/node-audio-asio) Still outdated but this fork has some slight improvements.

Overall it proves support can be performed through userland.
