### ISSUE TITLE
[Question] win.write?

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#13804]
> # **Question**

Is there anything like 
```js
mainWindow.write('<html><head></head><body><p>Text here</p></body></html>')
```
?

I don't want people to copy my repo files and then keep openning random html files though.
And i have seen Electron apps which don't have HTML files...

Is there anyway to do it?

I know that i can make Repo **Private**, but i want to keep Open Source and don't let people randomly view html files etc...

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
