### ISSUE TITLE
Can't prevent dropped file from opening in webview

### ISSUE THREAD

**Issue by EdwardLiao** [electron/electron#13811]
* Electron Version: 2.0.3
* Operating System (Platform and Version):  macOS 10.13.5

**Expected Behavior**
By default, dropping a file to a webview will trigger electron to open it within the webview.
I expect there is some way to prevent it.

**Actual behavior**
I can not find a way to prevent it.

**To Reproduce**

I'm trying to prevent the default drop behavior of Electron by adding the following code to renderer process.

```
document.ondragover = document.ondrop = (ev) => {
    ev.preventDefault()
    ev.stopPropagation();
}
  
document.body.ondrop = (ev) => {
    ev.preventDefault();
    ev.stopPropagation();
}
```

It did work for any non-webview elements, but if I drop the file to a webview, the webview will open the dropped file.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
#12655 disabled this behaviour by default in top-level frames. It should be disabled for webview too (though <webview> is in general fairly unstable, and I'd recommend finding a way to do what you need without it. Consider <iframe>s or an architecture that doesn't require embedding content).

Reopening this because this behaviour shouldn't be happening in webviews.
