### ISSUE TITLE
[Bug] Flash context-menu disappears randomly

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#13934]
**Electron Version:** v3.0.x, v2.0.x
**OS:** Windows 10 (1803) x64

**Expected Behavior**
Context menu of a flash object should stay open until user performs an action that normally closes it.

**Actual behavior**
Opening a flash context menu works fine but it randomly disappears when clicking nothing. Once it is gone, the app gets somewhat unresponsive. JS code is not getting executed, navigation does not work, reopening the context menu is impossible... 
I noticed that when I was using multiple electron windows, the bug only occured once and was only affecting that one window. Every other window was fine after that and the bug could not be reproduced a second time.

**To Reproduce**
Right click onto a flash object, so that the context menu appears. Then do nothing and wait until it disappears.

**Additional Information**
This one is very tricky to reproduce. It can take quite some time until it disappears, it is completely random when it disappears and I have no idea why it is happening. I was able to reproduce this issue in v2.0.2, v3.0.0-beta.3 and v3.0.0-beta.4 in various main.js setups.

**Workaround**
I came up with disabling the context menu, which seems to avoid the issue entirely (inline JS in HTML file):
`document.getElementById("flash").oncontextmenu = function(){return false};`

**Comment by codebytere** [comment]
@GhostlyDark could you please attach a minimal repro?

**Comment by christophpre** [comment]
Bump, I encountered this with current Electron Versions 4.0.6 und 5.0.X. I can consistently reproduce this with my gist. Here is the whole Bug report:
  * **Electron Version:**
  * 4.0.6
* **Operating System:**
  * macOS 10.13.6 **AND** Windows 10 (1803) (Linux not tested)

### Expected Behavior
If I right-click in a Flash application, the Flash contextmenu should stay open indefinitely and the Flash application should remain operable.

### Actual Behavior
If I right-click in a Flash application, the Flash contextmenu opens, but if you wait ~1 minute, the menu is closed and the Flash application becomes unresponsive.

### To Reproduce
1. Install current Flash Player for Chrome on your system (PPAPI - Flash Player 32.0.0.142)
2. Run the example from my gist https://gist.github.com/christophpre/f22145ced82b5ad1c54d0f5e0ff295ae
3. Right-click on the Flash content in the Flash about page, that is automatically loaded in the BrowserWindow, the Flash context menu should be open now
4. Wait ~1-2 minutes until the Flash context menu automatically closes
-> The Flash application is now unresponsive and the Flash context menu cannot be opened again

### Additional Information
Also tested this with current Google Chrome (Version  72.0.3626.119), the problem does not appear there.

**Comment by inukshuk** [comment]
I think this might be unrelated to Flash.

I've noticed context menus closing, seemingly randomly, on Linux and macOS. In one app it happens reliably after about 15s but I was also able to re-produce this with [a minimal test case](https://github.com/electron/electron-quick-start/compare/master...inukshuk:menu-close-issue) test case just now (4.0.7, macOS). This just opens a context menu in the quick-start window, right at start-up. In this example, it takes longer (less than 60s), but the menu also just disappears for me. When the menu disappears this way, neither the `menu-will-close` event nor the `callback` option of `.popup()` will fire.

I did not observe any issues after the menu disappears, so maybe this happens only in combination with Flash.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by GhostlyDark** [comment]
The issue persists up to Electron v7 (beta 2).
Issue #17292 is a duplicate and I don't mind continuing there as it has a better repro.
