### ISSUE TITLE
Does ipc use FIFO queue?

### ISSUE THREAD

**Issue by zl810881283** [electron/electron#13968]
In my test, I found that ipc between Main and Renderer is in order. But is that guaranteed in any OS?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
