### ISSUE TITLE
globalShortcut accelerator for mouse buttons?

### ISSUE THREAD

**Issue by raphadko** [electron/electron#13964]
I haven't seen this in the docs, so I presume it's not there.
How to setup a globalShortcut like ctrl + middle mouse?

**Comment by MarshallOfSound** [comment]
`globalShortcut` intercepts the key combination globally and prevents any application from receiving those key events.   If you blocked apps from receiving mouse button presses things would break everywhere very quickly 👍

**Comment by Vinby** [comment]
any workarounds for this?

**Comment by ldenoue** [comment]
@MarshallOfSound 
At least, could we obtain the current mouse buttons when the event fires? Instead of nothing, the callback could give us which other special keys and mouse buttons are pressed.
Also, could we register using globalShortcut only the Command or Control without specifying a key? I have a need in my application where the triggers should be Command + Click, not command + key.

**Comment by elmeunick9** [comment]
It would be nice if at least some alternative had been provided, if someone is asking it is because they need it. I for example use this to take screenshots of a specific area of the desktop in Python and I'm trying to port the code to node.js
