### ISSUE TITLE
Coding from https format

### ISSUE THREAD

**Issue by rastajamz** [electron/electron#13998]
* Electron version:
* Operating system:

* Last known working Electron version:

**Comment by rastajamz** [comment]
view-source:chrome://browser/content/aboutLogins.js

**Comment by ckerr** [comment]
I'm going to close this issue due to lack of information -- I literally can't tell what this issue is about.

Please file a new issue _and follow the issue template_ that prompts you to describe the issue, the Electron version, platform, expected results, and actual results. For reproducible issues, what would be ideal is if you could create a fork of `electron/electron-quick-start` that reproduces the issue.
