### ISSUE TITLE
shell.openExternal cannot open chrome

### ISSUE THREAD

**Issue by carlos121493** [electron/electron#14042]
* Electron version: 2.0.2
* Operating system: Mac

### Expected behavior

trun to browser & show page

### Actual behavior

show page but not trun to broswer

### How to reproduce
shell.openExternal('https://github.com', { activate: true });

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
