### ISSUE TITLE
No way to get the webContents for an iframe from main process

### ISSUE THREAD

**Issue by burtonator** [electron/electron#14091]
**Is your feature request related to a problem? Please describe.**

Right now there's no way to get the webContents from the main process.

It seems that you can get it from the renderer via webFrame.getFrameForSelector('iframe');

but this won't work from the main process.

This is needed because the frame webContents might need to have custom methods called like setZoomLevel or to add events like will-navigate.

Right now I can't implement either of them so it looks like I'm fundamentally blocked until I rework all my code to work in the renderer process.

**Describe the solution you'd like**

I want webContents.getAllWebContents() to return ALL WebContents not just the main one and ones associated with <webview>.

right now webviews are supported just not iframe.

**Describe alternatives you've considered**

I'm not sure there's a workaround.  The only thing I can think of is to inject code into the renderer and do it there but that's super frustrating and requires me to rethink my entire app and IPC framework.

**Additional context**

**Comment by burtonator** [comment]
This seems to be an issue for the webframe contents too. They aren't showing up in getAllWebContents.  
It looks like you can get them from the renderer. Just not from the main process.

**Comment by MarshallOfSound** [comment]
@burtonator I think there's a mis-understanding here, a `webFrame` instance is not a `webContents`.  A web contents can own many web frames.

For your use case I'd recommend handling all the web frame work inside a preload script and handling all the web contents work in the main process.  This is purely because this is where they technically live in the Chromium world.
