### ISSUE TITLE
perf: calculating shared bytes is very expensive on windows and mac

### ISSUE THREAD

**Issue by aasharmaMS** [electron/electron#14176]
* Electron Version: 3.0
* Operating System (Platform and Version): windows and mac

**Issue**
When we call [process.GetProcessMemoryInfo()](https://electronjs.org/docs/api/process#processgetprocessmemoryinfo) on electron then it calls chrome internally to get working set, peak working set, private bytes and shared bytes. Calculating shared bytes is very expensive because the code loops through every page and tries to find out if it is shared. This loop on a fast development machine can take from **30ms** to **100ms+** based on how many pages are there to loop through.
This problem exists at least on Windows and Mac.

**Comment by alexeykuzmin** [comment]
@ckerr 
One of the possible solutions is to optionally turn off calculation of the `sharedBytes`, it can help apps that do not need that data to run faster. Should be a small trivial change.
Are you ok with this?

**Comment by ckerr** [comment]
Echoing the Slack conversation here for transparency.

> Are you ok with this?

On the level of "do I like this patch?" Yes, I like it. @aasharmaMS found a valid issue and wrote a good patch for it.

But where to put it? It doesn't fit in `master` for 4.0.0 because `memory.sharedBytes` is going away there due to upstream changes in Chromium. And we can't put it in the `2-0-x` or `3-0-x` stabilization branches because our [versioning rules](https://electronjs.org/docs/tutorial/electron-versioning#beta-releases-and-bug-fixes) don't allow it:

> At that point, the feature set is locked. That release line admits no further features, and focuses only on security and stability.

I'd take this patch if we had a place to put it, and hope @aasharmaMS writes more patches in the future that we _can_ take.
