### ISSUE TITLE
Secure important data

### ISSUE THREAD

**Issue by mekramy** [electron/electron#14387]
Hi
How can i hide my important information (Database connection info, customer key, ...).
normally everyone can see the source code and my private code is insecure. Is there any solutions to this problem?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
