### ISSUE TITLE
IPC not working when bulk actions being run

### ISSUE THREAD

**Issue by teken** [electron/electron#14388]
* Output of `node_modules/.bin/electron --version`: 1.8.8
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
for ipc to return an array with data inserted

**Actual behaviour**
return empty array

**To Reproduce**
```
{
ipcMain.on(
	"settings.gets",
	(event, args) => {
		let results = args.reduce((acc, val) => {
			const name = String(val);
			acc[(name)] = this.settings.get(name);
			return acc;
		}, []);
		console.log(args, results);
		event.returnValue = results;
	}
)
```

**Screenshots**
Screenshot of log for console log in above code
![image](https://user-images.githubusercontent.com/1248314/44860268-c0bfad00-ac6d-11e8-8025-78b02cbde1cd.png)
Screenshot of log for application receive data
![image](https://user-images.githubusercontent.com/1248314/44860307-d3d27d00-ac6d-11e8-845c-525804cdd027.png)

**Comment by MarshallOfSound** [comment]
This is expected behavior, arrays shouldn't be used with non-string keys as they won't be serialized.

![image](https://user-images.githubusercontent.com/6634592/45131606-0d0c6f00-b1d1-11e8-8de5-f4c11af84624.png)

You should use an object instead like so:

![image](https://user-images.githubusercontent.com/6634592/45131638-35946900-b1d1-11e8-8f99-22b1f3161e4c.png)
