### ISSUE TITLE
How can I debug sharedworkers in electron

### ISSUE THREAD

**Issue by liuweichao** [electron/electron#14398]
In chrome debug sharedworkers need launch a window with "chrome://inspect/#workers"

like this

<img src="https://raw.githubusercontent.com/liuweichao/Tools/master/prevImg/1.png" /> 

### but in electron i cannot launch a window with chrome://inspect/

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
