### ISSUE TITLE
Slack flickers on AMDGPU using Arch Linux.

### ISSUE THREAD

**Issue by HoshiYamazaki** [electron/electron#14424]
* Operating System (Platform and Version): Arch Linux x86_64 (i5-6600/rx480)

**Expected Behavior**
No appearance of graphical bugs.

**Actual behavior**
![obraz](https://user-images.githubusercontent.com/21007545/44960493-047e1500-af01-11e8-9739-f9be5ffd88cb.png)

**To Reproduce**
Download slack from aur, and just use it on Arch with AMDGPU. I tried to switch to uxa rendering in Xorg, appears that it doesn't help.

**Additional Information**
I use AMDGPU drivers.

**Comment by sofianguy** [comment]
Please file a bug report with Slack directly

**Comment by bulletmark** [comment]
I have long used skypeforlinux-preview-bin from the Arch AUR. It embeds a copy electron and has started flickering for the least few versions (i.e. about last 3 or 4 weeks). I raised an issue with Skype/Microsoft about this recently but this bug makes me realize it is probably due to electron. I am using GNOME on Wayland and plain intel graphics. I can't reproduce it on call and have not noticed any pattern causing it.

**Comment by v-i-s-h** [comment]
I am also encountering same issue with Slack and VSCode apps in Manjaro Linux. This clearly looks like an electron issue.
