### ISSUE TITLE
[TypeScript] Types are missing "session-created" event on "app"

### ISSUE THREAD

**Issue by Tenga** [electron/electron#14435]
* Output of `node_modules/.bin/electron --version`: `2.0.8`

**Expected Behavior**
Assigning the `session-created` event listener on `app` should be supported in TypeScript without workarounds.

**Actual behavior**
TypeScript throws an error:
> [ts] Argument of type '"session-created"' is not assignable to parameter of type '"window-all-closed"'. 

**To Reproduce**
```TS
app.on("session-created", (session) => {
  // ...
});
```

**Additional Information**
The event exists and fires, but `session-created` doesn't seem to be in `electron.d.ts` at all. 
Type auto-generation issue probably? It also seems to be missing from the API docs on the website, while it exists in the docs on GitHub.

Temporary workaround is to do something like this:
```TS
(app as any).on("session-created", (session) => {
  // ...
});
```

**Comment by MarshallOfSound** [comment]
@Tenga The issue here is those events aren't documented in the `2-0-x` branch so they won't end up in the typings files either.

https://github.com/electron/electron/blob/2-0-x/docs/api/app.md

This PR back to `2-0-x` should put them in the next `2.0.x` release https://github.com/electron/electron/pull/14439
