### ISSUE TITLE
app.makeSingleInstance() and flatpaks

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#14460]
hi,

i've been deploying my electron app as a flatpak for a while, but i notice that when running as a flatpak `app.makeSingleInstance()` does not correctly identify that the application is already running.

this is presumably to do with flatpak's sandboxing, and i probably need to add some permissions somewhere, but i can't find any docs describing how the app.makeSingleInstance actually works.

any tips on where i could find how makeSingleInstance() works?

with thanks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
