### ISSUE TITLE
Use registerStreamProtocol and nuxt.render

### ISSUE THREAD

**Issue by yuchonghua** [electron/electron#14489]
https://github.com/nuxt/nuxt.js/issues/3215
https://github.com/nuxt-community/electron-template/issues/19
https://github.com/nuxt-community/electron-template/issues/18

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

Issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.
