### ISSUE TITLE
Upgrade to Chromium 68

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#14549]
Chromium **68.0.3440.128**
V8 **6.8.275.30**
Node.js **10.10.0**

**Comment by Brandinga** [comment]
would need chromium #69.0.3480.0

because of this [fix](https://bugs.chromium.org/p/chromium/issues/detail?id=853403)
Reason: [win 10 tabletmode -> password fields -> no touchkeyboard](https://social.technet.microsoft.com/Forums/en-US/00e5ef30-8134-4fc6-8632-958d97b954d7/windows-10-1803-touchpad-doesnt-popup-for-password-fields-in-chrome?forum=win10itproapps)

**Comment by MarshallOfSound** [comment]
@Brandinga To make the upgrade process as simple as possible we go one version at a time, once 68 is complete we can look at 69

**Comment by biiiipy** [comment]
@MarshallOfSound It has been bugging for a long time - why is electron upgrading to newer chromium version so slowly? Electron 3.0 is out with v66, while Chrome v69 has been out for a while. It's kind of frustrating to be always 4-5 months behind. I get that it's not trivial to upgrade, but maybe the whole thing should be rethought how to make the upgrade easier. It would not only allow to upgrade faster, but to spend less engineering hours to upgrade to every.single.chromium.version. Isn't it worth to invest in a leaner upgrade path then to spend resources on upgrading every single time?
nwjs manages to upgrade chromium versions in <24 hours, so electron looks bad by comparison...

**Comment by nornagon** [comment]
@biiiipy You aren't the only one frustrated with Electron not keeping pace with Chromium! There are a lot of concrete changes happening at the moment to improve the situation, such as the recent switch to the GN build systems, and improvements to how we track node's patches to v8.

Electron integrates much more tightly with Chromium's internals than nw.js does, which is why upgrading is more difficult for Electron than nw.js.

Skipping Chromium versions does not make the upgrade process easier, in general. If 3 APIs change between chrome 67 and 68, and 5 other APIs change between chrome 68 and 69, then we still have to fix 8 APIs, whether we jump directly from 67 to 69 or do two upgrades, 67->68 and 68->69. The trick is going to be making those upgrades smoother and faster, not skipping them.

**Comment by alexeykuzmin** [comment]
Fixed in #14677.
