### ISSUE TITLE
net.response Headers includes single quoted header keys and values.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#14629]
The HTTP headers on the net.response object are all single quoted. The values are single quoted too.

This is against Electron 2.0.9 (stable) and the 3.0 betas.

These should not be quoted. The 'Headers' type in the electron.d.ts doesn't have any fields/methods so I assume it's just a dictionary.

There is no .constructor on the object either so it's just an object.

This means they're not compatible with the stream protocol headers so I have to mangle them back in but what if this behavior is fixed in the future?

I can unpack the dictionary of course but if it changes in the future things will break.

* Output of `node_modules/.bin/electron --version`:

v2.0.9

Both 2.0.9 and 3.0-beta12

* Operating System (Platform and Version):

Ubuntu 18.04

**Expected Behavior**

HTTP headers on the Response object should not be quoted.

**Actual behavior**

the HTTP header values are quoted.

**To Reproduce**

https://github.com/burtonator/electron-protocol-examples/

**Screenshots**
![image](https://user-images.githubusercontent.com/45447/45563175-70b22000-b801-11e8-8b9f-8fc3db347a43.png)

**Comment by MarshallOfSound** [comment]
@burtonator From your screenshot all those values are quotes because you logged them to console and therefore have been stringified for your console.  The actual key does not include these quotes.  For example:

<img width="358" alt="screen shot 2018-09-16 at 1 49 21 am" src="https://user-images.githubusercontent.com/6634592/45588110-c6e2a880-b952-11e8-9d24-93c26ae8bef5.png">

The quotes are only shown in your console
