### ISSUE TITLE
Can't hover 5px near border in frameless and resizableless mode

### ISSUE THREAD

**Issue by BertholetDamien** [electron/electron#14628]
* Electron: v2.0.9
* Operating System (Platform and Version): Window 10

**Expected Behavior**
Should be able to detect mouse hover when near of border in frameless and resizableless mode.

**Actual behavior**
Actually, the detection near border is not effective. There is a 5px all around the body who not detect mouse hover (seems to be the resizable area when actived). But if you click on the 5px, the detection is on.

**To Reproduce**
Please use this very simple app:
https://github.com/BertholetDamien/electron-quick-start

```sh
$ git clone https://github.com/BertholetDamien/electron-quick-start
$ npm install
$ npm start
```

Thank for your time !

**Comment by BertholetDamien** [comment]
Hi team,

Any idea ? =)

**Comment by BertholetDamien** [comment]
Hi team,

Still no idea ?
(Feel lonely 😆)

**Comment by BertholetDamien** [comment]
Anyone ? Please ? :)

**Comment by alitaheri** [comment]
I have the same issue. it's not detecting hover at all.

**Comment by chrisakakay** [comment]
I run into the same proble, but it's not just on hover.
Added event listeners are not triggering either.
Seems like that 5px "frame" is not reacting to anything without clicking on it (since dragging works).

Version: 9.x

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
