### ISSUE TITLE
Electron@3-beta.13 / Accelerator combination doesn't work on windows 10 

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#14674]
* Output of `node_modules/.bin/electron --version`: Electron 3.0.0-beta.13
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Electron 2.0.9

**Expected Behavior**
accelerator combination `ctrl-alt-i` triggers menu action on windows 10.

**Actual behavior**
accelerator combination `ctrl-alt-i` does not trigger menu action on windows 10.

**To Reproduce**
On windows 10, clone https://github.com/kwonoj/electron-quick-start/pull/1

`npm run start`: try ctrl-alt-i, check output `test output` is printed out into console.
`npm run start3`: try ctrl-alt-i, check no console output printed.

**Additional Information**

**Comment by brenca** [comment]
I investigated this yesterday, and it looks like all the accelerators with more than one modifier key are not working properly.

**Comment by brenca** [comment]
Alright, so I investigated yesterday, and I thought it was about 2+ modifiers added to an accelerator, but it turns out I was just sleepy. This is happening because `Ctrl+Alt` is `AltGr` in Windows's mind, so when you set an accelerator for `Ctrl+Alt` it won't get triggered, because it gets checked against `Ctrl+Alt+AltGr` when comparing the pressed modifier buttons. I'm going to post the PR shortly.
