### ISSUE TITLE
Drop shadows are almost non-existent with window property "frame: false"

### ISSUE THREAD

**Issue by AlexSHoffman** [electron/electron#14684]
Not sure if it affects MacOS and Linux but on Windows 10 it is very noticeable. Drop shadow of every window with `"frame: false"` is almost non-existent, hence you can barely distinguish the app from the background.

Is there anything we can do about it? 
I couldn't find any solution, looks like Windows doesn't have any APIs for this. Adding a window padding is not gonna help either since you effectively loose the ability to resize the window.

Here's a comparison of drop shadows showcasing the best case scenario - white window on top of another white window:

![shadows_comp_1](https://user-images.githubusercontent.com/13764106/45739898-b81f1e80-bbfc-11e8-9b1d-896f01415708.png)

**Comment by Stanzilla** [comment]
Currently having the same issue, any ideas?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
