### ISSUE TITLE
[Question] How to association Win32Api bounds between Electron screen display bounds?

### ISSUE THREAD

**Issue by gtk2k** [electron/electron#14703]
I have created an application to acquire images of monitors on Windows with Windows.
When Win32 Api acquires the bounds information of the monitor setting "scale and layout" to 175%
x: -180, y: -855, right: -463, bottom: 242
have become.
When you acquire the bounds information of the same monitor with Electron (screen module)
x: -618, y: -33, width: 618, height: 1098
have become.
I would like to link Win32 Api's monitor information with Electrion's display.bounds,
What kind of calculations can you associate with?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
