### ISSUE TITLE
I want Display object add rawbounds property.

### ISSUE THREAD

**Issue by gtk2k** [electron/electron#14724]
https://electronjs.org/docs/api/structures/display
We will add the rawBounds property to the Display object.
The bounds property is the value calculated by scaleFactor, but if it matches the monitor's matrix information acquired by the Windows application (eg System.Bounds of .Net), the scaleFactor of all monitors is 1 It is easy to match if there is one, but it is difficult to match if the scaleFactor differs for each monitor.
So I want a rawBounds property with raw bounds value ignoring the scale factor.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

Issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by gtk2k** [comment]
This is request, not Issue.

**Comment by MarshallOfSound** [comment]
@gtk2k We have a [Feature Request](https://github.com/electron/electron/issues/new?template=Feature_request.md) issue template as well
