### ISSUE TITLE
Racist terms such as slave/master

### ISSUE THREAD

**Issue by slammerhammer** [electron/electron#14771]
When reviewing the project's code I saw the phrase Master/Slave... This kind of terminology can lead to awkwardness and overall is dated terms. Don't you think we can do a little better? What I propose is something like Python just did, which was AMAZING of them. I feel like by keeping this we are excluding and not including everyone. Waiting to hear your thoughts...

**Comment by aequasi** [comment]
Troll account, please close

**Comment by codebytere** [comment]
hi @slammerhammer, we appreciate your surfacing this concern, and we recognize these terms to be damaging and rightly so. However, we don't in fact reference the term `slave` or `master` in our source code, as verified by [this search](https://github.com/electron/electron/search?q=slave&unscoped_q=slave) and [this search](https://github.com/electron/electron/search?utf8=%E2%9C%93&q=master&type=). We reference `master`, thus, only as it pertains to the primary branch name, which is directly in alignment with the current state of Python, as you referenced above. I'm not quite sure where you found those terms to exist, but if there are areas we have missed, we are happy to address them.

**Comment by potato20** [comment]
@codebytere I appreciate your concern, but you're forgetting a crucial point. The term `master` was adopted by git developers in the early days because they were simply borrowing from the `master`/`slave` terminology, so it's obvious where this naming convention came from. Other projects have adopted branch names such as `primary`, `main`, or `central`.

Also, while I appreciate what python is doing, we shouldn't be using them as a model of what we should or shouldn't do. There's no reason for us to not take charge and lead the way.
