### ISSUE TITLE
Skipping extension with invalid URL

### ISSUE THREAD

**Issue by kostysh** [electron/electron#14779]
Not sure is it issue or feature. I am trying to add an extension (not DevTool, a metamask extension) to the electron application using Electron API ([BrowserWindow.addExtension(path)](https://electronjs.org/docs/api/browser-window#browserwindowaddextensionpath)) and always get a error
```
Skipping extension with invalid URL
```
Before calling of `addExtension` (on app ready event) I downloading an extension .crx file and unziping it into subfolder in `userData` directory. 

So, is it possible to add extension using Electron API?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by rangerscience** [comment]
Hi, I'm running into this issue and have reproduction steps. Rather than open a new issue, I'll comment on this one...?

* Electron version: 7.1.7
* Operating system: MacOS Mojave 10.14.5

### Expected behavior

Extension should load without error

### Actual behavior

Main process logs error:
`[30712:0102/163027.980187:ERROR:CONSOLE(8007)] "Skipping extension with invalid URL: chrome-extension://my-cool-extension", source: devtools://devtools/bundled/shell.js (8007)`

### How to reproduce

  $ git clone https://github.com/rangerscience/electron-extensions
  $ npm install
  $ npm start

### Further Questions

It's not clear from the Electron docs where the logs from the background script should show up, or otherwise how to make them accessible. 

I'm trying to trace the source code, but there are places where I'm finding it extremely unclear where something is defined (`webContents.loadURL` being the prime example here) - it's not clear how to go from something's documentation to the code that implements it, and I'm finding it hard to navigate or search this repository (probably my own inexperience in JS).

On that note, it would be nice to figure out where `devtools://devtools/bundled/shell.js (8007)` is, but I have no idea where to even start. Searching for the error message in the Electro repo isn't giving me any results.

Most Chrome extensions have a browser action button, but it's not clear if Electron does or does not support this in some way. 

In the _actual_ app this work is for, I have a background process window. When I load the browser extension via `BrowserWindow.addExtension`, it's added to that window as well (at least when I have the background process have a window, so that I can see the logs), which seems less than ideal but not actual problematic.

PS - LMK if I should open a new issue, split any of this out into it's own issue, etc etc. Not entirely sure if I'm doing this correctly ;)
