### ISSUE TITLE
[question] How to get access to browser context menu?

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#14776]
I want to add my custom option to browser context menu. Is there a way to do it? To be clear, I want to add my custom option exactly to browser context menu (Chrome / Safari / Firefox / Edge), not Electron app.

Here is an example how 1Password did it in Chrome:

![image](https://user-images.githubusercontent.com/20713191/45929473-c9a15700-bf6b-11e8-99da-9f4ea1b3c4e2.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by SilencerWeb** [comment]
@codebytere unfortunately, these communities seem to be dead or they never were alive :(

Tried spectrum - no reaction.
Tried community forum - I cannot even post a question because I need to get verified or something, which I'm waiting already for more than one day.
