### ISSUE TITLE
Enhance favicon-updated event listener

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#14803]
**Is your feature request related to a problem? Please describe.**
The actual behavior of webview/webContents favicon-updated returns only a list of favicon urls that the page provided, it's a unproductive task to have to analyze each image to define the purpose of the favicon (16x16, 32x32, app icon, etc...) and see if each one is the correct for your application.

**Describe the solution you'd like**
Electron should return a object containing: the favicon url, the size and a base64/dataURI of the favicon.

**Describe alternatives you've considered**
I have to analyze each favicon to check it's size and format, to see if it fits in a predefined pattern and  if it's the correct one for my application.

**Comment by MarshallOfSound** [comment]
@4eveRS The `page-favicon-updated` event only emits the URL's because that is all we are given by chromium.  See our event logic here:

https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_web_contents.cc#L951-L962

We shouldn't fetch those URL's to provide the information you're asking for because that will caused increased network traffic for people that may not even be using this event.  You can find that size information out yourself by fetching each URL and checking the size of the image.

In addition, although Chromium does have a [`icon_sizes`](https://cs.chromium.org/chromium/src/content/public/common/favicon_url.h?dr=Ss&g=0&l=42) property on their favicons, having played with this property for a while today it appears to always be an empty vector.

**Comment by benfrancis** [comment]
@MarshallOfSound wrote:
> The page-favicon-updated event only emits the URL's because that is all we are given by chromium.

Is this still the case?

It would be much more efficient to pass on the metadata provided in the HTML link relation (rel, href, sizes and type) rather than rely on applications to download every referenced image and try to determine its MIME type and size. Particularly for .ico files which can contain multiple images.

If this is a limitation of Chromium, where is the best place to file an issue to enhance this on their end?

For reference, [this](https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Chrome/API/Browser_API/mozbrowsericonchange) is the equivalent event in Gecko.
