### ISSUE TITLE
Document Scan API

### ISSUE THREAD

**Issue by dustyroberts** [electron/electron#14819]
I am attempting to add document scanning to my electron app. The only solutions out there is to make use of third party libraries which are not affordable to most people

The Chrome API exposes a document scan function: https://developer.chrome.com/apps/documentScan that should make it easier to access scanner functionality. Would it be possible to expose this API?

I have looked at https://asprise.com/document-scan-upload-image-browser/direct-to-server-php-asp.net-overview.html but it is extremele expensive. I've also looked at https://www.dynamsoft.com/Products/WebTWAIN_Overview.aspx which also turns out to be quite expensive.

I have also seen the existing discussion: https://github.com/electron/electron/issues/11180, but it only refers to scanner-js, which is ultimately the asprise solution, and if you read the documents it mentions that you need to purchase a license if the software is ready for production.

**Comment by dan-willett** [comment]
@dustyroberts I am very interested to know how you make out with this.

You may find this helpful:  https://github.com/mgriit/ScanAppForWeb

I am looking to develop an app that can run on the users machine ( for an in-house project ) that would scan documents and upload them to our on-line application and be able to eliminate extra steps for the user such as manually scanning them, saving to a file, uploading, renaming, etc.  I.E. I want to make a app for 1 click scan and upload, and since the majority of the programming I do is in Javascript, I would like to be able to do it in Electron ...

**Comment by nornagon** [comment]
The Chrome API you link notes that it only works on Chrome OS. Here's the implementation on other platforms, which I don't think is what you're looking for: https://chromium.googlesource.com/chromium/src/+/master/extensions/browser/api/document_scan/document_scan_interface_nonchromeos.cc#30

Implementing a full scanner interface, while a cool idea, is beyond the scope of the Electron project.

**Comment by jia58960** [comment]
I'm looking for some solution. But ...

**Comment by josephj** [comment]
The following is the free cross-platform solution I will do.

### For Windows

Installed the [CmdTwain](http://www.gssezisoft.com/main/cmdtwain/)

**Comment by lonllua** [comment]
Any solution?

**Comment by marchbold** [comment]
We are interested in a solution to this as well. Has anyone tried using CmdTwain or got some more detailed examples ?
