### ISSUE TITLE
Ability to underline text

### ISSUE THREAD

**Issue by mrandrey** [electron/electron#14896]
**Is your feature request related to a problem? Please describe.**
I need to be able to underline text in my Electron application in a similar way I can do it in Notes on OS X.

**Describe the solution you'd like**
The ability to add the "underline" role, and trigger it with Cmd+U

**Describe alternatives you've considered**
I thought about using JS to generate <u></u> tags, but it seems messy, especially if the users will want to underline and already underlined section. I'd like OS to handle it, sort of like Cmd+I makes italics.

Thanks!

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
