### ISSUE TITLE
linux mint 17.3 libdbus-1.so.3 Error

### ISSUE THREAD

**Issue by burkoyuriy** [electron/electron#14930]
/opt/dandelion/map/node_modules/electron/dist/electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/dandelion/map/node_modules/electron/dist/electron)
/opt/dandelion/map/node_modules/electron/dist/electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/dandelion/map/node_modules/electron/dist/electron)

App not running)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by MarshallOfSound** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
