### ISSUE TITLE
Restoring in-app purchases

### ISSUE THREAD

**Issue by ivandroid** [electron/electron#14945]
* Electron version: 3.0.2
* Operating System (Platform and Version): MacOS High Sierra latest

### Expected behavior

There should be a method in the in-app purchase API to restore all purchased products at once. Apple has rejected my current app build because of the absence of this feature. They want to have a button to restore in-app purchases. 

### Actual behavior

Currently it’s not possible to restore purchased products. It’s possible to buy, but not to restore. 

Thank you for your help, guys!

**Comment by thomasdao** [comment]
I think you can restore purchases by using receipt. Electron already has API for retrieving receipts.

**Comment by MarshallOfSound** [comment]
Sounds like this was resolved

**Comment by semireg** [comment]
It's not clear what `inAppPurchase.getReceiptURL` is doing. Which receipt is this for? Is it always the current transaction?

Additionally, is there an equivalent that calls `[[SKPaymentQueue defaultQueue] restoreCompletedTransactions]`?

**Comment by nikbabchenko** [comment]
> You're right. It's possible indeed. If a product is already purchased, you can restore it without paying again. Apple has approved my current build. Thank you.

How have you implemented that? 
Has the same issue from appstore)

**Comment by thomasdao** [comment]
"Restore purchase" button that Apple required, is a way for users to maintain access to content they’ve already purchased. According to [Apple documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html):

`In most cases, all your app needs to do is refresh its receipt and deliver the products in its receipt. The refreshed receipt contains a record of the user’s purchases in this app, on this device or any other device.`

So you could get the receipt in your app, send to Apple server to decrypt and inspect the receipt to find out what user has purchased and then deliver that product to them. You can find more about validating the receipt from [Apple documentation](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573).

**Comment by ivandroid** [comment]
> > You're right. It's possible indeed. If a product is already purchased, you can restore it without paying again. Apple has approved my current build. Thank you.
> 
> How have you implemented that?
> Has the same issue from appstore)

I added a 'restore' button for each in app purchase. Clicking on this button forces the user to buy the corresponding product without paying again, if it's already purchased.

**Comment by semireg** [comment]
@ivandroid, @MarshallOfSound - I'm revisiting this because some users report they purchase my app's IAP but it's not reflected in the app for some reason. If they purchase the IAP *again* it "works." Of course, they are not charged twice - but they fear they will be... which is bad customer service. Has anyone else experienced this somewhat rare event of IAPs not being delivered properly the first time?

Fwiw, I don't have a restore button and it hasn't been an issue for MAS approval. If the Electron API had support for Apple's [SKReceiptRefreshRequest](https://developer.apple.com/documentation/storekit/skreceiptrefreshrequest) it would make implementing that button a bit easier, and probably make troubleshooting my rare issue a little easier.

It seems straightforward enough to add support for SKReceiptRefreshRequest, but I'm always intimidated setting up a dev environment for a library as large as Electron. Is there a guide on that? I see [this](https://electronjs.org/docs/tutorial/development-environment), but that's not for developing Electron itself.

**Comment by Jocs** [comment]
>I think you can restore purchases by using receipt. Electron already has API for retrieving receipts.

Can I get the receipt url if the `restored` event triggered?

**Comment by goodhyun** [comment]
Could we reopen this issue as we don't seem to have a proper API only to retrieve a receipt from Apple ? 

If you freshly installed the app after in-app purchases, or had purchased the app even before the in-app purchase was implemented, you wouldn't have a way to download receipts to restore purchase. 

@thomasdao How did you refresh the receipt? 
@semireg Any progress on your app on this?

**Comment by Jocs** [comment]
@goodhyun Same issue here, can you restore in app purchases now?

**Comment by thomasdao** [comment]
@goodhyun when user freshly install the app from App Store, or if user deletes the app and installs again from the App Store, App Store will write the receipt with latest transactions. So what I did is to simply send that receipt to server and validate. However I have the same issue with @semireg, as sometime the receipt is not updated after user purchased the product, hence I create this feature request #21435, hopefully it will be added to Electron.
