### ISSUE TITLE
Window.minimize () is not working in the main.js file

### ISSUE THREAD

**Issue by sambits** [electron/electron#14998]
Window.minimize () is not working in the main.js file

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by pronebird** [comment]
Works for me on macOS and Electron 3. Make sure you create the BrowserWindow with `minimizable: true`.

**Comment by MarshallOfSound** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
