### ISSUE TITLE
dump_syms can't resolve symbols for Squirrel.framework

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#15058]
Build: https://github.visualstudio.com/electron/_build/results?buildId=14677&view=logs
Patch: https://github.com/electron/electron/pull/15056

We should fix this properly instead of patching out the `sys.exit`

**Comment by nornagon** [comment]
I think fixing this will require some fairly drastic surgery. Here's the situation.

First, some context on how loader paths work in macOS.

Each executable has a list of dynamic libraries to load. These are mostly specified as absolute paths (e.g. `/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa`), but dyld will do some substitutions to support flexibility in where libraries are loaded from (see [`man 1 dyld`](https://opensource.apple.com/source/dyld/dyld-195.5/doc/man/man1/dyld.1.auto.html)). Specifically:
  - **`@executable_path`** will be replaced by the path to the directory containing the process's executable. e.g. if the process is `/some/path/Electron.app/Contents/MacOS/Electron`, then `@executable_path` will be replaced by `/some/path/Electron.app/Contents/MacOS`. It's the same path for all recursively loaded libraries, so if Electron depends on Squirrel.dylib, and Squirrel.dylib depends on Mantle.dylib, `@executable_path` will be the substituted by the same path in all cases.
  - **`@loader_path`** is similar to `@executable_path` when used from the main executable, but differs in the case of recursively loaded libraries. `@loader_path` is always substituted by the directory containing the binary that is doing the loading.
  - **`@rpath`** works a bit differently: it's not a pure substitution, but instead, it's substituted by each path in a list (called the "run path list") repeatedly until the library is found. The run path list is built up out of all the run paths of everything in the dependency chain of the current load. So for instance, if an executable `Exe` has a run path list of `"/a", "/b"`, and a library `Lib` has a run path list of `"/c"`, then when loading a dependency of `Lib`, the run path list is `"/a", "/b", "/c"`, and each of those directories will be tried in turn when looking for a library that `Lib` is trying to load. Run paths can also contain the variables `@executable_path` and `@loader_path`. Run paths are added to an executable or a library using the `-rpath` option to the linker, and are encoded as `LC_RPATH` commands in the linked object.

Useful tools for displaying rpaths and linker information in general are `otool -L` to see what libraries an object is linked against, and `otool -l` to see all the linker commands.

`generate_breakpad_symbols.py` contains logic which replicates dyld's library resolution, with [one important exception](https://chromium.googlesource.com/chromium/src/+/69.0.3497.106/components/crash/content/tools/generate_breakpad_symbols.py#138): it does not build the run path list for `@rpath` from the entire dependency chain, it only uses the entries from the library itself.

Squirrel's runpath list is: (from `otool -l path/to/Squirrel | grep -A2 LC_RPATH`)
- `@executable_path/../Frameworks`
- `@loader_path/../Frameworks`

and Squirrel lists `@rpath/Mantle.framework/Mantle` and `@rpath/ReactiveCocoa.framework/ReactiveCocoa` as dependencies. According to `generate_breakpad_symbols`'s requirement that every library contain all the rpath entries it needs and not rely on the rpath entries from the dependency chain, this means that Mantle.framework must be located at either:
1. `Electron.app/Contents/Frameworks/Squirrel.framework/Versions/Frameworks/Mantle.framework`
    - using `@loader_path`, since the `Squirrel` library is located at `Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel`
    - this is a weird path, because `Versions/` is supposed to only contain versions of the framework itself.
2. `Electron.app/Contents/Frameworks/Mantle.framework`
    - using `@executable_path`

the 2nd option would be fine, except for the fact that `Electron Helper.app` also depends on `Squirrel.framework`.

So here are our options:
1. ~Rely on the `@executable_path/../Frameworks` entry in Squirrel's rpath list, and duplicate Squirrel.framework and its dependencies underneath Electron Helper.app~
    - having a 2nd copy of Squirrel, Mantle and ReactiveCocoa on-disk is a no-go. They're about 1MB each.
2. ~Rely on the `@loader_path/../Frameworks` entry in Squirrel's rpath list and put Squirrel at `Electron Framework.framework/Versions/Frameworks/Squirrel.framework`~
    - `Versions/` is supposed to only contain versions of the actual framework, and messing with the framework directory structure seems like a Bad Idea
3. Symlink Squirrel.framework, Mantle.framework and ReactiveCocoa.framework into `Electron Helper.app/Contents/Frameworks/`
    - works, but is quite awkward to express in GN
4. Have a build step that uses `install_name_tool` to modify Squirrel's rpath
5. Rebuild Squirrel with the an rpath that complies with generate_breakpad_symbols.py's requirement that all dylibs contain the complete rpath that they need
6. Load Squirrel dynamically, since the render process will never actually call any squirrel functionality (it's main-process-only).
    - presumably we'd still need to run `generate_breakpad_symbols.py` on it? it wouldn't be automatically discovered by walking the dyld deps.
7. Dear god why are there so many ways of doing this

**Comment by oldmtn** [comment]
Cannot open libs/myEngine1.node: Error: dlopen(/Users/haha123/Documents/www_htdocs/1/libs/myEngine1.node, 1): Library not loaded: @rpath/TestEngineKit.framework/Versions/A/TestEngineKit
  Referenced from: /Users/haha123/Documents/www_htdocs/1/libs/myEngine1.node
  Reason: image not found

l caught this issue.
Is there anyone that fix this issue?

**Comment by MarshallOfSound** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove the dump_syms patch and ensure that Squirrel.Mac has symbols in release builds](https://trello.com/c/sYZS7JmP/17-remove-the-dumpsyms-patch-and-ensure-that-squirrelmac-has-symbols-in-release-builds)

**Comment by nornagon** [comment]
I think this might no longer be an issue since we build Squirrel et al from source now.
