### ISSUE TITLE
Not able to disable double-click-to-maximize on titlebar 

### ISSUE THREAD

**Issue by steverandy** [electron/electron#15163]
* Output of `node_modules/.bin/electron --version`: 4.0.0-beta.3
* Operating System (Platform and Version): macOS 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
By setting `-webkit-app-region: no-drag;` to the element, user should not be able to drag window and not be able to double click to maximize window.

**Actual behavior**
User not able to drag window.
User still able to double click to maximize window.

**Additional Information**
I'm using `titleBarStyle: hiddenInset`.
I can't find more documentation on the behavior of double click of the titlebar on macOS.
Is there a way to control the double click behavior? For example to disable on certain elements.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by JasinYip** [comment]
I'm facing on the same issue. It's common in frameless application.

**Comment by somebee** [comment]
@steverandy Did you ever find out how to avoid this? Struggling with the same problem

**Comment by steverandy** [comment]
@somebee I have not found any solution and still seeing the same issue on Electron v5.
