### ISSUE TITLE
npm install --save-dev electron does build node_modules folder.

### ISSUE THREAD

**Issue by crashbdx** [electron/electron#15164]
Trying to test electron, everytime i try a npm install --save-dev electron i get a package.json but no node_module, npm install also dont build any node_modules, what can be the problem here ?

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by crashbdx** [comment]
My bad, i actually corrected it, i have no idea how but working now, but it seem that i have some issue with atom, when i run electron in atom command terminal i get an erreur that i dont get on powershell where all work perfectly, is that a known issue ? do i start a new tread for that with the correct template this time :D 

`app.on('ready', function(){
    ^

TypeError: Cannot read property 'on' of undefined`

**Comment by MarshallOfSound** [comment]
> when i run electron in atom command terminal i get an error

You will have `ELECTRON_RUN_AS_NODE` set as an env var in that terminal (atom terminals do this sometimes incorrectly), unset it and everything will work fine 👍

**Comment by crashbdx** [comment]
Looked online but didnt found where to change that, can you indicate me how to change .ELECTRON_RUN_AS_NODE please ? thanks in advance :)
