### ISSUE TITLE
"Open folder" in dev tools does not work

### ISSUE THREAD

**Issue by pronebird** [electron/electron#15360]
* Output of `node_modules/.bin/electron --version`: 3.0.5
* Operating System (Platform and Version): macOS Mojave
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.x

**Expected Behavior**

"Open folder" should work in dev tools

**Actual behavior**

"Open folder" option does not work.

<img width="278" alt="screenshot 2018-10-24 at 12 45 38" src="https://user-images.githubusercontent.com/704044/47425686-69c8e680-d78b-11e8-9630-3d64d43a41ab.png">

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by ckerr** [comment]
<details><summary>This hits a check crash in `master`:</summary>

[7439:1024/164723.951450:ERROR:CONSOLE(621)] "This must be a file URL.", source: chrome-devtools://devtools/bundled/shell.js (621)
[7439:1024/164725.285994:FATAL:thread_restrictions.cc(29)] Check failed: !g_blocking_disallowed.Get().Get(). Function marked as blocking was called from a scope that disallows blocking! If this task is running inside the TaskScheduler, it needs to have MayBlock() in its TaskTraits. Otherwise, consider making this blocking work asynchronous or, as a last resort, you may use ScopedAllowBlocking (see its documentation for best practices).
#0 0x7f3e312f210d base::debug::StackTrace::StackTrace()
#1 0x7f3e30fd5dec base::debug::StackTrace::StackTrace()
#2 0x7f3e31004ffa logging::LogMessage::~LogMessage()
#3 0x7f3e3120553b base::AssertBlockingAllowed()
#4 0x7f3e312fb127 base::DirectoryExists()
#5 0x55e8d8f18f92 platform_util::ShowItemInFolder()
#6 0x55e8d8e1057d atom::InspectableWebContentsImpl::ShowItemInFolder()
#7 0x55e8d816912d _ZN4base8internal13FunctorTraitsIMN5prefs26ScopedDictionaryPrefUpdateEFvRKNSt3__16vectorINS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS9_ISB_EEEEEvE6InvokeISH_PS3_JSF_EEEvT_OT0_DpOT1_
#8 0x55e8d816908f _ZN4base8internal12InvokeHelperILb0EvE8MakeItSoIRKMN5prefs26ScopedDictionaryPrefUpdateEFvRKNSt3__16vectorINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENSB_ISD_EEEEEJPS5_SH_EEEvOT_DpOT0_
#9 0x55e8d8169025 _ZN4base8internal7InvokerINS0_9BindStateIMN5prefs26ScopedDictionaryPrefUpdateEFvRKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENSA_ISC_EEEEEJNS0_17UnretainedWrapperIS4_EEEEEFvSG_EE7RunImplIRKSI_RKNS5_5tupleIJSK_EEEJLm0EEEEvOT_OT0_NS5_16integer_sequenceImJXspT1_EEEESG_
#10 0x55e8d8168fb4 _ZN4base8internal7InvokerINS0_9BindStateIMN5prefs26ScopedDictionaryPrefUpdateEFvRKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENSA_ISC_EEEEEJNS0_17UnretainedWrapperIS4_EEEEEFvSG_EE3RunEPNS0_13BindStateBaseESG_
#11 0x55e8d81434dd _ZNKR4base17RepeatingCallbackIFvRKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEEEE3RunESC_
#12 0x55e8d8fa0251 _ZN12_GLOBAL__N_110ParamTupleIJEE5ApplyIN4base17RepeatingCallbackIFvRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEEEEJSD_EEEvRKT_DpT0_
#13 0x55e8d8fa01cf _ZN12_GLOBAL__N_110ParamTupleIJRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEE5ApplyIN4base17RepeatingCallbackIFvS9_EEEJEEEvRKT_DpT0_
#14 0x55e8d8f9ff5c _ZN12_GLOBAL__N_114ParseAndHandleIJRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEEEbRKN4base17RepeatingCallbackIFvDpT_EEERKNSB_IFvPKNSA_5ValueEEEERKNSA_9ListValueE
#15 0x55e8d8cb39ad _ZN4base8internal13FunctorTraitsIPFbRKNS_17RepeatingCallbackIFvRKNSt3__16vectorINS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS8_ISA_EEEERKNS_8FilePathEEEESE_SH_EvE6InvokeIRKSN_JSL_SE_SH_EEEbOT_DpOT0_
#16 0x55e8d8cb394d _ZN4base8internal12InvokeHelperILb0EbE8MakeItSoIRKPFbRKNS_17RepeatingCallbackIFvRKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENSA_ISC_EEEERKNS_8FilePathEEEESG_SJ_EJSN_SG_SJ_EEEbOT_DpOT0_
#17 0x55e8d8cb38f0 _ZN4base8internal7InvokerINS0_9BindStateIPFbRKNS_17RepeatingCallbackIFvRKNSt3__16vectorINS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS9_ISB_EEEERKNS_8FilePathEEEESF_SI_EJSK_EEEFbSF_SI_EE7RunImplIRKSO_RKNS4_5tupleIJSK_EEEJLm0EEEEbOT_OT0_NS4_16integer_sequenceImJXspT1_EEEESF_SI_
#18 0x55e8d8cb3824 _ZN4base8internal7InvokerINS0_9BindStateIPFbRKNS_17RepeatingCallbackIFvRKNSt3__16vectorINS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS9_ISB_EEEERKNS_8FilePathEEEESF_SI_EJSK_EEEFbSF_SI_EE3RunEPNS0_13BindStateBaseESF_SI_
#19 0x55e8d8ee1d40 _ZNKR4base17RepeatingCallbackIFbRK4GURLS3_EE3RunES3_S3_
#20 0x55e8d8fa3c5c DispatcherImpl::Dispatch()
#21 0x55e8d8e11d0a atom::InspectableWebContentsImpl::HandleMessageFromDevToolsFrontend()
#22 0x55e8d809fb6f _ZN4base8internal13FunctorTraitsIMN11google_apis13RequestSenderEFvRKNS_7WeakPtrINS2_29AuthenticatedRequestInterfaceEEEEvE6InvokeISA_RKNS4_IS3_EEJS8_EEEvT_OT0_DpOT1_
#23 0x55e8d809fad5 _ZN4base8internal12InvokeHelperILb1EvE8MakeItSoIRKMN11google_apis13RequestSenderEFvRKNS_7WeakPtrINS4_29AuthenticatedRequestInterfaceEEEERKNS6_IS5_EEJSA_EEEvOT_OT0_DpOT1_
#24 0x55e8d8e16f10 _ZN4base8internal7InvokerINS0_9BindStateIMN4atom26InspectableWebContentsImplEFvRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEEJNS_7WeakPtrIS4_EEEEEFvSD_EE7RunImplIRKSF_RKNS5_5tupleIJSH_EEEJLm0EEEEvOT_OT0_NS5_16integer_sequenceImJXspT1_EEEESD_
#25 0x55e8d8e16ea4 _ZN4base8internal7InvokerINS0_9BindStateIMN4atom26InspectableWebContentsImplEFvRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEEJNS_7WeakPtrIS4_EEEEEFvSD_EE3RunEPNS0_13BindStateBaseESD_
#26 0x7f3e32561e7d _ZNKR4base17RepeatingCallbackIFvRKbEE3RunES2_
#27 0x7f3e348ac0dc content::DevToolsFrontendHostImpl::DispatchEmbedderMessage()
#28 0x7f3e33149ed0 blink::mojom::DevToolsFrontendHostStubDispatch::Accept()
#29 0x7f3e34943c73 blink::mojom::DevToolsFrontendHostStub<>::Accept()
#30 0x7f3e2e924465 mojo::InterfaceEndpointClient::HandleValidatedMessage()
#31 0x7f3e2e922eb1 mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept()
#32 0x7f3e2e921342 mojo::FilterChain::Accept()
#33 0x7f3e2e927095 mojo::InterfaceEndpointClient::HandleIncomingMessage()
#34 0x7f3e2e76f315 IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread()
#35 0x7f3e2e765230 _ZN4base8internal13FunctorTraitsIMN3IPC12_GLOBAL__N_132ChannelAssociatedGroupControllerEFvN4mojo7MessageEEvE6InvokeIS8_RK13scoped_refptrIS4_EJS6_EEEvT_OT0_DpOT1_
#36 0x7f3e2e7650ef _ZN4base8internal12InvokeHelperILb0EvE8MakeItSoIRKMN3IPC12_GLOBAL__N_132ChannelAssociatedGroupControllerEFvN4mojo7MessageEEJRK13scoped_refptrIS6_ES8_EEEvOT_DpOT0_
#37 0x7f3e2e765055 _ZN4base8internal7InvokerINS0_9BindStateIMN3IPC12_GLOBAL__N_132ChannelAssociatedGroupControllerEFvN4mojo7MessageEEJ13scoped_refptrIS5_ENS0_13PassedWrapperIS7_EEEEEFvvEE7RunImplIRKS9_RKNSt3__15tupleIJSB_SD_EEEJLm0ELm1EEEEvOT_OT0_NSK_16integer_sequenceImJXspT1_EEEE
#38 0x7f3e2e764f0c _ZN4base8internal7InvokerINS0_9BindStateIMN3IPC12_GLOBAL__N_132ChannelAssociatedGroupControllerEFvN4mojo7MessageEEJ13scoped_refptrIS5_ENS0_13PassedWrapperIS7_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#39 0x7f3e31023bde _ZNO4base12OnceCallbackIFvvEE3RunEv
#40 0x7f3e30fd7102 base::debug::TaskAnnotator::RunTask()
#41 0x7f3e3109703c base::MessageLoop::RunTask()
#42 0x7f3e310972b8 base::MessageLoop::DeferOrRunPendingTask()
#43 0x7f3e31097689 base::MessageLoop::DoWork()
#44 0x7f3e31099f7c base::MessagePumpGlib::HandleDispatch()
#45 0x7f3e310eff51 base::(anonymous namespace)::WorkSourceDispatch()
#46 0x7f3e1c0a9287 g_main_context_dispatch
#47 0x7f3e1c0a94c0 <unknown>
#48 0x7f3e1c0a954c g_main_context_iteration
#49 0x7f3e3109a06f base::MessagePumpGlib::Run()
#50 0x7f3e3109682b base::MessageLoop::Run()
#51 0x7f3e3113ab9d base::RunLoop::Run()
#52 0x7f3e3390a4ec content::BrowserMainLoop::MainMessageLoopRun()
#53 0x7f3e3390a142 content::BrowserMainLoop::RunMainMessageLoopParts()
#54 0x7f3e339100a0 content::BrowserMainRunnerImpl::Run()
#55 0x7f3e338fcc50 content::BrowserMain()
#56 0x7f3e3586d574 content::RunBrowserProcessMain()
#57 0x7f3e3586feb7 content::ContentMainRunnerImpl::Run()
#58 0x7f3e358644ec content::ContentServiceManagerMainDelegate::RunEmbedderProcess()
#59 0x7f3e2a44938a service_manager::Main()
#60 0x7f3e3586a743 content::ContentMain()
#61 0x55e8d7f211ef main
</details>

**Comment by codebytere** [comment]
@ckerr exactly, i've dug into it more and it says `"This must be a file URL."` because of the mangling. Hopefully more answers soon!

**Comment by pronebird** [comment]
Maybe the path doesn’t contain `file://` part somehow?
