### ISSUE TITLE
Developer unable to display the developer tools

### ISSUE THREAD

**Issue by BaraHashesh** [electron/electron#15373]
If the **menus** are set to null using the flowing code `window.setMenu(null);`, the developer becomes unable to display the developer tools using the `shift + ctrl + i` command.

Using electron version 3.0.5.

Note1: It's not per-say a bug. I just want to check if this is the intended behavior or something random.
Note2: The only reason i noticed it, is that i found the menus to to be distracting, so i removed them, first time using the framework.

**Comment by salfredogonzalez** [comment]
Actually i am using electron version 3.0.5 and i have set window.setMenu(null), and the shift + cmd + i its working perfect here, i am using mac.

**Comment by BaraHashesh** [comment]
I'm using it on windows 10, I'm not sure what's the problem, I'm trying to create my first electron app, while using the Angular framework since I have prior experience with it, so I have many dependencies and unable to accurately locate the problem.

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sungdzda** [comment]
Hello OP, I think your issue is as follows:

The default electron menu bar is pre-fitted with some keyboard shortcuts. These keyboard shortcuts (AKA accelerators) are binded with their perspective menu items, so once you remove the menu bar entirely, those shortcuts will not work anymore. This includes the Ctrl+Shift+I which invokes dev tools.

![aa](https://user-images.githubusercontent.com/15174644/47570617-2deb7800-d969-11e8-9ca0-804adc67ce94.png)
