### ISSUE TITLE
Shortcut key to copy file Bug

### ISSUE THREAD

**Issue by shenlanchenwei** [electron/electron#15408]
In Windows System:

Ctrl+C Copy the picture  File, the clipboard cannot read the file path in the normal read cut.
Right mouse button copy can be read normally

Expected behavior
   Normally read the disk path to the copied picture file

Actual behavior
  Ctrl+C Copy the picture  File, the clipboard cannot read the file path in the normal read cut.
  But Right mouse button copy can be read normally

Code:
 path = clipboard.readBuffer("FileNameW").toString("ucs2");

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
