### ISSUE TITLE
Mouse clicks when I release the button

### ISSUE THREAD

**Issue by TheAifam5** [electron/electron#15428]
**Operating System (Platform and Version)**
ArchLinux x64

**Expected Behavior**
I right click (mousedown), the context menu appears, nothing happens when I release the button. To click an item in the context menu, I click it normally with the right mouse button.

**Actual behavior**
I right click (mousedown), the context menu appears, when I release the mouse button (mouseup), the item under the cursor is clicked.
The issue does not occurs when the Program runs in Full-Screen mode, because Context-Menus are placed only on top and bottom of the cursor.

**Tested**
- Different WM (Budgie Desktop, GNOME)
- Different WM themes
- Different Cursor themes
- Different mouses

**Comment by MarshallOfSound** [comment]
> I right click (mousedown), the context menu appears

This sounds like an app implementation issue, Electron has no default context menu and you should be using the `contextmenu` event to create your own, not a `mousedown` event.

If you can provide a repro of this issue using the `contextmenu` event do render the menu we can look at it but from the sounds of it, this is expected behavior with a mis-implemented context-menu.

**Comment by TheAifam5** [comment]
@MarshallOfSound - it‘s VSCode 😂

**Comment by TheAifam5** [comment]
Issue can be closed, since that's VSCode Issue.
