### ISSUE TITLE
request success but throw error "ESOCKETTIMEDOUT"

### ISSUE THREAD

**Issue by qwerchuan** [electron/electron#15447]
Electron v3.0.x ia32 other versions don't have this error.
Platform win10 x64
```javascript
const request = require('request');
const fs = require('fs');
let stream = fs.createWriteStream('d:\\test.txt');
let req = request({
    methods: 'get',
    url: 'https://www.github.com',
    timeout: 10 * 1000
});
req.pipe(stream);
req.on('end', function () {
    console.log('end');
});
req.on('error', function (error) {
    console.log('error', error);
});
```

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
