### ISSUE TITLE
Opening url which propmts download has no default file name

### ISSUE THREAD

**Issue by sglogovic** [electron/electron#15474]
Hi,

There is a bug with electron/chromium when opening url which automatically prompts user with save dialog, file name is always empty. I have tested this in Chrome, Edge and Firefox and they all have specified file name....

As this is window opening another url, there is no showSaveDialog or other handling where i can manually put file name. It is funny as it recognises file extension but not its name

Is there any way to make this work?

1. shell.openExternal(url); / window.location.href = url;
2. 
![image](https://user-images.githubusercontent.com/28756205/47725496-f591b580-dc58-11e8-9cd1-b3ae5f18c456.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sglogovic** [comment]
Thank you for contacting me.

While creating filling out your template and creating new repository, I noticed that the bug was only specific to our applications.... So with a bit of digging I found that we are hooking on 'will-download' and creating new saveDialog and not setting defaultPath.

Thank you once again!
