### ISSUE TITLE
setSize can't shrink non-resizable window (but can grow it)

### ISSUE THREAD

**Issue by CorySanin** [electron/electron#15560]
* Output of `node_modules/.bin/electron --version`: v3.0.7
* Operating System (Platform and Version): Windows 7
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.3 

**Expected Behavior**
mainWindow.setSize can be used to resize a window, regardless if resizable argument is true or false.

**Actual behavior**
The very first time setSize is used, the window can be shrank. After that, it can only grow. If the intended behavior is to not allow for resizing at all, then it shouldn't be able to grow.

**To Reproduce**

```sh
$ git clone https://github.com/CorySanin/electron-quick-start
$ npm install
$ npm start
```
Clicking the resize button several times will illustrate the problem.

**Additional Information**
I can reproduce the growing part on Ubuntu, but can't get the initial shrink to work. Also, I think this only affects versions 3.0.4 and up. 3.0.3 seemed to work as expected.

**Comment by nornagon** [comment]
I wonder if this is related to #15038?

**Comment by mynameisstephen** [comment]
Workaround for this issue, is to call `setMinimumSize` with the target height and with before calling `setSize`.

**Comment by CorySanin** [comment]
Just tried with electron 4.0.5 and the issue is still present. It's really bumming me out that I'm stuck on 3.0.3 🙁

**Comment by jameza111** [comment]
ส่งจากโทรศัพท์มือถือ Huawei ของฉัน-------- ข้อความต้นฉบับ --------เรื่อง: Re: [electron/electron] setSize can't shrink non-resizable window (but can grow it) (#15560)จาก: Cory Sanin ถึง: electron/electron สำเนา: Subscribed Just tried with electron 4.0.5 and the issue is still present. It's really bumming me out that I'm stuck on 3.0.3 🙁



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/electron/electron","title":"electron/electron","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/electron/electron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CorySanin in #15560: Just tried with electron 4.0.5 and the issue is still present. It's really bumming me out that I'm stuck on 3.0.3 🙁"}],"action":{"name":"View Issue","url":"https://github.com/electron/electron/issues/15560#issuecomment-466738831"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/electron/electron/issues/15560#issuecomment-466738831",

"url": "https://github.com/electron/electron/issues/15560#issuecomment-466738831",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by emmkimme** [comment]
I confirmed it is related to #15038. 
In Windows/Linux platform, we have this piece of code for no-resizable window
```
void NativeWindowViews::SetBounds(const gfx::Rect& bounds, bool animate) {
#if defined(OS_WIN) || defined(USE_X11)
  // On Linux and Windows the minimum and maximum size should be updated with
  // window size when window is not resizable.
  if (!resizable_) {
    SetMaximumSize(bounds.size());
    SetMinimumSize(bounds.size());
  }
#endif

  widget()->SetBounds(bounds);
}
```

So as soon as we change the size, the min, max are resetted to the current size.

According to #15038 code
```
void TopLevelWindow::SetSize(int width, int height, mate::Arguments* args) {
  bool animate = false;
>>  gfx::Size size = window_->GetMinimumSize();
>>  size.SetToMax(gfx::Size(width, height));
  args->GetNext(&animate);
  window_->SetSize(size, animate);
}
```
If it is no more possible to resize less than min size.

In a nutshell, we can always increase the size of the window, never decrease !
This case is not covered by unit tests.

I would suggest to revert #15038 until a better solution is found, negative side effect is far more critical than benefit

**Comment by sunylt** [comment]
> Workaround for this issue, is to call `setMinimumSize` with the target height and with before calling `setSize`.

thank you very much, not perfect but very smart idea

**Comment by fxdave** [comment]
I agree with @emmkimme .
For me it was enough to set the minimum size before the setSize:
```javascript
this.window.setMinimumSize(width, height);
this.window.setSize(width, height)
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by CorySanin** [comment]
I bumped up my fork to Electron 8.0.1 and it's still broken. The instructions at the top on how to reproduce are still accurate. I've been using Electron 3.0.3 this entire time because of this issue.

**Comment by ttrepka** [comment]
I can confirm this is happening on Electron 8.2.0, I created a [simple Electron Fiddle](https://gist.github.com/ttrepka/8606197b8d6069e18230e7d5471d190b) to demonstrate.

A workaround I found working is to use `setBounds({ width, height })` instead of `setSize(width, height)`.

**Comment by scris** [comment]
setSize blocks setKiosk as well
(only on Windows, in macOS everything goes well)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by kylefoo** [comment]
This works for me since setFullScreen is async call
```
    if (win.isFullScreen()) {
      win.setFullScreen(false);
      win.once('leave-full-screen', () => {
        win.setSize(arg.width, arg.height);
      });
    }
```

**Comment by ArsalImam** [comment]
> I can confirm this is happening on Electron 8.2.0, I created a [simple Electron Fiddle](https://gist.github.com/ttrepka/8606197b8d6069e18230e7d5471d190b) to demonstrate.
> 
> A workaround I found working is to use `setBounds({ width, height })` instead of `setSize(width, height)`.

You saved my day :+1:

**Comment by thorsent** [comment]
This is still a problem.

**Comment by davidchi31415** [comment]
the solution is to

> ```js
> currentWindow.setResizable(true);
> currentWindow.setSize(width,height);
> currentWindow.setResizable(false);
> ```

taken from https://github.com/electron/electron/issues/16711
