### ISSUE TITLE
Clipboard reads multiple pictures.

### ISSUE THREAD

**Issue by bruce-gou** [electron/electron#15583]
More than two pictures were copied at a time. How can clipboard read these pictures? At present, it seems that only one picture can be read out.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.
