### ISSUE TITLE
3.0.x Windows crash during update - google_breakpad::ExceptionHandler::HandleInvalidParameter

### ISSUE THREAD

**Issue by zeevl** [electron/electron#15598]
* Output of `node_modules/.bin/electron --version`: v3.0.5
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Electron app to update without crashing

**Actual behavior**
Electron update has a hard crash during the initial update process -- window disappears and app fails to update.

**Additional Information**
App is built and deployed using `electron-builder`, however crash happens in v8.    Captured crash on backtrace --
```
[ 0 ] google_breakpad::ExceptionHandler::HandleInvalidParameter... ( exception_handler.cc:580 ) [ 1 ] _strset                                                      ( ucrtbase.dll:undefined   ) [ 2 ] google_breakpad::ExceptionHandler::HandleInvalidParameter... ( exception_handler.cc:572 )
```

Complete dump: [4e.txt](https://github.com/electron/electron/files/2554561/4e.txt)

Note the crash does not happen if the `blockmap` files are removed from deployment server (s3).

**Comment by MarshallOfSound** [comment]
> Note the crash does not happen if the blockmap files are removed from deployment server (s3).

@zeevl Sounds like the blockmap delta update strategy that `electron-builder` [implemented](https://github.com/electron-userland/electron-builder/issues/2851) is causing this issue, probably mis-applying the delta and breaking your executable.  I'd suggest raising this issue with the builder repo.

**Comment by develar** [comment]
@MarshallOfSound No, crash occurred during downloading blockmap data or something before that. Even if there is some bug in electron-updater JS code, it should not lead to crash in electron/nodejs native code.

That's why I asked @zeevl posted issue here because I am not v8 expert and cannot analyze crash dump.

> mis-applying the delta and breaking your executable

not related to this issue, but executable is checked using sha512 checksum, so old executable, that probably also can be previously updated, definitely should be correct.
