### ISSUE TITLE
When giving electron a custom index.js , appPath becomes broken...

### ISSUE THREAD

**Issue by burtonator** [electron/electron#15652]
* Output of `node_modules/.bin/electron --version`: v3.0.8
* Operating System (Platform and Version): Ubuntu 18.0.4

When running electron like:

npx electron web/spectron/example/index.js the appPath (via app.getAppPath()) ends up becoming broken and just:

```
/home/path/to/myproject/node_modules/electron/dist/resources/default_app.asar
```

... this is wrong.

Note that if I just do ```npx electron .``` the value is right and is:

/home/path/to/myproject

... and if I bundle my app as a real APP with .asar packaging I get:

/opt/Polar Bookshelf/resources/app.asar

The problem is that this breaks my spectron tests as I can't find a reliable path to require() my entry point.

**Comment by MarshallOfSound** [comment]
@burtonator This is expected behavior.  `getAppPath()` returns the directory containing the `package.json` used to launch your app.

When you pass in a directory containing a package.json (`electron .`) then that directory is used.  When you pass in an exact path to a JS file as the entry point we use the `default_app/package.json` as the entry and that `default_app` then loads the provided JS file.

**Comment by burtonator** [comment]
@MarshallOfSound If this is true how the heck can you rely on getAppPath?  It's not your appPath at that point... it's something else?

In the first two situations the appPath is sane.  IE it's your actual appPath.. When you pass a custom entry point the app path becomes insane and you can't use it to load resources.

I still insist this is a bug unless I'm missing something.

I mean the only work around is for me to have package.json files everywhere and duplicate node_modules?

This can't be right...
