### ISSUE TITLE
window.open with nativeWindowOpen option always enables nodeIntegration even set it to false

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#15666]
* Output of `node_modules/.bin/electron --version`: 4.0.0-beta.7
* Operating System (Platform and Version): Windows 10 1803 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): no

**Expected Behavior**
A window opened with `nativeWindowOpen` option should disables `nodeIntegration` if it's set to false

**Actual behavior**
`nodeIntegration` is still enabled

**To Reproduce**
* Open a `BrowserWindow` with `nativeWindowOpen` option
* Run `open('', '', 'nodeIntegration=no')`
* There will be a deprecated warning about memory leak of `nodeIntegration`, and `window.require` is still available in the window opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/8194131/48298468-6fe7f280-e501-11e8-9fd2-0c56a8379978.png)

**Additional Information**
The `nodeIntegration` option of parent window is set to true

**Comment by zcbenz** [comment]
This is a side effect since the introduction of the `nativeWindowOpen` option, and unfortunately we don't have a way to fix it because in Chromium it assumes native child windows must share exactly same web preferences with the parent window.

I'm going to make this behavior explicitly documented and close this as won't fix.

Since 5.x, child windows with `nativeWindowOpen` will always have node integration disabled.

**Comment by jkleinsc** [comment]
Closed via #15751

**Comment by pushkin-** [comment]
@zcbenz What is "5.x" in your comment? Are you saying that Electron 5.0+ will have node integration disabled if `nativeWindowOpen` is used, but for right now, it will inherit the parent view's nodeintegration?

**Comment by mehrshadFarzaneh** [comment]
webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      **nativeWindowOpen:true**
  }
