### ISSUE TITLE
browseWindow properties doesnt update.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#15682]
mainWindow = new BrowserWindow({
    height: 600,
    width: 600,
    useContentSize: true,
    transparent: true,
    fullscreenable: true,
    skipTaskbar: false,
    maximizable: true,
    minimizable: true,
    resizable: false,
    show: false,
    movable: false,
    frame: false,
    titleBarStyle: 'hiddenInset'
  })

i dont know when it started to happen.
was set the window to 1920x1080 then i decide to make it smaller.
so i change the values. but was looks weird. so i undo the change.
now this happened.

https://cdn.discordapp.com/attachments/351121729164410882/511490060672172032/unknown.png

pic prov. pls help.

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
