### ISSUE TITLE
Polymer 3 module imports fail..

### ISSUE THREAD

**Issue by eugv86** [electron/electron#15700]
require('./src/index.js') -- Polymer 3.0  Element
"Uncaught SyntaxError: Unexpected token"

see sample

[sample.zip](https://github.com/electron/electron/files/2577449/sample.zip)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
