### ISSUE TITLE
Can register a 'shift' key in globalShortcut

### ISSUE THREAD

**Issue by Menci** [electron/electron#15708]
* Output of `node_modules/.bin/electron --version`: v3.0.9
* Operating System (Platform and Version): Ubuntu 18.04.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
`electron.globalShortcut.register('shift', func);` will result in when I press Shift, the func is called.

**Actual behavior**
TypeError: Error processing argument at index 0, conversion failure from shift.

```
let { app, globalShortcut } = require('electron');

app.on('ready', function() {
  let success = globalShortcut.register('shift', () => {
	console.log('shift');
  });

  if (!success) {
    console.log('Failed to register shift');
	process.exit();
  }

  console.log('registered');
});

app.on('will-quit', function() {
  globalShortcut.unregisterAll();
});
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
