### ISSUE TITLE
Does not show ANSI correctly when run from command file

### ISSUE THREAD

**Issue by cuketest** [electron/electron#15727]
* Output of `node_modules/.bin/electron --version`: v10.2.0
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
When use the control characters in "console.log" statement, it can display color in command line. For example, writing the following two lines in a file called color.js:

```javascript
console.log('\x1b[36m%s\x1b[0m', 'info');  //cyan
console.log('\x1b[33m%s\x1b[0m: ', 'path');  //yellow
```

and then run it using "electron.exe" directly, it shows color characters.

However, when running it using electron.cmd, it does not show color, instead, it just show the control characters directly.

**Screenshots**

![repro_electron_bug](https://user-images.githubusercontent.com/26730486/48540173-54f7f280-e8f4-11e8-91be-8bfb3859f573.png)

**Additional Information**
This is a problem with running electron using command file. Actually I resort to command file because running electron.exe directly under command line has another problem:

It does not return to command prompt when script finished, I have to press an "Enter" in order to return to command prompt. Any idea about this problem?

**Comment by xmedeko** [comment]
Workaround is to use more, see [#1917](https://github.com/electron/electron/issues/1917#issuecomment-275603056)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
