### ISSUE TITLE
How Do you pass flages to NodeJS such as '--experimental-worker'?

### ISSUE THREAD

**Issue by vijayee** [electron/electron#15748]
How do you pass in flags to node to enable experimental features like '--experimental-worker'. I want to use the node version of workers in my electron application.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by vijayee** [comment]
Yeah ..... the forum and slack is dead. How does anyone actually get help with electron. There are other people having the same issue as me needing help.

**Comment by oyalhi** [comment]
Need help with this also. Using Parcel and need `--experimental-worker`.

**Comment by crossle** [comment]
How to enable `--experimental-worker`

**Comment by vijayee** [comment]
@oyalhi  and @crossle  The way you would enable it is ```
$ electron --js-flags="--experimental-worker" your-app
``` taken from https://github.com/electron/electron/blob/451b1782acfef01dd0758e7b9ddb329700626b98/docs/api/chrome-command-line-switches.md
However this will not work because this flag is not available to see all flags  you can use  ```
$ electron --js-flags="--help" your-app
``` and it is not listed. So unfortunately no worker threads in electron yet. I have been using the cluster api instead until this feature is no longer experimental. 
https://nodejs.org/dist/latest-v10.x/docs/api/cluster.html
 I have example code here https://github.com/vijayee/js-offs/blob/master/src/block-cache-cluster.js
vs its worker counterpart  https://github.com/vijayee/js-offs/blob/master/src/block-cache-worker.js
