### ISSUE TITLE
How to use crashReporter in locally?

### ISSUE THREAD

**Issue by zhangxy1035** [electron/electron#15750]
I want to use electron crashReporter to Collect errors locally,I saw the electron api,but i do not know how to use it.can someone help me ? thanks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
