### ISSUE TITLE
Tor connections being made automatically, without user request

### ISSUE THREAD

**Issue by libBletchley** [electron/electron#15793]
* Output of `node_modules/.bin/electron --version`:
`bash: electron: command not found`

* Operating System (Platform and Version):
Debian stretch

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
n/a

**Expected Behavior**
When I launch `wire-desktop` without specifically asking for a proxy, I expect it to connect to the servers directly (not over Tor).

**Actual behavior**
`wire-desktop` discovers that I have Tor running and listening on port `9050`.  It then proxies through port `9050` (and thus Tor) without the user asking for it.

**To Reproduce**
Simply run `wire-desktop` while Tor is running.

**Additional Information**
This was originally reported here => https://github.com/wireapp/wire-desktop/issues/1846 and the closing comment finds that the problem is with "electron".

**Comment by MarshallOfSound** [comment]
@libBletchley My understanding is that this is expected behavior inherited from Chromium.  It's detecting Tor running on your system as a SOCKS proxy and automatically using it.  The workaround you found (forcing `--proxy-server=''`) is how to stop that behavior.

If running chrome on your machine does not automatically tunnel through Tor please ping me in a follow-up comment and we can circle back to this.  For now, closing this out as expected proxy behavior.
