### ISSUE TITLE
app icon resolution is very low.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#15808]
i set it to both .png and .ico (by using 1024x1024) - original image is resolution of 10000x10000.
and it looks really crappy.
https://github.com/Sombian/waifu-material

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Sombian** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀

what templeate? you can get the code with that link.

**Comment by codebytere** [comment]
In order to open this issue you needed to delete the pre-provided issue template. We need you to not delete that, and to fill out the fields.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
