### ISSUE TITLE
after set version compiling not work.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#15804]
i changed the value in package.json in field version.
originally it was 0.0.0 so i changed it to 1.0.0
then i try compile and failed.
then i created a new project paste everything i made expect for package.json and compile work.
https://github.com/Sombian/waifu-material

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by codebytere** [comment]
We haven't gotten a response to our question. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
