### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by joeyer** [electron/electron#15811]
Sentry caught the error of the .dylib dynamic library, but couldn't understand it at all. Is there any way to locate the dynamic library code?

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
