### ISSUE TITLE
I get a problem that electron always shows default app icon. I tried using png, NativeImage, different icon sizes but still the problem

### ISSUE THREAD

**Issue by akshay48299** [electron/electron#15814]
I get a problem that electron always shows default app icon. I tried using png, NativeImage, different icon sizes but still the problem

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
