### ISSUE TITLE
Can NativeImage.CreateFromBuffer() support ico buffer?

### ISSUE THREAD

**Issue by panzhiyi3** [electron/electron#15818]
**Is your feature request related to a problem? Please describe.**
My project use ffi and native module to retrive some ico files,and write them into memory buffer.

**Describe the solution you'd like**
I read the code of AddImageSkiaRep() and it only tries png and bmp, can it also try ico?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
