### ISSUE TITLE
could not creat canvas

### ISSUE THREAD

**Issue by Sakyaa** [electron/electron#15825]
electron all version 
could not creat canvas ,could not creat webgl ,use linux platform ;WebGL2 can be enabled

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
