### ISSUE TITLE
Import of some modules breaks import in anothers

### ISSUE THREAD

**Issue by tehSLy** [electron/electron#15860]
* Output of `node_modules/.bin/electron --version`: v3.0.6
* Operating System (Platform and Version): Windows 10 x64

**Expected Behavior**
Importing a module in some file should not affect imports in other files

**Actual behavior**
In case of import specific modules, some importing variables in other files become `undefined`

**Additional information**
Even order of import affects overall imports, leading to the same error as described above

**Comment by MarshallOfSound** [comment]
@tehSLy Without a code repro we can't look at this but I think you are running into a cyclic `require` issue.  If you have two modules that require each other the final require will resolve to an empty object.

E.g.

```js
// Module 1
require('./2')
```

```js
// Module 2
require('./3')
```

```js
// Module 3
require('./1') // <-- This is an empty object
```

Closing out as expected behavior, please @ mention me in a follow up if this is not the case
