### ISSUE TITLE
symbol lookup error in electron 3 and 4 beta

### ISSUE THREAD

**Issue by burkoyuriy** [electron/electron#15925]
symbol lookup error: node_modules/dbus/build/Release/dbus.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE

In electron 2 work fine.
System: linux mint 19 x64

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by nacmonad** [comment]
getting same error -- but with a built (target=electron, v=4.0.0) version of robotjs on linux

did you ever manage to rebuild your package so it worked?
