### ISSUE TITLE
Mac Os Mojave execute too long

### ISSUE THREAD

**Issue by Kickers** [electron/electron#16003]
Problem with exec (spawn, etc) on Mac Os Mojave. 
Code like this:

`let exec = require('child_process').exec;`
`exec('open', ['-a', 'Safari', 'http://goo.gl/'];`

in development mode work fast. But after packed (like `electron-packager`) it'll have the delay (can reach 40 seconds). 
Similar request in another project - [On Mojave, URLs are slow to open](https://github.com/will-stone/browserosaurus/issues/77#issuecomment-427273863)

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
