### ISSUE TITLE
await keyword blocks creating BrowserWindow

### ISSUE THREAD

**Issue by tncga** [electron/electron#16058]
* Output of `node_modules/.bin/electron --version`: v3.0.11 (also latest nightly)
* Operating System (Platform and Version): Windows 10 Version 1803 x64

**Expected Behavior**
call do_something()
wait its response
create window

**Actual behavior**
call do_something()
wait its response
does nothing, just waits

**To Reproduce**
You can fork [start-electron-window-after-await](https://github.com/tncga/start-electron-window-after-await) to produce it.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/tncga/start-electron-window-after-await.git
$ npm install
$ npm start || electron .
```

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
It's because the `ready` event is fired before you attach the event listener. move the `app.on("ready")` call before the `await`.
