### ISSUE TITLE
How to send messages to another process (other native windows app)

### ISSUE THREAD

**Issue by tillschweneker** [electron/electron#16070]
Is it possible to send messages to other processes, if I know the hwnd? 

I am having a native windows app that sends messages to the electron app via WM_COPYDATA. In electron I use hookWindowMessage to receive the message. 

How can I respond to the message? Is there a method I can use?

Cheers,
Till

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by linglq** [comment]
@tillschweneker HI, did you solve this problem? I have the same question

**Comment by haoxl3** [comment]
@tillschweneker @linglq HI, did you solve this problem? I have the same question

**Comment by scil** [comment]
> 
> 
> @tillschweneker @linglq HI, did you solve this problem? I have the same question

me too.
