### ISSUE TITLE
Fix callback for webContents.print() cancel event

### ISSUE THREAD

**Issue by popod** [electron/electron#16085]
* Electron version: 3.0.10
* Operating System: macOS Mojave and Window 10

**Expected Behavior**
When we cancel the printing (button cancel in the print dialog) after a call to `win.webContents.print()`, the callback should return something.

**Actual behavior**
When we cancel the printing (button cancel in the print dialog) after a call to `win.webContents.print()`, the callback does return nothing.

**To Reproduce**

I want to print an HTML page generated by my electron application and saved to a file. The problem with the following code is : when the cancel button is clicked on the print dialog, the newly created window (`win`) is not closed because the `print()` callback is not called.

As it is an hidden window (the user cannot see the window which is still open and close it), each print make a new "ghost" window. Then when the application is closed (quit) on Windows 10, the "ghost" Windows are not closed and the application cannot be launch again (I use `app.requestSingleInstanceLock()`) without restart the computer or kill each "ghost windows" in the Windows task manager.. This part works fine on macOS as all the "ghost" windows are closed on quit (but this is still an issue since after 50 printing cancelled, we have 50 "ghost" windows)..

``` node
// code on the renderer process
import path from 'path'
import fs from 'fs'
import { remote } from 'electron'

print () {
  const BrowserWindow = remote.BrowserWindow
  const app = remote.app

  const htmlFilePath = path.join(app.getPath('temp'), 'print-test.html')
  const htmlContent = '<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Page title</title></head><body><div id="app"><h1>Hello</h1><p>Lorem ipsum dolor sit amet, nec ne ferri voluptatum. Paulo omnes vituperata qui ex. Ut dicat mediocrem signiferumque pri. Ad mel alterum tincidunt, vero alterum ei usu. Sit te semper consequuntur, alii quot omittam ea mei, in cum stet pertinacia maiestatis.</p><p>Ne mel alii hinc phaedrum. Mel cu ullum philosophia, numquam reprehendunt et mel. Ne pro deleniti torquatos, duo modus omnium ei, mollis expetenda an quo. Minimum accusamus pro eu. No tota pertinax duo, ad pri torquatos mediocritatem.</p></div></body></html>'

  fs.writeFileSync(htmlFilePath, htmlContent)

  let win = new BrowserWindow({ width: 800, height: 600, show: false }) // note that this is an hidden window !
  win.loadURL('file://' + htmlFilePath)

  win.on('closed', () => {
    win = null
  })

  win.webContents.on('did-finish-load', function () {
    win.webContents.print({}, function (success) {
      if (success) {
        console.log('print success')
      }
      // this is not called if the print is canceled (click on the cancel button in the print dialog)
      win.close()
    })
  })
}
```

So I have no idea of how to close the window after a print cancel. Is it a bug that the callback is not called ? How can I workaround this problem ? Thanks

--
It could be linked with this issue #15568.

**Comment by codebytere** [comment]
@popod i think i see the locus of this issue, looking into it now!

**Comment by popod** [comment]
@codebytere yes thanks !

It is right than this issue is not really clear.. in fact, it describe two issues:

- the bug with the callback which is not called when the user close (button cancel) the print dialog
- an other bug ? where the application could not be quit when they are "ghost windows" opened

> Then when the application is closed (quit) on Windows 10, the "ghost" Windows are not closed and the application cannot be launch again (I use app.requestSingleInstanceLock()) without restart the computer or kill each "ghost windows" in the Windows task manager.. This part works fine on macOS as all the "ghost" windows are closed on quit.

**Comment by fxha** [comment]
@codebytere  I have not the possibility to build Chromium/Electron from source but you call the print callback only in the  `ReleasePrintJob` method in your [print patch](https://github.com/electron/electron/blob/01c8f698ee054d84b5345849f6aa7709405587ef/patches/common/chromium/printing.patch#L133).  The callback is called correctly when printing finished successfully. When you cancel the print dialog and open another print dialog, the first callback is called before the native dialog is shown and the new/newest callback is only called when the window is closed. I guess the callback (`OnceCallback`) is a `unique_ptr`-like type and therefore the callback is called before because it goes out of scope. This means you leak the callback because the `ReleasePrintJob` method is never called when the dialog is cancelled but if you print or just cancel the dialog again the callback goes out of scope because you reassign the value.

For example [TerminatePrintJob](https://chromium.googlesource.com/chromium/src.git/+/69.0.3497.128/chrome/browser/printing/print_view_manager_base.cc#571) only calls `ReleasePrintJob` when a `print_job_` already exists. Maybe this is not the case when the print dialog is cancelled?

**Comment by popod** [comment]
@codebytere thanks for your job on this issue !

Could this other issue #17265 be related with your current works on `webContents.print()` ?

Thanks

**Comment by popod** [comment]
@codebytere any news about this issue ? Is your PR still in draft ? Thanks

**Comment by popod** [comment]
Thanks, the callback problem is fixed in Electron `5.0.0`.

**Comment by fxha** [comment]
Thanks @codebytere for the fix :+1: I noticed another issue when cancelling the print dialog with Electron `v5.0.6` the renderer content freezes and you cannot longer click on elements on Linux - maybe other OSs too.

As this problem is related to this issue I'll describe details here. Please clone `electron-api-demos` and apply the patch below. Now run `npm run dev` and click on `Print` and cancel the dialog. After the cancellation you cannot longer click on buttons or other elements on the rendered page like the navigation. What I also noticed is when clicking on `full API documentation` link on `Create and Manage Windows` tab, the URL is opened in my default browser but after the print dialog was cancelled and the content freezed, the URL is loaded in Electron and I can navigate again.

```
diff --git a/main-process/menus/application-menu.js b/main-process/menus/application-menu.js
index b543889..60a3d5b 100644
--- a/main-process/menus/application-menu.js
+++ b/main-process/menus/application-menu.js
@@ -120,6 +120,13 @@ let template = [{
     click: () => {
       shell.openExternal('http://electron.atom.io')
     }
+  }, {
+    label: 'Print',
+    click: (item, focusedWindow) => {
+      focusedWindow.webContents.print({ printBackground: true }, success => {
+        console.log('Printed?', success)
+      })
+    }
   }]
 }]
 
diff --git a/package.json b/package.json
index 64b2a22..16becc7 100644
--- a/package.json
+++ b/package.json
@@ -48,7 +48,7 @@
     "standard": "^8.2.0"
   },
   "dependencies": {
-    "electron": "^5.0.1",
+    "electron": "^5.0.6",
     "electron-log": "^2.2.14",
     "electron-settings": "^3.0.7",
     "electron-shortcut-normalizer": "^1.0.0",
```

**Comment by codebytere** [comment]
@fxha seems the same as this issue, no?

https://github.com/electron/electron/issues/19008

ill tack this onto my backlog too :)

**Comment by fxha** [comment]
Yes, that's actually the issue but also button `onclick` events are affected. Just to your knowledge page scrolling and the `click` and `keyup` events added with `addEventListener` seem to work though.

**Comment by codebytere** [comment]
@fxha ty for the extra context; would you mind adding that to the issue i referenced so i ensure i'm checking for that as i work on a fix?
