### ISSUE TITLE
Crash in HttpAuthHandlerNegotiate::CanDelegate()

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#16131]
* Output of `node_modules/.bin/electron --version`: `3.1.0-beta.4`
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `3.x`, `4.x`

**Expected Behavior**
No crash.

**Actual behavior**
Crash. The [stack trace can be found here](https://gist.github.com/felixrieseberg/f9ad35a0312e848ae8c65bc49229684e).

Here's what's happening: In [this method](https://github.com/chromium/chromium/blob/027e10cae66f0255b3f02d41b9dad35b031903a8/net/http/http_auth_handler_negotiate.cc#L372-L379), `http_auth_preferences_` is a `nullptr`.

**To Reproduce**
I've made a fiddle here: https://gist.github.com/2fcbd2b8b4a9f795a7fe9cbeddfd405e

The root cause of this bug is an image in the renderer:

```html
<img src="https://autologon.microsoftazuread-sso.com/5e729370-42c0-400b-856a-8d18bcda2139/winauth/sso?desktopsso=true&amp;isAdalRequest=False'">
```

As soon as the request is made, Electron crashes. It's unclear what exactly about this destination is so crash-worthy - I've tried various other nasty endpoints (HTTP auth, etc) and couldn't find another one that crashes.

**Comment by deepak1556** [comment]
@felixrieseberg thanks for the repro!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
