### ISSUE TITLE
Feature : Is it possible to use electron for developing a website ?

### ISSUE THREAD

**Issue by shirishjambhorkar** [electron/electron#16229]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Comment by shiftkey** [comment]
@shirishjambhorkar thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
