### ISSUE TITLE
One key and a mouse click response a uncontronl event! [question]

### ISSUE THREAD

**Issue by WytheO** [electron/electron#16220]
+ I know i should try to find the answer in completed issues before open it and i truly tried some

# Description

Every time i clicked（mouse，left，once） the tag to control my program's router （electron-vue，router controled by vue-router）with keyboard pressed （any of ctrl ,shift or alt，or arbitrary combination of them）,It will create a new empty window（version 1.7.5）or new same program（version 4.0.0）like this:

![image](https://user-images.githubusercontent.com/38578631/50557717-bd732580-0d22-11e9-9972-5842872c2501.png)

Result:

![tim 20181231171849](https://user-images.githubusercontent.com/38578631/50557747-0d51ec80-0d23-11e9-9aab-a0f3e3d9fab7.png)

+ I checked my program and didn't find the code about this shortcut yet

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by WytheO** [comment]
OK
