### ISSUE TITLE
electron v4 - webview video full screen not work

### ISSUE THREAD

**Issue by absunstar** [electron/electron#16236]
when open youtube view or other site full screen mode not work
this problem not exists in older version

this problem in videos only

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
