### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by SheldonFei** [electron/electron#16259]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Comment by SheldonFei** [comment]
Recently, there are some problems in using Electron. 
. We developed with Vue + electronic. When we run on the Windows, we find that the frequent operation will quickly rise the memory usage, which will eventually lead to memory overflow. We use a lot of Websocket in our program, I don't know if this is the reason. I hope I can get technical help from the development team. Thank you.

**Comment by felixrieseberg** [comment]
Hey, thanks for opening an issue! Sadly, in its current state, the issue is neither actionable nor helpful - please take a moment to review our [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md). If you have any questions about them, feel free to reach out ℹ️
