### ISSUE TITLE
ARM Version giving Trace/Breakpoint trap

### ISSUE THREAD

**Issue by medemi68** [electron/electron#16290]
Hi, 

I am getting the same issue as someone else on here, except my processor is supported (Armv7l).

I am running it on an Orange Pi PC with an Allwinner H3.

I am using a custom version of Buildroot with all the dependencies installed.

Any help would be greatly appreciated.

P.S. using version 4.0.1

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
