### ISSUE TITLE
Using NTLM relevant headers

### ISSUE THREAD

**Issue by bargiladnice** [electron/electron#16321]
**Expected Behavior**
i'm trying to use 'session.defaultSession.allowNTLMCredentialsForDomains' to support on NTLM authentication on my app. my client side is Angular 7 that the electron wraps.
i expected to view on the header of the requests header of 'Authorization' that the value is starts with 'NTLM Tl...........'

**Actual behavior**
The header of the requests header of 'Authorization' that the value is starts with 'Negotiate YIG......'.
that's means the application tried to sent authorization headers that impliments Kerberos protocol, instead of NTLM protocol.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
