### ISSUE TITLE
Always Need New App in electron  on Windows 10 

### ISSUE THREAD

**Issue by franssuny** [electron/electron#16336]
![capture](https://user-images.githubusercontent.com/17058224/50893941-a7f1b000-1434-11e9-875b-e71516e64af5.PNG)

Hello i have problem in windows 10 always request this permission, how to fix it ?

Thanks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
