### ISSUE TITLE
Roteamento Angular Electron

### ISSUE THREAD

**Issue by vinisnt** [electron/electron#16339]
I made the installation of Electron in an Angular CLI project with routing between the pages, but this routing does not work in Electron, what can it be?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
