### ISSUE TITLE
There is problem with using offscreen-rendering in Ubuntu 18.04. I have to remove this : webPreferences: {       offscreen: true     } to get screenshot of my web page

### ISSUE THREAD

**Issue by HP213** [electron/electron#16337]
> 

* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Comment by HP213** [comment]
![screenshot from 2019-01-09 14-04-21](https://user-images.githubusercontent.com/34127674/50902670-80292a80-13e9-11e9-8af5-39a17dd234eb.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
