### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by wkibbler** [electron/electron#16389]
using the electron-quick-start app, starting it up with npm start after cloning everything works perfectly but then when i run npm install and then start it up again i loose the use of keyboard shortcuts such as control + R, control + shift + i and get this issue in the browser console
 `Electron Deprecation Warning (nodeIntegration default change) This window has node integration enabled by default. In Electron 5.0.0, node integration will be disabled by default. To prepare for this change, set {nodeIntegration: true} in the webPreferences for this window, or ensure that this window does not rely on node integration and set {nodeIntegration: false}.` 
never had this issue before, not sure whats going on

**Comment by wkibbler** [comment]
changed electron version in dev dependencies to 3.0.4 and it works however i feel it is a bit of a hacky approach

**Comment by Aarbel** [comment]
faced same issues, any alternative solution for 4.x ? @wkibbler

**Comment by Aarbel** [comment]
Adding this solved it :

mainWindow = new BrowserWindow({
        …
        webPreferences: {
            nodeIntegration: true,
        }
    });

**Comment by DeerMichel** [comment]
Is this issue still relevant in Electron v5 or v6?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
