### ISSUE TITLE
Electron apps not getting X11 properties on Linux

### ISSUE THREAD

**Issue by arifzeeshan** [electron/electron#16415]
* Output of `node_modules/.bin/electron --version`: 4.0.1
* Operating System (Platform and Version): Arch Linux 64 bit
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Unknown

**Expected Behavior**
Compiz WM Compiz gets icons from applications using XGetWindowProperty() for the _NET_WM_ICON atom and parsing the data. But when using the electron applications they are not  setting icon as a X window property and thus there is a missing icon in WM. 

**Actual behavior**
`xprop` does not show an icon for any electron applications while other applications do.
 Applications (such as window managers) cannot get the electron application icons using e.g. `XGetWindowProperty().`

![electron-minimized](https://user-images.githubusercontent.com/26674272/51223014-21722c80-1966-11e9-8765-93eaf469fcfc.png)
In the above screenshot, Compiz is forced to use default icon as it can't find a icon using `xprop`

**To Reproduce**
All the Electron apps not getting icon. 
Run `xprop` and click on an electron app and then run `xprop` and click on any other app (that does set an icon).

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by arifzeeshan** [comment]
I have filled the template. Please open the issue.

**Comment by Crandel** [comment]
Is there any news about this issue? This drive me crazy especially if so many apps used electron nowadays

**Comment by arifzeeshan** [comment]
It has been almost a year since filing this bug.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by CapOM** [comment]
Still happen

**Comment by sofianguy** [comment]
@CapOM which version?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by geigerzaehler** [comment]
This is still an issue for me on the latest Electron (v13.2.3)

**Comment by RobinBoers** [comment]
This is also an issue in v14.0.1

**Comment by soechka** [comment]
still

**Comment by HoratioVonBecker** [comment]
So this recently occurred to me, I don't know what caused it (best guess: an update broke it), and I have spent ~6 hours trying to fix it. I am on Linux Mint 22.3 Xfce edition, Obsidian was installed via Flatpak, and while I found a solution on the Linux Mint forums that _nearly_ works (https://forums.linuxmint.com/viewtopic.php?t=444222), the final step doesn't (due to deeply frustrating launcher issues).
So I would really like this fixed at the source, if possible. What other information is needed?
