### ISSUE TITLE
Widevine not working on Electron 4.0.1

### ISSUE THREAD

**Issue by amit996** [electron/electron#16446]
I need Widevine on electron app
I copied the widevinecdm.dll from Google Chrome. The CDM minimum version support is 68.0.3430.0
Widevine version 4.10.1224.7
On main.js

`app.commandLine.appendSwitch('widevine-cdm-path', path.join(__dirname, 'widevinecdm.dll'));
app.commandLine.appendSwitch('widevine-cdm-version', 4.10.1224.7);`

and then
`win = new BrowserWindow({
        width:1000,
        height:800, 
        webPreferences: { plugins: true}
    });
    win.loadURL("http://www.dash-player.com/demo/drm-test-area/")`

But this page shows NO Drm Support

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by steverandy** [comment]
@amit996 try to set widevine-cdm-path to the parent folder. It works in my case. You can view the example here: https://github.com/steverandy/electron-quick-start/tree/v4-cdm
