### ISSUE TITLE
MacOS keypress

### ISSUE THREAD

**Issue by GitNomster** [electron/electron#16483]
* Output of `node_modules/.bin/electron --version`: 3.1.0
* Operating System (Platform and Version): MacOS Mojave 10.14.2

**Expected Behavior**
When I hold down the key - only one letter is typed and that's it. This problem appears in input type text.

**Actual behavior**
When the key is pressed - the letters are printed.

**To Reproduce**
[Repo](https://github.com/GitNomster/electron-quick-start.git) to reproduce. Focus input. Try to hold down key.

```sh
$ git clone https://github.com/GitNomster/electron-quick-start.git
$ npm install
$ npm start
```

**Comment by nornagon** [comment]
Hi, thanks for the simple repro! This seems like expected behaviour in macOS. On my machine (High Sierra), key repeating behaves identically in Chrome and Electron.

See e.g. [this article](https://www.howtogeek.com/267463/how-to-enable-key-repeating-in-macos/) about how to change macOS's behavior.

I'm closing this for now but do let us know if you're seeing different behaviour in Chrome vs. Electron, or if enabling key repeating doesn't work in Electron (but does in Chrome).
