### ISSUE TITLE
Environment not supported with AngularFire Auth

### ISSUE THREAD

**Issue by andres01gc** [electron/electron#16586]
`angular version 7.2.2`:
`angulaFire 5.1.1`
`electron version 6.4.1`:
`Operating System Windows 10 64 bits`

**Expected Behavior**
login with AngularFire Google auth on electron application.

**Actual behavior**
when I run the app after tested correctly on chrome with ng serve , the google popup is not working,

`This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.`

**To Reproduce**

after adding this to module..
`  imports: [
    AngularFireModule.initializeApp(firebaseConfig),
    AngularFireDatabaseModule, AngularFireAuthModule, AngularFireModule, ...
  ]`

I followed this guide
https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md

```
export class AppComponent {
  constructor(public afAuth: AngularFireAuth) {
  }
  login() {
    this.afAuth.auth.signInWithPopup(new auth.GoogleAuthProvider());
  }
}
```

main_electron.js
```
const {app, BrowserWindow, ipcMain} = require('electron');
let win;

function createWindow() {
  win = new BrowserWindow({width: 800, height: 600, frame: false});
  win.loadFile('./index.html');
  win.webContents.openDevTools();
  win.maximize();
  win.on('closed', () => {
    win = null
  })
};
app.on('ready', createWindow);
```
similar to issue #11366

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
