### ISSUE TITLE
Electron preload scripts do not wait for promise resolution

### ISSUE THREAD

**Issue by alexgreenland** [electron/electron#16797]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
4.0.3

### Expected Behavior
When running asynchronous code, the preload script should complete when the returning promise is resolved.

### Actual behavior
When running asynchronous code, the preload script will finish before the promise is resolved, and page code is executed.

This might be considered a feature, but IMO this doesn't do what you expect, as AFAIK you can't synchronously block while waiting for a promise to resolve.

**Comment by MarshallOfSound** [comment]
> This might be considered a feature, but IMO this doesn't do what you expect, as AFAIK you can't synchronously block while waiting for a promise to resolve.

This is expected behavior, if there is no synchronous version of what you want to do you can use `ipcRenderer.sendSync` to offload the asynchronous work to another process and block the renderer process while it waits for the `returnValue`.  I wouldn't recommend doing this, instead you should handle doing things asynchronously but if you can't then `sendSync` is always an option.

**Comment by alexgreenland** [comment]
Thanks for the quick reply.

Indeed I want to do everything asynchronously, by doing so, the preload exited too fast and the app in the client side initialised before the promise in the preload finished.

As a workaround, what I ended up doing was exposing the promise on the `window` and deferring for resolution in the page.
