### ISSUE TITLE
Need to document how app.setAsDefaultProtocolClient works in "windowsStore" environment

### ISSUE THREAD

**Issue by ZudoMC** [electron/electron#16852]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.4
* **Operating System** (Platform and Version):
  * Windows 10 1809
* **Last known working Electron version** (if applicable):
  * Not applicable

### Expected Behavior
`app.setAsDefaultProtocolClient("practically-anything")` should register a protocol handler, or fail and return `false`.

### Actual behavior
`app.setAsDefaultProtocolClient("practically-anything")` returns `true` but no protocol handler is registered.

### To Reproduce
This is a tricky one to reproduce, the bare minimum would be:

```typescript
import {app} from "electron";

app.on("ready", () => {
   app.setAsDefaultProtocolClient("practically-anything");
});
```

and packaged as an `appx` with `electron-builder` or [with this guide](https://electronjs.org/docs/tutorial/windows-store-guide).

### Additional Information
Not sure if this is an Electron "bug" or just a specific case for appx distribution. Either way I'd love to hear from someone who knows more about this than me.

**Comment by MarshallOfSound** [comment]
@ZudoMC My understanding is this is working as intended and probably something we just need to document.  When installed as an `appx` your app gets fake versions of a few things including some parts of the registry.  So when we write your protocol handler to the registry it does **succeed**, just it writes it to a fake registry that windows gave your app and your app alone.

In order to register URI handlers in an `appx` you need to do it in the manifest at install time --> https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-protocol

**Comment by ZudoMC** [comment]
Makes sense, thanks 👍
