### ISSUE TITLE
Grandchild window stays open when main/grandparent gets closed on Linux

### ISSUE THREAD

**Issue by Woofthecat** [electron/electron#16897]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 3.1.3 (also present in: 4.0.4, 5.0.0, 6.0.0)
* **Operating System** (Platform and Version):
  * Ubuntu 18.10 x64

### Expected Behavior
I'd expect that if a main window has a child, and that child window has a child (grandchild), then the grandchild also gets closed when the main/grandparent window is closed.

### Actual behavior
The application closes and the grandchild window stays open.

### To Reproduce
```sh
$ git clone https://github.com/Woofthecat/electron-quick-start
$ cd electron-quick-start
$ npm install
$ npm start || electron .
```
The application will create 3 windows. Close the main one and the grandchild will remain opened. It does however gets closed on Windows and macOS.

### Additional information
Ubuntu is running on VirtualBox on Windows. First I noticed this issue when I was running my packaged application (no NodeJS or Electron installed), so I installed NodeJS and Electron and created a minimal app with 3 windows from scratch. It had the same result as explained above.

**Comment by Woofthecat** [comment]
I had some time to test this again, but this time with 5.0.0. Issue is still present.

**Comment by Woofthecat** [comment]
Tested with `6.0.0`, and it's still an issue.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
