### ISSUE TITLE
fullscreen not working with x, y offset on windows

### ISSUE THREAD

**Issue by hovancik** [electron/electron#16907]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  *4.0.4, 3.1.3, 2.0.17
* **Operating System** (Platform and Version):
  * Windows 10
* **Last known working Electron version** (if applicable):
  * works on Mac, Linux

### Expected Behavior

 app is fullscreeen
### Actual behavior

app is not fullscreen
### To Reproduce
```
  mainWindow = new BrowserWindow({width: 800, height: 600, x:1, y:2})
  mainWindow.once('ready-to-show', () => {
    mainWindow.setFullscreen(true)
  })
```

### Additional Information

Works on Linux, MacOS

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by hovancik** [comment]
Still issue in 8.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
