### ISSUE TITLE
App should offer to move itself to /Applications if run from elsewhere

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#1692]
This would be a very nice UX feature. Many users would just run the app directly from the `Downloads` directory.

A lot of apps use this module to achieve it: https://github.com/potionfactory/LetsMove

I realize this is a longshot, but I really like apps that do this and would be awesome if all Electron apps could easily do it.

![image](https://cloud.githubusercontent.com/assets/170270/7651879/e889c388-fb05-11e4-8b0f-69730c291f7b.png)

**Comment by thomasjo** [comment]
I agree that this would be a really great feature, but it should either (1) be opt-in, or (2) possible to opt out, since some developers might not want the feature.

**Comment by jorangreef** [comment]
I have implemented this for my app, but would prefer for it not to be part of Electron core, as it's non-trivial to get right and is very app-specific. That is, each app will want to customize exactly how they move the app to Applications. There are actually a myriad of things which can go wrong along the way.

**Comment by sindresorhus** [comment]
> each app will want to customize exactly how they move the app to Applications

Please elaborate.

> There are actually a myriad of things which can go wrong along the way.

Please elaborate.

**Comment by paulcbetts** [comment]
This seems like it'd be pretty good as a node module, I don't think you need to be in Electron to do this, if only because I imagine that many people would be opinionated about things like the header / message copy, we have to localize it, etc etc etc. 

Alternatively, we could implement the hard part (moving the .app folder), and let the developer just implement the opinionated part (popping the dialog)

**Comment by sindresorhus** [comment]
> This seems like it'd be pretty good as a node module

Sure, that's also an option, but it limits the use considerably. I'm not just asking as a developer, but as a user. As a user I want all apps to do this since it's so convenient and in a consistent way, but I have a feeling few will care or even know about it if it's not in core.

> I imagine that many people would be opinionated about things like the header / message copy, we have to localize it, etc etc etc.

Then have a `header` and `message` option and you can leave localization to the user.

**Comment by tommoor** [comment]
We've decided to just build a typical dmg installer for this purpose, however had this functionality been available we'd probably have used it.

I think the bigger problem is that if you move an electron app whilst it's running as people tend to do when they first download it completely screws up as it can't access any of the files. In our case the behaviour has been wildly unpredictable.

**Comment by paulcbetts** [comment]
> I think the bigger problem is that if you move an electron app whilst it's running as people tend to do when they first download it completely screws up as it can't access any of the files. In our case the behaviour has been wildly unpredictable.

This is a compelling reason for us to do this feature

**Comment by ronelliott** [comment]
Just to add a different view, automatically moving an app to /Applications could not be the desired behavior by the end user. Some users may opt to put personal apps in ~/Applications instead of /Applications. Mostly this would used in cases where the user does not have sufficient perms for /Applications, however I could see some people just preferring this.

**Comment by sindresorhus** [comment]
> In either of these cases this dialog being opened on each launch would quickly become annoying for the user.

It would of course not prompt every time, only the first.

> I think a better option is to architect your app to not require being run from /Applications, and just allow the user to run it from wherever they wish.

I think you're missing the point. It's not about the app not being able to run from outside `/Applications`, I don't think any OS X app has that limitation. Users are free to run their apps from anywhere. This is just about being friendly and ask once to move the app to the `/Applications` folder as that's what 99% of users would want. Nice UX like this goes a long way. [Read this](http://www.potionfactory.com/blog/2009/09/17/move-applications-folder) ;)

**Comment by davej** [comment]
Has anybody implemented something this in Electron? I tried but the move may require admin privileges and there is no way to show a native-looking authentication UI before making the move.

I could show a Web UI but it looks inherently unsafe when a non-system dialog asks for the users credentials, it would also mean that the user's password would be in my apps memory at some stage which I want to avoid if possible.

**Comment by jorangreef** [comment]
I have implemented a sudo for Mac without any native dependencies using a bit of a hack:

1. First try and run the command using sudo in non-interactive mode (with the -n switch). If it succeeds then the command ran and nothing further is required. If the command fails because privileges are required and the sudo timestamp for the user has expired then "sudo: a password is required" will be written to stderr, and privileges need to be requested.

2. Use "which" to lookup the location of the AppleScript binary (osascript) and copy this to a tmp path, but using the name of your application as the name of the copied binary. This causes the OS X permissions prompt to show the name of your application instead of the AppleScript binary.

3. Use the new AppleScript binary to set the sudo timestamp for your user:
```
var command = '"' + tmposascript + '" -e \'do shell script "mkdir -p /var/db/sudo/$USER; touch /var/db/sudo/$USER" with administrator privileges\'';
```
4. Re-run the command that required privileges.

Like this, your app will only request permissions when necessary, and not on every invocation of a command which requires privileges, i.e. only when your sudo timestamp runs out.

Perhaps, it would be a good idea to include this kind of functionality into Electron, as a core building block for more complex features.

**Comment by davej** [comment]
@jorangreef That sounds like a good alternative (and would make a good NPM package). The only issue that I can see is that it will be 'osascript' requesting the privileges instead of {{ myAppName }} and it will also have the Applescript logo instead my app's logo. This isn't a huge deal but for people who don't know what osascript is then it may raise alarm bells.

What about if you saved the Applescript as an app (with your apps logo and name) and packaged it inside of your app? Then you could `exec` the app and it would carry your app's name and logo, so it wouldn't look out of place.

**Comment by jorangreef** [comment]
No, it actually already shows the name of your app properly (see step 2 in my comment above for more detail how it does this). For example, here's a screenshot of my app Ronomon requesting permissions using the steps above:

![sudo](https://cloud.githubusercontent.com/assets/413206/8034777/369efeec-0deb-11e5-87b6-09b73356c603.png)

**Comment by jorangreef** [comment]
Let me know if you would use it as an npm module and I will put it up for you.

**Comment by davej** [comment]
Cool and does anything appear in the dock?

**Comment by davej** [comment]
By the way, yes, an npm module would be great!

**Comment by jorangreef** [comment]
Thanks! It's up at https://www.npmjs.com/package/sudo-prompt

Nothing extra should show in the dock.

**Comment by davej** [comment]
Excellent, thanks!

**Comment by davej** [comment]
For those interested in doing `sudo` stuff with electron. I've put together a module which make it easier to call node functions with administrator privileges: https://www.npmjs.com/package/sudo-fn

It uses @jorangreef's `sudo-prompt` module (OS X only) for pretty auth dialogs.

**Comment by tommoor** [comment]
I've created an npm module to help with this - it's 0.0.1, so not production ready just yet but i'd be interested to get some of you to try it out and help figure out where it falls down 😄 

https://github.com/tommoor/electron-lets-move

**Comment by MarshallOfSound** [comment]
PR up to add API's to do this 👍
