### ISSUE TITLE
Enabling Node.js integration in child windows opened with the "nativeWindowOpen" option will cause memory leaks, please turn off the "nodeIntegration" option. From 5.x child windows opened with the "nativeWindowOpen" option will always have Node.js integration disabled.

### ISSUE THREAD

**Issue by pocesar** [electron/electron#16958]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.3 (related pull #15076)
* **Operating System** (Platform and Version):
  * Windows 10 (1809)
* **Last known working Electron version** (if applicable):
  * 3

### Expected Behavior

Create a new window and just work as expected

### Actual behavior

Error is shown in devtools console but provide no equivalent functionality or workarounds

### To Reproduce

1. have 
```js
webPreferences: {
  nativeWindowOpen: true,
  nodeIntegrationInWorker: true,
  nodeIntegration: true
}
``` 
in your main window

2. use `window.open("about:blank")`

### Screenshots

![image](https://user-images.githubusercontent.com/461084/52772119-e4f62700-301e-11e9-9c31-3b61696ac882.png)

### Additional Information

I'm using React and [ReactDOM.createPortal](https://reactjs.org/docs/portals.html) to write to the newly created window `document.body`, which `new electron.remote.BrowserWindow` doesn't provide. Doing `newWindow.webContents.executeJavascript("window")` makes the code hang. `newWindow.webContents.executeJavascript("document")` returns a stripped down version of `window.document` with only location available and body being "null", therefore can't use createPortal, since it expects a dom node. disabling `nodeIntegration` isn't an option, so this is forced action of having to disable nodeIntegration is putting me between a rock and a hard place

**Comment by funwithtriangles** [comment]
I can confirm this issue is happening on OSX too (10.13.6 High Sierra).

I don't need node integration in the child window, it's just not working at all. The child window has Setting `nodeIntegration` to `false` for the child window doesn't remove the warning, or fix the issue.

Having to downgrade to 3 for now :(

**Comment by pocesar** [comment]
5.0 was released and no workaround for this...

**Comment by dariocravero** [comment]
@pocesar can you do without `nodeIntegration: true` and preload what you need from node land instead?
`react-new-window` works with this config:
```
    webPreferences: {
      nativeWindowOpen: true,
      preload: path.join(__dirname, 'preload.js'),
    },
```
An example of `preload.js` could be:
```
window.electron = require('electron')
```

**Comment by funwithtriangles** [comment]
It seems that this is now fixed with v7?

**Comment by electron-triage** [comment]
Reported as fixed in the above comment. Please upgrade to that as we are no longer supporting versions older than 6.x.y per our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions). We would be happy to reopen if this is still an issue in later versions of Electron
