### ISSUE TITLE
The memory of the main process keeps increasing. What's the matter?

### ISSUE THREAD

**Issue by UoToGK** [electron/electron#17017]
* **Last known working Electron version** (if applicable):
  *   windows

### Expected Behavior
The rendering process keeps opening pages, closing pages and clearing variables, but the memory of the main process is getting larger and larger. Is it a memory leak?

### Actual behavior
Memory increases first and then decreases to maintain a dynamic balance

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
