### ISSUE TITLE
File association not working with appx electron build.

### ISSUE THREAD

**Issue by abiniya-cnr** [electron/electron#17063]
Electron Version -4.0.4
OS -Windows 10 (17134)

Expected Behavior: Launching app(installed from store) using file association(Open with) must launch app and use same appdata that is used by launching app from start menu/Shortcut.

Actual behavior: Launching electron app(APPX) by clicking the exe inside windowsApps folder, launches the app but uses appData in C:\Users\<User>\AppData\Roaming\<app> whereas launching app from startmenu/Shorcut launches app and uses appData in C:\Users\<User>\AppData\Local\Packages\<app>\LocalCache\Roaming\<app>.Is that due to container virtualization and trust issue.How to achieve file association with appx electon build?

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
