### ISSUE TITLE
 WhatsApp works with Google Chrome 36+

### ISSUE THREAD

**Issue by has7eem** [electron/electron#17112]
I am making a WhatsApp client using electron as well.. I tried unregistering the service workers, trying to change the user agent but nothing worked.

**Comment by codebytere** [comment]
@has7eem at present, it's unclear this is a bug. If you'd like the maintainers to triage it as such, you need to go back and fill out the issue template you deleted, complete with version, operating system, expected/actual behavior, and information to reproduce. If you are looking for help, we suggest you consult the community instead of opening a bug report on this repo, and close this issue.

Please @ me in a follow-up comment when you have determined the path you feel is best to proceed with.
