### ISSUE TITLE
Windows borders not perfectly transparent

### ISSUE THREAD

**Issue by MrAmericanMike** [electron/electron#17139]
* **Electron Version:**
4.0.5
* **Operating System:**
Windows 7 - x64

### Expected Behavior
The window shouldn't have any color on the corners and it should be transparent.

### Actual Behavior
Corners aren't rounded perfectly with the transparency.

### Screenshots
https://imgur.com/zNVHZOo
In here we can see the top one an Electron App window and the bottom one is just Firefox

### Additional Information
Sorry if this is not actually a bug, but a feature/setting I'm not configuring correctly for my app.
Weirdly enough once I minimize and maximize the app, the border corner color that is there goes away and the window looks perfect.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
