### ISSUE TITLE
5.0.0beta3 bug

### ISSUE THREAD

**Issue by nwdxlgzs** [electron/electron#17138]
sometimes,it will let PC system haltet

win7 32 5.0.0beta3

----------another----
it start very slowly, maybe it used 5s to start it

win7 32    4

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
