### ISSUE TITLE
Run app in browser without node modules

### ISSUE THREAD

**Issue by pradosh987** [electron/electron#17160]
I am developing angular electron app that uses some node modules like `fs`, `paths` and other node modules and it works fine. I want to run same app in browser but electron is throwing errors like when I use `require`

```
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/pro/app/app/node_modules/electron'
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'path' in '/Users/pro/app/app/node_modules/electron'
```
AFAIK node modules cannot be used in browser, so its there way to conditionally compile using some sort of flag or something. I tried using if like below and got above error.

```
constructor() {
    function isElectron() {
      // Renderer process
      if (typeof window !== 'undefined' && typeof window.process === 'object' && window.process.type === 'renderer') {
        return true;
      }

      // Main process
      if (typeof process !== 'undefined' && typeof process.versions === 'object' && !!process.versions.electron) {
        return true;
      }

      // Detect the user agent when the `nodeIntegration` option is set to true
      if (typeof navigator === 'object' && typeof navigator.userAgent === 'string' && navigator.userAgent.indexOf('Electron') >= 0) {
        return true;
      }

      return false;
    }

    const initElectronCore = () => {
      this.electron = require('electron');
      this.remote = this.electron.remote;
    };

    this.platformElectron = isElectron();
    if (this.platformElectron) {
      initElectronCore();
    }
  }
```

BTW I am using seed from https://github.com/maximegris/angular-electron.git

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
