### ISSUE TITLE
BrowserWindow.webContents.printToPDF() fails/Freezes when used with await from the front end ipcRenderer

### ISSUE THREAD

**Issue by benji0522** [electron/electron#17171]
* **Electron Version:**
  * 4.0.6
* **Operating System:**
windows 10 1803

### Expected Behavior
It shd print using PrintToPDF() when requested from the renderer

### Actual Behavior
Upon the print request from the renderer using await everything freezes

### To Reproduce

//RENDERER
await ipc.sendSync("ExecuteBackendFx", { fxName: "PrintToPDF", fxArgs: null });
//MAIN
global.PrintToPDF = async () => {
let out = await new Promise((resolve, reject) => {
mainWindow.webContents.printToPDF(
{
marginsType: 0,
printBackground: false,
printSelectionOnly: false,
landscape: false
},
function(error1, data1) {
fs.writeFile(rootDir + "/UI/Temp/print.pdf", (data1, error1) => {
resolve("Success");
});
}
);
}
});

return out;
}

### Additional Information

CALL STACK
=========
WebContents.printToPDF (c:\BucksWild\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:218)
dataOut (c:\BucksWild\main.js:310)
global.PrintToPDF (c:\BucksWild\main.js:308)
ExecuteBackendFx (c:\BucksWild\IPCEVENTS.js:131)
InitializeEvents.ipc.on (c:\BucksWild\IPCEVENTS.js:157)
emit (events.js:182)
(anonymous function) (c:\BucksWild\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:355)
emit (events.js:182)

Unable to open 'web-contents.js': File not found (file:///c:/BucksWild/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js).

It prints normally when the request comes from the backend directly.for eg calling the function directly from the debug on VSCODE

**Comment by benji0522** [comment]
STEPS TO REPRODUCE
ipc.sendSync("ExecuteBackendFx", { fxName: "PrintToPDF", fxArgs: null });
  let out = await new Promise((resolve, reject) => {
      mainWindow.webContents.printToPDF(
        {
          marginsType: 0,
          printBackground: false,
          printSelectionOnly: false,
          landscape: false
        },
        function(error1, data1) {
          fs.writeFile(rootDir + "/UI/Temp/print.pdf", data1, error1 => {
            resolve("Success");
          });
        }
      );
    } 
  });

  return out;



PROBLEM IS THAT IT DOESNT EVEN TOUCH the callback from printing but when i use this backend function directly without await on the front end it prints

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by benji0522** [comment]
* **Electron Version:**
  * 4.0.6
* **Operating System:**
windows 10 1803

### Expected Behavior
It shd print using PrintToPDF() when requested from the renderer

### Actual Behavior
Upon the print request everything freezes

### To Reproduce




### Screenshots


### Additional Information

**Comment by benji0522** [comment]
Hey I have put the template. Has someone looked at the issue yet?

**Comment by benji0522** [comment]
NoOne Responded

**Comment by MarshallOfSound** [comment]
@benji0522 Please do not spam issue threads or open duplicates deliberately, Electron issues are not a support forum and there is no guarantee of someone looking at, fixing or implementing your issue.  Please be patient and respectful to the maintainers who spend their time maintaining this project.

**Comment by benji0522** [comment]
ok..Sounds Good.I will wait for sometime

**Comment by benji0522** [comment]
WebContents.printToPDF (c:\BucksWild\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:218)
dataOut (c:\BucksWild\main.js:310)
global.PrintToPDF (c:\BucksWild\main.js:308)
ExecuteBackendFx (c:\BucksWild\IPCEVENTS.js:131)
InitializeEvents.ipc.on (c:\BucksWild\IPCEVENTS.js:157)
emit (events.js:182)
(anonymous function) (c:\BucksWild\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:355)
emit (events.js:182)

**Comment by benji0522** [comment]
IT IS CONFIRMED THAT THE PROBLEM IS WITH THE PROMISES. I can print to pdf when promise is not used.Please fix it.

**Comment by benji0522** [comment]
PROMISE ALSO WORKS WHEN USED WITHOUT AWAIT..Please Check

**Comment by lee-dohm** [comment]
@benji0522, thanks for helping to make Electron better and especially the detailed bug report. You've made it very clear that this issue being fixed is important to you. 

Open source is tricky, and I understand that relying heavily on a project like Electron can be scary, frustrating, and confusing. We do not want to break anyones apps. None of the maintainers want that. We even run a program to help ensure we fix participating app's major issues during our beta cycle.

However, because of the Electron maintainers' limited time and resources, we can't get to everything immediately and some things we can't get to for an extended period. This is common in open source projects. Repeatedly commenting with no new information and "shouting" at the development team by using all caps is not something we do here.

Moving forward, I would recommend reading and following the advice in [Creators, contributors, and collaborators](https://github.community/t5/Studies-in-Community/Creators-contributors-and-collaborators/ba-p/234).

Just to be clear, you are welcome to continue participating in the following ways:

1. submitting bug reports with enough detail to reproduce - ideally a [Fiddle](https://github.com/electron/fiddle) example
1. a new feature request with context
1. logistical questions that may not be covered in the docs (e.g. asking about release timelines in a polite way)

Including additional comments in all caps or responding repeatedly with requests of the maintainer team are off-topic and will result in those issues being closed immediately.

_Please follow the next step exactly_

Let's all take a moment to digest the above. **Please do not interact with the project for 24-hours.** No comments, new issues, or pull-requests. After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to engage going forward.

**Comment by benji0522** [comment]
You don't care about issue and I wasted my time reporting this issue.I fixed it myself.Thanks for teaching me the rules and the ways not to help....Live in the rules and world of arrogance

**Comment by ThomasMoutel** [comment]
Hi @benji0522 , though I can understand your frustration I think you just missed a point here. You're not on a support forum and electron is an open-source project, with volunteer contributors. You cannot expect any level of support, just hope for it.
It would have been nice from you to share your findings once you solved your problem, that's the way it works.

**Comment by benji0522** [comment]
I was expecting better\polite replies.I understand its an open forum.I didn't feel like it was a conversation.I don't expect anything at all now..Cheers

**Comment by lee-dohm** [comment]
@benji0522, we're glad to hear that you were able to find a solution to the problem you experienced.

On the other hand, claiming that people don't care or that they're arrogant are specifically against the [Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). Continuing with this type of behavior or further violations of the code of conduct will result in you being blocked from the Electron organization.

Additionally, because we believe that further communication on this issue will only result in escalating tensions, we're going to lock the conversation.
