### ISSUE TITLE
support webview method addContentScripts

### ISSUE THREAD

**Issue by njleonzhang** [electron/electron#17209]
### Problem Description
I am working on a tool to debug our own web pages, and need inject different code to the guest page according to user's selection. 

for example, there is a page which shows differently when it is opened inside app webview and in a browser. The tool load the page in a `webview`, and provide a `select` for user to set the run time ( inside app/ in browser). 
When `select` is selected, I have to refresh the page, and set a global variable to guest page before the javascript of the guest page is executed. 

Here I encounter problem.

chrome `webview` has an api [addContentScripts](https://developer.chrome.com/apps/tags/webview#method-addContentScripts), which can be leveraged to inject code dynamically to guest page. But It seems electron `webview` doesn't support this method.

### Proposed Solution
support addContentScripts

### Alternatives Considered
any workaround?

**Comment by njleonzhang** [comment]
issue https://github.com/electron/electron/issues/13196 shows that `preload` tag can be leveraged, but `preload` can only work with static files, I need to inject dynamical codes.

**Comment by njleonzhang** [comment]
@sofianguy any workaround for me?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
