### ISSUE TITLE
shadow

### ISSUE THREAD

**Issue by jazzwsr** [electron/electron#17285]
* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**:
  *

**Comment by jazzwsr** [comment]
hello , i find no shadow on win7 system?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by jazzwsr** [comment]
Electron Version: 
1.4.13
Operating System:
Win 7
Last Known Working Electron version:
1.4.13
Expected Behavior:
expected BrowserWindowhas shadow on win7 system.
Actual Behavior:
actual no shadow on win7 system, but can work on win10 system.
To Reproduce:
i create a new BrowserWindow, has shadow on win10, no shadow on win7
Screenshots:
![image](https://user-images.githubusercontent.com/8381304/54098473-ba19ab80-43ef-11e9-8c60-916825a4608c.png)
![image](https://user-images.githubusercontent.com/8381304/54098495-d61d4d00-43ef-11e9-9c77-b8d27a869c90.png)
Additional Information:
As mentioned above

**Comment by sofianguy** [comment]
@jazzwsr We are no longer supporting Electron versions older than 2.0.x. Is this issue present in a newer version?

**Comment by jazzwsr** [comment]
Hi, this issue present in electron V1.4.13，I'm using border resolved~

**Comment by sofianguy** [comment]
We are no longer providing bug fixes for Electron versions older than 2.0.x. Feel free to reach out if you find this bug is still present in later versions of Electron.
