### ISSUE TITLE
Semver documentation issue

### ISSUE THREAD

**Issue by adipascu** [electron/electron#17324]
Right now [the documentation](https://github.com/electron/electron/blob/a958eb9c4434c9004b924871a4c3c7692696d7b1/docs/tutorial/electron-versioning.md) states that electron follows semver since electron 2 .

I have discovered that minor version changes of electron have different native module ABIs.
The different module versions are documented [here](https://github.com/lgeiger/node-abi/blob/9c5acd11ae297c4eabb29c531334dec4b09ebdf3/index.js#L69).

 - Electron 4.0.0 has ABI 64
 - Electron 4.0.4 has ABI 69

I suggest respecting semver (only change de ABI in major versions) or stating this exception in the documentation.

**Comment by MarshallOfSound** [comment]
Please see the discussion in https://github.com/electron/node/commit/8bc5d171a0873c0ba49f9433798bc8b67399788c

We will be releasing `4.1.0` to workaround any `node-pre-gyp` issues folks are having and will communicate more about that change when it happens.

**Comment by adipascu** [comment]
@MarshallOfSound Thank you for the quick response and your work on electron!
Please consider keeping an open issue thread on this, I don't think comments on a diff are the place to discuss such a "hot" issue.

Cheers!

**Comment by MarshallOfSound** [comment]
As far as I know there isn't much discussion to have here, the commit was linked as something to read relevant to your issue not as a "please go talk over here" (you're right you really can't have a discussion on a commit).

What happened here was a non-consistent interpretation of semver.  Namely, if fixing a release line requires changing the ABI number (which some interpret as being a semver major change because that's how node treats it) does that "fix" constitute itself as a breaking change.

We have a plan to mitigate the issues caused by this change (as far as we are aware the only impact is node-pre-gyp modules require rebuilding) by releasing 4.1 as a noop change purely to trigger rebuilds from all the node-pre-gyp modules out there.

If you have questions / thoughts please feel free to use this thread but I'm not on board with leaving it open when we have already determined the path forward.
