### ISSUE TITLE
5.0.0-beta5 distributed node.lib links against node.exe

### ISSUE THREAD

**Issue by PaulFreund** [electron/electron#17326]
* **Electron Version:**
  *  v5.0.0-beta.5
* **Operating System:**
  * Windows 10 (1803) x64
* **Last Known Working Electron version:**:
  * 3.0.3

### Expected Behavior
napi_* functions should be loaded from a file that is available in the electron distribution. (As node.dll is no longer distributed with electron it could also be the electron.exe which includes them) with the right target platform.

### Actual Behavior
When creating an N-PI DLL it is linked against node.exe. This will fail to load with electron.

### To Reproduce
Install VS2017 or VS2017 build tools, CMake 3.12.0 and cmake-js (global and apply patch https://github.com/cmake-js/cmake-js/pull/161/files)

In package.json
"devDependencies": {
    "electron": "5.0.0-beta.5",
}
"cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "5.0.0-beta.5"
}

CMakeLists.txt must include the line "target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB})" which will direct to the node.lib included from:
https://atom.io/download/atom-shell/v5.0.0-beta.5/x64/node.lib (x64)
or
https://atom.io/download/atom-shell/v5.0.0-beta.5/node.lib (ia32)

Both files point to node.exe

### Screenshots
![Link](https://user-images.githubusercontent.com/678367/54110238-30fb7800-43e1-11e9-99cb-8d1410d71bc0.jpg)

**Comment by PaulFreund** [comment]
I'm currently using this code as a workaround in my N-API plugins:

```
//======================================================================================================================
// In CMakeLists.txt we need to add:
// if(WIN32)
//     set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/DELAYLOAD:NODE.EXE" )
// endif()
// The following code will redirect all lookups to NODE.EXE to the current process
//======================================================================================================================

#ifdef _MSC_VER
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #include <delayimp.h>

    static FARPROC WINAPI loadDLLHook(unsigned int event, DelayLoadInfo* info) {
        if (event != dliNotePreLoadLibrary) { return NULL; }
        if (_stricmp(info->szDll, "NODE.EXE") != 0) { return NULL; }

        return (FARPROC)GetModuleHandle(NULL);
    }

    decltype(__pfnDliNotifyHook2) __pfnDliNotifyHook2 = loadDLLHook;
#endif
```

**Comment by nornagon** [comment]
This is intentional, as it allows renaming the `electron.exe` binary. `node.exe` was chosen because it allowed working around a node-gyp limitation that was fixed here: https://github.com/nodejs/node-gyp/commit/3fcddce5972a3e7381092045c26f91d83711a6d7. However, it doesn't matter what the executable is labelled as, the delay-load hook is still necessary if you want to change the name of your executable file. Without the delay-load hook, if your executable is not named `node.exe`, Windows will attempt to load `node.exe` into the process, and won't find it, and the LoadLibrary call will fail.

`node-gyp` automatically includes the delay-load hook for you. `cmake-js` will need to be updated to add the hook.

**Comment by PaulFreund** [comment]
Thank you for the comment. What is the reason to remove the node.dll? The tradeoff to intercept and redirect all loads to node.exe in every node extension seems quite huge.
