### ISSUE TITLE
Context menu closes without callback

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#17341]
* **Electron Version:**
4.0.7, 4.0.8

* **Operating System:**
Linux, macOS 10.14.13

### Expected Behavior
I would expect a context menu opened via `.popup()` to stay open when there is no further user interaction. When it does close, it should always fire the respective event / callback.

### Actual Behavior
The context menu often closes, seemingly randomly. When disappearing this way, neither the callback not the `menu-will-close` event is triggered. In one Electron app I've noticed this reliably on both Linux and macOS after about 10 seconds of inactivity; sometimes (typically right after start-up) even quicker. In the minimal repro below it takes longer, but still less than a minute.

### To Reproduce
This might be tricky to reproduce. Use this [minimal test case](https://github.com/electron/electron-quick-start/compare/master...inukshuk:menu-close-issue) based on electron-quick-start. This pops up a menu at start-up. On macOS / 4.0.7 the menu disappears for me in under one minute, without triggering the respective event/callback. (If I close the menu via clicking, Escape, or switching focus to a different window the event/callback fire reliably.) If I switch the application after the menu has disappeared and then return to the quick start window, sometimes the event/callback will be triggered at that point.

### Additional Information

Might be related to #13934 and #17292

**Comment by MarshallOfSound** [comment]
@inukshuk So what you're seeing here is the `Menu` object is being garbage collected (rightfully so, you don't have any use of it after you create it).

For now you can leak the `menu` object into a different scope to prevent it being garbage collected.  E.g. `global.plzNoGarbageCollect = [menu]`

This is probably something we want to document (It's similar to the GC behavior of our `Notification` objects) rather than forcefully fix but because we are notified of menu closure we may be able to manage this memory a bit better for you.  I'll take a look at some point.

**Comment by inukshuk** [comment]
@MarshallOfSound thank you! Now that you explain it, it makes a lot sense (specifically, why I was seeing this right at start-up). I think the most surprising aspect of this was that the callback was not called when the menu closes (at the same time, it's easy to make the callback a closure over the menu to ensure it's not garbage collected in the first place).
