### ISSUE TITLE
word`s transparent not work

### ISSUE THREAD

**Issue by wlk1204** [electron/electron#17366]
electron v3.0.8 word`s transparent property is ok , but v4.0.3 not work.

![image](https://user-images.githubusercontent.com/33086234/54265540-7f12a600-45b0-11e9-8a5b-e623bee69fc4.png)

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
