### ISSUE TITLE
How can I install and use electron in in anaconda environment?

### ISSUE THREAD

**Issue by xlinxlin** [electron/electron#17370]
Hi all,

I want to install and use electron and set my app in anaconda environment, any suggestions?

I saw an installation command on this page: https://anaconda.org/conda-forge/electron , but I didn't think it works...

Thank you!

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
