### ISSUE TITLE
Hardware acceleration fails to initialise when electron is installed locally to the project. Works when electron is installed globally.

### ISSUE THREAD

**Issue by joel1st** [electron/electron#17437]
* **Electron Version:**
  * Electron 6.0.0-nightly.20190311 and Electron stable: 4.1.0
* **Operating System:**
* Windows 10 Pro - Build 18342
* **Last Known Working Electron version:**:
  * I have tried the stable and nightly versions without success.

### Expected Behavior
When I add electron as a dev dependency of the project, I expect it to handle webgl the same way as when I install electron globally. I expect that if my app is able to create a webgl context when running from a globally installed electron, it should also be able to create a webgl context for a locally installed electron of the same version.

### Actual Behavior
All webgl initialisation calls are failing when electron is installed locally to the project (installed using `npm install --save-dev electron-nightly`).  Project started with `./node_modules/.bin/electron .`
Example error: `THREE.WebGLRenderer: Failed to execute 'getContext' on 'OffscreenCanvas': The provided value 'experimental-webgl' is not a valid enum value of type OffscreenRenderingContextType.`

The exact same calls are succeeding when using a global electron binary (installed using `npm install -g electron-nightly`). Project started with `electron .`

Interestingly enough, if I copy the global electron folder (including all the dll's etc.), into my local project and name it `electron-nightly` and call it as `electron-nightly/electron .`, it gives the same error as if it was installed locally.

Any help would be much appreciated.

**Comment by MarshallOfSound** [comment]
@joel1st What you are seeing I think is conflicting `electron` and `electron-nightly` global installs.

If you run `electron --version` globally you'll probably see a stable/beta version of Electron rather than a nightly.

The string `experimental-webgl` is definitely not a supported context type any more, not sure when / if it was removed but looking at the implementation of [`OffscreenRenderingContextType`](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/canvas/offscreencanvas/offscreen_canvas_module.idl?type=cs&q=OffscreenRenderingContextType&sq=package:chromium&g=0&l=10&rcl=8e87c7f1833f49138268496d47db791f273e785b) it just isn't a valid context type.

According to Can I Use

![image](https://user-images.githubusercontent.com/6634592/54550421-36b90680-4969-11e9-9c4f-afb73d849458.png)

The type `experimental-webgl` was only in use until Chromium 32

**Comment by joel1st** [comment]
Hey @MarshallOfSound 

Thanks for replying quickly.

I believe the reason why we are seeing 'experimental-webgl' showing is because three.js attempts to get an experimental-webgl context if it is unable to get a regular 'webgl' context.
See:
https://github.com/mrdoob/three.js/blob/2a0670b95413ba0f4c49749980500904b156329e/src/renderers/WebGLRenderer.js#L204

Below is proof that both are on the same version:

![Uploading electron versions.png…]()

When I open the dev tools, both say chrome version 73 as well.

It's almost as if the graphics card is not registering at all with the local build, all of css transitions are very janky/laggy, whereas the global installed build are smooth as expected.

**Comment by MarshallOfSound** [comment]
> It's almost as if the graphics card is not registering at all with the local electron, all of css transitions are very janky/laggy, whereas the global installed build are smooth as expected.

That's pretty crazy, gonna ask for a bit more info here.

* How are you launching Electron in both cases (cmd, powershell, etc) and what command are you using
* What is the output of `chrome://gpu` for both instances (global/local)
* Is this reproducible on just your machine or other machines as well

**Comment by joel1st** [comment]
Hey @MarshallOfSound ,

Thanks again for replying quickly:

Global installed electron:
[electron-global.txt](https://github.com/electron/electron/files/2981061/electron-global.txt)

Local installed electron:
[electron-local.txt](https://github.com/electron/electron/files/2981062/electron-local.txt)

It appears that the GPU is crashing on the local build based off the logs. 

I have attempted this on both my home and work computer with the same results. When I attempt to actually package the build I have the same issue (where the GPU doesn't appear to be working).

I've tried booting it from WLS (windows linux subsystem), git bash and cmd. And have seen the same results with all three (global has webgl, local doesn't). 

The command I use from the project directory:
`./node_modules/.bin/electron .` for the local build and `electron .` for the global build.

**Comment by joel1st** [comment]
Interestingly, after `rm -rf` and reinstalling the node modules a couple of times without any success, I removed the entire project and re-cloned, and now it is working as expected! I really have no idea how that fixed it, considering the issue was happening on multiple computers. But all good now.

**Comment by joel1st** [comment]
So one year later, I ran into the same issue and I believe I have worked out the cause. 

It appears to be caused with Windows Linux Subsystem 1 and a directory created with case sensitivity attribute enabled (https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/).
`fsutil.exe file queryCaseSensitiveInfo broken_folder_name` returns: `Case sensitive attribute on directory broken_folder_name is enabled.`
As soon as I clone the project into a folder that wasn't modified by WLS I have no issues with hardware acceleration. 
The working folder:
`fsutil.exe file queryCaseSensitiveInfo working_folder_name` returns: `Case sensitive attribute on directory working_folder_name is enabled.`
This then explains why the global install was working: the globally installed electron didn't have the case sensitivity attribute enabled

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
