### ISSUE TITLE
TypeError: Electron.BrowserWindow is not a constructor

### ISSUE THREAD

**Issue by FHGDev** [electron/electron#17466]
* **Electron Version:**
  * v3.0.10
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
I expected a window to pop up like it's supposed to.
### Actual Behavior
I keep getting the error: "TypeError: Electron.BrowserWindow is not a constructor"

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

In particular we are missing any information on how to reproduce this error

Thanks for understanding and meeting us half way :grinning:

**Comment by OrzX** [comment]
You should run with "electron ./index.js" instead of "node ./index.js"

**Comment by sofianguy** [comment]
@FHGDev Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
