### ISSUE TITLE
Electron+WebBluetooth: RequestDevice not showing dialog

### ISSUE THREAD

**Issue by jacqueline-staub** [electron/electron#17475]
* **Electron Version:**
  *  4.1.0 

* **Operating System:**
  * Windows 10 

### Expected Behavior
I am using WebBluetooth in the newest version of electron (4.1.0) on Windows 10. I added the flag for experimental features in electron's main.js: 

`app.commandLine.appendSwitch('enable-experimental-web-platform-features');`  

I am using the following command to request all nearby BLE devices and to show them in a dialog:

`let options = {
  filters: [
    {services: ['heart_rate']},
    {services: [0x1802, 0x1803]},
    {services: ['c48e6067-5295-48d3-8d5c-0395f61792b1']},
    {name: 'ExampleName'},
    {namePrefix: 'Prefix'}
  ],
  optionalServices: ['battery_service']
}

navigator.bluetooth.requestDevice(options).then(function(device) {
  console.log('Name: ' + device.name);
  // Do something with the device.
})
.catch(function(error) {
  console.log("Something went wrong. " + error);
});` 

I expect to see a dialog popping up and showing all devices.

### Actual Behavior
In reality, no such dialog shows. From reading older issues it seems that this error has existed for a long while, but I suspect it has not been fixed so far. Do you have a workaround so I can still use the WebBluetooth functionality in my electron application? 

### Additional Information
I tried both with electron version 4.1.0 (where the flag still needs to be set, since I am working on Windows 10) and with beta version 5.0 (where in principle the flag is not needed any longer on Windows 10). I tried both Windows and Mac, but neither seemed to work. For me it would be fine to have a workaround that just pair with the first device on the list in case the dialog cannot be shown at the moment.

**Comment by MarshallOfSound** [comment]
You have to listen to [`select-bluetooth-device`](https://electronjs.org/docs/api/web-contents#event-select-bluetooth-device) and show a selector yourself using that API 👍

**Comment by voxson** [comment]
I got the exact same error then @jacqueline-staub, however, the event 'select-bluetooth-device' is never called by my mainProcess. I also use the 'default' code display on the Electron documentation:

win.webContents.on('select-bluetooth-device', (event, deviceList, callback) => {
    // event.preventDefault()
    let result = deviceList.find((device) => {
      return device.deviceName === 'test'
    })
    if (!result) {
      callback('')
    } else {
      callback(result.deviceId)
    }
  })

// Code from my Angular App
navigator.bluetooth.requestDevice({
      acceptAllDevices: true
    }).then(function(device) {
      console.log('Name: ' + device.name);
    })
    .catch(function(error) {
      console.log("Error: " + error);
    });

I suppose I did something wrong and I can't find an example on Google and i don't think it's coming from Angular because all the others event are working perfectly well.

**Electron Version:**

- 5.0.2

**Operating System:**

- MacOS 
- Linux Mint

**Comment by Rekoc** [comment]
I got the exact same error then @jacqueline-staub, however, the event 'select-bluetooth-device' is never called by my mainProcess. I also use the 'default' code display on the Electron documentation:

win.webContents.on('select-bluetooth-device', (event, deviceList, callback) => {
// event.preventDefault()
let result = deviceList.find((device) => {
return device.deviceName === 'test'
})
if (!result) {
callback('')
} else {
callback(result.deviceId)
}
})

// Code from my Angular App
navigator.bluetooth.requestDevice({
acceptAllDevices: true
}).then(function(device) {
console.log('Name: ' + device.name);
})
.catch(function(error) {
console.log("Error: " + error);
});

I suppose I did something wrong and I can't find an example on Google and i don't think it's coming from Angular because all the others event are working perfectly well.

**Electron Version:**

- 5.0.2
**Operating System:**

- MacOS
- Linux Mint
