### ISSUE TITLE
I want to CROD Allow in Webview

### ISSUE THREAD

**Issue by kimyoonchul** [electron/electron#17508]
Hello I'm Kim

var webview = document.getElementById('view');
  
  $("#view").on('did-start-loading', function (e) {
    var session = webview.getWebContents().session;
    const filter = {
      urls: ["http://*/*", "https://*/*"]
    };
    session.webRequest.onHeadersReceived(filter, (details, callback) => {
        details.responseHeaders['x-xss-protection'] = null;
        details.responseHeaders['timing-allow-origin']  = null;
        details.responseHeaders['access-control-allow-origin'] = 'https://www.op.gg';
        details.responseHeaders['access-control-allow-methods'] = 'POST, GET, OPTIONS';

        details.responseHeaders['X-XSS-Protection'] = null;
        details.responseHeaders['Timing-Allow-Origin']  = null;;
        details.responseHeaders['Access-Control-Allow-Origin'] = 'https://www.op.gg';
        details.responseHeaders['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS';
        callback({cancel: false, responseHeaders: details.responseHeaders})
    });
  });

this is my code

I want CROD Allow in webview

but It can't

is Possible CROD Allow in Webview?

If possible I want to have resolved 

I'm Poor eng therefore I can feel so hard

thanks :)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
