### ISSUE TITLE
Background color is slightly off in electron apps

### ISSUE THREAD

**Issue by DictumMortuum** [electron/electron#17516]
* **Electron Version:**
  * 3.1.6
* **Operating System:**
  * Ubuntu 18.04 x64
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
Both my bar and my electron apps have background = #2e3440 according to my custom gtk theme.
On other applications (e.g. firefox) , the colors match and I expect this to happen in electron apps 

### Actual Behavior
Unfortunately it doesn't. Inspecting the background color shows that's correctly set to #2e3440

### Screenshots
![2019-03-22-220636_695x76_scrot](https://user-images.githubusercontent.com/2356012/54850549-12a25000-4cf0-11e9-980d-25a6898df147.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
