### ISSUE TITLE
Enhance crashReporter with optional attachments

### ISSUE THREAD

**Issue by eyardeni** [electron/electron#17678]
breakpad supports specifying list of files that will be sent as attachments along with the minidump when a crash happens. This allows attaching log files that can help debugging a crash.

Please enhance the crashReporter API to support attachments.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by eyardeni** [comment]
thanks for pointing that out..

how do i do it?

**Comment by nornagon** [comment]
This is a good idea but we no longer use breakpad and crashpad doesn't support additional files. We'll add support if crashpad ever adds support for this.
