### ISSUE TITLE
setVisibleOnAllWorkspaces cann't work when dock is hide？

### ISSUE THREAD

**Issue by vifird** [electron/electron#17716]
`setVisibleOnAllWorkspaces` cann't work when dock is hide？
After excuted `app.dock.hide()`, setVisibleOnAllWorkspaces(false)  cann't work, although `isVisibleOnAllWorkspaces()` returns `false`.
To correct this, excute `app.dock.show()`, and delay for a while(200ms), and then `setVisibleOnAllWorkspaces` works correctly.
**Why? Is this a bug?**

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by rahul-dutt-sharma** [comment]
Yes its a bug :) @Ianistor
