### ISSUE TITLE
Dialogs on Windows 10 have insufficient left-padding for window title

### ISSUE THREAD

**Issue by sbatten** [electron/electron#17736]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Any
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**:
  * 

### Expected Behavior

There is sufficient padding on dialog titles.

### Actual Behavior
There is no padding on the left of dialog titles.

### To Reproduce
Use `dialog.showMessageBox` and see that Electron has no space to the left of the message box title.

### Screenshots

![image](https://user-images.githubusercontent.com/6561887/55820443-fc4a1180-5aaf-11e9-87b2-1c6d78b7fdda.png)

### Additional Information
See downstream VS Code issue. https://github.com/Microsoft/vscode/issues/71861

**Comment by DeerMichel** [comment]
Worth to mention that this only occurs when no icon is displayed (which is the case when the `browserWindow` property is passed to the dialog).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
