### ISSUE TITLE
Sqlite is not recognized by electron

### ISSUE THREAD

**Issue by sostenesapollo12** [electron/electron#17733]
Hello guys, do you know why all times I try to use sqlite with electron something wrong happens ? How can I install a package and include it in electron correctly ? (like import)

**Comment by inukshuk** [comment]
See https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
