### ISSUE TITLE
Documentation request :  <webview> "nodeintegrations" and "plugins" props.

### ISSUE THREAD

**Issue by Aarbel** [electron/electron#17777]
These docs are not clear at all to know how to use it ;)

https://electronjs.org/docs/api/webview-tag
![image](https://user-images.githubusercontent.com/25119847/56084841-b9829380-5e39-11e9-9af9-b1c78d9d2427.png)

![image](https://user-images.githubusercontent.com/25119847/56084844-c0110b00-5e39-11e9-89c7-74d080b4f3d0.png)

## How should we access plugins or node within the webview ? 
Thanks for your help !

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
