### ISSUE TITLE
fs.existsSync fail while checking a file path contain dot character

### ISSUE THREAD

**Issue by Leaking** [electron/electron#17913]
Look like this, i have a folder `app.asar` whose name contains dot character, and this folder exists in my mac
but the under line always return false
```javascript
const existResult = fs.existsSync('/Users/quinn/WeTest/WeTest/测试权限，先别加文件/app.asar')

```

Here is my versions detail

```xml
process.versions { http_parser: '2.8.0',
    node: '10.11.0',
    v8: '6.9.427.24-electron.0',
    uv: '1.23.0',
    zlib: '1.2.11',
    ares: '1.14.0',
    modules: '64',
    nghttp2: '1.33.0',
    napi: '3',
    openssl: '1.1.0',
    electron: '4.0.3',
    chrome: '69.0.3497.106',
    icu: '62.1',
    unicode: '11.0',
    cldr: '33.1',
    tz: '2018e' }

```

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.
