### ISSUE TITLE
how to communicate between two iprenderer process(child process)

### ISSUE THREAD

**Issue by tactfulness** [electron/electron#17916]
i'm trying to communicate between two **child process**, anyone here can suggest me the steps

thanks in advance!!

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
