### ISSUE TITLE
custom library

### ISSUE THREAD

**Issue by TeoDoe777** [electron/electron#17918]
Good day, is it possible to create and connect your custom library?
For example, unload a part of logic there and connect it in another place, something like dll

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
