### ISSUE TITLE
Electron 5.0.0 breaks node.js functionality in app scripts on MacOS

### ISSUE THREAD

**Issue by tailorvj** [electron/electron#17976]
### Preflight Checklist

 [ *] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
 [ *] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
 [ *] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.0
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**:
  * v3.1.8

### Expected Behavior

I have an app that runs well on v3.1.8. It is actually targeted for Raspberry Pi, so I kept on using that version, but now that v5.0.0 supports Raspberry Pi, I've decided to start developing for it. 

So, after testing it on my Raspberry Pi succesfully, I changed electron version to 5.0.0 in package.json on my Mac 10.14 development machine, ran npm install and npm start. 

I am calling the following require in my app index.html and using ipcRenderer to communicate with main. 

```javascript
const ipcRenderer = require('electron').ipcRenderer;
```

### Actual Behavior

Regretfully, once I changed electron version on my Mac to 5.0.0, I started getting "Uncaught ReferenceError: require is not defined" errors in the Devtools console and ipcRenderer functionality stopped working, because it relied on node.js require functionality in its' script. 

### To Reproduce

Please clone the following branch from my repo:

```sh
$ git clone https://github.com/tailorvj/fullpagedashboard-client.git -b e5bugmac
$ npm install
$ npm start || electron .
```

Working branch with Electron 3.1.8:

```sh
$ git clone https://github.com/tailorvj/fullpagedashboard-client.git -b experimental
$ npm install
$ npm start || electron .
```

### Screenshots

![Screen Shot 2019-04-25 at 23 34 12](https://user-images.githubusercontent.com/1202692/56772823-3875b580-67c4-11e9-8cd1-70dd9cc6d8d3.png)

### Additional info

I think this problem, specifically on Mac OS, is a result of security measures taken to address sandbox problems encountered in previous versions of Chromium, but it has been taken too far on Mac OS for some reason. 

I haven't tested on Ubuntu or Windows, only Raspbian. Raspbian seems to work. 

Kind regards,
Tailor VJ
FullPageOS product owner

**Comment by MarshallOfSound** [comment]
@tailorvj This is a documented breaking change in `nodeIntegration` setting in Electron 5.0 (It now defaults to `false` instead of `true`).

Refs: https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#new-browserwindow-webpreferences-

As a matter for us to improve our documentation and communication here, is there any way that you think this information could have been surfaced to you differently so you could discover the breaking changes document on your own.  We currently list the breaking changes in the 5.0 blog post and release notes but having received a few of these issues we recognize that there is clearly a missing line of communication here and would appreciate any insight into how we can fix it.

**Comment by tailorvj** [comment]
Thanks, I added the following to main.js new BrowserWindow() and it solved the issue. 

```javascript
    webPreferences: {
      nodeIntegration: true
    }
```

Kind regards,
Tailor VJ
FullPageOS product owner

**Comment by Neguhs** [comment]
Thank you for this! I was having issues with my app since the 5.0 release and this worked.

**Comment by J-Cake** [comment]
I'm on windows, I'm getting the same symptops, except `nodeIntegration` is `true`. yelp!

**Comment by ronen** [comment]
> As a matter for us to improve our documentation and communication here, is there any way that you think this information could have been surfaced to you differently so you could discover the breaking changes document on your own. We currently list the breaking changes in the 5.0 blog post and release notes but having received a few of these issues we recognize that there is clearly a missing line of communication here and would appreciate any insight into how we can fix it.

@MarshallOfSound I know this issue is already closed, but to answer your question:  

The place I looked for breaking changes is the release notes here:
https://github.com/electron/electron/releases/tag/v5.0.0 -- 
and that page doesn't list the change to `nodeIntegration` under "Breaking Changes", instead it's listed at the very end of the list of  "Other changes".  

And I'll admit, I didn't read that far :) -- but even if I had I probably wouldn't have noticed the significance, since I wasn't explicitly aware of the `nodeIntegration` option anyway.    (In fact, because Chrome version *is* listed as a breaking change, I presumed that was the cause of the problem and started looking into differences in Chrome that might explain what was going on.)

So for me best would have been to include the change on that page, under Breaking Changes, along with a quick description of who/what would be affected by it.

FYI I found the solution at https://stackoverflow.com/questions/55093700/electron-5-0-0-uncaught-referenceerror-require-is-not-defined

In any case, thanks for all the great work on electron!
