### ISSUE TITLE
in place promisification seems like a breaking change due to introduction of unhandled rejections

### ISSUE THREAD

**Issue by bughit** [electron/electron#17990]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

If you are terminating on unhandled rejections and an api starts returning a promise (e.g. win.loadURL) this will result in crashes.

* **Electron Version:** 5.0.0
  * 

### Expected Behavior
Promise based api could be given different names, but if breaking changes like win.loadURL are intentional, they should at least be documented as such.

**Comment by MarshallOfSound** [comment]
I assume you mean you are doing something like this.

```js
process.on('unhandledRejection', () => app.quit())
```

IMO doing something like that doesn't make much sense as 99% of unhandled rejections are entirely recoverable.  i.e. they don't break your app.

That said I can see how doing this would cause unexpected behavior initially but I don't think we can or should classify *every* API change as a breaking change.  Because with this logic any change to any API could be considered breaking as it could break someone if they are doing something unusual.

E.g. Adding another parameter to a method

```js
myMethod(...args);
```

That would break because now you may be passing the new argument whether you intended to or not.

The `loadURL` change is rightfully documented as `semver/minor` IMO.  Adding promises can't be considered breaking changes otherwise every single usage of `async` functions in our internal logic would be classified as a breaking change.

So although I empathize that this caught you unawares I don't think we mis-classified this change.

**Comment by bughit** [comment]
> IMO doing something like that doesn't make much sense

1. it's now the node default, that electron is not following, makes its default unusual
2. it actually does makes sense, a rejection in async programming is an analog of an exception in sync, so an unhandled rejection is an unhandled exception, and that's why node started treating them similarly 

> with this logic any change to any API could be considered breaking as it could break someone if they are doing something unusual.

No, not any change, but if before upgrade openURL using code runs fine and after it produces unhandled rejections and exits, that's a breaking change by definition and it's not clear why it shouldn't at least be documented as such, considering you have a section for breaking changes.

**Comment by MarshallOfSound** [comment]
> it's now the node default, that electron is not following, makes its default unusual

Electron handles `uncaughtException` differently from node as well (we do not exit rather log and continue working).  The promise behavior is consistent with that.

Your logic is currently "any change that could cause an unhandled rejection is a breaking change" and that is not true IMO.  Otherwise, every time we add `async () => {}` internally it's now a breaking change because it _might_ reject :/

I stand by the original conclusions.

> So although I empathize that this caught you unawares I don't think we mis-classified this change.

**Comment by nornagon** [comment]
`loadURL` doesn't produce unhandled rejections, as the promise comes with a pre-registered rejection handler.

**Comment by bughit** [comment]
> loadURL doesn't produce unhandled rejections, as the promise comes with a pre-registered rejection 

Thanks, that's good to know. That's worth documenting because otherwise one has to add their own.
