### ISSUE TITLE
How does electron justify chrome startup switches?

### ISSUE THREAD

**Issue by johnyradio** [electron/electron#18021]
Your docs say that you support Chrome startup switches:

http://imfly.github.io/electron-docs-gitbook/en/api/chrome-command-line-switches.html

But, Chromium docs doesn't recommend them:

"It is important to note that using these switches is not supported or recommended. They should only be used for temporary cases and may break in the future."
https://sites.google.com/a/chromium.org/dev/developers/how-tos/run-chromium-with-flags

How does electron team justify supporting switches which aren't "supported" by the browser itself?

thx

**Comment by vladimiry** [comment]
My understanding is that electron supports passing the switches to Chromium which doesn't mean electron is responsible for those switches work well.

**Comment by johnyradio** [comment]
That's my understanding too. That's what i'm asking about. 

The doc lists _specific_ switches "supported" by electron-- not just "we pass through all switches".

**Comment by MarshallOfSound** [comment]
@johnyradio That doc lists the common / important ones that we know work.  Other switches can and do work as well but documenting all of them is not worth the churn.  The ones we have documented such as `--proxy-server` and `--log-net-log` are relatively stable to use but as you pointed out, they are not considered API by Chromium and therefore can be removed, renamed or replaced at any time.

The document doesn't imply any sort of promise that we will maintain these flags if chromium gets rid of them, just that the way Electron currently works it supports using Chromium CLI flags.  If you feel that documentation could be improved we always welcome PRs that improve our documentation 👍

The reason we document the big ones that work is because not all switches work through the `app.commandLine.appendSwitch` API.  All switches should work if you actually use them when launching electron (`electron --foo`) but not all switches work when injected at runtime with `app.commandLine`. 

Refs: https://electronjs.org/docs/api/chrome-command-line-switches#supported-chrome-command-line-switches

**Comment by johnyradio** [comment]
Actually, i'm seeking your opinion that chrome switches, in general, are not know to break anything, they are known to work as advertised, that you know of no reports that they are unsafe or buggy, and the only reason not to use them is because they may be removed or may stop working in the future versions of chrome. 

I ask because someone advised me that chrome switches should _never_ be used-- not even for temporary needs. That seems alarmist and unfounded to me.

**Comment by MarshallOfSound** [comment]
> I ask because someone advised me that chrome switches should never be used-- not even for temporary needs. That seems alarmist and unfounded to me.

I would agree that is a bit excessive.  The main points you need to consider when using Chrome Switches

* They can be removed at any time
* Depending on the switch they may cause unstable behavior, you have to use your own judgement here
  * `--proxy-server` is probably 100% safe
  * `--enable-experimental-3d-canvas-renderering` _might_ cause some issues
  * `--enable-smooth-scrolling` is probably gonna be OK

Many Electron apps I know of use some switches to change behavior or enable/disable features (`--disable-gpu` is a common one).  You have to make a calculated assessment of the flag itself, and the impact it could have on your app.
