### ISSUE TITLE
input = file unfriendly work in mac

### ISSUE THREAD

**Issue by huzaixing123456** [electron/electron#18054]
When the file selection dialog box opens，at the moment ，window loses focus，when to return to window，The file dialog box could not be found，input = file it doesn't work

electron 1.8.7

thanks

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
hi @huzaixing123456 we require our issue template to be filled out. 

Also, we are no longer providing bug fixes for versions of electron older than 3.1.x. Please test on a later version and let us know if the bug still persists.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
