### ISSUE TITLE
recreate main window throw error

### ISSUE THREAD

**Issue by freddy-daniel** [electron/electron#18134]
Issue:
I'm trying to reopen my main window after network reconnect. But it not working properly. It just shows a white blank page.

What I found:
I have enabled developer tools for the main window. And I found URL is not right.

Console tab
```
> window.location.href
<- "chrome-error://chromewebdata/"
```

I'm doing this from main.js after re-connection
```
if (networkErrorWindow && connected) {
  networkErrorWindow.close();
  mainWindow.close();
  createWindow();
}
```

**Comment by mlalkaka** [comment]
I may have run into the same or similar issue. If you listen to the [did-fail-load](https://electronjs.org/docs/api/web-contents#event-did-fail-load) event, what `errorDescription` do you get? You can see an example of how to listen for the event [here](https://github.com/ccnokes/electron-did-fail-load/blob/ce7f3a6d18615cbbf20bc09132bc81f58b7f0496/app/background.js). 

For me, I got the following:
```
Event: [object Object].
Error Code: -21.
Description: ERR_NETWORK_CHANGED.
isMainFrame: true.
Frame Process ID: 35.
Frame Routing ID: 1.
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
