### ISSUE TITLE
"titleBarStyle" on Windows.

### ISSUE THREAD

**Issue by ghost** [electron/electron#18160]
### Problem Description
It's really nice that on MacOS you can just overlay the traffic lights over your application but you can't do it in Windows.

### Proposed Solution
Have "titleBarStyle" on Windows. This would overlay the Window Controls over your application. "hidden" would display the normal window controls, while "hiddenLight" would display those icons in white.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by coolmax10** [comment]
@MarshallOfSound I changed my request to follow the template.

**Comment by mqtik** [comment]
Any updates on this?

This is a must-have. On Linux too.

**Comment by nornagon** [comment]
#29600 seems related.

**Comment by bpasero** [comment]
Isn't this possible now? It even seems to be supported in Electron 13.

**Comment by codebytere** [comment]
Yes, this is supported on all current versions.
