### ISSUE TITLE
De-prioritize SimSun and PMingLiu in the default font fallback list

### ISSUE THREAD

**Issue by be5invis** [electron/electron#18197]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
In current Chromium font fallback implementation, the prioritized font for Simplified Chinese and Traditional Chinese are set to SimSun and PMingLiu _on purpose_, which is very inconsistent with most western typefaces. 

https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/win/font_fallback_win.cc

![image](https://user-images.githubusercontent.com/240091/57318383-d48cae80-712c-11e9-8003-438b2bb60b64.png)
https://www.zhihu.com/question/323244457/answer/675834621

### Proposed Solution

Prioritize “Microsoft YaHei” and “Microsoft JhengHei” instead.

### Alternatives Considered

A better solution may be defining multiple font fallback sequences for different font styles: one for serif, one for sans-serif, and have different priority for specific fonts.

**Comment by nornagon** [comment]
I was hoping you'd also fill out the part of the template that specifies the Electron version that you saw this issue in, as we've changed some font fallback things in recent versions.

In general we tend to follow Chrome's behaviour as closely as we can. For instance, #15486 changed Electron's fallback fonts to match Chrome's. If you believe that this is not the optimal fallback font behaviour for Chrome, consider filing a bug against Chrome at https://crbug.com/new.

**Comment by ShikiSuen** [comment]
@nornagon Considering that this issue is sent by people from Microsoft (as what you may already know) who is working on the CJK font experience of Windows, I suggest you to treat Believe,s opinion prior to Chromium default behavior. If the source code of Edge Chromium is available, its behavior (which is optimized by Microsoft) can be your new reference.

(Sorry for the misuse of certain symbols in this message. I still cannot get used to the Japanese keyboard in the classroom.)

**Comment by ShikiSuen** [comment]
Moving the discussion of this issue (with Chromium) to here:
https://bugs.chromium.org/p/chromium/issues/detail?id=960450

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
