### ISSUE TITLE
how to install  multiple versions of the same application on the same machine

### ISSUE THREAD

**Issue by jhmei** [electron/electron#18363]
how to install multiple versions of the same application on the same machine

**Comment by jhmei** [comment]
@vitaliel @bkeepers @lsegal @probablycorey

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by jhmei** [comment]
Received, thank you for your reply！ @miniak
