### ISSUE TITLE
How to set the value of <input type= "file" > for the rendering process

### ISSUE THREAD

**Issue by Lee66** [electron/electron#18362]
Between system A and system B; A is our own system and B is A third party. I want to input some information of system A into system B and check the correctness manually. However, due to security restrictions <input type= "file" > is not allowed to be assigned by script in the browser. The present solution is realized by electron in combination with a third party testing framework. For example: Puppeteer, nightmare. But this opens the browser in addition and can't be done in electron alone. I don't know if electron has a solution or a better suggestion. Related issues [here](https://github.com/electron/electron/issues/749)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

You're also more than welcome to comment on the issue you linked to and see if others there have more thoughts.
