### ISSUE TITLE
`skipTaskbar: true` does not work if setFullScreen (true) in Win8.1.

### ISSUE THREAD

**Issue by ikehiroki** [electron/electron#18378]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.2
* **Operating System:**
  * Windows 8.1 (It does not occur in Windows 10)
* **Last Known Working Electron version:**
  * 4.1.2

### Expected Behavior
Taskbar icon does not appear.

### Actual Behavior
Taskbar icon does appear.

### To Reproduce
Always reproduce with the code below.
```
'use strict';

var electron = require('electron');
var app = electron.app;
var BrowserWindow = electron.BrowserWindow;

let mainWindow;
app.on('window-all-closed', function() {
  if (process.platform != 'darwin') {
    app.quit();
  }

});
  
app.on('ready', function() {
  mainWindow = new BrowserWindow({
    frame: false,
    show: true,
    transparent: true,
    resizable: false,
    skipTaskbar: true,
  });

  mainWindow.loadURL('file://' + __dirname + '/index.html');
  mainWindow.setFullScreen(true);
  
  mainWindow.on('closed', function() {
    mainWindow = null;
  });

});
```

**Comment by maxbarbieri** [comment]
I'm having the same issue on Windows 7 with Electron v6.0.4, it happens if the BrowserWindow is either in fullscreen mode or in kiosk mode.
In my case the window icon is not shown immediately in the taskbar, but it appears after the taskbar has been opened (for example by pressing the Windows key on the keyboard) and then closed (for example by clicking on the BrowserWindow).
I thought it could be related to the BrowserWindow losing and gaining focus, and actually this solved the issue for me:
```js
mainWindow.on("focus", () => {
    mainWindow.setSkipTaskbar(true);
});
mainWindow.on("blur", () => {
    mainWindow.setSkipTaskbar(true);
});
```

Still, this is not the expected behavior, and the solution I came up with feels more like a workaround than the right way to use skipTaskbar.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by jackple** [comment]
I still have this problem on win7
