### ISSUE TITLE
Will auto-update tolerate a self-signed app on Windows?

### ISSUE THREAD

**Issue by axfelix** [electron/electron#18442]
I have an Apple dev certificate, but I don't really want to have to get a Microsoft one too as they seem more expensive / have a more complicated pricing structure, and as far as I know most managed Windows environments don't defer to Microsoft as a signing authority to nearly the same extent as Macs do with Apple. Do I have to get a Microsoft dev certificate to use auto-update on Windows, or can I get away with self-signing the app?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
