### ISSUE TITLE
 Is it possible to load HTML_CODE string？

### ISSUE THREAD

**Issue by TheoXiong** [electron/electron#18441]
Is it possible to load HTML_CODE string？

Like this：
```
<iframe srcdoc="HTML_code"> 
```

**Comment by vladimiry** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by TheoXiong** [comment]
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

This is very helpful to me, thank you very much.
