### ISSUE TITLE
在remote渲染进程中，使用setMinimumSize设置最小的宽高，同时设置win.setResizable(true)，只能缩放，不能固定到setMinimumSize设置的最小宽高

### ISSUE THREAD

**Issue by 18124772589** [electron/electron#18451]
"electron": "^2.0.4"

let win = remote.getCurrentWindow()

            win.setSize(960, 600)

            win.setMinimumSize(960, 600)

            win.setContentSize(960, 600)

            win.setResizable(true)

            win.center()

            win = null

希望改变窗口的大小，是时设置窗口的最小宽高，并且用户可以改变大小，但是不能缩放小于最小宽度

**Comment by nikolamakin** [comment]
建议自己更改下源代码....

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
