### ISSUE TITLE
Calling `getWebContent` immediately after creating webview would crash webview

### ISSUE THREAD

**Issue by xinnian88** [electron/electron#18462]
When calling `webview.getWebContent` immediately after creating webview, the `createGuestSync` would be called automatically to create WebContent, however Electron also calls `createGuest` asynchronously and another WebContents would be created later, resulting in webview not working. 

### Issue Details

* Electron Version: 4.x and later
* Operating System:macOS 10.14
* Last Known Working Electron version:3.1.9

### To Reproduce

https://github.com/xinnian88/electron-webview-webcontent-bug

**Comment by miniak** [comment]
@zcbenz I would close this one as won't fix as there is no `webview.getWebContents()` anymore in master

**Comment by miniak** [comment]
A possible workaround is to wait for the `dom-ready` event and only then call `webview.getWebContents()`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
