### ISSUE TITLE
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. 

### ISSUE THREAD

**Issue by Yuezi32** [electron/electron#18469]
update Electron 4.0 to 5.0.2, when running build version, got "Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. ".
![1](https://user-images.githubusercontent.com/12807041/58443966-2de26f00-8128-11e9-8dc7-b9b05229b86f.png)

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
