### ISSUE TITLE
Issues with electron on rasbian

### ISSUE THREAD

**Issue by hn6pot** [electron/electron#18481]
Hi, i'm trying to use electron on a raspi but the app object is undefined when i import it from electron.

My electron version is 4.0.1 but its not working on 5.0.2 as well.

For some reason the npm install is not working so i use : sudo npm install electron@4.0.1 -g --arch=armv7l --unsafe-perm=true --allow-root 

i'm running electron with ELECTRON_RUN_AS_NODE = true;

my issue : 
 let userPath = app.getPath('userData');
                                  ^

TypeError: Cannot read property 'getPath' of undefined

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
