### ISSUE TITLE
Can I specify os-specific accelerators to one menu item?

### ISSUE THREAD

**Issue by yafp** [electron/electron#18498]
### Question
Is it possible to define os-specific menu accelerators for one menu item?

### Problem Description
I am using F11 for toggling fullscreen mode in my application.
This seems like the right shortcut, as it is the default in i.e. Firefox and Chrome on Linux.

But F11 seems system-wide preconfigured on osx - as a result pressing F11 in my application on osx triggers the system function and not my function.

Triggering the menu item manually via the menu works as expected.

Therefor it would be great to be able to define an os-speciifc accelerator for my menu item

### Additional Information
I am using electron 4.0.2 right now

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
