### ISSUE TITLE
LoadURL for Childwindow doesnot work in version 5.0.2

### ISSUE THREAD

**Issue by chandrakanthi07** [electron/electron#18497]
I am using angular path to load content for childwindow. However the path is not loaded in the child window.
Below is the code 
child.loadURL('file://' + __dirname + '/index.html#/about');

Please fix this or let me know a workaround, so that i can upgrade the electron version in our app.

This is working in version 4.2.2

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by chandrakanthi07** [comment]
Please let me know where is the template because when I created the issue I
didn't get any.

**Comment by sofianguy** [comment]
@chandrakanthi07 https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by chandrakanthi07** [comment]
closing this and opening new issue with template filled up
