### ISSUE TITLE
Window is still blinking after calling flashFrame with false after several seconds

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#18520]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.2, 5.0.2, 6.0.0-beta.5
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Window is not blinking after calling `win.flashToggle(false)`

### Actual Behavior
Window is still blinking after calling `win.flashToggle(false)`

### To Reproduce
1. Clone the repo (window-flash branch), install modules and start the project:
```sh
$ git clone https://github.com/clusterberries/electron-sample.git -b window-flash
$ npm install
$ npm start
```
2. Minimize the smaller window
3. Click 'Flash toggle' button (it calls `win.flashToggle(true)`, you can see it in the console)
4. Wait for 10-12 seconds (window in the taskbar is orange all the time)
5. Click 'Flash toggle' button once again (it calls `win.flashToggle(false)`)

### Additional Information
The issue is not reproduce if you click the button second time in less than 10 seconds.

**Comment by brenca** [comment]
Based on what I could find out about this on the interwebs, this is expected behavior on Windows. I tried to find a lightweight and stable workaround, but I couldn't so far. Chromium had a [workaround ](https://chromium.googlesource.com/chromium/src/+/55b8563/chrome/browser/ui/views/panels/panel_stack_view.cc#304)a while ago for this problem, but they recreated a window just to reset the taskbar state, and that would be waaay overkill imho.

**Comment by clusterberries** [comment]
@brenca is there any documentation about it? It would be great to have confirmation that it is expected behavior.

**Comment by ericblade** [comment]
hmm.  I am presently finding almost the opposite of issues -- it rarely wants to start flashing, but when it does, it stops just fine.

Since the Win32 API function just does a single flash, it seems that it needs to be controlled by either Electron or Chromium, and that whoever is currently trying to control it doesn't do it right.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
