### ISSUE TITLE
Unable to use NodeJS worker_threads module

### ISSUE THREAD

**Issue by d0peCode** [electron/electron#18540]
### Issue Details

* **Electron Version:**
v5.0.2
* **Operating System:**
  Windows 10
### Expected Behavior
On app ready start nodejs worker which consoles string. 

### Actual Behavior
App crash immediately after run

### To Reproduce
- git clone https://github.com/BorysTyminski/electron-issue.git
- cd electron-issue
- npm install
- npm run start

### Additional Information
I used electron-forge to quick build app.

**Comment by walmat** [comment]
Having the same issue with Electron 4.x.x and Node 12.4. Same behavior and setup. Have you found a fix for this? 

I've tried:
1. `export NODE_OPTIONS=--experimental-worker` in both the runtime script && in my `~/.bash_profile`
2. Running electron as a node process via the `RUN_ELECTRON_AS_NODE=1` flag

I've switched to using a `global.window.Worker` (web worker) for now, but would love to implement this lib in my project as soon as possible. If anyone can shed some light on this, or share a working example, that'd be great!

**Comment by BorysTyminski** [comment]
> Having the same issue with Electron 4.x.x and Node 12.4. Same behavior and setup.

AFAIK Electron ship its own node fork, so your local 12.4 doesn't really matter.

> Have you found a fix for this?

No, still waiting for response. There is pinned discussion #18397 which might be relevant somehow.

**Comment by InfSpell** [comment]
Having the same issue with Electron 5.0.6 and Windows 10 :(
App crash...

**Comment by d0peCode** [comment]
Still no updates I still can not use threads in my electron app :(

**Comment by InfSpell** [comment]
I tested it on - Electron 4, 5, 6 and even 7 ....
The result is the same, app crash :(

**Comment by i7soft** [comment]
i have this problem too

**Comment by d0peCode** [comment]
Is there any chance of some statement from electron team? It's been months now (half year #17030)

**Comment by SaltFish001** [comment]
![04(35B$JGE3MHE)_(S5M$G9](https://user-images.githubusercontent.com/42058801/62835904-27c44f00-bc90-11e9-8ba2-08dc11fa681c.png)
Add NODE_OPTIONS(--experimental-worker) in your system environment variable.Restart terminal.

**Comment by walmat** [comment]
@SaltFish001 And what happens when you try to spawn a worker?

**Comment by SaltFish001** [comment]
> 
> 
> @SaltFish001 And what happens when you try to spawn a worker?

It's work.

**Comment by SaltFish001** [comment]
> 
> 
> @SaltFish001 And what happens when you try to spawn a worker?

sorry, it's seems no working

**Comment by d0peCode** [comment]
I've tried it before even posting this issue. It doesn't change anything. Experimental flag for worker module was only required in node v11 if I remember correctly.

**Comment by coltorchen** [comment]
just require('worker_threads') in render.js
`const {
  isMainThread, parentPort, workerData, threadId,
  MessageChannel, MessagePort, Worker
} = require('worker_threads');`
![image](https://user-images.githubusercontent.com/24756502/63400260-bc078200-c405-11e9-9b6d-53e4d71b6607.png)
I have the same problem about this.

this error seems throwed by node_work.cc, when you try to new Worker object in javascript.

**Comment by codebytere** [comment]
Working on this now - just got https://github.com/electron/electron/issues/18540 up as a partial starter fix :)

**Comment by durasj** [comment]
For anybody interested I think @codebytere meant PR #20416

**Comment by codebytere** [comment]
@durasj yes, but the two issues are tightly connected and will likely involve the same codepaths (which is why i close the other as a duplicate)

**Comment by codebytere** [comment]
Small update - still working on this!

it's related-but-different-than the `ELECTRON_RUN_AS_NODE` issue i put up a PR for earlier. This is related to the way we initialize Node.js in renderer processes and will will require some changes over there which will take a bit longer but which i'll hopefully have more updates soon.

Thanks for your patience, all 😁

**Comment by d0peCode** [comment]
Looking forward for solution as it may allow us to improve efficiency of our applications if we can use other threads for some interval tasks of app.

**Comment by Inomezi** [comment]
> Small update - still working on this!
> 
> it's related-but-different-than the `ELECTRON_RUN_AS_NODE` issue i put up a PR for earlier. This is related to the way we initialize Node.js in renderer processes and will require some changes in our renderer client code which will take a bit longer but for which i'll hopefully have more updates soon.
> 
> Thanks for your patience, all 😁

Hi, is it work already ?

**Comment by Inomezi** [comment]
Hello, will you fix it ?

**Comment by coltorchen** [comment]
Hello,any updates about the issues?
can use worker_threads modules in the electron-8-x-x?

**Comment by codebytere** [comment]
Updates will be posted to this thread, when they occur. For now, you should use web workers. There are fundamental discrepancies in Node.js and Chromium that make this potentially very difficult. No promises can unfortunately be made about whether this is going to be possible.

**Comment by spinorkit** [comment]
For our multi-threaded app, which currently uses web workers for number crunching and I/O with devices, the most serious limitation of web workers compared to node workers is that the former do not appear to run with a v8::Locker in place, which means you can't use v8::Unlocker and switch a thread on to a different isolate where some JS you need is living (this works with node workers).
Would be hard to put a Locker in place for the web workers in Electron?

**Comment by codebytere** [comment]
@spinorkit that in insolation may be more achievable - i'll poke around :)

**Comment by spinorkit** [comment]
Thanks @codebytere , much appreciated!

Currently in an electron web worker, code like :
auto isolate = v8::Isolate::GetCurrent();
bool lockerActive = v8::Locker::IsActive();
bool isLocked = v8::Locker::IsLocked(isolate);

results in both bools being false.

**Comment by huvboo** [comment]
The V8 platform used by this instance of Node.js does not support creating Workers.

**Comment by huvboo** [comment]
I used worker_threads in renderer process. my  electron version is 8.2.0. but it error:
The V8 platform used by this instance of Node.js does not support creating Workers.
why? @codebytere

**Comment by d0peCode** [comment]
@huvboo because electron ship own Node fork. And their fork doesn't enable you to use worker_threads module as you can see this issue is still opened. Just let them work, I'm waiting almost year for this fix and I hope it will be done or if no - they will inform they gave up.

**Comment by d0peCode** [comment]
I think this will not be fixed sadly. @codebytere may you please add some statement and wontfix label and close the issue?

**Comment by dsteinman** [comment]
I'm using Electron v9.0.2 and my worker_thread is working in development mode.

But when I package the application using `electron-build` (yarn run pack) the resulting build cannot find the worker .js file.  This is very close to working.  I just need to know how to add the the .js file to app.asar.

I've tired adding the file to the build using this but it's not working, when the worker is instantiated `new Worker(path)` it throws a file not found exception.

```
"build": {
    "files": [
      "build/**/*",
      "node_modules/**/*",
      "package.json"
      "my-worker-thread.js",
    ],
```

**Comment by dsteinman** [comment]
I still don't know how to add my worker thread file to the app.asar, but I discovered you can load a worker file from the electron `appData` directory.

```
const { Worker } = require('worker_threads');

...

const localPath = Path.resolve(electron.app.getPath('appData'), 'MYPACKAGENAME');
const worker = new Worker(localPath + '/my-worker-thread.js');
console.log('worker', worker);
```

I copied my worker thread files to `appData` manually before running the app.  On my MacOSX system, that is:

```
/Users/USERNAME/Library/Application\ Support/MYPACKAGENAME
```

So, until I figure out how to add the file to app.asar in a way that the Worker() can load this is at least a temporary solution.  The app just needs to download or write the file to `appData` the first time you run the app.

**Comment by jjustin3** [comment]
@dsteinman I've spent more time than I should have on this and ran into the same problem as you. It appears that the `app.asar` entry file doesn't respect the fact I've included a separate .js file when calling `new Worker(<path>)`, even after verifying via `fs.readdir(...)` that the file does exist.

Seeing that `fs` recognizes the file's existance, I managed to get this to work by doing
```
const workerContents = fs.readFileSync(path.resolve(__dirname, 'sysinfo.worker.js'), { encoding: 'utf8' });
...
const worker = new Worker(workerContents, { eval: true });
```
in order to load the contents of the file as a string into the worker constructor. This seems to work after building via `electron-builder`. Definitely not pretty but far better than manually copying to `appData`.

Alternatively, you can try using `electron-builder`'s `extraResources` and reference the worker files that way. I would imagine that works fine.

**Comment by dsteinman** [comment]
> ```
> const workerContents = fs.readFileSync(path.resolve(__dirname, 'worker.js'), { encoding: 'utf8' });
> ...
> const worker = new Worker(workerContents, { eval: true });
> ```

@jjustin3, that's a good idea, just switched to this and can confirm it works.

**Comment by d0peCode** [comment]
@jjustin3 but you load code from js file into your desktop app. This might be a vulnerability.

**Comment by linonetwo** [comment]
But when use in production, worker_therad will error:

```Error: Cannot find module 'xxxxx'```

It works fine in development.

**Comment by jjustin3** [comment]
@linonetwo, what module are you not able to find? `worker_threads`? If that's the case, you are on an older version of Node and need to upgrade to v12+ or use the `--experimental-worker` flag. Also, how are you packaging your app for prod?

**Comment by linonetwo** [comment]
Oh, my error message is actually `Error: Cannot find module 'tiddlywiki'`, it is a 3rd party module.

But I solved it just now.

I can confirm this will work:

```
    extraFiles: [
      {
        from: 'public/libs/wiki/wiki-worker.js',
        to: 'wiki-worker.js',
      },
    ],
```

And `wiki-worker-mamager.js`

```js
/* eslint-disable no-console */
const { Worker } = require('worker_threads');
const isDev = require('electron-is-dev');

const path = require('path');

const WIKI_WORKER_PATH = isDev
? path.resolve(__dirname, './wiki-worker.js')
: path.resolve(process.resourcesPath, '..', 'wiki-worker.js');

// { [name: string]: Worker }
const workers = {};

module.exports.startWiki = function startWiki(homePath, tiddlyWikiPort, userName) {
  const workerData = { homePath, userName, tiddlyWikiPort };
  const worker = new Worker(WIKI_WORKER_PATH, { workerData });
  workers[homePath] = worker;
  worker.on('message', message => console.log(`[${homePath}] ${message}`));
  worker.on('error', error => console.error(`[${homePath}] ${error}`));
  worker.on('exit', code => {
    if (code !== 0) console.error(`[${homePath}] Worker stopped with exit code ${code}`);
  });
};

module.exports.stopWiki = function stopWiki(homePath) {
  const worker = workers[homePath];
  if (!worker) return; // no running worker, maybe tiddlywiki server in this workspace failed to start
  worker.terminate();
};


```

**Comment by linonetwo** [comment]
I manage to make it work during dev and local production mode.

I can use `./dist/mac/TiddlyGit.app` without error.

But app in `./dist/TiddlyGit-0.0.9.dmg` resulting in the following error:

```
{"code":"MODULE_NOT_FOUND","requireStack":["/Applications/TiddlyGit.app/Contents/wiki-worker.js"],"level":"error"}
```

Very strange, seems compressing things into dmg breaks something.

**Comment by dsteinman** [comment]
> Seems in "real" production mode, script in worker_thread can't use electron's require hook, so it can't find dependences in asar.

Without looking very closely, this sounds very similar to a problem I encountered last week [here](https://github.com/mozilla/DeepSpeech/issues/3127#issuecomment-653862396)

In an electron packaged app, the `app.asar` file gets unpacked to a directory name `app.asar-unpacked`.  So in this case, in production mode, the path of a file being loaded needed to have a search & replace performed to use the unpacked directory:

This might be what your `tiddlywiki` module needs.  If it is loading something from a local path, you **_might_** be able to do something like this to get it to work:

```
const pathToFile = '.../myfile';
const unpackedPath = pathToFile.replace("app.asar", "app.asar.unpacked");
const module = require(pathToFile);
```

**Comment by linonetwo** [comment]
I tried `asar: false,` and it just works. Seems the problem is that script in worker_threads can't require modules in asar.

@dsteinman `tiddlywiki` is a package in the node_modules, it is a self-contained 3rd party module, can only be required by name.

---

My Solution:

electron-builder
```
    asarUnpack: ['**/node_modules/tiddlywiki/**/*', '**/node_modules/chokidar/**/*', '**/node_modules/lodash/**/*'],
    extraResources: [
      {
        from: 'public/libs/wiki/wiki-worker.js',
        to: 'app.asar.unpacked/wiki-worker.js',
      },
      {
        from: 'public/libs/wiki/watch-wiki-worker.js',
        to: 'app.asar.unpacked/watch-wiki-worker.js',
      },
      {
        from: 'public/libs/git.js',
        to: 'app.asar.unpacked/git.js',
      },
    ],
```

worker manager
```js
const WIKI_WORKER_PATH = isDev
  ? path.resolve(__dirname, './wiki-worker.js')
  : path.resolve(process.resourcesPath, 'app.asar.unpacked', 'wiki-worker.js');
const WIKI_WATCHER_WORKER_PATH = isDev
  ? path.resolve(__dirname, './watch-wiki-worker.js')
  : path.resolve(process.resourcesPath, 'app.asar.unpacked', 'watch-wiki-worker.js');
```

**Comment by LBRGeorge** [comment]
I've made it works with Electron 9.x.x, however something weird is happening. The thread is making some sqlite queries and some intensive CPU tasks, until here is fine, however, when all the tasks finishes and the thread terminates (which should happen), the whole electron app simply crash.

**Comment by linonetwo** [comment]
@LBRGeorge I run into this once, where I set

```js
worker.on('exit', code => {
    if (code !== 0)
      logger.warn(
        `WikiWatcher ${wikiRepoPath} Worker stopped with exit code ${code}, this also happen normally when you delete a workspace.`,
        loggerMeta,
      );
```

Electron just crush and I see the log get `uncaughtException: logger.warn is not a function`, actually I should use `logger.warning`, and this crush the electron.

You can try winston's  `exceptionHandlers`, it can help you find the bug.

**Comment by codebytere** [comment]
Hey folks - i understand that there's still active discussion in this thread, and insofar as it helps folks i encourage it to continue. However, this issue was opened as a reflection of the fact that `worker_threads` don't function in the renderer process, and a length investigation results in that being a problem whose solution is fundamentally incompatible with the architecture of the renderer process. I'm happy to provide more details if that would help contextualize this decision, but for now folks should expect moving forward that we will support Web Workers in the renderer to accomplish similar goals, and to use and open issues related to those instead of the worker_threads module provided by Node.js. If issues arise with regard to `worker_threads` in the main process we are also happy to investigate those as future individual issues.

**Comment by User0111** [comment]
> I tried `asar: false,` and it just works. Seems the problem is that script in worker_threads can't require modules in asar.
> 
> @dsteinman `tiddlywiki` is a package in the node_modules, it is a self-contained 3rd party module, can only be required by name.
> 
> My Solution:
> 
> I'm using `tiddlywiki`, `lodash` and `chokidar` in my scripts, so:
> 
> electron-builder
> 
> ```
>     asarUnpack: [
>       '**/node_modules/tiddlywiki/**/*',
>       '**/node_modules/lodash/**/*',
>       '**/node_modules/chokidar/**/*',
>       // dep of git.js
>       '**/node_modules/fs-extra/**/*',
>       '**/node_modules/dugite/**/*',
>       // dep of fs-extra
>       '**/node_modules/jsonfile/**/*',
>       '**/node_modules/universalify/**/*',
>       '**/node_modules/graceful-fs/**/*',
>       '**/node_modules/at-least-node/**/*',
>       // dep of dugite
>       '**/node_modules/rimraf/**/*',
>       '**/node_modules/progress/**/*',
>       '**/node_modules/mkdirp/**/*',
>       '**/node_modules/minimist/**/*',
>       '**/node_modules/glob/**/*',
>       '**/node_modules/checksum/**/*',
>       '**/node_modules/got/**/*',
>       '**/node_modules/tar/**/*',
>       '**/node_modules/fs.realpath/**/*',
>       '**/node_modules/inflight/**/*',
>       '**/node_modules/path-is-absolute/**/*',
>       '**/node_modules/optimist/**/*',
>       '**/node_modules/minimatch/**/*',
>       '**/node_modules/inherits/**/*',
>       '**/node_modules/@sindresorhus/is/**/*',
>       '**/node_modules/@szmarczak/http-timer/**/*',
>       '**/node_modules/decompress-response@/**/*',
>       '**/node_modules/duplexer3/**/*',
>       '**/node_modules/cacheable-request/**/*',
>       '**/node_modules/get-stream/**/*',
>       '**/node_modules/lowercase-keys/**/*',
>       '**/node_modules/mimic-response/**/*',
>       '**/node_modules/p-cancelable/**/*',
>       '**/node_modules/to-readable-stream/**/*',
>       '**/node_modules/url-parse-lax/**/*',
>       '**/node_modules/fs-minipass/**/*',
>       '**/node_modules/chownr/**/*',
>       '**/node_modules/safe-buffer/**/*',
>       '**/node_modules/once/**/*',
>       '**/node_modules/minizlib/**/*',
>       '**/node_modules/wrappy/**/*',
>       '**/node_modules/wordwrap/**/*',
>       '**/node_modules/defer-to-connect/**/*',
>       '**/node_modules/minipass/**/*',
>       '**/node_modules/clone-response/**/*',
>       '**/node_modules/get-stream/**/*',
>       '**/node_modules/http-cache-semantics/**/*',
>       '**/node_modules/keyv/**/*',
>       '**/node_modules/lowercase-keys/**/*',
>       '**/node_modules/brace-expansion/**/*',
>       '**/node_modules/responselike/**/*',
>       '**/node_modules/pump/**/*',
>       '**/node_modules/normalize-url/**/*',
>       '**/node_modules/yallist/**/*',
>       '**/node_modules/json-buffer/**/*',
>       '**/node_modules/balanced-match/**/*',
>       '**/node_modules/concat-map/**/*',
>       '**/node_modules/prepend-http/**/*',
>       '**/node_modules/end-of-stream/**/*',
>       // dep of chokidar
>       '**/node_modules/is-binary-path/**/*',
>       '**/node_modules/normalize-path/**/*',
>       '**/node_modules/glob-parent/**/*',
>       '**/node_modules/braces/**/*',
>       '**/node_modules/anymatch/**/*',
>       '**/node_modules/is-glob/**/*',
>       '**/node_modules/readdirp/**/*',
>       '**/node_modules/fsevents/**/*',
>       '**/node_modules/binary-extensions/**/*',
>       '**/node_modules/picomatch/**/*',
>       '**/node_modules/is-extglob/**/*',
>       '**/node_modules/fill-range/**/*',
>       '**/node_modules/to-regex-range/**/*',
>       '**/node_modules/is-number/**/*',
>     ],
>     extraResources: [
>       {
>         from: 'public/libs/wiki/wiki-worker.js',
>         to: 'app.asar.unpacked/wiki-worker.js',
>       },
>       {
>         from: 'public/libs/wiki/watch-wiki-worker.js',
>         to: 'app.asar.unpacked/watch-wiki-worker.js',
>       },
>       {
>         from: 'public/libs/git.js',
>         to: 'app.asar.unpacked/git.js',
>       },
>     ],
> ```
> 
> wow, our `watch-wiki-worker.js` dependes on my local `git.js` and `git.js` depends on `chokidar` and `dugite`.
> 
> seems `chokidar` and `dugite` depends on tons of things, and things depend on things... So I have to use `npx npm-remote-ls --flatten chokidar -d false -o false` and so on to get the flattened dependency tree...
> 
> If you miss one of the dep of dep, you will get MODULE_NOT_FOUND error too.
> 
> worker manager
> 
> ```js
> const WIKI_WORKER_PATH = isDev
>   ? path.resolve(__dirname, './wiki-worker.js')
>   : path.resolve(process.resourcesPath, 'app.asar.unpacked', 'wiki-worker.js');
> const WIKI_WATCHER_WORKER_PATH = isDev
>   ? path.resolve(__dirname, './watch-wiki-worker.js')
>   : path.resolve(process.resourcesPath, 'app.asar.unpacked', 'watch-wiki-worker.js');
> ```
> 
> 1. list all 3rd party package that is required in worker_threads script, in the `asarUnpack`
> 2. use `extraResources` to copy worker_threads scripts and local files that are required in worker_threads script, to `app.asar.unpacked`

This solution works for me as well

I was not able to use worker_threads with the following configuration: 
![image](https://user-images.githubusercontent.com/25059655/119239673-4fc62f00-bb53-11eb-929e-d0afb5743ff5.png)

I've used Electron Workers described [here](https://www.electronjs.org/docs/tutorial/multithreading). Tasks processing is x2 faster now. I had a lot of ~~sex~~ love with Electron before I made it works but it is doable. it was really hard to get the list of all the dependencies(50) I have to add to asarUnpack. It's weird that so powerfull feature not documented well and needs so a lot of tricks to do. I would be happy to get know that I can do something simpler to make it works in another way even after all this hell.

**Comment by linonetwo** [comment]
@User0111  Actually I move to electron-forge, and use `threads-plugin`, so webpack pack standalone js file for worker to run, and it works fine and no asar-unpack now.

https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/afacc142f65b2afd951edd25ee4b731b6da3ad3f/webpack.plugins.js#L9-L41

But it takes me a long time refactor my code to electron-forge + typescript.

**Comment by m4heshd** [comment]
Electron really need to add more support for `worker_threads` especially since it's a god given for GUI development. I still find it very weird why the worker is unable to use Electron's patched `fs`. The most of my time I've spent debugging my projects, is related to Electron + asar + worker threads. There's always a "gotcha" waiting around the corner when going into production. @linonetwo I see that you're going through the same exact hell as I am since I see you on every `worker_threads` related issue that I'm also having.

**Comment by linonetwo** [comment]
@m4heshd Yes, but I finally make it worked... My latest solution includes:

1. Use electron forge (webpack typescript)
2. copy thread used npm packages to dist folder https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/283a3263792d33a200500d1d73b1cf821d41b6f0/webpack.plugins.js#L23-L29
3. use threads plugin https://github.com/andywer/threads-plugin/issues/43#issuecomment-851607253

**Comment by m4heshd** [comment]
> I finally make it worked... 

That's great. Unfortunately I cannot afford the time for any major refactoring right now. I'm just using my workers and dependencies unpacked for the moment. But love to move to a solid solution in the near future.

**Comment by Coukaratcha** [comment]
@linonetwo Thank you for your help. I have used the asar.unpacked trick and it worked like a charm. However, I am very disappointed that `worker_threads` are not working properly out of the box when the app is packaged.
I see that you found a better solution with electron-forge but still I think it should be great that electron improves `worker_threads` integration. I am not satisfied with @codebytere's reply as I think that the issue was misunderstood: the issue is not that `worker_threads` are not working in renderer process, but that it cannot be possible to load modules from worker when using `worker_threads` from the main process. I think unpacking modules, even if it is a clever idea and a good temporary workaround, is not a good solution as we lost the perks of packaging.
Is there any better solution if we want to keep nsis build target?

**Comment by JaspreetChhabra** [comment]
@linonetwo Thanks for the help. The mentioned solution did work but my worker is also using 'electron-store' which internally uses 'electron' Module. 'electron' needs to be mentioned in the dev-dependecies and I am not able to unpack the modules mentioned in the dev-dependencies using "asarUnpack" in package.json. Any workaround for this ?
I am getting below error 

`error Error: Cannot find module 'electron'
Require stack:
- /Volumes/ccaas-screenrecorder-desktop-app 1.0.4/ccaas-screenrecorder-desktop-app.app/Contents/Resources/app.asar.unpacked/node_modules/electron-store/index.js`

**Comment by linonetwo** [comment]
@JaspreetChhabra  I think code in worker don't have access to electron modules, because electron module only accessible from electron main thread (not any worker thread).

A workaround may be passing signal to trigger things in main thread and return data back to the worker thread. You may use threads plugin to simplify this, it supports rxjs, so passing things here and there is not that terrible.

> I think unpacking modules, even if it is a clever idea and a good temporary workaround, is not a good solution as we lost the perks of packaging.

@Coukaratcha I'm currently not unpacking everything, I only unpack as need. [https://github.com/tiddly-gittly/TidGi-Desktop/blob/master/docs/Development.md#how-to-add-dependency-that-used-in-a-worker_thread](https://github.com/tiddly-gittly/TidGi-Desktop/blob/master/docs/Development.md#how-to-add-dependency-that-used-in-a-worker_thread)

[https://github.com/tiddly-gittly/TidGi-Desktop/blob/7831fa44bd27c18e1c25e62d78383d88c2930528/scripts/afterPack.js#L35-L50](https://github.com/tiddly-gittly/TidGi-Desktop/blob/7831fa44bd27c18e1c25e62d78383d88c2930528/scripts/afterPack.js#L35-L50)

It makes building complex a bit, but it works and not increasing too much bundle size.

![](https://user-images.githubusercontent.com/3746270/169651186-9a5e964b-15c8-4da5-bb5d-4df27b664f28.png)

well... 74M after install, but when zipped, no much , I think... See [https://github.com/tiddly-gittly/TidGi-Desktop/releases](https://github.com/tiddly-gittly/TidGi-Desktop/releases) [TidGi-darwin-x64-0.7.7.zip](https://github.com/tiddly-gittly/TidGi-Desktop/releases/download/v0.7.7/TidGi-darwin-x64-0.7.7.zip) 119 MB

**Comment by Cmaxd** [comment]
@linonetwo thanks for your solution. do you know if electron has made any progress on this matter?  It has been two years

**Comment by linonetwo** [comment]
I don't think electron will do anything new on this, because worker_thread is working with simple npm dependency.

It depends on the npm package, if it use `fs` and `path` to locate other file, you have to move them to resource/ folder in afterPack script. I'm always doing this.

But I'm not sure now, because @giladgd say it is possible to locate `.node` dependency without manually move them? https://github.com/withcatai/node-llama-cpp/issues/199#issuecomment-2053701922
I'm currently only move `.node` files to resource/ folder in afterBuild.js, and other JS dependency are bundled by electron-forge and works correctly in worker_thread.

**Comment by Cmaxd** [comment]
@linonetwo Thanks for reply. In my case, I have an SDK, the SDK calls a .dll based on [ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi), I configured SDK externals in webpack, and move the SDK to asar.unpacked folder, which runs well in main thread;  
But  now I want to call this SDK in worker_threads, it report an error MODULE_NOT_FOUND,  to solve this problem, I need to bundle the SDK and worker's JS code together? and move the .node file in SDK's dependencies(ffi-napi ... ) to asar.unpacked folder ?

**Comment by galetahub** [comment]
The main reason is that utilityProcess doesn't know where to find node_modules.
With option `asar: true` electron package all of them (except native modules see AutoUnpackNativesPlugin) to archive app.asar.
But inside the electron process, we can use modules from this archive like normal modules:
`import { SomeClass } from "app.asar/node_modules/some_module"`
So the main idea is to tell utilityProcess where the archived node_modules are located (`app.asar/node_modules`).

I have found the solution in the VSCode source code:
https://github.com/microsoft/vscode/blob/16bb31f856d64fded303542a7e4a628dc92e63a2/src/bootstrap-node.js

Two functions enableASARSupport and removeGlobalNodeModuleLookupPaths did the job.
In our case the function enableASARSupport must inject path `app.asar/node_modules` before `app.asar.unpacked/node_modules`.
So utilityProcess module lookup paths first of all will look at `app.asar/node_modules` and then as normal lookup.

Save path where unpacked node_modules is located to modulesPath:

```typescript
// main.ts

let childPath = path.join(__dirname, 'my.worker.js');
let modulesPath = path.join('./node_modules');

if (app.isPackaged) {
  childPath = path.join(process.resourcesPath, 'app.asar.unpacked/.vite/build/my.worker.js');
  modulesPath = path.join(process.resourcesPath, 'app.asar.unpacked/node_modules');
}
```

Pass variable modulesPath to our utilityProcess worker via envs:

```typescript
childProcess = utilityProcess.fork(
    childPath,
    [],
    {
      stdio: 'pipe',
      serviceName: 'Utility Process',
      env: {
        'NODE_MODULES_PATH': modulesPath,
        ...
      },
    }
  );
```

Configure forge.config.js to include the worker module in the unpack:

```js
// forge.config.js
module.exports = {
  packagerConfig: {
    asar: {
      unpack: "**/.vite/build/*.worker.*",
    },
  },
  ...
 }
```

Use hook to lookup `app.asar/node_modules`:

```typescript
// my.worker.ts
const path = require('path');
const fs = require('fs');
const Module = require('module');

// increase number of stack frames(from 10, https://github.com/v8/v8/wiki/Stack-Trace-API)
Error.stackTraceLimit = 100;

const removeGlobalNodeModuleLookupPaths = function () {
  if (typeof process?.versions?.electron === 'string') {
    return; // Electron disables global search paths in https://github.com/electron/electron/blob/3186c2f0efa92d275dc3d57b5a14a60ed3846b0e/shell/common/node_bindings.cc#L653
  }

  // TODO@esm this might not work anymore (https://github.com/microsoft/vscode/issues/226042)

  const Module = require('module');
  // @ts-ignore
  const globalPaths = Module.globalPaths;

  // @ts-ignore
  const originalResolveLookupPaths = Module._resolveLookupPaths;

  // @ts-ignore
  Module._resolveLookupPaths = function (moduleName, parent) {
    const paths = originalResolveLookupPaths(moduleName, parent);

    if (Array.isArray(paths)) {
      let commonSuffixLength = 0;
      while (commonSuffixLength < paths.length && paths[paths.length - 1 - commonSuffixLength] === globalPaths[globalPaths.length - 1 - commonSuffixLength]) {
        commonSuffixLength++;
      }
      return paths.slice(0, paths.length - commonSuffixLength);
    }

    return paths;
  };
};

/**
 * Helper to enable ASAR support.
 */
const enableASARSupport = function () {
  // ESM-comment-begin
  const NODE_MODULES_PATH = process.env.NODE_MODULES_PATH;
  const NODE_MODULES_ASAR_PATH = process.env.NODE_MODULES_PATH.replace('.unpacked', '');

  // @ts-ignore
  const originalResolveLookupPaths = Module._resolveLookupPaths;

  // @ts-ignore
  Module._resolveLookupPaths = function (request, parent) {
    const paths = originalResolveLookupPaths(request, parent);

    if (Array.isArray(paths)) {
      for (let i = 0, len = paths.length; i < len; i++) {
        if (paths[i] === NODE_MODULES_PATH) {
          paths.splice(i, 0, NODE_MODULES_ASAR_PATH);
          break;
        }
      }
    }

    return paths;
  };
  // ESM-comment-end
};

// Remove global paths from the node module lookup (node.js only)
removeGlobalNodeModuleLookupPaths();

// Enable ASAR in our forked processes
enableASARSupport();

// Your worker code here
(() => {
  const SomeClass = require('@some/package');

  SomeClass.start_long_running_job();

})().catch((error) => {
  console.log('ERROR', error);
  process.exit(1);
});
```

Be careful not to use require/import any packages from node_modules before the function enableASARSupport call, because Error MODULE_NOT_FOUND will raise. 
Vite/webpack build can move `require` to the top of the code, so double-check it.

Hope, this will help somebody
