### ISSUE TITLE
在mac系统上，使用electron-builder打包，Command+C复制粘贴失效

### ISSUE THREAD

**Issue by 18124772589** [electron/electron#18544]
"electron": "^2.0.4",
"electron-builder": "^20.19.2",

在mac打包后的dmg文件安装后，复制粘贴快捷键失效了，在开发环境是正常的，如何解决，急

-----
_Moderator translation:_

After the mac packaged dmg file is installed, the copy and paste shortcut key is invalid, the development environment is normal, how to solve, urgent.

**Comment by tonyganch** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by miniak** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see [the CONTRTIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).
