### ISSUE TITLE
ShortCut (globalShortcut) is everywhere and cant be removed

### ISSUE THREAD

**Issue by Feuerhamster** [electron/electron#18590]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.0.4
* **Operating System:**
  * Windows 10 Pro [Version 10.0.17736.503]

### The Problem
Most of my electron windows reacts to the global shortcut "strg+r" and "strg+d+r".
I think i made misstakes in the past and forgot to unregister some shortcuts. 
And now the shortcuts are registered somewhere in Windows and every time i press the keys "strg+r" any electron window will reload.
Electron Apps also reacts to those, who does not have this shortcuts in the code.

### Questions
Where i can find the registered shortcuts (from globalShortcut) in windows to remove it manually?
How do i fix this annoying problem?

**Please Help
Feuerhamster**

**Comment by Feuerhamster** [comment]
Is there anyone who could help me?
Because this issue is 1 month old and no one has answered.

**Comment by wubing0324** [comment]
i have the problem too

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
