### ISSUE TITLE
  ERROR in unknown: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)

### ISSUE THREAD

**Issue by shengcai9922** [electron/electron#18645]
ERROR in unknown: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)
    Child html-webpack-plugin for "index.html":
             Asset     Size  Chunks  Chunk Names
        index.html  556 KiB       0  
        Entrypoint undefined = index.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.14 KiB {0} [built]
        [1] ./node_modules/lodash/lodash.js 527 KiB {0} [built]
        [2] (webpack)/buildin/module.js 497 bytes {0} [built]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mx_tool_client@0.0.1 build:mac: `node .electron-vue/build.js && electron-builder --platform=mac `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mx_tool_client@0.0.1 build:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by codebytere** [comment]
With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
