### ISSUE TITLE
[Feature request] window.opener full support

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#1865]
when opening a new window using window.open, we currently get a BrowserWindowProxy that only support posting messages.

Some websites, webapps and libraries uses `window.opener` to access properties and objects of the opener window. Thoose are broken in Electron.
That's the case for example of Chromium devtools, that use window.open / window.opener in dockable/undockable mode.

**Comment by zcbenz** [comment]
In Electron every page is forced to run in its own process, however current architecture requires the pages to run in the same process if you want to access one page's contentWindow from the other, so it is not possible to implement it for now.

Chrome is now working on implementing [out of process iframe](https://www.chromium.org/developers/design-documents/oop-iframes), when it is done we might be able to implement this.

**Comment by zcbenz** [comment]
Seems that windows opened by `window.open` can run in separated process in Chrome 45, having full `window.opener` support becomes possible now.

**Comment by felicienfrancois** [comment]
@zcbenz Good news !

**Comment by zcbenz** [comment]
After a closer look into the problem, Chromium only allows certain operations to be sent across renderer processes, and from the issue tracking that (https://crbug.com/128768), they doesn't have plan to support all operations.

So since Electron has a strong requirement that each page runs on a separate process, I'm afraid this is not something that we are able to fix under current architecture.

I'm still keeping this open in case someone has an idea on how to fix this.

**Comment by MichaelOstermann** [comment]
Depending on your situation you can make a workaround - in my scenario I'm listening to the [new-window](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#event-new-window) event, on the next tick I [inject a script](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsexecutejavascriptcode-usergesture) which overwrites `window.opener.postMessage` and sends off the arguments via [ipc](https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md), to which other windows can listen to.

**Comment by bridiver** [comment]
https://crbug.com/128768 is marked as fixed and everything works correctly for us across renderer processes with the code referenced from #4175

**Comment by zcbenz** [comment]
@bridiver It only supports a very limited set of operations, while we have to support `contentWindow` to make `window.opener` fully work.

**Comment by bridiver** [comment]
We have some initial support for this in https://github.com/brave/electron that is referenced in https://github.com/atom/electron/issues/4175. Currently only works between guest views (in same or different browser windows), but that's mainly because that was our only requirement. We'd like to get it working for all cases and upstream it (assuming it meets the requirements) and we welcome any input or PRs. If you want to see it working the easiest way would be through https://github.com/brave/browser-laptop. This also enables non-user initiated popup blocking so don't be surprised if calling window.open directly does nothing. Thanks!

**Comment by Mossop** [comment]
@bridiver I'm interested in seeing this working in our fork of electron too. Your code references are all against old source though so it's tough to apply. Any chance you have a patch against current source handy and some notes on what needs to happen on the app side?

**Comment by hivaga** [comment]
Hi, I am working on a multi-windows application and I need to share a object instances from the main application process with the other windows of the application. Currently in browser you can reference window.opener to achieve this. In browser window.opener (in child window) will give you the instance of the Window object form which window.opent(myURL) was called. 
In Electron when I open window via (window.opent(myURL)) window.opener is replaced with BrowserWindowProxy (Electron API) which does not expose the same window (Window object instance) from which the (window.open(myURL)) was called. Is there a way to access window.opener the same way it works in Browser. I need some hint do you plan to support this in the future and when ?

Using remote.sharedObject (Electron API) is not an option since it only serialize/deserialize data and can be used for passing data from one window to others but does not give access to same object instances across windows.

**Comment by sltam** [comment]
@Mossop I posted an minimal example at https://github.com/brave/browser-laptop/issues/3270#issuecomment-241877534 of what needs to happen on the app side to use this `brave/electron` hack. Basically everything needs to be inside a `<webview>`, and these webviews are uniquely identified by their guest IDs, which allow them to be moved from one `BrowserWindow` to another.

**Comment by tarruda** [comment]
This is now supported in electron through the `sandbox` flag passed to `webPreferences` when creating a new `BrowserWindow`.

I have not documented yet because I still need to push a some extra PRs(tracked by #6712) before the feature is fully complete(should be considered experimental), but it should already possible to use the native `window.opener` API as long as you can live with a few of limitations:

- node.js/electron modules are not available in the renderer with one exception: `require('electron').ipcRenderer` still works on preload scripts. This means you can indirectly use all node.js/electron APIs as long as you set the proper IPC infrastructure in the browser process.
- spell checking, plugins and `<webview>` and some extra functionality implemented in normal electron windows might not be available. This is because the sandboxed renderer inherits directly from chromium content renderer, so most of what was implemented by electron on renderer side is not available(this will be fixed in future PRs)

Some examples of how to use it are available in https://github.com/electron/electron/blob/master/spec/api-browser-window-spec.js

So far the feature is only available master branch(no prebuilt binaries), but I think it will be on the next released version(cc @zcbenz)

Any help in testing this flag is appreciated, especially on OSX/windows which are not my native OSes.

**Comment by tarruda** [comment]
Another limitation about the `sandbox` flag: The preload script does not have a commonjs environment yet. Instead, the preload code is executed in the context of a function that has `require` in its scope, but only `require('electron').ipcRenderer` works for now.

You can still split your renderer code into multiple modules by using browserify to generate a preload bundle that delegates `require('electron')` to the enclosing funciton: `browserify renderer.js -x electron -o preload.js`

**Comment by lijunle** [comment]
@zcbenz @tarruda It has passed 2 months after the feature is merged into master? Is it available in any version?

**Comment by tarruda** [comment]
@lijunle it is available on electron 1.4.2 and up

**Comment by davidrevmakx** [comment]
@tarruda I just tried to do a google auth on Asana.com / trello It doesn't seem to work. I used 1.4.8

**Comment by davidrevmakx** [comment]
@tarruda 
main.js
`app.on('ready', () => {
	console.log("ready");
  const win = new BrowserWindow({webPreferences: {
	       sandbox: true
        }})
  win.loadURL('http://localhost:8888/index.html');
 // win.open('https://app.asana.com', "check");
   const ses = win.webContents.session
ses.clearStorageData();

})`
index.html 
`<a href="javascript:window.open('https://app.asana.com')">Click here</a>`

When I try accessing window.opener from here it says null. Am I doing anything wrong?

**Comment by lijunle** [comment]
@davidrevmakx The `window.opener` is available in `https://app.asana.com` page, not the `index.html` onw.

**Comment by tarruda** [comment]
@davidrevmakx There's a [spec](https://github.com/electron/electron/blob/fb74f5576db29ccef15e1995bd9eeaf0088870a8/spec/api-browser-window-spec.js#L833) for this scenario, but maybe it is not the correct behavior. Should `window.opener` be set in children from a different domain? If yes, then please file an issue.

**Comment by davidrevmakx** [comment]
@lijunle @tarruda sorry for the confusion. Yes opener is null in https://app.asana.com page.

**Comment by Gvozd** [comment]
To correct window.opener, and work facebook(and others) logins

You need use `webPreferences.nativeWindowOpen=true`, and set same `webPreferences.affinity` for mainWindow, and opened windows(hook on `mainWindow.webContents.on('new-window')`)
https://gist.github.com/Gvozd/2cec0c8c510a707854e439fb15c561b0
