### ISSUE TITLE
Setting Proxy using  --proxy-pac-url issue

### ISSUE THREAD

**Issue by ronwang01** [electron/electron#18675]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.1.8

* **Operating System:**
  * Windows 10

* **Last Known Working Electron version:**
  * 

### Expected Behavior

After launching our application with --proxy-pac-url="https://<company host>/proxy.pac" all connection should go through the specified proxy. 

### Actual Behavior

 Using ---log-net-log=net.log I could see the connections are resolving the correct proxy but unfortunately verifying via Wireshark I found the connection having packets going to the wrong proxy.

**Comment by 1c7** [comment]
did you solve the problem?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
