### ISSUE TITLE
Specify Required Options, showMessageBox

### ISSUE THREAD

**Issue by jlord** [electron/electron#1868]
Porting https://github.com/atom/electron.atom.io/issues/38 over here and assigning myself. I'll look for things like this as I go through the content in my next phase of documentation-ing. 

Original issue content from @cfjedimaster:

> The dialog doc (http://electron.atom.io/docs/v0.27.0/api/dialog/) for showMessageBox doesn't state what options are required. I ran into this trying to open a box w/o specifying buttons.

**Comment by zcbenz** [comment]
I'm merging this to more generic #2088.

**Comment by SimulatedGREG** [comment]
**Electron: `1.4.12`**
**OS: macOS Sierra `10.12.1`**

Not sure if something got changed since last year, but the docs currently show that [`buttons`](http://electron.atom.io/docs/api/dialog/#dialogshowmessageboxbrowserwindow-options-callback) is an optional option yet it fails without an array.
```js
electron.dialog.showMessageBox({
  // buttons: ['Dismiss'],
  message: data
})
```
![image](https://cloud.githubusercontent.com/assets/8327811/21092647/461e42ca-c013-11e6-8afe-fb40fde90f11.png)

**Comment by kevinsawicki** [comment]
Thanks @SimulatedGREG, reopening this.
