### ISSUE TITLE
macOS  traffic lights control is gray when window is show by tray menu

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#18694]
### Issue Details

* **Electron Version:**
  * 4.x
* **Operating System:**
  *  macOS 10.14.3 (18D42)
* **Last Known Working Electron version:**
 
### To Reproduce

https://www.youtube.com/watch?v=aPSXlcbhe54&feature=youtu.be

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

The youtube video is also not available in the USA, so I cannot view it.

**Comment by gaodeng** [comment]
here is the gif
![ctls](https://user-images.githubusercontent.com/1118249/59173071-c263bd00-8b7d-11e9-99a8-9f1406745a76.gif)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

**Comment by gaodeng** [comment]
@sofianguy  
here is the repository
https://github.com/gaodeng/electron-quick-start

**Comment by codebytere** [comment]
This unfortunately is a macOS level quirk present on native apps as well; for now it's not triagable on our end but I'm happy to return to this should something change.
