### ISSUE TITLE
Custom Protocol not honouring CORs for PUT/DELETE

### ISSUE THREAD

**Issue by andyboyne** [electron/electron#18710]
Custom protocol handlers only appear to accept GET/POST and reject PUT/DELETE, regardless of what CustomScheme settings are.

I can manually scrape the request to determine it was a delete/put, but it would be better if the method arrived correctly. 

The documentation should make it clear what methods are supported, or should document what other magic is needed if these methods are in fact supported for custom protocols. E.g. can we intercept the pre-flight request?

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
5.0.1

Operating System: Windows 10 (1709)

Last known working: Never

Expected behaviour: allow put and delete
Actual behaviour: put and delete fail pre-flight options request.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

In particular, you're missing the minor and patch components of the affected version (e.g we should be made aware of `5.x.y`, not just `5`) as well as the platform you're experiencing this bug on and a previous working version should it exist.

**Comment by andyboyne** [comment]
Updated

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
