### ISSUE TITLE
Allow running single instance for all the applications

### ISSUE THREAD

**Issue by focusedMonk** [electron/electron#18728]
I have created two electron apps where I need to open only one instance at a time. 
I am using app.requestSingleInstanceLock() to obtain the lock for first instance.

Bug: When I open app_1 and try to open app_2, app_2 fails to obtain the lock since app_1 has already obtained. This condition is right when I open the app_1 for the second time.

Please provide a solution asap.

**Comment by robatwilliams** [comment]
There's a `lockfile` file created in the application's application data folder. It sounds like both your apps are sharing the same folder.

**Comment by focusedMonk** [comment]
Hi Williams,
Where can I find application's data folder?

**Comment by robatwilliams** [comment]
http://lmgtfy.com/?q=electron+application+data+folder

**Comment by focusedMonk** [comment]
Thank you Williams. It worked for me. As you told, both the apps were sharing the same folder.
I used setPath method to set the application data folder independently.

**Comment by tonyganch** [comment]
> Please provide a solution asap.

Hi @focusedMonk!
Open source is largely volunteer-driven and collaborative. Because of this, time and energy to get things done are often the scarcest resources. We want Electron to be the best that it can be, but we also have to be realistic about what the team maintaining Electron can achieve. This means that we might not have an ETA for when an issue will get investigated or fixed.
Insisting on or making demands for such things is considered against [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md).

Also, we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

> The electron documentation: http://lmgtfy.com/?q=electron+application+data+folder

@robatwilliams, thank you for helping others with their issues!
We try to foster an open and welcoming environment in this project, and you can help a lot by sharing links to actual documentation or posting answers to the questions instead of links to lmgtfy.

Thanks for understanding and meeting us half way 😀

**Comment by tonyganch** [comment]
@focusedMonk, can this issue be closed as resolved?

**Comment by focusedMonk** [comment]
@tonyganch Yes, please close and mark it as resolved. Thank you.
