### ISSUE TITLE
Buffer.from(large_string) followed by decode() crashing in Electron 5

### ISSUE THREAD

**Issue by fohristiwhirl** [electron/electron#18733]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * Windows 10
* **Last known Working Electron versions:**
  * 5.0.0.beta8 is OK, 5.0.0.beta9 crashes.

### Expected Behavior

The following code, when run in a renderer process, should not crash.

```javascript
let decoder = new TextDecoder("utf8");
let msg = "a".repeat(4096);		// Exact minimum size that crashes for me, i.e. 4095 does not.
let buf = Buffer.from(msg);
decoder.decode(buf);
```

### Actual Behavior
It does crash. I have also tested this in Node 12.0.0 itself (the version of Node included in Electron 5.0.3) and did not experience any crashes.

### To Reproduce
https://github.com/fohristiwhirl/electron_crash_test

```
git clone https://github.com/fohristiwhirl/electron_crash_test -b master
cd electron_crash_test
electron .
```

**Comment by codebytere** [comment]
Hmm...i can repro this on master with macOS but curiously _not_ in `6-0-x` or `5-0-x` 🤔

**Comment by fohristiwhirl** [comment]
It crashed for me in Electron 6 and 7. I got someone with Linux to try it with Electron 5 and it crashed for him.

**Comment by fohristiwhirl** [comment]
If I test it with a StringDecoder rather than a TextDecoder it doesn't crash.

**Comment by fohristiwhirl** [comment]
If, instead of using the global TextDecoder, I import from util like so:

```javascript
const util = require("util");
let decoder = new util.TextDecoder("utf8");
```

It does not crash.

**Comment by fohristiwhirl** [comment]
Having dug a little into it, 5.0.0.beta8 is OK but beta9 crashes. That was the point at which Electron's fork of Node 12 was integrated. Presumably there's some problem there.

**Comment by codebytere** [comment]
Ah, that makes sense! i think i tried to repro this with a beta of 5 which explains how you could repro it and i could not!

**Comment by dsanders11** [comment]
@codebytere, I believe this issue and #14915 have the same root cause. Both occur in the renderer process, and that I believe is the key.

Both issues involve code which use Node globals which have the same name as a standard browser API. When in the renderer process the Node version is shadowed by the browser version, and bad things happen.

That's why for this issue the crash started happening after 5.0.0-beta.8, when the Node version jumped from 10 to 12. In Node 11 they added [a `TextDecoder`](https://nodejs.org/api/globals.html#globals_textdecoder) global, which is being shadowed by the browser version of `TextDecoder`. That's also why it works when @fohristiwhirl uses `TextDecoder` from the `util` module, as then the code is using the Node version rather than the browser version.

In issue #14915 it's a similar story. The `net` module creates a timeout using an internal API, `setUnrefTimeout` which it then clears with the [Node version of `clearTimeout`](https://nodejs.org/api/globals.html#globals_cleartimeout_timeoutobject), which takes as input a `Timeout`. When in a renderer process the Node code will try to use the browser version, which will gladly take any input and silently do nothing.

It seems like this globals shadowing could have a lot of negative effects in exiting Node code. The timer stuff alone is likely to cause a lot of bugs.

Does Electron have a coherent policy on this issue of globals shadowing in renderer processes with Node integration? It seems like a pretty messy issue since you can have code in the renderer that wants to use the browser version of `clearTimeout` on one line, then on the next call into some code from Node which is expecting to use the Node version of `clearTimeout`.

In theory the `TextDecoder` should be a drop-in replacement since the Node version was implemented to the WHATWG standard, but from this issue it looks like there's some incompatibilities. With the timer stuff since the arguments are different, Electron could switch between the implementations by inspecting the arguments, but that's a bit hackish.

**Comment by MarshallOfSound** [comment]
@dsanders11 just to verify the theory that this is caused by overlapping globals, can you enable contextIsolation and see if the crash still occurs

**Comment by dsanders11** [comment]
@MarshallOfSound, I don't know anything about this particular bug other than I stumbled upon it when investigating #14915, but I cloned the reproduce repo and tried it out with `contextIsolation`, but the reproduce case provided in this bug uses `Buffer`, so when Node APIs aren't available the code can't run. In this particular case they probably want to be using the Node version of `TextDecoder` if they need to use `Buffer`.

But I'm 99% sure of the theory. You can fix #14915 by patching the global `clearTimeout` in the way I described, see https://github.com/electron/electron/issues/14915#issuecomment-502607259.

**Comment by fohristiwhirl** [comment]
By the way, this isn't really a Windows issue (as currently labelled), we've seen reports on Mac and Linux as well now.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
