### ISSUE TITLE
BrowserWindow  setBounds()  this method probabilistic does not work

### ISSUE THREAD

**Issue by joeyer** [electron/electron#18761]
electron 4.0.4
node 8.2.1
npm 5.3.0

I am sure that this method is called, but the window size does not change without any error, which is probabilistic.

> `this._mainWin.setResizable(true);
        this._mainWin.setMinimumSize(370, 520);
        this._mainWin.setBounds({ x: 775, y: 270, width: 370, height: 520 }, true);`

_mainWin is an instance of BrowserWindow

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

it's also not clear what you mean by `probabalistic`, which ostensibly means:
> based on or adapted to a theory of probability; subject to or involving chance variation.

but i doubt that is what you are intending in this context.

**Comment by codebytere** [comment]
With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
