### ISSUE TITLE
Systray icon option to force visibility (windows)

### ISSUE THREAD

**Issue by johaven** [electron/electron#18813]
The systray icon disappear regularly (folding) on Windows 10, an option to make it always shown would be interesting.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by MarshallOfSound** [comment]
--> https://www.npmjs.com/package/electron-promote-windows-tray-items

**Comment by johaven** [comment]
Not maintained. Would not it be interesting to integrate that with Electron?

**Comment by MarshallOfSound** [comment]
@johaven What makes you say it's not maintained, just because it hasn't had super recent commits doesn't mean it isn't maintained.... It's probably just "working" and doesn't require active changes 😕 

And no, this is not something that makes sense as a core electron API

**Comment by roytan883** [comment]
@MarshallOfSound 

1, **electron-promote-windows-tray-items** not work with electron 6.0.12, which use electron-edge not support win32-x64.

2, I think this is core API for electron on **WINDOWS** platform. Because default the tray is hidden in folding customize area, meaning **default** it **NOT VISIBLE**.  That means the **whole tray module is useless on WINDOWS**, because user can't see it (the only way is show a dialog tell user to manually dray it out, which is silly). So can you consider add it to core API ?

**Comment by miniak** [comment]
There is a reason why the user has to consciously make your app visible in the tray.
