### ISSUE TITLE
rename process.versions.{openssl => boringssl}

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#18826]
We no longer depend on openssl at all, it should not be listed in `process.versions`.

![image](https://user-images.githubusercontent.com/6634592/59560038-b5046380-8fbf-11e9-9207-46874847126e.png)

**Comment by dulvinw** [comment]
Can I get a beginner issue? new to both JS and OSS

**Comment by nornagon** [comment]
I think we should keep `process.versions.openssl`:

1. some things expect `process.versions.openssl` to exist; this would break them.
2. BoringSSL doesn't have a version, so there's nothing meaningful we could put in `process.versions.boringssl`.
3. If people want to version-check boringssl, they can use electron version as a proxy, since it's not possible to load a different boringssl with a given version of electron as it's statically compiled.

**Comment by nornagon** [comment]
Closing this for now, we can reopen if needed.
