### ISSUE TITLE
Unresponsive Developer Tools in Electron >= 5

### ISSUE THREAD

**Issue by dperetti** [electron/electron#18830]
### Issue Details

* **Electron Version:**
  * 5.0.4, 6 beta
* **Operating System:**
  * Mac OS X 10.14.5 (18F132)
* **Last Known Working Electron version:**
  * 4.2.4

### Expected Behavior
Developer Tools working smoothly.

### Actual Behavior
I experience long (~10s) and frequent moments (every 5s) when the UI of the developer tools is totally unresponsive (scrolling in console, scrolling in IndexedDB, buttons, etc), although the CPU is perfectly calm. 
I don't have any issue whatsoever in Electron 4.
This is not fixed in Electron 6 beta.

👉 **Interestingly, everything runs fine if I detach the developer tools from the window AND minimize the app window to the Dock**.

**Comment by 4eveRS** [comment]
Noticed that as well and if you look to the browser window that the DevTools detaches from, it is briefly rendering the DevTools content (weird bug).

More noticeable way to reproduce this bug is by creating two BrowserWindow, then open a detached DevTools in the second one and use mission control on Mac (F3 key). Once you do that, the first window will be rendering the contents of the DevTools of the second BrowserWindow for a few milliseconds and the stop, and after that, the DevTools will work as expected and smoothly.

**Comment by dperetti** [comment]
@4eveRS Crazy, this is absolutely correct! The problem is gone if I use Mission Control once! At least this is a simple workaround at the moment!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
