### ISSUE TITLE
"Insert" Accelerator not appearing correctly as a shortcut on menu items on MacOS

### ISSUE THREAD

**Issue by andyherbert** [electron/electron#18912]
Defining "Insert" as an accelerator for a menu item on the Mac results in an illegible glyph to be rendered in the menu list (it successfully appears on the Windows equivalent). I believe a special case needs to be made for this menu item as the Mac equivalent of "Insert" is Fn+Enter.
<img width="249" alt="Screenshot 2019-06-20 at 23 58 54" src="https://user-images.githubusercontent.com/25620/59886721-06459600-93b8-11e9-801b-77ff84017e6d.png">

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
