### ISSUE TITLE
windows_shortcut_maximize

### ISSUE THREAD

**Issue by lianglinux5** [electron/electron#18953]
## (On Windows)When maximizing, calling esc will call the maximize method
![electron_bug](https://user-images.githubusercontent.com/14293060/60012436-83ba2080-96ae-11e9-9763-78a8b93f96e0.jpg)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
