### ISSUE TITLE
notifications do not work at win10,no matter packaging or installation package

### ISSUE THREAD

**Issue by swagerYe** [electron/electron#18972]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:5.0.3
  * 
* **Operating System:windows 10
  * 
* **Last Known Working Electron version:**
  *

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ngudbhav** [comment]
I have made the notifications work on my app. Have a look at the code here:
https://github.com/ngudbhav/TriCo-electron-app

If you are installing your app via NSIS, you need to register your app with an ID. The same ID is used by electron to send notifications. While testing, you may see a text 'Snore Toast'.

**Comment by sofianguy** [comment]
@swagerYe 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/18972#issuecomment-505541952). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
