### ISSUE TITLE
css font-family does not support chinese

### ISSUE THREAD

**Issue by mankeheaven** [electron/electron#18971]
```html
<span style="
    font-family: cursive;
">文字设置</span>
```
what I see is 
![image](https://user-images.githubusercontent.com/17426397/60074376-54aaba00-9755-11e9-9308-8d9b895a7896.png)
It's absolutely not a cursive, but when I use i18n, like this with english, it's ok
```
<span style="
    font-family: cursive;
">text setting</span>
```
![image](https://user-images.githubusercontent.com/17426397/60074475-93407480-9755-11e9-9eee-eb942f6a8973.png)

cursive font should be like this in browser:
![image](https://user-images.githubusercontent.com/17426397/60074550-c256e600-9755-11e9-9089-e461d0baf174.png)

**Comment by mankeheaven** [comment]
looking for your help,tks

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
