### ISSUE TITLE
how to set 'PacHttpsUrlStrippingEnabled' in electron

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#19046]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
5.0.0
* **Operating System:**
  * 
Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

i want set `PacHttpsUrlStrippingEnabled` to `false` or set `--unsafe-pac-url` , but i didn`t konw how to set it

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by hxkuc** [comment]
i want to know if it support to set  this parameter `unsafe-pac-url`, you tell me it support and i try to find some way to do this, now the question is electron whether support to set this parameter `unsafe-pac-url`
