### ISSUE TITLE
Is fetch in an Electron Isolated Context supposed to be CORS restricted?

### ISSUE THREAD

**Issue by bughit** [electron/electron#19065]
I'd like to get a clarification before providing all the formal bug report details.

#8802 suggests it shouldn't be, but I'm getting CORS errors (v3 v4 v5).

What is the expected behavior? Since isolated preload script is trusted app code, it would make sense for it to be unrestricted.

**Comment by MarshallOfSound** [comment]
The expected behavior is that fetch operates the same in the isolated context as it does in the main world context.

It follows the same cors and corb rules.

If you want to make unrestricted network requests you can do so through the `http` module or through another process.

That PR you linked simply sets the origin policy on the isolated context to be the same as the main world to avoid a nullptr crash.
