### ISSUE TITLE
3 versions of electron

### ISSUE THREAD

**Issue by jhonyourangel** [electron/electron#19076]
i think this should be spliced into 3 repository:
1. ultra light on ram
2. one full options ( like it is now )
3. one that is able to include both worlds ( if possible )

this idea came, after hearing a lot of people complain about slack memory usage.
making some apps using less stuff, but being more native like, it will bring a huge plus to the electron library, and will make more people use it for developing cross platform apps.

if i dare to make a comparison, i will push it to the limit and compare 
**gitkraken** with **"sublime merge"**
**"vs code"** with **"sublime text"**
what do you think?

**Comment by codebytere** [comment]
We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
