### ISSUE TITLE
Where i can read electron4 document?

### ISSUE THREAD

**Issue by WangYuLue** [electron/electron#19078]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I can't find electron4 document in [docs](https://electronjs.org/docs)

### Proposed Solution

I wish i can read different versions of the document by switching the version type.

**Comment by codebytere** [comment]
Thanks for reaching out!

e close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by DeerMichel** [comment]
Hey @WangYuLue, thanks for reaching out. You can find docs of other versions by checking out the specific branch on our repo. All the docs can then be found within the `docs/` folder. E.g. for v4.2.x [here](https://github.com/electron/electron/tree/4-2-x/docs). 

I don't think we're going to add a version selector to the docs since we encourage users to use the most recent Electron version (and older revisions are not lost but can be found as stated above).

**Comment by WangYuLue** [comment]
@DeerMichel Thank you very much for your help

**Comment by miniak** [comment]
https://github.com/electron/electron/tree/4-2-x/docs
