### ISSUE TITLE
Electron5.06 starts too slowly on Mac OS!

### ISSUE THREAD

**Issue by JackMing0** [electron/electron#19123]
Electron5.06 starts too slowly on Mac OS! It takes about 10 seconds to pop up! Is there a solution to this

**Comment by DeerMichel** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
