### ISSUE TITLE
MacOS minimizes opening will have a white screen flashing in version 5.4.0

### ISSUE THREAD

**Issue by renhaoweixiao** [electron/electron#19146]
Then my version drops to 4.0.1, this problem does not occur.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
