### ISSUE TITLE
使用child_process运行dotnet命令在打包安装后出现问题

### ISSUE THREAD

**Issue by LuciferJun1227** [electron/electron#19219]
electron:5.0.6
Mac:10.14.5
在开发的时候child_press exec运行dotnet命令正常,但是打包安装后运行,显示/bin/sh: dotnet: command not found,返回的代码是127

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by JianwenXu** [comment]
遇到类似的问题，请问怎么解决的

**Comment by LuciferJun1227** [comment]
@JianwenXu 
exec(cmd,{}),cmd是命令行，将命令所在位置补齐就行了
