### ISSUE TITLE
BrowserWindow.setSize crash app with exit status 3221226525

### ISSUE THREAD

**Issue by itayit** [electron/electron#19266]
Electron 5.0.0.6
I'm calling BrowserWindow.setSize from a callback registered on  ipcMain.on('resize') and from times to times it crashes the electron app with the error above.

**Comment by DeerMichel** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
