### ISSUE TITLE
electron ibgobject-2.0.so.0 error

### ISSUE THREAD

**Issue by MD-AZMAL** [electron/electron#19275]
But the files and directory exist
```
root@loopaz:~# electron -v
/usr/local/lib/node_modules/electron/dist/electron: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by DeerMichel** [comment]
Similar to #19205, you are missing some of Chromiums [deps](https://chromium.googlesource.com/chromium/src/+/master/build/install-build-deps.sh#233). Installing these packages should fix your issue. _Sidenote_: Running electron as root requires the `--no-sandbox` parameter. And we don't have a `-v` flag, instead use `--enable-logging`. I'll close this issue as it is not a problem of Electron itself.

**Comment by DeerMichel** [comment]
Oh and it probably doesn't find the library since it might not be installed for the root user (only normal ones).
