### ISSUE TITLE
where to download the pepper flash plugin

### ISSUE THREAD

**Issue by wskongdesheng** [electron/electron#19325]
I searched the plugin, but find nowhere to download, please help

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
