### ISSUE TITLE
Push notifications from third-party websites doesn't work

### ISSUE THREAD

**Issue by daltonmenezes** [electron/electron#19341]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  All versions
* **Operating System:**
  * macOS 10.12.6
* **Last Known Working Electron version:**
  * No

### Expected Behavior
Push notifications from a service worker should work.

### Actual Behavior
Nothing happens. Push notifications doesn't work.

### To Reproduce
Go to any website that request push notification pemission and subscribe. Then, go to **Dev Tools > Application > Service Workes** and click on **Push**. Nothing happens.

### Screenshots
This works on Chromium, but why not in Electron? Why this behavior is disabled by default?
<img src="https://i.imgur.com/wVtecji.png?1"/>

### Additional Information
If there's a reason for Electron don't allow us to show it from external websites, we could at least sign up for and add an eventListener to receive the push notifications and deal with it in the best way for us.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
