### ISSUE TITLE
Unable to close modal window

### ISSUE THREAD

**Issue by stychu** [electron/electron#19363]
macOS 10.14.5 (MOjave)

```
const getVideoFile = src => {
  const loadView = () => `
        <video controls style="position: absolute; top: 0;left: 0;height: 100%;width: 100%;outline: none;">
          <source src="${src}">
        </video>
    `;

  return `data:text/html;charset=UTF-8,${encodeURIComponent(loadView())}`;
};

function openModal(url) {
  modal = new remote.BrowserWindow({
    parent: remote.getCurrentWindow(),
    modal: true
  });

  modal.loadURL(url);
}

openModal(getVideoFile(directLink));
```

Whenever I open the modal window I can't close it. There is no way I can see to manually close the window. Main process window close button is disabled whenever modal opens and I can't interact with the app afterward.

Is this intentional?
 How do you close such a modal window when there is no UI for closing it?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
