### ISSUE TITLE
the notification of electron is too trouble for using.

### ISSUE THREAD

**Issue by caihaibin1991** [electron/electron#19377]
the notification of electron is too trouble for using. I use node-nodify to replace the notification of electron. it need not to set anything, and it is easy to use. 
electron could try to use it ??
https://www.npmjs.com/package/node-notifier
but I found a little bug, if I repeat to bind click event, then when you trigger it, the same callback function will be call many times.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
