### ISSUE TITLE
better wiki for communication between Webframeworks e.g. Angular and Electron (e.g. on https://electronjs.org/docs/faq)

### ISSUE THREAD

**Issue by geyuqiu** [electron/electron#19380]
### Problem Description
Establishing ipc-communication between angular and electron based on the yeomon project
https://github.com/ngx-rocket/generator-ngx-rocket

### Additional Information
following tutorials brought me futher: 
https://dev.to/michaeljota/integrating-an-angular-cli-application-with-electron---the-ipc-4m18
```js
"start": "./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron ./electron.main.js dev",
```

https://electronjs.org/docs/faq
```js
webPreferences: {
    nodeIntegration: true
}
```

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
