### ISSUE TITLE
Event when the icon is clicked in the doc.

### ISSUE THREAD

**Issue by probablycorey** [electron/electron#194]
We've gotten a few bug reports about people wanted a new window to open when the dock icon is clicked. Could we get an event sent when the dock icon is click? That should be enough for us to solve this on the Atom side.

**Comment by tommoor** [comment]
@zcbenz do you think we could get another event for when the dock icon is clicked and there are open windows? In our case we hide the main window when the close icon is clicked and then want to reshow it when the dock is clicked however this event is never triggered because there are other, permanently open windows.

**Comment by zcbenz** [comment]
> @zcbenz do you think we could get another event for when the dock icon is clicked and there are open windows?

We can add a new `activate` event for it, can you open a new issue for it?

**Comment by tommoor** [comment]
I can, because you're awesome.
