### ISSUE TITLE
Mission Control app preview of full-screened app is blank when initiated from different workspace

### ISSUE THREAD

**Issue by iAmWillShepherd** [electron/electron#19430]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 3.1.6

### Expected Behavior
When opening Mission Control with the app in full screen mode, I expect the preview to contain the contents of the app consistently, no matter which workspace I initiate Mission Control from.

### Actual Behavior
The app preview is only visible when initiating Mission Control from the workspace that contains the app. In some instances, the preview is available; however, hovering your mouse over the preview causes it to go blank.

### To Reproduce

1. Full screen an application (GitHub Desktop is an excellent app to choose 😄)
2. Initiate Mission Control from another workspace (You can use Spotlight or Alfred to do this as your keyboard shortcut is likely different from mine)
3. Move mouse to top of screen to get app previews
4. Hover mouse over the workspace that contains the full-screened app

https://github.com/desktop/desktop/tree/bump-electron

Setup instructions for macOS can be found [here](https://github.com/desktop/desktop/blob/bump-electron/docs/contributing/setup-macos.md)
```sh
$ git clone https://github.com/desktop/desktop.git -b bump-electron
$ yarn
$ yarn build:dev
$ yarn start
```

### Screenshots

![Electron_5_0_8](https://user-images.githubusercontent.com/1715082/61805615-b7967c00-adfb-11e9-8ab0-a245f786d749.gif)

<img width="357" src="https://user-images.githubusercontent.com/359239/61804087-b0766a80-ae09-11e9-8482-1098d10d1b75.png">

<img width="372" src="https://user-images.githubusercontent.com/359239/61804089-b10f0100-ae09-11e9-8ce1-35422c5ddbf7.png">

### Additional Information
https://github.com/electron/electron/issues/17942 and https://github.com/electron/electron/issues/18410 seem related; however, the fix ( https://github.com/electron/electron/pull/19315) that was shipped in `5.0.8` did not fix the problem for Desktop.

**Comment by winzig** [comment]
This issue drives me nuts as I use Mission Control constantly. Any idea when this will be fixed?

**Comment by S1M0N38** [comment]
I notice that a similar behavior even when I use Mission Control when Github desktop is not full screen that can be related to this issue. At first the window is all white (Light theme or Dark theme make no difference) and then load the content. Otherwise all the other application seem that they aren't refreshing durning the Mission Control.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22257750/65266897-40881600-db14-11e9-8af5-77574396c9b1.gif)

**Comment by Badokas** [comment]
This is still happening in electron@7.0.0. Are there any workarounds? Can't wait when this will get fixed...

**Comment by JosephTLyons** [comment]
This drives me crazy on a daily basis, but just now decided to write up an Issue on it, but it seems this already exists, so I'm just chiming in now.  Any news on when this may be fixed?

**Comment by NilsEnevoldsen** [comment]
A report that this may be fixed in Electron 8: https://github.com/getferdi/ferdi/issues/333#issuecomment-593529715

Also adding this keyword for searching: Spaces bar.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
