### ISSUE TITLE
Webview's touchend event bug after send Emulation.setTouchEmulationEnabled and Emulation.setEmitTouchEventsForMouse

### ISSUE THREAD

**Issue by tedpenk** [electron/electron#19645]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.2.5、v.5.0.8、v6.0.0
* **Operating System:**
  *  macOS 10.14.3
* **Last Known Working Electron version:**
  * v3.1.13

### Expected Behavior

First click the webview's button can trigger touchend event after send Emulation.setTouchEmulationEnabled and Emulation.setEmitTouchEventsForMouse command by webview.getWebContents().debugger.sendCommand

### Actual Behavior

Click webview's button twice can trigger the touchend event(Webview must get the focus first)
### To Reproduce
https://gist.github.com/tedpenk/58e1b39e4c0d0771b8fa0b737853439d

### Screenshots

![image](https://user-images.githubusercontent.com/7235487/62526710-657a3f80-b86c-11e9-89dc-a37500a3a8bb.png)

### Additional Information

I tried v3.1.13 and It works well as I expected, but It not working in v4.2.5, v5.0.8 and v6.0.0

The example code：
[touchend-bug.zip](https://github.com/electron/electron/files/3471320/touchend-bug.zip)

**Comment by jacklovepdf** [comment]
I met the same problem.

**Comment by flashyu** [comment]
I met the same problem too.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
