### ISSUE TITLE
Wrong Exit Status on Signal

### ISSUE THREAD

**Issue by tim-janik** [electron/electron#19650]
When Electron-6.0.0 (and earlier versions) is killed with a signal, the exit status is 0.
It should be > 128 though. Example:

        (sleep 5 ; killall electron ) & node_modules/electron/dist/electron ; echo exitstatus: $?
        [1]+  Done                    ( sleep 5; killall electron )
        exitstatus: 0

Here's how it *should* behave:

        (sleep 5 ; killall nodejs ) & nodejs ; echo exitstatus: $?
        [1]+  Done                    ( sleep 5; killall nodejs )
        Terminated
        exitstatus: 143

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
