### ISSUE TITLE
BwroserWindow "will-resize" event's newBounds argument does not have dip scale applied

### ISSUE THREAD

**Issue by alitaheri** [electron/electron#19651]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * any
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * none

### Expected Behavior
The `newBounds` provided to the `will-resize` event's callback must take DIP scale into account. as does the `getBounds` on BrowserWindow.

### Actual Behavior
`getBounds` and `newBounds` provided to `will-resize` do not have the same scale when the screen's DIP scale is not 100%.

### To Reproduce
Set the scale to anything other than 100%, listen to `will-resize`, call `getBounds` and you'll se the diff is off the chart.

### Additional Information

It **IS** easy to fix on the user side. But took me a long time to figure this out. Just in case someone else comes across this issue, the fix is this:

```js
win.addListener('will-resize', (event, newBounds) => {
  const newFixedBounds = screen.screenToDipRect(win, newBounds);

  // ...
});
```

I'm sure it's also easy to aply this to the electron code base so others won't suffer from the same problem.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Fental** [comment]
Electron 11.1.1 still has this problem.
