### ISSUE TITLE
How to customize the Cancel button text of the Save File dialog box

### ISSUE THREAD

**Issue by TyQuanCN** [electron/electron#19660]
I want to customize the Cannel button text of the Save File dialog box, But did not find the relevant api support

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
