### ISSUE TITLE
to attach all opened tabs to a single main window of our app like in case of chrome browser

### ISSUE THREAD

**Issue by shubham-latiyan** [electron/electron#19682]
### Problem Description
Actually, I am looking for to open the multiple tabs in my electron app which I successfully did. But how should I attach all those opened windows to the main application window?
like we have an option in native windows app to pin or unpin the windows.

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
