### ISSUE TITLE
electron 6.x -  ERROR ITMS-90277: "Invalid Bundle Identifier. "

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#19681]
Electron Helper (GPU).app
Electron Helper (Plugin).app
Electron Helper (Renderer).app
is using invalid bundle identifier

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by gaodeng** [comment]
@MarshallOfSound  the problem is obvious. these helper apps is using invalid bundle identifier!!!
