### ISSUE TITLE
The backdrop-filter style causes a transparent window to be invalid on windows

### ISSUE THREAD

**Issue by lakxtxue** [electron/electron#19683]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.1
* **Operating System:**
  * Windows 10 (1809) 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Display transparent window correctly
### Actual Behavior
No transparent window

### To Reproduce

```sh
$ git clone https://github.com/lakxtxue/transparent-window.git
$ npm install
$ npm run dev
```

### Screenshots
Displaying correctly on mac is like this
![image](https://user-images.githubusercontent.com/4651283/62697859-49ae9f00-ba0e-11e9-898a-753e28ebaa95.png)

Can't display correctly on windows, it is like this
![image](https://user-images.githubusercontent.com/4651283/62698096-e40ee280-ba0e-11e9-8865-69f1a179edb8.png)

**Comment by kapilsharma432001** [comment]
This is interesting...
I wanna contribute in it. Please assign this to me.
Also I want guidance as this will be my 1st project.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
