### ISSUE TITLE
Window height shrinks when minimized and opened again

### ISSUE THREAD

**Issue by oonqt** [electron/electron#19712]
### Expected behavior:
Window should stay the same size when it is minimized and opened again

### Actual behavior: 
Window size shrinks vertically when being minimized and opened again.

### Code to reproduce: 
`const { app, BrowserWindow } = require("electron");

let mainWindow;

async function startApp() {
    mainWindow = new BrowserWindow({
        width: 340,
        height: 340,
        resizable: false
    });

    mainWindow.loadFile("index.html");
}

app.on("ready", () => startApp());`

### Additional Info: 
This only happens when resizable is set to false
Video: https://memester.cf/u/bn1.mp4

**Comment by xocialize** [comment]
I've seen this behavior as well.

**Comment by oonqt** [comment]
I noticed it only happens if you remove the menu. If you have a menu, this does not happen.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
