### ISSUE TITLE
Detect Windows 10 Taskbar Theme (Dark / White)

### ISSUE THREAD

**Issue by hacdias** [electron/electron#19729]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

The latest version of Windows 10 introduced a new color scheme (light) as many have already posted about. With #19217 we now support knowing whether or not Windows is set to use dark mode **on applications.**

What we don't know is the theme of the taskbar which might not be the same as for the apps. If we don't know this, we don't know which icons to show in the tray area (I'd like a black on white and white on black).

### Proposed Solution

1. Make the tray icon api automatically detect the current theme and set a light/dark icon accordingly; **or**
2. Add some way to check the current tray theme.

### Alternatives Considered

For now, use icons that can be easily seen on either a dark or light taskbar.

### Additional Information

A problem with this is that Windows taskbar can have many colors, but with the dark mode, they're usually dark and light icons can be seen well. On light mode, it's just almost pure white.

**Comment by DeerMichel** [comment]
So with the `sysPrefs.isDarkMode` you can detect the lower setting (def app mode):

![image](https://user-images.githubusercontent.com/8472721/62963481-ef1e9580-bdb5-11e9-93dd-5b35e1085ad0.png)

If I get you correctly, we now also need an API for the upper setting (def win mode; which among other things controls whether the taskbar is dark/light).

cc @MarshallOfSound - I think there's no hope `nativeTheme` will implement this bc why should Chromium need it, or? Then I'd add it to `sysPrefs` although that'd be another candidate for a possible `appearance` API since it shouldn't be put to the `nativeTheme` API if it's not backed by it. Which is a bit weird bc the other dark mode detection will reside there 😆

**Comment by hacdias** [comment]
> If I get you correctly, we now also need an API for the upper setting

Exactly 😄

**Comment by tresf** [comment]
Landed here researching this problem... 

In defense of closing #19735, I can also confirm that the registry technique isn't comprehensive as systems that were upgraded from previous Windows version [seem to be missing it](https://stackoverflow.com/questions/60837862/detect-dark-windows-taskbar), which is a surprisingly high percentage of PCs in the wild.  As this problem is sparsely documented I wanted to offer this information for others and perhaps the Electron team. 🍻

**Comment by gaodeng** [comment]
any news?

**Comment by panther7** [comment]
any news?

**Comment by Stanzilla** [comment]
Having an API for this would be great, or auto switching icons

**Comment by codebytere** [comment]
See https://github.com/electron/electron/issues/31898#issuecomment-2222980254
