### ISSUE TITLE
How to write automated UI tests for electron 

### ISSUE THREAD

**Issue by Aaron0919** [electron/electron#19730]
My Page uses React technology.

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
