### ISSUE TITLE
Full Screen API doesn't work

### ISSUE THREAD

**Issue by Royalone-mobile** [electron/electron#19744]
when open youtube view or vimeo full screen mode not work
this problem not exists in older version but exists after v4 to v7.
this problem in videos only

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by Royalone-mobile** [comment]
I am using this framework now in my electron project.
https://www.npmjs.com/package/electron-tabs

code is just simple.

in demo project of electron tabs project, I have made changes in electron-tabs.html.

 const TabGroup = require("../index");

    let tabGroup = new TabGroup({
        newTab: {
            title: 'New Tab'
        }
    });

    tabGroup.addTab({
        title: 'Google',
        src: 'https://www.youtube.com/watch?v=8YP_nOCO-4Q&feature=youtu.be',
    });

    tabGroup.addTab({
        title: "Electron",
        src: "http://electron.atom.io",
        visible: true,
        active: true
    });

First tab is showing electron tutorial and full screen works in v1-v3 versions.
But after v4, full screen didn't work.
I had to migrate version from 4 to 3 in my project.

**Comment by codebytere** [comment]
This is an open source project that maintainers dedicate significant time to triaging and improving for the benefit of the community at large. When we ask reports to fill out the template, we are doing so because if that's not done, it's harder for us to do our jobs as maintainers. 

Electron is also a cross-platform project, which means that it is implemented **differently** on different platforms like Linux, macOS and Windows. 

> it seems you don't want to fix this issue.

Without a provided platform, I am not able to know where I should start to investigate this issue. It is not a matter of "want", it is a matter of simple logistics and a request that provided directions be followed as clearly delineated in the issue template when it is initially opened.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
