### ISSUE TITLE
code (addEventListener) doesnt register click

### ISSUE THREAD

**Issue by source1471** [electron/electron#19746]
Im writing a program to monitor prices on the steam market and im building a UI in electron, the issue is that when i click a button it doesn't register.

OS: Windows 10

here is the project if anyone wants it:
https://github.com/source1471/market-monitor

i have tried with logging it to console or sending to a new window or opening a link but it doesn't work. I tired using an .on('click', .... as well

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

In addition, that project is a full-featured application, with nontrivial usage of varying APIs. That makes it hard for us to say with any level of certainty that this is an Electron-specific problem.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by source1471** [comment]
@codebytere i have updated the issue in a new post https://github.com/electron/electron/issues/19757
