### ISSUE TITLE
Method to set the packaged app as default browser

### ISSUE THREAD

**Issue by EnderDev** [electron/electron#19807]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I have made a browser in Electron which uses the BrowserWindow, BrowserView combo, however my users are complaining because they can't set my browser as the default browser.

### Proposed Solution
Is there a chance you could add something like `app.setDefaultHandler('web')` or `app.requestDefaultWebPermission()`

### Alternatives Considered
Peeked through the registry, but couldn't find any way to set it for a protocol like http or https, only file extensions.

### Additional Information
This would be very helpful for other users who have made like a mail client and want the mailto protocol to open their app.

**Comment by MarshallOfSound** [comment]
`HKEY_CLASSES_ROOT\https\shell\open\command` is the registry key that controls this iirc

I'm not sure if this API is something that should live directly in Electron (it's a rather specialist use case).  Maybe an `npm` module that does this would be a better home 🤔

**Comment by EnderDev** [comment]
Yeah, could put it in electron-userland. But I'll have a look in that registry path. Would you know though how to do it on  Darwin or Linux?

**Comment by PalmerAL** [comment]
@EnderDev
For macOS, register the scheme: https://github.com/minbrowser/min/blob/eadbaa5fb71c2364f9b6e91b4c7661cf411f6b06/scripts/createPackage.js#L27-L33

then listen for the "open-url" event: https://github.com/minbrowser/min/blob/master/main/main.js#L236-L244

For Linux, you also need to register the scheme: https://github.com/minbrowser/min/blob/31384f19f8966aa23b2c4f89a3d1a4ce2d2452fa/scripts/buildDebian.js#L18

then search through the command-line arguments for URL's: https://github.com/minbrowser/min/blob/master/main/main.js#L56-L66

make sure you enable single-instance support, otherwise your app will be launched again whenever a new URL is opened:
https://github.com/minbrowser/min/blob/master/main/main.js#L246-L255

**Comment by EnderDev** [comment]
@PalmerAL I use electron-builder.

**Comment by PalmerAL** [comment]
@EnderDev Then I'm guessing you could use this option: https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations

**Comment by EnderDev** [comment]
I'll give this a shot

**Comment by MarshallOfSound** [comment]
Looks like this is covered by existing APIs and packaging tools.  Gonna close this out
