### ISSUE TITLE
TTFB Very slow response

### ISSUE THREAD

**Issue by Im-Kevin** [electron/electron#19815]
不知道为什么,我的TTFB会偶尔响应非常慢
我试过同时开两个程序,其中一个响应很慢,另外一个正常,所以,应该不是网络和服务器的问题
TTFB happens to be very slow
Start two programs at the same time, one may be very slow and the other normal.

**Comment by jkleinsc** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info.
