### ISSUE TITLE
Debug frozen renderer process

### ISSUE THREAD

**Issue by fxha** [electron/electron#19814]
### Problem Description

I don't know whether this is the correct issue tracker for this problem but how do I debug a frozen renderer process due an infinite loop or ReDoS in JS. As I understand, V8 execute a part of my code and due the fact that node is single threaded, all further code is blocked. How can I get the current stack trace or take away V8 from CPU (e.g. crash V8 to get the last stack trace)? In x64 we can use CPU debugging features to do so but in JS the renderer process and debug console just freezes. Is there some way to trigger an interrupt to stop V8 and get debug information? Debugging with vscode debugger is also not possible because the renderer process is blocked.

**Comment by MarshallOfSound** [comment]
@fxha If you have a debugger / devtools attached when it happens you can "pause execution" and get a stack trace and see what it is looping

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by Slapbox** [comment]
I believe this is a real issue in Electron 6 and not merely the code it's running.

I upgraded and setting breakpoints in working code that was previously debuggable in Electron 4 there are issues. There's been no changes to that code and the debugger worked fine in Electron 4. I've been working on new code and figured that the issue was caused by a bug in my newly written code until just now.

It will stop properly at the breakpoints (in a number of places in my code), then CPU usage spikes and stays high, taking up 40-45% CPU on my dual core machine. It appears to respond, but if you resume or step ahead nothing happens. If you press `Pause script execution`, similarly nothing seems to happen except the UI updates. CPU usage remains the same throughout. This code also runs properly when not debugging and last time I ran it in React Native and debugged with React Native Debugger (based on Electron 1.8 I think?)

![image](https://user-images.githubusercontent.com/6835891/65823699-47580c80-e229-11e9-97aa-d51106852bc7.png)

**Comment by fxha** [comment]
@Slapbox My question was about how to debug a frozen renderer process without compiling Electron debug binaries and get the stack trace because the process was not responsive (vscode debugger/dev tools no longer worked). After the recent Electron 6 upgrade the freeze didn't occurred any more but is still reproducible with Electron 5 when pressing `PageDown` with a special content in a contenteditable element. I guess it's a problem with Electron or Node but I never tracked down the issue. I notice that some `Ntdll.dll` thread caused the freeze on Windows but don't know how this thread/library is used by Electron or whether is a stupid bug in our code.

**Comment by Slapbox** [comment]
Ah I misread. Thank you.

I'm realizing this morning that Electron 6 is based on Chromium 76, and on some machines Chrome 76 shoots to using a full CPU core and doesn't stop until the process is ended. I wonder if perhaps I'm seeing the same thing here. In any event, if it becomes a bigger problem I guess I'll make a new issue. If the issue is in Chromium though it's doubtful the Electron team can do much about it.
