### ISSUE TITLE
How to make a runtime function ?

### ISSUE THREAD

**Issue by 1057437122** [electron/electron#19862]
I want to do this, I create a electron app  , the `main.js` load a `index.html` file . And in this html, i wan to call a function created by electron ,such as `electronconsole(abc)` , then the app will do what i want in the function ,instead of call such as `const {ipcrender} = electron `...
Is this possible ?

**Comment by thomascayne** [comment]
@1057437122 Have you looked into dynamic functions or functional functions. I think I had t do that `once` in a project. But I forgot myself. Here's a StackOverflow response: https://stackoverflow.com/questions/20129236/creating-functions-dynamically-in-js

**Comment by 1057437122** [comment]
> @1057437122 Have you looked into dynamic functions or functional functions. I think I had t do that `once` in a project. But I forgot myself. Here's a StackOverflow response: https://stackoverflow.com/questions/20129236/creating-functions-dynamically-in-js | https://benohead.com/javascript-dynamically-call-functions/

thanks for the answer.But I dont mean to do dynamic funcitons. What i need is this : I create an electron app , and create a function in main.js or some other files called `eleconsole`,and it accept a parameter such as a `string`, and this function will do `console.log(parameter + ' to electron');` . And I load a file `index.html`,in the html, what i do is only this:
```
<html>
<body>
</body>
</html>
<script>
eleconsole.log('nice');
</script>
```
then the console will tell 'nice to electron' . I dont want to import the electron like this:
```
const {ipcRenderer} from 'electron'
....
```

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
