### ISSUE TITLE
Intercept HTTPResponse

### ISSUE THREAD

**Issue by chuanxinwong** [electron/electron#19865]
Excuse me, I embedded an IFRAME in the page. How can I intercept all HTTP request results in this HTML? And modify the HTTP results?

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
