### ISSUE TITLE
After BrowserWindow.setResizable(false), window can still be resized by unmaximizing it

### ISSUE THREAD

**Issue by kerolloz** [electron/electron#19870]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.3
* **Operating System:**
  *  Ubuntu 19.04 x64

### Expected Behavior
The window shouldn't be resized!

### Actual Behavior
The window gets resized when I drag it down from the title bar.

### To Reproduce

```javascript
 mainWindow = new BrowserWindow({
        autoHideMenuBar: true,
        webPreferences: {
            nodeIntegration: true,
        },
    });

  mainWindow.maximize();
  mainWindow.setResizable(false);
```

### YouTube Video Demo

[https://youtu.be/ZzZZm0fNteY](https://youtu.be/ZzZZm0fNteY)

**Comment by ckerr** [comment]
Thank you for your bug report and for making a code sample.

Since changing the maximized/minimized/normal state causes the window size to be changed as a side-effect, I see your point. But even though they're related, I don't think it's a good default to assume that `setResizable(false)` means a window can't be minimized/maximized. For that reason, I'm going to close this issue.

Your use case of forcing an application to stay at its maximized size is doable. Adding these two `'once'` handler to your code snippet works for me:

```js
    mainWindow.once('maximize', () => {
      mainWindow.once('resize', () => {
        const [ width,  height ] = mainWindow.getSize()
        mainWindow.setMinimumSize(width, height)
      })
    })
  
    mainWindow.maximize()
    mainWindow.resizable = false
```

You may also find BrowserWindow's fullscreen feature useful.
