### ISSUE TITLE
macOS: window.focus() does not focus window anymore

### ISSUE THREAD

**Issue by bpasero** [electron/electron#19920]
### Issue Details

* **Electron Version:**
  * 6.0.4
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 4.x

### Expected Behavior
BrowserWindow.focus() puts the window to the front.

### Actual Behavior
Window is not moved to front. 

### To Reproduce
Open a hello world app and add this code:

```js
setTimeout(() => {
	mainWindow.focus();
}, 5000);
```

Click on another app. The window is not focused. It works fine with Electron 4.

**Comment by MarshallOfSound** [comment]
@bpasero This will be caused by the UX change we made in https://github.com/electron/electron/pull/16400

Can you describe your use case for seizing focus when your app isn't the focused app, it's generally bad UX for another app to randomly take focus away from another.

**Comment by bpasero** [comment]
@MarshallOfSound starting VSCode from the terminal when VSCode is already running should bring the window of VSCode to the foreground as it used to be.

**Comment by MarshallOfSound** [comment]
@bpasero How are you doing that communication? Are you using the single instance lock?

**Comment by bpasero** [comment]
@MarshallOfSound we have never been using the Electron API for that purpose but have our own socket that we communicate through, just using node APIs.

**Comment by luke255** [comment]
As per the documentation here https://github.com/electron/electron/blob/master/docs/api/app.md#event-second-instance

**Comment by luke255** [comment]
As per the `Event: 'second-instance'` section of [the Electron documentation](https://github.com/electron/electron/blob/master/docs/api/app.md#event-second-instance):

**Comment by luke255** [comment]
As per the `Event: 'second-instance'` section of [the Electron documentation](https://github.com/electron/electron/blob/master/docs/api/app.md#event-second-instance):
> Usually applications respond to this by making their primary window focused and non-minimized

This is no longer possible, along with any other legitimate use for this functionality.

Will this change be reverted, or will `window.focus()` be deprecated on Windows and Linux also?

**Comment by soundar78** [comment]
> Can you describe your use case for seizing focus when your app isn't the focused app

When the user clicks on notifications.
We are using node-mac-notifier and onclick we want to focus the window with window.focus().

**Comment by jsphweid** [comment]
@MarshallOfSound , any response to the other posts here for legitimate uses of this feature that was taken away?

The whole point of the app I'm writing is to toggle the app from anywhere using a hotkey, which is not possible with the newest versions of Electron. Can't developers and UX people decide what is good/bad UX for their use case instead of this library?

**Comment by mksmtn** [comment]
Seems to be resolved here https://github.com/electron/electron/pull/22612

**Comment by Noctsyndrome** [comment]
Same issue in 7.3.0.
I'm making a multi-window app that the main-window opens sub-windows and should be able to call them up. The feature works well even in browser. 
Cannot know why electron trim this off.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by tonyarnold** [comment]
> Cannot know why electron trim this off.

Because it causes _all_ Electron apps to steal focus from the running app, even when they don't need to. This causes apps to steal focus no matter what you're doing in another app, whether they requested it or not. 

There are legitimate reasons to do this, such as if your app only runs in the background, and doesn't appear in the Dock. That being said, this stealing of focus should _always_ be done as a result of a user's direct action, and always immediate. 

Making this an explicit option, as was done in #22612 is an excellent move.

**Comment by j-lord** [comment]
I know this is old, but this issue came up for me as well. On MacOS, the only way that I was able to get this to work was be below (only tested on MacOS):

```
let mainWindow
... 

// mac: option + cmd + i
// win: alt + ctrl + i
globalShortcut.register('Alt+CommandOrControl+I', () => {
	forceFocusWindow(mainWindow);
	console.log('it works!')
})

...

function forceFocusWindow(window) {
	// mac specific
	if (process.platform === 'darwin') 
		app.focus({ steal: true });
	// windows/linux specific
	else {
	  // return if there is currently no application window 
	  if (!window) return;
	  // Restore the window if it's minimized.
	  if (window.isMinimized()) window.restore();
	  // Show the window in case it's hidden.
	  window.show();
}
```
