### ISSUE TITLE
Websockets disconnect when computer sleeps on recent electrons

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#19993]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Hi, our electron application spawns a server on localhost, and then connects to it with websockets. However, recent versions of electron, when the computer goes to sleep, disconnect websockets (on macOS at least, i'm pretty sure on windows too).

i appreciate this behaviour makes sense for a web-browser, but perhaps not for a desktop application. is it possible to keep websockets open? perhaps only when the websocket is on localhost?

this *is* an issue with electron 6, and *isn't* an issue with electron 3 ... i can do the bisect and find out exactly when the change occurred if needed.

with thanks

**Comment by Nealsoni00** [comment]
@jonathon-love did you ever figure out the issue? Or a way to keep the socket connection open?

**Comment by jonathon-love** [comment]
hi,

no, we re-establish the web socket connection when the computer awakes. ... this works fine under macOS and linux, but there's still some issues on windows that i haven't got to the bottom of (don't have a windows laptop to test!)

cheers

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
