### ISSUE TITLE
Enable Devtools experimental features

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#20072]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Chromium DevTools has a new domain [Fetch](https://chromedevtools.github.io/devtools-protocol/tot/Fetch) which is experimental. It's possible to use it in Electron?

**Comment by btzsoft** [comment]
I try to set `app.commandLine.appendSwitch('enable-features', 'NetworkService')` but app goes crash

**Comment by btzsoft** [comment]
@MarshallOfSound do you have any idea of how to use `Fetch` domain? Thx!

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
