### ISSUE TITLE
I can't get form-data with webview on new-window event

### ISSUE THREAD

**Issue by wfeang** [electron/electron#20078]
I can't find the form-data from event of 'new-window'
    
    main.html
    ----------
      <webview id="webview" src="data.html" style="height:93%; width:100%" plugins allowpopups/>
    <script>
    var webview =  document.getEletmentById("webview");
    webview.addEventListener("new-window", function(){
                console.log(arguments);
    // how to get the form-data
    //如何获取到 下面的form 表单中的data信息
     });
    </script>
    ----------
    
    data.html
    ----------
    <form action='postData' method='post' target='_blank'>
        <input type='hidden' value='data' name='data'>
    </form>
    ----------

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
