### ISSUE TITLE
floating icon for a desktop app

### ISSUE THREAD

**Issue by ram2349** [electron/electron#20087]
I'm working on an application where a floater icon (for the desktopapp) to be always showed on desktop (similar to snagit or jing apps). This means that the desktop application should be always showing up at some corner of the desktop so users can tap on it using touchscreen and start using this desktop application. (more of...app hanging constantly on some border of the screen)

**Tech Stack:**
1. Front end (all program logic) - Angular JS 7 
2. ElectronJS - building cross-platform desktop applications 
3. Visual Studio2017 for generating the win installer

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
