### ISSUE TITLE
add Page.lifecycleevent support to electron debugger api.

### ISSUE THREAD

**Issue by goodjius** [electron/electron#20107]
The Page.lifecycleEvent handler can be subscribed on the debugger api. However, not event is fired.

It would be nice so that electron can be used similar way as puppeteer.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your request once you do so.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
