### ISSUE TITLE
win.isNormal() always return true

### ISSUE THREAD

**Issue by zjinh** [electron/electron#20143]
win.isNormal() always return true
 win.isMaximized() always return false
and win .on('unmaximize'）listen not working
and win .on('maximize'）listen not working
the window all in frame:false state 
the electron version was 6.0.7

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
