### ISSUE TITLE
bug with min-height: 100vh vs height: 100vh

### ISSUE THREAD

**Issue by ursi** [electron/electron#20178]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.8
* **Operating System:**
  * Windows 10 (1809)

### Expected Behavior

When setting a `min-height` value of an element that is greater than the computed height, it should have the same outcome as setting that same value as just a plain `height` attribute.
### Actual Behavior

Setting `min-height: 100vh` on a body element that has no margins, if it contains a single element with a non-zero margin-bottom, the height of the body element will be `100vh` + the margin of the single inner element. Setting the `height` attribute to `100vh` works as expected. Setting the height to **any** value earlier in the cascade also makes `min-height: 100vh` behave as expected.
### To Reproduce

Open this if Electron Fiddle, then go to dev tools and toggle the `height` attribute of `body` on and off.
https://gist.github.com/Ursi/a23fe8b15e290999386c5448c8b219f2

### Additional Information

In v7.0.0-beta.4 this code behaves as expected.

**Comment by ursi** [comment]
should this be closed, since we're on version 8 at the time of writing?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
