### ISSUE TITLE
BrowserWindow.setMovable(false) can still trigger aero-shake and aero-snap on Windows

### ISSUE THREAD

**Issue by carterbs** [electron/electron#20173]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Background
Windows introduced a suite of window management behaviors in Windows 7. One of them is called 'aero-shake'. If you grab a window and vigorously shake it, all other windows will minimize, reducing the visual clutter on your desktop.

Another is called aero-snap. If you drag a window to the edge of an outer-most monitor (won't work on middle monitors), the OS will resize your window to half of your monitor's available space, and give you the option to split the monitor with another window.

### Issue Details
* **Electron Version:**
  * 4.2.9
  * **Also reproduced on 6.0.7**
* **Operating System:**
  * Windows 10 (1903)

### Expected Behavior
Prerequisites:
* `BrowserWindow.setMovable(false)`.

Dragging a window should not change its position. It should also not trigger underlying operating system window management behaviors (e.g., aero-shake, aero-snap).

### Actual Behavior
Prerequisites:
* `BrowserWindow.setMovable(false)`.

1. Smoothly dragging a window from left to right (or right to left) will occasionally trigger aero-shake, which minimizes all other windows on the user's desktop.
2. Dragging a window into an aero-snap zone still triggers aero-snap.

### To Reproduce
https://github.com/carterbs/electron-quick-start

`npm i && npm start`

1. Drag the window smoothly from left to right. This should trigger aero-shake 2 out of 5 times.
2. Drag the window to the left-most part of your left-most monitor. This will trigger aero-snap 100% of the time.

## Aero-shake
![Aero-shake](https://user-images.githubusercontent.com/16466430/64535845-fb7b0d00-d2e5-11e9-8104-bcb0f10004aa.gif)

![image](https://user-images.githubusercontent.com/16466430/64536018-56acff80-d2e6-11e9-81a5-506b684b8508.png)

The image above shows output from the 'will-move' event, which is emitted prior to actually moving the window. The highlighted numbers show the x position jittering left to right, which would trigger aero-shake in the real world. But as you can see from the GIF, I was moving my mouse left to right -- not jittering 20px to the left and right. I believe this is the cause of the aero-shake behavior.

## Aero-snap
![Aero-snap](https://user-images.githubusercontent.com/16466430/64535995-4dbc2e00-d2e6-11e9-8ecb-c015d374a76f.gif)

### Additional Information
I have 3 monitors; one is 200%, and the other two are 100%, so I don't think this is related to any kind of scaling math.

This might seem like an inconsequential bug, but `setMovable(false)` and `will-move` form the bedrock of our window management system. This has been a longstanding issue for us and we've just gotten to the bottom of it. If there's anything else I can provide, please let me know.

**Comment by itsananderson** [comment]
I was also able to confirm the shake/snap/`will-move` repros with this Electron Fiddle using Electron 6.0.8 and Win 10: https://gist.github.com/d18a9ab010eba9f9a8dffeed57e817d1

Looking briefly in code, it looks like the `will-move` event is indeed [fired before checking the `movable_` field](https://github.com/electron/electron/blob/5f59c6ddfee8124e45516b8d685a789a3bbaa4fa/shell/browser/native_window_views_win.cc#L440-L442).

The shake/snap issues are a bit trickier. I wonder if `setMovable(false)` should be implemented via `WM_NCHITTEST` (disabling `HTCAPTION`) rather than by relocating the window in response to attempted moves. I think that would require a bit of coordination with `-webkit-app-region`, and there might be other side-effects I'm not aware of.

**Comment by carterbs** [comment]
Glad it's easy to repro. I'm not as up on how will-move/setMovable are actually implemented, but what it felt like was that however we're doing this isn't actually preventing the OS from processing the move that would happen if the window was actually being redrawn.

**Comment by carterbs** [comment]
@codebytere @zcbenz I noticed that you guys are the last people to touch setMovable in `shell/browser/api/atom_api_top_level_window.cc`. Do Either of you have any insight or comments into the bug above?

**Comment by sarahshuffle** [comment]
Any news on this?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by txj-xyz** [comment]
This is still a bug in the latest version of electron 19 as of writing this, has anyone found a fix for this?
