### ISSUE TITLE
reCaptcha integration

### ISSUE THREAD

**Issue by Romain-P** [electron/electron#20170]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  * win32
* **Last Known Working Electron version:**
  * none

### Expected Behavior
reCaptcha should work

### Actual Behavior
reCaptcha is not working

### To Reproduce
https://developers.google.com/recaptcha/

### Additional Information
I think it's important to have support for reCaptcha, which at the moment does not have any integration tutorials. When my application is compiled, I do not see any errors or explanations about the malfunction of reCaptcha that does not work.
I read many other issues that have never been solved and speak of a procole, another a trick passing through a local express server.
Could someone explain why this is not working correctly and in detail and propose a generic solution?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
