### ISSUE TITLE
protocol.interceptBufferProtocol not called when using a session in a window

### ISSUE THREAD

**Issue by Gryphon109** [electron/electron#20175]
Hello, when creating a browser window like this:
`new BrowserWindow({
        show: false,
        webPreferences: {
            nodeIntegration: true,
            webSecurity: false,
            partition: '',
            session: session.fromPartition(`${counter}`)
        }`
and using a session:
`protocol.interceptBufferProtocol('http', (req, callback) => {
    console.log('Hello World');
});`
Is never called

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
please follow #20191 for updates
