### ISSUE TITLE
ContextMenu disappeared when right click on both DevTools window and BrowserWindow when cross-monitor with main window

### ISSUE THREAD

**Issue by chairuosen** [electron/electron#20179]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 4.2.6 && latest 6.0.*
  * 
* **Operating System: macOS 10.13.3
  * 
* **Last Known Working Electron version: 1.8.7
  * 

### Expected Behavior
native contextmenu shows up when I call `menu.popup()` or right click in DevTools window.

### Actual Behavior
contextmenu disappeared. but transparent overlay shows and invisible contextmenu is able to click.

### To Reproduce
clone electron-quick-start project and run it with devtools opened.
drag the devtool window to another monitor.
right click on devtool window.
no menu shows.

### Screenshots

https://www.youtube.com/watch?v=6hMwL14ft4w

### Additional Information
Both `new Menu().popup()` and Devtools Window have this problem.

**Comment by Kilian** [comment]
Can confirm this is still a bug, and my guess is that it has something to do with https://github.com/electron/electron/issues/10862

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
