### ISSUE TITLE
showOpenDialog filters not work in deepin system

### ISSUE THREAD

**Issue by xianxuhua** [electron/electron#20199]
```
filters: [
    {
        name: "Musics",
        extensions: ["mp3"]
    }
]
```
![深度截图_dde-desktop_20190911164026.png](https://upload-images.jianshu.io/upload_images/13985423-729520b3d6b99a6d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.
