### ISSUE TITLE
Can't close child window in fullscreen mode

### ISSUE THREAD

**Issue by alxmiron** [electron/electron#20228]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.9
* **Operating System:**
  * macOS 10.14.6

### Steps to reproduce

* Launch the app, set fullscreen mode for main window
* open child window from main window by `new BrowserWindow({ parent: mainWindow })` ("Archive" page on screenshots)
* child window is opened in separate screen to the right
* move cursor to the top side of the screen

### Expected Behavior

* Top toolbar with "close", "minimize", "exit fullscreen" buttons is opened
* User can close child window and move back to main window

### Actual Behavior

* No toolbar is visible. User can't close child window
* Main window is black

### Screenshots

https://streamable.com/slo6w

### Additional Information

The but is not reproducible if child window was opened while main window is not in fullscreen mode

**Comment by SeungjongHan** [comment]
Is it on process?

**Comment by abettadapur** [comment]
This still is reproducible on 8.0.2

**Comment by AllSeeingEye** [comment]
Reproducible.

**Comment by Maus3rSR** [comment]
Same issue here! (with electron v8.2.5)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
