### ISSUE TITLE
Notifications for Windows 10

### ISSUE THREAD

**Issue by trae-op** [electron/electron#20250]
I'm trying to use Notifications from here https://github.com/electron/electron/blob/master/docs/tutorial/notifications.md, but only for windows 10 not work. Also I used line `app.setAppUserModelId(process.execPath)` to my main process to see notifications, but not work too. After opening the mainWindow should after 5 seconds will display Notification. For all platform is work, except win 10.
Electron v6.0.9
My code:

const electron = require('electron');
const Notification = electron.Notification;
...
app.setAppUserModelId(process.execPath);
...
app.on('ready', () => {
  createWindow();
  setTimeout(() => {
    new Notification({
      title: 'title',
      body: 'Lorem Ipsum Dolor Sit Amet'
    }).show();
  }, 5000);
});

**Comment by trae-op** [comment]
Already works. Need to add line `app.setAppUserModelId('appId').` **appId** and not **process.execPath** like here https://github.com/electron/electron/blob/master/docs/tutorial/notifications.md

**Comment by xland** [comment]
How about this issue's progress?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
