### ISSUE TITLE
Does requestSingleInstanceLock work without a window?

### ISSUE THREAD

**Issue by sjamesexamsoft** [electron/electron#20268]
Electron: 4.1.0
Windows 10 Enterprise: 1903

Our application does some post processing of the data collected from the user in the Browser process, with no windows open. When running on Windows, I am not seeing the second-instance event issued when a second instance is launched and not I requestSingleInstanceLock is always returning true. The code is pretty much a copy of the code seen in examples.
I never see the `Not the first instance - quit` log. Note: I am using electron-log package for logging (hence, log.info not console.log)
```
// The following code runs on launch of the application

const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  log.info(`Not the first instance - quit`);
  app.quit();
  return;
}

log.info('Got the single instance lock');

app.on('second-instance', (event, commandLine, workingDirectory) => {
  log.info(`second-instance ${commandLine} ${workingDirectory}`);
  rewritePortFile();
});
```
+

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
