### ISSUE TITLE
Crash on Electron 5.x and 6.x Start on 64bit Windows 7

### ISSUE THREAD

**Issue by dengf** [electron/electron#20278]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.x to 6.0.9
* **Operating System:**
  *  64Bit Windows 7
* **Last Known Working Electron version:**
  *  4.2.10

### Expected Behavior
 No Crash

### Actual Behavior
 Crash with the error message as show in attached screenshot

### To Reproduce

`node_modules/.bin/electron`

### Screenshots

electron.exe - Application Error:

The exception unknown software exception (2xc00000409) occurred in the application at location 2x43b4f737.

Click on Ok to terminate the program
Click CANCEL to debug the program

### Additional Information

The crash normally happens after a close and relaunch. I tested all released versions starting from 5 and to latest 6.0.9. The last working version tested is 4.2.10 which is currently used in our production app.

**Comment by dengf** [comment]
Hi, just want to follow up on this. Any suggestions or the issue will be address in the 7 release? Thanks

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
