### ISSUE TITLE
Web proxy is slow: what's the maximum # of connections between a proxy and browser?

### ISSUE THREAD

**Issue by gogo9th** [electron/electron#20304]
Hi,

I'm using my own web proxy and I see that when the proxy is used, Electron's page loading speed is too slow. I set up the proxy near the web server (NOT in the client browser's device). The web proxy is a mitm proxy, so it creates TLS sessions with the browser, and also with the web servers. When I use my proxy and load webpages of popular websites, its page loading speed is about 10~30% slower. I'm trying to figure out what the exact reason is and wonder if anyone has a clear idea. 

Another big question is what is the limit on the number of connections between the web proxy and the browser. I know the browser can have maximum 6 connections with the same host and maximum 10 connections across all hosts. But if a proxy is used, is it that the browser can have maximum 6 connections with the proxy? Or is it maximum 10? Or a different number?

**Comment by RICKROSSWIFEINGRIDE** [comment]
MEEK MILL SAID HE THE ONLY ONE SUPPOSE TO INVADE MY PRIVACY NOT RAT APPS

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
