### ISSUE TITLE
Sometimes the electron crashed event of render process is triggered too late?

### ISSUE THREAD

**Issue by aircloud** [electron/electron#20319]
* **Electron Version:** 5.0.0

### Problem Description: 

I use `process.crash()` or `process.abort()` in the render process.
And it took a long time to receive the crash event.

This can cause a bad user experience：

If for some reason a crash occurs in a rendering process, the user needs to wait a long time（about 20 - 30 seconds）on the unresponsive page, and after a long time The callback for `webContents.addListener('crashed'` is called and then the developer can do something.

### My exploration：

I search in the electron source code and find：

```
void WebContents::RenderProcessGone(base::TerminationStatus status) {
  Emit("crashed", status == base::TERMINATION_STATUS_PROCESS_WAS_KILLED);
}
```

is this the right function which emit `crashed` event to `win.webContents`？

Maybe it is related to some chromium's processing

Limited by my level of knowledge, I am not very clear about this part.

### Some schematic code：

```
const win = new BrowserWindow({
   // some config...
});

win.webContents.addListener('crashed', () => {
  // This callback is triggered too late  
  if (!win.isDestroyed()) {
    win.close();
  }
});
```

Actually, the application is much more complicated. It’s a bit unrealistic to put all the codes there and what I want most is some analysis of some experienced developers or maintainers of electron.

### Wanted：

I want to know why it takes a long time from `process.crash()` or `process.abort()` called to The `crashed` event emitted ? What did the electron or the chromium do during that time? 

And I want to know if There is any solution to solve this problem(get the `crashed` event as quick as possible) ?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
