### ISSUE TITLE
login event of webContents is not work

### ISSUE THREAD

**Issue by jianzhiyao** [electron/electron#20310]
### Issue Details
login event of webContents is not work

* **Electron Version:**
  * 6.0.9
* **Operating System:**
  * Window10

### Expected Behavior
access proxy by authorization

### Actual Behavior
 callback param is undefined

### To Reproduce
```
    mainWindow.webContents.on('login', (event, webContents, request, authInfo, callback)=>{
      event.preventDefault()
      console.log(callback)//==> undefined
    })
```

**Comment by eurbs** [comment]
For anyone finding this in the future, the issue here is because `webContents.on('login')` does not return `webContents`. While the documentation points you from webContents.on('login') to app.on('login'), the usages are ever so slightly different.

Usage comparison between [`webContents.on('login')`](https://www.electronjs.org/docs/api/web-contents#event-login) vs [`app.on('login')`](https://www.electronjs.org/docs/api/app#event-login):

```
let wcs = mainWindow.webContents
wcs.on('login', (event, details, authInfo, callback) => { /* your code here */ })
app.on('login', (event, webContents, details, authInfo, callback) => { /* your code here */ })
```
