### ISSUE TITLE
Communication between Web Page opened in Chrome Browser and Electron

### ISSUE THREAD

**Issue by thelazyrk** [electron/electron#20340]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I'm looking for a clean way to communicate between a page that is opened in chrome browser with an electron app that is running locally.
I understand that I could do any of the two approached

Open the webpages pretty much in Chromium through Electron and have preload scripts pass IpcRenderer/remote and I really like the approach but the differences and user preferences to use Chrome and support from any off the shelf products like CRMs is non-existent in chromium and also all the difference between chrome and chromium.
There can be a chrome extension that can communicate to the electron process using native messaging, this hasn't been very easy and the process seems to be extremely difficult and almost impossible to maintain.

So Is there way we can achieve a seamless communication channel between Chrome and Electrron?

### Proposed Solution
[Carlo](https://github.com/GoogleChromeLabs/carlo) project seems to have a way to establish a connection through pipes which can launch chrome installed locally with a node process. If this can be modeled to talk to may be a browser extension or webpages then the applications can communicate with the electron Apps
### Alternatives Considered

node-ipc and chrome native messaging are two other alternatives I've considered.
node-ipc can't be called from a browser extension or client side code of a web page.
chrome native messaging has a lot of overhead and did not seem like an easy option to integrate with a web page/chrome extension

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
