### ISSUE TITLE
Pango-ERROR: Harfbuzz version too old

### ISSUE THREAD

**Issue by aurora-of-earth** [electron/electron#20348]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Some Electron-based apps raise this crash dump when run(e.g. <a href="https://github.com/codeforscience/sciencefair">sciencefair</a>):
<pre>
(sciencefair:44491): Pango-ERROR **: 12:51:35.888: Harfbuzz version too old (1.4.2)
Trace/breakpoint trap
</pre>

Running on Debian 12 unstable with experimental repos

Other examples of electron apps having the same issue;
- <a href="https://github.com/webtorrent/webtorrent-desktop">WebTorrent Desktop</a>

----------

- Original issue: <a href="https://gitlab.gnome.org/GNOME/pango/issues/428">gitlab.gnome.org/GNOME/pango/issues/428</a>

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by unixall** [comment]
### Preflight Checklist


* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
electron: 1.6.2
electron-builder: 19.19.1
* **Operating System:**
  * 
Archlinux x64
* **Last Known Working Electron version
-
+:**
  * 

### Expected Behavior


### Actual Behavior

Electron fails to start
### To Reproduce





https://github.com/ToastWallet/core

https://github.com/ToastWallet/build-scripts/tree/master/linux

### Screenshots


### Additional Information

Needs to be rebuilt against an updated version of Harfbuzz

**Comment by HugoKlepsch** [comment]
I also have this issue, but with StarUML, another electron app. 

---

[ x ] I have read the Contributing Guidelines for this project.
[ x ] I agree to follow the Code of Conduct that this project adheres to.

[ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Issue Details

```
staruml

(staruml:15789): Pango-ERROR **: 22:15:15.458: Harfbuzz version too old (1.4.2)

Trace/breakpoint trap (core dumped)
```

    Electron Version:
        electron: ?
        electron-builder: ?

    Operating System:
        Archlinux x64

### Expected Behavior
App starts

### Actual Behavior

Electron fails to start
To Reproduce

https://sourceforge.net/p/staruml/code/HEAD/tree/

### Additional Information
- Pango thread tracking down the issue: https://gitlab.gnome.org/GNOME/pango/issues/410

- Needs to be rebuilt against an updated version of Harfbuzz

**Comment by unixall** [comment]
@sofianguy Can we update the label?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by darthdeus** [comment]
Any chance for a workaround for this issue? I'm running into the same problem, but with an external app I can't modify easily that uses electron 1.8.2.

**Comment by aurora-of-earth** [comment]
The only solution is to ask the developers to update to the latest version of electron, that's all.

**Comment by lorenzleutgeb** [comment]
I am getting the same error for an application, where I neither have access to the source code, nor are the developers going to update. Therefore I'd like to ask for possible workarounds.

My first idea would be to package the app inside a container which would be built to include the correct version of whatever dependency. In order to do that I'd like to ask for some sort of compatibility matrix: Which version of Electron is compatible with which version of Harfbuzz/Pango/...?

**Comment by morpheusthewhite** [comment]
A quick workaround is to downgrade `pango` to an older version, like `1.43`

**Comment by Cyborg369** [comment]
Hi, I have this issue 
Pango-ERROR **: 21:28:53.345: Harfbuzz version too old (1.3.1)
Trace/breakpoint trap
any help ?
thanks

**Comment by tahesse** [comment]
I have the same issue running ArchLinux.

harfbuzz-2.6.2-1-x86_64
electron@latest

$ uname -r
5.6.8-arch1-1

**Comment by chronotechdev** [comment]
> The only solution is to ask the developers to update to the latest version of electron, that's all.

1.44.7 is the only version available on Ubuntu 20 :(
How can i downgrade safely pango ?

```
$ sudo apt policy libpango-1.0-0
libpango-1.0-0:
  Installé : 1.44.7-2ubuntu4
  Candidat : 1.44.7-2ubuntu4
 Table de version :
 *** 1.44.7-2ubuntu4 500
        500 http://fr.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by vdegenne** [comment]
> The only solution is to ask the developers to update to the latest version of electron, that's all.

Have you ever heard about backward compatibility ?

**Comment by Wirone** [comment]
@chronotechdev I have this issue with Zimbra Desktop which is starting and running, but window disappears when I use shortcuts like `mu` or `alt+tab` (process still works and I have to kill it). Today my password expired and I can't reconfigure account because when I hit backspace or arrows on password field window disappears too. Really annoying.... :tired_face:

**Comment by mrfricks** [comment]
for a workaround create a new folder & copy libharfbuzz & libpango from bionic beaver to it (note i put them in the electron app folder. 'chirp' in my case).
then create a script to launch your app. 
```
#!/bin/sh
LD_LIBRARY_PATH=/path/to/folder/with/libs /path/to/app
```

**Comment by Crucizer** [comment]
Same problem when running `wanna`

Gtk-Message: 03:53:39.849: Failed to load module "canberra-gtk-module"

(wanna:90765): Pango-ERROR **: 03:53:41.569: Harfbuzz version too old (1.4.2)

Trace/breakpoint trap (core dumped)

**Comment by ozoli** [comment]
Same issue with postman:
(postman:731524): Pango-ERROR **: 11:56:01.932: Harfbuzz version too old (1.3.1)

**Comment by mslinn** [comment]
# SOLVED!

Atom on Ubuntu 20.04 died this way for me. I considered the following choices:

 1. Try building Atom against the current version of Electron (life is too short for that!)
 2. Downgrade Atom to an older version. (I don't to do that)
 3. Install using `apt` from a repository that has a more current version. (This worked for me!)
   ```
   $ wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
   $ echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" | sudo tee /etc/apt/sources.list.d/atom.list
   $ sudo apt update
   $ yes | sudo apt install atom
```

**Comment by cheese** [comment]
I found an application with the same problem on Fedora 33. My workaround is download an old version of Pango and use LD_LIBRARY_PATH to let the old one is chosen:

```
wget https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/23/Everything/x86_64/os/Packages/p/pango-1.38.1-1.fc23.x86_64.rpm
mkdir pango-1.38.1-1.fc23.x86_64
cd pango-1.38.1-1.fc23.x86_64
rpm2cpio ../pango-1.38.1-1.fc23.x86_64.rpm |cpio -div
LD_LIBRARY_PATH=$PWD/usr/lib64/ /usr/bin/SomeApp
```

**Comment by kaushalyap** [comment]
@cheese I am also facing the same on Fedora 33. This even happens with Electron 11. Is it same for you too?

**Comment by devmaster-terian** [comment]
Latest version of Sencha Architect for Linux has the same error.

```
~/sencha/Sencha Architect 4.2$ ./SenchaArchitect --disable-gpu

(SenchaArchitect:1655): Pango-ERROR **: 18:09:51.703: Harfbuzz version too old (1.3.1)

«trap» para punto de parada/seguimiento (`core' generado)
```

on Ubuntu Mate
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```


So, how can we solve it!?

**Comment by Yasir900aslam** [comment]
Latest version of Ubuntu 20.04 Mate throw this error for an app built with Electron
 
`Trello:124983): Pango-ERROR **: 00:48:04.892: Harfbuzz version too old (1.4.2)
Trace/breakpoint trap (core dumped)`

**Comment by Yasir900aslam** [comment]
Latest version of Ubuntu 20.04 Mate throw this error for an app built with Electron
 
`Trello:124983): Pango-ERROR **: 00:48:04.892: Harfbuzz version too old (1.4.2)
Trace/breakpoint trap (core dumped)`

**Comment by Blackrucat** [comment]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/miau/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/opt/Cerebro/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/opt/Cerebro/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/opt/Cerebro/resources/app.asar/main.js:21:30)
    at /opt/Cerebro/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)

(cerebro:362424): Pango-ERROR **: 14:08:58.102: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (imagem do núcleo gravada)

**Comment by avenmia** [comment]
I came across this issue by following this outdated cesium/electron tutorial. 

https://cesium.com/blog/2016/04/04/an-introduction-to-cesium-desktop-apps-with-electron/

I'm running it in Ubuntu 20.04 in WSL.

I fixed the error by removing electron-prebuilt and electron-packager and replacing it with the latest version of electron.
