### ISSUE TITLE
No notifications on elementary OS Juno (5.0)

### ISSUE THREAD

**Issue by marbetschar** [electron/electron#20355]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

The Signal App is based on Electron and it does create a notification using the Electron standard facility whenever a new message is received. But unfortunately on elementary OS the notification is not displayed.

See [this issue over at the Signal App repository](https://github.com/signalapp/Signal-Desktop/issues/3628#issuecomment-535978488) for further details.

### Expected Behavior

If the Signal App receives a new Message, a Notification is displayed on elementary OS.

### Actual Behavior

No Notification is displayed at all on elementary OS

### To Reproduce

Install the Signal App on elementary OS and receive a new Message.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
