### ISSUE TITLE
Using sandbox and affinity together crashes render process on window close

### ISSUE THREAD

**Issue by sgd2z** [electron/electron#20350]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behavior
Render process should not crash when closing one window in the process using browserWindow.close() if sandbox is true and affinity is set.

### Actual Behavior
When using affinity and sandbox together closing any window in code causes the render process to crash making the rest of the windows sharing that affinity to become unusable.

### To Reproduce
See this branch on my fork of quick-start:
https://github.com/sgd2z/electron-quick-start/tree/sandbox-affinity

It launches two windows with the same affinity and closes one of them. The remaining window goes blank and content never shows.

Remove sandbox: true from the config makes things all work fine.

```
$ git clone https://github.com/sgd2z/electron-quick-start.git -b sandbox-affinity
$ npm install
$ npm run start
```

### Screenshots
Crashed Window:
![image](https://user-images.githubusercontent.com/18012933/65708804-64d87b00-e05d-11e9-86f6-4a2f83cfa82f.png)

Actual Content:
![image](https://user-images.githubusercontent.com/18012933/65708949-b6810580-e05d-11e9-8d92-5152e1c88499.png)

**Comment by kirilpopov** [comment]
The Electron team and @MarshallOfSound are working for deprecating affinity (ignoring the set of apps that depend on it), so I guess their answer will be "affinity is experimental feature, you should not depend on it", as in several similar tickets.

**Comment by lkonstantinov** [comment]
This is actually an issue that is related to #17406 and removing the affinity overrides wont help in all cases (i.e. it will happen again if you use the Chromium process per site option).

The renderer process doesnt crash, but rather waits for a mutex that never is signaled. The issue is caused by this:
```
// Notify the main process when current context is going to be released.
// Note that when the renderer process is destroyed, the message may not be
// sent, we also listen to the "render-view-deleted" event in the main process
// to guard that situation.
process.on('exit', () => {
  const command = 'ELECTRON_BROWSER_CONTEXT_RELEASE'
  ipcRendererInternal.sendSync(command, contextId)
})

```
and can be patched out by just changing to a async invocation, but such solution leaves a bit of a bad taste. @nornagon - can you please chime in - it looks like the IPC tears down prematurely in this case.

On a slightly related note - why do we have blocking calls in a single threaded environment? I know it will be a breaking change, but I, for one, would sleep better if `sendSync` actually returns a promise.

**Comment by kirilpopov** [comment]
Seems similar to https://github.com/electron/electron/issues/20086

**Comment by markns** [comment]
@kirilpopov would you be able to give some reasons or link to some discussion why affinity is considered for deprecation. Thanks.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
