### ISSUE TITLE
webContents.fromId issue just after web-contents-created event

### ISSUE THREAD

**Issue by magne4000** [electron/electron#20404]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * `4.2.10`, `5.0.11`, `6.0.11`, `7.0.0-beta.5` and probably others
* **Operating System:**
  * MacOS 10.14.6, Windows 10, Ubuntu 18.04
* **Last Known Working Electron version:**
  * _unknown_

### Expected Behavior
- In the main process, after receiving `web-contents-created` event:
  1. we get a `webContents` (lets call it `wc`) as an argument, which is defined and correct ✅ 
  2. `wc.id` is valid ✅ 
  3. `webContents.fromId(wc.id)` returns `null` ❌ 
  4. `webContents.fromId(wc.id)` inside a `process.nextTick` returns the `webContents` ✅ 

### Actual Behavior
In step 3, `webContents.fromId(wc.id)` should have returned the correct `webContents` object (which is `wc`)

### To Reproduce
Fiddle: https://gist.github.com/a8986983e0b62d38bcda5ac42bebe1fb

**Comment by magne4000** [comment]
Could be related in some ways to https://github.com/electron/electron/issues/12036

**Comment by pushkin-** [comment]
Somewhat related to [this](https://github.com/electron/electron/issues/21608)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
Can't repro with Electron 12.0.1
