### ISSUE TITLE
Help needed with running applescript

### ISSUE THREAD

**Issue by bharat619** [electron/electron#20422]
- Electron version: 5.0.4
- Operating System: MacOS Mojave 10.14

Hello folks. I needed help/suggestion. We are developing an application that requires a few apple scripts to run every second. In the local environment, we faced no issue and the application works perfectly fine. But when we build it to dmg file, extract and run it, the application heavily slows down the entire OS.
Initially, we thought that it was due to setInterval method eating up the entire memory space and replaced it with cron job. The result was the same when extracted from .dmg, the application slows down the entire OS.

A thing which works after extracting from dmg is if we launch the content present inside the package contents i.e.  Application/my-app/Contents/MacOS/my-app
This launches the terminal and the application works fine without any issues.

Please suggest what could be the problem over here.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
