### ISSUE TITLE
BrowserView setBackgroundColor() not working

### ISSUE THREAD

**Issue by Beelink** [electron/electron#20447]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.11
  * v7.0.0-beta.5
* **Operating System:**
  * Windows 10 (latest)
  * Manjaro Linux 18.1.0 (x64)

### Actual Behavior

BrowserView background is always transparent

### To Reproduce
view.setBackgroundColor("#2e2c29");
view.setBackgroundColor("#66CD00");
view.setBackgroundColor("66CD00");
view.setBackgroundColor("#FFF");

// help me if i do something wrong

**Comment by mahnunchik** [comment]
Confirm it..

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
