### ISSUE TITLE
Startup Screen Error on Starting on Initiation of Electron application

### ISSUE THREAD

**Issue by Abinash-bapu123** [electron/electron#20469]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.11
* **Operating System:**
  * Windows 8
* **Last Known Working Electron version:**
  * 3.0.2

### Expected Behavior
While starting the electron app it must show the output of index.html clearly.

### Actual Behavior
While starting the electron app the application window opens with black and blank screen. 

### Screenshots
![Screenshot (4)](https://user-images.githubusercontent.com/14068408/66362007-b73f6300-e99e-11e9-9358-c71d266fc813.png)

**Comment by juancarlosfarah** [comment]
I'm also seeing this issue after an upgrade to 6.1.2. Build is working fine on macOS, but on Windows 7 it shows a black screen. Nothing showing up in the logs.

**Comment by Abinash-bapu123** [comment]
> I'm also seeing this issue after an upgrade to 6.1.2 from 5.0.3. Build is working fine on macOS, but on Windows 7 it shows a black screen. Nothing showing up in the logs.

**Comment by damianaiamad** [comment]
I'm seeing this issue with Windows 7 & Electron 6.1.2. 
Ok for Windows 10. Going to test Electron 7.1.1 next.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
