### ISSUE TITLE
BrowserWindow: resizable: false results in incorrect size on Windows

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#20463]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 6.0.0 through 6.0.11, fixed in Electron 7
* **Operating System:** Windows only (macOS and Linux are fine)
* **Last Known Working Electron version:**: 5.x and earlier

### Expected Behavior
Setting the window size should work

### To Reproduce
Run this fiddle with Electron 6.x and observe that the size is wrong. Do it with Electron 7 and things will be peachy again.

https://gist.github.com/7e7322fc3b40d5a9ede016aea321df1b

### Screenshots

![image](https://user-images.githubusercontent.com/1426799/66351005-93820b80-e911-11e9-9b98-7a323b7da587.png)

### Additional Information

To work around this issue, create the window with `resizable: true` and then use `setResizable(false)`.

**Comment by Liupeng8** [comment]
When can fix this bug, 4.x-7.x has this problem, as long as resizable is set, not only unmaximize monitoring fails, isMaximized () also always returns false, and the size of the win.unmaximize () window cannot be restored Set size

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
