### ISSUE TITLE
Electron 6, 7 and 8 does not open the KDE dialog instead

### ISSUE THREAD

**Issue by gusbemacbe** [electron/electron#20516]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.0.0, 6.0.12, 7 and 8
* **Operating System:**
  * Arch Linux with KDE 5
  * Fedora 30 with KDE 5
* **Last Known Working Electron version:**
  * 6.0.0

### Expected Behavior
In reference to https://github.com/electron/electron/issues/765, https://github.com/electron/electron/issues/2911, https://github.com/electron/electron/issues/2927, , which spoke about the desktop environment dialog and also in reference to https://github.com/microsoft/vscode/issues/50386, the Microsoft developer responsible for developing VSCode, asked me to test VSCode Exploration shipped with Electron 6.0.0, checking if it opens the Dolphin/KDE/QT dialog instead.

### Actual Behavior
- Electron 6.0.0, shipped by VSCode, did not open the KDE/QT dialog.
- I also was asked to test with Electron Fiddle. On Electron Fiddle, using Electron 6, 7 and 8, it did not open the KDE/QT dialog instead either.

### To Reproduce
Check the two screenshots.

### Screenshots
* VSCode's Electron 6.0.0 did not open the KDE/QT dialog:
![image](https://user-images.githubusercontent.com/2257024/66544946-ee815180-eb0f-11e9-89e2-855ac02f5942.png)

* Neither Electron Fiddle:
![image](https://user-images.githubusercontent.com/2257024/66552707-31e3bc00-eb20-11e9-8248-9cebc7ffac87.png)

**Comment by gusbemacbe** [comment]
Recalling @tristan957.

**Comment by tristan957** [comment]
Hello. Work is currently ongoing in https://github.com/electron/electron/pull/19159. It is fairly slow going. What you are seeing is expected behavior. Hopefully in the future, I can merge my PR into electron. We will see. Work still needs to be done on it. I am active on GitHub most days, so when the electron devs provide reviews on the PR, I should get to them fairly quickly. Patience is the only thing we can have at the moment.

**Comment by Natetronn** [comment]
Any updates on this a year later, by chance?

**Comment by tristan957** [comment]
Updates are typically in the linked PR.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
