### ISSUE TITLE
After Cmd+R, calling history.back() in renderer reloads the page instead of applying the #hash change in URL

### ISSUE THREAD

**Issue by dko-slapdash** [electron/electron#20515]
### Issue Details

* **Electron Version:**
  * v6.0.12 (newest)
* **Operating System:**
  * MacOS 10.14.6

### Expected Behavior
Cmd+R should likely not affect the way how history.back() navigation happens; i.e. if a #hash change is in the history, after Cmd+R it should still apply the webContents URL #hash part change without page reloading.

### Actual Behavior
Cmd+R on some page affects the way how history.back() acts in renderer: if Cmd+R is pressed, then all calls to history.back() force the page to be reloaded instead of just applying the #hash part stored in the history.

### To Reproduce
1. On some single-page app with hash routing (i.e. using #/some/path in the URL), click on some links to apply e.g. #/some/1 and #/some/2 and #/some/3 hash changes which will be added to the history.
2. Run window.history.back(): it won't reload the page; instead, it would just change the hash part of the URL (perfectly fine).
3. Now hit Cmd+R.
4. Try running window.history.back() again: you'll see that each time you do so, the **page will be hard-reloaded** instead of just changing the #hash part of the URL.

### Additional Information
Notice that e.g. Chrome default Back button works fine: it changes the #hash part of the page without the page reloading independently on whether Cmd+R was pressed or not.

**Comment by ls365882248** [comment]
I have the same question, and how to fix it ?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
