### ISSUE TITLE
[Question] How to display text (some app data) when hovering over the tray icon

### ISSUE THREAD

**Issue by MarchWorks** [electron/electron#20539]
I would like to display some data when the user hovers over the tray icon but I don't have any idea of how

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
