### ISSUE TITLE
Electron 7/8 api? 

### ISSUE THREAD

**Issue by warpcut** [electron/electron#20532]
Is there a way to have electron 8 or at least 7 apis?  I would like to know more about updates, in particular about touchbar module.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
