### ISSUE TITLE
Websocket re connection issue

### ISSUE THREAD

**Issue by pashvin** [electron/electron#20534]
WebSocket reconnection fail due to Chromium issue (see link below).

Could you please update Chromium with the fix in next electron 6.x patch?

https://bugs.chromium.org/p/chromium/issues/detail?id=1006243

### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * macOS all / Windows 10  
* **Last Known Working Electron version:**
  * Don't know

### Expected Behavior

After coming out machine from sleep mode, new web socket connection should work,

### Actual Behavior

New Websocket connection throws an unknown error 

### To Reproduce

This is not easy to reproduce. Sometime it apear quickly for machine sleep and wake up usecase but other time it takes time

### Additional Information

Already fixed in Chromium 77.0.3865.114+. See following link.
Just need to generate Electron 6.x with latest Chromium
https://bugs.chromium.org/p/chromium/issues/detail?id=1006243

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by pashvin** [comment]
Electron 7.x has latest chromium
