### ISSUE TITLE
Memory leak when using offscreen window from a renderer 

### ISSUE THREAD

**Issue by summeroff** [electron/electron#20559]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * start from v6.0.0 , also reproduced on v6.0.12 and v7.0.0-beta.6. 
* **Operating System:**
  *   Windows 10  (1903 build 18362.418)
* **Last Known Working Electron version:**
  * v5.0.11 not leak for me. 

### Expected Behavior
Memory usage stay not grow with time.

### Actual Behavior
Electron continues to allocate memory till system have no more free ram. 

### To Reproduce

There is small electron app that show memory leak. 
https://github.com/summeroff/electron_remote_offscreen_memory_leak
It based on electron quick start example app. 
Most changes In renderer.js. 
Code creates BrowserWindow with offscreen true. And subscribe to paint callback. Callback may do nothing. 
Also loadUrl with some page that constantly update to induce paint events. 

disableHardwareAcceleration() has no effect on memory leak for me. 
There is no memory leak if code moved from renderer.js to main.js. 

  
### Screenshots
<a href="https://ibb.co/CVVHrCb"><img src="https://i.ibb.co/CVVHrCb/offscreen-memory-leak.png" alt="offscreen-memory-leak" border="0" /></a>

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
