### ISSUE TITLE
App Store build succeeded but no window shows due to "out of memory"

### ISSUE THREAD

**Issue by alicerunsonfedora** [electron/electron#20560]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.11
* **Operating System:**
  * macOS 10.15
* **Last Known Working Electron version:**
  * 5.x.x

### Expected Behavior
When opening an App Store version of the app, it should have the main window displayed.

### Actual Behavior
The main window doesn't display at all.

### To Reproduce

Example repo: https://github.com/hyperspacedev/hyperspace

```sh
$ git clone https://github.com/hyperspacedev/hyperspace
$ npm install
$ npm run build-desktop
```

(Making sure to add the proper entitlements files and such as listed in the README)

Submit the resulting dist/mas/ pkg file or install it locally.

### Additional Information
I notice that this happens in the console when I launch it from the terminal:

```
Error: Error: ENOENT: no such file or directory, open '/Applications/Hyperspace.app/Contents/Resources/app-update.yml'
(node:6521) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Applications/Hyperspace.app/Contents/Resources/app-update.yml'
(node:6521) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Applications/Hyperspace.app/Contents/Resources/app-update.yml'
(node:6521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

#
# Fatal process OOM in CodeRange setup: allocate virtual memory
#
```

**Comment by KevinGervais** [comment]
Actually, I think I found where is the problem, but I don't know the solution.

I want to say first that I tested the problem only on osx 10.15 and that I didn't find this problem in older versions of osx.

So let me explain the facts I saw when testing:
In version 5.x.x of electron, Electron.app/Contents/Frameworks folder contains only 2 folders:
1. Electron Framework.framework
2. Electron Helper.app

When we sign the Electron app in 5.x.x  and sign also the folders and subfolders of Electron Framework.framework and Electron Helper.app  everything works great.

But with electron 6.x.x and 7.x.x Electron.app/Contents/Frameworks folder contains 5 folders:
1. Electron Framework.framework
2. Electron Helper.app
3. Electron Helper (Plugin).app
4. Electron Helper (GPU).app
5. Electron Helper (Renderer).app

by example if we delete Electron Helper (Plugin).app because we don't need it, everything still works (the app window opens well).

 If we sign the app and sign also the folders and subfolders of Electron Framework.framework and Electron Helper.app  everything works great (the app window opens well). but when we send the app to the app store, it says that Electron Helper (GPU).app and Electron Helper (Renderer).app are not sandboxed (because they are not signed)

so if we sign Electron Helper (GPU).app and Electron Helper (Renderer).app, the app crash (the window doesn't show up)
if we sign one of them, it crashes also (both are the problem).

to be more specific, the problem occurs when we do:
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Helper (GPU).app/Contents/MacOS/Electron Helper (GPU)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Helper (GPU).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Helper (Renderer).app/"

Hope that this could help!

**Comment by alicerunsonfedora** [comment]
Yes, I do have these signed. I don't know if I need extra entitlements to the helper apps besides the `com.apple.security.app-sandbox` and `com.apple.security.inherit` entitlements

**Comment by cruzerld** [comment]
Hey @alicerunsonfedora , I had the same issue as you and the answer is you need to have the same entitlements in the helper apps as you do in the main app. Seems like hardened-runtime doesn't pick up the inherit entitlements correctly. I spent most of today chasing this exact issue down.

Hope that works for you!

**Comment by alicerunsonfedora** [comment]
I've made the necessary changes and it appears that App Store verification is alright, but I've been unable to actually test the binary.

**Comment by mahnunchik** [comment]
It seems it is related https://github.com/electron/electron-osx-sign/issues/223

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
