### ISSUE TITLE
globalShortcut should allow for registering shortcut that should be triggered once by keypress

### ISSUE THREAD

**Issue by sky0matic** [electron/electron#20567]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * Windows 10 Pro (1903)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

`globalShortcut.register` should only call the callback once by keypress when the user keeps pressing the keys matching a shortcut (or have a mode for it)

E.g. On `Spotify` keeping pressing `Next` should only change songs once.

### Actual Behavior

`globalShortcut.register` is calling the callback repeatedly when the user keeps pressing the keys matching the shortcut

E.g. On `Spotify` keeping pressing `Next` is changing the songs repeatedly to the point it will actually crash

### To Reproduce
* Simply register a simple shortcut like this : 
```
globalShortcut.register('num7', () => console.log('num7');
```
* Run the app
* Keep pressing <key>NumPad7</key> and notice all the `num7` console logs.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
