### ISSUE TITLE
Hotkeys crash in the case of Russian languages

### ISSUE THREAD

**Issue by joeyer** [electron/electron#20601]
electron 4.2.2

1.The keyboard language is Russian. When there are Russian letters, the globalShortcut method will crash or be invalid.

2.On the MAC system, hotkey conflicts cannot be detected, windows can

**Comment by joeyer** [comment]
eg:Ctrl+Shift+Й

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
