### ISSUE TITLE
Build failed on Windows GN

### ISSUE THREAD

**Issue by jc-lab** [electron/electron#20604]
### Issue Details

* **Electron Version:** 6.0.12
  * 
* **Operating System:** Windows 10
  * 

I followed this link: https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md.

```bash
> set GIT_CACHE_PATH=D:\.git_cache
> mkdir %GIT_CACHE_PATH%

> set SCCACHE_BUCKET=electronjs-sccache-ci
> set SCCACHE_TWO_TIER=true

> mkdir electron-gn && cd electron-gn
> gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
> gclient sync --with_branch_heads --with_tags
> cd src/electron
> git checkout v6.0.12
> cd ../../

> cd src
> set CHROMIUM_BUILDTOOLS_PATH=%cd%\buildtools
> gn gen out/Debug --args="import(\"//electron/build/args/debug.gn\")"
```

But GN shows error below:
```
ERROR at //electron/BUILD.gn:1165:9: Only source, header, and object files belong in the sources of a executable. //electron/atom/browser/resources/win/atom.ico is not one of the valid types.
        "atom/browser/resources/win/atom.ico",
        ^------------------------------------
See //electron/BUILD.gn:1127:3: whence it was called.
  executable("electron_app") {
  ^----------------------------
See //electron/build/args/all.gn:3:21: which caused the file to be included.
root_extra_deps = [ "//electron" ]
```

I try to rebuild electron to use shared node.dll.
This is because I tried to LoadLibrary(electron.exe) and tried node::Start but it didn't work.
Is there a better way than this?
I have a situation that can not use electron_run_as_node.

Thanks.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
