### ISSUE TITLE
Windows Narrator triggers `blur` on certain types of items

### ISSUE THREAD

**Issue by natnan** [electron/electron#20608]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta.7
  * 6.0.12 
  * 5.0.11
  * 4.2.11
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * Gave up trying after 4.2

### Expected Behavior
To keep the focus on the window.

### Actual Behavior
The window is blurred when navigating to `<button>`s, links (`<a>`), `<input>`s and possibly other types of elements. Seems to be fine with `span`s, `h1`s etc..

### To Reproduce
Easy to reproduce with Fiddle, trying different versions.
- Add `mainWindow.on('blur', () => console.log('blur'));` to Main Process.
- Add a simple input element to HTML.
- Start the fiddle and Windows Narrator.
- Navigate to the input box using Narrator (Caps Lock - arrow keys).
- When the narrator gets to the input box, "blur" will be logged to the console.

### Screenshots
![image](https://user-images.githubusercontent.com/5628051/66933555-8c59ac80-f039-11e9-9756-f406ea47d43e.png)

### Additional Information
The narrator seems to continue to work and you can still type into the input box even though the BrowserWindow doesn't think it has the focus.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
