### ISSUE TITLE
app.getPath('downloads') doesn't work correctly!

### ISSUE THREAD

**Issue by gebalesev** [electron/electron#20619]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v4.2.4
* **Operating System:**
macOS 10.15 Catalina

### Expected Behavior
I'd like to save a file using https or http module like node js in my downloads file!
the script is working fine when i set different directory, but when i use app.getPath('downloads' or 'desktop' or whatever from electron) the file is saving in /var/root/downloads so i cannot access them, 

![image](https://user-images.githubusercontent.com/56690529/67024057-0eaea300-f104-11e9-8dff-dc8229dcb195.png)

I don't want to use default electron downloader.

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

Could you please attach a minimum repro for this problem? A small snippet of code will do, just so we can get this moving more easily. Thanks!

**Comment by alirezavalizade** [comment]
same issue on Catalina

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/20619#issuecomment-543305213). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
