### ISSUE TITLE
MAC menu how can use role and click at the same time

### ISSUE THREAD

**Issue by StetsenkoAnton** [electron/electron#20617]
"electron": "^6.0.10",
macOS: 10.14.6

I create custome menu:
```javascript
{
  label: 'Edit', 
  submenu: [
    { label: 'Copy',  accelerator: this.isMac ? 'meta+c' : 'ctrl+c', click: ()=> {SendEventToRender}},
    { label: 'Paste', accelerator: this.isMac ? 'meta+v' : 'ctrl+v', click: ()=> {SendEventToRender}},
  ]
}
```

The current code just sends the event to the renderer process. But default (copy/paste) functionality doesn't work. If add the "role", default functionality works but doesn't work events.

How I can send the event to the renderer process and not break default functionality?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by StetsenkoAnton** [comment]
Thanks for the answer. I will in the community. But if this is not possible, then this is a bug! Or am I wrong? :)
