### ISSUE TITLE
Resizing a window with a set aspect ratio makes window size jump shrink

### ISSUE THREAD

**Issue by someonewasherebefore** [electron/electron#20618]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 6.0.12
* **Operating System:**
  10.14 macOS
* **Last Known Working Electron version:**
  * 

### Expected Behavior
To resize correctly and not jump.

### Actual Behavior
As soon as you click the far bottom far right corner and drag, it jumps shrinks by 100px. It doesn't happen on the bottom centre point (very beginning of the GIF attached shows it)

### To Reproduce
1. Set aspect ratio with an added custom height of 38px: `win.setAspectRatio(16/9, { height: 48, width: 0 })`
2. Try resizing it from the bottom right corner (resizing from bottom center works fine)

### Screenshots
![CleanShot 2019-10-17 at 12 52 32](https://user-images.githubusercontent.com/55196141/66996681-0479ae00-f0de-11e9-97eb-7c83d405641b.gif)

**Comment by momakes** [comment]
I want to confirm this bug is present in 7.1 too.

**Comment by robinleboe-sw** [comment]
Confirming this bug is present in 9.0 as well.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by morajabi** [comment]
This is still happening.
