### ISSUE TITLE
error in manjaro

### ISSUE THREAD

**Issue by 2637309949** [electron/electron#20616]
> electron .

[21341:1017/133146.932756:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by miniak** [comment]
Closing after 10 days
