### ISSUE TITLE
Can't set Host header

### ISSUE THREAD

**Issue by liximomo** [electron/electron#20647]
* **Electron Version:**
  6.0.12
* **Operating System:**
  macos 10.14.5 

All custom headers worked except `Host`.

```ts
function handleBeforeSendHeaders(
  details: electron.OnSendHeadersDetails,
  callback: (response: electron.OnBeforeSendHeadersResponse) => void
) {
  const host = hostMap.get(details.id);
  if (host) {
    hostMap.delete(details.id);
    console.log('set host headers', details.id, host);
    details.requestHeaders['Host'] = host;
    details.requestHeaders['x-Host'] = host;
  }

  callback({
    requestHeaders: details.requestHeaders,
  });
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/9816225/67171621-89204100-f3ea-11e9-984a-fdc13a848785.png)

Only `x-host` has been sent.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
