### ISSUE TITLE
Setting the window title causes flashing with Windows 7 Classic Theme

### ISSUE THREAD

**Issue by sbatten** [electron/electron#20695]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 2.0.0 -> 7.0.0
* **Operating System:**
  * Windows 7 SP1
* **Last Known Working Electron version:**
  * 1.7.12
### Expected Behavior

Setting the window title should have no effect on the window chrome when frameless browser windows are enabled.

### Actual Behavior

When setting the window title, the native window chrome flashes through the window. See this longstanding VS Code issue for a demo: https://github.com/microsoft/vscode/issues/56630

### To Reproduce
Prereq: Enable Classic Theme on Windows 7

1. Using Electron Fiddle, set up a frameless browser window app with titlebarstyle set to hidden and some default title.
2. In page, set up a button with a handler that changes the window title in some way. I just have `document.title = document.title + '!'`
3. Run the app and spam the button. 

You will be able to see the flicker of the window chrome.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by RogueX957** [comment]
Still reproducible on VScode 1.55, which is using Electron 11.3.0 and Discord too, but I can't confirm if Discord is using a supported version
