### ISSUE TITLE
Failed to load local resources with session.fromPartition webPreferences

### ISSUE THREAD

**Issue by hulufei** [electron/electron#20697]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.1
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 
Here is a simple example:
```
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 450,
    webPreferences: {
      // session: session.defaultSession,
      session: session.fromPartition('test'),
      nodeIntegration: true
    }
  });
  // The local js file is existed
  mainWindow.loadURL('file:///_next/static/agJsBJLE49FTSdYD_CfK0/pages/_app.js');
```
Can't load the js file when setting `session.fromPartition`, with error `Not allowed to load local resource`.

However, if I changed session to `session.defaultSession`, it works.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
