### ISSUE TITLE
macOS Sierra - Native tabs does not work

### ISSUE THREAD

**Issue by dalisoft** [electron/electron#20703]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.x, v5.x, v6.x, v7.x
* **Operating System:**
  * macOS 10.12.6
* **Last Known Working Electron version:**
  * 3.x

### Expected Behavior

Native tab should work and i should able to create multiple Native tabs inside Single window

See [here](https://github.com/microsoft/vscode/issues/76537#issuecomment-545030479)

### Actual Behavior

Missing "+" button, when if available somehow, creates Window in new Full-screen space or creates black full-screen space

### To Reproduce

Try Electron Fiddle, [how i tested here](https://github.com/microsoft/vscode/issues/76537#issuecomment-545309805)

### Screenshots

![](http://joxi.ru/Vrw6EGni7eEbWA?d=1)
![](http://joxi.ru/gmv5pMOcqoWbdr?d=1)

### Additional Information

Related issue: [#76537](https://github.com/microsoft/vscode/issues/76537)

**Comment by bpasero** [comment]
//cc @deepak1556

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
