### ISSUE TITLE
Rendering offscreen performance and example on how to use it as 3D texture

### ISSUE THREAD

**Issue by danielmorena** [electron/electron#20714]
I'm trying to find a way to grab the results from an offscreen render and use it as 3D texture to provide a perspective correction on a projected surface. Is it possible, in a performant way?  I didn't find an example on how to use the renderer result, it's just stubbed on comment on the tutorial page. Also, is it possible to alter the matrix projection of a native window as it is accessible by the api. If it's, there's an example of it somewhere?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
