### ISSUE TITLE
Notification remove unknown strings

### ISSUE THREAD

**Issue by Crazie-ash** [electron/electron#20740]
Myself trying to create a notification using electron's native notifications feature..
When I use an icon it resulted the following:-
![image_2019_10_25T09_25_07_802Z](https://user-images.githubusercontent.com/45698249/67560104-d2002e80-f737-11e9-89e0-5ba09bfdf513.png)

But without an icon it resulted as expected:- 
![image](https://user-images.githubusercontent.com/45698249/67560706-104a1d80-f739-11e9-8c54-451a3a3abc89.png)

I would need with an icon but without the string "electron.app.Electron" and I am not sure where does it comes from....
Also please let me know the feasibility to set duration of the notification... e.g. notifications must show & remain for 5 mins....

**Main:-**
notification = new Notification({
      title: 'Testing',
      body: 'Create a notification',
      icon: path.join(__dirname, 'favicon.256x256.png')
    });
    notification.show();

**Comment by rajnishsingh04012001** [comment]
I am a beginner can I work on this project.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by Crazie-ash** [comment]
"template to be filled out on all new issues" meaning the code part @codebytere .... or something else... Can u pls explain more in detail?

**Comment by Crazie-ash** [comment]
Sorry, I used "app.setAppUserModelId('MyAppname')" before the using notification. It resolved it. Thanks anyway.
