### ISSUE TITLE
Electron app is not brought back on X11 session restore

### ISSUE THREAD

**Issue by alekksander** [electron/electron#20756]
This is regarding Linux compatibility. Apparently applications like caprine are not brought back with Xs session. Is Electron not following the standard session protocol on X?

X11 documentation: https://www.x.org/releases/X11R7.7/doc/libSM/xsmp.html

(i was told to post here with this issue. https://github.com/sindresorhus/caprine/issues/1134 )

Thank You

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
