### ISSUE TITLE
Error with Electron 7, setPreload and require

### ISSUE THREAD

**Issue by magne4000** [electron/electron#20782]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 6.1.2

### Expected Behavior
With the following:
```typescript
// main.js
session.defaultSession.setPreloads([path.join(__dirname, 'preload-init.js')]);

// preload-init.js
require('./preload');

// preload.js
console.log("I'm a preload")
```
If I load any BrowserWindow or webview, I should see the `I'm a preload` message in a console without surrounding errors.

### Actual Behavior
With Electron 7, I got the following error message printed in the main console:
```
[4219:1028/175451.570030:ERROR:CONSOLE(3536)] "Unable to load preload script: /Users/magne/workspace/electron-quick-start/preload-init.js", source: electron/js2c/sandbox_bundle.js (3536)
[4219:1028/175451.570065:ERROR:CONSOLE(3537)] "Error: module not found: ./preload", source: electron/js2c/sandbox_bundle.js (3537)
```
The `I'm a preload` message is printed as well, which is really misleading.

The issues does not arise if I use the `webPreferences.preload` parameter instead of `session.setPreloads`.

### To Reproduce
```sh
$ git clone https://github.com/magne4000/electron-quick-start.git -b electron-7-set-preloads
$ npm install
$ npm start || electron .
```

With Electron 6 or 7, you see the following messages in renderer console:
![image](https://user-images.githubusercontent.com/1098371/67700146-b3a36880-f9ad-11e9-9bb1-0f9aa3402100.png)

It means that the preload loaded successfully.

But with Electron 7, you also got the message error from above printed in the main console.

**Comment by sentialx** [comment]
That's because the preload scripts try to inject also in the opened devtools, which I think should be an expected behavior. Previously it didn't work, even though the devtools were in the same session as webContents (correct me if I'm wrong). However it would be great if devtools preload script could have also Node Integration, so that we could add Chrome APIs.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
