### ISSUE TITLE
An Electron Build Service for Windows, Linux and Mac like https://build.phonegap.com?

### ISSUE THREAD

**Issue by jasdeepkhalsa** [electron/electron#2079]
I have built an app in Electron (https://github.com/sikher/sikher) and wanted to know if you have a build service where I can upload my source and get back Atom binaries for each platform?

I wish for the users of my app to not have to install anything - just double click and off they go but since I'm only on Ubuntu/Linux I do not have access to Windows or Mac to build binaries for these platforms, and I'm sure developers on other platforms will suffer from the same problem!

This could be a really important and significant addition for the Atom project to have e.g. an https://build.atom.io service which is similar to the https://build.phonegap.com service for Apache Cordova/Phonegap apps.

The service would:
* Take in a .zip file of an Atom source
* Ask if you would like to re-name 'Atom' app to another name e.g. 'MyApp'
* Build binaries for Windows, Linux and Mac hosted on AWS

Everyone's thoughts on this would be much appreciated! :smiley:

**Comment by Tribex** [comment]
@jasdeepkhalsa You can build for all platforms locally using https://github.com/maxogden/electron-packager . I can't comment on how well it works though.

**Comment by jasdeepkhalsa** [comment]
Yes I'm using this currently but AFAIK you need a Mac to create a Mac executable  (.app) and a Windows to create an (.exe)

**Comment by Tribex** [comment]
@jasdeepkhalsa I'm *pretty* sure you can build for all platforms and architectures, or at least most of them with that.

**Comment by jasdeepkhalsa** [comment]
I'll have a go and report back!

**Comment by jprichardson** [comment]
> @jasdeepkhalsa I'm pretty sure you can build for all platforms and architectures, or at least most of them with that.

This is correct. I've been doing this for awhile.

**Comment by jasdeepkhalsa** [comment]
Okay I've just tested it and yes you can build for all platforms locally with `electron-packager` - even though it is incredibly slow (and my laptop is a top spec core i7 with 16GB RAM) e.g. I did...

    electron-packager ./ {{appname}} --platform=all --arch=all --version=0.29.2 --out=./dist/

So I still think some would prefer a build service hosted by Atom/GitHub themselves, especially those with less powerful laptops/PCs.

**Comment by jprichardson** [comment]
@jasdeepkhalsa The first time yes, because it's downloading six bundles and packaging them up (since you used `all`). The second time it shouldn't be as slow, but even if it were, you're still packaging for six different platforms. Packaging my app for Windows, Linux, and Mac  (x64) only takes a min or two on my MBA 8 GB. I could however see the utility in such a service if you were building with native modules, because then you would have to compile on said platform.

**Comment by jorangreef** [comment]
If you used a third party build service, it probably would not be able to code sign your Windows exe and Mac app since you wouldn't want to give out your private key.

**Comment by jasdeepkhalsa** [comment]
@jprichardson I'll try it a subsequent time to compare!

@jorangreef I doubt there's any particular app signing going on if you can build from any platform in the first place?

**Comment by jorangreef** [comment]
@jasdeepkhalsa I might have misunderstood, I thought you meant a service which takes care of building the finished binaries for all platforms? Normally this would need to include code-signing for Windows and Mac, as otherwise it won't run on those platforms or be caught by antivirus when downloaded by users. So I guess you could have a third party service which does everything except code-signing, but then one would still need to automate the code-signing on Windows and Mac platforms, so it probably makes sense to just do everything in one private service.

**Comment by jasdeepkhalsa** [comment]
@jorangreef Ah right I see what you mean! I didn't know that, thanks for explaining! What I meant was that the `electron-packager` itself does not ask anything about signing, it just seems to build the binary? Now I don't know if that's because electron binaries are already signed or they are missing this part out totally? Either way I think your concern is valid although I have seen other build services e.g. Phonegap handle signing keys securely so to make building in the cloud more hassle-free than building locally.

**Comment by jorangreef** [comment]
@jasdeepkhalsa I'm not sure about `electron-packager` but I think Mac will require everything in the .app to be signed, not just binary but also javascript source. Windows might be fine with a pre-signed Electron binary (and maybe even if you rename it), but then I think you won't be able to edit any of the exe details (e.g. version, publisher, copyright). Hope that helps.

**Comment by zcbenz** [comment]
I'm closing this since it is not actually related to Electron itself, anyone interested in this can just go ahead building a service, but currently we don't have any plan for this.

**Comment by ianjennings** [comment]
Hey all, I'm working on a prototype for a service like this. If you'd like to be notified when it's available, you can indicate your interest through [this form](https://ianjennings.typeform.com/to/TaYmnL).

**Comment by zeke** [comment]
This is also this thing, though I haven't used it or heard of anyone using it:

http://www.electronbuild.com
https://www.npmjs.com/package/electron-build

**Comment by develar** [comment]
electron-builder now supports building Electron app for Linux (all supported targets) on Windows (on macOS it is already supported locally) using free public [electron-build-service](https://github.com/electron-userland/electron-build-service).

Building for Windows is not so required, because electron-builder bundles all needed tools and you can easily build (and even sign) Windows on macOS and Linux (for Linux wine is not prebundled). Docker images also provided if you want just run without installing anything (https://www.electron.build/multi-platform-build#docker).

The only exception — Appx target, Windows is required. And so, electron build service will in the future provides Windows build agents and electron-builder will be able to build AppX on any OS. Thanks to Microsoft, Appx must be not signed (it is done by MS on publish), and so, no questions about "can we trust and pass code signing certs to remote build server?")

macOS — depending on feedback about electron-build-service. 

(and to make clear for everyone — it is not Electron issue that you cannot build app for all platforms (https://www.electron.build/multi-platform-build)).
