### ISSUE TITLE
Electron app is not brought back on X11 session restore

### ISSUE THREAD

**Issue by alekksander** [electron/electron#20822]
Tested on:
* Electron version: 6.0.1 and up (edit: last checked 7.1.1)
* Operating system: Ubuntu 18.04.1 

### Expected behavior
Electron based applications are brought back on X11 session restore

### Actual behavior
Electron app is not brought back on X11 session restore, user has to start manually

### How to reproduce
→Install Electron based application like Caprine (https://github.com/sindresorhus/caprine/releases)
→Have session saving set in the system
→Restart system with some apps running
→Electron based ones are not saved upon session restore

Documentation about X11 standard protocol: https://www.x.org/releases/X11R7.7/doc/libSM/xsmp.html

**Comment by alekksander** [comment]
@sofianguy do we need a new label? this issue is valid on 7.1.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
