### ISSUE TITLE
Buggy zoom. The cursor automatically changes the width to 0.

### ISSUE THREAD

**Issue by truepatch** [electron/electron#20837]
This problem is most likely in the Chromium engine. 
But I hope this helps you solve the scaling issue.
### Information
vscode -> settings.json -> `"window.zoomLevel": -1`

This problem in this subject [vscode#83347](https://github.com/microsoft/vscode/issues/83347)
And here [Bracket-Pair-Colorizer-2#175](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/175)

Width or height must be at least 1 pixel even when reduced. 
Because these values are set explicitly.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
