### ISSUE TITLE
How to disable LOG in the userData directory?

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#20843]
### Problem Description
In electron 5.x, there'll be a LOG file in the ~/Library/Application Support/xxx/(userData directory), which is a duplicate with mine. 
![image](https://user-images.githubusercontent.com/11768033/67834762-339f0f00-fb23-11e9-8478-0dc61391410a.png)

### Proposed Solution
Disable the creation of this LOG file

### Alternatives Considered
None

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
