### ISSUE TITLE
Text is rendered slightly thicker

### ISSUE THREAD

**Issue by harryi3t** [electron/electron#20848]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Same as https://github.com/electron/electron/issues/19861 which was closed since the reported version was 4.x which is not supported anymore. I found that even the latest versions are affected by this.

* **Electron Version:**
 &gt; v3.1.8 < v4, v5, v6, v7
* **Operating System:**
macOS 10.15.1
* **Last Known Working Electron version:**
<= 3.1.8, 4.x

### Expected Behavior
The font-weight should be normal

### Actual Behavior
The text is slightly thicker

### To Reproduce
Use this fiddle. Open multiple windows and change electron versions
https://gist.github.com/d65e479e241de2361106ec37f82b22ad

### Screenshots

<details>
  <summary>Issue on v5</summary>
  
![image](https://user-images.githubusercontent.com/5207331/67861468-4a0a9200-fb46-11e9-9c85-629bfca42223.png)
</details>

<details>
  <summary>Issue on v6</summary>
  
![image](https://user-images.githubusercontent.com/5207331/67861390-27787900-fb46-11e9-8341-87f98241251c.png)
</details>

#### Issue on v7
![image](https://user-images.githubusercontent.com/5207331/67861336-06178d00-fb46-11e9-8669-d52bb8b320a5.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
