### ISSUE TITLE
setAlwaysOnTop stops working on Linux KDE Plasma

### ISSUE THREAD

**Issue by MHekert** [electron/electron#20858]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.11
  * 7.0.0
* **Operating System:**
  * Manjaro 18.1.2 with KDE Plasma 5.17.1
  * Kubuntu 18.10 with KDE Plasma 5.13.5
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Window should stay always on top after setting it with setAlwaysOnTop method, then hiding it and showing it again.

### Actual Behavior
Window always stays on top until it is hidden and then shown again. Running setAlwaysOnTop method again after showing window fixes it.

### To Reproduce
```sh
$ git clone https://github.com/MHekert/electron-quick-start.git -b bug-set-always-on-top
$ npm install
$ npm start
```
* setAlwaysOnTop works
* click with left mouse button on tray to hide
* click with left mouse button on tray to show
* setAlwaysOnTop does not work anymore

#### Code snippet after which window stops staying on top
```javascript
mainWindow.setAlwaysOnTop(true)
mainWindow.hide() 
mainWindow.show()
```

### Additional Information
I also tested it on Windows 7 x64 and it works there.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
