### ISSUE TITLE
There is no API to disable TouchBarButton  [macOS]

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#20903]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Currently we can't disable the  TouchBarButton
![Screen Shot 2019-11-01 at 11 30 00 AM](https://user-images.githubusercontent.com/1118249/68000474-3b81bf00-fc9b-11e9-9e0e-339e46798f29.png)

### Proposed Solution

Add API to disable TouchBarButton

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by gaodeng** [comment]
@codebytere  updated
