### ISSUE TITLE
There is no API to mark the menu item as an alternate to the previous menu item. [macOS ]

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#20902]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Press the Option key while the menu is open and see the menu items change.
Electron has no related API to implement this
![alt](https://user-images.githubusercontent.com/1118249/68000147-dc6f7a80-fc99-11e9-8323-4e1487a1b388.gif)

### Proposed Solution

Add API isAlternate to MenuItem
### Additional Information

https://developer.apple.com/documentation/appkit/nsmenuitem/1514823-isalternate

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by gaodeng** [comment]
@codebytere  updated
