### ISSUE TITLE
BrowserWindow.setIcon wrong types

### ISSUE THREAD

**Issue by NaridaL** [electron/electron#20929]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

The TS types don't match behavior/docs. According to https://electronjs.org/docs/api/native-image, you can pass a string to set the window's icon, and you *can*. Running it works. There is an unexpected compile error, however.

* **Electron Version:**
```
$ npx electron --version

 v7.0.0
```
* **Operating System:**
![image](https://user-images.githubusercontent.com/10828874/68068343-ef468580-fd53-11e9-96a9-2b4a664da29d.png)

* **Last Known Working Electron version:**
N/A

### Expected Behavior
No TS type error.

### Actual Behavior
Following TS type error
> Argument of type '"foo.ico"' is not assignable to parameter of type 'NativeImage'.ts(2345)

### To Reproduce
În renderer.ts
```ts
import { remote } from 'electron'
remote.getCurrentWindow().setIcon('foo.ico')
```

### Screenshots
![image](https://user-images.githubusercontent.com/10828874/68068416-d1c5eb80-fd54-11e9-8f92-a3063f562d03.png)

**Comment by miniak** [comment]
@NaridaL the linked documentation claims that you can pass an `icon` property in the `BrowserWindowOptions`, not that you can pass a string to `setIcon()`. The `icon` icons actually does not seem to be even implemented.

**Comment by NaridaL** [comment]
@miniak I guess the docs are ambiguous, but as I said, BrowserWindow.setIcon(string) works, as does Tray.setIcon(string). The problem is the types.

**Comment by MarshallOfSound** [comment]
This is mostly because of an API decision made a long time ago that the `NativeImage` type will be auto-constructed from a string (treating the string as a file path) if possible.  Personally although that is possible I don't think we should type this as it fundamentally isn't type safe.

Passing any old string is not valid to any of those methods, it's safer to make users do the `nativeImage.load....` calls themselves and retain type safety that way IMO.

Whatever we do it should be consistent across our docs, at the moment it's like 50/50 between `NativeImage` and `NativeImage | String`
