### ISSUE TITLE
cookies.set with custom protocol is broken in Electron v7

### ISSUE THREAD

**Issue by luy19** [electron/electron#20940]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.0
* **Operating System:**
  *  macOS 10.14.4 
* **Last Known Working Electron version:**
  *  6.1.4

### Expected Behavior

Set cookie successful.
### Actual Behavior

Set cookie failed. [Error: Cannot set cookie for current scheme]
### To Reproduce

```
const { app, BrowserWindow, protocol, session } = require('electron');
const path = require('path');

const CUSTOM_SCHEME = 'app';
const CUSTOM_HOST = 'com.example.www';
const CUSTOM_ORIGIN = `${CUSTOM_SCHEME}://${CUSTOM_HOST}`;

let mainWindow;

protocol.registerSchemesAsPrivileged([
  { scheme: CUSTOM_SCHEME, privileges: { standard: true, secure: true } },
]);

app.on('ready', function() {
  protocol.registerFileProtocol(
    CUSTOM_SCHEME,
    (request, callback) => {
      callback({ path: path.normalize(`${__dirname}/index.html`) });
    },
    // error => {
    //   if (error) console.error('Failed to register protocol');
    // },
  );
  const {
    node,
    chrome,
    electron,
  } = process.versions;
  console.log(`We are using Node.js ${node}, Chromium ${chrome}, electron ${electron}.`);
  const bar_cookie = {
    url: CUSTOM_ORIGIN,
    name: 'bar',
    value: 'bar_value',
    expirationDate: Date.now() / 1000 + 60 * 60 * 24,
    session: false,
    // secure: true,
  };
  session.defaultSession.cookies.set(bar_cookie).then(
    () => {
      console.log('Set bar_cookie successful.');
    },
    error => {
      console.error('Set bar_cookie failed.', error);
    },
  );
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  });
  mainWindow.loadURL(`${CUSTOM_ORIGIN}/index.html`);
});
```

### Screenshots

![20191106103451](https://user-images.githubusercontent.com/26106266/68264073-a6a80880-0082-11ea-88b7-077ae9fa0c14.jpg)
![20191106103115](https://user-images.githubusercontent.com/26106266/68264116-c2abaa00-0082-11ea-8782-d55016aaadba.jpg)

### Additional Information

And, if I put `secure: true` in the cookie, it will cause error`[Error: Failed to parse cookie]`, both in 7.1.0 and 6.1.4 version

**Comment by nornagon** [comment]
Yep, I can reproduce this. Doesn't seem platform-specific.

**Comment by nornagon** [comment]
Looked into this, I don't think we can fix this without patching Chromium.

The cookie is blocked [here](https://source.chromium.org/chromium/chromium/src/+/master:net/cookies/cookie_monster.cc;l=1164;drc=2b448df782bbd326d328c9c71795114fab9461d3?originalUrl=https:%2F%2Fcs.chromium.org%2F), which references the "cookieable schemes" list, which is initialized somewhat confusingly in two places [[1](https://source.chromium.org/chromium/chromium/src/+/master:services/network/cookie_manager.cc;l=228-239;drc=2b448df782bbd326d328c9c71795114fab9461d3?originalUrl=https:%2F%2Fcs.chromium.org%2F)] [[2](https://source.chromium.org/chromium/chromium/src/+/master:net/cookies/cookie_monster.cc;l=331-333;drc=2b448df782bbd326d328c9c71795114fab9461d3?originalUrl=https:%2F%2Fcs.chromium.org%2F)], but both of those places include only the [default schemes](https://source.chromium.org/chromium/chromium/src/+/master:net/cookies/cookie_monster.cc;l=495-496;drc=2b448df782bbd326d328c9c71795114fab9461d3?originalUrl=https:%2F%2Fcs.chromium.org%2F) `{"http", "https", "ws", "wss"}`, (and optionally `"file"`, but we don't set things up such that file is allowed).

Probably this involves refactoring the CookieManager `AllowFileSchemeCookies` to be something like `AddCookieableSchemes` and change the mojom file to be a list of extra cookieable schemes instead of a boolean for `file`.

cc @deepak1556

**Comment by deepak1556** [comment]
> Probably this involves refactoring the CookieManager AllowFileSchemeCookies to be something like AddCookieableSchemes and change the mojom file to be a list of extra cookieable schemes instead of a boolean for file.

Yeah definitely needs this change, no other way to solve this. `URLRequestContextGetter` allowed us to do this without patch because of same process https://github.com/electron/electron/blob/4-2-x/atom/browser/net/url_request_context_getter.cc#L347 ;)

**Comment by gamerz1990** [comment]
Facing same issue on win10 x64 electron v8.x

**Comment by walmat** [comment]
Same (or similar) issue on macOS Catalina / Electron 8.x.x

Unable to set `secure: true` cookies no matter what I do.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
