### ISSUE TITLE
hwo to disable IME in <input type='text'/>

### ISSUE THREAD

**Issue by nbuhell** [electron/electron#20971]
call api  "ImmAssociateContext(handle, NULL) " not work in electron 7.0.1

<input type="text" style="ime-mode: disabled;"> not work in chrome

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
