### ISSUE TITLE
backgroundThrottling: false not obeyed in Electron 4+

### ISSUE THREAD

**Issue by mbman** [electron/electron#20974]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 All versions starting from 4
* **Operating System:**
 Tested on Win 10, don't know if other platforms are affected.
* **Last Known Working Electron version:**
  3.1.13

### Expected Behavior
When an electron window is opened with `backgroundThrottling: false` set in `webPreferences` it shouldn't throttle `setTimeout` while window is minimized, but it does throttle it.

### Actual Behavior
Minimized window's `setTimeout `is throttled, despite disabling it.

### To Reproduce
Please load the Electron Fiddle: [https://gist.github.com/987afc63925e8ab2ad9c1e02dd7c3309](https://gist.github.com/987afc63925e8ab2ad9c1e02dd7c3309) and follow instructions in the opened window.

### Additional Information
Possible similar issue: https://github.com/electron/electron/issues/17402

**Comment by codebytere** [comment]
@mbman i believe this was fixed in https://github.com/electron/electron/pull/20239, but was not backported. I'll see if I can get some backports up to address this in versions 7 and 6.

**Comment by mbman** [comment]
@codebytere thanks for the info - does that PR also fixes `window.setBackgroundThrottling() `not working?

**Comment by codebytere** [comment]
That'll be fixed by the PR i put up a little while ago: https://github.com/electron/electron/pull/21037

**Comment by Slapbox** [comment]
#21037 says it's backported to `6.1.x`, but I'm getting `document.visibilityState === 'hidden'` when my window is `minimized` or `hidden` on `6.1.7` - any thoughts?

Much more strangely, static content in my `BrowserWindow`s disappears when I focus a separate window in my project and many other oddities, 3 shown below

![image](https://user-images.githubusercontent.com/6835891/71941216-f2605680-3186-11ea-8ec8-4cfa3ea92670.png)

**Comment by Slapbox** [comment]
Unfortunately I continue seeing this issue and the `visibilityState` continues to return unexpected results. [You can see here the effects](https://recordit.co/WSyRahO9bI). The cursor updates in response to the underlying content, but that content is not visible (`default`, `pointer`, `text`). Note that when the cursor is missing in this video, it is a `text selection cursor` but the screen recorder doesn't capture that cursor.

The failure to render contents can occur at any time in any application window or multiple application windows. Any ideas about this? Is this not actually fixed in Electron 6? Am I doing something wrong?

**Comment by Slapbox** [comment]
@sofianguy @codebytere  this persists in `Electron 8.2.5` _or_ [the docs](https://www.electronjs.org/docs/api/browser-window#page-visibility) are wrong

`document.visibilityState === "hidden"` when the docs say this should not occur.

### From the docs:

> If `backgroundThrottling` is disabled, the visibility state will remain `visible` even if the window is minimized, occluded, or hidden.

![image](https://user-images.githubusercontent.com/6835891/86852625-1c85c900-c083-11ea-8654-2a0153a233bf.png)

This happens when I minimize or hide a window. I've tried the following, and the issue persists:

- Creating the window with `webPreferences.backgroundThrottling: false` 
- `win.setBackgroundThrottling(false)`
- `win.webContents.setBackgroundThrottling(false)`

Unfortunately there's no `win.getBackgroundThrottling()` for me to see what the renderer thinks its own state is supposed to be. 

This is creating big issues for us with lag when users show the window for our app, because operations that are intended to happen when the window is hidden don't occur reliably, and instead they need to be done when the user shows the window, which leads to a confusing delay for the user.

**Comment by crypto-dump** [comment]
@Slapbox  is this issue resolved? I also have same problem

**Comment by Slapbox** [comment]
It was still an issue the last time I tested in `18.3.x`

@deepak1556 @codebytere  I don't think this should be closed because #21037 doesn't seem to resolve the issue - unless the documentation I'm relying on was incorrect.

**Comment by hlevring** [comment]
I think this might have finally gotten resolved in V 28.0.0

https://www.electronjs.org/blog/electron-28-0#behavior-changed-webcontentsbackgroundthrottling-set-to-false-affects-all-webcontents-in-the-host-browserwindow

I just had a 10 sec look and could really find the related PR, but it's definitely described as something that should fix this issue I think
