### ISSUE TITLE
 macOS 10.15.1 install global error

### ISSUE THREAD

**Issue by globules-io** [electron/electron#20989]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Installation failed (no previous version installed).
* **Electron Version:**
  7.1.0
* **Operating System:**
   macOS 10.15.1
   npm 6.12.1
   node 10.15.3

### Actual Behavior
Error happens at
```
node install.js
UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdtemp '/usr/local/node_modules/electron/electron-download-okj00y
```

### To Reproduce
sudo npm install -g electron

### Additional Information
npm install -g electron also fails
none of the workarounds found in github worked for me (6.1.3, 6.1.4, 7.1.0, 8..)

**Comment by madbonkey** [comment]
I can't install the `7.x` versions either on macOS 10.14.6, it just hangs at `node install.js` in the postinstall step, doing nothing. `6.1.4` works, and after looking through the changes to `install.js` between 6 and 7 I saw that `@electron/get`'s `downloadArtifact` is now used in place of `electron-download`'s `download`. The issue seems to come from around there.

**Comment by globules-io** [comment]
10 days and nothing? You do not seem to understand we can't even install electron on a Mac? Any update appreciated.

**Comment by susuzheng** [comment]
First run `sudo npm i -g electron@latest ` of course, and then run <code>sudo node /usr/local/lib/node_modules/electron/install.js</code>. This worked for me.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
