### ISSUE TITLE
[Electron 7] window.open incorrectly handles the second parameter

### ISSUE THREAD

**Issue by t57ser** [electron/electron#20996]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
Parameter is being handled according to spec: https://www.w3schools.com/jsref/met_win_open.asp

### Actual Behavior
It is treated as any custom name would

### To Reproduce
In a window execute the following code: window.open("https://www.google.com/", "_blank")
A new window will be created with google. Then execute: window.open("https://www.youtube.com/", "_blank"). Instead of a new window being created, the google window will navigate to youtube.

According to the specs: https://www.w3schools.com/jsref/met_win_open.asp "_blank" should open a new window or tab. My assumption is that this is not being considered and treated the same way as any custom window name would be, therefor navigating instead.

**_self - URL replaces the current page:**
This is also not working, it opens a new window instead

**Comment by t57ser** [comment]
This is working correctly if
```
webPreferences: {
	nativeWindowOpen: true,
}
```
Is this expected?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
