### ISSUE TITLE
webContents.print() Function Not Working For Hindi Language

### ISSUE THREAD

**Issue by jayapal92** [electron/electron#20993]
- Electron version: 7.0.0 

-  Chrome version:  78.0.3905.1

`Source Code`
 
![export_source](https://user-images.githubusercontent.com/14808427/68270789-94c76500-0084-11ea-9939-3cf3138a5a97.png)

const {remote} = require('electron');

/**
 *
 * @param html
 * @param options
 * @returns {Promise<any>}
 * @description
 * Function is used to print the given Html string.
 */
function print(html, options = {silent: false, printBackground: true}){
	const url = `data:text/html;base64,${Buffer.from(html).toString('base64')}`;
	const win = new remote.BrowserWindow({}, url);
	return new Promise((resolve) => {
		win.webContents.print({silent: false, printBackground: true}, resolve);
	});
}

 When i calling  `print(<!DOCTYPE html><html><head></head><body><h3>संपर्क मॉड्यूल हिन्दी</h3></body></html>) ` 

**Expected Behavior**

![expected](https://user-images.githubusercontent.com/14808427/68271323-2388b180-0086-11ea-86d0-c0bcd6acc28c.png)

**Actual behavior**

![actual](https://user-images.githubusercontent.com/14808427/68271352-38654500-0086-11ea-9e4b-b8cd495b3004.png)

`NOTE`

`win.webContents.printToPDF()` also Not supporting for Hindi language

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
