### ISSUE TITLE
Window.show restores a docked window to its previous size and location

### ISSUE THREAD

**Issue by sachetsharma1** [electron/electron#21051]
### Issue Details

When window is docked to a side, calling window.show() on same window restores the window to its previous size and location.

* **Electron Version:**
 5.0.8
* **Operating System:**
  Windows 7
* **Last Known Working Electron version:**
 N/A

### Expected Behavior
Window should remain docked to its original size and location

### Actual Behavior
Window is restored to its previous size and location.

### To Reproduce

1. Dock a window to the right side of the monitor.
2. Call the window.show api from the main process.

**Comment by zona-ciq** [comment]
This issue is affecting us as well and it's happening on both Windows 7 and Windows 10

**Comment by pashvin** [comment]
I tried to use window.focus but that does not solve the issue.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
