### ISSUE TITLE
ipcRenderer.sendTo is invalid in development environment

### ISSUE THREAD

**Issue by smi1lee** [electron/electron#21071]
I was test for communication between two renderer,  I used vue

**Code:**

```js
// in A.vue,  get windowid is 1
<button @click="testPopWindow">testPopWindow</button>

method: {
  testPopWindow () {
    ipcRenderer.sendTo(popWindowid, 'testcommunication ', 'Hello World!')
  }
}

// in B.vue load in popWindow,  get windowid is 2
create () {
  this.$electron.ipcRenderer.on('testcommunication', (event, data) => {
    alert(data)
  })
}
```

when I test in production env, it's OK, 

when I test in development env,

version (4.1.5 and 6.0.2) is invalid

version 2.x is OK
so it's my wrong?

**Comment by smi1lee** [comment]
test 3.0.0 is OK

**Comment by smi1lee** [comment]
test 3.0.0 is OK
test 3.0.8 is failed

**Comment by guhuangjin** [comment]
+1

**Comment by smi1lee** [comment]
> +1

这个可能和电脑有关，至少我还没有找到其它原因，我重装系统之后直接装这个还是不行，但是我同事电脑都是可以的，如果没有用到一些高版本的API的话3.0.0凑合做用吧，如果需要用到高版本的话可以这样直接拉取最新代码，然后直接build也是可以用的，很神奇，我还碰到其它未解决的坑😞

**Comment by guhuangjin** [comment]
好吧 谢谢

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
