### ISSUE TITLE
TypeError: Cannot set property 'Origin' of undefined

### ISSUE THREAD

**Issue by Praveer1981** [electron/electron#21078]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  7.1.1
* **Operating System:**
 Windows 10
* **Last Known Working Electron version:**
  6.12.0

### Expected Behavior
it should not throw below error
`TypeError: Cannot set property 'Origin' of undefined`

### Actual Behavior
its throwing below error when I try to connect to the `box`

### Additional Information
`  const filter = {
    urls: ['https://*.box.com/*']
  }
   session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
    details.requestHeaders['Origin'] = null; 
    details.headers['Origin'] = null; 
    callback({ requestHeaders: details.requestHeaders }) 
  });`

**Comment by vladimiry** [comment]
Currently, electron v7 doesn't properly handle the headers setting/modifying scenarios for the CORS requests, see #20730 and #20923. But it's probably going to be fixed with the next release as the fix #21099 has been recently merged.

**Comment by vladimiry** [comment]
I'd suggest trying recently released 7.1.2 as it got I think related issue #20923 fixed.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
