### ISSUE TITLE
Taskbar overlaps in game window

### ISSUE THREAD

**Issue by sonikdude1000** [electron/electron#21073]
any apps that uses electron causes my taskbar to pop up in game and cover some of the game.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
