### ISSUE TITLE
electron@7.1.1,webContents.print(): Invalid optional callback provided

### ISSUE THREAD

**Issue by 1134506391** [electron/electron#21089]
electron@7.1.1

Uncaught (in promise) Error: webContents.print(): Invalid optional callback provided.
    at WebContents../lib/browser/api/web-contents.js.WebContents.print

```
const options = { silent: true, deviceName: 'My-Printer' }
win.webContents.print(options, (success, errorType) => {
  if (!success) console.log(errorType)
})
```

![image](https://user-images.githubusercontent.com/30287598/68661352-c99c5600-0575-11ea-871b-5a6cbca72fe3.png)

**Comment by xland** [comment]
In my case,
It will correctly go into the callback function.
(I do not have a printer, when I save the pdf file the callback function start to execute)

![image](https://user-images.githubusercontent.com/2980915/68818625-88fd2380-06c0-11ea-8817-75eae40fb21b.png)

**Comment by mnlauaa** [comment]
I got the same error but I am using webview to print

**Comment by xland** [comment]
Whether webview or browserWindow use it's webContents to print.
So they shouldn't be diffrent.

**Comment by ibalaji777** [comment]
any solution for this?

**Comment by jiyarong** [comment]
same error in electron version of 8.4.0

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
