### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by lida1984** [electron/electron#21090]
Uncaught (in promise) Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317)
    at TLSSocket.emit (events.js:203)
    at TLSSocket._finishInit (_tls_wrap.js:792)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606)

**Comment by lida1984** [comment]
> Uncaught (in promise) Error: certificate has expired
> at TLSSocket.onConnectSecure (_tls_wrap.js:1317)
> at TLSSocket.emit (events.js:203)
> at TLSSocket._finishInit (_tls_wrap.js:792)
> at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606)

when i use axios for my request , the bug appear

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by lida1984** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀

I know where the problem is. Server certificate has expired.  Thanks so much.
