### ISSUE TITLE
No event firing on Windows shutdown

### ISSUE THREAD

**Issue by Spenhouet** [electron/electron#21093]
The powerMonitor `shutdown` (https://electronjs.org/docs/api/power-monitor#event-shutdown-linux-macos) event currently is not implemented for Windows: https://github.com/electron/electron/issues/12810

The BrowserWindow `session-end` event (https://electronjs.org/docs/api/browser-window#event-session-end-windows) should fire on shutdown and restart but currently doesn't: https://github.com/electron/electron/issues/15880 (this issue was wrongfully closed).

The BrowserWindow `close` event (https://electronjs.org/docs/api/browser-window#event-close) does only fire on manually closing the window and not on a forced close by shutdown or restart.

The app `window-all-closed` event (https://electronjs.org/docs/api/app#event-window-all-closed) also doesn't fire for shutdown and restart.

This is frustrating. PowerMonitor `shutdown` misses the implementation for Windows and BrowserWindow `session-end` is bugged.
Is there any working way in electron to detect a shutdown and restart on Windows?

**Comment by xland** [comment]
And PowerSaveBlocker can not prevent display sleep.

See #21017 (This issue should not be closed)

**Comment by ari62** [comment]
I havnt tried it but maybe: https://nodejs.org/docs/latest/api/process.html#process_event_exit

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by kics223w1** [comment]
Hi Is there anyone solve this issue, I am facing it.

**Comment by gergof** [comment]
I've made a nodeJS addon that can be used to detect and block the shutdown on windows. You just need to pass the main window's handle: https://www.npmjs.com/package/@paymoapp/electron-shutdown-handler
