### ISSUE TITLE
net module will not emit the end event in renderer process

### ISSUE THREAD

**Issue by xland** [electron/electron#21107]
Electron Version: 6.1.2
Operating System: Windows 10 (1803)

Main process doesn't has this issue.

```js
const { net } = require("electron").remote;
const request = net.request("https://www.cnblogs.com/aggsite/AggStats");
request.on("response", response => {
  let html = "";
  response.on("data", data => (html += data));
  response.on("end", () => console.log(html));   //This event will never be triggered.
});
request.end();
```

**Comment by MarshallOfSound** [comment]
The issue here is the `end` event is actually emitted **before** the `response` callback is called in the renderer.  Because that `response` event is emitted asyncronously from `main --> renderer` by the time the `end` event listener has been added the event has already fired.

This is a fundamental limitation of the `remote` module.  You should not be using the `net` module in the renderer anyway as you can just use the `fetch` API.

I'd reccomend reading https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31 which highlights the problems with `remote`

**Comment by xland** [comment]
AHA!
Thanks!
