### ISSUE TITLE
Hope that the promise of <webview>.print return is not void

### ISSUE THREAD

**Issue by 1134506391** [electron/electron#21106]
Hope that the promise of `<webview>.print` return is not void
like` <webview>.printToPDF`

![image](https://user-images.githubusercontent.com/30287598/68752386-31b66f00-063e-11ea-8c76-6be7a2fc5563.png)

**Comment by codebytere** [comment]
We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
