### ISSUE TITLE
win.unmaximize() Invalid

### ISSUE THREAD

**Issue by MisterAries** [electron/electron#21126]
I updated Windows yesterday，but win.unmaximize() is  Invalid.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
