### ISSUE TITLE
Modo tablet Windows 10 não abre virtual keyboard

### ISSUE THREAD

**Issue by jottasystem** [electron/electron#21120]
Estou desenvolvendo uma aplicacao para ficar em um totem, porem essa aplicacao ira funcionar em modo tablet, mas meu input onde digita o nome não sobe o keyboard virtual do modo tablet
já tentei inumeras coisas, mas nada....

alguém poderia me ajudar por favor, codigo do meu input

Apenas um exemplo mais ou menos de como está o codigo....

  constructor(props) {
    super(props);
    this.state = {
      name: ''
    };
    this.textInput = React.createRef();
  }
 
  componentDidMount() {    this.focus()   }
  focus = () => {    this.textInput.current.focus();  };

        <Form.Control
          onKeyPress={e => this.onKeyPress(e)}
          autoFocus={true}
          maxLength={19}
          onChange={value => this.changeValue('name', value)}
          style={{ color: 'white' }}
          placeholder={'Digite seu nome.'}
          className={styles.inputName}
          type={'text'}
          ref={this.textInput}
        />

abaixo segue o requisito esperado :) 

grato.
        
<img width="1409" alt="Captura de Tela 2019-11-13 às 17 53 58" src="https://user-images.githubusercontent.com/36551379/68820167-347a8980-0669-11ea-9ced-d120913d25ab.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
