### ISSUE TITLE
listen EPERM: operation not permitted 0.0.0.0

### ISSUE THREAD

**Issue by skarl-api** [electron/electron#21124]
electron+express
package is ok
builder is no ok
Error message ‘listen EPERM: operation not permitted 0.0.0.0’

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by ah3nry** [comment]
@skarl-api did you ever get to the bottom of this?
