### ISSUE TITLE
Forced cache invalidation

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#21165]
### Problem Description

1. I'm rendering something like this in my app:

	```html
	<img src="file:///Users/fabio/foo.png">
	```

2. I'm listening for changes to that file.

3. A filesystem change is detected.

4. I want to reload that file from disk, so that the app shows the updated version of it, but without an API for triggering the cache invalidation this may get tricky and messy to do.

### Proposed Solution

I'm not sure what the best solution for this would be, or if this problem is worth adding additional APIs for, but since inside of Electron we kind of control the browser maybe an API for forcing cache invalidation of arbitrary urls could be added? With that I think I would just need to invalidate the urls I want and recreate the DOM node that may host such urls to force a reload of them.

I'm not sure this is a good idea, especially as if at some point I want my app to work in the browser I would have to resort to something else anyway, but I thought I'd mention it.

### Alternatives Considered

I could force a cache invalidation in the "usual" way by appending a query argument to urls, but if the app is not generating the url itself, e.g. they may be provided by the user, the app would have to detect these sorts of links and update them, which may not be trivial nor performance insignificant to do.

**Comment by vladimiry** [comment]
A few quick ideas:
- Tweaking the cache control headers for specific requests in the webRequest.onHeadersReceived handler.
- Listening for changes to the file like you do in the ipcMain process. Then on change event triggered you send message to the renderer process with image content encoded into the data-uri format (like `data:image/png;base64,iVBORw0KGgoAA...`) and then change in the DOM the image url to the received data url. If moved to a browser you could use web sockets channel instead of IPC used in @electron.

**Comment by MarshallOfSound** [comment]
`file://` URLs are not cached.  If you watch that file for changes and just reload it, the new contents will be loaded.

Note that doing `img.src = theSameURL` will not trigger a change.  You would have to provide a different URL for chromium to trigger a refetch.
