### ISSUE TITLE
Linux: save dialog with filter no longer returns file extension

### ISSUE THREAD

**Issue by bpasero** [electron/electron#21170]
### Issue Details

* **Electron Version:**
  * 6.x
* **Operating System:**
  * Ubuntu 18
* **Last Known Working Electron version:**
  * 4.x

### Expected Behavior
A save dialog with filter extension adds that to the path.

### Actual Behavior
The extension is no longer added.

### To Reproduce
```ts
const { app, BrowserWindow, dialog } = require('electron')

let mainWindow = null

app.on('ready', () => {
  mainWindow = new BrowserWindow({ height: 600, width: 600 })

  // Show an "Open File" dialog and attempt to open
  // the chosen file in our window.
  //
  // If you provide a callback, the method will be asynchronous,
  // but in thise case, we'll just use the synchronous variant.
  const file = dialog.showSaveDialogSync({
    title: 'Hello!',
    defaultPath: '<some folder>',
    filters: [{extensions: 'code-workspace'}]
  });

  console.log(file);

  mainWindow.loadURL(`file://${file}`)
})
```

//cc @deepak1556

**Comment by bpasero** [comment]
More info in https://github.com/microsoft/vscode/issues/84818. In VSCode we open a save dialog without providing a file name, but with a folder as location and a filter extension. After the user has picked, the extension is not added to the resulting path.

This worked in 4.x.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by deepak1556** [comment]
Unable to repro with current stable.
