### ISSUE TITLE
how to switch to other active native app from electron

### ISSUE THREAD

**Issue by caprice** [electron/electron#21197]
tru the following way, I got all the window sources:

desktopCapturer.getSources({types: ['window', 'screen']}, function (error, sources) {
    for (let source of sources) {
        console.log("Name: " + source.name);
    }
});

and all the sources are displayed on a vue window like below screen shot,
![image](https://user-images.githubusercontent.com/2981114/69140067-b8ff5900-0afc-11ea-8b05-7de8c57f5d43.png)
**when i click the 'publish.html' item, it is expected to open publish.html window, can electron do this job. if yes, could you show the code? I will truly appreciate your timely help.**

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
