### ISSUE TITLE
Multiple webviews load websites incorrectly.

### ISSUE THREAD

**Issue by Stanlyhalo** [electron/electron#21208]
I have a project I'm making, and if I load duckduckgo.com on one, it loads correctly with the black theme, auto complete searches, top right nav buttons, but when I load duckduckgo.com through a second webview, it loads a white theme, does not have the nav buttons, and does not autocomplete. Also when it loads roblox.com, it loads a grayish background-color with a scrollbar and that's it, but if I load roblox.com/home, it loads the games, but does not have upper right nav buttons. How do I fix this, or is this a electron problem, and if so, would running a proxy server above each webview with the webview has a child tag fix this?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
