### ISSUE TITLE
Frameless Window -webkit-app-region:drag question

### ISSUE THREAD

**Issue by iFurySt** [electron/electron#21238]
[https://github.com/electron/electron/issues/15386](https://github.com/electron/electron/issues/15386)

This problem has always existed.
Hope to get help, thx :)

` 
 "devDependencies": {
    "electron": "^7.1.1"
  }
`

**Comment by momakes** [comment]
In order to get help, you should stick to the issue template, so we can correctly understand your case and help. Just pointing to an old issue doesn't provide enough information about _your_ case.

if you create a new issue and fill out the template, ideally provide a minimal repo, or a video, your electron version, exact code you're using, then others and I will be able to help out!

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
