### ISSUE TITLE
Microphone Access in Electron Browser Window in WindowsOS

### ISSUE THREAD

**Issue by PRASHANT1104** [electron/electron#21261]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 v7.1.2
  
* **Operating System:**
  * Windows 10(1809)
* **Last Known Working Electron version:**
  * Didnt work in earlier version as well

### Expected Behavior
Microphone access for electron browser window in Windows10( docs have support for MacOS).

### Actual Behavior
I cannot access microphone in my electron app. I embedded a url in my index.html(this is loaded in Browser Window) , which requires microphone . The web url is working fine in browser and voice is being recorded correctly by microphone , but this isnt happening for electron window . 

### To Reproduce
I am using an url which converts your speech to text. Even if you load google.com and try to use microphone for search it says no Internet connection.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
