### ISSUE TITLE
Electron screen Display object's internal attribute is useless.

### ISSUE THREAD

**Issue by xland** [electron/electron#21274]
Win 10 , Electron 6.1.5 

My computer is a laptop，an external display is connected through HDMI.
So my computer has two displays.
`screen.getAllDisplays`  shows that all of them are `internal:false`.
but the doc says:
> internal:true for an internal display and false for an external display

```js
let remote = require("electron").remote;
let screens = remote.screen.getAllDisplays();
console.log(screens);
```

**Comment by xland** [comment]
My computer is a laptop

**Comment by Imior** [comment]
Mac has the same problem.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
