### ISSUE TITLE
Mircotaskscope in the renderer interferes with debugging async/await

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#21288]
**Electron Version:** 6-1-x, 7-1-x, 8-xy

### Expected Behavior

Devtools should perform normally without crash

### Actual Behavior

Renderer crashes with following,

https://gist.github.com/deepak1556/29458392e72d01c097b822cbb36848f9 -> interesting frame starts from 33

### To Reproduce

https://gist.github.com/deepak1556/f9ce7fd4d695361f1568c787affa3795

This originally surfaced in https://github.com/microsoft/vscode/issues/83994 as a different issue, this is just one example based on the task event loop was processing when we originally saw the crash but we have explicit Microtaskscope spread out in a couple of places in the renderer and depending on the task queue at the time of debugger pause, they will cause a similar issue.

/cc @zcbenz

**Comment by zcbenz** [comment]
The `blink::PromiseRejectHandlerInMainThread` is called when promise is rejected, and crash happened inside it because blink could not could a valid DOM window at current scope.

From the crash report, it seems that we need to make `electron::EmitIPCEvent` call JS via blink.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by deepak1556** [comment]
Can confirm the issue doesn't repro with Electron >=11
