### ISSUE TITLE
Print on rapberry Pi 3 error

### ISSUE THREAD

**Issue by flyxlee** [electron/electron#21330]
### Issue Details

* **Electron Version:**
  * 6.1.5
* **Operating System:**
  * Raspbian GNU/Linux 9.8 (stretch)
* **Last Known Working Electron version:**
  *unKnown

### Expected Behavior
Can show the select printer dialog

### Actual Behavior
the application close itself,and show the error:
**Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.**

### To Reproduce
the code is the same as  the sample which refer to the guide doc

### Screenshots
![image](https://user-images.githubusercontent.com/10684063/69852211-adf7b600-12be-11ea-8d4e-48ac8736d964.png)

**Comment by ckerr** [comment]
Looks like a regression related to https://github.com/electron/electron/issues/12423

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
