### ISSUE TITLE
Electron doesn't support proprietary native node modules?

### ISSUE THREAD

**Issue by anurbol** [electron/electron#21337]
I am sorry for not following the issue templates, because they seem not to fit this. 

So I have a private native node addon, and I don't have its sources. Is it true that I can't use it reliably for electron-based VSCode because every version of VSCode have different electron versions, and different electon versions require that the native addon must be rebuilt for that version specifically, which is impossible because I don't have the sources to do that rebuilding?

I've read that this is because different electron versions may use different V8 versions, but then, why the module works fine with different node versions? I know there may be some technical reasons but are they big enough for making this questionable decision?

**Comment by MarshallOfSound** [comment]
> I've read that this is because different electron versions may use different V8 versions

This is accurate and one of the main reasons you need to rebuild native modules specifically for Electron

> why the module works fine with different node versions

Without seeing that native module there is no way to know, could be built using napi, could have multiple pre-built binaries, 🤷‍♂ impossible question

> I know there may be some technical reasons but are they big enough for making this questionable decision?

This isn't a "decision", we have no choice, we target a different version of V8 to the version of Node we embed + different dependencies (E.g. boringssl instead of openssl).  We can't and won't change the way this works.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by anurbol** [comment]
@MarshallOfSound Thanks so much for explaining, now it's a little more clear (though I am still sad).
