### ISSUE TITLE
Electron app is taking long time in first launch or after restarting machine.

### ISSUE THREAD

**Issue by BONDbATIF** [electron/electron#21335]
### Issue Details

* **Electron Version:3.0.7, 5.0.8, 7.1.2
  
* **Operating System: Windows 7/ Windows 10 /macOS 10.13.6/ macOS 10.14.6

### Expected Behavior
The first launch takes a long time to electron window comes up compare to the second launch and so on.
### Actual Behavior
The application launch should not take a long time in the first launch or after the restarting of the machine.

### To Reproduce
Scenario 1:
install electron app(release build from electron packager).
click on xyx.exe(electron.exe) or launch from cmd/terminal take  more than 25 sec to launch electron window 

Scenario 2:
Restart the machine and immediately try to  click on xyx.exe(electron.exe) or launch from cmd/terminal take longer time then scenario 2

Note: The macOS launch is batter than windows. None of the electron update this issue resolved.

**Comment by momakes** [comment]
Without a minimal reproduction repository, it's almost impossible to help you!

**Comment by BONDbATIF** [comment]
@momakes updated

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
