### ISSUE TITLE
More details on manual distribution

### ISSUE THREAD

**Issue by Danissss** [electron/electron#21340]
System: Ubuntu 16.04. 64-bit machine.
Hi, I tried the manual distribution then I got lost. I can package through `electron-packager`, but I want to try manual too,
After download the prebuilt electron https://github.com/electron/electron/releases, here are the files without `npm install`:
```
appveyor.yml             DEPS                    filenames.hunspell.gni  SECURITY.md                typings
azure-pipelines-woa.yml  docs                    lib                     shell                      vendor
build                    docs-translations       LICENSE                 spec                       vsts-arm32v7.yml
buildflags               electron_paks.gni       native_mate             spec-main                  vsts-arm64v8.yml
BUILD.gn                 electron_resources.grd  npm                     tools                      vsts-arm-test-steps.yml
chromium_src             electron_strings.grdp   package.json            tsconfig.default_app.json  yarn.lock
CODE_OF_CONDUCT.md       ELECTRON_VERSION        patches                 tsconfig.electron.json
CONTRIBUTING.md          filenames.auto.gni      README.md               tsconfig.json
default_app              filenames.gni           script                  tsconfig.spec.json

```
I couldn't find `resources/` folder like this guide demonstrates https://electronjs.org/docs/tutorial/application-distribution . Should I create the `resources/` folder and put my app code in resources folder like 
```
electron/resources/app
├── package.json
├── main.js
└── index.html
```
Last, what does it mean by execute `electron` (something like this `npm install` or `./electron`?

Thanks!

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
