### ISSUE TITLE
Accelerator Left and Right Shift

### ISSUE THREAD

**Issue by stefnotch** [electron/electron#21348]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Keyboards have two `Control` and `Shift` keys, one on each side. Sometimes they also have two `Alt` keys. However, the [Electron accelerator API](https://electronjs.org/docs/api/accelerator) doesn't seem to have support for distinguishing between those keys.

### Proposed Solution

I'd suggest adding left and right versions of the aforementioned keys to the accelerator API such as `LeftControl`, `RightControl`.

### Alternatives Considered

Using different shortcuts.

### Additional Information

I stumbled upon this while searching for a shortcut for a [launcher](https://github.com/oliverschwendener/ueli) that doesn't conflict with existing ones.

**Comment by codebytere** [comment]
This is unfortunately not possible at present since Chromium itself is responsible for modifier acceleration, and it registers both left and right as the same for Control, Shift, etc. You're more than welcome to open a crbug.com for it, and then at some point in the indeterminate future we could add support for it once Chromium does.
