### ISSUE TITLE
Maximizing/Minimizing windows with an opacity causes window to flash

### ISSUE THREAD

**Issue by adarshdamodaran** [electron/electron#21366]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v7.1.2
* **Operating System:** Windows 10 Pro 64 bit  
* **Last Known Working Electron version:**

### Expected Behavior
If the BrowserWindow has an opacity value set, maximizing and minimizing should occur with the window using the same opacity value.

### Actual Behavior
If the BrowserWindow has an opacity value set(between 0 and 1), maximizing and minimizing causes the window to flash before the resize occurs.

Printing the opacity value showed that the opacity value does not actually change during the maximize and minimize events of the browser window.

### To Reproduce
https://gist.github.com/adarshdamodaran/9acbe28b31bf1210d0061689220465a7

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
