### ISSUE TITLE
different NODE_MODULE_VERSION ?

### ISSUE THREAD

**Issue by xiaoqufengdi** [electron/electron#21391]
node_modules\usb\build\Release\usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73.

window 10
electron v6.0.7
node v12.10.0
but i cannot fount  that node  NODE_MODULE_VERSION 73, I try to .\node_modules\.bin\electron-rebuild.cmd, it doesn't work?

**Comment by vladimiry** [comment]
Try to remove `node_modules\usb\build` dir and `./node_modules/prebuild-install` dir if you have it (so the prebuid-binary doesn't get dowloaded if provided), then trigger building from sources.

**Comment by xiaoqufengdi** [comment]
> Try to remove `node_modules\usb\build` dir and `./node_modules/prebuild-install` dir if you have it (so the prebuid-binary doesn't get dowloaded if provided), then trigger building from sources.

it doesn't work

**Comment by vladimiry** [comment]
It's supposed to work if you got the native code successfully compiled (not downloaded as a prebuild binary since sometimes such binaries are wrong), so most likely you are doing something wrong (for example make sure you are actually compiling from the sources and running the code as electron app but not as nodejs script). Anyway, it's better to post such issues on resources like StackOverflow or Electron's Slack channel.

**Comment by xiaoqufengdi** [comment]
> It's supposed to work if you got the native code successfully compiled (not downloaded as a prebuild binary since sometimes such binaries are wrong), so most likely you are doing something wrong (for example make sure you are actually compiling from the sources and running the code as electron app but not as nodejs script). Anyway, it's better to post such issues on resources like StackOverflow or Electron's Slack channel.
After i delete the dir, and then .\node_modules\.bin\electron-rebuild.cmd
it's work , thank you very much.

**Comment by vladimiry** [comment]
Let's close the issue then :)
