### ISSUE TITLE
Debugger.restartFrame inspector request fails

### ISSUE THREAD

**Issue by roblourens** [electron/electron#21401]
Electron version: 6.1.5

- Debug an electron app with the chrome devtools
- Hit a breakpoint
- Right click the frame in the callstack and click "Restart frame"
- Nothing happens, but if you then "step in", execution will jump back to the top of the frame

If you watch the devtools inspector traffic, you can see that the restartFrame request failed. Typically it would succeed then the devtools would send a stepIn event automatically.

![image](https://user-images.githubusercontent.com/323878/70266054-9bfb9480-1750-11ea-8229-42bd4827260a.png)

FYI @deepak1556

**Comment by roblourens** [comment]
Oops, this works in Electron 7

**Comment by deepak1556** [comment]
I am reopening, the fix for this came from chromium bump, I will try to backport it for electron 6 for stable. Also better to close this issue once electron 7 moves to insiders.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
