### ISSUE TITLE
crash when using webview onBeforeRequest redirect

### ISSUE THREAD

**Issue by javaxiu** [electron/electron#21455]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.4
* **Operating System:**
  * MacOS 10.15.1
* **Last Known Working Electron version:**
  * 6.1.5

### Expected Behavior
```typescript
webRequest.onBeforeRequest(() => {
    callback({redirectURL: 'about:blank'})
})
```
callback will go to about:blank  empty page

### Actual Behavior
crash when calling callback

### To Reproduce
```javascript
window.onload = () => {
  const div = document.createElement('div');
  div.innerHTML = '<webview id="webview" src="http://google.com/" style="width: 100vw; height: 100vh;"></webview>'
  document.body.appendChild(div);
  const webview = document.getElementById('webview')
  webview.addEventListener('dom-ready', () => {
    webview.getWebContents().session.webRequest.onBeforeRequest((details, callback) => {
      try {
        if (details.url.startsWith('https://ads.google.com/')) {
          callback({ redirectURL: 'about:blank' });
          return;
        }
      } catch (e) {
      }
      callback({});
    });
    webview.addEventListener('did-navigate', (e) => {
      console.log(e.url);
    });
  })
}
```

a minimal proj git is here

```sh
$ git clone https://github.com/javaxiu/electron-onbeforerequest-example
$ npm install
$ npm start || electron .
```

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by javaxiu** [comment]
@codebytere  i've update issue description,  including a minimal proj git.  could you help me find out the crash reason  please?  thanks a lot

**Comment by codebytere** [comment]
Could you please include a crash report?

**Comment by javaxiu** [comment]
![image](https://user-images.githubusercontent.com/4281225/72066836-8c0d3c80-331c-11ea-9184-5dc30949ae2a.png)
i am trying to get the crash report,  sorry but... is it an other issue?  I've also invoke this function in main process as below
```typescript
const { crashReporter} = require('electron');
app.on('ready', () => {
  const report = crashReporter.getLastCrashReport();
  console.log(report);
})
```
and the same error output:  `call_failedError processing argument at index 0, conversion failure from undefined`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
