### ISSUE TITLE
Same Code Base but two electron react boilerplate Applications

### ISSUE THREAD

**Issue by SachinJeremiahL** [electron/electron#21482]
I have built an desktop application using electron-react-boilerplate, at the same time a requirement came, they want same application but in different name. so now i have two applications in same code base(little changes only).but the problem is when i installed both applications in a same computer,any one folder which created first in C:\users\appdata will be a local storage for both applications.i've used react localStorage for store different data for each applications. help me to solve. thanks

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
