### ISSUE TITLE
SameSite by default cookies

### ISSUE THREAD

**Issue by ronag** [electron/electron#21509]
It seems google has started to automatically enable the "SameSite by default cookies" option. Is there anyway to explicitly disable this in electron?

![Screenshot 2019-12-13 at 13 15 00](https://user-images.githubusercontent.com/3065230/70799671-96cec300-1daa-11ea-8c41-9f3d84cdfb93.png)

Refs: https://github.com/google/google-api-javascript-client/issues/585

**Comment by jsheffers** [comment]
Looks like this will be possible with 11?
https://github.com/electron/electron/issues/24225

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
You can try `--disable-features=SameSiteByDefaultCookies`, but we'll only support this as long as Chromium does, and we can't make any guarantees about how long Chromium will support it.

**Comment by jsheffers** [comment]
This doesn't seem to have any effect ☝️
