### ISSUE TITLE
Get unexpected 'navigated to'  after create table with knex on Windows.

### ISSUE THREAD

**Issue by zotille** [electron/electron#21502]
My App always get navigated to http://localhost:3000 after create a Knex table on Windows.
The code is sth like:
![image](https://user-images.githubusercontent.com/38178024/70768734-71898700-1da1-11ea-89be-b70f201f3ead.png)
After create a table, I got 
![image](https://user-images.githubusercontent.com/38178024/70768806-d644e180-1da1-11ea-9ce4-7890abca3273.png)
on my console, But no error reported. And the table was created successfully.
I have tried start electron with admin account, but it didn't work.
And everything went fine on my macbook,  Anyone can tell me how i can solve this problem?...

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
