### ISSUE TITLE
`net.request(...)` is not API-compatible with Node.js

### ISSUE THREAD

**Issue by szmarczak** [electron/electron#21517]
The [documentation](https://electronjs.org/docs/api/net#netrequestoptions) says:

> The API components (including classes, methods, properties and event names) are similar to those used in Node.js.

While the [API](https://electronjs.org/docs/api/client-request) is nowhere compatible with Node.js, I see two solutions here:

1. Rewrite the code so it is compatible.
2. Mention in the docs that it is **NOT** compatible (aka "abandon")

Every new release [Got](https://github.com/sindresorhus/got) needs monkey-patching because there's always something incompatible.

[Electron in a nutshell :trollface:](https://github.com/sindresorhus/got/issues/899#issuecomment-555330649)

**Comment by MarshallOfSound** [comment]
Cutting to the point to maybe get this fixed.

This issue is fundamentally useless to us, if there is an API mis-match between `net` and `http.request` then raise an issue for that specific mismatch and it will be triaged appropriately.  There was a dramatic shift in network code in Electron 7 due to network servicification in Chromium so anything new in Electron 7 is probably directly related to that.

> Electron in a nutshell :trollface:

This is unnecessary, please be sure to communicate in line with our CoC on this repository.

I'm going to close this issue out, please raise individual issues for the actual API differences.  If we aren't informed of the differences, there is no chance we are going to fix them. 😄

**Comment by szmarczak** [comment]
> This is unnecessary, please be sure to communicate in line with our CoC on this repository.

[Firstly, I would love to see your team follow it](https://github.com/electron/electron/issues/11787#issuecomment-565617635) :wink:

> If there is an API mis-match between net and http.request then raise an issue for that specific mismatch and it will be triaged appropriately.

So, if I'm correct, your team is too lazy to look at the differences between the Electron API and Node.js API. This violates CoC in these statements:
> Focusing on what is best for the community
> Other conduct which could reasonably be considered inappropriate in a professional setting

Please don't make me open yet another ~100 issues. For example, these things are expected to work but they don't:

- redirects don't emit `response` event; there's `redirect` event, all redirects are done via the same ClientRequest instance
- there's no `request.socket` property
- you cannot specify a `content-length` header
- you cannot set timeouts on specific events, like done [in here](https://github.com/sindresorhus/got/blob/master/source/utils/timed-out.ts)
- body is automatically decompressed, no option to disable that, this is very misleading as `content-encoding` response header is still present,
- does not support the `lookup` option,
- no Agent support
