### ISSUE TITLE
Allow accelerators to be modifier-only

### ISSUE THREAD

**Issue by abejfehr** [electron/electron#21518]
I would like the ability to apply a listener to a "command key down" type of event.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Right now, specifying `CmdOrCtrl` claims that it's not a valid accelerator.

### Proposed Solution

I'd like to propose that "CmdOrCtrl" should be a valid accelerator for a global/local keyboard shortcut.

### Alternatives Considered

I've tried adding a window keydown listener that checks for `event.metaKey` but that's actually problematic for my app since the entire app is an iFrame, which swallows all events and doesn't propagate them down to the document.

I'd like to make an app where:
1. someone can navigate to a YouTube video (fullscreen iFrame in my document)
2. hold in the command key
3. use mousewheel to scroll and change window opacity

What I could do if command was a valid accelerator:
1. listen for command
2. on command pressed, add a div to the DOM that goes over the iFrame to capture mousewheel events

**Comment by codebytere** [comment]
Unfortunately this is a byproduct of Chromium and not something we're currently capable of fixing, as it would entail assuming more maintenance burden for Menus than we feel comfortable assuming. A fundamental assumption of Chromium is that a modifier exists _alongside_ a non-modifier key, and so a significant part of the codebase would need to be rewritten in order to upend this assumption. As such, i'm going to close this as a wontfix, but should something change i'm happy to look further.
