### ISSUE TITLE
LoadUrl is not loading the angular route in child window

### ISSUE THREAD

**Issue by chandrakanthi07** [electron/electron#21510]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Reproducible with version :6.0.12
  * 
Windows 7&8/Ubuntu/Mac Seirra
  * 
Working in version : 4.2
  * 

### Expected Behavior
The angular route should be loaded in the child window

### Actual Behavior
The child window displays only the index.html file content

### To Reproduce
git clone https://github.com/chandrakanthi07/sample-angular-electron
npm install
npm start
Click on text 'Open' in the app.

**Comment by chandrakanthi07** [comment]
Hi, Please let me know when this will be looked in to.

**Comment by chandrakanthi07** [comment]
Hi @sofianguy 
I was able to get it working, by enabling nodeintegration for the childwindow.
Please let me know if it can be achieved using the preload flag.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
