### ISSUE TITLE
BrowserView - set referrer and align bottom right corner

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#21527]
Hello,

How to set referrer and align bottom right corner for [BrowserView](https://electronjs.org/docs/api/browser-view)

In [Webview tag](https://electronjs.org/docs/api/webview-tag) it was as simple as

```html
<webview src="https://www.github.com/" httpreferrer="http://google.com"></webview>
webview { position: absolute; bottom: 0; right: 0 }
```

But Webview is deprecated now.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
