### ISSUE TITLE
Text with bright colors flickers when mousing over unrelated UI elements

### ISSUE THREAD

**Issue by raethkcj** [electron/electron#21533]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I tried reporting this to Discord, but they say it's an Electron bug:
  - Sanjay#0540 | Not a discord-related bug, this is a electron bug (what discord is run on, meaning discord has no control over it) that has to do with certain vibrant colors
  - Encrium#0004 | NAB, Electron bug, discord has no control over this
  - ryan#0570 | This is not a Discord bug, but an issue with electron that Discord cannot fix.

* **Electron Version:**
I tried `process.versions.electron` but it seems Discord disables that.
Discord Version: [BUILD INFO] Release Channel: stable, Build Number: 51469, Version Hash: f0631d8e9918d740411b887e93531b3afbf604a4
* **Operating System:**
Windows 10 Pro Version 10.0.18363 Build 18363
* **Last Known Working Electron version:**
N/A

### Expected Behavior
Brightly colored text should maintain a regular font weight

### Actual Behavior
The colored text appears to flicker between regular and bold font weights (the CSS properties do not change). 

### To Reproduce
In any Discord server:
- Create a user role (or set your name) with the color #ff05ea (other bright colors sometimes work too, but this one was easy to reproduce for me)
- Send a message in any channel so that the newly colored username appears there
- Move the mouse cursor between the list of servers and the list of channels 
- Observe the brightly colored text flicker

### Screenshots
https://youtu.be/890I7_pTcqE

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
