### ISSUE TITLE
Can not install electron application at multiple locations in windows OS

### ISSUE THREAD

**Issue by harshkoralwala** [electron/electron#21534]
Hello,

I want to install my electron application at multiple locations in windows e.g (d:\folder1,d:\folder2,e:\folder3 ).

But while installing the application at the second time removes previous installation files though the second time installation directory is different.

e.g first time application installed at d:\folder1
   while installing the application at d:\folder2 removes files from d:\folder1.

So, as a result, I can not install same application at multiple locations

My package.json looks like:

>{
  "name": "testApp",
  "version": "0.0.1",
  "main": "main.js",
  "author": {
    "name": "testApp",
    "email": "admin@testApp.com"
  },
  "homepage": "https://www.testApp.com/",
  "build": {
    "appId": "testApp001",
    "compression": "maximum",
    "productName": "testApp",
    "win": {
      "target": "NSIS",
      "icon": "resources/testApp_final.png"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "resources/testApp_1024.ico",
      "installerSidebar": "resources/left-panel.bmp",
      "uninstallerSidebar": "resources/left-panel.bmp"
    }
  }
}

So how can I enable to install the application at multiple locations in windows os?

Thanks in advance.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
