### ISSUE TITLE
electron NO_SUPPORTED_PROXY error

### ISSUE THREAD

**Issue by Linch1** [electron/electron#21535]
* **Electron Version:**
  * v6.1.5
* **Operating System:**
  * Ubuntu 19.10

### Expected Behavior
I have the main electron window with a button on it, each time that the user clicks the button depending by some settings the app will generate a new window with (or not) a proxy on it, If the generated window has to havea proxy I do the following:

- 1) Take the new generated window session
- 2) call the `setProxy` method
`this.proxy_window.webContents.session.setProxy({  proxyRules: `socks5://${proxy}` })`
where the proxy viariable respects the following format `user:pswd@ip:port`.
- 3) The poroxy is correctly setted.

### Actual Behavior
The `setProxy` method return this error

```
Uncaught (in promise) Error: ERR_NO_SUPPORTED_PROXIES (-336) loading 'https://www.google.com/'
    at rejectAndCleanup (/home/pero/wihype_pro/node_modules/electron/dist/resources/electron.asar/browser/navigation-controller.js:67)
    at WebContents.failListener (/home/pero/wihype_pro/node_modules/electron/dist/resources/electron.asar/browser/navigation-controller.js:77)
    at WebContents.emit (events.js:200)
```

**Comment by 1c7** [comment]
Hi, I want to implement a similar feature like yours, did you solve the problem?

**Comment by Linch1** [comment]
Not yet, i think that the problem is caused Becouse of the proxy auth

**Comment by 1c7** [comment]
@Linch1 
Check out this: 
https://github.com/electron/electron/issues/21050

![image](https://user-images.githubusercontent.com/1804755/71446895-8253d880-2763-11ea-87a8-f50ed3d93315.png)

Maybe it's helpful, I am not sure.

**Comment by Infante** [comment]
hey did you end up getting this?

**Comment by Linch1** [comment]
@Infante Actually i didn't

**Comment by arslanmughal99** [comment]
Facing same issue with [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) however my proxy does not required auth .

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
