### ISSUE TITLE
`page-title-updated` sometimes not updating

### ISSUE THREAD

**Issue by sentialx** [electron/electron#21584]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta.5
* **Operating System:**
  * Windows 10 (but this may apply to other OSs too)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
The title in the tab should update.

### Actual Behavior
When going for example to a GitHub repository then going to some directory and going back, the title does not update using `page-title-updated`. However, in my tab preview which uses `getTitle` method, it gets the proper page title.

### To Reproduce
https://gist.github.com/bd87de6508e5f4ba626e53b09272c72d

### Screenshots
![xddd2](https://user-images.githubusercontent.com/11065386/71204558-afeedc80-22a0-11ea-9612-d77c9c89dcf1.gif)

![image](https://user-images.githubusercontent.com/11065386/71206225-4f619e80-22a4-11ea-84f6-c83b3a418499.png)

**Comment by sentialx** [comment]
The event also isn't being fired when navigating to a PDF file.

**Comment by panther7** [comment]
The `page-title-updated` is not fired if webpage has not `title` element.

Tested on v11.1.1

**Comment by sugrace** [comment]
I think Event page-title-updated is not fired an check if the did-navigate-in-page event has occurred.
In my case, I solved the problem by bringing the tick-navigate-in-page event to webview.getTitle() and webview.setTitle()

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
