### ISSUE TITLE
Worker slowdown updating from 4.2.8 to 7.1.2

### ISSUE THREAD

**Issue by Mr-Wallet** [electron/electron#21582]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * 4.2.8

### Behavior
When sending a large chunk of data back from a Worker (`nodeIntegrationInWorker: true`) to my renderer process, it takes 1.5-2.5 times as long on 7.1.2 compared to 4.2.8 from the worker finishing its work for the renderer to receive the data. This slowdown seems to be roughly proportional to the size of the data.

### To Reproduce
Send back from a Worker an array with ~10k small objects (just a string property on them should suffice). It should be perceptibly slower on 7. Using `performance.now()`, it's easy to see that the extra time is being added between the worker finishing its work and the render thread receiving the data.

Before I build a reproducing repository, I just wanted to know if perhaps there was something I missed, such as a known issue or a recommended migration. I know there's been a lot of murmuring around getting rid of `remote` - are there any notable changes to IPC that might have changed the best way to performantly send data?

Update: we discovered that transferring a JSON through an ArrayBuffer (in the 2nd argument to [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage)) gives us the same performance as we saw using normal messages in 4.2.8. This works perfectly fine for us, but it's still not clear to me what's caused the slowdown.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
