### ISSUE TITLE
File input crashes the app on Ubuntu 19.10

### ISSUE THREAD

**Issue by MechoshiPuhanaga** [electron/electron#21599]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Ubuntu 19.10 x64
* **Last Known Working Electron version:**
  * n.a.

### Expected Behavior
Open the file system dialog after clicking the input

### Actual Behavior
The app crashes. The result is the same when calling showOpenDialog from main.
On Ubuntu 18.04. everything works fine.

**Comment by ckerr** [comment]
I'm running 19.10 x64 and would be happy to test, but I don't know what "open the file system dialog after clicking the input" means -- e.g. what input am I supposed to be clicking?

I don't understand what this bug is saying. @MechoshiPuhanaga, would it be possible to write a simple "hello world" app, such as something forked from https://github.com/electron/electron-quick-start, and paste it here so that I can test **exactly** what you're testing?

**Comment by MechoshiPuhanaga** [comment]
Hi, @ckerr 
I'm talking about clicking on `<input type="file" id="file-input" name="file-input" accept="image/jpeg">`. 
The expected behavior is to get the file system dialog opened and be able to select a file from your file system. On 19.10 the app crashes. But on 18.04 - this works as expected.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
