### ISSUE TITLE
cannot find where to write header json for asar compile for electron

### ISSUE THREAD

**Issue by xiao2013** [electron/electron#21609]
I would like to change the header json file for asar compilation. I use text file to open the asar with the newest electron app. Here is what I have seen:
`XTN{"files":{"default_app.js":{"size":3135,"offset":"0"},"icon.png":{"size":73801,"offset":"3135"},"index.html":{"size":11901,"offset":"76936"},"main.js":{"size":5852,"offset":"88837"},"octicon":{"files":{"build.css":{"size":88,"offset":"94689"},"gear.svg":{"size":457,"offset":"94777"},"gift.svg":{"size":788,"offset":"95234"},"gist.svg":{"size":321,"offset":"96022"},"mark-github.svg":{"size":691,"offset":"96343"},"star.svg":{"size":202,"offset":"97034"}}},"package.json":{"size":75,"offset":"97236"},"preload.js":{"size":1730,"offset":"97311"},"styles.css":{"size":2379,"offset":"99041"}}}`

I am new to electron, and even if I have looked at the code structure and find 
`archive.cc` and `asar.js`. I feel that I still cannot change the headers of the `default_app.asar`. Is there any hint where I can look at the part that can change the headers? at least write a phrase `hello world?` in the beginning.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
