### ISSUE TITLE
NotificationActions - how to test on local app

### ISSUE THREAD

**Issue by mjurkowski** [electron/electron#21607]
Hi, I have found the information app should be signed and set NSUserNotificationAlertStyle to show notification actions, but how can I test the app using `npm start` - the local app is not singed?

Any workaround?

Ref. https://electronjs.org/docs/api/structures/notification-action#button-support-on-macos

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
