### ISSUE TITLE
Notification (main process) doesn't emit click and show events.

### ISSUE THREAD

**Issue by pjebs** [electron/electron#21610]
OS: macOS High Sierra
Electron: v6.1.7

Notifications (Main process) work perfectly on Mac EXCEPT they don't seem to emit events.

```js
const n = new Notification({
    body: 'Lorem Ipsum Dolor Sit Amet'
  });

console.log(n.eventNames()) // displays []

  n.on("click", () => {
// Doesn't work
    console.log('Notification clicked')
    app.quit();
  });

  n.show();

```

I am only running on Dev.

**Comment by pjebs** [comment]
Perhaps related to: https://github.com/electron/electron/issues/18746

**Comment by pjebs** [comment]
Doesn't work on electron 7 either

**Comment by codebytere** [comment]
@pjebs i think this may be due to issues with either your machine or the location you're looking for console output, because when i (running 6.1.7 and Mojave, identical to you) run the following in Fiddle:

```js
const {app, BrowserWindow, Notification} = require('electron')

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true
    }
  })

  mainWindow.loadFile('index.html')

  const n = new Notification({
    body: 'Lorem Ipsum Dolor Sit Amet'
  })

  n.on("click", () => {
    console.log('Notification clicked')
    app.quit()
  })

  n.show()

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

i experience no issues and see the output as i should on click:
<img width="304" alt="Screen Shot 2019-12-30 at 4 56 26 PM" src="https://user-images.githubusercontent.com/2036040/71606404-5a7ac100-2b25-11ea-9130-4e5a12f0d733.png">

**Comment by pjebs** [comment]
What does `console.log(n.eventNames())` display for you?

**Comment by codebytere** [comment]
@pjebs updated original snippet to include `n.eventNames()`, and when i run that (the updated version) i see:

<img width="273" alt="Screen Shot 2019-12-30 at 6 35 11 PM" src="https://user-images.githubusercontent.com/2036040/71608089-48078400-2b33-11ea-8220-3ea8907872a4.png">

**Comment by pjebs** [comment]
Very strange. I get an empty array. Do you think this is a regression due to my OS (High sierra)?

**Comment by codebytere** [comment]
are you running your original code snippet? `eventNames` is only populated after calls to `.on('blah')` so if you run:

```js
  n.on("click", () => {
    console.log('Notification clicked')
    app.quit()
  })

  const es = n.eventNames()
  console.log(es)
```

it'll show as `['click']` for me, but if i run:

```js
  const es = n.eventNames()
  console.log(es)

  n.on("click", () => {
    console.log('Notification clicked')
    app.quit()
  })
```

i too get an empty array

**Comment by pjebs** [comment]
My mistake regarding`eventNames`.

After investigating further, I discovered the problem is actually deeper.
Here is what I mean:


```javascript


setInterval(() => {

const n = new Notification({
    body: 'Lorem Ipsum Dolor Sit Amet'
  })
  n.on("click", () => {
    console.log('Notification clicked')
  })
  n.show()

}, 10000)

```

You will see that from the second notification onwards, the click event is not triggered.
The solution is in the click event do this:

```javascript

  n.on("click", () => {
    n.removeAllListeners(["click"])
    console.log('Notification clicked')
  })

```

That fixes the problem but highlights a more serious underlying issue.

**Comment by stanurkov** [comment]
Any news on this issue?  It seems that notifications are only clickable during development. In an installed app notifications can only be closed on Windows 10

**Comment by Willyfrog** [comment]
I'm seeing this problem on windows 10 with a custom installer. I've created a (hopefully) small enough [project](https://github.com/willyfrog/enp) so it can be checked if needed, as this is affecting mattermost's desktop app and would love to help solve it.

using that project and having electron on the start menu, notifications work as expected.
building the MSI using the script, notifications show but on click they act as manually closed.

Let me know if I can provide any more info that might be helpful or help you in any way.

**Comment by vyunikov** [comment]
Any progress on this? 
The problem I have is that notification click events are only delivered when notification is clicked once shown. But when notification is clicked from Action Center click event doesn't get delivered.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
