### ISSUE TITLE
webContents unresponsive after a period of time without devtools

### ISSUE THREAD

**Issue by 26903651** [electron/electron#21613]
If you do not open devtools, it will not respond after a period of time. But if you open devtools, even if you leave it for a day, there is no problem

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by 26903651** [comment]
I think this problem may be a problem with the scaffolding I used. I replaced it with a new scaffolding and there is no problem now
