### ISSUE TITLE
Scroll bar position change

### ISSUE THREAD

**Issue by y489436672** [electron/electron#21611]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
The position of the scroll bar changes when you drag a window from one screen to another, which may be caused by the different zoom ratio to return the scroll bar to its original position.
* **Electron Version:**
v7.1.2
* **Operating System:**
window10
* **Last Known Working Electron version:**
v7.1.2
### Expected Behavior
Scroll bar in original screen position

### Actual Behavior
Scroll bar back to home position

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
