### ISSUE TITLE
Display exception when MAC switches full screen

### ISSUE THREAD

**Issue by china-net-meng** [electron/electron#21617]
### Issue Details

* **Electron Version:v7.1.7**
  * 
* **Operating System:osx 10.15.2**
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior
For example, the full screen switching of GitHub desktop software is normal, but the software I built with electronic 7.1.7 is not. Note that it is not that the full screen switching is not possible, but that the page content display is abnormal when the full screen switching is performed

In the demonstration, the default background of electronic is white, and the background of HTML is red
### Screenshots
![2](https://user-images.githubusercontent.com/33045952/71434657-74309880-2720-11ea-82db-8f0c2e0487bc.gif)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
