### ISSUE TITLE
crashReporter fail to send dmp file to server in 7.1.2

### ISSUE THREAD

**Issue by Leaking** [electron/electron#21618]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Recently, I upgrade my electron from 5.0.8 to 7.1.2, i found the crashReporter fail to report crash with Electron 7.1.2.

I use crashReporter to catch native crash and upload to our server

```
crashReporter.start({
      productName: 'xxxx',
      companyName: 'xxxx',
      submitURL: 'https://xxxxx/feedback/upload?func=4',
      uploadToServer: true,
      extra: {
        vid: vid,
        sid: xmSid,
        uin: xmUin,
        skey: xmSkey,
        processType: 'main',
        release: packageJSON.version
      }
    })
```
But I found the dmp file is generated but it never upload to my server, and I can not find any http request of the crasshReporter in my fiddler.

but I find some error log in the operation_log.txt which beside with the dmp file

```
[18784:8028:1225/202536.733:ERROR:http_transport_win.cc(349)] WinHttpWriteData: 操作成功完成。 (0x0)

```

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Windows 10 (10.0.17134)
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behavior
generated dmp file and upload it to server
### Actual Behavior
generated dmp file but fail to upload it to server

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
