### ISSUE TITLE
-webkit-app-region: drag; not working when set to an element in BrowserView

### ISSUE THREAD

**Issue by ghost** [electron/electron#21621]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.11 & 7.0.1
* **Operating System:**
  * Windows 10 (1903) 
* **Last Known Working Electron version:**
  * N/A 

### Expected Behavior

Setting -webkit-app-region: drag; should enable dragging of the window

### Actual Behavior

Setting -webkit-app-region: drag; doesn't allow dragging of window

### To Reproduce

main.js
```
const { app, BrowserWindow , BrowserView } = require('electron');
const { Path } = require('path');
function createWindow () {
// Create the browser window.
let win = new BrowserWindow({
width: 800,
height: 600,
frame : false
})

// and load the index.html of the app.
win.loadURL('https://www.github.com/');

let view = new BrowserView();
win.setBrowserView( view );
view.webContents.loadURL( Path.join( __dirname , 'draggable.html')  );
view.setBounds({
x:0,
y:0,
width:800,
height:30
});

view.setAutoResize({
width : true,
horizontal:true
});
}

app.on('ready', createWindow);

```

draggable.html
```
<html>
	<head>
		<style type="text/css">
			body{ background: blue; overflow: hidden; -webkit-app-region: drag; width: 100%; height: 100%; }
		</style>
	</head>
<body>
</body>
</html>
```

### Additional Information

Worked as expected in MacOS

**Comment by arleyGuoLei** [comment]
me to.

```
"vue-electron": "^1.0.6",
"electron": "^2.0.4"
```

```css
  body,
  html {
    -webkit-app-region: drag;
  }
```

**Comment by Slapbox** [comment]
I'm seeing draggable areas randomly lose draggability. I thought it was maybe just development environment weirdness until today when I spotted the bug in `prod`.

When I found the bug, I set the element to be fullscreen and above all other elements, and it's still not draggable.

I just made a new `div` in the DOM, assigned in the following styles, and it is indeed not draggable right now. Some of my existing draggable areas still work, some don't, and newly created ones don't either.

```css
    z-index: 999999;
    position: fixed;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background: green;
    -webkit-app-region: drag;
```

![image](https://user-images.githubusercontent.com/6835891/74187553-c9fec880-4c1a-11ea-8fb8-207ba7bdc085.png)

I set every other element to `display: none` so that I'm left with only my newly created `div`. All of the green areas should be draggable, but they're not.

`Electron@7.1.11`

**Comment by Slapbox** [comment]
To add some context, in `dev` I was seeing this seemingly only when React hot-reloaded. I'm guessing that whatever led to it breaking for me in `prod` happened a few times and I chalked it up to hot-reloading.

I don't know if the bit about hot-reloading might give any clue about what might be the issue here. I'll update if I uncover anymore information.

**Comment by Slapbox** [comment]
Hit the bug again today. Suddenly draggable regions are not draggable, and right clicking doesn't provide the OS context menu. Draggable is set, it's the top element, but nothing.

**Comment by kasenvr** [comment]
I'm trying to make a Vue element draggable, it's not working either.

**Comment by jhuckaby** [comment]
Can confirm, this is 100% reproducible on macOS 10.15.3 with Electron 8.1.1, even using the most vanilla of examples.  I believe `-webkit-app-region: drag;` is completely broken in this version.

**Comment by quanglam2807** [comment]
I found a workaround for this issue. You can put the draggable divs at the same region in `BrowserWindow`, then even if you put a BrowserView on top of that region, that region is still draggable.

**Comment by tejasmanohar** [comment]
I'm facing this same issue on MacOS 10.14.6 and Electron version v8.2.5. 

> I found a workaround for this issue. You can put the draggable divs at the same region in BrowserWindow, then even if you put a BrowserView on top of that region, that region is still draggable.

This solution is not so easy with all sites (especially third party sites or if you are shrinking the main BrowserWindow's client area to not overlap with the BrowserView on top, see https://github.com/electron/electron/issues/23758).

**Comment by ThomasStubbe** [comment]
@quanglam2807 I'm trying this, but the browser-view on top is not receiving the clicks anymore. It seems that the browserWindow is in front of it... Did you do something special to get the browserView before the html code of the browserWindow?

**Comment by gknapp** [comment]
I'm also seeing inconsistent behaviour. I've set both `user-select: none;` and `-webkit-app-region: drag;` on my app icon (top left), I can still drag the image out of the electron BrowserWindow and on to my desktop. A copy of the file appears on my desktop wallpaper. My app isn't packaged, the devtools are not open.

**Comment by ccorcos** [comment]
> I found a workaround for this issue. You can put the draggable divs at the same region in BrowserWindow, then even if you put a BrowserView on top of that region, that region is still draggable.

@quanglam2807 do you mean that you're putting the drag region in the BrowserWindow's webContents?

**Comment by quanglam2807** [comment]
> > I found a workaround for this issue. You can put the draggable divs at the same region in BrowserWindow, then even if you put a BrowserView on top of that region, that region is still draggable.
> 
> 
> 
> @quanglam2807 do you mean that you're putting the drag region in the BrowserWindow's webContents?

Yes, that's what I did.

**Comment by ccorcos** [comment]
Hmm. I'm doing this: 

```ts
	const header = `data:text/html;charset=utf-8,<body style="height: 100vh; width: 100vh"><div style="position: absolute; z-index: 9999; top: 0px; left: 0px; right: 0px; height: 34px; pointer-events: none; -webkit-app-region: drag;"></div></body>`
	window.webContents.loadURL(header)
```

And it sorta works. If I move my mouse fast so the mouse leaves the region, it stops dragging which feels really jank. Do you have that problem as well?

**Comment by pejman1** [comment]
I have same issue with browser view by electron version 10.1.5 in windows 10
browser view is not draggable while I set -webkit-app-region: drag

**Comment by daveyjones** [comment]
Google brought me here, but the issue that ended up being relevant to me was #27173. Removing `<!DOCTYPE html>` did the trick. So far, I haven't seen any negative repercussions of removing that doctype.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by gknapp** [comment]
Tried removing `<!DOCTYPE html>`, didn't see a difference.
