### ISSUE TITLE
Tray icon shows in file menu OSX

### ISSUE THREAD

**Issue by schroef** [electron/electron#21628]
Does anyone understand why this app icon shows in the file menu bar?

We are using a 512x512 icon and it shows hige in the topbar. Ive tried 256 and 128, but keeps showing. The logomark is a PNG format and added by using this code

```
import AppIcon from '../renderer/resources/logo/logomark_128.png';
let tray: Tray | null;
if (!tray) {
    tray = new Tray(`${__dirname}/${AppIcon}`);
    const trayMenu = Menu.buildFromTemplate([
      {
        label: 'Open',
        type: 'normal',
        click: () => (mainWindow ? mainWindow.focus() : createWindow()),
      },
      { label: 'Exit', type: 'normal', click: app.quit },
    ]);
    tray.setContextMenu(trayMenu);
    tray.setToolTip('Allusion - Your Visual Library');
    tray.on('click', () => mainWindow ? mainWindow.focus() : createWindow());
  }
```

**Comment by miniak** [comment]
Can you please add a screenshot?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
