### ISSUE TITLE
How can you put Menu in the upper right corner of the page

### ISSUE THREAD

**Issue by lizeze** [electron/electron#21625]
### Preflight Checklist

 - [x]  have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
 - [x] agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
 - [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

How can you put Menu in the upper right corner of the page, like this, thank you!

![image](https://user-images.githubusercontent.com/33169073/71508116-be9d4b00-28c1-11ea-86f7-e3271e3212fa.png)

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
