### ISSUE TITLE
application start error when required fabric-client dependency

### ISSUE THREAD

**Issue by Randyshu2018** [electron/electron#21638]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.3
* **Operating System:**
  * windows 7
* **Last Known Working Electron version:**
  * 

### Expected Behavior

application start normally.

### Actual Behavior

![image](https://user-images.githubusercontent.com/19544447/71574130-5600d900-2b22-11ea-8f5b-2e57924d3b3f.png)

### Screenshots

package.json:
![image](https://user-images.githubusercontent.com/19544447/71575833-5cdf1a00-2b29-11ea-9f00-2f5500c4aaf2.png)

main.js 
![image](https://user-images.githubusercontent.com/19544447/71574452-b5abb400-2b23-11ea-87c5-e7bfd8df6952.png)

### Additional Information

first when i run yarn start,the error below ,

![image](https://user-images.githubusercontent.com/19544447/71574505-eee42400-2b23-11ea-830a-6d3256552955.png)

then i install electron-rebuild and then rebuild the native dependency,
```
$ yarn add electron-rebuild@1.8.8
$ ./node_modules/.bin/electron-rebuild
$ yarn build-win
```
finally,got below error(dmg file is well while exe file is wrong),
![image](https://user-images.githubusercontent.com/19544447/71575132-c1e54080-2b26-11ea-9251-e70d6c259521.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
