### ISSUE TITLE
Windows 10/Linux: Notifications ignore tag

### ISSUE THREAD

**Issue by elan** [electron/electron#21646]
### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Windows 10

### Expected Behavior

When creating notifications with the same `tag`, new notifications replace existing ones.

### Actual Behavior

The notifications queue up and display one after the other, with standard pause between them.

### To Reproduce

From the renderer process, create multiple notifications with the same tag:

```js
new Notification('Hello', { body: 'world', silent: true, tag: 'whatever' });
new Notification('Yo', { body: 'world', silent: true, tag: 'whatever' });
```

**Comment by WonderKeisy** [comment]
I also have the same issue too.
I tested both Windows 7, 10 using html5 notification.
Unlike the intent of the questioner, I would like to stack messages in Windows 10 as well in Windows 7 if there are multiple alarms.

**Comment by zxcal** [comment]
Same issue encountered.

Electron Version:
9.0.3
Operating System:
macOS 10.15.4

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
