### ISSUE TITLE
App reload when copy sharing-link-button is clicked

### ISSUE THREAD

**Issue by iamtitere** [electron/electron#21648]
Hi! im new with this so... i dont know what is recommended to post an issue, but im going just to explain the case:

When i try to share a song (right-click on the player bar, share, "copy link" button on the right of the window) the player just reload itself (as reloading a page) and starts again the song by the beginning. 

This is not a big problem cause i can select the link an ctrl+c, but a bug is a bug...

Someone else with the same problem?

Thanks for reading, i love the app <3

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed. Thank you!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
