### ISSUE TITLE
Error: UNKNOWN: unknown error, open chrome_100_percent.pak'

### ISSUE THREAD

**Issue by Hggkfe** [electron/electron#21640]
![image](https://user-images.githubusercontent.com/43810131/71577176-150ec180-2b2e-11ea-91e7-8d02f862fc5d.png)

Download package replaces all files in the project, but something goes wrong?

![image](https://user-images.githubusercontent.com/43810131/71577386-ddece000-2b2e-11ea-9116-65b00a0098e6.png)
![image](https://user-images.githubusercontent.com/43810131/71577401-ec3afc00-2b2e-11ea-918c-7ec11360666e.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
