### ISSUE TITLE
new Browserwindow over fullscreen browser window on macOS catalina, electron 6.1.2 becomes fullscreen

### ISSUE THREAD

**Issue by sdetweil** [electron/electron#21655]
I have an extension for the MagicMirror SPA using Electron. the extension shows an image in a small browserWindow floating over/on top of the fullscreen dom window. neither window knows about the other

on macOS catalina if the SPA window is fullscreen, the image window, configured for 400px by 400px, becomes a fullscreen window  on TOP of the SPA, and one cannot surface the SPA again. 

if the SPA is NOT fullscreen, then the image window behaves as coded,  like a pong game paddle selecting random locations on each new picture shown 

the settings to create the new window

```
		// create the window, in new position, hidden
		viewerinfo.window = new BrowserWindow({
					width: viewerinfo.config.width, (400)
					height: viewerinfo.config.height, (400)
					x: new_x,
					y: new_y,
					//alwaysOnTop: true,
					show:false,
					//transparent: true,
					backgroundColor: "#000000",
					dx: 0,
					dy: 0,
					frame: false,
					skipTaskbar: true
					})
```

I have an 'did-finish-load' handler,  loadUrl the image, and show it once loaded (to eliminate the empty window while the image loads from a remote resource)

macOS 10.15.1, 
electron 6.1.2
node 10.17.0,
npm 6.11.3

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
