### ISSUE TITLE
Using nodeIntegrationInSubFrames may result in an unresponsive BrowserWindow

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#21670]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.1.2, 7.1.7, 8.0.0-beta.5
* **Operating System:**
Windows 10 (1809)

### Expected Behavior
Website remains interactive, mouse interaction does work (pointer changes, clicks will be registered, scrollbars work as expected.

### Actual Behavior
Website is not interactive, scrollbars dont work (but the scrollwheel somehow does work), clicks on site elements do nothing. Regarding the scrollbars: When scrolling by dragging the scrollbar the scrollbar becomes stuck.

The browser window instance will also report that it has become unresponsive.

### To Reproduce
Create a window with a preload script (script does not need to do anything at all) and nodeIntegrationInSubFrames enabled. Navigate to a heavy loading website, for example one of those:
https://n-tv.de (just need to wait until everything has loaded)

https://stern.de (may need to actively scroll through the site)
https://bild.de (may need to actively scroll through the site)

Gist:
https://gist.github.com/9d1de5bda4bbbcc592ef963acd51459c

On fast computers this issue does only occour very seldom, on my work PC I was only able to reproduce it by artificially slowing down my CPU (I used CPU Killer @70% slowdown on my i7-7700K @4.20Ghz CPUs), sometimes multiple tries are needed.

### Additional Information
The bug is hard to reproduce on fast computers, our QA uses some slower machines (comparable to the machines customers will use) and the application does some more work, like logging navigations, eg. I was only able to reproduce this in a testable manner by slowing down my computer and waiting a while when loading the sites.

**Comment by Ririshi** [comment]
We are facing the same problem in our Electron 11.1.1 application that is distributed to computers in restaurants. Many of these are 32-bits systems with low specs. We aren't able to reproduce the issue on our own machines (both Mac and Windows), but it is occurring for our clients.

Extremely frustrating since we cannot even reproduce it, let alone try to debug and fix it. I am happy to have found a possible culprit though. The only way (if OP is correct), would be to disable `nodeIntegrationInSubFrames` entirely. I don't think we are able to do that, because of the way we handle printing actions.

I hope this issue will get some traction so we can figure out what is going on and if there is any other way to fix it.
