### ISSUE TITLE
Electron's scroll area missing from application's children in Accessibility Inspector (macOS)

### ISSUE THREAD

**Issue by dexterleng** [electron/electron#21672]
When I traverse top-down, the Accessibility API doesn't show the `AXScrollArea` containing the `AXWebArea`.

<img width="550" alt="Screenshot 2020-01-04 at 12 45 07 AM" src="https://user-images.githubusercontent.com/34204380/71736332-c2196f00-2e8b-11ea-8fe6-7d9c5b92aa98.png">

But if I check what's under the cursor, one of the parent is the `AXScrollArea`

<img width="672" alt="Screenshot 2020-01-04 at 12 44 51 AM" src="https://user-images.githubusercontent.com/34204380/71736327-c04fab80-2e8b-11ea-9cbe-bbe315223e49.png">

I have set the `AXManualAccessibility` property on my Electron app (Slack).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
