### ISSUE TITLE
in <iframe>. Calling history.back, history.forward, or history.go will always cause a full page refresh in the parent window.

### ISSUE THREAD

**Issue by blalablack** [electron/electron#21680]
**I find this [issues](https://github.com/electron/electron/issues/3734) was closed,but I still have this problem in electron@7.1.2.**

I have an application that embeds user content within an <iframe>. Calling history.back, history.forward, or history.go will always cause a full page refresh in the parent window.

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by TotallWAR** [comment]
I have the same issue with native browser history API when i use IFRAME history.back func in SAFARI on IOS. And it doesn't work for first history event only. For example i open iframe window, click on button and into iframe i change history by pushState. Then if i try go back by history.back() method or by phone's system back button – page is reloaded. But if i change history INTO iframe multiple times, then history.back() works untill the moment i reach the first history change into iframe - then page is reloaded again.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/21680#issuecomment-572262180). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
