### ISSUE TITLE
file:/// protocol conversion

### ISSUE THREAD

**Issue by blankTwo** [electron/electron#21700]
`electron  version 6.0.9 `

I encountered such a problem when electron was packaged and installed.
There is `<img src ="//xxxxx.png"/>` in html (this is just an assumption).
Unacceptable, changed to `file://xxxxx.png` in the actual web request 
(Ideally should be `https://xxxxx.png`).
This is just one of them. There are still many such problems, and some examples also exist in the source code of the package: 
![image](https://user-images.githubusercontent.com/45682935/71964777-4b88c280-3239-11ea-8892-4dffcd8cfe44.png)
This is what it looks like in the request：
![image](https://user-images.githubusercontent.com/45682935/71964799-5c393880-3239-11ea-90e4-402120c49f74.png)

`protocol.registerFileProtocol` did not achieve the effect I expected

What should I do?

**Comment by jacobq** [comment]
See https://github.com/electron/electron/issues/10975#issuecomment-340660259

**Comment by blankTwo** [comment]
At present, there is no better reproduction scheme. After installing and running the software package on the client, the user is using the export function (data is xlsx)，this error occurs when requested.

I have tried <a href="#protocolregisterfileprotocolscheme-handler">`registerFileProtocol`</a> It will make the program blank when running! It makes me a headache。
My purpose is very simple. I just want to intercept all requests. All requests starting with `cdn` use `https://` instead of `file:///`.

**Comment by vladimiry** [comment]
> I just want to intercept all requests

https://electronjs.org/docs/api/web-request

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
