### ISSUE TITLE
importing powerMonitor from electron before 'ready' event causes crash

### ISSUE THREAD

**Issue by mtgto** [electron/electron#21716]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Same as #18966, app crashed when launched.

```typescript
import electron, { app } from "electron";

let mainWindow: electron.BrowserWindow;

app.on("ready", () => {
  mainWindow = new electron.BrowserWindow({
    width: 800,
    height: 600,
  });
});
```

Here is my repro sample.
https://github.com/mtgto/sample-electron-crash

Here is compiled index.ts
https://gist.github.com/mtgto/2a60ed4ce2e280c7577412884cde166e

* **Electron Version:**
  * v7.1.8
* **Operating System:**
  * Ubuntu 18.04.3
* **Last Known Working Electron version:**
  * Don't know

### Expected Behavior

Open an empty window.

### Actual Behavior

```console
$ yarn start
yarn run v1.21.1
$ electron index.js
App threw an error during load
Error: The 'powerMonitor' module can't be used before the app 'ready' event
    at Object.module.<computed> [as on] (electron/js2c/browser_init.js:6800:30)
    at Object../lib/browser/api/power-monitor.ts (electron/js2c/browser_init.js:2671:18)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at loader (electron/js2c/browser_init.js:2060:41)
    at Object.powerMonitor (electron/js2c/browser_init.js:7079:17)
    at __importStar (/home/user/sample-electron-crash/index.js:5:96)
    at Object.<anonymous> (/home/user/sample-electron-crash/index.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The 'powerMonitor' module can't be used before the app 'ready' event
    at Object.module.<computed> [as on] (electron/js2c/browser_init.js:6800:30)
    at Object../lib/browser/api/power-monitor.ts (electron/js2c/browser_init.js:2671:18)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at loader (electron/js2c/browser_init.js:2060:41)
    at Object.powerMonitor (electron/js2c/browser_init.js:7079:17)
    at __importStar (/home/user/sample-electron-crash/index.js:5:96)
    at Object.<anonymous> (/home/user/sample-electron-crash/index.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
```

### To Reproduce

```console
$ git clone https://github.com/mtgto/sample-electron-crash.git
$ cd sample-electron-crash
$ yarn install
$ yarn build
$ yarn start
```

### Screenshots

N/A

### Additional Information
Stacktrace says `__importStar` calls powerMonitor. It happens when tsconfig uses `esModuleInterop: true` (default is true)
In macOS, app doesn't crash.

**Comment by jacobq** [comment]
Why can't you just use `const electron = require('electron')` instead of `import`?

Also, does electron support TypeScript natively? If so, please specify URL that discusses this.

**Comment by vladimiry** [comment]
The issue is valid. Although TypeScript developers normally do (no import-start helper involved in both cases)
```
import { app, BrowserWindow } from "electron";

let mainWindow: BrowserWindow;
```
or 
```
import { app } from "electron";

let mainWindow: Electron.BrowserWindow;
```
instead of
```
import electron, { app } from "electron";

let mainWindow: electron.BrowserWindow;
```

Besides, in a real-world scenario, you would probably go with Webpack/Rollup/etc bundlers which often have own module loading wrappers that usually do `require` under the hood.

**Comment by jacobq** [comment]
> Can confirm the issue is reproducible.

Sure, but is it a bug in electron? It looked to me like this only happens when the application code attempts to load the `powerMonitor` module before the `ready` event occurs, which is forbidden by the spec.

**Comment by vladimiry** [comment]
In my opinion, loading the library and using it are different things. So from this point that would be a bug in Electron. But it's clear the Electron initializes the instance eagerly/on-module-loading https://github.com/electron/electron/blob/ec61041d41254ab9a6eaae7673b5ded133d39060/lib/browser/api/power-monitor.ts#L11

So maybe it's just documentation issue and the docs should be adjusted like you can't `load or use` the module.

Given the import start helper code:
```javascript
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
```

The power monitor module and all of them listed on `electron` are clearly accessed here: `mod[k];`.

And well, it's better not to use TS import-start stuff a lot since if affects performance, you know that `for (var k in mod) if` stuff.

**Comment by vladimiry** [comment]
> Sure, but is it a bug in electron?

Actually I think Electron could do something like:
```typescript
process.platform === 'linux' && (async () => {
  const {app} = await import("electron");

  app.on("ready", () => {
    powerMonitor.on('newListener', (event:string) => {
      if (event === 'shutdown' && powerMonitor.listenerCount('shutdown') === 0) {
        powerMonitor.blockShutdown()
      }
    });

    powerMonitor.on('removeListener', (event: string) => {
      if (event === 'shutdown' && powerMonitor.listenerCount('shutdown') === 0) {
        powerMonitor.unblockShutdown()
      }
    })
  })
})()
```

Instead of eagerly calling `powerMonitor.on` method in along with module loading:

https://github.com/electron/electron/blob/ec61041d41254ab9a6eaae7673b5ded133d39060/lib/browser/api/power-monitor.ts#L14-L26

**Comment by ckerr** [comment]
Yeah, I agree this is a bug in Electron rather than an issue with ts wildstar.

For example, you can remove typescript from the equation altogether and instead try to run the sample code from the top of [`electron/docs/api/power-monitor.md`](https://github.com/electron/electron/blob/master/docs/api/power-monitor.md#powermonitor):

```
This module cannot be used until the ready event of the app module is emitted.

For example:

const { app, powerMonitor } = require('electron')

app.on('ready', () => {
  powerMonitor.on('suspend', () => {
    console.log('The system is going to sleep')
  })
})
```

That code causes the same failure on `require`.

If you don't mind, I'm going to edit the issue topic to reflect that the issue doesn't require TypeScript
