### ISSUE TITLE
GPU process crashes when electron app is started on a network share

### ISSUE THREAD

**Issue by tnixeu** [electron/electron#21713]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * At least 7.1.1 - 8.0.2
* **Operating System:**
  * Windows 7 / 10
* **Last Known Working Electron version:**
  * 3.0.0

### Expected Behavior
Electron behaving the same way as when started on a local disk

### Actual Behavior
Default electron app does not open a window. However, two electron processes keep running.

```
[20464:0109/105238.208:WARNING:gpu_process_host.cc(1221)] The GPU process has crashed 1 time(s)
[20464:0109/105238.504:WARNING:gpu_process_host.cc(1221)] The GPU process has crashed 2 time(s)
[20464:0109/105238.769:WARNING:gpu_process_host.cc(1221)] The GPU process has crashed 3 time(s)
[20464:0109/105239.035:WARNING:gpu_process_host.cc(1221)] The GPU process has crashed 4 time(s)
[20464:0109/105239.284:WARNING:gpu_process_host.cc(1221)] The GPU process has crashed 5 time(s)
[20464:0109/105239.565:WARNING:gpu_process_host.cc(1221)] The GPU process has crashed 6 time(s)
[20464:0109/105239.565:ERROR:browser_gpu_channel_host_factory.cc(138)] Failed to launch GPU process.
```

### To Reproduce
Extract electron release onto a network share and start it. 
In order to get the log messages set `ELECTRON_ENABLE_LOGGING=true`

### Additional Information
I noticed that my electron app is behaving differently when it is started on a network share.  In my app I am using express for starting a webserver and the BrowserWindow. I tired debugging my app, however, I am not able to open the developer tools. I slimmed down the app more and more and even when I removed everything besides opening the window and loading the page (from another server), it still behaves the same and the developer tools cannot be opened.

I have not tired electron versions between 3.0.0 and 7.1.1.

Initially I wanted to provide this as the way to reproduce it:
```js
const {app, BrowserWindow} = require('electron');

(async () => {
    await app.whenReady();
    let win = new BrowserWindow({ width: 800, height: 600 });
    win.loadURL('https://electronjs.org/');
})();
```
 However, when I noticed that even the default app behaves differently. I thought it is easier to reproduce and I think it is the same bug.

### Edit: 
I tried it with the recent 8.0.2 release. The bug still exists. With `--no-sandbox` the app runs, however, I do not think it is the solution I want to deploy.

The line number of the crash has changed:
```
[35656:0228/153643.164:WARNING:gpu_process_host.cc(1166)] The GPU process has crashed 1 time(s)
```

**Comment by mjlawrence83** [comment]
I believe I'm also seeing this when using Cypress 3.8.1, which I think uses Electron 7.1.4. When opening a project on a mirrored drive, I get exceptions, if I open from the original c: drive, then it is fine.

**Comment by dreamflow** [comment]
in our network , electron.exe also chrashes when run
from a network-drive(= network-share with drive-letter) .

i've used/tested the standard 64bit windows zip downloads
"electron-vX.Y.Z-win32-x64.zip"   from
https://github.com/electron/electron/releases
and tested in Win10-1909-64bit the following electron 64bit versions
6.1.5  ,  6.1.6  ,  6.1.7  ,  8.0.0  ,  9.0.0-nightly.20200121  ,  10.0.0-nightly.20200210
with always the same result : all crash and no electron-window is created/shown .

the "newest" electron.exe that runs normal from a network-drive is version 5.0.13  .

i've also run the current Visual-Studio-Code 64bit 1.42.0 (based on Electron 6.1.6 )
from a network-drive and it starts and works normal .

i've viewed the command-line-switches that Visual-Studio-Code uses to start .

it turned out that by starting electron.exe(versions 6.1.5-10.0.0nightly)
with --no-sandbox it starts and works normal for me from an network-drive .

**Comment by VishwasShashidhar** [comment]
I don't think Chrome supports running on a Network Drive with sandboxing enabled.

Please refer to the last comment in this issue -> https://bugs.chromium.org/p/chromium/issues/detail?id=103902

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
