### ISSUE TITLE
useContentSize is set to undefined after setMinimumSize (and one other issue)

### ISSUE THREAD

**Issue by gtkpr** [electron/electron#21740]
### Issue Details

* **Electron Version:**
  * 7.1.8
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**

### Expected Behavior
A. I expect `useContentSize` to maintain its state.

B. I expect `setMinimumSize` to enlarge the window to the minimum size if the window is smaller.

### Actual Behavior
A. `useContentSize` gets set to `undefined` after `setMinimumSize`.

B. The dimensions of the window remain unchanged.

### To Reproduce
A. Use `remote` to `setMinimumSize`.

B. `setMinimumSize` to greater than the current dimensions of the window.

### Additional Information

Here is a rough solution to problem B.

```
const { remote } = require('electron')
let width, height
remote.getCurrentWindow().setMinimumSize(X, Y)
width = innerWidth < X ? X : innerWidth
height = innerHeight < Y ? Y : innerHeight
remote.getCurrentWindow().setContentSize(width, height)
```

**Comment by pushkin-** [comment]
your second issue is documented [here](https://github.com/electron/electron/issues/20613)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
