### ISSUE TITLE
Zipped file download is not working when sandbox is enabled in webview

### ISSUE THREAD

**Issue by sanoopjose-hashedin** [electron/electron#21755]
### Issue Details

* **Electron Version:**
  * 7.1.8
* **Operating System:**
  * macOS 10.15.1 / Windows 10 (1809)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Downloading zipped files(Download a folder of multiple files) from GDrive should trigger the download action(will-download event) and download the file into the default download path from a sandboxed webview.

### Actual Behavior
Download action is not triggering from a sandboxed webview when downloading a folder or multiple files(zipped file)

### To Reproduce

```sh
$ git clone https://github.com/electron/electron-quick-start.git
$ npm install
```
Add a webview element(enable sandbox in webPreferences) and load GDrive URL(https://drive.google.com/drive/)

```sh
$ npm start 
```

Download a folder of select multiple files and download them from GDrive.

### Screenshots
<img width="1099" alt="Screenshot 2020-01-13 at 2 25 34 PM" src="https://user-images.githubusercontent.com/57390531/72242991-ae4ed500-3610-11ea-8409-7d980a216306.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
