### ISSUE TITLE
Memory leak when creating iframe

### ISSUE THREAD

**Issue by vsnal** [electron/electron#21788]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 7 (build 7601)

### Expected Behavior
Memory usage does not increase over time.

### Actual Behavior
Electron continues to allocate memory.

### To Reproduce
Minimal example: 
https://github.com/vsnal/electron-memleak-iframe

1. Clone repository
2. Run "npm install"
3. Run "npm start"
4. Take a series of memory snapshots.

### Screenshots
![image](https://user-images.githubusercontent.com/17480365/72433831-454f9480-37ab-11ea-99f5-5797cad26480.png)

### Additional Information
Problem code:
```
var element = null;

setInterval(function() {
    if (element) {
        element.remove();
    }

    element = document.createElement('iframe');
    document.body.appendChild(element);
}, 100);
```
This code works correctly in Chrome, but causes a memory leak in Electron (and NW.js too).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
