### ISSUE TITLE
the file is corrupted when it's downloaded via a custom http protocol

### ISSUE THREAD

**Issue by LuoJinghua** [electron/electron#21784]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior

A correct file should be downloaded and its content should match the origin file.

### Actual Behavior

The file is corrupted and doesn't match the origin file.

### To Reproduce

https://github.com/LuoJinghua/electron-quick-start/tree/custom-http-protocol-bug

```sh
$ git clone https://github.com/LuoJinghua/electron-quick-start -b custom-http-protocol-bug
$ npm install
$ npm start || electron .
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
