### ISSUE TITLE
Collect process GPU usage

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#21791]
We work on a product which we are in need to collect process CPU, Memory, Bandwidth and GPU usage per `BrowserWindow`.

I have already created a module which collect them but without GPU.
I didn't found anything related, but is there a way to collect the GPU usage of the process?

Thank you.

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by btzsoft** [comment]
@codebytere thank you for your prompt reply. I placed here because it's not just a question but an feature request if this is in generally is planned to be implemented in the future and when.

**Comment by codebytere** [comment]
@btzsoft yes - 

```
app.getGPUInfo('complete')
app.getGPUInfo('basic')
```

Are methods you can call at present.

**Comment by btzsoft** [comment]
@codebytere I want to collect the GPU usage of a single process, we already use `process.getCPUUsage()` to get the CPU usage of an `BrowserWindow` but we want also to get the `GPU` usage of each open `BrowserWindow`.
