### ISSUE TITLE
Electron persistent

### ISSUE THREAD

**Issue by Amosss** [electron/electron#21793]
Hi
I work with Quasar and use Electron to build it as an executable.

1. Do I need a Mac/Iphone in order to make my pwa project compiled to Mac/Iphone?

2. I have a data object. For simplicity, lets say the object is:
```
user : {
   name: "";
   age: 0;
}
```
When the user logs in to the web version, the app loads the data from the server into this object and all is good. When the user logs out, the object is forgotten until the next time he logs in and the app loads the data again.

When working as desktop (Windows for example), I want to store (encryptedly) this data locally, so the next time the user logs in, the data will be loaded from that file instead of querying the server for it.

(How) Can I achieve the above?
Thanks

**Comment by codebytere** [comment]
We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options
. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
