### ISSUE TITLE
Feature request: function to show Mac tab bar / check if it's shown

### ISSUE THREAD

**Issue by adam-lynch** [electron/electron#21806]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I want to always show the native Mac tab bar in my app. `window.toggleTabBar()` exists but it doesn't accept any parameters; it simply toggles. When an app is killed and launched, the tab bar will be shown by default if it was shown at the time it was killed. So if I call `window.toggleTabBar()` after creating my main window, there's a 50/50 chance of the tab bar being there each time my app launches.

### Proposed Solution

Add `.showTabBar()` and `.hideTabBar()` functions. Also, there should probably be a `.isTabBarShown()` function. Maybe events too because the tab bar can be shown/hidden via the menubar.

**Comment by codebytere** [comment]
Unfortunately this is pretty straightforwardly plumbed from the [macOS native API](https://developer.apple.com/documentation/appkit/nswindow/1644517-toggletabbar?language=objc) - there doesn't exist a show, hide, or check functionality. We also can't just track for example a boolean ourselves, since there are multiple ways to toggle the bar that don't flow through our APIs. Should this become possible we're happy to revisit this but for now i'm going to close it out.
