### ISSUE TITLE
Node.js packages don't seem to work in renderer process

### ISSUE THREAD

**Issue by pjebs** [electron/electron#21808]
In my renderer process I have:    
```
const nodeMachineID: require('node-machine-id');
```

It seems to spit out an error about `child_process`

I am using rollup to bundle the render.js file and the output format is `cjs`.

**I was wondering if this is a bug or by design?**

i.e. Is the renderer process meant to **work like main process and accept nodejs libraries** or is it meant to operate strictly as a browser.

If it is strictly as a browser, why does `require("electron")` work (I'm assuming it's because of nodeIntegration: true)?

**Comment by pjebs** [comment]
**NOTE: I have "nodeIntegration":      true,**

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
