### ISSUE TITLE
Problems with Trend Micro Worry-Free Business Security

### ISSUE THREAD

**Issue by p-fusi** [electron/electron#21802]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.1.9
* **Operating System:**
Windows 10

### Actual Behavior
I cloned the electron-quick-start project.  
I ran 
`npm install` 
and then 
`npm run start`  

The app starts but, immediately, an alert window of **Trend Micro Worry-Free Business Security** appears. The alert is related to a not authorized modification and the motivation is "Loading system libraries". 
Looking at the Antivirus register it seems to be a problem with **ZwWriteVirtualMemory**

Thanks a lot

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by p-fusi** [comment]
I am sorry. I just edited my issue

**Comment by codebytere** [comment]
Looking at the issue at hand, 
> Trend Micro Worry-Free Business Security
is a system program you have installed onto your system, since Electron.js installs no external programs of that nature and neither does Chromium. We recommend you search your computer and determine how you can uninstall said system, as Electron does not assume responsibility for externalities present as a result of 3rd party programs which may act in malicious or unexpected ways.
