### ISSUE TITLE
Display only MenuItem accelerators, no keyboard shortcut functionality ?

### ISSUE THREAD

**Issue by Sakari369** [electron/electron#21815]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I am porting an existing HTML5 based application to Electron. My application handles keyboard input using traditional keydown/keyup event handlers inside the renderer process. Application logic happens through single key keyboard commands, like 'j', 'a', 'z' or by selecting same operations from a menu.

I am handling all the input inside the renderer process, but I would like to display menu shortcuts still in the menu. In order to display the menu shortcuts in the MenuItems, I have to register an accelerator. I don't really need the accelerator.

I have logic in my code so that it handles the keyboard input inside the renderer without propagating to the menu events, but the problem comes when I have also <input> fields in my application and I need to enter text into those.

Now if I press for example 'a' in the text input, and have that single-key shortcut registered as an accelerator (just to be able to display the shortcut in the menu), this accelerator will be triggered. 

### Proposed Solution
I am wondering, is it possible or would it possible just to have a _display only_ menu accelerator items, that are not registered as keyboard shortcuts ?

This way, an application could handle the input internally, and still utilize the nice native formatting of the keyboard accelerators for example in macOS menus. Would this be possible ? Can this be supported even, or is this a system level restriction ?

### Alternatives Considered
I have tested disabling the passing of the keyboard shortcut when input fields are active, but this means the whole keyboard event is not propagated to the renderer and I cannot get any input.

One way to get around this issue would to be have a way to disable keyboard accelerators in Electron and enable them back again when the input is blurred. Is this possible already ?

### Additional Information
I am using electron@7.1.3, macOS 10.14.6.

**Comment by inDigiNeous** [comment]
![Screenflick Movie 17](https://user-images.githubusercontent.com/1212726/72585524-05aab900-3921-11ea-80f4-6f127e28ef0d.gif)

Attached is a screencapture of where I show how the keyboard item is activated when input field is active on my application. This is due to the nature of the single keyboard shortcut being activated. 

In my application logic, while my inputs are active, the keyboard shortcuts are not handled.
This could be also a solution, if there is a way to disable the accelerators with some callback and enable them again ?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
