### ISSUE TITLE
I can't focus a window when I create it

### ISSUE THREAD

**Issue by alexsanro** [electron/electron#21828]
Hi!!  I have a problem that i cant understan why not work. I use `.focus()` for focused the window when i create but not work.  For reproduce i have a littel example:

```
setInterval(function () {
            console.log(powerMonitor.getSystemIdleTime() + "seconds");
            if (powerMonitor.getSystemIdleTime() == 5) {
                openScreen();
            }
        }, 1000);
```
```
function openScreen(){
let browserWindow1 = new BrowserWindow({
        show: false,
        x: 1,
        y: 1,
        width: 800,
        height: 700,
        title: "test-title-1",
        focusable: true,
    });
    browserWindow1.on("focus", () => {console.log("focus");});
    browserWindow1.loadURL("http://www.google.com");
    browserWindow1.setFocusable(true);
    browserWindow1.show();
}
```

The log returned me 'focus', then is on focus, but if i use the keyboard  I see that it is still in the other app. Example: I use `npm start`, click  on Chrome and pass 5 seconds of inactivity, the windows is open and I use the keyboard but what moves me is the chrome window.

What happen!!! Is a bug?

**Comment by RoderickQiu** [comment]
I don't think you are using `.focus()` in the code.

Anyway, you can use `.setAlwaysOnTop()` to help this, I think.

**Comment by alexsanro** [comment]
Not working :/ and sorry,  I forgot to add that line .focus()
I add javascript event keyup for when i push a key give me an alert. But since it does not focus when the window is created when pressing it does nothing.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
