### ISSUE TITLE
Error: Redirect was cancelled - on app update with electron-updater

### ISSUE THREAD

**Issue by technicallyty** [electron/electron#21822]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.1.7
  * 
* **Operating System:**
Windows 7
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

I want to update my app through a github private repo. I have set environment variables and put my token in the code.
### Actual Behavior

I'm getting the following error: Redirect was cancelled, inside of autoUpdater.on('error')
### To Reproduce
It is worth noting I'm using react in this project. here is my build script:
```
"build": {
    "publish": [
      {
        "provider": "github",
        "owner": "tytech3",
        "repo": "<repo>",
        "private": true,
        "token": "<my-token-here>"
      }
    ],
    "appId": "com.example.me",
    "files": [
      "build/",
      "node_modules/**/*",
      "main.js",
      "package.json"
    ],
    "directories": {
      "buildResources": "assets"
    },
    "extraResources": [
      {
        "from": "node_modules/regedit/vbs",
        "to": "regedit/vbs",
        "filter": [
          "**/*"
        ]
      }
    ]
  }
```

**Comment by vladimiry** [comment]
See https://github.com/electron-userland/electron-builder/issues/4505 and https://github.com/electron/electron/issues/21566

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
