### ISSUE TITLE
chrome.desktopCapture API, extend to allow selecting <webview>, BrowserView for sharing. 

### ISSUE THREAD

**Issue by vishal6121** [electron/electron#21839]
Currently in Chromium there is only support for capturing the screen/window.
I can't find anything for more refined sharing granularity (e.g. to only share <webview> or BrowserView  instead of the entire screen or Window). 

I am not sure even if this is possible. But, this can be requirement for desktop apps.

Does anyone know, what the event desktop-capturer-get-sources https://electronjs.org/docs/api/web-contents#event-desktop-capturer-get-sources is for or how can it be used?

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by vishal6121** [comment]
This was more of a feature request. To allow <webview> to be selected as DesktopSourceType

i found this in webview section, so just added it as a question. https://electronjs.org/docs/api/web-contents#event-desktop-capturer-get-sources
