### ISSUE TITLE
app.relaunch fails inside a snap-packed electron

### ISSUE THREAD

**Issue by chase-itay** [electron/electron#21859]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ]x I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *7.1.19
* **Operating System:**
ubuntu 18
* **Last Known Working Electron version:**

### Expected Behavior
application should relaunch when app.relaunch is invoked

### Actual Behavior

an exception is thrown and app is not relaunched.
here is the exception:

/snap/chasedevapp/x1/chasedevapp --no-sandbox[16721]: ../../third_party/electron_node/src/node_platform.cc:444:std::shared_ptr<PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate *): Assertion `data' failed.
Aborted (core dumped)

### To Reproduce
just invoke app.relaunch within electron running in a snap package

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
