### ISSUE TITLE
Crash when select file on ubuntu

### ISSUE THREAD

**Issue by dustin0o7** [electron/electron#21862]
I rendered a full website in electron app using iframe. When I try to choose an image to upload, app crashes with below message

> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

This happens only in Linux

ScreenCast: [media.io_CrashOnUpload.mp4.zip](https://github.com/electron/electron/files/4096943/media.io_CrashOnUpload.mp4.zip)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by rfedericoni** [comment]
> I rendered a full website in electron app using iframe. When I try to choose an image to upload, app crashes with below message
> 
> > Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
> 
> This happens only in Linux
> 
> ScreenCast: [media.io_CrashOnUpload.mp4.zip](https://github.com/electron/electron/files/4096943/media.io_CrashOnUpload.mp4.zip)

Did you solve this issue?
