### ISSUE TITLE
Image loading takes about 300ms for some images

### ISSUE THREAD

**Issue by Christilut** [electron/electron#21869]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
`"electron": "^6.1.7",`
* **Operating System:**
Windows 10 64 bit

### Expected Behavior
Images should load fast. At least within a few ms on a high end computer.

### Actual Behavior
Some images in my electron app take about 300ms to load. You can always noticeably see image popping when navigating.

### To Reproduce
I'm using `electron-builder` with `vue-cli-plugin-electron-builder`.

I can try to make reproduction but maybe someone can confirm that this is an electron issue or not first. I'd like to report this to the correct repo but I honestly don't know where this problem is most likely to come from.

It's happening sporadically so it might not be easy to reproduce.

### Screenshots

![image](https://user-images.githubusercontent.com/3471363/72921153-09887200-3d4b-11ea-8007-7cc15b670935.png)

**Comment by Christilut** [comment]
For some extra context:
![image](https://user-images.githubusercontent.com/3471363/77739243-794bff00-7011-11ea-8acb-8174d609ea32.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
