### ISSUE TITLE
Rounded Corners Disappear on Refresh

### ISSUE THREAD

**Issue by NicholasLYang** [electron/electron#21920]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When I first load the electron app, it has rounded corners:

<img width="592" alt="Screen Shot 2020-01-27 at 1 57 20 PM" src="https://user-images.githubusercontent.com/7357863/73215133-78861200-4121-11ea-8d81-a540f87de559.png">

then, when I refresh (i.e. hit Command-R), they become square:

<img width="589" alt="Screen Shot 2020-01-27 at 4 23 57 PM" src="https://user-images.githubusercontent.com/7357863/73215166-8471d400-4121-11ea-8f49-3ef5cbd85ec4.png">

I'm using React and my DOM hierarchy is:
```
<body>
  <div id="root">
    <MainWindowApp />
  </div>
</body>
```
MainWindowApp has a borderRadius of 20px. The `div` and `body` do not have a background color and I can't figure out for the life of me why they'd be white. I especially don't know why they turn white after a refresh.

Here's how I'm initializing my window:
```
mainWindow = new BrowserWindow({
    width: 560, // 400
    height: 100, // 60
    x: 500,
    y: 350,
    transparent: true,
    frame: false,
    resizable: false,
    alwaysOnTop: true,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: true
    }
  });
```

* **Electron Version:**
v8.0.0-beta.7 (but I've tried it on npm latest, v7.1.10)
* **Operating System:**
macOs 10.14.6 (18G103)
* **Last Known Working Electron version:**
N/A

### Expected Behavior
Corners are rounded and stay rounded

### Actual Behavior
Corners start rounded and after refresh become square

### To Reproduce
Minimum repro [here](https://gist.github.com/NicholasLYang/eaba2b6ecce112e9936c7d5db1e6ade7)

### Screenshots
<img width="592" alt="Screen Shot 2020-01-27 at 1 57 20 PM" src="https://user-images.githubusercontent.com/7357863/73223661-db34d900-4134-11ea-9086-c90997bd015d.png">
<img width="589" alt="Screen Shot 2020-01-27 at 4 23 57 PM" src="https://user-images.githubusercontent.com/7357863/73223662-db34d900-4134-11ea-92a0-71f260f871c3.png">

### Additional Information

Thanks for your help!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
