### ISSUE TITLE
setBounds does not work correctly in Linux, `y` is not kept

### ISSUE THREAD

**Issue by hovancik** [electron/electron#21928]
* Electron version: 7
* Operating system: Debian Linux

### Expected behavior
https://www.electronjs.org/docs/api/browser-window#winsetboundsbounds-animate

 ```
Resizes and moves the window to the supplied bounds. Any properties that are not supplied will default to their current values.
```

### Actual behavior

If I only provide `height`, for example, `y` is not the same. 

### How to reproduce

  $ git clone https://github.com/hovancik/set-bounds-bug.git
  $ npm install
  $ npm start || electron .

Then you can click one links called `one`, `two`, `three` that change the `height` of bounds. You will notice that window goes slowly down, thus `y` of bounds is not the same. 

### Workaround-ish

always set whole bounds, from the first bounds. It kinda works: 
- with first change the `y` is changed a bit
- consecutive changes keep the `y` the same

### Note
- works fine on mac, didn't test on Windows

**Comment by vladimiry** [comment]
Can confirm the issue as a long standing. I experience it too (Xfce Desktop Environment), but was not firing the bug here.

> You will notice that window goes slowly down, thus y of bounds is not the same.

I guess the value it gets down is equal to the height of the task bar. The second guess is that the described behavior might differ on different Linux systems, ie it might be working well on some systems.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by hovancik** [comment]
@sofianguy , do I really need to create identical issue for this? Can't we reopen this one? Behavior is the same in electron 12 for me as it was for each version before on Debian Linux with KDE.

**Comment by hovancik** [comment]
Please subscribe here if you're interested in getting updates: https://github.com/electron/electron/issues/28128. This issue was closed by awesome electron bot.
