### ISSUE TITLE
BrowserWindow - center option does not correctly center vertically when set to true (but does when set to false)

### ISSUE THREAD

**Issue by 2called-chaos** [electron/electron#21979]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.11
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**
  * not aware

### Expected Behavior
The window should be centered horizontally and vertically when option `center: true` is provided

### Actual Behavior
The window is not correctly vertically centered with `center: true` but it is with `center: false`

### To Reproduce
The default electron-fiddle example (which is 7.1.8 but 7.1.11 is the same), just add `center: true`

### Screenshots
center false: ![Hello World! 2020-01-30 23-22-23](https://user-images.githubusercontent.com/218011/73495760-7b019980-43b7-11ea-9e5f-a8d5e1a0578c.png)
center true: 
![Hello World! 2020-01-30 23-23-42](https://user-images.githubusercontent.com/218011/73495827-9b315880-43b7-11ea-884b-def15191c9a0.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by valeriangalliat** [comment]
Same issue on 29.1.4
