### ISSUE TITLE
Project Dependencies has @types packages

### ISSUE THREAD

**Issue by Amoodaa** [electron/electron#21999]
If i understand correctly these should be dev dependencies, and shouldn't ship with electron zero-dependencies \*package\*
https://github.com/electron/electron/blob/720cf6eb276bf76f2b600f58cff47f92e7ebe9a5/package.json#L140-L143

**Comment by vladimiry** [comment]
It's this one https://github.com/electron/electron/blob/master/npm/package.json

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
