### ISSUE TITLE
Looks blurry with Windows Magnifier 2

### ISSUE THREAD

**Issue by Stediat** [electron/electron#22003]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7
* **Operating System:**
  * Windows 10 1903 
* **Last Known Working Electron version:**
  * Before 7

### Expected Behavior
When i use Windows Magnifier, items should not appear blurry

### Actual Behavior
When i use Windows Magnifier, items are blurry

### Screenshots
![e1bcf48b3c2f71fbf3418047e556037bf01045e4](https://user-images.githubusercontent.com/60404334/73600331-f0ec3900-454e-11ea-9b4a-3fdfefdb4ca1.jpeg)

### Additional Information
This is my second (and last, dont worry) attempt :-) I am not a programmer but I use Joplin. And they [sent me](https://discourse.joplinapp.org/t/joplin-looks-blurry-with-magnifier-since-v1-0-177/5509) here to report this behavior. According to them they switched to Electron 7 in v.1.0.177. And then the problem occured.

I hope you can help. Thank you.

**Comment by Stediat** [comment]
I found out that the last working version was 5.0.13

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
