### ISSUE TITLE
Not able to get user's current location

### ISSUE THREAD

**Issue by AnandK1100** [electron/electron#22005]
### Issue Details

I using electron with react js. I have followed all the steps explained to get Google API Key and activate all google geolocation/ geocoding / maps etc., API's. I have also added process.env.GOOGLE_API_KEY =  'AIza....' to main file. 
I'm fetching user's current location using 'navigator.geolocation.getCurrentPosition()' method but it shows 'Network location provider at 'https://www.googleapis.com/' : No response received.'
I have also enabled location services of my mac.

* **Electron Version:** ^7.1.11

* **Operating System:** macOS 10.14.4

### Expected Behavior
navigator.geolocation.getCurrentPosition() must return user current location

### Actual Behavior
getCurrentPosition method returns error 'Network location provider at 'https://www.googleapis.com/' : No response received.'

### To Reproduce
Simply call navigator.geolocation.getCurrentPosition() method

**Comment by erickzhao** [comment]
Was able to repro with a minimal example in Fiddle on 9 Nightly, 8 Beta, and 7. Not sure what the deal is, but it seemed to work just fine on a Testing build from `master`.

**Comment by erickzhao** [comment]
Hey @AnandK1100, I traced it back to an interaction with the Google API. It seems like you need to add a Billing Account to the Google API Project that your key is associated with.

I think I'll send a PR in to improve the documentation on our end to make this clearer.

**Comment by AnandK1100** [comment]
Hey @erickzhao, 
The same code is working on react (website) on localhost and we are running the same on our electron project. So why we need billing account for the electron?

**Comment by erickzhao** [comment]
@AnandK1100

From what I can gather, your code works on the browser because Google Chrome comes with working Google API keys built in, while the open-source Chromium does not ([source](https://chromium.googlesource.com/chromium/src/+/master/docs/chromium_browser_vs_google_chrome.md)).

Since we embed Chromium into the Electron framework, we don't have access to those built-in API keys, so it is up to downstream apps to generate and use their own.

Furthermore, the Enable Billing part is mandatory for all calls to the Geolocation API endpoint. For instance, calling `https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_API_KEY` with your favorite HTTP request client will also fail unless you have billing enabled for your API key's project ([source](https://developers.google.com/maps/documentation/geolocation/usage-and-billing)).

**Comment by AnandK1100** [comment]
Thanks @erickzhao, this worked for me

**Comment by danieltigse** [comment]
Just so you know, getting user's location is broken in version 11. Mac 10.15.4. Code:
```js
navigator.geolocation.getCurrentPosition(
    function(position) {
          // never triggered
    },
    function(error) {
          // never triggered
    }
);
```

**Comment by erickzhao** [comment]
@danieltigse if this is a regression, it'd be helpful to open a separate issue with an [Electron Fiddle](https://github.com/electron/fiddle) gist repro.

Bonus points: If this broke on `11.0.0`, Fiddle has a Bisect feature that allows you to quickly search for the nightly/beta version of Electron that caused the regression. This will help people narrow down the commit range that the regression could have been introduced in.

**Comment by shakkeelbhat** [comment]
for me  navigator.geolocation.getCurrentPosition is working fine on localhost but not when running on ip.
call made in django project from frotend js
