### ISSUE TITLE
Installing electron-quick-start fails

### ISSUE THREAD

**Issue by dcatteeu** [electron/electron#22017]
Trying to get started with electron-quick-start, but installation fails. When running `npm install`, `node install` hangs. I suspect that the electron release cannot be downloaded.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.11
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * None

```
$ npm --version
6.13.6
$ node --version
v13.7.0
``` 

### Expected Behavior

`npm install` finishes after at most a few minutes (I waited up to an hour)

### Actual Behavior

`npm install` hangs after printing:

```
> core-js@3.6.4 postinstall /Users/dcatteeu/projects/private/electron-quick-start/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.1.11 postinstall /Users/dcatteeu/projects/private/electron-quick-start/node_modules/electron
> node install.js
```

### To Reproduce

Follow the installation instructions for electron-quick-start:
```
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick-start
$ npm install
```

### Additional Information

Downloading `https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-darwin-x64.zip` directly from `https://github.com/electron/electron/releases/tag/v7.1.11` fails as well. The download starts, but is then stuck, and fails eventually. I tried multiple times (yesterday and today). 

I have no other network issues. 

I successfully downloaded `https://github.com/electron/electron/releases/download/v6.1.7/electron-v6.1.7-darwin-x64.zip`, but it way longer than expected (±1h instead of ±1 minute).

**Comment by benbut** [comment]
I have the same situation

**Comment by han814992037** [comment]
I have the same situation

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
