### ISSUE TITLE
Failed to load gRPC binary module because it was not installed for the current system

### ISSUE THREAD

**Issue by hariomgoyal64** [electron/electron#22023]
I am running electron v7.1.1 on linux-x64. When building an app using electron i am getting the following error:
Uncaught Exception:
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v7.1-linux-x64-glibc

Since, grpc runs on node environment, so i used 
npm install grpc --runtime=electron --target=7.1 --target_platform=linux --target_arch=x64 --target_libc=glibc but get same error.

 grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1

I checked with grpc with the same error but nothing useful found.
I removed node_modules, tried again. 
I used npm rebuild but nothing works.
Is there any way to get over this.? 

I also used electron v4.0 and 3.1 with npm install --runtime=electron --target=4.0/3.1

**Comment by dannypaz** [comment]
@hariomdebut having the same issue but with Electron 6.1.9. I will let you know if anything comes up

**Comment by skb1129** [comment]
You need to use the `electron-rebuild` package to rebuild the grpc modules on electron environment as mentioned here in this document: https://www.electronjs.org/docs/tutorial/using-native-node-modules#installing-modules-and-rebuilding-for-electron.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
