### ISSUE TITLE
Printer Problem With Device Name

### ISSUE THREAD

**Issue by aitldeveloper** [electron/electron#22029]
Since long this request is pending for printing with multiple printers...

Either silent:true is not working or print by device name is not working..

If someone can help us on an urgent basis as we have POS application completely developed and due to printing issues we are stuck in progress. 

We need to print bill on bill printer and KOT in kitchen printer...

Please forgive us if we have added this issue in other threads as well...

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
