### ISSUE TITLE
Gtk-WARNING **: cannot open display

### ISSUE THREAD

**Issue by zhenliliu** [electron/electron#22046]
When I use electron to do screen recording on the server under the centos server system, running the electron command will give an error: can not open display, How can I to resolve this issue

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
