### ISSUE TITLE
Question: How I can install Electron .nupkg files using PowerShell?

### ISSUE THREAD

**Issue by xmha97** [electron/electron#22045]
Hello,
How I can install Electron .nupkg files using PowerShell?
For example, I want to install `GitHubDesktop-2.2.4-full.nupkg`
![WinRAR](https://user-images.githubusercontent.com/23485114/73824222-042d2c00-480f-11ea-9365-cb7eb7e6d518.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
