### ISSUE TITLE
Support childProcess.spawn for files

### ISSUE THREAD

**Issue by mafintosh** [electron/electron#22047]
Hi! I've noticed in the docs that only execFile is currently supported under an asar archive, https://www.electronjs.org/docs/tutorial/application-packaging#executing-binaries-inside-asar-archive due to the other commands optionally accepting commands in addition to files.

I understand the limitation, but it would be really useful to be able to spawn processes with streaming stdout/stderr for use-cases such as embedding a daemon process etc. 

Has there been a discussion about supporting childProcess.spawn but only for file execution?

**Comment by nornagon** [comment]
NB the relevant part of the docs has since been removed (by https://github.com/electron/electron/pull/26239, not sure if that was intentional), but the behavior remains—we support `execFile` and `execFileSync` but not any of the `spawn*` variants.

The docs previously read:

> ### Executing Binaries Inside `asar` Archive
> 
> There are Node APIs that can execute binaries like `child_process.exec`,
> `child_process.spawn` and `child_process.execFile`, but only `execFile` is
> supported to execute binaries inside `asar` archive.
> 
> This is because `exec` and `spawn` accept `command` instead of `file` as input,
> and `command`s are executed under shell. There is no reliable way to determine
> whether a command uses a file in asar archive, and even if we do, we can not be
> sure whether we can replace the path in command without side effects.

Under the hood though, these commands just copy the file out of the asar onto disk and then execute the file from there. You're just as well served by shipping the binary unpacked—better, even, because the binary will be unpacked at install time rather than on first use.

I'm going to close this as wontfix because I think the benefit is marginal and the implementation complexity is high.
