### ISSUE TITLE
electron does not support public key credentials.

### ISSUE THREAD

**Issue by LianJilu** [electron/electron#22057]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Mac OS X 10_14_6
* **Last Known Working Electron version:**
  * 

### Actual Behavior

The user agent does not support public key credentials.
### Screenshots

![image](https://user-images.githubusercontent.com/25577583/73904789-2048d000-48d8-11ea-8061-1d0997ee6a09.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Specifically, we need a way to reproduce this. We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
