### ISSUE TITLE
wechat screenshot （微信截图）

### ISSUE THREAD

**Issue by pureZjr** [electron/electron#22059]
when i use wechat screenshot on my **mac**,it will be like [this](https://yim-dev.yidejia.com/android/b4d212d31cfd94a9917d2fcac82d94b6.mp4)

electron version is '7.1.7'

when i use version '4.2.12' is ok

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
