### ISSUE TITLE
Is there any option to add count down timer inside the message box

### ISSUE THREAD

**Issue by ManasaGowda-ui** [electron/electron#22065]
I would like to add countdown timer inside the dialog box . is it possible ? it should be like 10,9,8,6,5...0 
at 0 count this message box should get closed automatically.

![image](https://user-images.githubusercontent.com/60742045/73939951-87827680-4910-11ea-9058-c0e7ae683080.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
