### ISSUE TITLE
Random white pixels on electron apps. 

### ISSUE THREAD

**Issue by vinsevinalon** [electron/electron#22079]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.6
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
User Interface needs to run smoothly. 

### Actual Behavior
User Interface having random white pixels on the window. 

### To Reproduce
Reproducing is a little tricky. White pixels just show randomly. While scrolling, while hovering or changing tabs. 

### Screenshots

![Annotation 2020-02-07 132050](https://user-images.githubusercontent.com/8083286/73996842-e8fa2200-49b0-11ea-8951-7ad64609363a.png)
![Annotation 2020-02-07 121312 - 100%](https://user-images.githubusercontent.com/8083286/73996860-f8796b00-49b0-11ea-8e66-c029df0b71ca.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
