### ISSUE TITLE
"channel" and "args" props missed in webview "ipc-message" event when "contextIsolation" flag enabled

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#22085]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.0.0
* **Operating System:** Linux
* **Last Known Working Electron version:** none of v5/v6/v7, so unknown

### Expected Behavior

"channel" and "args" **props present** in webview "ipc-message" event

### Actual Behavior

"channel" and "args" **props missed** in webview "ipc-message" event

### To Reproduce

https://github.com/vladimiry-playground/electron-quick-start-context-isolation-webview-ipc-issue

### Screenshots

- `contextIsolation: false`
  ![false](https://user-images.githubusercontent.com/1560781/74029371-9bd07d00-49bd-11ea-9827-9e829a1cd255.png)
- `contextIsolation: true`
  ![true](https://user-images.githubusercontent.com/1560781/74029372-9c691380-49bd-11ea-8d73-675e056a7a35.png)

### Additional Information

What is the workaround aside of using main process as a communication bus? I mean a workaround for the communication between guest page and embedder page keeps working even if "contextIsolation" flag enabled.

CC @MarshallOfSound

**Comment by vladimiry** [comment]
This issue is currently blocking the `contextIsolation` enabling in https://github.com/vladimiry/ElectronMail.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
