### ISSUE TITLE
Thumbar buttons are disappeared after browserwindow hide and show

### ISSUE THREAD

**Issue by joojaeyoon** [electron/electron#22081]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Thumbar buttons should be visible after hide and show browserwindow.

### Actual Behavior

before hiding browser window
![before](https://user-images.githubusercontent.com/32611377/74004965-bfde8f00-49ba-11ea-996c-a04866d41c6b.png)

after hiding browser window and showing browser window
![after](https://user-images.githubusercontent.com/32611377/74004973-c2d97f80-49ba-11ea-86f5-b70150e779c5.png)

thumbar buttons are disappeared.
and i set thumbar buttons again after open(show) browserwindow, but it is not worked.

### To Reproduce

set Thumbar buttons and hide your browserwindow and show your browserwindow.
then your thumbar buttons will disappeared.

https://github.com/wow1548/YouTube-Music-Player

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
