### ISSUE TITLE
Spawning a detached process/unref()ing it doesn't work on Linux

### ISSUE THREAD

**Issue by shrewdlogarithm** [electron/electron#2208]
This is tested on the 0.29.2 Linux32 build.

I have something like this in my main.js

`var child = child_process.spawn(exepath, [], {detached: true});`
`child.unref();`
`console.log("quitting")`
`app.quit()`

I also have code which outputs when "before-quit", "will-quit" and "quit" events fire.

The exe being called takes a while to run - on Windows, it runs whilst Electron closes down - on Linux however, Electron doesn't seem to close AT ALL - not even when the spawned process completes (e.g. I suspect it's hitting an error?)

I get the "quitting" message (so the spawn isn't failed - the process runs), I then get messages from "before-quit", "will-quit" and "quit" - but the app continues to run (it's tray icon doesn't disappear and it's still in "ps")

Any ideas - anything I can do to debug this further?

**Comment by Mingling94** [comment]
1. This is node.js related, not electron related
2. Set the stdio pipes to not default to that of the parent
```js
var fs = require('fs'),
     spawn = require('child_process').spawn,
     out = fs.openSync('./out.log', 'a'),
     err = fs.openSync('./out.log', 'a');

 var child = spawn('prg', [], {
   detached: true,
   stdio: [ 'ignore', out, err ]
 });

 child.unref();
```
>When using the detached option to start a long-running process, the process will not stay running in the background unless it is provided with a stdio configuration that is not connected to the parent. If the parent's stdio is inherited, the child will remain attached to the controlling terminal."

**Comment by shrewdlogarithm** [comment]
Thanks - I tried that but Electron STILL doesn't quit (output is written into the out.log so that bit is working OK)

Even without that change, Electron should have quit AFTER the script completed - but it doesn't!?

Hence I think there's an error preventing quit from completing or some resource being held-onto - specifically on Linux (it works OK on Windows as far as I've tested)

**Comment by shrewdlogarithm** [comment]
I've posted a quick demo here

https://github.com/shrewdlogarithm/electron-spawn-problem

Obviously you'll need to use taskmgr/ps to check what's happening to the electron processes - but my testing here (on Mint Linux 32) shows that Electron does NOT terminate until the spawned/detached task ends (despite all events firing to suggest it does) - on Windows the processes DO end immediately?

**Comment by Mingling94** [comment]
Hmm, this is an interesting dilemma and may be electron related. In my own project, I spawn the detached child_process from a renderer process instead of the main. I can close my app while the child runs in the background fine enough. This would be on Ubuntu 14.04 64 bit though.

Check if the renderer process starting said process still behaves in this odd way on your system.

Lastly, it could be some unexpected `beforeunload` or `unload` handler, see [this part of the documentation](https://github.com/atom/electron/blob/master/docs/api/app.md#appquit)

**Comment by shrewdlogarithm** [comment]
I'll look into that - but this app doesn't HAVE a renderer window open all the time (it quite often exists only as a main, interacting through a tray menu) so...

I should also add that what I'm trying to do - ultimately - is restart the app (after doing some housekeeping and other stuff) - hence why I really need one to stop running before the other starts!!

Perhaps there's another way to force that to happen - but as-is, on Linux32 at least, the 'old' process is still running when the 'new' process starts.

**Comment by shrewdlogarithm** [comment]
p.s. just FYI, issue doesn't seem to affect OSX - I've not tried the 64bit Linux port yet but it's

Windows 32 OK
Linux 32 - Not Working
Linux 64 TBC
OSX 64 - OK

**Comment by Mingling94** [comment]
@shrewdlogarithm I totally forgot about this issue but I just encountered a similar situation to yours on Linux 64. My application hangs after `app.quit()` is certainly called until my detached process is closed manually as well. I found I was adding a listener, and thus a reference, from the main process to the detached child process.
```js
    processOpotions = {}
    let log = require('path').join(__dirname, 'out.log')
    let out = fs.openSync(log, 'a')
    let err = fs.openSync(log, 'a')
    processOptions.detached = true
    processOptions.stdio = [ 'ignore', out, err ]

    // Spawn my process
    const Process = require('child_process').spawn
    var myProcess = new Process(myCommand, processOptions)

    // Exclude it from the parent process' event loop if detached
    myProcess.unref()

    // Listen for erroring.
    // *** MY PROBLEM IS THE BELOW LINES ***
    myProcess.on('error', function (err) {
      self.emit('error', err)
    })
    myProcess.on('exit', function (code) {
      self.emit('exit', code)
    })
```

If I didn't have those listeners, the main process did not hang after `app.quit()` because then the main process doesn't have references to itself hanging about. Could this have been your situation, i.e., that your giving your detached child process references pointing to your main process?

**Comment by zcbenz** [comment]
Unable to reproduce in 0.37.x anymore.

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/41907495-a77731a6-7973-11e8-9ff9-06d855dfb8e5.png)
````js
"electron": "^2.0.2"
````
## still have the problem!  I am doing an auto-update program, so I need to exec it when it was downloaded. 

## The main browserWindow closed. But the tray is still there. When I close the new application. The tray disappeared. But It works well on the windows.

**Comment by sunzongzheng** [comment]
I skipped it by using app.relaunch with execPath
