### ISSUE TITLE
Electron App is always rendered in "dark mode" on Windows

### ISSUE THREAD

**Issue by maku** [electron/electron#22084]
### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Windows 10 (10.0.18362)

### Expected Behavior
 When I set the themeSource to "light" the app should be rendered correctly

### Actual Behavior
 Although I explicitly set 
`nativeTheme.themeSource = 'light';`
the app is rendered in dark mode

**Comment by habbes** [comment]
@maku I tried reproducing the issue on Nodejs 12.13.0, Chromium 80.-.3987 and Electron 8.0.0 on Windows 10 but it worked as expected. In particular, tried setting `nativeTheme.themeSource` to `light`, `dark` and `system` in different combinations of Windows Light and Dark mode, and in each case the app had the correct theme. Could you share more details (or code snippet) about where exactly you set the them source? If you put that statement in a function, are you sure the function is called?

**Comment by luketokheim** [comment]
* Electron version: 8.0.0
* Operating system: Window 10 Pro (Version 1909 Build 18363.592)

### Expected behavior

Setting `nativeTheme.themeSource = 'dark'` should make the `prefers-color-scheme` CSS query match `dark` mode.

As per docs:

https://www.electronjs.org/docs/api/native-theme#nativethemethemesource

### Actual behavior

The `prefers-color-scheme` media selector uses the settings from Windows as if the `themeSource` is `system`.

### How to reproduce

```
git clone https://github.com/luketokheim/electron-quick-start
npm install
npm start
```

- Windows in light app mode, Electron UI elements are dark but CSS media selector does not match dark.

![light](https://user-images.githubusercontent.com/3877224/74059326-aa5a6c80-499c-11ea-90c1-be2ec61a49a5.png)

- Windows in dark app mode, CSS media selector matches dark.

![dark](https://user-images.githubusercontent.com/3877224/74059311-a3cbf500-499c-11ea-9769-d8ebcd4a3377.png)

**Comment by maku** [comment]
@luketokheim  I tried it with the steps mentioned (cloning https://github.com/luketokheim/electron-quick-start, etc.)

But the result is the same. My windows setting is "**Dark mode**". When I set themeSource to "light" ( `nativeTheme.themeSource = 'light';`) the electron app is rendered in dark mode...

BTW, what I **have to do** after "npm install" is to provide electron "manually" -> see https://github.com/electron/electron/issues/20994 (otherwise I get an error: `Error: Electron failed to install correctly, please delete node_modules/electron and try installing again`)

**Comment by luketokheim** [comment]
Yes, I think have the same issue as you @maku. The Electron menu bar and UI elements toggle as expected but the CSS media selector does not match light/dark as it should (and did in Electron 7).

**Comment by gleb-grigoriev** [comment]
I have the same issue with electron  8.1.1 and win 10.0.18363.
Setting 'light' mode has no effect - app still has dark mode (as OS Win

  app.on('ready', () => {
    const { nativeTheme } = require('electron')
     nativeTheme.themeSource = 'light'; 
    createWindow();

  });

**Comment by Prinzhorn** [comment]
Same on Ubuntu 19.10. Just upgraded from Electron 7.1.7 to 8.0.1. `@media (prefers-color-scheme: light)` is always matching despite `nativeTheme.themeSource = 'dark';` (and `nativeTheme.shouldUseDarkColors` is true).

**Comment by Prinzhorn** [comment]
For me this is fixed in 9.0.0-beta.13 (see #22900). Can y'all confirm?

**Comment by abbrechen** [comment]
I jumped from 6.0.0 to 9.0.0-beta.18 and the bug is fixed on my Mac now. Thank you.

**Comment by erickzhao** [comment]
Closing, seems like this was fixed (tested with [Fiddle Gist](https://gist.github.com/151c3804bb771807c38fc4f0c8bc74bf)).
