### ISSUE TITLE
Main process doesn't connect to self-signed server.

### ISSUE THREAD

**Issue by pjebs** [electron/electron#22130]
Electron v8.0.0
OS: MacOSX

I have a self-signed https server. It definitely can be connected to because I've tested it with other client libraries.

When I try to connect to it **from** the **main process** it get an error.

According to this site: https://stackoverflow.com/questions/38986692/how-do-i-trust-a-self-signed-certificate-from-an-electron-app I have to subscribe to `certificate-error` on `app`.

That is not getting fired. I think there is a bug or regression.

A later comment from 2019 also confirms that the accepted solution doesn't work.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by pjebs** [comment]
@MarshallOfSound Do you want a Go based self-signed server too?

**Comment by pjebs** [comment]
I have provided a demo of the issue here: https://github.com/pjebs/electron-quick-start @ `https-self-signed` branch.

Step1: Install Go
Step2: run: `go get -u github.com/rocketlaunchr/https-go`
Step3: run server: `go run server.go`
Step4: run electron app.

You will notice error: `Error: unable to verify the first certificate`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
