### ISSUE TITLE
`session.clearStorageData()` should delete custom SpellChecker dictionary

### ISSUE THREAD

**Issue by erickzhao** [electron/electron#22161]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * macOS Mojave
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Session-specific data can normally be cleared using `session.clearStorageData()`. I would expect the `Custom Dictionary.txt` file added through the `storages` folder. `session.addWordsToSpellCheckerDictionary()` API to be removed.

We would also expect an option to include `'dictionary'` in the types of storage to be cleared.

### Actual Behavior
It's not touched. Note that the `Custom Dictionary.txt` file actually doesn't live in the `Session Storage` subfolder of the userData folder.

### To Reproduce
Open this Fiddle. Before running, ensure that the `Execution > Do not delete user data directories` is **enabled**.

https://gist.github.com/9c14da159033493e5c2396c0f4156526

Open the custom dictionary path logged to the console (something like `/Users/ezhao/Library/Application Support/spiffy-camp-swell/Partitions/ericktester`), and observe that `Custom Dictionary.txt` still exists.

**Comment by erickzhao** [comment]
Will leave this open, but there are some problems with how Chromium handles its custom dictionary files that prevent me from going forward with a definite fix:

* Deleting the `Custom Dictionary.txt` doesn't delete dictionary words saved in memory, so we have to call the `RemoveWord()` API internally to clear the in-memory dictionary.
* Calling `RemoveWord()` is synchronous, but also schedules a task to write the `Custom Dictionary.txt` file to disk.
* Being unable to know when the write to disk is completed, I can't seem to find a path forward that will allow me to delete `Custom Dictionary.txt` manually while avoiding a race condition with the `RemoveWord()` write to disk.

See WIP branch: https://github.com/erickzhao/electron/tree/fix/custom-dictionary-delete

In its current state, it successfully clears all words in the in-memory and disk custom dictionary, but fails to delete `Custom Dictionary.txt` or `Custom Dictionary.txt.backup` fairly often.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
