### ISSUE TITLE
Error while making build

### ISSUE THREAD

**Issue by AnandK1100** [electron/electron#22169]
### Issue Details
* **Electron Version:** 8.0.0
* **Operating System:** macOS 10.14.4
* **next :** 8.1.0
* **electron-builder:** "^22.3.2",

### Expected Behavior
I followed the steps described in 'https://medium.com/@johndyer24/building-a-production-electron-create-react-app-application-with-shared-code-using-electron-builder-c1f70f0e2649' to generate builds (.dmg and .exe file).
It gives error message for wrong configuration.

### Actual Behavior
.dmg and .exe should be generated

### To Reproduce
Make build with using next:
"build": "rimraf ./.next && next build"
then use "electron-builder" to generate .dmg and exe files

If this is not the correct way to make build then please guide me on how to make build with react+next+electron

**Comment by codebytere** [comment]
@AnandK1100 Thanks for reaching out, but this is an issue with a tutorial and not with Electron itself; please follow up there. 

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
