### ISSUE TITLE
Cannot require modules in forked child_process.

### ISSUE THREAD

**Issue by TongDaDa** [electron/electron#22184]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 6.0.0
  * 
* **Operating System:** OSX
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

It could require modules(node_modules, node's internal modules) in forked child_process just like in the main process.

### Actual Behavior

It cannot require **electron** and the any modules installed in node_modules.

### To Reproduce

```
// app/main-process/core/manager/index.js
const child_process = require('child_process');


let child = child_process.fork('./fork.js');
child.send('start');

// app/main-process/core/manager/fork.js
const request = require('request');
// It will throw an error that cannot find the request module
```

### Additional Information

My purpose to use the forked child_process is that I want to use persistent tasks(ie: although quit the app, it can also run tasks on the computer)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
