### ISSUE TITLE
Task Manager on showing just app name!

### ISSUE THREAD

**Issue by burakkp** [electron/electron#22183]
Hi folks, 

Showing just application name on Task Manager, Why i can't seen application active screen title name? Have any idea about this? 

I seen other applications doing this. I want this because we use AutoIT test automation, that tool using active window names. This testing tool looking to the "Chrome_WidgetWin_1" class name, but showing app name on this class by the Electron application. 

How can I figure out this problem? 
Could you help me?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
