### ISSUE TITLE
Something about 'will-prevent-unload' event

### ISSUE THREAD

**Issue by xland** [electron/electron#22181]
Win10 
Electron `6.x.x`  `7.x.x`  `8.0.0`

When render process register the `onbeforeunload` event
```js
window.onbeforeunload = () => false;
```
Main process listen `will-prevent-unload` event  to ask user if they want to close the window.
```js
  win.webContents.on('will-prevent-unload', event => {
    let choice = dialog.showMessageBoxSync({
      title:'do you want to close',
      buttons:['cancel','yes']
    });
    if(choice === 1)  event.preventDefault();
    //...
  })
```
But `showMessageBoxSync` method will block the whole main process.
And the asynchronous method can not prevent the `onbeforeunload` event.
```js
  win.webContents.on('will-prevent-unload', async event => {
    let choice = await dialog.showMessageBox({
      title:'do you want to close',
      buttons:['cancel','yes']
    });
    if(choice === 1) event.preventDefault();  //useless
    //...
  })
```

So sometimes you can't use either of these methods.
What should I do?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by xland** [comment]
I do not think this is not an issue
