### ISSUE TITLE
Add 'focus' & 'blur' events to BrowserView/WebContents

### ISSUE THREAD

**Issue by aziz512** [electron/electron#22201]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
When working with BrowserViews, there's no way to listen to focus changes on either BrowserView itself or its WebContents.

### Proposed Solution
On BrowserWindow, there are `focus` and `blur` events. The same events need to be emitted on BrowserView/WebContents.
i.e. : 
```
browserView.on('focus', () => {
    // view is focused, do stuff
});
```
or  
```
browserView.webContents.on('focus', () => {
    // contents are focused, do stuff
});
```

### Alternatives Considered
I can't think of a good way of working around this lack of functionality

**Comment by Lee182** [comment]
Hello I too would like the same event emitted. To keep track of the active. Though for my use case (applying a global keyboard shortcut to tab) I've gotten around with this.
```js
const { webContents } = require('electron')
webContents.getFocusedWebContents()
```

**Comment by mckravchyk** [comment]
It probably won't help with every scenario, but you can have a quasi-focus event by tapping to pointerdown.

Minimal example:
(add to preload, and ensure preload is also in iframes (option `webPreferences.nodeIntegrationInSubFrames: true`): 
```
document.body.addEventListener('pointerdown', () => { ipcRenderer.send('focus'); });
```

I say quasi-focus event because it will be emitted even when the webContents are already focused (but sometimes it's good enough). You could also try use it and implement tracking of which webContents are currently focused and put it together to emulate a real focus event. And if you use `webContents.focus()` - it would have to be taken into account as well.

Still, a built-in implementation would surely be appreciated :)
