### ISSUE TITLE
Clicking a draggable region on macOS sets document.activeElement to document.body

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#22208]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** `7.1.1`
* **Operating System:** `macOS 10.13.6`
* **Last Known Working Electron version:** Unknown, issues dates back to at least `4.1.5`

### Expected Behavior
Clicking a draggable region should match Windows and Linux and not affect `document.activeElement`

### Actual Behavior
Clicking/dragging a draggable region removes focus from the currently focused element and sets `document.activeElement` to the `<body />`

### To Reproduce
Run this Fiddle on macOS. The input is auto-focused. The focus is only lost when dragging on macOS: https://gist.github.com/f4ae630f4ad915d957ecad7babb16ebd

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Slapbox** [comment]
Still relevant in 11.3.0. I'm really surprised no one else is reporting this. Is this some weirdness particular to my machine that cannot be reproduced with the shared Fiddle?
