### ISSUE TITLE
dialog.showMessageBox does not observe 'dark' theme on Windows 10

### ISSUE THREAD

**Issue by rmraya** [electron/electron#22231]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

when `nativeTheme.themeSource` is set to `dark` , `dialogShowMessageBox()` shoud display a dark box. Works fine on macOS Catalina but fails on Windows 10.

### Actual Behavior

Setting `nativeTheme.themeSource='dark'` produced a light box when calling dialogShowMessageBox() on Windows 10.
![dialog_and_menu png](https://user-images.githubusercontent.com/7977584/74660021-12b30600-5174-11ea-9c7e-0526f6445706.jpg)

### Screenshots
In the attached screenshot you can see that the application menu is dark but the message box is light.

**Comment by rmraya** [comment]
Also happens in e.0.0 beta2 Windows.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by ArtemAvramenko** [comment]
@rmraya I don't think this is an Electron problem, as even Windows Explorer has the same thing:
![image](https://user-images.githubusercontent.com/11413326/197503398-7d48e048-49ea-4314-8381-107008f67274.png)

**Comment by crystalfp** [comment]
VS Code is based on Electron and has all message dialogs with dark theme. File selector instead are light as everywhere.
I'm using electron 25.3.2
