### ISSUE TITLE
Incorrect window size when using transparent window

### ISSUE THREAD

**Issue by tzach-chase** [electron/electron#22349]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.1
* **Operating System:**
  * Windows 10 (1909)

### Expected Behavior
`window.outerHeight` should be the same as defined in options.

### Actual Behavior
`window.outerHeight` is 64px while the value set in constructor options is 30. This blocks clicking below the window.

### To Reproduce
```javascript
const { app, BrowserWindow } = require('electron')

function createWindow() {
  let win = new BrowserWindow({
    width: 1000,
    height: 30,
    frame: false,
    transparent: true
  })

  win.loadFile('index.html')
}

app.whenReady().then(createWindow)
```

### Screenshots
![image](https://user-images.githubusercontent.com/56874121/75116997-66db5000-5676-11ea-8292-f3293d0ff519.png)

### Additional Information
Only happens when setting `transparent` to `true`.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
