### ISSUE TITLE
desktopCapturer.getSources() only detecting one screen in a multi-screen setup

### ISSUE THREAD

**Issue by EmptyCrown** [electron/electron#22364]
* **Electron Version:**
8.0.0
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
In most cases, desktopCaptuerer has been working fine, with the expected source names including `Entire Screen` in a single-monitor setup and `Screen 1` and `Screen 2` when there are two.

### Actual Behavior
However, in certain two-monitor setups, the source names only include `Entire Screen` instead of the expected `Screen 1` and `Screen 2`. So desktopCapturer is only able to record one of the screens. I am not sure what differentiates these setups from others. OS is Windows 10 across the board.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by liubo113** [comment]
I have a similar problem, I can only detect one window in a muti electron app setup, the desktop.getSources() returns:

![image](https://user-images.githubusercontent.com/28495577/78623100-770f5d80-78b9-11ea-9a9e-6e25a8acd9a2.png)

The `name` field is duplicated, and the id field is random, so electron application cannot detect it's own window.

Here is the code:

```js
'use strict'

const { desktopCapturer } = require('electron')

class WindowRecorder {
  client
  _mediaRecorder

  constructor(client) {
    this._handleDataAvailable = this._handleDataAvailable.bind(this)
    this._handleStart = this._handleStart.bind(this)
    this._handleStop = this._handleStop.bind(this)
    this.client = client
    return (async () => {
      await this._init()
      return this
    })()
  }

  start(ms) {
    this._mediaRecorder.start(ms)
  }

  stop() {
    this._mediaRecorder.stop()
  }

  async _init() {
    const source = await this._getCaptureSource()
    const mediaStream = await this._getMediaStream(source)
    let recorder = new MediaRecorder(mediaStream, {
      mimeType: 'video/webm; codec=h264',
    })
    recorder.ondataavailable = this._handleDataAvailable
    recorder.onstart = this._handleStart
    recorder.onstop = this._handleStop
    this._mediaRecorder = recorder
  }

  async _getCaptureSource() {
    let sources
    try {
      sources = await desktopCapturer.getSources({ types: ['window'] })
    } catch (err) {
      throw new Error(`failed to get sources ${err}`)
    }
    return sources.find(s => s.name === process.env.npm_package_name)
  }

  async _getMediaStream(source) {
    const constraints = {
      audio: false,
      video: {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: source.id,
        }
      }
    }
    let stream
    try {
      stream = await navigator.mediaDevices.getUserMedia(constraints)
    } catch (err) {
      throw new Error(`failed to get media stream ${err}`)
    }
    return stream
  }

  async _handleDataAvailable(evt) {
    if (evt.data && evt.data.size > 0 && this.client.readyState === WebSocket.OPEN) {
      this.client.send(evt.data)
    }
  }

  _handleStart() {
    console.log('start recording')
  }

  _handleStop() {
    console.log(`stop recording`)
  }
}
```

**Comment by CapOM** [comment]
Can you detect all the screens with Google Hangouts ?

**Comment by liubo113** [comment]
I use a random id for detecting the window.

**Comment by worldsayshi** [comment]
Okay so this seems to be related to switchable graphics (and I have very simple workaround that works for me). 

I have a MSI laptop with dual graphics Intel UHD 630 and Nvidia Geforce RTX 2060. I had the same issue of only one screen coming back from `desktopCapturer.getSources` and it seems I just managed to fix it by going into NVIDIA Control Panel and flipping the "Preferred graphics processor" setting from "High performance NVIDIA processor" to "Auto-select". When I switch this setting back I can reproduce the issue again.

(Background: I'm trying to use github.com/pavlobu/deskreen to turn another laptop into a second screen. To accomplish this I have a dummy hdmi adapter that tricks Windows into creating two screens.)

Electron Version:
11.2.1
Operating System:
Windows 10
Graphics Card:
Intel UHD 630 and Nvidia Geforce RTX 20260

Reproduction steps:
1. Connect hdmi dummy, or perhaps second display to hdmi output (of the Nvidia card?) - And check that Windows acknowledge the second display
2. Clone electron-quick-start master, currently at b7cc17cba0719d90f81aab2e90736ab0949a6cfa
3. Paste this at the end of main.js:
```
const { desktopCapturer } = require('electron')
setTimeout(() => {
  console.log("desktopCapturer.getSources");
  desktopCapturer.getSources({ types: ['screen'] }).then((sources) => {
    console.log("sources", sources.length);
  });
}, 0);
```
5. Go to NVIDIA Control Panel and set `Preferred graphics processor` to `High-performance NVIDIA processor`
6. Run it.

Expected: The console should print `sources 2`
Outcome: The console prints `sources 1`

**Comment by SteveYurka** [comment]
I'm having the same issue on a client's laptop, where I've been working on a screenshot/capture app.

    **Electron Version:**
    13.1.7
    Operating System:
    **Windows 10**
    **Last Known Working Electron version:**
    Unknown

**Expected Behavior**

desktopCapturer.getSources() should always return the correct amount of screens, eg 'Screen 1' and 'Screen 2' on a two monitor setup.

**Actual Behavior**

My personal computer correctly reports having 'Screen 1' and 'Screen 2' correctly, where my clients laptop only reports 'Entire screen' in a two monitor setup. We are both using Windows 10 for the OS with NVIDIA graphics.

**To Reproduce**

Not sure how this can be reproduced as it seems to be dependent on the laptop/computer setup.

**Screenshots**
**Additional Information**

It possibly seems like this is occurring on laptops, based on the above comments/posts. Possibly related to having multiple graphics processors, where each monitor is controlled by one of them separately. But this is just a random guess.

I dumped the contents of screen.getAllDisplays() and desktopCapturer.getSources() into a log file from my client's laptop:

**screen.getAllDisplays() reports:**

[2021-07-26 16:16:49.507] [info] 
{
  id: 2480450848,
  bounds: { x: -1920, y: -167, width: 1920, height: 1200 },
  workArea: { x: -1920, y: -167, width: 1920, height: 1160 },
  accelerometerSupport: 'unknown',
  monochrome: false,
  colorDepth: 24,
  colorSpace: '{primaries_d50_referred: [[0.6526, 0.3252],  [0.3303, 0.5945],  [0.1482, 0.0772]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}',
  depthPerComponent: 8,
  size: { width: 1920, height: 1200 },
  displayFrequency: 59,
  workAreaSize: { width: 1920, height: 1160 },
  scaleFactor: 1,
  rotation: 0,
  internal: false,
  touchSupport: 'unknown'
}
[2021-07-26 16:16:49.511] [info]  {
  id: 2528732444,
  bounds: { x: 0, y: 0, width: 1920, height: 1080 },
  workArea: { x: 0, y: 0, width: 1920, height: 1040 },
  accelerometerSupport: 'unknown',
  monochrome: false,
  colorDepth: 24,
  colorSpace: '{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}',
  depthPerComponent: 8,
  size: { width: 1920, height: 1080 },
  displayFrequency: 60,
  workAreaSize: { width: 1920, height: 1040 },
  scaleFactor: 1,
  rotation: 0,
  internal: true,
  touchSupport: 'unknown'
}

**desktopCapturer.getSources() reports:**

[2021-07-26 16:16:49.539] [info] 
{
  name: 'Entire Screen',
  id: 'screen:3:0',
  thumbnail: {
    toPNG: '[function] function toPNG() { [native code] }',
    toJPEG: '[function] function toJPEG() { [native code] }',
    toBitmap: '[function] function toBitmap() { [native code] }',
    getBitmap: '[function] function getBitmap() { [native code] }',
    getScaleFactors: '[function] function getScaleFactors() { [native code] }',
    getNativeHandle: '[function] function getNativeHandle() { [native code] }',
    toDataURL: '[function] function toDataURL() { [native code] }',
    isEmpty: '[function] function isEmpty() { [native code] }',
    getSize: '[function] function getSize() { [native code] }',
    setTemplateImage: '[function] function setTemplateImage() { [native code] }',
    isTemplateImage: '[function] function isTemplateImage() { [native code] }',
    isMacTemplateImage: false,
    resize: '[function] function resize() { [native code] }',
    crop: '[function] function crop() { [native code] }',
    getAspectRatio: '[function] function getAspectRatio() { [native code] }',
    addRepresentation: '[function] function addRepresentation() { [native code] }'
  },
  display_id: '2480450848',
  appIcon: null
}

**Comment by dengs-official** [comment]
I'm having the same issue on a client's laptop, and it's not  stable, sometime is one, sometime is two with screens

**Comment by ProdigyView** [comment]
Anyone resolve this issue?

**Comment by Galkon** [comment]
Seeing this on electron 31
