### ISSUE TITLE
Webview catch console errors

### ISSUE THREAD

**Issue by valerxx22** [electron/electron#22361]
----------

### Problem Description
I use the `webivew` to display different web pages in my electron app. However I want to catch all the incoming inputs inside the `webview` console.
I have added an event listener `console-message` for this as specified in the [documentation](https://www.electronjs.org/docs/api/webview-tag#event-console-message), but it seems that doesn't catch the error exceptions as:
`Failed to load resource: the server responded with a status of 502 (Bad Gateway)`

### Using console-message
Here is the example I use from the official documentation. Error is not caught.
```
  const webview = document.querySelector('webview');
  webview.addEventListener('console-message', event =>
    trackLogs(`WEBVIEW_LOG_EVENT: ${event.message}`)
  );
```
### Script injection
Here is an example where I try to inject the code, but it seems the error is caught, even before the injected script is called.
```
  const webview = document.querySelector('webview');
  function contentload() {
    webview.executeJavaScript(`
      window.onerror = function(error, url, line) {
        `trackErrors({acc:'error',` data:'ERR:'+error+' URL:'+url+' L:'+line});
      };
    `);
  }
  webview.addEventListener('did-start-loading', contentload);
```
### Question
How can I catch such inputs from the `webview` console and send them to my logger service?

**Comment by electron-triage** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
