### ISSUE TITLE
Electron prints a blank page

### ISSUE THREAD

**Issue by francoscarpa** [electron/electron#22379]
I want my app to print a page. The HTML page is correctly shown if I open it in a separate BrowserWindow, but the printing process shows only a blank page. No error is shown. The most important snippet of my code is this:

    const BrowserWindow = electron.remote.BrowserWindow;
    let win = new BrowserWindow({ width: 800, height: 500 })
    let urlFile = url.format({
       protocol: 'file',
       slashes: true,
       pathname: path.join(__dirname, 'scontriniHtml/' + nomeScontrino + "Cucina.html")
    })

    win.loadURL(urlFile);
    const options = { silent: true }
    win.webContents.print(options, (success, errorType) => {
       if (!success) console.log(errorType)
    });

**Comment by electron-triage** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by francoscarpa** [comment]
What does it mean to "fill the template"?

**Comment by codebytere** [comment]
@francoscarpa when you opened the issue there was a template. You deleted it before posting your issue, and as such we cannot triage your issue. It included, amongst other things, platform, os, version, repro steps. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by pouriamoosavi** [comment]
I have the same issue. Did you manage to fix it?
