### ISSUE TITLE
session setProxy default exclusive local (electron@8.0.1)

### ISSUE THREAD

**Issue by Falways** [electron/electron#22373]
I have a remote  socsk proxy addr, I want to use session setProxy to visit my resorce.
my resource addr are 127.0.0.1:1555 which deployed at remote server. If use socks proxy ,I could visit this resouce successfully!
My code such as:
```
session.setProxy({proxyRules: "socks5://127.0.0.1:1080",proxyBypassRules: ''})

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Falways** [comment]
finally I refer to chrome docs, I do it, I solved the problem by doing so.
session.setProxy({proxyRules: "socks5://127.0.0.1:2080",proxyBypassRules:"<-loopback>"})
