### ISSUE TITLE
Memory leak when calling drawImage with video element as source on a hidden canvas

### ISSUE THREAD

**Issue by hristoterezov** [electron/electron#22417]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.x.x
* **Operating System:**
  * macOS 10.15.1
* **Last Known Working Electron version:**
  *  6.x.x, 8.x.x

### Expected Behavior

Even if the canvas is not visible (because of setting display: none to an ancestor) calling CanvasRenderingContext2D.drawImage shouldn't cause a memory leak.
### Actual Behavior

Calling CanvasRenderingContext2D.drawImage allocates memory in the renderer process that isn't released until the canvas is displayed. Calling the method 5 times per second for a few minutes allocates more than 4GB of memory.
### To Reproduce

Electron Fiddle URL: https://gist.github.com/3ccac676acaaecacc19ecb2e7bcaa47a

### Screenshots

<img width="1636" alt="Screenshot 2020-02-27 at 5 11 12 PM" src="https://user-images.githubusercontent.com/1729265/75467902-3ea86580-5984-11ea-97e2-85de80547d52.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
