### ISSUE TITLE
Check local time of system (mac, linux, win10)

### ISSUE THREAD

**Issue by trae-op** [electron/electron#22413]
**electron: v7.1.11
node: v10.16.3
macOS: mojave**
Hi! I need to catch change the local time of my system. Maybe have module or something like this for catching the local time. Should be event running when local time changed. 
Can I do it for electron?
![image](https://user-images.githubusercontent.com/12648541/75441323-24f82580-5966-11ea-8803-f21b4bafee12.png)

**Comment by codebytere** [comment]
Realistically speaking, this is something that can fairly trivially be accomplished with a native node [addon](https://nodejs.org/api/addons.html).

In the interest of not introducing new features into core which can be flexibly bolted on and will increase maintenance burden and bloat API surface, this isn't something we'll be incorporating into core at this time. Should something change, i'll update this issue to reflect that.

**Comment by Slapbox** [comment]
@codebytere I've noticed that it seems like Electron takes about 30 seconds to start showing the new date after a system time change on Windows, but on Linux it seems to be instantaneous. I guess this is probably a Chromium thing since we're seeing the same delay in Chrome on Windows, but do you have any idea _why_ this is the case?
