### ISSUE TITLE
Add breakpad support for Mac App Store builds

### ISSUE THREAD

**Issue by jack-arms** [electron/electron#22433]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Crashpad is used by Electron's `crashReporter`, but it does not function correctly if the app is sandboxed. That means for Mac App Store apps, which have to be sandboxed, the crash reporter doesn't work at all.

### Proposed Solution
Allow using breakpad instead for MAS builds so that `crashReporter` can still be run for sandboxed apps.

MAS builds do not have the crash reporter bundled because of this in the build script: https://github.com/electron/electron/blob/master/BUILD.gn#L534

Could we instead add breakpad support for MAS similar to what's done for Linux? https://github.com/electron/electron/blob/master/BUILD.gn#L500

**Comment by wnajar** [comment]
This affects the [Messenger app in the Mac App Store](https://apps.apple.com/us/app/id1480068668), which is currently in a limited preview. For a variety of reasons we prefer distributing via each platform's app store but this is a major downside for us on MacOS. Adding breakpad support for Mac App Store builds would go a long way to give us confidence in Electron via the Mac App Store. Thank you!

**Comment by gtamas** [comment]
@wnajar @jack-arms 

Hi guys!

This crash / sandbox issue is my problem too.

Is it an absolute requirement to make your app sandboxed? Can you upload apps to App Store without this entitlement?

My app works perfectly without the "com.apple.security.app-sandbox" entitlement, but adding it breaks everything. The app crashes immediately and I'm getting the "EXC_BAD_ACCESS (Code Signature Invalid)" error.

Is there a good tutorial about how to make "sandbox" work with electron? I tried to Google it, but there seem to be many different guides and recommendations. I'm not sure which one to follow.  

I'm using electron builder 21.2.0 (which has electron-osx-sign) with Electron 6.1.9. 

My understanding is that in order to build a proper MAS package, I need to do the following:

- sign the app using "Mac App Distribution" and "Mac App Installer" certificates
- sign all native dependencies as well with the same certificates
- Request the following entitlements (besides the ones my app actually needs):

```
   <key>com.apple.security.application-groups</key>
    <array>
      <string>TEAM_ID.your.bundle.id</string>
    </array>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
```
Is there anything else I'm missing?

Thanks in advance for any help!

**Comment by nornagon** [comment]
Unfortunately, Breakpad isn't supported on mac in Chromium upstream, and it's beyond the scope of this project to restore such support. I'm not totally sure why crashpad is disabled in the MAS build, but I suspect it's due to usage of private APIs.

Perhaps the Mac App Store has some solution for collecting crash reports?
