### ISSUE TITLE
Version mismatch between V8 binary and snapshot (6.1.4->8.0.1, Windows 10)

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron/electron#22450]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.4 -> 8.0.1
* **Operating System:**
  * Windows 10 64-bit Build 1809, with a NVIDIA GPU & Intel CPU
* **Last Known Working Electron version:**
  * 6.1.4

### Expected Behavior
Have Signal Desktop v1.31.0-beta.2, running on Electron 6.1.4, installed. Automatically update to v1.32.0-beta.2, on Electron 8.0.1. Start up successfully.

### Actual Behavior
The new Signal Desktop fails to start:

```
Fatal error in , line 0
Version mismatch between V8 binary and snapshot.
V8 binary version: 7.6.303.31-electron.0
Snapshot version: 426.16-electron.0
The snapshot consists of 622528 bytes and contains 3 context(s).
#FailureMessage Object: 00000034DF2FE5A0
```

### To Reproduce
We've only had one user report this, so it's not necessarily reproducible. Mostly we're looking for reasons this might happen, ways to avoid it and fix it.

**Comment by nornagon** [comment]
I'm not quite sure how the user could have arrived at a snapshot version of `426.16-electron.0`, as snapshot blob version numbers ought to have at least two `.`s in them before the `-`. The snapshot version should identical to the V8 binary version, and afaik `426.16-electron.0` has never been a V8 binary version. Perhaps it got corrupted somehow?

**Comment by asadmalik3** [comment]
One of our user out of 12 users is facing this very same issue. Our version of electron is: **8.2.0**. @scottnonnenberg-signal were you able to resolve this?

**Comment by scottnonnenberg-signal** [comment]
@asadmalik3 Sadly, no, never figured out the root cause. A reinstall seemed to address it.

**Comment by chalkplum** [comment]
#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 8.0.426.27-electron.0
#    Snapshot version:
# The snapshot consists of 622528 bytes and contains 0 context(s).

joke

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
