### ISSUE TITLE
Main window reload, after clicking <a href></a>, if print window is open

### ISSUE THREAD

**Issue by FitsnerAS** [electron/electron#22460]
After opening print window and if DOM of main window contains `<a href>` without parameters, such links become clickable and main window reload the page.

### Issue Details
After opening print window and if DOM of main window contains `<a href>` without parameters, such links become clickable and main window reload the page.

* **Electron Version:**
  * 7.1.11
* **Operating System:**
  * Windows 10 (1809) 
*
### Expected Behavior
click on `<a href>` links shouldn't call  main window reload if print window is open. 

### Actual Behavior
If print window is open, then main window become unlickable, except `<a href>` links (href without parameters). If you click on suck link, main window is reloading and become clickable.

### To Reproduce
1. Open print window with contents.print();
2. Click on `<a href></a>` on main window

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
