### ISSUE TITLE
electron mac Left slide full screen？【Graphic】

### ISSUE THREAD

**Issue by w602542704** [electron/electron#22471]
electron mac Left slide full screen？Why not enlarge the full screen？What's the reason?

![20200302_115647 (1)](https://user-images.githubusercontent.com/24689873/75644466-5e3dd780-5c7d-11ea-8ed6-9f02cf40906e.gif)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
