### ISSUE TITLE
Electron Freezing on Certain Linux Machines

### ISSUE THREAD

**Issue by kenpowers-signal** [electron/electron#22477]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.1
* **Operating System:**
  * Xubuntu 19.10 and Kernel: 5.3.0-40-generic, i3 4th gen, 8GB Ram, SSD disk
  * Xubuntu 19.10 x64, Linux kernel 5.5.5
* **Last Known Working Electron version:**
  * v6.1.4

### Expected Behavior

Electron apps should start, and failing to start should give good debugging information for developers to work with.

### Actual Behavior

We upgraded Electron to 8.0.1 for our latest beta, and we have some Linux users reporting that Signal freezes at a blue screen on startup. So far we're unable to reproduce this on virtual machines and suspect it may be a hardware issue.

As we aren't 100% sure what the issue is and it only occurs on certain Linux machines, we're primarily looking for guidance on how to further debug this before we make a production release.

### Additional Information

We think https://github.com/electron/electron/issues/21415 may be related.

**Comment by PEPERSO** [comment]
I have also experienced problem depending on the OS : on Lubuntu, the electron app I use ([Min browser](github.com/minbrowser/min) uses around 650MB of RAM, whereas on Trisquel 9 (which is based on the same Ubuntu 18.04 version), with the exact same `.deb` file, it uses less than 200MB of RAM. Same for Manjaro 20.1 and Windows, less than 300MB... It is also reported to be higher RAM usage on Linux Mint...

Shall I open a new Electron issue for this ?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
