### ISSUE TITLE
Synchronous WebAssembly compilation in a NODE_OPTIONS --require script crashes in 8.0.x

### ISSUE THREAD

**Issue by Mike-Dax** [electron/electron#22495]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.x
* **Operating System:**
  * macOS 10.14.6 
* **Last Known Working Electron version:**
  * Doesn't crash in 9.0.0

### Expected Behavior
When using NODE_OPTIONS to pass a `--require` script that synchronously compiles a WebAssembly module, it should not crash.

### Actual Behavior
It crashes in 8.0.0, not in 9.0.0 beta.

### To Reproduce
I have a reproduction repo at https://github.com/Mike-Dax/electron-sync-webassembly-compilation

```sh
git clone https://github.com/Mike-Dax/electron-sync-webassembly-compilation.git
yarn install
yarn dev:require
```

### Additional Information

This came to view because of Yarn PnP's automatic injection of a --require script (that includes synchronously instantiated WebAssembly.) 

https://github.com/electron/electron/issues/22472

Given that `--require` doesn't work in a packaged app, should `--require` be explicitly disallowed in NODE_OPTIONS in development as well? 

Does this not crashing in the 9.0.0 beta have something to do with https://github.com/electron/electron/pull/20857?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
