### ISSUE TITLE
When will BrowserView stop being experimental?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#22504]
Excuse me for misusing the Electron issues, but I don't know where else to get a response to this.

BrowserView is still [marked as experimental](https://www.electronjs.org/docs/api/browser-view#new-browserviewoptions-experimental) in Electron 8. Are there plans to remove the label, or are we waiting for it to bake for a few more releases? Or is it experimental while webview issues are being worked out?

Thanks

**Comment by thecorsair** [comment]
same question

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by pushkin-** [comment]
@miniak I'm not interested in the community helping, I'm interested in the Electron team helping since only they can know the answer to this.

If BrowserView is meant to not be experimental and this is a documentation issue, then the task that needs to be completed is the Experimental label needs to be dropped. I wanted to check if that is indeed the case.

I'll ask on slack anyway

**Comment by pushkin-** [comment]
reposted question [here](https://discuss.atom.io/t/when-will-browserview-stop-being-experimental/74919)
