### ISSUE TITLE
Tray icon not showing on Elementary OS

### ISSUE THREAD

**Issue by Akumzy** [electron/electron#22550]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:*8.0.3*
  * 
* **Operating System:*elementary OS 5.1.2 Hera*
  * 
* **Last Known Working Electron version:*7.0.0*
  * 

### Expected Behavior

Expected Tray icon to display on app startup
### Actual Behavior

The Tray icon is not showing
### To Reproduce

[Repo](https://github.com/Akumzy/electron-tray-icon-not-working-on-elementary-os)

**Comment by vladimiry** [comment]
This is likely because Elementary OS doesn't implement the [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) standard support.

**Comment by Akumzy** [comment]
@vladimiry is there any workaround to this issue that you know?

**Comment by vladimiry** [comment]
@Akumzy, I listed some workarounds for other systems in [this](https://github.com/electron/electron/issues/21445#issuecomment-565710027) message but I'm unfortunately not aware of the existing workarounds for Elementary OS. The wild guess is to try to do something like described in the following articles:
- https://www.addictivetips.com/ubuntu-linux-tips/re-enable-app-indicators-on-elementary-os/
- https://www.linuxuprising.com/2018/08/how-to-re-enable-ayatana-appindicators.html

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
