### ISSUE TITLE
Atom does not run over NX

### ISSUE THREAD

**Issue by Weuxel** [electron/electron#2256]
Atom does not start in an NX environment.

App load time: 150ms
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[7643:0716/110551:ERROR:gl_surface_glx.cc(357)] GLX 1.3 or later is required.
[7643:0716/110551:ERROR:gl_surface_x11.cc(56)] GLSurfaceGLX::InitializeOneOff failed.
[7643:0716/110551:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[7643:0716/110551:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
atom: Fatal IO error 11 (Ressource is not available) on X server :1000.0.

Sent here from: https://github.com/atom/atom/issues/7928

**Comment by zcbenz** [comment]
If Chromium works in it Electron should probably support it too, but I don't think anyone would actually look into it.

**Comment by Weuxel** [comment]
Yeah, Chromium works without problems, in fact Atom is the first Application i encountered that does not.
Would be sad if noone would look into it.

**Comment by volth** [comment]
It works with NoMachine's NX.
It does not work with x2go (open-source NX) and xrdp (open-source RDP).

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by timholy** [comment]
This issue still has reasonably recent activity: https://github.com/Microsoft/vscode/issues/3451
I was able to hack around this problem using tips in that issue, but modifying Xlibs is a little on the scary side.

**Comment by rob3c** [comment]
What does "abandonment" mean? This is listed as the upstream issue for both the Atom and VS Code editors, two fundamentally important parts of Atom Shell's...err, Electron's history.

**Comment by Lusitanian** [comment]
Why is this issue abandoned?

**Comment by gabefair** [comment]
This should really be reopened.

**Comment by jblee123** [comment]
Does "Closing due to abandonment" mean, " We're choosing to abandon this because we don't care," or "It looks the community doesn't care,"? Because if it's the latter, I think people still obviously care. Hacking a binary file isn't a quality solution (and that only worked once for me -- I'm now back to getting the same error even with the hacked file).

**Comment by sitsofe** [comment]
(Note that https://github.com/ArcticaProject/nx-libs/pull/729 strongly suggests this occurs due to servers (that are acting as X) not containing an old fix from 2007)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
