### ISSUE TITLE
Does Electron support Dual screens (Win 10x)

### ISSUE THREAD

**Issue by aRajeshKumar** [electron/electron#22575]
Hello,

Could you let us know if Electron can support Dual screens on Win10x ?

https://docs.microsoft.com/en-us/dual-screen/introduction

Regards,
Rajesh

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
