### ISSUE TITLE
dialog.showMessageBoxSync defaultId not work under windows OS.

### ISSUE THREAD

**Issue by ForJason** [electron/electron#22580]
Electron Version: 8.0.0
Testing OS: Win7, Win10, Ubuntu 14.04
`dialog.showMessageBoxSync(null, {
		type:'warning',
		buttons: ['Yes', 'No'],
		defaultId: 1,
		cancelId: 1,
		title: 'Power Control',
		message: "Warning!",
	});
`
Execute the function, in windows OS, it focus on the "Yes" button, but it focus on the "No" button in Ubuntu.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ForJason** [comment]
Thanks for your patience, I will resubmit the question according to the template.

> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀
