### ISSUE TITLE
Our application sometimes load images from disk cost too much time in Windows system, but MacOS never

### ISSUE THREAD

**Issue by fehengli** [electron/electron#22603]
It perform very well most of time in Windows, but sometimes it perform weakly. The size of image is smaller than 4MB.

**Comment by fehengli** [comment]
Sometimes it can block the render process

**Comment by delmes** [comment]
I also meet this problem, anynone know what's up.

**Comment by fehengli** [comment]
electron version is 6.0.12

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
