### ISSUE TITLE
client certificate (windows cert store)

### ISSUE THREAD

**Issue by tripower** [electron/electron#22629]
hi

is it a bug or feature that only certificates will be found
which are at the cert store of the current user and not of the local machine?

regards
klaus

![cert store](https://user-images.githubusercontent.com/25051422/76286761-3533cd00-62a3-11ea-9596-e392f98e2355.JPG)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
