### ISSUE TITLE
Our application sometimes load images from disk cost too much time in Windows system, but MacOS never

### ISSUE THREAD

**Issue by fehengli** [electron/electron#22628]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:6.0.12**
  * 
* **Operating System:Windows**
  * 
* **Last Known Working Electron version:4.0.16**
  * 

### Expected Behavior
loading images don't block the render process

### Actual Behavior
loading images sometimes block the render process

### To Reproduce

Loading much images from disk in Windows system.

### Additional Information

Our Application is a IM application which load many avatars from disk. Sometimes it can block the render process.Maybe it is a bug of chromium.Together, useing <img src="file://"> to load some images can cost about 10 seconds, but we use base64 instead of 'file://' cost less.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
