### ISSUE TITLE
--lang parameter does not work for en-AU locale

### ISSUE THREAD

**Issue by cln650** [electron/electron#22630]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
Setting `electron . --lang=en-AU` will set the locale to `en-AU`.
`app.getLocale()` should return `en-AU`

### Actual Behavior
`app.getLocale()` returns `en-US`

### To Reproduce
Start the application by `electron . --lang=en-AU`

### Additional Information
In the documentation: [Locales](https://github.com/electron/electron/blob/v8.0.2/docs/api/locales.md) en-AU locale is present as a return value for `app.getLocale()`

**Comment by calinchiper** [comment]
If I pass the `--lang=en-AU` in chrome ,`navigator.language` returns `en-GB`. I guess the chromium handles Australian locale as GB. Can someone find an explanation or a possible solution?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
