### ISSUE TITLE
Window height cannot be lower than 39 on Windows

### ISSUE THREAD

**Issue by virtuecoder** [electron/electron#22653]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:** 8.0.1
* **Operating System:** Windows 10 (1803) 
* **Last Known Working Electron version:** 7.0.0

### Expected Behavior
Window height should be 25

### Actual Behavior
Window height is 39

### To Reproduce

``` javascript
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const win = new BrowserWindow({
    width: 400,
    height: 25,
    frame: false,
    show: false,
    thickFrame: false,
  });

  win.loadURL('https://github.com').then(() => {
    win.webContents.executeJavaScript(
      'document.body.innerHTML = innerHeight;' +
      'document.body.style.boxShadow = "inset 0 0 0 1px lightblue";');
  });

  win.once('ready-to-show', () => {
    win.show();
    win.setSize(400, 25);
  });
});
```

### Screenshots
Window on electron 7.0.0:
<img width="422" alt="Screenshot 2020-03-11 at 16 42 53" src="https://user-images.githubusercontent.com/1092912/76437159-6bfc0700-63b9-11ea-91bd-531bbea32183.png">

Window on electron 8.0.1:
<img width="421" alt="Screenshot 2020-03-11 at 16 43 02" src="https://user-images.githubusercontent.com/1092912/76437062-4a028480-63b9-11ea-8244-fb0668fb1b84.png">

### Additional Information
It is not compataible with Mac OS which displays window of height 25 even without `setSize` on `ready-to-show`, and that is how it should work on Windows 10 as well, IMHO. It should be possible to decide whether to display scrollbar for the window content or not.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
