### ISSUE TITLE
Browser's url not changed after 302 when using interceptStreamProtocol

### ISSUE THREAD

**Issue by liximomo** [electron/electron#22666]
### Issue Details

* **Electron Version:**
  * 8.1.1
* **Operating System:**
  * MacOS 10.15.3
* **Last Known Working Electron version:**
  * N/A

```js
interceptStreamProtocol('http', (request, callback) => {
  if (request.url.indexOf('http://www.google.com') === 0) {
    setTimeout(() => {
      callback({
        data: null,
        statusCode: 302,
        headers: {
          Location: 'http://www.github.com'
        }
      })
    }, 300)
  } else {
      callback({
        data: request('http://github.com'),
        statusCode: 200,
      })
  }
}

window.loadURL('http://google.com')
```

### Expected Behavior
browser shows the contents of 'http://github.com' and the `window.location.href` equals to 'http://github.com'.

### Actual Behavior
browser shows the contents of 'http://github.com' but the `window.location.href` is still 'http://www.google.com'.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
