### ISSUE TITLE
 display no full screen

### ISSUE THREAD

**Issue by lichaomeng** [electron/electron#22679]
centos7:  Linux localhost.localdomain 3.10.0-1062.9.1.el7.x86_64
	     CentOS Linux release 7.7.1908

Electron version: 7.1.9
![issus](https://user-images.githubusercontent.com/25163978/76609290-1b6be180-6552-11ea-8a19-7d488749161c.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
