### ISSUE TITLE
7.1.14 crashed: SimpleURLLoaderWrapper.<anonymous>

### ISSUE THREAD

**Issue by jackple** [electron/electron#22676]
### Issue Details

* **Electron Version:**
7.1.14

### Actual Behavior
have a blank screen problem

### To Reproduce
[2020-03-12 19:09:12.633] [main] [info] app ready, current APP_ENV:  prod
[2020-03-12 19:09:14.232] [main] [error] {
  constructor: 'Error',
  stack: 'Error: net::ERR_FAILED\n' +
    '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2545:21)\n' +
    '    at SimpleURLLoaderWrapper.emit (events.js:203:13)\n' +
    '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)\n' +
    '    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)'
}

### Screenshots
![image](https://user-images.githubusercontent.com/6183232/76582836-67973180-6512-11ea-8c85-2260c10cc65e.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. That's also a stacktrace, not a reproducible piece of code. In order for the maintainers to look at this, you'll need to include something we can run to replicate the issue.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by ms-dosx86** [comment]
@jackple were you able to solve your problem? I have faced the same issue while implementing auto updating feature with electron-builder.

**Comment by flashyu** [comment]
@jackple were you able to solve your problem? I have faced the same issue

**Comment by jackple** [comment]
@flashyu  I had gradually upgraded to 9.x, and this is no longer a tricky problem for me.

**Comment by guigechen** [comment]
> @jackple were you able to solve your problem? I have faced the same issue while implementing auto updating feature with electron-builder.

i do autoupdate, first time is successfull ,but stop java service ,nextime autoupdate fails.whats matter

**Comment by guigechen** [comment]
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. That's also a stacktrace, not a reproducible piece of code. In order for the maintainers to look at this, you'll need to include something we can run to replicate the issue.
> 
> We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

i also discount this problem
