### ISSUE TITLE
internal/modules/cjs/loader.js:985

### ISSUE THREAD

**Issue by imty2** [electron/electron#22697]
I am using VS8 with nodejs. When i attempt to run process.argv I don't see the arguments array. I am using windows 10. The error message i get is internal/modules/cjs/loader.js:985. I don't know what this means. I would appreciate any help.

thanks,
MT

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
