### ISSUE TITLE
When running the app, the screen is blank.

### ISSUE THREAD

**Issue by rhslvkf** [electron/electron#22700]
When the electron app, which was used well without problems, suddenly runs, the screen becomes blank.
The execution is normal, but the URL called by loadURL function is not displayed on the screen after execution.
The source code and execution screen are as follows.

![image](https://user-images.githubusercontent.com/16009350/76724753-6a528a80-678f-11ea-9f2f-ec678a923de2.png)

![image](https://user-images.githubusercontent.com/16009350/76724789-8bb37680-678f-11ea-9588-543b02c42b39.png)

It is difficult to find the cause because there is no error log. The loadURL function doesn't seem to work properly, but I don't know how to fix it.
Please help.

**Comment by jean-emmanuel** [comment]
Could be the same issue we're having [here](https://github.com/jean-emmanuel/open-stage-control/issues/599), it seems to be related to the gpu, because disabling hardware acceleration fixes it in our case.

This occurs on windows and when run from a terminal the following error is printed : 
`[4084:0315/190151.075:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.`

**Comment by aswinsekar** [comment]
Is this issue fixed in electron 8?

**Comment by lucasyvas** [comment]
See something similar in some windows in 7.2.1 and I'm at a loss. Only in Windows (32-bit) bundle. (Windows 10 64)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
