### ISSUE TITLE
H5 Notification on windows 10

### ISSUE THREAD

**Issue by mbigger** [electron/electron#22712]
![image](https://user-images.githubusercontent.com/10558740/76820721-e2c85280-6846-11ea-81c5-93b351d2387f.png)

Could anybody help me？ 
How can I change or cancel the String in above image "electron.app.XXXXX"？
**In debug mode, it shows 'electron.app.Electron', in Release mode, it shows "electron.app.{appName}".**

OS: windows 10 x64
Electron: 8.1.1

My code in Render Process:
```
const updateOnlineStatus = () => {
        let onLine = navigator.onLine;
        if (onLine) {
            log.info('online');
        } else {
            log.info('offline');
        }
        new Notification('网络连接状态变化', {
            body: onLine ? '上线' : '离线',
            icon: onLine ? '../assets/images/connected.gif' : '../assets/images/disconnected.png'
        });
    }
    window.addEventListener('online', updateOnlineStatus);
    window.addEventListener('offline', updateOnlineStatus);
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by xudafeng** [comment]
@mbigger https://github.com/electron/electron/issues/11290#issuecomment-670828109
