### ISSUE TITLE
PiP doesn't work properly 

### ISSUE THREAD

**Issue by alirezavalizade** [electron/electron#22717]
I updated to electron v7, but the PiP feature doesn't work properly. Actually it has the feature on video tag controls but when you click on it, it doesn't show anything, I only see something like this.

![image](https://user-images.githubusercontent.com/14992757/67330434-9f2e1e80-f51c-11e9-9a1b-ee5312152cee.png)

https://github.com/electron/electron/pull/17686#issuecomment-545144393

**Comment by TeraNovaLP** [comment]
I have the same problem. When I try to open a twitch stream in PiP, a window opens but it is only black.

Electron version: 8.2.4
OS: Windows 10 1909

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
