### ISSUE TITLE
Mouse cursor of presenter in screenshare is not visible

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron/electron#22716]
* **Electron Version:**
  * 7.1.11
* **Operating System:**
  * Windows 10 (Build 18362)

### Expected Behavior
Mouse cursor is visible

### Actual Behavior
Mouse cursor is not visible

### Additional Information
Laptop with two external monitors and two graphic cards (Intel and NVIDIA)
If the presenter makes a screenshare and shares one of the external monitors (not the laptop’s which is the main monitor), the movements of the mouser pointer are not visible to the viewer. 
BUT when the presenter moves the cursor in any other screens except from the shared one, then the mouse pointer is visible to another side. It looks like the pointer have offset of the full monitor width.
Laptop screen (full HD) configured as the main one and two external screens (also full HD) configured on the right of the main one. One of the screens in connected with DVI-D cable on the docking station and the second one with display port also connected on the docking station.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
