### ISSUE TITLE
electron version: 6.0.1

### ISSUE THREAD

**Issue by htrlq** [electron/electron#22714]
error execute BrowserWindow Remote method 'setPosition' or 'setBounds' fault
renderer process execute fault
`
currentWindow.setPosition(screenInfo.x,  screenInfo.y);//currentWindow.setPosition(x: screenInfo.x, y: screenInfo.y );
`
exception:
`
C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:219 Uncaught Error: Could not call remote method 'setPosition'. Check that the method signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 2
`

`
            currentWindow.setBounds({
                x: screenInfo.x,
                y: screenInfo.y,
                width: screenInfo.width,
                height: screenInfo.height
            })
`

exception:
`
C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:219 Uncaught Error: Could not call remote method 'setBounds'. Check that the method signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>
`

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
