### ISSUE TITLE
new Tray() randomly crashes in Linux (KDE neon) when used from remote

### ISSUE THREAD

**Issue by SevenSystems** [electron/electron#22725]
I've created a BrowserWindow, which loads a JS file via a `<script>` tag, and that JS file does  `var electron = require('electron').remote`. Calling `new electron.Tray('icon')` results in a complete application crash (the BrowserWindow closes and `npm start` exits) **almost** every time (it doesn't crash maybe one out of 10 times). There is no relevant console output in the terminal where I did `npm start`.

The same code works perfectly if executed directly from main.js (not from a BrowserWindow through `remote`).

The reason why we want to execute this from a BrowserWindow is that we're integrating Electron into an existing large-scale multi-platform app development framework, and it's much easier to integrate this way.

IMPORTANT UPDATE: The crashing seems to only happen if we do `window.Electron = require('electron').remote`. It seems to somehow "overwhelm" the browser process? If we only require the required modules explicitly and in a local variable, it doesn't seem to crash.

Electron version: 12.13.0
Operating system: Linux (KDE neon 5.18.3)
Kernel version: 5.3.0-42-generic

**Comment by holycleugh** [comment]
I'm running into similar issues and believe `tray.setContextMenu(null)` is a workaround.

See https://github.com/electron/electron/issues/22137#issuecomment-586105622 and https://github.com/electron/electron/issues/22652.

**Comment by jsjolen** [comment]
Similar issue here, `new Tray()` in the main process crashes electron.

KUbuntu 19.10, Electron 8.2.0, 5.3.0-42-generic kernel

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
