### ISSUE TITLE
Object passed via contextBridge equality check fails

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#22740]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8.0.2

### Expected Behavior

Same object passed via contextBridge allows equality check

### Actual Behavior

Equality check fails

### To Reproduce

- clone https://github.com/kwonoj/ctx-bridge-reference
- `npm run prev` : shows `true` in console
- `npm run curr` : shows `false` in console

When preload script exposes fn to return certain object's reference (i.e array), 

```
// preload.js

const ref = []
contextBridge.exposeInMainWorld('desktop', {
  store: {
    getState: () => ({
      a: ref
    })
  }
});
```

Renderer process could check if object is same or not:

```
const y = window.desktop.store.getState().a;

const state = {
  noti: window.desktop.store.getState().a
}

console.log(Object.is(state.noti, y)); //this was true
```

from Electron 8.1.1, this check no longer works and `Object.is` returns false.

I am not sure if this is expected change or not - but at least this seems breaking change. We use redux in renderer process passed via preload to synchronize to main process and any state contains array now triggers infinity render cycle since shallow equality for state doesn't pass.

### Screenshots

![image](https://user-images.githubusercontent.com/1210596/76938775-75eba180-68b4-11ea-93ec-7caed7e9b53f.png)

**Comment by kwonoj** [comment]
This issue is more of to get clarification if this is expected behavior, not requesting to change any behavior in electron.

**Comment by MarshallOfSound** [comment]
This is expected.  Object identity was never part of the API spec and by nature of it being present it caused significant issues when mutated objects were sent multiple times across the bridge.

i.e. if you sent an object over the bridge, modified a property and then sent it again, it wouldn't know about the updated property and would just use the old cached version.  This was incredibly unpredictable and fundamentally unsolvable so we reduced object identity caching to per-transaction so that recursive objects still work but multiple transactions will generate multiple objects.

This aligns with how IPC and postMessage and other cross-boundary APIs work.
