### ISSUE TITLE
Frameless transparent resizable window maximize or restore invalid

### ISSUE THREAD

**Issue by kf53916** [electron/electron#22798]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
8.1.1
* **Operating System:**
  * 
Windows 10(10.0.17763)
* **Last Known Working Electron version:**
  * 
8.1.1

### Expected Behavior

After double-clicking the title bar to maximize the window, you can restore the window to the original state by using the restore button, or after the window is maximized by the maximize button, and then double-clicking the title bar with the mouse, the window can also be restored to the original state.
### Actual Behavior

After double-clicking the title bar with the mouse to maximize the window, the window cannot be restored to the original state through the restore button, or after the window is maximized with the maximize button, then double-clicking the title bar with the mouse cannot restore the window to the original state
### To Reproduce

// Create the browser window.
  mainWin = new BrowserWindow({
    width: 812,
    height: 590,
    minWidth: 812,
    minHeight: 590,
    show: false,
    center: true,
    frame: false,
    hasShadow: false,
    transparent: true,
    useContentSize: true,
    titleBarStyle: 'hidden',
    backgroundColor: '#00FFFFFF',
    webPreferences: {
      webSecurity: false,// disable cross domain access
      nodeIntegration: true,
      nodeIntegrationInWorker: true
    }
  })
ipcMain.on('win-maximize', event => {
    console.log('win-maximize', mainWin.isMaximized())
    mainWin.isMaximized() ? mainWin.unmaximize() : mainWin.maximize()
  })

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
