### ISSUE TITLE
WIndows Tray MenuItem with built in Role not working

### ISSUE THREAD

**Issue by sethwhitaker** [electron/electron#22797]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Im working on a `Tray` context menu for my application. On Windows there seems to be an issue in that `MenuItems` with one of the pre-defined `role` options (ex: `togglefullscreen`) doesnt seem to work when added to a `Tray` Menu.

I have tested my application on Mac and they all seem to work as expected, this only seems to be an issue on `Windows`.

* **Electron Version:**
  * 8.1.1
* **Operating System:** 
  * Windows 10 (1909)
* **Last Known Working Electron version:** 
  * N/A

### Expected Behavior
the created `Toggle Full Screen` menu item should toggle full screen

### Actual Behavior
The Menu Item does not perform the action on Windows 10 devices.

### To Reproduce
```
app.on('ready', () => {
  let tray
  tray = new Tray( icon ) 
  const contextMenu = Menu.buildFromTemplate([
    {
        role: 'togglefullscreen'
    },
  ])
  tray.setContextMenu(contextMenu)
})
```

### Additional Information

Another related issue Im having is that the Tray Icon only shows up in Development builds. When I actually create a production build and install it and run, the Tray Icon isnt showing up at all.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
