### ISSUE TITLE
Uncaught (in promise) TypeError: Error processing argument at index 2, conversion failure from #<Object>

### ISSUE THREAD

**Issue by billwing** [electron/electron#22803]
![1](https://user-images.githubusercontent.com/3411815/77290320-e8c2a580-6d16-11ea-9568-1a268190b48e.png)

![image](https://user-images.githubusercontent.com/3411815/77290409-16a7ea00-6d17-11ea-9b13-c1dd1fccb1f4.png)

This worked on macOS, not worked on windows 7 with the error. (Electron v7.1.14)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
