### ISSUE TITLE
Process becomes uninteractable after running electron on Windows, not the case for MacOS

### ISSUE THREAD

**Issue by navarrojandg** [electron/electron#22809]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.1.1
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
 On macOS the process is interactable after electron spawns, this can be checked by looking at process.stdin.isTTY. On macOS process.stdin.isTTY returns true before and after electron is spawned. On windows this evaluates to false after electron is spawned. I am expecting that process.stdin.isTTY return true in both operating systems.
### Actual Behavior
 After electron is spawned process.stdin.isTTY evaluates to false.

### To Reproduce

```
// main.ts
import { app, BrowserWindow } from 'electron';
if(!!app) {
    console.log('Init electron');
    console.log('w/ electron', process.stdin.isTTY);
    app.allowRendererProcessReuse = true;
    await app.whenReady();
    let win = new BrowserWindow();
    win.on('closed', () => { win = null });
    app.on('window-all-closed', () => { console.log('all windows are closed!') });
    console.log('electron initialized');
} else {
    console.log('w/o electron', process.stdin.isTTY);
};
```

```
tsc main.ts && node main.js
```
shows true for both windows and macOS

```
tsc main.ts && electron main.js
```
shows true for macOS and false for windows

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
