### ISSUE TITLE
White flash on switching back to Electron apps 

### ISSUE THREAD

**Issue by mikeyyyzhao** [electron/electron#22826]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.2.1
* **Operating System:**
  * macOS (10.15.2
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Electron app does not flash whenever we switch back to the app.

### Actual Behavior
I'm getting a white flash when switching apps. I saw that there was a merge (#21751 ) fixing this issue but even after pulling in the latest build, I am still seeing this issue on our app.

### To Reproduce
Switch to different app and after a while, switch back to electron app.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
