### ISSUE TITLE
The sendBeacon method on beforeunload does not work when the window is closed

### ISSUE THREAD

**Issue by tidg** [electron/electron#22845]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * macOS Catalina 10.15.3

### Expected Behavior
I would like to send data analytics when closing the application using the navigator.sendBeacon() method when the window.addEventListener('beforeunload', () => {}) event is emitted in the rendering process.
My goal is to analyze the time of presence of the user between the opening and closing of the application. If you have other ways of doing this I am also a taker.

### Actual Behavior
When I close the application, i can see that the 'beforeunload' event is triggered into the renderer process but sendBeacon doesn't work. 
The renderer code works perfectly on browser like Chrome when i close Chrome, the data is sent correctly.
This issue is similar to #12654 

### To Reproduce
In main process i added 
```
mainWindow.on('close', (e) => {
    e.preventDefault();

    dialog.showMessageBoxSync({
        title: 'Quit app',
        type: 'question',
        noLink: true,
        buttons: ['No', 'Yes'],
        message: 'Are you sure you want to quit the app?'
    })
    .then(function(result) {
        if (result.response === 1) {
            mainWindow.close();
        }
    }).catch(function(error) {
        logger.info(error);
    });
});
```
In renderer process i added 
```
window.addEventListener('beforeunload', () => {
    try {
        const data = {
            "Title": title,
            "Date": "DateTime"
        }

        navigator.sendBeacon('urlToSendDatas', JSON.stringify(data));
    } catch(err) {
        logger.info(err);
    }
});
```

**Comment by GoldAndYouth** [comment]
I also encountered the same problem, I am looking for a way to send an asynchronous request beforeUnload and was relying on sendBeacon to do this.

Electron Version: 8.2.1
OS: Windows 10 Professional 1903

**Comment by p120ph37** [comment]
This is still an issue in current versions of Electron.  The problem seems to be that during the "quit" teardown sequence, all windows are closed, and all `beforeunload` / `unload` events fire correctly, but if one of them produces a beacon request, that request outlives the window and continues on in the `session`.  To work around this, you can use `session.webRequest.onBeforeRequest` / `onCompleted` / `onErrorOccurred` to build a registry of in-flight requests, trap the case where there is a remaining in-flight request during the `will-quit` and/or `window-all-closed` event, and wait on that request to complete before exiting.  I've made this workaround work (if anyone is interested, I can provide sample code), but it's really convoluted, and due to the singleton nature of the `webRequest` listeners, can't be easily combined with anything else that uses them.  This really should be fixed by adding some sort of event or promise directly to the `app` and/or `webContent`s which can provide a list of in-flight network requests, and the ability to wait on them to complete...

**Comment by nornagon** [comment]
It would be really helpful to get a self-contained standalone test case for this. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.

**Comment by p120ph37** [comment]
Here is a gist which reproduces the error, and which also demonstrates a workaround:
https://gist.github.com/p120ph37/41689cb66a1708d0533df2414b0c6883

As I said, it is a little convoluted because it has to trigger a race condition, so the HTTP server introduces and artificial 500ms delay in processing the beacon request in order to simulate realistic network conditions.  This test seems to operate repeatably on MacOS and on Windows 10, and with the latest Electron versions (including 13 and 14)

**Comment by cawa-93** [comment]
I faced a similar problem. In addition, I use a beacon to send data to the server when the window closes:
```js
// renderer
document.addEventListener('visibilitychange', () => {
  if (document.visibilityState === 'hidden') {
    navigator.sendBeacon('https://analytics.com/', data); // <--
  }
})
```

This works when the page is reloaded and the required data reaches the server. But when I **close** the page I saw in the logs that the request is created (`onBeforeRequest` was fired) but does not end (`onCompleted` or `onErrorOccurred` was't fired) and I do not get the necessary data on the server.

I came to the conclusion that the reason is that when you close the window, the whole application immediately shuts down and does not wait until the queues in the queue are completed:
```js
// main
app.on('window-all-closed', () => app.quit());
```
And my theory is confirmed by the fact that if you add a timeout, then all requests have time to end:
```js
// main with workaround
app.on('window-all-closed', () => setTimeout(() => app.quit(), 1000));
```

It's not very reliable, of course, but it works for me.

So, I can understand when the application is shutting down and aborted any active network connections, but the browser must guaranteed to initiate **beacon requests** before the page is unloaded and to run them to completion. Isn't that right? So shouldn't the electron follow the same rules and guarantee that the Beacon's queries will be completed before app will be shut down?
