### ISSUE TITLE
BrowserWindow show event does not fire on Windows platform

### ISSUE THREAD

**Issue by NilSet** [electron/electron#22854]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * Windows 10 Pro (1903)

### Expected Behavior
'show' event on a BrowserWindow fires when a window is first shown on all platforms.

### Actual Behavior
'show' event fires on mac, but not on win.

### To Reproduce
fiddle gist: https://gist.github.com/5cae7ebca7c33226a49c06f6a177c258

**Comment by ilias-t** [comment]
I believe same goes for `'ready-to-show'`

**Comment by NilSet** [comment]
After some more investigation it seems that the behavior for this event has always been different between mac and windows. On mac, the event fires when a window shows via `{show: true}` option or via the explicit `win.show()` method, but on windows, it ONLY fires when you call `win.show()`.

**Comment by NilSet** [comment]
Found this in the docs, I assume it is related?

> Additionally, on macOS, the visibility state also tracks the window occlusion state. If the window is occluded (i.e. fully covered) by another window, the visibility state will be hidden. On other platforms, the visibility state will be hidden only when the window is minimized or explicitly hidden with win.hide().
> If a BrowserWindow is created with show: false, the initial visibility state will be visible despite the window actually being hidden.

**Comment by stanleyxu2005** [comment]
Yes. 
Works for Windows 7 
but broken on Windows 10. 
Same code base.
I debugged a while...

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by NilSet** [comment]
This still occurs on electron v12.0.1 with the same fiddle. Do I still need to open an entirely duplicate ticket?

**Comment by RyanLandDev** [comment]
Still experiencing the same issue

**Comment by nornagon** [comment]
@RyanLandDev This kind of comment is only useful if you include the specific version on which you're seeing the problem :)

**Comment by SamPoate** [comment]
I've tested this on "^13.1.8" and it works as expected now.
