### ISSUE TITLE
`scrollTo` isn’t working with `webview` while same thing works with `executeJavascript`

### ISSUE THREAD

**Issue by deadcoder0904** [electron/electron#22877]
### Preflight Checklist

• [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
• [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF𝑐ONDUCT.md) that this project adheres to.
• [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

• **Electron Version**: v8.0.2
• **Operating System**: v10.15.2

### Expected Behavior
It should scroll the `webview`

### Actual Behavior
It doesn’t scroll the `webview`

### To Reproduce

```js
currentWebview.addEventListener('ipc-message', event => {
	const { args } = event
	const { position } = args[0]
	const allWebviews = Array.from(document.querySelectorAll('webview'))

	allWebviews.forEach(webview => {
		if (webview.id !== uniqueId) {
			webview.executeJavaScript(
				`document.documentElement.scrollTop = document.body.scrollTop = ${position.y};`
      ) // this works
			webview.scrollTo(position) // this doesn't work
      webview.shadowRoot.querySelector('iframe').scrollTo(position) // this also doesn't work
		}
	})
})
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
