### ISSUE TITLE
Redirect event fired after close event on ClientRequest

### ISSUE THREAD

**Issue by cyu** [electron/electron#22875]
The `ClientRequest` documentation says this:

> Emitted as the last event in the HTTP request-response transaction. The close event indicates that no more events will be emitted on either the request or response objects.

However, the behavior I'm seeing, when option `redirect: "manual"`, is that the redirect event comes after the close.  I'm not sure if this is a bug or a documentation update.  However, this behavior makes it trickier to determine when a redirect didn't happen.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.1.1
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Expecting to receive 'close' event after 'redirect' event on `ClientRequest`.

### Actual Behavior
Receive 'close' event first, then 'redirect' after.

### To Reproduce
Create `ClientRequest` with `redirect: "manual"` option.  Log handlers to 'close' and 'redirect' events.

**Comment by VincentAl** [comment]
I have the same problem, with electron `8.2.3 `and macOS `10.14.6.`

`close` event is emitted before `request.on('response')` and before `response.on('data')`.

Bug was already here in electron `4.x.`

Is there an other way to determine when the request is done ?

**Comment by BrunoMoreira99** [comment]
I have the same problem.
- **Electron Version:**
  - v8.2.5
- **Operating System:**
  - Windows 10

It happens with `redirect: "follow"` as well.

**Comment by nornagon** [comment]
Thanks for the report—it would be helpful to have a small example that reproduces the issue you're describing. You might find [Fiddle](https://github.com/electron/fiddle) helpful in creating one!

**Comment by VincentAl** [comment]
Hi, I made one here :)
https://gist.github.com/83c4b6c66f39a1e07867718ec3a83b7e

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
