### ISSUE TITLE
findInPage causes focus loss

### ISSUE THREAD

**Issue by Lusito** [electron/electron#22880]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * Windows 7 and Ubuntu 18.04
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
When I call findInPage to search a page, I expect my input element to stay focused.

### Actual Behavior
The input element loses focus as soon as I call findInPage. 

### To Reproduce

Simplest example:
- After window creation, add a global shortcut, which calls findInPage
- open any sample URL, which has an input element
- Click inside of that input element to focus it.
- execute the shortcut (ctrl/cmd + F)
- see how the input element lost focus.
```javascript
    win.on("focus", () => {
        globalShortcut.register("CommandOrControl+F", function() {
            if (win && win.webContents) {
                win.webContents.findInPage("Welcome", { findNext: true });
            }
        });
    });
    win.on("blur", () => { globalShortcut.unregister("CommandOrControl+F");
```

### Additional Information

Sadly existing "search UI" projects are all made for much older electron versions, so I tried to create a search UI myself.
- I tried using webview (to avoid the input element itself being searched), but got focus loss. calling focus on the webcontent did not help.
- I tried using input elements within the page itself, but they lost focus as well. Calling focus on these elements afterwards didn't solve the problem either.

I just started with electron and can't believe this hasn't happened to anyone yet, but all my google skills led me nowhere.

#### Sidequest if anyone feels like it:
I know webview is frowned upon, but how are you supposed to create a search UI without using a webview, yet still ignore the input element during search? #11444 seems to be about this topic, but it has been closed recently after years of being ignored. Is no-one using this API?

**Comment by vladimiry** [comment]
I don't experience the focus lost issue. I use BrowserView instead of WebView in order to ignore searching within the input control itself (inefficient approach but has to be used since #11444 not resolved). You can try it in action using https://github.com/vladimiry/ElectronMail.

> #11444 seems to be about this topic, but it has been closed recently after years of being ignored.

I hoped too that #11444 will be resolved one day but recently got rejected, very sad story.

**Comment by Lusito** [comment]
Yes, it seems to work with BrowserView. Thanks!

**Comment by mdealer** [comment]
I'm not sure how a BrowserView solves all issues related to this (coming not from the node.js / Javascript / web development world here, bear with me). @vladimiry Your project structure is completely different to mine.

How would you recommend using a BrowserView in Quasar + Electron app in order to work around this issue? Since I already have a search element in the app, I don't see how it works. The idea is to have this search field completely integrated.

**Comment by ccorcos** [comment]
@mdealer You're going to need to render the search input in a separate process unfortunately
