### ISSUE TITLE
Transparent window limitations

### ISSUE THREAD

**Issue by ttrepka** [electron/electron#22915]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0 

* **Operating System:**
  * macOS 10.14.6
  * Windows 10 (1909)

* **Last Known Working Electron version:**
  * Not sure, I tested with 2.0.7 but doesn't work either. 

### Expected Behavior
Transparent window behaves according to [the limitations in docs](https://www.electronjs.org/docs/api/frameless-window#limitations):
  * It is not resizable on either platform.
  * It has a shadow on Windows.
  * It doesn't have a shadow on Mac.

### Actual Behavior
  * It is resizable on both platforms.
  * It doesn't have a shadow on Windows.
  * It has a shadow on Mac.

### To Reproduce
[Electron fiddle](https://gist.github.com/021cef8e3d1a84cf073b22966ee24e95)

### Additional Information
I don't know if the actual behaviour is correct (in that case the docs should be updated) or if there is a bug.

**Comment by xland** [comment]
When `transparent` is true, `frame` is false,
window can be resized on Windows 10 OS,Electron 8.2.3
code:
```javascript
        this.win = new BrowserWindow({
            width: 800,
            height: 600,
            transparent: true,
            frame: false,
            hasShadow: false,
            webPreferences: {
                nodeIntegration: true
            }
        })
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
