### ISSUE TITLE
Can I use the nodejs worker_threads at childprocess?

### ISSUE THREAD

**Issue by yangwuan55** [electron/electron#22927]
I know that the web worker can support thread,but I can't use the nodejs or electron module(like 'net') in worker.
Can I use the worker_threads of nodejs when create a childprocess?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
