### ISSUE TITLE
Set app name (and app data folder name) upon start

### ISSUE THREAD

**Issue by hosnar** [electron/electron#22929]
Hi,

is there a way to set app name and app data folder name dynamically upon app start or build? We have an app that is used by multiple brands, but app data that is created has always the same name (the one from package.json). Is there a way to change this upon start, based on the brand that we are compiling for?

Thank you.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
