### ISSUE TITLE
Intercept requests in BrowserWindow

### ISSUE THREAD

**Issue by trae-op** [electron/electron#22936]
electron: 7.1.11
node: 10.16.3
Can I intercept all requests in BrowserWindow? I need to add a remote URL and I don't have available to UI, but I want to check the URL for change

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
