### ISSUE TITLE
hidden-inset ignored on some Electron apps in macOS

### ISSUE THREAD

**Issue by austincondiff** [electron/electron#22934]
![image](https://user-images.githubusercontent.com/806104/78258774-52824280-74c1-11ea-914c-5cfe9d4b49ef.png)

Slack and Teams always open up with the titlebar this way. Atom does this on occasion. I've seen this issue on someone else's machine as well. Any idea what this could be caused by?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction. You might also consider reaching out to the apps in question directly.
