### ISSUE TITLE
Tray icon context menu not working on a multi-display vertically aligned

### ISSUE THREAD

**Issue by rever-whale** [electron/electron#22959]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v8.0.1
* **Operating System:**
  *  macOS 10.15.4
* **Last Known Working Electron version:** 
  *  N/A

### Expected Behavior

When I click on the tray icon, the context menu should be visible on any screen.
### Actual Behavior

When multi-screen alignment is vertical, the context menu of the screen located below is not visible.

### To Reproduce

1) Set display alignment as follows:
    <img width="674" alt="Screen Shot 2020-04-05 at 1 07 35 AM" src="https://user-images.githubusercontent.com/53922712/78455518-d9aa0300-76d9-11ea-9b94-71315c8690d6.png">
2) Click on the tray icon on the screen aligned below.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
