### ISSUE TITLE
Text cursor blinking even though app not focused

### ISSUE THREAD

**Issue by DarkDust** [electron/electron#22967]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.10, 6.1.9, 7.1.11
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * None

### Expected Behavior

On macOS, an app (more precisely: a window) that does not have input focus (is "key") is expected to not show the input cursor or at least not blink it. (I was unable to find the relevant section in Apples Human Interface Guidelines but every native app behaves that way.)

### Actual Behavior

Electron-based apps all have their text input cursors blinking, regardless of window state. I have WhatsApp, Skype and Mattermost open, all of them blinking their cursors all the time. This makes it somewhat harder to recognize which app is going to get my input and pretty often I find that after typing, my text is in another app.

WhatsApp only other indicator that it is key are the three traffic-light buttons in the upper left (close/minimize/zoom), Skype and Mattermost at least have a title bar… but that's all that changes when one of its windows becomes/loses key. So the blinking cursor is a vital clue as movement draws attention. One could argue that it's up to the individual apps to provide better key window indications (e.g. dimming some colors when they lose key, as native apps do) but this small detail (the blinking cursor) is something the framework can improve to provide a more native-feeling experience to all Electron apps.

### To Reproduce

Open several Electron-apps that have text input.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
