### ISSUE TITLE
Electron downloads dictionaries from internet and puts them to "Dictionaries" folder even though the "webPreferences.spellcheck" flag is disabled

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#22995]
* **Electron Version:** 8.2.1, 9.0.0-beta.14
* **Operating System:** Linux
* **Last Known Working Electron version:** unknown, probably never worked properly ("native spellcheck" is a quite new feature)

### Expected Behavior
- Electron doesn't download stuff from the internet / Chromium CDN when 
`webPreferences.spellcheck` flag disabled. Electron should not download anything from the internet when there is no need to do that.
- Electron doesn't fill dictionaries related data into the `Cache` and `Dictionaries` directories located in the `app.getPath("userData")` directory when `webPreferences.spellcheck` flag disabled.

### Actual Behavior
The `webPreferences.spellcheck` flag is disabled by default. But even if I disable it explicitly Electron still downloads the stuff from Chromium CDN and then `Cache` and `Dictionaries` folders located in the `app.getPath("userData")` directory get filled with some data.

### To Reproduce
https://github.com/electron/electron-quick-start should be enough to test the case.

**Comment by raksooo** [comment]
As a developer of an app with a high privacy/security focus this prevents us from upgrading. We can't have our app perform network requests that's not initiated by us.

**Comment by Wexoo** [comment]
I have another variation of the problem. Apparently electron already creates the `Dictionaries` folder as soon as the app starts, which, i guess, is also the reason that `spellcheck: false` fails to have an effect on dictionary download.

My problem is, the `Dictionaries` folder is created even before my custom `userData` path is applied (via `app.setPath('userData', dataPath);`), so it sits in `Users\<user>\AppData\Roaming\<app-name>\` (on Win 10) instead of my custom path. Any way to prevent this? 

It seems both problems would be solved, if the initialisation / download of the dict folders & files would be moved further back in the process to only after a window component was created, where the `spellcheck` can be used to check, if dicts are even needed and skipped entirely, it it's set to `false`. Thanks in advance!

**Comment by bblwbtd** [comment]
I also have this issue. Any good solutions?

**Comment by nornagon** [comment]
I was able to work around this by calling [`ses.setSpellCheckerDictionaryDownloadURL()`](https://www.electronjs.org/docs/api/session#sessetspellcheckerdictionarydownloadurlurl) and passing a non-resolving URL.

**Comment by jmeinke** [comment]
Related to Electron 10:

For us the spellcheck has caused another problem: A file de-DE-3-0.bdic is automatically created in the Users\<user>\AppData\Roaming\<app-name>\` (NOT in Users\<user>\AppData\Roaming\<app-name>\Dictionaries). This happens even when disabling spellcheck. However our app shows a blank window and renderer / VueJS does not load (no error shown). After deleting the bdic file, the app "works" again.

**Comment by kocjs** [comment]
In the Joplin forum the discuss a related [issue](https://discourse.joplinapp.org/t/new-version-of-joplin-contacting-google-servers-on-startup/23000/108). Apparently the electron update contacts [redirector.gvt1.com](http://redirector.gvt1.com/) on every start and leaks meat information to google. Even if the spell check is disabled.

As a privacy oriented app this might be of interest here too.

**Comment by vladimiry** [comment]
bump

The issue is still there. Tested on the current stable/v21 version.

**Comment by xoxloviwan** [comment]
Can we use `file://` protocoll in method `setSpellCheckerDictionaryDownloadURL()` to take the file `hunspell_dictionaries.zip` with dictionaries locally that may be installed with distro?

**Comment by codering** [comment]
is it resolved ？
