### ISSUE TITLE
Calling 'process.getcpuusage' incorrectly does not support the use of inline events in js

### ISSUE THREAD

**Issue by wuzhong233** [electron/electron#22993]
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
# repeat
Clone the code locally
Add in index.html
```
<div>
    <h2>Process</h2><button onclick="getProcessinfo()">getProcess</button>
</div>
```
Add in renderer.js
```
function getProcessinfo() {
    console.log('Processinfo:', process.getCPUUsage())
}
```
```
npm start
```
Click the process button
An error has occurred in the developer tool

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. This is not an issue with Electron, but rather a correct handling by Chrome of your usage of that code.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
