### ISSUE TITLE
The detection of a website requesting access to a future inside of a webview

### ISSUE THREAD

**Issue by EnderAdel** [electron/electron#22994]
This is a question, please answer me.
https://stackoverflow.com/questions/61075597/how-can-i-manage-websites-settings-in-electron

**Comment by vladimiry** [comment]
https://www.electronjs.org/docs/api/web-request

**Comment by EnderAdel** [comment]
How exactly?

**Comment by vladimiry** [comment]
You have a direction, the rest is up to you.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by EnderAdel** [comment]
I've asked multiple times, and I've tried. But I'm still not able to find an answer to my question.

https://stackoverflow.com/questions/61075597/how-can-i-manage-websites-settings-in-electron

https://discuss.atom.io/t/how-can-i-manage-websites-settings-in-electron/73398

https://stackoverflow.com/questions/61186170/how-can-i-detect-when-a-website-is-trying-to-use-the-camera
