### ISSUE TITLE
Electron processes still exists after app closed causing node-hid/usb-detection unable to detect devices if app is reopen (Mac)

### ISSUE THREAD

**Issue by faisalm786** [electron/electron#23029]
Hi Electronians,

I have an issue with electron processes remaining open after app has closed on Mac which node-hid/usb detection to become unable to detect the usb device that remains connected while the was being closed and reopened.

I can easily demonstrate the relationship electron helper processes remaining open and node-hid/usb-detection unable to detect the usb device. Simply force closing the electron process after reopening the app causes the usb device to be detected.

I would like to know how can I ensure that all electron helper processes are closed and also please educate me on how do these processes come about. There is scant information on google search.

Many thanks.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
