### ISSUE TITLE
A JavaScript error occurred in the main process   Uncaught Exception: 

### ISSUE THREAD

**Issue by Mbc11** [electron/electron#23027]
A JavaScript error occurred in the main process 

Uncaught Exception: 
 Error: ProcessUncIeanExitError: QUERY command exited with code 1:
 
 ERROR: The system was unable to find the specified registry key or value. 
 at regKey.vaIues 
(C:\Users\PCname\deckboard\extentions\.temp\voicemeter-control.asar\node_modules\vo...:11)
 at ChildProcess.<anaonymous>
(C:\Users\PCname\deckboard\extentions\.temp\voicemeter-control.asar\node_modules\win...:7)
 at ChildProcess.emit (events.js:182:13)
 at maybeCIose (internal/child_proess.js:962:16)
 at Socket.stream.socket.on (internal/child_process.js:381:11)
 at Socket.emlt (events.js:182: 13) 
 at Pipe._handle.close (net.js:60612)

Deckboard version 1.9.31
OS: Windows 10 Pro
Version: 1909
OS build: 18363.752

Platform specs:
windows 10 Pro 64 bit
intel xeon 
gtx1080
12gb Ram

Error appears when opening deckboard then the software functions normal but multimedia functions do not appear and cannot be selected or used.

Any fix would be much appreciated and great work btw.

Many thanks.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
