### ISSUE TITLE
setUserTasks/setJumpList don't work after window was created

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#23025]
* [+] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [+] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [+] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
calling app.setJumpList or app.setUserTasks sets the list of tasks on an application.

### Actual Behavior
If the BrowserWindow was already created, the call does nothing.
It does affect all windows created after the call to setJumpList though.

### To Reproduce

```
// before creating the window
    app.setJumpList([
      {
        name: 'before',
        type: 'tasks',
        items: [
          {
            type: 'task',
            title: 'before',
            description: 'before',
            program: 'cmd.exe',
          },
        ],
      },
    ]);
// create window
setTimeout(() => {
    app.setJumpList([
      {
        name: 'after',
        type: 'tasks',
        items: [
          {
            type: 'task',
            title: 'After',
            description: 'After',
            program: 'cmd.exe',
          },
        ],
      },
    ]);
}, 5000);
// observe how the jump list still says "Before" after the timeout expires
```

### Additional Information

I don't really know the windows api in the background so I can't 100% rule out this is a windows issue or limitation but I find that very unlikely.
It may be that electron is simply missing a change notification to let the windows shell know something has changed, probably
SHChangeNotify(SHCNE_UPDATEITEM,

This may be relevant:
https://devblogs.microsoft.com/oldnewthing/20150903-00/

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
