### ISSUE TITLE
通过web协议方式唤醒electron失败

### ISSUE THREAD

**Issue by yaoyuanrong** [electron/electron#23055]
**Preflight Checklist**
[x ] I have read the Contributing Guidelines for this project.
[ x] I agree to follow the Code of Conduct that this project adheres to.
**Issue Details**
- Electron Version:
  8.2.1
- Operating System:
   window 10
- Last Known Working Electron version:
   Dont know.
**预期行为**
没有崩溃
**实际行为**
通过web唤醒electron的时候，electron应用报错：
Invalid package C:\Program Files (x86)\Google\Chrome\Application\81.0.4044.92\resources\app.asar
正常的情况下打包安装双击能够打开。

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
