### ISSUE TITLE
Refused to display 'https://www.nisum.com/' in a frame because it set  'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by shahmed-nisum-com** [electron/electron#23053]
Hello Folks,

I am writing a scenario in cypress where i first visit google site then i type 'nisum Karachi' then i go to go to search page where i found result set. Then i click the first link in it. 

Actual Result: following error is being displayed on console;

Refused to display 'https://www.nisum.com/' in a frame because it set
 'X-Frame-Options' to 'sameorigin'.
 
I am using electron browser from cypress and OS is Window 10

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
