### ISSUE TITLE
Electron GPU issues on ChromeOS (under crostini)

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#23050]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.1
* **Operating System:**
  * Crostini on ChromeOS

### Expected Behavior

Electron will work

### Actual Behavior

Electron starts up blank, and does not render anything

### To Reproduce

Run an electron application on one of the following devices:

 - c423n
 - google pixelbook

Note that **not all** chromebooks are affected. A yoga N23 runs electron fine.

Electron outputs:

```
[32:0407/123834.030425:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

Disabling Crostini GPU support from `chrome://flags/` allows electron to work again.

setting:

```
export LIBGL_ALWAYS_SOFTWARE=1
```

reportedly does not fix the issue.

**Comment by CapOM** [comment]
Have you tried passing:

`--use-gl=egl` or `--use-gl=angle --use-angle=gl` or  `--use-gl=angle --use-angle=gl-egl` ?

**Comment by jonathon-love** [comment]
hey,

i don't actually have one of these devices that have this issue, this info has come from our community, but i'll see if i can find someone with the issue (although it's harder to find them now that we've a workaround).

with thanks

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
