### ISSUE TITLE
Windows action center OnClick

### ISSUE THREAD

**Issue by fsykes87** [electron/electron#23065]
Wondering if anyone is having the issue where the notification onclick event does not fire on notifications that are clicked in the action center.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
