### ISSUE TITLE
win.loadURL() on facebook likes plugin makes the window to crash.

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#23073]
### Issue Details

* **Electron Version:**
  * 8.2.1
* **Operating System:**
  * windows

### Expected Behavior
Page should load without crash.

### Actual Behavior
Page starts to load then crash.

### To Reproduce
```js
const win = new BrowserWindow({
  show: true,
  width: 600,
  height: 400,
});

await win.loadURL("https://www.facebook.com/v2.5/plugins/like.php?action=like&app_id=&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D46%23cb%3Df3978164fecdf48%26domain%3Dwww.visitorsdetective.com%26origin%3Dhttps%253A%252F%252Fwww.visitorsdetective.com%252Ff1855ea9668ee9c%26relation%3Dparent.parent&container_width=353&href=http%3A%2F%2Fwww.onlinekhabar.com%2F&layout=button_count&locale=en_US&sdk=joey&share=false&show_faces=false&size=small");
```

### Additional Information
Have tried in the `webview` tag and page loads. This issue as I saw is only related in `BrowserWindow`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
