### ISSUE TITLE
[Suggestion] Create a discord server for the community

### ISSUE THREAD

**Issue by futurelucas4502** [electron/electron#23084]
I know there is https://atomio.slack.com/

However to join you have to email and request it if it was on discord we could have a public invite link and be able to easily manage users with loads more integrations like the GitHub commit bot, release announcements and being able to more easily ask for generic help minimizing the issues on this GitHub repo.

Plus Discord is still built on electron so... :)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. At this time, we're not prepared to maintain or create a Discord server, and continue to recommend existing community-based options.
