### ISSUE TITLE
display-metrics-changed is not working for mac OS Catalina

### ISSUE THREAD

**Issue by BTARPAR** [electron/electron#23087]
### Issue Details

* **Electron Version:**
  * 4.2.12
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * Not Sure but working fine on Windows OS

### Expected Behavior
When changing the position of Taskbar/ Dock this event should fire since display matrices are changed du to this

### Actual Behavior
On windows OS it's working absolutely fine, BUt not triggered when I change my mac OS Dock preference/position

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. It's not clear how we might reproduce this issue, and as such we cannot triage it very effectively at present.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by BTARPAR** [comment]
Sure, I'll update this ticket with a new repo where the maintainers can reproduce the issue easily. @codebytere

**Comment by BTARPAR** [comment]
Closing this issue after upgrading my electron to the latest issue is fixed

**Comment by infinite3219** [comment]
I'm unable to get this to work on Catalina. It works on Mojave and on Windows 10. The display-metrics-changed event doesn't fire and the periodic check for the workArea change while the app doc hides and unhides doesn't detect the workArea change. This is the code to reproduce it.

Tried with latest stable electron 8.2.5 and the 9.0.0 beta as well. Same outcome.

```
app.on('ready', () => {
  // let displays = screen.getAllDisplays();
  let height = 0, width = 0;
  screen.on('display-metrics-changed', (event, display, changedMetrics) => {
    console.log(`Changed info in event: `, event, display, changedMetrics);
  });
  setInterval(() => {
    let d = screen.getPrimaryDisplay();
    if (d.workArea.height !== height || d.workArea.width !== width) {
      console.log(`Changed display info `, d);
      height = d.workArea.height;
      width = d.workArea.width;
    }
  }, 1000);
});
```
