### ISSUE TITLE
does not take care of the environment dark mod

### ISSUE THREAD

**Issue by promeneur** [electron/electron#23081]
openSuse Leap 15.1
kde apps 18.12.3
plasma 5.18.3
frameworks 5.68.0
qt 5.14.1

### Expected Behavior

messengerport takes care with plasma "breeze dark" mode

### Actual Behavior

messengerport does not take care with kde  "breeze dark" mode

### To Reproduce

choose "breeze dark" mode in plasma settings
launch messengerport
you see that the foreground is white instead of black

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by MarshallOfSound** [comment]
`messengerport` is an Electron application and this issue should be raised with them, not with Electron itself
