### ISSUE TITLE
Flash Support

### ISSUE THREAD

**Issue by waltder** [electron/electron#23091]
Will Electron support Flash beyond 2020 when browsers will not?
If not, does that mean Electron will remove its Flash code for releases beyond 2020?

Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by waltder** [comment]
@codebytere  Thanks for info.
