### ISSUE TITLE
net:ERR_CONNECTION_RESET from a specific website in electron app

### ISSUE THREAD

**Issue by eitanpinchover** [electron/electron#23094]
I Have an Electron app with a Webview. When i set the webview src to the website https://www.zap.co.il i'm receiving the error: net:ERR_CONNECTION_RESET. The weird things are:

It's happening only for that website, i'm not receiving this error from any other website.
I'm able to reach the website from any other browser on my computer (Chrome, Chromium).
This is happening in both Windows and Mac platforms.
A colleague of mine have the same App installed on her computer, and she is experiencing the same behaviour from a different computer (and network)
There is no antivirus Installed that may intercept and no proxy configured. I have tried to reset the network, clear cache and cookies, change the MTU and basically any solution i found on the internet, and since it's happening for my colleague too, i suppose it has nothing to do with a network issues. And since i can reach the website from other browsers, I think the issue is probably relates to Electron.

I'm Using the versions:

electron: 8.2.1
electron-builder: 22.4.1

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
