### ISSUE TITLE
solve it please

### ISSUE THREAD

**Issue by Mrblack007** [electron/electron#23114]
its my first time... firstly I install AhMyth with " git clone https://github.com/AhMyth/AhMyth-Android-RAT.git"...after that I write "npm install electron-packager -g" 
![1](https://user-images.githubusercontent.com/63680184/79278858-823a2e80-7e61-11ea-9ff6-02f7b9afa3bd.PNG) 
THEN i write ls for listing and it give me 
![1](https://user-images.githubusercontent.com/63680184/79278951-bdd4f880-7e61-11ea-8b7d-ae30fb67238c.PNG) 
after this i write a code  cd AhMyth-Android-RAT/AhMyth-Server/ the again ls then i see .json file and I trying to install it then i receive the error 
![1](https://user-images.githubusercontent.com/63680184/79279128-2fad4200-7e62-11ea-9b77-ad6261ef5295.PNG)

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
