### ISSUE TITLE
After upgrading from electron version 6.x to the new version of electron (7.x, 8.x, 9.x), the page rendering performance drops significantly

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#23148]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.x,8.x,9.x
* **Operating System:**
  * macOS 10.14.6 
* **Last Known Working Electron version:**
  * v6.1.10

### Expected Behavior
There should be no noticeable performance degradation

### Actual Behavior
After upgrading from electron version 6.x to the new version of electron (7.x, 8.x, 9.x), the page rendering performance drops significantly
### To Reproduce
The only change I made was to try to upgrade different electron versions (from 6.x to 7.x 8.x 9.x)

### Screenshots

electron 6.x  https://moon.fm/dist/6.x.mov
electron 8.x  https://moon.fm/dist/8.x.mov
Take a look at these two screen recordings (6.x vs 8.x), the problem in the video is not as obvious as it actually is, but please observe the expansion animation of the menu, you can still find obvious differences

### Additional Information

here is the demo repository based on  electron quick start
https://github.com/gaodeng/electron-render-issue
click the **toggle expand** button
You will see a lot of unnecessary renderings on the right column (electron v7.x 8.x 9.x)

**Comment by Gaitin** [comment]
electron 4.x.x  worked fine, after which it became clear that the full screen page was rendered

**Comment by weilao** [comment]
Very slow after upgrade from electron 5.x to 7.x.

**Comment by pushkin-** [comment]
Does this affect all page rendering or are you experiencing the slow down in a specific scenario? Can you post a html page that demonstrates the degradation?

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by gaodeng** [comment]
> Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).
> 
> Thanks!

@nornagon read **Additional Information** section  the repo link is there .

**Comment by nornagon** [comment]
@gaodeng thanks for pointing that out, sorry I missed it.

Are you able to reproduce this issue in Chromium? It seems like a blink issue to me. If so, https://crbug.com/new is the right place to report this. If Electron's behavior is different to Chromium's, then that's something we should investigate here.

**Comment by sorentycho** [comment]
Electron Version:
    * 7.x,8.x,9.x

Operating System:
    * Arch Linux

Last Known Working Electron version:
    * v6.1.10

**See below for steps to reproduce**

I'm also experiencing this with my app [BlackMirror](https://github.com/sorentycho/blackmirror). In specific, it seems that Chromium's layout performance is about 5-10x worse after Electron 6.x. This is not a subtle difference, and it renders Electron semi-unusable on even a fairly powerful desktop with moderately complex content.

Here are profiles of the same page with the same content, first in Electron 6.x:

![2020-05-28-163721_441x428_scrot](https://user-images.githubusercontent.com/30617489/83206246-4d2e2680-a105-11ea-8911-404b4047dcac.png)

Then, Electron 7/8/9:

![2020-05-28-163127_457x427_scrot](https://user-images.githubusercontent.com/30617489/83206269-5cad6f80-a105-11ea-97ac-31384b1621e5.png)

Note that all categories other than Layout are close in performance. Since this test I've endeavoured to make the code somewhat more DOM-intelligent with no significant change in the Layout category.

## Steps to reproduce:

1. `git clone https://github.com/sorentycho/blackmirror.git`
2. `cd blackmirror`
3. `npm i && npm run build:linux`
    - or whatever OS you're using; see package.json#scripts, this builds native deps
4. `npm start`
5. Create a new Journal (using the `+` button on the homescreen that appears on launch), and populate it with about 500 `.convo` files.
    - These need not have any content, so running e.g. `touch "$(date +%s%12N).convo"` in the created directory repeatedly will suffice to create them.
6. Open the created Journal in BlackMirror (Ctrl+Shift+O or click on it in the homescreen), open devtools (Ctrl+Shift+I) and start profiling, then refresh the page.
    - Profiling a page load is insufficient as this misses most of the asynchronous loading process.
7. Save profiling data as you prefer.
8. `npm i electron@7 && npm run build:linux` (or 6 or 8 or 9, etc)
9. Repeat 6 & 7

There should also be a significant subjective difference in performance just scrolling around this view.

**Comment by JJansenJJansen** [comment]
Electron Version:
* 5.0.0, 6.x, 7.x, 8.x, 9.x

Operating System:
* Windows 10 64-bits

Last Known Working Electron version:
* v4.2.12

I am experiencing the same renderer performance issues. After upgrading initially to version 8 (and later 9) I noticed that my app performance went down drastically. After trying different versions I was able to pinpoint the exact version at which this occured. For me (perhaps related to the fact that I am on windows) the renderer performance drops when upgrading from **v4.2.12** (last stable release of 4.x) to version **5.0.0** (the first 5.x stable release).

More specifically, it appears that the renderer process gets blocked for a while (sometimes several seconds) for no apparent reason. Any function executed in the renderer process gets blocked during this period. When moving a function to the main process it is executed as fast as normal, but UI events in the renderer process still remain noticeably slower than before.
In version 4.2.12 this is not an issue and all functions are executed within milliseconds, in version 5.0.0 it can take up to seconds.

It looks like this to is somehow related to the event handler for click events..? When clicking a button it can take up to several seconds for the corresponding action to be executed. At this time there are no blocking processes active in the user code, it just appears to be 'idling' in the event click handler, blocking everything else. The performance monitor shows an violation warning stating that 'Event (click) Handler took 3.57s'.

Unfortunately I cannot share our code, but I am more than willing to test anything when possible. This is a serious issue preventing us from updating to recent versions of Electron. Let me know if you need any additional data.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
