### ISSUE TITLE
getUserMedia raises a DOMException

### ISSUE THREAD

**Issue by chukitow** [electron/electron#23149]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  * Windows 8/10
* **Last Known Working Electron version:**
  * N/A

I'm working on a WebRTC application and everything is working perfect on Mac OS but on Windows it works intermittently.

When I try to get the MediaStream, on some machines it raises a DOMException.
```
navigator.mediaDevices.getUserMedia({audio: true, video: false}) 
```

It works until I go to Settings → Privacy → Microphone and I toggle disabled/enabled the microphone, sometimes I need to restart the machine to make it work.

Also I'm not sure why on Windows it doesn't prompt for permissions as it does on Mac. 

![image](https://user-images.githubusercontent.com/4173376/79525740-3a660380-8029-11ea-9144-6babb5081c27.png)

**Comment by pratik14** [comment]
@chukitow does the error occur randomly. I am having same issue on mac machine. It randomly raises exception. Most of the times it works well

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
