### ISSUE TITLE
The Electron window freezes

### ISSUE THREAD

**Issue by 13683299065** [electron/electron#23150]
I had a problem developing an application with Electron that when the window.minimize() function was called, it worked, and when the page was restored the window seemed to freeze and not react. You can only see a static picture. JavaScript is all dead, and I don't think there's anything worse than that.

1. I tried to BrowserWindow webPreferences add backgroundThrottling: false problem still not solved.
2. In min. Js that executes ` app.commandLine. AppendSwitch (' disable - background - timer - throttling '); 'but the problem still hasn't been solved
3. Using the above method to upgrade the version, the problem is still not resolved.

I am currently using Electron version 3.1.0 and have tried versions 4.0+ and 5.0 with the same problem.

How to solve this problem?

**Comment by ColorfulPang** [comment]
I have also the same problem. 
How to solve?

**Comment by 13683299065** [comment]
@ColorfulPang 
My problem is that instead of using `event.returnValue` in the event, I added `event.returnvalue = false ` after the interprocess communication. 'The problem was solved.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
