### ISSUE TITLE
Where is the feature to keep logged in status after restarting app?

### ISSUE THREAD

**Issue by fer-fullstackdev** [electron/electron#23164]
I have built an app that loads some urls inside the app.
I loaded Slack.com on webview and logged into slack on it. 
Whenever I restart the app and go to slack.com, the app asks to login again.
I want that I am able to go to the channel directly without re-login if I already logged in before. 

Does webview have any feature to implement this?

Here is a snippet of the code how to load the webview.

```
    ...
    let webview = document.createElement('webview');
    webview.setAttribute('id', 'id_' + endpoint.id);
    webview.setAttribute('src', endpoint.url);
    webview.style.display = 'flex';
    webview.style.width = '100%';
    webview.style.height = (remote.getCurrentWindow().getContentSize()[1] - 25) + 'px';
    webview.setAttribute('partition', 'persist:' + endpoint.url + endpoint.id);
    ...
```
In this case the endpoint.url is slack.com

**Comment by fer-fullstackdev** [comment]
I need this resolved ASAP. Any answer yet?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by fer-fullstackdev** [comment]
Hello. Thanks for your quick reply. 
But I am not sure what you want right now. 
Do you want me to add some code to this repo and create pull request that you can reproduce this issue?

**Comment by fer-fullstackdev** [comment]
Hello?

**Comment by fer-fullstackdev** [comment]
Do you want me to invite to my repository? @codebytere

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or app-specific problems since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
