### ISSUE TITLE
Random boxes appearing on Ubuntu

### ISSUE THREAD

**Issue by rajivshah3** [electron/electron#23204]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.3
* **Operating System:**
  * Ubuntu 18.04 x64 (running on Parallels Desktop)
* **Last Known Working Electron version:**
  * 7.2.3

### Expected Behavior
UI works without boxes appearing

### Actual Behavior
Boxes seem to appear somewhat randomly and they sometimes flicker

### To Reproduce

I don't have a minimal reproduction available yet, so here are the instructions to clone our project. I can also provide a build if that's helpful.

```sh
$ git clone https://github.com/iotaledger/trinity-wallet -b snyk-fix-fab81bcd0fb12f6f26adf4de573f2550
$ yarn && yarn deps:shared
$ cd src/desktop
$ npm ci && npm run build && npm start
```

### Screenshots
![image](https://user-images.githubusercontent.com/19519564/79900205-df8f2c00-83db-11ea-8d55-c2e07853549f.png)
![image](https://user-images.githubusercontent.com/19519564/79900213-e453e000-83db-11ea-9d5f-d7ffc85164ee.png)

### Additional Information
I'm still trying to isolate the issue so I don't have much information at the moment. At this time, here's what I know (will update this list as I find more info):

- The boxes seem to pop up after an animation takes place

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
