### ISSUE TITLE
Minimum Height for Frameless, Transparent BrowserWindow on Windows is 65px?

### ISSUE THREAD

**Issue by kassimir** [electron/electron#23200]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.3
* **Operating System:**
  * Windows 10 Pro
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Window to be smaller than 65px.

### Actual Behavior
Window is 65px

### To Reproduce
Create a new BrowserWindow with `frame: false, transparency: false`, and the window will not go smaller than 65px in height.

I would like to create a transparent, frameless window that is no larger than 25px. When it's not transparent, I can get it down to 38px. Even that would be okay, but for some reason, making it transparent adds 27px to the window.

**Comment by kassimir** [comment]
I'm bumping this. I would like some kind of response.

**Comment by marc2332** [comment]
Hello,

Have you tried setting `minHeight ` and `minWidth ` to 25px ?

Docs: https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions

**Comment by frombit** [comment]
did you solve this problem?

**Comment by sgd2z** [comment]
We also run into this problem too. It is a problem with display scaled monitors. We use setShape in addition to setBounds to hide the part of the window that we don't want to show as a workaround to this

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
