### ISSUE TITLE
Redux Devtools can not find store if set userAgent fall back in app

### ISSUE THREAD

**Issue by MinhPhu0304** [electron/electron#23212]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Hi Electron team, I have a weird behaviour in Electron that I encountered recently. If I don't set the userAgent fall back in ```app``` object from Main process, the Redux dev tools can find my redux store. But if I set the userAgent fallback to a specific Chrome version ie: ``` Chrome/79.0.3945.79```, the redux dev tool can not find my store any more.
* **Electron Version:**
  * 8.2.3
* **Operating System:**
  * macOS 10.14.6 
* **Last Known Working Electron version:**
  * Not sure

### Expected Behavior
The redux store should be shown

### Actual Behavior
![Screen Shot 2020-04-22 at 5 04 58 PM](https://user-images.githubusercontent.com/29682322/79942663-71219b00-84bb-11ea-81a8-bdc43f98c1ca.png)

### To Reproduce
The demo code can be found at [this github repo](https://github.com/MinhPhu0304/demo-dev-tools-broken)
Command to set up 
```sh
$ git clone https://github.com/MinhPhu0304/demo-dev-tools-broken.git -b master
$ yarn
$ yarn dev
```

**Comment by MarshallOfSound** [comment]
https://github.com/MinhPhu0304/demo-dev-tools-broken/blob/master/src/main/main.ts#L6

`Chrome/79.0.3945.79` by itself is not a valid user agent string.  Can you try setting it to a legit string for that version of Chrome?  My guess is redux devtools is doing UA sniffing and you providing a bad user agent is causing some internal logic to break.

I don't believe this is an issue with Electron itself.

**Comment by MinhPhu0304** [comment]
I changed the user agent to ```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36``` and redux dev tools still can't find the store

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
