### ISSUE TITLE
how to change nodejs source code which electron's used

### ISSUE THREAD

**Issue by guomh** [electron/electron#23249]
For some reason,I need to change nodejs source code.Then I successed in node for version 14.0.0.
Now I need to use Electron. I found that Electron's node is different from the node I changed.How I can change the Electron's nodejs source code? or how to import the node I changed in Electron?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
