### ISSUE TITLE
Cannot use ELECTRON_ENABLE_SECURITY_WARNINGS and load WASM

### ISSUE THREAD

**Issue by alexdima** [electron/electron#23252]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.3
* **Operating System:**
  * macOS 10.15.4 

### Expected Behavior

I would expect to be able to use `ELECTRON_ENABLE_SECURITY_WARNINGS` and be able to load WASM.

### Actual Behavior

From https://github.com/WebAssembly/content-security-policy/issues/7 , it looks like the only way to be able to use WASM is to add `'unsafe-eval'` to the CSP. But doing that triggers Electron's warning.

### To Reproduce
Self contained example at https://github.com/alexdima/electron-wasm-issue

### Screenshots

Without `'unsafe-eval'`:
![image](https://user-images.githubusercontent.com/5047891/80075250-b4771a80-854a-11ea-8d59-6947de1dc6ef.png)

With `'unsafe-eval'`:
![image](https://user-images.githubusercontent.com/5047891/80075295-c5c02700-854a-11ea-906a-b4485e29df00.png)

### Additional Information

We would like to be able to use `ELECTRON_ENABLE_SECURITY_WARNINGS` and load WASM at the same time.

cc @bpasero @deepak1556

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by alexdima** [comment]
This still reproduces with Electron 11.x using the exact same steps (the same repo)

<img width="899" alt="Screen Shot 2021-03-11 at 09 39 41" src="https://user-images.githubusercontent.com/5047891/110759340-cab6c380-824d-11eb-8e9c-fe1fcc2a8ef8.png">

@codebytere I believe the bot is mistaken in its assessment that this issue is no longer reproducible. I think the tag `8-x-y` indicates that the issue was first discovered in `8-x-y`, not that the issue reproduces **only in** `8-x-y`.

**Comment by zcbenz** [comment]
@alexdima If I understand this issue correctly, I think you would like to keep the `'unsafe-eval'` CSP while still be able to load WASM? Then this is a feature request rather than a bug.

**Comment by alexdima** [comment]
Nice, thank you @zcbenz ! :heart:
