### ISSUE TITLE
setContectProtection allows google chrome on Mac OS to capture the app

### ISSUE THREAD

**Issue by sajjanbalar** [electron/electron#23269]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.2.1
* **Operating System:**
  * macOS 10.14.6
--

* **Last Known Working Electron version:**
  * NA

### Expected Behavior

When I use the setContentProtection(true) api to protect my electron window from being captured, it should not be captured by screen shares done on web apps like Google Meets
### Actual Behavior

On MacOs chrome, Google meets is able to capture my electron window even when setContentProtection is set to true
### To Reproduce

Take the default electron app, call setContentProtection(true) on the main window. Start a google meets conference call and present your screen. The people who you are presenting to, will see your electron app window.

https://gist.github.com/7181aeeaa5203e5a3126d486a11cc11d

### Additional Information

[Link](https://bugs.chromium.org/p/webrtc/issues/detail?id=8652) Electron uses  NSWindowSharingNone to protect the window from getting captured but the new webrtc capturer doesn't respect this.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
