### ISSUE TITLE
getLocale() doesn't work for locales that aren't supported in Chrome

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#23272]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.2.3
  * 
* **Operating System:** macOS 10.14.6, Windows 10, Linux
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

The value returned by `app.getLocale()` should match the operating system's setting for all the locales listed in the [documentation](https://www.electronjs.org/docs/api/locales#locales).

### Actual Behavior

* For languages that are officially supported in Chrome, this works as expected.
* For languages not supported in Chrome, `getLocale()` will return `en-US` regardless of the operating system's setting.

### To Reproduce

* set your operating system's language to Uzbek (Latin).
* Open Electron and check the value of `app.getLocale()`.
* The value should be `uz`, but instead it is `en-US`.

As a result of this issue, we can't provide automatic translations of our app for languages beyond what Chrome supports.

I'm not sure whether this is actually fixable, or if it's a Chromium limitation, but if it's not possible to fix, the documentation should at least indicate which locales are actually supported.

Possibly related to #22630.

**Comment by cln-oss** [comment]
Any updates?

**Comment by savannidgerinel** [comment]
Esperanto (`eo.UTF-8`) is also not supported on Chromium 85.0.4183.83 (Linux)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
