### ISSUE TITLE
When window's transparent property is true, can not emit 'maximize' or 'unmaximize' event correctly

### ISSUE THREAD

**Issue by xland** [electron/electron#23275]
Win 10
Electron `7.1.3`,`8.2.3`

When window's transparent property is true, 
can not emit 'maximize' or 'unmaximize' event correctly.

Minimize runnable code:

```js
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    transparent:true,
  })
  mainWindow.loadFile('index.html');
  mainWindow.on("maximize", () => {
    console.log(1);
  });
  mainWindow.on("unmaximize", () => {
    console.log(2);
  });
  setTimeout(()=>{
    mainWindow.maximize();
  },1200)
```

**Comment by MaksRamenskiy** [comment]
I have the same problem. (frame: false, transparent: true)

But when I double-clicked on element with -webkit-app-region: drag; events emit correctly.

**Comment by tzach-chase** [comment]
A possible workaround is to manually trigger the event when calling `maximize()` (and other methods):
```
onMaximize() {
  mainWindow.maximize();
  mainWindow.emit('maximize');
}
```

I did notice another issue: When double-clicking a draggable area a `resize` event is triggered then followed by two `maximize` events.

**Comment by AmrBinBashir** [comment]
The issue still exists on electron `9.0.0`, setting `transparent` to `true` also disables the window snapping/docking to edges of screen.

**Comment by AmrBinBashir** [comment]
This [workaround](https://github.com/electron/electron/issues/12854#issuecomment-602062349) submitted in #12854 , fixes the issues with maximizing.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
