### ISSUE TITLE
Tray icon size broken on Linux, locked to 22px.

### ISSUE THREAD

**Issue by exander77** [electron/electron#23287]
Broken by this pull request (details there): 
https://github.com/electron/electron/pull/21904

![Screenshot_2020-04-27_00-14-48](https://user-images.githubusercontent.com/2256039/80321566-49656680-881e-11ea-9b11-7d7853d546e0.png)

The icon should have a proper size.

I am using Xfce, but it is probably broken for anybody using larger than 22px icons (which I would say is pretty common with current display resolution).

**Comment by exander77** [comment]
I have made an instruction-level patch, to jump over the code as a workaround:

```
#!/usr/bin/env python3
import sys
import re

# 17b4693:      85 c9                   test   %ecx,%ecx
# 17b4695:      74 6f                   je     17b4706 <_ZN2v88internal17ExternalReference18address_of_jslimitEPNS0_7IsolateE@@Base+0x93d6>
# 17b4697:      83 f9 16                cmp    $0x16,%ecx
# 17b469a:      74 6a                   je     17b4706 <_ZN2v88internal17ExternalReference18address_of_jslimitEPNS0_7IsolateE@@Base+0x93d6>

f = open(sys.argv[1], 'rb+')
data = f.read()
match = re.search(rb'(\x85\xc9.\x6f\x83\xf9\x16\x74)', data)
if match:
    result = match.group(1)
    print('Found:');
    print(match.span());
    new = list(result)
    print(new);
    new[7] = 0xeb
    print(new);
    result = bytes(new)
    f.seek(match.span()[0])
    f.write(result)
    print('Replaced.')
else:
    print('No match.')
f.close()
print('Done.');
```
It is small and should probably work with newer versions as well. I didn't want to recompile the whole electron to get rid of that stupid 22px.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
