### ISSUE TITLE
How to open renderer process microphone permission?

### ISSUE THREAD

**Issue by ZKeLin** [electron/electron#23283]
When i use browser recoder api 'navigator.mediaDevices.getUserMedia', it throw DomException: Permission denied.
![image](https://user-images.githubusercontent.com/16497503/80294699-c7cdf400-879d-11ea-999c-146d8317d7b9.png)

electron version:  "electron": "^8.2.3",

How can i default permit the permission, have some api to open this?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by ahallicks** [comment]
Sounds like this is related to https://github.com/electron/electron/issues/23281

**Comment by ZKeLin** [comment]
I solve it,just add iframe `iframe.allow = 'camera;microphone';`.
