### ISSUE TITLE
BrowserView needs 'show' and 'hide' api

### ISSUE THREAD

**Issue by xland** [electron/electron#23323]
I know user can use `win.removeBrowserView` and `win.setBrowserView` to hide and show BrowserView.
But some times it is difficult to use.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
