### ISSUE TITLE
Multiple resource loads on setAttribute() with Angular

### ISSUE THREAD

**Issue by jjsiman** [electron/electron#23349]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.4
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I'm using Electron to bundle an Angular app. I'm using attribute binding (as shown below), and fragments to load symbols from a master SVG using the `<use xlink:href="">` tag. The master SVG should load once and be cached.

### Actual Behavior
The resource loads for every element as shown below. This behavior is only exhibited in Electron and not in the other major browsers when served with Angular, hence why I am posting it as an issue here.

### To Reproduce
I created a new project and added a master SVG with two symbols. In `app.component.html` I added to `<use>` tags, the devTools again displayed the SVG loading twice.

Here is the repo: [REPO](https://github.com/jjsiman/electron-resource-test)
```sh
$ git clone https://github.com/jjsiman/electron-resource-test.git
$ npm install
$ npm run electron
```

### Screenshots
![Screen Shot 2020-04-30 at 9 43 18 AM](https://user-images.githubusercontent.com/18491599/80717985-91f37d00-8ac7-11ea-947d-0fbd8a11482d.png)
![Screen Shot 2020-04-30 at 9 45 17 AM](https://user-images.githubusercontent.com/18491599/80717989-9324aa00-8ac7-11ea-8d69-66e081c2769c.png)
![Screen Shot 2020-04-30 at 9 45 31 AM](https://user-images.githubusercontent.com/18491599/80717992-9324aa00-8ac7-11ea-9186-6c5d5239c067.png)

Here is the network tab when normally serving through Angular:
![Screen Shot 2020-04-30 at 9 53 43 AM](https://user-images.githubusercontent.com/18491599/80718987-d7647a00-8ac8-11ea-96db-d4171992aed0.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
