### ISSUE TITLE
AES256-SHA256 cipher support

### ISSUE THREAD

**Issue by SwiTool** [electron/electron#23347]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.3
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
It should accept using `AES256-SHA256` cipher, which is in the list of openssl cipher suite.

### Actual Behavior
It throws `RequestError: error:100000b1:SSL routines:OPENSSL_internal:NO_CIPHER_MATCH`
### To Reproduce
```javascript
const https = require('https');

https.request('https://google.com', {
    ciphers: 'AES256-SHA256'
}, console.log);
```

### Screenshots
![image](https://user-images.githubusercontent.com/8834915/80707514-5f0eb080-8aea-11ea-843a-64bc343f8ddc.png)

**Comment by codebytere** [comment]
We use BoringSSL under the hood instead of OpenSSL, leading to some incompatibilities. In order to fix this, we would need to patch BoringSSL itself, leading to increase maintenance burden for a less common algorithm, which we strive to avoid.

In the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
