### ISSUE TITLE
Sync works only on startup with SSL

### ISSUE THREAD

**Issue by 8666** [electron/electron#23394]
I tested two versions and on two OSs (Mac and Win7) and the sync is working fine on startup. After using it for a while when I check the menu there a lot of unsynced changes. Clicking sync blocks the app. 

I can click on the tree but the notes are not loading, it is stuck on the last opened one.

I think it was working fine without SSL. After using a valid Let's Encrypt certificate it is not working properly. I have a VM acting as a server.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.
