### ISSUE TITLE
Opening dev tools black screen followed by crash

### ISSUE THREAD

**Issue by kremeran** [electron/electron#23400]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.2.4
* **Operating System:**
  *  CentOS 7 (ReadonlyRoot) 
* **Last Known Working Electron version:**
  *  

### Expected Behavior
 Dev tools should open and functions normally

### Actual Behavior
 Dev tools box is black and will flicker they are open/closed

### To Reproduce
 
*  Build starter project using electron, react, and electron-builder
*  Copy to CentOS 7 ReadonlyRoot
*  Open developer tools

### Additional Information
 The directory the AppImage is whitelisted in CentOS 7 ReadonlyRoot

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
