### ISSUE TITLE
Can't remove rigth click context menu on Borderless Window (no frame)

### ISSUE THREAD

**Issue by jdounivers** [electron/electron#23454]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.0
* **Operating System:**
  * Windows 10 Pro (1909)
* **Last Known Working Electron version:**
  * ??? Never maybe

### Expected Behavior
Right click context menu should be customized or not shown

### Actual Behavior
Default context menu is shown

### To Reproduce
 * Create a new electron project
 * Set the option `frame` to `false` in the main BrowserWindow constructor
 * Use the code given in the [menu doc api](https://www.electronjs.org/docs/api/menu#render-process) : 
```js
const menu = new Menu()
menu.append(new MenuItem({ type: 'separator' }))
window.addEventListener('contextmenu', (e) => {
  e.preventDefault()
  menu.popup({ window: remote.getCurrentWindow() })
}, false)
```

### Additional Information
I think it's a known issue because i already saw it in the past (5 years ago may be) but i didn't see anyware a bypass of this troubleshot, is there?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
