### ISSUE TITLE
Caching headers are missing on local files

### ISSUE THREAD

**Issue by mihaiav** [electron/electron#23482]
It looks like the static files are missing the cache header(only content-type and cors is being sent) which makes perform quite badly (i.e. flickering on complex/CSS heavy local pages). The static files (bundled with the app) are not supposed to be updated. Why a cache header is not provided? Or at least a method to provide the headers ourselfs through the `protocol.interceptFileProtocol` method.

**Comment by MarshallOfSound** [comment]
The `file://` protocol by definition doesn't have a concept of "cache".  It's a special protocol that doesn't work like other `http` / `https` protocols.  If you want to have some kind of custom cache logic you should register a custom protocol and serve up headers on that custom protocol instead of trying to use the `file:` protocol.

Closing out as this is expected behavior.

**Comment by mihaiav** [comment]
The file protocol doesn't have a concept of Content-Type either and still provides a Content-Type header. I believe adding a cache header as well (preferably customisable) would be beneficial for developers and apps as well.  As the static files are "static" I want the browser engine to cache them(in memory) instead to read them from HDD on each access. The performance difference is visible. Now as a workaround to this limitation I put all the static assets in a single file and use a custom loader.  This is ugly.
