### ISSUE TITLE
webRequest.onHeadersReceived is dead on file:// scheme

### ISSUE THREAD

**Issue by mihaiav** [electron/electron#23485]
### Issue Details
I'm trying to add extra headers(e.g. cache-control) to local files. It seems   webRequest.onHeadersReceived could be one way to do that. The issue is that (as I've just found out) it's not working on the file scheme. Why is that ? The code below never throws:

```
  const localFilter = {
        urls: ['file://*/*']
    };
        session.defaultSession.webRequest.onHeadersReceived(localFilter, (details, callback) => {
                throw("i'm working");
        });

```

* **Electron Version:**
  8.2.5
* **Operating System:**
 MacOS
* **Last Known Working Electron version:**
  8.2.5

### Expected Behavior
throw()/get called when local resources are requested (via fetch or embedded by the html page)
### Actual Behavior
It does nothing
### To Reproduce
on app "ready" event add the handler below:

  ```
  const localFilter = {
        urls: ['file://*/*']
    };
        session.defaultSession.webRequest.onHeadersReceived(localFilter, (details, callback) => {
                throw("i'm working");
        });

```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
