### ISSUE TITLE
App Doesn't run on Win7

### ISSUE THREAD

**Issue by andrewragy** [electron/electron#23509]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  8
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Electron app renders properly on another windows 7 computer

### Actual Behavior

the main window opens but is a blank white

**Comment by Kjuby2** [comment]
I got the same issue on Windows 7 SP1 Pro x64.

The application is a blank white, but it seems that controls (buttons, edit boxes) are presented, because there is a cursor change in proper places and click handlers are working (some API functions are called properly)

Electron Versions: 8.0.0, 8.2.5

**Comment by andrewragy** [comment]
Yes this closely resembles the behaviour in may app. but i fixed it with app.disableHardwareAcceleration()

**Comment by qwerchuan** [comment]
> Yes this closely resembles the behaviour in may app. but i fixed it with app.disableHardwareAcceleration()

 It doesn't work for me

**Comment by Syed-Umair** [comment]
> Yes this closely resembles the behaviour in may app. but i fixed it with app.disableHardwareAcceleration()

But app.disableHardwareAcceleration is not working 8.x

See https://github.com/electron/electron/issues/20702

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
