### ISSUE TITLE
Is it possible to probe event loop to see if anything is running?

### ISSUE THREAD

**Issue by jprichardson** [electron/electron#2358]
In Node.js:

```js
setTimeout(function () {
  console.log(process._getActiveHandles().length)
}, 5000)
```

Would output `1` as the setTimeout is still on the event loop. However, in the `renderer` process, this returns 0. Is there a way to tap into the event loop (presumably v8) and check if anything is pending?

**Comment by mattdesl** [comment]
If I understand this correctly, does it mean CLI tools like [electron-spawn](https://github.com/maxogden/electron-spawn) could use this to auto-quit?

If so :+1: this feature would be amazing.

**Comment by zcbenz** [comment]
Electron itself uses an async handle to implement Node.js integration so that's why `process._getActiveHandles()` is ways >=1 handle.

But even if we avoid creating active handles in Node.js, the Chromium itself still maintains a quite complex message loop, which means even if there is nothing active in Node.js we might still have lots of things running in Chromium.

**Comment by zcbenz** [comment]
I'm closing this as won't fix, because even though we can check whether there is things running in Node, we can not do it for Chromium's message loops. Many tasks of Chromium are designed to run forever, so the state of message loop can only be always running.
