### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed, for NAPI prebuild/cmake module

### ISSUE THREAD

**Issue by bsrdjan** [electron/electron#23587]
Dear Electron Team, 

we have `Error: A dynamic link library (DLL) initialization routine failed.` error with napi module on Windows 10, for Electron 8.2.5, using prebuild/cmake toolchain. 

None of [Using Native Node Modules](https://www.electronjs.org/docs/tutorial/using-native-node-modules) instructions helped and I created an issue for the `prebuild`, with detailed logs: [prebuild#269](https://github.com/prebuild/prebuild/issues/269)

It would be great if you could give a feedback what could be the problem here and in which direction to investigate further?

Manu thanks,
Srdjan

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
