### ISSUE TITLE
Support for NativeFileSystem 

### ISSUE THREAD

**Issue by waterlike86** [electron/electron#23608]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
following the sample in https://web.dev/native-file-system/
turning on the feature flag for NativeFileSystem works and i am able to read files from the local file system, however it fails to get permission to write back the file.
the call to FileSystemHandle.requestPermission fails.

is Electron meant to support native-file-system?

* **Electron Version:**
8.0.2
* **Operating System:**
   Windows 10
* **Last Known Working Electron version:**
N/A

### Expected Behavior
FileSystemHandle.requestPermission shows a prompt

### Actual Behavior
FileSystemHandle.requestPermission fails

**Comment by aleksey-hoffman** [comment]
@waterlike86 just curious, why would you want to use `NativeFileSystem` when you have access to more powerful Node.js APIs?

**Comment by waterlike86** [comment]
> @waterlike86 just curious, why would you want to use `NativeFileSystem` when you have access to more powerful Node.js APIs?

before PWA becomes standard, I would like to write once and run everywhere. So use the NativeFileSystem on web and package it with Electron, using as little of Electron as possible is kind of the strategy.

**Comment by Jaifroid** [comment]
Please note that the API is now called the [File System Access API](https://web.dev/file-system-access/). I agree that this is now needed quite badly, because the API is in a buggy state in Electron 12.0.

I have code that runs as a PWA using this API, but I also support the same code running in an Electron instance. What Electron should do is always return "granted" as the response to `FileSystemHandle.requestPermission`. Instead, Electron fails to launch the permissions dialogue and fails silently, returning "denied" as the response. This makes no sense, given that the API is exposed by the browser instances used in Electron 11 and 12.

With Electron 10.x, the API was not supported at all, and so my code gracefully used the fallback of the standard browser file picker plus Electron path access. That was fine. In 11.x and 12.0, Electron now exposes the File Sstem Access API, but it is incompletely supported: the permissions dialogue does not pop up and permission is denied. This means I cannot use my fallback without adding even more code. Electron should either support the API properly or not support it at all!

FYI, **NWJS** handles this properly: it always returns "granted", and I can access files through this API without the system requiring user confirmation. I don't understand why this doesn't "just work" in Electron too.

My goal is interoperability between PWA and Electron code.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by RangerMauve** [comment]
This is still an issue. :(

**Comment by RangerMauve** [comment]
I'll open a new issue with a repro today. 😁
