### ISSUE TITLE
Accelerators on macOS with case-sensitive file system not working

### ISSUE THREAD

**Issue by fcastilloec** [electron/electron#23619]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.3.0
* **Operating System:**
  * macOS 10.15.4 with **Case-sensitive** APFS

### Expected Behavior
Based on https://www.electronjs.org/docs/api/accelerator#available-key-codes
Also, the application/example has been "trusted" as an Accessibility Client in macOS.
When trying to register a `globalShortcut` using `MediaNextTrack`, `MediaPreviousTrack`, `MediaStop` and `MediaPlayPause` they should work. i.e. :
```js
globalShortcut.register('MediaNextTrack', () => {
// do stuff
})
```

### Actual Behavior
None of the shortcuts get registered, but using the following code does work:
```js
globalShortcut.register('medianexttrack', () => {
// do stuff
})
```
This makes me wonder if having a case-sensitive file system might be the problem.

### To Reproduce
Make sure you have a **case-sensitive** file system and use the previous code.

### Additional Information
I have tried using another camelcase accelerator, `PageUp` and `PageDown`, but those seem to work without any problems.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by fcastilloec** [comment]
I can confirm that this bug is no longer present on electron 12
