### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by aminya** [electron/electron#23613]
#23203 # Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Support **"Deno"** in Electron by default. 
https://deno.land/

### Aditional Information
Deno 1.0 has been released.
https://deno.land/v1

**Comment by nornagon** [comment]
Deno is Rust, which our build system doesn't have support for.

We may consider it if Chromium ever ends up building support for Rust into their build tools. For now it is a non-starter.

**Comment by aminya** [comment]
> Deno is Rust, which our build system doesn't have support for.
> 
Deno is shipped as a binary. I am not sure why a build tool is needed. 

> We may consider it if Chromium ever ends up building support for Rust into their build tools. For now it is a non-starter.

Deno is targeting desktop computers. Chrome is a browser. Waiting for Chrome to make a move is highly unlikely

**Comment by MarshallOfSound** [comment]
@aminya I recommend you look into how Electron is built and what part node plays in its architecture.  Electron **embeds** node by building it alongside Chromium.  Although slightly outdated [this post](https://www.electronjs.org/blog/electron-internals-using-node-as-a-library) explains how we used to build node as a library.

> Deno is shipped as a binary. I am not sure why a build tool is needed.
> Even if you want to build from source (although not needed), it is just 5 shell commands:

The binary is fundamentally useless to us, we don't ship a node binary alongside Electron, as mentioned above we build node as a library.  Building from source also doesn't help us as we'd have to build it *alongside* electron and chromium which means Chromium's build system has to support rust as per the comment above.

Locking this discussion for now to avoid it devolving into a "why not" scenario.  The status here is that there are both technical and non-technical reasons why integrating deno as the JS runtime in Electron instead of node is not possible or wanted at this time. Although that may change in the future my personal opinion is that is won't.
