### ISSUE TITLE
Attempting to call a function in a render window that  has been closed or refleased

### ISSUE THREAD

**Issue by UoToGK** [electron/electron#23611]
I opened a webview, and when I tried to press CTRL +r, he reported the following error
I want to know how to avoid this error, thanks
![image](https://user-images.githubusercontent.com/32165193/82074767-d7da5300-970d-11ea-85bc-1311cd07ba4f.png)

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
