### ISSUE TITLE
keep rendering my electron app on minimize

### ISSUE THREAD

**Issue by peererror** [electron/electron#23624]
I want to keep rendering my electron app on minimize I am capturing my application window but when I minimize I could not get any frames of it I have tried this flag but no result backgroundThrottling 
:false I am using electron version v6.1.11

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
