### ISSUE TITLE
Can we use AddressSanitizer to detect memory issue for electron?

### ISSUE THREAD

**Issue by oldmtn** [electron/electron#23625]
I'm building an electron app, and it will dependent a lot of nodejs c++ addon.
These c++ addon could have some memory issues.
I want to use address sanitizer(https://clang.llvm.org/docs/AddressSanitizer.html) to detect memory issue.

But it will failed when I load the electron.app with address sanitizer.

Does anyone know how to debug electron app with address sanitizer?

Thanks.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nkallen** [comment]
@oldmtn did you make any progress on this? I'd love to try this too
