### ISSUE TITLE
Can't create new browser window with nodeintegration false

### ISSUE THREAD

**Issue by TMaxedCode** [electron/electron#23655]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I read the electron docs and it said that it is best practice to set nodeintegration to false. I did that but then I couldn't create a new browser window since I can't run nodejs in my javascript file. I have a button that is supposed to open a new browser window when its clicked. How would I be able to open a new browser window while setting nodeintegration to false?

**Comment by danielweck** [comment]
IPC-message your main process, and create + open the BrowserWindow from there.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
