### ISSUE TITLE
Question about changing main app asar location

### ISSUE THREAD

**Issue by martinlombana** [electron/electron#23669]
I want to move the main app (app.asar) location, away from the resources folder. Because I want to isolate my app from the rest of the electron framework (for organizational purposes and a custom updater for my app). 

I managed to do it (I used 7Zip, opened electron.asar, init.js and changed the path to the asar location). But I am looking for a cleaner way to do this, and possibly automate it when building electron. 

Is it doable or the way I did it is the only way?

Thanks,

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
