### ISSUE TITLE
[Question] [Ask help] How can I enable 'memlog' and change 'memlog-stack-mode' to 'native-with-thread-names'

### ISSUE THREAD

**Issue by maple-leaf** [electron/electron#23702]
Currently, our electron APP has some performance issues, in order to do some analysis and get more information, we want to use 'chrome://tracing' to help us.
But in order to make 'chrome://tracing' more useful, we need to enable 'memlog' and change 'memlog-stack-mode' to 'native-with-thread-names' to generate tracing data with debug symbols.
I try to configure these twos with
```
// --memlog-stack-mode=native-with-thread-names --memlog='all'
app.commandLine.appendSwitch('memlog', 'all');
app.commandLine.appendSwitch('memlog-stack-mode', 'native-with-thread-names');

```
But the code didn't work, of course, they are placed before app fire 'ready' event.

So how can I make this works?

1. In chrome, I can go to 'chrome://tracing' to make the changes(see the screenshot below). But in electron app, it just shows a blank page, I can't access it.
2. how can I use 'commandLine' to change the flags?

Thanks very much!

![image](https://user-images.githubusercontent.com/3980995/82565985-dc8b8500-9bad-11ea-99b5-904d7e72e6df.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
