### ISSUE TITLE
Multiple windows are opening while launching the application

### ISSUE THREAD

**Issue by sddddfdfdf** [electron/electron#23723]
Our application is developed using electron while launching the application using spectron multiple windows are opening and this is stopping us from automating the application.For execution purpose we are using node js.

Sample Script:-
const Application = require('spectron').Application
const assert = require('assert')
const electronPath = require('electron') 
const path = require('path')
const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');
 global.before(() => {

     chai.should();
     chai.use(chaiAsPromised);
	 
  });
describe('Application launch', function () {   
it('Launching the application',function (done) {
	this.timeout(1000);
     const opts = {		
  path: 'C:/Spectronexcecution/app.exe'  
};
const app = new Application(opts)
done();
return app.start().then( async () => {
      await app.browserWindow.focus();
      await app.browserWindow.setAlwaysOnTop(true);
	   });
done();
  })   
  it('Closing the application',function () {
    if (this.app && this.app.isRunning()) {
      return this.app.stop()
    }
  })     
})

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
