### ISSUE TITLE
binarie execution not working on electronjs build

### ISSUE THREAD

**Issue by joaojlf4** [electron/electron#23737]
I'm trying to execute a .exe that's in my app folder on electron-react bloatfree boilerplate. It works on development but when i build the aplication, it's like electron-builder "ignores" the .exe file. How can I maintain the file on the application after build?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
