### ISSUE TITLE
Is it possible to install and use Deno as dependency for an electronjs app?

### ISSUE THREAD

**Issue by sujeet-agrahari** [electron/electron#23734]
I want to built an app using electronjs. I need Deno as a dependency for that app.

I know I can install npm packages inside an electron app, and also I can use nodejs.

But, is it possible to install Deno as a dependecy? Is there any doc to use these kind of app, which are not npm modules, as a dependency for an electron app?

**Comment by vladimiry** [comment]
https://github.com/electron/electron/issues/23613

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
