### ISSUE TITLE
taking more than 30secs to load app

### ISSUE THREAD

**Issue by ashu-ch** [electron/electron#23744]
I am working on a laravel desktop application. The app runs properly but only issue is that it's taking to much time to redirect from one page to another. In web browser the pages open within 1 sec but in electron it's taking more than 30secs.

electron version: 9.0.0,
laravel: 5.3
OS: Ubuntu

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or requests for debugging one's own app since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
