### ISSUE TITLE
Disable window-state-main.json option

### ISSUE THREAD

**Issue by Speuta** [electron/electron#23752]
Can we please have an option to disable the `window-state-main.json` file ?

I suppose it's a Google Chrome feature...

Maybe in createWindow(), something like `keepLastUserWindowSize: false` ?
Or `fixedSizeAtStart: true` ?

Thank you

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
