### ISSUE TITLE
Change client area size independently of window size?

### ISSUE THREAD

**Issue by tejasmanohar** [electron/electron#23758]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

On Electron v8, it seems that calling BrowserWindow.setContentSize adjusts the overall window size and calling BrowserWindow.setSize adjusts the client area / webpage size? How do I control the window client area size independently of the browser window size? The only way I've find to work is changing the viewport with `enableDeviceEmulation` but that doesn't feel right

Goal: I want to make the BrowserWindow part of the window smaller so the BrowserView part of the window doesn't overlap with it

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
