### ISSUE TITLE
`app.getPath('userData')` gives invalid path if Product Name has invalid characters

### ISSUE THREAD

**Issue by papb** [electron/electron#23754]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior

Calling [`app.getPath('userData')`](https://www.electronjs.org/docs/api/app#appgetpathname) should always give a valid path

### Actual Behavior

If my app's Product Name contains characters which are not valid for a folder name, such as `:` in windows, `app.getPath('userData')` will generate an invalid path (since it simply concatenates the Product Name):

```
C:\Users\Pedro\AppData\Roaming\Foo: Bar
```

### To Reproduce

Create any electron app with `productName: "Foo: Bar"` in `package.json` and call `app.getPath('userData')` and see the invalid path be returned.

If you want a step-by-step reproduction guidance:

* Clone `https://github.com/electron/electron-quick-start`
* Add `productName: "Foo: Bar"` to `package.json`
* Add `console.log(app.getPath('userData'))` to `main.js`
* Run and see it log `C:\Users\Pedro\AppData\Roaming\Foo: Bar`

### Additional Information

Suggestion: [filenamify](https://github.com/sindresorhus/filenamify) could be used internally by electron.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
