### ISSUE TITLE
requestHeaders is undefined  in onHeadersReceived

### ISSUE THREAD

**Issue by liximomo** [electron/electron#23795]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *	8.2.2
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
`detail.requestHeaders` is always defined

### Actual Behavior
`detail.requestHeaders` is undefined for some requests

### To Reproduce
```js
ses.webRequest.onHeadersReceived(
    {
      urls: ["https://*/*"]
    },
    (details, callback) => {
      console.log('details', details)
      callback({ responseHeaders: details.responseHeaders });
    }
  );
```

**Comment by Juice10** [comment]
I'm having the same issue in version 9.0.x

**Comment by NilSet** [comment]
Based on the typescript types, requestHeaders should always be defined on details, but it is clearly not.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
