### ISSUE TITLE
navigator.mediaDevices.getUserMedia return active audio stream if Microphone is disable.

### ISSUE THREAD

**Issue by FitsnerAS** [electron/electron#23792]
navigator.mediaDevices.getUserMedia return active audio stream if microphone is disabled via System preferences>Security&Privacy>Privacy..

### Issue Details

* **Electron Version:**
  * 7.1.11
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
Return an error if microphone is disable

### Actual Behavior
Active stream is returning

### To Reproduce
make navigator.mediaDevices.getUserMedia with:{
    audio: {optional: [
      {autoGainControl: true},
      {echoCancellation: true}
   ]},
   video: false 
}

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
