### ISSUE TITLE
Shadow missing on frameless windows in linux

### ISSUE THREAD

**Issue by tommoor** [electron/electron#2380]
We've found that under linux when setting a browser-window to `frame: false` then it loses it's shadow. Note, this is not a transparent window, just a frameless one. This was tested on Ubuntu 14.04.

Expected behaviour is that the shadow remains as it does on OSX and Windows.

**Comment by zcbenz** [comment]
Whether to show shadow for a frameless window completely depends on the window manager, on OS X the real frameless window doesn't have shadow too and it is fixed by using a window with frame while resizing the content area to covert the frame. However I don't think there is a way to fix this on Linux, because the frame and shadow are drawn by the window manager.

**Comment by tommoor** [comment]
@zcbenz is there a reason that you couldn't take a similar approach to OSX on linux, covering the frame?

**Comment by zcbenz** [comment]
@tommoor The window manager is in charge of drawing the frame, and there is no simple way to cover what's drawn by the window manager.

**Comment by tommoor** [comment]
Ew.

I see the problems, unfortunately this makes the frameless window not too useful at all on Linux as if you draw the shadow yourself in css then the window can't be resizable (the real bounds are at the edge of the shadow). And if you don't draw a shadow then a white window completely merges into other white windows.

We might need some wacky alternative ideas on how to achieve this!

**Comment by zcbenz** [comment]
I'm closing this since unfortunately this is a platform limitation of Linux and I don't see any way to work around it.
