### ISSUE TITLE
Causes Latte Dock to freeze while VSCode open

### ISSUE THREAD

**Issue by TechnicalJohn** [electron/electron#23803]
Please reference [VSCode Issue #94651](https://github.com/microsoft/vscode/issues/94651).

Apparently this issue, which was originally reported with VSCode, can be replicated using https://www.electronjs.org/fiddle. 

**STEPS TO REPRODUCE**

1. Latte Dock running on left side, 1 KDE panel at top hosting system tray and clock, 4 virtual desktops.
2. open Electron Fiddle
3. Switching virtual desktops seems to initiate this behavior, as well as starting additional applications, like Calc
4. The animations of Latte and response become slowed by at least 2 seconds, sometimes even longer.
5. After closing Electron Fiddle, Latte immediately begins acting as expected without delays.

**SOFTWARE/OS VERSIONS**
Linux/KDE Plasma: Kubuntu 18.04
(available in About System)
KDE Plasma Version: 5.12.9
KDE Frameworks Version: 5.44.0
Qt Version: 5.9.5
Kernel Version: 5.3.0-7642-generic
OS Type: 64-bit
Hardware: Intel i7-4710MQ; 16GiB RAM
Latte Dock: 0.8.9
VSCode
Version: 1.43.2
Commit: 0ba0ca5
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-7642-generic

VS Code version: Code 1.43.2 (0ba0ca5, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-7642-generic

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
