### ISSUE TITLE
app.showAboutPanel doesn't show icon set by app.setAboutPanelOptions

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#23850]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.3.0
* **Operating System:**
  *  Ubuntu 20.04 x64
* **Last Known Working Electron version:**
  *  -

### Expected Behavior

Icon set by `setAboutPanelOptions` method is shown in about window.

### Actual Behavior

Icon is shows as error icon.

![VirtualBox_Ubuntu_29_05_2020_16_10_23](https://user-images.githubusercontent.com/780935/83275171-191f3800-a1cf-11ea-8211-6f6cb15f6312.png)

### To Reproduce

```js
app.setAboutPanelOptions({
  iconPath: path.join(__dirname, 'resources/icon.png'),
});
await app.showAboutPanel();
```

### Additional Information

It happens at least in `deb` package packaged by `electron-builder`.

**Comment by codebytere** [comment]
I had no issue when running [this fiddle](https://gist.github.com/c37918ea0059b1dfb0b38953f71f6e0e)

<img width="1223" alt="Screen Shot 2020-05-29 at 12 32 03 PM" src="https://user-images.githubusercontent.com/2036040/83298079-a7cc8e80-a1a8-11ea-92c9-929def3fadd6.png">


Are you sure you're specifying the path correctly?

**Comment by mahnunchik** [comment]
@codebytere not packaged as **deb** version works as expected. Produced asar have icon on right place. Windows build works as expected.

I'm going to check snap version.

Question: Is any way to add image inside of fiddle to have reproducible deb package?

**Comment by mahnunchik** [comment]
@codebytere Hi, I have more info.

Packaging any linux targets with `asar` option produces broken icon in about window.

**Comment by dragonDScript** [comment]
Can't repro, Ubuntu 20.04

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by kiruh** [comment]
@mahnunchik  are there any updates on this issue?

**Comment by kiruh** [comment]
Same issue still occurs in **electron@12.0.9**
