### ISSUE TITLE
Windows: The number of handles increase in WINDOWS system when reload page or close and reopen the window

### ISSUE THREAD

**Issue by EattingGrass** [electron/electron#23904]
![image](https://user-images.githubusercontent.com/12228784/83505841-f2c40a00-a4f8-11ea-9c59-1905636084e2.png)

Like picture above. Can I decrease the handles manually?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.
