### ISSUE TITLE
Get reference to new Window if loadedurl will open

### ISSUE THREAD

**Issue by mrzewnicki** [electron/electron#23937]
I'm new with Electron and i face with problem. Generally i would like to write a scrapper to website and run in as desktop app. When i load page using mainWindow.loadURL(url) and log ing usccessfully the site always open for me new window. I would like to now how can i catch this new window.

I thinked to keep it in some global array to keep access for later use but how can i catch it. I tried mainWindow.webContents.on('new-window' but it doesnt work..
```

app.on("ready",function(){
 mainWindow = new BrowserWindow({});

 mainWindow.loadURL(myUrl);

 mainWindow.webContents.on('did-finish-load', function() {
    // Here i'm log in using mainWindow.webContents.executeJavaScript
    // And here after log in, new window is opening, how can i catch this window from main
 });

});
```
Thank you for all sugesstions

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
