### ISSUE TITLE
ssh2-sftp-client module

### ISSUE THREAD

**Issue by insmart-application-developers** [electron/electron#23942]
I have a problem with ssh2-sftp-client module.

When i am using node for running, it's ok.
But when using electron-angular, i get some errors like below.

Error: connect: Error while signing data with privateKey: error:06000080:public key routines:OPENSSL_internal:UNSUPPORTED_ALGORITHM after 2 attempts

Are there some idea for me to handle this case?

Sorry, my English is not good.

**Comment by codebytere** [comment]
We use BoringSSL and not OpenSSL as Node.js does owing to our embedding structure - BoringSSL is a fork of OpenSSL with some esoteric functionality stripped out. In order to fix this, we would need to apply patches on top of BoringSSL, which would add nontrivial maintenance cost we strive to avoid.

As such, i'm going to label this a `wontfix`, but you're welcome to open a feature request against BoringSSL itself, and if they add it it will become available through Electron.
