### ISSUE TITLE
[Mac] electron zip cannot be packaged since electron > 8.2.5

### ISSUE THREAD

**Issue by CapOM** [electron/electron#23950]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.0.2 (fails since 8.3.0)
* **Operating System:**
  * 
Mac

* **Last Known Working Electron version:**
  * 
8.2.5

### Expected Behavior

Archive MyApp-1.0.0-mac.zip can be unzip

### Actual Behavior

```
Archive:  package/MyApp-1.0.0-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of package/MyApp-1.0.0-mac.zip
```

### To Reproduce

Run `node pack.js` and then `unzip -t package/MyApp-1.0.0-mac.zip`

### Screenshots

None

### Additional Information

See attached pack.js 

[pack.zip](https://github.com/electron/electron/files/4725068/pack.zip)

**Comment by CapOM** [comment]
See last commit here to reproduce: https://github.com/CapOM/electron-quick-start/commits/pack_issue and run : 

```
npm install
npm run pack
unzip -t package/MyApp-1.0.0-mac.zip
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
