### ISSUE TITLE
Reloading devToolsWebContents closes process

### ISSUE THREAD

**Issue by Kilian** [electron/electron#23982]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.2.0, 9.0.2
* **Operating System:** Ubuntu 18.04 x64 

### Expected Behavior
Calling `mainWindow.devToolsWebContents.reload();` does not close the process and reloads the devtools.

### Actual Behavior
`mainWindow.devToolsWebContents.reload();` closes the process, no crash message.

### To Reproduce
Open this fiddle, press the reload button: https://gist.github.com/b794a68cc2d6400aea05cf200602e53b

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
