### ISSUE TITLE
CTRL + C multiple files on the desktop, how to get the path of multiple files through CTRL + V

### ISSUE THREAD

**Issue by bei-yang** [electron/electron#23981]
### Problem Description

Copy and paste a file path with the following code:

```js
// win

let filePath=clipboard.readBuffer('FileNameW').toString('ucs2')

filePath=filePath.replace(RegExp(String.fromCharCode(0),'g'),'')

// mac

let filePath=clipboard.read('public.file-url').replace('file://','')
```

But I copy multiple files, using the code above is the path to the last one, how do I get all of them

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
