### ISSUE TITLE
contextmenu for copy/paste/cut can't work

### ISSUE THREAD

**Issue by smildlzj** [electron/electron#24007]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.x
* **Operating System:**
  * win32

### Expected Behavior
copy/paste/cut work

### Actual Behavior
copy/paste/cut not work

### To Reproduce
if document have `webview`，contextmenu role for copy/paste/cut can not work

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="format-detection" content="telephone=no">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" />
</head>
<body>
<textarea class="content"></textarea>
<webview src="https://www.baidu.com"></webview>

<script>
  var $ = require('jquery')
  var remote = require('electron').remote


  let menus = [{
    label: 'copy',
    role: 'copy',
  }, {
    label: 'cut',
    role: 'cut',
  }, {
    label: 'paste',
    role: 'paste',
  }]
  let Menu = remote.Menu
  let menuObj = Menu.buildFromTemplate(menus)



  $('.content').on('contextmenu', (event) => {
    menuObj.popup({ window: remote.getCurrentWindow() })
  })
</script>

<style>
  .content {
    border: 1px solid #000;
    height: 300px;
  }

</style>
</body>
</html>
```

**Comment by vladimiry** [comment]
#15219

**Comment by elmeet** [comment]
I also have this problem.
windows 64 bit
Electron 9.0.2

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
