### ISSUE TITLE
Is v9.0.3 coming to npm repository?

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#24002]
[v9.0.3](https://github.com/electron/electron/releases/tag/v9.0.3) released ~24 hours ago but npm repository still missing this version.

It was not npm published because some checks of 4ad03dc60a062691bb993803b970e2ec936aa0a2 commit failed or there is another reason?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by ArisuOngaku** [comment]
@miniak this is a bug report not a question (despite the title)

**Comment by vladimiry** [comment]
I wanted to try #23674 change in action on 9.0.3 so I could close #21576 But I realized that 9.0.3 release was not published on npm repository. So yet this is a bug report (I guess an infrastructure / build scripts issue), since I expect all releases to be npm-publihsed.

**Comment by codebytere** [comment]
@vladimiry we had a release hiccup which is being handled as we speak! expect it to be published soon.

**Comment by MarshallOfSound** [comment]
With a bit of convincing `9.0.3` has decided to make itself available on npm 😄
