### ISSUE TITLE
webContents.executeJavaScript firing multiple times after first execution (Accumulating)

### ISSUE THREAD

**Issue by bxi-iripple** [electron/electron#24047]
### Issue Details

* **Electron Version:**
  * 4.2.12
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
* execute javascript code in renderer using webContents.executeJavaScript once in a single iteration in a loop

### Actual Behavior
* after executing on the first iteration, webContents.executeJavascript seems to be executed cumulatively

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by sofianguy** [comment]
Additionally, the version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 7.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

**Comment by bxi-iripple** [comment]
Thank you for replying though. I may be writing a detailed reproduction on this issue but not sure when. I still have a lot of tasks to work on will get back to you whenever I can. Thank you for your time.

**Comment by sofianguy** [comment]
@bxi-iripple Thank you for your issue!

We haven't gotten a response to our questions in our comment for a repro. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
