### ISSUE TITLE
Simple fullscreen: monitor location not preserved when leaving simple fullscreen

### ISSUE THREAD

**Issue by bpasero** [electron/electron#24048]
### Issue Details

* **Electron Version:**
  * 8.1.3
* **Operating System:**
  * macOS 10.15.x
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Leaving simple fullscreen does not move window to primary monitor.

### Actual Behavior
Window moves back to primary monitor after leaving simple fullscreen.

### To Reproduce

Take the following code into a Fiddle:

```js
function createWindow() {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    },
    fullscreenable: false,
    simpleFullscreen: true
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  setTimeout(() => {
    mainWindow.setSimpleFullScreen(true);

    setTimeout(() => {
      mainWindow.setSimpleFullScreen(false);
    }, 5000);
  }, 5000);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}
```

Start the app and move the window to a secondary monitor. Wait for 10s until the simple fullscreen was entered and left. The window is being moved back to the original primary monitor and does not stay on the secondary one.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by bpasero** [comment]
@nornagon @samuelmaddock @codebytere @deepak1556 this reproduces with Electron `v13.0.0-beta.5`.

**Comment by bpasero** [comment]
I am not aware of any changes in this area that would have addressed this issue, @zcbenz please reopen.
