### ISSUE TITLE
protocol.registerFileProtocol时候不允许带参数

### ISSUE THREAD

**Issue by devmings** [electron/electron#24056]
在使用registerFileProtocol时不允许带参数 比如  /home/index.html?path=abc 这样就不行
当使用registerHttpProtocol时，回调的url为 file://时，在mac os下可以正常使用，在win下就报协议不存在

顺便请问一下，需要传递参数访问本地的资源下。有什么推荐的办法呢？

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
