### ISSUE TITLE
Always on top on multiple displays

### ISSUE THREAD

**Issue by somsarashvili** [electron/electron#24096]
### Issue Details

* **Electron Version:**
  * 7, 8, 9
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 6.1.12

### Expected Behavior
The browser window must be on top over all OS windows

### Actual Behavior
BrowserWindow goes under other apps if opened another app on second screen and then clicked on BrowserWindow again

### To Reproduce
```
  const mainWindow = new BrowserWindow({
    x: 0,
    y: 0,
    frame: false,
    alwaysOnTop: true,
    fullscreen: true,
  });

  mainWindow.loadURL('data:text/html;charset=utf-8,Hello World!');
  mainWindow.on('focus', () => console.log('is on top:', mainWindow.isAlwaysOnTop()));
```
Focus BrowserWindow, then any app on secondary screen and again the BrowserWindow. Repeat it to get an output in console
### Screenshots
![image](https://user-images.githubusercontent.com/52104791/84502998-6c62b180-acca-11ea-88e6-906b34327bbe.png)

### Additional Information
Changing focused apps will log  ``isAlwaysOnTop`` status which sometimes is ``true`` and sometimes ``false``

**Comment by JMS-1** [comment]
similiar problem after jumping from v6 to v10 but in scenarios with multi-display, single-display and active VNC as well as single-display only. Since I've a bit of a different scenario with reproducing the error purely in electron maybe the appended app helps locating the origin:

* make sure some random windows are open
* unpack; npm install; and npm run start
* the main window appears (actually over some background window behind)
* click the single link - the main window is **shifted** (and clipped in width) to the right and loaded with some other stuff
* the button left on the background window will just shift back the main window and reload it's contents

On Windows 10 the main window goes to the background and the random windows from above appear - on Linux everything is fine. You can click somewhere in it to bring it to front. BUT when you use the link to show the background and then click somewhere on the background window (NOT the button) everything moves to the BACK!

In addition there is one more point which is really strange: I use a FullHD test Windows 10 test system and both windows are initially FullHD 1920x1080. If you change BOTH windows widths from 1920 to **1919** the effect disappears and it works as it should - beside the fact that there is a one pixel gap. 1921 behaves like 1920. One more surprising behaviour (may be Windows): I use Visual Studio Code (electron based) on a secondary monitor. If I **maximize** it, there is a **pixel line to the left** on the primary monitor (secondary is configured to the left, primary to the right but)! This does NOT happen with Fullscreen (F11). Maybe somewhere there is a miscalculation (off-by-one :-) )

![image](https://user-images.githubusercontent.com/3493757/91470882-907b6b00-e895-11ea-81a0-7d119935f01a.png)

App Code (tiny repro)

[electron-10.zip](https://github.com/electron/electron/files/5137634/electron-10.zip)

Regards

Jochen

**Comment by JMS-1** [comment]
I did some further tests:

* no difference with 10.0.1
* but it seems (hm) that this **only happens** if the taskbar is made invisible (auto hide enabled) - actually can't believe this because I thought I tested both ways but now its quite repeatable

**Comment by JMS-1** [comment]
an explicit setAlwaysOnTop(true, "normal") after creating the BrowserWindow does the job for me. The trick seems to be the "normal" which perhaps explains the interference with the hidden task bar.

Sorry to bother (although the 1920/1919 issue is still surprising).
