### ISSUE TITLE
Blockbench doesn't start.

### ISSUE THREAD

**Issue by FentisDev** [electron/electron#24117]
Hi!

Since 3.5.0 if I'm not mistaken it gives this error. I do not know why.
I'm using the desktop version on a Windows 10 64bit.
Thanks!

https://prnt.sc/syv79w

Data exported | 2020-06-13T04:04:03.651Z
-- | --
Chrome version | Chrome/80.0.3987.163
Operating system | Windows NT 10.0.18363
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/e7fbe071abe9328cdce4ffedac9822435fbd3656/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/e7fbe071abe9328cdce4ffedac9822435fbd3656/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 362168eb695d
2D graphics backend | Skia/80 a91f9f612e5eeb93cf40a3c0ce7d7c6ddf838feb
Command Line | "C:\Users\mateu\AppData\Local\Programs\Blockbench\Blockbench.exe" --allow-file-access-from-files --ignore-gpu-blacklist

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
