### ISSUE TITLE
Electron Apps Control Panel

### ISSUE THREAD

**Issue by sobujbd** [electron/electron#24122]
Thanks Electron,

Today, is there many useful apps based on Electron. That's great.

Can we think about decreasing electron app size.

What's the biggest part, that increase Electron apps sizes?

Can we make default path for those files and a control panel to mange those files/components and a way to link (can be found from) to the Electron apps.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
