### ISSUE TITLE
get source for the designed branch or tags fail

### ISSUE THREAD

**Issue by bigben0123** [electron/electron#24169]
On windows, when I use 
 e init master-testing --root=~/src/electron
 e sync
It's ok.

Now I want to swith to branch 7-3-x. I can't figure out where to go. 

I use " e sync --revision 7-3-x", it shows checkout 7-3-x success. But source code is not update. When I force sync, it error.
or should I modify .gclient to http://github.com/electron/electron@7-3-x on unmanaged url?
Does unmanaged affect switch branch?

I don't find any tip on internet.

**Comment by bigben0123** [comment]
or how to set reversion in config file:

"origin": {
"electron": "git@github.com:electron/electron.git",
"node": "git@github.com:electron/node.git"
},

like :git@github.com:electron/electron.git@7-3-x

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

Additionally, for building electron, you should use [`build-tools`](https://github.com/electron/build-tools) and open subsequent issues there.
