### ISSUE TITLE
electron push to git repo file too large

### ISSUE THREAD

**Issue by natedetsi** [electron/electron#24186]
I have a electron app that i have been build for a while now. At some point I managed to push node_modules/electron to the repo. 

Now when I try and push a commit i get this error: 
remote: error: File node_modules/electron/dist/electron.exe is 107.79 MB;

I have tried to remove the node_modules folder and electron files like so 
git rm -r cached node_modules
git commit --amend -CHEAD

but it still tries to push the electron folder to the repo. Even if I fully remove the node_modules folder and repeat the above I get the same error. I even tried pushing to a completely new repo and still get the same issue

anyone have any clues, posting here because electron seems to be the root of the issue

**Comment by Timibadass** [comment]
ensure you're not pushing the 'build' folder for your app to your GitHub. I once had this issue and I found out that it was because of that.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
