### ISSUE TITLE
app showing in task manager even after close.

### ISSUE THREAD

**Issue by coder963** [electron/electron#24197]
I am using two windows in electron. The scenario is like this-
On clicking button in first window, I am hiding this window and showing second window. and in second window there is close button which is calling getcurrentwindow.close(). 

My issue is should I close first window too as this is still running in task manager. if yes then how as getcurrentwindow is refering to second window.

**Comment by pushkin-** [comment]
use [`BrowserWindow.getAllWindows()`](https://www.electronjs.org/docs/api/browser-window#browserwindowgetallwindows)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
