### ISSUE TITLE
Possible to specify default tab in DevTools ?

### ISSUE THREAD

**Issue by proto6** [electron/electron#24205]
Simple question:

Is is possible to specify the default tab that will be shown once DevTools open ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community)

 There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
