### ISSUE TITLE
Yarn Workspaces with Electron: Module can't be resolved

### ISSUE THREAD

**Issue by jordymeow** [electron/electron#24208]
Hello,

I am trying to use Yarn Workspaces with Electron. I have some simple React components in a /common directory. It looks like this.

- /root
- /root/common/
- /root/electron/

I am getting an error that my module _common_ can't be resolved. I have no idea why, no idea where to look, and I am not sure what to share :) I am looking for a plain and simple setup that works, but unfortunately I haven't find a repo doing this simply.

I had the feeling it was supposed to work out of the box. Is there any specific configuration required? Or maybe it just can't work?

I am using Yarn 1.22 and Electron 8.2.

Thanks a lot for your help.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
