### ISSUE TITLE
Image could not be created [Icon in BrowserWindow]

### ISSUE THREAD

**Issue by SentoxAIO** [electron/electron#24201]
* **Electron Version:** ^9.0.4
*  **Operating System:** Windows 10
* **Last Known Working Electron version:** Same version

### Expected Behavior
Icon/Image should be created, which it also did before. I just switched the image.

### Actual Behavior
Throws this error;`Error: Image could not be created from ./../html/assets/images/logo.ico` even tho this file is accessible and the path is 100% right.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### To Reproduce
- Not really reproduceable

### Screenshots
![image](https://user-images.githubusercontent.com/57367608/85074262-95001500-b1bc-11ea-8720-bc9aa2cda46b.png)
![image](https://user-images.githubusercontent.com/57367608/85074310-a21d0400-b1bc-11ea-99f3-81e30abce642.png)
![image](https://user-images.githubusercontent.com/57367608/85074337-aba66c00-b1bc-11ea-877e-268b26bb84db.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by SentoxAIO** [comment]
@codebytere I edited my issue and I hope you can now work with it.

**Comment by codebytere** [comment]
@SentoxAIO oh i missed that it's an `.ico` file. We only support `png` and `jpg` at present, see: https://github.com/electron/electron/blob/21a6062a31eaf5cb6493fe5acce4b60704bbc96a/docs/api/native-image.md#L32-L33
