### ISSUE TITLE
frameless can not close window

### ISSUE THREAD

**Issue by ZeronoFreya** [electron/electron#24218]
* **Electron Version:**
  * 9.0.4
* **Operating System:**
  * Windows 10 home (1903)

I am use electron with VueJs
```
import {
  app,
  protocol,
  BrowserWindow,
  Menu,
  ipcMain
} from "electron";

// ...

 win = new BrowserWindow({
    width: 1200,
    height: 620,
    frame: false,
    webPreferences: {
      nodeIntegration: true
    }
  });

// ...

ipcMain.on("close", () => {
    win.close()
  });

```
In Titlebar.vue
```
const {ipcRenderer} = window.require('electron')

// ...

methods: {
      close(){
        ipcRenderer.send("close");
      }
}
```
`win.close()`  can not close window, but `win.destroy()` can.
Is this bug?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community).

There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by yurnery** [comment]
the same to me, and I can't find any available solution about this issue.

**Comment by yurnery** [comment]
@ZeronoFreya  I found the way to fix it, the point is that you can't retain the window on mainProcess.
before in my `main.js`, I have a variable to store the window, now I change it to store the window.id, everything runs well.
