### ISSUE TITLE
Blank Pop-up when used with Azure AD B2C

### ISSUE THREAD

**Issue by ShruthiMallaiah** [electron/electron#24213]
Electron Version: 8.2.5

Expected Behavior:
 Visible pop-up with Azure AD B2C login

Actual Behavior
Blank screen with only close, minimize and maximize icon

Thsi is the actual pop-up we are supposed to get in the pop-up.
Additional Information
![Default Sign In](https://user-images.githubusercontent.com/28384851/85154462-1b782d80-b275-11ea-920f-afd7661c6d6c.PNG)

Instead I am getting the blank screen as shown below.
![Blank-PopUp](https://user-images.githubusercontent.com/28384851/85154135-b15f8880-b274-11ea-9191-6b8f8b53e5c8.PNG).

I am using msal.js for authentication. 
npm Package - msal - Version 1.3.2
Electron Version: 8.2.5

Pop-up is working fine while I run in the development mode. But when I deploy the package and run the Windows Installer package, I am not able to see the pop-up. Please find the screenshot for your reference. Usually default screen is coming in Development mode, but when I ran the Installer package this seems to be not working.

Can't able to produce the repository as it needs the Azure login details and setup. Kindly assist.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or app-specific issues since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
