### ISSUE TITLE
"cannot use import statement outside a module" but package.json present

### ISSUE THREAD

**Issue by marcoippolito** [electron/electron#24212]
When running electron. I get "cannot use import statement outside a module" 

     (base) marco@pc01:~/webMatters/vueMatters/GGC$ electron .
    App threw an error during load
    /home/marco/webMatters/vueMatters/GGC/src/background.js:3
    import { app, protocol, BrowserWindow, Menu, Tray, session } from 'electron'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at Module._compile (internal/modules/cjs/loader.js:895:18)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Module._load (internal/modules/cjs/loader.js:727:14)
        at Function.Module._load (electron/js2c/asar.js:738:28)
        at loadApplicationPackage (/home/marco/.nvm/versions/node/v14.3.0/lib/node_modules
    /electron/dist/resources/default_app.asar/main.js:109:16)
        at Object.<anonymous> (/home/marco/.nvm/versions/node/v14.3.0/lib/node_modules/electron
    /dist/resources/default_app.asar/main.js:155:9)
         at Module._compile (internal/modules/cjs/loader.js:967:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
    (node:5783) Warning: require() of ES modules is not supported.
    require() of /home/marco/webMatters/vueMatters/GGC/src/background.js from /home/marco
    /.nvm/versions/node/v14.3.0/lib/node_modules/electron/dist/resources/default_app.asar/main.js is  
    an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" 
    which defines all .js files in that package scope as ES modules.
    Instead rename background.js to end in .cjs, change the requiring code to use import(), or remove  
    "type": "module" from /home/marco/webMatters/vueMatters/GGC/src/package.json.
    Gtk-Message: 16:43:15.567: GtkDialog mapped without a transient parent. This is discouraged.
     MESA-LOADER: failed to retrieve device information
    MESA-LOADER: failed to open nouveau (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}
    /dri:/usr/lib/dri)
    failed to load driver: nouveau
    MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/x86_64-linux-
    gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
    failed to load driver: kms_swrast
    MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}
    /dri:/usr/lib/dri)
    failed to load swrast driver

vue info

    Environment Info:
      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
      Browsers:
        Chrome: 83.0.4103.106
        Firefox: 77.0.1

head /src/background.js

    /src$ head background.js 
    'use strict'

    import { app, protocol, BrowserWindow, Menu, Tray, session } from 'electron'
    import {
      createProtocol,
      /* installVueDevtools */
    } from 'vue-cli-plugin-electron-builder/lib'

    import { menubar } from 'menubar';

/src$ cat package.json   :   

    { "type": "module" }

electron packages installed: 

    │ │ ├── electron-to-chromium@1.3.364
    │ │ │ ├── electron-to-chromium@1.3.427
    │ │ ├── electron-to-chromium@1.3.427
    ├─┬ electron@9.0.4
    │ ├─┬ @electron/get@1.12.2

    │ └── electron-positioner@4.1.0
    ├─┬ vue-cli-plugin-electron-builder@2.0.0-rc.2
    │ ├─┬ electron-builder@22.7.0
    │ │ │ ├─┬ electron-publish@22.7.0

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by frank-dspeed** [comment]
@codebytere that was no question i guess!

I have the same issue the issue is that electron does not hornor package.json type fild

**Comment by Pomax** [comment]
The question implicit to this issue was "why does this happen? because the documentation does not explain this: can you please update the documentation to cover this subject so that I and everyone in the future can recover from this opaque error?"

So: why does this happen? because the documentation does not explain this: can you please update the documentation to cover this subject so everyone can recover from this opaque error because googling for it finds us the page on the electron site that explains how to solve this (increasingly more common problem) now that Node LTS has native ESM support, and packages with `type: "module"` are no longer curiosities?

**Comment by gebilaofan** [comment]
使用require就没有报错

**Comment by gebilaofan** [comment]
还没有解决嘛？？？？ 我现在也遇到这个问题

**Comment by sebheitzmann** [comment]
+1

**Comment by saifsmailbox98** [comment]
+1

**Comment by andyesfly** [comment]
+1

**Comment by Mikuu** [comment]
+1
