### ISSUE TITLE
spawn npm

### ISSUE THREAD

**Issue by EveChee** [electron/electron#24226]
Hi, I'm glad To use Electron!

I‘m English is not good,i'm so sorry!But i think you should get the general idea.
I want use node API spawn(npm, ['install'], options) in the production.
So you know in the devlopment is no problem on my Mac.
But you don't necessarily have a Node environment on your computer.
So I downloaded a Node file and packed it in a resource, trying to use the Node inside without any concern for the user.
I'm failed.
Pleace help me。

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
