### ISSUE TITLE
JS web Speech recognition not working on electron

### ISSUE THREAD

**Issue by Silver0401** [electron/electron#24278]
* **Electron Version: version: 9.0.4 (latest), however bug seems to persist on any past electron version**

* **Operating System: operating system and version: macOS Catalina version 10.15.5**

* **Last Known Working Electron version: It used to work on any recent electron version (I tested it with success in version 8.3.3 and version 9), however I am currently unable to make it work on any**

### Expected Behavior
The code in the repo below should console log every word you say out loud to your computer, via the use Web Speech recognition APi

### Actual Behavior
 When ran in electron, the code does not log anything (as if it didn't hear or work at all) however, it seems to work in other browsers such as chrome, safari or firefox 

### To Reproduce
To reproduce the bug simply clone and run the code in the repo attached, on any electron version. More details inside the code.

github repo url:  https://github.com/Silver0401/JSErrorRepo

1) clone repo, $ git clone https://github.com/Silver0401/JSErrorRepo.git
2) make sure to have any electron version installed globally, $ npm install -g electron
3) $npm start
4) check the console

### Additional Information
Maybe the error or bug has to do with my computers, or perhaps I didn't find the solution by mistake, however I've been stuck with this for weeks, I've tried everything to make it work and yet nothing solves the problem, I would appreciate any comment or help, thanks.

**Comment by ahallicks** [comment]
I can confirm this, though it was working in v9.0.{0,1} (I think). I now have started getting `error: "network"` issues on every version I've tried from v8.2.5 to latest stable (v9.0.5).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
