### ISSUE TITLE
.sendInputEvent does not work properly with Enter or Space

### ISSUE THREAD

**Issue by Alectrona18** [electron/electron#24279]
```
contents.sendInputEvent({type:'keyDown', keyCode:"Backspace"});
contents.sendInputEvent({type:'char', keyCode:"Backspace"});
contents.sendInputEvent({type:'keyUp', keyCode:"Backspace"});
```

This code does work and send a backspace.

```
contents.sendInputEvent({type:'keyDown', keyCode:"Enter"});
contents.sendInputEvent({type:'char', keyCode:"Enter"});
contents.sendInputEvent({type:'keyUp', keyCode:"Enter"});
```

But this writes "Ent" as a string, instead of sending "Enter" as an input, despite "Enter" being a valid keycode :
https://www.electronjs.org/docs/api/accelerator

**Comment by MarshallOfSound** [comment]
`Enter` is 
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
