### ISSUE TITLE
Not able to launch Electron

### ISSUE THREAD

**Issue by J-Bollie** [electron/electron#24298]
I can't launch any selfmade electron application because of a js file it can't find.

Included is a screenshot of the error that i'm getting.

 
![image](https://user-images.githubusercontent.com/48119536/85720636-e8102580-b6f0-11ea-8eec-bac865f63987.png)

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by pushkin-** [comment]
this issue should be closed. it was replaced by [this issue](https://github.com/electron/electron/issues/24320)
