### ISSUE TITLE
Window Maximization does not respect minwidth

### ISSUE THREAD

**Issue by rcmaehl** [electron/electron#24336]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * At least Electron 7, [@github/billygriffin](https://github.com/billygriffin) can shed light on what specific Electron 7 release Github desktop is using, Discord is more private, but I would believe they're on a supported build for security reasons.
* **Operating System:**
  * Microsoft Windows [Version 10.0.18362.900]
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Maximized Windows respect minwidth

### Actual Behavior
Window width is resized to the monitor width

### To Reproduce
* Set one monitor to a thin width resolution (e.g. 900x1440)
* Maximize an electron window with a minwidth larger than that width (e.g. Github desktop is 960, Discord is 940)

### Screenshots
![electonminwidth](https://user-images.githubusercontent.com/716581/85936357-db91f580-b8c7-11ea-84a6-25f0b38252cc.gif)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by rcmaehl** [comment]
Per Discord Testers group. This issue is still present as of 9.3.5
