### ISSUE TITLE
Capturing transparent window shown as black screen

### ISSUE THREAD

**Issue by akbar-animaker** [electron/electron#24346]
Hi,

I am trying to capture the  transparent window (screen which it was created BrowserWindow and transparent as true) using this guideline,

https://www.electronjs.org/docs/api/desktop-capturer

but that vide captured as black screen.... is there any idea?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
