### ISSUE TITLE
Process name on Task Manager

### ISSUE THREAD

**Issue by VaishakVk** [electron/electron#24343]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5

* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
I have multiple asar files and I have built an Electron app where each of the asar is loaded based on condition. Apps are loading properly and each window has a different title based on the condition. When I look into task manager, I see the first opened app has the same name of the window. But all the other opened apps will have the generic name though there is an explicit title assigned.

### Actual Behavior
If there are multiple windows opened, then the process name in Task Manager should have different names grouped inside main process. This works when only one window is opened. The same functionality should extend when there are multiple apps opened.

### To Reproduce
- Create Multiple asar files
- Create an Electron main.ts file that loads these asar files and build the app.
- Create shortcut for these apps and add a command line argument so that different asar files can be loaded
- Try opening the shortcuts. When the first app is opened, the title name is displayed in task manger. When the second app is opened the Task Manager would have the generic process name.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
