### ISSUE TITLE
When electron printing is not connected to the printer, it will automatically exit the electron application when printing

### ISSUE THREAD

**Issue by cailingling** [electron/electron#24361]
When electron printing is not connected to the printer, it will automatically exit the electron application when printing
electron version 7.2.3

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 8 days if the above is not addressed.
