### ISSUE TITLE
Spawn Node.JS child process from electron packaged application

### ISSUE THREAD

**Issue by Sneaky-Bot-Dev-Team** [electron/electron#24368]
When I spawn a Node.js child process from an electron app (packaged using electron-builder) the forked script doesn't have access to node_modules so I need to unpack them to extraResources when I build which takes a lot of space and is not efficient. Can someone please help ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
