### ISSUE TITLE
print-to-pdf wont work.

### ISSUE THREAD

**Issue by a-ditucalan** [electron/electron#24360]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
 "electron": "^9.0.5",
version 9.
* **Operating System:**
  * 
MACOS SIERA
* **Last Known Working Electron version:**
  * 

### Expected Behavior

it should open the pdf reader as a view of print
### Actual Behavior

 ipcRenderer.send('print-to-pdf') on my react function won't works. there's no action
### To Reproduce

main.js in react

ipc.on('print-to-pdf', function (event) {
  const pdfPath = path.join(__dirname, '/reports/print.pdf')
  const win = BrowserWindow.fromWebContents(event.sender)
  win.webContents.printToPDF(
    { printBackground: true, landscape: true },
    function (error, data) {
      if (error) throw error
      fs.writeFile(pdfPath, data, function (error) {
        if (error) {
          throw error
        }
        shell.openExternal('file://' + pdfPath)
        event.sender.send('wrote-pdf', pdfPath)
      })
    }
  )
})

in my react component where i add ipc.send(print-to-pdf)

  const handlePrint = () => {
    // window.print()

    ipcRenderer.send('print-to-pdf')
  }

this is a private project

### Screenshots

![image](https://user-images.githubusercontent.com/58244709/86070114-6896a380-baae-11ea-9429-e87fb105eab9.png)
![image](https://user-images.githubusercontent.com/58244709/86070144-7ba97380-baae-11ea-90a7-72157088eacc.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or issues with one's own code since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
