### ISSUE TITLE
Inconsistent window.maximize() behavior between Windows and OSX

### ISSUE THREAD

**Issue by mix3d** [electron/electron#24375]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.3
* **Operating System:**
  * Windows 10, MacOS 10.15.3
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I'm trying to create hidden (`show:false`) but maximized windows ahead of time, to pre-load an expensive SPA app for performance reasons. The window should be in the maximized state when it is eventually shown.

### Actual Behavior
I'm primarily building on a Mac, and creating windows with `show:false` then immediately calling `window.maximize()` works fine, the windows stay hidden until I manually call `window.show()`.

However, on Windows 10, the moment I call `window.maximize()`, the window is immediately shown while maximizing.

Looking at the documentation, https://www.electronjs.org/docs/api/browser-window#winmaximize, it says 
>This will also show (but not focus) the window if it isn't being displayed already.

This behavior is working as documented on Windows 10 (_annoying_, but it's documented) but OSX does not behave the same way.

For Windows, if I do not maximize prior to showing the window, the UI animates the maximize process, and it is not very pretty. I am trying to show a pre-maximized window.

### To Reproduce
```JS
const newWindow = new BrowserWindow({
    show: false,
    x: 50,
    y: 50,
    webPreferences: {
        nodeIntegration: false,
    },
})
// start with the window maximized, so we can show it fullscreen when ready.
newWindow.maximize() // Windows 10 will automatically show here, but OSX won't

//... some time later, via a user interaction ...
function onUserClick() {
    newWindow.show()
}

```

### Hopeful Outcome
I would like to see `window.maximize()` NOT show the window, following the OSX behavior. I recognize this would be a breaking change, but I do not see a reason why the window needs to be shown when maximizing.

**Comment by mhermher** [comment]
This could maybe be resolved in a non-breaking way by having window.maximize return a promise instead, resolved when the window has finished maximizing. 

`window.maximize().then(window => window.show())` or something like that. 
`window.maximize(); window.show();` or otherwise would still behave as they do in the current version.

But mostly agreed, just want consistent behavior across OS.

**Comment by mix3d** [comment]
While useful, I don't think returning a promise would help the fact that on Windows, `.maximize()` _shows the window immediately, even if you don't want it to_ but OSX does not.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
