### ISSUE TITLE
how can i add box shadow for frameless window in electron?

### ISSUE THREAD

**Issue by isekaimaou1109** [electron/electron#24411]
os: win7 professional
version: electron@9.x.x

i'm looking up on google but no see any good solution for mine. also see on electron documentation but no any api or method can fix this. So can you help me for this issue? tks too much

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by ahallicks** [comment]
For my app I had to add a margin to the HTML of the app (that covers the area the box-shadow will take up) and then set a box-shadow on the body. You can't do this natively as far as I am aware.
