### ISSUE TITLE
How to open exe with html button

### ISSUE THREAD

**Issue by hiimjustin000** [electron/electron#24422]
Title says it all. I know about `child_process`, but I don't know how to use it with an HTML button. Any help would be appreciated.

**Comment by marc2332** [comment]
Hello

`nodeIntegration` might be useful to you. By enabling it you can access `child_process` from the renderer process.
You would just need to bind a function which executes your app, to the click event of your button.

```javascript
const myButton = document.getElementById("myButton");

myButton.addEventListener("click", function(){
    const childProcess = require("child_process") //You can now use require since you have nodeIntegration activated
    /* ... */
})
```

Docs:
1. Go https://www.electronjs.org/docs/api/browser-window
2. Scroll until `webpreferences`
3. See `nodeIntegration`

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
