### ISSUE TITLE
Module not found: Error: Can't resolve '../../../../bazel-genfiles'

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [electron/electron#24425]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:9.0.0
  * 
* **Operating System:macOS 
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

According to the official method, I installed selenium-webdriver, and then copied the following demo code to my electron project, using a js to import in .vue
link:https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver

![image](https://user-images.githubusercontent.com/20324269/86517046-51620800-be58-11ea-8f95-c3d14c7e45f3.png)
![image](https://user-images.githubusercontent.com/20324269/86517050-5d4dca00-be58-11ea-9f0f-6d0e77b43781.png)
![image](https://user-images.githubusercontent.com/20324269/86517058-6f2f6d00-be58-11ea-99e1-730f9ae5a52d.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
