### ISSUE TITLE
ipcRenderer.invoke can't handle custom errors

### ISSUE THREAD

**Issue by k3nt0w** [electron/electron#24427]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

The product I'm developing now implements a custom error for gRPC to make the error handling. Then, by passing the additional information for the errors made by gRPC to the renderer, I am trying to do a flexible display of error messages with the renderer.

For example, I am trying to use custom errors in the following situations

- display the ID of data that failed to be received
- Handle custom error codes contracted to the gRPC server

However, [ipcRenderer.invoke](https://github.com/electron/electron/blob/659e79fc08c6ffc2f7506dd1358918d97d240147/lib/renderer/api/ipc-renderer.ts#L24-L30) does not allow to receive custom error generated on main process because this function make simple Error() instance with error message.

```ts
ipcRenderer.invoke = async function (channel, ...args) {
  const { error, result } = await ipc.invoke(internal, channel, args);
  if (error) {
    throw new Error(`Error invoking remote method '${channel}': ${error}`);
  }
  return result;
};
```

### Proposed Solution

I don't fully understand the [ipc.invoke process described in cpp](https://github.com/electron/electron/blob/72a089262e31054eabd342294ccdc4c414425c99/shell/renderer/api/electron_api_ipc_renderer.cc#L105-L129). If ipc.invoke can return a error thrown by the main process directly, I think the following changes will satisfy my wishes.

```ts
ipcRenderer.invoke = async function (channel, ...args) {
  const { error, result } = await ipc.invoke(internal, channel, args);
  if (error) {
    throw error;
  }
  return result;
};
```

However, the information on the channel drops off. I'd like to come up with a solution here when how to handle custom error policy is decieded.

### Additional Information

If it's the current implementation in relation to the cpp part of the implementation, please let me know. I'm glad to see it. I'm also glad that this custom error policy is being used as an anti If it's a pattern, I'd be happy to point that out as well.

**Comment by tomm1e** [comment]
Major issue!

I had to return normal objects inside ipcMain.handle with error information instead of throwing errors since the custom error becomes malformed for the renderer, that means I can not properly do catch handling on renderers invoke Promise.

I pretty much removed all of my .catch handlers in the renderer until this is fixed.

**Comment by nornagon** [comment]
Unfortunately, the proposed change will not fix this issue, as V8's serialization algorithm does not include custom properties on errors. You can test this in Chrome:

```js
window.onmessage = (e) => {
  console.log(e.data.extraProperty)
}
const error = new Error('message')
error.extraProperty = 123
window.postMessage(error)
// => undefined
```

You can see the logic for V8's error serialization here: https://chromium.googlesource.com/v8/v8/+/refs/tags/8.8.44/src/objects/value-serializer.cc#912. It serializes only the type of the error (if it's one of the built-in types), the `message` and `stack` strings, and nothing else.

I'm not sure right now what the best path forward is, but here are a few of my thoughts:

1. I think we should actually maybe be exposing _less_ information here, rather than more. Error messages can contain sensitive data in some situations, and the Web sanitizes error messages when they cross between contexts: https://html.spec.whatwg.org/multipage/webappapis.html#muted-errors. We should perhaps do the same; the main process should be considered "cross-origin" from any renderer context.
2. If we _do_ want to expose more error information, we should probably not expose the stack trace from the main process, as that stack won't make sense in the renderer.
3. Exposing extra properties could be done by serializing a property object alongside the error, for example (in `web-contents.ts`):

```js
    event._throw = (error: Error) => {
      console.error(`Error occurred in handler for '${channel}':`, error);
      event.sendReply({ error: { name: error.name, message: error.message, extra: { ...error } } });
    };
```

and then deserialized on the renderer side as:

```js
  const { error, result } = await ipc.invoke(internal, channel, args);
  if (error) {
    const errorObj = new Error(`Error invoking remote method '${channel}': ${error.name} ${error.message}`)
    Object.assign(errorObj, error.extra)
    throw errorObj;
  }
```

These techniques could easily be applied by an app to wrap `ipcMain.handle` and `ipcRenderer.invoke` with their custom error-handling logic. For example:


```js
// Main process
const encodeError = (e) => {
  return {name: e.name, message: e.message, extra: {...e}}
}

const handleWithCustomErrors = (channel, handler) => {
  ipcMain.handle(channel, async (...args) => {
    try {
      return {result: await Promise.resolve(handler(...args))}
    } catch (e) {
      return {error: encodeError(e)}
    }
  })
}

// Renderer process
const decodeError = ({name, message, extra}) => {
  const e = new Error(message)
  e.name = name
  Object.assign(e, extra)
  return e
}

const invokeWithCustomErrors = async (...args) => {
  const {error, result} = await ipcRenderer.invoke(...args)
  if (error) {
    throw decodeError(error)
  }
  return result
}
```

**Comment by alejandroclaro** [comment]
My two cents here.

I agree with the issue report. This problem is considerably important from my perspective.

I am using a workaround similar to the one proposed by @nornagon. However, it is quite confusing for another member of the team that this works like this and it should be explained that when the promise is rejected, the result is different to what is normally expected, and certain information such as the original message is lost (now it is encoded in the other message), the type of the error (constructor name), as well as any additional attributes.

I think the ipcRenderer and ipcMain implementations should encapsulate the solution and document the behavior. The solution can be something like @nornagon or any other mechanism (not necessarily that the error that is obtained is exactly the same that was emitted from the main process) to get the proper error without resorting to workarounds that may need a lot of code duplication or may be prompted by people unfamiliar with the issues here for errors.
```

**Comment by vladimiry** [comment]
> However, it is quite confusing for another member of the team that this works like this and it should be explained that when the promise is rejected, the result is different to what is normally expected, and certain information such as the original message is lost (now it is encoded in the other message), the type of the error (constructor name), as well as any additional attributes.

> I think the ipcRenderer and ipcMain implementations should encapsulate the solution and document the behavior.

Indeed, it's quite confusing to beginners at least, that when you receive the Promise but the error differs from the original error. So it's not like a real/pure Promise. If the feature is designed to return Promise, then I believe it should act like one, so it's not misleading. Or it could be designed to return a callback with a ResultOrSanitizedError-like response-wrapper object. I don't experience this problem though since from day one use the IPC-based communication only and realize that serialization is taking place (I use the [serialize-error](https://github.com/sindresorhus/serialize-error) module in this [type-safe IPC](https://github.com/vladimiry/electron-rpc-api) wrapper).

**Comment by nornagon** [comment]
I'm not sure I understand the confusion around the Promise behavior; there's nothing particularly unusual about a promise rejecting with an error. It doesn't seem surprising to me that sending a message to another process and receiving an error in response would produce a not-identical error to the one thrown in the remote process. The error message that _is_ received specifically explains what has happened: it says "Error invoking remote method '${channel}'".

Perhaps it would be less confusing if the error message thrown in the renderer actually didn't include any details about the remote error? It would, for example, be less surprising for developers to discover that none of the extra properties of the error they threw were present if the error was obviously a reconstructed, different error.

Note that it is ultimately impossible to create a perfect copy of the thrown error in the calling process, because it's possible for user code to create and throw custom objects as errors, and there is no way for us to recreate such custom objects in a totally separate process. (e.g. `class MyError extends Error { /* ... */ }`). V8 itself handles its builtin error types (`RangeError`, `TypeError` and so on) but any support for other error types must necessarily be handled by custom user code.

**Comment by ash0x0** [comment]
I spent 4 hours trying to figure out this issue, finally running into this thread and @nornagon's workaround which solved it for me. This should at the very least be documented in ipcMain docpage. I think the workaround should probably be included as well until a time we get a PR to fix this, if possible.

**Comment by kloverde** [comment]
I believe this should be tagged as a bug, not an enhancement.  You lose access to whatever object you try to pass back, so promise rejection is broken.

**Comment by m4heshd** [comment]
Just spent more than 2 hours to create a solid workaround for this issue. It's MOST DEFINITELY NOT how it should work. This is a bug.

**Comment by ash0x0** [comment]
@m4heshd by solid workaround do you mean something different and/or safer than what @nornagon came up with? can you share if you have something new?

**Comment by m4heshd** [comment]
@ash0x0 It's just something very specific to my use case but still hell dealing with this.

**Comment by maxcnunes** [comment]
Just an FYI, I tried @nornagon's approach using `ipcRender` with `contextBridge` and it won't work. I still see the serialization issue once the error is thrown again after the error has been decoded.

**Comment by janschmutz** [comment]
In case you have context isolation isolation enabled (officially recommended) and need to pass custom error types / properties to the UI component it gets even uglier because errors will be stripped of any custom attributes in the preload script.

refer to https://github.com/electron/electron/issues/25596

To use [nornagon](https://github.com/nornagon) example for the renderer you would need to write some kind of middleware function to 'parse' the error outside of the preload script in the renderer script but its really ugly, needs to be super well documented.

```
export async function callElectronApi(
  fn: (...args: any[]) => any,
  ...args: any[]
): Promise<any> {
  const { result, error } = await fn(...args)
  if (error) {
    throw decodeError(error)
  }
  return result
}
```

And then use like

`callElectronApi(window.electronApi.myFunction, arg1)`

please lmk if you find a better solution

**Comment by tanhh326** [comment]
`Error invoking remote method 'my-event': my error message`

Is there a way to get the original error message, I'm now using `message.split(":")[1]` to handle it.

**Comment by web-crab** [comment]
I used this helpers instead of `ipcMain.handle/ipcRenderer.invoke`

```ts
function handle<Fn extends (...args: never[]) => unknown>(
  channel: string,
  handler: Fn,
) {
  IpcMain.on(channel, async (event, ...args: Parameters<Fn>) => {
    try {
      const data = await handler(...args);
      event.reply(`${channel}:response`, data);
    } catch (error) {
      event.reply(`${channel}:response`, error);
    }
  });
}
```

```ts
function invoke<T>(channel: string, ...args: unknown[]): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    ipcRenderer.once(`${channel}:response`, (_, response) => {
      if (response instanceof Error) {
        console.error(response);
        reject(response);
      } else {
        resolve(response);
      }
    });

    ipcRenderer.send(channel, ...args);
  });
}
```
