### ISSUE TITLE
Changes in dialog API not mentioned in breaking changes

### ISSUE THREAD

**Issue by srijonsaha** [electron/electron#24438]
Upgraded from version `1.7.0` to `9.0.5` and noticed that [`showOpenDialog (v9.0.5)`](https://www.electronjs.org/docs/api/dialog#dialogshowopendialogsyncbrowserwindow-options) returns `Promise<Object>` but in [`showOpenDialog (v1.7.0)`](https://github.com/electron/electron/blob/v1.7.0/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback) returns `String[]`. This is also the case with other async methods like `showSaveDialog`. The API was changed at some point and not mentioned in the [Breaking Changes](https://www.electronjs.org/docs/breaking-changes) doc.

**Comment by codebytere** [comment]
This was discussed here as part of a larger initiative: https://www.electronjs.org/docs/api/modernization/promisification

**Comment by srijonsaha** [comment]
I think it should be mentioned in the Breaking Changes doc as well. As someone updating Electron versions in the codebase, I looked at the Breaking Changes doc to figure out whether errors were due to versioning changes or my code. I assume the purpose of a Breaking Changes doc would be inform users of changes that would break their code which is what happened here.

**Comment by SheetJSDev** [comment]
@codebytere this should probably be revisited for a few reasons:

1) It's not at all obvious how to land on the modernization page by traversing the docs other than by explicitly searching for the word "promisification".

It's not linked from the main docs page (https://www.electronjs.org/docs).  It's not linked from the breaking API changes pages (https://www.electronjs.org/docs/breaking-changes). 
 A quick github search in the repo shows that the Modernization page has no inbound links in the documentation and the only Promisification inbound link is from the Modernization page.  Effectively it's an island.

2) Even if it were linked, the breaking changes for 6.0 actually references an API change that returns a promise: https://www.electronjs.org/docs/breaking-changes#api-changed-contenttracinggettracebufferusage-is-now-a-promise

> API Changed: `contentTracing.getTraceBufferUsage()` is now a promise

It probably makes more sense to link to the promisification page in that position (assuming all of the changes happened in 6.0)

3) Each of the links in that page actually point to github rather than the official docs.  For example, the showOpenDialog link points to https://github.com/electron/electron/blob/master/docs/api/dialog.md#showOpenDialog
