### ISSUE TITLE
webFrame.setVisualZoomLevelLimits not work

### ISSUE THREAD

**Issue by little-tomorrow** [electron/electron#24431]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.3
* **Operating System:**
  * Windows 10 (1909) / Windows 10 (2004)
* **Last Known Working Electron version:**
  * null

### Expected Behavior

Limit zoom to a minimum of 1x and a maximum of 3x

### Actual Behavior

limit does not work

### To Reproduce

https://gist.github.com/little-tomorrow/3bb54d3013531d3e1ce2218d8d8177f9

### Screenshots

![image](https://user-images.githubusercontent.com/23186480/86617006-35da3700-bfe9-11ea-848c-e74e76200ba8.png)
![image](https://user-images.githubusercontent.com/23186480/86616955-2529c100-bfe9-11ea-80fb-1bfe5f1ed859.png)

### Additional Information

My ultimate goal is to disable scaling. Originally, I wanted to disable zooming through webFrame.setVisualZoomLevelLimits(1, 1).But I found this API does not work at all. So is there any other way to disable zoom

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
