### ISSUE TITLE
Notifications Icons dosn't work in the deployed project

### ISSUE THREAD

**Issue by ElmansourMouhcine** [electron/electron#24446]
i have a problem with the notifications icons in my projet deployed, they work very well on my project, but when i deployed the projet hey dosen't work !!!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
