### ISSUE TITLE
Webview Bug

### ISSUE THREAD

**Issue by Slender1808** [electron/electron#24498]
I'm having trouble with webview wheel
I'm trying to run this project https://github.com/hokein/electron-sample-apps/tree/master/webview/browser
I'm creating a webview of a project that has another webview inside
But it's not working
Is something missing ?
`<webview src="./apps/browser/browser.html" webpreferences="nodeIntegration: true, webviewTag: true, allowRunningInsecureContent, javascript = no"> </webview>`

![1](https://user-images.githubusercontent.com/50336793/87118390-a2576f00-c251-11ea-871f-c07d80770d3d.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
