### ISSUE TITLE
moveItemToTrash delete files permanently on Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#24501]
[shell.moveItemToTrash ](https://www.electronjs.org/docs/api/shell#shellmoveitemtotrashfullpath-deleteonfail) delete files permanently on Linux Ubuntu 20.04

electron `8.2.3`

**Comment by codebytere** [comment]
Thanks for reaching out!  This is intended behavior.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by vasyl-shumskyi** [comment]
> This is intended behavior.

`Move to Trash` and erase files permanently are not the same.

Node `fs.unlink` can be used for erasing files. 

`Move to Trash` means that users will be able to **restore** files anytime.
