### ISSUE TITLE
spawn procs don't close on electron exit

### ISSUE THREAD

**Issue by Viral** [electron/electron#24520]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

* **Electron Version:**
  v9.1.0
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
  N/A

### Expected Behavior

when I shut down electron via app.quit() I expect the spawn procs to close with the app. 
if I ctrl+C from command prompt the electron app will close and the spawned procs close with it.

### Actual Behavior

I have a worker.init() from main.js that spawns procs. when I quit the app these continue to run in background. I'm unable to figure out how to close them. only ctrl+C from command line will work right now. some code:

  ```
// main.js 
app.on('ready', function() {
  worker.init();
  // can only quit app from contextmenu. this does not close any spawns procs.
  app.tray.setContextMenu(Menu.buildFromTemplate([{ label: 'Exit', type: 'normal', click: function() {
    app.mainWindow.destroy();
    app.quit();
  }}]));
});

// worker.js

worker.start = function() {
  const options = {};
  const child = spawn('ffmpeg', options);
  ...
});
```

**Comment by Prinzhorn** [comment]
I'm having the same problem. `spawn` inside Electron seems to have `detached: true` hardcoded. This leads to a host of issue with my app because it doesn't shut down cleanly and launching it again will result in conflicts because the child process is still holding on to a port it is listening on.

I'm on Ubuntu. Can be reproduced with Fiddle, only main.js needed

```js
const { spawn } = require('child_process');

const child = spawn('python3', ['-m', 'http.server', '8000', '--bind', '127.0.0.1'], {
  // Even explicitly setting this does not help
  detached: false
});

child.on('exit', (code) => {
  console.log(`exited with code ${code}`);
});

child.stderr.on('data', (data) => {
  console.error(data.toString('utf8'));
});

child.stdout.on('data', (data) => {
  console.log(data.toString('utf8'));
});
```

# Steps

1. Copy the above code into Fiddle main.js
2. Launch the Fiddle, I'm using v13.1.6
3. In a terminal run `ps ax | grep http.server` and note the pid (`15882` in my case)
4. Run `ps -o ppid= -p 15882` to find the parent process (`15862` in my case, which is `/Electron Fiddle/electron-bin/13.1.6/electron`)
5. Stop the Fiddle and completely shutdown Electron Fiddle
6. Run `ps -o ppid= -p 15882` again. The parent process is now `2709` which is `systemd`

Looks like another case for my collection at https://github.com/electron/electron/issues/26593

Running the same main.js via `node main.js` and klling node via ctrl+c will also exit the python3 child process.

# It gets better

For some reason this child process (that now belongs to systemd) keeps several Electron processes alive. To me this looks broken?

```
 $ ps ax | grep electron
  16478 ?        S      0:00 /home/alex/.config/Electron Fiddle/electron-bin/13.1.6/electron --type=zygote --no-zygote-sandbox
  16479 ?        S      0:00 /home/alex/.config/Electron Fiddle/electron-bin/13.1.6/electron --type=zygote
  16481 ?        S      0:00 /home/alex/.config/Electron Fiddle/electron-bin/13.1.6/electron --type=zygote
```

Killing the original python3 process via `kill 15882` will get rid of all these processes.

**Comment by Viral** [comment]
iirc my issue was that ffmpeg would ignore sigterm and needed sigkill... but the way Electron handles children procs and their PID is very strange for sure

**Comment by Prinzhorn** [comment]
@Viral if your original problem is solved then let's close this issue and I'll open a new and clean one with my findings
