### ISSUE TITLE
How to use updated Squirrel framework

### ISSUE THREAD

**Issue by codefei** [electron/electron#24522]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I modified Squirrel source code and I want to use the updated Squirrel framework, What should I do?  

### Proposed Solution

Should I modify the `update-external-binaries.py`? 
Or whether I can replace the frameworks before packaging to the `dmg` file.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
