### ISSUE TITLE
mac app store... where is the /electron/.. folder in my macbookpro to proceed???

### ISSUE THREAD

**Issue by lse123** [electron/electron#24635]
and can be installed via npm install electron@beta
I applied this/installed this^^ from a folder in my documents in my macbookpro

I have an Electron App finished and want put in the mac app store... where is the /electron/.. folder in my macbookpro to proceed???

**Comment by lse123** [comment]
according to

https://www.electronjs.org/docs/tutorial/application-distribution

On macOS:

electron/Electron.app/Contents/Resources/app/
├── package.json
├── main.js
└── index.html

MyApp.app/Contents
├── Info.plist
├── MacOS/
│   └── MyApp
└── Frameworks/
    └── MyApp Helper.app
        ├── Info.plist
        └── MacOS/
            └── MyApp Helper

**Comment by lse123** [comment]
where is the /electron/.. folder in my MacBook pro to proceed???

**electron/Electron.app/**Contents/Resources/app/
├── package.json
├── main.js
└── index.html

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
