### ISSUE TITLE
Keeping app alive in tray, despite clicking 'Quit' in the dock

### ISSUE THREAD

**Issue by ionalexandrusecara** [electron/electron#24636]
Hi!

I'm trying to configure an Electron app that lives in the tray on Windows and Mac, but when opened, the app also shows in the dock for Mac and the taskbar for Windows. 

The issue that I'm having is that, whenever I two finger click on the app in the dock and I click 'Quit' the app is closed in both the dock and the tray. I would really appreciate it if someone could showcase a code snippet or point me to the right documentation to implement this functionality.

Really appreciate it. 
Thanks,
Alex

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by jwonderly** [comment]
My team has similar requirements, which I described in a feature request here: https://github.com/electron/electron/issues/24371. 

As described in the above feature request, I do not think it is currently possible to properly implement this behavior on Mac using Electron.
