### ISSUE TITLE
transparent  and  offscreen   Cannot be used together ？

### ISSUE THREAD

**Issue by wwping** [electron/electron#24643]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * npm  install Electron for 9.1.0
* **Operating System:**
  * windows 10(19041.388)

### Additional Information
why  transparent  and  offscreen   Cannot be used together ？

It can lead to a silent flashback

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by melody5417** [comment]
the same problem
