### ISSUE TITLE
globalShortcut can't support Numbers at the front

### ISSUE THREAD

**Issue by AlicePrincess** [electron/electron#24658]
![image](https://user-images.githubusercontent.com/18545458/88008594-37f0d980-cb43-11ea-8a38-ba706091e58f.png)
this my code
but when I only pressed  enter key,function into console.log
I want listening to the 1+Enter，what should I do?

**Comment by AlicePrincess** [comment]
globalShortcut.register('1+enter', () => {
      console.log('1+Enter is pressed')
    })
this my code

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
