### ISSUE TITLE
How the get the click event coordinates even when we set the setIgnoreEvents as true

### ISSUE THREAD

**Issue by akbar-animaker** [electron/electron#24662]
Hi Team,

I am new in electron development. Currently i am trying to create a one application with highlight click support...

I have created one window and sets the setIgnoreEvents as true made that window as a transparent and sets that window always on top as well... so that i can able to access the background window... this was working fine as expected...

In that case i have to achieve highlight feature (when i click my window i have to show one bubble highlight) how to achieve this feature i am unable to capture the co-ordinates of my click because of i have set the setIgnoreEvents as true...

is there any idea to implement that feature,

This is the same behavior i am trying to do achieve in my app.... 

https://www.loom.com/share/dae235b248b34417ba949f1f377cb3de

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
