### ISSUE TITLE
Encryption of files within ASAR - Where is the mount point?

### ISSUE THREAD

**Issue by onimac92** [electron/electron#24681]
Hi,

We’ve been looking for a way to protect the packaged ASAR from cursory inspection (with asar -extract) and wanted to encrypt files within it before packaging. Obviously modifying and rebuilding Electron is necessary, therefore myself and a colleague have been trawling through source to find the point at which the ASAR package is mounted / read

What we’d like to do is obfuscate and bake the decryption key within the Electron executable itself, then decrypt files within the ASAR when a seek within the ASAR happens.

Can anyone with experience of the source point us to where this might be?

Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
