### ISSUE TITLE
Javascript being cached - forcing hard refresh to work

### ISSUE THREAD

**Issue by arepp23** [electron/electron#24688]
I am using a BrowserWindow to view a web application. When I make changes to the typescript, compiled to JS, and re-open the Electron app, I have to hard refresh using ctrl+shft+r to see the new javascript changes. 

I have disabled the cache in the network tab of the devtools window. 

I have also tried using view.webContents.session.clearCache() and view.webContents.loadURL(url, { "extraHeaders": "pragma: no-cache\n" }); to no avail.

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell has some information on this; in addition to the session.clearCache() that you've already tried, it discusses clearStorageData() and the location of the cache directories themselves.
