### ISSUE TITLE
Webrtc remote stream Raw AV samples from Electron App

### ISSUE THREAD

**Issue by Raj123456788** [electron/electron#24695]
Advice Needed
I have been working on the screen sharing application: I need the raw AV buffer(**O/P of the decoder is typically YUV** ) that I receive from the remote stream.

So here is the html element that displays the stream

setTheirVideo : function (stream) {
        var video = document.getElementById('their-video');
        if (typeof video.srcObject == "object") {
            video.srcObject = stream;
        } else {
            video.src = URL.createObjectURL(stream);
        }
    },
The HTML element above gets the stream. I need to access the raw rendered AV data, is there a way I can get these samples?

Ideas to achieve this, What I have read so far:

With Gstreamer pipeline we can get access to the raw AV samples. If there are any examples of Gstreamer working with Electron please send me the links.
I have also tried the Media Recorder but samples are received when the webrtc session is ended.
Please let me know if anyone has already accomplished this on Windows?

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
