### ISSUE TITLE
Keytar

### ISSUE THREAD

**Issue by Amosss** [electron/electron#24692]
Hi

A short background: I develop in Quasar for the web and then build it in electron mode to run as an executable. Everything is working fine in this regard. Now I want to add something specific only when running in electron mode.

To implement that feature, I need keytar. I npm installed it put things in place (I hope) but when running the application as web mode I see the following in the console:

>     Cannot open C:\Users\user\Downloads\portable\vscode\Projects\project\node_modules\keytar\build\Release\keytar.node: TypeError: Cannot read property 'dlopen' of undefined
>     at Object.eval (keytar.node?3002:1)
> 

and the line itself is

> try {global.process.dlopen(module, "C:\\Users\\user\\Downloads\\portable\\vscode\\Projects\\project\\node_modules\\keytar\\build\\Release\\keytar.node"); } catch(e) {throw new Error('Cannot open ' + "C:\\Users\\user\\Downloads\\portable\\vscode\\Projects\\project\\node_modules\\keytar\\build\\Release\\keytar.node" + ': ' + e);}
> Obviously global.process is undefined.
> 

What is global.process and who owns it?
Is it because I'm in web mode and not in electron mode? 
If so, how can I set it to require/import/load keytar only in electron mode?
If it's something else, what am I doing wrong?
Thanks

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
