### ISSUE TITLE
Cannot dynamically delete or hide Menu Separator

### ISSUE THREAD

**Issue by jahnli** [electron/electron#24704]
It does not work when I attempt to hide or delete separator，But everything else is working；

![image](https://user-images.githubusercontent.com/20943608/88271697-2279dc00-cd0a-11ea-829a-b4f2d97dd0e2.png)

![image](https://user-images.githubusercontent.com/20943608/88271592-f2cad400-cd09-11ea-9ecc-51794a93c2a9.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
