### ISSUE TITLE
Uncaught ReferenceError: __dirname is not defined in Angular 8

### ISSUE THREAD

**Issue by VijalPatel** [electron/electron#24719]
Hello,

I am using electron for browsing directory and pick up directory path in my angular project.
But when i import electron its showing me error __dirname not defined.

Please check my below code

   import { BrowserWindow, dialog } from "electron";

    var WIN = new BrowserWindow({ width: 800, height: 600 });
    dialog.showOpenDialog(WIN, {
      title: "Select Application Local Folder",
      defaultPath: "C:\\Users\\xuser\\Desktop",
      buttonLabel: "Select Path",
      properties: ["openDirectory"],
    }).then((result) => {
      console.log(result.canceled);
      console.log(result.filePaths);
    }).catch((err) => {
      console.log(err);
    });

![__dirname](https://user-images.githubusercontent.com/28683045/88372948-8f49b080-cdb4-11ea-87d5-3566ca3433e6.png)

Please suggest me how can i solved this issue.
Or how can i implement browsing directory and pick up directory path in my angular project

Thanks.

**Comment by fenghengzhi** [comment]
try
```
const { BrowserWindow, dialog } = require('electron').remote;
```

**Comment by VijalPatel** [comment]
I tried this but getting same issue getting.

__dirname is not defined

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
