### ISSUE TITLE
[Discussion] How to validate that certificate in Electron request is not self-signed

### ISSUE THREAD

**Issue by jjason685** [electron/electron#24728]
In Electron's API docs [here](https://www.electronjs.org/docs/api/net), they explicitly say that they have support for traffic monitoring proxies. However, what if the purpose is to block these types of proxies? 

In the native node.js https module, the rejectUnauthorized boolean is used to block these types of connections. By default, it is true. If we were to integrate this behavior into Electron Net requests, what would be the optimal way to do so?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
