### ISSUE TITLE
How To Do Multiple Tabs? Spawn Chrome? Multiple BrowserWindow? <webview>s?

### ISSUE THREAD

**Issue by kingIZZZY** [electron/electron#24754]
#### Background
Project: Browser Automation for Data Entry
Trying to make an ElectronJS application using [Puppeteer](https://github.com/puppeteer/puppeteer) to automate some data entry tasks for some `<form>`-heavy websites.
To speed up processing I want to split the work across multiple "tabs" each doing more automation/scraping/form-submitting work.

### Question

What would be the "right way" or the least "wrong way" to go about running multiple browser tabs in ElectronJS?

- Chrome.exe Tabs - Spawn a totally separate child process of straight-up Chrome.exe and use actual chrome tabs controlled via puppeteer from the electronjs app
- BrowserWindow - Open multiple ElectronJS BrowserWindows as distinct "tab"s. Is this overkill? Like opening a whole new instance of Chrome rather than another tab _inside_ chrome?
- `<webview>` - This one seems fraught with confusion / warnings / uncertainty... Is it being phased out? Deprecated at some point? Suffers from bugs? etc. https://github.com/electron/electron/pull/13835 https://github.com/electron/electron/pull/18753

#### P.S.
Live chat anywhere? Where are you guys hiding 😉 
[No luck here](https://discuss.atom.io/t/join-us-on-slack/16638)
[Or here](https://discuss.atom.io/t/discussion-join-us-on-slack/25406)

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right dire
