### ISSUE TITLE
the interface BrowserViewConstructorOptions missing the property webContents

### ISSUE THREAD

**Issue by liubailing** [electron/electron#24760]
**Issue Details**

- Electron Version:
     5.0.4 and above

- Operating System:
     mac

- Last Known Working Electron version:
     5.0.4

**Expected Behavior**

when i new BrowserWindow, i can set the property - webContents。

let newwin: BrowserWindow = new BrowserWindow({
      ... properties,
      webContents: myWebContents,
})

**Actual Behavior**
Now is the error message

**Comment by ckerr** [comment]
Marking 5.0.4 as both the broken version and the last known working version is confusing to me.

The API docs don't show support for adding `webContents` as an option to BrowserWindow's constructor in [3.1](https://github.com/electron/electron/blob/3-1-x/docs/api/browser-window.md), [4.2](https://github.com/electron/electron/blob/4-2-x/docs/api/browser-window.md), or [5.0](https://github.com/electron/electron/blob/5-0-x/docs/api/browser-window.md), so I think you're asking for this to be added, rather than something that used to be there and was removed, right? 

Marking as an enhancement request

**Comment by MarshallOfSound** [comment]
Historically this has been intentional as it implies that you can _create_ a `webContents` or pass an arbitrary `webContents` here which isn't true for The Future Way Of Window.Open Working.  The new API will actually hide a lot of this #24517

Closing as it's currently expected
