### ISSUE TITLE
Electron Crashing Inside IPC call on face-api.js call

### ISSUE THREAD

**Issue by a93h** [electron/electron#24796]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.4
* **Operating System:**
  * Ubuntu 20.04.1 LTS
* **Last Known Working Electron version:**
  * not applicable
* **Node Version:** 
  * v14.6.0
* **NPM Version:**
  * 6.14.6

### Expected Behavior

[line 21 of my example project in recognition.ts should run](https://github.com/a93h/electron-quick-start-typescript/blob/master/src/recognition.ts#L21)
faceapi.detectAllFaces(...)
### Actual Behavior

Crashed with almost no information about why the process has failed.
### To Reproduce

Please see below for a working example.

Recommended platform Linux
Recommended OS Ubuntu 20.04.1 LTS
```sh
$ sudo apt install make g++ libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev
$ sudo npm i -g node-gyp
$ git clone https://github.com/a93h/electron-quick-start-typescript
$ cd electron-quick-start-typescript
$ npm i
$ ./node_modules/.bin/electron-rebuild 
$ export ELECTRON_ENABLE_LOGGING=true
$ npm start
```

### Screenshots

![Error Info](https://user-images.githubusercontent.com/8563086/88928942-6b202080-d247-11ea-9d14-0f326e7fa017.png)

### Additional Information

Really new to electron and not entirely certain if this is an electron issue or face-api.js
I assume I don't fully comprehend how the electron library works and since face-api.js was working before I put it inside an ipc call I believe I am not integrating electron and face-api.js properly.

**Comment by a93h** [comment]
I also made an attempt at using child_process.fork from main for the module that gave the same failure at the same line of code.
I also made an attempt to use Web Workers but never got the setup correct.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction. This issue is not a crash - if there was a crash there would be a stacktrace and dump which is not present in this screenshot. This appears to be an issue with your code architecture and not with Electron itself. However, should more information arise, we are happy to reconsider looking at this.

**Comment by a93h** [comment]
Thanks very much for the clarification.

I found an alternative library to face-api.js, everything works just fine now.
