### ISSUE TITLE
Frame rate of video not increasing above 30 fps while using desktopCapturer

### ISSUE THREAD

**Issue by sheminanto** [electron/electron#24808]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.2
* **Operating System:**
  * Windows 10 (1909) 
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
When frameRate constrain is applied. The output stream should of that Frame rate

### Actual Behavior
When the framerate constrain is applied above 30. The output video will be of 30 fps.
stream.getVideoTracks()[0].applyConstraints({ frameRate: 30 });

### To Reproduce
* Clone ```electron-quick-start```.

renderer.js
```
const { desktopCapturer } = require("electron");
 desktopCapturer
  .getSources({ types: ["window", "screen"] })
  .then(async (sources) => {
    for (const source of sources) {
      console.log(source.name);
      if (source.name === "Entire Screen") {
        try {
          const stream = await navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
              mandatory: {
                chromeMediaSource: "desktop",
                chromeMediaSourceId: source.id,
                minWidth: 640,
                maxWidth: 1980,
                minHeight: 480,
                maxHeight: 1080,
              },
            },
          });
          stream.getVideoTracks()[0].applyConstraints({ frameRate: 35 });
          console.log(stream.getVideoTracks()[0].getSettings());
        } catch (e) {
          handleError(e);
        }
        return;
      }
    }
  });
```

### Screenshots

![electron-issue-framerate](https://user-images.githubusercontent.com/13395437/89538567-5976e400-d818-11ea-928d-d7fe27db433d.png)

After applying the framerate constrain to 35 settings is still showing 30

**Comment by VerteDinde** [comment]
Hey @sheminanto, thanks for reporting this issue.

It looks like you're missing some information we ask for in our issue template, such as your version of Electron and operating system. We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by sheminanto** [comment]
Updated the info.

**Comment by hcatlin** [comment]
Struggling with the same thing.
