### ISSUE TITLE
Question: Is it possible to use Electron for the following app?

### ISSUE THREAD

**Issue by harshayburadkar** [electron/electron#24817]
I am good at developing web applications but have only limited desktop app development knowledge. I am seriously considering Electron to develop a desktop app (mainly for MacOS currently, Windows may be in the future).

It is a simple app with 2 to 3 pages. But in addition to the pages, there are a few requirements that I am unsure if an Electron app can have:

- custom Siri commands (SiriKit?) that initiate certain actions within the app and bring the app to focus
- an icon in the menu bar which changes depending on what website is in focus in the browser
- when clicking the icon in the menu bar, I would like to have a popup menu
- this icon in the menu bar should stay even in the menu bar even if the app is not open

If not directly supported by Electron - can I write native code in Swift just for these specialized requirements and still use Electron for the rest?
Kindly advise if I should use Electron for this scenario.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
