### ISSUE TITLE
clipboard multiple copy past

### ISSUE THREAD

**Issue by Ohunjon** [electron/electron#24810]
hi everybody! 
I want to get all files path, on copying multiple files with electron clipboard API. Is it possible?
I searched but not found any solve for this task ..
`path = clipboard.readBuffer('FileNameW').toString('ucs2').replace(RegExp(String.fromCharCode(0), 'g'), '');`
Here is code which will return only one file path (works for Windows). If multiple files are copied to the clipboard it will return only a single file path.
please help me ...
Thanks advance !

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
