### ISSUE TITLE
Plugin Pepper Flash not working build electron app

### ISSUE THREAD

**Issue by igorfastronicorrea** [electron/electron#24825]
I created an app that uses the Pepper Flash Plugin when I run with npm start it works perfectly, but when I build the app it doesn't work.

I put the specific path, I'm using Windows. I put the pepflashplayer.dll DLL in the root of my build folder and even so without success.

`app.commandLine.appendSwitch(
  "ppapi-flash-path",
  __dirname + "\\pepflashplayer.dll"
);`

**Comment by VerteDinde** [comment]
Hey @igorfastronicorrea, thanks for reporting an issue here.

Could I ask you to fill out our PR template that provides info like your version of Electron, etc? We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed. Thanks!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
