### ISSUE TITLE
uploadData is undefined for POST, PUT, PATCH

### ISSUE THREAD

**Issue by kamil-kielczewski** [electron/electron#24837]
This is duplicate of this https://github.com/electron/electron/issues/14720  closed issue which actually still exists :(((

I use following url request - uploadData is `undefined` for POST, PUT, PATCH

POST electron://process/file

(as you can see, instead https i have electron - because I use it as API to communicate with my web-based app ) and I'm unable to send file in body

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by kamil-kielczewski** [comment]
@codebytere this is DUPLICATE of This is duplicate of this #14720  - please open that issue and close this one
