### ISSUE TITLE
Memory usage increasing when background-image is updated

### ISSUE THREAD

**Issue by afloras** [electron/electron#24835]
I have a simple electron application that constantly updates the background image of a div element.

The problem is the memory keeps increasing when the window is active.

At the start :

![image](https://user-images.githubusercontent.com/36885107/89340326-db8fcd00-d69f-11ea-997f-6ea088c18673.png)

After around 1 minute :

![image](https://user-images.githubusercontent.com/36885107/89339761-fb72c100-d69e-11ea-966a-d7c8d007b28e.png)

It happens only if the window is active. If the window is minimized, the garbage collector does his job.

The parameter in the code is on purpose to force refreshing the image and not use the cache.

Is it an electron bug, a Chromium bug or something I missed?

The repository to reproduce: https://github.com/afloras/electron-bg-memory-usage

Electron v9.1.2 and NodeJS v12.18.0 used.

**Comment by dsanders11** [comment]
> Is it an electron bug, a Chromium bug or something I missed?

@afloras, I don't believe there's any bugs. I was able to replicate it using your repository and it does not replicate as long as you don't open DevTools in `main.js`.

Since the image is 1.3 MB and you're base64 encoding it, the data-uris are probably around 2 MB long for the image, and they're all different due to the timestamp you add. That means the DevTools network request tab is logging all of those, at 2 MB per request, 5 per second, so about 10 MB a second.

I believe the memory usage you're seeing is due to DevTools and the long image data-uris. When running without DevTools opened on start, the app never uses more than 90 MB of memory in my testing.
