### ISSUE TITLE
Net module request data is incomplete

### ISSUE THREAD

**Issue by chuanxinwong** [electron/electron#24848]
Net module request data is incomplete, 

my code:
```
// index.js
...
setTimeout(() => {
    test();
}, 5000)

function test() {
    var url = "https://www.baidu.com";

    const request = net.request(url);

    var bfh = new BufferHelper();
    var chunks = [];
    var size = 0;

    request.on("response", (response) => {
        console.log(`STATUS: ${response.statusCode}`);

        response.on("data", (chunk) => {
            console.log(`ondata...`);
            console.log(chunk);
            console.log(chunk.length);
            size += chunk.length;
            bfh.concat(chunk);
        });

        response.on("end", () => {
            console.log("end");

            console.log(size);
            console.log(chunks.length);

            var str = bfh.toBuffer().toString();
            console.log(str); // data is incomplete 
        });
    });
    request.end();
}
```

**Comment by VerteDinde** [comment]
Hey @chuanxinwong, thanks for reporting an issue.

It looks like your issue is missing a few items we include in our PR template, like your current version of Electron and the platform you're running on. We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by nornagon** [comment]
Closing this issue as it's missing the Electron version and also the provided code is incomplete (refers to `BufferHelper`, which is not defined anywhere).
