### ISSUE TITLE
can electron support key remapping on mac os?

### ISSUE THREAD

**Issue by pythonfirst** [electron/electron#24870]
Apple api link is below:
https://developer.apple.com/library/archive/technotes/tn2450/_index.html
Can electron support this?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
