### ISSUE TITLE
Write something

### ISSUE THREAD

**Issue by KINGBANANA007** [electron/electron#24904]
I want to write with my Bot, but it isn't working.
The called "Reload Messages" I try to reload Discord Bot Application, but isn't working.
It also doesn't working, when I redownloade the game

[](url
![image](https://user-images.githubusercontent.com/69401602/89718738-ab0ea280-d9c1-11ea-999d-fee0786ee4dd.png)
)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
