### ISSUE TITLE
Please clarify how Electron choose/runs an app

### ISSUE THREAD

**Issue by shrewdlogarithm** [electron/electron#2492]
I've asked this question at least twice before (in relation to specific issues) but never gotten a straight answer - and I believe what the Wiki suggests in some areas is plain wrong.

Running Electron from a command line often shows the option of setting a path/choosing an app to run - but I cannot actually get that to work - e.g.

electron resources/app/myappname

Doesn't seem to work at all - what electron seems to do is look for

resources/app.asar
(it may look for default_app.asar but I've not tested that)
resources/app/app/
resources/app/default_app/

Can I get clarification of what is SUPPOSED to work here - people clearly THINK you should be able to specify an app directory/asar name - but what I've tried just hasn't worked 

Thanks!

**Comment by frankhale** [comment]
If you execute Electron with no command line params it will look for the following:

```
resources/app.asar
resources/app
resources/default_app
```

You can however execute Electron from command line and pass in your app as a param:

```
electron your_app
```

**Comment by shrewdlogarithm** [comment]
Where your-app is an asar file or the name of a folder in resources\app or must it include the resources\app path??

e.g. I have an app in resources\app\myapp

Do I use

electron resources\app\myapp
or
electron myapp

??

I've had issues getting this working before (not tried with the last few releases) y'see - to the extent I was wondering if they'd changed how this worked at some point (I have made it work in the past)

**Comment by frankhale** [comment]
If your app is in the resources folder either as an app.asar, contained in a folder called app or default_app you won't need to tell Electron where it is. The folder resources\app or resources\default_app must be the root of your application. 

Having your app in the app folder like this is most likely not going to work:

```
resources\app\my_app
```

The way I choose to run Electron is to just put my app in resources\app and double click Electron.exe.

**Comment by shrewdlogarithm** [comment]
Custom app folders (or asar files as-of a recent build at least) just don't
work at-all - but people keep saying things like

electron myapp

Which kinda suggests it does work - which is why I asked the question
really.

At some point I suspect people may want to shop an Electron application
which contains more than 1 app - so the ability to pass the app name
(searched for as an asar or directory) would be nice (and it's implied that
it works but right now doesn't?)

or

If that's not possible, we need to stop suggesting it is in examples - if
it searches a set of presets (app.asar, resources\apps\app,
resources\apps\default_app) then that could be made clearer at least?

**Comment by etiktin** [comment]
The ability to run an electron app by passing an argument to electron is implemented in the `default_app` and not in electron it self (in [main.js](https://github.com/atom/electron/blob/master/atom/browser/default_app/main.js) follow the handling of `option.file`). It's meant to ease the development stage. For production, I reckon most apps don't want or need this behavior at least not as default. Keep in mind that in order to use the `default_app`, you can't have `app.asar` or `app` folder in your `resources` folder (any other name should be fine). If you really want to add this behavior for your app, I suggest you implement it in your app by following the `default_app` implementation (I wouldn't distribute the `default_app`, because it contains some other stuff I don't want in production, such as a global shortcut to open devtools).

**Comment by zcbenz** [comment]
I'm closing this since it has been perfectly answered.
