### ISSUE TITLE
Print is showing margin instead of margin to none or custom 0,0,0,0

### ISSUE THREAD

**Issue by uengage** [electron/electron#24949]
The print is showing margin instead of margin to none or custom 0,0,0,0
we have provided all the option marginType printable area, none, minimum still by default margin is coming.
Due to margin by text is getting cropper in  POS thermal printer 58".
Please help urgentlt

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.
