### ISSUE TITLE
Refactor printing code based on headless component print manager

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#24947]
This is based on the discussion from https://bugs.chromium.org/p/chromium/issues/detail?id=1101596 , our current implementation of pdf generation is kind of hack using bits from `//chrome`. 

We have hit the limits of this hack, with oopif enabled our implementation is unable to composite the document with sub frames. Also we maintain considerable amount of patch set in `printing.patch` that cannot be upstreamed.

Let us try to minimize this based on the pointers from upstream.

/cc @codebytere

**Comment by ckerr** [comment]
This is making its way into our roll in https://github.com/electron/electron/pull/33091 via https://chromium-review.googlesource.com/c/chromium/src/+/3111565, which is a precursor to https://chromium-review.googlesource.com/c/chromium/src/+/3082312/ .

I've put in stubs for our silent / job_settings / canceled parameters in https://github.com/electron/electron/pull/33091/commits/e17ada2846bccc6dfdc911623cdaf86143b9106f which unblocks the roll, but a more comprehensive refactor is called for with the kinds of goals described above by @deepak1556 about using upstream code instead of patching it
