### ISSUE TITLE
Building Blazor Electron App for Raspberry Pi 4 running Ubuntu 20.04

### ISSUE THREAD

**Issue by samanthazammit** [electron/electron#24954]
I have been able to create a blazor electron demo application following: https://github.com/jimbuck/blazor-electron-demo but unfortunately I'm having trouble building for arm64 so that I can put the application on my pi. I've only been able to build x64 linux executables using the "dotnet electronize build /target linux" command. What can I use to build/publish the application for linux arm64?

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
