### ISSUE TITLE
How to add a linux package that is not present in electron chromium linux build?

### ISSUE THREAD

**Issue by jenifa-r** [electron/electron#24960]
Electron : 4.0.0

OS : Ubuntu 18.04.3 TLS

I am trying to make few changes to the electron's source code which is compiled following the link below: https://www.electronjs.org/docs/development/build-instructions-linux#prerequisites

My requirement calls for the need of linux XCB Test Api's **xcb_test_fake_input_checked** function. But, when I include <xcb/xtest.h> in the c++ file I have created , I get **fatal error: 'xcb/xtest.h' file not found**.

The corresponding package **libxcb-xtest0-dev** is already installed in the machine.

I tried the command **locate xtest.h** . It gives the path as  /usr/include/xcb/xtest.h

But, other header files like xproto.h which gets properly included in the c++ file, are present under the electron build folder(Path: electron/src/build/linux/debian_sid_i386-sysroot/usr/include/xcb/xproto.h).

I assume, the reason for the fatal error is that electron linux build folder doesn't have xtest.h.

How can I install this libxcb-xtest0-dev dependency for my electron linux build, so that xtest.h gets included properly?

**Comment by ckerr** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
