### ISSUE TITLE
when contextIsolation is true,  <webview> listening "new-window" , the event can't get the url 

### ISSUE THREAD

**Issue by piaoguowyq** [electron/electron#24966]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by piaoguowyq** [comment]
Electron Version:  9.0.0 and 9.2.0;
Operating System:  macOS

**Comment by eugene-pr** [comment]
Do you have sandbox set to true in the BrowserWindow webPreferences?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
