### ISSUE TITLE
Devtools extensions

### ISSUE THREAD

**Issue by marekhrabe** [electron/electron#250]
Hi, is there any way to support devtools extensions or is it implemented on another level of Chromium? I'd like to implement a custom panel and provide some debugging UI specific for my app.

(Btw thanks for all the big announcements today :heart_eyes_cat:)

**Comment by deepak1556** [comment]
I suspect its because of those extensions using chrome.* apis which is not implemented in atom-shell yet according to this doc https://github.com/atom/atom-shell/blob/master/docs/tutorial/devtools-extension.md#chrome-apis . But extensions which just use chrome.devtools.* works fine, try https://github.com/snookca/CoffeeConsole/tree/master/src for example http://snag.gy/zMGTu.jpg
