### ISSUE TITLE
How to use bluetooth api?

### ISSUE THREAD

**Issue by fly7632785** [electron/electron#25036]
Hello, everybody!
After checking the all documents about the bluetooth, I still don't find the standard use for bluetooth.
I used the chrome's  bluetooth api of the web api, suck as :
```  
options.acceptAllDevices = true;
                navigator
                    .bluetooth
                    .requestDevice(options)
                    .then(device => {
                        console.log('> Name:             ' + device.name);
                        console.log('> Id:               ' + device.id);
                        console.log('> Initially, connected?        ' + device.gatt.connected);
                        console.log('> Now, connected?        ' + device.gatt.connected);
                        // return device.gatt.connect();
                    })
                    .catch(error => {
                        console.log('Argh! ' + error);
                    });
```
but it's not seem to work normally.
I just want to know how to scan bluetooth then  connect the one, and send some data by serial port.
Please tell me something, thank you all much!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by fly7632785** [comment]
OK thank you
