### ISSUE TITLE
Is there a way to hide the fullscreen stoplight button (“green traffic light”) in the top left?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [electron/electron#25037]
![image](https://user-images.githubusercontent.com/8111351/90627592-bcbc3980-e24e-11ea-94ec-9950b93ca2c0.png)

Electron version: 9.2.0
Operating system: Mac

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
