### ISSUE TITLE
is a way to   print preview and support default horizontal printing

### ISSUE THREAD

**Issue by yimenghuange95** [electron/electron#25038]
is a way to   print preview and support default horizontal printing in version9.2.0？i  used Css like this,but not take effect.： @page {
  margin: 0;
  size: A4 landscape;
}

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
