### ISSUE TITLE
App packaging

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#251]
It would be awesome to get packaging support with embedding resourses to executable file
Discussed a lot here: https://github.com/rogerwang/node-webkit/issues/151 don't get confused with issue title btw

**Comment by reggi** [comment]
@zcbenz I don't understand the benefit of asar, or really understand the point. Is it supposed to prevent users from viewing the source code of an atom shell app? It doesn't have compression so it doesn't make the app smaller. Would love to understand the point. :smile_cat:

**Comment by bwin** [comment]
@reggi: the *average person* can't look into these files (don't confuse this with security of any kind) and it can speed up installation (because you have a lot less files). Also there are plans for a atom-shell-runtime and this would be the app-format of choice.

**Comment by reggi** [comment]
@bwin Is there any way to hide my source code? I have a `package.json` with a github token in it that points to a private libs repo for my app, something like this. I'd have to remove stuff this before the app gets released publicly and thats a bummer.

```
"package-name": "git+https://<github_token>:x-oauth-basic@github.com/<user>/<repo>.git"
```

**Comment by bwin** [comment]
First thing I can think of right now, would be a grunt (or gulp or whatever) task, that replaces this line before release. (You would have to make a copy of your working dir for releases to not overwrite your "original" package.json; I would anyway suggest a release-dir).

About encryption: since the encrypted file has to be decrypted on the user's machine, the key/password would also have to be on the users machine. So having this info even in an encrypted state would still be dangerous. So maybe stripping this info beforehand is the better solution.
(Also your "secret" file could end up in the users temp dir ...)

**Comment by paulcbetts** [comment]
> and it can speed up installation (because you have a lot less files)

On WIndows this is most likely a **huge** benefit, file operations on Windows are *much* slower than on Linux (because Windows supports way more features); writing 10000 1KB files is going to be orders of magnitude slower than writing one 10MB file, even though it's the same amount of data.

**Comment by thedaniel** [comment]
Doing a ton of file reads to load a large JS app is also a performance killer. One of our startup time speedup strategies in Atom involves concatting files for this reason.

**Comment by bmeck** [comment]
I'd love to get on a call about this as it is a different format than my archive loader and we can discuss things. Particularly I have concerns with implementing a fake `fs` module that is not fully featured/compatible.

**Comment by shrewdlogarithm** [comment]
As my comments on asar were referenced above - I'll qualify them by saying a few things

1 - obfuscation/code-hiding is mostly pointless - if someone wants your code, they'll find a way to get it.  If this is a problem, you're using the wrong tools (CSS/HTML/JS) entirely.

2 - runtime performance isn't a huge deal either - you shouldn't be storing a large amount of data inside a distribution archive, there are many, many better places to store data and code is generally small enough that read/write performance isn't an issue (and again, the tools aren't really "performance" focussed)??

3 - whatever archive format you use should support dynamic read/write from the app itself so that the app can download/update it's own archive (auto-update) as slickly as possible(*)

4 - it would help if it built on WIndows without a lot of dodgy dealing with age-old libraries ;0

(*) for Node Webkit I built a thing which downloads GitHub releases and re-packs them as package.nw files (without needing to write anything to disk other than the final result - it's all streamed/piped in-memory)  The app then restarts itself and it's auto-updated!! - I'm not sure I could do that with an asar at this point?

**Comment by YuriSolovyov** [comment]
1. It is already mentioned that it is enough to prevent just average person messing with code. it is just handy, and you should not rely on that for security. 100% agree with you here.
2. When somebody says asar gives performance increase, I think they refer to faster reads for large number of files, not faster read of one big resource. Though, I'm not I got it right. /cc @zcbenz 
3. As docs [states](https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-packaging.md#archives-are-read-only), asar archives are indeed read-only, so yeah, for auto-update you have to re-create them yourself.
4. not sure what you mean.

I mostly agree with you, asar could be better, but hey, we need to start somewhere.
Possibly related: https://github.com/atom/atom-shell/issues/673

**Comment by shrewdlogarithm** [comment]
3 relies on there being an asar library which enables that sort of thing - right now, asar seems to be limited to archiving files already on-disk - it needs (and wouldn't be hard to give it I guess) pipe/streaming support?

4 relates to an issue I raised in the asar repo - it's not an easy thing to install on WIndows (I've yet to actually get it working properly without hackery)  - it's also non-native but then so are most zip/tar/gzip tools I guess...

**Comment by YuriSolovyov** [comment]
3. Looking at [asar archive structure](https://github.com/atom/atom-shell/issues/251#issuecomment-56296018), I think yes, you need files to be on disk at archive creation time, so yes, if you want to convert github release .zip into .asar, you need to do it manually, which, I agree, is not great.

**Comment by YuriSolovyov** [comment]
I am also thinking if monkey-patching node's `fs` module for transparent .asar support was a good idea, isn't it better to have separate `asar-fs` module to deal with asar-related tasks? ATM `fs` module can be treated as `asar-fs`, and node's fs is `original-fs`. Maybe it is just me, but it seems weird.

**Comment by smallscript** [comment]
Except that ZIP does support all the above, is extremely efficient for random access, does have symlinks, custom attrs, and zillions of tools that support that. I use it all the time for the exact use case you're describing including having it utilize a binary search to locate files with NO requirement to pre-sort on load.
