### ISSUE TITLE
Renderer crash after calling navigator.setAppBadge(42)

### ISSUE THREAD

**Issue by zarubond** [electron/electron#25141]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9, 10
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  *  none

### Expected Behavior
Calling navigator.setAppBadge(42) should create an application badge on taskbar with the number 42.

### Actual Behavior
Render process crashed after calling navigator.setAppBadge(42) 

### To Reproduce
Start Electron, open console and try to execute navigator.setAppBadge(42) 

### Additional Information

https://web.dev/badging-api/

**Comment by codebytere** [comment]
Seems to be the following: 
> ```Terminating render process for bad Mojo message: Received bad user message: No binder found for interface blink.mojom.BadgeService for the frame/document scope```

**Comment by zarubond** [comment]
Electron does support badges on Mac/Linux but not on Windows. On Windows I can use overlays but that is not very convenient. Having one standardized API would be simply be better.

**Comment by thomas-darling** [comment]
@codebytere

Yep, this definitely needs to be at least mitigated - I just spend two whole days trying to debug a crash caused by this.

May I ask how you found that log message?
Because I never found _any_ way to get _any_ useful log messages when the renderer crashes - and honestly, even though it is working for us right now, it's been so frustrating to debug this, that we are seriously considering just giving up on Electron, and dropping our plans for a desktop product. Maintaining a desktop package is just not worth the development costs, if we cannot properly debug those types of errors. So I'm hoping I'm just missing something obvious here 🙂 

Also, regarding the badge API - I think Electron should actually support this API. Having your own API is fine, if that provides more options, but I think it makes sense that the standard browser API should work too. Either that, or the methods need to be removed from the `navigator` object, so our feature detection doesn't mistakenly think they can be called...

**Comment by codebytere** [comment]
@thomas-darling if you simply add `navigator.setAppBadge(42)` to `renderer.js` in https://github.com/electron/fiddle and hit Run you should see it right in console. For some context - the reason this may be difficult to achieve is that on the Chromium side, this API in intrinsically tied to one's Profile in Chrome (the account they're signed in as) In context, it makes sense, since e.g if  i’m signed in to two different Slacks in two different Profiles, they’re gonna need different badge counts. However, Electron doesn't have a concept of a Profile, so we'd need to perform at minimum a nontrivial bit of patching to get it to compile at all.

**Comment by ckerr** [comment]
@thomas-darling did those suggestions help you to test/debug on the renderer side? Also, is there anything we could have done that would have made those two days of debugging the crash easier? E.g. is there something that would have made this information (e.g. `ELECTRON_ENABLE_LOGGING`) easier to find?

**Comment by thomas-darling** [comment]
@codebytere, Awesome, thanks!
That was indeed the magic environment variable to set, and now I do see the error message.
Also didn't know about Electron Fiddle, so thanks for that one too 🙂 

@ckerr To elaborate on my experience with this:

My initial experience, before enabling that environment variable, was this very frustrating and unhelpful view:

![image](https://user-images.githubusercontent.com/6388663/92155698-12383f00-ee28-11ea-9d2c-1d397adc15fc.png)
![image](https://user-images.githubusercontent.com/6388663/92155815-3f84ed00-ee28-11ea-90f0-4ef7fe6027a7.png)

I would imagine _a lot_ of new uses would give up pretty quickly when faced with that...

Regarding ways to improve the discoverability of the solution:

* When the process crashes, and debugging is not enabled, you should log a hint to the console, informing the user that they can set this environment variable to get more information about what happened. That would have solved my problem instantly.
 
* Googling `electron devtools disconnected` produces lots of questions, but not a single answer mentions the existence of this environment variable - and mostly the answers are just unhelpful and time wasting shots in the dark. Given how hard this is to debug for a new user, I think it might be worth investing a bit of time in replying to a couple of the top results on stackoverflow, just with some basic tips on how to debug in this situation.

* On https://www.electronjs.org, under the title "The hard parts made easy", there is a link to "Debugging & profiling".
  That's great - except that this page mentions nothing about this environment variable. Fair enough, that page is clearly not intended as documentation, but it certainly didn't make the hard parts any easier...

* Same goes for https://www.electronjs.org/docs - neither the section "Setting up the Development Environment" or "Testing and Debugging" mention this environment variable, or provide _any_ hints about how to debug in this situation. Actually, the only place I can find this mentioned on the entire site, is on that "Environment variables" page, linked under the heading "API Reference" - not exactly the first place one would look for debugging advice. Or for environment variables, for that matter.

* https://www.electron.build doesn't mention anything about debugging either - would have been helpful though.

**Comment by codebytere** [comment]
@thomas-darling thanks for such an in-depth response 🙇🏻‍♀️ 

These are all great & appreciated suggestions - i'll see if i can try to get some of these implemented and/or improved :)

**Comment by MarshallOfSound** [comment]
All good suggestions, just want to highlight that

> https://www.electron.build doesn't mention anything about debugging either - would have been helpful though.

that domain is not owned nor controlled by us, it's a third party and the content of that website isn't Official
