### ISSUE TITLE
MAC Versión 1.12.0 (1.12.0) - Doesn't refresh games online 

### ISSUE THREAD

**Issue by espbaygon** [electron/electron#25156]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:1.12.0
  * 
* **Operating System:macOS 
  * Catalina 10.15.6
* **Last Known Working Electron version:**
  * 

### Expected Behavior
 Import runes from Blitz to League of Legends game

### Actual Behavior
 It doesntt import and refresh live games (runes and live stats).

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by espbaygon** [comment]
Hello,

thank you for the response. Maybe I explained in bad way, Is not a question, before the new version, it works well. But actually it doesn't import runes and live games. It seems that now it does not synchronize well.
Reading my response if you consider that I can find a solution in the comunity formur, please let me know.

Regards

**Comment by espbaygon** [comment]
Hello Again,

just today is a new Versión 1.12.1 (1.12.1) and when I installed it, there is no issue now. So it works again. 

Thank you,
