### ISSUE TITLE
Getting error dialog box on windows 10 if remove application icon from %temp% folder.

### ISSUE THREAD

**Issue by anilgwl** [electron/electron#25190]
Hello guys,
i am getting error dialog box on windows 10 if remove application icon from temp folder.
![image](https://user-images.githubusercontent.com/47106917/91578010-31862680-e967-11ea-8cde-f2edab2eda5c.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks for understanding and meeting us half way 😀

**Comment by anilgwl** [comment]
> Hello guys,
> i am getting error dialog box on windows 10 if remove application icon from temp folder.
> ![image](https://user-images.githubusercontent.com/47106917/91578010-31862680-e967-11ea-8cde-f2edab2eda5c.png)
