### ISSUE TITLE
How to build electron.exe

### ISSUE THREAD

**Issue by AlvinZhangH** [electron/electron#25210]
After readed https://github.com/electron/electron/blob/master/CONTRIBUTING.md, I still not very clear to build electron.exe on WIN10.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
