### ISSUE TITLE
[ISSUE] Premid not opening (with explanation and fix)

### ISSUE THREAD

**Issue by ySkyler** [electron/electron#25213]
So, I contacted support and tried troubleshooting, but nothing would work.
So I did what made my Oculus software (fixed later on), as well as Microsoft Flight Simulator 2020, I created a new Windows user. 
In that Windows user, I would not have " " nor "é" present in my main user.
For now, I will have to use my secondary windows user and wait for it to be patched 
Thank you for the awesome support :)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
