### ISSUE TITLE
2 letters+colon in first parameter crashes electron if any second parameter is present

### ISSUE THREAD

**Issue by frfancha** [electron/electron#25270]
How to reproduce:

From a well known electron application, Visual Studio Code:

Try from command line:
`code aa: a` ==> crash
`code a: a` ==> ok
`code a: aa:` ==> ok

From scratch:

platform Windows 10
electron 10.1.1
electron-builder 22.8.0
only one single file in the project called _elec_:
main: index.js, containing one single line of code:
`console.log(process.argv);`

build with electron-builder (with all default)

start the exe from the command line
ok if first param has only 1 letter before colon:
```
D:\Dev\elec\dist\win-unpacked>elec a: aa:
[ 'D:\\Dev\\elec\\dist\\win-unpacked\\elec.exe', 'a:', 'aa:' ]
````
crashes if first parameter has 2 characters before colon:
`elec aa: aa:`

this crashes also:
`elec aa: a`

But without second parameter this works:
```
D:\Dev\elec\dist\win-unpacked>elec aa:
[ 'D:\\Dev\\elec\\dist\\win-unpacked\\elec.exe', 'aa:' ]

```

Note: the index.js used in pure node.js (not from electron) accept any combination of parameters)

**Comment by MarshallOfSound** [comment]
This is expected behavior, and is a security mitigation against an age old windows flaw

**Comment by frfancha** [comment]
It prevents to pass legitimate arguments such as url to electron apps so that surely can't be expected.
Could you at least give any kind of link to what you mention as "age windows flaw"?

**Comment by matschek** [comment]
@MarshallOfSound @pushkin This behaviour has been discussed/mentiones four times now, and every report has been closed with "expected behaviour" (Although the reportes did not expect a silent application crash) and that this is against an old windows flaw, but without giving details in any of the threads. 
I think more information is needed to work on a better method. At least the documentation should mention that (and why) some  parameters are not allowed and will crash the electron framework if tried.
