### ISSUE TITLE
BrowserView - win.getNativeWindowHandle()

### ISSUE THREAD

**Issue by anrouk** [electron/electron#25326]
Would it be possible to get the function 'getNativeWindowHandle()' within a BrowserView?

**Comment by pushkin-** [comment]
can't you do BrowserWindow.fromBrowserView(browserView).getnativeWindowHandle()? I'm not sure that it makes sense to get a window handle of a frame like that

**Comment by anrouk** [comment]
That’s what we originally thought, but we receive: getNativeWindowHandle() is not a function.

Maybe if I was give you the scenario:  If we open a window and can send the handle to our propriety video software, which it is able to hijack the handle to display video output within that window.  What we would really like to do, display the video within an ‘embedded’ window such as a BrowserView, which as an independent window and should, in theory, have it’s own handle.

**Comment by pushkin-** [comment]
I'm kind of confused. BrowserView isn't a window, right? It's just a frame embedded inside of a window, so how do you expect to get the window handle of it? (unless BrowserView is implemented like a window, I'm not really sure)

**Comment by anrouk** [comment]
I can’t answer that, as my understanding of a frame in electron is a frame is equal to a window. If that is not the case then I stand corrected.

**Comment by anrouk** [comment]
As a BrowserView is not always attached to a window and can be easily swapped inbetween other BrowerWindows, I can see no reason why it would not have its own native handler?

**Comment by pushkin-** [comment]
I guess I'm not familiar with cases where the BrowserView isn't attached to a window. I thought it always had to be.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
