### ISSUE TITLE
Cannot read property 'request' of undefined 

### ISSUE THREAD

**Issue by xclidongbo** [electron/electron#25384]
```
const { net } = require("electron");
    const postData = JSON.stringify({
      username: name_elem.value,
      passwd: md5_pwd,
    });
    const req = net.request({
      method: "POST",
      protocal: "https:",
      hostname: "caesar.sinosig.com",
      port: 9000,
      path: "/newLogin",
      // url: "https://caesar.sinosig.com:9000/newLogin",
      headers: {
        // "Content-Type": "application/json",
        "Content-Length": postData.length,
      },
    });
    req.on("response", (response) => {
      console.log(response);
    });
    req.write(postData);
    req.end();
```

encryptAES.js:45 Uncaught TypeError: Cannot read property 'request' of undefined
    at newLogin (encryptAES.js:45)
    at HTMLButtonElement.onclick (index.html:45)

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by MarshallOfSound** [comment]
@xclidongbo `net` is a main process only API, you are trying to use it in the renderer process (`index.html`) this is not and will not be supported.  In the renderer process use `fetch` instead
