### ISSUE TITLE
Cannot read property bind of undefined 

### ISSUE THREAD

**Issue by 0xayman** [electron/electron#25433]
I've found an issue on electron version 10, the following code gives and error saying cannot read property bind of undefined, however the functions are defined and the same code works perfectly in previous versions of electron up to version 9.3.0 but it crash on version 10. 

```
const { app, Menu, Tray } = require('electron')
class AppTray extends Tray {
  constructor(icon, mainWindow) {
    super(icon)
    this.setToolTip('SysTop')
    this.mainWindow = mainWindow
    this.on('click', this.onClick.bind(this))
    this.on('right-click', this.onRightClick.bind(this))
  }
  onClick() {
    if (this.mainWindow.isVisible() === true) {
      this.mainWindow.hide()
    } else {
      this.mainWindow.show()
    }
  }
  onRightClick() {
    const contextMenu = Menu.buildFromTemplate([
      {
        label: 'Quit',
        click: () => {
          app.isQuitting = true
          app.quit()
        },
      },
    ])
    this.popUpContextMenu(contextMenu)
  }
}
module.exports = AppTray
```

**Comment by MarshallOfSound** [comment]
@nornagon potentially related to the ginify changes?

**Comment by MarshallOfSound** [comment]
Though worth noting @0xayman we neither attempt to support nor recommend that you `extend` built in classes in Electron.  It can result in very unexpected behavior

**Comment by fcharron** [comment]
I have the same problem as the OP. I am in the process of learning Electron (through a [Udemy course](https://www.udemy.com/course/electron-from-scratch/), which I figure is where the OP found his code snippet, since it's the exact same code), and extending the Tray class was something the instructor did on one project.

Is the fact that we should not extend built-in Electron classes documented somewhere? I figure it would avoid a few headaches if it was.

BWT, this error only happens since 10.0.0. The exact same code works fine on 8 and 9 (up to the latest version).

**Comment by fcharron** [comment]
And is this non-support/recommendation valid for all Electron classes, or just ones that wrap native code? If it's just the native ones, is there a way to identify those?

**Comment by blazk0** [comment]
I fixed it this way. Remove the `.bind(this)` and write the function in arrow function syntax

`this.on('click', this.onClick)`

`onClick = () => {
    if (this.mainWindow.isVisible()) {
      this.mainWindow.hide();
    } else {
      this.mainWindow.show();
    }
  };`
