### ISSUE TITLE
setAsDefaultProtocolClient in ubuntu return false

### ISSUE THREAD

**Issue by dongasai** [electron/electron#25432]
ubuntu 18.04.5

https://github.com/dongasai/electron-api-demos/commit/ed3dfd5df550a6bb5d46938e9b2747ee3a84ebfe

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by dongasai** [comment]
This issue is a known bug, is it being processed?
