### ISSUE TITLE
Why webContents from certificate-error doesn't work?

### ISSUE THREAD

**Issue by Silvano14** [electron/electron#25447]
```
// SSL/TSL: this is the self signed certificate support
app.on(
  "certificate-error",
  (event, webContents, url, error, certificate, callback) => {
    // On certificate error we disable default behaviour (stop loading the page)
    // and we then say "it is all fine - true" to the callback
    event.preventDefault();

    console.log("list windows: ", BrowserWindow.fromWebContents(webContents));
    callback(true);
  }
);
```

Simply, this piece of code doesn't work. Why? 
The console get " list windows:  null" 

OS: Linux Mint 
Electron Version: 9.2.1

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
Possibly related: https://github.com/electron/electron/pull/25408
