### ISSUE TITLE
Is there any way to send a "SharedArrayBuffer" and communicate using Atomics API?

### ISSUE THREAD

**Issue by samad-aghaei** [electron/electron#25446]
const sab = new SharedArrayBuffer( 2 * Int32Array.BYTES_PER_ELEMENT )
const { port1, port2 } = new MessageChannel()
port1.addEventListener("message", (e) =>
{
    console.log(e.data)
    port1.close()
}, { once: true })
port1.start()
ipcRenderer.postMessage("message", [sab], [port2])

//Error: An object could not be cloned.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
@samad-aghaei we don't currently support sending SharedArrayBuffers to the main process.
