### ISSUE TITLE
How can i pass options to require.resolve

### ISSUE THREAD

**Issue by dicklwm** [electron/electron#25518]
I want to require my node library in render process, but this module is not in the node_modules.

1. `new BrowerWindows({  ..., nodeIntegration: true   })`
2. `const myLib = window.require.resolve('lib/myLib', { paths: ['my_node_modules'] })`, `require.resolve` function pass options paths
3. But Error!
4. Analyse call stack, see Screenshots.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  * macOS 10.15.6 (19G2021) and Windows 10 (1809)
* **Last Known Working Electron version:** 
    * 6.0.7

### Expected Behavior

I can require my library from my define paths

### Actual Behavior

I can not require my library from my define paths, the options dismiss
### Screenshots

![image](https://user-images.githubusercontent.com/19289258/93476625-990f1080-f92c-11ea-99b0-937c3d161db5.png)
1. `require.resolve` function `options` is here, and invoke `Module._resolveFilename`

![image](https://user-images.githubusercontent.com/19289258/93477297-716c7800-f92d-11ea-9e6d-699e495cf112.png)

2. `Module._resolveFilename = function (request, parent, isMain) {}` 
Why options dismiss?

### Additional Information

master branch also hava this problem, is this a bug?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
