### ISSUE TITLE
How to generate symbol file if I build electron by myself

### ISSUE THREAD

**Issue by wutianlin** [electron/electron#25517]
Hello, I would like to ask some questions about how to generate symbol files for breakpad. We only build dSYM files.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
