### ISSUE TITLE
Issue with appendSwitch 'force-fieldtrials' in v10.1.2

### ISSUE THREAD

**Issue by ashish-1689** [electron/electron#25529]
Electron Version: v10.1.2
Operating System (Platform and Version): MacOS Catalina v10.15.5

#### Expected Behavior
I’m trying to set force-fieldtrials with appendSwitch to my application in order to enable a trial feature of WebRTC (VP9 SVC)

#### Actual behavior
it doesn’t seem to work

#### To Reproduce

// on main.js
app.commandLine.appendSwitch('force-fieldtrials', 'WebRTC-SupportVP9SVC/EnabledByFlag_3SL3TL');

I can see that this flag is not listed in the supported command line switches:  https://www.electronjs.org/docs/api/command-line-switches

Is it just getting ignored? Any help would be appreciated.

**Comment by codebytere** [comment]
@ashish-1689 where are you finding the flag name? a search of the Chromium codebase shows me: https://source.chromium.org/search?q=WebRTC-SupportVP9SVC&sq=&ss=chromium

```
app.commandLine.appendSwitch('force-fieldtrials', 'WebRTC-SupportVP9SVC/EnabledByFlag_3SL3TL')
```

I recommend you ensure that the latter argument is correct - this should work properly (and regardless is not an issue with Electron itself since we just pass these straight to chromium)
