### ISSUE TITLE
Can't run Prolink Tools and Rekordbox on the same PC.

### ISSUE THREAD

**Issue by Sigvaladson** [electron/electron#25542]
I can't run Prolink tools and Rekordbox on the  same PC.

If I turn on Rekordbox and using the ethernet on my XDJ the Prolink Tools is offline, and vice versa if I turn on Prolink Tools I can't connect to my XDJs with Rekordbox.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
