### ISSUE TITLE
screenX is not correct in the touchmove event

### ISSUE THREAD

**Issue by wscj** [electron/electron#25556]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Windows 10 (1903 and 1709)
* **Last Known Working Electron version:**
  * 4.1.5

### Expected Behavior
In touch screen computer, the touchmove event has a screenX property, it's value is correct as I found it's definition in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX)
> The screenX read-only property of the MouseEvent interface provides the horizontal coordinate (offset) of the mouse pointer in global (screen) coordinates.

### Actual Behavior
The screenX is always equal to pageX, not the horizontal coordinate in screen coordinates.

### Additional Information
For example:

``` js
document.body.addEventListener('touchmove', (e) => {
  console.log(e.touches)
})
```
The result as below

![111](https://user-images.githubusercontent.com/18430196/94239271-20b7d900-ff44-11ea-9c1d-1b5598a697de.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by wscj** [comment]
@codebytere Finished

**Comment by wscj** [comment]
any news?
