### ISSUE TITLE
toggle the share UI of Windows 10

### ISSUE THREAD

**Issue by EnderAdel** [electron/electron#25590]
Wouldn't it be a good idea to add the ability to toggle the sharing UI on Windows 10?

![Screenshot 9_23_2020 1_41_38 PM](https://user-images.githubusercontent.com/57331033/94002413-8b311380-fda2-11ea-8d9b-44ea4e7cd1ea.png)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
