### ISSUE TITLE
Fully support running the Linux version of Electron on Chrome OS

### ISSUE THREAD

**Issue by EnderAdel** [electron/electron#25591]
Chrome OS can run Linux apps now. And I wonder if the Linux version of Electron will work normally on it. If not, then maybe you can make another version of Linux Electron for Chrome OS so it can work normally.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
