### ISSUE TITLE
Electron desktopCapturer.getSources().then is not resolved

### ISSUE THREAD

**Issue by pravintamil** [electron/electron#25595]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2
* **Operating System:**
  * Ubuntu 18.04.5 LTS

### Expected Behavior

`desktopCapturer.getSources().then` should be resolved

### Actual Behavior
`desktopCapturer.getSources().then` is not resolved after 1 minute

### To Reproduce
```js
const { app, desktopCapturer, screen } = require('electron');

const fs = require('fs')
const path = require('path')


function takeScreenshot() {
	console.log('Gathering screens...')
	const thumbSize = determineScreenShotSize()
	const options = { types: ['screen'], thumbnailSize: thumbSize }

	desktopCapturer.getSources(options).then((sources) => {
		console.log('Sources received:'+sources.length);
		sources.forEach(function (source) {
			const sourceName = source.name.toLowerCase();
			console.log(sourceName);
			if ( ['entire screen', 'screen 1'].includes(sourceName)) {
				const screenshotPath = path.join(app.getPath('pictures'), 'screenshot-' + new Date().toJSON() + '.png')
				fs.writeFile(screenshotPath, source.thumbnail.toPNG(), function (error) {
					if (error) return console.log(error)
					console.log('Saved screenshot to: ' + screenshotPath);
				})
			}
		})
	}).catch(console.error);
}

function determineScreenShotSize() {
	var screenSize = screen.getPrimaryDisplay().workAreaSize
	return {
		width: screenSize.width,
		height: screenSize.height
	}
}
setInterval(takeScreenshot, 15000);
```

```sh
git clone git@bitbucket.org:praveen-knackforge/electron-boilerplate.git -b screenshot
npm install
npm start || electron .
```

### Screenshots

![image](https://user-images.githubusercontent.com/14850417/94028581-93587580-fdd9-11ea-9adb-52d6ab5e92f8.png)

### Additional Information
I used `desktopCapturer` API from the main process

**Comment by codebytere** [comment]
Hmm - just tested this on `Ubuntu 18.04.5 LTS` with `10.1.2` and experienced no issues:

![Uploading Screen Shot 2020-09-24 at 1.39.51 PM.png…]()

**Comment by alectrocute** [comment]
I’m experiencing this bug albeit in a different context. On latest production Windows 10 and Electron 11.0.3, first call to `getSources` resolves perfectly. Second or third call will never resolve the promise, along with any subsequent calls. This effectively halts the application, at least in my use case. I’ll update this comment if/when I find a workaround.

**Comment by ibc** [comment]
We are experiencing this issue every day (macOS and Windows) using Electron 11 and previous values.

Yes, eventually we call `desktopCapturer.getSources()` (it may even be the first time we do it) and it never resolves.

**Comment by alectrocute** [comment]
> We are experiencing this issue every day (macOS and Windows) using Electron 11 and previous values.
> 
> Yes, eventually we call `desktopCapturer.getSources()` (it may even be the first time we do it) and it never resolves.

+1. I’ve since encountered the same issue on macOS.

**Comment by leandrogomide** [comment]
I have a similar problem when running code to periodically gather windows titles and icons. Code looks like this in main process:

```
setInterval(async () => {
    const options: Electron.SourcesOptions = {
      types: ["window"],
      fetchWindowIcons: true,
    };

    getLogger().debug("Calling getSources");
    const sources = await desktopCapturer.getSources(options);
    getLogger().debug("Finished sources");
}, 10000);
```

After some minutes running, I can only see a lot of `"Calling getSources"` lines in log - i.e., the call does not resolve. Electron version is 11.3.0 (previously, with version 11.1.1, app would simply freeze after entering a `getSources` call, but after updating it does not make app freeze, but does not return either).

**Comment by leandrogomide** [comment]
Electron returns the same Promise object if two successive calls to `getSources` are made with equal arguments. So if one fails, others will subsequently fail too. While this bug isn't solved, a possible workaround is to add an extra field to the `sources` argument, so that electron does not return same old Promise and actually runs the `getSources` logic again:


```typescript
const { app, desktopCapturer, screen } = require('electron');

const fs = require('fs')
const path = require('path')


function takeScreenshot() {
	console.log('Gathering screens...');
	const thumbSize = determineScreenShotSize();
        const workaroundTimestamp = Date.now();
	const options = { types: ['screen'], thumbnailSize: thumbSize,  workaroundTimestamp}

	desktopCapturer.getSources(options).then((sources) => {
		console.log('Sources received:'+sources.length);
		sources.forEach(function (source) {
			const sourceName = source.name.toLowerCase();
			console.log(sourceName);
			if ( ['entire screen', 'screen 1'].includes(sourceName)) {
				const screenshotPath = path.join(app.getPath('pictures'), 'screenshot-' + new Date().toJSON() + '.png')
				fs.writeFile(screenshotPath, source.thumbnail.toPNG(), function (error) {
					if (error) return console.log(error)
					console.log('Saved screenshot to: ' + screenshotPath);
				})
			}
		})
	}).catch(console.error);
}

function determineScreenShotSize() {
	var screenSize = screen.getPrimaryDisplay().workAreaSize
	return {
		width: screenSize.width,
		height: screenSize.height
	}
}
setInterval(takeScreenshot, 15000);
```

**Comment by samuelmaddock** [comment]
I'm able to reproduce this issue in Electron v13.0.0-beta.5 on Windows 10 64-bit (2004).
https://gist.github.com/90f43a52e7c48a531a57bec77428e11a

`desktopCapturer.getSources()` stops working after around 10 seconds of requests.

**Comment by samuelmaddock** [comment]
The root cause of the bug is related to the V8 handle of the internal `desktopCapturer` class being garbage collected too early, before the call to resolve the promise is invoked. I'll be creating a PR with a fix tomorrow.

**Comment by lmcarreiro** [comment]
It's good to have a fix at the root cause.

As there is a cache of pending promises for concurrent calls that have the same parameters, maybe it would worth to also have some kind of timeout (wrapping the main promise in a `Promise.race` with a promise that rejects itself after some seconds). In this case, if something else happens that keeps a stuck pending promise in the cache, the behavior on the caller would be easier to debug.

**Comment by samuelmaddock** [comment]
> maybe it would worth to also have some kind of timeout

If there are issues that persist after the fix is released, this might be something to consider.

**Comment by JaiKirhns** [comment]
---

**Issue Summary:**

After upgrading from Electron 27 to Electron 32, the `desktopCapturer.getSources` method behaves inconsistently on macOS versions 12 and later. The issue does not occur on Linux or Windows, and the same code worked correctly on all macOS versions when using Electron 27.

**Problem Details:**
1. **Initial Behavior:**
   - On the first or second call to `desktopCapturer.getSources`, no sources are returned, and the Electron app unexpectedly closes.
   - Adding a log statement before the call results in the logs being printed, but no response is returned, and the app closes.

2. **Subsequent Behavior:**
   - After 2–3 attempts, the method starts working as expected:
     - The sources are printed.
     - The app remains active and does not close.

3. **Observations:**
   - This issue only occurs on macOS versions 12 and above. 
   - On macOS 10.15, Linux, and Windows, the code works without any issues.
   - The issue is specific to the `desktopCapturer.getSources` method when upgraded to Electron 32.

**Code Example:**
```javascript
(async () => {
  try {
    const sources = await desktopCapturer.getSources({ types: ["screen"] });
    logger.info("Printing sources");
    logger.info(sources);
    if (sources.length > 0) {
      event.sender.send(
        "desktopSourceId",
        sources,
        JSON.stringify(screenSettings)
      );
    }
  } catch (error) {
    logger.info("Error fetching desktop sources:", error);
  }
})();
```

**Expected Behavior:**
- The `desktopCapturer.getSources` method should consistently fetch sources and return them on the first call.
- The Electron app should not close unexpectedly during this process.

**Actual Behavior:**
- On macOS 12 and later, the app closes unexpectedly on the first or second call, and no sources are returned.
- After 2–3 attempts, the method works correctly, and the app does not close.

---

Everything with mac os screen share permission are given.
