### ISSUE TITLE
Electron has lots of issues with Windows UNC paths

### ISSUE THREAD

**Issue by bpasero** [electron/electron#25618]
### Issue Details

* **Electron Version:**
  * 9.x
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * ???

### Expected Behavior
You can start an Electron app from UNC path and things work.

### Actual Behavior
Things do not work, like rendering or dev tools.

### To Reproduce
* open PowerShell
* `cd \\localhost\c$\Users\<username>\AppData\Local\electron-fiddle`
* run `electron-fiddle.exe` from there

You can see that the main window stays empty. You can also not open dev tools.

![image](https://user-images.githubusercontent.com/900690/94142047-f09e0680-fe6d-11ea-9d48-a6830fd4c25e.png)

We are seeing the same with VSCode, but I thought I report this with Electron Fiddle for easier reproduction.

**Comment by bpasero** [comment]
Another repro with just Electron:

* `git clone https://github.com/electron/electron-quick-start`
* `cd electron-quick-start`
* `npm install`
* open PowerShell
* `cd \\localhost\c$\<path to>\electron-quick-start`
* `.\node_modules\electron\dist\electron.exe .`

The app opens, but you cannot toggle devtools either.

**Comment by zcbenz** [comment]
I have tested Google Chrome and it can not open web pages under UNC paths with sandbox enabled:

```powershell
cd '\\localhost\c$\Program Files (x86)\Google\Chrome\Application\'
.\chrome.exe  # fails to open any website
.\chrome.exe --no-sandbox  # works normally
```

After a brief look at related code, it seems that Chromium's sandbox code has strict requirement at file paths, and we have to patch a lot of places to make sandbox work with UNC paths (if it is possible at all). So I think we should not support UNC paths with sandbox enabled in Electron.

For UNC paths with sandbox disabled, after some simple testing I think Electron already works under this case, a few apps (including Electron's default app) could not run under UNC paths but it was because their own code did not work with UNC paths, for example having Content Security Policy rules that do not allow loading UNC paths.

@bpasero So my conclusion so far is, Electron already works with UNC paths with sandbox disabled, and we should not try to make it work with sandbox enabled as it is not supported by Chrome.

**Comment by bpasero** [comment]
@zcbenz thanks for looking into this, I agree it is probably not worth the effort and we should follow Chrome's model here. I am fine closing this for now.
