### ISSUE TITLE
App reload when using Axios Response.data.pipe(fs.writeStreamFile()) ???

### ISSUE THREAD

**Issue by KidsBen7** [electron/electron#25627]
I'm using Electron React, and when i was saving new image from server by Axios response.data.pipe then the electron app or react auto reload, i dont know how to debug and why the app auto reload, can somebody help me? 
I have stucked in this bug for a week :( 

![bug](https://user-images.githubusercontent.com/34616034/94222651-2a2b4c00-ff18-11ea-8551-207be037badf.png)

**Comment by VerteDinde** [comment]
Hey @KidsBen7, thanks for reporting an issue! We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

When you fill out the template, could you please provide a standalone test that a tester could run to reproduce the issue?

Thanks so much!

**Comment by codebytere** [comment]
Closing as no response was provided.
