### ISSUE TITLE
How can NSService calling its NSMessage

### ISSUE THREAD

**Issue by leevscript** [electron/electron#25652]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

info.plist
```
<key>NSServices</key>
<array>
    <dict>
	<key>NSMenuItem</key>
        <dict>
            <key>default</key>
            <string>upload</string>
        </dict>
        <key>NSMessage</key>
        <string>uploadImage</string>
        <key>NSRequiredContext</key>
        <dict>
	    <key>NSTextContent</key>
	    <string>FilePath</string>
        </dict>
        <key>NSSendTypes</key>
	<array>
	    <string>NSFilenamesPboardType</string>
	    <string>public.plain-text</string>
	</array>
    </dict>
<array>
```

How to make the 'uploadImage' work? thanks you.

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
