### ISSUE TITLE
how to load muti htmls to an electron app in electron@10.1.2 like what electron-api-demos does

### ISSUE THREAD

**Issue by fw23t9** [electron/electron#25678]
in [electron-api-demos](https://github.com/electron/electron-api-demos), the app load muti htmls into an electron app, use html import. but the electron-api-demos is in electron@7.2.4

but i learned that HTML import is obsolete since Google Chrome 73, and i cann't use this way to load muti htmls into an electron app in electron@10.1.2, is this a bug or something changed?

my electron app cotains many tabs, and it's hard to write all the html codes in one html file

and how can i load muti htmls into an electron app in electron@10.1.2

or is there a better way to develop an electron app with many tabs?

that will help me a lot, waiting for your reply and suggests, and thank you~

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
