### ISSUE TITLE
Sqlite3 and electron js packaging issue

### ISSUE THREAD

**Issue by DivakarUpadhyay** [electron/electron#25683]
Dear Friends,
I am working with sqlite3 and electron js. My app is working fine in development environment but it is giving issue after packaging and running exe.
![image](https://user-images.githubusercontent.com/16423497/94576094-9698a900-0292-11eb-8563-39129924f827.png)
Please check the issue. Please help me asap.
you can contact me at my skype id :upadhyaydivakar1991

**Comment by ckerr** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
