### ISSUE TITLE
how to lock the OpenDialog in the front

### ISSUE THREAD

**Issue by ioriandy4** [electron/electron#25684]
how to lock the OpenDialog in the front，i use the method 'showOpenDialog' to let user slelect directory, but don't want user to do other things until they select the directory

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
