### ISSUE TITLE
Web links in Electron apps open up multiple windows

### ISSUE THREAD

**Issue by igbjnI05bF** [electron/electron#25712]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

This has been tested with multiple electron apps, Element and Hyper. When I click on a web link, multiple browser windows open. In my case it is 3 Qutebrowser windows and one Firefox window. 

xdg-settings get default-web-browser returns Qutebrowser (which is what I want)
xdg-open https://github.com opens up once in Qutebrowser (which is what I want)
Clicking on links in any other program on my desktop opens up in Qutebrowser once (which is what I want)
Clicking on links from within an Electron app opens up 3 Qutebrowser windows and 1 Firefox window (do not want)

* **Operating System:**
Gentoo Linux amd64 kernel 5.8.12

### Expected Behavior
I want the Electron app to respect my default program defined by xdg-settings set default-web-browser

### Actual Behavior
Electron apps open up web links in four separate windows, 3 in Qutebrowser and 1 in Firefox

### To Reproduce
Click on a web link in an electron app

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.  You have provided no information about the versions of Electron you are experiencing this with.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by srevinsaju** [comment]
Electron v10.1.2 and forward.

**Comment by igbjnI05bF** [comment]
@codebytere Do you need something else to take this out of blocked status?

**Comment by igbjnI05bF** [comment]
@codebytere Not sure what else I can do. Please let me know what other info you need to get this out of blocked status.

**Comment by srevinsaju** [comment]
@igbjnI05bF maybe we should close this issue, and reopen a new one with the electron version included so that @codebytere notices it?
