### ISSUE TITLE
My Electron App do no start

### ISSUE THREAD

**Issue by Ewan-skyrow** [electron/electron#25810]
# Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Electron version : 10.1.3

Everything worked so far, I wanted to change the menu at the top and my Electron application does not launch anymore, when I execute my command, nothing happens, I have no errors in the console but I do not not see the window that opens, in the task manager I have clearly marked as what Electron is open. I removed the changes I had made and still nothing ...

**Comment by VerteDinde** [comment]
Thanks for reaching out to the Electron team!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron, there are also a bunch of helpful people in [the community Discord](http://discord.gg/electron) that should be willing to point you in the right direction.
