### ISSUE TITLE
i can't use link.import in electron 10.1.2

### ISSUE THREAD

**Issue by fw23t9** [electron/electron#25842]
I made an app with many tabs, each tab has a unique html like tab-A.html, and the app could load special tabs in main process.
In the end of index.html I use <script>require('./tabs/imports')</script>

and in imports.js codes is like this

const links = document.querySelectorAll('link[rel="import"]')

// Import and add each page to the DOM
Array.prototype.forEach.call(links, (link) => {
  let template = link.import.querySelector('.task-template')
  let clone = document.importNode(template.content, true)
  
  if (link.href.match('tab-A.html')) {
    document.querySelector('.tab-A-content').appendChild(clone)
  } 
}
and tab-A.html

<template class="task-template">
    <section id="tab_A" class="section tab-A">
        
        <div class = "tab-pane modal-content panel panel-default" id = "A">
            <div class = "panel-heading">
                <h4 class = "panel-title">
                    TODO
                </h4>
            </div>
            <div class = "panel-body">
                AAA                  
            </div>                        
        </div>
    </section>
</template>

My codes is like above

link.import works for me with electron ^9 but not working In ^10
and i need a way to load muti htmls in an app

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
