### ISSUE TITLE
How to restart the child process without closing（如何在不关闭electron的情况下重启子进程后端）

### ISSUE THREAD

**Issue by m986883511** [electron/electron#25845]
const createPyProc = () => {
  let script = path.join(__dirname, 'app.py')
  pyProc = require('child_process').spawn('python', [script])
  if (pyProc != null) {
    console.log('child process success')
  }
}
app.on('ready', createPyProc)

you see，i use app.on to start my backend, but how to restart my backend without restart eletron

**Comment by ss7424Refar** [comment]
I think the easy way to restart is to use `kill` command to kill the script process in unix ( or use `taskkill` in window).
and then rerun the script.

This event can be executed with a button or keypress.

**Comment by m986883511** [comment]
> I think the easy way to restart is to use `kill` command to kill the script process in unix ( or use `taskkill` in window).
> and then rerun the script.
> 
> This event can be executed with a button or keypress.

by this way, after rerun, the sub process is not under electron control.
atfer rerun, the new sub progress can not exit by **app.on('will-quit', exitPyProc)**

const createPyProc = () => {
  let script = path.join(__dirname, 'app.py')
  pyProc = require('child_process').spawn('python', [script])
  if (pyProc != null) {
    console.log('child process success')
  }
}

const exitPyProc = () => {
  pyProc.kill()
  console.log('child process exit')
  pyProc = null
}

app.on('ready', createPyProc)
app.on('will-quit', exitPyProc)

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
