### ISSUE TITLE
I should hit “Force Reload” in Electron to opening my app.

### ISSUE THREAD

**Issue by namrouche993** [electron/electron#25861]
When directly opening the app, it opens up as a white screen and I should hit 2 times "Force Reload" in View to opening the app.
SO I want a solution for that,
for example "force Reload", it will be done automatically and thank you !

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
