### ISSUE TITLE
Remote HTTPS expired certification cause Electron crash

### ISSUE THREAD

**Issue by Changdao** [electron/electron#25908]
### Issue Details

* **Electron Version:**
8.0.0
* **Operating System:**
Darwin liujd 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
* **Last Known Working Electron version:**

### Expected Behavior
//Because I forget to update my server https certificate, so it's expired.
import axios from 'axios';
return axios.post(url,...);

### Actual Behavior
Electron crash.

**Comment by ckerr** [comment]
## If No Repro Included

Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) to make a stand-alone app that reproduces this issue?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case (a [gist](https://gist.github.com) is preferred since gists can be loaded directly into [Electron Fiddle](https://www.electronjs.org/fiddle) for testing), please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

## If Repro Requires Third-Party Tooling

Thank you for taking the time to report this issue and helping to make Electron better.

Researching issues that depend on third-party code is usually not feasible for the Electron team due to the time that would be required to research reported issues with open-ended dependencies.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself without other code?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case (a [gist](https://gist.github.com) is preferred since gists can be loaded directly into [Electron Fiddle](https://www.electronjs.org/fiddle) for testing), please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) to make a stand-alone app that reproduces this issue?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case (a [gist](https://gist.github.com) is preferred since gists can be loaded directly into [Electron Fiddle](https://www.electronjs.org/fiddle) for testing), please link to it in a followup comment.

Thanks in advance! Your help is appreciated.
