### ISSUE TITLE
In the specified Mac version will always appear -- app.setBadgeCount is not working!

### ISSUE THREAD

**Issue by yyccQQu** [electron/electron#26057]
### Issue Details

* **Electron Version:**
  *  v7.3.3 ，v9.3.2
* **Operating System:**
  *  macOS 10.15.4 (19E287)
* **Last Known Working Electron version:**
  * don`t know

-- the code 
-- The comment method also doesn’t work
```
import {
  app
} from "electron";

mainWindow.on('blur', () => {
    if (process.platform === 'darwin') {
      app.dock.setBadge('5');
      app.setBadgeCount(5);
      // const badgeString = app.dock.getBadge();
      // console.log(badgeString,'badgeString')

      // if (badgeString === '') {
      //   app.dock.setBadge('1');
      //   console.log(badgeString,'2333badgeString')
      // } else {
      //   app.dock.setBadge((parseInt(badgeString) + 1).toString());
      // }
    }
}

```
### Expected Behavior

![1](https://user-images.githubusercontent.com/32674176/96297000-42ffbc80-1001-11eb-8828-435f19b85ade.png)

### Else

Tested two versions of electron, found the problem is the same, it may be related to the MAC version. The development environment will not show the effect, but after packaging, the effect is good ~

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
