### ISSUE TITLE
focus is triggered on drag and drop events

### ISSUE THREAD

**Issue by MMcKester** [electron/electron#26073]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Issue Details

* **Electron Version:**
   10.1.4
* **Operating System:**
  * Windows 10 (1909) and macOS 10.15

### Expected Behavior
 On Windows and macOS the fired events should be the same.

### Actual Behavior
On Windows the `focus` event is triggered, whereas it is not on macOS.

### To Reproduce
Check out ElectronFiddle with: https://gist.github.com/74e543257eb15c19408d52622036582b (**only** addition is in renderer.js)

Drag a folder onto the Browser Window. On Windows you get a focus event as well, this is missing on macOS.

**Comment by ckerr** [comment]
Thanks for reaching out!

Please fill out the template when filing new issues and pull requests. This is necessary so that we can be certain we have all the information we need to address your submission efficiently and correctly -- for example, in this issue I have no idea which version of Electron I should test with to try to reproduce the issue you're seeing.

In addition, would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself without other code?

Thanks for understanding and meeting us half way :grinning:

**Comment by Githubber2021** [comment]
Sure, sorry for the inconvenience. I updated my original report
