### ISSUE TITLE
Transparent windows aren't maximizable!

### ISSUE THREAD

**Issue by adel-sbeh** [electron/electron#26076]
When creating a transparent window, the code of the max button gets broken:
```
var closeWin_, minWin_, maxWin_;
(function () {
  const remote = electron.remote;
  var window = remote.getCurrentWindow(), isMax = true;
  window.on('maximize', () => {
    isMax = true;
  });
  window.on('unmaximize', () => {
    isMax = false;
  });
  closeWin_ = function(){
    if(!_shouldWait){
      window.close();
    }else{
      _content.send("enderframework--willclose");
    }
    loop____ = setInterval(function(){
      if(!_shouldWait){
        clearInterval(loop____);
        window.close();
      }
    }, 5);
  };
  minWin_ = function(){
    window.minimize();
  };
  maxWin_ = function(){
    (isMax) ? (function(){
      document.documentElement.setAttribute("window-is-minimized", "");
      window.unmaximize();
    })() : (function(){
      document.documentElement.removeAttribute("window-is-minimized");
      window.maximize();
    })();
  };
  function init(){
    document.getElementById("_minWin").addEventListener("click", minWin_, true);
    document.getElementById("_maxWin").addEventListener("click", maxWin_, true);
    document.getElementById("_closeWin").addEventListener("click", closeWin_, true);
    document.getElementById("_exitFullscreen").addEventListener("click", function(){
      _content.executeJavaScript("document.exitFullscreen();");
    }, true);
    document.getElementById("_topBar").style.display = "block";
  }; 
  document.onreadystatechange = function (){
    if(document.readyState == "complete"){
      init(); 
    }
  };
})();
```

**Comment by ckerr** [comment]
@adel-sbeh, thanks for reaching out and for providing a partial repro.

It looks like this repro case is only partially complete and e.g. needs the corresponding html in order to be run and tested. Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) to make a stand-alone app that reproduces this issue?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

In addition, could you please provide the information requested in the issue template? For example, you didn't mention what platform and Electron version you're experiencing the issue on. Without this information, the maintainers would have to just guess.

Thanks for your understanding and for meeting us halfway on this!

**Comment by adel-sbeh** [comment]
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    [...]
  </head>
  <body window-background>
    <div id="_topBar" class="topBar" style="display: none;" hideInFullscreen><!-- This is the top bar -->
      <img id="_icon" class="topBar--icon _img" style="display: none;">
      <div id="_title" class="topBar--title" style="display: inline-block;"></div>
      <div id="_menu2" style="display: none;"></div>
      <div id="_windowControls">
        <div id="_closeWin" class="topBar--close click_">×</div>
        <div id="_maxWin" name="hideOnSub" class="topBar--max click">▢</div><!-- This is the button that stops functioning when I set the window to transparent-->
        <div id="_exitFullscreen" class="topBar--fullscreen click" style="display: none;">↗</div>
        <div id="_minWin" name="hideOnSub" class="topBar--min click">-</div>
      </div>
    </div>
    <webview id="_contentView" hideInFullscreen style="display: none;"></webview>
  </body>
</html>
```

**Comment by adel-sbeh** [comment]
https://gofile.io/d/6JlyOh

**Comment by ckerr** [comment]
@adel-sbeh thank you for the video!

What version of Electron are you using, and what version of Windows are you using it on?

**Comment by adel-sbeh** [comment]
Electron 10.1.3, and the 20H2 windows update.

**Comment by mlaurencin** [comment]
Hi @adel-sbeh [this PR](https://github.com/electron/electron/pull/28207) may have fixed your issue. Can you try upgrading to either version 11.4.3 or 12.0.3 and see if your transparent window is maximizing for you now?

**Comment by adel-sbeh** [comment]
It looks like #27851 has been closed, so I think that it's safe to assume that the current issue has been resolved. I'mma close this now.
