### ISSUE TITLE
axios in renderer will lost request body

### ISSUE THREAD

**Issue by klwfwdk** [electron/electron#26075]
I fond the solution by using fetch().Is there a similar solution that can be used for axios?

@anatoly314 This is a fundamental limitation of XMLHttpRequest: it [only sends upload bodies to http/https](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/xmlhttprequest/xml_http_request.cc;l=800;drc=df1adb1e58a995deb240cdc86e2b2bd9d65cb433). (see [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/weborigin/kurl.cc;l=820-828;drc=db82e0f37eb06d73ed1b62b6367555ee0e82005f) for the definition of `ProtocolIsInHTTPFamily`.)

`fetch()` does not have this problem, if you register your protocol as supporting Fetch. I've modified your example to show how: https://gist.github.com/e8f8f2322c5452d941a4fcc05f063942

_Originally posted by @nornagon in https://github.com/electron/electron/issues/17531#issuecomment-700952791_

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
