### ISSUE TITLE
localStorage causes memory allocation in separate renderer that is never gc'd

### ISSUE THREAD

**Issue by bowswung** [electron/electron#26124]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
When repeatedly setting an item with the same key in localStorage I expect consistent memory usage inside the renderer processes.

### Actual Behavior
Memory usage of the renderer process increases with every `setItem`. In the renderer that makes the call this seems to be less of an issue, because at some point gc will be invoked. But in other renderers that are not actively running code no gc call is triggered and therefore memory usage rises until the system runs out of memory.

### To Reproduce
I haven't been able to replicate this with electron fiddle yet. It is possible that some configuration specific to our project setup is causing this, but I wanted to document the behaviour in this issue as a starting point.

**Comment by BugBugStar** [comment]
I meet this problem, too. The Electron version I am using is 10.1.6. And my OS is WIndow 10, too.
I can reproduce this issue in VSCode (becasue VSCode is built from electron).

1. Open VSCode with a directory.
2. Open another VSCode window to make sure there are two render process in the Task Manager.
3. Open the Devtool in the 1st VSCode Window, and execute this script in console:
```
let i = 0; let interval = setInterval(() => {
    localStorage.setItem("keySet", `${i++}`.repeat(1024 * 1024));
}, 1000);
```
4. Then observe the 2nd render process in the Task Manager.

Expected Behavior
Memory usage of every renderer processes should not increase continuously.

Actual Behavior
Memory usage of every renderer processes increase continuously until the Memory Occupancy Rate shows in the Task Manager grows to 98%.
