### ISSUE TITLE
Windows are glitching when they are being resized!

### ISSUE THREAD

**Issue by adel-sbeh** [electron/electron#26161]
Windows are starting to glitch when they are being resized. But these glitches can't be recorded. This glitch started to happen when I installed the latest version of Windows 10 (20H2). *You can reproduce this bug by resizing the window of WhatsApp Web.*

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks for understanding and meeting us half way 😀

**Comment by adel-sbeh** [comment]
I think that this issue isn't just linked to Electron apps. Zoom started to glitch in a similar. So I guess that this issue should get closed.
