### ISSUE TITLE
After the background of the window is set to transparent by electron, the window will be minimized and the hidden display window will flicker

### ISSUE THREAD

**Issue by livelyPeng** [electron/electron#26163]
After the background of the window is set to transparent by electron, the window will be minimized and the hidden display window will flicker

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by ckerr** [comment]
Superseded by https://github.com/electron/electron/issues/26179
