### ISSUE TITLE
 After the background of the window is set to transparent by electron, the window will be minimized and the hidden display window will flicker

### ISSUE THREAD

**Issue by livelyPeng** [electron/electron#26179]
### Issue Details

* **Electron Version:**
 "electron": "^10.1.3",
  "electron-builder": "^22.8.1",
  "electron-devtools-installer": "^3.1.1",

### Expected Behavior
 After the background of the window is set to transparent by electron, the window will be minimized and the hidden display window will flicker

### Actual Behavior
 After the background of the window is set to transparent by electron, the window will be minimized and the hidden display window will flicker

### To Reproduce
no

**Comment by amazingmarvin** [comment]
I'm also having trouble with transparent windows since upgrading to 10.1.3 (still broken in 10.1.5). Possibly the same bug.

MacOS (the mentions input moved and got smaller, but there's still a transparent outline from where it was):
<img width="589" alt="image" src="https://user-images.githubusercontent.com/35364886/97435805-3cd2df80-1921-11eb-99e5-905f2be6314a.png">


Linux (window is black instead of transparent):
<img width="651" alt="image" src="https://user-images.githubusercontent.com/35364886/97428497-54f13180-1916-11eb-8f22-420d96b8cd0c.png">

Windows, on the other hand, looks normal.

**Comment by livelyPeng** [comment]
yes, I think this problem exists in electron itself
