### ISSUE TITLE
app.requestSingleInstanceLock gives rise to unnecessary resource use

### ISSUE THREAD

**Issue by ruppysuppy** [electron/electron#26219]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * Windows 10 Build 18362

### Expected Behavior
Using app.requestSingleInstanceLock should not use such a huge amount of CPU and when its released, the process should terminate

### Actual Behavior
On using app.requestSingleInstanceLock a huge amount of CPU is used when 2nd or 3rd instance is opened and app.releaseSingleInstanceLock doesn't release it.

### To Reproduce
[Example](https://github.com/ruppysuppy/UnHook/tree/98a6b9c667a9fb4789b30251faad67a482142860) without issue
[Example](https://github.com/ruppysuppy/UnHook/tree/6f61090d251d7bdfee3292a4c8eae4928704f86c) with issue

The steps to setup the project is given in the readme, with one additional step after cloning:
* Use `git reset --soft 98a6b9c667a9fb4789b30251faad67a482142860` to check the version without the issue

To **go back** to the version with the issue:
* Use `git reset --soft 6f61090d251d7bdfee3292a4c8eae4928704f86c`

### Demo
No Single Instance Lock (example without issue)

![Issue Absent](https://user-images.githubusercontent.com/44058757/97391303-ed7eb600-1904-11eb-9bdb-f162a04b5fd2.gif)

Single Instance Lock (example with issue)

![Issue Present](https://user-images.githubusercontent.com/44058757/97391338-06876700-1905-11eb-846c-dcad3bc2cbe8.gif)

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging another project's code is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ruppysuppy** [comment]
Sorry, even after several attempts, I could not recreate the bug, but I found where its occurring. It takes place only when [this](https://github.com/ruppysuppy/UnHook/blob/6f61090d251d7bdfee3292a4c8eae4928704f86c/app/AppTray.js#L41) line is replaced by:
```javascript
click: () => {
    app.releaseSingleInstanceLock()
    app.quit()
}
```

I did make a similar [gist](https://gist.github.com/ruppysuppy/884143ae91a24914f4c4c0fd9fbc03ee), but its working as expected (without bug)

**Comment by ruppysuppy** [comment]
@ckerr I am closing this issue. I will re-open it when I am able to create a stand-alone test

**Comment by PeterZdravkov** [comment]
Hi, did you manage to solve your issue? I am running into the exact same problem. 

For my application, I don't want it to ever be closed so i just hide the window instead of closing it. The users only option to reopen it is to run the program again to restore it and that is working perfectly, however, as you described that has the side effect of creating additional processes that eat up CPU resources. I don't have the time to recreate the issue as suggested so I was wondering if you came up with a solution?

All I can think of currently is that app.quit() still allows electron processes to be created and doesn't terminate them cleanly.

> Keep in mind here that app.quit() doesn't terminate immediately, so if you have code afterwards it will still run.

This is a comment from StackOverflow. Hopefully it is the cause of the issue as that should be simple to fix. If not who knows.

If I come up with a solution I will update for other people to find.

**Comment by ruppysuppy** [comment]
@PeterZdravkov Thanks a lot! It solved the resource leak issue

**Comment by ruppysuppy** [comment]
@ckerr should I update the corresponding documentation? This helps us avoid the resource leak.

Previously:
```
const { app } = require('electron')
let myWindow = null

const gotTheLock = app.requestSingleInstanceLock()

if (!gotTheLock) {
  app.quit()
} else {
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    // Someone tried to run a second instance, we should focus our window.
    if (myWindow) {
      if (myWindow.isMinimized()) myWindow.restore()
      myWindow.focus()
    }
  })

  // Create myWindow, load the rest of the app, etc...
  app.whenReady().then(() => {
    myWindow = createWindow()
  })
}
```

Suggested doc:
```
const { app } = require('electron')
let myWindow = null

const gotTheLock = app.requestSingleInstanceLock()

app.on('second-instance', (event, commandLine, workingDirectory) => {
  // Someone tried to run a second instance, we should focus our window.
  if (myWindow) {
    if (myWindow.isMinimized()) myWindow.restore()
    myWindow.focus()
  }
})

// Create myWindow, load the rest of the app, etc...
app.whenReady().then(() => {
  if (!gotTheLock) {
    app.quit()
    return
  }
  myWindow = createWindow()
})
```
