### ISSUE TITLE
An internal error has occurred: FirebaseError: [code=invalid-argument]: Property value contains an invalid nested entity.

### ISSUE THREAD

**Issue by apocoloco** [electron/electron#26215]
I keep on getting this error and can't find the reason why

Could anyone give me a solution? Keeps on constantly popping up as I scroll through the PDF 

ty

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
