### ISSUE TITLE
electron build error

### ISSUE THREAD

**Issue by lixm1988** [electron/electron#26218]
I have got a mistake when I was building electron source of version 6.1.12.The error infomation just like this 
![无标题](https://user-images.githubusercontent.com/24401006/97384474-bad7bc00-190a-11eb-89fc-9801eef8c50b.png)

All my operation is the same as [https://github.com/electron/electron/blob/v6.1.12/docs/development/build-instructions-gn.md](https://github.com/electron/electron/blob/v6.1.12/docs/development/build-instructions-gn.md).How could I reserve this problem?

**Comment by ckerr** [comment]
Thank you for reaching out!

I have four thoughts on this:

* My first guess is that it's a hiccup in the network. Maybe wait a few hours and see if it resolves itself.

* In the interim since 6.1.12 we've released [Electron build-tools](https://github.com/electron/build-tools) which has scripts to do a lot of the work discussed in those build instructions. You may find the codebase easier to wrangle when using build-tools.

* The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions). You may want to consider using a newer version of Electron.

* Also, the issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
