### ISSUE TITLE
Memory Free Bug

### ISSUE THREAD

**Issue by liudianwei** [electron/electron#26312]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Screenshots

![image](https://user-images.githubusercontent.com/28178193/97973886-be36e000-1e01-11eb-9fcd-93c0d55a42f9.png)
![image](https://user-images.githubusercontent.com/28178193/97973898-c2fb9400-1e01-11eb-9a58-ea50d867352e.png)
![image](https://user-images.githubusercontent.com/28178193/97973920-cbec6580-1e01-11eb-9c4f-07fb865ce21f.png)

### Additional Information

```

<html>
<body>
<script>
function repeat(arg2) {
  function repeatFun(arg1) {
    if (typeof arg1 === "string") {
      var whileTrueFun = function () {
        while (true) {}
      };
      return whileTrueFun();
    } else {
      if (
        ("" + arg1 / arg1)["length"] !== 0x1 ||
        arg1 % 0x14 === 0x0
      ) {
        debugger;
      } else {
        debugger;
      }
    }
    repeatFun(++arg1);
  }
  try {
    if (arg2) {
      return repeatFun;
    } else {
      repeatFun(0x0);
    }
  } catch (_0x1f872d) {}
}
setInterval(()=>{repeat()},10)
</script>
13212131321
</body>
<html>
```

electron load page like this , And no one was operating ,  After a while , the render process will throw stack over flow exception, but the chrome do not,.

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information. For example, I would have to guess which version of Electron to test with to try and reproduce this issue.

Also, would it be possible for you to make a standalone testcase with _only_ the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use. The code snippet you have here appears to be pseudocode, e.g. the `debugger;` lines and has nonintuitive code e.g. `   ("" + arg1 / arg1)["length"] !== 0x1 || arg1 % 0x14 === 0x0`. Are these pieces necessary in order to reproduce the bug, or are they extraneous?

**Comment by liudianwei** [comment]
> correctly

thanks for reply at first , sir.  I think these pieces are extraneous,  just use electron load above html, and after a while , it will throw the exception

**Comment by liudianwei** [comment]
> Thanks for reaching out!
> 
> Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information. For example, I would have to guess which version of Electron to test with to try and reproduce this issue.
> 
> Also, would it be possible for you to make a standalone testcase with _only_ the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use. The code snippet you have here appears to be pseudocode, e.g. the `debugger;` lines and has nonintuitive code e.g. ` ("" + arg1 / arg1)["length"] !== 0x1 || arg1 % 0x14 === 0x0`. Are these pieces necessary in order to reproduce the bug, or are they extraneous?

thanks for reply at first , sir. I think these pieces are extraneous, just use electron load above html, and after a while , it will throw the exception
