### ISSUE TITLE
Is there a way to show context menu in Webview when  right button is clicked? 

### ISSUE THREAD

**Issue by MashukeAlam** [electron/electron#26374]
I made this browser using _electron_. _**Not a good programmer by any means but what i did essentially is to insert a new webview for every new tab.**_ Now I want to implement the context menu for this. I need few menu items (Open in new tab, copy link, save image).

This the container for all divs:
```
<div id="tabs" class="tabs">
  </div>
```
This is createTabs function creating webview and injecting them into div:
```
const createTabs = (url, callback) => {
    const tabs = id('tabs');
    const selector = id('selector');
    tabs.innerHTML += `<webview id='tabs_${TAB_COUNT}' src="${url}" style="display: inline-flex !important; position: fixed; top: 54px;width: 100%;height: 100%;"></webview>
`;
selector.innerHTML += `<div onclick='surfaceTab(${TAB_COUNT})' class='indi_tab' id='selector_${TAB_COUNT}'><p class='noselect'></p><img height='10px' width='10px' onclick='closeTab(${TAB_COUNT})' src='./close.png'></div>`;

TAB_COUNT++;

callback(TAB_COUNT-1);


  }
 ```

This is the callback for createTabs:
It's actually giving me the title of the page to show on bar. 

```
  const processTabs = (number) => {
    const this_tab = id(`tabs_${number}`);
const this_selector = id(`selector_${number}`);
console.log(this_tab);
this_tab.addEventListener('did-stop-loading', () => {
let title = "";
  setTimeout(() => {
     title = this_tab.getTitle();
     console.log(title);
  this_selector.firstElementChild.innerHTML = title;
  if(!MASTER_RECORD.includes(number)) {
    MASTER_RECORD.push(number);

  }
  }, 2000);
  makeSearchBarCorrect(number);
});

 } 
```

For full code please check the repo:[Github]( https://github.com/MashukeAlam/Surf) 

For demo: [YouTube](https://youtu.be/ZagrPAWRUo4) 

Thanks. 💜💚💙

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
