### ISSUE TITLE
How to allow app access to images outside the app.asar file?

### ISSUE THREAD

**Issue by newalphamedia** [electron/electron#26446]
The electron app I'm building bundles the resources into win-unpacked/resources/app.asar.

In the app itself, I allow users to custom write in paths to image files. For example, "image/my-own-img.png".

This works fine to add `<img src="images/default-image.png" />` in the app and allow the user to change the src to "image/my-own-image.png" to display that one instead.

However, the goal is to allow users to add their own images to the relative "images" folder, which would unfortunately be inside of the app.asar file. I've attempted to allow access outside this path, but I run into security issues and frankly have not been able to get that to work.

Aside from disabling asar, is there a way I could allow users to:
a) Install the app
b) Copy/paste their images into an images folder in the apps installed path somewhere
c) Have the app display that image when the relative path is typed in?

Thank you.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
