### ISSUE TITLE
Electron window not starting!

### ISSUE THREAD

**Issue by Pranay144** [electron/electron#26451]
I am trying to run electron application but the gui is not starting.
i executed the commands in order i.e. 
npm init
npm i --save-dev electron
npm start

But gui window isn't showing.
I am using windows 10 home. I tried running electron in windows terminal as well as wsl (ubuntu), but its the same, no window showing

**Comment by Anil8753** [comment]
Yes, where is the application UI in your case? Better start with starter template.

# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install && npm start

**Comment by Pranay144** [comment]
I am just starting out...so I'm using the template provided on official website.

is it the version problem?
I'm using electron@10.1.5 and npm 6.14.8!

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
