### ISSUE TITLE
Windows app sometimes leaves a process hanging arround after closing.

### ISSUE THREAD

**Issue by ee11131** [electron/electron#26463]
Hi,

Sometimes, when I closed my packaged app on windows, a process of said app still appears on the task manager. This does not happen often, but it is a big issue when it does.

I have searched online and tried solutions such as:
`mainWindow.on('closed', () => {
     mainWindow = null
 })`

`app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') app.quit()
})`

Unfortunately, none of this solutions seem to work. I have logged both events above, and they are triggered.

I am using electron 10.1.5 and Windows 10.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
