### ISSUE TITLE
before-input-event

### ISSUE THREAD

**Issue by tony2016-0608** [electron/electron#26479]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * windows10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Before-input-event listens for this event, and I want each of the two functions to keep their own behavior, to pop up a window when I type on a page, and to type characters when I type in an iframe
Don't interfere with each other

### Actual Behavior
Before-input-event listening for this event, I need to capture the keyboard input event, and when I capture the input it pops up a window, which works really well,
But I have an iframe on my render page that's embedded in a web page, and there's an input field on the page, and when I type in a character, it opens the window of the window.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by updaterupdater** [comment]
[test gist](https://gist.github.com/1e54cc72f6e460c4e7d04de6c17a6b28)



I set up a global keyboard monitoring event. In the test sample, an iframe is created. An external webpage is linked in the iframe, and there is an input box in the external webpage.
Whenever I type text into the input box, keyboard input events are captured by global keyboard monitoring events, not by external web pages.
How can I modify my code so that external web pages can capture keyboard input events?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
