### ISSUE TITLE
Switch languages in the electron docs website

### ISSUE THREAD

**Issue by dragonDScript** [electron/electron#26489]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
My problem is that my native language's docs is very bad, with stuff in english and translated using google translate.
This is ok (after all this is a little oss), but I prefer the English option.

### Proposed Solution
Ability to switch between langs ( I can make a PR, but I need some discussion here & approvement )

### Alternatives Considered
-

### Additional Information
-

**Comment by ckerr** [comment]
Thanks for reaching out!

I think this issue should be reported in the website's repo at https://github.com/electron/electronjs.org/issues. Since the `electron/electron` issue tracker is used for issues/features in the Electron codebase itself, I'm going to close this copy of the issue. Please feel free to re-open it as a new issue in the electronjs.org repo. Thanks!
