### ISSUE TITLE
A weird scrolling bug!

### ISSUE THREAD

**Issue by adel-sbeh** [electron/electron#26486]
You can reproduce this bug by using a trackpad to scroll up on windows, then scrolling down using a mouse wheel on windows 10.
https://youtu.be/qHlwIRf9hy8
```js
app.commandLine.appendSwitch('--enable-features', 'OverlayScrollbar, ElasticOverscrollWin');
```
**+** ***The elastic overscroll thingy isn't working, and it might be the thing causing this problem.***

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by SvenAERTS228** [comment]
I've just left a recorded demo via de "?" feedback tool. It shows how the scrolling up and down doesn't work using the arrows on my screen. :) Thy and greetings from Brussels :)

**Comment by adel-sbeh** [comment]
This is a general issue in *Chromium* on *Windows*. I was able to recreate this behavior in *Electron* and *Google Chrome*.
