### ISSUE TITLE
White screen when i wait 10 second

### ISSUE THREAD

**Issue by Evgenie3311** [electron/electron#26536]
### Issue Details

* **Operating System:**
  * Windows 8.1 for one language Buid 9600 -->

### Screenshots
https://user-images.githubusercontent.com/71527364/99429017-78f1d280-2918-11eb-89bf-08db5ee06400.png

### Additional Information
 Reload not helping

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
