### ISSUE TITLE
Programmatic highlight fills primary selection

### ISSUE THREAD

**Issue by LinAGKar** [electron/electron#26563]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * OpenSUSE Tumbleweed

### To Reproduce

On Linux:

- Highlight something with the mouse, to put it into primary selection
- Put the cursor on a word in vscode
- Press ctrl+f
- This word the cursor is in will automatically be filled into the search box. However, when it does this, it also puts this word into primary selection, replacing whatever was there previously.
- If you then press enter to search, the primary selection will get filled with the search result

I reported this at https://github.com/microsoft/vscode/issues/86645, and there they stated that this is an upstream issue, and I do get the same behavior in Atom, so it seems like it might be. When something is programmatically selected, it is entered into primary selection, which should only be done when the user selects something.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Jaypers** [comment]
This has been raised numerous times as an issue in VSCode:
https://github.com/microsoft/vscode/issues/86645
https://github.com/microsoft/vscode/issues/130208
https://github.com/microsoft/vscode/issues/197495
https://github.com/microsoft/vscode/issues/261170

**Comment by Jaypers** [comment]
This is still a problem on Electron: 37.2.3

**Comment by cate02** [comment]
I'm having this problem with CachyOS KDE Wayland
**I believe this happens when an electron app is running with X11.**
I've vibe coded this basic gist: https://gist.github.com/cate02/fbcd7de9f455719729aa7431ab382e42
For me, the gist when run with `electron .` works fine, no bug, because it's wayland not x11.
When I select (drag mouse over) text, it will paste when i hit Ctrl+V etc, although this copied selected text does not appear in my Linux clipbaord contents gui.
This happens in electron: discord, vsc, obsidian, brave all have this issue.
Though it doesn't happen in other apps like Chromium or Kwrite.
**I run electron apps with the --ozone-platform=x11 --url -- %u command line arguments so they work in X11 so when I drag the window to my 75% scale monitor it will work normally without getting buggered.**
Just now, I realised that if I remove this x11 argument from discord, then discord no longer has this copy on select bug. But that's not a solution because electron doesn't support fractional scaling? And disabling fractional scaling also is no solution because having mis matching multi monitors of different resolution and size is janky without fractional scaling.

Pretty please fix this asap  because it is so infuriating. It makes no sense, when I noticed the bug it took me forever to realise it was (seemingly) electron's fault. A major pain point this bug creates is with coding where often you select text you're going to write or paste over.
Very very sad that this problem has been around for 5+ years :(

edit, fyi, chatgpt thought this command `kwriteconfig6 --file kwinrc --group Wayland --key EnablePrimarySelection false` would fix it, so I tried it but it didn't change anything.

**Comment by Jaypers** [comment]
I think someone will need to reopen this issue for it to get any attention.
