### ISSUE TITLE
print dosen't work when integrating flash plugin

### ISSUE THREAD

**Issue by littlewhaleoo** [electron/electron#26584]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
we integrate pepperflash to support flex app, everything is OK except the print functionality, the print dialog doesn't show when we use `flash.printing.PrintJob` lib `_printJob.send()` as below, which works fine in chrome
```
private var _printJob:PrintJob = new PrintJob();
if(_printJob.start()) { 
    try {
        _printJob.addPage(_sp,new Rectangle(0,0,_sp.width,_sp.height),_printOptions);
    } catch(e:Error) {
        trace(e.toString());
    }
    _printJob.send(); 
}

```
that is very important for us and  sadly we don't have the ability to fix it.  I try to contact with info@electronjs.org. no reponse get.  so can you help us ? we are glad to donate for the team, 1366185724@qq.com

* **Electron Version:**
  9.3.4
* **Operating System:**
 windows7/10 mac
* **Last Known Working Electron version:**
  *

**Comment by nornagon** [comment]
FYI, Flash is EOL and not supported beginning with Electron 12.

**Comment by littlewhaleoo** [comment]
> FYI, Flash is EOL and not supported beginning with Electron 12.

thanks! due to some history reasons, flash is the only choice for us.

**Comment by ckerr** [comment]
It's very unlikely. Since Adobe [announced in 2017](https://blog.adobe.com/en/publish/2017/07/25/adobe-flash-update.html) that it will stop releasing updates for Flash at the end of 2020, continuing to support it in Electron would only expose our users to future security risks.

You should strongly consider migrating away from Flash.

**Comment by FrankWangZY** [comment]
> FYI, Flash is EOL and not supported beginning with Electron 12.

that is because  Chromium doesn't support flash any more?  

does it mean  
```
 app.commandLine.appendSwitch('ppapi-flash-path', plugin);
```
will not work in Electron 12? 
or 
it still work as before,   but electron team will not solve any issue about flash?
Hope flash still works in the future,   because some people need both new electron version and support  flash.

**Comment by frankieta** [comment]
> 
> 
> > FYI, Flash is EOL and not supported beginning with Electron 12.
> 
> that is because Chromium doesn't support flash any more?
> 
> does it mean
> 
> ```
>  app.commandLine.appendSwitch('ppapi-flash-path', plugin);
> ```
> 
> will not work in Electron 12?
> or
> it still work as before, but electron team will not solve any issue about flash?
> Hope flash can be integrated in electron 12, because some people need both new electron version and support flash.

Mind that the last version of the flash plugin will not load flash content, even if embedded in an Electron project after 12 January 2021.
