### ISSUE TITLE
NSPanel working on big Sur

### ISSUE THREAD

**Issue by castroCrea** [electron/electron#26596]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.

### Problem Description

Electron doesn't have a propers solution for NSPanel Window on Big Sur.

#### External Libs doesn't work anymore
I was using 
https://github.com/goabstract/electron-panel-window
And I tried 
github.com/mznet/electron-nspanel
https://github.com/syed-umair/electron-window-nspanel#readme

But nothing work on Bis Sur anymore
##### It crash with 
![image](https://user-images.githubusercontent.com/20707343/99651609-20751f00-2a57-11eb-997e-e1532e21468a.png)

#### Native solution doens't work with multiple window apps
And  alwaysOnTop: true, that can simulate a Panel window is not a solution for multiple window apps.

##### Why
* when win.hide the alwaysOnTop window, other windows are popping up in front most (you can still found an ugly workaround, that hide the dock when alwaysOnTop window and the show it when it's hide again, but It is not clean at all)
* Also there is still this problem of app.dock that is hide by default if one of the window has  alwaysOnTop: true

### Proposed Solution
* Dev a Panel window that extend Browser window and that is created with NSPanel https://developer.apple.com/documentation/appkit/nspanel

* Or help to fix the lib https://github.com/goabstract/electron-panel-window

### Alternatives Considered
Can't find any at the moment

Need some help please 🙏

**Comment by castroCrea** [comment]
Hello @dsanders11 as an Electron expert do you have an idea ? 
 Thank's in advance

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by castroCrea** [comment]
Create a panelwindow in electron like a browserwindow is kind of a feature, isn't it ? @MarshallOfSound

**Comment by stefanoTron** [comment]
@MarshallOfSound any chance this could be reopened? To me this looks like a feature request :)
Could @codebytere or @ckerr chip in here too?

**Comment by proxi** [comment]
@MarshallOfSound @codebytere @ckerr Could we reopen this? This is a feature needed by many apps on macOS, and there's no good alternative to implementing it in Electron, because superclass cannot be swizzled (what `electron-panel-window` attempted was a major hack and could not work reliably).

I've sketched a PoC to see what it would take to support this natively: https://github.com/proxi/electron/pull/1/files The solution has these parts:
- (almost) verbatim copy `NativeWidgetMacNSWindow` as `NativeWidgetMacNSPanel`, replacing parent `NSWindow` by `NSPanel`
- (almost) verbatim copy of `ElectronNSWindow` to `ElectronNSPanel`, replacing parent `NativeWidgetMacNSWindow` by `NativeWidgetMacNSPanel`
- minor tweak to `ElectronNativeWidgetMac` to select the right class based on `BrowserWindow`'s `type` option.

Unfortunately the first part requires patching chromium :/

I've no experience developing electron, but if you think such a solution would eventually be accepted and someone could help I could wrap it up and PR it.
