### ISSUE TITLE
Web Cam not working.

### ISSUE THREAD

**Issue by diode02** [electron/electron#26647]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I am using electron to ship a app developed using React. For new customer user have option to upload picture or use webcam. Both of these are working perfectly in simple React app without Electron but when i run my app using electron then if i try to use webcam then nothing happen, webcam light not turn not into green and nothing happens. When i run this app as on chrome by NPM start without electron, chrome ask for camera permission and light turns into green and camera works. Tested both on Windows and Ubuntu.

In normal web app ask for camera permission and then shows camera result. but in electron i can not see any permission related to this.

* **Electron Version:**
  * 
v 10.1.5
* **Operating System:**
  * 
Ubuntu 20.0
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Web camera should be shown
### Actual Behavior

nothing shown
### Screenshots

![Screenshot from 2020-11-23 19-02-58](https://user-images.githubusercontent.com/46993679/99971095-8f87a600-2dbe-11eb-87b3-4f50037a28e8.png)

### Additional Information

no info

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by diode02** [comment]
kindly view the code at this repo
https://github.com/diode02/issue-webcam

**Comment by diode02** [comment]
when i run the app with electron, camera will not work. but when i run just express, it works fine

**Comment by diode02** [comment]
I changed  the webcam libraray which i was using in react to "react-html5-camera-photo"  which also works fine without Electron but when i try it with Electron i got permission error.
![Screenshot from 2020-11-29 17-24-48](https://user-images.githubusercontent.com/46993679/100541815-301b1180-3268-11eb-9bbb-266717abe480.png)
![Screenshot from 2020-11-29 17-24-45](https://user-images.githubusercontent.com/46993679/100541817-33160200-3268-11eb-9e5c-5a14164e6520.png)
