### ISSUE TITLE
How can users help prioritize features?

### ISSUE THREAD

**Issue by lacymorrow** [electron/electron#26664]
It does not seem like anyone is actively scoping or prioritizing tickets or bugfixes. How can users get bugs prioritized and actually worked on? 

This ticket was opened due to a regression in version 6 and has no visible work done. Now there are security vulnerabilities in the last-known working version which puts developers between a rock and a hard place. It's discouraging when no contributors have responded in over a year.
https://github.com/electron/electron/issues/20933

**Comment by jkleinsc** [comment]
Open source is largely volunteer-driven and collaborative. Because of this, time and energy to get things done are often the scarcest resources. We want Electron to be the best that it can be, but we also have to be realistic about what the team maintaining Electron can achieve. This means that:

* We might not have an ETA for when an issue will get investigated or fixed.
* Something you want implemented might not get implemented.
* A change you want merged might not get merged.
* Insisting on or making demands for any of the above is considered against [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)

For additional context, I'd read https://github.community/t/creators-contributors-and-collaborators/10219.

**Comment by ckerr** [comment]
As a rule we use this issue tracker only for feature requests or bug reports in Electron itself, so this issue should be closed. However IMO the question is worthwhile. We _do_ have more bugs than people to solve them. @lacymorrow could you re-open this at https://github.com/electron/governance/issues ?

A lot of the time, priorities are obvious because there are clear critical issues, or low-hanging fruit, or a maintainer fixes an issue because their employer needs that fix. (And anyone, including people at Twilio, are **[encouraged to participate](https://github.com/electron/governance/)** in that governance / maintenance.)

But there is also a backlog of items that slip through. It _would_ be good to have some way of hearing the vox populi to prioritize that backlog. Maybe that's something as simple as sorting issues by the number of :+1: emojis. There is probably a better way to do it that I haven't thought of.
