### ISSUE TITLE
OneDrive files getting locked after opening them using electron

### ISSUE THREAD

**Issue by v151** [electron/electron#26707]
* **Electron Version:**
  * 11.0.3
* **Operating System:**
  *  Windows 10 (1809) / Ubuntu 20.04 x64
* **Last Known Working Electron version:**
  * NA

### Expected Behavior
We want to launch OneDrive files (for example .docx) using electron seamlessly, should be able to delete them after launching.

### Actual Behavior
The file in OneDrive is getting locked after launching it with electron.

### To Reproduce

- Just open an OneDrive file with electron.
- Make some changes (Optional).
- Close the electron window.
- Try to delete the file from OneDrive.

### Screenshots & Fiddler captures
![image](https://user-images.githubusercontent.com/58203478/100358449-3917a300-301c-11eb-9a65-3693b95389c5.png)
[Fiddler_captures_for_Close.zip](https://github.com/electron/electron/files/5603477/Fiddler_captures_for_Close.zip)

Attached zip file contains fiddler captures for closing the file with chrome browser and closing the file with electron.

Thank you.

**Comment by Ramanujam1983** [comment]
I am also facing the same problem when I use electron as a browser to edit the files docx/ppt/xlsx in onedrive. After closing the browser, we cannot delete the file.

When I open the same one drive file with other browsers like Chromium, then after editing the file and closing the browser, we can delete it.

We want electron community to consider this as a priority because it is also hampering many browsers which are using electron as an browsers. 

I have also tried the following browsers and all browsers are having the same issue:
1) wexond -> https://github.com/wexond/desktop.git
2)  dot browser -> https://github.com/dothq/browser.git
3) electron-browser --> https://github.com/pfrazee/electron-browser.git

if you navigate to your one drive, edit the file, close the file and then navigate to onedrive to delete, you will not be able to delete.

We need your help to get this solved ASAP because its very common for a user to use the Cloud free storages very frequently.

**Comment by nornagon** [comment]
We cannot debug issues with 3rd-party services. Please provide a repro case that shows the issue in isolation.

**Comment by Ramanujam1983** [comment]
Thanks.

Every browser like FireFox, Chrome, Edge, Opera is working with onedrive. if I edit and close the files docx/ppt/xlsx with all these browsers and then I try to delete it then delete works correctly. 

The only browser where we are seeing the problem is electron based browsers. All the below mentioned GIT repo's which are based on electron browser are having problem.
wexond -> https://github.com/wexond/desktop.git
dot browser -> https://github.com/dothq/browser.git
electron-browser --> https://github.com/pfrazee/electron-browser.git

Please help us here.

Just navigate to Microsoft one drive through electron browser, edit the files, close the electron browser and then try to delete. You can see the issue. 
And perform the same operation with Chrome/FireFox/Edge, then there is no problem

Regards,
Ramanujam
