### ISSUE TITLE
**/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV

### ISSUE THREAD

**Issue by happyworker101** [electron/electron#26712]
Recently I tried to upgrade electron 11,  but encountered a difficult problem. When i run 'electron ./babel-register.js' to run dev and focus window, main process crashes with message:
**/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
error Command failed with exit code 1.

Node Version:
14.15.1
Electron Version:
11.0.3
Operating System:
mac big sur
Last Known Working Electron version:
9.3.5

i'm confused about this, can anyone give me a help? where should i start debug?

**Comment by VerteDinde** [comment]
Hey @happyworker101! It sounds like this may be an issue with your specific Electron set up. Because we use this issue tracker to track bugs within Electron itself, could you ask for some help in our Electron Discord instead? We have many community members and maintainers there, and multiple help channels where you would get a faster response.

Link to our Discord is here: https://discord.gg/electron

My username on the Discord is the same as my GitHub handle here, so if you don't get a response relatively quickly, feel free to tag me!

**Comment by darkguy2008** [comment]
> Hey @happyworker101! It sounds like this may be an issue with your specific Electron set up. Because we use this issue tracker to track bugs within Electron itself, could you ask for some help in our Electron Discord instead? We have many community members and maintainers there, and multiple help channels where you would get a faster response.
> 
> Link to our Discord is here: https://discord.gg/electron
> 
> My username on the Discord is the same as my GitHub handle here, so if you don't get a response relatively quickly, feel free to tag me!

Well I'm experiencing the same issue and I don't think a Discord link could've helped. If you had kept this discussion to the github issue I would've been able to at least get a hint. Discord is the most bloated piece of software I've ever used, so thanks.

**Comment by VerteDinde** [comment]
@darkguy2008 That's a fair point, and I'll leave a bit more information here in the interest of helping any folks that came from Google. 🙂 

If you're seeing this issue, there's a fair chance that this is not a problem with Electron itself, but with something specific that your app is doing. A few places that you could start looking:

1. Did you upgrade your app recently? Jumping from one version to a much more current version (we had one user try to upgrade from Electron 4 to Electron 13, for example) could have many breaking API changes that are less easy to catch. Try upgrading one version at a time and reviewing what changed in our breaking changes doc here: [https://www.electronjs.org/docs/breaking-changes](https://www.electronjs.org/docs/breaking-changes)
2. Do you use native modules that may need to be updated after an Electron upgrade or other dependency bump? Some of these include sharp, node-gyp, etc.
3. Do you have a crash reporter, where you can look at a more detailed stacktrace on where your app is crashing? You can set one up fairly quickly by adding the following snippet to your main process code, before `app.whenReady` :

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

I do also encourage people to come to our Discord if the above two steps don't help you. We have multiple help channels and volunteers ready to look at your code, and since this issue is app-specific, will let you debug in more detail. Some people don't like Discord, and that's fine! But that is where our extended community of help is right now 🙂 

Thanks for using Electron, and I hope this comment helped somewhat!

**Comment by pzrq** [comment]
In my case, the `crashReporter` code example above does work 🎉 

However it generated a 1.2MB `.dmp` file which does have some interesting text in it but is very hard to read (presumably without compiling a bunch of other tools, e.g. [this SO](https://stackoverflow.com/questions/49148977/analyzing-electron-crash-dumps) suggests [Google Breakpad](https://chromium.googlesource.com/breakpad/breakpad) looks promising, though at the moment it's in my too complicated basket). I did get this though when running my Electron app at a command line:

    [2] [0412/122829.333181:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)

Which led to a VSCode issue (but different to the `<redacted>.../Electron exited with signal SIGTRAP` I started with?): https://github.com/microsoft/vscode/issues/121451

Either way, I don't know for sure if it's the same information, though just using the macOS Console app seems far easier to read out of the box, in case you're a novice to debugging such a complicated area and stumble here like I did:
<img width="833" alt="Screen Shot 2022-04-12 at 12 37 58" src="https://user-images.githubusercontent.com/1217010/162868269-d162dfa8-ce59-4c63-a526-4eca91c68d54.png">
