### ISSUE TITLE
why maxHeaderSize of http in electron is 8K, but in  node environment the maxHeaderSize is 16K?

### ISSUE THREAD

**Issue by redabc** [electron/electron#26759]
Hi, Electron team:

we use electron V6.1.9

Recently we encountered a problem，when we use http in electron ,we console the maxHeaderSize of http lib ,the result is 8K, but we use in node environment ,the result is 16K;

in electron quick start project, we use like this:
 let httpLib = require('http');
 console.log(httpLib.maxHeaderSize);

the result is 8192

but when we use node cli the result is 16384;

more information 👍 https://nodejs.org/api/http.html#http_http_maxheadersize

So, could you please give us some suggestions,

Looking forward your soon feedback.

Thank you in advance.

**Comment by ckerr** [comment]
Hi @redabc, the answer is that Node jumped from 8K to 16K [in Node 13](https://github.com/nodejs/node/commit/bd9f4d295495b11d2e460b320681e18a11524bb8). Electron 12 is the first version of Electron to be based on Node 13, so if you run an Electron 12 beta you'll get the 16384 value.

A couple of side comments:

* You're probably aware of this already, but Electron 6 has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions). You should consider upgrading to a newer, supported version.

* You might be interested in [the new Electron Discord server](https://discord.com/invite/electron). Developers who write apps that use Electron are there answering each other's questions. This place might be a good resource for you!

Since this question has been resolved, and also since the development team uses the issue tracker only to track features and enhancement requests, I'm going to mark this issue as closed.

Thanks for reaching out! I hope this helps.
