### ISSUE TITLE
indexDb data deleting on electron autoupdate

### ISSUE THREAD

**Issue by yogimr007** [electron/electron#26758]
we have encountered a strange issue in our app. For some of our users the app data files were deleted when the electron app updated to a new version using autoupdater in electron.

We are not maintaining the index Db in our application root folder. But we do not know why this issue was occurred . please provide a solution to this as the users data is important for the application.

Note : path of the app is “C:\Users<User name> \ AppData\Local \ <Application name>”
path of the indexdb and other local storage files is “C:\Users\<User name>\AppData\Roaming\<Application Name>\IndexedDB”

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by knubie** [comment]
I don't have a cause / solution, but just chiming in to say this has happened to me as well.
