### ISSUE TITLE
Feature request: way to get the user-facing name of a Display

### ISSUE THREAD

**Issue by jameshfisher** [electron/electron#26796]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
In my application, I would like to show the user a list of their displays, so that they can choose which display to show a window on. Each item in the list should have a name they recognize, e.g. "BenQ 27" PnP monitor".

I am using [`screen.getAllDisplays()`](https://www.electronjs.org/docs/api/screen#screengetalldisplays) to populate the list. However, [the `Display` structure](https://www.electronjs.org/docs/api/structures/display) does not have a `.name` property or similar to show to the user.

### Proposed Solution
I know common OS APIs provide a name, e.g.:

* [The `MONITORINFOEXW` structure on Windows](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-monitorinfoexw) 
* [`NSScreen.localizedName` on macOS](https://developer.apple.com/documentation/appkit/nsscreen/3228043-localizedname)

However, it looks like Electron relies on Chromium for `getAllDisplays`, and it looks like Chromium does not capture this information. So I suppose I am proposing either patching Chromium's implementation, or providing a helper API like `Display.getName()` which calls the OS API.

### Alternatives Considered

* Just show an index: "Display 1", "Display 2", etc. Uninformative, but it's what I'm currently doing.
* List the displays along with their resolution. OK but not ideal. I'm also listing this to help the user.
* Just show the numeric id: "Display 2779098405", etc. Uninformative and ugly.
* A custom UI showing the virtual screen, with clickable displays in their relative positions. OK but significant work and taking up a lot of UI space.

**Comment by codebytere** [comment]
Having looked into this before - the issue is less a technical one and more a cost-benefit analysis of patching Chromium to accomplish this goal since as you note we inherit this object directly [from upstream](https://source.chromium.org/chromium/chromium/src/+/master:ui/display/display.h). Generally speaking, we are loathe to take on patches that we would potentially have to float indefinitely, since our goal is to keep our patchset scoped to those patches which 1) we can either upstream and eventually remove or 2) Which are critical to Electron to such a degree that we are more willing to take on the maintenance burden for. 1) is unlikely, as Chromium tends to refuse upstream CLs which they themselves do not use, and 2) does not apply here. So - as of now, I'm going to say that this is not something it's likely we'd add in the short term, _but_ you are not necessarily out of luck. The way that this is done is fairly amenable to a userland native Node.js module. For example, the display `id` on macOS corresponds to the `NSScreenNumber` of the screen - so for example you could in a native module do something like:

```objc
std::string DisplayNameForScreenID(int64_t id) {
  NSArray<NSScreen*> *screens = [NSScreen screens];

  for (int i = 0; i < [screens count]; i++) {
    NSScreen *screen = [screens objectAtIndex:i];
    CGDirectDisplayID display_id = [[[screen deviceDescription]
      objectForKey:@"NSScreenNumber"] unsignedIntValue];
    if (id === display_id) {
      return std::string([[screen localizedName] UTF8String]);
    }
  }

  return "";
}
```

and then pass the display id to it from Chromium's display object to get the name.

**Comment by jameshfisher** [comment]
@codebytere thanks for the extensive reply! I think `wontfix` is reasonable on that basis. For now I'll stick with my low-effort approach of just showing the resolution - but your example is a very useful pointer 🙂
