### ISSUE TITLE
why all module of electron is undefined

### ISSUE THREAD

**Issue by redabc** [electron/electron#26797]
Hi, Electron team:

we use electron V11.0.3

Recently we encountered a problem，when we require  app of electron like following, the result is undefined, it also undefined event if we use the demo of quick start

const {app} = require('electron');
console.log(app);

the result is undefined, why?

and we alse console.log(require.resolve('electron'));

the result is D:\MyProjectWorkSpace\myproject\node_modules\electron\index.js;

why?

So, could you please give us some suggestions,

Looking forward your soon feedback.

Thank you in advance.

**Comment by VerteDinde** [comment]
Hey @redabc! It sounds like this may be an issue with your specific Electron set up. Because we use this issue tracker to track bugs within Electron itself, could you ask for some help in our Electron Discord instead? We have many community members and maintainers there, and multiple help channels where you would get a faster response.

Link to our Discord is here: https://discord.gg/electron

Thanks!
