### ISSUE TITLE
Does Electron Apps require node.js version to be installed on linux environment for execution

### ISSUE THREAD

**Issue by smartmouse** [electron/electron#26804]
Does Electron Apps require a particular node.js version to be installed on linux/mac/window  for execution?
I am not talking about building  the electron apps, I am about executing the electron apps after you built.

### Preflight Checklist

* [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
*  10.x
* **Operating System:**
  *   Ubuntu 16.04 x64 
* **Last Known Working Electron version
  * NA

**Comment by VerteDinde** [comment]
Hey @smartmouse - because we use this issue tracker to track bugs within Electron itself, could you ask for some help in our Electron Discord instead? We have many community members and maintainers there, and multiple help channels where you would get a faster response.

Link to our Discord is here: https://discord.gg/electron

Also, the answer to this specific question is no; you don't need Node installed to run a packaged app.

Thanks!
