### ISSUE TITLE
when will the stable version of 12.x.y be released

### ISSUE THREAD

**Issue by redabc** [electron/electron#26887]
hi, electron team，

there are not stable version of 12.x.y, only beta version;

so when will the stable version of 12.x.y be released;

because, Electron 12 is the first version of Electron to be based on Node 13, this feature is necessary for us

Looking forward your soon feedback.

Thank you in advance.

**Comment by pushkin-** [comment]
March 2nd according to [this](https://github.com/electron/governance/blob/master/wg-releases/major-version-release-schedule.md#1200)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
