### ISSUE TITLE
Getting an error on Appium desktop connection refused

### ISSUE THREAD

**Issue by grahate** [electron/electron#26906]
On my office laptop when I tried to start Appium desktop by entering capabilities getting an error below.

Error
<HEAD><TITLE>Connection refused</TITLE></HEAD> <BODY BGCOLOR="white" FGCOLOR="black"><H1>Connection refused</H1><HR> <FONT FACE="Helvetica,Arial"><B> Description: Connection refused</B></FONT> <HR>  </BODY>

PFA screenshots:
![appiumserverissue](https://user-images.githubusercontent.com/70128636/101614626-3319bd00-3a33-11eb-9412-26e9f2843b43.jpg)

![connection_refused](https://user-images.githubusercontent.com/70128636/101615770-850f1280-3a34-11eb-8acb-156b8dcd80dd.jpg)

**Comment by ckerr** [comment]
Hi @grahate, thanks for reaching out!

From this bug report it's not clear to me that this is a bug in Electron's code. Have you tried reporting it to Appium desktop's issue tracker @ https://github.com/appium/appium-desktop/issues ?

I'm closing this issue for now due to lack of Electron-specific information. If further investigation finds an issue in Electron's code, please open a new issue with that information. Thank you!
