### ISSUE TITLE
input file chooser do not remember file location since 10.1.6

### ISSUE THREAD

**Issue by Yolepo** [electron/electron#26947]
Hello,

Since electron 10.1.6 the filechooser from the input file do not re-open at the previous picked files location. Is this a normal feature or a bug ?
If it's a features, is this possible to have a parameter for choose to activate it?

Best regards

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by Yolepo** [comment]
I think i relate a bug, this is not a question. You are closing it a bit early. Plz reconsidere it. This feature still work in recent chromium release and do not since electron 10.1.6.
