### ISSUE TITLE
The Map of ES6 is used in electron, and the type is inconsistent.

### ISSUE THREAD

**Issue by devie2020** [electron/electron#27041]
The type of the map object created in the main process is printed in the rendering process. The result is [object object object], not the expected [object map]

**Comment by vladimiry** [comment]
This is apparently how https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm works doing types/data serialization during sending things between main/rendering processes.

**Comment by ckerr** [comment]
Hm, if I'm reading that link of @vladimiry's correctly, SCA supports serializing  / deserializing maps.

@devie2020 would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

In addition, please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
