### ISSUE TITLE
Unable to use webview in fullscreen on Electron 

### ISSUE THREAD

**Issue by Infinitive-team** [electron/electron#27082]
I'm having trouble using the webview on electron ie I can't get the webpage window to full screen
most likely I will not have explained well but I will attach a photo in the report to make the problem understandable.
<img width="1674" alt="Screenshot 2020-12-19 at 22 33 40" src="https://user-images.githubusercontent.com/67503004/102700132-14919e00-424b-11eb-9da3-a1e2a7f85976.png">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
