### ISSUE TITLE
"GUEST_WINDOW_MANAGER_WINDOW_OPEN" denied

### ISSUE THREAD

**Issue by slasher-dev** [electron/electron#27109]
Electron 11.0.3
OS Windows

We are working on an internal app (Electron 5.0.1) that had affinity to tie process together. Post an upgrade to 11.0.3, since affinity is being deprecated we have moved to process-per-site, as well as allowing for renderer process to be re-used. All seem to work fine, except for an use case where we open a new-window (newGuest) to display content to the user. Crash occurs with "GUEST_WINDOW_MANAGER_WINDOW_OPEN" denied message. Any thoughts please, would be helpful.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
