### ISSUE TITLE
electron-8.0.0

### ISSUE THREAD

**Issue by githubmxm** [electron/electron#27115]
electron8.0.0在使用中发现：如果窗口最大化，也就是点击右上角那个方块形的按钮后，在代码里调用设置窗口大小的方法不生效.不知道是设计成如此还是怎么回事，验证了下，应该和我写的业务代码没什么关系.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
