### ISSUE TITLE
electron 11, how to kill browserView process

### ISSUE THREAD

**Issue by quanweibai** [electron/electron#27114]
hi, i updated my electron version to 11, but when i close a browserView like this.

public destroy() {
        this.browserView.webContents.removeAllListeners();
        this.browserView.webContents.delete();
        this.browserView = null;
  }

the browserView process still exists.

how to kill the broserView process when i close the browserView.

**Comment by pushkin-** [comment]
What you're doing seems correct to me. At least that kills the process in my case. Are you sure that the process that still exists is not some other thing?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
