### ISSUE TITLE
Vue3 and CSSVariables don't work together

### ISSUE THREAD

**Issue by qq617564112** [electron/electron#27126]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * x

### Expected Behavior
Vue3 added a feature that can bind variables to css, for example:
```

//In vue
{
        data() {
		return {
			bg: "coral",
			width: "50px",
			height: "50px"
		};
	},
}
//In style tag
[selector]{
    width: v-bind(width);
    height: v-bind(height);
    background-color: v-bind(bg);
}
```
Or can check here: 
Vue will convert v-bind to cssvariables, I tried in normal vue3 project;
I've enable the CSSVariables feature and tried it successfully, but seems doesn't work with this vue3 feature;
It's because the `v-bind(bg)` was converted to `var(--bg)` but `--bg:coral` was not add to inline style;
I want to figure out why? Is there any blinkfeatures I haven't enable?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
