### ISSUE TITLE
Why monaco-editor doesn't work well in electron?

### ISSUE THREAD

**Issue by Fangrengehua** [electron/electron#27122]
I'm trying to get monaco-editor to work with react and electron,  I get the following error in console when I set language to javascript (the web worker that needed is loaded successfully):
`errors.js:12 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (http://localhost:3000/static/js/2.chunk.js:103397:27)
    at _foreignProxy._getProxy.then.proxy (http://localhost:3000/static/js/2.chunk.js:106231:22)setTimeout @ errors.js:12`

And when I set language to html, json, there's no error in console. Also i've tried to make monaco-editor work without react, I also get the same error. 
Is there any limitation in electron?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
