### ISSUE TITLE
how to catch BrowserWindow Unresponsive

### ISSUE THREAD

**Issue by quanweibai** [electron/electron#27138]
got this report in sentry, but cant reproduce this issue in my own machine.
so how to catch this error?
![image](https://user-images.githubusercontent.com/3831666/103190172-c6476380-490a-11eb-80ff-b40b2068a517.png)

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
