### ISSUE TITLE
Set CSP header unsafe-eval to 'none' by default

### ISSUE THREAD

**Issue by dragonDScript** [electron/electron#27130]
My idea is to set the CSP header unsafe-eval value to 'none' by default.

In most use cases, users will not use 'eval'. If they use it, and see the error, they will google it and find a solution.

So we should set unsafe-eval to 'none' by default.

**Comment by sofianguy** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

Thanks for understanding and meeting us half way 😀

**Comment by MarshallOfSound** [comment]
Changing a web-standard default like CSP is not something Electron as a project should be doing.  The warning is there so that users can make the choice for themselves and deliberately opt-in to the non-default behavior
