### ISSUE TITLE
Convert Word to PDF

### ISSUE THREAD

**Issue by eezzeeofficial** [electron/electron#27141]
📚 How to convert word to pdf.
Look how to turn a [Word document into a PDF format](http://eezzee.io/blog/word-to-pdf?utm_source=serg)

Click the “choose file” button and upload the Word file you need to convert from your computer or just drag it to the file selection field. Alternatively, import the file directly from a cloud storage (Drive, Dropbox or OneDrive).
When the upload is done, click “generate”. The Word to PDF converting will take you about a few seconds.
Once the conversion is complete, download the file in PDF format.
Click the “download” button and save the converted file to your computer
💻 Drive, Dropbox and OneDrive.
Do you need to convert a file from a cloud storage? Import it right from Google Drive, Dropbox, or OneDrive and run Word to PDF conversion.

💲 Free converter.
Use this tool to convert Word to PDF absolutely for free! There are no limits on the file size and number of conversions. It cannot be better, can it?

📧 No Email.
You are not required to provide you Email or other identifiable data, no register is needed to use this Word to PDF converter

📑 Word .doc Format.
This converter from Word to PDF is compatible with .doc, .docm, .dot, .docx, .dotm, .dotx, .odt, .xml, .txt, .xps Word extensions. The tool is platform neutral, therefore you can transform Word into a PDF file regardless of the OS you are using.

🚂 Quick and Easy.
PDF conversion from Word is now as easy and quick as possible! It only takes 4 steps to convert Word to PDF online. The conversion speed depends on the file size and the server’s overload.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
