### ISSUE TITLE
When selecting the css from the devtools insector , we dont have option to copy the css, it says as empty.Can we have that option in future,

### ISSUE THREAD

**Issue by variablemayank** [electron/electron#27140]
### When selecting the CSS from the dev tools inspector, we don't have the option to copy the CSS, it says as empty.Can we have that option in the future,

**Comment by variablemayank** [comment]
![Screenshot from 2020-12-28 14-46-00](https://user-images.githubusercontent.com/16155065/103210359-6ca36100-492b-11eb-90c9-096071048b89.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
