### ISSUE TITLE
How can I get the DevTools of the window to show up in a <webview>

### ISSUE THREAD

**Issue by adel-sbeh** [electron/electron#27162]
I know how to show the DevTools of a `<webview>` inside another `<webview>`. (https://stackoverflow.com/questions/60989426/how-to-open-developer-tools-inside-of-a-webview)

But I tried to show the DevTools of the window inside a `<webview>` and it didn't work!

```js
<webview>.addEventListener('dom-ready', () => {
    remote.getCurrentWindow().webContents.setDevToolsWebContents(remote.webContents.fromId(<webview>.getWebContentsId()));
});
```

Any idea why?

**Comment by adel-sbeh** [comment]
Hmmmm

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Electron Discord](https://discord.com/invite/electron) that should be willing to point you in the right direction.
