### ISSUE TITLE
Windows Multi Desktop Support

### ISSUE THREAD

**Issue by acerbastimur** [electron/electron#27197]
Hi, I would like to be able to change Windows's Desktop Switch feature (here [link)](https://www.cnet.com/how-to/how-to-use-multiple-desktops-in-windows-10/).

Is there any Electron API for this feature? Or do you know is there any way to trigger desktop switch like that?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Electron Discord](https://discord.com/invite/electron) that should be willing to point you in the right direction.
