### ISSUE TITLE
Any security concerns/challenges while opening the electron app as a root user without sandbox?

### ISSUE THREAD

**Issue by siva68533** [electron/electron#27194]
Our electron app required root access to run all internal tools.
As the latest electron framework (greater than 5) included chromium sandbox, so the root user is not able to open up an electron app. To make it work by disabling sandbox using --no-sandbox flag in launch command, the electron app can be opened up as a root user.
Are there any security concerns/challenges while opening the electron app as a root user without sandbox? or Any security actions needed to be taken care of in this case?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
