### ISSUE TITLE
[Feature Request]: Enable w3c trusted types usage with electron apps

### ISSUE THREAD

**Issue by jrieken** [electron/electron#27211]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

VS Code is in the process of adopting trusted types, see https://github.com/microsoft/vscode/issues/103699 and https://github.com/w3c/webappsec-trusted-types. This is going well and electron plays along nicely. However, there is one place in  `web-view-impl.ts` which directly assign a string to the `innerHTML` property: https://github.com/electron/electron/blob/34156c424cb1964cdd203293cbed138d19ee9c9d/lib/renderer/web-view/web-view-impl.ts#L47

When using trusted types this isn't allows (due to the potential for XSS) and either needs to be avoided or explicitly allowed via a trusted types policy. 

This can reproduced with a renderer like this

```html
<!DOCTYPE html>
<html>
		<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types *">

  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <link rel="stylesheet" type="text/css" href="./styles.css">
  </head>
  <body>
    <h1>Hello World!</h1>
    
    <script>
      const webview = document.createElement('webview');
      document.body.append(webview);
    </script>
 
  </body>
</html>
```

There is also a fiddle for the whole thing but that seems to trigger more/other violations that we don't see in VS Code. Might be related to the way electron fiddles work: https://gist.github.com/edd3cf4923d96a613c13954f546dd7d0

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/issues/new/choose) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by jrieken** [comment]
> Thanks for understanding and meeting us half way 😀

I am sorry but as someone that manages loads of issues in a very popular open source project, I have no understanding for your behaviour.

**Comment by jkleinsc** [comment]
@jrieken I missed the repro that you provided above, so sorry about that and I will reopen the issue.  We get lots of issues filed and when folks[ don't use our template we by default we close the issue and ask that folks fill out the template](https://github.com/electron/governance/blob/master/playbooks/issue-triage.md#process).  Also, can you clarify what the Expected Behavior/Actual Behavior you are seeing as it relates to Electron itself?

**Comment by jrieken** [comment]
thanks

**Comment by jkleinsc** [comment]
Running through the fiddle provided, the way this issue manifests itself is via the following error in the console:
```This document requires 'TrustedScript' assignment.```

**Comment by miniak** [comment]
![Uploading Screen Shot 2021-01-22 at 5.42.06 AM.png…]()

**Comment by koto** [comment]
Thanks miniak@, your patch is much better than my attempt. Not touching innerHTML if you can avoid it is best!
