### ISSUE TITLE
how can i find the detail reason for renderer process crash

### ISSUE THREAD

**Issue by exolution** [electron/electron#27243]
electron: 11.1.1
platform :Mac 

background:
c++ addons transfer Buffer data(Buffer::New) to renderer process(page)
and page use this data for webgl.texImage2D then crashed immediately without any error。
but there is no crash when i copy this bufferdata to a newer Uint8Array(it was a Uint8Array originally)

how can i debug this situation？

**Comment by exolution** [comment]
see 
https://stackoverflow.com/questions/64590540/renderer-process-of-electron-is-crashed-when-program-use-c-native-addon-and-gl
for exactly description

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Electron Discord](https://discord.com/invite/electron) that should be willing to point you in the right direction.
