### ISSUE TITLE
Question: Disabling CORS

### ISSUE THREAD

**Issue by brltdxd** [electron/electron#27242]
Hi,

I am planning on creating a desktop app with Vue and Electron. This is some kind of a monitoring application that frequently pulls data from an external API. Naturally, when fetching the data using Axios, I am getting blocked by CORS. I know that disabling the `webSecurity` is not ideal but this is the only way I can successfully pull the data.

I am sending the credentials on each request to retrieve the data.

__Question__: Is it still safe to proceed with the `webSecurity` disabled? Very few people would use the app (less than 8) and it would not be distributed to anyone outside of the organization. Also, we only have 1 dedicated account that can pull the data and it is shared to everyone in our team.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Electron Discord](https://discord.com/invite/electron) that should be willing to point you in the right direction.

**Comment by brltdxd** [comment]
Thank you. 😁
