### ISSUE TITLE
[Feature] Add direction to notification module

### ISSUE THREAD

**Issue by miladmeidanshahi** [electron/electron#27258]
Hi,

It's good to add [Notification.dir](https://developer.mozilla.org/en-US/docs/Web/API/Notification/dir) feature for `Notification` module.

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/issues/new/choose) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
