### ISSUE TITLE
Feature suggestion: lightweight binaries

### ISSUE THREAD

**Issue by rauschma** [electron/electron#27263]
I’d love to be able to create a native binary with these features:

* Contains native icons and web app artifacts (HTML, CSS, JavaScript, etc.)
* Only supports client-side APIs (those that are also available to Progressive Web Apps)
* The web app is executed via an installed web browser (like natively installed PWAs are)

FAQ:

* Q: Why not create a normal Electron binary?
  * A: Smaller binary (no engine included); engine is always up-to-date
* Q: Why not create a PWA?
  * A: Native binaries can be distributed via services such as Gumroad and Payhip.

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/issues/new/choose) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
