### ISSUE TITLE
setContentProtection  not working on MacOS，when used QucikTime player

### ISSUE THREAD

**Issue by aizhimin** [electron/electron#27298]
### Preflight Checklist

setContentProtection not working on MacOS，when used QucikTime player. But using other software such as Zoom,it can work.

### Issue Details

* **Electron Version:** 11.1.1

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/issues/new/choose) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
