### ISSUE TITLE
frameless window use win.hide() then use win.show() and the window flicker

### ISSUE THREAD

**Issue by lswl66** [electron/electron#27320]
`
new BrowserWindow option: {
   width: 1200,
    height: 1200,
    x: -1400,
    y: 0,
    transparent: true,
    frame: false,
}
`
when we have `transparent:true` and `frame:false` , if use `win.hide()` then use `win.show()` the window will **flicker**

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/issues/new/choose) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by lswl66** [comment]
thanks your reply , I use `win.minimize()` replace `win.hide()` and the issue be avoided
