### ISSUE TITLE
Parse Cookie Failed❌

### ISSUE THREAD

**Issue by rmGFW** [electron/electron#27338]
Electron can't parser cookie which has prefix `__Host` in name 
such as 
{
  "name": "__Host-user_session_same_site",
  "value": "******-fUlx9jLkZesH1550tTAJcW4hSo7QkQqpLxcCsXi",
  "domain": ".github.com",
  "path": "/",
  "secure": true,
  "httpOnly": true,
  "url": "https://github.com/"
}

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction. If you meant to report an issue, you are welcome to try again and fill the template properly.

**Comment by wernst** [comment]
@rmGFW If you're still running into issues, see the section on Cookie Prefixes https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies ... with your example it looks like you should drop the domain attribute
