### ISSUE TITLE
When I launch the app, I get the error "Widevine component installation failed".

### ISSUE THREAD

**Issue by KazukiSugiyama107** [electron/electron#27345]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.3
* **Operating System:**
  *  macOS Catalina 10.15.7
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
The app starts

### Actual Behavior
The following error occurs at startup.
```
Failed to install Widevine components
Error: net::ERR_FAILED
```
The app cannot be started properly due to an error.

This app uses Widevine to play the video.
I think the error occurred because Widevine CDM was not downloaded when the app was launched, but I don't understand why it wasn't downloaded.

### To Reproduce
It occurs only for a specific user, and the reproduction method is unknown.

### Screenshots
![image2](https://user-images.githubusercontent.com/70558785/104871548-b281a100-598e-11eb-8ac7-b344cda510b2.jpeg)

### Additional Information
* **hardware information:**
  * iMac（21.5-inch, Late 2013）

**Comment by codebytere** [comment]
@KazukiSugiyama107 without a reproducible sample or crash report, we cannot triage this - it is not enough information to go on. Please provide either or this issue will be closed.

**Comment by KazukiSugiyama107** [comment]
The reply was delayed.
We have sent you a bug report with the following file name, so please check it.
`issue27345_crashreport`

When I checked the report I received here, I couldn't find any problems related to electron.
Please let me know if the report you get is incorrect.

**Comment by codebytere** [comment]
@KazukiSugiyama107 please attach the crash report  _to this issue_

**Comment by ckerr** [comment]
Please note that Electron 8 reached end-of-life on November 17, 2020 and is [no longer supported](https://www.electronjs.org/blog/electron-11-0#end-of-support-for-8xy). If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

If this does persist in a supported version, please consider making a standalone testcase with only the code necessary to reproduce the issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making test cases and publishing them to a [gist](https://gist.github.com) that Electron maintainers can use. Because of the volume of reports that we get, triaging issues with third-party code dependencies is usually not feasible for a team our size.

Thanks in advance! Your help is appreciated.
