### ISSUE TITLE
Connection failed: Unexpected token B in JSON at position 0

### ISSUE THREAD

**Issue by wgregori** [electron/electron#27377]
I'm running Whirlpool on a Mynodebtc.  Trying to connect the GUI on an Ubuntu 20.04 system.  the Mynode is located at 10.10.1.191 of my local network.  I can successfully telnet to 10.10.1.191:8899.  However, when I try connect with the GUI I get the message

Connection failed: Unexpected token B in JSON at position 0

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction. If you intended to report an Electron specific issue, you are welcome to do so again, _completely filling out the required template_
