### ISSUE TITLE
how to set BrowserWindow's minWidth 20px?

### ISSUE THREAD

**Issue by Vishal1419** [electron/electron#27371]
When I set BrowserWindow minWidth to 20px (any value less than 70px) and try to resize the window by dragging from an edge, I am not able to resize it less than 70px. I can reproduce it on MacOS High Sierra.

Note: I have removed the frame of the BroswerWindow. If there is a frame then also behavior is same.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
