### ISSUE TITLE
Send DOM object to preload script with exposed api

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#27416]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I try to send a DOM object to preload script like this:
```
var terminal = document.createElement("div")
terminal.id = "terminal"

console.log("Sending: ", terminal)
window.api.startSSH(terminal)
```
The console outputs:
`<div id="terminal"></div>`
which is expected

But on the preload script:
```
const { contextBridge } = require("electron");
contextBridge.exposeInMainWorld(
	"api", {
           	startSSH(terminal) {
		     console.log("Got: ", terminal)
               }
         }
)
```

the console outputs:

![image](https://user-images.githubusercontent.com/17744127/105219092-e2ee4a00-5b0a-11eb-83ec-b6fd2f07710a.png)

but it should be a node object !

But alternativly when I send the terminal object I get:

![image](https://user-images.githubusercontent.com/17744127/105219522-66a83680-5b0b-11eb-9066-6e0d9f5848ec.png)

with same preload code and send object:
```
var terminal = document.createElement("div")
terminal.id = "terminal"

var term = new Terminal();
term.open(terminal)

console.log("Sending: ", term)
window.api.startSSH(term)
```

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. You did not provide a platform or Electron version. We also need a _standalone_ piece of code we can run in e.g. Electron Fiddle to reproduce the behavior.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by ShlomiRex** [comment]
Sorry.
But I made a workaround. I just send a callback to preload script and use it.
Sorry again :)
