### ISSUE TITLE
Restart the computer under windows and pack it in ffmpeg.exe Start up together by command

### ISSUE THREAD

**Issue by peiyuqi** [electron/electron#27427]
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden:false, 
  path: exeName,
  args: [
    `"start ${config.ffmpeg}"`, 'ffmpeg.exe',  
  ]
});
is not work

**Comment by lucybythec** [comment]
What is "config.ffmpeg"?

You should use the project bug report template. Probably no one will help if you don't.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
