### ISSUE TITLE
m3u8

### ISSUE THREAD

**Issue by Gao-R** [electron/electron#27434]
When using electron-vue to play m3u8 streaming video (using videojs-contrib-hls), you will get an error 'a is not defined'. If you run on other video streams, no error will be reported.

**Comment by Gao-R** [comment]
When using electron-vue to play m3u8 streaming video (using videojs-contrib-hls), you will get an error 'a is not defined'. If you run on other video streams, no error will be reported.

**Comment by lucybythec** [comment]
I recommend that you first find out which project the code that is causing the error belongs to. A look at the error stack trace should tell you this.

In addition, you should use the project bug report template. Probably no one will help if you don't.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
