### ISSUE TITLE
webviews create a seperate renderer process event though they have the same host

### ISSUE THREAD

**Issue by wenssh** [electron/electron#27433]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  all versions
* **Operating System:**
  *  all platform
* **Last Known Working Electron version:**
  *  all versions

### Expected Behavior

webviews with the same host share one renderer process to avoid cost too many memory
### Actual Behavior

webviews create a seperate renderer process event though they have the same host
### To Reproduce

create a webview

**Comment by lucybythec** [comment]
I don't think it makes sense, webview can go to any URL at any time. Have you tried setting the "section" property or using BrowserView in the same session?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
