### ISSUE TITLE
[Feature Request]: Move to system web view is possible

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [electron/electron#27430]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

Electron bundles a Chromium instance with every app. This just wastes memory since it's very similar. Electron apps start slowly because they need to load Chromium and Node but if it is already running what's the use?

**Proposed Solution**

Many modern OSes come with a built-in browser so Electron could use that (CoreWebView2 on Windows for Edge, WKWebView on macOS for Safari) instead of bundling a Chromium browser with every app. This has been done before and shows significantly less memory usage and smaller app size. On some platforms like Linux, this may not work out so bundled rendered can be used on those platforms but whenever there's a WebView built-in, use that instead of a separate rendered for each app.

**Alternatives Considered**

None

**Additional Information**

_No response_

**Comment by ijsankar** [comment]
This solves many of the downsides of Electron. So No.

**Comment by baconbrad** [comment]
This gets recommended a lot and it would work for web apps that can get by with normal browser security restrictions. Otherwise to do a lot of what Electron can do Chromium needs to be hacked at a bit. It would also make for compatibility issues as mentioned above. CoreWebView2 and WKWebView also occasionally suffer from getting behind in feature inclusion or feature incompatibilities. So your app would break if it developing on what version they are running and what version you are developing for. Again, basic web apps this would be great. But I couldn't see this being viable for Atom, Git Kraken, or the point of sale software we make it with. Further more this would require a rewrite of Electron than a modification. So it would be much better suited as a new project entirely.

**Comment by miniak** [comment]
Electron in based on Chromium, which makes this impossible.
