### ISSUE TITLE
Why does the webContents.print() method print only part of the content

### ISSUE THREAD

**Issue by liu1032031740** [electron/electron#27448]
### Issue Details

* Electron Version: v9.0.0
* Operating System: Windows

### Actual Behavior
I created a new window to hold the printed content and called webContents.print() to print the content of the window, but the printed PDF only has one page and the rest of the content is truned. How do I make the webContents.print() method print all the content and automatically pagate the content when it exceeds one page

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
