### ISSUE TITLE
I cannot sigh in in Unity Hub

### ISSUE THREAD

**Issue by coocoojonathan** [electron/electron#27460]
I have tried to login in UnityHub, but when I click sigh in, it only shows file, edit, view, window, help, no space to write username or password.

**Comment by MarcoGriep88** [comment]
Same here, using Manjaro with and unity hub install via Snap

Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux

**Comment by ckerr** [comment]
Hi @coocoojonathan, thanks for reaching out!

I'm a little confused by this issue. Did you mean to report it to the Electron bug tracker, or did you hit the wrong page by mistake?

If you intended this as an Electron bug report, please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Also, since the next triager might be confused like me about how Electron can address this issue, could you explain the issue a little further?

**Comment by MarcoGriep88** [comment]
@ckerr Sorry, i guess this is an issue of Unity. In the login screen there is an "troubleshooting" button that leads over here.

**Comment by StevenVentura** [comment]
credit goes to Scifer on https://forum.unity.com/threads/unity-hub-sign-in-window-blank.514092/
====

After looking through the logs I found that Unity Hub could not find my Windows Product key in the registry as the String was blank. After entering the product key in the registry I was able to sign in.

Checking the log file AppData\Roaming\UnityHub\logs\info-log.json I found the below entry which highlights "Key Not Found"

{"moduleName":"App","level":"error","message":"[ 'Failed to start Unity Hub, reason: Key Not Found' ]","timestamp":"2019-05-19T10:44:37.039Z"}

To fix this do the following:

Open regedit and goto Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion and enter in your windows product key XXXXX-XXXXX-XXXXX-XXXXX-XXXXX in the ProcudtID feild. Once entered make sure to kill all UnityHub processes and reopen Unity Hub.
![upload_2019-5-19_20-56-16](https://user-images.githubusercontent.com/18370382/140638987-399f35c6-9a97-4ffd-b829-e2979e9d7c98.png)
