### ISSUE TITLE
reload app issue

### ISSUE THREAD

**Issue by rajatmittal2716** [electron/electron#27473]
When I am trying to create a new desktop app with electron 11+angular 8. I am facing an issue after running the project. When I press f5 it's not able to reload the index.html properly, and it shows a blank window can you please let me know how to fix this issue. I can share my code also if needed.

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

In addition, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.
