### ISSUE TITLE
Weird black background after double-clicking menu bar

### ISSUE THREAD

**Issue by devkrxspl** [electron/electron#27484]
I tried making my own app menu-bar, and I've ran into a problem. On a normal app, when you double-click the menu bar it resizes the screen. However, when I double click on a div with `-webkit-app-region: drag`, it instead produces a weird black background i can't get rid of.

Before double-clicking menu bar:

![0cb9c22ead592227f9d6f17a4f6604a2](https://user-images.githubusercontent.com/69094742/105772340-07458e80-5f30-11eb-94cc-8b9da9398b56.png)

After double-clicking:

![15cc390550a0540ac90f208ed300256f](https://user-images.githubusercontent.com/69094742/105772419-1f1d1280-5f30-11eb-93b2-21ae4442f00f.png)

Solutions like setting resizable: false, or window.setResizable(false) also don't work, although they work as intended on a normal electron menu bar.

Any thoughts?

**Comment by ckerr** [comment]
Thanks for reaching out!

If you think this is a bug in Electron, please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

If you think this may be a bug in your own code and are asking for tips on programming, e.g. the custom menubar, you might try this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

Thanks for understanding and meeting us half way :grinning:
