### ISSUE TITLE
Rendering issues wth Electron 11

### ISSUE THREAD

**Issue by sweettyler** [electron/electron#27480]
This is  most likely an electron bug: https://github.com/microsoft/vscode/issues/114004

Please see the link for more detail, but the keys to reproduce are:

1) Electron 11.x (with electron 9.x no such an issue);
2) Remote connection (if run locally no such an issue);
3) Large initial window size (no such an issue with a small initial window).

**Comment by ckerr** [comment]
CC'ing @deepak1556 who did some initial triage with @sweettyler in the downstream ticket

**Comment by ckerr** [comment]
@sweettyler I do remember from the other issue you reported yesterday that you're running on CentOS 7, which is quite old and not on [Electron's supported platforms list](https://www.electronjs.org/docs/tutorial/support#supported-platforms).

Does this issue persist on supported distros; and if so, which one?

**Comment by ckerr** [comment]
@sweettyler if this issue persists on a supported distro, please file a new ticket with the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that is presented when you first fill out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way.

**Comment by sweettyler** [comment]
@ckerr Yes the OS is quite old, but I have few other choices (the only one is RHEL 7.9, which is not new either, and have the same issue if I run VScode remotely) as the computers belongs to my company and I have little control over them.
Anyway, thank you.

**Comment by deepak1556** [comment]
Commented on the original issue as to what the root issue would be https://github.com/microsoft/vscode/issues/114004#issuecomment-767841518
