### ISSUE TITLE
when I use xhr.setRequestHeader, the weird thing happens. The value I set in range differs from what is sent out!

### ISSUE THREAD

**Issue by a630140621** [electron/electron#27516]
when I use XMLHttpRequest.setRequestHeader("Range", "bytes=109051904-121634815"), sometimes that **header is different of actually send**, like this:
![image](https://user-images.githubusercontent.com/26158889/105994033-0bb1a900-60e2-11eb-8066-00576602784e.png)

my code is here
![image](https://user-images.githubusercontent.com/26158889/105993765-ba091e80-60e1-11eb-921d-15cd0caa4f2c.png)

**Comment by ckerr** [comment]
Hi, thanks for taking the time to reach out and report this.

Electron runs on many platforms and has many currently-supported versions. So to begin with, before anyone can triage this you will need to provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

I'm adding the `blocked/needs-info` label for this reason.

In addition, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

**Comment by a630140621** [comment]
---
name: Bug report
about: XMLHttpRequest.setRequestHeader

---

### Issue Details

* **Electron Version:**
  * 9.4.0
* **Operating System:**
  * Ubuntu 20.04 x64

### Expected Behavior
send ajax request with http header **Range: bytes=109051904-121634815**

### Actual Behavior
send ajax request with http header **Range: bytes=109051904-120900441**

### To Reproduce








### Screenshots


### Additional Information
