### ISSUE TITLE
nevzat.erk@bso.co Error code 9 on flexbox is there a fix please?? 

### ISSUE THREAD

**Issue by Nerk98** [electron/electron#27517]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by ckerr** [comment]
Thanks for reaching out!

It's hard to tell what you're referring to in this issue.

If you think you've found an Electron bug, please open a new tick *and be sure to provide* the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

If you're asking a more general question, you have better luck with at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
