### ISSUE TITLE
CPU usage spikes and Chrome crashes, being unresponsive and unusable

### ISSUE THREAD

**Issue by surya557** [electron/electron#27542]
When launching Chrome in Windows10, CPU usage spikes up to 100% and Chrome crashes, being unresponsive. This only happens when my application (which is built using Electron) is open while Chrome is being launched. Electron application begins to run extra processes when Chrome is opened. When the applications are opened separately, there doesn’t seem to be an issue.
The issue seems to happen only in Windows 10. User uninstalled and reinstalled both Electron and Google chrome applications on his machine, still able to reproduce it and CPU usage goes to 100%. I am not sure where exactly the issue is and how to reproduce it on our machines. Please help.

Is there any relation with Chromium that is integrated into Electron build and Google Chrome application?

Electron 4.0.8 version and Chrome - 85.0.4183.83.

Please find the reference of CPU usage and the number of instances of my application (Epoch) and Google Chrome.

<img width="454" alt="waymouth" src="https://user-images.githubusercontent.com/2225893/106216803-85f13480-6199-11eb-912d-854d7aa5aaad.png">

**Comment by ckerr** [comment]
Hi @surya557, thanks for reaching out and reporting this issue.

Electron 4.0.8 has been end-of-lifed for quite a long time now and is no longer supported. The latest supported version is 11.2.1. The bad news is that long span between 4 and 11 may add time to your upgrade process (e.g. if you used Electron APIS in 4 that have migrated from callbacks to Promises), but the good news is that the upstream Chromium improvements between 4 and 11 may resolve this issue for you.

Because of time constraints, triaging issues with versions this far off the support timeline is not really feasible for a small team like Electron's, so I'm going to close this ticket. I hope you're able to update this application and that the update solves the problem. Good luck!

**Comment by surya557** [comment]
Thanks for your quick response @ckerr. I'm not sure if I can upgrade my Electron version as the application is in production already. Could you please tell me the dependency between Chromium and Google Chrome, so that I will try to do some research on the actual fix.
