### ISSUE TITLE
Readline does not function with open browser windows

### ISSUE THREAD

**Issue by makingglitches** [electron/electron#27599]
Please see the below link:

https://github.com/nodejs/node/issues/37115#issue-796315896

They of course deferred this to Electron itself.

I'm going to take a shot in the dark and guess that the issue is resulting from the way electron communicates between processes and windows likely being related to the stdin handler itself.

But I thought I'd report this anyway.

the readline package simply doesnt function or consume the processes stdin handle.

Anyway now the code exits and the keystrokes do NOT appear in the terminal window they don't appear at all.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by MarshallOfSound** [comment]
`electron.exe` is a GUI application and therefore cannot capture or read stdin in the same way a Command Line app can on Windows.  Unfortunately there isn't really a good workaround, it's just how stdin/stdout work on windows 😞

**Comment by makingglitches** [comment]
Some part of me guessed that.
