### ISSUE TITLE
Mirroring fails (error connecting android devise error apk path faild (empty))

### ISSUE THREAD

**Issue by toshi-ue** [electron/electron#27619]
I used this app for the first time this time.
But I installed the app on mac (os: mojave) and
I downloaded it from the playstore of andoid (xiaomi note 9s) and ran it, but mirroring fails on mac.
I'm a beginner so I don't know.
Please tell me the solution.
Thank you.

this link is bug report by created vysor button.
https://gist.github.com/VysorLogs/9bb29d35100e5bd707355643c829e9b0

https://user-images.githubusercontent.com/46378023/106885921-a20b4d80-6726-11eb-9182-c3d130e6e156.mov

**Comment by ckerr** [comment]
Hi @toshi-ue, 

Thanks for reaching out! Vysor is an application that uses Electron, but the Electron team isn't otherwise related to them. Please report this issue to Vysor. I don't know much about that app so I might be wrong, but from a quick web search I *think* their technical support is available [here](https://support.vysor.io/).

Good luck! I hope you find the answer you need.
