### ISSUE TITLE
strange async behavior with HTML toast

### ISSUE THREAD

**Issue by StephaneAdeso** [electron/electron#27632]
Hi. I am building a very simple Electron app that takes "csv" files, process them and then write others "csv" files. 
I have made 2 divs on my "browserWindow" instance that acts like "Toast". No complicated codes, only css and a bit of javascript for hidding them after showing. 

### issue
One of them ( toast) is at the beginning of the method to notify the user that the process has started and another at the end to notify that it has finished. The problem is that they both happen last. After several days of reviewing and talking with colleagues, we believe that it is some kind of electron behavior with the processes. (we may be wrong).

Solutions I have tried:
* change the Toast code in 3 different ways.
* change libraries for csv in case it affected the processes.
* change "fs" methods from asynchronous to synchronous.

But nothing has worked. The problem continues to persist. So we come to the conclusion that it is something from Electron.

###  Details

* **Electron Version:**
  * "electron": "11.2.0"
* **Operating System:**
  * Windows 10 64
* **Node Version**
  * Node: 14.15.4

### Expected Behavior
1º Toast apear at the begining when lauching the method "generar" and the 2º Toast launching at the end, after all job is finished.

### Actual Behavior
Both are shown last despite no asynchronous code.

### To Reproduce
just run "npm run start" and select one file located in "documentacion > file_samples"

### Additional Information
* full project at github: [https://github.com/Osolemio44/bugged_electron_app.git](https://github.com/Osolemio44/bugged_electron_app.git)
* 3 min video example (If you want to see the demonstration directly, go to minute 2.25): 

https://user-images.githubusercontent.com/55595063/107028394-cbbb8780-67ad-11eb-8704-1fb9e7dae958.mp4

**Comment by vladimiry** [comment]
> Solutions I have tried:

Here is the addition thing you could try:

- Disable [these flags](https://github.com/Osolemio44/calculadorHD/blob/2974b13be3386d74505690b8706bf510bd6943fa/app.js#L12-L13) (you have them enabled, it's clear why):
```
            nodeIntegration: true,
            enableRemoteModule: true
```
- And then use IPC approach for communicating  between processes.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging third-party code (e.g. the csv app) is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the minimum of code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by Osolemio44** [comment]
Hi. Thank you very much for answering. To be honest, I have no idea how to reduce the existing code because it is an application that only does 1 thing. Redo a separate project or Gist, learn to use Electron Fiddle, etc ... all to remove a few lines of code and in the end do the same as what I already passed you I do not know if it will be possible, due to my little free time already that I'm really new to all this node and electron stuff. I will try to do something these days, but realistically, I don't know if I can do anything else besides what I have already done. But one thing is clear to me, is that this has to have a simple solution since showing and hiding some divs is something basic that electron must be able to do. I'm going to start with the advice that Vladimiry has given me to see if with that I can overcome the problem. A friend has told me that it is most likely the fault of the rendering process that has poor synchronization with the node process that performs the calculations. And that's why he prioritizes Node. And when Node finishes, it returns "power" to the rendering and then does it all at once. I will see what I can do.

**Comment by Osolemio44** [comment]
so, answering to vladimiry, i have been reading about ipc and i am not sure this will work for me since ipc is for sending messages from renderer to main and i have no messages to send. 
What I need is that in my "renderer process" the order in which the code is executed is respected. I don't really understand what is happening. It may be the "main process" that is interfering, but it doesn't make sense. Isn't all the code I have in the main.html file supposed to be from the renderer? I don't understand how there can be part that runs in the renderer and another in the main process. The truth is that I think this is not working well. But I can be wrong, my knowledge of electron is very limited.

**Comment by vladimiry** [comment]
@Osolemio44, if you need to make your project work I think you might want to try all know options which you didn't do yet (dropping direct-like node access from renderer process, ie using pure IPC). Since you are new to electron I'd suggest starting using IPC from day one since this way you won't regret in the future as your project evolves. If you believe there is a bug in electron you got the way of moving forward (highlighted by @ckerr above) - providing a minimal repro project. It's important to understand that it's not only your free time is limited but others have time constraints too.

**Comment by Osolemio44** [comment]
Perhaps I have not explained myself well. It's not that I haven't tried. I've been reading about IPC messaging all day to test the solution you have offered me. The problem is that I don't know how to use IPCmessaging in my case. This system is supposed to be used to send messages from the renderer to the main process and vice versa. Since I have nothing to send, I can't think of how to implement that solution. I also appreciate the effort you make and if you do not have time to look at it, I understand.

**Comment by vladimiry** [comment]
> Since I have nothing to send

See just one example.

`const { dialog } = require('electron').remote`

The `dialog` here is a part of the main process (as all other stuff you require via `remote`). So you would send IPC signal to main process that you want the dialog to be displayed. The main process accepts that signal and displays the dialog for you.

Same for using `fs` and other nodejs/main-process related things in the rendered process.

**Comment by Osolemio44** [comment]
So if I understood you correctly, every time I want to update the DOM of a renderer process (like now in my project), I have to write that code in the main process and request it from the renderer process?
If so, as I develop and add functions, won't I end up with a giant main process full of code from all the renderer processes?

**Comment by Osolemio44** [comment]
Encapsulando el código en un "remote setTimeOut" sigue dando el mismo comportamiento extraño. Sin embargo si utilizo un dialog en vez de mi "Toast",  el dialog funciona correctamente.
         
        // line 122
        require('electron').remote.getGlobal('setTimeout')(() => {
          
            let y = document.getElementById("snackbar2");
            // Add the "show" class to DIV
            y.classList.add("show");
            // After 3 seconds, remove the show class from DIV
            //setTimeout(function () { y.classList.remove("show"); }, 1000);
            require('electron').remote.getGlobal('setTimeout')(() => { y.classList.remove("show"); }, 1000);
            // FIN TOAST        
            console.log("textooooooooo"); // <= this still works correctly

        },0)

**Comment by Osolemio44** [comment]
I just tried using IPC. but will not let me.
In the main I have put:
```
const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');

let mainWindow

function makeToast(domEl,time){

    domEl.classList.add("show");
    setTimeout(function () { domEl.classList.remove("show"); }, time);

}

ipcMain.handle("make-toast",(el,ti)=>{
    makeToast(el, ti)
});
```

In the renderer:
Error that gives me:

**Comment by vladimiry** [comment]
IPC implies separation of concerns, this is a point of it. So you perform the main/node process related actions separately from the web/renderer/DOM related needs. Ie you can't handle DOM in the main/node process.

**Comment by Osolemio44** [comment]
Indeed i am not manipulating the DOM element from the main process. I am doing it from the renderer process since the javascript code is in the renderer html file.

**Comment by RayViljoen** [comment]
@Osolemio44 I believe everything is actually working as it should, BUT.. The CSV parser is blocking the renderer thread as it's the sync lib.
Therefore, having a "fadIn" on the first toast, you don't get to actually see it before the thread gets blocked.
If you remove the CSS animation from that element, I believe you'll see it for the duration of the csv processing and then once that's complete the timeout will continue to remove it. (The timeout execution will also stay blocked.)

Pls note, I've not tested this, but 99% sure that's why you're not seeing the first toast.
