### ISSUE TITLE
Electron Documentation about electron-windows-notifications

### ISSUE THREAD

**Issue by Draginfable** [electron/electron#27650]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.x, 11.x
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * 9.4.2

### Expected Behavior
As described on electron documentation(https://www.electronjs.org/docs/tutorial/notifications#advanced-notifications), in order to use ToastNotification and TileNotification it is recommended to use electron-windows-notifications. Those work fine for all version until the latest 9 version of electron.

### Actual Behavior
For versions starting from 10 and up, it is no longer possible to use them as npm install fails.

### To Reproduce
I have prepared an example where npm install fails:
https://github.com/Draginfable/Electron-samples/tree/electron11-windows-notifications

```sh
git clone https://github.com/Draginfable/Electron-samples.git -b electron11-windows-notifications
cd Electron-samples
npm i
```

### Additional Information
This issue is quite blocking for upgrading from version 9, which will soon be out of support. 
Apart from updating the documentation, are there any plans for this functionality to be implemented by Electron? If not, are there any alternatives that we could use? 
There is an open ticket(felixrieseberg/electron-windows-notifications/issues/26) on electron-windows-notifications for quite a while but there doesn't seem to be any progress. There is also this proposal(electron/electron/issues/24524) but there hasn't been any progress either.

**Comment by ckerr** [comment]
Hi @Draginfable, thanks for reaching out and reporting this.

Just doing initial triage on this, it's not clear to me whether this is an `electron/electron` issue or an [electron-windows-notifications](https://github.com/felixrieseberg/electron-windows-notifications) issue. Fortunately @felixrieseberg is a primary on both repos and may have a better idea, so I'm @'ing him here :smile:  

FWIW regardless of which repo this issue should be in... when I run `npm i` or `yarn install` on the electron11-windows-notifications I am not seeing any error from the install pass. (Tested with yarn 1.22.0, npm 7.3.0, Ubuntu 20.10). From the "Actual Behavior" in the description and since the repo doesn't seem to have any notification code in it, it seems that the bug report is only about the npm install phase?

`npm i` looked like this for me:

```

> electron-sample@0.1.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/tmp/triage/27650/Electron-samples/app

added 244 packages, and audited 245 packages in 13s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

So maybe I am not  understanding the report but this seems to be WFM. Marking as `blocked/need-info` for clarification on what the specific issue is, either from @Draginfable as the reporter, or maybe even @felixrieseberg as someone more familiar with the e-w-n package than me :slightly_smiling_face:

**Comment by Draginfable** [comment]
Hello @ckerr ,
Thank you for your fast response. 

Indeed the actual issue is with electron-windows-notification. The problem on electron's side is that the documentation suggests the usage of electron-windows-notification but this doesn't work anymore.

You are right, you don't need any code for it to fail. Just npm install. I think that the reason that this doesn't fail for you is that you tried it on linux as seen on your result. Could you please try again on a windows machine?

**Comment by Draginfable** [comment]
What finally worked for me was using the VS Build tools 2017 and having the same node version as the one that electron uses internally.

**Comment by semireg** [comment]
I couldn't get electron-rebuild to use 2017... until I found [this gem](https://github.com/electron/electron-rebuild/issues/221#issuecomment-368350434):

`$Env:GYP_MSVS_VERSION=2017`

Which roughly translates to a package.json entry of:

`"electron-rebuild": "cross-env GYP_MSVS_VERSION=2017 npx electron-rebuild ....`

😅
