### ISSUE TITLE
[macos] When "frame:false" in an app, here is a titlebar hot area still disturbs page elements.

### ISSUE THREAD

**Issue by blakezhu** [electron/electron#27683]
Many times, I want to hide the titlebar and customize the 3 window control button.
In windows, just "frame:false" works fine. But in macos, when I set "frame:false" and put 3 button in the top-right just like windows, here is a hot area disturbs the buttons <cursor:pointer>.

It looks like here is an invisible element over the buttons, so <cursor:pointer> can not work.

I don't want to set titlebarstyle, because I want to customize it by myself.

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
