### ISSUE TITLE
TypeError with documented menu example

### ISSUE THREAD

**Issue by rpatrick00** [electron/electron#27708]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.2.3
  * * **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

I am trying to get a context menu example working.  I tried using the example in the [Menu API documentation](https://www.electronjs.org/docs/api/menu#examples).  I expect both the application menu and the context menu to work.

### Actual Behavior

When I run the example, the app menu works but the context menu does not.  I see the following error i the dev tools console:

```
Uncaught TypeError: Cannot destructure property 'Menu' of 'remote' as it is undefined.
    at index.html:11
```

### To Reproduce

https://gist.github.com/f50117cd7b360334da1086d8c3bd3fc7

### Screenshots

![Screen Shot 2021-02-11 at 10 37 00 AM](https://user-images.githubusercontent.com/8006229/107667415-2c870c00-6c55-11eb-97e6-acdfd214792d.png)

**Comment by ckerr** [comment]
Hi @rpatrick00, thanks for reaching out and reporting this.

This is due to the [deprecation of the `remote` module](https://github.com/electron/electron/issues/21408) and [the default value of `enableRemoteModule` changing to `false` in Electron 10](https://github.com/electron/electron/pull/22091).

For the short term, if you want to use remote for accessing menus via the renderer you should be able to use the code as-is by changing the value of `enableRemoteModule`.

The full answer will be to avoid the remote module. I've created [a new issue](https://github.com/electron/electron/issues/27710) to address use of `remote` in the documentation.
