### ISSUE TITLE
Webcam NotAllowed : permission denied

### ISSUE THREAD

**Issue by JoeKing7** [electron/electron#27725]
I have a proble launching electron with JS file with webcam code. In browser the webcam starts but on Electron shows me a error : "NotAllowed : permission denied" I'm using electron with express.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
