### ISSUE TITLE
Quick Start fails

### ISSUE THREAD

**Issue by K2AAE** [electron/electron#27726]
Install current LTS Node.js
Following the steps (missing some?) https://www.electronjs.org/docs/tutorial/quick-start fails.

**Comment by hovancik** [comment]
What's the node version? What's the os/version? What exactly did you do? What errors did you get?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. If you have a substantive reproducible issue, you are welcome to open a new issue.
