### ISSUE TITLE
Blank Screen on Electron App 

### ISSUE THREAD

**Issue by jhalaa** [electron/electron#27765]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  *  mac
  * windows

### Expected Behavior
Electron windows should not be blank after putting the system sleep for 48 hours and then using the app

### Actual Behavior
The main window and all the new windows are blank and will not load. Quitting and restarting the app makes the app work as normal.

### To Reproduce

This is usually triggered by putting the system sleep for 48 hours and then using the app.

### Additional Information

When we get into this situation, we catch an error from the did-fail-load event. The error code is -2 and we know that this is a generic network error. Is there any workaround for this? Or a way to get more information about this generic error?
This seems related to https://github.com/electron/electron/issues/2357  but this has already been closed

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by manojty** [comment]
@nornagon Thanks for responding promptly! This issue mostly happens when we keep the machine in sleep mode for more than 48 hours. After user wakes it up and start using the application, Electron is not able to load the content in the Window and raise an event "did-fail-load" with generic network failure error code -2. We are wondering if you could help us gather more useful information around why such error happens and if we could do something to circumvent it. When we relaunch the app after quitting it, it works just fine. This indicates that Electron gets into a weird state when the system sleeps for a very long time/  If it rings some bells as the similar issue  has been reported by others as well, please help us narrow it down.

**Comment by nornagon** [comment]
@manojty does this happen with a "hello world" Electron app? e.g. can you try launching http://github.com/electron/electron-quick-start and triggering the conditions that put your app into a weird state?

I haven't heard of this happening to other apps.

**Comment by manojty** [comment]
Thanks for confirming @nornagon! We are trying to come up with sample test app to repro this issue. This issue does not repro easily and so far mostly Mac users have encountered it after they put their system for sleep for more than 48 hours. So this issue is very elusive and sporadic in nature thus far. We are reaching out to you if there is way to get deeper logs from Electron so that we can know the reason behind Network error code -2 (thrown by Chromium) during content load failure? Or if there is way to workaround by reinitializing some Electron components to address some sort of staleness due to longer sleep state of the system? Best!

**Comment by nornagon** [comment]
You could try a net log: https://www.electronjs.org/docs/api/net-log

**Comment by nornagon** [comment]
I'm closing this as it's been inactive for a while without a repro, but I'll happily reopen if there's further information available.

**Comment by JuanIrache** [comment]
I seem to be having a very similar issue on Windows, with Electron 13.3.0

Not sure how I can gather logs, as the app just goes irresponsive and neither main or render seem to print errors I can easily track
