### ISSUE TITLE
resource sharing between electron apps

### ISSUE THREAD

**Issue by xeome** [electron/electron#27832]
can something like an electron hub be done?
for example lets say i have discord and chromium open on my computer
if i use electron version of discord and normal chromium with it i get more ram usage
but if i use discord in web and create another chromium tab memory usage decreases significantly
now lets say i have microsoft teams, spotify, discord, and chromium
if i use them all in browser it uses significantly lesser memory
so a hub for sharing memory and electron apps running as a child process
and perhaps saving disk space too because they dont have to ship with electron

**Comment by kloverde** [comment]
I'm not a member of the Electron project, so this is just one random person's opinion.

The topic of creating an Electron runtime has come up many times before.  Speaking as a Java developer, I don't favor this.  Java proclaimed itself to be the "write once, run anywhere" language because you have one runtime environment installed on a machine.  This idea failed because different applications need different versions of the runtime, and for a non-technical user it's just straight-up impossible to get multiple versions of Java to work on a machine.  Java is now only used in enterprise development.

Yes, there are ways to package a JRE with a Java application, but that comes with the downside of significantly increasing the distribution size.  Granted, Electron has no advantage in that area, becaues Electron applications are huge, but I'd rather have a huge Electron app with far easier to use UI tech than to write a UI in Java.

I find Electron exciting because we finally have something that **IS** write once, run anywhere.  I feel that creating an Electron runtime would send Electron to the same fate Java met on the desktop.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by p32929** [comment]
@xeome 
I just entered github to write this, but you wrote this already, which is awesome.

BTW, it probably should be labeled as Feature request. Otherwise, the Bot might think it as a question
