### ISSUE TITLE
In Linux systems, using the tray function, setContextMenu is called twice, causing the tray icon to appear twice

### ISSUE THREAD

**Issue by r4ggj** [electron/electron#27850]
The system is DEEPIN or UOS.
Libappindicator1 and Libappindicator3-1 coexist in the system.
I don't know how Electron solves this problem, I'm very confused @probablycorey @lsegal @vitaliel @anaisbetts

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
