### ISSUE TITLE
nsis   Win7 has stopped working after switching the installation directory

### ISSUE THREAD

**Issue by coderzhouyou** [electron/electron#27875]
![image](https://user-images.githubusercontent.com/26644767/108809633-4117bc80-75e4-11eb-8414-cddd783a3496.png)

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
