### ISSUE TITLE
[Feature Request]: There way to hide "Redirecting to..." message?

### ISSUE THREAD

**Issue by iZume** [electron/electron#27909]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

I want hide message "redirecting to.." when use window.location.href or force load another page

**Proposed Solution**

way to prevent this default

**Alternatives Considered**

i seek global var to hide this message

**Additional Information**

this is unnecesary page to my program

![image](https://user-images.githubusercontent.com/11727616/109184682-ddf96780-7754-11eb-8060-9543bd9a8081.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
