### ISSUE TITLE
how do I keep devtools extensions when build app

### ISSUE THREAD

**Issue by royhuang813** [electron/electron#27951]
i can use devtools extensions in dev, but cant in the product. There are some extensions that need to be used in the product, how can i do it plz

**Comment by codebytere** [comment]
/
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
