### ISSUE TITLE
How to change appId (and productName) without breaking autoUpdater?

### ISSUE THREAD

**Issue by timche** [electron/electron#27963]
* **electron-builder Version**: 22.9.1

* **Electron Version**: 10.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS, Linux, Windows

I want to rename an Electron app (packaged with `electron-builder`), but when I change the `appId` in `package.json` from e.g. `com.foo.x` to `com.bar.y`, Electron's built-in `autoUpdater` fails with:

```
Error: Error: Could not locate update bundle for com.foo.x within file:///Users/<username>/Library/Caches/com.foo.x.ShipIt/update.<random_hash>/
```

After searching for this issue, I only found [one other person](https://github.com/electron-userland/electron-builder/issues/4994) dealing with the same problem.

Neither the Electron nor the `electron-builder` docs are giving any hints or guide on how to change it. Is it even possible? I'd like to avoid to ask the users to download the update manually.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Electron Discord](https://discord.com/invite/electron) that should be willing to point you in the right direction.
