### ISSUE TITLE
Naming App in arabic

### ISSUE THREAD

**Issue by Barbarosse** [electron/electron#28002]
When naming my App in Arabic in the Package.json, 
`{
  "name": "برنامج",
`
I get this error and the program won't start
`npm ERR! Invalid name: "برنامج"`

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by nornagon** [comment]
@Barbarosse I believe this is an npm issue. e.g. `npm install` also fails when `"name": "برنامج"` is in package.json.

Consider using [app.setName](https://www.electronjs.org/docs/api/app#appsetnamename) instead.
