### ISSUE TITLE
printToPDF does not complete after angular auto reload

### ISSUE THREAD

**Issue by gnujeremie** [electron/electron#28018]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
11.0.3
* **Operating System:**
macOS 11.1
* **Last Known Working Electron version:**
  * 

### Expected Behavior
The page is printed to PD

### Actual Behavior
The page is not printed

### To Reproduce
I am using electron with angular. In development mode, when I start my application, it starts the angular webserver using ng serve. 
Once my application is started, I can print to pdf using this code : 

```
                            const modal = new BrowserWindow({
                                show: false,
                                x: 50,
                                y: 50,
                                webPreferences: {
                                    nodeIntegration: true,
                                    contextIsolation: false
                                }
                            });
                            // Charge le fichier dans la nouvelle fenêtre
                            modal.loadURL('file://' + filePath);

                            // Un fois le chargement dans la fenêtre terminé, on fait le traitement pour la transformation en PDF
                            modal.webContents.on('did-finish-load', () => {
                                // Option de transformation en PDF
                                const pdfOptions = {
                                    marginsType: 1,
                                    pageSize: 'A4',
                                    printBackground: true,
                                    printSelectionOnly: false,
                                    landscape: false
                                };
                                // On lance la transformation en PDF
                                modal.webContents.printToPDF(pdfOptions).then((data) => {
                                    const filePathPdf = filePath + '.pdf';

                                    // On enregistre le fichier PDF généré afin de pouvoir le lire
                                    fs.writeFile(filePathPdf, data, (e) => {
                                        if (e) {
                                            console.log(e);
                                        } else {
                                            // On charge le PDF avec l'application configurée par défaut
                                            shell.openPath(filePathPdf).then(() => {
                                                this._win.webContents.send('download-finished');
                                            }).catch((e) => {
                                                this._win.webContents.send('download-finished');
                                                console.log(e);
                                            });
                                        }
                                    });
                                }).catch(e => {
                                    console.log(e);
                                });

                                // On supprime le premier fichier téléchargé (fichier HTML)
                                this.deleteFile(filePath);
                            });

```

When I update my angular code, the application (angular only) is reloaded in the electron application. When I try then to print to pdf, I can trace the code until `modal.webContents.printToPDF`, but then it never completes (no then, no catch).

Thanks for your help

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Hey, I'm not sure that I'm understanding this bug report completely -- does the issue _require_ Angular in order to be reproduced, or can it be done in vanilla JS + Electron?

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.
