### ISSUE TITLE
'require' is not defined in Electron v12.0.0 in renderer process

### ISSUE THREAD

**Issue by highestage** [electron/electron#28034]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * macOS 11.1
* **Last Known Working Electron version:**
  * 11.2.1

### Expected Behavior

'require' should import the module in the renderer process

### Actual Behavior

getting undefined error: 'Uncaught ReferenceError: require is not defined'
### To Reproduce

in index.html file, just import any electron module

**Comment by pushkin-** [comment]
see [this](https://github.com/electron/electron/issues/28017)

**Comment by ckerr** [comment]
This is intentional and is listed in the [breaking changes](https://github.com/electron/electron/blob/master/docs/breaking-changes.md) doc, `contextIsolation` now defaults to `true` rather than `false` in 12.0.0 to make renderer processes safer.

The safer solution is to take renderer code that uses require/import and move it into a preload script, then carefully control what gets exported from the preload script & is visible to scripts running in the renderer process. For example, instead of exposing all of `fs` such that `fs.appendFile()` is callable from the renderer, you might have the preload script export a function `appendToLog()` that uses `fs.appendFile()`. This way if any hostile code is loaded over the network somehow, its attack surface will be `appendToLog()` instead of all of `fs`.

Alternatively, if you have a lot of code in place already and migration is nontrivial, you may want to explicitly set `contextIsolation: false` in the short term to get up and running again until migration is complete.

**Comment by highestage** [comment]
Setting `contextIsolation` to `false` worked out for me. However, its a good point to migrate to the much safer route. 

Thanks everyone!

**Comment by highestage** [comment]
What issue are you facing? Setting `contextIsolation` to `false` worked for
me. Do you have `nodeIntegration` set to `true`? Because the issue
suggested by @ckerr worked for me.

**Comment by IonicaBizau** [comment]
@highestage I just had two different windows and I set the `contextIsolation` only for one of them. After setting it for both, it works nicely. 😄 Thanks!

**Comment by timoncp** [comment]
@ckerr Thank you! This should be on the electron README front page! Spent too many hours trying to get this working with create-react-app without using existing boilerplate. Thought it might be create-react-app, or webpack, or react-scripts and what not...

**Comment by SashaDesigN** [comment]
Worked for me when I passed directly in window settings alongside with webprefferences:
```
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    nodeIntegration: true,
    contextIsolation: false,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      preload: path.join(__dirname, 'preload.js')
    }
  })
```
