### ISSUE TITLE
how to use renderProcess in vue component

### ISSUE THREAD

**Issue by HomyeeKing** [electron/electron#28032]
```vue
<tamplate>

< button @click = 'test'>click me</button>
</template>


<script setup>
import electron from 'electron' // __dirname is not defined 
const electrom from 'electron' // require is not defined
const click = ()=>{
   // click logic, render process logic

}

</script>
```

 how to make it work, it confuses me for about two days .... 
or I just using origin html to quick development.....

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Electron Discord](https://discord.com/invite/electron) that should be willing to point you in the right direction.
