### ISSUE TITLE
[Bug]: Getting blank screen after reload

### ISSUE THREAD

**Issue by clark-97** [electron/electron#28289]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

I don't know

### Expected Behavior

reload webpage like broweser

### Actual Behavior

Getting blank screen after reload

### Testcase Gist URL

https://gist.github.com/clark-97/35b1bda0acfc604c714178795e9659a9

I guess it releted #14978 which is closed. 
steps to reproduce
```sh
npm install -g @angular/cli
ng new electron-test
cd electron-test
npm install electron --save-dev
npm install electron-builder --save-dev
nano src/index.html
nano index.js
nano package.json
ng build
npm run build
```
then I run release/win-unpacked/electron-test.exe, it load webpage normally. after click CTRL+R, it geting blank
<img width="960" alt="Snipaste_2021-03-19_15-59-21" src="https://user-images.githubusercontent.com/66821547/111749024-30e5bb00-88cc-11eb-8cd9-9e4bc545ed13.png">

the two don't work
https://github.com/electron/electron/issues/14978#issuecomment-510092294
https://github.com/electron/electron/issues/14978#issuecomment-610773951

the two work, but still get blank in short, then load page normally, and they are not friendly angualr router, after reload webpage, the page will go to default router, not original page
https://github.com/electron/electron/issues/14978#issuecomment-535191746
https://github.com/electron/electron/issues/14978#issuecomment-785097599

**Comment by pushkin-** [comment]
Does moving the window make it not blank? I was experiencing another "blank window" [issue](https://github.com/electron/electron/issues/28255) on 20H2 Windows as well

**Comment by clark-97** [comment]
> Does moving the window make it not blank?

@pushkin- no, I can't make it not blank by moving the window.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by clark-97** [comment]
@ckerr okay, I am trying Fiddle, but it's too slow to download electron V12.0.1 https://github.com/electron/fiddle/issues/258#issuecomment-804649837

**Comment by clark-97** [comment]
https://gist.github.com/clark-97/acb47c1f87132f4ca73c913fc0c5d61a , preload.js is too big, I am not sure whether it can be download completely, then I created an repository https://github.com/clark-97/angular-reload-webpage

**Comment by clark-97** [comment]
@ckerr Is there any new progress?
