### ISSUE TITLE
京东抢购助手已不能使用。

### ISSUE THREAD

**Issue by 50095137** [electron/electron#28291]
京东抢购助手已不能使用。请更新。谢谢你。

**Comment by 50095137** [comment]
京东抢购助手已不能使用。请更新。谢谢你。

**Comment by awong1900** [comment]
> 京东抢购助手已不能使用。请更新。谢谢你。

这不是好的提问方式。您应该用英文详细描述的问题。 You need use english.

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
