### ISSUE TITLE
[Bug]: clicking on a link before loadURL has resolved causes the promise to reject, even if the link navigation was prevented

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28338]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1, 11.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v1909

### What arch are you using?

x64

### Expected Behavior

I expect that calling `preventDefault` in the `will-navigate` handler will prevent us from attempting the navigation

### Actual Behavior

This doesn't seem to happen if we're in the middle of a `loadURL` call

this issue may very well be a dupe of [this one](https://github.com/electron/electron/issues/17526) and related to [this one](https://github.com/electron/electron/issues/19847) though I'm not calling `loadURL` twice.

I'm experiencing an issue in my app where if there's network delay, I make a `loadURL` and click a link on the main page before `loadURL` has finished, we get an `ERR_ABORTED` error. From reading in other issues, this is expected when a navigation happens in the middle of a navigation.

So I attempted to solve this by canceling the navigation in the `will-navigate` handler when the main window's webcontents are still loading (`isLoadingMainFrame()`), however, this doesn't solve the crash. The navigation is prevented, but `WebContents::did-start-navigation` has already fired for whatever reason (I'd expect it to fire *after* `will-navigate`), and we get the crash

1. add network delay. What I did was start Fiddler, Rules -> Performance -> Simulate Modem speeds
2. start main.js
3. Click a link (like the "Sign Up" link)
4. observe crash:

![image](https://user-images.githubusercontent.com/6374473/112063138-f0d24280-8b2e-11eb-9789-291049488711.png)

main.js:
```
(async () => {
	const { app, BrowserWindow, dialog } = require("electron");
	app.on("window-all-closed", async () => {
		app.quit();
	});

	await app.whenReady();
	const mainWindow = new BrowserWindow();
	mainWindow.webContents.on("will-navigate", (e) => {
		if (mainWindow.webContents.isLoadingMainFrame()) {
			e.preventDefault();
		}
	});
	try {
		await mainWindow.loadURL("https://github.com/");
	}
	catch (e) {
		dialog.showErrorBox("Error", e.message);
	}
})();
```

**Comment by nornagon** [comment]
Here's a Fiddle version using an in-process server that responds slowly: https://gist.github.com/0926377bbb9d14cd9319f8d26698e543

This is somewhat intentional: we explicitly listen to `did-start-navigation` and cancel the promise with `ERR_ABORTED` in navigation-controller.ts: https://github.com/electron/electron/blob/665ac6f9c830edbf85596369b49844e1b910c59a/lib/browser/navigation-controller.ts#L111

Both `will-navigate` and `did-start-navigation` are pretty direct exposures of the underlying Chromium callbacks. Perhaps we should be hooking something other than `did-start-navigation` in `loadURL` to reject the promise if the page is navigated away before finishing the load?

side note, i'm changing the title here to reflect that this is a rejected promise rather than a crash per se.

**Comment by pushkin-** [comment]
repros in Electron 21

**Comment by pushkin-** [comment]
repros in v22

**Comment by pushkin-** [comment]
bump
