### ISSUE TITLE
Re-enable nan test: typedarrays-test.js

### ISSUE THREAD

**Issue by nornagon** [electron/electron#28414]
The `typedarrays-test.js` test is failing due to an incompatibility between libc++ and libstdc++. 

We should build these tests against libc++ to fix this and prevent future incompatibilities.

**Comment by VerteDinde** [comment]
Some additional context on this issue (thanks @MarshallOfSound!):

`electron-rebuild` already has an option to use the same clang compiler as Electron itself, and on Linux it will use the same sysroot as well. We should update these flags so that running `electron-rebuild` uses the same libc++ (and libc++ flags) as the normal Electron build.

This is very open ended, as there are quite a few problems to solve here:

- How do you ensure the build flags are the same?
- How do you pull the right version of libc++?
-  Etc.

The end goal here is that native node modules are built in the exact same way as Electron itself, to ensure maximum compatibility.
