### ISSUE TITLE
desktopCapturer entire screen not working and some of the screens thumbnails broken

### ISSUE THREAD

**Issue by crashedpixel** [electron/electron#28426]
When I run ```await navigator.mediaDevices.getDisplayMedia()``` in the browser I can see all of the thumbnails to the screens and the "entire screen" is working.

When I run this 
```
desktopCapturer.getSources({ types: ['window', 'screen'] }).then(async sources => {
	data(sources.map(({ id, name, thumbnail }) => ({id, name, thumbnail: thumbnail.toDataURL()})));
				});
``` 

I get access to all the id's, names etc but the thumbnails are broken on all but the "entire screen" and the "electron app".

And another issue is for some reason the "entire screen" doesn't see anything but the desktop and the electron app. I thought it might be a permission issue as I read something about that. I tried calling ```await systemPreferences.getMediaAccessStatus('screen')``` but it returns denied.

As you see in this screenshot the "entire screen" doesn't see the browser in the background...

![Screen Shot 2021-03-28 at 4 46 15 PM](https://user-images.githubusercontent.com/69129964/112769338-186d5300-8fe6-11eb-8a1b-a4836fc59693.png)

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information. For example from this information I don't know what version of Electron you're testing with.

Also, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks for understanding and meeting us half way :grinning:
