### ISSUE TITLE
bug zoom/unzoom

### ISSUE THREAD

**Issue by JFailBreak** [electron/electron#28420]
i unzoomed discord bot client and now I cant unzoom i tried uninstalling and reinstalling, didn't work

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:
