### ISSUE TITLE
[Bug]: Tray icon disappear when package name contain scope

### ISSUE THREAD

**Issue by Armaldio** [electron/electron#28421]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro

### What arch are you using?

x64

### Expected Behavior

When using a scoped package name, Electron on linux should show an icon

### Actual Behavior

When using a scoped package name, Electron on linux **only** is not showing the tray icon

### Testcase Gist URL

https://github.com/Armaldio/electron-tray-error

**Comment by ckerr** [comment]
Confirmed.

Tested on Ubuntu 20.10 with Electron 11.0.0, 12.0.0, and 12.0.2.

If I invoke Electron with `/path/to/electron .` then the tray icon does not appear.
If I invoke Electron with `/path/to/electron main.js` the tray icon appears and works as it should.

So @Armaldio the good news is maybe you have a short-term workaround by changing the invocation in your package.json :slightly_smiling_face: 

Still, I'd like to understand _why_ passing a directory rather than a filename to Electron would cause this different behavior.

**Comment by MarshallOfSound** [comment]
> Still, I'd like to understand why passing a directory rather than a filename to Electron would cause this different behavior.

Launching electron from a directory automatically loads the apps name from the `name` or `productName` field of the `package.json` file.  Loading from a file does not.  My guess here is this platform does not let apps with `@` or `/` in their name show tray icons (probably due to the `/` being recognized as a path thing)

**Comment by pedro-pedrosa** [comment]
Please document this on the `Tray` page documentation. It's such a hard bug to find and I was going mental over this.

**Comment by nornagon** [comment]
@pedro-pedrosa i'd be happy to review a PR!
