### ISSUE TITLE
Electron call node.js addon throw exception:”Error:Module did not self-register”

### ISSUE THREAD

**Issue by huhaha123** [electron/electron#28488]
I have developed a node.js addon Demo.node by node-gyp. My node.js version is 14.16.0, the node-gyp I use is also 14.16.0. This Demo.node woks ok when I call it in node, but when I call it in electron it did not work.

When I test this Demo.node, I create a demo-test.js. In this js file, my code is as follow:
```
const addonpath = 'C:/Windows/System32/Demo.node';
const addon = require(addonpath);
```
and I use follow command to test:
`node demo-test.js`
this works ok.

My electron project info as follow:
Electron version:12.0.2
Node version:14.16.0
Chromium:89.0.4389.90
I use addon in my main.js file, my code is as follow:
```
function createWindow() {
  mainWindow = new BrowserWindow({ 
    width: 800, 
    heigth: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false
    }
   });
  mainWindow.loadURL(`file://${__dirname}/page.html`);
  mainWindow.on('closed', () => {
    mainWindow = null;
  });
   const addonpath = 'C:/Windows/System32/Demo.node';
const addon = require(addonpath);
}
```
When I debug, electron throw exception at line
const addon = require(addonpath);

What is wrong with my electron project? The same addon, why can it work in node, but can not work in my electron project?

**Comment by VerteDinde** [comment]
Hey @huhaha123, thanks for filing an issue for Electron!

Because we're a small team, we use this issue tracker to track larger project bugs, and try to avoid debugging individual projects. Could you try joining our Discord server and asking your question in one of our help channels there? You'll likely find help more quickly as well: https://discord.gg/electron

Thanks for understanding!
