### ISSUE TITLE
[Feature Request]: desktopCapturer Windows UAC

### ISSUE THREAD

**Issue by danielehrhardt** [electron/electron#28522]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The desktopCapturer does not capture the Windows UAC. 
I tried to run the Electron App as Administrator but it still does not work. 

I am currently building a Remote Control Desktop App. 
Two similar Tools are able to show the Windows UAC. 

### Proposed Solution

Maybe there should be a flag or request some permission to allow this kind of Feature. 

### Alternatives Considered

- 

### Additional Information

-

![image](https://user-images.githubusercontent.com/19570043/113638583-7ef21100-9677-11eb-8731-8b7501ae97b0.png)

**Comment by nornagon** [comment]
Is this even possible? I'd guess that UAC is protected from screen capture at the OS level.

Are there apps capable of capturing UAC?

**Comment by danielehrhardt** [comment]
> Is this even possible? I'd guess that UAC is protected from screen capture at the OS level.
> 
> Are there apps capable of capturing UAC?

Teamviewer,
AnyDesk,
UltraVNC

**Comment by baconbrad** [comment]
This is intentional. When UAC is activated it runs it in secure desktop mode and tries to isolate UAC from third party applications as much as possible. At this point only SYSTEM processes should be able to interact with it. [You can circumvent this](https://www.download3k.com/articles/How-to-screen-capture-a-User-Account-Control-UAC-prompt-in-Windows-10-or-8-00450) if you want this behavior for a certain machine but I do not recommend this as it does weaken security.

TeamViewer, Windows RDP, etc all get past this restriction by having the privileges of their application elevated.

I don't see Electron adding this ability as it would make all Electron applications require admin privileges as this isn't something that can be added as an option so easy. This would come more into the realm of when Electron is built. You can try an [ Electron specific exe.manifiest trick](https://www.authentise.com/post/electron-and-uac-on-windows) and see if this gets you a little closer to your goal. But from my understanding [Electron Packager can do invoking parameters too](https://github.com/electron/electron-packager/pull/610).

**Comment by nornagon** [comment]
Given what @baconbrad described above I'm going to close this as status/wontfix.

**Comment by danielehrhardt** [comment]
> I don't see Electron adding this ability as it would make all Electron applications require admin privileges as this isn't something that can be added as an option so easy.

I mean this should not be the default. The Application should require Admin privileges at runtime or start a sub process. 

I am not sure if 'wontfix' is here the correct decision. 

I already tried out to start the Application as Admin, but this did not help. 

I will try my best to find a Solution myself. But for me this is something Electron should support, even if you do not see the use cases right now, I can say there are a lot of use cases. (Remote Help, recording, ...)

**Comment by baconbrad** [comment]
@danielehrhardt This is something technically and intentionally meant to be difficult to achieve for security reasons. Especially elevating a program to SYSTEM if that is a firm requirement to achieve this. While it is ideal for Electron to cover as many use cases as possible it would be difficult to implement and support this use case unfortunately.

**Comment by danielehrhardt** [comment]
> @danielehrhardt This is something technically and intentionally meant to be difficult to achieve for security reasons. Especially elevating a program to SYSTEM if that is a firm requirement to achieve this. While it is ideal for Electron to cover as many use cases as possible it would be difficult to implement and support this use case unfortunately.

More and more people do request this. Maybe it makes sense to think twice.

**Comment by sanket1726** [comment]
It will be a better resolution for this if Electron provides option of sharing UAC and Secure Desktop Mode screen if application is signed.
Or provide some flags.
