### ISSUE TITLE
[Bug]: simpleFullscreen toggle will stop painting when backgroundThrottling is false on Mac

### ISSUE THREAD

**Issue by zengdongbao** [electron/electron#28632]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS 10.14.6

### What arch are you using?

x64

### Last Known Working Electron version

6.1.7

### Expected Behavior

I create a  simpeFullscreen window, and set backgroundThrottling is false.
I can toggle simpeFullscreen status as well.

### Actual Behavior

toggle simpeFullscreen status will make window stop painting.

**Comment by zengdongbao** [comment]
https://user-images.githubusercontent.com/265074/114537811-380ea780-9c85-11eb-939a-a865a3c9b141.mp4

this is the capture video

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on, v6.x, has been superseded by newer releases and is no longer supported. In order for us to triage this issue, you will need to demonstrate that it occurs on a [supported](https://www.electronjs.org/docs/tutorial/support) version

After you've responded, please @ me in a followup comment. This issue will otherwise be closed in 7 days.

Thanks in advance! Your help is appreciated.

**Comment by zengdongbao** [comment]
@codebytere The last supported version 10.0.0 had same bug result： not painting. 
 I tried all the versions, Last Known Working Electron version is 7.x

ps：minimize and restore window  repainted.

**Comment by codebytere** [comment]
Closing as this should be working in all latest supported versions.
