### ISSUE TITLE
I want disable open protocols link in webview?

### ISSUE THREAD

**Issue by zhenghanzheng** [electron/electron#28711]
What can I do disable open url like  "otherapp://asdasdasd"  in my app?    It's opened in webview

**Comment by AirFusion45** [comment]
You might want to try the `will-navigate` event here: https://www.electronjs.org/docs/api/web-contents#event-will-navigate
https://stackoverflow.com/questions/41068295/electron-prevent-cancel-page-navigation

**Comment by mlaurencin** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
