### ISSUE TITLE
[Feature Request]: trashItem can't use POSIX separator on Windows

### ISSUE THREAD

**Issue by WingDust** [electron/electron#28831]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

```js  
   const fs = require('fs')  
   console.log(
     fs.existsSync('G:/1.txt')
   );
   shell.trashItem('G:/1.txt').catch((reason)=>{
        console.log(reason);
    })
   shell.trashItem('G:\\1.txt').catch((reason)=>{
        console.log(reason);
    })
```
second trashItem will error `[Error: Failed to parse path]` in Windows

### Proposed Solution

   
```js
shell.trashItem('G:/1.txt').catch((reason)=>{
        console.log(reason);
  })
```
should direct support in Windows

### Alternatives Considered

```js
   shell.trashItem('G:\\1.txt').catch((reason)=>{
        console.log(reason);
    })
```

### Additional Information

none

**Comment by MarshallOfSound** [comment]
This is currently expected behavior, Electron APIs that take in file paths required resolved paths with the correct path separators.

This is very easy to do with `path.resolve` but supporting posix paths on windows comes with a myriad of edge cases that I'd rather not introduce to Electrons API surface

**Comment by WingDust** [comment]
if that Should explain in Doc with trashItem

**Comment by miniak** [comment]
@WingDust you can contribute the documentation change with a PR

**Comment by MarshallOfSound** [comment]
Closing per the comment in https://github.com/electron/electron/issues/28831#issuecomment-826370589

If someone wants to add docs around this PRs welcome, but the change to support posix paths is not something we'll do

**Comment by sammarshallou** [comment]
This also caught me out - it is a bit strange because all other fs APIs I've used in my app do work correctly with forward or mixed slashes. It's also a bit surprising because the native Win32 APIs (in C++, etc) do usually support both types of slash. I'll see how easy it is to submit a documentation change.
