### ISSUE TITLE
Electron9.0.5，The application has been running, and it was still in normal use yesterday afternoon. Today, the screen suddenly went blank, and it was restored after being hidden and displayed

### ISSUE THREAD

**Issue by ProvenceL** [electron/electron#28847]

**Comment by sofianguy** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

Thanks for understanding and meeting us half way 😀

**Comment by pushkin-** [comment]
sounds like [this](https://github.com/electron/electron/issues/28255) or [this](https://github.com/electron/electron/issues/27353) issue
