### ISSUE TITLE
[Feature Request]: Do not include FLoC in Electron

### ISSUE THREAD

**Issue by probablyup** [electron/electron#28951]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Google has begun to include FLoC (Federated Learning of Cohorts) functionality in Chromium as a replacement for tracking cookies. https://www.theverge.com/2021/4/16/22387492/google-floc-ad-tech-privacy-browsers-brave-vivaldi-edge-mozilla-chrome-safari

Other vendors composing Chromium have opted-out of this framework, will Electron do the same to preserve user privacy?

### Proposed Solution

n/a

### Alternatives Considered

n/a

### Additional Information

n/a

**Comment by MarshallOfSound** [comment]
Afaics we've never implemented or enabled floc.  Refs: https://github.com/electron/electron/blob/da8c35e3b256b4f9ad0c16edfbc2b56748b3a740/shell/browser/browser_process_impl.cc#L238-L240

It would be enabled in Chromium based browsers but because we directly embed //content we didn't get it by default and never implemented it.  Closing this out as it's a "we don't have it turned on" situation 🥳
