### ISSUE TITLE
[Bug]: Google Meet screen sharing not working

### ISSUE THREAD

**Issue by rimonhanna** [electron/electron#29080]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.x - 12.x

### What operating system are you using?

macOS

### Operating System Version

macOS 11.3

### What arch are you using?

x64

### Last Known Working Electron version

8.x

### Expected Behavior

Google Meet screen sharing to work when the website is loaded in an electron wrapper

### Actual Behavior

Google Meet just shows an error that my browser doesn't support screen sharing

### Additional Information

I built a the screen sharing source picker view and that was working perfectly in electron 8, latest version of google meet though released features that only work on newer version of chrome/chromium, hence why I'm trying to migrate to electron 12

Here is my branch for the migration:
https://github.com/rimonhanna/googleworkspace/tree/feature/latest-electron

So apparently the below chrome extension is needed for Google meet screen sharing to work, screen sharing used to work on older versions of electron <= 8.x because it used to use chrome instead of the bare bones chromium which included the extension, I tried loading this extension in my electron project, but it turns out electron doesn't support all the extension APIs needed for this to work :/

If someone has any ideas on how to get this working that would be appreciated

https://github.com/chromium/chromium/tree/master/chrome/browser/resources/hangout_services

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or requests for help with one's own project since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
