### ISSUE TITLE
Use desktop environment-aware file picker

### ISSUE THREAD

**Issue by Evpok** [electron/electron#2911]
At least when using Atom with Plasma DE, the file dialog is the GTK File Chooser one, which feels severely out-of-place (though one gets used to it from using other non-DE aware GTK apps). It would be nice if it could use QFileDialog as does Chromium.

**Comment by zcbenz** [comment]
Sounds good to me, the Chromium's dialog implementation can be a good start:
https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/libgtk2ui/select_file_dialog_impl_kde.cc.

**Comment by Evpok** [comment]
Good thinking! It doesn't actually use any Qt binding, it just invokes the command line utility `kdialog`. Seems easy enough.

**Comment by Evpok** [comment]
Keeping this as a reminder for myself if you don't mind.

The interesting point is in `https://github.com/atom/electron/tree/master/atom/browser/ui`. We have to

  - write `https://github.com/atom/electron/blob/master/atom/browser/ui/file_dialog_plasma.cc`
  - figure how to make atom use it if the current DE is Plasma
  - If we want to get fancy about it, figure a way to (possibly as an option) use it or a similar file picker for LXQt/other Qt based DEs (are there any ?).

**Comment by Siilwyn** [comment]
This is still needed right? I'd be interested in picking this up, not sure how to test though since I use Gnome...

**Comment by Thaodan** [comment]
QFileDialog would be good  every Qt based DE hooks their module in the provide  their native dialog if needed (look at frameworksintegration). I dont if its possible but using QFileDialog for every plattform would be possible too since it provides integration for every plattform.

**Comment by Siilwyn** [comment]
Never mind, doing this is above my current knowledge I will first need to learn more about C++ before being able to implement this. If anybody else is picking this up I would be interested in pair programming though.

**Comment by polarathene** [comment]
Using a few electron apps (GitKraken and Atom mostly), along with Chromium. Any updates on getting this supported? Or at least someone knowledgeable about the codebase that'd be happy to work with one of us to add the support?

**Comment by jhasse** [comment]
> I think I've heard of Flatpak packaged apps being able to use Qt file choosers, so that might work as a workaround?

I would even say that should be the way forward.

**Comment by Gim6626** [comment]
I think this feature is important too. Is there any progress on the issue?

**Comment by codebytere** [comment]
Hey all: a fix for this is in the works, and in the meantime here's a [module](https://www.npmjs.com/package/native-kde-file-open) to provide a workaround until it's been completed

**Comment by Thaodan** [comment]
Can you explain how you will fix this? Especially since the framework is 
usually shipped by the app it self and not the operating system.

**Comment by polarathene** [comment]
> Can you explain how you will fix this?

I assume something like environment variables would be checked when the app is launched? Qt does something like this to know what sort of file dialogue it should present iirc.

**Comment by jhasse** [comment]
When using Flatpak Portals the interface would be provided by `xdg-desktop-portal-kde` on KDE which uses Qt for file dialogs. See https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#KDE_implementation_of_portals

**Comment by keithzg** [comment]
Still very much awaiting this; as it stands now, in terms of desktop integration, Electron apps are undesirable compared to Chrome apps, which is somewhat of a perverse state of affairs!

**Comment by Rush** [comment]
Back in the day I wrote a small C library for run-time (shared library) swappable file dialog implementations: https://github.com/encharm/UELinuxNativeDialogs - run-time is important because user may not have the Qt library installed.

Supported ones are:
- GTK dialog
- Qt dialog

I think Qt dialog will use a KDE dialog when running in KDE. Would this help? I can improve my library upon request.

I just checked and everything still works:
![](https://rush.sh/18YTJlnxVrZDdIg0gC9Uiangwaw/screenshot.png)
![](https://rush.sh/_ckIGeZCU2RPp9eMiPp1Sbw3plc/screenshot.png)

**Comment by Thaodan** [comment]
> I think Qt dialog will use a KDE dialog when running in KDE. Would this 
> help? I can improve my library upon request.

Yes that is what frameworks integration is for.

https://api.kde.org/frameworks/frameworkintegration/html/index.html

It's a Qt platform integration plugin, this mechanic works with any program 
that provides this and not just KDE.

**Comment by Rush** [comment]
Anyway I think the logic could be as follows (click to edit):
[![](https://code2flow.com/D5x5AQ.svg)](https://code2flow.com/D5x5AQ)

The `dlopen` way is implemented in the repo I posted in my previous post.

**Comment by Thaodan** [comment]
You could also just use Qt and let Qt load the Gtk or whatever dialog.

**Comment by Rush** [comment]
Users may not want to have Qt installed. It's a big dependency just for a file dialog.

**Comment by Thaodan** [comment]
That's true what I tried to explain was that you could just implement 
electron using Qt  or at least use Qts Plattform abstraction to implement 
such things. The base part of Qt inst so large (5.1mb + platform plugin).

**Comment by mrmcq2u** [comment]
xdg-portals solve this issue right?

**Comment by TingPing** [comment]
It is probably a 10 line patch to switch `GtkFileChooser` usage to `GtkFileChooserNative` which then allows using `xdg-desktop-portal-kde` or `xdg-desktop-portal-gtk` depending on platform.

- https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html

**Comment by ssokolow** [comment]
Using `GtkFileChooserNative` would also avoid having to fine-tune "When do we use which dialog?" logic. 

> When the `org.freedesktop.portal.FileChooser` portal is available on the session bus, it is used to bring up an out-of-process file chooser. Depending on the kind of session the application is running in, this may or may not be a GTK+ file chooser.

**Comment by denisfalqueto** [comment]
> It is probably a 10 line patch to switch `GtkFileChooser` usage to `GtkFileChooserNative` which then allows using `xdg-desktop-portal-kde` or `xdg-desktop-portal-gtk` depending on platform.
> 
>     * https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html

I've made a fork and committed the corresponding changes, but I can't build electron and test it right now. If someone is willing to help, it would be very much appreciated.

https://github.com/denisfalqueto/electron

**Comment by nornagon** [comment]
Would be great if you could open a PR with [wip] in the title so we can see and comment on the changes!

**Comment by denisfalqueto** [comment]
> Would be great if you could open a PR with [wip] in the title so we can see and comment on the changes!

https://github.com/electron/electron/pull/15293

**Comment by dufferzafar** [comment]
@codebytere The [module that you mentioned](https://www.npmjs.com/package/native-kde-file-open), is it also available as an extension for VS Code? If not, how hard would it be to create one? I'm new to VSCode.

**Comment by rriemann** [comment]
It's open since 2015 and I am glad to see this may be resolved in early 2019! :smile:

**Comment by danbohea** [comment]
^ Always the most helpful comment in an OSS issue. So glad I'm subscribed.

**Comment by ssokolow** [comment]
I'm not a big fan of un-constructive comments either, but let's try to avoid sarcasm and keep a polite, professional atmosphere.

**Comment by Thaodan** [comment]
Arch as this opt depend:
kde-cli-tools: file deletion support (kioclient5) [Installiert]
So lets do that the same for KDE?
Portals would be also an option.

**Comment by ssokolow** [comment]
@Thaodan Unfortunately, the overhead for spawning a new process each time you want an open/save dialog gets irritating very quickly. Chrome did it and, as much as I'd like native dialogs, I had to force it back to GTK+ dialogs because I just couldn't stand the added sluggishness.

(Though, admittedly, that's partly because I'll middle-click a bunch of image links, then alternate between <kbd>Ctrl</kbd>+<kbd>S</kbd> and <kbd>Ctrl</kbd>+<kbd>W</kbd>, which makes any added delays very noticeable.)

Portals would avoid that because calling into the portal host over D-Bus doesn't require spawning a new process each time.

Also, portals would avoid the need to include "When do we use which picker?" logic in Electron when a user has more than one desktop installed and is mixing components. (Just use `GtkFileChooserNative` and it's the user's problem for not configuring their desktop and GTK the way they want.)

That said, if you do want to play with them, the commands you're looking for are
* `kdialog --getopenfilename [startDir] [filter]`
* `kdialog --getsavefilename [startDir] [filter]`
* `kdialog --getexistingdirectory [startDir]`
* `kdialog --getopenurl [startDir] [filter]`
* `kdialog --getsaveurl [startDir] [filter]`

They all require that you provide at least one argument, but will accept a filter without a startDir. (eg. you can pass `*.txt` and they'll recognize it as a filter and assume you want to start in the current working directory.

**Comment by Rush** [comment]
One thing to consider against a separate process file dialog is the inability of window managers to properly display modality in such cases. (for example block the primary window and dim the background)

**Comment by TingPing** [comment]
> One thing to consider against a separate process file dialog is the inability of window managers to properly display modality in such cases. (for example block the primary window and dim the background)

It passes the window id to the other process so on x11 it can work.

**Comment by ssokolow** [comment]
> It passes the window id to the other process so on x11 it can work.

It can work on Wayland too, if the portal host and compositor are written to work together, which makes sense, given that the DE is already supposed to write/customize both components to provide an integrated experience.

As for kdialog, that's done via this...

    --attach <winid>          Makes the dialog transient for an X app specified by winid

Zenity (GTK+'s equivalent) is confusing in that respect because it has `--modal` but appears to have no way to specify a parent window to be transient to. (Just the X11 class and name properties, which aren't even specific to a single process, let a lone a single window.)

**Comment by tristan957** [comment]
I will be taking a second crack at creating a PR for this issue since the last on never got merged.

**Comment by madprops** [comment]
Please support QT and KDE.

**Comment by TingPing** [comment]
@madprops The proposed solution supports Qt dialogs. (Perhaps read the discussion before uselessly bumping it)

**Comment by MurzNN** [comment]
Here https://github.com/codebytere/native-kde-file-open is workaround to open native KDE file open dialogs in current Electron.

**Comment by tristan957** [comment]
The PR is feature complete I think, so all that is left to do is figuring out is another serious code review from an electron contributor so we can decide if loading the module and functions as static classs members would be more beneficial.

**Comment by ShalokShalom** [comment]
Is there anything left to do, besides the code review?

**Comment by tristan957** [comment]
The PR might need a rebase, but I tested it and it worked, but I don't work with Electron at all, nor am I a contributor so someone would honestly need to plug in my branch of electron into their project and see if anything breaks.

**Comment by DemiMarie** [comment]
Can this be extended to handle Flatpak’s portal?  Right now the file picker is simply not compatible with the sandbox.

**Comment by tristan957** [comment]
The pr takes care of Flatpaks as well

**Comment by ssokolow** [comment]
@DemiMarie That happens automatically when using `GtkFileChooserNative`. GTK+ has built-in support for indirecting through Flatpak portals... it just requires applications to request OS-native file dialogs instead of always using the customizable GTK-provided ones.
