### ISSUE TITLE
[Bug]: Some of developer tools region also drag the electron app

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#29159]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 x86_64 5.11.0-16-generic

### What arch are you using?

x64

### Expected Behavior

All clicking inside the developer tool works well and not being interrupted by dragging the electron app.

### Actual Behavior

When I click the `option` and `close` tool inside the developer tool, it drags the electron app.

https://user-images.githubusercontent.com/61906684/118137437-666fd600-b42f-11eb-9443-ea1ebad1d0ec.mp4

### Additional Information

This bug only occurs if the dock position is on the left.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please provide a clear reproducible sample we can run in [Fiddle](https://github.com/electron/fiddle) or a repository.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by kimlimjustin** [comment]
Here's the Electron Fiddle: https://gist.github.com/kimlimjustin/7b402e7dac79fe338df4505813c6e26f

Things to note:
- Yellow background area is the draggable area
- To reproduce the bug, open developer tools, resize the developer tools to around 350 px (leaving 450 px of the main window), and switch dockside into the left side.
- Current way to fix this is by resizing the developer tools to extra large or extra small. 
Thanks

**Comment by kimlimjustin** [comment]
Update: this bug not only occur on Ubuntu, but also on Windows 10
