### ISSUE TITLE
[Bug]: mouse will tremble between arrow and grab when setIgnoreMouseEvents(true,{forward:true})

### ISSUE THREAD

**Issue by dream798** [electron/electron#29152]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Expected Behavior

 expected the mouse style is normal with grab not tremble 

### Actual Behavior

when set setIgnoreMouseEvents(true,{forward:true}) , the mouse will tremble between arrow and grab

### Additional Information
test case
https://gist.github.com/dream798/2910b197e1f0a781c4c7dd13b16a6b82

**Comment by dream798** [comment]
can some body help me ? thanks very much

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please provide a clear reproducible sample we can run in [Fiddle](https://github.com/electron/fiddle) or a repository.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by dream798** [comment]
@codebytere 
thank you

i hava make a test case , do you mean this like bottom link?
https://gist.github.com/dream798/2910b197e1f0a781c4c7dd13b16a6b82
