### ISSUE TITLE
[Bug]: flashFlame API does not work on windows 7

### ISSUE THREAD

**Issue by mafanwei** [electron/electron#29166]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.4.0

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Nothing happened.

### Actual Behavior

highlight.

**Comment by mafanwei** [comment]
I think flashWindow will work, but there is no api.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by mafanwei** [comment]
Why delete flashWindow API?

**Comment by mafanwei** [comment]
I can't find any way to make the windows 7 taskbar highlight, can you help me? This problem has been bothering me for a long time, thank you very much!
