### ISSUE TITLE
Lol crashes OS Catalina

### ISSUE THREAD

**Issue by lumpinator** [electron/electron#29167]
After the last lol patch league crashes wile running the overlay of Mobalytics desktop. Any solutions?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
