### ISSUE TITLE
[Feature Request]: Support arbitrary JSON-serializable extra data in the crash reporter

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#29184]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like to keep track of crashes in a very simple way, just by pinging a telemetry endpoint when crashes happen so that I can just keep track of the number of crashes. I don't want to set-up a full-blown crash dumps collector server at the moment.

The problem is my telemetry endpoint, and I'd imagine most telemetry endpoints are similar, either accept a GET request with an "events" query parameter, or a POST request with a JSON body containing an "events" object.

Crash reporter currently only allows me to pass it a `Record<string, string>` as the value of it's "extra" option, and the request is always POST, meaning that just doesn't work with my telemetry endpoint.

### Proposed Solution

I think it'd make sense to allow for any JSON-serializable value as the value of the "extra" option, which would make this way more flexible.

Alternatively adding a switch for instructing the crash reporter to make a GET request would solve the issue too for me.

### Alternatives Considered

Crying.

### Additional Information

Apparently this section must be filled too or I can't submit the issue, so here you go: the average lifespan of a giraffe is about 25 years.

**Comment by nohhhon** [comment]
firefly-beetle.jpg
<https://drive.google.com/file/d/1NXitAcweugURm0e3HvAADzOYbVLWVkim8A/view?usp=drivesdk>



Thats a huge amount of electricity..
https://www.instagram.com/p/B1BARz3pIWQ/?igshid=15ihvdyc02zxz

**Comment by poiru** [comment]
You could probably achieve something similar by using `uploadToServer: false` when configuring `crashReporter` so that you could manually enumerate the crashes in `app.getPath('crashDumps')` and make a request your telemetry endpoint with `net`.

To handle main process crashes, you could do that on startup and periodically from them on. Also be sure to delete files in that directory after you've let your telemetry endpoint know about them.

**Comment by fabiospampinato** [comment]
@poiru that's too laborious, I should just be able to flip a switch in the crash reporter or just pass it some JSON-serializable data.

Also I'm not sure if that would even work just as well as the crash reporter does, for example hypothetically the main process may crash and the user may then delete the app, in which case you'll never see the crash report that way.

**Comment by nornagon** [comment]
I agree this should be possible; see e.g. https://backtrace.io/blog/announcements/crashpad-with-file-attachments/ (which Backtrace [forked crashpad](https://github.com/backtrace-labs/crashpad) to add). I believe some Sentry folks are also interested in this, cc @jan-auer

**Comment by jan-auer** [comment]
In the Sentry Electron SDK, we're happy with serializing JSON to string. The actual problem are rather the character limitations, which require us to chunk large payloads into multiple fields and stitch them back on the server. 

The way @fabiospampinato sounds useful in principle. It would essentially mean that the crash reporter issues two requests: one for the minidump, and another for JSON data. For telemetry servers that do not offer multipart endpoints, this would make things much easier. Sentry does support multipart, however, and we expect all payloads (minidump and extra) in a _single_ request, which is why that would not be an option. 

I'm afraid, file attachments wouldn't solve these either, because you'd still be issuing a multipart POST. That said, we would be highly interested in support for file attachments in Electron directly. Right now, the Sentry Electron SDK achieves this by performing manual uploads just like @poiru mentions in https://github.com/electron/electron/issues/29184#issuecomment-842133930. That comes with many disadvantages, most notably upload delays and unreliable uploads of crashes during startup. 

We also maintaining a [crashpad fork](https://github.com/getsentry/crashpad) with attachment support (among other tweaks), if that is of interest.

**Comment by nornagon** [comment]
Ah, er, it looks like I misread the top post here. It _would_ be convenient to be able to attach arbitrary files to crash dumps (e.g. log files? configuration? etc.) as part of a multipart upload, but I don't think it's reasonable to support posting crashes with GET or allowing non-strings in `extra`. I'm going to close this for now.
