### ISSUE TITLE
Asking for an example

### ISSUE THREAD

**Issue by kry008** [electron/electron#29185]
Good morning, I would like to ask you for some simple application with comments or a good tutorial for beginners.

**Comment by Raheemshah2809** [comment]
https://www.youtube.com/watch?v=kN1Czs0m1SU

this one was quite good,

**Comment by Raheemshah2809** [comment]
https://medium.com/@voltx180/a-beginners-guide-to-electron-js-1679fd7b6e4f

https://www.tutorialspoint.com/electron/index.htm

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
