### ISSUE TITLE
Window height issue

### ISSUE THREAD

**Issue by sivakrrish1994** [electron/electron#29190]
Version: electron@12.0.7
OS: Ubuntu 18.04.5 LTS

On setting maximize window, need to consider the autohide/fixed dock of the system'. So without considering the dock its fully maximized & getting hidden by dock menu.

[Screenshot](https://drive.google.com/file/d/1FjYM1f0nRzrEuLI3AV6h1PB_VNFbZFcO/view?usp=sharing)

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sivakrrish1994** [comment]
https://github.com/electron/electron/issues/29203
