### ISSUE TITLE
[Bug]: Error [RunScriptError]: Run "C:\Windows\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1

### ISSUE THREAD

**Issue by AKclown** [electron/electron#29273]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^3.1.9

### What operating system are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Last Known Working Electron version

^3.1.9

### Expected Behavior

Able to pack normally

### Actual Behavior

The following error was reported when I installed the package in the last step. This problem has troubled me for a long time. Please give me some suggestions. I will be very grateful.
![image](https://user-images.githubusercontent.com/33648653/119101632-c546d800-ba4b-11eb-8a7f-a563fcf9bca2.png)

### Additional Information

python:2.7.18
![image](https://user-images.githubusercontent.com/33648653/119101955-1fe03400-ba4c-11eb-89ae-1bc2d82a8cee.png)

**Comment by Prinzhorn** [comment]
electron-builder 20.44.4 was released **Jun 21, 2019**. Try a recent version.

**Comment by AKclown** [comment]
Thank you so much, you saved me, thank you so much。

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
