### ISSUE TITLE
Very high CPU load with serialport input

### ISSUE THREAD

**Issue by 0x80** [electron/electron#2928]
I have a problem with Electron in combination with [serialport](https://github.com/voodootikigod/node-serialport). I need to talk to a device which emits frames of 519 bytes at an interval of 27ms and a baudrate of 115200. So nothing spectacular really. 

When I run the test code directly in Node it runs fine and uses less than 2% cpu. If I then run the exact same code in Electron my CPU goes through the roof at 130%. 

I've tested the code on OSX with iojs v1, v2 and more recently node v4.1.1. The behavior is exactly the same. Also it doesn't make a difference if I run the code in the Electron main or renderer process.

I've shared my test code [here](https://github.com/0x80/electron-serialport-test). Of course without the device you can't use the serialport test code without altering it a little.

I'm hoping someone can give me pointers on how to investigate further, maybe by profiling the main process? I would love to use Electron for the project but with this bug it's not an option.

**Comment by zcbenz** [comment]
We have some issues with low level modules like serialport since the way they post events is keep waking up our Node.js message loop, fixing this is impossible or extremely hard.

A popular way to work around this is to fork a Node process to use `serialport` and then post things back, in Electron `child_process.fork` should work perfectly in this case. Maybe this will work for you?

**Comment by 0x80** [comment]
Thanks for the feedback. A process fork seems like a plausible workaround. Could you be a bit more specific about what is going on with these events? I'd love to understand the problem with serialport a bit more in-depth. How are these events in Electron handled differently from a regular Node environment and what kind of modules are affected?

**Comment by zcbenz** [comment]
Electron has its own message loop, so we get notified of Node's events by listening to Node's message loop's backend fd. However when some modules like `serialport` or `pty.js` add a few special events to Node's message loop, we will keep getting notified in Electron even when there is nothing happened. This problem is OS X only and I think it is a bug OS X's `kqueue` implementation.

If you are interested in this you can look at the `atom/common/node_bindings_*` to have an idea of the implementation of Node integration.

**Comment by 0x80** [comment]
Thanks for this info. Do you think this is something that can be solved by the libraries by not using these special events? Then I would report this to serialport so they can consider it for a future update.

The fork works well. In a previous naive attempt I launched two node processes manually and had them talk over TCP. A fork is much more convenient and efficient.

**Comment by zcbenz** [comment]
No, those special events are required for their implementations, it is not possible for those libraries to remove that.

**Comment by 0x80** [comment]
OK thanks a lot for your help!

**Comment by leyenda** [comment]
I am getting this error when I try child_process.fork with serialport, and I get really lost about it.

`"Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\user\Documents\electron-quick-start\node_modules\serialport\build\Release\node-v47-win32-x64\serialport.node", source: ATOM_SHELL_ASAR.js (159)`

Im using Windows 7x64 and  0.36.7

**Comment by ruipimentel** [comment]
@leyenda, were you able to get this to work? :D
I'm having similar trouble while in normal execution ("`require`"), without even forking, and on this exact same platform.
Thank you in advance!

**Comment by leyenda** [comment]
Hello @ruipimentel, unfortunately I give up on forking, and that was the specific action giving this error message to me. I end up sending  the data to my other program over tcp. I am sorry for not being helpful.

**Comment by ruipimentel** [comment]
I understand! (so much that I'm actually reconsidering the whole stuff, too!)
And I appreciate that you answered, anyway, so thank you!

**Comment by weiway** [comment]
for those of you who needs help on using serialport, i built a little tool here for serialport run inside electron [https://github.com/weiway/node-serialport-worker](https://github.com/weiway/node-serialport-worker)

**Comment by zcbenz** [comment]
This should have been fixed with #5378.
