### ISSUE TITLE
[Feature Request]: how can i run another file when running the exe file on windows?

### ISSUE THREAD

**Issue by nguyenminhan** [electron/electron#29524]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

how can i run another file when running the exe file on windows?

### Proposed Solution

how can i run another file when running the exe file on windows?

### Alternatives Considered

how can i run another file when running the exe file on windows?

### Additional Information

how can i run another file when running the exe file on windows?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
