### ISSUE TITLE
Is there a sleep mode API?

### ISSUE THREAD

**Issue by theRealProHacker** [electron/electron#29533]
I actually have three questions:
1. I would like to know if there is an event for when the computer wants to go to sleep (power save mode), so that you can maybe do last actions before that.
2.  Can you wake the computer back up again at a certain time (either dynamically or predefined)?
3.  Is there a possibility to let the renderer code still run while the PC is sleeping.

BTW, I know how to prevent the computer from sleeping, but that's not what I need. 
Node-Version: v14.17.0
Electron-Version: 12.0.9
OS: Windows 10

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
