### ISSUE TITLE
[Bug]: Wrong Exit Status on Signal

### ISSUE THREAD

**Issue by tim-janik** [electron/electron#29559]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

Exit status of a process when killed by a signal should *not* be 0, example:
    (sleep 5 ; killall nodejs ) & nodejs ; echo exitstatus: $?
    [1]+  Done                    ( sleep 5; killall nodejs )
    Terminated
    exitstatus: 143

### Actual Behavior

Exit status of many Electron versions when killed by a signal should is erroneously 0, example:
    (sleep 5 ; killall electron ) & node_modules/electron/dist/electron ; echo exitstatus: $?
    [1]+  Done                    ( sleep 5; killall electron )
    exitstatus: 0

### Additional Information

I disagree with the following statement:
  "I agree to follow the Code of Conduct that this project adheres to. *"
IMHO, forcing bug reporters to click this is discriminatory and unrealistic to abide to by non-lawyers.

I disagree with the following statement:
  "I have searched the issue tracker for a feature request that matches the one I want to file, without success. *"
IMHO, forcing bug reporters to click this is counterproductive, issues can provide valuable information even if searches have not been performed or duplicate exists.

There is a previous issues for this bug report here, but it's closed: #19650

**Comment by cannujBarfu0negjiz** [comment]
_![image](https://user-images.githubusercontent.com/79840893/120970116-dc5e1900-c71f-11eb-964e-94f2a4f1dc87.png)_

**Comment by Stirfry70** [comment]
[]()

**Comment by Cehowine** [comment]
haha

**Comment by jkleinsc** [comment]
@tim-janik As outlined in our [Contributing doc](https://github.com/electron/electron/blob/main/CONTRIBUTING.md#contributing-to-electron) we expect everyone participating to uphold [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md).

Open source is largely volunteer-driven and collaborative. Because of this, time and energy to get things done are often the scarcest resources. We want Electron to be the best that it can be, but we also have to be realistic about what the team maintaining Electron can achieve. This means that:

* We might not have an ETA for when an issue will get investigated or fixed.
* Something you want implemented might not get implemented.
* A change you want merged might not get merged.
* Insisting on or making demands for any of the above is considered against [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
