### ISSUE TITLE
[Bug]: Application crashes on macOS < Catalina, related to Window Vibrancy

### ISSUE THREAD

**Issue by leolabs** [electron/electron#29653]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS High Sierra

### What arch are you using?

x64

### Expected Behavior

I'd expect the app to launch normally.

### Actual Behavior

The app launches for a second, then crashes. I get a crashdump with the following stack:

![CleanShot 2021-06-12 at 11 30 01](https://user-images.githubusercontent.com/541628/121771739-949d1e80-cb71-11eb-990c-381ce89bcb4f.png)

### Additional Information

On first launch, my app (https://ableset.app) opens two windows. One with vibrancy set to `window` and the other with vibrancy `popover`.

Unfortunately, I don't have a High Sierra machine, so I can't test it myself, but I've had multiple customers report this to me and couldn't find any related issues on here yet, so I thought it might be worth looking into.

**Comment by dsanders11** [comment]
@leolabs, looks like this is because Electron isn't initializing a variable. You can put in any random string value for `window.setVibrancy` and it will cause a crash.

In your case you're seeing it with High Sierra because `window` isn't a supported value [until macOS 10.14+](https://developer.apple.com/documentation/appkit/nsvisualeffectmaterial/nsvisualeffectmaterialwindowbackground?language=objc).

So until this is fixed you should be able to work around the crash by not setting vibrancy to `window` if the macOS version is before 10.14.

**Comment by leolabs** [comment]
Thanks for your clarification! I thought I could make a PR, but I think I'm not proficient enough in ObjC and the build pipeline to do that. To me, it looks like there's already a check to ensure the `vibrancyType` is set before applying it to the window. Is there anything wrong with this line of code?

https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L1451
