### ISSUE TITLE
[Bug]: Rounded window corners

### ISSUE THREAD

**Issue by flachware** [electron/electron#29707]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.2.3

### What arch are you using?

x64

### Expected Behavior

Electron windows with vibrancy effect should look identical to windows of native macOS applications.

### Actual Behavior

Electron’s corner radius is about 0.5px smaller and the white inner gloss effect is more accentuated.

![rounded-corners](https://user-images.githubusercontent.com/419747/122095207-5cb20780-ce0d-11eb-84de-3891bca8d79b.gif)

**Comment by nornagon** [comment]
## If No Repro Included

Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.



## If Repro Requires Third-Party Tooling

Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by zcbenz** [comment]
Can you also check if old versions <= 12 work correctly?

**Comment by flachware** [comment]
Related, but potentially a separate issue: it strikes me that the color of the 'traffic light' buttons in vibrancy mode does not match the color of native traffic light buttons. I’m wondering if Electron could have the same vibrant buttons as native apps?

**Comment by jordandearsley** [comment]
I'm experiencing something similar. Seems to render my rounded vibrant window properly initially. Dragging the window to a second display makes it lose its rounding. 

<img width="287" alt="Screen Shot 2021-07-07 at 2 47 11 PM" src="https://user-images.githubusercontent.com/13714501/124812936-4130ad00-df32-11eb-82c1-cc5a474beb16.png">
<img width="289" alt="Screen Shot 2021-07-07 at 2 47 05 PM" src="https://user-images.githubusercontent.com/13714501/124812939-41c94380-df32-11eb-9686-a126cda4fedf.png">

**Comment by flachware** [comment]
The issue is still reproducible in Electron 21.0.1.
