### ISSUE TITLE
[Bug]: Conflicting behaviour between ELECTRON_SKIP_BINARY_DOWNLOAD option and JS imports

### ISSUE THREAD

**Issue by aureliencousin** [electron/electron#29702]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

macOS

### Operating System Version

MacOS BigSur 11.2.2

### What arch are you using?

x64

### Expected Behavior

According to the documentation (https://www.electronjs.org/docs/tutorial/installation#skip-binary-download), it is possible to install the electron package without downloading the electron binaries thanks to the ELECTRON_SKIP_BINARY_DOWNLOAD=1 env var.

This can be useful to save time & bandwidth on CI Jobs where electron is only needed as a JS lib (where requiring only ipcMain for example). 

### Actual Behavior

  When importing any stuff from electron in a JS lib, electron throws an error when the binary is not present.

```
● Test suite failed to run
    Electron failed to install correctly, please delete node_modules/electron and try installing again
    > 1 | import { BrowserWindow, ipcMain } from 'electron';
        | ^
      at getElectronPath (../my-lib/node_modules/electron/index.js:14:11)
      at Object.<anonymous> (../my-lib/node_modules/electron/index.js:18:18)
```

### Additional Information

IMO this is a bug, we should not need to download the binary when we're not running it.

If this is not the case, then I think it should be mentioned in the docs that even if we skipped the binary download, we should still provide a binary (e.g. with the ELECTRON_OVERRIDE_DIST_PATH env var).

I also had the same issue on debian, this is not specific to MacOS.

**Comment by MarshallOfSound** [comment]
Hm, I guess something needs clarifying because there's a misunderstanding here.

`ELECTRON_SKIP_BINARY_DOWNLOAD` will prevent downloading the Electron binary during `npm install`.  All of the `electron` APIs fundamentally depend on that binary, i.e. there is no JS implementation of `app` or `ipcMain`.  They are loaded out of the `electron` binary.  You also can't use them from a `node` script, instead of `node index.js` you have to run `electron index.js`, it's literally a different runtime powered by the Electron binary.

Not sure how we would clarify this in the docs, cc @erickzhao any thoughts on how to make it more obvious that electron is the runtime not a normal node_module?

**Comment by erickzhao** [comment]
I can take a stab at explicating this!
