### ISSUE TITLE
[Bug]: Crash Reporter `globalExtra` values get truncated at first comma character for Breakpad

### ISSUE THREAD

**Issue by timfish** [electron/electron#29711]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

`globalExtra` values should support the max size supported by the platform?

### Actual Behavior

Form values added to the `crashReporter` via `globalExtra` get truncated at the first comma character (`,`) 

### Additional Information

Breakpad is on the way out so this issue is more just a reminder to anybody else who's pushing the limits...

**Comment by nornagon** [comment]
c.f. #29719 for switching to crashpad on linux.

This bug is due to https://github.com/electron/electron/blob/81795744cf82a57b129f8a1fe113a9b64f61ffb2/shell/browser/electron_browser_client.cc#L534-L540

and the accompanying parsing code

https://github.com/electron/electron/blob/81795744cf82a57b129f8a1fe113a9b64f61ffb2/shell/common/crash_keys.cc#L116-L124

I'd be happy to accept a fix for this, but given we're switching to crashpad on linux imminently, I don't plan to fix it myself.
