### ISSUE TITLE
how I use  webContents.executeJavaScript  execute a function that which be defined in preload.js

### ISSUE THREAD

**Issue by DJBoy520** [electron/electron#29754]
/*
I want to call a  function which defined in the preload.js file, but it getting an error. 
Instead, I just execute an alert (" aaaaaa "), which does the job correctly
*/
main process:

const winViewBrowser = new BrowserView({
        backgroundColor: '#ffffff',
        webPreferences: {
            contextIsolation:true,
            preload: path.join(__dirname, 'preload.js'),
        }
    });

win.setBrowserView(winViewBrowser);
winViewBrowser.webContents.loadURL(url_local);
winViewBrowser.webContents.on('dom-ready', () => {
        winViewBrowser.webContents.executeJavaScript(`aa();`, true).then((result) => {
            console.log(result);
        })
    });

/*-------------------------------------------------------------------------------------------------*/
renderer preload.js

aa = () => {
  alert(123123123);
}
/*-------------------------------------------------------------------------------------------------*/

but it does not work!
<img width="751" alt="0c809486a4e8a4b59b216336f9d62a1" src="https://user-images.githubusercontent.com/32264089/122426051-85c7c900-cfc2-11eb-8a41-229370b1457e.png">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
