### ISSUE TITLE
packaging encryption

### ISSUE THREAD

**Issue by hongyujinn** [electron/electron#29773]
I have an issue when I try to add encrypt feature , when the electron-packager is packaging my project codes to asar file , through executing the packager.sh 

Does anyone has ideas to encrypt the asar file while packaging, and automatically decrypt it when needed execution? Because I am using a specific Operating System and nearly only electron can make the app run smoothly. But the safety of the codes can not be ensured if the asar file barely has complex encryption.

I have tried several ways including adding transform stream myself, but since the deadline is approaching, I find myself made no progress on it. thought it could be less difficult! I tries to add it into disk.js and the parameter of "options" in asar.js both failed.

Since I found coders also posted similar confusions on github issues, I assume this could be a big issue if electron still is not going to add encryption feature inside.
(related issue[#3041 ](https://github.com/electron/electron/issues/3041) [#2570](https://github.com/electron/electron/issues/2570) [#152](https://github.com/electron/electron-packager/issues/152) [#4359](https://github.com/electron/electron/issues/4359))

**Comment by gpetrov** [comment]
Maybe this tip will help for encryption or compression of the ASAR files:

> If you want to use a compressed archive format, go ahead and use one. In the main process you can just use that archive format directly, or wrap fs if you want to make it seamless. For the renderer process you can intercept the file:// protocol and add support for reading out of an archive there, using interceptBufferProtocol or interceptStreamProtocol. You could use that to make .tar.gz archives work like how ASAR is currently supported.

https://github.com/electron/electron/issues/29556#issuecomment-856762238

If you get it to work - do share the solution! 😃

**Comment by VerteDinde** [comment]
Hey @hongyujinn and @gpetrov, thanks for using Electron and coming here with this question!

@gpetrov's tip is a good, one but it sounds like you might benefit from a longer conversation with more help 🙂 We use this issue tracker for specific bugs within Electron core (not other tools like Electron Packager), so I'm going to close this issue since it's app-specific, but I'd recommend checking out our community Discord for answers to your question. You can join it here: https://discord.gg/electron We have both maintainers and community members (myself included, I'll keep an eye out for your question) who can give you more detailed help there.

Thanks, and good luck!
