### ISSUE TITLE
Electron After packaging, can the compressed package in app.asar be decompressed by the program?

### ISSUE THREAD

**Issue by glk-hll** [electron/electron#29837]
That is, I want to unzip the `app.asar\dist\a.zip` file to `app.asar\dist` when the electron program starts。

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
