### ISSUE TITLE
[Feature Request]: How to remove a session completely?

### ISSUE THREAD

**Issue by leonhsl** [electron/electron#29856]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In electron a session can be created by session.FromPartition() conveniently, and we know that each session is backed by a local folder for saving all relevant data, then, how can we remove a given session completely when it will no longer be used? i.e., delete all data under the backend local folder.

I did not find any electron API to do the removal.

### Proposed Solution

Not yet.

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by vikasg603** [comment]
Hey team, are we planning to implement this somehow?
It's being almost 4 years, this feature is still not part of the system it seems.

we have an option to delete the data but seems like no option to delete the session completely, it still persist in the memory.

**Comment by gavinnn101** [comment]
any updates here?
