### ISSUE TITLE
event.preventDefault() on BrowserWindow.minimize event

### ISSUE THREAD

**Issue by freddy-daniel** [electron/electron#29860]
preventDefault not working

electron: ^12.0.0
os: MacOs Mojave (10.14.6) & Windows 10 x64

mainWindow.on('minimize',function(event){
    event.preventDefault();
});

window keep minimized

**Comment by Kitten9533** [comment]
try this

  mainWindow.on('minimize', function () {
    mainWindow.restore()
  })

**Comment by freddy-daniel** [comment]
> try this
> 
> mainWindow.on('minimize', function () {
> mainWindow.restore()
> })

It's not prevent minimize action just restoring after minimize... actually i need to skip that minimize animation

**Comment by ckerr** [comment]
I'm not sure that this is a bug: the documentation doesn't list `event.preventDefault()` as operating on the `minimize` event as it does on, say, `will-resize` or `will-move`.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
Read the issue more thoroughly and unfortunately this is a system limitation. It's not possible to prevent miniaturization in this way at the OS level - for example see [`windowWillMiniaturize`](https://developer.apple.com/documentation/appkit/nswindowdelegate/1419461-windowwillminiaturize?language=objc)
