### ISSUE TITLE
Minimizing issue in mac OS new version

### ISSUE THREAD

**Issue by Jamalsalehzadeh** [electron/electron#29873]
I have updated my mac OS to **`big sur 11.4`** and I see a problem in minimizing our application, 
our application is a multi window software, we have a `launcher window` and some other windows. after updating my OS, if I close a window and then minimize the launcher window, after a while the `launcher window` will quit automatically. 
I am using this command to minimize the window: 
`remote.getCurrentWindow().minimize()`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. If you did intend to report a bug, please open a new issue with the provided template properly filled out.
