### ISSUE TITLE
BrowserWindow.getTopBrowserView()

### ISSUE THREAD

**Issue by staniel359** [electron/electron#29905]
Hello. I'm currently implementing tabs using `BrowserView`. When tab (`BrowserView`) is closed, the view switches to last active tab, but I can't seem to find any info about how to programmatically know which tab it is.

So I was wondering: is it possible **to get top BrowserView** (the last active `BrowserView`) out of `BrowserWindow.getBrowserViews()`?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by staniel359** [comment]
@codebytere Ok, thanks.
