### ISSUE TITLE
Any way to load webpage and insert custom HTML?

### ISSUE THREAD

**Issue by DogFoxX** [electron/electron#29935]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Would it be possible to load url with `mainWindow.loadURL('https://github.com')` and insert HTML?
I don't want to just edit CSS with `insertCSS`, but load custom HTML from "index.html" into the webpage.

### Proposed Solution

Maybe something like:

`document.getElementsByTagName('body').innerHTML = '../index.html'; //insert index.html from root`

### Alternatives Considered

What I've tried is:

`document.getElementsByTagName('body').innerHTML = '<div>Hello World</div>'`

But this replaces all the content rendered by the webpage with the new div. I need to append, or add to the webpage.

### Additional Information

The alternative I've tried replaces all the content rendered by the webpage with the new div. I need to append, or add to the webpage.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
