### ISSUE TITLE
[Bug]: Remote Desktop Can't Input In Some App Base on Electron

### ISSUE THREAD

**Issue by a351399739** [electron/electron#29978]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Windows

### Operating System Version

Win10 20H2

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

just can input smoothly

### Actual Behavior

Same problem in my vscode and other software base in vscode.
An other phenomenon is: when I went back to the remote computer and use it directly, the stuck will not disapper so I must restart these software.
It happen almost EVERYTIME.

### Additional Information

I had report an issue to vscode, but they believe it Electron should own this:
https://github.com/microsoft/vscode/issues/119400

**Comment by VerteDinde** [comment]
Hey @a351399739, thanks for reporting this issue. As @deepak1556 mentioned in your original issue in VSCode, remote desktop support is highly untested in Electron in general, and I would recommend using the alternative he pointed you toward.

Because remote desktop support is a larger roadmap issue and we use this issue tracker to triage current bugs and features, I'd like to close this issue for now. If you want to provide any more information/screenshots/video of what you're seeing or think this issue should stay open, let me know. Thanks!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
