### ISSUE TITLE
[Bug]: 100% crash when you trying to visit about:blank when you set app.allowRendererProcessReuse = false;

### ISSUE THREAD

**Issue by maple-leaf** [electron/electron#30051]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

Windows

### Operating System Version

Window 10 Pro 19042.1052

### What arch are you using?

x64

### Expected Behavior

app not crash

### Actual Behavior

app crash

### Testcase Gist URL

https://github.com/maple-leaf/electron-crash-on-load-about-blank

### Additional Information

1.  clone the reproduce repo
2. yarn
3. yarn start
4. toggle devtools
5. input `location.href="about:blank"` in devtools console
6. app crash

**Comment by NhaLeader** [comment]
😄

**Comment by nornagon** [comment]
Looks like this is broken at least as far back as 9.x, but is fixed in v14.0.0-nightly.20210426+. https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426 is the range I bisected to. That range includes https://github.com/electron/electron/pull/26874, which removes the `allowRendererProcessReuse` option, so it's unsurprising that this no longer crashes.

Fiddle version of the repro for convenience: https://gist.github.com/69ced6fc93a72bbdd67e109af36786a1

Not sure if there's anything to backport here. cc @MarshallOfSound

**Comment by NhaLeader** [comment]
K

**Comment by NhaLeader** [comment]
#30051

**Comment by codebytere** [comment]
Closing as wontfix owing to the removal of `allowRendererProcessReuse`.
