### ISSUE TITLE
Question about Electron's dependency on libatk-bridge-2.0.so.0

### ISSUE THREAD

**Issue by lowjiefeng1998** [electron/electron#30075]
Hello!

I was running an electron app (packaged using electron-forge) on a linux host RHEL8 but I got an error:
`error loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory`

I was wondering why does electron depend on this particular library?

Thank you!

**Comment by jkleinsc** [comment]
Thanks for reaching out!  The short answer is that Electron has that dependency because it is a Chromium dependency.

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by gaoxiong523** [comment]
i was runing an AppImage  build by electron on redhat6.9 arch32, got an same error
![image](https://user-images.githubusercontent.com/34258160/140908536-f1dd450d-7040-40ce-9eaf-997ef354d162.png)
