### ISSUE TITLE
Clicking electron tray icon switches focus to an open BrowserWindow instance on MacOS

### ISSUE THREAD

**Issue by shubham-root** [electron/electron#30073]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.13

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

11.2.3

### Expected Behavior

Irrespective of which workspace I'd be on clicking on the Tray icon of Electron application should only show the context menu. 
The application is a multi window electron application and the behaviour was optimal in last working version for us in 11.2.3

### Actual Behavior

Update to Electron 12.0.13 causes the application to switch screen to any of the BrowserWindow instance that has isVisible() return true. The tray icon behaves normally if the BrowserWindow instances are hidden or minimized but if they are visible then clicking on tray icon while on a different workspace on MacOS switch the screen to focus the open BrowserWindow instance.
This action happens not at mouse-down itself i.e. screen (workspace) switching to focus on open BrowserWindow instance does wait for mouse click to complete. The context menu flashes and then screen switches to focus on the open BrowserInstance.

The BrowserInstance in question was created with these attributes:

```
new BrowserWindow({
	icon: pathToIcon,
	preload: path.join(__dirname, 'preload.js'),
	width: width,
	height: height,
	frame: false,
	zoomFactor: 1.4,
	show: false
})
```

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by shubham-root** [comment]
@codebytere thanks for feedback. Apologies I was away for a while and couldn't provide the follow-up earlier. 

If team would still pursue this I have added the issue using the default code from Electron Fiddle [in the this gist](https://gist.github.com/shubham-root/1cb9b2aeae14a29da1653e7d10c84e4b). Attaching a screen recording to demonstrate the issue using the same code as well [here](https://youtu.be/aZ_YLZ5zj5g).

**Comment by VerteDinde** [comment]
@shubham-root Does this behavior still reproduce in Electron 20?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
