### ISSUE TITLE
BrowserWindow 'title-bar-style': 'hidden-inset' option: drag & drop

### ISSUE THREAD

**Issue by dkfiresky** [electron/electron#3009]
If this option is set, you can't drag/drop elements that are located in the top of the window (in the region where window's toolbar is placed). Even with `-webkit-app-region: drag`, dragging is not performed correctly.

The element which being dragged is native `input[type="range"]`
Here is the preview:
![Preview](https://cloud.githubusercontent.com/assets/2175645/10311824/0f1bebae-6c51-11e5-9194-07cecebfbab3.gif)

**Comment by samwillis** [comment]
It looks to me like the Brave guys have fixed it in their fork of Electron https://github.com/brave/electron/pull/13 and it just needs merging upstream.

I would love to see this in electron.

**Comment by ggamel** [comment]
👍 I hope this makes it into Electron core

**Comment by loretoparisi** [comment]
I'm having this issue on MacOS El Capitan and `electron@1.2.5`. Has been merged with that?

**Comment by JonasRothmann** [comment]
This is still an issue. Anybody with solutions to this issue? Seems like it breaks a lot of software on OSX

**Comment by aguynamedben** [comment]
This is still an issue in Electron 1.6.7. I don't see why this issue was closed.

Steps to reproduce:
1. Create a BowerWindow with these settings:
```js
    mainWindowSettings = {
      show: false,
      width: 800,
      height: 500,
      frame: false,
    };
    mainWindow = new BrowserWindow(mainWindowSettings);
```
2. Put a link in the location the title bar would be:
<img width="405" alt="hello_electron_react__and_browserwindow__title-bar-style____hidden-inset__option__drag___drop_ _issue__3009_ _electron_electron" src="https://user-images.githubusercontent.com/107841/27620845-6165e6aa-5b81-11e7-8774-d88f9765e3a8.png">
3. Observe that you can click the link, but there is no cursor, even when you've defined a cursor in your CSS.
4. Remove the `frame: false` line from the settings and relaunch the app. Observe that you can click the link and there is a cursor as expected.

Other notes
* It's not fixed by using the titleBarStyle options
* It doesn't seemed to be directly caused by using [Electron's Draggable Region `-webkit-app-region: drag;` option](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region). If I remove my usage of that, the behavior is the same.
* It doesn't seem to be fixed by the [selectable text gotcha in the Frameless Window docs](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#text-selection).
* Maybe it's related to the [Transparent Window gotcha in the Frameless Window docs](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#transparent-window) (but I'm not sure)

My guess is that under the hood this is implemented using the transparent windows, so it's subject to https://github.com/electron/electron/issues/1335.

**Comment by aguynamedben** [comment]
Sorry if it's unclear... the main issue I'm seeing is this exact issue: https://github.com/electron/electron/issues/3619 which was closed and linked to this issue.

**Comment by MarshallOfSound** [comment]
@aguynamedben You're looking for this https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#custombuttonsonhover 😄

**Comment by JohannBlake** [comment]
I'm using electron 1.6.11 and the cursor doesn't change to a pointer using css. Was this fixed?
