### ISSUE TITLE
[Bug]: version 13.1.6  Cannot quit the process in Windows app.quit()

### ISSUE THREAD

**Issue by xiaoruijia** [electron/electron#30167]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

19042.1110

### What arch are you using?

x64

### Expected Behavior

Quit the program using app.quit() and app.exit(), and the Windows electron process should be shut down  

### Actual Behavior

There are remnants of the Windows process,Is normal in version 12.0.2

operation：

![EB1DE4FC-F4C3-4e25-A772-7B9CAC1D6908](https://user-images.githubusercontent.com/52593711/125923424-14cff3c5-e785-4bd5-b1df-3fc3f5284a96.png)

call app.quit() and app.exit() after：

![AF925E7C-F294-47ef-BC40-C5E62C5EF40A](https://user-images.githubusercontent.com/52593711/125923123-a2b61198-6a74-4c08-b9e4-b14a71b4d2b8.png)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by xiaoruijia** [comment]
The single electron does not have this problem  ,I wrote an example and found that the CORE CPP of the team had problems,We will check again when we have time, but the example cannot be uploaded due to commercial reasons
