### ISSUE TITLE
[Bug]: Unable to use node modules in renderer

### ISSUE THREAD

**Issue by akash07k** [electron/electron#30179]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20 H2

### What arch are you using?

x64

### Expected Behavior

We should be able to use node modules and no error should be thrown.

### Actual Behavior

I'm using ElectronForge webpack templet and enabled nodeIntegration and RemoteModule.
Now, when I'm trying to use any node module in my renderer script, I'm getting the error like:
Module not found: Error: Can't resolve 'fs' in "path here"
Helpp please?

**Comment by ofoxsmith** [comment]
Starting from Electron v12.0.0, the default value of _contextIsolation_ changed from false to true, which prevents use of require in the renderer even if _nodeIntegration_ is enabled. Primarily for security reasons, instead of using require in the renderer, we recommend that you instead use contextBridge in a preload script to provide functions to the renderer process instead of using require. 

You can use this as a starting point for your code: https://gist.github.com/malept/6670289ff76db1b675b0c347bc8c5d68.

If you accept the risks you can change the value of _contextIsolation_ to false and _nodeIntegration_ to true.

**Comment by akash07k** [comment]
Hi @ofoxsmith,
Thanks a tons for your help.
This code example is really useful for me.I'll use context bridge instead of enabling node integration by default.
One more question, what is better and recommended? IPC or context bridge?
Please advise.
> Starting from Electron v12.0.0, the default value of _contextIsolation_ changed from false to true, which prevents use of require in the renderer even if _nodeIntegration_ is enabled. Primarily for security reasons, instead of using require in the renderer, we recommend that you instead use contextBridge in a preload script to provide functions to the renderer process instead of using require.
> 
> You can use this as a starting point for your code: https://gist.github.com/malept/6670289ff76db1b675b0c347bc8c5d68.
> 
> If you accept the risks you can change the value of _contextIsolation_ to false and _nodeIntegration_ to true.

**Comment by MarshallOfSound** [comment]
> One more question, what is better and recommended? IPC or context bridge?

Both, they aren't exclusive and you can (and should) use both at the same time

**Comment by akash07k** [comment]
Thanks a lot. :-)
> > One more question, what is better and recommended? IPC or context bridge?
> 
> Both, they aren't exclusive and you can (and should) use both at the same time
