### ISSUE TITLE
>Remove history

### ISSUE THREAD

**Issue by ez5393ez** [electron/electron#30188]
> 

- - [ ] ````

````

**Comment by ez5393ez** [comment]
- Logout

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
