### ISSUE TITLE
[Bug] iMac 5k screen

### ISSUE THREAD

**Issue by SwissAdi** [electron/electron#30214]
hello,

I'm facing a bug currently on osx 11.4 on an iMac 27" with a 5k resolution screen with op.gg 0.1.74

as you can see bellow :
<img width="656" alt="Capture d’écran 2021-07-20 à 23 05 57" src="https://user-images.githubusercontent.com/85238534/126395429-13a36b18-dbe1-4855-89a0-0db84aae8ef1.png">

I can't resize (like in former versions) nor change the resolution of the text in the op.gg window (which should resolve the problem I think)

**Comment by SwissAdi** [comment]
Also the resolution of the window would be very useful as like you can see on the screen shotbelow the font is way to small to be red :
<img width="1211" alt="Capture d’écran 2021-07-20 à 23 09 13" src="https://user-images.githubusercontent.com/85238534/126395752-e6d8e52a-f7eb-4f12-a64f-9a6e1a516dfc.png">

Regards

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
