### ISSUE TITLE
Alternative to `<webview>`

### ISSUE THREAD

**Issue by TechStudent11** [electron/electron#30239]
Hi Electron Team! I am trying to program a web browser using Electron. I have been using the `<webview>` tag to render the pages. However, after reading into it more, I've realized that using `<webview>` is not recommended because "the chromium engine is undergoing major API changes". So now I am trying to find an alternative. I've done some research and all articles point to using an `<iframe>`, however, some websites block the use of `<iframe>`s. For example, Google.

Here are the two requirements for an alternative:
1. I'll just say it now, I don't want to use `BrowserWindow.loadURL()`. That is because I have my own UI in the `index.html` file that I want to use.
2. It HAS to be a tag. I should be able to write it out in plain HTML.

Thanks in advance!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by asd281533890** [comment]
Try BrowserView.
