### ISSUE TITLE
[Bug]: Electron reporting wrong Chrome version?

### ISSUE THREAD

**Issue by MrAmericanMike** [electron/electron#30245]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Expected Behavior

https://web.whatsapp.com/ to load inside window without issues

### Actual Behavior

https://web.whatsapp.com/ complains about not using a compatible Chrome version

### Testcase Gist URL

https://gist.github.com/MrAmericanMike/c703ddf47cd1281986d876159ba8854a

### Additional Information

When logging Chrome version it reports 91.0.4472.124 so not sure what's wrong here.

**Comment by Kilian** [comment]
Electron has a different userAgent than Chromium itself, adding "Electron/13.1.7" to it. It's likely that's why whatsapp complains. We can not affect any sort of userAgent sniffing that Whatsapp does.

You can provide your own user Agent with the webContents.setUserAgent api: https://www.electronjs.org/docs/api/web-contents#contentssetuseragentuseragent
