### ISSUE TITLE
[User Story] Create option for users to disable all focus related functionality

### ISSUE THREAD

**Issue by CiriousJoker** [electron/electron#30248]
If an Electron windows grabs focus and calls FlashWindow (from the windows api), the taskbar icon doesn't actually flash, but the taskbar doesn't Autoclose anymore, which forces me to cycle through all Electron windows until I found the one that caused this (ie Discords, Slack, Spotify, etc.).

Would it be possible to add a check before any focus related functionality that checks the registry or a text file in the application folder if the user has explicitly disabled this?

Hardware acceleration is usually found in these apps settings, so that could also be set once for all electron apps that way.

**Comment by clavin** [comment]
Hi! I'm sorry that you're having trouble with how Electron apps flash. While we appreciate the heads-up, adding a configuration to disable these functions is not something that our team will be able to implement in the near future. Since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap so I'm going to go ahead and close this.

If you believe there is a bug with how a certain app flashes or focuses their windows, we recommend reaching out to their own support. If you believe there is a bug with Electron's window flashing or focus APIs, feel free to open another issue using the 🐛 Bug template demonstrating the issue.
