### ISSUE TITLE
after inputting bot token directs me straight to generic discord login page

### ISSUE THREAD

**Issue by CGXAndres** [electron/electron#30299]
here is some evidence 
![proof 1](https://user-images.githubusercontent.com/72672365/127253707-0b713f97-051d-4dd7-b26e-b0e6be2a9ccd.png)
![proof 2](https://user-images.githubusercontent.com/72672365/127253717-7059af55-3f14-433b-9ef2-41939a0e5a4a.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
