### ISSUE TITLE
RequireJS support

### ISSUE THREAD

**Issue by charandas** [electron/electron#303]
Does atom shell plan to support AMD/RequireJS code in browser scripts?

I tried to run my AMD-based project and I am getting following:

``` bash
$ ../atom-shell-v0.12.4-win32/atom.exe atomApp
[12016:0513/123139:INFO:renderer_main.cc(227)] Renderer process started
[11164:0513/123139:INFO:CONSOLE(3)] "Uncaught TypeError: Object function require
(path) {
    return self.require(path);
  } has no method 'config'", source: file:///C:/Users/karan_001/code/atomApp/app
/js/config.js (3)

```

On line 3 of  `config.js` where it erred out, the JavaScript has a call to `require.config`. Is it conflicting with the CommonJS require definition.  I found [r.js](https://github.com/jrburke/r.js/) but looks like its for running node-only projects that are written in AMD, not browser code written in AMD.

Feel free to enlighten me on the subject. Thanks.

**Comment by julmot** [comment]
I have the same issue using `require.config`

**Comment by art-ist** [comment]
The [Electron Faq](http://electron.atom.io/docs/v0.37.2/faq/electron-faq/) documents that case perfectly:
```js
// In the main process.
var mainWindow = new BrowserWindow({
  webPreferences: { nodeIntegration: false }
});
```
I could take my browser targeting rjs-output as is and my bundled AMD modules as well as excluded local modules now load in electron.
Just 

- dealing with CORS to call the service api, 
- and addng electron specific functionality like filesystem access

had to be done now.

For the latter, adding the following to the beginning of a electron specific index.html. To keep the node-specific require. As this version is (in the browser-tread) only used for electron-specific functionality it seems to be a much better idea to rename this one than digg through all references of the browser-require and rename those.
```html
<script>
window.nodeRequire = require;
delete window.require;
delete window.exports;
delete window.module;
</script>
```
I had plenty of troubles getting my require build process to run but electron integration turned out to be super easy and perfectly suported by the docs. Great cheers to the electron team!

**Comment by tiemevanveen** [comment]
Despite your tips, I'm still getting this error while trying to load RequireJS into my `webview` which is loaded in a `BrowserWindow`. 

    require.dev.js:168 Uncaught Error: Mismatched anonymous define() module: function () {

Did somebody make an example repo by any chance?

**Comment by abarajasmdo** [comment]
The solution from art-ist has worked for me for some time.
I tried to use the https://github.com/paulmillr/chokidar on my project to track the usage of a specific folder, and it breaks... due to the require inside the chokidar.
I'm investigating a work-around, but I havent found it.

I believe that I will need to have to modify my requirejs and use another alternative.

**Comment by charandas** [comment]
If this is not too limiting for your usecase:

```
  const mainWindow = createWindow('main', {
    width: 1080,
    height: 1920,
    webPreferences: {
      plugins: true,
      nodeIntegration: false // also, look at the preload option
    }
  });
