### ISSUE TITLE
[Bug]: Open an extra window when openning a deeplink on windows

### ISSUE THREAD

**Issue by nvdai2401** [electron/electron#30301]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10, version 19043.928

### What arch are you using?

x64

### Expected Behavior

The app does not open an extra window when opening a deeplink.

### Actual Behavior

I opened Electron Fiddle app on my Windows laptop by opening a deeplink `electron-fiddle://open`. The app opened an extra window and this window was quit immediately. I did some researches and saw that's why it happened [here](https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app/).
According to my knowledge, [Front](https://front.com/download) and [Figma](https://www.figma.com/downloads/) are also using electron to develop their window apps. They are handling the deeplink without opening an extra window. Does anyone know how they can do that?

Please watch this screen record to understand more about the actual behavior:

https://user-images.githubusercontent.com/33539569/127255804-6fc436e6-7c82-4818-a08f-409311d2c82f.mov

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
