### ISSUE TITLE
cant login to my bot in discord bot Client

### ISSUE THREAD

**Issue by RaymanPlays** [electron/electron#30321]
When I try to login to my bot in discord bot client, it asks me to fill my gmail and password, and when i refresh the page, its asking me for my bot token, after I fill my bot token, it
 asks me again for my gmail and password. Any fixes?
its like this > https://user-images.githubusercontent.com/69285610/127461149-213d8dca-1648-4ab2-a153-d92ee92c4fb2.png

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
