### ISSUE TITLE
[Bug]: The modal window closes and the parent window sometimes flashes

### ISSUE THREAD

**Issue by tsoil** [electron/electron#30366]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.8

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

11.4.8

### Expected Behavior

The modal window closes and the parent window sometimes flashes

### Actual Behavior

The modal window closes and the parent window sometimes flashes,I use 	remote.getCurrentWindow().close()  to close

**Comment by clavin** [comment]
Hi! Thanks for reaching out!

It's not clear what the issue is here as you described both the expected and actual behavior as the same. It sounds like you are asking a question.

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

If you believe this is indeed a bug, feel free to reopen this issue after editing the template to say what the bug is and what you want to happen instead.

I hope this helps!
