### ISSUE TITLE
App gets stuck during launching on macOS

### ISSUE THREAD

**Issue by sharma94** [electron/electron#30374]
Unable to use the app Version 0.7.2 (0.7.2) on macOS - big Sur 

Unable to close the app - must Quit / force Quit the app.

Every time I launch the app - it only shows circular loading symbol - blocking me from using the app. 
<img width="952" alt="Screenshot 2021-08-03 at 3 57 27 AM" src="https://user-images.githubusercontent.com/26078354/127932835-4ea61cec-a405-4f4a-92b8-6e7a2cda93f6.png">

**Comment by clavin** [comment]
Thanks for reaching out!

This seems to be an issue with a specific application. You should reach out to the support of that application.

If you have questions about Electron, check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. I'm going to go ahead and close this issue but if you find a bug in Electron feel free to open a new issue using the 🐛 Bug template.
