### ISSUE TITLE
Quick Install And Setup Like React.js

### ISSUE THREAD

**Issue by kkanekii** [electron/electron#30435]
Will electron ever have a package like npx create-react-app, even tho we have a git repo which we can easily clone, we have to get the link every single time, how about a package which is shorter and easier to type in?

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
