### ISSUE TITLE
[Feature Request]: how to run electron app in a docker

### ISSUE THREAD

**Issue by m986883511** [electron/electron#30445]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to run electron app in container, I am win10
Can tell me how to do it

### Proposed Solution

can this support in wiondows?
https://stackoverflow.com/questions/39930223/how-to-run-an-electron-app-on-docker

### Alternatives Considered

None

### Additional Information

none

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
