### ISSUE TITLE
Forking a child process using a higher node version

### ISSUE THREAD

**Issue by arepp23** [electron/electron#30448]
Is it possible to fork a child process using a higher version of Node? The child process needs to be running node 16.6.1 for compatibility with a module. The newest stable version of Electron is only on node 14.x. Is it possible to fork a child process to run on node 16.6.1?

**Comment by miniak** [comment]
@arepp23 no, you can only use the node version included in Electron

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
