### ISSUE TITLE
[Feature Request]: How to build debug version of electron-v9.2?

### ISSUE THREAD

**Issue by Zhxhh** [electron/electron#30469]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I modify testing.gn to:
```
import("all.gn")
is_debug = true
is_component_build = false
is_component_ffmpeg = true
is_official_build = false
dcheck_always_on = true
symbol_level = 2
```

After building successfully, I use lldb to debug. However, build is optimized and I cannot print variable.

```
(lldb) p magic_number
error: Couldn't materialize: couldn't get the value of variable magic_number: variable not available
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression
```

### Proposed Solution

How can I build a debug version of electron and can print variable successfully?

### Alternatives Considered

no

### Additional Information

no

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
