### ISSUE TITLE
[Bug]: When I try to talk with my bot, it says LOAD MORE MESSAGES, when I click on it, nothing shows up. Also I can't talk.

### ISSUE THREAD

**Issue by JxviYT** [electron/electron#30473]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I thought when I clicked LOAD MORE MESSAGES, all the messages above would appear.

### Actual Behavior

Doesn't load and the message stays, I can't talk with my bot too.
![BUG](https://user-images.githubusercontent.com/88733404/128899888-5d9d1083-a6ac-4a05-9493-b81f381f48a6.png)

**Comment by VerteDinde** [comment]
Hey @JxviYT hanks for reaching out and logging this issue! A few things stick out to me - it looks like you're using a pretty old version of Electron, 3.1.0. Could you try upgrading to the later version (our current latest stable is 13.1.9)? It's also hard to get more detailed without a repro for us to look at - if you're able to share your repo or post a reproduction of your code, we can be a lot more helpful in debugging 🙂 

Having said that - it's not clear that this is an Electron-specific issue. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron, there are a lot of options!

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out. Good luck with your bot, and I hope this helps!
