### ISSUE TITLE
[Bug]: permissionCheckHandler webContents is null for main frame permission requests

### ISSUE THREAD

**Issue by CBMasri** [electron/electron#30496]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

macOS

### Operating System Version

11.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The webContents property should only be null for cross-origin sub frame permission checks.

### Actual Behavior

The webContents property is null for main frame permission checks.

### Testcase Gist URL

https://gist.github.com/a923d684a8e76f6f21552e091cf83882

### Additional Information

According to the docs on [setPermissionCheckHandler](https://www.electronjs.org/docs/api/session#sessetpermissioncheckhandlerhandler):

> webContents (WebContents | null) - WebContents checking the permission. Please note that if the request comes from a subframe you should use requestingUrl to check the request origin. _**Cross origin sub frames making permission checks will pass a null webContents to this handler.**_ You should use embeddingOrigin and requestingOrigin to determine what origin the owning frame and the requesting frame are on respectively.

See the log output in the fiddle gist, webContents is null despite the request originating from the main frame.

**Comment by MarshallOfSound** [comment]
@CBMasri I think this is a case of docs needing clarification.

I read this as "All cross origin sub frames making permission checks will pass null" whereas you read it as "The only way null is passed to this handler is if a cross origin sub frame makes the check" which is incorrect.

In reality `null` will always be passed for notification permission checks.  Other checks have the same limitation.  That's why the type was updated to `WebContents | null`. The internal Chromium permission system only provides the `requesting_origin` and `embedding_origin`.
