### ISSUE TITLE
macOS Accessibility, AXManualAccessibility and selectedRange

### ISSUE THREAD

**Issue by godbout** [electron/electron#30567]
i'm building Vim bindings all over macOS and i'm having issues with Electron apps.

according to the docs (https://www.electronjs.org/docs/latest/tutorial/accessibility/#macos) i should be able to set the `AXManualAccessibility` attribute to the frontmost app but i can't seem to make it work. here's the Swift code:

```swift
guard let pid = NSWorkspace.shared.frontmostApplication?.processIdentifier else { return nil }
let axApp = AXUIElementCreateApplication(pid)
        
let manualAccessibility = true
let error = AXUIElementSetAttributeValue(axApp, "AXManualAccessibility" as CFString, manualAccessibility as AnyObject)
```

pretty standard. i use AX all over the place. in this case i get an `attributeUnsupported` error back, in all the Electron apps i'm trying (latest VSCode, Whatsapp, Slack).

if i set the attribute on the `kAXFocusedUIElementAttribute` instead i get a `success` back, but it doesn't seem to change anything. trying to get the `AXManualAccessibility` attribute back too returns false, so that option doesn't seem to work.

any hint on what i could be doing wrong?

the furthest i'm able to do is getting the AXUIElement for an Electron app, but the `selectedRange` is equal to zero (location: 0, length: 0).

thanks!

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by godbout** [comment]
fair. although i've followed the "path". it's just wasn't any of the option (not a bug, more of a question) so i've chose the latest option, that doesn't come with a template. but ok, will do. thanks.

**Comment by godbout** [comment]
opened a new one with the `bug` template: https://github.com/electron/electron/issues/30644. closing this one. thanks.
