### ISSUE TITLE
[Feature Request]: Now playing mac os 

### ISSUE THREAD

**Issue by alirezavlz** [electron/electron#30613]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello There, 

I'm working on streaming application but I'd like to implement "now playing" feature in OS level to gave native app feeling to the users. 
I read the documents and researched but couldn't find any information.
I found only this one https://github.com/MarshallOfSound/electron-media-service but not sure if that's the solution.

![image](https://user-images.githubusercontent.com/53314423/129975719-fefa7c55-5b9b-40ea-b0e5-216177340b3a.png)

### Proposed Solution

.

### Alternatives Considered

.

### Additional Information

.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are debugging questions, since they don't represent a task needing to be completed. For most questions about Electron, there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out. if you open a help channel with a link to your code, someone can take a look for you.

Thanks, and good luck with your feature!
