### ISSUE TITLE
[Bug]: Webview Preload asar protocol 

### ISSUE THREAD

**Issue by Oliver-Fish** [electron/electron#30656]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Inside the webview preload documentation, there is the following 

```
 The protocol of script's URL must be either file: or asar:, because it will be loaded by require in guest page under the hood.
```
source: https://www.electronjs.org/docs/api/webview-tag#preload

However, I have been unable to pass anything using the ASAR protocol, after reviewing the code it appears that only the file protocol might be supported otherwise an error is thrown

https://github.com/electron/electron/blob/fb990ba1eb5628820557f5d375fb3b5d827970e9/lib/renderer/web-view/web-view-attributes.ts#L222

### Actual Behavior

Either the documentation should be updated or an example of how to use this functionality could be provided. Ideally, I would like to be able to load files directly from the ASAR.

**Comment by Hardik-hi** [comment]
Can I take up this issue? I think I can resolve this

**Comment by iketheguy** [comment]
How are you attempting to load your preload script in your webview? If I use this line in my html, my preload script loads inside the webview no problem. 
`<webview id="foo "src="./replacetext.html" preload="./app.asar/preload.js" style="display:inline-flex; width:640px; height:480px"></webview>`
This is because the Node API supports reading asar archives as normal directories. (if you want to play around with this, setting the flag `process.noAsar = true` disables this behavior.)

**Comment by RaisinTen** [comment]
> Either the documentation should be updated or an example of how to use this functionality could be provided. Ideally, I would like to be able to load files directly from the ASAR.

@Oliver-Fish The doc-update PR, https://github.com/electron/electron/pull/30768, has already landed, so I'm closing this issue. Do let me know if you feel that keeping this issue open further is the right thing to do.

**Comment by HighSoftWare96** [comment]
I have the same problem with Electron Forge and Vite (on WIndows). I have the preload script in the same folder of the main script but the webview is in a UI subfolder: 
- All attempts without file: prefix fail silently
- preload="./preload.js": not working
- preload={path.join(__dirname, 'preload.js')}: not working
- preload={'file:' + path.join('electron.asar', 'preload.js')}: not working
- preload={'file:' + path.join('app.asar', 'preload.js')}: not working
I do not understand what value I have to put in order to find the preload script...
