### ISSUE TITLE
[Question] disallow main window to get focused on hiding second windows

### ISSUE THREAD

**Issue by Jimmy-JS** [electron/electron#30836]
Whenever I try to hide my second window (command bar like alfred), it automatically shows my main window which I don't want.

my expected behavior is whenever I hide my command bar window (2nd window) I want the screen to go back to the previous focused/opened app, not the main window.

and also if I hide the command bar window on a different desktop (I'm on mac os) I heard an alert (beep) sound. which I thought it's because it couldn't find main window on the current desktop

My code is just like this to hide the command bar window
```
ipcMain.on('command-bar:hide', async (event, _arg) => {
  event.preventDefault()
  commandBarWindow?.hide()
})
```

and in the component:
```
<button onClick={window.electron.ipcRenderer.hideCommandBar}
```

which triggers:
```
hideCommandBar() {
      ipcRenderer.send('command-bar:hide')
}
```
is there any solution for this?

Thanks!

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
