### ISSUE TITLE
[Bug]: Ubuntu 21.04 Gnome on screen keyboard will not display

### ISSUE THREAD

**Issue by cutmoney** [electron/electron#30844]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

On screen keyboard pops up when a text field is entered.

### Actual Behavior

I am running Ubuntu 21.04 on a Raspberry Pi 4 with Electron 13.2.3 running under Wayland with a touchscreen. I have tried to replicate this issue in two different ways: 
Case 1: setting the following flags in my `main.js` file:
```
app.commandLine.appendSwitch('enable-features', 'UseOzonePlatform')
app.commandLine.appendSwitch('ozone-platform', 'wayland')
```
In this case, my app loads, but I get a solid grey screen and cannot interact with my app, although it will respond to key commands and functions such as app.quit(). I have tried various combinations of gpu related Chromium flags, but the app always displays with a grey screen.

Case 2: If I do not set the wayland flags (but while running under Wayland), my app will load and display properly, but the Gnome on-screen keyboard will not pop on text field entry (it will pop if I am running under Xorg under identical conditions). The on-screen keyboard does pop on the system and works properly.

If I attempt to drag the keyboard up from the bottom of the screen to display, it will jitter and I can see remnants of the keyboard briefly, but it will never stay open. If dragged from the bottom, the app acts as if the keyboard is open and will basically block off that portion of the screen, but it is invisible. Also, if the app is quit after dragging the keyboard from the bottom, the keyboard will be open on app quit.

**Comment by vchernin** [comment]
I'm curious what happens with the on screen keyboard when running Chromium instead? Is Wayland also broken there on your device (the flags are the same)?

**Comment by cutmoney** [comment]
> I'm curious what happens with the on screen keyboard when running Chromium instead? Is Wayland also broken there on your device (the flags are the same)?

I don't understand when you say "running Chromium instead". If I run Xorg instead, the keyboard pops, but under Wayland it does not.

**Comment by vchernin** [comment]
Please try installing Chromium and try that with the Wayland flags. I suggest since Chromium is the upstream to Electron, and Electron reuses a lot of work that goes into Chromium. If you don't know Chromium is also the upstream to Google Chrome (but isn't quite the same thing).

So if the same issue also occurs in Chromium that means the issue really is with Chromium and not Electron.

You can try installing Chromium from [Flathub](https://flathub.org/apps/details/org.chromium.Chromium) or [Snap](https://snapcraft.io/chromium).

With Chromium from Flathub, after you've installed it you can run in native Wayland with:
`flatpak run org.chromium.Chromium --enable-features=UseOzonePlatform --ozone-platform=wayland`

If you have further questions feel free to ask.
