### ISSUE TITLE
[Feature Request]: Set Windows control overlay height

### ISSUE THREAD

**Issue by theolivenbaum** [electron/electron#30857]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When using the [new API](https://www.electronjs.org/docs/api/frameless-window#windows-control-overlay) to enable the Windows control overlay, I would like to be able to set the height of the controls to match the height of the remaining of the custom window titlebar. 

Something similar to what Teams is already doing on their UI:

![image](https://user-images.githubusercontent.com/8791811/132228430-94084a83-3ba3-4b6d-bd86-798c9193de9c.png)

### Proposed Solution

My guess is that adding a height property to the titleBarOverlay object would be the best solution.

### Alternatives Considered

None

**Comment by mlaurencin** [comment]
Thanks for reaching out!

There is actually an open question as to what the standard for this should be noted [here](https://github.com/WICG/window-controls-overlay/blob/main/explainer.md#open-questions-overlaying-window-controls). Since the question has yet to be addressed upstream, it would be best for us to wait until it has so that we are inline with whatever standard is decided on. 

I will keep this issue open as it is a feature that I mentioned in [my initial PR](https://github.com/electron/electron/pull/29600) as well. It would probably be best if you move the conversation to where the explainer above is, if you want to get more up-to-date upstream updates though.

**Comment by theolivenbaum** [comment]
@mlaurencin it seems like this open question has been closed upstream and they don't plan to implement it in the standards.

https://github.com/WICG/window-controls-overlay/issues/23
