### ISSUE TITLE
Screen is black and never loads

### ISSUE THREAD

**Issue by quinnyboyss** [electron/electron#30856]
How to fix?

**Comment by tpdmgl** [comment]
i have that issue too

**Comment by ImAndromeda** [comment]
Same here, having that issue.

**Comment by L34NDR0S** [comment]
it once worked for me but now i have the same issue

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by gunggang** [comment]
me too

**Comment by CristianAndrei24** [comment]
i have this issue too

**Comment by Yuvalpre** [comment]
Hey!
I experience the same issue as well,
where can I find the template to fill the information needed to solve the issue?
Thanks!

**Comment by cakenoxi** [comment]
Breh its not working- 

i kept reloading but the screens is still black
