### ISSUE TITLE
[Feature Request]: Implement support for xdg_activation_v1 Wayland protocol

### ISSUE THREAD

**Issue by Pointedstick** [electron/electron#30912]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

On Wayland, When you click on a link in an Electron app, it does not bring forward the web browser, because Electron does not implement the xdg_activation_v1 wayland protocol which governs this. Both the sending and receiving app both need to implement this protocol, and then the receiving app's window will be raised as it does on X11.

GTK 4.3 already implements this protocol, and  work to do so in Qt is under review: https://codereview.qt-project.org/c/qt/qtwayland/+/321246

It would be good if Electron implemented the protocol as well, given how many chat clients where you will be clicking links from are written in Electron these days.

### Proposed Solution

Implement the xdg_activation_v1 Wayland protocol

### Alternatives Considered

Don't implement the protocol, and accept that automatic window raising for externally-activated or activating Electron apps on Wayland will be broken.

Propose and implement a competing activation protocol for Wayland and then get all apps and toolkits to adopt it instead of xdg_activation_v1.

**Comment by elcste** [comment]
I think this upstream Chromium bug is related: https://bugs.chromium.org/p/chromium/issues/detail?id=1175327

**Comment by Pointedstick** [comment]
The Qt patch was merged; now all that's needed to make this work for Electron apps is to implement it in Electron.

**Comment by eddy-geek** [comment]
As per the upstream bug mentioned, Chromium has just merged support!

**Comment by joanbm** [comment]
I believe this is working now with Electron v24 (but *not* with Electron v23).

My tests (all on Arch Linux updated as-of 20230404 and with GTK3 3.24.37):
* electron-v23.2.2 on Sway 1.8.1 with `focus_on_window_activation smart`: ❌ Fail (`window.show()` has no visible effect)
* electron-v23.2.2 on GNOME-Shell 43.4: ❌ Fail (`window.show()` has no visible effect)
* electron-v24.0.0 on Sway 1.8.1 with `focus_on_window_activation smart`: ✅ OK (`window.show()` focuses the window)
* electron-v24.0.0 on GNOME-Shell 43.4: ✅ OK (`window.show()` shows this notification and clicking it focuses the window.
    ![GNOME-Shell notification](https://user-images.githubusercontent.com/519004/229855464-cf37e55f-3604-4acf-bc8e-1f7d3f86dae6.png)

Manual test case:
```js
// Test for https://github.com/electron/electron/issues/30912
// Run with: ./electron --enable-features=UseOzonePlatform --ozone-platform=wayland ~/window-focus-test.js

const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const mainWindow = new BrowserWindow();
  mainWindow.loadURL('data:,' + encodeURI('Window should get focus in 3 seconds'));

  setTimeout(() => {
    mainWindow.show();
    mainWindow.loadURL('data:,' + encodeURI('Did it get focus?'));
  }, 3000);
});
```

**Comment by Pointedstick** [comment]
Nice!

**Comment by retrixe** [comment]
This issue still persists and should be reopened since Electron does not pass `xdg_activation_v1` tokens to other applications when e.g. clicking links in the demo app in [releases](https://github.com/electron/electrion/releases).

> I think this upstream Chromium bug is related: [bugs.chromium.org/p/chromium/issues/detail?id=1175327](https://bugs.chromium.org/p/chromium/issues/detail?id=1175327)

Chromium recently fixed their implementation of `xdg_activation_v1` by implementing token passing using the `XDG_ACTIVATION_TOKEN` environment variable. Chromium can now:
- activate other apps by passing them in that env var a token retrieved via `xdg_activation_v1`,
- activate itself with a token passed by another app in that env var,
- or activate itself with a token self retrieved via `xdg_activation_v1` if another window of the same Chromium instance is passing focus.

Only the last point works in Electron, since Electron now correctly moves focus between windows of the same app (tested with >v32). However:
- Electron itself doesn't pass activation tokens to any apps it opens (tested with `<a>` and `shell.openExternal` in main/renderer), thus e.g. opening a link in VSCode leaves Chrome/Firefox in the background
- Discord and VSCode (both using Electron 30.x.x with relevant upstream Chromium commits) fail to focus when their URL handlers are used from Chrome/Firefox which pass the activation token in an environment variable

**Comment by ogarai** [comment]
@retrixe The latest fixes above should fix the outstanding issues. They have now been merged to the latest 31, 32 and 33 releases.

**Comment by retrixe** [comment]
I tried to test this recently with Electron 31.5.0, 32.1.0 and 33.0.0-beta.1, and the example app fails to pass focus to Chrome/Firefox on Fedora 41 + GNOME 47 through any of these methods:
- clicking `<a>` anchor links in the example app,
- calling `shell#openExternal` from the Electron REPL in the main process (with an actively focused `BrowserWindow`)
- or calling `shell#openExternal` from the renderer process of a focused `BrowserWindow`

I haven't been able to test the converse though i.e. passing focus to Electron yet

**Comment by ogarai** [comment]
@retrixe Could you try the following (assuming chrome is the default browser):

1. Close all chrome windows
2. Open chrome from the command line as follows:
    `WAYLAND_DEBUG=1 <chrome executable> --ozone-platform=wayland 2>&1 | grep "xdg_activation_v1.*activate"`
3. Open the electron executable to open the example app:
    `WAYLAND_DEBUG=1 <electron executable> --ozone-platform=wayland 2>&1 | grep xdg_activation_token`
4. Click on a link in the electron app

When I click on a link I see the following logs from electron:
```
[ 342047.961]  -> xdg_activation_v1@27.get_activation_token(new id xdg_activation_token_v1@46)
[ 342047.980]  -> xdg_activation_token_v1@46.set_surface(wl_surface@23)
[ 342047.986]  -> xdg_activation_token_v1@46.set_serial(222131, wl_seat@17)
[ 342047.991]  -> xdg_activation_token_v1@46.commit()
[ 342048.557] xdg_activation_token_v1@46.done("c0e4df49-b9dc-42d4-b6c7-98baff58f61c_TIME0")
[ 342048.592]  -> xdg_activation_token_v1@46.destroy()
```

And the following logs from chrome:
```
[ 342186.981]  -> xdg_activation_v1#28.activate("c0e4df49-b9dc-42d4-b6c7-98baff58f61c_TIME0", wl_surface#47)
```

Could you confirm if this is what you see?

In my testing it works as expected for both launching an app from electron and also for the case when I launch an electron app e.g. `element://` from another app on GNOME 46.5 and Electron 31.6.0. 

Could you provide the chrome version you have?

**Comment by retrixe** [comment]
It turns out I was accidentally launching the Electron application in Ozone/X11, so I'm very sorry about wasting your time with that, I can confirm xdg_activation_v1 works fine with `<a>` links and `shell#openExternal` in the main process (with currently focused `BrowserWindow`) on Electron 31.5.0 :tada: thanks a lot for your work

I did find out, however, that focus isn't passed when calling `shell#openExternal` from the preload or renderer processes though, and checking with `WAYLAND_DEBUG=1` it seems that `xdg_activation_v1.get_activation_token` doesn't get called. I'm not sure fixing this is a priority since doing this involves disabling Electron's sandboxing/context isolation capabilities (which most apps probably aren't or shouldn't be doing? unfortunately the apps I use ie Discord, VSCode are on older Electron versions currently)

**Comment by ogarai** [comment]
> I can confirm xdg_activation_v1 works fine with <a> links and shell#openExternal in the main process

Awesome great to hear it's working for you, and no worries!

> I did find out, however, that focus isn't passed when calling shell#openExternal from the preload or renderer processes though

Hmm, I guess this is a special case that is different from how it works in chrome where only the browser process launches other apps. Fixing that may be quite involved, i.e. requesting a token from browser process, then passing it back to the renderer process and using that to launch the app. In theory it is do-able I think although complicated. In any case, if you feel there is a strong need for it, I would say open a separate electron bug for it.

> unfortunately the apps I use ie Discord, VSCode are on older Electron versions currently

Yeah I have it working with element for instance which uses my system electron package, but it doesn't work for other apps like vscode that package an older electron. I'm waiting for this as well. FWIW I have used the "Grand Theft Focus" gnome extension as a workaround.
