### ISSUE TITLE
[Bug]: Backdrop Filter (Blur) Broken on Body background-color Alpha Value Set to 0

### ISSUE THREAD

**Issue by BitesPotatoBacks** [electron/electron#30915]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

I have also noticed something like this back in 13.0.1

### Expected Behavior

When the HTML body's CSS is set as so:
```CSS
body {
    background-color: rgba(255, 255, 255, 0);         /* The alpha value is set to 0 */
}
```
the `blur()` style of `backdrop-filter`, when applied to a DOM, should be (of course) **_NOT_** broken, as it is in this screenshot:

![Screen Shot 2021-09-10 at 10 48 44 AM](https://user-images.githubusercontent.com/83843298/132896896-eb55349c-263a-4ce3-88b1-5fb045217f34.png)
### Actual Behavior

Instead -- when the HTML body's CSS is set with an alpha of 0 -- the `blur()` style of `backdrop-filter` becomes broken.

![Screen Shot 2021-09-10 at 10 47 57 AM](https://user-images.githubusercontent.com/83843298/132897092-65d279ee-fcce-4c10-a0b9-8f95412b5c99.png)

### Testcase Gist URL

https://gist.github.com/BitesPotatoBacks/16b9ea6925701b895f512ff92f439ba2

### Additional Information

I originally thought this bug occurred when vibrancy was set on Electron's `BrowserWindow`, but I recently realized it was **actually** due to the alpha channel of the HTML body being set to 0...

Because of this, I don't know whether this is actually just bug of _Chromium_, or if Electron's code itself is the culprit..? 🤔

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue?  You did add a Fiddle, but it cannot be run in Fiddle standalone because it only contains a single `index.html` and nothing else. I can just swap that out with the index.html in stock Fiddle, but that forces me to make some assumptions I'd rather not make.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by BitesPotatoBacks** [comment]
@codebytere  Sorry about that! I updated the test case...hopefully it's okay now
[https://gist.github.com/BitesPotatoBacks/16b9ea6925701b895f512ff92f439ba2](https://gist.github.com/BitesPotatoBacks/16b9ea6925701b895f512ff92f439ba2)

**Comment by BitesPotatoBacks** [comment]
@codebytere hey there! Hope you had a great weekend. Just leaving another followup comment regarding the updated testcase. I know you're busy but I was curious If you have any updates for the issue, or If you saw my _last_ followup comment? (and if not, here's the updated test case [https://gist.github.com/BitesPotatoBacks/16b9ea6925701b895f512ff92f439ba2](https://gist.github.com/BitesPotatoBacks/16b9ea6925701b895f512ff92f439ba2))

Hope to here back soon👍 good day

**Comment by codebytere** [comment]
@BitesPotatoBacks good news! looks like it was fixed in https://github.com/electron/electron/commit/7379e5eb3696fbae10e896ad3f5d00308c6277f6 - hopefully a similar fix will be backported soon.

**Comment by BitesPotatoBacks** [comment]
@codebytere Awesome 👍

**Comment by szalaybalazs** [comment]
Was this fixed? I am still experiencing the same issue.
