### ISSUE TITLE
[Bug]: `window.webContents.userAgent = ` not applied to late initial iframes

### ISSUE THREAD

**Issue by Karlatemp** [electron/electron#30918]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 1909, 18363.1679

### What arch are you using?

x64

### Expected Behavior

The javascript code `navigator.userAgent` returning right value in late initial iframe

### Actual Behavior

![image](https://user-images.githubusercontent.com/30070303/132940547-8b958563-1814-4182-911c-ab295834af2f.png)

### Reproduce

```typescript
    let window = new BrowserWindow({
        height: 500,
        width: 500,
        webPreferences: {
            nodeIntegration: false,
            webSecurity: true,
            contextIsolation: false,
            nativeWindowOpen: true,
            preload: ''
        },
    });
    window.webContents.userAgent =
            .....
            ;
    window.loadURL('');
```

```html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
</head>

<body>
    <script type="text/javascript">
        (function () {
            setTimeout(() => {
                var frame = document.createElement("iframe");
                frame.src = "https://docs.github.com";
                document.body.appendChild(frame);
            }, 1000);
        })();
    </script>
</body>

</html>
```

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Karlatemp** [comment]
https://gist.github.com/Karlatemp/bd6262e3c935bc4522cc49b6a61c0b48

**Comment by codebytere** [comment]
@Karlatemp running the provided Fiddle:

![Screen Shot 2021-09-14 at 1 58 01 PM](https://user-images.githubusercontent.com/2036040/133253530-20688fb2-f027-4137-be33-558e5f36a60b.png)

shows the intended user agent. Is there something i'm missing to reproduce this?

**Comment by Karlatemp** [comment]
@codebytere switch it to the iframe
![IMG_20210914_220718](https://user-images.githubusercontent.com/30070303/133273077-c7594f03-6432-4676-b275-85ca7f862a8f.jpg)
