### ISSUE TITLE
Docs has no exact information on when getPath should be called to be sure the directory is created

### ISSUE THREAD

**Issue by SuperKirik** [electron/electron#30931]
There is a method:
`app.getPath(name)
`

It's good to know at what point of app lifecycle it is guaranteed that the corresponding directories are created.
For example to use the logs path for logging with winston. Is it guaranteed in the very top of the main file or only after 'ready' event ? There are no such information in documentation as I see...

Searching in issues I found such text regarding userData:
> As before, by default,
> * 'userData' is computed from 'appData' and app name
> * 'userCache' from 'cache' and app name
> But not at the same moment. previously it was done very early, before app main script was executed. Now it is done when the app is ready, giving some opportunities to customize 'appData', app name
https://github.com/electron/electron/pull/19693

Does it mean that I should wait 'ready' event  to use this directory ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by SuperKirik** [comment]
@codebytere thank you for reply ! 
Sorry, I thought that it could be treated as the task for "updating docs" (in case of my question makes sence)
