### ISSUE TITLE
enable-features VaapiVideoDecoder issue with electron >=13

### ISSUE THREAD

**Issue by arey-instoresolution** [electron/electron#30955]
Hello,

We've been amazed with Electron 12 to see MojoVideoDecoder instead of FFmpegVideoDecoder and its compatibility with VAAPI.

However, starting with electron 13, it seems to not be working anymore, and even the new "enable-features VaapiVideoDecoder" command line switch doesn't seem to help.

Our software is running on Lubuntu 20.04.3 (with X11 and LXQt), the CPU is an Intel Celeron N3350, and here are the command line switches used : 

app.commandLine.appendSwitch("ignore-gpu-blacklist");
app.commandLine.appendSwitch("enable-accelerated-video");
app.commandLine.appendSwitch("enable-accelerated-video-decode");
app.commandLine.appendSwitch("use-gl", "desktop");
app.commandLine.appendSwitch("enable-features", "VaapiVideoDecoder");

Does anyone here has been experiencing the same issue ? Are we making any mistake with command line switches ? 

Thanks a lot, have a nice day, and electron rocks ;-) !

**Comment by arey-instoresolution** [comment]
Hello,

I was wondering maybe I should not post this issue here since it may be more related to chromium than electron itself ? 

Thanks a lot, have a nice day :-)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
