### ISSUE TITLE
Add progess for deleting a directory

### ISSUE THREAD

**Issue by Milo123459** [electron/electron#31028]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This [issue](https://github.com/microsoft/vscode/issues/131815) needs this [method](https://github.com/electron/electron/blob/13-x-y/docs/api/shell.md#shelltrashitempath) to return the progress of deleting a directory. Maybe a package like [`p-progress`](https://npmjs.com/package/p-progress) would help?

### Proposed Solution

Use [`p-progress`](https://npmjs.com/package/p-progress)

### Alternatives Considered

N/A

### Additional Information

For issue https://github.com/microsoft/vscode/issues/131815

**Comment by Milo123459** [comment]
^ I'm looking to implement this.

**Comment by BlackHole1** [comment]
This is hard to do (at least on the electron)

This is because the electron call is a delete command executed by calling the system api.
I checked the source code and found that only windows can do this

### macOS

https://github.com/electron/electron/blob/3ef74abfe45b65f6bf3207ba2ed27155edcaf921/shell/common/platform_util_mac.mm#L145-L158

The mac calls are [trashItemAtURL](https://developer.apple.com/documentation/foundation/nsfilemanager/1414306-trashitematurl) and [removeItemAtURL](https://developer.apple.com/documentation/foundation/nsfilemanager/1413590-removeitematurl)

Also, I checked apple's documentation and did not find any information about `progress`

### Windows

https://github.com/electron/electron/blob/3ef74abfe45b65f6bf3207ba2ed27155edcaf921/shell/common/platform_util_win.cc#L403-L413

The windows calls are [DeleteItem](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifileoperation-deleteitem) and [PerformOperations](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifileoperation-performoperations)

You can use UpdateProgress to get the current progress, details can be found at: https://stackoverflow.com/questions/57461683/track-progress-of-moving-to-recycle-bin-on-windows

### Linux

https://github.com/electron/electron/blob/3ef74abfe45b65f6bf3207ba2ed27155edcaf921/shell/common/platform_util_linux.cc#L360-L371

Under linux, this is a direct system command call

----

### Summary

If this feature is to be implemented, it will only be available on windows systems.

There is an indirect implementation solution:

Before executing the deletion, get the size of the file to be deleted, and then get it again every 200 milliseconds (or other values), by taking the difference.

cc @nornagon

**Comment by Milo123459** [comment]
OK, even if it is only for Windows, still a good feature to have imo. There will be workarounds.

**Comment by Milo123459** [comment]
> Before executing the deletion, get the size of the file to be deleted, and then get it again every 200 milliseconds (or other values), by taking the difference.

I think this could actually work quite well! This is for a feature request downstream in VSCode, so I think this would probably be the best, especially because it'd be cross platform!

Alternatively, how would that work for folders? Walk the folder and delete the files inside it manually?

**Comment by Milo123459** [comment]
Hey! Just was curious if anyone had a problem with a theoretical implementation that could be used: 

1. Walk the directory and sub directories.
2. Get all the files that will be deleted.
3. Delete each file one by one (possibly in parallel? could work) and then calculate a percentage on how many files are left.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
