### ISSUE TITLE
How to define endpoints for prisma

### ISSUE THREAD

**Issue by M-Barari** [electron/electron#31022]
Hi, I made an app in nuxt.js + electron.js + electron-builder . then added `prisma` to `nuxt` and used `express` in serverMiddleware to handle my endpoints started `api/` and send them to prisma CRUD . It works just fine in dev mode, but when building `.exe` file , there is no serverMiddleware to handle those endpoints. 

So as I searched through articles , I found out you can added `express` to `electron` as you can add `prisma` in `background.js` , but didn't found any solution to integrate them so that my requests that starts with `api` go through `prisma` functions. e.g. `$axios.get('api/users)` get me all users :

```javascript
import express from 'express'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
const app = express()
app.use(express.json())
app.get('api/users', async (req, res) => {
   const result = await prisma.admin.findAll()
   res.json(result)
})
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
