### ISSUE TITLE
[Bug]: UI Freezes when windows size is changed

### ISSUE THREAD

**Issue by MatanYemini** [electron/electron#31122]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 - 10.0.19043

### What arch are you using?

x64

### Expected Behavior

App works normally

### Actual Behavior

On a specific size, the UI gets immediately stuck, while not giving any errors.

Important to mention -- when devtools are open -- we cannot reproduce it.

It is reproducible also on Mac (both M1 and Intel chips).

I could get few errors on the main process (every time different error):
- [4192:0925/192834.269:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
- [21864:0925/180122.290:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.

Few times I have not seen any errors at all (so not sure they are related).

We are running few windows, the others are still working once it happens + we are still getting audio feedback from the "frozen" window.

Running React using these flags of chromium:
Electron.app.commandLine.appendSwitch("ignore-gpu-blacklist", "true");
Electron.app.commandLine.appendSwitch("enable-gpu-rasterization", "true");
Electron.app.commandLine.appendSwitch("enable-zero-copy", "true");
Electron.app.commandLine.appendSwitch("disable-software-rasterizer", "true");
Electron.app.commandLine.appendSwitch("enable-usermedia-screen-capturing", "true");

I have tried to disable hardware acceleration (using -- Electron.app.disableHardwareAcceleration();) -- no success as well

Any ideas?

**Comment by MatanYemini** [comment]
If it is an interest of someone, I was able to solve it (actually just not getting hurt by the problem)

It was happening when I had a scroll and a button with a tooltip inside the window.

When the tooltip got to the exact point where the scroll should have render -- it will freeze the UI with those errors.

I would still keep it open, since a infra fix is probably needed (close if you think differently)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by MatanYemini** [comment]
I think we can close it 

The problem was on popper.js -- it was trying to calculate the positioning for the tooltip and stuck into an infinite loop. Closing this. Thanks!
