### ISSUE TITLE
[Feature Request]: Please require all people to use latest of 6 months old elctron version.

### ISSUE THREAD

**Issue by fisforfaheem** [electron/electron#31135]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

currently, most devs are using about a year or even 2 years old electron.

### Proposed Solution

if electron supports only the version from 6 month old ... then most people would use the latest version and be on the latest improvements and speed bumps.

### Alternatives Considered

otherwise flutter woudl win in all places as well asl UNO

### Additional Information

this is a suggestion, please try to use it to make electron better

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by miniak** [comment]
@fisforfaheem it’s up to the apps to keep up with Electron upgrades, we cannot force them.

**Comment by fisforfaheem** [comment]
But failing to force them to comply to use latest versions, Is leading them
to move to ReactNative and Flutter SDk.  It's time, at least you can show
them notifications warnings if they are using a 6-month-old version.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality8&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality8&>
10/03/21,
12:56:43 PM
