### ISSUE TITLE
[Bug]: Improve Linux XDG FileChooser implementation

### ISSUE THREAD

**Issue by vchernin** [electron/electron#31258]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux any

### What arch are you using?

x64

### Expected Behavior

Support for the XDG FileChooser portal landed in Electron 14 https://github.com/electron/electron/pull/19159.
Electron should try to use the XDG FileChooser wherever it can.

### Actual Behavior

There are cases where it is not used where it could be used (specifically on Ubuntu and in Flatpak, see below). The old non portal file chooser is used, meaning the work in https://github.com/electron/electron/pull/19159 is not taken advantage of.

### Additional Information

Any help on how to debug Electron here would be appreciated, as I’m not sure why this is happening. 

See discussion on what likely is a symptom of this issue:
https://github.com/squalou/google-chat-linux/issues/38 https://github.com/flathub/com.mattermost.Desktop/pull/39

This is not a regression. Worst case the old file chooser will be used, but that’s what’s been the behaviour for years anyway.

**Comment by prozaiczyk** [comment]
X

**Comment by MurzNN** [comment]
Same problem for me, even with forcing `GTK_USE_PORTAL=1` I still see old GTK file dialogs instead of native KDE, but on same system Firefox with `GTK_USE_PORTAL=1` shows the KDE file dialogs, so seems in Electron the xdg portals are detected wrongly?

**Comment by ilyazzz** [comment]
The XDG Picker seems to work properly for me on Arch Linux with the `discord_arch_electron` package and `GTK_USE_PORTAL=1` set.

**Comment by MurzNN** [comment]
My Ubuntu have 3.24.25 version of GTK, and here is dbus call that I caught on file save event in app (Ferdi with Electron 15.2.0): 
```
method call time=1634390665.793665 sender=:1.722 -> destination=org.freedesktop.DBus serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',interface='ca.desrt.dconf.Writer',path='/ca/desrt/dconf/Writer/user',arg0path='/org/gtk/settings/file-chooser/'"
method return time=1634390665.793693 sender=org.freedesktop.DBus -> destination=:1.722 serial=6 reply_serial=10
```
But still see the GTK file chooser.

**Comment by MurzNN** [comment]
And here is the `dbus` call on `zenity --file-selection` cli command:
```
method call time=1634391265.992642 sender=:1.713 -> destination=:1.717 serial=187 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.FileChooser; member=OpenFile
   object path "/org/freedesktop/portal/desktop/request/1_755/gtk338803498"
   string ""
   string ""
   string ""
   array [
      dict entry(
         string "accept_label"
         variant             string "_ОК"
      )
      dict entry(
         string "modal"
         variant             boolean false
      )
      dict entry(
         string "multiple"
         variant             boolean false
      )
      dict entry(
         string "directory"
         variant             boolean false
      )
      dict entry(
         string "filters"
         variant             array [
            ]
      )
   ]
method return time=1634391265.993344 sender=:1.713 -> destination=:1.755 serial=188 reply_serial=2
   object path "/org/freedesktop/portal/desktop/request/1_755/gtk338803498"
```

**Comment by vchernin** [comment]
Hm, @tristan957 I noticed on Electron 16 while testing Jitsi Meet (Flatpak) and this [demo](https://github.com/hokein/electron-sample-apps/tree/master/desktop-capture) (toolbox), it seems the portal works reliably now? I can clearly see the calls in Bustle, and within Flatpak I can choose beyond the sandbox. Even without `GTK_USE_PORTAL=1` it's still using the portal.

So that's something I guess.

**Comment by tristan957** [comment]
Hey that is awesome. Not sure what would have changed beyond that PR last week.

**Comment by vchernin** [comment]
Yeah me neither, hopefully other apps update soon to 16 so it can be confirmed to work.

**Comment by tristan957** [comment]
VSCode is working on it, but there are still a couple of blockers. Will be cool when it does.

**Comment by vchernin** [comment]
Yeah VScode will be interesting, although I'm not sure how useful  the portal will be for them given https://github.com/flatpak/xdg-desktop-portal/issues/463 exists. Wouldn't an IDE need permanent access to a whole directory?

**Comment by tristan957** [comment]
I would think the VSCode flatpak has filesystem=host permissions. VSCode mainly just wants ability to pick file chooser at the moment.

**Comment by vchernin** [comment]
Yeah, hopefully eventually they can move away from those static `filesystem` permissions.

**Comment by shimmark** [comment]
The document portal can be used to get access to directories with a file chooser already. What’s missing is things like knowing the real path of the file or directory (flatpak/xdg-desktop-portal#475) and getting properly notified when files are changed by another program (flatpak/xdg-desktop-portal#567).

**Comment by ssokolow** [comment]
@shimmark You really consider it optimal to force a two-stage "Pick a directory, now use our proprietary picker to pick a file within it" workflow on people for something like a directory fully of `.mp4`+`.srt` or `.cue`+`.bin` pairs?

**Comment by shimmark** [comment]
No, I don’t consider that optimal! My list of things missing wasn’t meant to be exhaustive. What you’re asking for is flatpak/xdg-desktop-portal#463.

Though there are also editors that expect to have access to .editorconfig and .git in parent folders when opening a single file, and a portal that merely allows opening neighbouring files wouldn’t be enough for that (since .editorconfig and .git could be in parent folders rather than the same folder). So some cases might still require having the user select a directory rather than a file, even when they’d prefer to select only a file.

**Comment by ssokolow** [comment]
@shimmark Oops. Sorry. I got about half a dozen message notifications at the same time, got mixed up, and thought this *was* flatpak/xdg-desktop-portal#463.

**Comment by opl-** [comment]
I figured out a solution which works for me after brief two hours of confusion.

#19159 tries to be safe in how it depends on libgtk by loading it dynamically and trying to find the dialog related functions dynamically. It does this by requesting a file called `libgtk-3.so`:

https://github.com/tristan957/electron/blob/25b540187140463a4d0f9908bccc8606d2693bb4/shell/browser/ui/file_dialog_gtk.cc#L75

Debian, meanwhile, packages libgtk as `libgtk-3.so.0`:

```
$ dpkg -L libgtk-3-0:amd64
...
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0
...
```

As a workaround, I linked the library (which seems to be common practice with [sonames](https://en.wikipedia.org/wiki/Soname), but is for some reason applied very inconsistently by repository maintainers):

```sh
sudo ln /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 /usr/lib/x86_64-linux-gnu/libgtk-3.so
```

Restarting the electron application and triggering a file picker again confirmed that this was the issue.

(As an aside, the KDE file picker appeared behind the electron application which hints at an extra issue here. Setting a window override for window class `xdg-desktop-portal-kde` to force no focus stealing prevention fixed this, which makes me think this might caused by the parent window not being set?)

**Comment by shoffmeister** [comment]
Fedora 36 does not ship `libgtk-3.so` either; creating it via softlink to `libgtk-3.so.0` unbreaks the electron functionality.

**Comment by MurzNN** [comment]
> Fedora 36 does not ship `libgtk-3.so` either; creating it via softlink to `libgtk-3.so.0` unbreaks the electron functionality.

For Ubuntu this trick works too, thanks!
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 /usr/lib/x86_64-linux-gnu/libgtk-3.so
```

**Comment by shoffmeister** [comment]
It seems to have been addressed already (indirectly) by way of https://github.com/electron/electron/commit/37b7e347fce555836d694f36f6ee5e2ea67db049 which came as part of https://github.com/electron/electron/pull/33650

That PR basically flipped to different dynamic referencing to shared library code that is known to be working for Chrome. Chrome shows the portal dialogs, so knows how to correctly get hold of the GTK native dialogs.

As far as I can tell (from the git branches), this has been on electron since version 18.

**Comment by damnms** [comment]
for those on fedora (36), too lazy to read all that:
sudo ln /usr/lib64/libgtk-3.so.0 /usr/lib64/libgtk-3.so

at least that worked for me to upload files in element, thanks!
