### ISSUE TITLE
[Bug]: Transparency of iframes doesn't work

### ISSUE THREAD

**Issue by barnabwhy** [electron/electron#31265]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

The iframe should have transparency with `allowtransparency='true'` and `background-color: transparent;`

### Actual Behavior

The iframe renders with a white background

### Additional Information

iframe in a transparent window: 
![image](https://user-images.githubusercontent.com/22575741/135768695-8ba0fa5a-306b-4d91-ac3e-5f8abdaa24ea.png)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by pejman1** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

it seems is related issue with this topic 
https://github.com/electron/electron/issues/30993

**Comment by barnabwhy** [comment]
It seems that iframes, webviews and browserviews are all affected by this problem, so it is likely related. I know it works in v11.5.0. It could also be related to this #31019

**Comment by rodnoycry** [comment]
I have the same issue
