### ISSUE TITLE
[Bug]:  window size and position restore through restarts is unreliable

### ISSUE THREAD

**Issue by RJVB** [electron/electron#31293]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux 4.14

### What arch are you using?

x64

### Expected Behavior

I expect application window geometry (size, position) to be restored if the desktop environment is configured to do so.

### Actual Behavior

The current Ferdi version violates that assumption, instead starting up (almost?) systematically with a predefined size and position (0,0). 

### Additional Information

I initially reported this as getferdi/sponsors-only#217 but analysis by one of the Ferdi devs strongly suggests that this is a bug in Electron, causing it to impose a geometry that the code intends to define only as the acceptable minimum size. I was thus asked to file a ticket here as well.

Electron: 13.3.0
Chrome: 91.0.4472.164
Node.js: 14.16.0

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by RJVB** [comment]
Unfortunately for you I'm not (planning to be) a nodejs/electron developer. I'm transferring your request to the Ferdi dev team - but I do hope that bugs do end up getting fixed even if they are reported by "Joe or Jane" Users who have really zero knowledge or possibility to code!
