### ISSUE TITLE
[Feature Request]: Ability to force high-performance discrete GPU

### ISSUE THREAD

**Issue by aleksey-hoffman** [electron/electron#31355]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

By default Electron runs on integrated graphics if preferred graphics processor is set to "Auto-select" (Nvidia graphics control panel) which results in Electron apps having huge memory usage imprint, since most of the memory system is usually taken by the gpu-process.

This flag `--force_high_performance_gpu` doesn't do anything on Windows

### Proposed Solution

Ability to force high-performance discrete GPU for Electron apps.

This might help:

```c
// Enable dedicated graphics for NVIDIA:
extern "C" 
{
  __declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
}

// Enable dedicated graphics for AMD Radeon:
extern "C"
{
  __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
}
```

### Alternatives Considered

n/a

**Comment by psulek** [comment]
Looking for this as well. 
Maybe someone from team can explain why it does not work when such cmd is also in official docs of electron - https://www.electronjs.org/docs/latest/api/command-line-switches#--force_high_performance_gpu

**Comment by nornagon** [comment]
This is an upstream issue, we do not handle this flag directly. It is handled by Chromium. Consider filing a bug on Chromium at https://crbug.com/new.

Handling gpu switching ourselves is outside the scope of the Electron project, so I'm going to close this issue.

**Comment by ylqhust** [comment]
chrome support the "--use-adapter-luid=high,low"  command line switch to specify the LUID of the
GPU adapter to use when using D3D11 since Jun 17 2020

gpu adapter luid can be find in regedit "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DirectX\" , or you can get it from
[DXGI_ADAPTER_DESC](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/ns-dxgi-dxgi_adapter_desc)

![image](https://user-images.githubusercontent.com/13652665/161041446-99ddbe7f-f1da-4ddc-9135-31a8a53f724a.png)
for this nvidia gpu in image, command line is "--use-adapter-luid=0,72772"

https://chromium.googlesource.com/chromium/src/+/000e431a5fce6fa1f6b9db0ed29d68600312adf9
https://chromium.googlesource.com/angle/angle/+/a2ec926cfcc44bf3cace1bd0795183d18834fcba
