### ISSUE TITLE
[Feature Request]: allow to set DNS verbatim setting of NodeJS to be set to "true" for IPv6 compatibility

### ISSUE THREAD

**Issue by treysis** [electron/electron#31515]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron depends on NodeJS, which reorders DNS lookups, giving precedence to IPv4 (this only changed in NodeJS v17, which is far away from being integrated into Electron). This poses a problem on any IPv6-capable system in general, but especially on IPv6-only systems without IPv4 connectivity, because connections will always be tried with the IPv4 address of a DNS lookup.

### Proposed Solution

NodeJS supports disabling the reordering of DNS results by passing the option `verbatim = true`. Electron should expose that option to app developers, so that they can build IPv6 capable applications based on the Electron framework. Ideally, that would also be configurable by end users via a system variable or a config file.

### Alternatives Considered

None viable.

**Comment by andreialecu** [comment]
If this gets implemented, please don't forget about [Happy Eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) alongside it, otherwise this can create big problems for users randomly, when IPv6 starts glitching.

More reading in: https://github.com/nodejs/node/issues/41625 and all linked threads therein.

**Comment by treysis** [comment]
It's already creating problems for users when IPv4 is glitching :/

**Comment by andreialecu** [comment]
> It's already creating problems for users when IPv4 is glitching :/

Agreed, but IPv4 seems way less likely to glitch than v6 since it had way more time to mature. If you go through the issue I linked, there's a big rabbit hole of assorted problems resulting mainly from IPv6 networking issues.

The right way forward would be to implement Happy Eyeballs. Would solve it if either one of them is glitching.

**Comment by nornagon** [comment]
As far as I can tell, we don't do anything to prevent using the [`verbatim` option](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback) in node.js's DNS API. I'm closing this as I don't think there's any action for us to take here.
