### ISSUE TITLE
[Feature Request]: Expose raw headers on `IncomingMessage`

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#31531]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The Electron `net` module (and other associated APIs, types, etc.) is supposed to be similar to Node's `http` and `https` modules. At this point in time however, Electron's `IncomingMessage` does not expose `rawHeaders`.

### Proposed Solution

Expose a `rawHeaders` on `IncomingMessage`. The return value should be similar to that as in the `http` module:

> The raw request/response headers list exactly as they were received.
>
> The keys and values are in the same list. It is not a list of tuples. So, the even-numbered offsets are key values, and the odd-numbered offsets are the associated values.
>
> Header names are not lowercased, and duplicates are not merged.

https://nodejs.org/api/http.html#messagerawheaders

### Alternatives Considered

Don't use Electron `net` module. I don't want to do this because of the greater functionalities of `net` vs the Node `http` and `https` modules. 

### Additional Information

I am more than happy to implement this myself!

**Comment by ckerr** [comment]
Hi @MRayermannMSFT, thanks for the suggestion!

I'm just doing issue triage and see your issue didn't get any response yet. Even though I am coming into this without context, I wanted to at least give a pong, suggest next steps, and get some more information on the issue so that I can understand better what you're looking for. If I'm readling [the current implementation right](https://github.com/electron/electron/blob/b8c2481edb264e4fb8c79fa44f016bd48b4980c0/lib/browser/api/net.ts#L60) it looks like exposing the raw headers would be pretty straightforward -- but it also looks like the filtering is pretty minimal, e.g. handling duplicates. What problem would raw headers solve?

Also, thanks for volunteering to implement this!

If you're still on-board for this, please create a draft PR for `electron/electron` targeting main and @ the electron/wg-api for review. They review and approve / req changes / etc. any new API, so for example if you wanted to get approval before writing the full patch, it would be fine for the PR to just patch `docs/` with your proposed changes first.

Thanks again!

**Comment by MRayermannMSFT** [comment]
> but it also looks like the filtering is pretty minimal, e.g. handling duplicates.

Yep I felt the same way!

> What problem would raw headers solve?

Our app runs against a service which lets you store and get objects via http requests. When you store objects, you can set metadata about the object. Metadata is transmitted as http headers. Each piece of metadata is a header, where the key is the header name and the value is the header value.

The service also preserves the casing of any metadata that you send. So if I send a metadata header like `metadata-PascalCaseMetadata`, when you get the object later, the casing of that metadata header will be the same.

Prior to using `net`, we would look at the `rawHeaders` of incoming requests to get that preserved casing to workaround the fact that Node was lowercasing header names. We'd like to use `net` though for the better native networking capabilities. So that's the problem adding raw headers will solve.

> if you wanted to get approval before writing the full patch, it would be fine for the PR to just patch docs/ with your proposed changes first.

Ohhhh ok. That makes sense. Thanks for the tip!

**Comment by MRayermannMSFT** [comment]
Closing as my PR was merged. :)
