### ISSUE TITLE
[Feature Request]: add missing menu item role "Show All Tabs"

### ISSUE THREAD

**Issue by dmnsgn** [electron/electron#31624]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

https://github.com/electron/electron/pull/10321 added support for most but it is still missing the "Show All Tabs" role which display an "exploded" view of all tabs that is present when using the role "viewMenu".

"viewMenu" menu:
<img width="225" alt="Screenshot 2021-10-28 at 17 42 39" src="https://user-images.githubusercontent.com/1636460/139300667-7f0d6569-b4ac-4bc2-9581-57e602735029.png">

Resulting view:
<img width="1440" alt="Screenshot 2021-10-28 at 17 48 24" src="https://user-images.githubusercontent.com/1636460/139300673-cf0c111c-18ec-401b-8423-2310c5ce494c.png">

### Proposed Solution

Adding the role as `showAllTabs`.

### Alternatives Considered

N/A

### Additional Information

MacOS BigSur 11.5.1

**Comment by ameeet** [comment]
I would love to help!
I would need some guidance .

**Comment by ameeet** [comment]
@dmnsgn

**Comment by itsmingjie** [comment]
Hi! I'm one of the program coordinators of a nonprofit program called [CodeDay Init](https://labs.codeday.org/), and we partner with colleges to help CS students make their first open-source contribution. 

We'll claim this issue for now and a group of students will be on it soon with mentorship! If this issue is no longer relevant, please let me know.

**Comment by itsmingjie** [comment]
Hi! I'm one of the program coordinators of a nonprofit program called [CodeDay Init](https://labs.codeday.org/), and we partner with colleges to help CS students make their first open-source contribution. 

We'll claim this issue for now and a group of students will be on it soon with mentorship! If this issue is no longer relevant, please let me know.

**Comment by Ayush-Kori** [comment]
@dmnsgn  I would like to take up this Issue

**Comment by RaisinTen** [comment]
Hey folks, please feel free to send a PR instead of commenting that you would like to take this up! :)

**Comment by hemanthnxtwave** [comment]
I want to work on this issue . Please assign me this issue.

**Comment by Imperat** [comment]
PR raised: https://github.com/electron/electron/pull/38965
