### ISSUE TITLE
[Bug]: Much slower performance when fullscreen

### ISSUE THREAD

**Issue by Jazcash** [electron/electron#31653]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v9042

### What arch are you using?

x64

### Expected Behavior

Fullscreen: true should not noticeably affect performance

### Actual Behavior

Fullscreen: true does noticeably affect performance

### Additional Information

My app is getting roughly ~100 less fps when fullscreen is enabled. The app seemingly looks and behaves exactly the same in both. Worth mentioning I have devtools open in both in order to see the fps.

`fullscreen: false`
![image](https://user-images.githubusercontent.com/1434248/139704367-1e8bccbc-0a5f-4a49-8450-92fb8ce3fd39.png)

`fullscreen: true`
![image](https://user-images.githubusercontent.com/1434248/139704458-3fdf4ca0-c82d-4146-bf28-e3635322351b.png)

The full project is here: https://github.com/Jazcash/bar-lobby

Any ideas?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Jazcash** [comment]
I'd argue this is a bug report but ok

**Comment by Kitaharakasusa** [comment]
I have encountered the same problem. Have you solved it?
