### ISSUE TITLE
[Feature Request]: Introduce file drag icons made with HTML & CSS

### ISSUE THREAD

**Issue by Goubermouche** [electron/electron#31667]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Whenever anyone wants to implement file drag & drop behavior they have the option to use an icon, but this in my opinion limits the overall usefulness, since the user has to choose an already existing image (or potentially take a screenshot and use that).

### Proposed Solution

Add the option to attach an HTML file / string instead of a link to an icon.

### Alternatives Considered

Taking a screenshot of an element and using that as an icon.

**Comment by zcbenz** [comment]
The drag and drop icons are rendered by the operating system instead of the application, and we must pass actual images to the system and can not simply render a HTML document when dragging.

So this feature request is essentially asking us to provide a way to convert a HTML document/element to a small sized image, which I think requires too much work for a convenient feature like this, so I'm closing this as won't fix.
