### ISSUE TITLE
[Bug]: When one downloadItem is canceled  all other downloadItems will be blocked

### ISSUE THREAD

**Issue by xland** [electron/electron#31743]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Other downloadItems work correctly

### Actual Behavior

Other downloadItems will be blocked.
'updated' and 'done' event will not be triggered.

### Additional Information

My staple code is here.
When one downloadItem is canceled  all other downloadItems will be blocked.
Neither 'updated' nor 'done' event will be triggered.
```js
ipcMain.handle('cancelDownload', async (e, param) => {
        const currentParam = this.paramList.find(v => v.messageId == param.messageId)
        // currentParam.item.pause();   // useless too.
        currentParam.item.cancel()
    })
session.defaultSession.on("will-download", async (e, item)=>{      
        const param = this.paramList.find(v=>v.url === item.getURL())
        param.item = item
        this.listenDownloadUpdateEvent(param)
        this.listenDownloadDoneEvent(param)
    })
ipcMain.handle('dowloadFile', async (e, param) => {
        const flag = this.paramList.some(v=>v.url === param.url)
        if(flag) return
        this.paramList.push(param)
        e.sender.downloadURL(param.url)
    })
```
```js
private paramList = []
private listenDownloadUpdateEvent(param){
    param.item.on('updated', (event, state) => {  
      console.log('updated', param.messageId);    
    })
  }
private listenDownloadDoneEvent (param) {
    param.item.on('done', (event, state) => {
        console.log("one done:",state,param.messageId, this.paramList.map(v=>v.messageId))     
    })
  }
```

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by xland** [comment]
Download url has blank space will cause this issue.
