### ISSUE TITLE
[Bug]: auto-updater SQRLCodeSignatureErrorDomain with new certificate

### ISSUE THREAD

**Issue by teaxio** [electron/electron#31749]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

macOS

### Operating System Version

MacOS BigSur 11.5.2

### What arch are you using?

x64

### Last Known Working Electron version

13.0.1

### Expected Behavior

auto-updater should be able to pull the update file from Nucleus server and update

### Actual Behavior

This error occurs when the auto-update occurs `"code":-1,"domain":"SQRLCodeSignatureErrorDomain"`

### Additional Information

We have a Nucleus update server for our electronJS app. Previous versions of the app were signed by a Personal Apple Developer certificate. We decided to upgrade to an Enterprise Certificate for our organization. We released a new version and now the auto-updater is not able to update to the new version. The updater is able to successfully download the update, but it is not able to install it.
I understand how this is more for a security measure, but since this is something we (the app authors) are doing, is there a way to get around this?
Thank you

**Comment by ckerr** [comment]
Hi @teaxio, I think I may be misreading this issue or you might have typed it in wrong. Are you saying it's broken in 13.0.1 or that 13.0.1 was the last known working version?

Anyway, if this is not so much a bug as it is a security issue with changing certificates, you may have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I'm closing this issue as discussion since this tracker is only intended for tracking bugs in the code, but I hope those links help you to find the answers you're looking for!
