### ISSUE TITLE
[Bug]: when Use LoadFile to load local html file, SharedArrayBuffer is not available

### ISSUE THREAD

**Issue by dongyado** [electron/electron#31789]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

15.3.0

### Expected Behavior

I use wasm module on web pages, when load wasm, console print SharedArrayBuffer not available:

`
sxedit.js:1069 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

Uncaught ReferenceError: SharedArrayBuffer is not defined
`

 after research, i found chomium above 91 will need origin isolation to enable SharedArrayBuffer. So  will need some add header to reponse header. but is there a way to enable SharedArrayBuffer when use loadFile to open local pages.

### Actual Behavior

SharedArrayBuffer can not used in local web Files when use LoadFile

`
sxedit.js:1069 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

Uncaught ReferenceError: SharedArrayBuffer is not defined
`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
