### ISSUE TITLE
[Bug]: window.open frameName 

### ISSUE THREAD

**Issue by seefl** [electron/electron#31813]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0

### Expected Behavior

` mainWindow.webContents.setWindowOpenHandler(({ url,frameName }) => {
    // My actual effect is: window.open frameName ==='github'
    // But the expected effect is: window.open frameName ===''
    log.info(frameName)
    if(frameName === 'github'){
      return {
        action: "allow",
        overrideBrowserWindowOptions: {
          module:true,
          width,
          height,
        },
      };
    } else {
      // Open the browser
      shell.openExternal(url);
    }
    return { action: 'deny' }
  });`

### Actual Behavior

` mainWindow.webContents.setWindowOpenHandler(({ url,frameName }) => {

    // But the expected effect is: window.open frameName ===''  // Open the browser

      shell.openExternal(url);
    }
    return { action: 'deny' }
  });`

### Additional Information

    // My actual effect is: window.open frameName ==='github'  Open new window
    // But the expected effect is: window.open frameName ===''

**Comment by codebytere** [comment]
hi @seefl - I see that you've provided some code byt you've not described in plain language what the issue is. we'll need this information before we can properly proceed because as we look to triage issues, we want to make as few assumption as possible about the way you expected the code to behave as opposed to how it behaved.

We also require a standalone testcase with only the code necessary to reproduce the issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by seefl** [comment]
I have pushed the resource to the gist

[](https://gist.github.com/seefl/ea6568d3c0081874aed3bfdcfbfd016f)

**Comment by seefl** [comment]
I have pushed the resource to the gist  

url:  https://gist.github.com/seefl/ea6568d3c0081874aed3bfdcfbfd016f

[](https://gist.github.com/seefl/ea6568d3c0081874aed3bfdcfbfd016f)
