### ISSUE TITLE
[Bug]: Cookies removed when upgrading from 15 to 16

### ISSUE THREAD

**Issue by exander77** [electron/electron#31833]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-beta.6

### What operating system are you using?

Other Linux

### Operating System Version

21.10

### What arch are you using?

x64

### Expected Behavior

Cookies should be preserved between versions.

### Actual Behavior

Cookies are not preserved between some versions.

### Additional Information

This is a really big issue when you regularly update and there are important things set as cookies.

**Comment by ckerr** [comment]
Hi @exander77, is this the same as https://github.com/electron/electron/issues/31689? If so, that's been fixed in `main` via https://github.com/electron/electron/pull/31785 and that fix is currently being backported to 16.

- Even though it's 17 instead of 16, could you try out 17.0.0-nightly.20211112 or newer in the 17 line to confirm the fix?

**Comment by exander77** [comment]
@ckerr Do you recommend moving to 17 from 16 in general?

I will try, but I am not sure how I would make fiddle for losing cookies on upgrade.

**Comment by ckerr** [comment]
@exander77 I'm not recommending that you port your app to 17 right now, since it's in pre-beta mode. What I meant is that _temporarily_ using 17.0.0-nightly.20211112 with your code and seeing if it solves the problem would be the fastest way to confirm that this is the same bug.

**Comment by exander77** [comment]
@ckerr How I can upgrade to nightly from npm, those 17 nightly packages do not seem to be available.

**Comment by vladimiry** [comment]
@exander77 try to use https://www.npmjs.com/package/electron-nightly instead of https://www.npmjs.com/package/electron

**Comment by SpacingBat3** [comment]
> Hi @exander77, is this the same as #31689? If so, that's been fixed in `main` via #31785 and that fix is currently being backported to 16.
> 
>  * Even though it's 17 instead of 16, could you try out 17.0.0-nightly.20211112 or newer in the 17 line to confirm the fix? That nightly has the 31785 fix and should be good to test out whether this is the same issue.
> 
>  * If that's _not_ it and it's a separate issue, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

@ckerr I believe I have reproduced this issue and it seems to occur for both latest `17-x-y` nightly and alpha versions. I've also tested the current latest version (`v16.0.2`). From my experiments, this bug seems to be similar to the one described in #31689 and it occurs only when `localStorage` is being used in `preload` scripts of `BrowserWindow` (where #31689 describes it is caused in preloads of `WebViews`). I hope anyone will find that comment helpful.

**Comment by exander77** [comment]
Is there a version that does not forget cookies?

**Comment by SpacingBat3** [comment]
> Is there a version that does not forget cookies?

I've recently found myself a workaround for this issue. You just need to use the `localStorage` after page stopped to load. (`contents.on('did-stop-loading', ...)`).
