### ISSUE TITLE
Chromium and electron based applications does not use hardware accelerations

### ISSUE THREAD

**Issue by Joe23232** [electron/electron#31859]
With the distros that I have used such as Xubuntu, Manjaro and EndvourOS, even though if on chromium I have enabled hardware acceleration, my PC fails to use it unless if I force hardware accelerations by enabling certain flags and this is the same issue on any PC that I install Linux on.

With electron based applications (since it is based on the blink rendering engine like what chromium uses), it is the same issue, but this time alot of these electron based applciations don’t have “chromium flags”.

There must be something that is causing chromium/electron based applications to not use hardware acceleration(s), even though it is enabled in the settings?

What would I need to do to fix this?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Joe23232** [comment]
@codebytere 
Thanks for your help.
