### ISSUE TITLE
[Bug]: Failed to show BrowserWindow after it was hidden while running a child process

### ISSUE THREAD

**Issue by majoglattli** [electron/electron#31861]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

 15.2.0

### Operating System Version

macOs Big Sur 11.6

### Expected Behavior

The application executes BrowserWindow.show() correctly after being hidden while the child process is running.

### Actual Behavior

Sometimes BrowserWindow.show() does not execute correctly after the child process is closed; it does not redirect the user to the right desktop (where the main window is set to full screen).

### Additional Information

We create a new BrowserWindow and set the full screen to _true_ when it is shown, then hide it to run a child process. The expected behavior would be to display the mainWindow after the child process is closed, and then directly showcase the desktop where the mainWindow is located.

We believe there is some kind of bug related to the time **mainWindow.show()** is executing, since if we use a timeout, that error disappears.

index.js

```
  mainWindow = new BrowserWindow({
     webPreferences: {
       webSecurity: false,
       nodeIntegration: true,
       contextIsolation: false,
       preload: join(__dirname, "preload.js"),
     },
     show: false,
     frame: false
   });
 
   mainWindow.setMenu(null);
 
   mainWindow.on("closed", () => {
     mainWindow = null;
   });
 
   mainWindow.on("leave-full-screen", () => {
     mainWindow.hide();
   });
 
   mainWindow.on("show", async () => {
     mainWindow.setFullScreen(true);
   });

```

player.js

```
 const { spawn } = require('child_process');
 const options = { cwd: '../player' };
 const player = spawn(exeName, args, options);
 
 mainWindow.hide();
 
 player.on('close', async code => {
   console.log(`child process exited with code ${code}`);
   mainWindow.show(); // This line is not executed correctly
 });
```

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by majoglattli** [comment]
Thanks for your quick response!

I created a stand-alone test for you guys to reproduce.

### Link:
**https://gist.github.com/majoglattli/42f0926839196e05c5248da5b6e07c23**

### Things to keep in mind:
- Make sure to give Electron Fiddle access to control the PC (Security & Privacy> Privacy> Accessibility)
- Close any open Safari window

### What it does:
- Hide the Electron window
- Generates a new child process that opens Safari
- Sets Safari to full screen (control + command + F)
- Wait 5 seconds
- Close the Safari window (command + Q)
- Show the Electron window

### What we expect:
When the child process is closed, we expect Electron BrowserWindow.show () to direct the user to where the window is displayed. 
We can only make it work by setting a timeout function on child process close (you can see it commented in the code).

Thank you again,
Kind regards,
María

**Comment by majoglattli** [comment]
bump
