### ISSUE TITLE
[Bug]: Permission issue in electron js (NEXT.js + Electron)

### ISSUE THREAD

**Issue by dipaksavaliya** [electron/electron#31875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

macOS

### Operating System Version

macos catalina 1.01507

### What arch are you using?

Other (specify below)

### Expected Behavior

i should be able to run project successfully and want to remove this preference error

### Actual Behavior

I'm creating a desktop application using electron. I need camera, microphone and screen recording permission so I'm using systemPreferences But Getting undefined for system preference mediaType as a 'camera', 'microphone' and 'screen'

### Additional Information

Here is the full function we use to request media access. It is called when the Permission Request Handler is invoked with the media permission. The app does not reach the catch Block, so the error is not logged. We tested this behavior on 3 different machines

- mediaType as a 'camera', 'microphone' and 'screen'

**Below is a code**

export default async function onPermission(mediaType) {
  try {
    console.log("systemPreferences", systemPreferences);
    const status = await systemPreferences.getMediaAccessStatus(mediaType);
    console.log(`Current ${mediaType}  access status:`, status);

    if (status === "not-determined") {
      const success = await systemPreferences.askForMediaAccess(mediaType);
      console.log(
        `Result of ${mediaType}  access:`,
        success.valueOf() ? "granted" : "denied"
      );
      return success.valueOf();
    }
    return status === "granted";
  } catch (error) {
    console.log(`Could not get ${mediaType} permission:`, error.message);
  }
  return false;
}

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by dipaksavaliya04** [comment]
[my-app.zip]![Annotation 2021-11-26 130117](https://user-images.githubusercontent.com/93366473/143543414-e233dfac-3973-4c84-8aea-bcfbb2841b51.png))

This is my code and permission function inside renderer folder -> helpers -> permission.jsx

and permission function use inside renderer folder ->  components folder -> permission.jsx

and permission component use inside renderer folder -> pages folder 

** I need camera, microphone and screen recording permission so I'm using systemPreferences But Getting undefined for system preference mediaType as a 'camera', 'microphone' and 'screen'**

**Comment by dipaksavaliya04** [comment]
[my-app.zip](https://github.com/electron/electron/files/7607134/my-app.zip)

**Comment by dipaksavaliya04** [comment]
Any solution for this bugs ??
