### ISSUE TITLE
[Feature Request]: Add support for Windows 11's split color mode selector

### ISSUE THREAD

**Issue by devinbinnie** [electron/electron#31898]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently our (Mattermost) application uses the dark mode setting in `nativeTheme` to check to see which tray icon we renderer, be it a light or a dark one. If the value of `shouldUseDarkColors` is `true`, we renderer a white tray icon, and a black one for when it is false.

However, in Windows, the user can select a different setting for apps and the Windows interface. We've had some user reports that the icon appears black when they're using dark mode for the interface, but not for the apps.

### Proposed Solution

I'd like to suggest adding the ability to check for both settings in Windows so that we can assign the icon accordingly, and differentiate between what needs to be light/dark for the OS vs. our app.

### Alternatives Considered

- Changing our icon: It's not out of the realm of possibility, but it would be ideal to have this feature instead.
- Force users to make sure they have light and dark set for both: Also possible, but sometimes creates a training issue and gives us a bad taste, also some users may wish to have a dark Windows interface and light apps (I'm not one of those, but I assume people want that :P)

**Comment by tresf** [comment]
I'm not an electron user, and I understand that this issue is closed, but I've spent a considerable amount of time researching  this across nearly all Windows 10 versions, so I wanted to (re)share my findings, which are also published [here](https://stackoverflow.com/a/61148435/3196753).

Windows stores light/dark mode settings in two separate preferences: Applications (`AppsUseLightTheme`) and System (`SystemUsesLightTheme`).  The taskbar icon is handled by `SystemUsesLightTheme`.  When the documented registry entries are missing, it appears something in the OS is coded to fallback the following settings.  This information was gathered by installing as many Windows 10 versions and testing the registry values against the default Windows 10 appearance.

```reg
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\
```

* If `AppsUseLightTheme` is missing, assume it's 1
... and then make the dark/light Windowing decisions based on this value.
* If `SystemUsesLightTheme` is missing, assume it's 0
... and then make the dark/light Taskbar/SystemTray decisions based on the this value.

This logic has been in production on over 100,000 computers for 4 years and has been working very well.

I'm leaving this here only for informational purposes since this issue was a common landing spot when searching the internet for this problem. 🍻
