### ISSUE TITLE
[Bug]: production version  will be break by  "TypeError: Error processing argument at index 0 in production "

### ISSUE THREAD

**Issue by colining** [electron/electron#31893]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^15.3.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

production same as dev 

### Actual Behavior

I'm using package @cliqz/adblocker-electron  https://www.npmjs.com/package/@cliqz/adblocker-electron

and it's working normally on dev, but when I package and run the production version. It's will be an error  and don't create a new window

the error log is like this
```
node:18588) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from 
    at enable (F:\workspace\electron-react-webview-adblock-test\release\build\win-unpacked\resources\app.asar\dist\main\main.js:2:197327)
    at tn.enableBlockingInSession (F:\workspace\electron-react-webview-adblock-test\release\build\win-unpacked\resources\app.asar\dist\main\main.js:2:199713)
    at v (F:\workspace\electron-react-webview-adblock-test\release\build\win-unpacked\resources\app.asar\dist\main\main.js:2:785754)
    at F:\workspace\electron-react-webview-adblock-test\release\build\win-unpacked\resources\app.asar\dist\main\main.js:2:786585
(Use `ElectronReact --trace-warnings ...` to show where the warning was created)
```

by the way, the code I use in this package is like this

```
  mainWindow = new BrowserWindow({
    show: false,
    minWidth: 720,
    width: 1600,
    height: 1024,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      enableRemoteModule: true,
      nodeIntegration: true,
      webviewTag: true,
    },
  });
  console.log('====', getAssetPath('easylist-china.txt'));

  const filter = fs.readFileSync(getAssetPath('easylist-china.txt'), 'utf-8');
  console.log('filter', filter);
  const blocker = await ElectronBlocker.parse('||bianxianwu.com^');
  console.log('blocker', blocker);
  console.log('session', mainWindow.webContents.session);
  blocker.enableBlockingInSession(mainWindow.webContents.session);    //I think this line break the whole app
```

### Additional Information

Any Idea will be helpful ,thanks a lot

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by colining** [comment]
I found It's work if I write code like this：
```
  mainWindow
    .loadURL(`file://${__dirname}/index.html`)
    .then(() => {
      return blocker.enableBlockingInSession(mainWindow!.webContents.session);
    })
    .catch((e) => console.log(e));
```
