### ISSUE TITLE
[Bug]: Electron helper high cpu usage

### ISSUE THREAD

**Issue by crapthings** [electron/electron#31916]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS big sur 11.5.2

### What arch are you using?

x64

### Expected Behavior

Observing system load should be fine I think.

https://systeminformation.io/statsfunctions.html

the module works fine itself, but when i run it with electron or as a fork process it impact cpu usage

### Actual Behavior

![image](https://user-images.githubusercontent.com/1147704/142694927-da78bf5a-4c17-4c4d-b356-c26706f4d352.png)

the electron helper is about 99% usage

### Testcase Gist URL

https://github.com/crapthings/revealer

### Additional Information

![image](https://user-images.githubusercontent.com/1147704/142695082-6956a398-43d3-4652-9581-9d81739bc4c3.png)

```bash
git clone https://github.com/crapthings/revealer
cd revealer
npm i
npm run dev
```

**Comment by crapthings** [comment]
![image](https://user-images.githubusercontent.com/1147704/142720867-bcaf51bb-d932-42fb-9ddd-2f03219f1bcf.png)

macOS High Sierra 10.13.6 is okay

**Comment by vladimiry** [comment]
Also starting from @electron v16 facing an abnormally high CPU load issue, see https://github.com/vladimiry/ElectronMail/issues/461. So had to downgrade to v15. Could not yet narrow down the scope.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by M00N-MAN** [comment]
@deepak1556 

Do you think this thread https://github.com/microsoft/vscode/issues/148226 is related to the current bug?

**Comment by yanguoqiang29** [comment]
我目前用的是 Linux arch芯片的电脑，使用electron做的应用出现了这个问题，有什么解决办法吗？
#######
I am currently using a computer with Linux arch chip. This problem occurs in the application made with electron. Is there any solution?
