### ISSUE TITLE
[Bug]: nodeIntegration cannot be disabled via window.open() with nativeWindowOpen

### ISSUE THREAD

**Issue by miniak** [electron/electron#31949]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

I have a `BrowserWindow` with `nativeWindowOpen` enabled and `nodeIntegration` enabled. I want to open a popup using `window.open('popup.html', '', 'nodeIntegration=no');`, to have `nodeIntegration` disabled. This is documented here: https://github.com/electron/electron/blob/086526738745f205241aed9926bb8915759c0f76/docs/api/window-open.md#L45-L47

### Actual Behavior

The popup window has `nodeIntegration` enabled incorrectly. However, when the parent window has `nativeWindowOpen` disabled, it works.

### Additional Information

[native-window-open-node-integration.zip](https://github.com/electron/electron/files/7577664/native-window-open-node-integration.zip)

Test passed: Electron exited with code 0.
Test failed: Electron exited with code 1.

This issue is blocking #29405

**Comment by codebytere** [comment]
@miniak i think this might be intentional? 

https://github.com/electron/electron/blob/18cc33055db5f2cf2a5a79e1fdb86ee7105eb711/lib/browser/guest-window-manager.ts#L231-L260

**Comment by zcbenz** [comment]
@codebytere The bug is the child window has nodeIntegration enabled incorrectly, while the referenced code tries to disable nodeIntegration, so it does not seem related.

**Comment by codebytere** [comment]
ah you're right , misread it!

**Comment by zcbenz** [comment]
I have some basic ideas on this issue, will try to create a PR later.

**Comment by zcbenz** [comment]
The root cause of this issue is, when a child window is created with `window.open`, Chromium will load an empty page in it immediately in renderer, which bypasses browser side navigation and we don't have a chance to override the child window's WebPreferences. So when the empty page is loaded in the child window, its parent's WebPreferences will be used and the child window will have node integration enabled in it.

I have a simple workaround at https://github.com/electron/electron/compare/child-window-prefs?expand=1, and I'm still fixing a few tests that rely on this buggy behavior.

An ideal fix would be prevent Chromium from loading an empty page in child window before navigation, but I couldn't find out how to achieve that and I'm not sure if changing this behavior would break things.
