### ISSUE TITLE
[Bug]: document.visibilityState broken in window opened from <webview> with nativeWindowOpen

### ISSUE THREAD

**Issue by miniak** [electron/electron#31959]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

I open a scriptable popup window from a webview, which has `nativeWindowOpen` enabled (explicitly or via sandbox). I expect `document.visibilityState` to work correctly.

### Actual Behavior

`document.visibilityState` always returns `visible` even when the window is occluded or minimized.

### Additional Information

[window-open-document-visibility.zip](https://github.com/electron/electron/files/7583777/window-open-document-visibility.zip)

The problem is that the window is incorrectly identified as being a webview, which has customized `document.visibilityState` handling:
https://github.com/electron/electron/blob/4713acce8dff0528a3025b40c4feed82439a8538/lib/renderer/window-setup.ts#L321-L352

I think the root cause is the same as in #31949.

**Comment by zcbenz** [comment]
This issue has a very similar root cause with https://github.com/electron/electron/issues/31949: when opening a child window with `window.open` to load a URL that has the same origin, Chromium would initialize the JS context immediately with the parent page's web preferences, and we did not get a chance to override the web preferences.

So when initializing Node.js for the child window, the `isWebView` preference is inherited from parent webview and the child window will be treated as a webview too.
