### ISSUE TITLE
[Bug]: setInterval and setTimeout delays after few minutes from 10ms => 60ms

### ISSUE THREAD

**Issue by iamisti** [electron/electron#31967]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 and Windows 11

### What arch are you using?

x64

### Expected Behavior

setInterval and setTimeout fires roughly the specified time.

### Actual Behavior

I have quite a lot of setInterval and setTimeout calls specified in my project (roughly around the amount of 40-50 setintervals/settimeouts).
Few of these setIntervals have low delays specified (10ms), others have a lot higher value (1000ms, 5000ms, etc).

My problem is that the low delay intervals works fine for the first few minutes, sometimes even longer, but then randomly they start firing with a big delay. I've measured it and from 10ms it goes up to 50-60ms which is unacceptable.

This is clearly an electron issue, it seems like the whole thing gets throttled for no apparent reason (the code that exectutes these 10ms tasks are done in 0-1ms, so this shouldn't be an issue)

Plaese help me how I can fix this because it's quite a major issue now in my project!

Thank you

### Additional Information
I'm using the following command to create the nodejs server where this issue is happening:

```
serverWindow = new BrowserWindow({
    height: 600,
    show: true,
    webPreferences: {
      devTools: true,
      backgroundThrottling: false,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      webSecurity: false,
    },
    width: 800,
  });
```

as well as this in the main process:
```
app.commandLine.appendSwitch("disable-background-timer-throttling");
app.commandLine.appendSwitch("disable-site-isolation-trials");
app.allowRendererProcessReuse = false;
```

**Comment by BlackHole1** [comment]
Please create a gist using `Electron Fiddle` to facilitate our positioning.

In the meantime, you may need to see if this is caused by the `eventloop lag`.

When your code has performance issues, it can affect the `event loop`, which in turn can lead to inaccurate `setTimeout` and `setInterval`.

**Comment by baconbrad** [comment]
Keep in mind your reported Electron version is no longer supported. Have you tried to upgrade to a later version of Electron to see if this is resolved? Because even if it is reported to be an issue a fix will not be backported v12.x.

12.x is around the time timer throttling was introduced in Chromium 88. 12.x uses 89 so there might have been some tweaks needed to smooth this out. Would have to revisit the change logs to be sure.

Historically timers in browsers have never been perfect and certain versions have made things worse just as much certain versions have made them better. As BlackHole1 has mentioned other things could cause unexpected lag of these timers. If precision is a must I would look into using a accurate timer node package which have checks against the client's time to offset the stray of setInterval and setTimeout. For our product in some cases where accuracy was important this got us in the sub 10ms range on versions this was exceeded.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
