### ISSUE TITLE
mouse can't work in alert dialog.

### ISSUE THREAD

**Issue by xiaojun777** [electron/electron#31966]
code:
document.body.addEventListener('mousedown', function(){alert('hello')});

run code in electron, and click in html > body, press 'enter' can close alert dialog, but mouse click can not.

**Comment by xiaojun777** [comment]
make testing in electron-16

**Comment by xiaojun777** [comment]
try show modal browserwindow, when mousedown fired. same as alert dialog.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
