### ISSUE TITLE
[Bug]: getSources has crashed when no active windows

### ISSUE THREAD

**Issue by papamishka911** [electron/electron#31987]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Last Known Working Electron version

15.3.1

### Expected Behavior

`desktopCapturer.getSources({ types: ['screen', 'window'], thumbnailSize: { width: 150, height: 150 } })` causes an electron app to fall, when no active (not minimized) windows on the desktop (except current electron app). 

`desktopCapturer.getSources({ types: ['screen', 'window'], thumbnailSize: { width: 0, height: 0 } })` is still work.

### Actual Behavior

`desktopCapturer.getSources({ types: ['screen', 'window'], thumbnailSize: { width: 150, height: 150 } })` should return every screen and the electron window that ran it, when no other active windows.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by jeanfbrito** [comment]
We are having this issue too on Rocket.Chat Electron app.
When the desktopCapturer.getSources is called if there isn't any other window beside the electron one, the app crashes without any log. I tried to debug but it just crashes and quit.

It only happens in Windows and if you have any other window open besides the electron application, it didn't happen.
If you have other windows and start polling the function, it will work, then you start closing another windows until there is only the electron one and it will crash.

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.
