### ISSUE TITLE
can't start the UI of electron

### ISSUE THREAD

**Issue by ctlinglingliu** [electron/electron#31980]
when i run the electron ，the UI of the electron can't start
and i use the gdb to debug  the electron ,there is  a error below,there has a thread exited:
####################################################
Starting program: /home/lgs/electron-binary/electron --no-sandbox
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/loongarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xfff513d370 (LWP 195736)]
[Detaching after fork from child process 195737]
[Detaching after fork from child process 195738]
[New Thread 0xfff513d370 (LWP 195739)]
[New Thread 0xfff513d370 (LWP 195740)]
[New Thread 0xfff513d370 (LWP 195741)]
[New Thread 0xfff313eaf0 (LWP 195742)]
[New Thread 0xfff513d370 (LWP 195743)]
[New Thread 0xfff513d370 (LWP 195744)]
[New Thread 0xfff513d370 (LWP 195745)]
[New Thread 0xfff513d370 (LWP 195746)]
[New Thread 0xfff513d370 (LWP 195747)]
[Thread 0xfff313eaf0 (LWP 195742) exited]

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. Please open a new issue with the template correctly filled out.
