### ISSUE TITLE
[Bug]: -webkit-app-region: drag Is there a way to receive a double click event?

### ISSUE THREAD

**Issue by wonkyungup** [electron/electron#31996]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.0

### What operating system are you using?

Windows

### Operating System Version

windows10 pro build 19043

### What arch are you using?

x64

### Last Known Working Electron version

13.6.0

### Expected Behavior

1. After setting webkit-app-region: drag
2. use Mouse event

### Actual Behavior

webkit-app-region: drag Every event has an eating phenomenon.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
