### ISSUE TITLE
[Bug]: webContents.capturePage() returns empty image for fully occluded BrowserWindow on Windows

### ISSUE THREAD

**Issue by miniak** [electron/electron#31992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 (10.0.22000.348)

### What arch are you using?

x64

### Last Known Working Electron version

10.4.7

### Expected Behavior

`webContents.capturePage()` should work for fully occluded BrowserWindow as the window is not minimized.

### Actual Behavior

`webContents.capturePage()` returns an empty `NativeImage` in this case.

### Additional Information

main.js for Fiddle
```js
const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })

  setInterval(async () => {
    const image = await mainWindow.capturePage();
    console.log(image.getSize())  
  }, 1000);

  mainWindow.loadFile('about:blank')
  mainWindow.webContents.openDevTools({mode:'detach'})
}

app.whenReady().then(() => {
  createWindow()
})

app.on('window-all-closed', function () {
  app.quit()
})
```

to reproduce cover the BrowserWindow with the devtools, you'll see the image size being logged as `{ width: 0, height: 0 }`.

This is a regression from #27883, when I revert the change `webContents.capturePage()` is working correctly for occluded windows. Checking the visibility state does not seem correct to me as both occluded and minimized windows' webContents have visibilityState hidden.

The abandoned fix #27892 seems like a better option. Also according to the documentation of `CopyFromSurface`:
>  // |callback| is guaranteed to be run, either synchronously or at some point
>  // in the future (depending on the platform implementation and the current
>  // state of the Surface). If the copy failed, the bitmap's drawsNothing()
>  // method will return true.
>  //
>  // If the view's renderer is suspended (see WasOccluded()), this may result in
>  // copying old data or failing.
>  virtual void CopyFromSurface(
>      const gfx::Rect& src_rect,
>      const gfx::Size& output_size,
>      base::OnceCallback<void(const SkBitmap&)> callback) = 0;

**Comment by deepak1556** [comment]
> If the view's renderer is suspended (see WasOccluded()), this may result in copying old data or failing.

@miniak if you have reverted the above change, do you always get the data from the callback when occluded ? If so then we can change the condition to also check on `content::WebContents::WasOccluded`

My worry is that occluded window will put the renderer scheduler into a throttled state because of https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_native_window_occlusion_tracking.md, so the callback may not always fire.

**Comment by miniak** [comment]
why does the documentation claim that "|callback| is guaranteed to be run"?

**Comment by codebytere** [comment]
@miniak from the abandoned PR:

> When BrowserWindow.webContents.capturePage is called on hidden
page we try to resolve its promise on the worker thread instead of
the main thread of the browser process. It happens because when page
is hidden compositor calls the callback OnCapturePageDone immediately
without posting it to the main thread). When it happens worker thread
dead locks as it tries to acquire lock kept by the main thread (the
lock which guards the promise returned by capturePage).

It may be that the callback is always run per design, but this error makes it so that in some scenarios that's prevented.

**Comment by pushkin-** [comment]
@miniak This still reproduces in Electron 21

**Comment by pushkin-** [comment]
repros in v23

**Comment by miniak** [comment]
bump

**Comment by pushkin-** [comment]
bump
