### ISSUE TITLE
[Bug]: Menu selections jumps to the first element when try to select sub-menu

### ISSUE THREAD

**Issue by Mingun** [electron/electron#31994]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.2 - from VSCode about. I don't known which version GitKraken used

### What operating system are you using?

Ubuntu

### Operating System Version

$ uname -a Linux mingun 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Working menus

### Actual Behavior

See attached GIF: when you try to select sub-menu element the menu selection focus jumps to the first element of menu which caused to hide sub-menu.
![VSCodeMenuBug](https://user-images.githubusercontent.com/450131/100836768-b36b7b80-3491-11eb-91d7-2e1727dd8fd2.gif)

For clarify: this happens when I connect to my Ubuntu 18.04/20.04 remotely via RDP (with xrdp). Maybe this bug also reproducible with physical access -- I cannot check that now.

On Windows I've never faced with such problem.

Can be reproduced in VSCode and GitKraken. See the original report in https://github.com/microsoft/vscode/issues/111716

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Mingun** [comment]
Unfortunately, Electron Fiddle hungs on loading concrete electron version when I try to run project. Just nothing happens, no logs, nothing. Is it able to work behind a proxy? I have no much time to debug it problems.

**Comment by Mingun** [comment]
I've got a physical access to my machine and this bug is not reproduced them. But I have different desktop environments for RDP connection and direct access:
* RDP -- GNOME 3, bug is present
* direct -- Unity, bug is not present

**Comment by Mingun** [comment]
I think, at least you can try to reproduce this is VSCode as shown on the GIF.
