### ISSUE TITLE
[Bug]: Dev Tools arrow to toggle to show tools list isn't working

### ISSUE THREAD

**Issue by Inqnuam** [electron/electron#32077]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.3

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6.1 (20G224)

### What arch are you using?

x64

### Last Known Working Electron version

16.0.2

### Expected Behavior

Show full tools list

### Actual Behavior

No response

### Additional Information

 Dev Tools arrow to show tools full list isn't working  when called from **mainWindow.webContents.openDevTools()**
It is working after closing and reopening again Dev Tools manually
![dev tools](https://user-images.githubusercontent.com/69360379/144302565-beb22efe-6d9a-461f-8954-a76cc1642114.gif)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Inqnuam** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Hello,
Thanks for the answer.
It seems like it was been fixed in 16.0.5.
Im closing this issue.
