### ISSUE TITLE
[Bug]: All web content turn completely transparent when resume from OS wakeup 

### ISSUE THREAD

**Issue by BrightWind** [electron/electron#32084]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19041

### What arch are you using?

x64

### Last Known Working Electron version

13.1.9

### Expected Behavior

Keep display the web content properly.

### Actual Behavior

Windows settings:

- We have the default windows settings for the closing the lid option and power option.

Electron settings:

-     type: 'toolbar', 
-     frame: false, 
-     resizable: false,
-     transparent: true, 

Web App behaviors:
after closing the lid for about 20mins, we then sign the OS, click on our electron app, the web app will send a message to the main process to stretch the window from a small size of 185*187 to a medium size of  388 * 187 and show the related content.
But sometimes, the web content turn completely transparent, we have only set the background to be transparent, but the internal content has a non-transparent image and  the foreground content should not be transparent. nomarlly all content could  dispaly correctly. is any idea what is happening? any idea how I can figure out the cause?

**Comment by ckerr** [comment]
> is any idea what is happening? any idea how I can figure out the cause?

Hi @BrightWind, thanks for reporting this.

The first thing I'd suggest is to see if testing on a newer version of Electron works. 17.1.0 is the latest stable release, and since Electron [supports the most recent 4 major version numbers](https://www.electronjs.org/docs/latest/tutorial/support#supported-versions) of 14 through 17, this means that 13.1.9 is currently unsupported. More importantly for you, though, this also means that there have been several releases in which this issue may have been fixed either by a bugfix or by a refactor in the code.

If you're still experiencing this issue in the latest version of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.
