### ISSUE TITLE
[Bug]: Upgrading to v16 breaks screensharing in Google Meet

### ISSUE THREAD

**Issue by anulman** [electron/electron#32127]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

macOS

### Operating System Version

Monterey, 12.0.1 (21A559)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

15.3.3

### Expected Behavior

The testcase gist should be able to share a screen through Google Meet using the v16.x series.

### Actual Behavior

The testcase gist throws an error and cannot share a screen through Google Meet using the v16.x series.

### Testcase Gist URL

https://gist.github.com/anulman/1d3be658c8fe5d460f13f7f27f7f4149

### Additional Information

Here is a Loom demonstrating the issue: https://www.loom.com/share/51ac83d8911f471f9c654fc4f3dfcab2

This is sort-of related to #29081 insofar as it's about Google Meet screenshare support, however as you can see in the Loom previous versions of Electron allowed us to shim in screensharing support.

**Comment by anulman** [comment]
Poking this pre-holidays bug. I'm happy to take on R&D to fix it, but if any of you maintainers can help me isolate this to Electron vs. Chromium codepaths I'd be greatly appreciative!

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by EricRahm** [comment]
Hi @nornagon there's a fiddle in the report, do you need something different or is that good enough?

> Testcase Gist URL
https://gist.github.com/anulman/1d3be658c8fe5d460f13f7f27f7f4149

**Comment by nornagon** [comment]
@EricRahm that loads all of Google Meet, which is an enormous, non-open-source product into which we have no visibility. Without some narrower idea of specifically what is broken, it's hard to know where to look.
