### ISSUE TITLE
webview new-window not work

### ISSUE THREAD

**Issue by QMangoJ** [electron/electron#32138]
const webview = document.querySelector('webview');

        if (webview) {
          webview.addEventListener('new-window', e => {
            debounce(this.openWebView(e), 1000, { leading: true, trailing: false });
          });
        }

webview的new-window事件失效
electron版本为15.3.0

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
