### ISSUE TITLE
[Bug]: webContents.setWindowOpenHandler cannot set preload

### ISSUE THREAD

**Issue by IrvingZhao** [electron/electron#32136]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### What arch are you using?

x64

### Expected Behavior

``` Typescript
const conversationWindow = new BrowserWindow({
  webPreferences: {
    devTools: true,
    preload: path.resolve(__dirname, 'preload.js')
  }
})

  conversationWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url === 'about:blank') {
      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          frame: false,
          fullscreenable: false,
          backgroundColor: 'black',
          webPreferences: {
            preload: resolve(__dirname, 'preload2.js')
          }
        }
      }
    }
    return { action: 'deny' }
  })
```
In conversationWindow, use `window.open('about:blank')` to open a new window, execute preload2.js

### Actual Behavior

it also execute preload.js

### Testcase Gist URL

[index.ts](https://gist.github.com/IrvingZhao/dcf4e98a44a31ebb2d83eb83a4608357)

**Comment by thorsent** [comment]
I think that preloads will not run in window.open when `contextIsolation=true` for the parent window. This appears to be the case for both `setWindowOpenHandler()` as well as the deprecated `new-window` event (when setting newGuest).

I'm running Electron 13.6.1 . Since the OP is version 16.0.2, I think this is possibly a generalized problem.

@IrvingZhao can you try `contextIsolation=false` to see if the preload runs? (Perhaps it's defaulting to true in recent releases?)

**Comment by thorsent** [comment]
Same with `-add-new-content` (https://github.com/electron/electron/pull/26802). Preloads will only run when contextIsolation is false in the parent.

**Comment by thorsent** [comment]
This issue was mentioned in another thread: https://github.com/electron/electron/issues/16224#issuecomment-803315750

**Comment by bastecklein** [comment]
I am having a similar issue.  When my app was using Electron 14.x and I called window.open, the preload script was working on the child window (which is what I wanted).  I have now upgraded to Electron v16.0.5 and the preload script is no longer loading on my child window, and I am not seeing anything in the changelogs to indicate why this is happening.  I need to have contextisolation: true, and it worked fine before updating electron.

**Comment by t57ser** [comment]
This is happening because when navigating to about:blank the window will take over the webpreferences from the parent and it is not possible to change them.
https://github.com/electron/electron/blob/94d4a07fa2399eb6e64fc941bc73c7d644ad559d/shell/renderer/electron_render_frame_observer.cc#L84-L86
Note that this is only happening for about:blank. See:
https://github.com/electron/electron/blob/94d4a07fa2399eb6e64fc941bc73c7d644ad559d/shell/renderer/electron_render_frame_observer.cc#L99-L102
Other cases will work fine

**Comment by general-ice** [comment]
It looks like fixed. Latest electron 20.0.2
