### ISSUE TITLE
[Bug]: can't close [Picture in Picture] in video controls

### ISSUE THREAD

**Issue by whuhewei** [electron/electron#32156]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6.1

### What arch are you using?

x64

### Last Known Working Electron version

13.4.0

### Expected Behavior

I can close the [Picture in Picture]
![image](https://user-images.githubusercontent.com/66014139/145705623-fa338e27-bffb-4397-b9e4-d8de4342291a.png)

### Actual Behavior

the [Picture in Picture] can't be closed

**Comment by whuhewei** [comment]
I think this is an obvious bug and should be fixed.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by seatalkhewei** [comment]
Does anyone knows how can I import a video file in Electron Fiddle?

**Comment by seatalkhewei** [comment]
https://gist.github.com/seatalkhewei/393b9de885a6ea02b0f7b23bb9991447

**Comment by codebytere** [comment]
It remains unclear what the issue is. I can switch to picture in picture then close the window and switch back without an issue. Could you provide a video? more information?

**Comment by seatalkhewei** [comment]
https://www.dropbox.com/s/k5sfttem0qwhyh9/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62022-01-11%20%E4%B8%8A%E5%8D%889.31.39.mov?dl=0
