### ISSUE TITLE
[Bug]: Windows store (APPX) electron application consume more memory

### ISSUE THREAD

**Issue by gsvin99** [electron/electron#32153]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

15.0.0

### Expected Behavior

automatically release all the memory used by the app after some time, if application running long time.

### Actual Behavior

I'm using electron application from windows store. The application running long time and it not closed. After some time, electron application memory usage gradually increased.

This issue not happen, if we are using directly in windows os.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! It looks like this issue is using a version of Electron that is no longer supported. It's also a bit hard for our team to take action on this issue in its current state - we don't have a performance profile, logs or any repro steps that we can use to investigate further.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. However, if you're able to repro this issue on newer, supported versions of Electron and can include a performance profile or additional repro steps, please feel free to open a new issue!
