### ISSUE TITLE
[Bug]: Confirm if only sqlite3 library is used and not CLI

### ISSUE THREAD

**Issue by baparham** [electron/electron#32221]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Other (specify below)

### Operating System Version

Across both Linux and Windows Electron binaries

### What arch are you using?

x64

### Expected Behavior

I would expect that Electron is only using the sqlite3 library, and not the CLI, but want to confirm

### Actual Behavior

Unknown at this time

### Additional Information

Based on CVE-2021-36690 (https://www.sqlite.org/cves.html#status_of_recent_sqlite_cves) that affects sqlite CLI .expert extensions, I would like to verify that current versions of Electron (e.g. 16.0.4) which use sqlite are not affected.

There's also the possibility that this is in the Chromium space, in which case I can take my question over there.

Thanks for the support!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
