### ISSUE TITLE
I waited 1 Hr.

### ISSUE THREAD

**Issue by DevBloxYoutube** [electron/electron#32231]
It never loaded.

**Comment by VerteDinde** [comment]
Hey @DevBloxYoutube! I think you may be looking for the Roblox exploit - which we are not. 😊 You may need to find their website and report help there!

If you were trying to load an Electron app and it wasn't working, we'd still be happy to help you. But because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. I'm going to close this issue, but  please check out the [Electron community Discord](https://discord.gg/electronjs) ! We have many active help channels and mentors, as well as fellow devs, who can help you out. Good luck!
