### ISSUE TITLE
[Bug]: Grey layer over whole application

### ISSUE THREAD

**Issue by dccoder84** [electron/electron#32278]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.2

### What operating system are you using?

Ubuntu

### Operating System Version

Xubuntu 21.10

### What arch are you using?

x64

### Last Known Working Electron version

6.1.12

### Expected Behavior

No gray layer over whole application.

### Actual Behavior

This is so weird and I really don't know what's the problem.

![146986937-fcf77fca-69f2-47ba-930e-d07113d36575](https://user-images.githubusercontent.com/15836736/147244299-51434d1f-6c30-4775-814f-5a9904d3e77e.gif)

I am using the Atom editor for some time now but this never happened before. Any idea what I could try to figure out the problem? The app is always greyed out after startup. So there is not much to say how to reproduce the issue. Otherwise the editor works normal which means I can edit files, select menus etc. So there is only this grey layer over the whole application. I have this issue with Atom version 1.58.0 x64. I also have the same issue with Visual Studio Code. So it's not an issue specific to a certain application.

**Comment by dccoder84** [comment]
I have now tested older versions of Atom. Version 1.55 does work and seems to be the last working version because version 1.56 doesn't work anymore and has again the bug described above. Interestingly between these two versions the devs bumped up the electron version from 6.1.12 to 9.4.4. So Atom works fine with Electron 6.1.12 but not with Electron 9.4.4.

**Comment by dccoder84** [comment]
I now tried Visual Studio Code Insiders but it has the same issues and is using Electron 13.5.2.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by miniak** [comment]
Electron 13 is not supported anymore

**Comment by dccoder84** [comment]
With the new Xubuntu 22.04 this issue has been resolved.
