### ISSUE TITLE
[Bug]: Debian11 Linux  dialog【 Callback function feedback time delay is very high】

### ISSUE THREAD

**Issue by cosoc** [electron/electron#32284]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Debian11

### What arch are you using?

x64

### Expected Behavior

Quick opening of electron dialog

### Actual Behavior

Electronic dialog Caton

### Additional Information

``ts
 dialog.showSaveDialog({
        title: "请选择文件存储路径",
        buttonLabel: "保存",
        defaultPath: defaultName,
        properties:[
            'createDirectory',
            'treatPackageAsDirectory',
            'showOverwriteConfirmation',
            'dontAddToRecent'
        ],
        filters: [
            { name: 'Images', extensions: ['svg', 'png', 'jpg', 'jpeg'] },
        ]
      }).then(result => {          
        let {canceled,filePath} = result;
        【Callback function feedback time delay is very high】
       }).catch(err => {
        console.log(err)
      })
``

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. You did not really describe the issue or provide a clean and reproducible sample.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
