### ISSUE TITLE
[Feature Request]: Rounded Windows when transparent is set to True on Win11

### ISSUE THREAD

**Issue by SquitchYT** [electron/electron#32295]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When i set the Windows to frameless and the transparent to `true`, the edge of the window is not rounded on Windows 11

### Proposed Solution

Apply a rounded style to the window

### Alternatives Considered

Add an option to choose between rounded or sharp corner when transparency is set to `true`

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.

**Comment by lmsccc** [comment]
So, why isn't a transparent borderless window rounded in Windows 11? Is there any way to make the window follow the system style? @codebytere
