### ISSUE TITLE
Please Update discord invite url 

### ISSUE THREAD

**Issue by jensysantana** [electron/electron#32296]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I tried to join the but I have error: Invite Invalid.

### Proposed Solution

Update discord invite url 

### Alternatives Considered

Update discord invite url

**Comment by mwoodpatrick** [comment]
I am seeing the same issue :-(

**Comment by jensysantana** [comment]
I hope they fixed soon.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed in Electron's core codebase. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
