### ISSUE TITLE
Unable to isnatall

### ISSUE THREAD

**Issue by krasnit** [electron/electron#32309]
Get error tryng to install electron-fiddle Win64 package.

Never used electron, but want to try it out to see if I can get my js apps to run "natively" without a browser. But I cannot install the package currently on your web site: electron-fiddle-0.27.2-win32-x64-setup.exe
Trying to install, I get an error window: "The procedure entry point av-buffer-create could not be located in the dynamic link library", and installation stops. Any Ideas?

Running Win10 64 Enterprise, AMD Ryzen 7 3200, 32gb RAM.

**Comment by krasnit** [comment]
Never used electron, but want to try it out to see if I can get my js apps to run "natively" without a browser.  But I cannot install the package currently on your web site:  electron-fiddle-0.27.2-win32-x64-setup.exe
Trying to install, I get an error window: "The procedure entry point av-buffer-create could not be located in the dynamic link library", and installation stops.  Any Ideas?

Running Win10 64 Enterprise, AMD Ryzen 7 3200, 32gb RAM.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
