### ISSUE TITLE
[Bug]: How can Count the per Mouse Click and Keyboard Press in Electron and nextjs

### ISSUE THREAD

**Issue by dipaksavaliya04** [electron/electron#32333]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

How can Count the per Mouse Click and Keyboard Press in Electron?

### Proposed Solution

Now , I don't know?

### Alternatives Considered

I don't know How can Count the per Mouse Click and Keyboard Press in Electron?

### Additional Information

I created an Electron APP using react in windows with gkm packages and all functions are working, but I don't know How can Count the per Mouse Click and Keyboard Press in Electron?

Please let you know about this

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron, there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out. I hope the Discord is helpful to you!
