### ISSUE TITLE
[Bug]: Windows Control Overlay button hover effect not working

### ISSUE THREAD

**Issue by mlaurencin** [electron/electron#32360]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

See https://github.com/electron/electron/issues/30764 for specific behavior

### Actual Behavior

See https://github.com/electron/electron/issues/30764 for specific behavior

### Additional Information

I am creating this issue based on https://github.com/electron/electron/issues/30764 and the information I have gathered while trying to triage it. Though this not a breaking bug, it does create a visual inconsistency for users, as a window control button would typically change color when hovered over. For this reason, I think it should still be addressed at some point. Consolidating all current information and future questions/comments here should help in finding a solution.

[Here](https://bugs.chromium.org/p/chromium/issues/detail?id=1218921) is a link to the bug that led to the original fix implemented in Chromium

And [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1271293#c1) is the link to the follow-up bug report created noting issues with the implemented fix. This was then labeled as `WontFix` 

The chromium fix artificially creates the correct tooltips and allows for the button color to change on hover. However, this results in a response to the `WM_NCHITTEST` [message](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest) that does not correspond with the function of the button. For example, `HTMAXIMIZE` is not returned, thus Snap Layout on Windows 11 does not work.

If someone else wants to take a look at this, the relevant Electron files can be found in [this PR](https://github.com/electron/electron/pull/29600) adding WCO to Electron. For this bug in particular, I believe the related files are: `shell/browser/ui/views/win_caption_button.cc`, `shell/browser/ui/views/win_caption_button_container.cc`, and `shell/browser/ui/views/win_frame_view.cc` but changes to other files may provide a solution as well.

**Comment by AngeloCore** [comment]
any update here?

**Comment by JT-Potato** [comment]
any workarounds?

**Comment by shanselman** [comment]
👀

**Comment by clavin** [comment]
Just noting this observation here while I look into this: if you create a BrowserWindow but don't load anything (no `loadURL` or `loadFile`) then the window controls work perfectly fine (note: this is of a build without the [first fix in chromium that breaks Snap Assist](https://bugs.chromium.org/p/chromium/issues/detail?id=1218921)). So something about the actual web view is breaking the event flow described in the chromium bugs.

**Comment by clavin** [comment]
I've been diving deep into this one and I've managed to find out a lot. Take a look:

This bug seems to be triggered due to [`LegacyRenderWidgetHostHWND::OnMouseRange`](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/legacy_render_widget_host_win.cc;l=287-332;drc=4aaea83384df67f75d0a361cd9b47dff888ea8ad) calling the view event handler twice in a very roundabout way. The first is when it calls `HandleMouseMessage` which eventually ends up correctly being the mouse enter event. However, the second call is when it calls the Win API function `DefWindowProc`, essentially causing the OS to send a `WM_NCMOUSELEAVE` message which is what causes the mouse exit event.

I think the only fix here is to somehow mark the original call to `HandleMouseMessage` as handled, which prevents `LegacyRenderWidgetHostHWND::OnMouseRange` from passing the message on to `DefWindowProc`. I can verify that this is a valid solution by manually changing `Widget::OnMouseEvent` to set the event as handled for any non-client event, and it does solve this bug! However, I'm not really sure if this is the right solution or not and if this could affect anything else.

```patch
# void Widget::OnMouseEvent(ui::MouseEvent* event)
# ...
         last_mouse_event_was_move_ = true;
         if (root_view)
           root_view->OnMouseMoved(*event);
+        if ((event->flags() & ui::EF_IS_NON_CLIENT) == 0)
+          event->SetHandled();
       }
       return;
# ...
```

**Comment by panther7** [comment]
Hover is broken in 17.4.2 with transparent color (`titleBarOverlay: { color: 'rgba(0,0,0,0') }`)

![hover](https://user-images.githubusercontent.com/3808250/169792023-7f3d6b54-9126-4011-8a37-4f486fcb6b43.gif)
