### ISSUE TITLE
[Bug]: if tray setContextMenu null, click tray show window, input auto focus but cannot be input

### ISSUE THREAD

**Issue by CahierX** [electron/electron#32393]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

click tray input dom should work

### Actual Behavior

 const tray = new Tray(‘xxx.png’);
 tray.setContextMenu(null);
 tray.on('click', (e) => {
      this.showWindow(); 
 });
input :
 <input autofocus={true} />

now input is work, when click tray icon show windows, input dom cannnot be input 

https://user-images.githubusercontent.com/31394482/148746452-5137f422-c1c1-4fb4-8e65-c418d18b7002.mov

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by BlackHole1** [comment]
Based on his description, I helped create a test case: https://gist.github.com/BlackHole1/e509f3ae09a94fe87eae10c8578e392d

And I found that this problem exists from `electron@13.0.0` to `electron@main`

cc: @codebytere

**Comment by BlackHole1** [comment]
I have found that this is related to the input method software, which is normal when using the system's input method.

**Comment by CahierX** [comment]
> Based on his description, I helped create a test case: https://gist.github.com/BlackHole1/e509f3ae09a94fe87eae10c8578e392d
> 
> And I found that this problem exists from `electron@13.0.0` to `electron@main`
> 
> cc: @codebytere

Thank you, I was busy yesterday and didn't have time to do it

**Comment by CahierX** [comment]
> I have found that this is related to the input method software, which is normal when using the system's input method.
> 
>  1.mp4 
> When `type="text"` is changed to `type="password"`, it returns to normal.
> 
> This is a problem that may require the assistance of @zcbenz to troubleshoot.

The Sogou input method I use is used to input Chinese

**Comment by huzunjie** [comment]
I encountered a similar problem and my solution was to change
```js
  function showMainWindow() {
    if (win.isMinimized()) win.restore();
    win.show();
    win.focus();
  }```
To 
  ```js
  function showMainWindow() {
    if (win.isMinimized()) win.restore();
    win.hide();
    win.show();
    win.focus();
  }```

**Comment by CahierX** [comment]
> I encountered a similar problem and my solution was to change
> 
> ```js
>   function showMainWindow() {
>     if (win.isMinimized()) win.restore();
>     win.show();
>     win.focus();
>   }
> ```
> 
> To
> 
> ```js
>   function showMainWindow() {
>     if (win.isMinimized()) win.restore();
>     win.hide();
>     win.show();
>     win.focus();
>   }
> ```
> 
> [ElectronFiddleDemo.zip](https://github.com/electron/electron/files/8954496/ElectronFiddleDemo.zip)

This solution works for me
