### ISSUE TITLE
[Bug]: shell.openExternal(..., {activate:false}) opens in foreground

### ISSUE THREAD

**Issue by tedspare** [electron/electron#32471]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When specifying a second `options` argument to `shell.openExternal(url[, options])` as `{ activate: false }`, I expect URLs to open in the background.

### Actual Behavior

When opening URLs (tested only with protocols `https://`, `http://`), tabs open in the foreground with Chrome (97.0.4692.71) as the default browser.

When Safari is the default browser, URLs open in the background as expected. Not tested with Firefox.

### Testcase Gist URL

https://gist.github.com/5520aa7ef6beafe408cafc93c7890156

### Additional Information

This is similar to #12492 which was closed due to unsupported version.

**Comment by nornagon** [comment]
Hm, if this works when Safari is the default browser but not when Chrome is, then it might be an OS issue rather than an Electron issue.

When opening links in non-Electron apps, do you see the same behavior when Chrome is the default browser?

`shell.openExternal` is a fairly small wrapper around [`-[NSWorkspace openURLs:withAppBundleIdentifier:options:additionalEventParamDescriptor:launchIdentifiers:]`](https://developer.apple.com/documentation/appkit/nsworkspace/1535886-openurls), and passing `activate: false` corresponds to passing [`NSWorkspaceLaunchWithoutActivation`](https://developer.apple.com/documentation/appkit/nsworkspacelaunchoptions/nsworkspacelaunchwithoutactivation) in the options. It seems that method is now deprecated, but it _is_ supposed to be the OS's job to interpret that option correctly 😅

**Comment by VerteDinde** [comment]
Can repro on 16.0.7 with a pretty minimal example: https://gist.github.com/5520aa7ef6beafe408cafc93c7890156

Possible upstream issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=854609

**Comment by tedspare** [comment]
@nornagon thanks for explaining. It seems the macOS Notes app also opens links in the foreground, but in both Safari and Chrome. Same with About This Mac > Resources links. Not sure if they specify `NSWorkspaceLaunchWithoutActivation`.

I see how it might be a Chrome responsibility so I hope I haven't caused unnecessary trouble! Thanks.

> <a href='https://neat.run?ref=gh_footer'>Sent from Neat</a>
