### ISSUE TITLE
[Feature Request]: Hide a few windows while getting the entire screen stream using the desktopCapturer API

### ISSUE THREAD

**Issue by WonksknowAravind** [electron/electron#32473]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am trying to use the electron desktopCapturer API to get the stream for a screen. However, I want a few windows in the stream to be hidden even when the entire screen is being shared.  Is there a way to do this already?

### Proposed Solution

If there is way to overlay a browser window above the entire screen share stream or if there is a way to make a window the part of a logical display surface, it would help

### Alternatives Considered

I am not able to find an alternative. The windows that I want to hide from the screen share stream still get shared

**Comment by ckerr** [comment]
Hi @WonksknowAravind, thanks for reaching out!

I may be misreading this ticket but I think this is more about looking for help / advice on a goal, rather than a specific Electron bug. This issues tracker is used for tracking bug reports; fortunately though, there are other places where you'll probably have better luck with this question! Check out the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try. It's pretty active and has a lot of other Electron app developers who share questions and answers :+1:
