### ISSUE TITLE
[Bug]: clipboard.availableFormats can't list custom format after clipboard.writeBuffer.

### ISSUE THREAD

**Issue by sohobloo** [electron/electron#32490]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6.2, Windows 10 Version 20H2

### What arch are you using?

x64

### Expected Behavior

`clipboard.availableFormats` API always work as expected.

### Actual Behavior

`clipboard.availableFormats` returns correct format list if I copy something from external.
But after calling `clipboard.writeBuffer` with some custom type, `clipboard.availableFormats` returns empty list even other API works fine. e.g.: `clipboard.read`, `clipboard.has`.

![image](https://user-images.githubusercontent.com/13310861/149717101-1309235b-000c-4c79-9f52-f266da797a21.png)

### Testcase Gist URL

https://gist.github.com/4b14bdc891856921e0098244ada72814

**Comment by sohobloo** [comment]
It seems `availableFormats` working differently against `has` / `read` / `readBuffer`
Here's another incomprehensible example of clipboard API:
(I'm pretty sure each clipboard item copying from external has contents.)

![image](https://user-images.githubusercontent.com/13310861/149871368-0a0b999c-7b4a-4095-a0d4-f4ebd07cce9e.png)

**Comment by nornagon** [comment]
This is expected behavior; `availableFormats` returns the subset of the standard formats which can be read from the current clipboard. See implementation in Chromium here: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/clipboard/clipboard_mac.mm;l=176-200;drc=de533fceff84e830847b2a2bd66d017c06372d98

Closing because this is working as intended. `clipboard.has` is what you should use for testing for availability of a specific type.

**Comment by sohobloo** [comment]
@nornagon  `clipboard.has` and `clipboard.read`also confused me. I just copy somthing from vscode and run the demo below. `clipboard.has` returns false for whatever format, and `clipboard.read` returns nothing too. You say `availableFormats` returns the subset of the standard formats which can be read from the current clipboard, in fact `vscode-editor-data` is not a standard format, and all the format listed even it's standard can not read.

![image](https://user-images.githubusercontent.com/13310861/150257254-3266a5f2-ba2e-4d49-b262-6a8fe0eb29ef.png)

**Comment by nornagon** [comment]
ah, looks like `availableFormats` has some logic for detecting custom data from web stuff: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/clipboard/clipboard_mac.mm;l=215-219;drc=de533fceff84e830847b2a2bd66d017c06372d98. Specifically, it looks for [`org.chromium.web-custom-data`](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/clipboard/clipboard_constants_mac.mm;l=13;drc=62baf0808ab1d15aea5c775ba73a032807104762).

As for why `has` and `read` don't work with `text/plain`... hm, it looks like under the hood there's a mapping from the underlying format names to mime types: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/clipboard/clipboard_mac.mm;l=181-198;drc=de533fceff84e830847b2a2bd66d017c06372d98

i.e. the actual name of the format on macos is `public.utf8-plain-text`. The API that `clipboard.availableFormats()` calls converts that to `text/plain` before returning it, but we don't do the reverse mapping for `has` or `read`. I think this is intentional? But not totally sure.

More weirdly, though, `has('vscode-editor-data')` _also_ returns false. It seems like that should be true? Kind of confused on what the point of `availableFormats()` is supposed to be.

I'm reopening this because something fishy might be going on. cc @jkleinsc who's recently touched the clipboard API.
