### ISSUE TITLE
[Bug]: Window postMessage problem

### ISSUE THREAD

**Issue by neyvan** [electron/electron#32507]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows version 21H2

### What arch are you using?

x64

### Expected Behavior

`window.postMessage` and `window.addEventListener` functions work on Electron as on web.

### Actual Behavior

Nothing happens. It is impossible to send any message from one window to another.

### Additional Information

Could you help, please? What is the reason of the problem? Could I wrap PostMessage communication with IPC renderer and main (without changing the source of web application)?

This [guide](https://medium.com/@henrikbjorn/electron-communicating-via-postmessage-f9a419f94bf7) doesn't help.

**Comment by Prinzhorn** [comment]
I'm using `postMessage` extensively in my app and it works as expected. Can you provide a [Fiddle](https://www.electronjs.org/fiddle) that reproduces your problem?

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by neyvan** [comment]
@Prinzhorn, you are right. The problem wasn't in PostMessage. The problem was in our code.

We used `window.webContents.on('new-window', ...)`. Here we called `event.preventDefault()` and created a window via `BrowserWindow`. So this new window didn't have `window.opener` property and that's why PostMessage didn't work on electron for windows. We changed on:
```
  window.webContents.setWindowOpenHandler(() => {
    return {
      action: 'allow',
      overrideBrowserWindowOptions: {
        width: defaultWidth,
        height: defaultHeight,
        autoHideMenuBar: true,
      }
    };
  })
```

Thank you for changing direction of finding a problem. I am going to close this issue.
