### ISSUE TITLE
GtkDialog mapped without a transient parent. This is discourage

### ISSUE THREAD

**Issue by rfedericoni** [electron/electron#32541]
Ubuntu 18.04.6 and 20.04.3
Electron 12.0.0 and 13.6.7 and 16.0.7

When an html file input element is clicked in order to pick file the application crash with this error message:
**GtkDialog mapped without a transient parent. This is discourage** 

How to solve this issue?

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rfedericoni** [comment]
Sure sorry you are right.. so I create a very sample project starting from electron-quick-start boilerplate.. here the link https://drive.google.com/file/d/1tDvRkjlnPgS7FhARljdT73VRSuyHkq3y/view?usp=sharing

The issue happen when the button "Chosse File" that open a file dialog  ( in this sample I used a simple <input type="file"> element ) and in the main process I import a signsdk that is working correctly (press "test sdk is working")
This issue happen only in Ubuntu, in Windows and MacOS tha same app works.
Thanks

**Comment by rfedericoni** [comment]
I will open an other specific issue for this
