### ISSUE TITLE
[Bug]: App crash when an open file dialog is called

### ISSUE THREAD

**Issue by rfedericoni** [electron/electron#32552]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04.6; Ubuntu 20.04.3

### What arch are you using?

x64

### Expected Behavior

The file dialog is shown

### Actual Behavior

The app crash

### Testcase Gist URL

https://drive.google.com/file/d/1tDvRkjlnPgS7FhARljdT73VRSuyHkq3y/view?usp=sharing

### Additional Information

I create a very sample project starting from electron-quick-start boilerplate.. here the link 
https://drive.google.com/file/d/1tDvRkjlnPgS7FhARljdT73VRSuyHkq3y/view?usp=sharing

The crash happens when the button "Choose File", that open a file dialog, is pressed ( in this sample I used a simple input file element ) and in the main process the signsdk is imported ad used correctly (press "sdk is working")
This issue happens only in Ubuntu, in Windows and MacOS the same app works.

**Comment by ckerr** [comment]
Hey @rfedericoni, I'm a little confused by the sample project you committed? It doesn't seem to have any  'choose file' button or any call to Electron's Dialog API. It also appears to rely on an external dependency `@namirial/sign-sdk` that I don't have any information on. Lastly, instead of uploading it as a gist, you made it a zipfile on Google Drive, which makes it harder for Electron maintainers to download and test.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue, e.g. without any external dependencies? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

**Comment by rfedericoni** [comment]
In the html there is an input file with is default button that should open a file dialog, and a button that call an sdk method... the problem is that once the sdk is loaded and working the Electron is not more able to show any dialog.

**Comment by rfedericoni** [comment]
I published the fiddel here https://gist.github.com/a2e54d4bcc4add40c9d34092187ec158 ... 
In the Fiddle published the [node-sign](https://drive.google.com/file/d/17Hq5MmEkhfbpz5oxmI1ACSz4T-5JIhbd/view?usp=sharing) is only imported and not used nevertheless Electron crash in dialog opening.
I continue to insist on the external library sign-sdk because it works and is not related to the opening file dialog, despite this Electron + node-sign crash only on Ubuntu where some one ask to open a dialog .. during startup electron shows the following message:
(electron --enable-crashpad.: 2867): Gtk-WARNING **: 17: 58: 05.019: **gtk_disable_setlocale () must be called before gtk_init ()**

How can a library that is correct and working cause Electron to crash when it tries to open a dialog (I remember that this happens only in Ubuntu, in Windows and MacOS all works as expected)?

I can continue to investigate myself but I need help.
