### ISSUE TITLE
Error while webContents reload() of BrowserView

### ISSUE THREAD

**Issue by tushar-ghadge** [electron/electron#32553]
Electron version : 12.2
I have a BrowserView object which is trying to reload the current webpage.
It works with normal webpages, however with an attempt to refresh a page that is the result of a POST request it reload doesn't work. (You can think of  like you are at abc.com/login and you put credentials and now you are at abc.com/dashbaord and try to reload abc.com/dashboard, it won't work. Same process flow followed in chrome or other browser and try to reload it will display confirmation box `The page that you're looking for used information that you entered. Returning to that page might cause any action you took to be repeated. Do you want to continue?`)

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
