### ISSUE TITLE
[Feature Request]: `contextBridge.exposeInIsolatedWorld`

### ISSUE THREAD

**Issue by IdkGoodName** [electron/electron#32588]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am working on application's plugin/add-on system and I want to disallow from plugins/add-ons doing anything without user giving permissions to them. This can work great with isolated worlds, but isolated worlds still lack things. Node's `vm` feels more powerful than Electron's isolated worlds, but Node's `vm` doesn't work great with Electron.

You can't really set isolated world's window variables either without using hacks like executing JS in isolated world to set its window variables, which will make you struggle implementing functions properly.

### Proposed Solution

The introduction of `contextBridge.exposeInIsolatedWorld(worldId, apiKey, api)`. This would allow you to set isolated world's window properties and would be similar to `contextBridge.exposeInMainWorld(apiKey, api)`.

Example:
```js
webFrame.setIsolatedWorldInfo(1005, {
    name: "Isolated World 5"
});
contextBridge.exposeInIsolatedWorld(1005, "api", {
    doStuff() { console.log("Isolated World 5 is doing stuff"); }
});
await webFrame.executeJavaScriptInIsolatedWorld(1005, [
    {
        "code": "window.api.doStuff()"
    }
]);
```
Console Output:
```
-> Isolated World 5 is doing stuff
```

### Alternatives Considered

`webFrame.setIsolatedWorldInfo` could allow setting window variables for that isolated world.

**Comment by miniak** [comment]
why do you need this?

**Comment by kris7t** [comment]
One use-case is to load, e.g., independent plugins into different worlds without them interfering by accidentally clobbering something in the `window` object. Essentially, to let us use `setIsolatedWorldInfo` to the fullest and do useful work in various isolated world. Note that this isn't really a security measure by any stretch of imagination (plugins would still have access to the DOM and can use it for nefarious purposes, although maybe setting a CSP for the isolated world would reduce the attack surface somewhat)).

To some extent, this is already possible by having the code in the isolated world return a function instead of running whatever code you want to have there directly. Rougly,

```javascript
webFrame.setIsolatedWorldInfo(1005, {
    name: "Isolated World 5"
});
const callback = await webFrame.executeJavaScriptInIsolatedWorld(1005, [
    {
        "code": "(api) => api.doStuff()"
    }
]); 
callback({
    doStuff() { console.log("Isolated World 5 is doing stuff"); }
});
```

This works because the same `contextBridge` API is used to serialize the result of `executeJavaScriptInIsolatedWorld` as `exposeInIsolatedWorld`, so all the communication between worlds works the same.

In practice, you might want to make the function returned by the code in the isolated world `async`, so the plugin code can use `await` during initialization (as if it was an ES module loaded by a HTML page). However, building plugins might be a bit tricky with a bundler (this is not a usual output format for a bundle at all). Alternatively, a two-step process might work, where you first set a property on the `window` objects from a function returned by `executeJavaScriptInIsolatedWorld`, then run your plugin code proper with a second `executeJavaScriptInIsolatedWorld` call.

Nevertheless, having a proper `contextBridge` API would be much nicer.

**Comment by akshaydeo** [comment]
@miniak is the core team planning to add this feature? If not, can I pick this up as a first issue?
Or are there any concerns about enabling this feature?
