### ISSUE TITLE
[Bug] [Mac OS]: "open-url" event is triggered before "ready" or "will-finish-launching"

### ISSUE THREAD

**Issue by maksim-pushkin-team-wrike** [electron/electron#32600]
Confusing event order is happening in case when trying to launch app from scratch via deep url.
"open-url" event is triggered before "ready" or "will-finish-launching", so I have to manually collect all the urls coming from "open-url" until the app will be ready.

This behaviour remains at least from Electron version 8.0.0 and is still present in the version 16.

Is this by-design or is it a bug?

Please, let me know if more details are needed.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
