### ISSUE TITLE
[Bug][macOS]: browser window dragging capability deactivated on browser view over drag region 

### ISSUE THREAD

**Issue by b3ll00z** [electron/electron#32642]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.1

### What arch are you using?

x64

### Last Known Working Electron version

15.0.0

### Expected Behavior

Given a frameless browser window with provided html drag region, the browser window itself should be draggable despite any browser view attached

### Actual Behavior

Given a frameless browser window with provided html drag region, the dragging capability for the browser window is deactivated by a browser view attached exactly over the drag region 

(probably you'll see in the poc that sometimes it's draggable after you resized and dragged the "always"-draggable window).

### Testcase Gist URL

https://github.com/b3ll00z/poc-undraggable-frameless

### To reproduce

```
$ git clone https://github.com/b3ll00z/poc-undraggable-frameless
$ cd poc-undraggable-frameless
$ npm install ; npm start
```

https://user-images.githubusercontent.com/16275841/151346663-0e976fd7-08b0-4ead-b9de-7fd058dd3570.mov

**Comment by codebytere** [comment]
This is, unfortunately, behavior by design. I corrected this in https://github.com/electron/electron/pull/31085. On macOS, draggable regions are implemented making the whole web view draggable  and overlaying regions that are not draggable. BrowserViews and BrowserWindows hve independent web views, and so independent exclusion zones. Thus, if a BrowserView with different draggable regions than the BrowserWindow it belongs to is superimposed on top of that window, the draggable regions of the BrowserView take precedence over those of the BrowserWindow.
