### ISSUE TITLE
Difference between chromedriver here vs those available on chromium.org

### ISSUE THREAD

**Issue by shitchell** [electron/electron#32660]
Hi! I apologize if this isn't the correct place to ask this, but I'm not sure where else to go.

Is there any difference between the chromedrivers released here on the releases page and the chromedriver versions available on https://chromedriver.chromium.org/downloads?

I'm testing an electron app and was told that I would absolutely need to use one of the chromedriver versions released from this repository, because the chromedrivers available on chromium.org interfere with some sort of communication APIs in electron...? I'm documenting the process I went through in this project for colleagues to duplicate, and before I tell them that they absolutely need to find/use a chromedriver releaseon this page, I want to make sure that's accurate.

Thank you so much for any feedback!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
