### ISSUE TITLE
Import Certificate doesn't set SSL Trust bit in nssdb (app.importCertificate)

### ISSUE THREAD

**Issue by tn185075** [electron/electron#32816]
**Detailed Info:**

> OS: Ubuntu
> CA-certificate: self-signed
> format: p12
> certificate import result code: 0

**code:**
``` typescript
app.on('ready', () => {
  app.importCertificate(
    {
      certificate: "cert.p12",
      password: "password",
    },
    res => {
      console.log(`import certificate result code: ${res}`);
    },
  );
createWindow();
});
```
trust attributes for SSL are not being set in nssdb when checked using,
```bash
certutil -d sql:$HOME/.pki/nssdb -L
```
output:
``` text
cert-name ,,,
```
expected output:
```  text
cert-name CT,,
```
or 
``` text
cert-name C,,
```
When loading browser window, results in `ERR_CERT_AUTHORITY_INVALID`.

**Comment by mlaurencin** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by tn185075** [comment]
Closing this, as I have raised a different issue with bug template.
