### ISSUE TITLE
[Doc] Need example for label printing with silent option enabled

### ISSUE THREAD

**Issue by bierdok** [electron/electron#32874]
Hello,

The documentation is based on a label printer from the Brother brand, we also have this type of printer from the same brand  QL-700.

https://www.electronjs.org/docs/latest/api/web-contents#contentsprintoptions-callback

But silent printing does not start and the printer light indicates an error.

Could you show the parameters used for silent printing with this type of printer?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
