### ISSUE TITLE
[Bug]: ACTION //v8:run_mksnapshot_def...t(//build/toolchain/linux:clang_arm64)

### ISSUE THREAD

**Issue by SUST-MaZhen** [electron/electron#32928]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

i want no error

### Actual Behavior

[1/330] ACTION //v8:run_mksnapshot_def...t(//build/toolchain/linux:clang_arm64)
FAILED: gen/v8/embedded.S snapshot_blob.bin 
python ../../v8/tools/run.py ./clang_x64_v8_arm64/mksnapshot --turbo_instruction_scheduling --target_os=linux --target_arch=arm64 --embedded_src gen/v8/embedded.S --embedded_variant Default --random-seed 314159265 --startup_blob snapshot_blob.bin --native-code-counters
#
#Fatal error in , line 0
#ignored
#
#
#
#FailureMessage Object: 0x7ffc68f36780
==== C stack trace ===============================

    ./clang_x64_v8_arm64/mksnapshot(+0x13d8373) [0x559ec654c373]
Return code is -6

**Comment by SUST-MaZhen** [comment]
can anyone help me.thanks

**Comment by SUST-MaZhen** [comment]
I am doing cross compile in ubuntu20.04 for arm64 ,because the official electron was build in pagesize 4096, I need rebuilt it in 65535

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by chenamy2017** [comment]
I have the same problem, does anyone know how to solve it?
