### ISSUE TITLE
[Docs]: Difference between Electron Fiddle and "Runtime Mode".

### ISSUE THREAD

**Issue by 7ombie** [electron/electron#32938]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Many people have asked for a way to ship apps without bundling Electron, reusing the local Electron installation in *runtime mode*. This has been a popular request, but has never been implemented, seemingly because it would be too complicated in practice. On the other hand, we have Electron Fiddle, which seems to do exactly what's been asked for??

The docs for Electron Fiddle (I could only find its README) are not very detailed, so it's not clear what the limitations would be. I appreciate that Fiddle is not an IDE, but we would obviously be looking to develop the app outside of Fiddle, with regular tools, and only use Fiddle to run and package apps.

What am I missing?

### Proposed Solution

Expand the docs to make it clear what Fiddle can and cannot do.

### Alternatives Considered

Exploring Fiddle till I just kinda figure stuff out for myself??

### Additional Information

I'd be happy with a way of sharing apps with other web devs that use the Electron platform. It doesn't have to permit shipping software to endusers. I just don't know what the limitations of a Fiddle would be, compared to a full Electron app.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. At minimum, this issue is better opened on the Fiddle repo.

**Comment by 7ombie** [comment]
@codebytere - Technically, the issue contains a request to improve the docs, so that should be considered, though I accept that this is basically a user question. I'm not trying to pretend otherwise, but the question rises from a lack of documentation.
