### ISSUE TITLE
[Bug]: electron16 --no-sandbox as root doesn't work

### ISSUE THREAD

**Issue by toghrulgasimov** [electron/electron#33028]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16

### What operating system are you using?

Ubuntu

### Operating System Version

Linux tg 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

electron --no-sandbox app.js opens windows with correct index.html content

### Actual Behavior

electron --no-sandbox app.js opens windows but it is white and empty.

### Additional Information

With root user, electron --no-sandbox app.js opens windows but it is white and empty.

Gif file available from https://drive.google.com/file/d/1fMqXxmxX5eiy9_Z_zScE1RSqmNaQWYB0/view?usp=sharing

**Comment by ckerr** [comment]
Hey @toghrulgasimov, 

Yes this probably should work, but it's unlikely that this ticket will get prioritized because running Electron (or any Chromium-based app, really) as root is not a supported configuration. The most likely scenario for a fix would be if a contributor wants to track this issue down and submit a patch. In the meantime, I'd strongly recommend that you find a different workflow that doesn't require root.
