### ISSUE TITLE
baseUrl is not work ? 

### ISSUE THREAD

**Issue by TBSten** [electron/electron#33048]
I am developing an electron app that uses react and typescript.

I cloned the following template from github

https://github.com/diego3g/electron-typescript-react

I copied the following contents to `src/test/funcs.ts`.

```tsx
export function test () {
     console.log ("test ok")
}

```

I want to import this in `src / app.ts` with an absolute path like this:

```tsx

import {test} from "src / funcs";

```

I added the following to tsconfig.json, but I couldn't import the module successfully.

```json
{
   "compilerOptions": {
     "baseUrl": "."
   }
}

```

How can I import with an absolute path?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by TBSten** [comment]
i misstook! sorry...
