### ISSUE TITLE
[MAS Rejection]: Rejected because app built with a Beta version

### ISSUE THREAD

**Issue by lukas2** [electron/electron#33054]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

13.3.0

### Rejection Email

This build is using a beta version of Xcode and can't be submitted. Make sure you're using the
latest version of Xcode or the latest seed release found on the releases tab in a
href="https://developer.apple.com/news/releases/" target=" blank">News and Updates

### Additional Information

This was not an email, but an error message when submitting the build to a Testflight Beta.

<img width="659" alt="Screenshot 2022-02-23 at 13 14 44" src="https://user-images.githubusercontent.com/213249/155317505-a33e539b-a798-4314-898f-aa65e97ac9de.png">

My suspicion is, this is rejected because the Info.plists all list 12.4 as the Xcode build version, however, according to [Testflight guidelines](https://help.apple.com/app-store-connect/#/devdc42b26b8), it has to be 13.

<img width="731" alt="Screenshot 2022-02-23 at 13 14 19" src="https://user-images.githubusercontent.com/213249/155317446-e826caa5-dd96-4d14-829f-1903703712e9.png">

I wanted to rebuild Electron with a different value there, but I cannot find the right configuration setting. Any help is appreciated!

**Comment by lukas2** [comment]
Please reopen, you are right, the version was outdated. However, the same exact problem happens when we use electron 17.1.0.

**Comment by devinbinnie** [comment]
This is happening to me as well, please re-open this. Using Electron v17.1.0 as well.

**Comment by lukas2** [comment]
@nornagon please reopen 

@devinbinnie please post if you have a solution. I have not been able to find the problem yet, Xcode 12.4 is not beta, so it should work.

**Comment by lishid** [comment]
Running into this as well with 17.3.1.

This is likely due to the fact that official Electron releases are currently still built with Xcode 12.2: 

https://github.com/electron/electron/blob/9207c2aa685a8eec69a83673ed0d2dee2b095281/docs/development/build-instructions-macos.md?plain=1#L47

https://github.com/electron/electron/blob/b711860d21da111270c3c59945a037d6d04eec83/.circleci/build_config.yml#L60

Not sure what's the usual process for upping the Xcode version...

**Comment by lukas2** [comment]
I actually built electron myself with a new Xcode 13.2.1, replaced the binaries in our app, resigned, and still ran into the problem with Apple.. Now writing back and forth with them about it, but no solution yet.

**Comment by lishid** [comment]
Maybe Apple is requiring Xcode 13.3? When I deployed iOS apps I had to update Xcode to 13.3 for TestFlight to work.

**Comment by lukas2** [comment]
Darn, [13.3 requires Monterey](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-13_3-release-notes). Thanks, Apple..

**Comment by Thomas-Vos** [comment]
I am running into the same issue when publishing to external testers with a JVM (Java) app. (So not Electron)

<img width="662" alt="Screenshot 2022-04-07 at 01 21 00" src="https://user-images.githubusercontent.com/11077217/162089468-7d8dbdc5-8c5b-4d3e-a7b2-53770d1bdc41.png">

**Comment by idoodler** [comment]
> I am running into the same issue when publishing to external testers with a JVM (Java) app. (So not Electron)
> 
> <img alt="Screenshot 2022-04-07 at 01 21 00" width="662" src="https://user-images.githubusercontent.com/11077217/162089468-7d8dbdc5-8c5b-4d3e-a7b2-53770d1bdc41.png">

Check your `Info.plist` for the value `DTXcode`. It will tell you what version of xCode was used to create your app.

**Comment by idoodler** [comment]
> I actually built electron myself with a new Xcode 13.2.1, replaced the binaries in our app, resigned, and still ran into the problem with Apple.. Now writing back and forth with them about it, but no solution yet.

I am also writing with them. So far they just came to the conclusion not to give support our Buildserver and Electron which is absolutely understandable. Tho I don't understand why they "blacklisted" Xcode 12.4 for external TestFlight testing but allow it for internal and AppStore releases.

**Comment by lukas2** [comment]
@idoodler yeah it's 12.4 and it's not beta, so the error message is probably wrong. It should read "This build is using an Xcode version less than 13.3 and can't be submitted."

**Comment by idoodler** [comment]
Apple just recommend to use the latest xCode Version :/

**Comment by idoodler** [comment]
Apparently Xcode 13 has already been added, but is not used: https://github.com/electron/build-tools/blob/main/src/utils/xcode.js

**Comment by lukas2** [comment]
We rebuilt electron ourselves with the currently latest version of Xcode, 13.3.1 (13E500a) and we still got the same rejection.

**Comment by idoodler** [comment]
@lukas2 what does your Info.plist say regarding the Xcode version?

**Comment by hisnameisjimmy** [comment]
Also running into this. I am bummed! I really want to get this in testing!

**Comment by hamilr2** [comment]
@lukas2 I encountered the same issue today, and eventually determined that the issue is the MacOS SDK version, defined by the `DTSDKBuild` field, not the DTXcode(Build) fields.

When building my app with electron-forge / electron-packager and Electron 19.0.1, my `DTSDKBuild` is automatically set to `12.3`. I created a default Hello World app in Xcode, and after building it observed that the `DTSDKBuild` field is set to an alphanumeric build number, `21E226`.

Sure enough, overriding the value in the base Info.plist file allows the app to be submitted for External Testing.

In my case, with `electron-forge`, the solution was to add an override to the plist file in the forge config:

```
  packageConfig: {
    ...
    extendInfo: {
      ...
      DTSDKBuild: '21E226',
    },
  },
```

I imagine you could also override the value directly in the plist before packaging. Only the top-level Info.plist needed to be updated for my app to enter the review process -- the other .plist files in the frameworks/libraries/helpers are seemingly not validated.

I tried to figure out where the `DTSDKBuild` field is being set, but hit some dead-ends and I ultimately decided that the override solution is fine until this can get fixed upstream by whatever package is causing it -- as I'm not sure if this is an `electron` issue or an `electron-packager` issue.

As a aside, the potential issue about why AppStore Connect thinks this is a beta build is seen here:
https://xcodereleases.com/
There are both beta and non-beta builds with the build number `12.3`, and perhaps the non-specific resolution of that build number maps it to the beta build 🤷 .

**Comment by idoodler** [comment]
Any news?

**Comment by MarshallOfSound** [comment]
This will be fixed by https://chromium-review.googlesource.com/c/chromium/src/+/3934881/ and can be worked around per @hamilr2 above.

**Comment by lukas2** [comment]
Thank you very much everyone for the workaround and for the link to the Chromium issue. Much appreciated. 👍 Closing this issue now.
