### ISSUE TITLE
Serial Web Api - Select port more then once

### ISSUE THREAD

**Issue by aviTwito** [electron/electron#33068]
I have implemented a helper function for selecting serial port
When calling it for the 1st time it works fine, But trying to call it again throws the following exception:
![Capture](https://user-images.githubusercontent.com/19937147/155501556-eeebfd4e-c8e7-45c7-8cd4-7bdd45ce3390.PNG)
I used global dictionary for preventing this from happening if the user chooses the same port for the second time, But I can not prevent it if he wants to choose another port for the second time

My helper method looks like this
```
const ports: { [id: string]: boolean } = {};


const selectSerialPort = async (
  serialPort: Electron.SerialPort
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
): Promise<void> => {
  return new Promise((resolve) => {
    logger.info(
      `Requested to select ${serialPort.portName}-${serialPort.portId}`
    );
    if (ports[serialPort.portId]) {
      logger.info(
        `${serialPort.displayName} - ${serialPort.portId} Already Selected`
      );
      return resolve();
    }
    const listener = (
      event: any,
      portList: any,
      webContents: any,
      callback: any
    ) => {
      try {
        event.preventDefault();
        const selectedPort = portList.find((device: any) => {
          return device.portId === serialPort.portId;
        });
        if (!selectedPort) {
          callback("");
        } else {
          delete ports[serialPort.portId];
          callback(selectedPort.portId); //This is what throws the error
          ports[serialPort.portId] = true;
          logger.info(`SerialPort [${selectedPort.portId}] Selected`);
        }
        resolve();
      } finally {
        // win.webContents.session.off("select-serial-port", listener);
      }
    };
    win.webContents.session.on("select-serial-port", listener);
    win.webContents.executeJavaScript(
      `navigator.serial.requestPort().then(port => port).catch(err => console.error(err));`,
      true
    );
  });
};
```

This is how I call the method from my renderer
```
const getPort = async (serialPort: Electron.SerialPort): Promise<any> => {
  const filters = [
    {
      usbVendorId: serialPort.vendorId,
      usbProductId: serialPort.productId,
    },
  ];

  await window.ipcRenderer.invoke("selectSerialPort", serialPort);
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore: next-line
  const port = await navigator.serial.requestPort({ filters });
  try {
    await port.close();
    // eslint-disable-next-line no-empty
  } catch {}
  const options: SerialOptions = {
   ...
  };

  await port.open(options);
  return port;
};
```

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by aviTwito** [comment]
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

Not sure if I should open a bug regarding this

**Comment by aviTwito** [comment]
[https://github.com/electron/electron/issues/33095](url)
