### ISSUE TITLE
[Bug]: `WebAssembly.instantiateStreaming` fails when `sandbox: true` and `contextIsolation: true`. Works when I disable them.

### ISSUE THREAD

**Issue by akshaydeo** [electron/electron#33098]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

macOS

### Operating System Version

12.2.1 (21D62)

### What arch are you using?

x64

### Expected Behavior

- Based on #25127, this should work even if `contextIsolation` is enabled.
- When I checked [spec](https://sourcegraph.com/github.com/electron/electron/-/blob/spec-main/chromium-spec.ts?L352) for the same feature,  I tried the same flow with ` enableBlinkFeatures: 'WebAssemblyCSP'`, but it still fails

### Actual Behavior

- Throws error when I try to generate wasm code.
<img width="859" alt="Screenshot 2022-02-27 at 5 47 46 PM" src="https://user-images.githubusercontent.com/1050029/155919762-9bb33ea4-bac4-452a-9882-4b3a4fffa9c4.png">

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by akshaydeo** [comment]
I'm using the undocumented `webContents.create(webPreferences)` API for this. Would this be causing any issues?

**Comment by codebytere** [comment]
@akshaydeo then the repro needs to reflect that - please update it for us to continue triaging.

**Comment by akshaydeo** [comment]
Could not reproduce this. Closing for now 🙇
