### ISSUE TITLE
[Bug]: Transparent Window contents do not render after updating Electron.

### ISSUE THREAD

**Issue by MineAndCraft12** [electron/electron#33113]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2 build 19042.1526

### What arch are you using?

x64

### Last Known Working Electron version

9.4.0

### Expected Behavior

- Window opens with a transparent background.
- Window content renders as normal on top of the transparent background.
- Window content can be clicked on as normal.
- Clicks on the background are passed through to applications behind the window.

### Actual Behavior

- The entire window has a white background, and none of the page's content renders.
- Chrome DevTools still work, and the DOM is still present in the Elements panel.
- However, none of the page's HTML is rendered, and none of the document layout is rendered either.
- "Clickboxes" of page content are not present and any clicks are passed through to applications behind the window.

### Additional Information

This was previously working as expected in Electron 9.4.0, on the same project just before updating Electron.
Window has the Transparent option enabled, and the Electron app has GPU Hardware Acceleration disabled.

Video example with multiple tests:
    https://youtu.be/pRDymWJ41UU
    Video description details what happened on each of the five tests, in case it's unclear in the video.

Working version of the project at tag v1.11 on Electron 9.4.0:
    https://github.com/MineAndCraft12/AaronOS_Music/releases/tag/v1.11
    Use `npm start` and select Transparent Window; the application will relaunch in transparent mode.

Current bugged version of the project at master on Electron 11.5.0:
    https://github.com/MineAndCraft12/AaronOS_Music
    Use `npm run start-transparent` to launch the application in transparent mode.

**Comment by ckerr** [comment]
Hi @MineAndCraft12, thanks for reporting this.

The Electron 11 line is fairly old and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/support). Could you try this out with the latest stable release, [17.1.0](https://www.electronjs.org/releases/stable)? 

Also, because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. If the problem is still there in Electron 17, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

**Comment by MineAndCraft12** [comment]
I don't know how in the world I missed that. Somehow I updated my installation and ended up with 11!

I'll be trying this out when I get a chance, thank you very much.

**Comment by MineAndCraft12** [comment]
I'm following up; I've updated to Electron 17, and it's working great. Looks like the old Hardware Acceleration bug was fixed too, so that'll certainly boost performance. Thank you!
