### ISSUE TITLE
[Feature Request]: Is it possible to run the main process as root permissions and keep the renderer process with user permissions?

### ISSUE THREAD

**Issue by tal-rofe** [electron/electron#33112]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I try to run Electron, however I'd like to get to a state where I run the main process with root permissions, and the renderer process with user permissions.

Is it possible?

### Proposed Solution

Let the developer configure some options to allow the main process to run in root permissions

### Alternatives Considered

NONE

**Comment by ckerr** [comment]
Hi @tal-rofe, thanks for reporting this.

Running apps like Chromium or Electron as root is inherently risky. Speaking just for myself, I'd be surprised if that were ever to be a supported configuration in Electron. See also related upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=638180 .

On the other hand, if you're just wanting to discuss with other developers how it might be _possible_ rather than an issue that maintainers should track, fix, and support, you may want to try of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

I'm closing this issue since it's not something that the maintainers are going to prioritize, but I hope you find a solution that works for you at the Electron Discord!
