### ISSUE TITLE
[Bug]: skipTaskbar: true ignored

### ISSUE THREAD

**Issue by Mininock-afk** [electron/electron#33124]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0-1-x86_64

### What operating system are you using?

Other Linux

### Operating System Version

Kernel: 5.16.11-arch1-1

### What arch are you using?

x86_64

### Last Known Working Electron version

16.0.8-2-x86_64

### Expected Behavior

electron app not shown in the taskbar

### Actual Behavior

electron app is shown in the taskbar

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

**Comment by Mininock-afk** [comment]
I didn't know what to test. With Vers. 16.0.8-2 "skipTaskbar" works, after upgrade to Vers. 
17.1.0-1 "skipTaskbar" will be ignored, the app is shown in the taskbar like any other app as 
vivaldi, thunar etc. So I downgrade and all works fine again. In the attachment the important 
files for you from my app. I hope it helps.

Walter

**Comment by Medialabster** [comment]
Thanks. I'm always appreciative, as the owner of this, of anyone honestly
trying to improve.
H

**Comment by ckerr** [comment]
This is likely a side-effect of X11 -> Wayland migration.

### GNOME

According to [wayland-bites](https://wayland-bites.github.io/) the equivalent to `_NET_WM_STATE_SKIP_TASKBAR` on GNOME is with `Window.is_skip_taskbar`, but that "Since GNOME 41, WaylandClient, Workspace, WorkspaceManager, IdleMonitor and Window Meta APIs are available only to GNOME Extensions or in the unsafe mode."

The same page says that "WaylandClient.{hide_from|show_in}_window_list" might also be an approach, but that "WaylandClient controls only subprocess surfaces".

### KWin

On the KWin side, the `KWin::Toplevel::skipTaskbar` is the API to use but "[the] KWin Scripting API is available only to dedicated registered scripts."


... in short, there doesn't seem to be an easy way to do this anymore in a Wayland world, and the tradeoffs involved (e.g. running in unsafe mode) are IMO not worth the cost.

I'd be happy to be proven wrong if someone knows of a better workaround, but if the above is correct IMO we should update the documentation to say that `skipTaskbar` is not supported on Wayland

**Comment by rokejulianlockhart** [comment]
Has anyone requested at the Wayland issue tracker that an API be provided? It seems like that should have been the first port of call.
