### ISSUE TITLE
[Bug]: Electron App doesn not open at VM (Virtualbox with W10)

### ISSUE THREAD

**Issue by tripower** [electron/electron#33153]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 at Virtualbox

### What arch are you using?

x64

### Last Known Working Electron version

9.3.33

### Expected Behavior

App should open
Window shown

### Actual Behavior

our app doesn't start / show the browserwindow after update from Electron v9 to v15 in a Virtualbox VM with Windows 10 it works at pure Windows 10 without VM

also the native app from Electron has the same problem https://github.com/electron/electron/releases/download/v15.4.0/electron-v15.4.0-win32-x64.zip

VM for Test https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ select MSEdge on W10 and Virtualbox

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by tripower** [comment]
fyi

seems that the problem was the wrong version of installer
because the app worked after electron-packager and worked not after electron-winstaller
after upgrade from v2.6.4 to v4.0.2
it looks good and works at pure Windows and also Windows in VM Image
