### ISSUE TITLE
Unable to add content to a new open window

### ISSUE THREAD

**Issue by NiteenRC** [electron/electron#33154]
What version of electron-installer-windows are you using?
"electron": "^17.1.0"

What version of node and npm are you using?
Angular CLI: 11.0.7
Node: 14.17.0

What operating system are you using?
OS: win64

What did you expect to happen?
I am expecting to open new window and its opening perfectly but contents are not adding into opened window,
private _printPdf1(response) {
const url = http://localhost:4200/#table;
const myWindow = window.open(url, "_blank", "width=800,height=600,left=250,right=150");
myWindow['response'] = response;
}

Note: Same above code is working in angular9+ without any issue its contents are added in new window.

What actually happened?
Not adding response data into new Window. so window is blank.
Note: response is a Json data.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues don't follow the Issue Template that we set for the project. It looks like you may be using an issue template for Electron Forge or Electron Installer Windows. If this is an Electron core issue, could you please resubmit it following the Bug Template?

If you're looking for more detailed help with your app, feel free to also check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
