### ISSUE TITLE
WebAuthn Discoverable Credential (Resident Key)

### ISSUE THREAD

**Issue by ks75vl** [electron/electron#33271]
When I try to get resident credential from security key, a DOMException was thrown
After do some trace, I found that the exception related to `AuthenticatorStatus::RESIDENT_CREDENTIALS_UNSUPPORTED`
That exception caused by Electron or am I missing some conditions to perform a get resident key request?

Environment
- OS: Window 11
- Electron: 17.1.2

**Comment by clavin** [comment]
Hi there! We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by miniak** [comment]
Duplicate of #33353
