### ISSUE TITLE
[Bug]: Crash in AppendExtraCommandLineSwitches when clicking a link on Linux

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#33315]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17-x-y

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

No crashes

### Actual Behavior

Our users report that their app crashed when they clicked on a link in the BrowserWindow. Here are the crash reporter dumps: https://gist.github.com/indutny-signal/b42dd2e19b959a85aa1e545cc140df6e

### Additional Information

Unfortunately, we do not have a repro for this and it seems to happen very rarely.

**Comment by codebytere** [comment]
@indutny-signal my intuition is that it's `CHECK`ing here: https://github.com/electron/electron/blob/ebfcf89a0b554804fc8707215752a1130dc10182/shell/browser/electron_browser_client.cc#L549-L551

**Comment by codebytere** [comment]
@indutny-signal I believe it's `CHECK`ing here: https://github.com/electron/electron/blob/ebfcf89a0b554804fc8707215752a1130dc10182/shell/browser/electron_browser_client.cc#L549-L551

We might want to consider a softer way to handle that 🤔 

cc @nornagon who added this in https://github.com/electron/electron/pull/27804 - maybe we should `LOG(ERROR)` instead of `CHECK`ing?
