### ISSUE TITLE
[Bug]: Chrome extension not loading in production build

### ISSUE THREAD

**Issue by AnonymousXC** [electron/electron#33324]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H1

### What arch are you using?

x64

### Expected Behavior

The unpacked chrome extension must be loaded in the compiled or packed app (which is in exe).
The unpacked chrome extension is placed in the projects directory and it is working while debugging but after packing the source code it is not loading but all the other things are working absolutely fine.

### Actual Behavior

The extension is not loading in the packed app.
[This is the extension](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) which I am loading. 
I have loaded it with this line of code :- `const ext = await session.defaultSession.loadExtension(extPath);`

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by AnonymousXC** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Thanks but I got the problem actually I was keeping that extension in my source directory and while packing the file i used --asar switch so, the extension was not able to load. After removing --asar everything works fine.
Sorry for the Inconvenience.
