### ISSUE TITLE
[Bug]: Cannot call ipcRenderer.removeListener through contextBridge

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#33328]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS 12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect to be able to remove a listener from ipcRenderer from the renderer process while using the contextBridge.

### Actual Behavior

The contextBridge changes the function identity (I'm seeing `f() [native code]`  in the dev tools) which leads to an unbounded number of listeners getting added and never removed.

### Testcase Gist URL

https://github.com/ccorcos/electron-context-bridge-remove-listener-bug

**Comment by MarshallOfSound** [comment]
This is not incredibly well documented but this is expected behavior, I'll type this up here and either I or someone else can put it into the `contextBridge` documentation later.

Values sent over the context bridge maintain object identity in a single transaction.  A transaction in this context is _currently_ defined as:

* A call to `exposeInMainWorld`
* A call to a function, the transaction encompasses the passing of all function arguments and the return value but does **not** include nested function calls
* A promise resolution

Nested transactions (such as a function returning a promise that resolves async, or a function calling another function) do not maintain object identity.  Here are some practical examples.

```js
const foo = {};
exposeInMainWorld('test', {
  a: foo,
  b: foo,
});

// window.test.a === window.test.b
``` 

````js
const foo = {};
exposeInMainWorld('test', {
  a: foo,
});
exposeInMainWorld('test2', {
  a: foo,
});

// window.test.a !== window.test.b
```

````js
const foo = {};
exposeInMainWorld('test', {
  a: () => foo,
});

// window.test.a() !== window.test.a()
```

There is one interesting exception to this rule that function passed _back over_ the bridge do maintain object identity.  So for instance.

```js
let fn = null;
exposeInMainWorld('test', {
  setFn: (f) => { fn = f },
  getFn: () => fn,
});

// const testFn = () => {}
// window.test.setFn(testFn)
// window.test.getFn() === testFn
```

The solution to your specific case is to implement some kind of event emitter wrapper that maps event listeners to string / primitive keys that you can pass safely over the bridge.

At a higher level though, what you are trying to do (expose `ipcRenderer` over the context bridge) is fundamentally unsafe and fundamentally means the context bridge may as well not be in use.  Why separate the contexts and then just expose the entire IPC API to the unsafe context.

You should be exposing scoped and limited IPC apis, only for specific messages / senders.

I'd highlight that you might say "I still think this is a bug", that's fair, but from a technical level this is how things _have_ to work for GC reasons.

**Comment by ccorcos** [comment]
> Why separate the contexts and then just expose the entire IPC API to the unsafe context.

Is the IPC API unsafe to expose? I suppose I'm only using a few channels... But I'd like my renderer process to remain as generic as possible so that I can reuse it later in a mobile application...
