### ISSUE TITLE
[Bug]: Linux AppImage: Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by aronsommer** [electron/electron#33356]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS 12.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

My Linux application (builded on macOS) needs to download files via Git to a folder inside the application.
And it needs to write new seetings to a file called settings.json inside the application.

### Actual Behavior

In the unpacked Linux version everything works fine.
But with the AppImage version I have following error when I want to write new settings to the settings.json  inside the application:

```
Error: EROFS: read-only file system, open '/tmp/.mount_ElectrF5eHhx/resources/settings.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at writeNewSettings (/tmp/.mount_ElectrF5eHhx/resources/app.asar/main.js:361:6)
    at /tmp/.mount_ElectrF5eHhx/resources/app.asar/main.js:654:9 {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_ElectrF5eHhx/resources/settings.json'
}
[10886:0321/085227.648448:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 467C85D0A45DA64D.E7C3DA00B86A32F1
```

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. 

For most questions about Electron, there are a lot of options. Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out. Hope this helps you!
