### ISSUE TITLE
[Question]How to get current broswer window in renderer?

### ISSUE THREAD

**Issue by Kenhuey** [electron/electron#33456]
In the older version can use
```
/* renderer process */
const remote = require("electron").remote;
const window = remote.getCurrentWindow();
```

But Electron 14+ is already remove remote module, I tried use ipc to get window, but it only works in ipcMain.
```
ipcMain.on("some-event", event => {
    const window = event.sender.getOwnerBrowserWindow();
});
```

So how do I get the current broswer in renderer(or maybe ipcRenderer)?

Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by sgehrman** [comment]
@codebytere I would have appreciated an answer.  Very lame to blow this guy off.
