### ISSUE TITLE
[Bug]: "Error: cannot find module 'semver'" when running built executable

### ISSUE THREAD

**Issue by damms005** [electron/electron#33558]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When I build my executables and run them, it should not throw any exception

### Actual Behavior

When I build my executables and run them, it throws an exception:

### On Windows (using Wine on Linux)
![image](https://user-images.githubusercontent.com/9839355/161060094-07ef21c0-3346-49f1-a4a0-b6d4ef07480b.png)

### On Linux (Zorin OS based on Ubuntu 20.04 - ran via command line to see console error)
![image](https://user-images.githubusercontent.com/9839355/161060398-4e30032f-c573-4b7f-98c1-aad8eda9f02c.png)

### Additional Information

Source code: https://github.com/damms005/schoolserver-quasar

**Comment by damms005** [comment]
I think it might be necessary also to add my config options for  BrowserWindow and my package.json dependencies:

```
  const options = {
    show: false,
    icon: trayIconPath,
    width: 1350,
    height: 970,
    webPreferences: {
      preload: path.resolve(
        __dirname,
        process.env.QUASAR_ELECTRON_PRELOAD
      ),
    },
  }

```

```
{

  "dependencies": {
    "@headlessui/vue": "^1.4.2",
    "@heroicons/vue": "^1.0.5",
    "@quasar/extras": "^1.0.0",
    "@sentry/electron": "^2.5.4",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.4.1",
    "@tailwindcss/typography": "^0.5.0",
    "axios": "^0.21.1",
    "chart.js": "^3.7.0",
    "collect.js": "^4.29.3",
    "core-js": "^3.6.5",
    "electron-store": "^8.0.1",
    "hamsters.js": "^5.4.2",
    "lodash": "^4.17.21",
    "node-multiprocess": "^0.0.2",
    "node-polyfill-webpack-plugin": "^1.1.4",
    "quasar": "^2.0.0",
    "sequelize": "^6.17.0",
    "sharp": "^0.29.3",
    "sqlite": "^4.0.23",
    "sqlite3": "^5.0.2",
    "vue": "^3.2.31",
    "vue-router": "^4.0.14",
    "vuex": "^4.0.1",
    "xlsx": "^0.17.4"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.13.14",
    "@faker-js/faker": "^6.0.0-alpha.5",
    "@quasar/app": "^3.0.0",
    "@quasar/quasar-app-extension-testing": "^2.0.1",
    "@quasar/quasar-app-extension-testing-e2e-cypress": "^4.0.0-beta.8",
    "@quasar/quasar-app-extension-testing-unit-jest": "^3.0.0-alpha.7",
    "@sentry/cli": "^1.72.2",
    "@types/inflection": "^1.13.0",
    "@types/node": "^12.20.21",
    "@types/sequelize": "^4.28.10",
    "@types/sharp": "^0.29.4",
    "@typescript-eslint/eslint-plugin": "^5.13.0",
    "@typescript-eslint/parser": "^5.13.0",
    "@vue/devtools": "^6.0.0-beta.19",
    "dotenv": "^10.0.0",
    "electron": "^18.0.1",
    "electron-builder": "^22.14.5",
    "electron-devtools-installer": "^3.2.0",
    "electron-download": "^4.1.1",
    "electron-packager": "^15.4.0",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-cypress": "^2.11.3",
    "eslint-plugin-jest": "^26.1.1",
    "eslint-plugin-vue": "^7.0.0",
    "majestic": "^1.7.0",
    "tailwindcss": "^3.0.7"
  }
}
```

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment]
... or @damms005 are you saying that it works when unpackaged, but the semver failure occurs only in the packaged executable built by electron-builder?
