### ISSUE TITLE
[Bug]: Electron ignores locale info about the first day of the week

### ISSUE THREAD

**Issue by GamerClassN7** [electron/electron#33553]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.x.x

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/22167469/161029403-9e0b5a27-d2a6-4cda-90cf-c1e7d11903f0.png)
* From Browser

### Actual Behavior

![image](https://user-images.githubusercontent.com/22167469/161029351-26d0d9ce-87c3-48f0-9753-2ca9632a6c15.png)
* from electron

### Additional Information

Somehow dont know why Only electron on my machine see sun as first day of the week no other application

**Comment by miniak** [comment]
@GamerClassN7 title?

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.
