### ISSUE TITLE
[Bug]: shelljs.which('node') return null in Electron production

### ISSUE THREAD

**Issue by sufangyu** [electron/electron#33598]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Montery

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

shelljs.which('node') return null in Electron's production mode.

System: Mac.

shelljs.which('node') return value in Electron's production mode.

### Actual Behavior

shelljs.which('node') return null in Electron's production mode.

System: Mac.

shelljs.which('node') return value in Electron's production mode.

### Additional Information

shelljs.which('node') return null in Electron's production mode.

System: Mac.

shelljs.which('node') return value in Electron's production mode.

**Comment by MarshallOfSound** [comment]
Cocoa applications when self responsible (launched from finder or via launchd) don't have environment variables set.  This makes sense because env vars like `PATH` are configured for your shell not for an application.  You can spawn a `bash` tool or something to try load the users `PATH` variable into your application but this isn't expected to work out of the box
