### ISSUE TITLE
[Bug]: window showSaveFilePicker stores empty file

### ISSUE THREAD

**Issue by sirkrisp** [electron/electron#33648]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I am trying to write a file to disk using the showSaveFilePicker function (https://developer.mozilla.org/en-US/docs/Web/API/window/showSaveFilePicker
) from the window file system access API. However, while the file is created, the content of that file is empty. It works in the web app but not in electron.

Here is the code I use to save the file:
```typescript
async function saveFile(name: string, data: Uint8Array) {

            // create a new handle
            const newHandle = await window.showSaveFilePicker({
                suggestedName: name,
                types: [{
                    accept: {
                        "application/pdf": [".pdf"]
                    }
                }]
            });

            // create a FileSystemWritableFileStream to write to
            const writableStream = await newHandle.createWritable();

            // write our file
            await writableStream.write(data);

            // close the file and write the contents to disk.
            await writableStream.close();
}
```

The issue has also been raised on stack overflow:
https://stackoverflow.com/q/66661551/7446235

### Actual Behavior

The file is created but it is empty. I also get an error: `Uncaught (in promise) DOMException: The request is not allowed by the user agent or the platform in the current context.`

**Comment by Cirras** [comment]
Looks like a duplicate of https://github.com/electron/electron/issues/28422

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Andrew-web-coder** [comment]
I can confirm that this bug still exists. Simply call `await window.showSaveFilePicker(opts);` and an empty file will be created for no reason.
