### ISSUE TITLE
[Bug]: Scroll BrowserWindow with robotjs  / @nut-tree/nut-js

### ISSUE THREAD

**Issue by lucasvieceli** [electron/electron#33701]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

be able to scroll with mouse

### Actual Behavior

I'm using electron with react to create a bot for bombcrypto

in it I'm using "@nut-tree/nut-js" / "robotjs" to make the mouse movements

https://github.com/lucasvieceli/bot-electron

at some point when running the system, @nut-tree/nut-js needs to scroll or drag, but for some reason in the window that is opened by "BrowserWindow", it can't do it.

the rest of the mouse commands work

I already tried to scroll with python too, but nothing works

have. any configuration of the "BrowserWindow" that is blocking?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
