### ISSUE TITLE
[Bug]: When I force reload the app, it's clearing the localStorage

### ISSUE THREAD

**Issue by cjambrosi** [electron/electron#33740]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

x64

### Expected Behavior

When forcing application reload, example:` window.location.reload()`. 
Not clear the localStorage variables.

Using Electron + Next.js

### Actual Behavior

When I force reload of the application, example: `window.location.reload()`. 
It is clearing the localStorage variables and that is bad for me.

Using Electron + Next.js

### Additional Information

I don't believe it's a bug, but I would like to understand if this is the correct behavior.
I have an application with Electron integrated with Next.js and through the components I'm storing some variables in localStorage.
However, for specific reasons, i need tforce a reload in the app at a certain time and only in the app build (production version), when i force the reload, all localStorage variables are cleared.
Is this expected? Is there a way around so that this doesn't happen?

Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
