### ISSUE TITLE
[Bug]: electron crashes when run better-sqlite-sqlcipher  on centos

### ISSUE THREAD

**Issue by lyxgy841** [electron/electron#33809]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.*, 15.*, 16.*

### What operating system are you using?

Other Linux

### Operating System Version

CentOs 8.4.2105

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

`npm install better-sqlite3-sqlcipher`
then add code 
```
const Database = require('better-sqlite3-sqlcipher')
const db = new Database('./data.db');   
db.pragma('key = "123"');
db.prepare('CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY, name TEXT)').run();    
db.prepare('INSERT INTO people (name) VALUES (@name)').run({ name: 'jack' });
```
If the version of electron used is above 14， please modify the source code of better-sqlite-sqlcipher.
modify better_sqlite3.cpp line 461
`node::AtExit(Database::AtExit);`
to
```
node::Environment* env = node::GetCurrentEnvironment(ctx);   
node::AtExit(env, Database::AtExit, nullptr);
```
should create a sqlcipher database

### Actual Behavior

Crashes when run code.
And crashes only when running on centos using electron，run normally with electron on ubuntu，run normally with node on centos.
If remove `db.pragma('key = "123"');`,  it works fine

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue, as well as provide steps that do not involve code modification? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by lyxgy841** [comment]
https://github.com/lyxgy841/electron-sqlcipher-crash
