### ISSUE TITLE
I can't type/write in Games :(

### ISSUE THREAD

**Issue by ThomasPoloBelgini** [electron/electron#33811]
I'm trying to type inside the games in parts that I need to type or control the character with the keys...how could I solve this?

**Comment by mlaurencin** [comment]
Thanks for reaching out! I am not quite sure what you are referring to. Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

And would it be possible for you to use the issue make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-info` label for this reason. After you make a test case, please link to it in a follow-up comment.

Thanks for understanding and meeting us half way :grinning:
