### ISSUE TITLE
[Bug]: Audion DevTools Extension not working in Electron

### ISSUE THREAD

**Issue by marcelblum** [electron/electron#33935]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13 through 18

### What operating system are you using?

Windows

### Operating System Version

Win 10 Pro 21H2

### What arch are you using?

x64

### Expected Behavior

A "Web Audio" tab/panel should appear in the DevTools. [Audion](https://github.com/GoogleChrome/audion) is a DevTools extension for the Web Audio API.

### Actual Behavior

The `extension-ready` event successfully fires and the extension appears to load, but a couple warnings appear in the console and the "Web Audio" tab never appears in the DevTools. The relevant warnings in the console are:
`Permission 'debugger' is unknown or URL pattern is malformed`
and
`[5208:0426/153939.221:ERROR:CONSOLE(2)] "Uncaught TypeError: Cannot read properties of undefined (reading 'attach')", source: chrome-extension://clijboajkbjbbjkopfofddimcfaeochf/devtools.js (2)`

### Testcase Gist URL

https://github.com/marcelblum/audion-in-electron

### Additional Information

Note: my test repo uses [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer) for simplicity, but I also tested with vanilla `loadExtension()` on a manual build from source of Audion and got the same errors.

Also note: I tested and got the same results in several Electron versions 13 through 18. My test repo defaults to using Electron 16 for simplicity because in latest Electron 18 some additional, presumably unrelated errors appear in the console similar to #32133:
`[10792:0426/153220.575:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[10792:0426/153220.575:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)`

Ref: https://github.com/GoogleChrome/audion/issues/141

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by marcelblum** [comment]
@jkleinsc thanks, maybe you didn't see that I already included a test repo for this (https://github.com/marcelblum/audion-in-electron). If that's not sufficient let me know.

**Comment by codebytere** [comment]
hey @marcelblum - it looks like this isn't working bc under the hood the chrome extension calls `chrome.debugger.attach`, which we currently [don't support](https://github.com/electron/electron/blob/caddc83cfe1be3837d060467835e4a705d9d0cb4/docs/api/extensions.md#L37). I'll see if there's anything i can do.

**Comment by treeoflife111** [comment]
bump

**Comment by dawidjaniga** [comment]
Hey @codebytere 👋🏻
Did you by any chance find something which can be done here to run Audion extension?

@marcelblum Do you know other ways to debug Web Audio in Electron?

**Comment by marcelblum** [comment]
@dawidjaniga nope just sweat and tears 🥲 Honestly I found Audion to be kinda janky and unstable even in regular Chrome anyway so just got used to not using it
