### ISSUE TITLE
[Docs]: Document V8's 4GB memory cap

### ISSUE THREAD

**Issue by robinchrist** [electron/electron#33994]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v14 upwards

### What operating system are you using?

Ubuntu

### Operating System Version

21.04

### What arch are you using?

x64

### Expected Behavior

Native Addons should be able to allocate as much memory as they require without depending on the main electron instance

### Actual Behavior

Electron has **_undocumented_** memory limitations, as was also discussed in this issue: https://github.com/electron/electron/issues/31330

Additionally, I realised that native addons **do** count into the overall Electron process memory limit! This is because chromium overrides C++ allocators (e.g. `allocator_shim_override_cpp_symbols.h`), apparantly because the memory-infra teams decided that they want to take native addons into account for their heap profiler? See https://bugs.chromium.org/p/chromium/issues/detail?id=550886

This is problematic, because there are also weird quirks like

```
// We generally prefer to always crash rather than returning nullptr for
  // OOM. However, on some macOS releases, we have to locally allow it due to
  // weirdness in OS code. See https://crbug.com/654695 for details.
```

I suggest the following steps:
- Clearly document that there is a 4GB (or 8GB? or something in between? see #31330 ) memory limit which **includes memory allocated by native addons**
- Clearly document that chromium overrides your C++ allocators (like malloc), because this has probably caused some performance issues for me in the past
- **Start shipping two versions of electron, one with pointer compression enabled (default) and one without, allowing for more than 4GB / 8GB of memory**

**Comment by MarshallOfSound** [comment]
> Clearly document that there is a 4GB (or 8GB? or something in between? see https://github.com/electron/electron/issues/31330 ) memory limit which includes memory allocated by native addons
> Clearly document that chromium overrides your C++ allocators (like malloc), because this has probably caused some performance issues for me in the past

These two things are easy enough, happy to review a docs PR 👍 

> Start shipping two versions of electron, one with pointer compression enabled (default) and one without, allowing for more than 4GB / 8GB of memory

This isn't going to happen, we won't ship multiple versions of Electron and pointer compression is a fundamental performance feature of V8 nowadays that we definitely don't want to do differently to upstream or we're going to run into super bad edge cases.

**Comment by robinchrist** [comment]
> These two things are easy enough, happy to review a docs PR 👍

I would love to prepare a PR - unfortunately I don't have time to do so. Because I'm dealing with the fallout from your silently introduced, undocumented limitation.

> This isn't going to happen, we won't ship multiple versions of Electron and pointer compression is a fundamental performance feature of V8 nowadays that we definitely don't want to do differently to upstream or we're going to run into super bad edge cases.

In that case you should think about how to allow native addons to allocate memory outside Node's heap.
Perhaps patching / removing the C++ allocator shim would be an option?

Because one thing is for sure: If you limit the entire Electron process including native addons to 4GB, you essentially make Electron useless for everything that goes beyond a very simple Desktop application.

**Comment by MarshallOfSound** [comment]
I'd like to take this opportunity to remind you that all interactions on the Electron issue tracker fall under our [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md), we engage with you respectfully, please do so in return.

> you essentially make Electron useless for everything that goes beyond a very simple Desktop application.

That simply isn't true and the vast swarm of Electron apps in existence proves that.  Please avoid superlative statements like these, they really don't help the discussion or make anyone want to assist you.

<hr />

> In that case you should think about how to allow native addons to allocate memory outside Node's heap.
> Perhaps patching / removing the C++ allocator shim would be an option?

I don't think removing the allocator shim is an option here, far too much of Chromes memory infra will inherently rely on it.  For instance Chromiums new `PartitionAlloc` relies on `use_allocator_shim` being enabled.

In regards to the actual limit, there is a much more extensive / eloquent discussion from @/nornagon in the original thread #31330

These limits should be documented, but if you have large data processing requirements that legitimately exceed 8GB of data in memory (a) try make that smaller, that's huge and (b) farm it out to a child process, either a custom executable or just `node` with your original native addon.  There is more info on that in the linked thread.  I'm sorry there's not a fantastic solution to this, the costs of disabling the feature causing you trouble are simply to high.

**Comment by robinchrist** [comment]
> (a) try make that smaller, that's huge
It may be for the usual web stuff, but it's definitely not for anything that is related to (Hi-Res) Audio, Video or (scientific) simulation (see the other issue #31330 you linked - I am not the only one having issues)

That is also the reason why we're using native addons...

> (b) farm it out to a child process, either a custom executable or just node with your original native addon.
Yes, that seems to be the only option

Sadly, changing from a native addon to a completely separate process is a huge endeavour and now we're faced with a planned released which we won't be able to make.

At the very least, there should've been a warning before the v14 release! This isn't the first time there are weird issues with 
native addons, which are seemingly kind-of accepted in Electron, but only get the bare minimum of attention.


> I don't think removing the allocator shim is an option here, far too much of Chromes memory infra will inherently rely on it. For instance Chromiums new PartitionAlloc relies on use_allocator_shim being enabled.

I should've been more precise: Removing the allocator shim for native addons.
However, I do see why this could be problematic: The addon will have to allocate JS objects which probably need to reside inside the 4GB V8 / Node / Chromium heap.

> That simply isn't true and the vast swarm of Electron apps in existence proves that. Please avoid superlative statements like these, they really don't help the discussion or make anyone want to assist you.

I don't want to get this discussion started, but from my point of view, most Electron applications I know fall into the category I mentioned. Correct me if I'm wrong, but VS Code for example uses a custom Electron build to work around some limitations.

I also wonder how many existing, more sophisticated applications will hit this limit once they decide to upgrade Electron to a version above 14.


Circling back to the official documentation issue, I want to emphasise that I am not the right person to file a PR. I do not have the required experience with the Electron / V8 / Node / Chromium management subsystem to make correct statements about this topic. As there also seems to be some confusion about what the actual memory limit is (again, please refer to #31330 ), it is important that somebody who knows exactly what is going on writes a summary on this.

This documentation issue should be assigned high priority, as currently it is entirely undocumented, persists since v14 (whereas Electron is already at v19 beta) but is overall just very little work.
Ideally, this would addressed together with the other documentation issues concerning native addons.

**Comment by ckerr** [comment]
> At the very least, there should've been a warning before the v14 release! 

It probably could've been made more explicit, e.g. listed in the 'breaking changes' section, but FWIW the [14.0.0 release notes](https://www.electronjs.org/blog/electron-14-0) do link to the [V8 v9.2 release notes](https://v8.dev/blog/v8-release-92) that discuss this issue directly.

**Comment by MarvMartian** [comment]
It looks like the Chromium team is planning to expand only to 16G:
https://chromium-review.googlesource.com/c/chromium/src/+/3383838/  

I would encourage the Electron team to remove the limit altogether.

**Comment by MarshallOfSound** [comment]
> I wonder if the Electron team is curious about how many of their users will be following those instructions to build their own private version to get around this limit. My guess is that it will be a significant amount. If it is, what a waste of everyone's time.

Based on our own surveys / understanding of how folks build Electron apps, I personally think your guess is wrong 🤷 The number of folks downloading straight Electron binaries outweighs the number of people in these issue threads by multiple orders of magnitudes.  You have to realize, using >8GB of memory in heap in a renderer is a massive edge case.

> I'm in full agreement with @robinchrist - What is the point of using Electron if we must be hamstrung by the artificial limits imposed by the Chromium team?

This is the wrong~ish way of thinking about this, from your perspective right now you see this is Electron arbitrarily accepting a limitation imposed by Chromium.  Here's the missing context, Electron has had a relatively strict policy of following the guidance and direction of upstream Chromium for years now, ensuring our build systems, configurations and flags _align_ is incredibly important to the stability of Electron.  If we diverge in any of those things (build, config, flags, etc.) then suddenly we're in untested territory, the incredibly work the Chromium security and performance teams do, suddenly doesn't apply.  The fuzz testing, E2E testing, beta / canary testing that Chromium goes through, also doesn't directly apply.  And if we run into an issue caused by our unique / patched configuration, we're on our own.  The Electron maintainer team is _miniscule_ compared to the Chrome team.  We _have_ to align, or we _will_ inevitably run into issues that cause problems for much larger groups of our users down the road.  (There are multitudes of historical examples where this happened).

> https://chromium-review.googlesource.com/c/chromium/src/+/3383838/

It looks like crrev is down for me at the moment but if that change is what the comment in the crbug outlines it to be this will just be inherited by Electron when it makes its way into one of our Chromium roller PRs.  Probably Electron 21 🤷 

> I would encourage the Electron team to remove the limit altogether.

As outlined above, deviating from Chromium is something we are incredibly unlikely to do especially if the deviation is intended to be permanent.

**Comment by MarvMartian** [comment]
Understood and makes perfect sense.  Nevertheless, the Chromium team member posting seemed rather confident:

"In the meantime, we can either land a GN arg that Electron can use downstream to increase the limit unconditionally on the platform (knowing that it incurs a cost on Windows pre-8.1), or the patch to set the limit to a higher value is supported as well. Note that an even higher value should work as well."

I'm not entirely sure what is meant by "supported" in the above sentence, but what would Electron's policy be if a higher limit were "supported" by Chromium, but Chromium continued to lock the limit lower for some reason?

**Comment by jpambrun** [comment]
I think there is a bit of confusion here. I see mentions of heap, which refers to v8's js heap, and is limited to 4gb because of pointer compression. The issue many of us are facing is not about js heap but buffer and typed array which are not allocated within this heap. You can allocate 8GB of TypedArray + 4GB of js heap per process today on Windows. On mac and Linux you can allocate  16GB of TypedArray + 4GB of js heap per process. In fact, I believe wasm heaps are from yet another pool of memory and can go up to 16GB on windows.

On top of that, because of the partition allocator you don't actually get 8GB of typed array, but 8gb of address space. Buffer/typedarrays are allocated on a 2MB boundaries. If you allocated many 1.01MB buffers, you can only get about 4096 of them.. the rest of the memory is not consumed, but the address space is lost.

This is obviously a complex issue. Writing comprehensive documentation on the current limitation might just be more effort than enabling the use more memory with #35218.

**Comment by MarvMartian** [comment]
@jpambrun:  Thank you for pointing out WebAssembly.Memory().  If indeed it carves buffers out of an independent 16G heap, that's very interesting and could definitely help some of the posters on this thread.

**Comment by vrunhofen** [comment]
This is definitely an issue. This is not an edge case. 

Electron isn’t just used by vs code but by other programming environments as well. The official APL GUI application uses electron. 

I have a custom JS IDE that I created to experiment with various ideas in finance and ML. And I consistently hit upon the 4GB limit per tab/page. Even though I have 16 GB physical RAM.

It makes sense for chromium to have these limits since no webpage/app should hog that much of your computing resources. But when it’s a desktop application I would like it to use all of my resources to get the job done faster. 

Newer computers of any form have higher available RAM at cheaper rates, and use cases like ML are fairly common. 

If there is any sensible way to delimit this limitation, please, please do so.

**Comment by marcelblum** [comment]
@vrunhofen the limit was bumped to 16gb as of electron 21/chromium 106

**Comment by MarvMartian** [comment]
@vrunhofen it depends on what you're doing.  The 4G limit is on heap. Apparently there will be no future joy on that front, ever. It is considered by the Chromium team to be more important to focus on optimizations for the "many ordinary" browser users than to support the "few people" who want to build memory-hungry browser-based applications. And, sadly, per @MarshallOfSound, there are important reasons why the Electron team has to follow the Chromium team rather than just going ahead and compiling Chromium without "pointer compression" (pointer compression being the origin of the 4G limit).  I should add that it is alleged to be possible to build Chromium (and a private copy of Electron) without pointer compression, but we followed some posted suggestions and we had no luck.  There must be build magic we've missed in terms of the flags to be set and how to properly set them, since our attempts still had the 4G limit.

If you are running out of heap, you'll either have to run in Firefox (where there are few memory limitations), or -- if this is even possible for your application -- you'll need to do whatever it takes in order to store massive stuff in typed arrays instead of heap (as, sigh, we have). Per @vrunhofen the limit on typed arrays is now 16G again as opposed to 8G (hooray!) (but see @jpambrun cautions on allocating typed arrays).  There's also 16G available for WebAssembly (WebAssembly.memory()).  I've successfully allocated some of that to try it out, and it seemed to work, but that's all I can say about it at the moment.  Presumably a hack could move heap data into WebAssembly memory also, so maybe there's as much as 32G hanging around for memory hacking.

**Comment by frank-pian** [comment]
```v8_enable_pointer_compression = false``` is a viable way to lift the 4GB heap limit?

**Comment by marcelblum** [comment]
@frank-pian yes, but in practice most high memory use cases are for items stored off-heap such as media, and disabling pointer compression has no affect on those limits. Instead you would need to change this line in Chromium's source which currently sets a 16GB limit:

https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/allocator/partition_allocator/partition_alloc_constants.h#284

And even with that modified, on Windows you additionally have to disable sandboxing in Electron in order to go past 8GB.

**Comment by highperformancecoder** [comment]
This is an incredible pain point for me too. The problem is the forced crash when the heap memory is exceeded, rather than null returned. It is not a good look for an application to quietly die - I would prefer an error message returned to the user so they can try a different thing.

I have been forced to use mmap and create my own heap - which works for one of my use cases, where I can use a simple pool allocator, but I keep finding others, meaning that at the moment, I will probably have to implement my own general heap, and I'm not finding a lot of information on how to do this correctly.

**Comment by MarvMartian** [comment]
Yes, it does crash in some circumstances.  But not in others. I would love reliable crashes.  Crashes would be 1000 times better than the "other" Chromium behavior in this situation, which is to spend 99% of its time in the garbage collector, leaving users wondering what's going on, and leaving developers wondering what sort of bizarre performance issue there might be. Some sort of trap when the GC isn't freeing sufficient memory, or the GC is called too quickly and repetitively, would be nice.  And, to @highperformancecoder's point, an error code would be nice as well.
