### ISSUE TITLE
How do I rename Atom.app

### ISSUE THREAD

**Issue by joerozek** [electron/electron#340]
When I try to rename Atom.app to MyAppName.app I get the following error dialog.
I'm using Mavericks 10.9.2

You can’t open the application “MyAppName.app” because it may be damaged or incomplete.

**Comment by jakefb** [comment]
@zcbenz I noticed that in the docs it says the structure of a renamed app should be Contents/MacOS/MyApp instead of Contents/MacOS/Electron. I'm guessing that this is a mistake so I fixed it and made a PR here https://github.com/atom/electron/pull/2044

**Comment by JuanFerrer** [comment]
Is this still true? If I rename `Contents/MacOS/Electron` to `MyApp` and change the value of `CFBundleExecutable` in `Contents/Info.plist` to `MyApp` (as mentioned by @felicienfrancois and @zcbenz ), when trying to execute I get a message saying:

> The application "MyApp" can't be opened.

Everything else that is mentioned in the [distribution guide](https://electronjs.org/docs/tutorial/application-distribution#rebranding-with-downloaded-binaries) I can do and it all runs fine (except that the name of the app in the dock on hover is "Electron").

I think the guide should be updated, because the process described leads to an error. @jakefb's PR looked OK, but it says it was unnecessary, so I'm confused. It's been two years
