### ISSUE TITLE
[Bug]: navigator.mediaDevice.getUserMedia cannot move sources to front

### ISSUE THREAD

**Issue by weiweian90** [electron/electron#34087]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

Window10 version 19044.1645

### What arch are you using?

x64

### Last Known Working Electron version

15.5.2

### Expected Behavior

expected move source to front

### Actual Behavior

not move the source to front

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by weiweian90** [comment]
https://github.com/electron/electron/issues/34087#issuecomment-1118432758

> 

https://gist.github.com/weiweian90/ae6197a608687772ac18fc409f7f17cd
