### ISSUE TITLE
[Bug]: Get multiple Bluetooth devices with requestDevice() 

### ISSUE THREAD

**Issue by alminisl** [electron/electron#34124]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 

### What arch are you using?

x64

### Expected Behavior

I expect to get a list of Bluetooth devices when executing: 

```
const device = await navigator.bluetooth.requestDevice({
    acceptAllDevices: true,
  });
  ``` 
  

### Actual Behavior

I just get one device. 

### Additional Information

```
const result = deviceList.find((device) => {
        console.log("device: ", device);
        return device.deviceName === "test";
      });
  ```
      
Tried also this however I only get 1 device when using this too. Not sure what is happening as this should list all the BT devices according to documentation?

**Comment by alminisl** [comment]
one of the solution I came up with is using a recursion and "constantly" check for the devices and add them to a list. Stopping the execution after x number of seconds. 

But there has to be a better way?

**Comment by codebytere** [comment]
From https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice

> The Bluetooth.requestDevice() method of the [Bluetooth](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth) interface returns a Promise to a BluetoothDevice object with the specified options.

it returns a single device - this is working as intended.

**Comment by jkleinsc** [comment]
In investigating [implementing persistent Web Bluetooth permissions](https://bugs.chromium.org/p/chromium/issues/detail?id=974879) in Electron, I have discovered that our `select-bluetooth-device` only fires with one device instead of all of the possible devices.  
@alminisl are you using that event? eg see the example here: https://www.electronjs.org/docs/latest/tutorial/devices#web-bluetooth-api.  In theory one should be able to use that event to get a list of possible devices, but right now it only returns one device at a time.  I'll put up a PR shortly that fixes this issue.
