### ISSUE TITLE
Compatible with the low version of chromium's chrome-devtools-frontend

### ISSUE THREAD

**Issue by white-than-wood** [electron/electron#34246]
electron version: v18.2.3
Operating system: macOS 12.13.1

Hi,now when I using Adb-forward to debug android webview remotely, Can I use the high version of electron's chromium to be compatible with the low version of chromium's chrome-devtools-frontend?

How to solve the problem that the inspect.html page is blank due to different chromium versions?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
