### ISSUE TITLE
[Bug]: Some JavaScript stop working and outline didn't show after a window.confirm

### ISSUE THREAD

**Issue by agoudbg** [electron/electron#34254]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Expected Behavior

Everything work well after a window.confirm

### Actual Behavior

After window.confirm, the element lose the outline and JavaScript events that seem have something to do with focus.
Returns normal after window lost and get focus.
I know it's not suggested to use window.confim, but I think this issue should be fixed.

### Testcase Gist URL

https://gist.github.com/6597de549975787e3f2dff5d6f327b9e

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. Looking at the gist you attached, I think this may be an issue that requires some debugging help with you app, rather than an issue with Electron specifically. Because of this, I'm going to close this issue. 

For most questions about Electron there are a lot of options. Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
