### ISSUE TITLE
[Bug]: The error "The exception Breakpoint" showed when system shutdown in windows 7

### ISSUE THREAD

**Issue by weiluenju** [electron/electron#34311]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.4

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Expected Behavior

Close the program normally.

### Actual Behavior

1. Use the electron-quick-start, add a empty close event for mainWidow like this:
`mainWindow.on("close", function(event) {});`
2. Use electron-forge package and distribute.
3. Run electron-quick-start.exe.
4. Shutdown system.
5. The error is show
![0x80000003](https://user-images.githubusercontent.com/10330207/169662690-2071fc4e-857b-4e29-8bb6-290ab2699587.PNG)

Only happen in Windows7

Complete code:
```
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  mainWindow.on("close", function(event) {});
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

```

**Comment by gdavidkov** [comment]
It also happens in Windows 10.

**Comment by dforeman141** [comment]
I had this problem and found the root cause in my case.
I was using event.preventDefault() in the mainWindow.on('close') function and mainWindow.on('minimize') function.
I was doing this so that I could hide the window into the system tray instead of closing it.
The error occurs because when the application is closed on shutdown or logoff those two functions don't have the opportunity to clean up all the application processes. So, there were processes from the application still running while Windows is trying to 
 shutdown or logoff the user.
I modified my code and removed the event.preventDefault() in the two functions and just went with a frameless window.
Now I don't get the error.

Hope this will help someone.
When you have this problem, it could be because there are processes not getting terminated when the application quits.
