### ISSUE TITLE
[Bug]: Italian keyboard changed history shortcuts

### ISSUE THREAD

**Issue by superandrew** [electron/electron#34347]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The history back and forward mapping where `CMD+[` and `CMD+]`. 

### Actual Behavior

Now they are mapped to `CMD+ò` and `CMD+à`

### Additional Information

The keyboard shortcuts for history have changed in a non consistent way.
The former shortcut was "CMD+[" and "CMD+]" which in an italian keyboard were consistent.

Now the shortcut is mapped tp "CMD+ò" and "CMD+à" which, honestly does not make much sense.

**Comment by superandrew** [comment]
I must add that CMD+à in the case of slack is the shortcus to open the keyboard shortcuts panel
![CleanShot 2022-05-25 at 11 42 34](https://user-images.githubusercontent.com/71364/170233145-e3a681ba-60e3-448d-a633-c6d450b15561.png)

**Comment by squidbork** [comment]
@superandrew Might just be a mac bug, I can repro in Safari too

**Comment by superandrew** [comment]
it is true that ( in 12.4 at least) safari uses CMD+ò and cmd+à to move in history. However Electron until now used the CMD +[ and CMD + ] shortcuts. An example is Mattermost 5.04 vs Mattermost 5.1 and the last version of slack which has conflicting shortcuts as reported. Not sure if before in Safari the shortcut was different, but I'll check.

**Comment by clavin** [comment]
Just to note: I looked into Mattermost and 5.0.4 was Electron 14.1.0 whereas Mattermost 5.1.0 is Electron 18.0.3, a rather sizable jump. (Congrats to them on making the jump! 🎉) This makes it a little bit difficult to pin down exactly what changed to cause this behavior to change because there were a lot of changes between those two Electron versions. 🤔

Could I ask you to make a test case with [Fiddle](https://electronjs.org/fiddle) (or just in an editor and upload it as a gist, whatever flow you prefer) and link it here? This helps us with triaging as well as diagnosing, fixing, and verifying the issue. 🙂
