### ISSUE TITLE
[Bug]:  For how long `chrome.webvieTag` will be available in Electron, even if is already `"deprecated"` in Google Chrome docs ? 

### ISSUE THREAD

**Issue by raphael10-collab** [electron/electron#34356]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04 Desktop

### What arch are you using?

x64

### Expected Behavior

Continue to use `webviewTag` or replace it with equivalent API

### Actual Behavior

May be I reached a wrong google webpage, but it looks like that `chrome.webviewTag` is already a `deprecated API`  : https://developer.chrome.com/docs/extensions/reference/webviewTag/  

If this is the case,  why `webviewTag` is still deployed in Electron ?

### Additional Information

The problem in a nutshell is the following: in the Electron docs it is stated that  : `" it's not guaranteed that the WebView API will remain available in future versions of Electron"` . And this while in the `Chrome Developers Docs` `webviewTag` looks ALREADY `"deprecated"`.  

My main question is: for how long `chrome.webviewTag` will be available in Electron, even if, if I'm not wrong, it is ALREADY considered `"deprecated"` in Google Chrome docs ? 
For the next 2 / 3/ 5  or 10 releases ? 
Since the frequency of new Electron releases is, luckily, accelerated, this is a very important point

**Comment by VerteDinde** [comment]
Hey @raphael10-collab, thanks for asking this! The honest answer to your question is "we don't know." As of this time, there aren't any plans to remove `webviewTag` on Electron's side. However, `webviewTag` is is part of the deprecated Chrome Apps platform - as such, Chrome could decide to remove it or drop support at any time. According to this timeline outlined by Chrome itself, Chrome is planning to end support for Chrome Apps for all customers next month, June 2022: https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html

My recommendation to you would be to remove any `chrome.webviewTag` dependencies in your apps as soon as possible, while the API is deprecated, but still available. Chrome included a migration guide for appis using the Chrome Apps platform API here: https://developer.chrome.com/docs/apps/migration/

I hope this helps you! Since this issue doesn't represent a task needing to be completed, I'm going to close it, but please feel free to ask in our Discord if you have more questions - we have many active help channels and mentors, as well as fellow devs, who can help you out.
