### ISSUE TITLE
[Bug]: can't download the blob:http file 

### ISSUE THREAD

**Issue by leconehu** [electron/electron#34373]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.3.4

### What operating system are you using?

Windows

### Operating System Version

window 10 19044

### What arch are you using?

x64

### Expected Behavior

var content='';//
var base64ToBlob = function (code) {
        const parts = code.split(';base64,')
        const contentType = parts[0].split(':')[1]
        const raw = window.atob(parts[1])
        const rawLength = raw.length
        const uInt8Array = new Uint8Array(rawLength)
        for (let i = 0; i < rawLength; ++i) {
          uInt8Array[i] = raw.charCodeAt(i)
        }
        return new Blob([uInt8Array], {
          type: contentType
        })
      }
		window.onload=function(){
			   const aLink = document.createElement('a')
      const blob = base64ToBlob(content) // new Blob([content]);
      const evt = document.createEvent('HTMLEvents')
      evt.initEvent('click', true, true) 
      const fileName =  'dw' + '.jpg'
      aLink.download = fileName
      aLink.href = URL.createObjectURL(blob)
	    aLink.click()

### Actual Behavior

can't download the file

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! I think this specific issue may be an issue with your app, and not an issue specific to Electron. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
