### ISSUE TITLE
Bad file descriptor (9)

### ISSUE THREAD

**Issue by vinnitu** [electron/electron#34370]
Hi.
Am I missing something?

I run npm start on hello world project and get error

[1:0528/221624.446950:FATAL:proc_util.cc(76)] Check failed: . : Bad file descriptor (9)
Trace/breakpoint trap (core dumped)

What does it mean?

I works only with --no-sandbox, why?

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
