### ISSUE TITLE
[Bug]: require("log4js") blocks the normal starting process

### ISSUE THREAD

**Issue by PH8919** [electron/electron#34400]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

ia32

### Expected Behavior

After I run the command, the window appears and UI refresh immediately, no matter how many applications I will run.

### Actual Behavior

Recently,  I find my application will block several seconds when opening it in more than one terminals. I find the require("log4js") in my code cause this issue and it puzzles me. Then I run the "electron-quick-start-master" with _Electron 12.2.3_ with "log4js" installed and I add `require("log4js")` in render.js, change the webPreferences for main window to be `webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: true,
      contextIsolation:false
    }`
After "npm install", I open two terminals to execute "npm start". In the first terminal, after I run the command, the window appears and UI refresh immediately. In the second terminal, after running the command, the window appears immediately, but the UI refreshs several seconds later.

### Additional Information
Also I reprocuce this issue on Linux of redhat 7.9 and ubuntu 20.04

![image](https://user-images.githubusercontent.com/84227812/171198906-c0355b01-e26e-4b66-bbf2-3c397783e173.png)

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! It looks like another maintainer already responded to this issue - maybe this was a duplicate?: https://github.com/electron/electron/issues/34397

Generally speaking, the Electron team doesn't triage issues that involve third-party libraries - we ask that you take the issue to the concerning library itself. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron, there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by PH8919** [comment]
@VerteDinde I have verified the issue using the pure NodeJS Env. The library of 'log4js' can be loaded fastly no matter how many times I execute the script repeatedly. So I think the issue may be related to the electron.
