### ISSUE TITLE
[Bug]: REACT_APP_GOOGLE_API_KEY

### ISSUE THREAD

**Issue by MuhammetAdamoglu** [electron/electron#34421]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.1

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.4 (21F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.1

### Expected Behavior

Electron needs to define REACT_APP_GOOGLE_API_KEY like GOOGLE_API_KEY.

### Actual Behavior

I'm developing ReactJs with Electron and I need to use geolocation. GOOGLE_API_KEY needs to be defined for geolocation, but only REACT_APP_GOOGLE_API_KEY can be defined for ReactJs. This also does not work in electron.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
