### ISSUE TITLE
> Hello,

### ISSUE THREAD

**Issue by Aameen5** [electron/electron#34434]
> Hello,
> 
> Screen sharing is working fine in my electron app. i can see captured screen to another browser using "DesktopCapturerSource" but i want to set border color to the selected screen or window so i can see which screen currently i am sharing to others. we can see in skype or microsoft team or other application like red border to the selected screen while screen sharing something like that i want to make. 
> 
> thanks.

_Originally posted by @Aameen5 in https://github.com/hokein/electron-sample-apps/issues/76#issuecomment-1145937095_

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
