### ISSUE TITLE
[Bug]: electron ignores `--require` in `NODE_OPTIONS` in non-packaged app

### ISSUE THREAD

**Issue by mondaychen** [electron/electron#34470]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

tested on 17.x ~ 19.0

### What operating system are you using?

macOS

### Operating System Version

macOS Montery 12.3.1

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

According to https://www.electronjs.org/docs/latest/api/environment-variables#node_options in non-packaged apps, electron supports majority of `NODE_OPTIONS`. Since `require` is not in "unsupported list", it should be supported.

### Actual Behavior

I got an issue on about react-devtools with Yarn PnP. https://github.com/facebook/react/issues/24682
Yarn PnP needs `--require` in `NODE_OPTIONS` to load correctly. Looks like electron somehow ignores it. Am I missing something?

**Comment by deermichel** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com/) that Electron maintainers can use.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by m-yasir** [comment]
@mondaychen The issue is unclear. What error are you facing?

I have tried reproducing this on my end and looks like `require` is not meant to be used in packaged apps, which Electron Fiddle works with. 

According to [docs](https://www.electronjs.org/docs/latest/api/environment-variables#node_options), only following options are allowed to be used in packaged apps:

```
--max-http-header-size
--http-parser
```

For non-packaged app, it works perfectly fine. I see you are missing quotations for require. Make sure you are setting environment variable correctly. Something like `export NODE_OPTIONS='--require="path/to/file.js"' && npm start`

For more info: [NODE_OPTIONS](https://nodejs.org/api/cli.html#cli_node_options_options)

**Comment by mondaychen** [comment]
In our codebase, we are doing
```
const electron = require('electron');
const result = spawn.sync(electron, [require.resolve('./app')].concat(argv), {
  stdio: 'ignore',
});
```
https://github.com/facebook/react/blob/main/packages/react-devtools/bin.js#L32

Is this use case considered as packaged app or non-packaged app? If this is packaged app, is there a way we can do convert to non-packaged app while keeping the original functionality?
