### ISSUE TITLE
How to disable caching for specific image tag in electronjs?

### ISSUE THREAD

**Issue by kamyabsoft** [electron/electron#34495]
I can disable caching in electron like
`const { app } = require ("electron");
app.commandLine.appendSwitch ("disable-http-cache");`
But this will disable cache in whole app. I dont want this behaviour. I want to disable caching for specific image elemment only but not all image elements

How can I disable cache for specific image in electron?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
