### ISSUE TITLE
Would the electron repl work on windows in a bash shell like Git BASH?

### ISSUE THREAD

**Issue by mcgrue** [electron/electron#34513]
In reference to this line:
https://github.com/electron/electron/blob/bd81ae08acf2a2ebb9f6ca7c17590b472ddae789/default_app/main.ts#L145

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
