### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by yo34** [electron/electron#34527]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

On a my PC, I launch an electron application build for production mode.

Ie, the application use an index.html file instead of running a express localy.

  ```
mainWindow.loadURL(
    !app.isPackaged
      ? process.env.ELECTRON_START_URL
      : url.format({
        pathname: path.join(__dirname, '../index.html'),
        protocol: 'file:',
        slashes: true,
      }));
```
The electron application send the login password on a remote server where passport-local is used.

The documentation https://www.passportjs.org/packages/passport-local/ specifies to redirect the user to /

```
app.post('/login', 
  passport.authenticate('local', { failureRedirect: '/login' }),
  function(req, res) {
    res.redirect('/');
  });
```
But this is not working with an electron production build, ie using an electron app server by index.html

### Proposed Solution

Do you have a documentation that specifies how managing redirection from server or cookies using production mode ?

### Alternatives Considered

same above

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
