### ISSUE TITLE
[Bug]: app exited with code 3221226505, waiting for change to restart it

### ISSUE THREAD

**Issue by thewebmaster509** [electron/electron#34539]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

To print the content

### Actual Behavior

Crash the app

### Additional Information

When i call webContents.print() it crash the app even with callback or not .

**Comment by ckerr** [comment]
I wasn't familiar with that exit code, so FWIW a quick search shows [this discussion](https://github.com/moby/moby/issues/40328) from an unrelated context:

> That code likely is the error code that is returned from the container's process; 3221226505 looks to be a generic "Internal process error" coming from Windows.

Absolutely :+1: on the request for a repro testcase because otherwise we're just stuck guessing on how to trigger this issue; but FWIW this return value is plausible as an exit code from an Electron issue.

**Comment by CodingMoeButa** [comment]
This issue may be the same one as https://github.com/adonisjs/logger/issues/71.
