### ISSUE TITLE
[Bug]: TypeError: A[t][n] is not a constructor     at Object.R (<path>\electron\node_modules\@capacitor-community\electron\dist\core\index.js:1:2349)

### ISSUE THREAD

**Issue by mjaga** [electron/electron#34532]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0

### Expected Behavior

Command : npm run electron:start

 trying to upgrade electron and capacitor. showing below error

### Actual Behavior

```
(node:20412) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
TypeError: A[t][n] is not a constructor
    at Object.R (<path>\electron\node_modules\@capacitor-community\electron\dist\core\index.js:1:2349)
    at ElectronCapacitorApp.init (<path>\electron\build\setup.js:177:20)
    at <path>\electron\build\index.js:43:26

```[18812:0614/023605.377:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled

### Testcase Gist URL

_No response_

### Additional Information

_No response_

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
