### ISSUE TITLE
[Bug]: Inconsistent multi-touch

### ISSUE THREAD

**Issue by ngmartins** [electron/electron#34579]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Ubunto 20.04

### What arch are you using?

x64

### Expected Behavior

Our application uses different multitouch actions. And we use electron to access the app.
When used in Windows everything works as expected. 
We are running a couple of PoCs in 2 different Linux environments (Ubuntu and Alpine). We are using Wayland.
We were expecting the app to work in the same way in Linux-based OSs.

### Actual Behavior

Using Wayland Linux and electron the multitouch actions from `babylon.js` do not work at all. Other multitouch actions work fine.
Using Wayland Linux and chromium all the multitouch actions work as expected.

### Additional Information

[Here is a playground](https://playground.babylonjs.com/#DWPQ9R#1) for `babylon.js`

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

If it is possible to isolate the issue in some way, could you make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. If you can make this kind of test case, please link to it in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by clamm96** [comment]
hello @codebytere 
just created a ticket about the multitouch and Electron. 
[https://github.com/electron/electron/issues/38387](url)
I'm interested if you have a lead.
best
christophe
