### ISSUE TITLE
Instructions to Install Electron Manually?

### ISSUE THREAD

**Issue by lsantich** [electron/electron#34578]
I would like to install Electronv17.4.6 (because I have node 16.13.0), but am running into a certification issue. I believe this is due to my company's firewall, so I am attempting to manually install the package instead of using npm. 

However, the [instructions ](https://www.electronjs.org/docs/latest/tutorial/installation#troubleshooting)to do so are unclear. I have downloaded the Linux version of Electron 17.4.6, but I am not sure what to do after that.

I am still rather new to Linux and am using the CentOS7 build.

If someone could give me a quick How-to, I would really appreciate it.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
