### ISSUE TITLE
Can I create Intel windows binary on Apple Arm M1 machine ?

### ISSUE THREAD

**Issue by renetik** [electron/electron#34595]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I believe not, so is it at last possible to develop it on Apple Arm M1 and then easily just create binary and installer on windows machine ?

### Proposed Solution

Best would be if project can package binaries for all supported platfroms

### Alternatives Considered

.net Avalonia UI 
react.nodegui.org

### Additional Information

I own M1 computer but have job offer to create widows desktop application but I am quite puzzled on how to accomplish that.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
