### ISSUE TITLE
[Bug]: disable-color-correct-rendering flag is not respected

### ISSUE THREAD

**Issue by landersonfigma** [electron/electron#34592]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.2

### What operating system are you using?

macOS

### Operating System Version

11.6.1

### What arch are you using?

x64

### Expected Behavior

Required: disable-color-correct-rendering is enabled and using wide gamut display

In the provided gist, there are 2 div elements on the page. The 1st div's red background should render with wide gamut colors i.e. it should correctly respect the disable-color-correct-rendering flag.

### Actual Behavior

The 1st div's red background renders incorrectly in sRGB (i.e. it seems to disregard the disable-color-correct-rendering flag). 

If only the 1st element is present, its red background does render correctly with wide gamut colors (i.e. it correctly respects the disable-color-correct-rendering flag). There seems to be some interaction between the 2 elements that causes the flag to switch from being respected to not being respected.

### Testcase Gist URL

https://gist.github.com/landersonfigma/10b141139cd97271ac7c1dfb3cd60e44

**Comment by samuelmaddock** [comment]
The [disable_color_correct_rendering.patch](https://github.com/electron/electron/blob/main/patches/chromium/disable_color_correct_rendering.patch)—which is responsible for allowing this functionality—only applies to the OpenGL renderer used by Chromium. This renderer has been deprecated and was actually [removed at the beginning of the month](https://chromium-review.googlesource.com/c/chromium/src/+/3652749) in Chromium upstream.

Chromium has switched to using its Skia renderer instead of the GL renderer sometime last year. To revert to the GL renderer, you can try adding the following code:
```ts
app.commandLine.appendSwitch('disable-features', 'UseSkiaRenderer');
```

This should allow the patch to continue working, likely until the next few major versions of Electron.

cc @poiru This patch will likely need to be reworked onto the Skia renderer.

**Comment by poiru** [comment]
cc @Hans-Halverson

**Comment by landersonfigma** [comment]
Thanks for the quick response. I'm not sure I fully understand what's happening in my example. In my gist, it looks like the disable-color-correct-rendering flag is working when there is only 1 div but not when there are 2. In the version of Electron I'm using, it sounds like both OpenGL and Skia are supported and maybe the OpenGL renderer has been patched to respect the flag but the Skia renderer has not. Is it possible that different renderers are being used e.g. with 1 div, it uses the OpenGL renderer, which respects the flag and renders correctly, but for 2 divs, it switches to Skia (if you know of reasons why that would happen, that would be very informative), which does not respect the flag and renders incorrectly?

**Comment by anonmate** [comment]
Any update on this? It seems like colours aren't rendering correctly still for P3 displays.
