### ISSUE TITLE
[Bug]: App crash using FFI

### ISSUE THREAD

**Issue by Hikai** [electron/electron#34636]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2, OS Build 19044.1766

### What arch are you using?

x64

### Expected Behavior

When the app starts, `Return: 0, Channels: 4` or `Return: null, Channels: 4` should be printed on the console.

### Actual Behavior

When the app starts, a follow text message will be printed on the console.

`[13700:0620/103607.408:ERROR:crashpad_client_win.cc(815)] not connected`

The same crash occurs even if the DLL file is not present.

### Testcase Gist URL

https://gist.github.com/Hikai/9cb8ba526813cf5e6d30be1989738a90

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. If this issue can be generated without this addon, please modify your test to exclude it.

I'm adding the `blocked/need-repro` label for this reason.

Thanks in advance! Your help is appreciated.

**Comment by Hikai** [comment]
Oh, sorry i don't clearly read that.
Then, I'll close my gist for now and write the reproduce code again without third-party libraries and upload it.
Thanks for comment even through you're busy. :)
