### ISSUE TITLE
[Bug]: webContents.startDrag not working for dropping files into Chromium installed as a flatpak

### ISSUE THREAD

**Issue by SevenSystems** [electron/electron#34648]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Pop OS 21.10

### What arch are you using?

x64

### Expected Behavior

When using webContents.startDrag({ file: '/foo/bar/bleh.pdf', icon: ... }), I would expect this to work when dropped into an [input type="file"] (onto the "Choose File..." button) in a Chromium window.

### Actual Behavior

The file dropped into an [input type="file"] is 0 kB and submitting the form doesn't work: DevTools in the target Chromium window report "ERR_FILE_NOT_FOUND". Dropping the file into other apps, file managers etc. does work normally. Also, the NAME of the file is "transmitted" properly. The full path seems to be broken though, which means Chromium can't find it.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by SevenSystems** [comment]
> @SevenSystems can you verify that this does/doesn't reproduce in Chrome itself?

Sorry, I don't have Chrome installed -- but I just tested in Firefox (installed as a package, not flatpak) and it works as expected there too, so the issue is clearly related to flatpak.

**Comment by SevenSystems** [comment]
Might this be related? #30650
