### ISSUE TITLE
[Bug]: Register Electron JS[Windows,Linux and MAC]  Application for tel and callto protocols

### ISSUE THREAD

**Issue by aarati1908** [electron/electron#34700]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.1

### What operating system are you using?

Ubuntu

### Operating System Version

Windows 10, Mac Os, Ubnuntu 18.04.5

### What arch are you using?

x64

### Expected Behavior

Hello,

Our customers want us to develop an app working as click to call. The app is working just fine, but we are encountering problems with that appearing in the "default apps for protocol" menus for callto and tel protocols in OS Windows, Mac & Linux.

Kindly help for this solution.

Regards,
Aarati Joshi

### Actual Behavior

Hello,

Our customers want us to develop an app working as click to call. The app is working just fine, but we are encountering problems with that appearing in the "default apps for protocol" menus for callto and tel protocols in OS Windows, Mac & Linux.

Kindly help for this solution.

Regards,
Aarati Joshi

**Comment by dsanders11** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
