### ISSUE TITLE
[Bug]: Cannot launch ICA file in webview

### ISSUE THREAD

**Issue by GGGav** [electron/electron#34719]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04.5

### What arch are you using?

x64

### Expected Behavior

In a webview when a link to an ICA file is clicked the file is downloaded, saved locally and launched with the correct application.

### Actual Behavior

When the link is clicked a 'Save As' dialog appears.  Manual intervention is required to save the file.  The file is never launched

### Additional Information

How do I get an Electron JS app which is using a webview to save and launch an ICA file?

I am running an Electron JS v18.3.0 on Ubuntu 18.04.5.  It is a simple browser we are hoping to use to view some local web pages - effectively our Intranet.

One page includes links to various Citrix services, each link is an ICA file.  If I click on one of these links I just get a 'Save File' dialog from the OS.

I have Chromium installed on the same box and configured to save and launch the ICA files.  How do I configure the chromium embedded in Electron JS to behave the same way?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
