### ISSUE TITLE
Streaming large chunk of data from main process to renderer

### ISSUE THREAD

**Issue by detronetdip** [electron/electron#34728]
I want to stream a large file(1gb)  from main process to renderer process. The large file is in my system I want to show that file in my renderer process. What is the  efficient way to achieve this ?

**Comment by dsanders11** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
