### ISSUE TITLE
[Bug]: Aspect ratio does not work when resizing through double-clicking on the window border

### ISSUE THREAD

**Issue by Asmedian** [electron/electron#34751]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.21

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

With win.setAspectRatio(960 / 600) and double clicking on the top/bottom window border, stretch the window to 100% either width or height, whichever hits first at the user-specified ratio.

Well, or just add a will-resize event when double clicking on the window border

### Actual Behavior

With win.setAspectRatio(960 / 600) when stretching a window by double clicking on the top/bottom window border, window is stretched without respecting the aspect ratio.

### Testcase Gist URL

https://gist.github.com/6f13592598ff8c43523e3ca468179319

### Additional Information

When the window is stretched by double-clicking on the border, the content of my application breaks and the **will-resize** event does not fire.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Please also add an appropriate title.

**Comment by Asmedian** [comment]
I understand.
Just ran Electron Fiddle and added 1 line:
`mainWindow.setAspectRatio(960 / 600);`
The problem is reproduced.

**Comment by Asmedian** [comment]
Issue exists in version 23.0.0

**Comment by Asmedian** [comment]
bump
