### ISSUE TITLE
How to package an SDK and call each WebView application in the electron application?

### ISSUE THREAD

**Issue by livelyPeng** [electron/electron#34818]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The problem I currently encounter is that there are multiple tabs in the electron project。

Each tab is an independent web application. I want to realize that electron has its own SDK, and then each application can call methods to communicate with electron.

For example, I am a desktop application. Users can develop their own applications. Our desktop provides an entry to display their web pages. We need to provide some SDKs so that these users can call the pop-up, authorization, and other methods of the desktop application

### Proposed Solution

For example, I am a desktop application. Users can develop their own applications. Our desktop provides an entry to display their web pages. We need to provide some SDKs so that these users can call the pop-up, authorization, and other methods of the desktop application

### Alternatives Considered

no

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
