### ISSUE TITLE
[Bug]: ubuntu 22.04 LTS powerMonitor.getSystemIdleTime() returns "0"

### ISSUE THREAD

**Issue by trae-op** [electron/electron#34826]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 22.04 LTS

### What arch are you using?

x64

### Expected Behavior

I expect the `getSystemIdleTime()` function to work as before in the ubuntu 22.04 LTS 

### Actual Behavior

My app uses `powerMonitor.getSystemIdleTime()`. I recently upgraded ubuntu from 18.04.6 to 22.04 LTS and `getSystemIdleTime()` function stopped counting idle time. 
I know works in 20.04.4 LTS too. Doesn't work on the v22.04 LTS

### Testcase Gist URL

https://gist.github.com/trae-op/663bbb53cd75c6485ccd40d36d14a64f

**Comment by codebytere** [comment]
This falls directly to [this function](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/idle/idle.h;l=31?q=CalculateIdleTime&ss=chromium) in Chromium. You should open a https://crbug.com/ identifying this issue, and then we will recieve the fix when upstream addresses it.

**Comment by trae-op** [comment]
> This falls directly to [this function](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/idle/idle.h;l=31?q=CalculateIdleTime&ss=chromium) in Chromium. You should open a https://crbug.com/ identifying this issue, and then we will recieve the fix when upstream addresses it.

I wrote to [https://crbug.com/](url) and they gave me the answer [https://bugs.chromium.org/p/chromium/issues/detail?id=1343535](url)
Need to update latest chrome version #103.0.5060.114

**Comment by kramerc** [comment]
This seems to be a Wayland issue. Chromium currently uses the X11 Ozone platform by default so it's using X11ScreenOzone's [CalculateIdleTime](https://source.chromium.org/chromium/chromium/src/+/main:ui/ozone/platform/x11/x11_screen_ozone.cc;l=170?q=CalculateIdleTime&ss=chromium&start=21) which always returns zero on Wayland because of the lack of an X11 screen saver.

Adding the command flags `--enable-features=UseOzonePlatform --ozone-platform=wayland` will start the Electron app in Wayland and get `powerMonitor.getSystemIdleTime()` working, but on my system running Ubuntu 22.04.1 LTS and GNOME 42.4 I lose the window's title bar and frame.

There is this [bug reported a year ago](https://bugs.chromium.org/p/chromium/issues/detail?id=1150408) about it, and it's because GNOME's Mutter doesn't support server-side decorations with the xdg-decoration protocol. It is [not planned](https://gitlab.gnome.org/GNOME/mutter/-/issues/217) as well. Chrome does have client-side decoration support under Wayland on GNOME, so it looks like Electron might be lacking client-side decoration support on Wayland when `frame` is set to `true` on BrowserWindow.

So there is a workaround, but depending on your Wayland display server, or rather your desktop environment, it probably won't be practical in terms of usability until client-side decorations are available.

**Comment by kramerc** [comment]
I've been looking into this a bit more, and it seems [since Electron 17 support for client-side decorations](https://wiki.archlinux.org/title/Wayland#Command_line_flags) is available with the additional flag `--enable-features=WaylandWindowDecorations`

![image](https://user-images.githubusercontent.com/114056/189541678-ff3b1cc4-a49c-4c59-86d1-b4f958a03cf6.png)

`powerMonitor.getSystemIdleTime()` also appears to work on Electron 17. Most of my initial findings were with trying to get Discord to work under Wayland, which seems to be [stuck on Electron 13](https://theevilskeleton.gitlab.io/2022/05/29/a-letter-to-discord-for-not-supporting-the-linux-desktop.html#determining-the-electron-version-in-use).
