### ISSUE TITLE
How to gracefully increase the width and height of the window dynamically without flickering?

### ISSUE THREAD

**Issue by MoNaiZi** [electron/electron#34869]
At present, I use SetSize setposition to change the window size and move the window, but the window always flashes, and the experience is not very good。
Do you have any good solutions?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
