### ISSUE TITLE
EAGAIN (resource temp. unavailable) error installing electron? (Linux)

### ISSUE THREAD

**Issue by RJVB** [electron/electron#34866]
I'm running into a strange error when projects attempt to install their copy of electron:

```
npm ERR! code 1
npm ERR! path /opt/local/var/tmp/Node/ferdi-git/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c /tmp/postinstall65744835.sh
npm ERR! Error: EAGAIN: resource temporarily unavailable, copyfile '/tmp/electron-download-k58rsD/electron-v15.3.5-linux-x64.zip' -> '~/.cache/electron/5db3cc9a7ad2811d3add012105c4f78da0ec79c6f833fb2d19655c4c8a610ac5/electron-v15.3.5-linux-x64.zip'
```

This currently happens with all versions of Node and npm I've tried, but I can't seem to figure out the underlying reason. Is there a way to make npm/node NOT remove the temp. files of the package that failed to install?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
