### ISSUE TITLE
Child_process sample project

### ISSUE THREAD

**Issue by 1ProCrafters** [electron/electron#35023]
I am having trouble using child process with electron, it just doesn't seem to run it so I was wondering if someone would create a sample project for using child process with electron that returns output in the console of html.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
