### ISSUE TITLE
[Bug]: getMediaAccessStatus returns not-determined if permission was set through script 

### ISSUE THREAD

**Issue by has-n** [electron/electron#35025]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.2.8

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5

### What arch are you using?

x64

### Expected Behavior

I'm setting up CircleCI to run automated tests for my app which uses the microphone. CircleCI runs Mac tests on an image with SIP disabled and injects permissions into the TCC.db. The command is add-permission : [source](https://circleci.com/developer/orbs/orb/circleci/macos )

Using the `list-permissions` command, I am able to confirm that the app does have the correct permission:

`client                            service                   auth_value
--------------------------------  ------------------------  ----------
com.apple.Terminal                kTCCServiceDeveloperTool  0         
/usr/sbin/sshd                    kTCCServiceAppleEvents    2         
/usr/sbin/sshd                    kTCCServiceAppleEvents    2         
/usr/libexec/sshd-keygen-wrapper  kTCCServiceAppleEvents    2         
/usr/libexec/sshd-keygen-wrapper  kTCCServiceAppleEvents    2         
/usr/libexec/sshd-keygen-wrapper  kTCCServiceAccessibility  2         
APP.BUNDLE.IDENTIFIER                 kTCCServiceAll            2         `

When testing for the permission using `systemPreferences.getMediaAccessStatus`, the result is always not-determined.

### Actual Behavior

Call to `systemPreferences.getMediaAccessStatus` should return granted regardless of how the permission was granted - manually by the user or through a script.

**Comment by MarshallOfSound** [comment]
@has-n I can't be as helpful as I'd like here but I can give the following pointers:

* We do similar things on Circle CI but instead of using `add-permission` we directly update the `TCC.db` database (which that command appears to do under the hood anyway so this difference might not matter)
* The TCC sqlite format changed from macOS 10.* -> macOS 11.*, you might want to try older macOS images on Circle and see if they work.  If they do I might be able to provide some SQL syntax that works on newer macOS releases
* After we do the TCC injection we run `sudo killall Dock && sudo killall Finder` which _may_ be important too 😅 

Other than those points there isn't much we can do here, I know it works, and we aren't a support team so all I can do is wish you luck finding the right magic incantation.  Apple doesn't make this easy 😆

**Comment by has-n** [comment]
Thanks @MarshallOfSound . I commiserate your pain. 

Unfortunately these pointers don't seem to work. Separately, the `add-permission` command handles the change from 10.* -> 11.*.

Is there a public project you can point me to? I'm definitely doing something wrong in my setup but can't figure it out despite many sleepless nights :(

**Comment by has-n** [comment]
I think I've been able to further narrow down the issue. We use Playwright to run our e2e tests. When run locally, Playwright launches the app and it is able to request and receive permissions. When Playwright is called by CircleCI, the app is NOT able to request and receive permissions. I can't pinpoint why that may be yet. 

I'll update when I have more.
