### ISSUE TITLE
[Bug]: Unable to load preload script \@capacitor\electron\dist\electron-bridge.js

### ISSUE THREAD

**Issue by meghajayakumar** [electron/electron#35027]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

8.5.5

### Expected Behavior

Just migrated from electron 8.5.5 to 19.0.9 for an electron ionic desktop application project. When trying to open electron window with the command 'npx cap open electron', it should open the electron window.

Implememtation below:
```
mainWindow = new BrowserWindow({
    width: 400,
    height: 700,
    resizable: false,
    title: "App name",
    show: false,
    icon: path.join(__dirname, 'favicon.ico'),
    webPreferences: {
      backgroundThrottling: false,
      nodeIntegration: true,
      preload: path.join(__dirname, 'node_modules', '@capacitor', 'electron', 'dist', 'electron-bridge.js')
    }
  });
```

### Actual Behavior

When opening the electron window with the command 'npx cap open electron', it throws an error: Unable to load preload script: ..electron\node_modules@capacitor\electron\dist\electron-bridge.js
![image](https://user-images.githubusercontent.com/54796878/180453134-a26065f4-a304-4e41-a5a4-94dd16566dfc.png)
![image](https://user-images.githubusercontent.com/54796878/180453153-718e64d4-19cc-4996-bd10-a2221a46dedf.png)

**Comment by VerteDinde** [comment]
Hey @meghajayakumar - there were quite a few breaking changes between Electron 8 and Electron 19. In your specific case, I think you likely need to disable contextIsolation, or refactor your app to use contextIsolation. It was enabled by default in Electron 12 - you can read more about that and view other breaking changes here: https://www.electronjs.org/docs/latest/breaking-changes#default-changed-contextisolation-defaults-to-true

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. I'm going to close this issue, but if you end up needing more help after changing contextIsolation, I'd recommend our [Discord](https://discord.gg/electron) - we have many active help channels and mentors, as well as fellow devs, who can help you out.
