### ISSUE TITLE
Need help building electron with pointer compression disabled

### ISSUE THREAD

**Issue by jssdgit** [electron/electron#35032]
As discussed in https://github.com/electron/electron/issues/31330 V8 pointer compression is enabled by default in electron and that is not going to change.  That issue mentions several times that if one needs to disable it (so as to get at more than 8 GB of memory), all one needs to do is set `v8_enable_pointer_compression = false` (and/or `v8_enable_pointer_compression_shared_cage = false`).

Alas, I am at a complete loss on how to do this.  I have followed the instructions at [https://www.electronjs.org/docs/latest/development/build-instructions-gn](instructions) to build electron, guessing at how and where to set the custom flag.  The binary `electron.exe` that I end up with is still limited to 8 GB of RAM.  Clearly I am guessing wrong.  Unfortunately, I have been unable to locate any instructions on how to set a custom flag like this in the electron build, and so am appealing for help here.  (I would be happy to describe what I've tried so far, but as none of it has worked, I'm not sure how helpful that will be.)

Can someone either point me at detailed instructions or include them here?  Thanks!

**Comment by MarshallOfSound** [comment]
You set GN build flags here --> https://github.com/electron/electron/blob/main/build/args/all.gn

You can also set it via `gn gen` arguments.  If you are building using build tools your `evm.*.json` config file has a block with

```
{
  "gen": {
    "args": [
      ...
    ]
  }
}
```

Where you can also put that flag

**Comment by jssdgit** [comment]
Thanks for the response, but I'm afraid it was not helpful.  I am unable to reopen this bug, but I hope my comment can draw your attention for further assistance.

1. The only "all.gn" file I found was in `$SOURCE_TOP/electron/build/args.gn` - I don't have a `blob/main` directory.  So I put the two flags `v8_enable_pointer_compression = false` and `v8_enable_pointer_compression_shared_cage = false` in there.
2. I then ran `gn gen out/Release --args="import(\"//electron/build/args/release.gn\")"`.  It made 17895 targets from 3080 files.
3. I then ran `ninja -C out/Release electron`.  The only output I saw was:
          `ninja: Entering directory 'out/Release'`
           `[0/1] Regenerating ninja files`
           `[1/137] ACTION //components/resources:about_credits(//build/toolchain/win:win_clang_x64)`
It completed in a few seconds. 

I have no confidence that the changed flags caused anything of importance to rebuild, given that I've observed that it takes a very long time (many minutes) to link electron.exe.  The timestamp of electron.exe was not altered.

What am I missing?  How can I trigger a proper rebuild having added the required parameters to all.gn ?

**Comment by jssdgit** [comment]
I also tried the following:
- Removed all .obj files under `$SOURCE_TOP/out/Release/obj/v8`
- `ninja -C out/Release electron`
This resulted in 1541 files being recompiled and electron.exe linked, but no joy on the memory limit - my test still crashes after 8.3 GB.  So clearly whatever I did to get those flags in did not work.

**Comment by MarshallOfSound** [comment]
```diff
diff --git a/build/args/all.gn b/build/args/all.gn
index f1de439d83..c68ea5b84e 100644
--- a/build/args/all.gn
+++ b/build/args/all.gn
@@ -45,3 +45,5 @@ enable_cet_shadow_stack = false
 # V8 in the browser process.
 # Ref: https://source.chromium.org/chromium/chromium/src/+/45fba672185aae233e75d6ddc81ea1e0b30db050:v8/BUILD.gn;l=281
 is_cfi = false
+
+v8_enable_pointer_compression = false
```

Applying that patch resulted in 13500 recompilations on my build machine 🤷 I'm not entirely sure what you're doing but somehow you're not change that file correctly

**Comment by jssdgit** [comment]
There's a disconnect here.

The only all.gn file I can find is  `$SOURCE_TOP/electron/build/args/all.gn`.  This file is not under git source control on my machine.

I am building under Windows 10, having followed these instructions: 
- [https://www.electronjs.org/docs/latest/development/build-instructions-gn](build1)
- [https://www.electronjs.org/docs/latest/development/build-instructions-windows](build2)

I have not done anything beyond what was instructed.  The commands I've run are
- `$ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron`
- `$ gclient sync --with_branch_heads --with_tags`
- `$ gn gen out/Release --args="import(\"//electron/build/args/release.gn\")"`
- `$ ninja -C out/Release electron`

This produced an electron.exe file that showed the 8.3 GB memory limit.  I then edited `$SOURCE_TOP/electron/build/all.gn` to add the two flags, and repeated the last two commands (`gn` and `ninja`).  As I stated, this did not result in anything being recompiled.

Can you be very specific about exactly which files are being edited and which commands you are running?  As a complete newbie to building electron, I'm obviously not doing something right, but I cannot figure out what I'm missing.  I'm likely getting lost right at the start:  which "all.gn" file I should be editing, since yours is under source control and mine is not.

**Comment by jssdgit** [comment]
I wonder:  Has anyone actually tried building electron with `v8_enable_pointer_compression = false` and actually _confirmed_ that it really works?  That is, tried allocating a typed array that uses more than 8 GB?

Or, for that matter, has anyone in the Chromium project tried building chrome with pointer compression turned off and confirmed that it works?  I'm starting to feel like I'm chasing phantoms here and the switch does not work as advertised.

**Comment by marcelblum** [comment]
@jssdgit FWIW I have arrived at similar unsatisfying results though going a slightly different route to build electron and on a different platform (M1 Macbook Pro). I used the `e` build tool following the instructions [here](https://github.com/electron/build-tools/blob/main/README.md). AFAICT there's no need to overcomplicate and manually run `gn`, `ninja`, etc. if all you want to do is change some build args (I could definitely be wrong though!).

I built off of the main release branch (21.0.0-nightly) doing something along the lines of:

1. `npm i -g @electron/build-tools`
2. `e init main-mod -i release`
3. `e sync`
4. edit `src/electron/build/args/all.gn` to add `v8_enable_pointer_compression = false` and `v8_enable_pointer_compression_shared_cage = false`
5. `e build`

My resulting build did not have the expected altered memory behavior, by which I mean that using my [tests](https://github.com/marcelblum/electron-memory-tests) showed the exact same results as when testing with electron@latest prebuild. @MarshallOfSound if there is something incorrect in my steps above that would result in the pointer compression flags being ignored please let me know.

It should be noted that on the Apple Silicon/macOS 12 arch/platform, the limit in latest electron is around 16GB, not 8GB. I don't know why this is the case, perhaps some platform specific quirks can explain it. On Windows it is very hard limited at 8GB since Electron v14 through to @latest. On Apple Silicon/macOS I was hoping with pointer compression disabled there would be no limit (as with Electron v11 which can go beyond 25+GB on *all* platforms), but my custom build showed the same 16GB limit in place. That said, a 16GB limit is obviously vastly superior to 8GB and much less of an obstacle for Electron development! I wonder if some maintainers can comment as to why that platform has double the memory limit and whether it would be somehow possible to enable this doubled limit on Windows regardless of pointer compression.

In any case, I'll be doing some Windows experiments in the same direction soon and report back. Just happened to have an M1 Mac not being used for much at the moment and with lots of free space so started working on this there. The 100+GBs of disk space and 8+ hours of compile time required is a slight hinderance 😅

**Comment by marcelblum** [comment]
Built electron@nightly on Windows using `e` as described in my last comment with the pointer compression mods to `all.gn` and got the same results, no observable change to memory limit (8GB). So either both @jssdgit and I are doing something wrong and the args are being ignored (seems unlikely?), or `all.gn` is not the right place for these args to be overridden, or disabling pointer compression by itself is not the solution. I wonder is there any way to confirm that the args have been applied correctly in the resulting build so we can troubleshoot whether it's a build/configuration issue or there's a deeper flaw in the thinking around the root cause of this issue?

For now I'm probably going to move on to half-blindly hacking away at `src\v8\BUILD.gn` and see if I can come up with anything meaningful as time permits, there seems to be a lot of juicy relevant stuff in there...

**Comment by marcelblum** [comment]
Relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=1243314

**Comment by marcelblum** [comment]
Ok I did it. Edited [these lines](https://source.chromium.org/chromium/chromium/src/+/main:base/allocator/partition_allocator/partition_alloc_constants.h;drc=0f6d74ba3e875529c58befa9c4eacce94b421254;l=260) to bump up the Windows limit to same as macOS and rebuilt with everything else untouched, including leaving pointer compression enabled, and the Windows limit in my (sandbox off) tests is 16GB. If I run my tests with sandbox on, the 8gb limit is hit regardless of the hardcoded value of `kPoolMaxSize`. AFAICT from various Chromium dev discussions, using Windows' built-in sandboxing methods results in the 8gb limit. I guess Chromium devs figured running with `--no-sandbox` is such an edge case they hardcoded the limit in there regardless of the sandbox status. 🤮 

No idea what the implications might be in terms of stability or any other issues as I haven't done extensive testing yet, but feels like progress, and even better if the solution means not having to touch pointer compression so we get the benefit of leaving that on. 😂 


```diff
$ git diff partition_alloc_constants.h
diff --git a/base/allocator/partition_allocator/partition_alloc_constants.h b/base/allocator/partition_allocator/partition_alloc_constants.h
index 0d0cab2033c88..345bc6dc3f3a8 100644
--- a/base/allocator/partition_allocator/partition_alloc_constants.h
+++ b/base/allocator/partition_allocator/partition_alloc_constants.h
@@ -247,7 +247,7 @@ constexpr size_t kSuperPageBaseMask = ~kSuperPageOffsetMask;
 #if defined(PA_HAS_64_BITS_POINTERS)
 // The Configurable Pool is only available in 64-bit mode
 constexpr size_t kNumPools = 3;
-#if BUILDFLAG(IS_MAC) || BUILDFLAG(IS_LINUX)
+//#if BUILDFLAG(IS_MAC) || BUILDFLAG(IS_LINUX)
 // Special-case macOS. Contrary to other platforms, there is no sandbox limit
 // there, meaning that a single renderer could "happily" consume >8GiB. So the
 // 8GiB pool size is a regression. Make the limit higher on this platform only
@@ -256,9 +256,9 @@ constexpr size_t kNumPools = 3;
 // On Linux, reserving memory is not costly, and we have cases where heaps can
 // grow to more than 8GiB without being a memory leak.
 constexpr size_t kPoolMaxSize = 16 * kGiB;
-#else
-constexpr size_t kPoolMaxSize = 8 * kGiB;
-#endif
+//#else
+//constexpr size_t kPoolMaxSize = 8 * kGiB;
+//#endif
 #else  // defined(PA_HAS_64_BITS_POINTERS)
 constexpr size_t kNumPools = 2;
 constexpr size_t kPoolMaxSize = 4 * kGiB;


```

**Comment by jssdgit** [comment]
My build just completed (10.5 hours).  I can confirm that the changes @marcelblum came up with work for me as well.  Huge relief to know that my company's application can move forward with electron updates given that I can restore our ability to get to 16 GB, albeit with a custom electron build.  A huge "thank you" to @marcelblum - it would have taken me a long time to figure this out myself, if at all.  I am opening a new bug to formally request that the powers that be at electron make this change.

To be clear:  The 8 GB limit in Windows has nothing to do with Pointer Compression - it is a hard coded limit in Chromium that can be changed, and I believe it should for Electron.
