### ISSUE TITLE
[Bug]: Window with transparent option enabled opens twice

### ISSUE THREAD

**Issue by AlexWhiteCorp** [electron/electron#35044]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise, version 21H2, build 19044.1826

### What arch are you using?

x64

### Expected Behavior

On `window.show()` **Window** opens one time and keeps open

### Actual Behavior

On `window.show()` **Window** opens for a while(~100 ms), hides and after this opens again

![bug](https://user-images.githubusercontent.com/47445536/180771265-a962cb92-d47b-4740-ad61-a7039c431251.gif)

### Testcase Gist URL

[Gist](https://gist.github.com/AlexWhiteCorp/cfca84c3f7742954015ba4dab1c4ea8b)

### Additional Information

This bug reproduces only on Windows OS(on MacOS ARM works as expected) and if **transparent** option is enabled. If set `transparent = false` - works as expected

Window is opened on TrayIcon click.

Was found during working on project [WatchDog](https://github.com/AlexWhiteCorp/watchdog) (main branch can be used for reproducing).

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by AlexWhiteCorp** [comment]
@codebytere I've created gist with small testcase and added link to issue description.
Just one note: I haven't find how to upload image to gist, so add this image[logo_black@2x](https://user-images.githubusercontent.com/47445536/181523059-5eba5e82-f4e3-4226-b9d1-cf39d8e5a2e5.png) to project dir after gist will be cloned(it's tray icon)

**Comment by AlexWhiteCorp** [comment]
bump

**Comment by codebytere** [comment]
Tried to reproduce this on both v19 and v23 with the provided gist and image file but couldn't.
