### ISSUE TITLE
[Bug]: npm test returns error

### ISSUE THREAD

**Issue by Hoovi-Official** [electron/electron#35048]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows

### What arch are you using?

x64

### Expected Behavior

I just got done with quick start on the electron web page, and I have the same code from the website but my program returns `Passthrough is not supported, GL is disabled, ANGLE is` about a minute after I try to run `npm test`, which is set to `electron .` I ran all the necessary commands again, `node -v` and `npm -v` both return only the version number. I have also searched and found nothing that would help me.
![image](https://user-images.githubusercontent.com/60634346/180818205-bb5ef2bf-9eb8-46c9-b661-e7b631659474.png)

### Actual Behavior

After running `npm test`, the terminal returns my package name with the version and `electron .` after. After about a minute `[27908:0725/093342.322:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is ` is returned and nothing else happens in the terminal after that. My program wont start on `npm start` either.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
