### ISSUE TITLE
[Bug]: got ERR_FAILED when use net.request after network service restart(crash)

### ISSUE THREAD

**Issue by anyerqi** [electron/electron#35093]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

can use api `net.request` expectedly

### Actual Behavior

got error when use api `net.request` after network restart(crash)
```
Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7068)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (node:domain:152:15)
    at SimpleURLLoaderWrapper.callbackTrampoline (node:internal/async_hooks:128:24)
```

### Additional Information

To repro:
1. start app
2. kill the network service process
3. the network service process will restart automatically
4. use api `net.request` to visit some url
5. will get error

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by liutuoni** [comment]
@codebytere Hi Ms Shelley Vohr. I might meet same problem. I can't send any http request in main process using the net.fetch api. I think it may due to the network utility process crashed at some moment and re-created. But Electron cannot send request anymore.
You can reproduce manually. Kill the net work process first and then You cannot send any request in main process but the network request from renderer process is fine.

**Comment by jayakrishnankp** [comment]
Hi @anyerqi , @liutuoni 
> To repro:
> 1. start app
> 2. kill the network service process
> 3. the network service process will restart automatically
> 4. use api `net.request` to visit some url
> 5. will get error

Were you able to fix this issue? Could you let me know how you were able to kill the network service process?
