### ISSUE TITLE
How to compile electron as a shared library on windows?

### ISSUE THREAD

**Issue by xspeed1989** [electron/electron#35150]
Does someone has any idea?

**Comment by RaisinTen** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed.

For your question, I'd recommend reaching out to @itsananderson. AFAIK, Dropbox uses / used to use electron as a shared library.

**Comment by winsan-zhang** [comment]
> 

Have you solved this problem yet?
