### ISSUE TITLE
[Bug]: can require module in preload script electron20.0.0

### ISSUE THREAD

**Issue by tjx666** [electron/electron#35195]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS montery 12.5

### What arch are you using?

x64

### Last Known Working Electron version

19.0.10

### Expected Behavior

I can load preload script without error

### Actual Behavior

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/41773861/182520626-7d867d11-ac5d-4280-9071-7057fa06ec81.png">

Preload Script code:

![image](https://user-images.githubusercontent.com/41773861/182520667-aee1026d-fe59-4793-92a4-fffe98adeb5f.png)

**Comment by lishulincug** [comment]
I encountered similar problem。
https://github.com/electron/electron/issues/35204

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by JCMais** [comment]
I have the same error.

In my case, I was using a monorepo and the workaround is to make sure all dependencies are in the package's node_modules. If you are using yarn, this can be done by adding:

```
    "installConfig": {
        "hoistingLimits": "dependencies"
    },
```

This is not great tho, as lots of dependencies will be duplicated in the monorepo.

**Comment by Quimy** [comment]
As @lishulincug wrote it is enough to add sandbox: false to webPreferences. But doing this keep in mind possible security issues.

More on sandbox you can read here: https://www.electronjs.org/docs/latest/tutorial/sandbox

**Comment by miniak** [comment]
https://www.electronjs.org/blog/electron-20-0#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default
