### ISSUE TITLE
[Bug]: use contextBridge ，but window.electron is undefined

### ISSUE THREAD

**Issue by lishulincug** [electron/electron#35204]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

v20.0.0-beta-13.0

### Expected Behavior

1、preload use contextBridge

import { contextBridge, ipcRenderer, IpcRendererEvent } from 'electron';
const electronBridge = {
  send: ipcRenderer.send,
  on: function (
    channel: string,
    listener: (event: IpcRendererEvent, ...args: any[]) => void
  ) {
    ipcRenderer.on.apply(ipcRenderer, [channel, listener]);
  }
}
contextBridge.exposeInMainWorld('electron', electronBridge)

2、use window.electron

window.electron.on('topic_list', this.onTopicList)
window.electron.on('topic_message', this.onTopicMessage)
window.electron.send('sub', 'hardware_config')

### Actual Behavior

window.electron is undefined！

![image](https://user-images.githubusercontent.com/13003282/182594028-8baaa415-a005-4e17-b873-eaed3d4d7397.png)

<img width="405" alt="1659525735536_B2EE3E7C-9783-4c3a-B099-DE0427A93D2A" src="https://user-images.githubusercontent.com/13003282/182597316-b75a01a5-a8c0-4fb3-a107-259860d6cc11.png">

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by lishulincug** [comment]
I solved the problem with this，not use sandbox：
![image](https://user-images.githubusercontent.com/13003282/182760379-7612c7bd-aa9e-4cd5-8b8e-a72ee99abaa4.png)

**Comment by ermuxanov** [comment]
bug is comeback

Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.

I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

**Electron Version**
38.4.0

**Node Js**
22.20.0

**What operating system are you using?**
Windows

**Operating System Version**
Windows11

**What arch are you using?**
x64

I installed it as
npm create @quick-start/electron
cd electron-app
npm install
npm run dev

**in renderer**
<img width="797" height="535" alt="Image" src="https://github.com/user-attachments/assets/90c18df2-3e46-4ae8-ba90-ab5da723c7f5" />

**main.js**
<img width="1014" height="982" alt="Image" src="https://github.com/user-attachments/assets/3a2e9758-3f58-4464-943c-fb90a24537ef" />

**preload.js**

<img width="749" height="728" alt="Image" src="https://github.com/user-attachments/assets/7b9d852f-ae36-4e0f-afbc-8d3a02b9b92c" />

**DevTools**
<img width="1454" height="138" alt="Image" src="https://github.com/user-attachments/assets/7c28eddb-14db-47e3-a992-191b16de9ea2" />
