### ISSUE TITLE
[Bug]: WCO maximize button doesn't work in Windows 11 with external monitor

### ISSUE THREAD

**Issue by jediwade** [electron/electron#35245]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.x, 19.x, 20.x, 21-alpha.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro,  Version: 21H2, Build: 22000.832

### What arch are you using?

x64

### Last Known Working Electron version

17.4.11

### Expected Behavior

Clicking Maximize button of BrowserWindow maximizes the BrowserWindow.

### Actual Behavior

In Windows 11, if a BrowserWindow is configured with titleBarOverlay option (set to either true or with object containing color/symbolColor) and titleBarStyle set to "hidden", the maximize button is not clickable.

To rule out my application, I created a new test project following the [Electron Quick Start guide](https://www.electronjs.org/docs/latest/tutorial/quick-start) with only two deviations: including the titleBarStyle and titleBarOverlay options.

I have tried the most recent builds of Electron 18, 19, 20, and 21-alpha.1, and the result is the same for each. It works as expected in the last version of Electron 17.

You can double-click on the region I have set "-webkit-app-region: drag" on and it maximizes the window.

If you leave the mouse hovering over the maximize button for a few seconds, you get the Windows 11 Snap layout menu.

I have tested my app on two different Windows 10 Home computers and works as expected.

### Testcase Gist URL

https://gist.github.com/jediwade/9e1e463b37299e9f244ab242c60d20f6

**Comment by deepak1556** [comment]
Unable to repro the issue with Windows 11 Build: 22000.795, would be good to confirm if the issue is present with preview release Build: 22000.832

**Comment by jediwade** [comment]
@deepak1556 build 22000.832 is what is on my computer right now. Im more than willing to try just about any configuration change as long as it isn't an OS reinstall if there is something you think I should take a look at. I have a Surface Pro 8 connected to a 4K monitor over Thunderbolt. The Surface Pro screen is disabled when connected to my monitor. The monitor is set at 4K resolution and Windows DPI is at 100%.

**Comment by deepak1556** [comment]
@jediwade I left the comment for other maintainers on the team to see if they could repro with the reported OS build since I didnt't test on that version.

Can you clarify if the issue is present when not connected to the external monitor, trying to rule out if this is specific to OS version or display configuration.

**Comment by jediwade** [comment]
@deepak1556 After disconnecting my monitor and using the Surface Pro screen only, the problem went away. After plugging the monitor back in, the maximize button would always work when spawning WCO-configured windows. I closed and re-launched my app and it continued to work every time after the monitor disconnect/reconnect.

**Comment by deepak1556** [comment]
Thanks for confirming, looks like issue is related to particular display setup and not as much related to the OS version. I will update the issue title to reflect it.

As follow-up, can you confirm if the issue happens with PWA as well, to verify:

* Open the following link https://amandabaker.github.io/pwa/windowControlsOverlay-newCSSVars/index.html in either chrome or edge
* Install the application as PWA
* Perform the maximize operation with both single display and external display setup
* Confirm if the issue is present.

**Comment by jediwade** [comment]
@deepak1556 the issue hasn't returned. If I notice it happen again, I will open up the PWA and see if it happens there.
