### ISSUE TITLE
[Feature Request]: Provide builds without the memory cage

### ISSUE THREAD

**Issue by rconde01** [electron/electron#35241]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The introduction of the memory cage presents some problems for my project. I accept that the electron project has decided the tradeoffs are best for most, but now I'm in the position of having to set up and maintain infrastructure to do custom electron builds on linux/mac/windows.

### Proposed Solution

It would be great if the electron project could continue to provide an alternative package stream with pointer compression and sandboxing disabled rather than requiring multiple 3rd parties to implement this themselves.

### Alternatives Considered

The alternative is that we (and other projects like us) all separately need to setup/maintain this infrastructure.

**Comment by RaisinTen** [comment]
> The introduction of the memory cage presents some problems for my project.

Could you explain some of those problems? I was wondering if there is a way to solve those without disabling the memory cage / maintaining alternate builds.

**Comment by VerteDinde** [comment]
Hey @rconde01, we discussed having separate builds for the v8 memory cage and ultimately decided against it. While we get some people may run into limitations with the memory cage, the maintenance costs (both financially and in maintainer time for bug fixing) just didn't make sense. Pointer compression is now a fundamental performance feature of V8; we wanted to stay mapped closely to upstream or we risk running into some gnarly edge cases.

You can read more of the discussion here (this started with pointer compression, but expanded into the memory cage as well): https://github.com/electron/electron/issues/31330#issuecomment-1005262642

I'll leave this issue open for a time to get more input from others, but I think it's unfortunately unlikely that we'll ship two different builds, or move away from the memory cage. If there are other ways we can make this easier for you as an app developer, we're open to hearing them!

**Comment by rconde01** [comment]
I apologize I am ooo this week but I will respond ASAP

**Comment by rconde01** [comment]
First question:
The blog post says:
"ArrayBuffers are counted separately from the rest of the V8 heap, but have their [own limits](https://bugs.chromium.org/p/chromium/issues/detail?id=1243314)"

But [here](https://github.com/electron/electron/issues/31330#issuecomment-1020664617) @nornagon says " I do see experimentally that ArrayBuffer data isn't stored off the heap as I had guessed". So is the blog wrong, or was that comment later retracted. Also, it would be great to extract the details of the various limits for the docs. The dialog at the references chromium [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1243314) is a bit impenetrable.

**Comment by marcelblum** [comment]
@rconde01 that issue #31330 that I opened almost a year ago contains what has become a confusing jumble of (some wrong, some outdated) info gathered over many months, but I can try to answer based on the most recent findings. ArrayBuffer data *is* stored off heap and is not subject to the 4GB pointer compression heap limit. But it is still subject to Chromium platform-specific hardcoded per-process limits as discussed in that Chromium issue. Those limits are currently 16GB for Mac & Linux and 8GB for Windows. It appears that Chromium will be going ahead with raising the Windows limit to 16GB, which will trickle downstream to Electron, however even with that limit increased, as I understand it, Windows will still be limited to 8GB in each renderer process _if sandboxing is on_ (now on by default). In Electron it's easy enough to disable [sandboxing](https://www.electronjs.org/docs/latest/tutorial/sandbox). But if you need >16GB, even if that Chromium change is merged in, as it stands you would still need to build your own Electron to increase/remove the 16GB limit.

**Comment by rconde01** [comment]
Thanks @marcelblum ! We use node integration in the render process, so I think sandboxing must already be disabled there. 16 GB should probably be fine with us if it comes to windows. Then, the main issue is then the pointer sandboxing. We were definitely relying on the capability to wrap an off-heap pointer in an `ArrayBuffer`. I need to study a bit more whether it's critical for us.

**Comment by nkallen** [comment]
Hi, I'm also wrapping my head around this issue. I have lots of 3d mesh data stored off-heap and the memory cage is potentially a big problem for me. I can refactor some but not all of my native code to use Napi allocated buffers, but both the 8gb and 16gb limit are too small.

**Comment by ckerr** [comment]
Since previous maintainer discussions have been against this idea and no maintainer has stepped up to champion the feature in the last month, I'm closing this ticket as per discussion in https://github.com/electron/electron/issues/35241#issuecomment-1209952443

**Comment by ggreco** [comment]
I would never had started using electron years ago if I thought such a limitation can go live.

Sharing memory between the native layer and the javascript world is the only feature electron has that you do not have using other similar frameworks. We will stick with electron 20 until is so obsolete that we will need to decide to fork electron 20 or fork electron-latest disabling `memory cage` (and possibily also `pointer compression`), when you share array buffers between the native world and the javascript world typically you are sharing things like video frames or huge datasets.

Electron is used to build client application most of these security concerns are not useful for a large part of the user base, and for those who runs remote javascript inside electron they should have additional flags like `sandbox: true`, `nodeIntegration: false` to enforce those behaviours...

**Comment by WillAvudim** [comment]
We are in the same boat as the rest of the folks. Our application uses nodeIntegration and we are extremely memory-heavy, loading all sorts of datasets for visualization and running inference on GPUs (we are primarily doing ML). Splitting it explicitly into a back-end and an electron front-end would be an infeasible massive rewrite with no benefits. In fact, in that case it would make more sense to dump Electron entirely and switch to web.

I hope, at the very least, we could get a memory cage-free build from time to time, even if it's once in every few years.

Sticking to version 20 indefinitely for now.

If anyone is aware of a recent electron build without memory caging (and pointer compression), please post a link.

**Comment by nkallen** [comment]
I am waiting to upgrade but my plan eventually is to have two memory zones, a hotter one inside the cage and a colder one outside the cage, copying when necessary. Annoying but not outrageous.

It's funny you mention nodeIntegration because the developers of VSCode mentioned "Blocking Node.js from renderer processes is an encouraged Electron security recommendation and will eventually be the only way of writing Electron applications. " https://code.visualstudio.com/blogs/2022/11/28/vscode-sandbox

If that is in fact true, the only way to access a native module would be over IPC, meaning a high-overhead async API for EVERYTHING. Electron would certainly be a poor technology choice for any application that's not basically a frameless website: wasm and js only. At that point, it would be insane to use Electron for a lot of the things it is currently being used for. It's a shame because, while Electron has its downsides, nothing else has emerged as good replacement for cross-platform native GUI apps.

**Comment by ggreco** [comment]
The only reason we choose electron when designing our architecture was the possibility to hook native code (and share his memory) in the renderer process...
This focus on web-like security in the last two years or so for electron is IMHO out of scope, since most of the users want to run a LOCAL web UI on the application, not some unsafe web site...

If that is the plan (removing node from the renderer) using a native webview widget in a QT application will be as effective as electron... with far less limitations.

**Comment by WillAvudim** [comment]
Resubmitting my request here per Charles' (@ckerr) suggestion:


### Problem Description

It's not uncommon for a desktop computer nowadays to have 64GB memory. There is a large array of desktop applications dealing with ML, image processing, rendering, e.g. displaying financial charts or annotation tools for medical images that require large datasets to be loaded in-memory and accessed for every mouse move (e.g. to display the precomputed inference of the hierachical bayesian network for the selected point in time, which is kept in a multi-gigabyte Float32Array).
Such desktop applications do not benefit from the security context, we run with nodeResolution set to true, in fact, here's the exact config we run with:

```
  const mainWindow = new BrowserWindow({
    width: 2800,
    height: 2000,
    webPreferences: {
      // Electron memory cage is enforced starting with version 21:
      // https://github.com/electron/electron/issues/35241
      preload: path.join(__dirname, "index_preload_njs.js"),
      // preload: "/storage/mono/out/electron/preload.js",
      contextIsolation: false,
      nodeIntegration: true,
      nodeIntegrationInWorker: true,
      nodeIntegrationInSubFrames: true,
      sandbox: false,
      webSecurity: false,
      allowRunningInsecureContent: true,
      additionalArguments: [
        // Most likely doesn't take effect and can be removed.
        "-r",
        "ts-node/register/transpile-only",
      ]
    }
  })
```

There is no user code to run. Obviously, we do not include any hosted 3rd party content. All .js files limited to well-known frameworks (Vue3, react, etc) and vetted before getting incorporated into the code base and referenced directly. We do not benefit from the security benefits that you currently promote, it's simply unnecessary for us, it is the memory that the Renderer can immediately access we are after.

I understand that maintaining such a build, especially with your insane pace of releases (we can only attempt to upgrade every few years, VSCode was behind for several years before they could catch up with you), would waste a lot of time unnecessarily.

### Proposed Solution

Would it be possible to provide an infrequent, e.g. once in 2-3 years, build without memory caging and, if possible, without memory compression?

### Alternatives Considered

There is a thread currently discussing the problem: https://github.com/electron/electron/issues/35241
And, apparently, the top two alternatives considered so far are to switch to the web and drop Electron entirely, or use "a native webview widget in a QT application". Neither can be done without massive rewrites of the application.

### Additional Information

Well, we actually love Electron overall, and we do want to continue using it going forward. Please help us leverage the entire available memory from the Renderer, it's vital to many applications.

**Comment by nkallen** [comment]
That's a relief. He says it was a mistake.

**Comment by ymeine** [comment]
Given the position of the Electron team regarding that topic, it seems that currently there is no other choice than maintaining a build elsewhere.

I wrote in this comment https://github.com/electron/electron/issues/10409#issuecomment-1870164008 how I made a custom build, if anyone was, like me, a bit stuck wondering how to do it.

DISCLAIMER: I can't be sure the generated build has no issues due to the changes, since I haven't had the time to test it a lot (I just tested the `ArrayBuffer` external buffer feature). But if we think about the scope of the change, there shouldn't be any: sandboxing and pointers compression are options in the build, so the code must accommodate opting out of them. Also, it should be something purely internal to V8, so neither Chromium nor Node.js should consider those features are enabled or disabled. But again, I'm not sure of anything, it's just my intuition built over the years through experience.

**Comment by roundsdr** [comment]
I don't know where current bookkeeping of the memory cage issue is happening, but this is still very much a problem for me and my team. 

We have a real-time 3d app that relies on a native node module that uses mmap. It would be _really_ nice for people that have already bought into the Electron ecosystem to not have to re-write or scrap major projects like this

**Comment by JonathanRosado** [comment]
Same boat as everyone else, we have cybersecurity apps that rely on functions such as memory scanning. Copying buffers completely destroys the performance

**Comment by gerhardberger** [comment]
@nkallen and me cooked up builds for electron based on `26.6.9` that has `v8_enable_sandbox=false`, so the memory cage disabled.

feel free to download it for Intel and ARM macOS, x64 Windows and Linux from here: https://github.com/gerhardberger/electron-releases/releases/tag/v26.6.9

based on our testing it works reliably, but let me know if you experience any issues or regressions because of the change

**Comment by CaineWind** [comment]
Hey everyone, I've been working on medical image acquisition and rendering it in Three.js. When I try to pass the data using IPC communication or MessageChannel, it always copies the buffer, causing a delay of about 50–200ms. I also tried using SharedArrayBuffer, but it threw a 'cannot clone' error. Are there any more mature solutions to solve this issue now?

**Comment by sjchao** [comment]
> [@nkallen](https://github.com/nkallen) and me cooked up builds for electron based on `26.6.9` that has `v8_enable_sandbox=false`, so the memory cage disabled.
> 
> feel free to download it for Intel and ARM macOS, x64 Windows and Linux from here: https://github.com/gerhardberger/electron-releases/releases/tag/v26.6.9
> 
> based on our testing it works reliably, but let me know if you experience any issues or regressions because of the change

Can you create a 4GB buffer?
I can do it in node, but can not in electron.
```shell
$ node -p "Buffer.alloc(4*1024*1024*1024)"
<Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 4294967246 more bytes>
```

```shell
$ ELECTRON_RUN_AS_NODE=1 ./node_modules/electron/dist/electron.exe -p "Buffer.alloc(4*1024*1024*1024)"
node:internal/buffer:961
    super(bufferOrLength, byteOffset, length);
    ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:961:5)
    at Function.alloc (node:buffer:395:10)
    at [eval]:1:8
    at runScriptInThisContext (node:internal/vm:209:10)
    at node:internal/process/execution:118:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:101:62)
    at evalScript (node:internal/process/execution:133:3)
```

**Comment by ymeine** [comment]
@sjchao As I wrote in my comment https://github.com/electron/electron/issues/10409#issuecomment-2417414128 (which I already mentioned earlier in this thread), to me it seems that memory cage is driven by 2 variables in the build, not just 1: 

- `enable_sandbox = false`: the sandbox consists in using offsets from the base address of the sandbox instead of using raw pointers, for **safety** reasons. But the sandbox is limited in space: **4GB max**.
- `v8_enable_pointer_compression = false`: pointer compression consists in using 32 bits offsets from a base address (the managed heap address, which can turn out to be the same as the sandbox), for **performance** reasons (so they can use 64 bits values and combine a 32 bits offset with some other information). But 32 bits offsets limit the addressable space to: **4GB max**.

Turns out both features use the same mechanism and have a very similar impact: 

- disabling the sandbox allows addressing space anywhere, so you can wrap external buffers, **outside** the cage
- disabling pointer compression allows addressing more space, **beyond** the cage

So for your use case you will need a build with the two features disabled, not just one.

You can refer to those articles for more information: 

- [The V8 Sandbox](https://v8.dev/blog/sandbox)
- [Pointer Compression in V8](https://v8.dev/blog/pointer-compression)

**Comment by CaineWind** [comment]
I ultimately solved the memory copy problem by using the 'context not isolated' method directly for convenience

**Comment by david-metrica** [comment]
@nkallen @gerhardberger Is there something else needed that wasn't mentioned besides setting "enable_sandbox = false" and 
"v8_enable_pointer_compression = false"?

I was able to compile Electron 40,0-0.1-beta using these flags, however when I try to run my application, I get an unhandled exception and the app won't boot.
The dmp shows an Illegal Access Exception at IndirectBaseHandle IsEmpty (v8-handle-base.h)

It works fine with your 33.2.1  build, unless something has changed, my build doesn't seem to work.

**Comment by david-metrica** [comment]
I can confirm this issue only happens with 40.X.X.
I tried building every version from beta 0 to beta 3 and it happens for all of them.
It works perfectly fine on v39.2.6 built on the same machine with the same flags.

The error I get isn't descriptive at all:

`Unhandled error in main process: Error: ERR_FAILED (-2) loading 'http://localhost:8100'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:83298)
    at finishListener (node:electron/js2c/browser_init:2:83460)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:83847)
    at WebContents.emit (node:events:508:28)
    at WebContents.emit (node:domain:489:12) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'http://localhost:8100'`

I created a bug report to see if there's something we can do.
https://github.com/electron/electron/issues/49199

@nkallen @gerhardberger
