### ISSUE TITLE
[Bug]: Should we remove the renderer.js reference at this stage?

### ISSUE THREAD

**Issue by tjcchen** [electron/electron#35251]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.6

### What arch are you using?

x64

### Last Known Working Electron version

20.0.1

### Expected Behavior

<img width="1425" alt="Screen Shot 2022-08-08 at 3 25 55 PM" src="https://user-images.githubusercontent.com/6133656/183363417-2ee3e037-4e5e-4fbb-9d80-6b5b157dbba4.png">

The `renderer.js` file is not yet showing its meaning and usages, I think we should remove it until we have a formal explanation.

I cannot edit the page, so just file an issue. thanks a lot!

### Actual Behavior

nope, nothing to attach

### Testcase Gist URL

https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by tjcchen** [comment]
Hi @codebytere! Maybe the approach I am proposing the issue is not correct, but I think we should remove the `renderer.js` reference in app starter boilerplate. It will cause readers feel ambiguous about the code snippet.

<img width="1425" alt="Screen Shot 2022-08-08 at 3 25 55 PM" src="https://user-images.githubusercontent.com/6133656/183384100-3b1b9431-ccb4-44c1-9c7a-641e86c5b6c5.png">
