### ISSUE TITLE
Does electron have a Vendoring issue ?

### ISSUE THREAD

**Issue by YaminoYuki** [electron/electron#35257]
Electron is licensed under MIT license which is a permissive one, so we can use it for commercial purposes, without having to provide a source , we need to put the license and copyright notice, but what about the chromium (since electron is using it) ? in the LICENSES.chromium.html file there were mentioned some GPL licenses (copyleft license: for instance Mozilla Personal Security Manager) , also in [wekipedia  ](https://en.wikipedia.org/wiki/Chromium_(web_browser)#cite_note-other_FOSS_licenses-8) it was mentioned that the license is BSD and others: https://web.archive.org/web/20081026150300/http://code.google.com/chromium/terms.html.
So is the "real" license of electron is "MIT" and can I use it without compelling to any copyleft license ?

**Comment by Prinzhorn** [comment]
Basically #34236 ?

**Comment by ckerr** [comment]
disclaimer: IANAL. I'm a maintainer for Electron who has read the relevant licenses and this is my personal interpretation of how the project complies.

> So is the "real" license of electron is "MIT" and can I use it without compelling to any copyleft license ?

Short answer: yes, that's correct.

Longer answer [here](https://github.com/electron/electron/issues/34236#issuecomment-1209637391). Electron is covered by LGPL-2.1 sections 5 and 6. Electron's source is a "work that uses the library". Since Electron satisfies section 6, the Electron project can make releases that "distribute [Electron] under terms of [the project's] choice". And as you've pointed out, that choice is MIT.
