### ISSUE TITLE
[Bug]: electron : The term 'electron' is not recognized as the name of a cmdlet,

### ISSUE THREAD

**Issue by fox-tech0** [electron/electron#35265]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows [Version 10.0.22000.795] (Windows 11)

### What arch are you using?

x64

### Expected Behavior

A window of 500x500 to appear.

### Actual Behavior

```js
electron : The term 'electron' is not recognized as the name of a cmdlet
```

### Testcase Gist URL

https://gist.github.com/fox-tech0/e405400ed6078e2afce15a1c8f231917

**Comment by fox-tech0** [comment]
and yes, I have ran `npm i -g electron`

**Comment by prakrit55** [comment]
In package.json file recheck the script section if there is <h1>{start:electron .}</h1>

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
