### ISSUE TITLE
[Bug]: require("node-red") Opening devtools immediately will fail

### ISSUE THREAD

**Issue by fullmooooon** [electron/electron#35280]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

 20.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Expected Behavior

I added a line of code at the top of `main.js`
```
require("node-red");
```

```
mainWindow.webContents.openDevTools()
```
openDevTools() can work . It's like not adding that line of code `require("node-red");`

### Actual Behavior

if i add `require("node-red");` 
Opening devtool immediately will fail.
No any error output

Unless I change 
```
mainWindow.webContents.openDevTools()
```
to
```
  setTimeout(() => {
    mainWindow.webContents.openDevTools()
  },100)
```

### Testcase Gist URL

https://gist.github.com/fabe81a40b5e0ba6c59a947fde9f2dfe

### Additional Information

This is very confusing. If I require a package, devtools will cannot be opened immediately

**Comment by vloddot** [comment]
I’m pretty sure this isn’t a bug because I think `node-red` is doing something asynchronous blocking the window from loading.

**Comment by fullmooooon** [comment]
> I’m pretty sure this isn’t a bug because I think `node-red` is doing something asynchronous blocking the window from loading.
> 
> Edit: does this happen with every package or just `node-red`?

i try
```
require('lodash');
require('dayjs')
require('express')
```
no this problem

`node-red` is special, but I have no ability to understand the source code

so ` mainWindow.webContents.openDevTools()` electron just try to open devtools, if fail no error output and can't set error callback

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. Since this issue involves triaging a third-party dependency that isn't specific to Electron, I'm going to close this out. However, for most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by fullmooooon** [comment]
@vloddot @VerteDinde 
I think I know why openDevTools fail
The correct way is:
```
  mainWindow.on("ready-to-show", () => {
    if (!mainWindow) {
      throw new Error("mainWindow is not defined");
    }
    mainWindow.webContents.openDevTools();
  });
```

[electron-quick-start](https://github.com/electron/electron-quick-start)
The code example in `electron-quick-start` is unstable
https://github.com/electron/electron-quick-start/blob/master/main.js
```
mainWindow.webContents.openDevTools()
```
The example in `electron-quick-start` may not always successfully open devtools
