### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IamZiroToxic** [electron/electron#35300]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2 

### What arch are you using?

x64

### Expected Behavior

When i use animation any animation i mean in CSS and JS CSS animation: bla bla and js is Anime library
In CSS 
`@keyframes OnAppOpen {
  0%{transform: scale(0);}
  100%{transform: scale(1);}
}`
`animation: OnAppOpen .5s forwards;`
In JS
`anime({
    targets: '#MainFrame',
    scale: [0, 1],
    duration: 450,
    easing: 'easeInOutQuad'
});`

when I use them -webkit-app-region does not work but when I not use it fix please fix that

### Actual Behavior

when i use animation -webkit-app-region must work

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
