### ISSUE TITLE
[Bug]: Electron Crash, when Windows use mobaxterm(X11) connect Linux, run Electron and quick click menu many times then crash

### ISSUE THREAD

**Issue by acklj1** [electron/electron#35315]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

Other Linux

### Operating System Version

centos7

### What arch are you using?

x64

### Last Known Working Electron version

20.0.2

### Expected Behavior

electron run normal

### Actual Behavior

use  electron-quick-start (Electron official code https://github.com/electron/electron-quick-start), and all my electron project are same

in windows10, I use mobaxterm, connect to my linux(centos7), with X11

when the Electron View display, I quick click the menu many times(example: click menu View, click menu window, click menu View, click menu Window, click menu ...........), and then app crash

![image](https://user-images.githubusercontent.com/18612941/184295926-2bdc4948-84ee-4628-85cf-addd7e7e93ca.png)

### Testcase Gist URL

https://gist.github.com/acklj1/328247c0d809f3e24a648bcc62481a87

### Additional Information

Please solve it. Thank you

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests. Linking quick-start with no changes is not sufficient.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by acklj1** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests. Linking quick-start with no changes is not sufficient.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

I use code from https://github.com/electron/electron-quick-start
No change at all

Environment: code deploy to Linux(centos7), then in windows10 I use mobaxterm to connect Linux and run project
then quick click menu, project crash

**Comment by acklj1** [comment]
???
https://gist.github.com/acklj1/328247c0d809f3e24a648bcc62481a87
