### ISSUE TITLE
Accessing Virtual Camera on MacOS without com.apple.security.cs.disable-library-validation entitlement

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#35313]
Hi,

Since the hardening of the mac apps, we need to include `com.apple.security.cs.disable-library-validation`  in the entitlements.plist to access virtual camera in an webrtc application.

So my question is, if we remove the above entitlement, is there a way to access virtual cameras in a webrtc call?

The mac OS api has exposed a new method for the same https://developer.apple.com/documentation/coremediaio/cmioextensionprovider but unsure of how to exactly use it within the electron app.

Any info/help is appreciated.

**Comment by RaisinTen** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

---

You might find https://stackoverflow.com/a/72552064 helpful ;)
