### ISSUE TITLE
[Feature Request]: Add proper usage examples to the functions removed with the remote module

### ISSUE THREAD

**Issue by aleksey-hoffman** [electron/electron#35335]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hey guys. Since remote module was deprecated, no one knows what you're supposed to do with the functions that this  module was providing.

See my [Stackoverflow post](https://stackoverflow.com/questions/73354435/electron-js-how-to-get-current-window-without-using-remote-module) as an example:

How do you get the current window in the renderer?

I tried passing the BrowserWindow object of the renderer itself into the IPC call, but it throws the serialization error:
```js
windows.computeWindow.webContents.send('compute-size', {
  data, 
  window: windows.computeWindow
})
```

### Proposed Solution

Add proper examples

### Alternatives Considered

N/A

**Comment by MarshallOfSound** [comment]
> How do you get the current window in the renderer?

By design this is not supposed to be easy / possible.  It is a massive security issue to just blindly provide the renderer with the entire `BrowserWindow` API.  Per our other documentation and examples your goal should be to provide minimal and scoped IPC access to specific APIs.

E.g. If you need to be able to minimize the window from the renderer

```js
ipcMain.on('plz-minimize', (e) => {
  if (!validate(e.senderFrame)) return;

  e.sender.minimize();
});
```

```js
ipcRenderer.send('plz-minimize')
```

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by aleksey-hoffman** [comment]
@MarshallOfSound thanks for the clarification, mate, that cleared it up for me
