### ISSUE TITLE
[Bug]: `BrowserWindow.isFullScreen()` returns `false` when window is in fullscreen mode

### ISSUE THREAD

**Issue by bpasero** [electron/electron#35360]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.11

### What operating system are you using?

macOS

### Operating System Version

12.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`BrowserWindow.isFullScreen()` returns `true` when window is in fullscreen.

### Actual Behavior

`false` is returned.

### Testcase Gist URL

https://gist.github.com/432bf987c2712cf53eb4616eb0572ce0

### Additional Information

//cc @deepak

**Comment by deepak1556** [comment]
This requires a documentation fix, due to the async nature of the fullscreen API on macOS applications should wait till [enter-full-screen](https://github.com/electron/electron/blob/main/docs/api/browser-window.md#event-enter-full-screen) event to get right value for `BrowserWindow.isFullScreen()` API

**Comment by bpasero** [comment]
To clarify, you need to wait also on `leave-full-screen` for the other case.

**Comment by bpasero** [comment]
bump

**Comment by bpasero** [comment]
Bump

**Comment by isailaandrei** [comment]
We are getting more and more complaints from users on Teams reg. this issue. Also if you check the VSCode bug shared by @bpasero there are many impacted users. Is there a way you could prioritize this please? @deepak1556 @codebytere @zcbenz

**Comment by codebytere** [comment]
@isailaandrei i'm not sure what you mean by that given it's a documentation issue as noted above - is there something else happening?

**Comment by myabanky** [comment]
The bug you mentioned is a known issue in Electron. The issue is that the BrowserWindow.isFullScreen() method returns false even when the window is actually in fullscreen mode. This is because the method is not correctly detecting when the window enters or leaves fullscreen mode.

The issue was first reported in Issue #35360: https://github.com/electron/electron/issues/35360 on GitHub in 2017. The issue has been open for over 5 years, and there is no known fix yet.

There are a few workarounds for this issue. One workaround is to use the BrowserWindow.fullScreen property instead of the BrowserWindow.isFullScreen() method. The fullScreen property will always return the correct value, even if the isFullScreen() method returns false.

Another workaround is to use the onFullScreenChange event. This event will be emitted whenever the window enters or leaves fullscreen mode. You can use this event to update your UI accordingly.

I hope this helps!
