### ISSUE TITLE
[Bug]: Electron fails to start on non-English OS

### ISSUE THREAD

**Issue by herrjemand** [electron/electron#35453]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

10.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The app to open

### Actual Behavior

The app crashes with error

### Additional Information

Persistent issue on Russia, Ukrainian, Japanese, Chinese, and Korean language.
![184306772-05f8d897-7058-4bb1-b745-8c0058e4e78b](https://user-images.githubusercontent.com/1636116/186642630-fa59c95b-de3f-4d69-89af-53ca93947563.png)

Ref https://github.com/fido-alliance/conformance-test-tools-resources/issues/683

**Comment by zcbenz** [comment]
Sorry but we are unable to look into bugs of ancient versions.

From the screenshot the app is not able to started because the execution of `net session` command failed, Electron never runs it so it must be in your app's code or in some third party modules. I suggest finding out which module executes the command and report the issue to the related project instead.
