### ISSUE TITLE
[Bug]: Content reload on ipcMain.on

### ISSUE THREAD

**Issue by mixon00** [electron/electron#35521]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5.1

### What arch are you using?

x64

### Expected Behavior

ipcMain.on should receive the message from ipcRenderer.send and execute the callback function

### Actual Behavior

ipcMain.on receives the message from ipcRenderer.send, runs the callback function, and reloads the entire contents of the window. All application state resets.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by mixon00** [comment]
I found a solution to the problem. The cause was my mistake.
Inside electron, I have a react application.  After receiving the message in ipcMain.on, I wanted to save the file in the `public` folder, which caused a hot reload of the react application.
