### ISSUE TITLE
[Bug]: Missing audio device after restart of Pulseaudio or Pipewire-Pulse

### ISSUE THREAD

**Issue by toby63** [electron/electron#35577]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro Linux

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Electron should be able to handle a restart of Pulseaudio.

### Actual Behavior

No audio device is visible in the pulseaudio tray and sound can't be played.

There also seems to be stuttering and hanging of the application.

### Additional Information

I use [FreeTube](https://github.com/FreeTubeApp/FreeTube), but I am quite sure that it is an electron problem.

I also use KDE plasma on Wayland with an Nvidia GPU, if that is somehow of interest.

**Comment by toby63** [comment]
Could be related to #26735.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by toby63** [comment]
I can take a look at that, but I think this should be quite easy to reproduce, if it is a problem with electron.

I assume that you might have a standard example application for video and audio functionality and then you can restart the pulseaudio (or pipewire-pulse) service on a Linux system and see whether Electron still works and plays video and audio correctly.
I also experience problems (long buffering, stuttering etc.) once I restart FreeTube (Electron), so something must be triggered that makes problems even after restarting the application.
