### ISSUE TITLE
Numpad not working

### ISSUE THREAD

**Issue by liar666** [electron/electron#35639]
Hi,

In both Chromium and VSCodium, hitting keys on my numpad result in nothing beeing inserted (apart for a few keys, like 6). It does not work even when I enable/disable the numap with the "verr. num" (sorry if it's only the French name?) key.

Numpad works perfectly in all other applications.

Xev shows that KP_xxx keysym is reported when a numpad key is hit.

My intuition is that Electron/Chromium does not interpret correctly the keyboard, either because it reads the low level signal (keycode) instead of the high level (keysym) or because it just does not read it at all.

This is very limiting.

**Comment by ckerr** [comment]
Hey @liar666,

Thanks for reporting this, but it looks like you accidentally skipped the bug report issue template. Any maintainer who wants to confirm this bug report is going to have to guess what platform you're on, what version of Electron you're using, and so on.

Please add the requested info so that maintainers won't have to guess! :smile_cat: The template's text is found at https://github.com/electron/electron/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️
