### ISSUE TITLE
[Feature Request]: Different contextMenu options depending on element right-clicked

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#35632]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There's no viable way to customize the contextMenu on a per-element clicked basis and there's no possible workaround with the current system as an communication to detect the clicked element must originate from the `main` process like:

### Proposed Solution

Include clicked element `nodeName` and/or `id` and/or `classList` in the information sent to Main on `contextmenu` so that Main can decide whether the condition is met.

### Alternatives Considered

So many things, and not one of them can work. Only [one](https://stackoverflow.com/a/62746840) or [two](https://github.com/angrykoala/gaucho/blob/master/src/app/api/context_menu.js) methods are even possible when using `remote` and `nodeIntegration: true`, which it is not our desire to re-enable - and re-enabling `remote` is not even possible.

I've wasted days on this and am not one inch closer to a solution. The only "solution" I can think of is not to use `contextmenu` and instead build a fake contextmenu in-Renderer, as Discord does - which puts an absolutely enormous burden on end users equivalent to weeks of work. It could be easily solved by the proposed solution in a structured-clone-compliant way.

As far as attempts to make `contextmenu` aware of the clicked elements, here's one thing I tried:
1. Main receives `contextmenu` trigger
2. Main sends clicked `x/y` to Renderer to get the DOM node from the position
3. Renderer determines in DOM node meets condition
4. Renderer informs Main of whether condition is met
5. **But** main has already fired `contextmenu` and it cannot be delayed, so there seems no possible workaround whatsoever

I also tried to set the node via `ipc` from the Renderer to always be up to date for when `contextmenu` is triggered, but this can't work either because `contextmenu` fires milliseconds before the `ipc` update notifies Main of the focused DOM node - a race `contextmenu` always wins.

### Additional Information

This is a common issue that has long been unaddressed.

- https://github.com/sindresorhus/electron-context-menu/issues/30
- https://github.com/sindresorhus/electron-context-menu/issues/49
- https://stackoverflow.com/questions/62745948/electron-dynamic-context-menu
- https://stackoverflow.com/questions/43934593/atom-electron-webview-contextmenu-get-click-target
- https://github.com/electron/electron/issues/12633#issuecomment-382910148

I saw in #12633 that the code is not able to handle this dynamic changing of text - but it is absolutely manageable by end users **_IF_** Electron will provide one or all of the properties I've mentioned in my proposed solution - and I expect it would only require minor modifications to implement that.

**Comment by MarshallOfSound** [comment]
It isn't that we don't _want_ to do this, it's that we can't really even consider it because blink itself does not expose this information.

Ref: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/context_menu_data/untrustworthy_context_menu_params.h;l=124;drc=2c16971ca8beb611f33b2abbd321838e956b792a;bpv=1;bpt=1

There is no reliable way for us to generate this information, you're best bet is to handle right-click events yourself in the renderer process and call `e.preventDefault()` to prevent the `context-menu` event.  Then via IPC show your context menu at the coordinates the `right-click` event came from 🤷

**Comment by Prinzhorn** [comment]
I've written my own system that allows arbitrary hierarchical context menus on any element. It also transparently handles clicking of the items via `CustomEvent`, so that for my Svelte component this just looks like every other function. It works with sandbox and without context isolation. The main trick is `executeJavaScriptInIsolatedWorld` + `document.elementFromPoint(x, y)` (and some `target.closest('[data-context-menu]')`). So it does the reverse of what @MarshallOfSound suggested and `main` pulls the data inside `'context-menu'` via `executeJavaScriptInIsolatedWorld` instead of pushing it from the renderer via ipc.

**Comment by danielhaim1** [comment]
Thanks for sharing this. I’m also working on a similar feature and found this ticket valuable. Have you made any recent progress or found additional solutions since your last update?
