### ISSUE TITLE
[Bug]: print-js can not print pdf file on the Electron

### ISSUE THREAD

**Issue by hy999** [electron/electron#35652]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Windows

### Operating System Version

window11

### What arch are you using?

x64

### Last Known Working Electron version

none

## Install the print-js

`npm install print-js@latest --save-dev`

## Import print-js

`import printJs from 'print-js'`

## Print the pdf

```
<template>
<el-button @click="Print()">Print Test</el-button>
</template>
<script setup lang="ts">
   const Print=async ()=>{
      printJS({
         printable:"this is base64 str or pdf url",
        type: 'pdf',
        base64: true
     })
}
</script>
```
 
## result
It  used on the webbrowner,but not actived on Electron

## Install the print-js

`npm install print-js@latest --save-dev`

## Import print-js

`import printJs from 'print-js'`

## Print the pdf

```
<template>
<el-button @click="Print()">Print Test</el-button>
</template>
<script setup lang="ts">
   const Print=async ()=>{
      printJS({
         printable:"this is base64 str or pdf url",
        type: 'pdf',
        base64: true
     })
}
</script>
```
 
## result
It used on the webbrowner,but not actived on Electron

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Is this an issue that you could file with the `print-js` team?

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
