### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aleqsss** [electron/electron#35673]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

13.2.0

### Expected Behavior

Cypress version `8.6.0` to work with our self-hosted agents when running on the Electron browser.

### Actual Behavior

We're using [Cypress](https://www.cypress.io/) to do some testing. We run the tests on a self-hosted Azure Pipelines agent and up until version `8.6.0` of Cypress it works fine. From Cypress version `8.6.0` and above, we get errors.

If we run it on [Microsoft-Hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) (Ubuntu 20.04), Cypress version `8.6.0` and above works fine.

The OS image which we use for our self-hosted agents are generated from the exact same source as the Microsoft-Hosted ones:
https://github.com/actions/runner-images

Our self-hosted even use the same type of hardware as the Microsoft-Hosted ones.

We also have this discussion with one of the maintainers of the Microsoft-Hosted and the image:
https://github.com/actions/runner-images/discussions/6135

In which he concludes as of why Cypress version `8.6.0` works in the Microsoft-Hosted environemnt but not in our self-hosted,
is that the Microsoft-Hosted environment is running the agent as a systemd service, so in a non-interactive mode, whilst our is running in an interactive mode. See here:
https://github.com/actions/runner-images/discussions/6135#discussioncomment-3583568

If I look at the release notes of version [8.6.0](https://docs.cypress.io/guides/references/changelog#8-6-0) of Cypress, I can see that they've upgraded electron from **13.2.0** to **14.1.0** and this is when it stops working for us. So a question here, is there any change here that you're aware of, that would make this not work from our self-hosted agents but still working from the Microsoft-Hosted ones, with the only difference which I'm aware of at the moment, being that our self-hosted are being run from an interactive shell, and the Microsoft-Hosted ones from a non-interactive?

**Comment by ckerr** [comment]
https://github.com/electron/electron/blob/main/docs/breaking-changes.md has a list of breaking changes that can affect projects using Electron when they upgrade major versions.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. You might want to check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
