### ISSUE TITLE
[Feature Request]: How to use command in production environment

### ISSUE THREAD

**Issue by yiqianglin** [electron/electron#35706]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to use npm command. such as "rollup", "sdep" in production environment, because i want to build a front-end development environment in electron；

I added rollup and other dependencies into packages.json, and i use child_process.exec("rollup xxxxxx") in production environment  to rollup my file, i got error: [No such command: rollup] or [No such command: sdep] ; 

How can i solve the problem？

### Proposed Solution

i want to use rollup and other npm command in production environment by using node exec；

### Alternatives Considered

-

**Comment by Prinzhorn** [comment]
> How can i solve the problem？

This is not an Electron problem and nothing that can be fixed on Electron's end. You can checkout the Discord or ask this question on StackOverflow https://www.electronjs.org/community

Hint: you cannot expect binaries such as `rollup` to be magically available on the machines you install your Electron app on. Usually these CLIs come with JavaScript APIs as well, that you can use in your code https://rollupjs.org/guide/en/#javascript-api . That would be much easier than working with the commands across multiple platforms and systems.

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
