### ISSUE TITLE
Get HD icons of desktop files

### ISSUE THREAD

**Issue by fanchenio** [electron/electron#35717]
The icon obtained by app.getFlieIcon is not clear, how to get the high-definition icon of a certain file

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! We ask that all reporters fill out our issue template, so we have the information we might need to debug this without asking as many follow ups. However, I think this specific question is less a bug within Electron, and more specific to your project. 

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron, there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
