### ISSUE TITLE
sync  clipboard  two  computer

### ISSUE THREAD

**Issue by samantrader** [electron/electron#35712]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

how can   sync  clipboard  with  any  format ( inside)   between  two   pc  computer  (windows)  with  electron  app

example :
in the    first  pc      copy   file      and      in    second  pc    can  paste  that  file     (via   server )

### Proposed Solution

no solution

### Alternatives Considered

donot

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
