### ISSUE TITLE
[ASK] exec package from node_modules inside electron application

### ISSUE THREAD

**Issue by DELEPaps** [electron/electron#35727]
I use electron-forge

I added webdriverio to be executed in electron
```
// ipc

ipcMain.handle('test', () => {
    exec('npm run wdio')
})
```

when in development it runs fine `npm run start`, (which I know) because it gets executed in the path when running `npm run start`

but after I build using `npm run package` it shows error `/bin/sh: wdio: No such file or directory`

The question:
how can i execute `wdio` inside electron application

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
