### ISSUE TITLE
this  code  donot  work for  me   why  ?  and  paste item  on  windows   context menu  donot enable

### ISSUE THREAD

**Issue by samantrader** [electron/electron#35721]
this  code  donot  work for  me   why  ?  and  paste item  on  windows   context menu  donot enable 

clipboard.writeBuffer('public.file-url', Buffer.from(`file://${encodeURI(filepath)}`, 'utf-8'));

_Originally posted by @samantrader in https://github.com/electron/electron/issues/9035#issuecomment-1250664747_

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
