### ISSUE TITLE
Debugging published App

### ISSUE THREAD

**Issue by timepp** [electron/electron#35738]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi Electron,

We sometimes need to investigate issue on customer's device, which is a published App that we cannot open debug console there. How can we debug in this case? We do not need readable javascript code: as we are familiar with the logic, setting debug point and monitor traffic should be enough.

Also, if this is not possible, how can I do small change directly in code cache and make Electron still believe that code cache is up to date? I think there should be somewhere to verify file hash and I need to update new file hash there but If the file hashes are get from cloud every time then that seems impossible.

Thanks for your advice!!

### Proposed Solution

Some advice (or document) needed.

### Alternatives Considered

no.

**Comment by lucasrabiec** [comment]
Maybe https://github.com/bytedance/debugtron will be helpful.

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
