### ISSUE TITLE
Electron +React Api consumption failure

### ISSUE THREAD

**Issue by bjjumba** [electron/electron#35798]
Hello ,am new to electron, but was developing a desktop application with electron and react(inside electron +webpack)
i failed to consume restapis

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
