### ISSUE TITLE
[Bug]: preload.js, method in class instance does not exist

### ISSUE THREAD

**Issue by lanten** [electron/electron#35832]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

macOS

### Operating System Version

12.6

### What arch are you using?

x64

### Last Known Working Electron version

20.0.2

### Expected Behavior

- method exist

### Actual Behavior

- method not exist

### Additional Information

prelod.js:

```js
import { contextBridge } from 'electron'

class Test {
  value = 'v1'
  public method() {
    return 'ok'
  }
}

const preload = {
  test: new Test(),
}

contextBridge.exposeInMainWorld('preload', preload)
```

BrowserWindow:
```js
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      sandbox: false,
      preload: process.env.PRELOAD_PATH,
    },
  })
```

result:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/16203518/192491181-3570d9f0-852b-4391-ab95-555b3eec061c.png">

where my method?

Is this a security policy? 

I didn't find any instructions in the [documentation](https://www.electronjs.org/docs/latest/tutorial/tutorial-preload)

**Comment by Prinzhorn** [comment]
See table of how things are cloned, you cannot use a class in this way https://www.electronjs.org/docs/latest/api/context-bridge#parameter--error--return-type-support

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
