### ISSUE TITLE
[Bug]: How to set startup parameters when electron is turned on and use it when it is turned on for the second time，function second-instance 

### ISSUE THREAD

**Issue by shencaobo** [electron/electron#35858]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Expected Behavior

i want to receive data with double url like
[
"electron.exe",
"--allow-file-access-from-files",
"https://github.com/1",
"https://github.com/2",
"3"
]

But he needs extra parameter --
How can I add parameter -- by default in my program, not when it is called externally

I tried below method but it didn't work

const args = []
args.push('--')
app.setAsDefaultProtocolClient(PROTOCOL, process.execPath, args)

### Actual Behavior

https://github.com/electron/electron/issues/34195

### Additional Information

Is there a pre-configured

**Comment by shencaobo** [comment]
And I can't do it by  electron.lnk   ，Is there any way to implement it through code

**Comment by RoyalBob** [comment]
I have the same problem.Is there a solution?

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
