### ISSUE TITLE
[Bug]: DownloadItem.getFileName returns wrong filename when using accents on MacOS

### ISSUE THREAD

**Issue by gnujeremie** [electron/electron#35935]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20

### What operating system are you using?

macOS

### Operating System Version

12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When downloading a file with accent in its name, the name of the file saved on disk should not be altered.

### Actual Behavior

On MacOS, words with accents are removed, and I loose the file extension in the name.

'Inventaire troisième trimestre Agence Santé.csv' becomes 'Inventaire  trimestre Agence Pulse_'

### Additional Information

Using electron 20, on MacOS (12.4) the following code does not work as expected :

```
 this._win.webContents.session.on('will-download', (event, item, webContents) => {
            try {
                const itemUrl = decodeURIComponent(item.getURLChain()[0] || item.getURL());
                const queueItemIdx = this.downloadQueue.findIndex(e => e.url === itemUrl);
                const queueItem = this.downloadQueue[queueItemIdx];
                this.downloadQueue.splice(queueItemIdx, 1);

                // getFileName() should return 'Inventaire troisième trimestre Agence Santé.csv' (it works on Windows) but on MacOS
                // I get 'Inventaire  trimestre Agence Pulse_'
                const filePath = path.join(this._downloadPath, item.getFilename().split(/[?#]/)[0]);
            
                item.setSavePath(filePath);j
       ...
});
```

It works fine on windows.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by gnujeremie** [comment]
Thanks, I'll try to reproduce the error using Electron  Fiddle.

**Comment by gnujeremie** [comment]
Ok so here is the link to the fiddle : https://gist.github.com/184ecb3c364b17d7936c646a6326b550

You will just need a small nodejs server : 
```
const http = require('http');

const requestListener = function (req, res) {
    console.log('Passe');
    res.writeHead(200, {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': 'attachment; filename="export-troisième-trimestre-export-inventaire.csv"'
    });

    let header = [
        '"Référence"',
        '"Nom"',
        '"Quantité avant inventaire"',
        '"Quantité inventoriée"',
        '"Prix d\'achat total"',
        '"Prix de revient total"',
        '"Prix de revient unitaire"',
        '"Fournisseur(s)"',
        '"Utilisateur"'
    ];

    // Ajoute le BOM pour encodage
    res.write("\ufeff" + header.join(';') + "\n", "utf-8");
    res.end('');

}

const server = http.createServer(requestListener);
server.listen(8080);
```

In the fiddle, item.getFilename() returns "download.csv" and I don't know why, in my case it is the name specified in the "Content-Disposition" option. Anyway, the item.getContentDisposition() displays the encoding error : 

```
attachment; filename="export-troisi�me-trimestre-export-inventaire.csv"
```

When the file is saved on disk with the name from the Content-Disposition, it is then altered.

**Comment by clavin** [comment]
Salut @gnujeremie, merci d'avoir signalé ce problème! 🙇  (I'm still learning French, so I'll leave my attempt to just that.)

I've been investigating this issue for the past couple weeks, navigating all the way up the networking stack in Chromium, even to the most basic parts like [HTTP transactions](https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_transaction.h) and the [HTTP stream parser](https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_stream_parser.cc). Every step of the way, I found that the header value contained that [Unicode Replacement Character "�"](https://unicode-table.com/en/FFFD/).

After taking a step back, I tried looking at the response I was getting from a slimmed down version (text instead of csv) of your Node.js server in curl:

```shell
$ curl -i -XGET 'http://localhost:8080'

HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Disposition: attachment; filename="troisi�me ans.txt"
Date: Tue, 29 Nov 2022 20:30:06 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

c'est le troisième ans
```

The Node.js server is sending the faulty value! With a little more research, I found that UTF-8 values in HTTP headers is a [tricky situation](https://github.com/nodejs/llhttp/issues/126) and some server applications choose to erase them to avoid possible security issues. That is to say, attempting to put unicode-formatted text in an HTTP header is invalid per the spec (even though browsers do sometimes understand it) and might even be a security risk in certain scenarios.

I was able to verify this by changing the server to use a more barebones transport:

```js
import * as net from "node:net";

// 🚧 for example purposes only! 🚧
// ⛔️ this is the wrong way of accomplishing this! do not do this in real code! ⛔️
net
  .createServer((socket) => {
    socket.write(
      "HTTP/1.1 200 OK\n" +
        "Content-Type: text/plain; charset=utf-8\n" +
        // ⛔️ do not do this in real code! ⛔️
        'Content-Disposition: attachment; filename="troisième ans.txt"\n' +
        "\n" +
        "c'est le troisième ans",
      "utf8"
    );
    socket.end();
  })
  .listen(8080);
// 🚧 for example purposes only! 🚧
```

With this server, which encodes the entire HTTP response (headers and all) as UTF-8, then the Electron code began working, where `downloadItem.getFileName()` returned `"troisième ans.txt"`.

My advice here would be to instead use the `filename*=` encoding described in [RFC 6266](https://www.rfc-editor.org/rfc/rfc6266#page-7) to set the filename, which is also spec compliant:

```js
'Content-Disposition': `attachment; filename*=utf-8''${encodeURIComponent(filename)}`
```

I believe there is fairly wide support for this format, but you can also supply a backup as `filename=` still too; `filename*=` will be used when it is properly understood.

Wrapping up, I'm going to close this issue as not a bug given what I've found above. I hope that this information helps you with your problem! 😊

Still beyond my knowledge: I am not sure how Chrome manages to figure out the right file name from the bad header value. 🤷

**Comment by gnujeremie** [comment]
Thanks a lot for your time, and for your answer, it helps a lot :)
