### ISSUE TITLE
[Bug]: Notarisation Process failed after Successful Electron Build

### ISSUE THREAD

**Issue by SwapnilSherekar** [electron/electron#35941]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Monterey 12.2.1

### What arch are you using?

x64

### Expected Behavior

Hi team,
I have set the Notarization configuration to my test project in the file vue. config.js as below:

```
module.exports = defineConfig({
  transpileDependencies: true,
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        win: {
        },
        mac: {
          icon: "src/assets/appIcons.png",
          executableName: "Test_Vue",
          target: "pkg",
          type:"development",
          entitlements : "src/assets/entitlements.plist",
          entitlementsInherit:"src/assets/entitlements.plist",
          appId: "debasish@systoolsgroup.com",
          
        },

        appId: "Test_Vue",
        productName: process.env.VUE_APP_PROJECTNAME,
        
        buildVersion: "6.4.0",
        copyright: "SysTools Software @2022",
        
      }
    }
  }
})
```

After Running on Any other machine show the below alert:-
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1716663/194478782-e72fe5ab-78ca-4325-8343-471f6ba40e99.png)

Please help me to find out the exact changes required

Thanks,
Swapnil Sherekar
swapnil.s@systoolsgroup.com

### Actual Behavior

As we come to know that PKG file notarization is successful but another machine are not able to detect pkg notarization

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
