### ISSUE TITLE
Arrays containing multiple references to the same object are lost when sending over IPC

### ISSUE THREAD

**Issue by ajwhite** [electron/electron#3598]
I came across a very interesting scenario. There was some missing information in a collection that I sent between two processes.

Assume the scenario, Renderer and Process.

If I have an array that contains multiple entries of the **same object reference**, only the **first object** will be provided to the receiving side of the message -- the other entries will be `null`.

#### Renderer
```js
import {ipcRenderer} from 'electron';
var theObject = {foo: 'bar'};
var theList = [theObject, theObject, theObject];
ipcRenderer.send('test', theList);
```

#### Main Process
```js
import {ipcMain} from 'electron';

ipcMain.on('test', (evt, data) => {
  console.log(data);
  // this will output [{foo: 'bar'}, null, null];
});
```

-----

It is only when the object references are distinct from each other does the information remain intact. For example, If we do
#### Renderer
```js
import {ipcRenderer} from 'electron';
var theObject = {foo: 'bar'};
// create new object references for the other two entries, such that all entries are unique by reference
var theList = [theObject, {...theObject}, {...theObject}];
ipcRenderer.send('test', theList);
```

#### Main Process
```js
import {ipcMain} from 'electron';

ipcMain.on('test', (evt, data) => {
  console.log(data);
  // this will output [{foo: 'bar'}, {foo: 'bar'}, {foo: 'bar'}];
});
```

Then the proper information will be received.

I'm not sure if this is a problem with Chromium, and how virtual address space between threads is propagated when sending information between two processes, but clearly a collection of the same object references struggles to be passed around unless they are all distinct references.

**Comment by zcbenz** [comment]
This behavior is intended, objects sent through `ipc` are serialized into JSON, and we recognize the recursive objects by checking whether an object has appeared for more than once. This check is simple but efficient, a full detection of recursive objects would be quite inefficient and hard to get right.

**Comment by ajwhite** [comment]
You see the problem that solution presents though right? We're not really dealing with a recursive object here, and the prevention against recursive objects is crossing into other territory.

To me, that sounds like a bug. Would you be open to a pull request that will retain efficiency, but also narrow down so only cyclic objects are affected, versus arrays of the same thing?

**Comment by blueoctopus** [comment]
Since the current behavior is counter-intuitive, I suggest mentioning this corner case into the API references and also raising an exception if multiple references are detected (instead of silently sending objects as null).

A variation of the issue that was reported here made me scratch my head for longer than would've been necessary if I saw this documented or if an exception as thrown. I was sending a list with an object that was referenced in the list as the second argument. In my case sending to the renderer process using the `webContents.send()` API:

`webContents.send('test', [someObject, anObject, theObject], theObject);`

On the receiving side:

`ipcRenderer.on('test', (_, listOfObjects, interestingObject) => {
    console.log(interestingObject); // output: null
});`

**Comment by kevinsawicki** [comment]
Reopening this since I believe a fix for this exists in Chromium that can be ported to Electron.
