### ISSUE TITLE
[Bug]: sign in with apple

### ISSUE THREAD

**Issue by luokunman** [electron/electron#36071]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

macOS

### Operating System Version

macOS M1

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

16.0.0

### Expected Behavior

I thought I could use sign in with apple through node.

### Actual Behavior

I couldn't find a way to operate sign in with apple to work on macOS. Am I wrong or does Electron have this feature on MacOS?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
