### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by sisliu** [electron/electron#36109]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Recently, there is a task that needs to implement statistics on each process, including the process id, the memory used by the process, and the most important thing is the GPU used by each process. Functionally the same as the browser manager. Now the problem is that there is no interface to get the gpu situation used by each process. Hope to provide a process management tool for us to analyze performance

### Proposed Solution

Can we open an API so that we can directly open the electron task manager?

### Alternatives Considered

Or consider providing an API that allows us to get the gpu used by each process?

### Additional Information

Reference Browser Task Manager

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by sisliu** [comment]
Thank you for your reply
