### ISSUE TITLE
[Bug]: webview's visibilitychange event fired accidentally when webview or its parent element's style(display none, height 0 or visibility hidden) changing

### ISSUE THREAD

**Issue by daief** [electron/electron#36104]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

webview's visibilitychange event should not be fired when it or its parent element's style changing.

### Actual Behavior

visibilitychange event fired everytime when its **display**, **heght** or **visibility** switch.

I try iframe and behavior of iframe is normal.

### Testcase Gist URL

<https://gist.github.com/9deaf52169cb3256fbef1b27bb002093>

### Additional Information

Demo video:

https://user-images.githubusercontent.com/19222089/198248509-fd52f966-153e-4c34-ae62-6f0c0e0f37c2.mov

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by daief** [comment]
@codebytere I edited the description.

**Comment by daief** [comment]
bump

**Comment by daief** [comment]
bump
