### ISSUE TITLE
[Bug]: desktopCapturer does not work when types:['screen'] in ubuntu 22

### ISSUE THREAD

**Issue by thamizh-qwerty** [electron/electron#36115]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

Expecting the desktopCapture to take screenshot of whole screen and the save the file locally via fs module.

### Actual Behavior

desktopCapture works fine if it takes screenshot of all app separately and saves them locally when we use desktopCapturer.getSources({
      types: ['windows'],
      thumbnailSize: { width: 500, height: 500 }
    }).

but when we use desktopCapturer.getSources({
      types: ['screen'],
      thumbnailSize: { width: 500, height: 500 }
    })

we get only black image. it does saves an image locally in a folder. just fully black.
![Screenshot from 2022-10-24 07-01-58](https://user-images.githubusercontent.com/80245924/197430548-f0c09a94-6588-4785-ba7e-670525d2af96.png)

### Additional Information

1. Additional error shown:
[30280:1024/070124.798034:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[30280:1024/070124.861924:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

2. https://github.com/electron/electron/issues/14194 - referring the issue - used "app.disableHardwareAcceleration()" does not help.

**Comment by codebytere** [comment]
@mlaurencin wonder if this is related to https://github.com/electron/electron/issues/36037?

**Comment by mlaurencin** [comment]
@codebytere I wonder if it might be a separate problem since this is occurring with 'screen', while the other is related to 'window'.

@thamizh-qwerty Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? A testcase for [Electron Fiddle](https://www.electronjs.org/fiddle) would be very helpful for comparison purposes. It is a great tool for making small test cases in general, and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.
