### ISSUE TITLE
[Bug]: Global Shortcut Issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by TrofinSorin** [electron/electron#36152]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Last Known Working Electron version

16.00

### Expected Behavior

The Global App should work after packaging the app not only when developing on a local server.

### Actual Behavior

The global shortcut is working when developing, but after i'm packaging the app, it doens't work on prod, the keys registrered doesn't trigger.
The global shortcut doens't work on Ubuntu 22.04?

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by TrofinSorin** [comment]
I managed to fix it, it was an error from a package that required to install xsel on ubuntu.
I had to debugg in main in production, i send it to renderer from catch block through IPC to see the actual error from catch. 
It's weird because on development everything was working good.

Because of that error, it looked like the global shortcut was not working, sorry about that. Closing
