### ISSUE TITLE
[Feature Request]: A way to allow requests to private and local adresses in electron

### ISSUE THREAD

**Issue by ThijsOnGitHup** [electron/electron#36177]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![image](https://user-images.githubusercontent.com/47325246/198384913-8eb5f15d-413c-496b-b6c2-fae2d72431da.png)
`Access to XMLHttpRequest at 'http://localhost:3001/ajaxcom' from origin '<<site>>' has been blocked by CORS policy: Request had no target IP address space, yet the resource is in address space `local`.`
When I do a request to localhost from an website that is hosted on vercel (or any other webhosting). I get this error. I want to disable this CORS error in electron.

### Proposed Solution

A way to allow requests to private and local address in a electron application.

### Alternatives Considered

I have disabled webSecurity and this didn't fixed it

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
