### ISSUE TITLE
[Feature Request]: Emit initial installation event

### ISSUE THREAD

**Issue by sharifcse57** [electron/electron#36198]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently I store some data in local storage for my device.
I just want to remove local storage data when any one try to install device again which was previously set.

Currently storage data is present or not removed when someone while reinstall the app.

So I just want a installation event so that I can manually remove the storage items.

Or do you have any Idea how can I remove cached storage data from new installation device or app?

### Proposed Solution

Emit an event while app is installing first time.

### Alternatives Considered

Remove device cahced data storage while app is installing.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
