### ISSUE TITLE
electron dialog.showOpenDialog How to set display Chinese?

### ISSUE THREAD

**Issue by Likunone** [electron/electron#36236]
### I open the file selector through dialog.showOpenDialog and it displays an English window.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/15193414/199459826-141d7cef-f698-49e1-ab78-3a58a37d24e8.png">

### I want to open the Chinese window how should I set?
![image](https://user-images.githubusercontent.com/15193414/199459933-b75c41b1-0e8c-41fe-a8d2-cd44c2e92367.png)

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
