### ISSUE TITLE
[Bug]: Crash due to ZLIB dll in native addon

### ISSUE THREAD

**Issue by romainmnr** [electron/electron#36239]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.x.y
21.x.y

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I want to use a native c++ addon which use [ZLIB](https://zlib.net/) in an electron app.

### Actual Behavior

When runing my script with `node` everything is working as expected. 
But when I try to launch the same script with `electron` the app is crashing at the function calling zlib.

One thing to notice, I don't have the issue on macOs (intel and ARM)

Can someone help me ? 

### Additional Information

```
const myadddon = require('myaddon');

myadddon.fnUsingZlib() // crash here

```

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by romainmnr** [comment]
I have the same issue with electron@21

**Comment by nornagon** [comment]
Okay, I'll reopen this then. However, in order to assist further, we'll need a standalone testcase with only the code necessary to reproduce the issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.
