### ISSUE TITLE
[Bug]: Tray window freezing after running shell.openExternal

### ISSUE THREAD

**Issue by vitaliyzolotoy** [electron/electron#36238]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Clicking on tray window works correct

### Actual Behavior

After few clicks on context menu or on external link tray window is freezed

### Testcase Gist URL

https://gist.github.com/vitaliyzolotoy/5f9a35b7d33a98f8140422f91353373e

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.
