### ISSUE TITLE
[Bug]: Can not create accelerator with CommandOrControl+Shift+Plus

### ISSUE THREAD

**Issue by Imperat** [electron/electron#36234]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Hello,

I can not add menu item with accelerator "CommandOrControl+Shift+Plus".

I expect that my menu item will be assigned to "CommandOrControl+Shift+Plus".

### Actual Behavior

"CommandOrControl+Shift+Plus" appears on my Mac as "Command+Plus".
"CommandOrControl+Shift++" does not appear.

### Testcase Gist URL

https://gist.github.com/Imperat/8c9722f58b6a818b176020986b8aea7d

### Additional Information

Also, I reproduced the same bug in Windows 11 (in Virtual Machine)

**Comment by mlaurencin** [comment]
It looks like since `Shift` is needed to activate `+`, it is consumed and therefore not displayed in the menu item. Additionally the accelerator "CommandOrControl+Shift++" is not valid, thus it does not display. Valid key codes and modifiers can be found [here on the website](https://www.electronjs.org/docs/latest/api/accelerator). 

In the future, I would encourage looking to one of the [community resources](https://www.electronjs.org/community) for addressing problems such as these -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
