### ISSUE TITLE
[Bug]: The built app doesn't reopen after closing

### ISSUE THREAD

**Issue by devlab0110** [electron/electron#36259]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 22.04 .... 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

18.2.0

### Expected Behavior

the built app must be able to be reopened after being closed

### Actual Behavior

the built app doesn't reopen after closing ... i have to wait about a minute to be able to open it again

### Additional Information

I have builtеd application of _amd64.deb
when I install and test it the following happens:
- I open the app and everything is fine
- I close the app and everything is fine
- then I try to open it again but nothing happened, the app doesn't start and I have to wait about a minute
- after about a minute I try to open the app again and everything is fine ?!

**Comment by devlab0110** [comment]
screencast video
https://www.youtube.com/watch?v=uBhlEvQO7lI

**Comment by devlab0110** [comment]
i just tested the same case with
https://github.com/electron/electron-quick-start
here are all the steps:

- git clone https://github.com/electron/electron-quick-start
- cd electron-quick-start
- npm install 

- npm install --save-dev @electron-forge/cli
- npx electron-forge import
- npm run make

... ultimately the same problem?!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. This also seems like a potential problem with electron forge and not electron. If you do believe this is an issue the team can solve, please re-open on that repo.
