### ISSUE TITLE
How does macos monitor uninstall events and do user statistics

### ISSUE THREAD

**Issue by iiemos** [electron/electron#36286]
Hello, does anyone know how macOS monitors the uninstall event to make user statistics

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
