### ISSUE TITLE
Does the latest version of electron (v21) support Region Capture?

### ISSUE THREAD

**Issue by bynho** [electron/electron#36317]
From Chromium 104 there is now support for Region capture when screensharing.   I have an application which is working fine when I run it from the browser, however when running on Electron the track being returned is MediaStreamTrack instead of BrowserCaptureMediaStreamTrack, therefore throwing an error when calling track.cropTo.

More info on feature:
https://developer.chrome.com/docs/web-platform/region-capture/

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
