### ISSUE TITLE
[Feature Request]: navigator.share not support in electron js 

### ISSUE THREAD

**Issue by pouyamca** [electron/electron#36410]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello

I developed a desktop application with electron js. 
I'm going to add the share feature to it. 
Actually, I researched navigator share in electron js.  when I was trying to use this feature of the browser, console log of "navigator.canshare" return false.
Could you please tell me how can I implement this feature in electron js? 
Do you have any plans for supporting this feature?

### Proposed Solution

add this feature in electorn js as like as other browser

### Alternatives Considered

Do you have any alternative or sloution for this problem?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
