### ISSUE TITLE
[Bug]: BrowserView removed by removeBrowserView not properly cleaned up

### ISSUE THREAD

**Issue by sdelrue** [electron/electron#36436]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home Windows Feature Experience Pack 1000.22636.1000.0

### What arch are you using?

x64

### Expected Behavior

I have a basic setup where I load a BrowserView with a looping video with sound:
`const embedView = new BrowserView()`
`win.addBrowserView(embedView)`
`embedView.webContents.loadURL("http://localhost/video.html");`

When I remove the BrowserView, the view is removed, but in the background I still here the video playing. So it looks like the content of the BrowserView still exists somehow.
`const views = win.getBrowserViews()`
`for (const view of views) {`
`    win.removeBrowserView(view)`
`}`

When I call view.webContents.destroy() in the above for-loop, before removing the BrowserView, the video stops playing, but electron randomly crashes.### 

### Actual Behavior

When Removing a BrowserView, it should be properly cleanup (no more sound playing)

**Comment by wheezard** [comment]
This is expected behaviour *(except for the crash)*.

`BrowserWindow.prototype.removeBrowserView()` does not destroy the browser view, it only removes it **from the window**, which means it's not visible or attached to a window anymore, but is still active.
To remove the BrowserView completely, you should call `view.webContents.destroy()`, however, this is an *undocumented* method, which is why it can result in a crash.

I advise you to first remove the browser view from the window, calling `win.removeBrowserView(view)` and ***then*** call `view.webContents.destroy()`. If you still get the crash, please open a new issue here specifically for that.

**Comment by nornagon** [comment]
In Electron 22+ you can use `webContents.close()`, which _is_ documented: https://www.electronjs.org/docs/latest/api/web-contents#contentscloseopts
