### ISSUE TITLE
[Bug]: WebSocket method works on browser but not working on Electron

### ISSUE THREAD

**Issue by kerimaksoy** [electron/electron#36492]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I am using a library that has web sockets and I am using a method called "watchOHLCV" which returns an array on Angular (browser):

![image](https://user-images.githubusercontent.com/46629380/204775307-eed320e8-0042-4cd6-a1dc-e739400fb7bd.png)

### Actual Behavior

but when I build that and run it on electron app it gives me this error: 

![WhatsApp Image 2022-11-30 at 13 26 11](https://user-images.githubusercontent.com/46629380/204775980-3881303b-4bef-441e-bbf9-39faa42fc088.jpeg)
(other methods like fetch methods works fine on both Angular (browser) and electron (desktop) but I don't know why only WebSocket methods are not working in electron?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
