### ISSUE TITLE
Improving Docs Link Linting

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#36541]
Let’s talk about links in our docs. 🖇️ Specifically, what we can do to better lint them and prevent broken links from sneaking into the docs. 💀

Linting links in Markdown is non-trivial; there’s several ways they can be broken:

1. Relative links can point to an incorrect path or have an incorrect URL fragment
    1. Links to headers within the same document are possible to lint with no further context, but cross-file links require holistic knowledge of what link targets are valid, i.e. headers in other files for URL fragments
    2. [`script/check-relative-doc-links.py`](https://github.com/electron/electron/blob/79d2fc9c234059baf474e7f33a722bd1cb142e39/script/check-relative-doc-links.py) is our current approach for linting these, but it has several problems:
        1. Doesn’t check URL fragments across files
        2. Doesn’t detect broken reference links (https://github.com/electron/electron/issues/34670)
        3. Uses regexes to detect links which isn’t robust
2. Since reference links need the link definition to render as a link, it’s easy for them to become broken when text is moved between files, link text is changed, etc.

## Reference links

Reference links come in three variations:

1. `[foo][]` - [collapsed reference link](https://spec.commonmark.org/0.30/#collapsed-reference-link) - link text with an empty link label
2. `[foo]` - [shortcut reference link](https://spec.commonmark.org/0.30/#shortcut-reference-link) - omits the empty link label
3. `[foo][bar]` - [full reference link](https://spec.commonmark.org/0.30/#full-reference-link) - link text followed by link label

Reference links are a particularly thorny issue to lint. It’s fairly straightforward to detect link definitions that are unused, but much more difficult to detect reference links which are missing a link definition, and as such aren’t rendered as a link as intended. Markdown parsers will treat `[foo]` as just plain text if there’s no corresponding link definition for it, making after the fact detection of these cases difficult - any generated AST doesn’t mark it as a (possibly) broken reference link, it just considers it text within the larger paragraph. This is compounded by legitimate uses of the “shortcut reference link” syntax in text - is [0, 1] simply text describing an interval, or is it a shortcut reference link for the link `0, 1`? So any attempt at linting those for missing link definitions is fighting an uphill battle and bound to have lots of false positive noise.

📮 With that in mind, I’m going to say “shortcut reference links considered harmful”, since they’re so ambiguous. I think “collapsed reference link” style is significantly less likely to conflict with legitimate uses of the syntax, so it will generate fewer false positives. False positives can be dealt with by escaping the opening `[` in the Markdown. In addition, `markdownlint` does have a linter check for broken reference links ([`MD052`](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md052---reference-links-and-images-should-use-a-label-that-is-defined)), but it doesn’t cover the shortcut links due to the aforementioned ambiguity. As such, I think we should ban “shortcut reference links” from the docs in favor of the more explicit “collapsed reference link” style and add a linting check to enforce the ban (it’s pretty trivial to add a new `markdownlint` rule to do so, [I’ve implemented it here](https://github.com/electron/electron/commit/43e8d4d418cec1775125871c84bd1836372a8d99)).

Once we convert the existing shortcut links to collapsed style (just add a trailing `[]`), we can flip on the `MD052` rule for `markdownlint` and that should give us linting coverage for broken reference links and close out https://github.com/electron/electron/issues/34670.

## Cross-file Relative Links

I'd like to replace `script/check-relative-doc-links.py` with a new solution based off of [`vscode-markdown-languageservice`](https://github.com/microsoft/vscode-markdown-languageservice). That's the npm package which now powers Markdown linting in VS Code, and it takes a holistic view of the workspace of Markdown documents so it can handle cross-file links and determine when URL fragments are wrong, in addition to other goodies like duplicate reference link definitions. [I've got an initial implementation here](https://github.com/electron/electron/commit/e9261c6cbd6adde9fe61189805fb2aef19b83065). A nice benefit of that work is it could power [a script to easily find all incoming links to a file](https://github.com/electron/electron/commit/8824cacf0c76f7e875b66f028162791abc388dee), which could be useful for knowing what documentation might need to be updated when making a change.

Unfortunately it also relies on regexes for detecting links (due to the needed information about lines and range not being exposed by `markdown-it`), which isn't robust - most of the open issues on that repo are related to problems with the link matching. I've got a plan for an upstream change there which would allow for swapping in a different implementation for detecting links, and I think an alternative implementation could be built on top of `mdast` and be pretty robust.

**Comment by DavidAnson** [comment]
@dsanders11 Thanks for pointing me here, this is very relevant to my interests! Some thoughts:

- While it is now possible to author asynchronous rules which enable the scenario of validating external links, I am unlikely to do so for any of the core rules because asynchronous rules don’t run in the synchronous scenario and I’d like to continue to support that while possible.
- As someone who is comfortable writing custom rules (nice, by the way!), you may be interested in taking that approach. It would allow you to rely on the parser to identify all links, so should be easy and accurate. This may require CLI2 for asynchronous rule support, but that should be a pretty simple change based on what I’ve seen.
- I have plans to add a new consistency rule for reference/collapsed/shortcut links that would help with your goal of standardizing. If you’re planning to do that work anyway, maybe you would like to submit it - or at least submit a draft of it, and I could fill in the scaffolding around it?
- Your idea to use the VS Code language service is clever and I wish you luck with that. Ever since they introduced it, I get the occasional bug for it filed against my code, so good luck? :)
- In the spirit of the saying, “if you solve a problem with a regular expression, now you have two problems“, I recently converted from using a regular expression for URL detection to something I’m calling “function expression“. I don’t know if I love this approach, but I needed it to fix some bugs and avoid a warning about an inefficient regular expression. What I’ve done is make a similar interface that runs code instead of a regular expression. You can see that along with some test cases here: <https://github.com/DavidAnson/markdownlint/commit/8d6e0b541958e044c73a12489d5e8dcf29467a3d>. I am concerned there may be some flaws with this approach, but I believe it will be easier to fix them this way than by iterating on a regular expression that already wasn’t adequate.
- It’s really interesting to see you are considering other parsers. I got flagged on an ESLint RFC last week where they are considering opening up to other languages. One of the comments I left talked about the struggles I’ve had due to the fact that markdown-it does not provide detailed line/column information. I’ve superficially looked into that a few times and didn’t think I could add it, but I will be making another pass after the upcoming release and trying a little bit harder than before. I don’t think it would be practical to change parsers for markdownlint, but I am open to the idea given my current level of desperation.
- In your custom rule code, you reference a bug in one of my helpers. If you could please provide an example of that, I’d like to have a look and see if it’s something I can fix!

Happy to discuss/debate/argue about any of this further, if you’re interested. Also, happy to help if you run into any issues with markdownlint!

**Comment by dsanders11** [comment]
> I have plans to add a new consistency rule for reference/collapsed/shortcut links that would help with your goal of standardizing. If you’re planning to do that work anyway, maybe you would like to submit it - or at least submit a draft of it, and I could fill in the scaffolding around it?

I could try to take a look, but I don't have a lot of time at the moment to make a more general PR for that functionality. I don't know a lot about `markdownlint` internals, just enough to hurt myself. 🙂 Feel free to use any code of mine though, not that the custom rule linked in this issue is anything special.

> Your idea to use the VS Code language service is clever and I wish you luck with that. Ever since they introduced it, I get the occasional bug for it filed against my code, so good luck? :)

Anything in particular I should watch out for? 😄 I've implemented all of that part and didn't have any issues doing what it needed to do, other than my PR to expose a hook for swapping out the "linkComputer" got declined so I'll have to fork. Most of the issues I've seen with it are problems with finding links due to the regex stuff, which is why I'm sidestepping that.

> In the spirit of the saying, “if you solve a problem with a regular expression, now you have two problems“, I recently converted from using a regular expression for URL detection to something I’m calling “function expression“. I don’t know if I love this approach, but I needed it to fix some bugs and avoid a warning about an inefficient regular expression. What I’ve done is make a similar interface that runs code instead of a regular expression. You can see that along with some test cases here: https://github.com/DavidAnson/markdownlint/commit/8d6e0b541958e044c73a12489d5e8dcf29467a3d. I am concerned there may be some flaws with this approach, but I believe it will be easier to fix them this way than by iterating on a regular expression that already wasn’t adequate.

Interesting! Regular expressions are definitely not adequate (unfortunately) to cover all the cases for links without false positives, which is why I'm swapping that part out in `vscode-markdown-languageservice`. I'm by no means an expert, but does feel like the only foolproof way to detect links is with true parsing of the Markdown. I've got more wiggle room than `vscode-markdown-languageservice` since I don't need exact positioning information for the links within the file, line number suffices.

> It’s really interesting to see you are considering other parsers. I got flagged on an ESLint RFC last week where they are considering opening up to other languages. One of the comments I left talked about the struggles I’ve had due to the fact that markdown-it does not provide detailed line/column information. I’ve superficially looked into that a few times and didn’t think I could add it, but I will be making another pass after the upcoming release and trying a little bit harder than before. I don’t think it would be practical to change parsers for markdownlint, but I am open to the idea given my current level of desperation.

I came to the same conclusion about it not being possible with `markdown-it`, as I think has everyone who has looked into it, including the author, who has said as much in the past. 😅 I'd be very happy if you did find a way as that would simplify things, so best of luck!

The only reason I considered other parsers is because it happened that `vscode-markdown-languageservice` had a nice interface (just not exposed) that made it easy enough to swap in any other implementation for finding links, and performance isn't really an issue in this use case. I just want correctness so that hopefully broken links can be "solved" in the Electron docs, since I've had to fix a couple dozen of them at this point, and they sneak in too often thanks to reference links during reorganizing between files - which hopefully won't be a problem thanks to `MD052` once I clear out the shortcut links (which I've done the work on over at https://github.com/electron/electron/compare/main...dsanders11:electron:markdownlint-no-shortcut-refs, just need some other PRs to land first to avoid conflict issues).

> In your custom rule code, you reference a bug in one of my helpers. If you could please provide an example of that, I’d like to have a look and see if it’s something I can fix!

Sure, I'll file an issue. 🙂 

> Happy to discuss/debate/argue about any of this further, if you’re interested. Also, happy to help if you run into any issues with markdownlint!

Thanks for the discussion. `markdownlint` has been a helpful tool in keeping the docs consistent. 👍
