### ISSUE TITLE
[Bug]: Get network traffic of browser in electron

### ISSUE THREAD

**Issue by taihoa** [electron/electron#36549]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

I want to tracking download speed (kb/s) and upload speed (kb/s) of browser in electron app
![image](https://user-images.githubusercontent.com/8847573/205549367-d266ce76-3638-4551-8fb1-29194b37970d.png)

### Actual Behavior

I am developing application video call. I want to tracking download speed (kb/s) and upload speed (kb/s) of browser in electron app. But I not found library support it.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
