### ISSUE TITLE
[Bug]: Error invoking remote method 

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#36607]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

ia32

### Expected Behavior

How can i solve this error？
Help me please！！！

### Actual Behavior

I catch the erro by listener unhandledrejectionr:

Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:105:526)

But I don't know how it happened。
Under what circumstances will this occur？
How should I avoid this error？

**Comment by MounicaChanda0809** [comment]
I am also facing this error with 21.1.1, 21.3.3, 22.0.0. This issue is closed https://github.com/electron/electron/issues/28208 with the PR https://github.com/electron/electron/pull/36129.

But still facing the issue. Please let us know the right version to use that fixes the issue.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Galkon** [comment]
Running into a similar issue, people in Discord are non-responsive sadly. Electron unusable after electron 19.x for us.
