### ISSUE TITLE
Enable proto-format traces

### ISSUE THREAD

**Issue by jasonmevans** [electron/electron#36604]
Hello, 

I'm setting up some automated content tracing for my application, and whenever I load these into Perfetto UI, I get a warning saying,

> _Perfetto UI features are limited for JSON traces. We recommend recording proto-format traces from Chrome._

Would it be possible to expose an option in the content tracing [TraceConfig object](https://github.com/electron/electron/blob/7acb513ba675aee12bdf52cf5ca8c3d162a93ef4/docs/api/structures/trace-config.md) to enable this feature?

Thanks!

![Screen Shot 2022-12-07 at 2 26 00 PM](https://user-images.githubusercontent.com/505818/206310946-8a81bbf0-ca09-43f7-a72b-5a92a2bf4010.png)

![Screen Shot 2022-12-07 at 2 25 25 PM](https://user-images.githubusercontent.com/505818/206310930-6c049991-ffe9-40c2-80d0-2fbc30803362.png)

**Comment by codebytere** [comment]
@jasonmevans we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please correct this to conform to the enhancements template.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
