### ISSUE TITLE
[Bug]: 'renderer' process exited with 'oom' 0x7701e062

### ISSUE THREAD

**Issue by curiosity26** [electron/electron#36614]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.2

### What operating system are you using?

Windows

### Operating System Version

10.0.19044(2251)

### What arch are you using?

ia32

### Expected Behavior

I would expect the render process to not crash

### Actual Behavior

The renderer process crashes unhandled

### Additional Information

[8fa0ae8c0a2241b881c3f08292146e0b-symbolicated.crash.txt](https://github.com/electron/electron/files/10188766/8fa0ae8c0a2241b881c3f08292146e0b-symbolicated.crash.txt)

**Comment by curiosity26** [comment]
Also seeing this:

```
{
exitCode: -536870904, 
reason: oom
}
```

Also seems to happen in version 21.3.1 with the same exitCode.

**Comment by MarshallOfSound** [comment]
Your renderer process is using too much memory, use devtools to try track down your memory usage and identify and leaks that are occurring.  This is an issue with your code, not Electron generically

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
