### ISSUE TITLE
[Bug]: Lazy relink of dynamic library leads to crash

### ISSUE THREAD

**Issue by Ranxi** [electron/electron#36636]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I compiled a C dynamic library, which exposes some API to do some simple things.
Then, I used `ffi-napi` to call the APIs in the main.js, like the following:
```
const ffi = require('ffi-napi');
const ref = require('ref-napi');

const my_dll = new ffi.Library("./lib/libmydll", {
    'set_book_fpath': [
    'bool', ['char*'],
    ],
});

var fpath = new Buffer.from("/Path/To/something/")
fpath = ref.types.char;

const result = my_dll.set_book_fpath(fpath);
console.log("set fpath result:", result);
```
When I open the MacBook pro, execute `electron .`, everything goes perfect.
However, When I just modify the library source code, (i.e. add one line of printf), compiled the dynlib, copy newest dynlib file to the `./lib` directory of electron project, execute `electron .` again, I got:

> Electron exited with signal SIGKILL

Then I shutdown the macbook, restart it again, `electron .` goes well again !
I thought the problem is the lack of relinking the recompiled dynlib, so how can I solve this problem?

### Actual Behavior

When I open the MacBook pro, execute `electron .`, everything goes perfect.
However, When I just modify the library source code, (i.e. add one line of printf), compiled the dynlib, copy newest dynlib file to the `./lib` directory of electron project, execute `electron .` again, I got:

> Electron exited with signal SIGKILL

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by Ranxi** [comment]
您好，您发的邮件已收到，谢谢！

**Comment by Ranxi** [comment]
Come on, pls, Discord is hard to use. And I have no permission to post an new issue.
I want to say something ugly for your redirecting policy.
What I encountered is definitely the problem of electron.
