### ISSUE TITLE
[Bug]: Installing new electron app ,version is going back to old one

### ISSUE THREAD

**Issue by MahmoodIrakeZ** [electron/electron#36646]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 64-bit operating system, x64-based processor

### What arch are you using?

x64

### Expected Behavior

i am creating new exe file with new version of my app, and i want to install it to client end 
after installing it , it supposed to work fine and i can see that the version of my app changed .

### Actual Behavior

after installing new version on the client end ,the version is changed at first but when i enter the app it returns to older version that was installed before and when i do clear cache it returns to new one ,but after using the app again it return immediately to older version  

### Additional Information

i have tried many things , c4reating custom installer deleting app data, 
i don't know how but its keeps returning to older version

**Comment by MahmoodIrakeZ** [comment]
any one can help me @electron

**Comment by miniak** [comment]
https://www.electronjs.org/blog/a-quiet-place-22

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
