### ISSUE TITLE
[Bug]: Electron does not save session info as in chrome which causes playwright to not load session info

### ISSUE THREAD

**Issue by suchcodemuchwow** [electron/electron#36689]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

macOS

### Operating System Version

MacOs Monterey

### What arch are you using?

x64

### Expected Behavior

User data dir content should be also usable in playwright chromium.

### Actual Behavior

While I was working on pet project that I was planning to load remote whatsapp web in electron app and scan the qr code then run playwright/puppeteer on the background to celebrate birthdays struggled with loading **userDataDir** in playwright. 

It works perfectly fine when I use my daily browsers(chrome) userDataDir: **/Users/x/Library/Application Support/Google/Chrome** but when I try to use any of the following:
- **/Users/x/Library/Application Support/Electron**
- **/Users/x/Library/Application Support/Electron/Partitions**
- **/Users/x/Library/Application Support/Electron/Partitions/infragistics**
- **/Users/x/Library/Application Support/Electron/Partitions/Default**
- **/Users/x/Library/Application Support/Electron/Default**

it doesn't load the whatsapp session and asks me to login again...

To reproduce the problem these 2 simple snippets are enough:
Electron:
```ts
mainWindow = new BrowserWindow({
  show: false,
  width: 1024,
  height: 728,
  icon: getAssetPath('icon.png'),
  webPreferences: {
    preload: app.isPackaged
      ? path.join(__dirname, 'preload.js')
      : path.join(__dirname, '../../.erb/dll/preload.js'),
    partition: 'persist:infragistics',
  },
});

mainWindow.loadURL('https://web.whatsapp.com');
```

Playwright:
```ts
const { chromium } = require('playwright');

(async () => {
  const playwrightCtx = await chromium.launchPersistentContext(
    '/Users/x/Library/Application Support/Electron',
    { headless: false }
  );

  const page = await playwrightCtx.newPage();
  await page.goto('https://web.whatsapp.com');
})();

```

**Comment by codebytere** [comment]
hey @suchcodemuchwow  -  there's not and has never been an expectation that the session info is identical. In this instance, the issue is that the location of `Cookies` and `Cookies-Journal` are different for Electron and Chromium. Chromium has a concept of Profiles and given a user data directory `/a/b`, chromium launched with no profile will create user data under `/a/b/Default`. Electron has no concept of Profiles, and so does not work identically. 

Try copying the `Cookies` file from `Application Support/Electron/Partitions/infragistics`  into `Application Support/Electron/Partitions/infragistics/Default` and the browser should pick up the persisted cookies.
