### ISSUE TITLE
[Bug]: White screen and source code are exposed 

### ISSUE THREAD

**Issue by hajeonghun** [electron/electron#36716]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.4

### What operating system are you using?

Mac

### Operating System Version

macOS Ventura

### What arch are you using?

arm64

### Expected Behavior

The new browser should display a normal screen.

### Actual Behavior

Occurs intermittently when you launch a new window browser.

js or css code is exposed along with the white screen.

The build of the main window and the new window is divided into webpack5 settings
(ex. mainWindow.html / mainWindow.js, newWindow.html / newWindow.js)

This is to avoid including js that do not require each window.

![image](https://user-images.githubusercontent.com/52861562/208802719-9f6afe61-4e1c-4d45-8dd0-66fa87b242de.png)

**Comment by Slapbox** [comment]
How certain are you that this is an Electron bug?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
