### ISSUE TITLE
[Bug]: Is there any API can  lock an Electron app to landscape mode on Windows PAD ?

### ISSUE THREAD

**Issue by famingyuan** [electron/electron#36755]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.8

### What operating system are you using?

Windows

### Operating System Version

window11 PAD

### What arch are you using?

x64

### Expected Behavior

I have build an APP for windows PAD. I want to lock  app to landscape mode . is there any api can do this ?

### Actual Behavior

Did not find any solution ...

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
