### ISSUE TITLE
[Feature Request]: Allow opening links in mobile browser mode

### ISSUE THREAD

**Issue by SwankyTigerYY** [electron/electron#36786]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

My H5 code does not work in Electron. It has the same problem as when I open a file in a computer browser. When I use the mobile mode of the browser, this problem no longer exists.I hope Electron has the function of packaging in H5 mode.

### Proposed Solution

none

### Alternatives Considered

none

### Additional Information

quasar + q-select + showPopup()

https://v1.quasar.dev/vue-components/select

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
