### ISSUE TITLE
[Bug]: Cannot print in for loop

### ISSUE THREAD

**Issue by AkhmedovSH** [electron/electron#36795]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I could not find solution
Restaurant project when waiter make order i need print check of this order in kitchen barman and cashier printers simultaneously
When i call  printerWindow.webContents.print(options) in for loop 
like this
for (let i = 0; i < printers.length; i++) {
        console.log(i)
	const options = {
		silent: true,
		deviceName: printer[i]['name']
	}
	printerWindow.webContents.print(options)
}

### Actual Behavior

I see in console i 3 times but printer print only 1 check in 1 printer. Now i use kind of setTimeout in js but it makes many problems

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
