### ISSUE TITLE
[Question]: Will electron really prevent node integration in the render process in the future?

### ISSUE THREAD

**Issue by rconde01** [electron/electron#36792]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This [article](https://code.visualstudio.com/blogs/2022/11/28/vscode-sandbox) says:

"Blocking Node.js from renderer processes is an encouraged Electron [security recommendation](https://www.electronjs.org/docs/latest/tutorial/security) and *will eventually be the only way of writing Electron applications.*"

Is that really true? The recommendation is "Disable the Node.js integration in all renderers that display remote content" - but not for trusted local content.

### Proposed Solution

Don't impose this limitation.

### Alternatives Considered

IPC has too much overhead.

**Comment by rconde01** [comment]
https://github.com/electron/electron/issues/35241#issuecomment-1371262598

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
