### ISSUE TITLE
[Feature Request]: How to implement Synchronizing Documents in the iCloud Environment?

### ISSUE THREAD

**Issue by tinhzionlabs** [electron/electron#36823]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi everyone,

I see Apple support Sync Documents in Icloud Environment:
- Ref: https://developer.apple.com/documentation/uikit/documents_data_and_pasteboard/synchronizing_documents_in_the_icloud_environment?language=objc

But I dont know how to implement it in Electron App. 
Do we have some packages for handling it?

Thank you!

### Proposed Solution

Nope, I have no idea on my question.

### Alternatives Considered

Nope, I have no idea on my question.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by maheskrishnan** [comment]
Hi [codebytere](https://github.com/codebytere), could you please explain the your reasoning for closing issue? I noticed that you are working for Microsoft and suspect that you are naturally inclined to avoid any useful features benefit Apple ecosystem?
