### ISSUE TITLE
[Bug]: electron+axios开发的商业应用，中级证书和服务端证书都是正常，但在用户电脑上出现了unable to verify the first certificate接口错误

### ISSUE THREAD

**Issue by AceAZhe** [electron/electron#36833]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17+

### What operating system are you using?

Windows

### Operating System Version

window10 专业版

### What arch are you using?

x64

### Last Known Working Electron version

17+

### Expected Behavior

electron+axios开发的商业应用，在用户电脑上出现了unable to verify the first certificate接口错误，请求的域名的根证书是GlobalSign Root CA R1，中级证书和服务端证书都是服务器云侧分发的，是没有问题的。
期望：想找到electron+axios开发的应用的GlobalSign Root CA R1根证书是从哪获取的？

### Actual Behavior

electron+axios开发的商业应用，在用户电脑上出现了unable to verify the first certificate接口错误（重装应用，重启电脑仍然会报错这个unable to verify the first certificate），接口请求的域名的根证书是GlobalSign Root CA R1，中级证书和服务端证书都是服务器云侧分发的，是没有问题的，那么可能出问题的是点是在根证书GlobalSign Root CA R1，尝试过certmgr.msc证书管理界面，禁用根证书GlobalSign Root CA R1证书，但是无效。所以想请问electron+axios开发的应用，其内部的根证书GlobalSign Root CA R1是从哪里来的？

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
