### ISSUE TITLE
[QUESTION] How to open the virtualkeyboard in a webview tag

### ISSUE THREAD

**Issue by JFeldaca** [electron/electron#36840]
Hello!

I'm making an app using electron as a base, for the ubuntu platform.

Said APP consists of a screen in kiosk mode that opens a web page that is passed through the command line when opening, for example, `electron-webview https://google.com`

So far I've already achieved this milestone with no problems, but I can't get the ubuntu virtual keyboard to come up when the search text input is clicked (or, in my case, when the input is touched).

I've been looking, and I've seen that the solution could be done with the ipcRenderer, but I don't have much idea how to implement it, do you know of any site that gives an example or a simple solution? It is to take a base and develop from there.

Thanks!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
