### ISSUE TITLE
[Feature Request]: Questions about npm install

### ISSUE THREAD

**Issue by cariha** [electron/electron#36861]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am working on a project with electron at my company.
Before using it, I ran npm install electron to install it.

However, the address of the github to connect is
It is an IP address, not a domain address.
(RequestError: connect ETIMEOUT 20.200.245.247:443)

Other modules are domained and can be installed.
Only electron is ip.

It is possible to connect to the domain, but it is currently impossible to install it because it is impossible to access with the IP for security reasons.
Is there a reason to access by IP rather than domain name?
Is it possible to change the domain name in npm install?

### Proposed Solution

Request to change the accessing github path to a domain rather than an ip, if not possible, request an explanation of the reason.

### Alternatives Considered

Request to change the accessing github path to a domain rather than an ip, if not possible, request an explanation of the reason

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
