### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by James-kelly1** [electron/electron#36898]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

NA

### Expected Behavior

R shiny was bundled into an electron executable following procedure outlined in "https://github.com/COVAIL/electron-quick-start/".  I expected the executable to work without any internet dependency.

### Actual Behavior

The executable works with internet connection but it does not work without internet connection.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
