### ISSUE TITLE
[Bug]: win7 64 can install？win7 64 can‘t install？

### ISSUE THREAD

**Issue by YLQZ** [electron/electron#36894]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.00

### What operating system are you using?

Windows

### Operating System Version

windows 7 2011years release

### What arch are you using?

x64

### Last Known Working Electron version

22.x.y

### Expected Behavior

can install  electron app

### Actual Behavior

win 7 64 2011 can't install
win 7 64 2019 can install

can support all win7 64 install?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
