### ISSUE TITLE
Input Values

### ISSUE THREAD

**Issue by rungtavaidik** [electron/electron#36907]
Hi,
I've been using the below code to get input values from index.html
```js
const user = document.getElementById("name");
const login = document.getElementById("password");
const enter = document.getElementById("enter");
enter.addEventListener("onclick" , function() {
    if(login==null) {
        console.log("err");
    }
})
```
But on clicking the enter button. there's no response in the console when left login as empty...

**Comment by dsanders11** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed.

For your particular question, I'd suggest asking on StackOverflow as it's a general HTML/JS question. You want to get the value of the input, not just the element.
