### ISSUE TITLE
[Bug]: How to prohibit the selection of all webview pages in the main window?

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#36916]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

ia32

### Last Known Working Electron version

13.6.0

### Expected Behavior

Do not select all webview interface。

### Actual Behavior

Why can all webview interfaces be selected by using ctrl+a to select all in the main renderer? This looks like a bug because the entire webview interface is grayed out. how to solve this problem?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
