### ISSUE TITLE
[Feature Request]: Allow changing Block 3rd party cookies flag

### ISSUE THREAD

**Issue by xadh00m** [electron/electron#36922]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi,

We have a setup with multiple iFrames to present internal and external webpages in a browser window. With the latest update these webpages can no longer set their cookies due to the cookie policy changes and do not work properly anymore.

I´ve searched through [command line switches](https://peter.sh/experiments/chromium-command-line-switches/) without success and only found a hint without further information about [custom capabilities](https://stackoverflow.com/questions/60633957/how-to-change-block-third-party-cookies-in-chromium-through-chromedriver).

Is there a way to disable blocking somehow without forking electron and patching the chromium sources?

### Proposed Solution

Maybe an additional `webPreferences` window option.

### Alternatives Considered

A `before-added` event based solution requested [here](https://github.com/electron/electron/issues/22830), which supports adding `SameSite=none` and `Secure` manually to allow them.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
