### ISSUE TITLE
[Bug]: Fullscreen & frameless options has no effect on embedded Windows system

### ISSUE THREAD

**Issue by ameurenand** [electron/electron#36992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 IoT Entreprise LTSB 2016

### What arch are you using?

x64

### Expected Behavior

I would like to use my Electron app on an embedded Windows system (Windows client kiosk).
Then I set my Electron app as Custom Shell (it means my app replaces the explorer.exe process).
In this configuration, I need a fullscreen (and so frameless) application.

### Actual Behavior

The fullscreen & frameless options of BrowserWindow doesn't work in this configuration.

**Comment by Abhijrathod** [comment]
It sounds like you're encountering an issue with using the fullscreen and frameless options of the BrowserWindow class in Electron when your app is set as the custom shell on an embedded Windows system.

It is possible that this issue is related to the specific version of Windows you are using, as well as the version of Electron. It may also be related to the way that custom shell applications are handled by Windows.

One potential solution may be to try using a different version of Electron to see if that resolves the issue. Additionally, you can try to search the Electron's Github repository, or other community forums, to see if other users have encountered similar issues and if there are any known solutions.

You may also consider creating a minimal reproduction of the issue, so that you can file a bug report to the Electron's repository.

**Comment by ameurenand** [comment]
I found the mistake: when the app is launched as the custom shell, the current directory is not the app directory. And I loaded a configuration file with a relative path.
So I close the issue.
Sorry for that.
