### ISSUE TITLE
How to disable macOS topbar in fullscreen mode ?

### ISSUE THREAD

**Issue by microSoftware** [electron/electron#37131]
On macos, you can do view > full screen
It works great !

1/ Can you automatically set your app in full screen mode at launch without the user having to do it ?

2/ On macOS, when your cursor is at the top of the screen. The macOS topbar and window bar will show up. Is it possible to disable it ? Like a video game where you can be in full screen mode but your cursor can be on the top of the screen without triggering macOS to show the topbar.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
