### ISSUE TITLE
[Feature Request]: Extend support for  Tray Menu

### ISSUE THREAD

**Issue by npc1437** [electron/electron#37133]
Can consider whether to add switch on menu，look like Figure

<img width="296" alt="image" src="https://user-images.githubusercontent.com/40747064/216745280-8b53c0cb-13dd-4bc1-97fe-c9abb641fe78.png">

**Comment by VerteDinde** [comment]
Hey @npc1437, can you say more about what APIs or support specifically you'd like to see from Electron here to support this feature?

**Comment by npc1437** [comment]
@VerteDinde  The menu add to tray can support switch button like picture,thanks!

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
