### ISSUE TITLE
Many small tasks (performance monitor)

### ISSUE THREAD

**Issue by jdgjsag67251** [electron/electron#37143]
We were experiencing a performance issue in our app and used the Performance tab in the DevTools to try to debug it; we noticed that a lot small tasks are created. The DevTools don't give us much information as to what these tasks are. Could somebody give us a hint as to what this could be?

![image](https://user-images.githubusercontent.com/88368191/216957242-ca16864b-7957-45e7-aa44-bc72f1367cac.png)

We use React and noticed that if we delay rendering using `useTimeout` the problem goes away.

Electron version: 20.3.6
OS: Windows 11 Home 22H2 (x64)

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
