### ISSUE TITLE
How to resolve blank screen when we try to login microsoft login while running the electron application via automation script?

### ISSUE THREAD

**Issue by sowmiya410** [electron/electron#37204]
1.Launching the electron application
2.Clicking on "Login with Microsoft Account"
![image](https://user-images.githubusercontent.com/40947711/217777842-b976b104-b5c4-48d2-9771-2e5624078613.png)

3.Got the below popup to enter the Microsoft account: (But, this is not loading while launch the application via automation script)
![image](https://user-images.githubusercontent.com/40947711/217777879-06dcf1f7-384d-40f9-8109-a97d990cdd95.png)

But Login page gets loaded as below while opening the application manually:
![image](https://user-images.githubusercontent.com/40947711/217777936-3f60a4a2-4a3a-4263-8c94-8d282105af54.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
