### ISSUE TITLE
[Bug]: Chromium fails to render UI when window is hidden

### ISSUE THREAD

**Issue by fanchenio** [electron/electron#37349]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.4.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

#16169
Same as the above problem, this problem is still not resolved, is there any solution?

### Actual Behavior

The UI can also be rendered when the window is hidden.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
