### ISSUE TITLE
[Bug]: electron Interface stuck When the computer resume from sleep

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#37361]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

ia32

### Expected Behavior

When the computer resume  from sleep, the electron window appears black screen or freezes, I want to know the cause of the stuck, and how to detect and fix it。

### Actual Behavior

When the computer resume  from sleep, the electron window appears black screen or freezes, but the ui thread is active (My js code executes normally and cpu usage is normal)。Then when i call window.show() it recover。

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
