### ISSUE TITLE
electron auto-updater not working as intended

### ISSUE THREAD

**Issue by MrFiend179** [electron/electron#37392]
` autoUpdater.checkForUpdates()
      autoUpdater.forceDevUpdateConfig = true
      autoUpdater.autoDownload = false
      window.webContents.on('did-finish-load', () => {
        const vltsnd = 'ola amigo'
        window.webContents.send('sndinf', vltsnd)
        autoUpdater.on('update-available',(info)=>{
          window.webContents.send('updtinf')
        })
        autoUpdater.on('update-not-available',()=>{
          window.webContents.send('updtinfnl')
        })
        autoUpdater.on('error',(error)=>{
          window.webContents.send(error)
        })
      }) `
so this is my code it is being handled in renderer js file but even after packaging it from electron-builder it doesnt tell me if there is update available or not or if theres an error

`autoUpdater.setFeedURL({
  provider: 'github',
  owner: 'MrFiend179',
  repo: 'Flubel-System-Info',
  token: 'ghp_uMZBZikwI9P03x5ksadjnaskjdasjdnasT',
  releaseType: 'release'
})`
This is my setFeedURL

**Comment by dsanders11** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
