### ISSUE TITLE
[Bug]: BrowserWindow rendering error with setting frame:false,transparent:true and resizable:true 

### ISSUE THREAD

**Issue by Aze-ziv** [electron/electron#37400]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Window render correctly.

### Actual Behavior

The window appears but is completely transparent

### Additional Information

![185b488abf38fc859be1fc8f953829e](https://user-images.githubusercontent.com/45890545/221110635-5705567e-f620-44e8-8abd-fd3234e669aa.png)
Graphics card: AMD Radeon R5 200 Series.
The version I downloaded from npm is 21.3.1, but when npm install, it shows that the downloaded version is 21.4.2.
I found information that some systems cannot enable transparent and resizable at the same time, but I did not find relevant instructions in the official website documents.
Or is this because of the amd cpu?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
