### ISSUE TITLE
[Bug]: webContent cant run in Windows7 Server Pack 1

### ISSUE THREAD

**Issue by AKA-LittleCow** [electron/electron#37433]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Windows

### Operating System Version

windows 7 sp1

### What arch are you using?

x64

### Last Known Working Electron version

19.0.8

### Expected Behavior

I hope to use webContent on windows7sp1

### Actual Behavior

 Cannot read properties of undefined (reading 'webContents')

### Additional Information

The following error occurred when my electric program was running on the operating system windows7 serve pack 1: Cannot read properties of undefined (reading 'webContents'). The general meaning of my code is to display and hide windows through webContext. This problem does not occur on other operating systems higher than Windows 7 SP1.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
