### ISSUE TITLE
[Feature Request]: Support TLA (top level await)

### ISSUE THREAD

**Issue by TomasHubelbauer** [electron/electron#37492]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi, I searched for `is:issue "top level await"` to no avail.

I am having trouble even searching the Internet for this so I am opening this feature request in part as a request for clarification as well as to help other search engine users.

I would like for Electron to support top level await.

TLA looks like this:

`main.js`
```javascript
// No wrapper function!
await doSomething();
```

Specifically, this request comes about because I have found it is possible to work around Electron's lack of support for ESM by using dynamic `import`. That means I can do this and avoid using `require` that way:

```typescript
void async function () {
  const electron = await import('electron');
  const window = new electron.BrowserWindow({ width: 1024, height: 300 });
}();
```

Until ESM is supported, this is a fine way for me to simulate something that at least resembles it, but the wrapper function is just noise. With TLA, the code could look like this:

```typescript
const electron = await import('electron');
const window = new electron.BrowserWindow({ width: 1024, height: 300 });
```

This will make it easier to rewrite to ESM once ESM is supported:

```typescript
import electron from 'electron';

const window = new electron.BrowserWindow({ width: 1024, height: 300 });
```

### Proposed Solution

Support TLA if technically feasible

### Alternatives Considered

Do not support TLA - but why?

**Comment by mattlucock** [comment]
Someone probably knows a lot more about this than I do, but I don't think what you're asking for makes sense; I think you're confused about top-level await. Top-level await is a feature of ESM, and it works because the ESM loader is asynchronous; loading and executing an ES module is an asynchronous process. Hence, top-level await simply delays the ESM loader's import of your module. Top-level await only works in ESM, and it wasn't possible at all prior to the advent of ESM (you could, of course, emulate it with an async IIFE as you show in your example).

You seem to be suggesting that Electron should support top-level await even without supporting ESM, but more than just being technically infeasible, I don't see how it makes sense; I can't conceive of a way it could work. I expect this why you didn't find any issues specifically asking about top-level await; Electron supporting top-level await is the same issue as Electron supporting ESM.

You use the dynamic `import()` method in your example, but it's very unclear to me what the advantage of this is; `electron` is CJS, so you can just `require` it. In this case, `await import('electron')` seems literally equivalent to `require('electron')`, except importing it as ESM is actually worse in this case because it's (unnecessarily) asynchronous. The reason you're asking for top-level await is so that you can do this, so... I don't know about that. But top-level await is a good and useful feature regardless.

The simple workaround that I believe is discussed in #21457 is to run your app as ESM, but have the entry point be CJS. This can be achieved simply with a very short CJS script that dynamically `import()`s your real app script and does nothing else. This essentially lets you pretend that Electron supports ESM even though it doesn't (see [this comment](https://github.com/electron/electron/issues/21457#issuecomment-1267951303) for the very minor caveat), and have all the benefits of ESM, including top-level await. It's a little clunky, but Electron is a little clunky.

I would love to complain more about Electron's failure to support ESM, but that would be off-topic for this issue.

**Comment by TomasHubelbauer** [comment]
@mattlucock On second though, you're right, supporting TLA must necessarily mean supporting ESM and there are other issues for supporting ESM. I didn't think of it that way when I was opening the ticket, but you've connected the dots for me and now I get it. Thanks for the very useful links! I appreciate you taking the time to write this. Closing now to reduce noise and allow the ESM-related tickets to receive the attention they deserve.

**Comment by TomasHubelbauer** [comment]
FWIW Electron now supports ESM and TLA in case that's useful to future web search travelers!
