### ISSUE TITLE
Whether to consider python

### ISSUE THREAD

**Issue by monkeycc** [electron/electron#37499]
https://github.com/flet-dev/flet
https://flet.dev

Based on the Flutter framework,

I think it can be based on Electron,

Python calls the Electron component directly

![微信截图_20230306115444](https://user-images.githubusercontent.com/6490927/223016004-37214968-58d1-4a82-bdba-59bccac56a05.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
