### ISSUE TITLE
[Bug]: macos arm64 can not get dump file

### ISSUE THREAD

**Issue by cqmonly** [electron/electron#37519]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

macOS

### Operating System Version

macos monterry 12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

20.0.0

### Expected Behavior

in arm64 , can get dump file

### Actual Behavior

in arm64 , can  not get dump file

### Additional Information

I am using electron app on m1 machine.
 My app is built x64. On x64, if the application crashes, it is possible to generate a dump file. But on macos of arm64, it cannot be generated. I tested the electron fiddle and found that the x64 version can't generate a dump file, but the arm64 version can. 
May I ask how should I deal with it now? Do I need to build my application using arm64 to get the dump file on m1? grateful

`
crashReporter.start({uploadToServer:false, ignoreSystemCrashHandler:true});

// and later 

setTimeout(()=>{
    process.crash();
}, 5000)
`
electron fiddle build for x64 : not dump file

electron fiddle build for arm64: has dump file

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
