### ISSUE TITLE
[Bug]: window.close() not working

### ISSUE THREAD

**Issue by t57ser** [electron/electron#37545]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.3

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

Window should close

### Actual Behavior

Window does not close

```
electron.app.whenReady().then(()=>{
	let main = new electron.BrowserWindow({
		"height" : 700,
		"width" : 800,
		show: true,
		webPreferences: {
			nativeWindowOpen: true,
		}
	});

	main.webContents.loadURL("https://www.youtube.com");
})
```
Open the devtools
execute the following:
`var w = window.open("https://www.google.com");`
After the window opens do:
`w.close();`
Nothing happens

**Comment by codebytere** [comment]
@t57ser this looks to be oddly specific to google itself - try another page and it works just fine. If more info comes to light I can look further but I'm not able to repro it further, and so from an impact perspective this probably isn't something we can look into much more.

**Comment by t57ser** [comment]
That does indeed seem to be the case. I did not notice that.
One interesting thing to mention. When opening google the window object (within the opener) shows the child.closed property to be true even though no window.close has been triggered yet

**Comment by t57ser** [comment]
I can reproduce this in Chrome, so this is a chromium issue.

**Comment by codebytere** [comment]
@t57ser great - if you could file a bug upstream it'll probably get fixed before long! And re. your second comment - yes, the child.closed` property shows `true` originating [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/dom_window.cc;l=107;drc=79bb66cf71ad8038b36faa4bf742a42c0a300a0b?q=closed%20focus%20close%20window%20-f:out%20&sq=package:chromium) because it seems that the frame is missing when google is loaded, which triggers the second condition!

**Comment by wheezard** [comment]
Isn't that a security feature? Scripts can't get access to frames (and windows) with other origins, so they can't close them!
```js
const w = window.open('https://youtube.com');
w.close()
```
^ This works just fine on youtube but *will not work* on google because the origins are different!

Also, Firefox has the same behavior, though I haven't yet found this behavior being described in any web standards

**Comment by wheezard** [comment]
[Found it.](https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-window-close)

The 7th step's check fails on pages of different origins because they wouldn't be [*"familiar"*](https://html.spec.whatwg.org/multipage/document-sequences.html#familiar-with) with each other

So, this is neither a bug in Chromium, nor in Electron, this is intended behavior.
