### ISSUE TITLE
How can I specify a build number of my current app version?

### ISSUE THREAD

**Issue by lincdh** [electron/electron#37540]
In package.json I can set the version with key version: '1.0.3'.

However, this will result in a build when uploading to Appstore Connect to be 1.0.3(1.0.3).

What I want to to increment the build number each time I upload like 1.0.3(1.0.0) then 1.0.3(1.0.1), 1.0.3(1.0.2), ...

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
