### ISSUE TITLE
Arm32 support?

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [electron/electron#37557]
I just recently got a Surface RT and was looking to port Spotify or even Discord to it. 

Specifically, my RT is the 64 gigabyte model running Windows 10, build 15035. ![image](https://user-images.githubusercontent.com/8545874/224512372-9d8760c3-f218-4a78-8b09-1037c4c34b4f.jpeg)

This would make a lot of RT device owners happy, I'm sure.

**Comment by Prinzhorn** [comment]
https://github.com/search?q=repo%3Aelectron%2Felectron+Arm32&type=issues
https://github.com/electron/electron/issues/29040

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
