### ISSUE TITLE
[Bug]: Cookie is not set from parition when domain is present

### ISSUE THREAD

**Issue by ncrmro** [electron/electron#37568]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Venture 13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The following code when a valid session cookie is set in the rederer throws the following error. I am able to set a cookie when no domain is present.

```
(node:52646) UnhandledPromiseRejectionWarning: Error: Failed to parse cookie
```

```typescript
const createWindow = async (): Promise<void> => {
  console.log();
  const partitionSession = session.fromPartition("persist:federated");
  const sessionCookie = store.get("__session");
  if (sessionCookie) {
    await partitionSession.cookies.set(sessionCookie);
  }

  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      /**
       * The next two items are not normally set and required
       * because of our nodejs usage
       */
      nodeIntegration: true,
      contextIsolation: false,
      partition: "persist:federated",
      session: partitionSession,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
  const cookies = mainWindow.webContents.session.cookies;
  cookies.on("changed", (event, cookie, cause, removed) => {
    if (cookie.name === "__session")
      store.set("__session", {
        url: "http://localhost:3000",
        name: cookie.name,
        value: cookie.value,
        domain: cookie.domain,
        path: cookie.path,
        secure: cookie.secure,
        httpOnly: cookie.httpOnly,
        sameSite: cookie.sameSite,
      });
  });
};
```

### Actual Behavior

A cookie should be set when the domain option is present.

### Testcase Gist URL

https://gist.github.com/8ee681e77bbcf7603642532fc27b0334

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ncrmro** [comment]
@nornagon hellow, I've attached a repo that demonstrates the error in the testcase gist URL on startup it will print the error.

**Comment by Spencer17x** [comment]
By design, domain names must have at least two dots; otherwise the browser will consider them invalid. (See reference on http://curl.haxx.se/rfc/cookie_spec.html)
When working on localhost, the cookie domain must be omitted entirely. You should not set it to "" or NULL or FALSE instead of "localhost". It is not enough.
reference: https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain

**Comment by ncrmro** [comment]
My example has a domain with two dots in it that throws an error thought

**Comment by ckerr** [comment]
@ncrmro is it possible to reproduce this issue without third-party dependencies? The testcase you're linking to skipped over [this request](https://github.com/electron/electron/issues/37568#issuecomment-1467067485) for a test case without any third-party dependencies?

**Comment by ncrmro** [comment]
Hello I've provided a gist here

https://gist.github.com/8ee681e77bbcf7603642532fc27b0334

**Comment by codebytere** [comment]
It doesn't appear that it's related to including a domain at all - it's that your domain in this case is invalid per requirements. I've opened a PR to better surface errors.

**Comment by ckerr** [comment]
> You can
> 
> By design, domain names must have at least two dots; otherwise the browser will consider them invalid. (See reference on http://curl.haxx.se/rfc/cookie_spec.html) When working on localhost, the cookie domain must be omitted entirely. You should not set it to "" or NULL or FALSE instead of "localhost". It is not enough. reference: https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain
> 
> Or you can use `domain: "localhost"`

@ncrmro this documentation appears to be in error or obsolete and I think is the root of the misunderstanding?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent looks more accurate:

> The Domain attribute specifies which hosts can receive a cookie. If the server does not specify a Domain, the browser defaults the domain to the same [host](https://developer.mozilla.org/en-US/docs/Glossary/Host) that set the cookie, excluding subdomains. If Domain is specified, then subdomains are always included. Therefore, specifying Domain is less restrictive than omitting it. However, it can be helpful when subdomains need to share information about a user.
>
> For example, if you set Domain=mozilla.org, cookies are available on subdomains like developer.mozilla.org.

This is more consistent with my understanding of domains and also has the benefit of working.

I think it won't [_always_](https://publicsuffix.org/) be a single dot though, depending on the domain, so the important part is the domain after the public suffix, rather than counting the number of periods :smile_cat:
