### ISSUE TITLE
[Bug]: electron: Failed to load URL: <https url> with error: ERR_TIMED_OUT

### ISSUE THREAD

**Issue by SShnoodles** [electron/electron#37631]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.2 LTS

### What arch are you using?

x64

### Expected Behavior

I built it on Manjaro and it works fine.
But when running on ubuntu, white screen. an error is thrown.

I just packaged a website. And set some commandLines
```
app.commandLine.appendSwitch("--disable-http-cache")
app.commandLine.appendSwitch('--ignore-certificate-errors', 'true')
```

### Actual Behavior
White screen after opening
I'm sure the network is working properly.

Error logs
```
[1078020:0321/133618.260312:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(node:1077987) electron: Failed to load URL: https://xxx.xxx.com/ with error: ERR_TIMED_OUT
[1078020:0321/133645.583660:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[1078020:0321/133649.572918:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[1077987:0321/133743.951127:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for xxx.xxx.com failed:
----- Other errors (not certificate specific) -----
ERROR: Deadline exceeded


[1077987:0321/133743.951193:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for redirector.gvt1.com failed:
----- Other errors (not certificate specific) -----
ERROR: Deadline exceeded
```

**Comment by SShnoodles** [comment]
I found that as soon as I started pcscd(PC/SC Smart Card Daemon), it failed to load.

**Comment by jaovitubr** [comment]
When I try to load specific sites, the error **ERR_CERT_DATE_INVALID** occurs, the browser loads normally.
When I set it to ignore certificate errors, the error **ERR_TIMED_OUT** appears
I'm thinking that the problem is with **Let's Encrypt** certificates, when I try to access for example https://letsencrypt.org or https://www.nginx.com/ it doesn't load, but when I try to access https://www.mozilla.org/ or https://www.google.com/ loads fine!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by koraybilgi** [comment]
@SShnoodles did you able figure out the problem?
