### ISSUE TITLE
[Bug]: Is there a way to manage bluetooth permissions on Desktop (MacOS, Windows and Linux)? 

### ISSUE THREAD

**Issue by AElbert** [electron/electron#37673]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 

### What arch are you using?

x64

### Expected Behavior

Some way to handle the bluetooth permissions when they were denied.

### Actual Behavior

I am developing an app on MacOS but if I don't grant the permission the only way is to grant it from the settings.

Is there any way to handle permissions when they have been denied so that the app asks for permission again?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
