### ISSUE TITLE
[Bug]: Electron builds binary with BT dll dependency

### ISSUE THREAD

**Issue by JeanPaulLucien** [electron/electron#37686]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

Binary will not use BT DLL, because there is no features about bluetooth.

### Actual Behavior

Binary use DLL for bluetooth.

### Additional Information

Binary (ready to use application) use DLL for bluetooth. Binary for Desktop and application has not features for bluetooth.

**Comment by jkleinsc** [comment]
@JeanPaulLucien Electron ships with Bluetooth support because we support [Web Bluetooth](https://www.electronjs.org/docs/latest/tutorial/devices#web-bluetooth-api).  If this is a problem for you, you would have to create your own Electron builds with Electron and Chromium patches to completely disable/remove bluetooth.  It would be a pretty large undertaking to do so.

For more information, check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
