### ISSUE TITLE
[Bug]: Running electron in docker with nodeIntegration: true enabled will not start electron

### ISSUE THREAD

**Issue by 343058360** [electron/electron#37712]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Other Linux

### Operating System Version

node:14.17-alpine

### What arch are you using?

x64

### Last Known Working Electron version

16.0.2

### Expected Behavior

Running electron in docker with nodeIntegration: true enabled will not start electron

webPreferences: {
    devTools: true,
    contextIsolation: false,
    nodeIntegration: true,
},

Dockerfile

FROM node:14.17-alpine
WORKDIR /workspace
COPY . .

CMD npm run electron:serve
EXPOSE 80

### Actual Behavior

Running electron in docker with nodeIntegration: true enabled will not start electron

docker runing no error

### Additional Information

Running electron in docker with nodeIntegration: true enabled will not start electron

**Comment by 343058360** [comment]
supplementary instruction: "vue-cli-plugin-electron-builder": "~2.1.1",

**Comment by ckerr** [comment]
Hi @343058360, thanks for reporting this issue!

Electron 16 reached end-of-support in [May 2022](https://www.electronjs.org/docs/latest/tutorial/electron-timelines), so the next step is, could you please test and see if the problem persists in a [newer version of Electron](https://github.com/electron/electron/releases), e.g. 23 stable or 24 beta.?

Also, Electron's maintainer team is pretty small, so issues that require a maintainer to copy someone's setup in order to test -- like this issue's Docker dependency -- usually get triaged last because of the extra time involved. Is there any error message or other information that might be actionable to the Electron maintainers without having to copy your setup? Otherwise, is there any way you can narrow down the repro steps to something only involving Electron without third-party tools?

Thanks for your understanding!

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
