### ISSUE TITLE
[Bug]: Automation problem in windows server os

### ISSUE THREAD

**Issue by sagarrabadiya** [electron/electron#37718]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.x

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 10 server 2016, Windows 10 server 2019

### What arch are you using?

x64

### Expected Behavior

I am using robot.js and nut.js for automation of keyboard and mouse, it works as expected on normal process when no administrator privileges are required, but if UAC or anything that requires administrator privileges it should work automation as well.

### Actual Behavior

robot.js and nut.js works in normal process mode, but when I run the same process with administrator privileges it doesn't work, keyboard mouse doesn't work when in administrator mode. I am running the process using windows command line, and exact same application using command line process works in windows 10 and 11 regular os (not server) the I am facing is only with windows server OS, please provide some guidance.

**Comment by ckerr** [comment]
Hi @sagarrabadiya, thanks for reporting this issue.

From the description, I'm 50-50 on this ticket:

- If you think this might be a configuration issue and are looking for help troubleshooting, check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that may be able to answer this question.should be willing to point you in the right direction. 

- If you think this is a bug in Electron itself, Electron 17 reached end-of-support in [August 2022](https://www.electronjs.org/docs/latest/tutorial/electron-timelines), so the next step would be for you to see if the problem is still there in a [newer version of Electron](https://github.com/electron/electron/releases), e.g. 23 stable or 24 beta. Also, Electron's maintainer team is pretty small and so doing triage on issues that arise in combination with third-party tools, like robot.js and nut.js here, usually don't get addressed. Is there any error message or other information that might be actionable to the Electron maintainers without having to copy your setup; or alternately, is there any way you can narrow down the repro steps to something only involving Electron without third-party tools?

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
