### ISSUE TITLE
[Bug]: Electron network process is holding onto SOCK type files even when the window is destroyed and over due time the Open files count is increasing and Resulting in electron network process crash.

### ISSUE THREAD

**Issue by p1kumarn** [electron/electron#37734]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Other Linux

### Operating System Version

NAME="Oracle Linux Server" VERSION="8.5"

### What arch are you using?

x64

### Expected Behavior

Once the window is destroyed - we expect that all the open files related to that window which are held by electron network process should be closed.

### Actual Behavior

Context : We are using electron in a Oracle linux server - which will show 15-24 websites on a 12 to 24 screen setup. 
Every time the content on a screen changes i.e. the URL which electron needs to load on a screen or browser window changes we are destroying the browser window and creating a new one. 

We have observed that over a period of time, say anywhere between 24 to 36 hours after starting up the electron - the Open files on the electron Utility network process is increasing and we could see that most of these files are of the Type SOCK. 

So our initial thought is that these are the SOCK files used to open outbound network connections and once the Window is destroyed - electron network process is holding onto them 

Could you please suggest if our analysis is in right direction 

### Additional Information

and some insights into how this works 
1. Electron receives the URLs though a persistent connection ( Single connection for PC )
2. Electron creates a window with the URL - which will establish a Server Sent Events peristent connection to backend to update content dynamically , and each window is a renderer process 
3. Once the URL needs to change electron destroys the window and sets up a new Window

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
