### ISSUE TITLE
Mouseenter event and mouseenter not working in build mode

### ISSUE THREAD

**Issue by juanmacaballeror** [electron/electron#37779]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I have a view created with vue 2.6.2 with quasar v1.11. In it I have the events mouseenter and mouseleave

It is desired that in executable mode it captures the mouseenter and mouseleave events. In development mode it works but when doing the build it doesn't work.

### Actual Behavior

It does not detect the mouseenter and mouseleave events after doing the build

### Additional Information

In development mode it works but when doing the mode build it doesn't work.

What happens in the build so that it doesn't work?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
