### ISSUE TITLE
[Feature Request]: How to implement functions similar to nwjs domain parameters in Electron

### ISSUE THREAD

**Issue by huangjunchao** [electron/electron#37816]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

How to implement functions similar to nwjs domain parameters in Electron

### Proposed Solution

Accessing local files within the system is no longer done through the file://path, similar to Chrome- extension://domain Form of

### Alternatives Considered

Accessing local files within the system is no longer done through the file://path, similar to Chrome- extension://domain Form of

### Additional Information

Accessing local files within the system is no longer done through the file://path, similar to Chrome- extension://domain Form of

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
