### ISSUE TITLE
[Bug]: Window Always on top is not working when any other app is on full screen

### ISSUE THREAD

**Issue by singhiam** [electron/electron#37865]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

macOS

### Operating System Version

Mac M1 Pro

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

11.0.0

### Expected Behavior

I am using code this way :

mainWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
mainWindow.setAlwaysOnTop(true, 'floating', Number.MAX_VALUE);
mainWindow.setFullScreenable(false);

App should be always on the top for all the applications. 

### Actual Behavior

App is currently on the top usually but any time any other application like Chrome, Zoom or any other app gets into full screen mode my electron app is no longer always on top.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
