### ISSUE TITLE
[Bug]: Fs it in electron. Asar file, knowledge as a folder by mistake

### ISSUE THREAD

**Issue by lei006** [electron/electron#37959]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Just tested 21.3.1 24.1.1 these two versions

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Using the fs traversed, found that as long as it is. Asar files, will be for a folder!
But I but have not found this problem in the node!

`var fs = require('fs');

let file_path = "C:\\Users\\Administrator\\Desktop\\123123\\app.asar";
var file_stat = fs.statSync(file_path);

console.log("isFile:", file_stat.isFile());
console.log("isDirectory:", file_stat.isDirectory());
console.log(file_stat);`

![image](https://user-images.githubusercontent.com/5562875/231648419-22ccb5b6-d582-4990-8648-df7014cf097d.png)

### Actual Behavior

`var fs = require('fs');

let file_path = "C:\\Users\\Administrator\\Desktop\\123123\\app.asar";
var file_stat = fs.statSync(file_path);

console.log("isFile:", file_stat.isFile());
console.log("isDirectory:", file_stat.isDirectory());
console.log(file_stat);`

![image](https://user-images.githubusercontent.com/5562875/231648800-764f0be0-1e7a-485b-b7d9-6821d5c63083.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
