### ISSUE TITLE
[Question] access to ENV var during production runtime

### ISSUE THREAD

**Issue by ferllings** [electron/electron#37951]
I have a electron + angular app.
Before to fully start the app checks for some configured env vars, like JAVA_HOME.
In dev mode, it works fine:
I can fully access the vars using process.env.
In production/packaged mode only a limited set of env vars are listed.

This is probably a desired behavior, rather than a bug, for security reason, but
I'm not sure whats causing this. electron-builder? Angular? the builder/webpack process?
and if it possible to access a specific set of env vars.

Thanks for your help.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
