### ISSUE TITLE
[Release Request] Could you please make a follow-up release for #37863

### ISSUE THREAD

**Issue by zeeker999** [electron/electron#37979]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows/macOS

### What arch are you using?

x64

### Expected Behavior

Thank you for fixing the defaultFontFamily bug(#37863).  Could you please make a follow-up release to make this fix available to stable branch users? We plan to use this feature and encountered this bug... 

### Actual Behavior

N/A

**Comment by VerteDinde** [comment]
Hey @zeeker999, sure thing 🙂 Two releases are currently running for E23 and E24. They should be done in the next 2-3 hours.

For the future: Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. If you want to leave future requests in our [Discord](https://discord.gg/electron) you should still get a fast response.

**Comment by donatocayurin** [comment]
Thank you ❤️🙏
