### ISSUE TITLE
[Bug]: how to safe restart gpu-process

### ISSUE THREAD

**Issue by acklj1** [electron/electron#38001]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.11

### What operating system are you using?

Other Linux

### Operating System Version

centos

### What arch are you using?

x64

### Last Known Working Electron version

19.0.11

### Expected Behavior

app do not whitescreen

### Actual Behavior

when I run electron app long time
There's a certain chance gpu-process use cpu 100% and app whitescreen
then I kill -s 9 {gpu-process pid}, the back to normal

and I write code setinterval per 5 second kill gpu-process
even kill 4- 5times app crash

one may ask, how to safe restart gpu-process

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
