### ISSUE TITLE
[Bug]: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getSources')

### ISSUE THREAD

**Issue by Kubzelll** [electron/electron#38019]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

I want to make this working

### Actual Behavior

I want to create screen recorder in electron but error occure
Code:
Main js: https://gist.github.com/Kubzelll/9bcfae6b09cd6246691ef6ee5253e09e
render file: https://gist.github.com/Kubzelll/ab4bd7cd880e31631d8d5048adf70c4d

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
