### ISSUE TITLE
./node_modules/electron/index.js:1:0 Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by KingofMidnight** [electron/electron#38022]
i have been trying to use app.exposeFunction from electron but from what I have been seeing fs is I think down, does someone know how I can do something about this

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
