### ISSUE TITLE
How to show stack up notification like Microsoft Teams in Electron Application for Windows.

### ISSUE THREAD

**Issue by AmHackish** [electron/electron#38049]
I am trying to show multiple toast notification together like we receive in Teams, but getting the Notification one by one, can somebody help me with that

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by Slapbox** [comment]
I don't think this is solely a support question since it seems that this functionality cannot be leveraged with Electron; so I don't think it should be closed even though it failed to follow the issue template.
