### ISSUE TITLE
How to add custom installer for DMG?

### ISSUE THREAD

**Issue by malapashish** [electron/electron#38045]
I want to package my application for MAC in DMG format, but I also need to run a script while the application is being installed.

For NSIS we have include to pass the script.

Is there something similar for DMG?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
