### ISSUE TITLE
[Bug]: XHR User-Agent

### ISSUE THREAD

**Issue by tahafatih** [electron/electron#38053]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Issue
I am developing an application with Electron and using Axios for communication, but I am getting a "Refused to set unsafe header 'user-agent'" error. When I tried with XHR, I still received an error.

![Ekran görüntüsü 2023-04-21 023816](https://user-images.githubusercontent.com/45592550/233508339-5a11b76e-d0f4-4631-8745-2c9214c7fe6a.jpg)

**Comment by Prinzhorn** [comment]
Are you seeing different behavior in Chromium? I'm getting the same error in Chromium, so this doesn't appear to be an Electron issue at all.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! I agree with Prinzhorn, this issue seems to be the same as current behavior in Chromium. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
