### ISSUE TITLE
[Bug]: v0.3.731 not connecting to OBS requiring name and still showing red 

### ISSUE THREAD

**Issue by Rentella** [electron/electron#38070]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v0.3.731

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

the program to work and have no errors

### Actual Behavior

it doesn't connect even after closing,reopening and re downloading.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out. I will note - you're using a version of Electron that has been EOL for some time, and I'd try updating that version to see if it works better.
