### ISSUE TITLE
[Feature Request]: How to obtain the path of the exe file generated by Electron when opened on the window platform

### ISSUE THREAD

**Issue by hong418884611** [electron/electron#38085]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If I create a shortcut and place it on the desktop, I would like to obtain the path when the shortcut is opened, not the installation path. Which method do I need to call to implement it（Right click on the general path address）

### Proposed Solution

Obtain the path when the current exe is opened, not the actual installation path

### Alternatives Considered

nothing

### Additional Information
electron api
app.getPath
node
__dirname
Can't even achieve it

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
