### ISSUE TITLE
[Bug]: This is not a bug，and What method should I use to open a drop-down window in the top toolbar, similar to the image below

### ISSUE THREAD

**Issue by TJX666666** [electron/electron#38130]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^21.2.0

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/51389459/234825446-795fd8e4-0b74-4c41-ba29-236d4463505b.png)

### Actual Behavior

i could't do it by current api

**Comment by TJX666666** [comment]
top tools is generated ：new BrowserWindow()

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
