### ISSUE TITLE
[Bug]: Accessing `BrowserWindow.id` throws an error after the window is closed/destroyed

### ISSUE THREAD

**Issue by schontz** [electron/electron#38170]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to get the `id` of a `BrowserWindow` object, regardless of whether or not it is closed or destroyed. I expect the following to work:

```
win.on('closed', () => {
  console.log('window closed, id=', win.id);
}
```

### Actual Behavior

It throws an error:

```
TypeError: Object has been destroyed
    at BrowserWindow.<anonymous> (**/main.js:20:60)
    at BrowserWindow.emit (node:events:513:28)
```

### Testcase Gist URL

https://gist.github.com/d1819a38f1a9327ae56d4098b9d382d1

**Comment by Arshdeep-13** [comment]
The error message you are seeing indicates that the BrowserWindow object has already been destroyed and is no longer available. This means that you won't be able to access its id property or any other properties or methods associated with the object.

One way to work around this issue is to store the id of the BrowserWindow object in a separate variable before the window is closed or destroyed. For example, you could do something like this:
```javascript
let windowId;

win.on('closed', () => {
  console.log('window closed, id=', windowId);
});

win.on('ready-to-show', () => {
  windowId = win.id;
});
```
This code sets up an event listener for the closed event on the BrowserWindow object, which logs the windowId variable to the console. Before the window is closed, the ready-to-show event is triggered, which sets the windowId variable to the id of the BrowserWindow object. This way, even if the BrowserWindow object is destroyed, you will still have access to its id.

**Comment by schontz** [comment]
I understand that there are workarounds, but it still feels like a bug that accessing a readonly, primitive property could throw an error. Especially when things like `win.isDestroyed()` work.

**Comment by wheezard** [comment]
Though this is intended behavior, something like a `window.getID()` method would be a better alternative because getters aren't usually expected to throw.

**Comment by schontz** [comment]
I would expect a _method_ to throw, but not a _property_.
