### ISSUE TITLE
[Bug]: Unable to log WebRTC modules

### ISSUE THREAD

**Issue by pavigor** [electron/electron#38195]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

Is it possible to debug webrtc inside electron?

### Actual Behavior

For Google Chrome we can pass '--enable-logging --v=1' params and get detailed logs of webrtc engine. I've tried to set this params with:
`
app.commandLine.appendSwitch('enable-logging');
`
`
app.commandLine.appendSwitch('log-level','1');
`
`
app.commandLine.appendSwitch('v','1');
`
`
app.commandLine.appendSwitch('vmodule','*/webrtc/*=2');
`
or
`
app.commandLine.appendSwitch('vmodule','peer_*=2');
`
but get nothing.

So my question is - is it possible to enable webrtc logs by passing the same arguments as for Chrome ?

**Comment by pavigor** [comment]
Just tested with 24.2.0 - the same behavior, there are no logs of webrtc engine

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by oalfroukh** [comment]
Hi @pavigor 

Hope you're doing well!

Did you get any idea about this issues?

BR
