### ISSUE TITLE
[Bug]: Screen Recording is not working on macOS

### ISSUE THREAD

**Issue by gregoiregentil** [electron/electron#38190]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.x

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

Screen recording should work on macOS like it works on Linux or Windows.

### Actual Behavior

The following code which grabs the desktop, works on Linux and Windows platforms:

```
const mediaDevices = navigator.mediaDevices as any;
const sources = await (<any>window).electron.ipc.invoke("getDesktopSources");
let videoLive = await mediaDevices.getUserMedia({
	audio: false,
	video: {
		mandatory: {
			chromeMediaSource: "desktop",
			chromeMediaSourceId: sources[0].id
		}
	}
});
```

```
ipcMain.handle("getDesktopSources", async (event) => {
	const { desktopCapturer } = require('electron');
	const sources = await desktopCapturer.getSources({ types: ["screen"] });
	return sources;
});
```

**But on macOS, I receive the following error: "DOM Exception: Could not start video source". It happens ONLY on macOS.**
```
DOM Exception: Could not start video source
```

In order to give more details, I have added the screen recording permission for the terminal or for my app in the system preferences of macOS. Also, in the Electron part, I can do:
```
const { systemPreferences } = require('electron');
console.log(systemPreferences.getMediaAccessStatus('screen'));
```
and then I receive "granted".

Also, the following code which grabs the webcam, works on all platforms (Linux, Windows, macOS):

```
const mediaDevices = navigator.mediaDevices as any;
let videoLive = await mediaDevices.getUserMedia({
	audio: false,
	video: { facingMode: 'environment' }
});
```

Am I missing a permission or something for macOS? I have searched everywhere on Google/SO/Github, but I haven't found any clue. Or is this somehow a problem inside Electron? Thank you for any clarification if possible.

**Comment by gregoiregentil** [comment]
I have created a super small test case. It's working on Linux but not on macOS: https://gentil.com/tmp/test-desktop-macos.zip

The problem might be related to: https://bugs.chromium.org/p/chromium/issues/detail?id=1307502

Is this a problem only on Monterey / Electron?

(Strangely, in a standalone webpage on Chrome/macOS:
- without system preferences permission, I can see the screen preview in the Chrome screen tab but then it fails with a permission error.
- with the system preferences permission granted for Chrome, the screen preview in the Chrome screen tab is black (!) and I get the same error as above.)

Can anyone please confirm what I'm experiencing? Can anyone make this work?

**Comment by tomhaydn** [comment]
I can confirm that I'm also experiencign this issue with a similarly built app:

```
const constraints = {
      audio: false,
      video: {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: selectedSource, // <--- valid id
        },
      },
    };

    console.log('getting user media with: ', constraints);

    try {
      const stream = await navigator.mediaDevices.getUserMedia(
        constraints as any
      ); // fails here
```

In my case **I only experience the issue in the packaged version of my app.**

Electron version: 23.0.0
macOS: 13.3.1
Node: v14.21.3

**Comment by gregoiregentil** [comment]
@tomhaydn Thank you for stepping in and confirming that I'm not crazy!!!

It's still confusing if the problem is solely in macOS and if there are some workarounds to be implemented in Electron.

BTW, have you granted the permission of THE app in the system preferences when running the packaged version? Have you checked if you are getting a permission error or the "Could not start video source"?

**Comment by williamli0707** [comment]
This is actually really similar to an issue I'm having in https://github.com/electron/electron/issues/36529. Some other things I noticed about this bug: 

- When I build my app for Apple silicon and run the app on my M1 MBP, the app correctly asks for camera permissions. 
- However, when I build for Mac x64 with `electron-builder --mac --x64`, the app does not work on my M1 Mac through Rosetta nor through a x64 Mac - both on Ventura - with the same error "DOMException: Could not start video source".
- `navigator.permissions.query({name: 'camera'}) .then((permissionObj) => { console.log(permissionObj.state); })` logs "granted", even though System Preferences does not show the app in the Security and Privacy list. 
- This means it thinks it has access but doesn't really because it never requested access?
- The console shows `Prompting policy for hardened runtime: service: kTTCServiceCamera requires entitlement com.apple.security.device.camera but it is missing for responsible={TCCDProcess: identifier=<ID of InvalidCode>, pid=....`
- and also `This app has crashed because it has a hardened runtime and attempted to access privacy-sensitive data without an entitlement indicating its intent to access this data. The app must have the 'com.apple.security.device.camera' entitlement.`

Have you managed to fix this issue?

**Comment by williamli0707** [comment]
I fixed it by applying the fix [here](https://stackoverflow.com/questions/72024011/electron-app-not-asking-for-camera-and-microphone-permission-on-macos-monterey).

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by simo-an** [comment]
> I fixed it by applying the fix [here](https://stackoverflow.com/questions/72024011/electron-app-not-asking-for-camera-and-microphone-permission-on-macos-monterey).

Really ? I can't solve this issue by the link solution.

**Comment by simo-an** [comment]
Is there anyone who have solved this issue ?
