### ISSUE TITLE
[Bug]: How to only capture desktop audio with Electron? 

### ISSUE THREAD

**Issue by Wlitsoft** [electron/electron#38239]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.2

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

x64

### Last Known Working Electron version

24.1.2

### Expected Behavior

Get to the audio stream

### Actual Behavior

Prompts for device not found or crashes

### Additional Information

How to only capture desktop audio with Electron? The following code doesn't work, it only works when combined with video.

`navigator.mediaDevices.getUserMedia({
    audio: {
        mandatory: {
            chromeMediaSource: 'desktop'
        }
    }
})`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
