### ISSUE TITLE
[Feature Request]: Printer

### ISSUE THREAD

**Issue by AkhmedovSH** [electron/electron#38265]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

3

I have a web application, I need when take order then printout from desktop with ElectronJS desktop App.

But I have 3 printers and 3 Sections for order

Sample :

Pants Section, Socks Section, T-Shirt Section

When I get order like this : 2 Panths, 3 Socks, 1 T-Shirt

I need printout 3 order invoice own section printer

When I try this only I get 1 printout first order section:

### Proposed Solution

Have to work correctly not print only first printer device
_.forEach(printList, (printer)=>{
            let deviceName = printer.name;
            win.webContents.print(
                {
                    deviceName: deviceName,
                    silent: true,
                    printBackground: true,
                },
                (success, error) => {
                    if (success) {
                        resolve(true);
                    } else {
                        reject(true);
                    }
                }
            );
        });

### Alternatives Considered

...

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
