### ISSUE TITLE
[Bug]: The frequency word and custom statement of Microsoft IME not work when using partition session

### ISSUE THREAD

**Issue by alan-zhang** [electron/electron#38340]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19044.2846

### What arch are you using?

x64

### Expected Behavior

The frequency word and custom statement of Microsoft IME work normally when we using partition session to sperate instance

### Actual Behavior

The frequency word and custom statement works well on other IMEs except Microsoft IME on windows with partition session, but it works with default session and 'persist: name' session, however we don't want to persist the data, so why other IMEs works well? Is it a bug of Electron or Microsoft IME?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
