### ISSUE TITLE
electron+react打包后无法更改public里的文件

### ISSUE THREAD

**Issue by siifan168** [electron/electron#38374]
我现在是想在electron里面去更改react文件夹中的public文件里面的静态资源，但是我发现我不能打开public里的文件。好像是因为我打包后的react文件夹变成了一个app.asar文件

**Comment by bobby-palmer** [comment]
Translation according to google translate : "I now want to change the static resources in the public file in the react folder in electron, but I find that I can't open the public file. It seems to be because the react folder after I packaged it became an app.asar file"

**Comment by HackerWand** [comment]
可以在打包选项里把asar选项关闭就行，或者用asar工具解压出来修改完再压缩回去

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
