### ISSUE TITLE
Astrosharp not loading properly 

### ISSUE THREAD

**Issue by ikeysolomon** [electron/electron#38386]
Hi everyone, 

                   very new. The astrosharp load page does not come up for me. Just a blank screen with title bar. Running windows 11.

Any ideas?
Thanks, 
Sam

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Deepskyobservatory** [comment]
no help on the discord server, same problem here just a blank screen
