### ISSUE TITLE
[Bug]: The following error occurred when using window.open 

### ISSUE THREAD

**Issue by steady-join** [electron/electron#38486]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12

### What arch are you using?

x64

### Expected Behavior

Open the window normally
em... Open addresses such as https://www.baidu.com

### Actual Behavior
<img width="603" alt="image" src="https://github.com/electron/electron/assets/29935583/7093757a-8d08-47e1-a3b0-21e2b843c887">

How should I solve the problem? Thank you

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
