### ISSUE TITLE
[Feature Request]: Support full frame transparency with Mica background material

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#38532]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The [Mica `backgroundMaterial`](https://github.com/electron/electron/pull/38163) effect does not appear below the WebContents.

### Proposed Solution

The `backgroundMaterial` option should behave the same as when setting the `vibrancy` option.

| macOS: `vibrancy: 'medium-light'` | Windows: `backgroundMaterial: 'acrylic'` | Windows: `backgroundMaterial: 'acrylic'` + `transparent: true` |
| --- | --- | --- |
| ![Screenshot 2023-05-31 at 4 30 04 PM](https://github.com/electron/electron/assets/1656324/3f2a47e7-ed33-4f88-ae0d-2f67b1cb9b1d) | ![image (5)](https://github.com/electron/electron/assets/1656324/cb4c3a2e-284f-4a54-a968-7870af8be549) | ![image (6)](https://github.com/electron/electron/assets/1656324/318797e0-63ea-49d6-9feb-50cd66db0664) |

When `vibrancy` is set, the WebContents is transparent by default. The same should apply to `backgroundMaterial`. Setting `transparent: true` doesn't seem to be a valid workaround, but ideally should still work.

The code below needs to be updated:
https://github.com/electron/electron/blob/9ffffdb6ef202bd93be496b53fdd4156dd3504ce/shell/browser/api/electron_api_browser_window.cc#L58-L64

### Alternatives Considered

None.

### Additional Information

Tested on:
```
Edition	Windows 11 Pro
Version	22H2
OS build	22621.1778
```

Fiddle gist: https://gist.github.com/34cf667b21a5075d1f6fbe093d7ad7f9

**Comment by michalzaq12** [comment]
`backgroundMaterial` works well with `transparent: true`, but window cannot be frameless

**Comment by SHEN-Muchuan** [comment]
`transparent: true` works but it will set the window `frameless`, which will make the window unresizable. Does anyone have a potential solution?

**Comment by ttnn5876** [comment]
> `backgroundMaterial` works well with `transparent: true`, but window cannot be frameless

Do you know why it works like this?

**Comment by clavin** [comment]
I've been looking into this and I've discovered that something about the `remove_standard_frame` option in `views` is causing the background to be non-translucent. Still investigating...

**Comment by clavin** [comment]
This is what I have on my `clavin/frameless-bg-mat` branch with `remove_standard_frame` set to false:

![A window with the acrylic background material, but ](https://github.com/electron/electron/assets/9995434/808ba762-ec58-43e6-b0bd-f4c043475bc7)

Obviously, it has a frame, which is not great, but turning on the option causes the window to no longer be translucent, strangely. Still, it's progress 😄

**Comment by clavin** [comment]
I fiddled around more with this issue and I unfortunately am going to have to drop it for the time being.

Since I wasn't getting any traction modifying Electron & Chromium, I decided to try to see if making a window like this was even possible. In the end, I wasn't able to create a window that has no title bar (window title, controls, bg), but does have a frame (the rounded corners and resizable border around the window) while also applying the Mica or Acrylic window effects.

In my research I saw some possible WinRT solutions. I skipped these for the time being as I sensed they may require a bit of a refactor in Electron to get working.

Also, I didn't come across any code samples that demonstrate how to crate the type of window desired here. I did see some mentions that it is possible, but ultimately no proof or demonstration. 😕

Within Windows 11, I did notice that the Task Manager's performance charts have a detail mode that collapses the window (including the title bar!) to only show the chosen chart. This makes me think it is somehow possible, but unfortunately I don't quite know how to recreate the behavior.
