### ISSUE TITLE
[Bug]: Wrong publisher name("GitHub, Inc") on windows task list and startup menu.

### ISSUE THREAD

**Issue by jhlee8804** [electron/electron#38575]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Build 22621

### What arch are you using?

x64

### Expected Behavior

The publisher name of the app that appears in Windows Task Manager should be the my company name (ex: "miksystem inc.").
How can i change thease?

### Windows Task List
![image](https://github.com/electron/electron/assets/8110371/beeababf-b2f9-4b28-97aa-aaef721b4273)

### Startup List
![image](https://github.com/electron/electron/assets/8110371/e7f63940-977c-467e-9fa1-2471f267803e)

### Additional Information

I'm code signing with PFX certificate.

The following is the metadata from `Collaboration.exe.`
![image](https://github.com/electron/electron/assets/8110371/040884b1-4858-44dd-a704-df3ddd8bbf08)

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
