### ISSUE TITLE
[Bug]: DesktopCapturer includes magnified screen when capturing - possible to prevent this?

### ISSUE THREAD

**Issue by benank** [electron/electron#38624]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10/11

### What arch are you using?

x64

### Expected Behavior

The expected behavior is correct, currently: when capturing the entire screen with DesktopCapturer, it also captures the magnified contents of the screen rather than the non-magnified screen. (when using the magnifier tool in Windows - use Start and + to start the magnifier)

### Actual Behavior

Is it possible to exclude or prevent the magnified view from appearing in the screen capture in DesktopCapturer? I understand that it works fine when capturing a single window (eg. capture a window and then use magnifier to zoom in - window will not be magnified).

From what I understand, we should be able to exclude it from screen share if some native code is written and then the magnifier window is set so that it has content protection and doesn't appear in the captured screen. However, it would be great if there were another, easier way to do this. Are there any other possible solutions to this?

This is important to have in apps that have screen sharing because it enables users who have accessibility needs to be able to still share their screen with others without everyone having to see the magnified version.

### Testcase Gist URL

https://gist.github.com/benank/ad32081dc7d5d7cc6235a53d0de391ff

### Additional Information

Using the gist provided, the scenario can be replicated like this:
1. Start the fiddle - your screen will be captured and displayed in the app.
2. Open the magnifier and zoom in.
3. The Electron app will display the zoomed in version of the screen capture, not the original, non-zoomed version.

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by benank** [comment]
Thanks, I'll try that!
