### ISSUE TITLE
IpcRenderer.on listens for port events, and the obtained messagePort instance does not have a postmessage method

### ISSUE THREAD

**Issue by liushuai97020** [electron/electron#38725]
During the rendering process, IpcRenderer. on listens for port events. The instance obtained from event. ports [0] does not have a postmessage method, but this method can be called in the official document example. Why?

[Official Document Guide Link](https://www.electronjs.org/zh/docs/latest/tutorial/message-ports#setting-up-a-messagechannel-between-two-renderers)

Here is my code:
`const { ipcRenderer } = require("electron")
ipcRenderer.on('port', async (e) => {
  window.electronMessagePort = e.ports[0]
  console.log(e.ports[0])
  window.electronMessagePort.onmessage = messageEvent => {
    // console.log(messageEvent.data)
  }
  // window.electronMessagePort.start()
})`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
