### ISSUE TITLE
[Feature Request]: speed up Electron build process

### ISSUE THREAD

**Issue by wanted002** [electron/electron#38806]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I wonder is there any way to speed up the build of electron binary, especially the linking stage. Please guide me ,many thanks.
For me ,my laptop components are listed here: ubuntu18.04 , Intel Core i7 7th Gen CPU, 16G DDR RAM, and the src code is on an IDE disk . The linking stage is about 5 hours as I just changed one line of the C++ source code. 

### Proposed Solution

I' m a newbie to the build_tools and BUILD system of chromium, and in my opinion, most 'big size' components for electron, like node, libc++ ,v8 and third parties are static library, for debugging ,is it possible to change them into shared library ?

### Alternatives Considered

Maybe buy a strong laptop:)

**Comment by wanted002** [comment]
My electron branch to build is 23-x-y

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
