### ISSUE TITLE
[Bug]: protocol.handle() is blocked by WebContents.startDrag()

### ISSUE THREAD

**Issue by mike-wellner** [electron/electron#38845]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 10, Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

protocol.handle() should work while dragging elements with WebContents.startDrag() 

### Actual Behavior

Async function calls in protocol.handle() are blocked as soon as WebContents.startDrag() was called.
The blocked calls resume once the drag-and-drop operation ended.

### Additional Information

Hi, 
I am not sure if this is intentional. It seems off. I wrote a minimal reproducer.
This is an electron application reduced to the problematic function calls:
https://github.com/mike-wellner/reproducer-drag-and-drop-block

**Comment by mlaurencin** [comment]
Would it be possible for you to remake your test case using [Electron Fiddle](https://www.electronjs.org/fiddle)? Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Due to bandwidth, I think this would make triaging this issue easier to manage. It may also further remove unnecessary variables from the equation, and can provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.
