### ISSUE TITLE
Setting up IDE for Electron development

### ISSUE THREAD

**Issue by Imperat** [electron/electron#38934]
Hello,
I would like to change some Electron source code.
Now I am able to compile it from source code (I used [this](https://www.electronjs.org/docs/latest/development/build-instructions-gn) instruction).
I use CLion as my IDE and want properly setup auto-completion and navigation. I followed this [guide](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/clion.md#autocompletion) from Chromium project and tried [approach 1](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/clion.md#approach-1_using-cmakelists) and [approach 2](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/clion.md#approach-2_compilation-database)
It seems like CLion correctly index chromium source files, but ignores Electron files itself (which are stored in `electron/src/electron` directory:
<img width="772" alt="Screenshot 2023-06-27 at 11 51 52 am" src="https://github.com/electron/electron/assets/7069867/0cd60da6-f80f-48f2-960e-873670c51d85">

I would like to ask any maintainers to help with it :) I am mac user now. What IDE do you use for your development? Could you share some insights or hacks how to setup it properly? I am looking forward to contribute to the Electron project (at least share this knowledge in the docs to let the other developers setup their IDE easier).

**Comment by Imperat** [comment]
cc @refi64 @ckerr (I found you as recent contributors when performing `git blame`
@codebytere

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by Imperat** [comment]
Hi @MarshallOfSound 
Thanks for the feedback, it is much appreciated.

Sorry for asking question in "Issues", I'll go to Discord or use other means in future
