### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by donPablo2** [electron/electron#38945]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎8/‎16/‎2022 OS build	19044.3086 Serial number	PF3ZCH0E Experience	Windows Feature Experience Pack 1000.19041.1000.0

### What arch are you using?

x64

### Last Known Working Electron version

25.0.1

### Expected Behavior

Bookmarker app to come up
![image](https://github.com/electron/electron/assets/123344804/ffdc3d27-7ce2-4c2e-92aa-4e59c2a89506)

### Actual Behavior

Exception has occurred:  Error: not found: electron
occurs in C:\Program Files\nodejs\node_modules\npm\node_modules\which\lib\index.js   line 106

### Additional Information

get   https://github.com/electron-in-action/bookmarker
delete package.json
(delete app/package-lock.json if present)
(delete node_modules folder if present)
npm init --yes
npm install electron marked --save
npm ls electron   to confirm version 25.2.0
add script  "start": "electron .",
turn on stop for unexpected and expected
run the start script
see  Error: not found: electron
occurs in C:\Program Files\nodejs\node_modules\npm\node_modules\which\lib\index.js   line 106

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
