### ISSUE TITLE
Error with devtools

### ISSUE THREAD

**Issue by Wehaveall** [electron/electron#38966]
Hi, 

I am writing a simple code using a single window with a custom title bar e menus. Here is the code:

`const createWindow = async () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1200,
    height: 680,
    minWidth: 940,
    minHeight: 560,
    frame: false,
    webPreferences: {
        nodeIntegration:true,
        contextIsolation:false,
        devTools:true,
        preload: path.join(__dirname, 'preload.js')
        
    }
  })

  
  Menu.setApplicationMenu(mainMenu);
 
  // and load the index.html of the app.
 await mainWindow.loadFile('./src/index.html')
 
  // Forcing Open the DevTools, after shortcut not working
 mainWindow.webContents.openDevTools()`

At some point, which I did not get, **I noticed the shortcut "ctrl+shift+I" was not working**, so I found a way to force it open with " mainWindow.webContents.openDevTools()`"

However, when using it, a I get the following error in console after running the program: [33948:0702/031435.512:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

ps: tried reinstalling electron, clear app and electron cache without success.

Can anyone help me please? I am starting with JS and electron. Thanks in advance.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
