### ISSUE TITLE
[Bug]: openAtLogin does not work with Windows Store appx

### ISSUE THREAD

**Issue by hovancik** [electron/electron#38967]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^25.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

`app.setLoginItemSettings({ openAtLogin: value })` should make app start on next login and create an item in Windows Startup Apps

### Actual Behavior

Startup Apps item is not created and app does not start at login

### Additional Information

I googled around and found that apps via Store need different path (https://github.com/Teamwork/node-auto-launch#windows-app-store-apps) but I am not able to figure out what to put in there. Their implementation seems to not work anyway, but there is a PR with fix, so maybe inspiration: https://github.com/Teamwork/node-auto-launch/pull/111

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by hovancik** [comment]
@codebytere I am not sure whether I understand. `openAtLogin` does not work with appx and that is the fact, not a question. Or am I being silly?
