### ISSUE TITLE
how to hook the key events of the console, not the window

### ISSUE THREAD

**Issue by noname29** [electron/electron#38987]
https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts

I understand I can hook key events with this, for the BROWSER WINDOW. How can I do the same for the CONSOLE ?

in nodejs, it goes with `process.stdin.setRawMode(true)` YET `process.stdin.setRawMode` is not a property of the app as I run my application with `electron myapp.js` rather than `node myapp.js`

Please help... Thank you in advance

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
