### ISSUE TITLE
process.nextTick from dev tools doesn't fire until blurred

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#39]
Doing the following in the dev tools will not fire until the dev tools loses focus:

``` javascript
process.nextTick(function() {console.log('here?')})
```

**Comment by aka2024** [comment]
It looks like you're dealing with a **code injection** issue flagged by CodeQL. This type of vulnerability occurs when user input is directly evaluated as code without proper sanitization, allowing attackers to execute arbitrary code¹.

### Recommendations to Fix Code Injection

1. **Avoid Direct Evaluation**: Do not directly evaluate user input as code. For example, avoid using `eval()` or similar functions that execute strings as code.

2. **Sanitize User Input**: If you must include user input in an expression, ensure it is properly sanitized. Use context-specific escaping to prevent malicious code execution.

3. **Use Safe Methods**: Instead of constructing code from user input, use safe methods to handle user data. For instance, in template engines, use interpolation expressions that safely include user input.

### Example Fix

Here's an example of how to safely use a template engine without risking template injection:

```javascript
const express = require('express');
var pug = require('pug');
const app = express();

app.post('/', (req, res) => {
    var input = req.query.username;
    var template = `
doctype
html
head
    title= 'Hello world'
body
    form(action='/' method='post')
        input#name.form-control(type='text)
        button.btn.btn-primary(type='submit') Submit
    p Hello #{username}`;
    var fn = pug.compile(template);
    var html = fn({username: input});
    res.send(html);
});
```

In this example, the user input is included via an interpolation expression `#{username}`, which is provided as an option to the template, rather than being part of the template string itself¹.

If you need more detailed guidance or have specific questions about your code, feel free to ask!

Source : conversation avec Copilot, 22/09/2024
([1](https://codeql.github.com/codeql-query-help/javascript/js-code-injection/)) Code injection — CodeQL query help documentation - GitHub. https://codeql.github.com/codeql-query-help/javascript/js-code-injection/.
(2) Remote property injection — CodeQL query help documentation - GitHub. https://codeql.github.com/codeql-query-help/javascript/js-remote-property-injection/.
(3) Regular expression injection — CodeQL query help documentation - GitHub. https://codeql.github.com/codeql-query-help/javascript/js-regex-injection/.
(4) github.com. https://github.com/cmboling/redesigned-broccoli/tree/02b5059d6970698b46d5eeacdc5d9d860af16b26/codeqlbinaries%2Fmacos%2Fqlpacks%2Fcodeql-javascript%2FSecurity%2FCWE-094%2Fexamples%2FServerSideTemplateInjectionSafe.js.
