### ISSUE TITLE
[Bug]: Installation of electron on macos

### ISSUE THREAD

**Issue by Alireza17224** [electron/electron#39023]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

Macos 13.4.1 (22F82) Ventura

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

npm install --save-dev electron

Must work but it fails

### Actual Behavior

I have tried a lot of ways like going to node_modules and install it from install.js but not working

also with yarn + npm

npm install --save-dev electron

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
