### ISSUE TITLE
Requests stuck at pending when multiple renderer (window) is being debugged by VSCode.

### ISSUE THREAD

**Issue by cnSchwarzer** [electron/electron#39028]
Please check the issue at https://github.com/microsoft/vscode-js-debug/issues/1741

This appears to be a bug in Electron -- it never responds to the debugger calling `Runtime.runIfWaitingForDebugger` and proceeding with startup. Unfortunately I don't reproduce the issue locally, but I recommend opening an issue [on Electron](https://github.com/electron/electron) and they may be able to provide instructions to get more diagnostic data.

_最初由 @connor4312 在 https://github.com/microsoft/vscode-js-debug/issues/1741#issuecomment-1626125377 发布_

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by cnSchwarzer** [comment]
Sorry, I didn't expect it because I create the issue directly from reply. Restart in https://github.com/electron/electron/issues/39038
