### ISSUE TITLE
[Bug]: How I can get computer connected domain name

### ISSUE THREAD

**Issue by kondareddy** [electron/electron#39024]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I have been trying to fetch computer connected domain name - its pretty straight forward in C# but struggling to find solution for same in electron.

https://learn.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipglobalproperties.domainname?view=net-7.0#system-net-networkinformation-ipglobalproperties-domainname

// function getCurrentUserDomain() {
//     const username = os.userInfo().username;
//     console.log('Current User Name:', username);
//     const domainArray = username.split('\\');
//     const domain = domainArray.length > 1 ? domainArray[0] : null;
//     console.log('Current User Domain:', domain);
//     console.log('Current User Host Name:', os.hostname);
//     return os.hostname;
//   }

### Actual Behavior

I am able to just retrieve either user name or just device name not domain name

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
