### ISSUE TITLE
[Bug]: Render frame was disposed before WebFrameMain could be accessed

### ISSUE THREAD

**Issue by huanghanyue** [electron/electron#39068]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home

### What arch are you using?

x64

### Last Known Working Electron version

13.6.1

### Expected Behavior

I have no idea to resolve this problem and in my process.on('uncaughtException', xxxx) or process.on('unhandledRejection', xxx) can not catch this error. Help me please!

### Actual Behavior

![img_v2_f161108f-78ff-44f2-a939-e9d7058a064g](https://github.com/electron/electron/assets/16572115/c3453ffc-b89a-4f73-94da-cc5bd0a2ae70)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. Beyond that, Electron v13 has not been supported in some time. If the above communities are not able to solve your issue and you are able to reproduce it on a [supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines), you're welcome to file a new issue.

**Comment by YeesterPlus** [comment]
I have this error and i get this error in electron 31.0.0-beta.10

**Comment by araisch** [comment]
Have this problem after Version Bump 27 -> 33.0.2
