### ISSUE TITLE
[Feature Request]: how can get opener in webview?

### ISSUE THREAD

**Issue by mawenjie521** [electron/electron#39081]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I create a webview, the webview listen "new-window", and create a new webview, I cannot get opener in new webview.
there is any method, can I get opener?

### Proposed Solution

The Electron provide any methods, that can get opener in new webview.

### Alternatives Considered

give some methods for resolving this question.

### Additional Information

nothing

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
