### ISSUE TITLE
[Bug]: ReferenceError: File is not defined

### ISSUE THREAD

**Issue by joris-delorme** [electron/electron#39093]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0.1 (22A400)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I use whisper and chatgpt with the new [OpenAI V4 API](https://github.com/openai/openai-node/discussions/182) and TRPC.

Electron app init from [electron+vite](https://evite.netlify.app/).

### Actual Behavior

I got this error :
```
App threw an error during load
ReferenceError: File is not defined
    at Object.<anonymous> (/Users/joris/Documents/2023 Pro/Talk To Notion/app/dist-electron/main.js:141:2307)
```

It's come from the openai node module but it **work on src folder**.

I have found that this error is because File interface is only available in browser side, and I use this following code in the "back-end" of my electron app. But I don't find how to fix it. How I can import File inside my app ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
