### ISSUE TITLE
Passing a stream through IPC

### ISSUE THREAD

**Issue by akshay-aravind** [electron/electron#39134]
Working on video calling project, My Call is displayed in the mainWindow and when I Click On a button , I need the Call to be on another Window. but am not able to send stream through the IPC , so the only possible way I can see is to start a separate call in the other window. Is there anything like createPortal(react) where I can just renderer the same component in the mainwindow without breaking the flow to the other window?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
