### ISSUE TITLE
BrowserView showing Error

### ISSUE THREAD

**Issue by akshay-aravind** [electron/electron#39150]
Hi, I was trying to load a content using the BrowserView .
view?.webContents.loadURL(`http://localhost:1212/#/join`);
I wanted to show a page of my project in the view But it shows an error message in the view saying "cannot read the properties of undefined reading ipcRenderer" , the thing is am not even using a ipcrenderer in the that page.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed, or issues that don't complete our issue template. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
