### ISSUE TITLE
Reducing size of final package of an application

### ISSUE THREAD

**Issue by wbgl** [electron/electron#39183]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I saw a sample application (Imagine-0.7.4), built on Electron, that the size of downloaded application was about 55 MB. Generally, I think the size of Electron applications is more then 100 MB, If I am not wrong. Please help me to find out how that application (Imagine-0.7.4) has been packaged on this size.

![Snap 2023-07-21 at 20 28 39](https://github.com/electron/electron/assets/50794556/9acc5786-578d-4d7e-8edb-cebf0702eeae)

### Proposed Solution

No Idea.

### Alternatives Considered

No Idea.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
