### ISSUE TITLE
Secure electronjs app secure against code read by end user

### ISSUE THREAD

**Issue by learncodingforweb** [electron/electron#39192]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When electronjs app is build, build folder has resource folder, where asar contained all js files used to build electronjs app. asar can be extracted, where extracted folder contained all code. how to secure js files against read by end user. there is no security of code. how to make sure that code can not be read by end user?

### Proposed Solution

there should be provision to encrypt js files against read by end user, while still electrons js should be able to run encrpyted js files. so that there will not any way to reverse engineering to find the source code.

### Alternatives Considered

like wails and tauri app, where they use webkit on linux.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
