### ISSUE TITLE
[Bug]: Electron reports 'not installed correctly' while it can open manually successfully on macOS.

### ISSUE THREAD

**Issue by 7086cmd** [electron/electron#39196]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I can use `electron ...` correctly.

### Actual Behavior

I installed electron in my project, and I can use `npx electron` to open the electron app successfully.

But when I run
```bash
npx electron dist/app/background.js
```

, It reports that I didn't install the app correctly.

<img width="520" alt="image" src="https://github.com/electron/electron/assets/54303040/26db6db4-f3b8-4325-9daf-37b4ffb4da18">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
