### ISSUE TITLE
[Feature Request]: NativeVideo API

### ISSUE THREAD

**Issue by Imperat** [electron/electron#39383]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is pretty useful [NativeImage API](https://www.electronjs.org/docs/latest/api/native-image)
Did Electron team consider the same set of tools for videos? It might be very useful for the apps to have means to get width, height and duration (probably preview?) from the video files in the main process without utilizing any third-party libraries.

### Proposed Solution

Implement `NativeVideo` class with the same methods as `NativeImage` has.

### Alternatives Considered

If you considered this before and think that Electron is not right place to implement this API then I'll look for third-party libraries to do this on main process.

**Comment by MarshallOfSound** [comment]
`NativeImage` serves to loosely wrap `gfx::Image` in JS so that we can easily pass images to APIs that need them from JS.  I don't think there is a similar usecase (or equivalent internal api) for videos, it's also a massive can of worms to open.  The API surface of things like ffmpeg is _huge_.

I think this is much better served by folks using any of the many ffmpeg native node modules that exist in npm
