### ISSUE TITLE
Unable to get desktop video stream in MacOS

### ISSUE THREAD

**Issue by kiko111pro** [electron/electron#39386]
I'm using `desktopCapturer` api from electron which actually works fine on Windows for both locally served and final exe application. But on macOS it only shows the stream while developing the application or served locally. But shows a **blank white screen** on final dmg application. More specifically we are able to control or see the screen of window on the mac screen but unable to control or see the Mac screen on any other platform (only in production build but works fine in local development). I tried adding Info.plist file with `NSScreenCaptureUsageDescription` but it still is same. Below is the package.json and code for sharing screen file.

<img width="803" alt="Screenshot 2023-08-04 at 7 55 25 PM" src="https://github.com/electron/electron/assets/65704651/c5c59602-06d1-46e9-8859-9d962db20865">
<img width="856" alt="Screenshot 2023-08-04 at 8 15 41 PM" src="https://github.com/electron/electron/assets/65704651/94640310-0324-469a-ad79-fcafe804c0eb">

While launching the final build application a popup is shown for Accessibility Settings where i have already selected this application to access the screen of this device.

What could be the possible reason for a electron application not showing the stream

**Comment by roy2651** [comment]
I have black screen，which version macos

**Comment by kiko111pro** [comment]
@roy2651 its Monterey 12.6.6

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by roy2651** [comment]
I guess in MacOS , if I change my app's Bundle ID and in privacy this app still have authority，and when I use screen share via Electron so the remote screen is black. Is this problem cause  Bundle ID changed. and how to solve this problem @codebytere @kiko111pro
