### ISSUE TITLE
How to add C linker header while compiling electron app for MAC

### ISSUE THREAD

**Issue by avaidhyajc** [electron/electron#39393]
I am developing a screen-share application and I would like to add  C linker headers `__CGPreLoginApp __cgpreloginapp /dev/null` while building the app. I have looked extensively for the solution but couldn't find any. Any insights on this will be much helpful.

Ref: https://stackoverflow.com/questions/41429524/how-to-simulate-keyboard-and-mouse-events-using-cgeventpost-in-login-window-mac

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
