### ISSUE TITLE
The utility process  Translation problem 【Chinese】

### ISSUE THREAD

**Issue by qianqianWXQ** [electron/electron#39404]
每个Electron应用程序都可以使用UtilityProcess API从主进程生成多个子进程。实用程序进程在 Node.js 环境中运行，这意味着它能够 require 模块并使用所有 Node.js API。例如，实用程序进程可用于托管：不受信任的服务、CPU 密集型任务或容易崩溃的组件，这些组件以前会托管在主进程或使用 Node.js child_process.fork API 生成的进程中。实用程序进程和 Node.js child_process 模块生成的进程之间的主要区别在于，实用程序进程可以使用 MessagePort 与渲染器进程建立通信通道。当需要从主进程分拆子进程时，Electron应用程序总是可以首选UtilityProcess API而不是Node.js child_process.fork API。

**Comment by codebytere** [comment]
English Translation:

> Every Electron application can spawn multiple child processes from the main process using the UtilityProcess API. The utility process runs in a Node.js environment, which means it is able to require modules and use all Node.js APIs. For example, utility processes can be used to host: untrusted services, CPU-intensive tasks, or crash-prone components that would previously be hosted in the main process or a process spawned using the Node.js child_process.fork API. The main difference between utility processes and processes spawned by the Node.js child_process module is that utility processes can use MessagePort to establish communication channels with renderer processes. Electron applications can always prefer the UtilityProcess API over the Node.js child_process.fork API when a child process needs to be forked from the main process.

-----------------

Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
