### ISSUE TITLE
[Bug]: Trigger maximize when leave-full-screen

### ISSUE THREAD

**Issue by xlj-my** [electron/electron#39450]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19045.3208

### What arch are you using?

x64

### Last Known Working Electron version

25.5.0

### Expected Behavior

`win.setFullScreen(false)`
`leave-full-screen` event triggered only.

### Actual Behavior

`maximize` event triggered also.

### Additional Information

```
win.on('maximize',()=>{
    if(!win.isFullScreen()){
        win.setFullScreen(true);
    }
})
globalShortcut.register('Esc',()=>{
    if(win.isFullScreen()){
        win.setFullScreen(false);
        win.unmaximize()
    }
})
```
intention: When I `maximize` the window to `enter-full-screen`, when I press 'Esc' to `leave-full-screen` and restore the window.
result: `leave-full-screen`  also trigger `maximize` cause it to be ineffective

**Comment by MafistoPL** [comment]
### Electron Version
Bug still present in Electron v30.0.1
### What operating system are you using?
I've tested it on Windows 10, 11, and Ubuntu - and it's present on all three. The issue manifests itself slightly differently on Windows and Linux.
### Testcase Gist URL
https://gist.github.com/MafistoPL/d6eafd7968cf7118dcc00149bbf08031 
### Expected Behavior
By following the repro steps, we should see the following console logs at specific steps:
1. Maximize window: `Event triggered: maximize`
2. Enter full screen: `Event triggered: enter-full-screen`
3. Leave full screen: `Event triggered: leave-full-screen`
### Actual Behavior
On Windows 10 and 11, we observe:
```
Event triggered: maximize
Event triggered: enter-full-screen
Event triggered: maximize
Event triggered: leave-full-screen
```
On Linux, we see:
```
Event triggered: maximize
Event triggered: enter-full-screen
Event triggered: leave-full-screen
Event triggered: maximize
```
### Additional Information
Repro steps:
1. Run the fiddle.
2. Maximize the window.
3. Press F11 twice to enter and leave full screen.
4. Observe the logs in the fiddle console.
