### ISSUE TITLE
[Bug]: Overlay Disappears in Dev Tools Rendering Tab

### ISSUE THREAD

**Issue by balaji-sivasakthi** [electron/electron#39468]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.4.0

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 11 Home Single Language Version	22H2 Installed on	‎11/‎30/‎2022 OS build	22621.1992 Experience	Windows Feature Experience Pack 1000.22644.1000.0

### What arch are you using?

x64

### Expected Behavior

1. Open the Dev Tools.
2. Navigate to the rendering tab within the Dev Tools.
3. Check the "Frame Rendering Stats" option to display the rendering statistics overlay.
4. Reload the window.
5. Observe that the rendering statistics overlay disappears, even though it was previously checked.
6. Uncheck the "Frame Rendering Stats" option.
7. Recheck the "Frame Rendering Stats" option.
8. Notice that the rendering statistics overlay reappears.

### Actual Behavior

The "Frame Rendering Stats" overlay should persist after reloading the window, maintaining the same state as when it was initially checked, without requiring it to be unchecked and checked again.

**Comment by codebytere** [comment]
@balaji-sivasakthi this is, unfortunately, not a bug - or at least, it's the same behavior as upstream Chromium. If you load https://www.youtube.com/ instead of `index.html`, you'll see that the settings UI persists on reload. Similarly, if you go to Chrome and load `index.html`, then follow your repro steps, you'll see the UI disappears the same way on reload. I recommend you file a bug with Chromium at https://crbug.com/
