### ISSUE TITLE
[Bug]: Missing NPM packages for 22.3.18 and 22.3.20

### ISSUE THREAD

**Issue by boutetnico** [electron/electron#39480]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.18 & 22.3.20

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5

### What arch are you using?

x64

### Expected Behavior

Packages for 22.3.18 and 22.3.20 are published on NPM.

### Actual Behavior

Packages for 22.3.18 and 22.3.20 are not published on NPM.

### Additional Information

https://www.npmjs.com/package/electron/v/22.3.18
https://www.npmjs.com/package/electron/v/22.3.20

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

These packages installed successfully on multiple devices for me so you should seek advice for your issue in one of the above forums.
