### ISSUE TITLE
[Bug]: WebGL is not supported on this device

### ISSUE THREAD

**Issue by Baoing** [electron/electron#39485]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 家庭中文版

### What arch are you using?

x64

### Last Known Working Electron version

25.5.0

### Expected Behavior

Use webgl successfully

### Actual Behavior

log.js:20 Initialization of backend webgl failed
log.js:20 Error: WebGL is not supported on this device

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

Beyond that - this is something Electron has no control over. WebGL support is implemented in Chromium.
