### ISSUE TITLE
任务管理器内存持续升高

### ISSUE THREAD

**Issue by OMY-onlymissyou** [electron/electron#39575]
使用electron+vue开发桌面应用，内存会持续升高，有没有什么办法可以清除
![image](https://github.com/electron/electron/assets/58871216/2ad0bd93-8022-406e-920e-cefe3c7b5b5a)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
