### ISSUE TITLE
[Bug]: setVisibleOnAllWorkspaces correct behavior on macOS M1 chip

### ISSUE THREAD

**Issue by ashwin-mittal** [electron/electron#39580]
- **Issue:** I found a possible bug in Electron.
- **Objective:** I want to use the `setVisibleOnAllWorkspaces` function with `skipTransformProcessType` set to false.
- **Expected Behavior:** I want my application to be visible on all workspaces, including fullscreen, but still visible in the dock.
- **Solution Attempt:** I changed the activation policy to 'regular' explicitly.
- **New Issue:** When using an input of type date, it is not working in fullscreen mode, even though the window is visible over fullscreen.
- **Request:** Please provide assistance with this issue.

Here is the GitHub gist for the same code: [gist](https://gist.github.com/ashwin-mittal/a328a3e6d989d70090636a112296cce3)

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by codebytere** [comment]
Closing as https://github.com/electron/electron/issues/39601 filled the template more correctly.
