### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by juanmacaballeror** [electron/electron#39598]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.6.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

25.2.0

### Expected Behavior

You want to call a function declared in contextBridge.exposeInMainWorld from vue3 and a proxy type data is passed to it because in vue3 the reactivity objects are of proxy type

### Actual Behavior

From Vue3 we are passing a proxy type object (the reactivity in vue3 are of proxy type) to call a contextBridge operation. This produces an "object could not be cloned" error. As I observe, objects, arrays, strings can be passed, but I don't know if proxy data can be passed to call operations in contextBridge.exposeInMainWorld

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
