### ISSUE TITLE
[Bug]:  app.getGPUInfo('complete')   get the info is an Object, please tell me  which key can juge the computer's graphics card counts?

### ISSUE THREAD

**Issue by liujian891010** [electron/electron#39625]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.4.2

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Last Known Working Electron version

9.4.2

### Expected Behavior

thx   
I want know how to juge computer's graphics card count

### Actual Behavior

thx   
I want know how to juge computer's graphics card count

### Testcase Gist URL

no

### Additional Information

thx   
I want know how to juge computer's graphics card count

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
