### ISSUE TITLE
[Feature Request]: 能不能优化一下窗口启动

### ISSUE THREAD

**Issue by iyuli** [electron/electron#39726]
### 飞行前清单

- [X]我已经阅读了这个项目的[贡献指南]（https://github.com/electron/electron/blob/main/CONTRIBUTING.md）。
- [X]我同意遵循该项目遵守的[行为准则]（https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md）。
- [X]我搜索了[问题跟踪器]（https://www.github.com/electron/electron/issues）以查找与我想提交的功能请求相匹配的功能请求，但没有成功。

### 问题描述

能不能优化一下窗口的启动速度。
或者和手机App一样可以设置启动图，
这样在浏览器创建完成并开始加载页面之前就不会存在空白时间了。

### 建议的解决方案

希望优化窗口的启动速度，如果不行的话，设置启动图也可以的。

### 考虑的替代方案

如果设置App启动图也可以
![QQ截图20230903224529]（https://github.com/electron/electron/assets/38270397/684f0947-3ac6-422c-818c-5f2b1da613a1）

### 附加信息

_没有回应_

**Comment by foxxy432** [comment]
ONLY ENGLISH PLEASE!

**Comment by asd281533890** [comment]
你可以创建一个新的browserWindow作为启动图，这个browserWindow只加载一个图片，速度应该会很快。真正的browserWindow在创建时隐藏，设置show: false，当真正的browserWindow触发ready-to-show或其webContent触发dom-ready事件时再将启动图browserWindow销毁，将真正的browserWindow显示出来。

**Comment by VerteDinde** [comment]
Hey @iyuli, thanks for reporting this issue. Apologies, I translated your issue into English, so let me know if I misunderstood:

It sounds like you're asking if we can optimize the startup speed of the window, to avoid a blank screen until the browser is created and starts loading the page. Different apps handle this in different ways, and we have a small section in the Electron docs that covers performance optimizations (though not time to first load specifically): https://www.electronjs.org/docs/latest/tutorial/performance

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. I'm going to close this specific enhancement issue, since it's more of a discussion and not a specific proposal for handling the initial window load. For most questions about Electron, there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out. Thanks!
