### ISSUE TITLE
[Question] - How to switch to About panel on Mac to verify the info

### ISSUE THREAD

**Issue by kobenguyent** [electron/electron#39723]
Currently, I'm using CodeceptJS - Playwright to write automated tests for an Electron app. And there is a case like when clicking the About on menu, the About Panel is opened but there is no possibility to switch to that window to verify the info on that.

![Screenshot 2023-09-02 at 07 54 29](https://github.com/electron/electron/assets/7845001/41d59534-d168-488c-90a8-817fc98e97d8)

I'm just curious is there any option to switch to that About panel to verify info.

Thanks in advanced!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
