### ISSUE TITLE
[Bug]: Dropdown shows up on different screen

### ISSUE THREAD

**Issue by t57ser** [electron/electron#39741]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

Dropdown should appear below the select element

### Actual Behavior

Dropdown appears on a different screen

![image (1)](https://github.com/electron/electron/assets/10595986/df9c10ce-4dd8-4672-8f13-d5f4278abc43)

This is related to the screen configuration
1st screen 1920x1080 dpi 1
2nd screen 2560x1440 dpi 1 main display
3rd screen 2560x1440 dpi 1.25

![image (2)](https://github.com/electron/electron/assets/10595986/5b79fc05-af2d-4fca-b65b-fdf79f761384)

### Testcase Gist URL

https://gist.github.com/t57ser/613c73a8a460520f4af5e309a34c36ea

**Comment by SyedAbuBakerAli** [comment]
hi, @t57ser  can you tell me more about to solve this issue , I'm new to open source

**Comment by codebytere** [comment]
@t57ser can this be seen in chromium itself?

**Comment by dhiraj0911** [comment]
i would love to resolve this issue, can you assign it to me

**Comment by t57ser** [comment]
@codebytere Yes I can reproduce this in Chrome. Appears to be a chromium issue

**Comment by VerteDinde** [comment]
@SyedAbuBakerAli @dhiraj0911 You're both welcome to submit PRs to fix any open Electron issues. We ask people not to comment asking that issues be assigned to them, and just go ahead and submit pull requests if they want to try tackling a fix - I will say, because this issue is also happening in Chrome, it will likely not be a good first issue for people new to Electron. I'd recommend searching for issues with the label `beginner-friendly` 🙂 

@t57ser Thanks for confirming it also happens in chromium (and thanks for reporting the issue and including a gist 🙇‍♀️)

**Comment by codebytere** [comment]
@t57ser the right place to report this is crbug.com then - when they fix it we'll inherit that fix.
