### ISSUE TITLE
[功能请求]：Windows11  Add context menu 

### ISSUE THREAD

**Issue by iyuli** [electron/electron#39787]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Add context menu API for win11.
![AE5F6718-2FBB-42B9-9F3D-8F23D846F958](https://github.com/electron/electron/assets/38270397/a4a69f5c-5d44-4143-bd06-88e8a168d156)

### Proposed Solution

https://github.com/ikas-mc/ContextMenuForWindows11
This project allows users to add menus freely。

We can add an Api, for example: app.addContextmenu()

### Alternatives Considered

Not yet

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
