### ISSUE TITLE
Codesigning for Desktop application using circleci

### ISSUE THREAD

**Issue by reddybhavanish** [electron/electron#39849]
I want to codesign my desktop application(electron application) that is being generated during build process in the circleci. Does anyone help me out how to achieve this codesigning in circleci. I tried setting environment variables of certificate path and certificate password in circleci but i am unable to codesign my appliaction.

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. 

In your specific case, if you're using Electron Forge, you can follow our code-signing guide here: https://www.electronforge.io/guides/code-signing For CircleCI specifically, if you're not seeing environment variables populate, you may need to set them in the Project Settings or in specific contexts for your jobs: https://circleci.com/docs/contexts

For other questions about Electron, there are a lot of options. Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
