### ISSUE TITLE
[Bug]: Apple framework is not working in macOS build.

### ISSUE THREAD

**Issue by rohitRohi123** [electron/electron#39844]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.4.4

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4.1

### What arch are you using?

x64

### Expected Behavior

Native framework should work in macOS electron app. 

### Actual Behavior

Native MacOS App:
 
I have created a native macOS app to demonstrate the functionality of locking and unlocking, and I can confirm that the lock and unlock features are working as expected.

Electron App:

In Electron app, I used the same code as in the native app, along with the same certificate and provisioning profile. However, I'm encountering an issue where the 'Lock' and 'Unlock' session returns null. I've added logs for debugging, but I'm not receiving any errors or exceptions. It's just returning null.

I also verified the Candidate app, ensuring it is properly signed, packed with a valid certificate, provisioning profile, and linked to Apple frameworks.

https://github.com/electron/electron/assets/13746916/c13c84a2-959a-4a1b-983b-214067de1ff6

<img width="1440" alt="Screenshot 2023-09-05 at 3 34 52 PM" src="https://github.com/electron/electron/assets/13746916/6d3bbb43-d07a-4148-9215-83861c11b535">
<img width="1440" alt="Screenshot 2023-09-05 at 3 28 56 PM" src="https://github.com/electron/electron/assets/13746916/2ffeac44-400b-4868-a6f8-742889bcbff0">

https://github.com/electron/electron/assets/13746916/7a1cb695-f1e3-4ec5-9250-9875be935c8a

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
