### ISSUE TITLE
[Bug]: After upgrading to electron 26.x.x, worker_threads subthreads cannot use better-sqlite3

### ISSUE THREAD

**Issue by code-small-white** [electron/electron#39860]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

Windows

### Operating System Version

macOS Ventura 13.4.1 (22F82)

### What arch are you using?

x64

### Last Known Working Electron version

25.x.x

### Expected Behavior

It works fine

### Actual Behavior

Running error [89505:0914/170541.532620:ERROR:child_thread_impl.cc(235)] Invalid PlatformChannel receive right, then crash

### Additional Information
Here is the pseudocode roughly:
```ts
main.ts
import { Worker } from 'worker_threads'
sqlite_thread = new Worker(path.join(__dirname, 'sqlite_thread.js'))
woker.ts
startSqlite = (dbPath: string) => {
    db = new Database(dbPath)
    Object.values(createSql).forEach((sql) => db.exec(sql))
}
```

**Comment by Jasonford323** [comment]
main.ts
import { Worker } from 'worker_threads'
sqlite_thread = new Worker(path.join(__dirname, 'sqlite_thread.js'))
woker.ts
startSqlite = (dbPath: string) => {
    db = new Database(dbPath)
    Object.values(createSql).forEach((sql) => db.exec(sql))
} @

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! The Electron team is small and generally doesn't have enough bandwidth to triage third-party code.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
