### ISSUE TITLE
[Feature Request]: Intercept HTTP(s) calls and modify them on the fly

### ISSUE THREAD

**Issue by Zabrane** [electron/electron#39888]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi guys,

I'm new to Electron and  I'd like to know if it is capable of handling these use cases:

[1] `GET`
. let's say I'd like to load a web page, be it: https://www.wikipedia.org/
. an Electron `Listener` will intercept that URL before it's even sent to the wire:
. the URL is rewritten and sent to my local proxy:
```plain
GET http://localhost:8000/https://www.wikipedia.org/ 1.1\r\n
X-MY-PROXY-HEADER: some_value_here\r\n
[...] I don't touch the original HTTP request headers and keep them as they were
...
```

[2] `POST`
Same logic for post requests. I intercept a POST query and rewrite it this way:
```plain
POST http://localhost:8000/https://reqbin.com/post-online/ 1.1\r\n
X-MY-PROXY-HEADER: some_other_here\r\n
[...] I don't touch the original HTTP request headers and keep them as they were
...
<POST BODY>
```

Please notice that my proxy is only handling `http` scheme for simplicity. 

Is this doable in `Electron`? If yes, please point me to the corresponding doc or any code snippet.

Help appreciated
Thanks

### Proposed Solution

Don't know how to achieve this

### Alternatives Considered

None for now

**Comment by XieJiSS** [comment]
RTFM

https://www.electronjs.org/docs/latest/api/protocol#protocolhandlescheme-handler
https://www.electronjs.org/docs/latest/api/net#netfetchinput-init - with `bypassCustomProtocolHandlers`
https://www.npmjs.com/package/http-proxy-agent
https://www.npmjs.com/package/https-proxy-agent

This is not a feature request issue

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
