### ISSUE TITLE
[Bug]: Electron deep linking showing help page instead of app

### ISSUE THREAD

**Issue by fredywhatley** [electron/electron#39894]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

macOS

### Operating System Version

13.5.2 (22G91) - ventura

### What arch are you using?

ia32

### Expected Behavior

The deeplinking section of electron docs shows the help page instead of the app. Link I am following is here: https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app#conclusion

**Steps to reproduce**
- From the link above, click "**Open in Fiddle**".
- Run the app.
- Click the link "**Click here to launch the app**".

**Expected**: to launch the app

### Actual Behavior

**Actual**: it opens the help page (see picture link below)

### Testcase Gist URL

none

### Additional Information

**Things I've tried**:
- Uninstalled all apps related to electron because I develop several electron apps.
- Removed all files related to all other electron apps from these folders
  - /Users/username/Applications
  - ~/Applications
  - /Applications
- Restarted mac laptop and made sure no other electron apps are running
- Removed node_modules package-lock.json and reinstalled all dependencies
- Looked at past & currect issues in electron. 
- Tried this fix and a few other withou success: https://stackoverflow.com/questions/60774286/electron-app-auto-launch-shows-an-additional-window-due-to-incorrect-app-path
After trying all these things, I still get the same issue.

Thanks for taking a peek at this issue. Your help is greatly appreciated.

[electron deeplinking issue image][1]

  [1]: https://i.stack.imgur.com/F4LyR.png

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
