### ISSUE TITLE
[Bug]: Electron keeps closing itself whenever I try to attach it.

### ISSUE THREAD

**Issue by KingK318** [electron/electron#39923]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windiws10 Version 22H2

### What arch are you using?

x64

### Expected Behavior

The expected behavior for Electron is to attach to Roblox.

### Actual Behavior

Whenever I try to attach it it crashes and closes itself

### Additional Information

There's nothing else

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! The Electron team is small and generally doesn't have enough bandwidth to triage third-party code.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
