### ISSUE TITLE
How to determine checksum when downloading Electron directly

### ISSUE THREAD

**Issue by ujov** [electron/electron#39935]
Hello, 

since I had problems installing electron (version 17.1.0) due to network settings, I followed the instructions at https://www.electronjs.org/docs/latest/tutorial/installation.

As described under **Troubleshooting**, I downloaded the release directly from[https://github.com/electron/electron/releases/v17.1.0/](https://github.com/electron/electron/releases/v17.1.0/) and created a cache in the home directory (Windows).

`~\electron\Cache\476dc8b6146fd15b05acf6b4419b73220900597c3f2bbf4275bc0a4a910d584d\electron-v17.1.0-win32-x64.zip`

In this way I can also build the application in the company network.

However, it is not clear to me how I can determine the checksum?

I was trying this via `$sha256sum ./electron-v17.1.0-win32-x64.zip`
But I come up with a different checksum. This can also be found in SHASUMS256.txt.

I was only able to determine the correct checksum by installing it on a different network where the download from electron works.

Can someone help me with this issue?

Nice regards

**Comment by msimoni18** [comment]
I am also having an issue installing electron from local cache because of this exact reason. Figuring out the correct checksum should close my issue in #39948.

**Comment by ujov** [comment]
@msimoni18 

What was interesting but also incomprehensible to me was that in a second build of the same repo under Linux (Ubuntu) I received exactly the same checksum, even though the asset in this case was electron-v17.1.0-linux-x64.zip.

**Comment by ujov** [comment]
@msimoni18 

What was interesting but also incomprehensible to me was that in a second build of the same repo under Linux (Ubuntu) I received exactly the same checksum, even though the asset in this case was electron-v17.1.0-linux-x64.zip.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
