### ISSUE TITLE
[Bug]: Transparent windows have no animation on minimize/close

### ISSUE THREAD

**Issue by itz4rv** [electron/electron#39971]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows Server 2022 Standard Evaluation 21H2

### What arch are you using?

x64

### Expected Behavior

When minimizing window, it should transition to the taskbar with a small animation.

### Actual Behavior

When minimizing window, it just disappears and minimizes.

### Additional Information

Like https://github.com/electron/electron/issues/32993 but with the transparency

> Animation works without frame, but not with `transparent: true`

**Comment by JohnBrayden** [comment]
I still have this problem with the latest version of Electron, but once I removed the transparency, the problem was solved and the animation worked, but then the flashing problem appeared.

The flashing problem occurs when I click on minimize sometimes, and the screen is white and empty of components. I read that this problem can be solved by using transparency, which in turn causes another problem.
