### ISSUE TITLE
[Bug]: The exception call stack in the child process cannot be caught

### ISSUE THREAD

**Issue by yin-shu** [electron/electron#39970]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

macOS

### Operating System Version

13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I use the fork method to start a child process. When an abnormal error in the child process causes the child process to crash, I want to be able to listen for the crash and error call stack in the main process。

### Actual Behavior

I couldn't get the error call stack using any of the following listeners

```
const p = fork('child.js')
    p.on('error', (err) => {
      console.error('SubProcessProxy error', err);
    });

   p.on('exit', (code, signal) => {
      console.log('SubProcessProxy exit', code, signal);
    });

    p.on('close', (code, signal) => {
      console.log('SubProcessProxy close', code, signal);
    });

    p.on('spawn', () => {
      console.log('SubProcessProxy spawn');
    });

    p.on('uncaughtException', (err) => {
      console.error('SubProcessProxy uncaughtException', err);
    });

    p.on('unhandledRejection', (reason, promise) => {
      console.error('SubProcessProxy unhandledRejection', reason, promise);
    });


```

When the child process has an exception, only 'close' and 'exit' can be heard, and there is no valid information in the parameter

### Additional Information

May I ask whether it is my problem or Electron can not do this

**Comment by pruthula0** [comment]
In Electron, when a child process crashes or throws an unhandled exception, you can indeed capture the error information in the main process. However, the event you should be listening for is the "message" event, not the "error" event. Here's how you can modify your code to capture the error call stack:

```javascript
const { fork } = require('child_process');

const p = fork('child.js');

p.on('message', (message) => {
  if (message.type === 'error') {
    console.error('Child process error:', message.error);
  }
});

p.on('exit', (code, signal) => {
  console.log('Child process exit', code, signal);
});

// Rest of your code...
```

In your child process (`child.js`), you should send an error message to the main process when an exception occurs:

```javascript
process.on('uncaughtException', (err) => {
  process.send({ type: 'error', error: err.stack }); // Send the error call stack
  process.exit(1); // Terminate the child process
});

// Rest of your child process code...
```

This way, when an unhandled exception occurs in the child process, it will send an error message with the call stack to the main process. The main process can then listen for this message and handle the error information accordingly.

**Comment by MarshallOfSound** [comment]
The above comment is accurate and provides good pointers for how to solve this, closing this out as it is more of a question than an actual issue

**Comment by yin-shu** [comment]
I wrote a nodejs extension package in C++ and used it in the child process. When the C++ layer reported an error that caused the process to crash, how did the main process catch the crash call stack

**Comment by yin-shu** [comment]
I was unable to catch the call stack for such an exception using methods such as uncaughtException of the child process

**Comment by pruthula0** [comment]
When you have a Node.js extension package written in C++ and it's used in a child process, capturing the crash call stack can be more challenging. The `uncaughtException` event is not reliable in such cases because it is limited to JavaScript exceptions and doesn't catch low-level crashes in C++ code.

To capture the call stack when a C++ error causes the child process to crash and report it to the main process, you can use a combination of techniques:

1. **Custom Error Handling in C++**:
   - In your C++ extension, implement custom error handling that captures error information, including the call stack, when an exception occurs in the C++ code.

2. **IPC (Inter-Process Communication)**:
   - Use IPC mechanisms to communicate the error information from the C++ layer to the Node.js layer (JavaScript) in the child process. This could be achieved by sending a message from C++ to JavaScript in the child process using `node-addon-api`.

3. **Forward the Error to the Main Process**:
   - In the child process, when an exception occurs in C++ and you've captured the call stack, send a message to the main process (the parent) via IPC to report the error. The message should include the call stack information.

4. **Main Process Event Handling**:
   - In the main process, listen for the message sent from the child process and extract the error information, including the call stack.

Here's a simplified example of how you might implement this:

In your C++ code (child process):

```cpp
// Catch and report C++ errors
try {
    // Your C++ code
} catch (const std::exception& e) {
    // Capture the error information and send it to JavaScript
    // using your Node.js addon and IPC mechanisms.
    // Include the call stack if available.
    ReportErrorToNodeJS(e.what());
}
```

In your JavaScript code (child process):

```javascript
const { fork } = require('child_process');

const child = fork('child.js');

child.on('message', (message) => {
    if (message.type === 'error') {
        console.error('Child process error:', message.error);
    }
});

// Rest of your code...
```

This way, when a C++ error occurs in the child process, it is captured, sent to the parent process, and logged with the call stack if available. This allows you to handle low-level C++ errors in the child process and report them in the main process. .

**Comment by yin-shu** [comment]
Thank you very much for your reply. As for the first step, I am not sure how to implement it. Could you please provide a scheme or code example?
Also, if you do this, it won't cause the child process to crash when C++ raises an exception?

**Comment by pruthula0** [comment]
This example assumes you have a C++ extension module integrated into your Node.js code within the child process.

In the main process:

javascript

const { fork } = require('child_process');
const path = require('path');

const p = fork(path.join(__dirname, 'child.js')); // Replace 'child.js' with the path to your child process script.

p.on('message', (message) => {
  if (message.type === 'error') {
    console.error('Child process error:', message.error);
  }
});

p.on('exit', (code, signal) => {
  console.log('Child process exit', code, signal);
});

// Rest of your code...

In the child process (child.js):

javascript

const { parentPort } = require('worker_threads'); // Use 'worker_threads' for better isolation

process.on('uncaughtException', (err) => {
  // Send the error information to the main process
  parentPort.postMessage({ type: 'error', error: err.stack });
  // Do not exit the child process to prevent crashing
  // process.exit(1); // You can comment this out or remove it
});

// Your C++ extension code
try {
  // Call your C++ code here
} catch (error) {
  // If an exception occurs in your C++ code, it will be captured here.
  parentPort.postMessage({ type: 'error', error: error.stack });
}

// Rest of your child process code...

In this updated code example, we use worker_threads for better isolation of the child process. In the child process, when a C++ exception occurs, it's caught and the error information is sent to the main process via parentPort.postMessage. The child process doesn't exit (i.e., no process.exit) to prevent it from crashing.

The main process listens for messages from the child process and handles errors when they occur.

This approach allows you to prevent the child process from crashing due to C++ exceptions while still capturing error information in the main process.

**Comment by yin-shu** [comment]
c++ extensions do not need to be modified, start child threads in nodejs, and execute c++ extension logic in the child threads. Is that right?

**Comment by pruthula0** [comment]
yes thts right

**Comment by yin-shu** [comment]
thank you
