### ISSUE TITLE
 Getting thease errors while uploading electron app to mac store through transporter

### ISSUE THREAD

**Issue by prabhatm102** [electron/electron#39977]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

12.0.0

### Rejection Email

prabhat@rudrainnovative.in

### Additional Information

Asset validation failed (90237)
The product archive package's signature is invalid. Ensure that it is signed with your "3rd Party Mac Developer Installer" certificate. (ID: 4456a1aa-3d2a-4e3b-a1f4-a8dc6f558671)

Asset validation failed (90236)
Missing required icon. The application bundle does not contain an icon in ICNS format, containing both a 512x512 and a 512x512@2x image. For further assistance, see the Human Interface Guidelines at https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/. (ID: f8e39bef-dd66-4079-8482-a16d1ea502ea)

Asset validation failed (90287)
Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.team-identifier' in 'com.kitesuite.app.pkg/Payload/kite.app/Contents/MacOS/kite'. (ID: a4aa84c8-6148-4d69-afd3-6e70c2a2b050)

Asset validation failed (90287)
Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.application-identifier' in 'com.kitesuite.app.pkg/Payload/kite.app/Contents/MacOS/kite'. (ID: 8e182655-cd1b-4b0e-8664-9e2051dedd32)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
