### ISSUE TITLE
[Bug]: Running child_process.spawn on sandboxed MacOS app

### ISSUE THREAD

**Issue by GabrielNSD** [electron/electron#40050]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.8

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6

### What arch are you using?

x64

### Expected Behavior

My application downloads a JRE and a .jar. To execute this .jar, require('child_process').spawn is used, passing the jre binarry as command and the arguments and path to .jar.  
This implementation runs perfectly on non sandboxed macApp and on other Operating Systems.

### Actual Behavior

When it is a sandboxed macOS app (to publish on store), the error `spawn EPERM` is raised and I cannot run the .jar.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
