### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TareoKuo** [electron/electron#40071]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 19045

### What arch are you using?

x64

### Expected Behavior

I'm using the React Electron boilerplate template. Whenever I use 'var ffi = require('ffi-napi')', ffi keeps showing as 'undefined.'

### Actual Behavior

He should display something instead of 'undefined', shouldn't he?

### Additional Information

How can I call my DLL file? I'm using the React Electron boilerplate template. Whenever I use 'var ffi = require('ffi-napi')', ffi keeps showing as 'undefined.' This issue has been bothering me for a long time. I hope someone can help me.

var ffi = require('ffi-napi');
console.log(ffi);

In fact, no matter what module I use, it always displays 'undefined'.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
