### ISSUE TITLE
[Bug]: Causing Command+R shortcut keys to be unusable in Chrome applications

### ISSUE THREAD

**Issue by tjzhaojunchen** [electron/electron#40093]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

2.3.10.12

### What operating system are you using?

macOS

### Operating System Version

macOS 14

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

2.3.10.12

### Expected Behavior

fix it

### Actual Behavior

Does not affect the use of Command+R shortcut keys in Chrome applications

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
