### ISSUE TITLE
Renderer process crashed

### ISSUE THREAD

**Issue by hbole** [electron/electron#40152]
I currently upgrade my electron app from v 13.6.9 to 22.3.24
I have upgraded all the necessary packages.

Entire flow of the app is working as expected except reload

When I reload the app, it works sometimes, but suddenly it starts throwing `Renderer process crashed` error

I also tried running the app using `npx electron . --enable-logging to get the logs for the crash. But I don't get anything in the logs.

I just get
```Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information```

Sometimes I also get 
```sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed```

But other than these errors I don't get anything else to determine why the app is crashing.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

You also did not fill out the issue template as required. If you think this is a legitimate issue and open a new issue, it must be filled correctly for us to proceed with triage.

**Comment by snps-zhengxu** [comment]
Greetings @hbole  Did you finally solve your problem? I'm getting the same issue, just wondering what could be the root cause?

**Comment by KarthikTarun** [comment]
even i am facing the same issue

@hbole did you find the issue?

@snps-zhengxu what about you, any updates?
