### ISSUE TITLE
child_process got Error: spawn EACCES

### ISSUE THREAD

**Issue by alminQSD** [electron/electron#40198]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The application should locate and spawn the native host without any issues.

### Actual Behavior

Received an error as shown in the attached screenshot. The error details are below:

<img width="632" alt="Screenshot 2023-10-13 at 09 48 42" src="https://github.com/electron/electron/assets/97589739/dd7c3eb3-6c65-475e-a24f-e5da4899fc82">

Workaround:

The following is not working and I got the error:
` nativeHostPath = path.join(__dirname, 'extensions', 'pdc', 'nativeHost', process.platform, 'PDCNativeHost.app', 'Contents', 'MacOS', 'PDCNativeHost');`

Using the path to the already installed app works as expected. For example:
`nativeHostPath = '/Applications/PDCNativeHost.app/Contents/MacOS/PDCNativeHost';
`

### Additional Information

I've encountered a problem when trying to use a path to the file PDCNativeHost in an ElectronJS project on macOS.

I've also attached a screenshot of the error for a visual reference. Any assistance or insights on why the relative path is causing this issue would be appreciated.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
