### ISSUE TITLE
[Bug]: Limiting background FPS in the NVIDIA Control Panel causes some Electron apps to lag.

### ISSUE THREAD

**Issue by 016R35H** [electron/electron#40208]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.8.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

This shouldn't affect the Electron apps, they're not games. And if they were considered "games" they are not even running in the background. 

### Actual Behavior

![image](https://github.com/electron/electron/assets/138529583/fc55577d-0c36-4721-b031-c3111da9f1ce)

If I limit it to 30, some Electron-made apps runs laggy, at 30fps or less.

### Additional Information

Test by yourself in VS Code for example.

**Comment by MarshallOfSound** [comment]
> This shouldn't affect the Electron apps, they're not games. And if they were considered "games" they are not even running in the background.

Nvidia control panel settings are not limited to just "games".  You're telling the GPU to limit fps to all applications that do gpu based rendering (which chromium does).  Chromium also dynamically determines the correct framerate to use so if it get's limited in the background, it will use that limit as the frame rate target until it determines a new frame rate to use either via rescan or relaunch.

This is technically speaking expected behavior of Chromium itself, nvidia let's you set settings per-exe so I'd suggest doing that instead of blanket limiting fps for all apps on your PC

**Comment by kamild1996** [comment]
I've just experienced such an issue with two Electron apps. They work fine when they're opened for the first time, but as soon as the focus is switched to another app and then back to these ones, they're stuck at that background framerate. Discord seems to have worked around this issue somehow, but if this is something that could potentially be fixed by the framework so application devs don't have to worry about it, that would be great.
Recommending people to set FPS limits for each app separately is completely impractical, especially for people playing a lot of video games.

**Comment by mirh** [comment]
Discord probably did nothing, they are just blocklisted by a specific driver app profile (to confirm whether this is the case or not, just try to rename its executable to something else).
