### ISSUE TITLE
Add support for "Open Recent" menu

### ISSUE THREAD

**Issue by jarek-foksa** [electron/electron#4028]
Document-based apps often have "File" => "Open Recent" menu which lists recently opened files.

AFAIK there is currently no way to create this menu manually so that it works under OS X sandbox.

**Comment by erkyrath** [comment]
I'm trying to do this also. Lacking Menu.remove (https://github.com/atom/electron/issues/527) or some other way to replace a submenu, it's not really possible.

**Comment by callodacity** [comment]
I'm using electron `1.4.3` and I just manually implemented this functionality like so:

```javascript
function updateRecents(path, clear = false) {
  const currentMenu = Menu.getApplicationMenu();
  if (!currentMenu) return;

  const recents = getItemByKey(currentMenu, 'recents');
  if (!recents) return;

  // Clear menu if requested.
  if (clear) {
    config.set('recentDocuments', []);
    recents.submenu.clear();
    recents.submenu.append(new MenuItem({ key: 'null', label: 'No Recent Documents', enabled: false }));
    Menu.setApplicationMenu(currentMenu);
    return;
  }

  const item = new MenuItem({
    label: require('path').basename(path),
    click: () => this.open(path)
  });

  // If first recent item clear empty placeholder.
  if (recents.submenu.items[0].key == 'null') {
    recents.submenu.clear();
    recents.submenu.append(item);
  }
  // Limit to maximum 10 recents.
  else if (recents.submenu.items.length >= 10) {
    const items = recents.submenu.items;
    recents.submenu.clear();
    items.push(item);
    items.slice(10).forEach((i) => recents.submenu.append(i));
  }
  // Otherwise just add item.
  else recents.submenu.append(item);

  // Update application menu.
  Menu.setApplicationMenu(currentMenu);
}
```

You just have to be careful to **always** set a valid `menu` at the end with `Menu.setApplicationMenu(menu)`. If you modify/remove any menu instance that is being used and you don't call it, your app with crash when that menu is rendered.

**Comment by jarek-foksa** [comment]
@callodacity Last time I checked, this approach did not work when using macOS sandbox.

**Comment by callodacity** [comment]
@jarek-foksa ah, I haven't tried it in the sandbox yet - that is not good news for me!

**Comment by jtoy** [comment]
any more info on this?

**Comment by taivu** [comment]
https://github.com/Microsoft/vscode/issues/6912

**Comment by sethlu** [comment]
🚧 Managed to create a rough workaround...

Edits are made to the default xib file for the system "Open Recent" submenu that's otherwise difficult to create programmably unless with private API calls. Currently, without overwriting the default menu bar, the "Open Recent" should function correctly... The `app` instance will emit `open-file` when user selects a file in the list of recent documents.

[WIP] https://github.com/sethlu/electron/tree/openrecent

Next steps:

- Retain "Open Recent" menu item at an invisible state in the menu;
- Introduce a new role `openrecent`, similar to `services` for macOS, for the submenu;
- Allow passing label for `Clear Menu` through some menu item option...

Refs:

- http://www.mattrajca.com/2011/07/23/appkit-quick-tip-populating-the-open-recent-menu-in-non-document-based-applications.html
- https://forum.juce.com/t/mac-app-store-sandbox-and-open-recent/8619
- https://raw.githubusercontent.com/vinniefalco/SimpleDJ/master/Extern/JUCE/extras/example%20projects/Builds/MacOSX/RecentFilesMenuTemplate.xib

**Comment by fred-tt** [comment]
@sethlu how to make it on windows? please help me, thanks.
