### ISSUE TITLE
[Bug]: Using electron js with electron-tabs not able to click any external urls

### ISSUE THREAD

**Issue by IamSteveStifler** [electron/electron#40327]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows

### What arch are you using?

x64

### Expected Behavior

Upon clicking on href links that will redirect to another page with target="_blank" that should perfectly work.

### Actual Behavior

On clicking the external href link, it is not doing anything. we think that electron might not be able to track the click events

### Additional Information

Since this is working fine for our application but we are taking services from another page on that particular page we are seeing this issue happening.
**Without using the electron tab this click event on the button we are able to track**

![image](https://github.com/electron/electron/assets/44442342/c36e75e3-cbcb-4054-984b-43297a82b63a)

**This is from main.js** 

![image](https://github.com/electron/electron/assets/44442342/eb3ba764-4e11-4cc0-950d-7184561fe64d)

**After adding the electron-tab code this simply not works.**

Please help us with any solutions.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
