### ISSUE TITLE
Setting image src from disk not working on Windows.

### ISSUE THREAD

**Issue by madalinul** [electron/electron#40352]
I am trying to create something like a file explorer, where the user browsers the local file system and I want to display the images in the folders.
I have registered a protocol with
```
app.whenReady().then(() => {
  protocol.handle('atom', (request) =>
    net.fetch('file://' + request.url.slice('atom://'.length)))
})
```
And in the renderer I do 
```
 <img style={{ objectFit: 'cover' }} src={'atom://' + file.path} height='100%' width='100%' />
```

This works on macOs without any issues but on Windows I get this error:
```
TypeError: Failed to parse URL from atom://C:\\Users\\myUser\\Pictures\\Screenshots\\Screenshot 2023-02-24 133652.png
    at new Request (node:internal/deps/undici/undici:7134:19)
    at AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:57323) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:616:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:57323) {
    input: 'atom://C:\\Users\\myUser\\Pictures\\Screenshots\\Screenshot 2023-02-24 133652.png',
    code: 'ERR_INVALID_URL'
  }
```

Any ideas on what the problem might be?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
