### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SirDrolet** [electron/electron#40357]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

Colocar bordes redondos a mi ventana de electron.js con border radius y frame: false y transparent: true

**TRANSLATION**
Add round borders to my electron.js window with border radius and frame: false and
![prueba](https://github.com/electron/electron/assets/145229764/ef4f54c5-d2b1-4f5a-b0fa-816afc45b0da)
 transparent: true

### Actual Behavior

Hola, estoy creando una aplicación con **Electron** y he querido hacer los bordes de la ventana redondos, pero no da resultado. He visto por internet que dicen que en mi mainwindow.js ponga:

**- Frame: false,
- Transparent: true,**

Coloqué también en mi HTML un border radius en un <div> e intenté con el CSS, pero no ha funcionado. Lo he colocado en el body o HTML, pero no da resultado alguno.

He probado muchas cosas, pero ninguna funciona.

Espero que tenga solucion!

**TRANSLATION**
Hello, I am creating an application with **Electron** and I wanted to make the window borders round, but it does not work. I saw on the internet that they say that in my mainwindow.js put:

**- Frame: false,
- Transparent: true,**

 I also placed a border radius in a <div> in my HTML and tried with the CSS, but it has not worked. I have placed it in the body or HTML, but it does not give any result.

I have tried many things, but none work.

I hope you have a solution!
![CapturaVentana](https://github.com/electron/electron/assets/145229764/693197ca-5161-4ea8-b70b-5c43a68266e3)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
