### ISSUE TITLE
[Bug]: Need to manually remove GPUCache directory for every Electron app after every Mesa update

### ISSUE THREAD

**Issue by iRomanyshyn** [electron/electron#40366]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.0

### What operating system are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed

### What arch are you using?

x64

### Expected Behavior

After the Mesa update, open any Electron app (currently Slack and Joplin) and use it routinely.

### Actual Behavior

After Mesa updated Slack and Joplin became unusable as could not display properly any elements including text, except for some icons and images.

### Additional Information

To make it work again as expected, I need to manually remove the `GPUCache` directory for every Electron app in their `~/.config/` directory (for example, `rm -r ~/.config/Slack/GPUCache`) after every Mesa update because otherwise, those apps wouldn't display anything only some icons and images. It happens after every Mesa update on my system. **Be careful anyone repeating this: check for any extra whitespace in the path to not remove crucial directories! The `rm` command along with `-r` is a dangerous thing.**

**Comment by iRomanyshyn** [comment]
@jkleinsc I need to wait for the next Mesa update for my system to make this trace as it happens after Mesa updates.

**Comment by codebytere** [comment]
@iRomanyshyn in the meantime - does this happen with Chrome itself?

**Comment by JoshStrobl** [comment]
Yea it's a Chromium issue and should be resolved in a future release (possibly 120).

- https://bugs.chromium.org/p/chromium/issues/detail?id=1442633
- https://chromium.googlesource.com/chromium/src/+/3290d6aee7a53a6b1a811c8b50ff0a3bf84fb6a6

**Comment by codebytere** [comment]
@iRomanyshyn what this means is that this bug is not Electron's fault - Electron depends on Chromium, as does Microsoft Edge. Per the bug linked above (CRBUG:1442633) Chromium is looking into this and will hopefully fix it soon. When they do, we receive the fix for free through our upgrade process. Please track the issues upstream for further progress - in the meantime, I'm closing this out as an upstream issue.

**Comment by bbhtt** [comment]
Hey, @codebytere, are you willing to backport the chromium fix into the current supported versions of Electron?

The patch looks fairly small https://chromium-review.googlesource.com/c/chromium/src/+/4988290

The issue affects all Electron versions as a change in mesa caused the shader logic in chromium to fail. It'd be nice to have this fixed instead of waiting for v28 to be out (it is in 28.0.0-beta3).

Please let me know if I should open a seperate issue for that.
