### ISSUE TITLE
chrome.runtime.connectNative

### ISSUE THREAD

**Issue by tangYinPeng** [electron/electron#40380]
Doesn't electron support native messaging? Extension load can succeed, but using chrome. Runtime. ConnectNative connection not only on local applications, but use the Google browser is ok. Is there a reason?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
