### ISSUE TITLE
How to remove the animation when the window is hidden on Windows?

### ISSUE THREAD

**Issue by fanchenio** [electron/electron#40401]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.4.2

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Remove window animation and also have window shadow

### Actual Behavior

There is a default animation when hiding a window

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by fanchenio** [comment]
The problem now is that when I set the window to `toolbar`, the window animation will disappear. This is the effect I want, but if I set the window to transparent and retain `toolbar`, the animation will come back. I don’t know this Is it considered a BUG?
@codebytere
