### ISSUE TITLE
[Bug]: autoUpdater.quitAndInstall() will be interrupted by user behavior

### ISSUE THREAD

**Issue by coolswitch** [electron/electron#40429]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.3.10

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4  

### What arch are you using?

arm64 (including Apple Silicon)
 

### Actual Behavior

After `autoUpdater.quitAndInstall()`, when all windows closed, users may think that the update has been completed and manually run the app, causing the install to be interrupted.

### Expected Behavior

When installing that prohibits app startup.

Or do something to let users know that the update is not complete yet, such as keeping a pop-up until the app restarts.
 
### Additional Information

What am I supposed to do now?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
