### ISSUE TITLE
[Feature Request]: Why does the package size increase so much for each iteration of each version?

### ISSUE THREAD

**Issue by tetap** [electron/electron#40427]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Each major version requires an increase of no less than 5MB, with an increase of even 10MB on 27 and 28 Do I know where the effort here is?

![image](https://github.com/electron/electron/assets/57606461/0a75a66d-3099-4b18-9111-2a8431892eef)

![image](https://github.com/electron/electron/assets/57606461/07f0c0f7-0e11-4976-a935-87e2e796e91a)

![image](https://github.com/electron/electron/assets/57606461/8ab4c006-99f3-4e04-9e35-5a54d4b65967)

### Proposed Solution

We should establish a version to maintain the volume of this package.

### Alternatives Considered

We should establish a version to maintain the volume of this package.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
