### ISSUE TITLE
[Bug]: When clicking on the minimize window or the software icon on the taskbar, it cannot prevent the window from being minimized

### ISSUE THREAD

**Issue by 82318179** [electron/electron#40431]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

When clicking on the minimize window or the software icon on the taskbar, it cannot prevent the window from being minimized
`  mainWindow.on('minimize',(e)=>{
    e.preventDefault();
    //Prevent minimization and then do other things, but minimization cannot be prevented
  })`
I hope to prevent window minimization from continuing through e.preventDefault (), but it doesn't work. So how can I prevent window minimization?

### Actual Behavior

When the window is minimized, even in the minimize event, use e.preventDefault (); Still unable to prevent the window from continuing to minimize

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
