### ISSUE TITLE
[Bug]: About web worker access

### ISSUE THREAD

**Issue by wonkyungup** [electron/electron#40442]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.4.3

### What operating system are you using?

Windows

### Operating System Version

Window 11

### What arch are you using?

x64

### Last Known Working Electron version

26.4.3

### Expected Behavior

WebWorker operates normally on Mac. Worker files do not work in Windows.

Mac:  m2 pro
Version: Sonoma

### Actual Behavior

Main.vue:258 Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'file:///C:/xxx' cannot be accessed from origin 'http://localhost:5173'.

**1. The path is normal**

 webPreferences: {
      webSecurity: false
 }
 
 **2. If you put that option in, it works normally.**
 
 
 

### Additional Information

Is there a way to run worker files more safely?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by wonkyungup** [comment]
@jkleinsc thx
