### ISSUE TITLE
how to request location permission on mac os 

### ISSUE THREAD

**Issue by Jantakarn12** [electron/electron#40492]
I want to request to allow location like request to use camera . 

thank you.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by mahnunchik** [comment]
@codebytere @Jantakarn12  Why it is closed? There is currently no way to request geolocation permission on macos in electron app.

```
navigator.geolocation.getCurrentPosition();
```

it waits for a location forever

**Comment by nilayarya** [comment]
@Jantakarn12 check out https://github.com/nilayarya/electron/tree/custom-geolocation-manager. You'll have to build it yourself. Instructions on how to use are here : [https://github.com/nilayarya/electron/pull/1](https://github.com/nilayarya/electron/pull/1)
