### ISSUE TITLE
[Bug]: HTML5 Notification API Not Working in Electron 26 and Above

### ISSUE THREAD

**Issue by 253eosam** [electron/electron#40532]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26

### What operating system are you using?

Windows

### Operating System Version

window11

### What arch are you using?

x64

### Expected Behavior

Notifications should be displayed as per the HTML5 Notification API specifications.

### Actual Behavior

Notifications are not appearing or functioning correctly.

### Additional Information

This issue is critical for applications relying on the HTML5 Notification API for user notifications, and its resolution would be highly appreciated. If there are any workarounds or temporary fixes, please provide them as well.

Thank you for your attention to this matter, and I appreciate your efforts in maintaining and improving the Electron framework.

Best regards,

---

HTML5 Notification api : https://developer.mozilla.org/en-US/docs/Web/API/Notification

**Comment by codebytere** [comment]
@253eosam if i add, for example `const notification = new Notification("Hi there!")` to the renderer process a on Windows 11 x64 i see the notification just fine. What exactly isn't working?

**Comment by 253eosam** [comment]
> Hello @253eosam. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

=> The above method seems difficult to make into a test case due to my lack of ability..

**Comment by luke-webdev** [comment]
Encountering the same issue with version 26.4.1. Last known working version was 26.3.0.

**Comment by codebytere** [comment]
@luke-webdev: https://github.com/electron/electron/issues/40532#issuecomment-1818411645

**Comment by codebytere** [comment]
@luke-webdev I still cannot triage this as no one has successfully clarified what the issue is specifically nor how to reproduce it in a minimum viable environment. A preload script can contain nearly any code - that you are using one does not help me triage. If you would like further investigation, please provide a repro as requested in my earlier comments.

**Comment by codebytere** [comment]
It would help if someone could provide an example of a URL which causes the notification to fail - i'm not able to reproduce this still.

**Comment by ghost1face** [comment]
I am also experiencing something similar.  Notifications in the main process displayed just fine up to `electron@26.4.0` but anything higher than that version I am unable to get notifications to display with my application on Windows Server 2016 Datacenter (old image I used for regression and targeting multiple OS versions).

The funny thing is, if I start a brand new project everything works just fine on the same server.

What's more interesting is, my application displays notifications fine on all `electron@26+` versions on my Windows 11 instance.

All that being said I'm thinking its one of two things but completely unsure:

1. Somehow I've got some old cached something between changing electron versions 26.4.0 to 26.4.1+
2. The changeset between 26.4.0 and 26.4.1 maybe targeted something newer?

I wish I was able to create a reproducible sample to help but maybe this info may spark some ideas?

**Comment by vladimiry** [comment]
This issue looks like a cause of https://github.com/vladimiry/ElectronMail/issues/666 report. I'm unable to provide an isolated repro project since at this time I have no Windows system at my side.

**Comment by geovie** [comment]
Had the same issue when we wanted to update to the latest electron version. Our setup is similar as the gist in https://github.com/electron/electron/issues/40532#issuecomment-1828382531    
For us it worked when loading the url from the dev server but not when running it from the release url which is a bit longer (spoiler alert 😉)

We run our app with log output enabled for electron and notifications (e.g. `ELECTRON_DEBUG_NOTIFICATIONS=1 electron --enable-logging`) and when creating a notification this error popped up in the logs:
`WinAPI: Setting tag failed,ERROR -2143420138` searching the electron source reveals this line from this MR https://github.com/electron/electron/pull/40242/files#diff-83363a49cbd80a542422409785b8bb78d601340c52a6d1fc0a3ef61b59966f77R202
and the message of the HRESULT
```c++
    _com_error err(-2143420138);
    LPCTSTR errMsg = err.ErrorMessage();
    std::cout << errMsg << std::endl;
```
outputs the nice description `The size of the notification tag is too large.`.
Looking at the docs for [tag](https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification.tag?view=winrt-22621#windows-ui-notifications-toastnotification-tag) it says the `The tag can be maximum 16 characters long. However, the Creators Update (15063) extends this limit to 64 characters.`

We haven't found out how the notification_id is created which is used for the tag but our guess is that the loaded url is somehow included.

Another thing we found in the electron source code is this comment `The notification_id is generated from the tag` so maybe setting a tag while constructing the Notification will not lead to a too large ToastNotification tag!?
And indeed that does the trick so for now a workaround for this issue is to simply set a tag when constructing the Notification.

![tag](https://github.com/electron/electron/assets/29738679/1ec19541-19fc-4f3c-b61a-debeeb81c38d)

**Comment by ghost1face** [comment]
Following up to confirm, I flipped on the debug flags and also noticed the same as @geovie .  Confirming this on an older OS build:

![image](https://github.com/electron/electron/assets/2773690/a1addfab-5407-4377-a71b-60c20b8a9c57)

For now, will generate a 16 character tag to prevent breakage
