### ISSUE TITLE
[Bug]: symbol lookup error: bbgl: undefined symbol: gbm_bo_map

### ISSUE THREAD

**Issue by hushaohhy** [electron/electron#40530]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

Other Linux

### Operating System Version

Linux hiking-W515-PGUV-WBY0 4.19.71-9-kr990 #6b2-KYLINOS SMP PREEMPT Mon 0ct 1806:44:02 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

9.0.0

### Expected Behavior

使用终端打开应用，报错信息如标题

### Actual Behavior

使用终端打开应用，报错信息如标题

### Additional Information

使用终端打开应用，报错信息如标题

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
