### ISSUE TITLE
[Bug]: Can't login to visa online website , "is not a function" error

### ISSUE THREAD

**Issue by ytzlax** [electron/electron#40533]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

x64

### Expected Behavior

Steps to reproduce:

1. Add `webgl: false` to to the BrowserWindow webPreferences
2. Browse to `https://www.visaonline.com`
3. Fill user name - "abc"
4. Fill password  - "1234"
5. Open the devtools
6. Press on "LOG IN" button

Expected:
1. Not to see any error in the devtools ( like browsing without electron) 
2. Be logged in when type the right creds

### Actual Behavior

Actual -->

 seeing the next error in the devtools:
`ERROR TypeError: Q[ey(...)][ey(...)](...)[ey(...)] is not a function`

![Screenshot 2023-11-15 at 14 50 43](https://github.com/electron/electron/assets/15896790/d958d691-9ced-4100-8af1-fd0d0b1318b4)

**Comment by codebytere** [comment]
I see the same failure in Electron as when i try in the browser:
<img width="1116" alt="Screenshot 2023-11-15 at 4 44 31 PM" src="https://github.com/electron/electron/assets/2036040/6b7f3436-69c6-48de-a7b0-585b6dbf4ff2">

and no console error.

**Comment by ytzlax** [comment]
@codebytere  , you are right, the error happend only when I add `webgl: false` to the BrowserWindow webPreferences.
I updated the steps to reproduce comment.
Can you check it again?

**Comment by GsnMithra** [comment]
![noissues](https://github.com/electron/electron/assets/50359897/8d01399b-8da1-4cc4-b5de-633995b530a4)
there is no such error even if i add `webgl: false` to BrowserWindow webPreferences.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
