### ISSUE TITLE
[Bug]: The serial device request submitted by the rendering process cannot be obtained in the 'select serial port' event.

### ISSUE THREAD

**Issue by xhc-code** [electron/electron#40550]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Expected Behavior

It is expected that in this event, the corresponding serial device ID can be returned based on the desired serial device requested by the user

### Actual Behavior

Hello, I would like to manually filter the device ID in the mainWindow. webContent. session. on ('select serial port ',...) event based on the serial. requestPort (xxx) information executed by the user on the renderer side. Since I have multiple serial devices but do not have parameters for vid and pid, is there a way to return the corresponding serial device portId based on the type of serial device requested by the user?
I am currently unable to perform manual filtering in the 'select serial port' event, as if the built-in electric handler automatically performs filtering based on vid and pid

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
