### ISSUE TITLE
[Feature Request]: how to get the BrowserWIndow partition of the instance?

### ISSUE THREAD

**Issue by riseHorizon** [electron/electron#40572]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I create a BrowserWIndow instance by partition like this：
let win = new BrowserWindow({
	show: false,
	width: 1022,
	webPreferences: {
		nodeIntegration: true,
		contextIsolation: false,
		partition:"test-test-123",
	}
});

win.loadURL("file://" + __dirname + "/demo.html");
win.once("ready-to-show", function() {
	win.show();
});
win.once('close', function(event) {
	console.log(">>>>>>>>>>>>>>>>>win close", win.webContents.getOwnerBrowserWindow());
	win = null;
});
but I can not find the partition value。

### Proposed Solution

 I can not find the partition value

### Alternatives Considered

I think the win instance can find all options of set，but i can not find it.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by pipiscrew** [comment]
@riseHorizon 

yes no trace, of solution... 

as is JS, use the casual as :
```js
    var win = new BrowserWindow({
      width: 1181,
      height: 670,
      webPreferences: {
        partition: "persist:test",
      },
    });
    
    //store new property to BrowserWindow
    win.partitionName = "persist:test";
```

<>

afterwards use it by any context as :
```js
const focusedWindow = BrowserWindow.getFocusedWindow().partitionName;
```

@codebytere
solved, type: workaround
