### ISSUE TITLE
[Bug]: newGuest event is missing in setWindowOpenHandler

### ISSUE THREAD

**Issue by akshay-aravind** [electron/electron#40604]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.3

### What operating system are you using?

Windows

### Operating System Version

window 11

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0

### Expected Behavior

mainWindow.webContents.on('new-window',
(event, url, frameName, disposition, options, additionalFeatures) =>
{
// This is the name we chose for our window. You can have multiple names for
// multiple windows and each have their options
if (frameName === 'NewWindowComponent ') {
event.preventDefault();
Object.assign(options, {
// This will prevent interactions with the mainWindow
parent: mainWindow,
width: 300,
height: 300,
// You can also set left and top positions
});
event.newGuest = new BrowserWindow(options);
}
});

"new-window" event is currently marked as deprecated there is no newGuest event in setWindowOpenHandler which is suggested as the replacement.

### Actual Behavior

As the method got depreacted , there is no replacement to handle this the same way.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
