### ISSUE TITLE
Open links in Webview with click instead of shift+click

### ISSUE THREAD

**Issue by DogFoxX** [electron/electron#40613]
I'm running a webapp inside a Webview. How can I open links in the default browser without using shift-click?
It's custom software I'm writing for the company I work at, and most users won't realize that they should use shift+click to open links.

My working code as of now.

```js
const {shell} = require('electron');

app.on('web-contents-created', (e, contents) => {
  if (contents.getType() == 'webview') {
    contents.setWindowOpenHandler((details) => {
      shell.openExternal(details.url);
      return { action: 'deny' }
    })
  }
}
````

Thank you in advance.

**Comment by B-Anand18** [comment]
const { app, shell } = require('electron');

app.on('web-contents-created', (e, contents) => {
  if (contents.getType() == 'webview') {
    contents.on('will-navigate', (event, navigationUrl) => {
      // Open external links in the default browser
      if (!navigationUrl.startsWith(contents.getURL())) {
        event.preventDefault();
        shell.openExternal(navigationUrl);
      }
    });

    contents.setWindowOpenHandler((details) => {
      shell.openExternal(details.url);
      return { action: 'deny' };
    });
  }
});

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
