### ISSUE TITLE
[Bug]: BrowserWindow -webkit-app-region drag is not working with overflow: hidden content over

### ISSUE THREAD

**Issue by vavdav** [electron/electron#40610]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I am able to drag the window outside of the container with `overflow: scroll`

### Actual Behavior

I am unable to drag the window when I scroll content inside the container with `overflow: scroll` and try to drag the window with the mouse above the container. Because there is hidden scrolled content.

### Testcase Gist URL

https://gist.github.com/vavdav/67e8f9bb6b9fd0d4153d21c2f9bcc771

### Additional Information

In the video it is visible that it is not possible to drag the window when the content is scrolled.

https://github.com/electron/electron/assets/215969/52bf309c-9c34-49db-8544-b107c3be11ea

**Comment by codebytere** [comment]
@vavdav unfortunately it looks like this is an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=365593&q=webkit-app-region%20scroll&can=1, which has since been closed.

We currently plumb through upstream logic - if the issue can be solved we'd consider taking a patch but this is something best filed upstream at https://bugs.chromium.org. I recommend commenting on the closed issued and opening a follow-up.

**Comment by nbonamy-kochava** [comment]
@vavdav facing the same issue. were you able to find a workaround?
