### ISSUE TITLE
[Bug]: `shell.beep()` doesn't do anything on Linux (unless Electron was launched from a terminal)

### ISSUE THREAD

**Issue by DeeDeeG** [electron/electron#40625]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

Ubuntu

### Operating System Version

Tested on Ubuntu 22.04 and 23.10, Fedora 39 (all via LiveUSB session)

### What arch are you using?

x64

### Expected Behavior

`shell.beep()` should always produce a "beep" or "alert" noise.

### Actual Behavior

On Linux, `shell.beep()` produces no sound or alert, if Electron was launched any way other than from a terminal.

### Testcase Gist URL

https://gist.github.com/DeeDeeG/d28093106b3f5a747cf925d00ae67357

### Additional Information

On Linux, If Electron _is_ launched from a terminal, the _terminal app_ handles the beep, and an audible beep _does_ play, assuming the user's terminal preferences allow it -- see "alert" or "bell" settings in your terminal app of choice.

On Windows and macOS, `shell.beep()` plays an audible noise regardless of whether Electron was launched from a terminal or otherwise.

**Comment by piotrpdev** [comment]
I'm not sure if there is a good solution for this. Here is the code that produces the beep on Linux:

https://github.com/electron/electron/blob/433d6c33d87b62eab2e920d7b74af9ab3e397f62/shell/common/platform_util_linux.cc#L394-L404

The code tries to:

- Send a beep to the console that opened the process (`/dev/tty`).
	- https://unix.stackexchange.com/a/60646/578409
- Send a beep to the system console (`/dev/console`). However, on many distros this is only possible for `root`.
	- https://stackoverflow.com/a/29446193/19020549
	- https://superuser.com/a/1150867/1775919

Apart from those methods, the only thing I can think of doing is [creating and playing a beep using `asoundlib.h`](https://www.alsa-project.org/alsa-doc/alsa-lib/_2test_2pcm_min_8c-example.html) since the linux build uses ALSA development dependencies.

https://github.com/electron/electron/blob/433d6c33d87b62eab2e920d7b74af9ab3e397f62/docs/development/build-instructions-linux.md?plain=1#L21-L22

I'm not sure if doing all of that is worth it just to get a beep though.

---

Meanwhile, Windows and Mac call their respective built-in beep functions :/

https://github.com/electron/electron/blob/433d6c33d87b62eab2e920d7b74af9ab3e397f62/shell/common/platform_util_win.cc#L448-L450

- https://developer.apple.com/documentation/appkit/1473622-nsbeep

https://github.com/electron/electron/blob/433d6c33d87b62eab2e920d7b74af9ab3e397f62/shell/common/platform_util_mac.mm#L241-L243

- https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebeep

**Comment by DeeDeeG** [comment]
Thanks for that info. I somewhat suspected there was no one neat API for this to address "all of Linux". But the info you linked definitely backs that up.

I suppose it would be okay to close this as "not planned" or something like that, since it may not be very doable? Hmm.

**Comment by DeeDeeG** [comment]
Technically still applies, so "bump".

I dunno if Electron folks wanna go the ALSA `asoundlib` route that was mentioned just above.

I'm personally not totally invested in this topic, I filed it after someone asked about it who uses the project I do work on. But, yeah. Still relevant, I guess.
