### ISSUE TITLE
How to use typescript and import in electron？

### ISSUE THREAD

**Issue by cn-ryh** [electron/electron#40639]
Hello developer of  electron:

I am trying to build my application in electron, and for some reason I want to use typescript instead of javascript as the entry point for my application. Also, to facilitate the use of type hints, I want to import modules using `import` statements rather than `require` statements.

**I configured ·"type": "module"· in package.json, use `.mts` as an extension name**, but when I try to preview and build the application, it still prompts "SynthexError: Cannot use import statement outside a module"

![image](https://github.com/electron/electron/assets/93967737/130d95bb-629d-494b-9ca4-1bf39579d524)

Does Electron support the use of typescript and import statements? What should I do if possible?

Thank all of you very much！

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
