### ISSUE TITLE
desktopCapturer does not work in Mac m1 but can work in Mac m2

### ISSUE THREAD

**Issue by Merry9** [electron/electron#40649]

**Comment by Merry9** [comment]
我是用 desktopCapturer 完成客户端截图功能，在 m2 上一切正常，但是在 m1 上授权之后，并不起作用，由于是用户电脑，目前不清楚不起作用的原因在哪？想请教下大佬们是否有可排查的方案

**Comment by JaiKirhns** [comment]
**Issue Summary:**

After upgrading from Electron 27 to Electron 32, the `desktopCapturer.getSources` method behaves inconsistently on macOS versions 12 and later. The issue does not occur on Linux or Windows, and the same code worked correctly on all macOS versions when using Electron 27.

**Problem Details:**
1. **Initial Behavior:**
   - On the first or second call to `desktopCapturer.getSources`, no sources are returned, and the Electron app unexpectedly closes.
   - Adding a log statement before the call results in the logs being printed, but no response is returned, and the app closes.

2. **Subsequent Behavior:**
   - After 2–3 attempts, the method starts working as expected:
     - The sources are printed.
     - The app remains active and does not close.

3. **Observations:**
   - This issue only occurs on macOS versions 12 and above. 
   - On macOS 10.15, Linux, and Windows, the code works without any issues.
   - The issue is specific to the `desktopCapturer.getSources` method when upgraded to Electron 32.

**Code Example:**
```javascript
(async () => {
  try {
    const sources = await desktopCapturer.getSources({ types: ["screen"] });
    logger.info("Printing sources");
    logger.info(sources);
    if (sources.length > 0) {
      event.sender.send(
        "desktopSourceId",
        sources,
        JSON.stringify(screenSettings)
      );
    }
  } catch (error) {
    logger.info("Error fetching desktop sources:", error);
  }
})();
```

**Expected Behavior:**
- The `desktopCapturer.getSources` method should consistently fetch sources and return them on the first call.
- The Electron app should not close unexpectedly during this process.

**Actual Behavior:**
- On macOS 12 and later, the app closes unexpectedly on the first or second call, and no sources are returned.
- After 2–3 attempts, the method works correctly, and the app does not close.

---
