### ISSUE TITLE
[Bug]: setVisualZoomLevelLimits not working in 27.0.1 version

### ISSUE THREAD

**Issue by CosbyBs86** [electron/electron#40651]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

NA

### Expected Behavior

I added on my rendere.js file the following statement:
require('electron').webFrame.setVisualZoomLevelLimits(1, 3)

When the web page is loaded in the electron form the CTRL + mousewheel +/- and The CTRL + +/- keys should zoom in/out the page.

### Actual Behavior

I added on my rendere.js file the following statement:
require('electron').webFrame.setVisualZoomLevelLimits(1, 3)

When the web page is loaded in the electron form the CTRL + mousewheel +/- does not work. The CTRL + +/- keys don't work as well.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
