### ISSUE TITLE
How to paste from Electon app to non-Electron app, and how to position Electron app based on text cursor of non-Electron app

### ISSUE THREAD

**Issue by ryancwalsh** [electron/electron#40718]
I posted at https://discord.com/channels/745037351163527189/1181731722728050759/1181731722728050759 and StackOverflow and haven't been able to find the answers yet.

Details are there.

Summary:

I'm trying to build a replacement for Mac's emoji picker.

1. (Most important question) When a user chooses an emoji in my Electron app, I want the emoji to get pasted to the non-Electron window that the user had been working in before they used the global hotkey to focus on my Electron app. This is possible, right? I've tried using robotjs unsuccessfully.

2. How can I position (x,y) my Electron app as described in my StackOverflow question? I want its location to be based on the user's text cursor at the time of the hotkey.

I understand if "Issues" is the wrong place for these questions. 

If you have resources other than Discord or StackOverflow, please let me know!

**Thanks for your AMAZING repo!** 😀

**Comment by bymustfa** [comment]
Hi dude. I see that you're experiencing the same issue as me. Although it's been a while since you faced the problem, I want to come back here and share the solution I found, perhaps to help others.

We can't perform the "Paste" operation with Robot JS. Yes, it has many issues in many aspects, but an alternative to it, **nut.js** [https://nutjs.dev/](https://nutjs.dev/) allows us to solve this problem very easily.

```tsx
// electron js project

import { clipboard } from "electron";
import { keyboard, Key } from "@nut-tree/nut-js";

    return {
            label: label,
            click: async () => {
              clipboard.writeText(pasteText);
              await keyboard.pressKey(Key.LeftCmd);
              await keyboard.pressKey(Key.V);
              await keyboard.releaseKey(Key.V);
              await keyboard.releaseKey(Key.LeftCmd);
            },
          };
```
