### ISSUE TITLE
[Bug]: Supporting conditional access the same as Chrome

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#40721]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.6.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 22H2

### What arch are you using?

x64

### Expected Behavior

As Microsoft documents [Conditional Access: Conditions](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-conditions) is supported on `Chrome 111` [supported browsers](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-conditions#supported-browsers)

"[Chrome 111+](https://chromeenterprise.google/policies/#CloudAPAuthEnabled) is supported for device-based Conditional Access, but "CloudApAuthEnabled" needs to be enabled."

### Actual Behavior

So as our customers when using our app that is based on Electron `v26.6.2` the feature is not supported, So the question is here shall we have to enable something like `CloudAPAuthEnabled` from our side the same as Chrom users who need to create a registries to enabled it

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by adarshasodiya** [comment]
Hello @jkleinsc,
Hope you are doing well.

As you mentioned, we have also reached to [Discord](https://discord.gg/electronjs). But not found anything helpful.

Can you please update us here as we are stuck with this issue?

**Comment by Woersty** [comment]
Hi all, what's the status here after more than a year?
Changed your mind?
I have the same issue in the ALE Rainbow Client using the framework and "Not planned" is not what we like to hear 😞 
Regards 
Christian
