### ISSUE TITLE
[Bug]: The will-prevent unload event for webContens is triggered even if no action is taken on the page

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#40780]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

If I don't do any operation on the page (https://developer.mozilla.org/en-US/docs/Glossary/Sticky_activation), When I call webcontents.close ({"waitForBeforeUnload": true}), the "will-prevent unload" event for webContents should not be fired

### Actual Behavior

Even if I do nothing, when I do webContents.close({"waitForBeforeUnload": true}), the "will-prevent unload" event is triggered

### Testcase Gist URL

https://gist.github.com/14cc99cc29354f7e6f5f7b5cb62c845b

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by 1339240789** [comment]
> Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
> 
> Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

6
