### ISSUE TITLE
[Bug]: Electron app is running in efficiency mode on Windows

### ISSUE THREAD

**Issue by himanshurajora** [electron/electron#40791]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 (22621.2861)

### What arch are you using?

x64

### Last Known Working Electron version

8.0.3

### Expected Behavior

The application that we're working on is meant to run 24x7 on the machine. In that case the application should not run in Efficiency mode, it might affect the performance of the application.

### Actual Behavior

Currently the application is running in efficiency mode that hasn't shown anything wrong yet but we're still afraid to deploy it to production.

![image](https://github.com/electron/electron/assets/50817974/4f244418-220a-4c72-82bd-85b099712bbf)

### Additional Information

We have recently upgraded from electron 8.0.3 to electron 27.1.0. Our application wasn't running in efficiency mode before the upgrade but now it is. It might be related to the Chromium itself, even in that case what is the solution or work around to this problem.

**Comment by rafaelcw8** [comment]
I have the same problem, do you have a solution?

**Comment by himanshurajora** [comment]
Not yet, can someone from electron look into it please?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by NickGeek** [comment]
@jkleinsc Could this please be re-opened? It is not a question/discussion and is a change in behavior for electron (due to a new chrome flag for efficiency mode)
