### ISSUE TITLE
Windows "Making sure it's you" popup

### ISSUE THREAD

**Issue by elarrat** [electron/electron#40812]
Hello everyone,

I have an electron app which has a screen that, when clicked, calls the following code: 
```
   this.session = session.fromPartition(`${v4()}`);
    this.window = new BrowserWindow({
      width: 500,
      height: 550,
      show: false,
      parent: this.parent,
      modal: true,
      resizable: false,
      webPreferences: {
        session: this.session,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        contextIsolation: true,
      },
    });
(...)
await this.window.loadURL('https://www.linkedin.com/uas/login');
```

But this is triggering, on some windows machines, the "Making sure it's you popup" from Windows Hello. 
Do any of you faced something similar or know if there's something we can do to overcome this?

**Comment by Lilneo786** [comment]
await this.window.loadURL('https://www.linkedin.com/uas/login', {
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36',
});

**Comment by elarrat** [comment]
Thank, but it didn't work 😢

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
