### ISSUE TITLE
[Feature Request]: Add or extend audio and video decoders

### ISSUE THREAD

**Issue by dylanZk1** [electron/electron#40822]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The application features include a local video preview function, but Chromium only supports a small number of video decoders, resulting in a considerable portion of other encoded local videos being unable to play. I want to solve this problem by adding or expanding audio and video decoders through customization, but my level is not enough to modify the chrome source code. Is there a way to inject custom ffmpeg.DLL or other audio and video link libraries into the program by adding APIs in the main process?

### Proposed Solution

inject custom ffmpeg.DLL or other audio and video link libraries into the program by adding APIs in the main process

OR

you do the codec customization

### Alternatives Considered

Embed the external native video window into the original video node

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. If this does result in something actionable from our end, we can circle back and reopen this!
