### ISSUE TITLE
[Bug]: Electron27 memory issue

### ISSUE THREAD

**Issue by RongRC** [electron/electron#40825]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

macOS

### Operating System Version

14.1.1 (23B81)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Memory consumption of E27 should not be higher.

### Actual Behavior

Previously, we built a desktop application based on E20. Now it's been upgraded to E27. Memory consumption of E27 is ~100MB higher than that of E20 when we ran the same web page on them. Is the memory increase as expected? And if so, is there a declaration somewhere of the approximate memory usage for each Electron version? Thanks!
<img width="1364" alt="Screenshot 2023-12-25 at 10 09 43" src="https://github.com/electron/electron/assets/142976204/7c0a906f-99e2-4371-8893-9094a220d665">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. If this results in a demonstrable issue in Electron itself, we can look to reopen the issue, but we recommend you start with the aforementioned forums.
