### ISSUE TITLE
[Bug]: Electron27 Sharing Screen CPU issue

### ISSUE THREAD

**Issue by xuminjieleon** [electron/electron#40833]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045.3803

### What arch are you using?

x64

### Expected Behavior

CPU cost should be improved compared with old version (E20), whether System Total CPU Usage or Electron App Usage

### Actual Behavior

In all my test PC, the Electron27 App CPU Usage is higher than E20. And the inreased part is mostly in Renderer Process.
In some of my test PC (which hardware is medium), System Total CPU Usage result is unstable, sometimes E27 better than E20, sometimes worse.
But other PC (which hardware is better), E27 always better than E20

### Additional Information

![image](https://github.com/electron/electron/assets/15783776/2e3bac3e-88b1-45c9-9143-30ea7dd75d6b)
![image](https://github.com/electron/electron/assets/15783776/3c23ba5d-585c-4ae5-8118-5eb170e51876)
![image](https://github.com/electron/electron/assets/15783776/f16483c8-8a31-4016-b1e5-bc619d889320)
![image](https://github.com/electron/electron/assets/15783776/029822d5-aad4-49be-ab71-3e573ec8b8d4)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
