### ISSUE TITLE
[Bug]: Refreshing Issue with Show Method in Transparent Frameless Window

### ISSUE THREAD

**Issue by LinuaBio** [electron/electron#40830]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0.

### What operating system are you using?

Windows

### Operating System Version

window 11

### What arch are you using?

x64

### Expected Behavior

I want to prevent flickering when calling the show method on a hidden window

### Actual Behavior

Actually, if I create a window with parameters like frame=false and transparent=true, when I call the hide method and then the show method again, there will be flickering, similar to page refresh.

This is written based on the code in the Quick Start document for Electron, which is basically the same as the official one. I just added keyboard shortcuts and window property settings

To make it easier for observation, I set the background color to white.
![image](https://github.com/electron/electron/assets/104708810/e2dcb2b0-1941-45ba-9f34-5c2acc818cf5)

In the video, I repeatedly press the shortcut keys for hide and show. Sometimes there is no flickering issue, but most of the time the window keeps flickering.

https://github.com/electron/electron/assets/104708810/8883fd32-6754-49a6-928f-0fcb4feaed98

### Additional Information

![image](https://github.com/electron/electron/assets/104708810/fe0db5fe-7344-4774-8c84-dce38ad808d2)
(no renderer.js file)
![image](https://github.com/electron/electron/assets/104708810/7c1e4540-cf2e-4c73-ac16-5c0ab423cb1d)
![image](https://github.com/electron/electron/assets/104708810/6998d2b4-7880-4fc6-a58a-7368e6413288)

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by Koppel-Zhou** [comment]
I have the same problem too
