### ISSUE TITLE
[Bug]: Renderer fails to load, if context isolation is disabled 

### ISSUE THREAD

**Issue by abhinavkgrd** [electron/electron#40838]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

macOS

### Operating System Version

14.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

21.4.4

### Expected Behavior

The app should load the web app on the URL 

### Actual Behavior

It shows a white screen 

### Testcase Gist URL

https://github.com/abhinavkgrd/electron-blank-screen-issue-repo

### Additional Information

The Repo I have provided is a barebone reproducible sample. The app is based on `electron-quick-start` template and is using next js for its renderer code.

The problem seems to be arising from disable `contextIsolation`, if I let it be enabled  context isolation(default), the app loads properly, 
But, when I disable context isolation, it shows a white screen and never loads the app.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
