### ISSUE TITLE
[Bug]: rimraf not removed all the files properly when application uninstall

### ISSUE THREAD

**Issue by ArunKathir98** [electron/electron#40845]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

All the folders should be deleted

### Actual Behavior

I have developed one electron application with squirrel windows.

While uninstalling the application I am trying to clear the folder of user AppData directory by using
require( "rimraf" ).sync( AppDataPath() );

Some of the file are removed but some files are not removed properly still maintained in appDatapath.

Non Removed Folders ( Eg: Blob storage, cache storage, code cache, network folder )

Any solution how to address the error why other files are not removed from this directory?

Thanks in advance for your help

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
