### ISSUE TITLE
Auto Updates Support for Portable Apps

### ISSUE THREAD

**Issue by VitorAndrey** [electron/electron#40843]
Hello,

I am developing a portable application using Electron and I am trying to implement auto updates. However, I couldn't find any specific information in the Electron documentation regarding whether the auto update functionality is supported for portable apps.

The Electron documentation at [docs](https://www.electronjs.org/docs/latest/tutorial/updates) discusses update practices, but it's not clear if these practices apply to portable apps as well.

Could you please clarify if auto updates are supported for portable apps? If not, could you suggest any alternative approaches for implementing updates in portable apps?

Thank you for your time.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
