### ISSUE TITLE
How to disable index DB logs

### ISSUE THREAD

**Issue by ArunKathir98** [electron/electron#40847]
I have developed one electron application with squirrel windows.

Inside the electron application we are embedding external URL ( It contains login ).

After login in the user directory it creates one index Db with some log files. Those log files saves credential information seems. 

Is that any way to handle that logs file inside index DB? or Any way to disable that logging support ? or is this expected behaviour ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
