### ISSUE TITLE
how to load dynamiclly css file and images

### ISSUE THREAD

**Issue by wu0211** [electron/electron#40858]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

May I ask, if I want to dynamically download a theme file from the server, including CSS files and related images referenced inside, how can I load it in Electron? Mainly, how can I change the image address in the CSS file to the local path for downloading images

Chinese:
    问一下，如果我想动态从服务端下载一个主题文件，包含css文件和里面引用的相关图片，这在electron 中怎么load进去，主要是css文件中的图片地址，要怎么改，改成图片下载到本地的路径吗

### Proposed Solution

My current idea is to first download the CSS file and the images referenced in CSS to a local file, and then change the image address of the referenced images in CSS to the local file path file:\\\

use css file for example:
```
 let css = fs.readFileSync(join(cacheFolder, 'index.css'), 'utf-8').toString()
                   
 win?.webContents.insertCSS(css)

```

### Alternatives Considered

Who else has a more convenient way,help me

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
