### ISSUE TITLE
[Bug]: Korean(non-ascii) character print not correctly

### ISSUE THREAD

**Issue by tilto0822** [electron/electron#40876]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Electron version

21.3.1

### Expected Behavior

```js
console.log("안녕 세계!") // means Hello World!
```
this code will print `안녕 세계!`(korean) characters in console. 

### Actual Behavior

above code print `?덈뀞 ?멸퀎!` characters.
this is a character that is generally displayed when there is a problem with output.

### Additional Information

![image](https://github.com/electron/electron/assets/56160437/67444b39-92d1-47ce-963c-2b0f536085f9)

i made a `test.js` file with above code, and run node and electron both.
node print characters correctly but electron is not.

**Comment by codebytere** [comment]
@tilto0822 could you please verify that this happens or doesn't happen in Chrome itself?

**Comment by sangzun-han** [comment]
저도 같은 문제를 겪었었는데 코드상에 문제는 아니었고 한글 문자 인코딩과 관련된 문제로 저는 아래의 순서대로 하니 해결됐습니다.
1. '시작' 메뉴를 열고 '설정'을 클릭합니다.
2. '시간 및 언어' > '언어 및 지역'으로 이동합니다.
3. '관리 언어 설정'을 클릭하고, 'Beta: 세계 언어 지원을 위해 Unicode UTF-8 사용' 옵션을 활성화합니다.
4. 변경 사항을 적용하고 시스템을 재부팅합니다.

---

I experienced a similar issue, but it turned out not to be a problem with the code itself. It was related to Korean character encoding. I resolved it by following these steps:

Open the 'Start' menu and click on 'Settings'.
Go to 'Time & Language' > 'Language & Region'.
Click on 'Administrative language settings', and then enable the option 'Beta: Use Unicode UTF-8 for worldwide language support'.
Apply the changes and reboot your system.
After doing this, the issue with Korean characters not displaying correctly in the Electron application was resolved. I hope this helps you as well.
