### ISSUE TITLE
[Bug]: I cannot sign in with my Apple ID on my Mac

### ISSUE THREAD

**Issue by TianbinTobin** [electron/electron#40873]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

![截屏2024-01-03 17 01 47](https://github.com/electron/electron/assets/16282973/cffee43d-2ea1-458c-8ffc-f622ee801dac)

### Actual Behavior

![截屏2024-01-03 17 03 14](https://github.com/electron/electron/assets/16282973/940b9f68-0629-45aa-a01a-2caac8c52441)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
