### ISSUE TITLE
[Bug]: App crashes on MAS Verification or when I signed app locally

### ISSUE THREAD

**Issue by BenLaKnet** [electron/electron#40902]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14

### What arch are you using?

x64

### Expected Behavior

I am using electron-packager to package app and osx-sign option.
After I update .app to .pkg with electron-osx-flat and sign option.

App crashes on startup when I published there on MAS.

If I do not sign app locally, it is running.

### Actual Behavior

App crashes on MAS when they test the app.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

It's not clear now whether the issue is resultant of your packaging software (`electron-packager` is not maintained by Electron) or by Electron itself. Additionally, you provided no crash report or any other crash information. We would consider reopening this once you can demonstrate that the issue lies with Electron itself and provide the requested information.
