### ISSUE TITLE
[Bug]: Some kind of color in css did not shown in electron on some pc.

### ISSUE THREAD

**Issue by chinaofmelon** [electron/electron#40919]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

10.0.18363

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

The html show correct, and color show correct.

### Actual Behavior

Background color of button show as transparent and did not show the correct color.

correct in edge:
![edge](https://github.com/electron/electron/assets/9248242/a6d9ba51-d1fa-4c05-bdb1-64309e36ec16)

incrrect in electron:
![electron](https://github.com/electron/electron/assets/9248242/1f46950c-ea4c-49d0-8e4c-957732ce0ede)

### Testcase Gist URL

https://gist.github.com/8baa05ddb396c78ab633385ff308ce10

### Additional Information

The issue only reproduce on the special pc, and it's not happen on my own pc, so any idea about how to debug it, and what info do I need to collect?

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
