### ISSUE TITLE
[Bug]: Recursive rmdir returns error while trying to remove folder, that contains asar file.

### ISSUE THREAD

**Issue by tangjfn** [electron/electron#40960]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22631.3007

### What arch are you using?

x64

### Last Known Working Electron version

27.2.2

### Expected Behavior

const fs = reuqire("fs");
// const fs = require("original-fs");
await fs.promises.rm("path contains asar file",{force: true, recursive: true})
// no error thrown

### Actual Behavior

const fs = reuqire("fs");
// const fs = require("original-fs"); // same error thrown
await fs.promises.rm("path contains asar file",{force: true, recursive: true})
// throw a error ENOTEMPTY: directory not empty, rmdir '...'

### Additional Information

[test.zip](https://github.com/electron/electron/files/13903590/test.zip)

extract test.zip to a dir
cd the dir
electron .
input a dir contains any asar file
click rm button

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
