### ISSUE TITLE
[Bug]: The gpu process memory leaks when webgl is used to render images(When hardware acceleration is used by default) on a windows computer in the locked screen state

### ISSUE THREAD

**Issue by Candylong** [electron/electron#41016]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

any version

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

28.0.0

### Expected Behavior

gpu process memory normal

### Actual Behavior

gpu process memory increases

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community).

There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. As you've not provided a repro or more information we can't triage this any further. If, after consulting the above resources, you determine this is a bug in Electron and provide all requested information, we can consider investigating this further.
