### ISSUE TITLE
Files from src dosen't including into app sources

### ISSUE THREAD

**Issue by ZaksenCode** [electron/electron#41054]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.4

### What operating system are you using?

Other Linux

### Operating System Version

Archlinux

### What arch are you using?

x64

### Expected Behavior

![image](https://github.com/electron/electron/assets/70453716/e6b1ae70-2267-4c5b-986f-57b9876d0dba)
i want load images from art folder. 

### Actual Behavior

![image](https://github.com/electron/electron/assets/70453716/1687ed1f-a833-4775-be48-dd8a6f91339f)
loading only icon.png from art folder.

**Comment by VerteDinde** [comment]
Hey @ZaksenCode, I think this may be an issue with packaging your application rather than with Electron itself - do you happen to have a repro or a repo of your project we can take a look at? Are you using Electron Forge?

**Comment by ZaksenCode** [comment]
Here is repository: https://github.com/ZaksenCode/VCreator-Electron/tree/main
Yes, i use Electron Forge

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
