### ISSUE TITLE
Question: How to show spesific html content for electron users?

### ISSUE THREAD

**Issue by martenzo7** [electron/electron#41059]

**Comment by martenzo7** [comment]
Hi,
I'm working on a flask based web application that support electronjs. I was wondering If there is a way to force electron to view a web page with additional content (ex: div, scripts or css styles). I found a way to do this with user-agent but that could be easily bypass by users.

**Comment by Ocean-OS** [comment]
Try using this script in JS: 
```js
if(typeof process !== "undefined" && typeof process.versions.electron !== "undefined"){
  var isElectron = true;
}else{
  var isElectron = false;
}
```

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
