### ISSUE TITLE
Can't read contents of settings.dat generated by the crashReporter

### ISSUE THREAD

**Issue by darkydarkjason** [electron/electron#41056]
Electron crashReporter generates a settings.dat file locally whenever the app crashes.

However I can not read its content, looks like it's encrypted.
If I open it up manually, it's scrambled text.
If I open it up using fs.readFileSync, it's showing the following, looks to be encrypted.

```
16:42:30.777 › {
 '0': 115,
 '1': 100,
 '2': 80,
 '3': 67,
 '4': 1,
 '5': 0,
 '6': 0,
 '7': 0,
 '8': 0,
 '9': 0,
 '10': 0,
 '11': 0,
 '12': 0,
 '13': 0,
 '14': 0,
 '15': 0,
 '16': 0,
 '17': 0,
 '18': 0,
 '19': 0,
 '20': 0,
 '21': 0,
 '22': 0,
 '23': 0,
 '24': 9,
 '25': 202,
 '26': 144,
 '27': 119,
 '28': 62,
 '29': 190,
 '30': 92,
 '31': 77,
 '32': 170,
 '33': 198,
 '34': 55,
 '35': 240,
 '36': 9,
 '37': 125,
 '38': 251,
 '39': 224
}

```

Is there anyway to read the content of the settings.dat file generated by the crashReporter, without having to upload info onto a remote url?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
