### ISSUE TITLE
How to migrate my custom file protocol?

### ISSUE THREAD

**Issue by Android789515** [electron/electron#41067]
I have tried following the docs but it is not working for me.

### Current:
```ts
import type { ProtocolRequest, ProtocolResponse } from 'electron';

type FileProtocolHandler = (request: ProtocolRequest, callback: (response: (string)
   | (ProtocolResponse)) => void) => void;

export const mediaProtocol: FileProtocolHandler = (request, callback) => {
   const url = request.url.replace('media://', '');

   try {
      return callback(decodeURI(url));
   } catch (error) {
      console.error(error);
   }
};

```
### main.ts
```ts
protocol.registerFileProtocol('media', mediaProtocol);
```

### Component
```tsx
...
const audioTrack = 'media://' + songPath;
   
   return (
      <audio
         src={audioTrack}
         autoPlay
         muted={controls.isMuted}
         onTimeUpdate={syncAudioTime}
         onEnded={onSongEnd}
         ref={speakerRef}
      />
   );
```

### Changed to:
```ts
import { net } from 'electron';

export const mediaProtocol = (request) => {
   const url = request.url.slice('media://'.length);

   return net.fetch(`file://${decodeURI(url)}`);
};

```

### main.ts
```ts
protocol.handle('media', mediaProtocol);
```

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by Android789515** [comment]
I hate to re-open this issue, but I really dislike social media.  And I stay away from community servers where moderators can do whatever they want.

**Comment by karthikcodes6** [comment]
I'm facing the same issue
