### ISSUE TITLE
[Bug]: app crashed after remove webview

### ISSUE THREAD

**Issue by zhanghaobin** [electron/electron#41071]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.26

### What operating system are you using?

macOS

### Operating System Version

macOS 14.1.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

removing webview wont cause crash

### Actual Behavior

app crash after remove webview

### Testcase Gist URL

https://gist.github.com/zhanghaobin/97fb2863be7aa9de6f3f0a502d69c01a

### Additional Information

1. setup 'close' event listener for webview to remove the webview element
3. call `alert()` and `window.close()` in webview
4. app crash

**Comment by zhanghaobin** [comment]
I try out other electron versions, it keep crash on electron <= 25.2.0, is there any workaround for lower version?

**Comment by ckerr** [comment]
@zhanghaobin, Electron 26 is the oldest supported version. Since you're saying this is working in the supported versions, I'm going to close this ticket. I know this isn't the outcome you were looking for, but I'd strongly recommend you to update the application in question to use a supported version of Electron.

We generally support the latest three major version numbers released. LTS support is problematic because the project also needs to stay up-to-date with Chromium and our team's resources are limited.
