### ISSUE TITLE
Routing stops working after new deployment NextJS

### ISSUE THREAD

**Issue by cervantes-x** [electron/electron#41226]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

After deploying a new version of my NextJS application to Vercel I should automatically get the latest version bundle when navigating in the app like in a normal browser. 

### Actual Behavior

After deploying a new version of my NextJS application to Vercel, I am unable to navigate. When I click on a link I see a network request and response but the navigation is not occurring. 

#### NextJS version
14.1.0 (app router)

I am loading the nextjs application in the browserwindow using BrowserWindow.loadURL(LINK_TO_VERCEL_DEPLOYMENT);

The application works fine before uploading a new deployment.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
