### ISSUE TITLE
[Bug]: ReferenceError: require is not defined (PRODUCTION APP)

### ISSUE THREAD

**Issue by secoldPrivate** [electron/electron#41308]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

??

### Expected Behavior

I want to be able to use contextIsolation=true, and nodeIntegration=false..

    

### Actual Behavior

However, when these settings are setup i get the error:

"Uncaught ReferenceError: require is not defined"

This ONLY occurs when i build the application with electron builder.
The exact error occurs:
```
    ,
    4300: ie=>{
        "use strict";
        ie.exports = require("buffer")
    }
    ,
    6113: ie=>{
        "use strict";
        ie.exports = require("crypto")
    }
    
```

Which appears to be deep within the renderer process (which is running electron via the: 
https://github.com/maximegris/angular-electron

This ONLY occurs when running a built and installed exe;
Running the app with npm run start, locally runs everything fine.

I've seen a lot of advice for 'turn on node integration, and turn OFF context isolation", but these are not recommended, and as this is a B2C client-facing production app and not a toy project, I cannot make it insecure like this.

What is the ACTUAL way to get this to work without taking security shortcuts?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
