### ISSUE TITLE
[Bug]: window.open not work at all 

### ISSUE THREAD

**Issue by YuInseo** [electron/electron#41322]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Hey guys, im using electron with next.js 
And I am trying to open window if user clicked the button on the window application

### Actual Behavior

Hey guys, im using electron with next.js 
And I am trying to open window if user clicked the button on the window application

I tried this:
rederer.js

```ts
export function test() {
    window.open('https://github.com', '_blank', 'width=200,height=200')
}
```

button.tsx

```tsx
import {test} from "@/main/renderer";

 <div className="hover:cursor-pointer">
       <Button onClick={
           async () => {
               test()
           }
       }>test</Button>
</div>
 ```

it works pretty well in chrome, but it doesn't work on my windows app how can I open new window browser? and returning back from window browser to window application

**Comment by sebbenmbarek** [comment]
Hi @YuInseo,

I don't think this is a bug but related to the way Security works in the Electron container

Have you looked into the Console of the Developer Tools?
It's likely to be caused by the Content-Security-Policy set in your index.html page.

Please have a look at this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Also, are you trying to open a Browser Window or a Native Window?
If you are trying to open a Native window, I suggest you look into the API at https://www.electronjs.org/docs/latest/api/browser-window

I hope that helps,
Seb

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
