### ISSUE TITLE
[Bug]: Electron 28 and Puppeteer-core v22 throws ProtocolError: Protocol error (Target.createTarget): Not supported 

### ISSUE THREAD

**Issue by tushar-ghadge** [electron/electron#41357]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.3

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6.4 

### What arch are you using?

x64

### Expected Behavior

I'm connecting puppeteer with electron via websocket debug url:

`const browser = await puppeteer.connect({
        browserWSEndpoint: webSocketDebuggerUrl
})`
`await browser.newPage()`
 should return the Page instance.

### Actual Behavior

I'm trying to get Page using browser.newPage() but its failing with `ProtocolError: Protocol error (Target.createTarget): Not supported`. 

### Testcase Gist URL

https://gist.github.com/tushar-ghadge/360b6838f7ed897f2d966f17daa9dbaa

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by zuituzi0** [comment]
Hi @tushar-ghadge,

I ran into the same issue with Electron not supporting `newPage` directly. A workaround is to create a page first and then control it with Puppeteer. Here's a quick way to do it:

1. **Start Electron with remote debugging:**

   ```javascript
   const { app, BrowserWindow } = require('electron');

   app.on('ready', () => {
     const mainWindow = new BrowserWindow({ show: false });
     mainWindow.loadURL('about:blank');
   });

   app.commandLine.appendSwitch('remote-debugging-port', '9222');
   ```

2. **Connect Puppeteer to Electron:**

   ```javascript
   const puppeteer = require('puppeteer-core');

   (async () => {
     const browser = await puppeteer.connect({ browserURL: 'http://127.0.0.1:9222' });
     const pages = await browser.pages();
     const page = pages[0];

     await page.goto('https://www.baidu.com');
     console.log('Navigated to:', await page.url());

     await page.screenshot({ path: 'baidu.png' });
     await browser.close();
   })();
   ```

This way, you use the existing pages instead of trying to create a new one.

Check out [this repo](https://github.com/TrevorSundberg/puppeteer-in-electron/tree/master) for more details.

Hope this helps!
