### ISSUE TITLE
Docs: Missing 'top-level-storage-access' permission

### ISSUE THREAD

**Issue by panther7** [electron/electron#41368]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.4,
29.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

Inside in docs.

### Actual Behavior

This comparison appears to be unintentional because the types...

### Additional Information

MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccessFor

Tested methods:
* setPermissionCheckHandler
* setPermissionRequestHandler

**Comment by panther7** [comment]
Still issue in 28.2.4 and 29.0.1

**Comment by jkleinsc** [comment]
@panther7 can you clarify the issue here?  You seem to be indicating that Electron documentation is missing something?  If so, what documentation is missing?  If you instead mean that Electron is missing functionality documented at the MDN link, can you provide a testcase?

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-info` label for this reason. If you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated

**Comment by panther7** [comment]
@jkleinsc ofcourse

Tested in Electron Fiddle 0.36.0 (with Electron 29.1.4)

main.js
```js
const { app, BrowserWindow, session } = require('electron')
const path = require('node:path')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  mainWindow.loadURL('https://youtube.com');
}

app.whenReady().then(() => {
  session.defaultSession.setPermissionCheckHandler((_webContents, permission) => {
    console.log('PermissionCheckHandler', permission);
  });

  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

In log see:
```log
...
PermissionCheckHandler top-level-storage-access
...
```

Btw, 'background-sync' permission missing too.

**Comment by panther7** [comment]
In v 29.3.1, but missing in changelog.
