### ISSUE TITLE
screen.getAllDisplays().length always return 1

### ISSUE THREAD

**Issue by Nam16** [electron/electron#41372]
Hi ,

I am using the latest version of electron .  My setup is  1 CPU connected to 2 monitors. 
My scenario is when I removed HDMI cable of both the displays then I want to check if the length of allDisplays() is zero.
But even after removing 2 HDMI cable the length of screen.getAllDisplays().length always shows 1 , the old entry is somehow retained.
Wanted to know if this issue is fixed ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
