### ISSUE TITLE
[Bug]: The user-agent of Chomium has version features with an electric element

### ISSUE THREAD

**Issue by rabbit-yu** [electron/electron#41383]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

28.2.1

### Expected Behavior

If I want to change the user agent of chomium from the source code layer to not include the version number of the electron, instead of simply using mainWindow. webContent. setUserAgent, what changes do I need to make

### Actual Behavior

Because I don't want to expose that I am using the Electron framework, I want to make changes directly from the underlying source code to prevent website detection, rather than simply using mainWindow. webContent. setUserAgent to make surface level changes

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
