### ISSUE TITLE
[Bug]:Simple electron application doesn't start

### ISSUE THREAD

**Issue by kaplinale** [electron/electron#41429]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

latest

### What operating system are you using?

Ubuntu

### Operating System Version

22.04.4 LTS

### What arch are you using?

x64

### Last Known Working Electron version

24-x-y

### Expected Behavior

I can run simple Electron app(electron-quick-start) of latest version

### Actual Behavior

When i try to run electron-quick-start on my laptop pc I see the 100% cpu load of application. I have laptop with intel integrated graphics:
**lspci -k** 
00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 03)
        Subsystem: Lenovo TigerLake-LP GT2 [Iris Xe Graphics]
        Kernel driver in use: i915
        Kernel modules: i915

Gpaphics settings:

**GPU**: Mesa Intel Xe Graphics

**OpenGL (EGL)**
attached

**OpenGL (GLX)**
attached

**Vulkan**
attached
[opengl_egl.txt](https://github.com/electron/electron/files/14389508/opengl_egl.txt)
[opengl_glx.txt](https://github.com/electron/electron/files/14389509/opengl_glx.txt)
[vulkan.txt](https://github.com/electron/electron/files/14389510/vulkan.txt)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
