### ISSUE TITLE
[Bug]: All Electron Apps fail to Render

### ISSUE THREAD

**Issue by aesguitar** [electron/electron#41427]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Whatever recent applications are using

### What operating system are you using?

Windows

### Operating System Version

Windows 22H2 19045.3930

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

Windows to render correctly.

### Actual Behavior

The window does not render correctly. Usually renders as just a black/white/transparent screen (when borderless) or black window with a border. All UI elements on the window appear to be interact-able even though the window is black. The behavior exists on all Electron/Chromium/Chrome apps on my computer.

When moving the window around, strange artifacts are present that look like past rendered frames are frozen within the window.

### Additional Information

Here is a link to the LTT forum where I tried to see if troubleshooting different things would help, but it also goes in to depth on what I've seen and tried. I'll quote a few key observations below. https://linustechtips.com/topic/1549364-chromechromium-app-blank-window/

```
"When hardware acceleration is disabled (such as with the --disable-gpu switch or via config file), the applications display just fine."

"Additionally, when I create a fresh account (both admin and standard) on the PC and open the applications on the new account, the apps work just fine."

"Clear XXX Cache and see if it works"
```

This is 100% reproducible on my system. No error messages appear, no other instabilities are obvious. Drivers are up to date and were last installed following a DDU uninstall.

Issue was first noticed in December '22. Issue has persisted many application updates, windows updates, new GPU (GTX 1070ti to RTX 4080), multiple SFC and other repair utility executions. I have not tried re-installing windows.

Other info:
i7 9700k
RTX 4080
Asus ROG Mobo

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. 

It's also apparent from the issues you linked that the root of the issue is Chromium. You should likely open an issue there.
