### ISSUE TITLE
[Bug]: Full Blank Page

### ISSUE THREAD

**Issue by aarishadhikary** [electron/electron#41431]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

It is Only Showing Blank

### Actual Behavior

Starting But Showing Blank

### Additional Information

![Screenshot 2024-02-26 154827](https://github.com/electron/electron/assets/160851989/f061271a-1f0b-40ad-b452-a196a8aeb5b3)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. 

Additionally, Electron v17 is not supported and has not been in some time.
