### ISSUE TITLE
[Question] Does electron's builtin autoUpdater support custom provider?

### ISSUE THREAD

**Issue by kafka-yu** [electron/electron#41443]
As title said, do we have something like the 'electron-updater's AppUpdater:
```
  this._updater.setFeedURL({
      url: feedURL,
      provider: 'custom',
      updateProvider: CustomProvider,
    });
``` 

With the CustomProvider, I can control where the update package downloads from. Currently it can only be from the same path as the YAML file if using the updater from 'electron'.

Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
