### ISSUE TITLE
[Bug]: The desktopCapturer.getSources method  Unable to obtain current window information

### ISSUE THREAD

**Issue by Gcbeginner** [electron/electron#41442]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 家庭中文版

### What arch are you using?

x64

### Expected Behavior

const { desktopCapturer, BrowserWindow } = require('electron');

const win = new BrowserWindow({
  width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true, 
      contextIsolation: false
    }
});

desktopCapturer.getSources({ types: ['window'] }, (error, sources) => {
  if (error) throw error;

  
  const source = sources.find(s => s.name === win.getTitle());

  if (!source) {
    console.error('The desktopCapturer.getSources method  Unable to obtain current window information');
    return;
  }

### Actual Behavior

The desktopCapturer.getSources method  Unable to obtain current window information

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by galaxy-s10** [comment]
same
