### ISSUE TITLE
[Bug]: Auto-updates not working on MacOS if app is not installed in Applications directory

### ISSUE THREAD

**Issue by pulkit0012** [electron/electron#41508]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I am using the auto-updater module from Electron framework to implement auto updates for my Electron application on MacOS. The updates succeed only if the app is installed in the Applications folder. If it is installed somewhere else, the updates do not work. I am using the implementation detailed here- https://github.com/electron/electron/issues/5020#issuecomment-477636990. The download succeeds but the app doesn't update on relaunch.

### Actual Behavior

The download succeeds but the app doesn't update on relaunch.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by Lsnsh** [comment]
Similar problem, in the `electron@29.1.0` and macOS, I use the [update-electron-app][0] to detect and update applications. When release a new version, can see the update information on the update website. When open the application, can see that the application will access the update website, but will not download the new version, which confuses me.

https://update.electronjs.org/lsnsh/first-electron-app/darwin/v0.0.6

I am not familiar with the context of [autoUpdater][1]. After reviewing the documentation and searching for relevant repositories, I found that the application only downloads and updates when running in the "Application" directory, whereas I have been running in the "Download" directory before.

For "macOS applications, they need to run in the Application directory in order to be updated automatically". For the requirements of the directory, there is no relevant description found in the documentation, and the documentation may need to be updated. It feels like it is as important as the application signature. Knowing it early can avoid some duplicate searches and attempts.

Some related docs and issues links:

- https://www.electronjs.org/docs/latest/tutorial/tutorial-publishing-updating
- https://www.electronjs.org/docs/latest/tutorial/updates
- https://www.electronjs.org/docs/latest/api/auto-updater
- https://github.com/electron/update-electron-app/issues/2
- https://github.com/Squirrel/Squirrel.Mac/issues/201
- https://github.com/electron/electron/issues/29943#issuecomment-1008437621

[0]: https://github.com/electron/update-electron-app
[1]: https://www.electronjs.org/docs/latest/api/auto-updater
