### ISSUE TITLE
[Bug]: when the savePage method was executed, it blocked the invocation of the rear interface. the console showed that the interface was canceled. I've tested it with a lot of experiments

### ISSUE THREAD

**Issue by qianghaifeng** [electron/electron#41509]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.12

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Expected Behavior

I hope can save page and normal request is not canceled

### Actual Behavior

// when the page is finished loading
mainWindow.webContents.on('did-finish-load', async () => {
         // save the login page locally    second params  HTMLComplete and HTMLOnly have problems,  request sometimes is canceled
         mainWindow.webContents.savePage('./index.html', 'HTMLComplete').then....
  
});

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. 

Electron 20.3.12 is not supported and has not been in some time. If after consulting with discussion groups above this is determined to be an Electron issue, you can open another issue with a reproducible sample.
