### ISSUE TITLE
[Bug]: JavaScript is not loading in renderer using loadURL

### ISSUE THREAD

**Issue by ashwin-mittal** [electron/electron#41533]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

If JS fails to load, the `did-fail-load` event should emit because in this case, it is failing silently without error.

### Actual Behavior

Actually loading is successful, `did-fail-load` is not emitted, but in the renderer browser window, I am getting only the document file - index.html and CSS file `main.<revision>.css` is fetched, but the JS file is not there in sources tab under the dev tools. The console is also clear with no errors.

This is how the script is included in the HTML file (index.html):
```
<script defer="defer" src="./static/js/main.<revision>.js"></script>
```

### Additional Information

The issue is happening when the app auto starts and URL loads in a renderer window in the background.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
