### ISSUE TITLE
[Feature Request]: Is App.asar file encryption support available?

### ISSUE THREAD

**Issue by Samarth-su** [electron/electron#41616]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am dealing with security vulnerabilities. I am trying find out a simple way to prevent app.asar unpacking/extraction, without code signing(free solution).
Deobfuscation of **app.asar** file and main.js is possible through app.asar extraction. I need to prevent that from happening.

### Proposed Solution

Any help regarding how we can prevent app.asar to get extracted with minimal changes. 

### Alternatives Considered

Maybe we can do encryption of the file or maybe add a checksum. without our build being broken.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
