### ISSUE TITLE
[Documentation][Bug]: Getting Started last step

### ISSUE THREAD

**Issue by angel-luis** [electron/electron#41669]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.5

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`npm run make` working without any error as expected in the guide.

### Actual Behavior

```
> electron-forge make

✔ Checking your system
⠋ Loading configuration
✖ Loading configuration
  › Cannot find module '@electron-forge/plugin-fuses'
...
```

### Additional Information

To fix this I only had to execute: `npm install --save-dev @electron-forge/plugin-fuses`.

The issue is reached in two parts of the docs:
- https://www.electronjs.org/docs/latest/tutorial/tutorial-packaging
- https://www.electronjs.org/docs/latest/tutorial/quick-start#package-and-distribute-your-application

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by angel-luis** [comment]
Sorry @codebytere but I just wanted to report a bug in the documentation, I don't need help as it has an easy fix, but I don't know where to report documentation errors exactly.
