### ISSUE TITLE
[Bug]: When making a folder using Electron-forge, after installing the exe file, a green boot page will pop up. How to close it?

### ISSUE THREAD

**Issue by xlorne** [electron/electron#41664]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.4

### What operating system are you using?

Windows

### Operating System Version

window11 x64 amd64

### What arch are you using?

x64

### Expected Behavior

How to remove this boot page? And I found that after closing the boot page, the program will exit and then reopen.

### Actual Behavior

<img width="197" alt="d9d55e9453f0d3d842d745e4a580515" src="https://github.com/electron/electron/assets/5245347/311b6b7b-3ede-4e20-9e4a-ab9bcde94d03">

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
