### ISSUE TITLE
[Bug]: setContentSize on BrowserWindow resizes the whole window anyway

### ISSUE THREAD

**Issue by veodko** [electron/electron#41665]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045

### What arch are you using?

x64

### Expected Behavior

According to the docs, `setContentSize` should "resize the window's client area (e.g. the web page) to width and height." which at least to my understanding, should leave the window size intact and change the size of the inner render area.

### Actual Behavior

`setContentSize` resizes the whole window no matter if `useContentSize` is set or not.

### Testcase Gist URL

https://gist.github.com/veodko/7d732656b42cb1b62edec9ba04234520

### Additional Information

I know this can be mitigated by using a `BrowserView` attached to the window, but in some cases it's kind of an overkill and produces an overhead of a spare webview instance that is not used (leaving the window "empty" and using `BrowserView` for the main content still shows an empty instance in devtools inspect). In my use case, I actually want to show another `BrowserView` **under** the main webview, but not so that it overlaps. I wanted to resize the content by subtracting the height of my additional view, but it's impossible. I ended up using two views at the moment, but this produces a third "abandoned" empty webview instance from the original `BrowserWindow` which probably consumes some unneccessary resources.

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by veodko** [comment]
Hmm, I quite don't get how is this a question and not a bug report or invalid documentation.
The docs state that this method changes the window's client area, not the window. But in reality the window size changes too, so IMO it is a bug, otherwise what is the point of this function if it behaves the same as `setSize`?
