### ISSUE TITLE
Unknown Error While connecting real device with appium inspector

### ISSUE THREAD

**Issue by praveenkumar06me** [electron/electron#41767]
Hello!
I was trying to connect my real device(Realme X2) but getting an unknown error message, but when I am using another device it is perfectly fine.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
