### ISSUE TITLE
[Bug]: Electron App Hangs

### ISSUE THREAD

**Issue by chellaprabujc** [electron/electron#41770]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.25

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 64bits

### What arch are you using?

x64

### Expected Behavior

![image](https://github.com/electron/electron/assets/137065807/2ffb7dbf-9c1f-4c0a-86ed-900c0e994334)

We have a customer report that the electron app is launched and stays frozen at the launch window. The issue is reproducible on this specific machine.

We added some logs on Renderer but there seem to be no evidence of renderer been launched.

Frozen State:
![image](https://github.com/electron/electron/assets/137065807/9b53b89c-a566-4784-9075-39e8f3c1d7b1)

### Actual Behavior

Ideally the App should launch and establish a WebRTC for Screen sharing. This works for all the devices except for one

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
