### ISSUE TITLE
[Bug]: Setting up and clicking on Windows notifications

### ISSUE THREAD

**Issue by wonkyungup** [electron/electron#41771]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

Window 11, version 23H2

### What arch are you using?

x64

### Expected Behavior

1. App notifications should show up in the notification settings and you should be able to turn them on/off.

2. Click events should be available in the Windows Notification Center.

### Actual Behavior

1. I clicked on turn off all notifications about Electron in notifications, but I don't know where to set it. I don't see the on/off switch at all.

2. I can't click on the Windows Notification Center, what should I do?

**Comment by wonkyungup** [comment]
Latest version 
29.2.0, 28.2.10 also have the same issue

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
