### ISSUE TITLE
main executable failed strict validation

### ISSUE THREAD

**Issue by jin-hua-z** [electron/electron#41817]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

macOS

### Operating System Version

macos big sur 11.5.1

### What arch are you using?

x64

### Last Known Working Electron version

13.6.9

### Expected Behavior

package 

### Actual Behavior

Command failed: codesign --sign .... main executable failed strict validation

### Additional Information

 "build": {
        "asar": false,
        "asarUnpack": "node_modules/puppeteer/.local-chromium/**/*",
        "productName": "XXX",
        "appId": "appid,
        "directories": {
            "output": "dist_electron"
        },
        "publish": [
            {
                "provider": "generic",
                "url": ""
            }
        ],
        "nsis": {
            "oneClick": false,
            "perMachine": true,
            "allowElevation": true,
            "allowToChangeInstallationDirectory": true,
            "installerIcon": "./src/assets/icons/icon.ico",
            "createDesktopShortcut": true,
            "createStartMenuShortcut": true,
            "shortcutName": "XXXX"
        },
        "files": [
            "**/*"
        ],
        "dmg": {
            "contents": [
                {
                    "x": 410,
                    "y": 150,
                    "type": "link",
                    "path": "/Applications"
                },
                {
                    "x": 130,
                    "y": 150,
                    "type": "file"
                }
            ]
        },
        "mac": {
            "icon": "src/assets/icons/icon.icns"
        },
        "win": {
            "icon": "src/assets/icons/icon.ico"
        },
        "linux": {
            "icon": "src/assets/icons"
        }
    },

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. 

Additionall, Electron v13 hasn't be supported in some years. If reaching out in forums yields the root issue as an Electron bug, you'll need to demonstrate it happens on a supported version.
