### ISSUE TITLE
[Bug]: in my electron i am using multiple webview and i am not able to get which webview is in focus or even onclick event

### ISSUE THREAD

**Issue by NormVg** [electron/electron#41848]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint

### What arch are you using?

x64

### Expected Behavior

in my electron i am using multiple webview and i am not able to get which webview is in focus or even onclick event
by 
const webview = document.getElementById('ws-1');

webview.addEventListener("click",() => {
  console.log("qwe")
})

### Actual Behavior

.

**Comment by murtaza030** [comment]
Hi in which file

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
