### ISSUE TITLE
打包后的安装包在安装时会卡死

### ISSUE THREAD

**Issue by 2502778498** [electron/electron#41901]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.4.3

### What operating system are you using?

Windows

### Operating System Version

win10  64位

### What arch are you using?

x64

### Expected Behavior

正常安装

### Actual Behavior

安装包在win10电脑上安装时会卡死在99%，偶发事件

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by 2502778498** [comment]
thanks
