### ISSUE TITLE
[Bug]: Electron cannot run inside a docker container

### ISSUE THREAD

**Issue by slayt12** [electron/electron#41919]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Other (specify below)

### Operating System Version

fedora docker container

### What arch are you using?

x64

### Expected Behavior

Start electron app

### Actual Behavior

While in a docker container, I was first thrown a message when running ```electron-forge start``` that node_modules/electron/dist/chrome-sandbox must be owned by root and to change permissions to 4755, which was then done. 
The issue I cannot get around after that was changed, is still running ```electron-forge start``` and the next message is:
```
$ electron-forge start
✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [0.4s]
✔ Running generateAssets hook

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[1486:0422/011858.545757:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
[1488:0100/000000.573871:ERROR:zygote_linux.cc(672)] write: Broken pipe (32)
```

Are there any other changes I should look into or is there a bug when running inside a docker container?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
