### ISSUE TITLE
[Feature Request]: Computer shutdown/sleep request

### ISSUE THREAD

**Issue by JuanIrache** [electron/electron#42038]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

With Windows, you can use node's child_process exec to run the _shutdown_ command and power the computer off, for example, if a long series of automated tasks has been left running overnight. On Mac and Linux this would need to be preceded by _sudo_, so it's not practical without breaking things, I believe. 

### Proposed Solution

Could some functions that instruct the OS to turn off or sleep be implemented as part od the API? Or does something like that already exist?

### Alternatives Considered

I understand this topic may have security implications, but apps like Adobe Media Encoder do this, so there may be a way for the OS to allow this, right?

### Additional Information

Thanks

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

Beyond that - I agree that the OS can do it, but this is something that should be done in e.g. a native Node.js module, and not a part of the core API.
