### ISSUE TITLE
[Bug]: win.setWindowButtonPosition it not work

### ISSUE THREAD

**Issue by gaoyia** [electron/electron#42081]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0-30.0.2

### What operating system are you using?

macOS

### Operating System Version

14.4.1 (23E224) Apple M3 16 GB

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to move the window button position

### Actual Behavior

not move

**Comment by gaoyia** [comment]
https://github.com/gaoyia/electron-bug-report

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
