### ISSUE TITLE
[Bug]: The CPU usage of the rendering process is high (10% to 20%) for some users.

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#42105]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.26

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

ia32

### Expected Behavior

I want to know what really happened? How Do I Solve the Problem of High CPU Usage?

### Actual Behavior

Several hours after some user applications are started, the CPU usage of the main rendering process is high (10% to 20%, 8-core CPU), and a large amount of CPU resources are consumed in the kernel.
User CPU usage：
![image](https://github.com/electron/electron/assets/26533635/13fd01e8-a2da-48a7-b7d5-9821d8020573)
devtools  recording ：
![image](https://github.com/electron/electron/assets/26533635/2d626240-7b05-497d-83af-852fa987dc9a)
CPU sampling for WPA recording on main thread：
![image](https://github.com/electron/electron/assets/26533635/6c967cea-daa7-402d-a18b-6c625ff87ee1)
CPU sampling for WPA recording on sub thread(node_bingdings)：
![image](https://github.com/electron/electron/assets/26533635/ffbb598d-ae35-46f5-96e3-769cfe871d99)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by yangyusiya** [comment]
I have the same problem in electron 22.3.27，Is there a solution to this problem at present ？
