### ISSUE TITLE
[Bug]: Happens on 30 https://github.com/electron/electron/issues/40328#issue-1961571600

### ISSUE THREAD

**Issue by YeesterPlus** [electron/electron#42170]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2 node 20.11.1 and chromium 124.0.6367.91

### What operating system are you using?

Other Linux

### Operating System Version

Linux debianhppc 6.6.13+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1~bpo12+1 (2024-02-15) x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

for it to open

### Actual Behavior

it errored: 
Gtk-Message: 12:33:59.501: Failed to load module "appmenu-gtk-module"
[43152:0514/123359.907227:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.

### Additional Information

It is on my acellus right when i used the 1 rpf and 60 fpr
acellus --no-sandbox --disable-gpu-compositing --in-process-gpu --no-zygote --no-network

**Comment by YeesterPlus** [comment]
r as in  internet reload

**Comment by YeesterPlus** [comment]
and build it

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by YeesterPlus** [comment]
I reported you to satmandu Supechicken and skycocker
