### ISSUE TITLE
本地调试检测更新没有问题，打包成功后，安装electron应用时提示Cannot find module 'electron-updater' 

### ISSUE THREAD

**Issue by CaoRuimiao** [electron/electron#42207]
![Cannot find module 'electron-updater' after build](https://github.com/electron-userland/electron-builder/assets/15841706/4f0a1937-efe1-4e53-bfc8-b9864df92a21)

`
"dependencies": {
    "electron-log": "^5.1.4",
    "electron-updater": "6.1.8"
},
"devDependencies": {
    "electron": "^27.0.2",
    "electron-builder": "^22.9.1"
},
`

有人遇到吗？该怎么解决？

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
