### ISSUE TITLE
[Bug]: add host-rules by app.commandLine.appendSwitch not work

### ISSUE THREAD

**Issue by oohusl** [electron/electron#42218]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.*

### What operating system are you using?

macOS

### Operating System Version

macOS 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

17.0.0

### Expected Behavior

resolve the domain names by host-rules

### Actual Behavior

host-rules doesn't work

### Additional Information

app.commandLine.appendSwitch('host-rules', 'MAP baidu.com 127.0.0.1')

const createWindow = () => {

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  mainWindow.loadURL("https://www.baidu.com")
  mainWindow.webContents.openDevTools();
};

baidu.com still resolve right ip, not the test ip 172.0.0.1

**Comment by clavin** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
