### ISSUE TITLE
[Bug]: app not loading

### ISSUE THREAD

**Issue by DeclanROfficial** [electron/electron#42259]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

idk, the latest from git hub?

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

working and letting me login

### Actual Behavior

opens but i am left on blank screen
![image](https://github.com/electron/electron/assets/164704434/e731254a-5977-4e05-b668-677e0bb8b40b)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by DeclanROfficial** [comment]
no

-------- Original Message --------
