### ISSUE TITLE
[Bug]: Error: Can not find Squirrel (when implementing auto-update in Windows) 

### ISSUE THREAD

**Issue by veena-mandhan-iphtech** [electron/electron#42307]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version
^26.0.0

### Operating System
Windows 11 Home

### Additional Information

I am working on an electron app using Angular. I created a `dmg` and a `zip` for Mac, an `nsis` for Windows, using `electron-builder`
When implementing autoupdate from electron, auto-update works as expected in Mac.
`const {  autoUpdater } = require('electron');`

However in Windows, it gives me this error `Error: Can not find Squirrel` when I try to implement auto-update.
As suggested by many answers, I created the Windows build with electron-forge. Now I am facing more issues with the build that I would rather like to have the build without autoUpdate.

Isn't there a way to implement auto-update with electron-builder itself, by just providing it squirrel somehow. Or any better way to handle this situation?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
