### ISSUE TITLE
[Bug]: When the electronic application continues to run, there is an occasional white screen phenomenon

### ISSUE THREAD

**Issue by luxiaoinfo** [electron/electron#42310]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 家庭中文版，操作系统版本22631.3593

### What arch are you using?

x64

### Last Known Working Electron version

26.1.0

### Expected Behavior

No white screen

### Actual Behavior

The project is realized by electronic+vue3

There is a timer in the program to request the back end interface every 1.5 seconds, and the page is set to refresh automatically every hour. Then again request the persistent request interface.

The obtained data is then displayed on the page. The whole process does not produce new file resources, but only changes the data,

When the app continues to run for a period of time (usually 24 hours), there is a white screen phenomenon. Through observation, it is found that the top option in the frames column of application does not load resources correctly, but becomes chrome-error: chromewebdata,

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
