### ISSUE TITLE
[Bug]: Why electron can't be run with npm script on linux?

### ISSUE THREAD

**Issue by panyann** [electron/electron#42343]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^30.0.9

### What operating system are you using?

Ubuntu

### Operating System Version

No LSB modules are available. Distributor ID:	Ubuntu Description:	Ubuntu 24.04 LTS Release:	24.04 Codename:	noble

### What arch are you using?

x64

### Expected Behavior

`npm run e` should run `electron .` command

### Actual Behavior

Error:
```
[80844:0602/184247.521974:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /mnt/DaneGry/Dane/Projekty/2FAPro/2fa-pro/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/mnt/DaneGry/Dane/Projekty/2FAPro/2fa-pro/node_modules/electron/dist/electron exited with signal SIGTRAP
```
Fixing chrome-sandbox file doesn't help.

### Additional Information

Let's say that in the package.json I have a script:
`"e": "electron ."`
Which is used as `npm run e`.
It doesn't work on linux, but earlier on Windows it was working.
Using `electron .`, without npm, works.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
