### ISSUE TITLE
[Bug]: There is no network info in devtool performance recording when using protocol handle http and https request

### ISSUE THREAD

**Issue by CurryYangxx** [electron/electron#42379]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.0

### What operating system are you using?

macOS

### Operating System Version

14.5 (23F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

show network waterfall in performance recording

### Actual Behavior

When I use http handle like this
```
if (!protocol.isProtocolHandled('https')) {
    protocol.handle(httpsScheme, async request => {
      return net.fetch(request, { bypassCustomProtocolHandlers: true });
    });
  }
  if (!protocol.isProtocolHandled('http')) {
    protocol.handle(httpScheme, async request => {
      return net.fetch(request, { bypassCustomProtocolHandlers: true });
    });
  }
```
there is no network informantion in performance tab, but we can see the request in the network tab
<img width="1084" alt="image" src="https://github.com/electron/electron/assets/163384738/840948ab-6cd6-4c9d-af1c-a99ec9702be8">
<img width="613" alt="image" src="https://github.com/electron/electron/assets/163384738/a1f54df5-ad4b-4faf-8e3d-d82d6e255616">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
