### ISSUE TITLE
[Feature Request]:Other than hiding the default buttons and using custom ones, are there other ways to adjust the spacing of traffic light buttons?

### ISSUE THREAD

**Issue by nianyi-778** [electron/electron#42456]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

除了隐藏默认按钮并使用自定义按钮,还有其他方法可以调整红绿灯按钮的间距吗? 

<img width="370" alt="image" src="https://github.com/electron/electron/assets/23355645/ba88d17d-76ce-4422-9423-8d692893c55d">

### Proposed Solution

无建议

### Alternatives Considered

无方案

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
