### ISSUE TITLE
[Bug]: File menu item automatically renamed to "Settings..."

### ISSUE THREAD

**Issue by adityatoshniwal** [electron/electron#42583]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

 30.0.5

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I am from pgAdmin team and we're working on integrating Electron. I noticed that my menu labelled as "Preferences" is automatically renamed as "Settings...". This doesn't happen on Windows.
Screenshot below:
<img width="785" alt="image" src="https://github.com/electron/electron/assets/31855755/dbe59519-d858-489d-bb06-4fee236fc109">

### Actual Behavior

Auto renaming the menu should be optional.

**Comment by adityatoshniwal** [comment]
Hi,
Here's the gist - https://gist.github.com/adityatoshniwal/9a97d779ca50617c765ea0aeae61cce4

**Comment by codebytere** [comment]
@adityatoshniwal this looks unfortunately like something Electron doesn't have much control over - it looks like a change in Ventura resultant of the system wide change from `System Preferences` to `Settings`, which appears to have some overactive auto-replacement.

It looks like there used to be a way to revert it: https://lapcatsoftware.com/articles/Preferences.html

but it's since been removed. This will happen in any macOS app - if someone comes up with a new way to revert it we're happy yto take a look but for now there's nothing we can do here.

**Comment by adityatoshniwal** [comment]
I got it. So it's a OS problem. Thank you for looking into it.

**Comment by adityatoshniwal** [comment]
@codebytere BTW, we're using NW.js right now and the menu remains `Preferences` without any issues.

**Comment by adityatoshniwal** [comment]
Hi @codebytere,
Any comments? It looks possible otherwise NW.js would have also renamed to Settings.

**Comment by adityatoshniwal** [comment]
Should I open a new bug as there is no more response on this?
