### ISSUE TITLE
[Feature Request]: Enable Chromium MacLoopbackAudioForScreenShare flag

### ISSUE THREAD

**Issue by ofagbemi** [electron/electron#42605]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

From [the docs](https://www.electronjs.org/docs/latest/api/desktop-capturer#caveats)
> navigator.mediaDevices.getUserMedia does not work on macOS for audio capture due to a fundamental limitation whereby apps that want to access the system's audio require a [signed kernel extension](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/KernelExtensions/KernelExtensions.html). Chromium, and by extension Electron, does not provide this.

Chromium added a [`MacLoopbackAudioForScreenShare` flag](https://chromium.googlesource.com/chromium/src/media/+/b8c61cfab744c6ca17f036ebf1c5bfc0acd3a97f%5E%21/base/media_switches.cc) a little while ago to enable system audio recording. Does that mean it's now possible to support audio capture natively?

### Proposed Solution

Support audio capture on screen recordings on MacOS with the `MacLoopbackAudioForScreenShare` Chromium flag

### Alternatives Considered

I've considered packaging another app with mine to capture system audio. I'd like to avoid this if possible — we're really concerned with keeping the wrapper around our web app light.

### Additional Information

I tried passing the Chromium flag in via `commandLine.appendSwitch`, and I still get `renderer.js:34 DOMException: Could not start audio source`. Here's [a quick Electron Fiddle](https://gist.github.com/ofagbemi/a06f95980d9e6266a18a47e8eb42ee9c).

**Comment by ozturkkl** [comment]
Anyone out there? Should we tag someone here to get some visibility?

**Comment by codebytere** [comment]
It looks like this is partially broken in Chromium too. I can try to take a better look sometime soon but given it's an experimental feature in Chromium and also not part of our public API i can't promise when i'll get to it.

**Comment by hartbeatnt** [comment]
@codebytere thanks for looking into this, and I understand that it might take a while on your end. In the meantime, do you have any recommendation of where I would look in the codebase to try to implement this on a fork?

**Comment by marcello3d** [comment]
> It looks like this is partially broken in Chromium too.

@codebytere do you have a link or repro for this? would love to learn more!

**Comment by codebytere** [comment]
@marcello3d - just opened https://issues.chromium.org/issues/353556451

**Comment by marcello3d** [comment]
> @marcello3d - just opened https://issues.chromium.org/issues/353556451
> 
> Is there a reason you aren't able to use `navigator.mediaDevices.getDisplayMedia`? I've put together this repro which records sound for me just fine:
> 
> https://gist.github.com/4104b5d7d5bcbf94cd1a8011005bef3e

ooh, that gist is super helpful, thanks for making that! it works for me on macOS 14.5 with electron 31.2.1 and will be a helpful reference.

The two differences:
1.  we were setting `audio: { mandatory: { chromeMediaSource: 'desktop' } }` instead of `audio: true` (which works on Windows. 
    - if I set that to true it just crashes the renderer process on macOS (I don't see the error from your chromium issue in Console.app logs, but I'm not sure how to get a formal stack trace from the renderer process crashing)
2. we haven't configured a `setDisplayMediaRequestHandler`, I will try that

**Comment by codebytere** [comment]
@marcello3d ah yeah - `setDisplayMediaRequestHandler` is a necessary prerequisite to using `navigator.mediaDevices.getDisplayMedia` and won't work without it. If there's a way we can make that clearer in docs we definitely can! Let me know what happens and if that achieves your use case :)

**Comment by marcello3d** [comment]
I just realized we're using `getUserMedia`, not `getDisplayMedia`, which might explain the crash!

our current flow is:
1. call `desktopCapturer.getSources` on main and IPC the list of sources and thumbnails
2. render a UI in web with the thumbnails and a checkbox for capturing audio
3. call `await navigator.mediaDevices.getUserMedia` with:
```
video: {
    mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: this.config.deviceID,
    },
},
```

if I change this to getDisplayMedia with `{ audio: true, video: true }` and add the request handler, it works (with audio!), but the request doesn't include any of the parameters from getDisplayMedia (for example, if I do `video: { deviceId }`). 

I'll need to either rebuild the window chooser UI in electron (rather than our web app, so not ideal) or exfiltrate some state to be used by the request handler via IPC

**Comment by marcello3d** [comment]
> If there's a way we can make that clearer in docs we definitely can!

so we started using getUserMedia because this page suggests it: https://www.electronjs.org/docs/latest/api/desktop-capturer

Not sure if `MacLoopbackAudioForScreenShare` is stable enough to mention in the caveats section (maybe a link to this ticket?). 

Might be nice to have an example with `setDisplayMediaRequestHandler` and `navigator.mediaDevices.getDisplayMedia`

**Comment by codebytere** [comment]
@marcello3d there are a few more properties we could potentially expose, but unfortunately we probably won't be able to expose the device ids without patching or something for the same reason they wouldn't show up when using `navigator.mediaDevices.enumerateDevices()` and why you can't request a device by id via `navigator.mediaDevices.getDisplayMedia` - it's disallowed by [spec for privacy reasons](https://www.w3.org/TR/screen-capture/#deviceId).

More specifically - `content::MediaStreamRequest` does have properties for requested [audio and video ids](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/media_stream_request.h;l=77-78;drc=4cc063ac39c4a0d1f6011421b259a9715bb16de1;bpv=0;bpt=1) but they're not populated when `navigator.mediaDevices.getDisplayMedia` is called, so I don't think they'd address your use case.

**Comment by marcello3d** [comment]
I think that’s fine. I don’t mean to suggest we expose more information to the web browser, but rather allow the fields the browser passes to getDisplayMedia() to be accessed in electron main’s request handler. We’re using preload + context bridge + IPC to expose the device ids that desktopCapturer.getSources() returns.

Right now the `setDisplayMediaRequestHandler` callback receives a very simple object (the WebFrameMain and a few booleans), but maybe that’s all chromium exposes?
