### ISSUE TITLE
Would you Recompile your App for Windows on the new Snapdragon X?

### ISSUE THREAD

**Issue by iaseth** [electron/electron#42648]
Recently some of the biggest laptop brands have launched Windows Laptops with the new Snapdragon X processors based on Arm Architecture. 

Snapdragon X in 2024 can potentially have a similar effect on Windows computers as the M1 chips had on Macs in 2020. While it can run x86 apps in 'emulation' with only 10% performance loss, it can be beneficial to optimise your app for Arm to get the best performance. Google Chrome officially has a Windows Arm version for Snapdragon X Elite laptops. Many others like Adobe are following suit.

Where do Electron devs stand in this? Do you think it could be worth it to release 2 version of installer for your app for windows - one for x86 and another for Arm? What would the process for creating this Arm version involve?

**Comment by SpacingBat3** [comment]
As someone who has ARM devices (both RPi with Linux and Windows ARM laptop) and is Electron dev I thought I'll share my thoughts on my thread.

> Snapdragon X in 2024 can potentially have a similar effect on Windows computers as the M1 chips had on Macs in 2020

I really hate Windows ARM, not only there's lack of apps for it that are native but also it stands with the serious issue of lack of the compilers as well... At least now some work was done on GCC, but it still didn't really reach stable and many projects don't seem to be using it really. I sometimes think Windows was made to be emulated; it's easier to run x86 software on it with multiple performance issues than struggle running native versions or builds of it, as those are usually not available as binaries and highly experimental due to dependence on GCC...

This is contrary to Linux case; I think GCC supports now ARM for ages in case of Linux ecosystem (which is surely quite obvious why) and more than that, it is fairly easy to compile x86 software with it. I wasn't so successful with CLANG and Windows ARM, going with the open-source games so far I've found only one that works, and I still got serious problems compiling SDL/SDL2 software under MSYS2... Jokes aside, I seriously consider Linux to be far more suited to gaming for that reason than Windows in case of ARM hardware... I think I've also seen weaker hardware than my ARM laptop to perform better with some games on Linux with Wine+X86 emulator combo than when run on Windows 11 ARM... The very thought of possibility for that to be the case makes me just more mad at it.

> Where do Electron devs stand in this? Do you think it could be worth it to release 2 version of installer for your app for windows - one for x86 and another for Arm? What would the process for creating this Arm version involve?

Nothing, since Electron already supports Windows ARM? There are literally binaries to use with the Electron-based software. I already distribute my app for Windows ARM with the similar success as for X86. I guess this thread should be closed due to that. There's just no reason to port something that's already there.

**Comment by VerteDinde** [comment]
Hey folks! As @SpacingBat3 said above, we do currently support a version of Electron that runs on Windows on ARM. We've actually supported that for several years and it's currently available on all major supported lines. 

@iaseth To your question about installers - we don't currently have a Windows on ARM installer for Electron Forge or Electron Builder, but I know several folks have been working on one, and we'll hope to get that into the Forge upstream sometime in the future. If you'd like to raise a feature request for an installer in the Electron Forge repo, you're welcome to do so - that would also help us gauge interest 🙂 

Since WOA is supported in electron/electron, I'm going to close this issue, but will be happy to updates on future installers in Electron's userland. Thanks for filing this request!

**Comment by AndreasKunar** [comment]
@SpacingBat3 - thanks, I totally agree with your comment. One small addition which might get overlooked: The Visual Studio 2022 installer for Windows on ARM (WoA) now also can install clang (besides cmake, git,...), enabling better/easier WoA development. With this, e.g. building llama.cpp for WoA now got almost as good, as building it in WoA's WSL2 with gcc.
