### ISSUE TITLE
[Bug]:  SetCaseSensitiveInfo  enable does not support WebGL.

### ISSUE THREAD

**Issue by gaoyia** [electron/electron#42764]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.1.2

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Electron version

31.1.0

### Expected Behavior

does not support WebGL.

### Actual Behavior

support WebGL

### Additional Information

1. fsutil.exe file SetCaseSensitiveInfo D:\test enable
2. unzip electron.zip
3. in D:\test `.\electron.exe http://webglreport.com/`

**Comment by gaoyia** [comment]
```
PS D:\> mkdir test
PS D:\> fsutil.exe file SetCaseSensitiveInfo D:\test enable
PS D:\> Expand-Archive -Path .\electron-v31.1.0-win32-x64.zip -DestinationPath .\test
PS D:\> .\test\electron.exe http://webglreport.com/
```

<img width="723" alt="7B8BB18F-00A8-4c43-9BCD-DAE1E3707856" src="https://github.com/electron/electron/assets/17539193/f4935fd4-d830-4d4f-8e70-3d96fb6e1a69">

![Dingtalk_20240704200352](https://github.com/electron/electron/assets/17539193/3e1953bd-8d2c-420a-bfab-a9d707a7e1e1)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
