### ISSUE TITLE
[Bug]: How to remove the upload_file_minidump field from the crashes Reporter multipart/form data POST parameter 

### ISSUE THREAD

**Issue by jackieli123723** [electron/electron#43022]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.2

### What operating system(s) are you using?

Windows, macOS

### Operating System Version

 [cpu={"model":"11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz","length":8},arch=x64,platform=win32,chrome=122.0.6261.156,electron=29.4.2]

### What arch are you using?

x64

### Expected Behavior

How to remove the upload_file_minidump field from the crashes Reporter multipart/form data POST parameter 

### Actual Behavior

How to remove the upload_file_minidump field from the crashes Reporter multipart/form data POST parameter

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
