### ISSUE TITLE
[Bug]: In BrowserWindow, I set frame: false and resize: false, but when I want to drag the window, I set the CSS of the div to - webkit app region: drag; Double clicking the div with the mouse will enlarge the window. I tried listening for the will resize event in BrowserWindow, but it didn't work. How can I prevent it from double clicking to enlarge the window

### ISSUE THREAD

**Issue by Czfhuaruan1940129373** [electron/electron#43042]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Window 10

### What arch are you using?

x64

### Expected Behavior

   mainWindow.on('will-resize', resizeWindow)
   function resizeWindow(event, newBounds) {
     event.preventDefault(); 
   }

### Actual Behavior

no work

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
