### ISSUE TITLE
 Failure to close BrowseView will cause the application to occupy more memory

### ISSUE THREAD

**Issue by Hao1617** [electron/electron#43066]
# Failure to close BrowseView will cause the application to occupy more memory
- Program Startup
![企业微信截图_17219859731875](https://github.com/user-attachments/assets/fd0abd23-4862-44ee-9fd6-7171ceada466)
- After using BrowserView
![企业微信截图_17219859974820](https://github.com/user-attachments/assets/ce1497c0-6a7e-4e7a-92a2-f00e6d455c62)
- Closing BrowserView Code
![企业微信截图_17219860362407](https://github.com/user-attachments/assets/2152f553-128d-42fd-9c28-25388cc9aabd)

**Comment by Hao1617** [comment]
How should I deal with this?

**Comment by Hao1617** [comment]
# "electron": "^21.4.4",

**Comment by Hao1617** [comment]
![image](https://github.com/user-attachments/assets/c1a59d4d-0dee-4e08-beed-0fa3039fded2)

**Comment by Hao1617** [comment]
Is it because BrowseView failed to be destroyed?

**Comment by Hao1617** [comment]
## The windows are indeed closed, I don't know where the extra memory comes from.
![image](https://github.com/user-attachments/assets/16d6e884-ecc2-4163-9a32-cb35a05b8f59)
# Oh,my god!

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by Hao1617** [comment]
success
