### ISSUE TITLE
[Bug]: different WebContentsViews  LocalStorage same

### ISSUE THREAD

**Issue by demons-joker** [electron/electron#43081]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 19045.4651

### What arch are you using?

x64

### Expected Behavior

Different WebContentsViews hold different localstorage

### Actual Behavior

![image](https://github.com/user-attachments/assets/1b03c978-294d-4903-8838-245a3fe5d039)
![1722248780694](https://github.com/user-attachments/assets/5028b187-49ad-435e-a1b0-f8a4707b06d3)

I create multiple WebContentsViews with different Partition, Why is the localStorage is the same？

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by demons-joker** [comment]
https://discord.gg/CaUkPyKY

**Comment by demons-joker** [comment]
If this is not a bug, can you provide some suggestions @codebytere
