### ISSUE TITLE
Off-screen rendering for 3D apps

### ISSUE THREAD

**Issue by AspiiiDev** [electron/electron#43190]
Hi,

I’m trying to use Electron’s off-screen rendering feature as described in this example: https://electronjs.org/docs/latest/tutorial/offscreen-rendering.

It says:

> Offscreen rendering lets you obtain the content of a BrowserWindow in a bitmap, so it can be rendered anywhere, for example, on texture in a 3D scene.

For example, by 3D scene I assume this is some sort of graphics API context such as Vulkan or OpenGL?

Is this type of use suitable for 3D applications created in a different context, such as GLFW? What I'd like to do is use this feature as an overlay in my game.

This raises questions about transferring the bitmap from a NodeJs Electron application to a C++ desktop application, event handling, javascript scripting and more...

Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by AspiiiDev** [comment]
Thanks for your reply, it seems that CEF is a much better option for my use case.
