### ISSUE TITLE
[Bug]: re-rendering issue with <_></_> custom tag

### ISSUE THREAD

**Issue by cdxxotus** [electron/electron#43193]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.25

### What operating system(s) are you using?

macOS

### Operating System Version

Soloma

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When re-rendering, the tag should be correctly re-render.

### Actual Behavior

When re-rendering, the tag is duplicated.

### Additional Information

https://github.com/user-attachments/assets/f5f3b99e-d632-46ea-a2c5-b0636cc90325

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by cdxxotus** [comment]
thank you @codebytere! i will visit communities :)
