### ISSUE TITLE
[Feature Request]: Get the app metadata from exe

### ISSUE THREAD

**Issue by cangSDARM** [electron/electron#43267]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

electron-builder can set some properties for the app metadata like buildVersion
![image](https://github.com/user-attachments/assets/95f5b59f-807d-4647-908f-20d7e9e4a413)
But it doesn't seem to get the relevant field in electron(And the data does not seem to be correct, such as app.getVersion(). I think it should return the exe's metadata first, not the package.json)

### Proposed Solution

add some fields or getter to get those metadatas

### Alternatives Considered

add a hint into the doc

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
