### ISSUE TITLE
[Bug]: Xbox pad doesn't work anymore on Electron 26+ -

### ISSUE THREAD

**Issue by Amiga4ever** [electron/electron#43263]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Any above 27+

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

26.6.10

### Expected Behavior

Phaser 2 game - Xbox 360/X/One pad works. Steam Deck analog/dpad works. 

### Actual Behavior

Phaser game- Xbox 360/X/One not detecting at all. For example Dual Sense works fine. Same with Steam Deck. Nothing works regarding Stem Deck controllers (analog/dpad).
I have tested all Electron versions and issue started after build 26.6.10. All below works fine.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by Amiga4ever** [comment]
Hi.
But is is a bug as xbox pad and steam deck controller doesn't work anymore
on Electron above version 26

Kind rageds
