### ISSUE TITLE
window.open() opens all windows on macos only.

### ISSUE THREAD

**Issue by Foraminiferatrv** [electron/electron#43335]
I have an electron app which can open a child window when in main window I receive a call. When this window is shown and main window is minimized, only the child window must be shown. It works exactly like that on Windows but on macos the app opens all the windows. Why this might be happening? Has someone else had this issue?

Thank you.

**electron: v31.4.0**

Unfortunately, I can't share much code. Here how I open a child window 
** renderer.tsx**
```const externalWindow = window.open("", "IncomingWindow"); //Portal window```

main.ts

```mainWindow.webContents.setWindowOpenHandler(({ frameName }) => {
    if (frameName === "IncomingWindow") {
      return {
        action: "allow",

        overrideBrowserWindowOptions: {
          parent: mainWindow,
          width: 700,
          height: 115,
          y: 40,
          x: getScreenCenter() - 230,
          center: true,
          alwaysOnTop: true,
          title: "call-window",
          resizable: false,
          minimizable: false,
          paintWhenInitiallyHidden: true,
          show: true,
          maximizable: false,
          frame: false,
          
          
          autoHideMenuBar: true,
          skipTaskbar: true,
          transparent: true,
          hasShadow: true,
        },
      };
    } else {
      return { action: "deny" };
    }
  });```
  
  I tried multiple configurations for the child window but the behaviour hasn't changed. I also checked if anything else might be calling window.show() but found nothing as well.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by absidue** [comment]
It sounds like it is just differences in how the operating systems handle child windows. To get the behavior that you want, you can remove the `parent: mainWindow` line in your code, that way it will no longer be a child window.

**Comment by Foraminiferatrv** [comment]
@absidue Thank you. It did resolve my issue!

**Comment by golimix** [comment]
I need to set the parent window, but when show the child window, it shows all the windows
