### ISSUE TITLE
[Bug]: screen.getPrimaryDisplay().id is different for different Electron versions (30.4.0 and 31.4.0)

### ISSUE THREAD

**Issue by MaksimDedov** [electron/electron#43355]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.4.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

30.4.0

### Expected Behavior

The `screen.getPrimaryDisplay().id` should return the same value for the same monitor in different Electron versions. 

### Actual Behavior

When I run the code below for the v30.4.0 and 31.4.0 I get different results:
for 30.4.0: `###primary 2528732444`
for 31.4.0: `###primary 462932844`
In my case the electron v30.4.0 has correct value.
```
app.whenReady().then(() => {
  const display = screen.getPrimaryDisplay();
  console.log("###primary", display.id);
})
```

### Additional Information

The closed bug in the same area #42747
 

https://github.com/user-attachments/assets/6c3454d1-765d-4602-bb41-9cf40c084651

**Comment by ckerr** [comment]
This isn't an Electron bug. The difference in ID is coming from an upstream Chromium change https://chromium-review.googlesource.com/c/chromium/src/+/5362362 which sounds like it will make IDs more stable going forward:

> Changes the way chromium display IDs are derived from monitor information on Windows. The display ID is now derived from the adapter and adapter ID for a given monitor.
>
> This stabilizes IDs during monitor connection and disconnection. Specifically, when disconnecting a monitor, the display ID of other monitors won't change.

**Comment by cheynewallace** [comment]
We are also experiencing this same bug which has broken a number of our customers screen displays although I feel there is something else at play here. 

That Chromium ticket says it will make monitor IDs more stable, basing its iD on the adapter now however what we are seeing is that this ID will change every time someone reboots their machine.   

It is the opposite of stable now, now we are losing display configurations every time someone reboots their PC instead of just changing cables.

This PR looks related: https://github.com/electron/electron/pull/42883
