### ISSUE TITLE
[Bug]: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by linglongmi** [electron/electron#43351]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Ventura 13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Correctly exposing the node API of the main process to the rendering process through preloading scripts, so that the rendering process can use it normally

### Actual Behavior

When I was adding a preload script, I attempted to expose some node APIs of the main process to the rendering process through preload. I enabled nodeIntegration: true, and the console displayed: global is not defined in the rendering process; To solve this problem, I set contextIsolation (default to true) to false, which solves the previous issue. But the console error told me that when using contextBridge, contextIsolation must be true for preloading scripts

**Comment by linglongmi** [comment]
But even after updating the electron version to v31.4.0, this issue still persists

**Comment by linglongmi** [comment]
electron+react

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
