### ISSUE TITLE
[Feature Request]: Serving https on BrowserWindow

### ISSUE THREAD

**Issue by cgarrovillo** [electron/electron#43447]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.3.1

### What arch are you using?

x64

### Expected Behavior

I would like to be able to serve my renderer sites through https so that JS libraries that require a site to load via https (stripe.js production, authorize.net acceptjs) can load properly.

### Actual Behavior

No documentation about this, with seemingly unresolved discussions surrounding it. There are only 2 notable threads for this:
- https://github.com/electron/electron/issues/24573
- https://github.com/electron/electron/issues/21525

I'm currently exploring the expressjs server approach, where I create an express server that serves my html files instead of a direct `loadUrl("file://...");`. However there's the problem of having a self-signed certificate not be acceptable by the renderer process as it is self-signed. Having a valid certificate requires a Certificate Authority, which doesnt issue certificates for localhost and essentially requires a public domain, at which point it is now a rabbit hole to get a site only local to a client to be available on https.

There is also the `("ignore-certificate-errors"` switch to append and this currently works but I'm wondering if there are alternatives to this approach.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
