### ISSUE TITLE
[Feature Request]: Adhere to the system font by default.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [electron/electron#43526]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As the undermentioned demonstrate:

1.	[this Reddit post](https://www.reddit.com/r/linuxquestions/comments/mu3lk2/comment/gv3gbfv/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button#:~:text=I%20use%20%22DejaVu,desktop%20font%20choices.) states:

	> I use "DejaVu Sans" with antialised turned off and it's absolutely perfect.
	> 
	> But all electron apps I use(d), such as Slack, Signal etc all use a different font with lots of horrible hinting effects because it's not a font designed for disabled anti-aliasing. So where do I change the font they use? They don't respect my desktop font choices.

1.	[this Reddit post](https://www.reddit.com/r/linuxquestions/comments/7dznaf/comment/dq1md5y/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button#:~:text=Maybe%20this%20is,except%20electron%20ones.) states:

	> Maybe this is an electron question more than linux question, but I hope somebody here knows a solution.
	> 
	> Electron apps (slack, remember the milk, etc) don't use my system font configuration. I use gnome 3.26 on fedora 27, I changed the system font from Tweak but electron apps still use another one.
	> 
	> I also create a `conf` file in `~/.config/fontconfig` to determine the default font for Arabic locale. All gnome apps respected this configuration except electron ones.

...there is desire for Electron (like every other application) to adhere to the system font preferences.

I needn't explain why - for anyone with dyslexia, this is a significant accessibility nightmare.

### Proposed Solution

By default, adhere to the system's font. On Windows, [this SU answer](https://superuser.com/revisions/1849000/2#:~:text=is%20very%20wrong.-,If%20\(\(Test%2DPath%20%2DLiteralPath,%2DForce%20%2DEA%20'SilentlyContinue';,-%7D) explain what needs to be read, whereas on GNU-based OSes, you can merely poll `fontconfig`.

As an example, I have my system font set to the font alias `monospace`. When an Electron-based application is installed, it should read the `fontconfig` value for the system-applied font, set that value as its fonts (for Gecko, these would be the `font\.name\..*\.x-western` RegEx-matching values) and then listen to a DBus command to change the font if ever it is changed, so that the change in Electron is instantaneous too.

### Alternatives Considered

The current sole alternative is to customise this by applying flags in the invocation file (`.desktop` or `.lnk`) or requesting that the application creator provide a GUI for it. Neither scale well, although the former is at least dynamically adaptive enough to be usable with a font alias set.

### Additional Information

https://github.com/electron/electron/issues/15242#issue-371407445 appears to depend upon this.

**Comment by absidue** [comment]
Even if Electron set that as a default, for most existing apps nothing would change, as the content in Electron apps are websites after all and most websites specify what fonts should be used to display the website correctly. Your best bet is to approach the developers of the apps that you are using, they might not go for supporting the default system font as that could be literally anything but you might be able to convince them to add an option to pick from a few select fonts. That way you can change the font and they don't have to worry about they layout breaking with fonts that they haven't been able to test.

**Comment by MarshallOfSound** [comment]
As noted above, doing something like this (forcing fonts) would violate web standards and probably break most apps (icon fonts are a thing). If you want system fonts for app X, contact them 🤷 Electron has to remain unopinionated in things like this.

For any app developers stumbling on this I _think_ the CSS incantation is:

```
font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu;
```

but do your own research 😄

**Comment by beedell-roke** [comment]
> As noted above, doing something like this (forcing fonts) would violate web standards and probably break most apps (icon fonts are a thing).

@MarshallOfSound, you've somewhat misunderstood the request. It's as @absidue describes - I merely want the *defaults* to be the system font. I'm not requesting that the Chromium instance override any stylesheets applied by the developers.

Specifically, your undermentioned example:

> ```YAML
> font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu;
> ```

...is what I consider erroneous. Instead of hardcoding these typefaces, they should be set according to the OS/DE's preferences.

As an example, I can enter `kcm_fonts` and set my system fonts to a dyslexia-supportive font, which shall effect all Qt and GTK applications (the latter via the `gtkrc`) yet Electron remains using whatever the developer thought was most pretty. Surely this is unacceptable?

Overriding what the stylesheets set is another matter, and can probably be achieved during invocation (in the `.desktop` or `lnk` file) for those dedicated enough to. And in those cases, asking the development team to be able to set the font is probably the sole viable option.

**Comment by beedell-roke** [comment]
> https://github.com/electron/electron/issues/43526#issuecomment-2327213415

@absidue, many thanks. Apologies for my ignorance. ~~Would it not make a little more sense to set the standard font aliases as the fallbacks, though? This is merely a question - I expect it's been considered.~~

**Comment by beedell-roke** [comment]
> https://github.com/electron/electron/issues/43526#issuecomment-2327213415

@absidue, I've bothered to do at least a minimum research and try developing with Electron since I requested this, in order to report https://github.com/electron/electron/issues/47949#issue-3287429133. Using an nigh unmodified Electron Fiddle template as a base, I've added `<style>* { font-family: system-ui }</style>`, yet don't see it adhere to Segoe UI on Windows 11:

<p><img width="541" height="162" alt="Image" src="https://github.com/user-attachments/assets/133e3eee-5d2d-46c3-b115-e55edd5114da" /></p>

I've tried setting it to `p`, `:root`, and `body`, and even run the file in a full (Chromium-based) browser, in order to verify:

<p><img width="1280" height="696" alt="Image" src="https://github.com/user-attachments/assets/6e278128-8d60-4367-8d7e-523fdaaf3961" /></p>

Considering that it reproduces there, is `system-ui` actually set anywhere? If not, I suppose it's an upstream bug. However, I feel I must be doing something wrong. I realise that this isn't the avenue for code assistance, but I can't see how what I'm doing is correct, so I'd like to ensure this isn't a bug.
