### ISSUE TITLE
Mods Not Showing In Manager

### ISSUE THREAD

**Issue by TheMCV3teran** [electron/electron#43616]
I have 2 mods in the server's mods folder, but when i look in the "mods" tab in the manager, it shows "total: 0" on both activated and deactived
![screenshot1](https://github.com/user-attachments/assets/eb0492eb-2791-474a-a900-671bfce3bd2e)
![screenshot2](https://github.com/user-attachments/assets/082955f4-bd3b-40ca-93dc-513425101284)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
