### ISSUE TITLE
[Bug]: uft-8 not supported

### ISSUE THREAD

**Issue by xiexiaopeng2016** [electron/electron#43628]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

WSL2 Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

display UTF-8 characters

### Actual Behavior

![image](https://github.com/user-attachments/assets/5eb8effd-c45d-42a1-9ad2-4b432d624121)
The content of the page and the original interface of the browser cannot display UTF-8 characters, how to solve this problem?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
