### ISSUE TITLE
Request: disable node-integration by default

### ISSUE THREAD

**Issue by aakilfernandes** [electron/electron#4362]
node-integration creates a global `module` object on the page. For better or worse, lots of node modules use the existence of a `module` object to indicate they are in a node environment (as opposed to a browser environment).

I think disabling by default is the safer way to go and will save devs a lot of headaches

**Comment by paulcbetts** [comment]
node integration is like the whole point of Electron

**Comment by felixrieseberg** [comment]
Yeah, if you don't want Node... just use Chromium? Or better yet, CEF?

**Comment by kevinsawicki** [comment]
Yeah, there are many frameworks for building cross-platform desktop apps that don't include node integration that should be used as alternatives if you don't want node integration in your app.

Node integration is a cornerstone of Electron and will stay enabled by default.

Closing this out as a `wontfix`.

**Comment by ckerr** [comment]
I'm reopening this topic for consideration for 3.0 because it came up again in our Slack #security channel, citing [a comment](https://electronhq.slack.com/archives/C3ANJ97H6/p1492539687035711) from @kevinsawicki:

> I think we should do this kind of thing in 2.0.

My own vote is 'no' for the reasons above -- Node integration is one of Electron's main features -- but I'd like to hear from the other maintainers.

Also it's not clear to me if @kevinsawicki was saying "we should make this change in 2.0", as was suggested in Slack, or if he was saying "breaking changes like this should be made in 2.0", which seems more in line with his comments in this issue.

**Comment by kevinsawicki** [comment]
> Also it's not clear to me if @kevinsawicki was saying "we should make this change in 2.0", as was suggested in Slack, or if he was saying "breaking changes like this should be made in 2.0", which seems more in line with his comments in this issue.

Yeah, I can't recall exactly what I meant at that time, but looking back at the initial report:

> node-integration creates a global module object on the page. For better or worse, lots of node modules use the existence of a module object to indicate they are in a node environment (as opposed to a browser environment).

I'm not sure how accurate this statement is these days compared to 2 years ago when this was originally reported. If this is still a headache for people, then revisiting what can be done to reduce this friction seems worthwhile. There could be other solutions out there to address this besides completely disabling node integration.

**Comment by poiru** [comment]
@ckerr It's extremely easy to load untrusted remote URLs with Node integration with something like:

```js
const win = new BrowserWindow()
win.loadURL('https://www.github.com')
```

To be safe, you have to write:

```js
const win = new BrowserWindow({
  webPreferences: {
    nodeIntegration: false,
  }
})
win.loadURL('https://www.github.com')
```

I think the shortest/simplest code should be safe by default. If you explicitly opt-in to Node integration, sure, we can't protect from that. But I'll argue that most new Electron users will not even be aware of what they're exposing themselves to with the first example. I have made this mistake myself many times because it is so easy to forget.

**Comment by VishwasShashidhar** [comment]
Agreed with @poiru that by default, it'll be better to turn off node integration and go with an opt-in model.

**Comment by jookyboi** [comment]
Thanks so much for doing this. We just found an issue in our app where a potential XSS attack could've done serious harm due to `nodeIntegration` being on by default.

**Comment by codebytere** [comment]
This is done in v5.0.0.
