### ISSUE TITLE
[Bug]: EXC_BAD_ACCESS / KERN_PROTECTION_FAILURE

### ISSUE THREAD

**Issue by menglingyu659** [electron/electron#43666]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.27

### What operating system(s) are you using?

macOS

### Operating System Version

mac os x 13.3.1 

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.27

### Expected Behavior

正常运行

### Actual Behavior

发生崩溃
[7a4fd17e-3e1e-41a4-93fc-b0f03cd41497.dmp_electron-v22.3.27-darwin-arm64-symbols.txt](https://github.com/user-attachments/files/16944641/7a4fd17e-3e1e-41a4-93fc-b0f03cd41497.dmp_electron-v22.3.27-darwin-arm64-symbols.txt)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
