### ISSUE TITLE
How to re-render while resizing with animation?

### ISSUE THREAD

**Issue by wearhere** [electron/electron#4368]
The relatively-new `animate` parameter to [`BrowserWindow#setSize`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetsizewidth-height-animate) is awesome, but It seems that Chromium waits to re-render until resizing is complete which kind of defeats the purpose of providing a smooth transition.

[Video](http://cl.ly/0P0M1E423m38)

Is there a way to force Chromium to re-render while resizing? Or how do you otherwise expect developers to use animated resizing?

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/atom/brightray/issues/196.

**Comment by davej** [comment]
I think this should be re-opened here because #196 is a separate issue and this bug seems to be related to Electron rather than Brightray. Repaint works fine while resizing, it just doesn't work with animated `win.setSize`.

Tested on 0.37.7 with devtools closed. Here's a video showing both `win.setSize` (not repainting) and manual resize (repainting OK): https://www.youtube.com/watch?v=y3hVFIaIEyE

**Comment by davej** [comment]
@zcbenz Pinging you to consider reopening this.

**Comment by davej** [comment]
Retested. Still occurring in `v1.2.6`.

**Comment by codebytere** [comment]
closing due to abandonment.
