### ISSUE TITLE
Chromium in Electron is forcing a http api call to https which isn't supported by the server

### ISSUE THREAD

**Issue by KoningWouter** [electron/electron#43692]
Hello. 

I was using an old version of Electron which didn't have this "feature". But after upgrading to the latest version of Electron some api calls are not working anymore.

The problem is the following.

I make a request to an HTTP api. It is not my server and the server doesn't support HTTPS. One way or the other Chromium thinks this call should be redirected to HTTPS and forces the api call to redirect to HTTPS. This is not available on the server so it gives an error.

Is there a way to disable this redirect? Because half of my application isn't working anymore. 

There is no way I can make the server to accept HTTPS. 

Thanks in advance

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
