### ISSUE TITLE
[Bug]: Activation from tray doesn't work if the window is minimized (Wayland)

### ISSUE THREAD

**Issue by ninja-** [electron/electron#43709]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

Other Linux

### Operating System Version

Fedora 40 KDE Wayland

### What arch are you using?

x64

### Expected Behavior

Clicking tray icon brings the app window to the front in both cases:
- the window is minimized
- the window was closed and is bring recreated

### Actual Behavior

When the window doesn't exist, activating via tray icon works (by pure luck of KWin being permissive or by proper implementation?)
When the window is minimized, activation doesn't work

### Additional Information

Compare it to Telegram, which AFAIK doesn't use custom Tray code just what Qt6 offers.  
It will activiate the app in both cases.  
I think KStatusNotifier DBUS has an interface to request an activation token for xdg-activation but I am struggling to find the relevant docs/code at this time  
(since plasmashell is a focused window when you interact with the tray icon, it fully makes sense for it to be able to generate an activation token when requested by DBus, even without using privileged interfaces to do so)

**Comment by ninja-** [comment]
see how telegram does it

```

method call time=1726564419.945667 sender=:1.586 -> destination=:1.651 serial=926 path=/StatusNotifierItem; interface=org.kde.StatusNotifierItem; member=ProvideXdgActivationToken
   string "kwin-27"
method call time=1726564419.945709 sender=:1.586 -> destination=:1.651 serial=927 path=/StatusNotifierItem; interface=org.kde.StatusNotifierItem; member=Activate
   int32 1546
   int32 1059
```

**Comment by ninja-** [comment]
I don't think I can provide a custom fiddle-based repro over next few days, this issue is however still relevant.

I also noticed that with some of the last updates, Discord and Teams for Linux, started requesting xdg activation tokens after clicking on tray icon, creating an effect where the token isn't granted but the application is (which was not seen before) marked as wanting attention on KDE taskbar.

It's weird because I am pretty sure that didn't happen before, and I am not able to trace it to any recent Electron commit.

But still, this is not the correct behavior because the token should be requested via  org.kde.StatusNotifierItem.ProvideXdgActivationToken to be successful

**Comment by taoky** [comment]
This issue is reproducible on both GNOME & KDE wayland session: when the window is minimized, or shown but not focused, the `show` and `focus` do not work.

MRE: <https://gist.github.com/taoky/309903d4b61f0c52b7535ba11254c3ac>.

`WAYLAND_DEBUG=1`:

```
[ 929957.860]  -> xdg_activation_v1#28.get_activation_token(new id xdg_activation_token_v1#50)
[ 929957.910]  -> xdg_activation_token_v1#50.commit()
[ 929961.510] xdg_activation_token_v1#50.done("26093f9e-7d39-4dc5-a77c-e1012bb31d54_TIME0")
[ 929961.557]  -> xdg_activation_v1#28.activate("26093f9e-7d39-4dc5-a77c-e1012bb31d54_TIME0", wl_surface#23)
[ 929961.570]  -> xdg_activation_token_v1#50.destroy()
```

Looks like the compositor would reject the activation request (as it's not focused?)

Some other apps, like Telegram Desktop, could successfully handle the tray activation with (tested on GNOME):

```
[2716301.642]  -> xdg_activation_v1@27.activate("gnome-shell/TelegramDesktop/487678-605-hostname_TIME354091465", wl_surface@53)
```

It probably uses [`ProvideXdgActivationToken()`](https://invent.kde.org/frameworks/kstatusnotifieritem/-/blob/master/src/org.kde.StatusNotifierItem.xml?ref_type=heads#L52-54) method in `org.kde.StatusNotifierItem` to get acknowledged token from compositor.

However, Chromium does not use this in its implementation ([chrome/browser/ui/views/status_icons/status_icon_linux_dbus.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/status_icons/status_icon_linux_dbus.cc?q=StatusNotifierWatcher&ss=chromium)).

(Correct me if I'm wrong...)
