### ISSUE TITLE
[Bug]: can not load QR code when visit https://channels.weixin.qq.com/

### ISSUE THREAD

**Issue by fisker0303** [electron/electron#43718]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS 14.6.1 (23G93)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

32.0.0

### Expected Behavior

visit https://channels.weixin.qq.com/ using normal web browser, the QR code is shown
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/b2dbdda7-2ce1-4eb1-ab44-25d988127ea9">

### Actual Behavior

visit https://channels.weixin.qq.com/ using electron webview, the QR code is always loading
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/ce138b53-a3af-448b-8c97-2771eb75878d">

### Testcase Gist URL

https://channels.weixin.qq.com/

### Additional Information

https://channels.weixin.qq.com/

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
