### ISSUE TITLE
[Bug]: Can't get the electron application window when using app.exe

### ISSUE THREAD

**Issue by sophieminasyan** [electron/electron#43881]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.4

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 v.1809

### What arch are you using?

x64

### Expected Behavior

Using main.js
const electronApp = await electron.launch({ args: ['main.js'] });
const window = await electronApp.firstWindow();
The above code can start electron app normally and the window can return back normal.

Using app.exe
const electronApp = await electron.launch({ executablePath: ’app.exe‘ });
const winCount=electronApp.windows().length; (This returns 0)
const window = await electronApp.firstWindow(); (This returns undefined)
The above code can start electron app normally, but can't get the window, and the windows().length is 0.

### Actual Behavior

So I'm a little confused why can't get the window with app.exe？

Its already packaged electronApp I build it using electron-builder. Can there be some security points?(I cant get windows(pages) and content from there)

**Comment by sophieminasyan** [comment]
I have updated my electron version to 28.2.8. This issue still available in this version too. Do you support this version of electron?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
