### ISSUE TITLE
Electron Internal Design & Architecture Docs ?

### ISSUE THREAD

**Issue by charancraj** [electron/electron#43939]
I'm interested in understanding the internal design and architecture of the Electron framework, particularly how Electron leverages the Chromium Content Module and integrates with Node.js, as well as the entire startup sequence.

I’ve searched for resources but haven’t found much detailed information. I did come across some related blog posts, such as:

[Electron Internals: Node Integration](https://www.electronjs.org/blog/electron-internals-node-integration)
[Electron Internals: Building Chromium as a Library](https://www.electronjs.org/blog/electron-internals-building-chromium-as-a-library)

and the [Electron Contributing Docs](https://www.electronjs.org/docs/latest/development/build-instructions-gn)

However, they don’t go into much depth on the topics I’m interested in.

Could you please share any relevant documentation that goes into more detail on these aspects? I’m looking for resources that core Electron contributors might use to understand the framework's workings.

Apologies if this doesn't fall into the "Issue" bracket. I really didn't find any other avenues to ask this question. ( I see that there is discord channel where i will try to post this question )

thanks,

**Comment by MarshallOfSound** [comment]
Hey @charancraj,

The three you found are good sources to read, a while ago we did note some high level things down in this onboarding-guide repo --> https://github.com/electron/onboarding-guide but haven't really kept it up to date or gone into too much depth.

In general, as you'll note by reading that onboarding guide repo, we tend to direct new folks to the relevant codebase documentation of node and Chromium rather than redocumenting things on our side.

If you're specifically looking for the integration of node/v8/chromium content beyond what you've linked above the best place to start is honestly just staring at the code --> https://github.com/electron/electron/blob/main/shell/common/node_bindings.cc
