### ISSUE TITLE
[Feature Request]: [Bug]: In electron, when using webview to embed a third-party website, how can we specify the file path that opens when clicking on the file upload button inside?在electron中，使用webview嵌入第三方网站的时候，点击里面的文件上传按钮时候，如何指定打开的文件路径呢

### ISSUE THREAD

**Issue by 1937650094** [electron/electron#43970]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

[Bug]: In electron, when using webview to embed a third-party website, how can we specify the file path that opens when clicking on the file upload button inside?在electron中，使用webview嵌入第三方网站的时候，点击里面的文件上传按钮时候，如何指定打开的文件路径呢

### Proposed Solution

[Bug]: In electron, when using webview to embed a third-party website, how can we specify the file path that opens when clicking on the file upload button inside?在electron中，使用webview嵌入第三方网站的时候，点击里面的文件上传按钮时候，如何指定打开的文件路径呢

### Alternatives Considered

[Bug]: In electron, when using webview to embed a third-party website, how can we specify the file path that opens when clicking on the file upload button inside?在electron中，使用webview嵌入第三方网站的时候，点击里面的文件上传按钮时候，如何指定打开的文件路径呢

### Additional Information

[Bug]: In electron, when using webview to embed a third-party website, how can we specify the file path that opens when clicking on the file upload button inside?在electron中，使用webview嵌入第三方网站的时候，点击里面的文件上传按钮时候，如何指定打开的文件路径呢

**Comment by 1937650094** [comment]
也就是设置一个默认的文件上传的路径

**Comment by leon9508** [comment]
you can set  preload for webview，and then interceptor the click event in preload

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by 1937650094** [comment]
但是怎样将主进程选择文件赋值webview里面的网页里面html的input标签呢
