### ISSUE TITLE
[Bug]: The electron program can run normally with npm start in vscode, but after using electron-builder to package and run my packaged exe file, part of the win10 computer will have a white screen

### ISSUE THREAD

**Issue by Heyh520** [electron/electron#43974]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows10 21H1 19043.1110

### What arch are you using?

x64

### Last Known Working Electron version

32.0.0

### Expected Behavior

The program is normal on win7,But it's not normal in the part win10,Theoretically it's normal,I found that in part of the win10 19043.1110 version of the white screen,Some of them can be

### Actual Behavior

My electron program can run normally with npm start in vscode, but after using electron-builder to package and run my packaged exe file, some win10 computers will have a white screen, and some of them are normal

**Comment by Heyh520** [comment]
Also appears in 32.0.0

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
