### ISSUE TITLE
[Bug]: Compile error

### ISSUE THREAD

**Issue by KotoWolod** [electron/electron#43976]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.1.2

### What operating system(s) are you using?

macOS

### Operating System Version

macOS sequoia

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When I'm using https://www.npmjs.com/package/swisseph-v2 with electron I'm getting the error. I tried reinstall and rebuild and change a node version, but nothing helps. To reproduce you have to just import that package:

`import swisseph from 'swisseph-v2';`

### Actual Behavior

node_modules/swisseph-v2/build/Release/swisseph.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 127. This version of Node.js requires
NODE_MODULE_VERSION 125. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

### Additional Information

Nothing to add.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
