### ISSUE TITLE
[Bug]: Why was my databases folder deleted on electron32

### ISSUE THREAD

**Issue by chenxi621** [electron/electron#43994]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.2

### What operating system(s) are you using?

Windows, macOS

### Operating System Version

windows10，macos 15

### What arch are you using?

ia32

### Last Known Working Electron version

31.2.0

### Expected Behavior

I don't want Electron to automatically delete my databases folder when the app starts

### Actual Behavior

When I launched the app, my 'databases' folder was deleted

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
