### ISSUE TITLE
customSession.setProxy({   mode: "fixed_servers",     proxyRules: "http=username:password@X.X.X.X:1000"})

### ISSUE THREAD

**Issue by adminmvne** [electron/electron#44120]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I hope to add an authentication method when setting up a proxy for the session, as some proxy IPs require an account and password for use.

### Proposed Solution

I hope to add an authentication method when setting up a proxy for the session, as some proxy IPs require an account and password for use.

### Alternatives Considered

I hope to add an authentication method when setting up a proxy for the session, as some proxy IPs require an account and password for use.

**Comment by absunstar** [comment]
i report same bugs https://github.com/electron/electron/issues/43284
But No Real Action Taken
it's abig problem Proxy Not Worked On All Sites

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
