### ISSUE TITLE
[Bug]: Chromium trace fails on macOS

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#44151]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v32.0.0-alpha.6

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.7 (23H124)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

v32.0.0-alpha.5

### Expected Behavior

Chromium trace is recorded and written to target file after exiting Electron.

### Actual Behavior

Chromium trace fails to be produced.

Console repeatedly logs the following lines:
```
[1008/120824.656792:ERROR:mach_port_rendezvous.cc(385)] bootstrap_look_up org.chromium.Chromium.MachPortRendezvousServer.5976: Permission denied (1100)
[1008/120824.657010:ERROR:shared_memory_switch.cc(237)] No rendezvous client, terminating process (parent died?)
```

### Additional Information

```
./Electron.app/Contents/MacOS/Electron --trace-startup="*" --trace-startup-file="$HOME/Desktop/trace.json"
```

It'd probably be a good idea for us to write a test to ensure traces are written on each platform. Can add `--trace-startup-duration=1` to limit the size during tests.

**Comment by codebytere** [comment]
@samuelmaddock were you able to confirm it works on other platforms?

**Comment by deepak1556** [comment]
This is a regression from https://chromium-review.googlesource.com/c/chromium/src/+/5581006

The new option `kTraceConfigHandle` passes the config via shared memory region that gets set as the mach port when launching child processes. `base::shared_memory::Serialize` registers the server port and passes the serialized value via the new switch. In the child process, `base::shared_memory::Deserialize` does the opposite to extract the client port. The crash happens because of two unrelated reasons,

1) there is no registered server port when launching the utility process via its host launch path
2) Trace switches are not copied from browser process into utility process in https://source.chromium.org/chromium/chromium/src/+/main:content/browser/utility_process_host.cc;l=313-381; which leads to incorrect choice in https://source.chromium.org/chromium/chromium/src/+/main:services/tracing/public/cpp/trace_startup_config.cc;l=119-121 that attempts to read from shm handle even with `--trace-startup`

We can fix this in Electron via the following change,

```patch
diff --git a/shell/browser/electron_browser_client.cc b/shell/browser/electron_browser_client.cc
index f56fc8ac10..16a94c76a1 100644
--- a/shell/browser/electron_browser_client.cc
+++ b/shell/browser/electron_browser_client.cc
@@ -30,6 +30,7 @@
 #include "components/embedder_support/user_agent_utils.h"
 #include "components/net_log/chrome_net_log.h"
 #include "components/network_hints/common/network_hints.mojom.h"
+#include "components/tracing/common/tracing_switches.h"
 #include "content/browser/keyboard_lock/keyboard_lock_service_impl.h"  // nogncheck
 #include "content/public/browser/browser_main_runner.h"
 #include "content/public/browser/browser_task_traits.h"
@@ -546,6 +547,14 @@ void ElectronBrowserClient::AppendExtraCommandLineSwitches(
     }
   }
 
+  if (!process_type.empty()) {
+    static const char* const kTraceSwitchNames[] = {
+        ::switches::kTraceStartup,
+        ::switches::kTraceConfigHandle};
+    command_line->CopySwitchesFrom(*base::CommandLine::ForCurrentProcess(),
+                                   kTraceSwitchNames);
+  }
+
   if (process_type == ::switches::kRendererProcess) {
 #if BUILDFLAG(IS_WIN)
     // Append --app-user-model-id.
```

However the issue also exists in upstream, proper copying of trace switches should happen in the `//content` layer that handles the process launching via different hosts, (utility, gpu, renderer etc)

**Comment by samuelmaddock** [comment]
> [@samuelmaddock](https://github.com/samuelmaddock) were you able to confirm it works on other platforms?

I can confirm tracing still works on Windows.

**Comment by eti-p-doray** [comment]
Are you able to reproduce upstream? Following the steps from the original description, I'm able to get a startup trace with data from child processes.
We shouldn't have to copy command line arguments from the browser process. Instead, relevant arguments are already added in ChildProcessLauncherHelper::LaunchOnLauncherThread by calling PassStartupTracingConfigSharedMemoryHandle()

https://source.chromium.org/chromium/chromium/src/+/main:content/browser/child_process_launcher_helper.cc;l=322?q=PassStartupTracingConfigSharedMemoryHandle&ss=chromium

Possibly, your issue is related to OverrideBundleID() which needs to happen early in process creation.
https://chromium-review.googlesource.com/c/chromium/src/+/5581006/60/content/shell/app/shell_content_main.cc

**Comment by deepak1556** [comment]
You are right moving the bundle overrides earlier does fix the crash.  


Sorry, my misunderstanding was from the following comment https://source.chromium.org/chromium/chromium/src/+/main:components/tracing/common/tracing_switches.cc;l=48-51. I thought config handle shouldn't be used when `trace-startup` is provided but saw the flag `trace-config-handle` was always being passed into the child process via the launcher and `TraceStartupConfig::EnableFromConfigHandle` was used in the child process. But now that I read back on the CL this is meant to be the case.
