### ISSUE TITLE
[Bug]: Pi camera is not detected from electron version 12 onwards

### ISSUE THREAD

**Issue by Amit-Pareek-VTS** [electron/electron#44176]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

Other (specify below)

### Operating System Version

Raspbian GNU/Linux 10 (buster)

### What arch are you using?

x64

### Last Known Working Electron version

11

### Expected Behavior

Pi camera is not getting detected from electron version 12. 

device : Raspberry Pi 4 - 8GB RAMModel B (2018)
my node version ^14.21, npm ^7.15.
Getting error DOMException: Requested device not found (From electron version 12 onwards)

Code : const stream = await navigator.mediaDevices.getUserMedia(constraints);

### Actual Behavior

Code : const stream = await navigator.mediaDevices.getUserMedia(constraints);

Pi camera should get detected from the above code

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
