### ISSUE TITLE
Node.js is adding more features that Chromium have, is this cause redundancy?

### ISSUE THREAD

**Issue by kkocdko** [electron/electron#44184]
As we know Node.js added [sqlite](https://nodejs.org/api/sqlite.html), and want to add [fetch cache](https://github.com/nodejs/undici/pull/3562) in the future.

These will not be the end, Deno added WebGPU, more and more things from browser and other project will be added into Node.js . Will this cause redundancy? Is this the waste of time, memory and storage?

Or, is it better to just add Chromium's network stack instead of undici into Node.js?

And, I wish the sqlite machinecode can be shared between Node.js(after Electron adopt Node.js 22+) and Chromium. Just a wish.

**Comment by TNO-C137** [comment]
Just like V8 ? shared with nodejs and chromium?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
