### ISSUE TITLE
[Feature Request]: Read and set the file path to the system clipboard directly

### ISSUE THREAD

**Issue by 1234567845246** [electron/electron#44221]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to be able to read and set the file path to the system clipboard directly. Although I can now rely on native modules to manipulate the operating system API directly, I can even add clipboard change events if I can.

### Proposed Solution

Currently in the Windows by AddClipboardFormatListener listening in. As for access to the file path win32API write very clear [,](https://learn.microsoft.com/zh-cn/windows/win32/dataxchg/clipboard) but I feel should because Google browser Clipboard does not implement I hope you didn't achieve it

### Alternatives Considered

none

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
