### ISSUE TITLE
Ak1


 { BrowserWindow, webContents } = require('electron');

// ...

const webviewWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    nodeIntegration: false,
    webviewTag: true
  }
});

webviewloadURL('https://example.com');


### ISSUE THREAD

**Issue by NameNoQuality** [electron/electron#44241]

**Comment by NameNoQuality** [comment]
> 

A portfolio is a set of pictures by someone, photographs of their work, or examples of their writing, which they use when entering competitions or applying for work.
After dinner that evening, Edith showed them a portfolio of her own political cartoons.
In finance, a portfolio is the combination of investments that a particular person or company owns.
...Roger Early, a portfolio manager at Federated Investors Corp.
In politics, a portfolio is a high-ranking official's responsibility for a particular area of a government's activities.
He has held the defense portfolio since the first free elections in 1990.
A company's portfolio of products or designs is their range of products or designs.
The company has continued to invest heavily in a strong portfolio of products.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
