### ISSUE TITLE
Electron unsupported on OS issue

### ISSUE THREAD

**Issue by vikhyat11** [electron/electron#44262]
Hi team,

I am trying to upgrade electron from a very old version(2.0.9) to the latest version. After upgrading all the dependencies and also upgrading node and node.js followed by fixing build errors I am getting the following error.
![Image](https://github.com/user-attachments/assets/825f3f1e-6570-453a-80e6-9076dccfb6eb)

The issue is that it is saying that the bit version is not supported even though I used the 64 bit zip file of electron.
Can you please help with the issue?

Thanks

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
