### ISSUE TITLE
Can't run when there is no NULL service on Windows 10/11(v31.6.0 exists too) #55416

### ISSUE THREAD

**Issue by leehark** [electron/electron#44294]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.6.0

### What operating system(s) are you using?

Windows

### Operating System Version

Window 10/11

### What arch are you using?

x64

### Expected Behavior

Normal start Electron Demo

### Actual Behavior

- Stop the NULL Service on Windows(Or Remove the NULL Service)
- Run Electron Demo (electron 31.6.0)
- Can't run with some error

### Additional Information

https://github.com/nodejs/node/blob/e2242b4e256082e01d8df6a4155ddc80e146c123/src/node.cc#L643C45-L643C47
it stops working in this line above.

We found there is **a lot of users** have not NULL service.

**Comment by leehark** [comment]
this bug is still in latest version , for example v31.6.0.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
