### ISSUE TITLE
Location of System Messages and Labels in Electron

### ISSUE THREAD

**Issue by AvremiB** [electron/electron#44330]
Hello,

I find a locales folder in the files of the Electron application on my computer. I'm trying to figure out where its source is on GitHub.

Could you please guide me to the exact location of these files? Is there any documentation or additional explanation regarding their usage?

Thank you in advance for your help!

PS Sorry for asking this here instead of Discord. I know this is not the right place, but I don't get along with Discord. Hoping for understanding.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
