### ISSUE TITLE
ERROR at //chrome/browser/pdf/BUILD.gn:9:1: Assertion failed.

### ISSUE THREAD

**Issue by killghost** [electron/electron#44359]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.2.1

### What operating system(s) are you using?

Windows

### Operating System Version

Win10

### What arch are you using?

x64

### Expected Behavior

Build Electron From Source Code

gn gen out\Debug --args="import(\"//electron/build/args/release.gn\") target_cpu=\"x64\"" --ide=vs2022

ERROR at //chrome/browser/pdf/BUILD.gn:9:1: Assertion failed.
 assert(enable_pdf)
 ^-----
 See //chrome/browser/ui/lens/BUILD.gn:210:5: which caused the file to be included.
 "//chrome/browser/pdf",
 ^---------------------

### Actual Behavior

Build Electron From Source Code

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
