### ISSUE TITLE
Linux does not support Tray event mouse mode

### ISSUE THREAD

**Issue by 2464138264** [electron/electron#44358]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.27

### What operating system(s) are you using?

Other Linux, Ubuntu

### Operating System Version

ubuntu

### What arch are you using?

x64

### Expected Behavior

Linux supports Tray event mouse mode

### Actual Behavior

Linux does not support Tray event mouse mode

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
