### ISSUE TITLE
Electron seems depending an unsupported package: npm warn deprecated boolean@3.2.0: Package no longer supported.

### ISSUE THREAD

**Issue by wildtang** [electron/electron#44416]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.2.2

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 19044.5011

### What arch are you using?

x64

### Expected Behavior

When npm install, I saw a warning:

```
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

I expect no this warning.

### Actual Behavior

After invest, I found it is electron that depend on it.

```
npm ls boolean
my-proj@0.1.0 F:\my-proj
└─┬ electron@32.2.2
  └─┬ @electron/get@2.0.3
    └─┬ global-agent@3.0.0
      ├── boolean@3.2.0
      └─┬ roarr@2.15.4
        └── boolean@3.2.0 deduped
```

Hope this problem can be resolved, thanks!

**Comment by ckerr** [comment]
@wildtang, thanks for reporting this.

As far as Electron goes, probably best to report this to https://github.com/electron/get, which is the last point in the dependency chain that the Electron maintainers have any control of.

Upstream global-agent issue: https://github.com/gajus/global-agent/issues/70

I'm going to close this `electron/electron` ticket since this isn't fixable inside this repo, but this should probably be tracked in electron/get.
