### ISSUE TITLE
Electron Sveltekit Apps Error Uncaught (in promise) Error: spawnSync C:\Windows\system32 ENOENT

### ISSUE THREAD

**Issue by batis97** [electron/electron#44415]
Hello I have a problem when my application is run, the application is just stuck on the splash screen and the console log displays an error 
"Uncaught (in promise) Error: spawnSync C:\Windows\system32 ENOENT"  on some users

Has anyone experienced this error and how to solve it.

Package uses:
"electron": "^33.0.2",
"electron-builder": "^24.6.4",
"typescript": "^5.1.6",
"vite": "^4.0.4"
"svelte": "^3.57.0",

thanks before

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
