### ISSUE TITLE
Websocket (WSS) fails to send cookies when intercepting custom app-files protocol

### ISSUE THREAD

**Issue by z2014** [electron/electron#44422]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Ventura 13.6.9

### What arch are you using?

x64

### Last Known Working Electron version

i dont know

### Expected Behavior

this is demo link

Websocket (WSS) fails to send cookies when intercepting custom app-files protocol

### Actual Behavior

ws create without cookies

### Testcase Gist URL

https://gist.github.com/z2014/0815b33d3ce8c700b63679d0519c1ab5

**Comment by mlaurencin** [comment]
Thanks for reaching out and logging this issue! It seems to me that rather than a bug, this is more a question about why your code is not working. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
