### ISSUE TITLE
How to call the WebHID API in an Electron application after packaging?

### ISSUE THREAD

**Issue by Leaf550** [electron/electron#44573]
I am using the WebHID API in an Electron application. The WebHID API requires the webpage to be served over HTTPS to work. However, after packaging the Electron application, the page is opened directly using loadFile. How can I correctly use the WebHID API in Electron?

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
