### ISSUE TITLE
Not set to open URL program

### ISSUE THREAD

**Issue by Homebrew1** [electron/electron#44617]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.6.1

### What arch are you using?

x64

### Expected Behavior

vue-cli-service electron:build

### Actual Behavior

![Image](https://github.com/user-attachments/assets/dff305d7-a0b7-467d-affb-6a7d15b924d6)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
