### ISSUE TITLE
Apply Chromium Patch

### ISSUE THREAD

**Issue by ChrisKuBa** [electron/electron#44663]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Works as expected. Was fixed in one of the latest chromium patches.

### Actual Behavior

Chromium/Electron instance crashes

### Additional Information

https://issues.chromium.org/issues/377324991
https://chromium-review.googlesource.com/c/chromium/src/+/6017885

Hello, we are using “experimental” Chromium features that are broken in one of the latest Chromium versions, so we cannot update Electron.
Hopefully it is an option for you to manually patch the Chromium version in the currently supported Electron versions.

Thanks

**Comment by nikwen** [comment]
Not a maintainer, but if you want to use the patch sooner than it's included in an official build, you could [build Electron yourself](https://www.electronjs.org/docs/latest/development/build-instructions-gn) and apply it.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
