### ISSUE TITLE
FCM integration

### ISSUE THREAD

**Issue by w4ugit** [electron/electron#44707]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS Sequoia 15.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The system will receive a token that I can transfer to the server and use it to send push notifications

### Actual Behavior

I have an application written in React. I integrated Firebase Cloud Messages there. If you open http://localhost:3000 in the browser, everything works. When I run the app through Electron - I get an error.

**AbortError: Registration failed - push service not available**

I have a mobile app running through FCM, so I would like to integrate it here as well. I would like to receive notifications and via IPC to the main thread to show as a system push

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
