### ISSUE TITLE
Map() data is getting lost

### ISSUE THREAD

**Issue by AneesShaik167** [electron/electron#44842]
The stored data in export let connectedDevices = new Map(); in a renderer.js is lost after few activities in the app. we are basically storing HID devices in this Map and using it further, after a point we have a button in UI on click of it we need this connectedDevices which were seeing empty.

-------code piece where we set----------
const newDevice = new HID.HID(path);

      connectedDevices.set(path, {
        device: newDevice,
        metadata: { model: null, serialNumber: null, firmwareVersion: null },
        path,
        receiveDataArray: [],
        receiveDataRemaining: 0,
        sendPacketsArray: [],
        noOfPacketsSent: 0
      });

Place where we fetch and see that as empty, both are in same file but different methods

@everyone kindly help

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
