### ISSUE TITLE
How to reject the url like 'bdapi://xxxxxx' from web page request in the BrowserView

### ISSUE THREAD

**Issue by elevenwin** [electron/electron#44863]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When the BrowserView open the website "https://map.baidu.com", it will open a dialog ('open new app for ......' .).

### Proposed Solution

I expect return a bad response only, but not show the dialog.
It will browses various websites, expect handle for the popular network protocol(Not only resolve the website tip on Problem Description).
How do I catch them ,and return a bad response,not show anything to user.

### Alternatives Considered

Nothing

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
