### ISSUE TITLE
why nodeIntegration set true webgpu cont work

### ISSUE THREAD

**Issue by lichspace** [electron/electron#44880]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.1.1

### What operating system(s) are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Expected Behavior

when nodeIntegration  = true webgpu cont get device

`async function webgpuTest() {
  if (!navigator.gpu) {
    throw Error("WebGPU not supported.");
  }

  const adapter = await navigator.gpu.requestAdapter();
  if (!adapter) {
    throw Error("Couldn't request WebGPU adapter.");
  }

  const device = await adapter.requestDevice();
  console.log(device);
  //...
}
`

### Actual Behavior

webgpu should get

**Comment by lslzl3000** [comment]
Test 32.1.1 on mac, the `webgpu` works well. 

I think it's noting to do with `nodeIntegration` for `webgpu` to work,  try find other problems.
e.g.  webgpu only works on [Secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) ,  the localhost or https domain should be fine.  If you run the page under custom Schemes, you can try disable `webSecurity`

**Comment by lichspace** [comment]
> Test 32.1.1 on mac, the `webgpu` works well.
> 
> I think it's noting to do with `nodeIntegration` for `webgpu` to work, try to find other problems. e.g. webgpu only works on [Secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) , the localhost or https domain should be fine. If you run the page under custom Schemes, you can try disable `webSecurity`

yes mac is OK, but windows11 Couldn't request WebGPU adapter
i make an demo https://github.com/lichspace/electron-ts

**Comment by clavin** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by gavan1** [comment]
@lichspace have you tested if the gpu workload is actually using the gpu?

I am seeing kernel task cpu usage even when webgpu is set.
