### ISSUE TITLE
Catch error from electron ERROR:mouse_cursor_monitor_win.cc(104)] Capture: Unable to get cursor info. Error = 5

### ISSUE THREAD

**Issue by chris0203** [electron/electron#44973]
When I trying to screen capture
```typescript

const mediaConstraints = {
      audio: false,
      video: {
          mandatory: {
              chromeMediaSource: 'desktop',
              chromeMediaSourceId: source.id,
          },
      },
  } as MediaStreamConstraints;
  try {
      const stream: MediaStream =
          await navigator.mediaDevices.getUserMedia(mediaConstraints);
          console.log(stream.getTracks());
          return stream;
  } catch (error) {
      // Handle errors here
      console.error('Error accessing media devices.', error);
      throw new Error('Could not access media devices')
  }
``` 
Then I Press `Win Key + L` on windows 10 system, then show the `ERROR:mouse_cursor_monitor_win.cc(104)] Capture: Unable to get cursor info. Error = 5`

This should system can't capture the mouse cursor, so got error, but on the try catch block is didn't catch the error, it's shows nothing no error message no streaming, only print out error message on electron dev log.

How do I catch this error??

Electron Version: 30.0.1
OS: Windows 10 Pro Version 22H2

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
