### ISSUE TITLE
Add Apple login error

### ISSUE THREAD

**Issue by Doker-Ambition** [electron/electron#44993]
Hello, I am developing an application using Electro9 and need to add the Apple login feature, but I encountered a problem:
1. Login principle:
When I click login, I will request Apple's login link and open it in a new window. Then, the user enters their account, clicks enter, and enters their password to log in
2. Phenomenon:
2.1. In the login page that opens in a new window, entering my account will tell me that my identity cannot be verified, but when I open this link in a browser such as Google, I can enter and log in normally
PS： This phenomenon will not occur in the locally running (echo: electron./main_decess/main. js), but it will appear after packaging and generating exe or pkg
I have no way to solve this problem, I hope to get your help

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
