### ISSUE TITLE
I hope there are user-friendly prompts during the installation process of Electron.

### ISSUE THREAD

**Issue by VacantHusky** [electron/electron#45032]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I hope there are user-friendly prompts during the installation process of Electron.

I have wasted a whole night installing the electron.

### Proposed Solution

For example, printing on the console:

```
Preparing to download from https://github.com/electron/electron/releases/download/v11.2.0/electron-v11.2.0-darwin-x64.zip
Downloading...1k/s

ERROR: xxxxxxxxxxxxx

Please manually download and place the file in C:\Users\xxxxxx\AppData\Local\electron\Cache\xxxxxxxxx\electron-v11.2.0-darwin-x64.zip.
Then try again npm install

Or set up a env: ELECTRON_DOWNLOAD_PROXY=http://127.0.0.1:10809

```

This way, I can clearly know where I am downloading from and what the download link is. And how to manually download it. Or use my agent.

### Alternatives Considered

。

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
