### ISSUE TITLE
how to get a startup business loan with no money

### ISSUE THREAD

**Issue by snake-plant-care-indoors** [electron/electron#45059]
"I’m interested in building a cross-platform desktop app with Electron to help startups manage loan applications. For example, the app could include offline financial calculators or tools for document preparation.

Are there starter templates or existing Electron-based financial applications that I can use as a reference? Would love to hear your thoughts. Thanks for this powerful framework!"

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
