### ISSUE TITLE
Youtube Video Stuck on 59sec

### ISSUE THREAD

**Issue by absunstar** [electron/electron#45087]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32

### What operating system(s) are you using?

Windows

### Operating System Version

window 11

### What arch are you using?

x64

### Expected Behavior

when open youtube video Normal Play until Ended

### Actual Behavior

when open youtube video Normal Play until 59 secound - after that loading but not played any more that

### Additional Information

most browsers bulitin Chromium has the same Problem
i try change useragent and edit headers but Not Working

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
