### ISSUE TITLE
Connecting a Flask server with the Electron frontend after .exe installation.

### ISSUE THREAD

**Issue by arrifat346afs** [electron/electron#45096]
In my IDE, when I run my app, it connects with the backend Flask server without any problem. But after I tried to build it into an .exe file to install on my computer, I used PyInstaller to make the backend into a standalone .exe. Then I built the whole Electron app into an .exe. After that, I tried running the .exe; it opened a blank app. Then I checked Inspect in the Network section; it could not connect with the backend. If there is any better way to solve this?

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
