### ISSUE TITLE
IME / diacritics / emoji & symbol picker appears at upper left-hand corner

### ISSUE THREAD

**Issue by geeeeeeeeek** [electron/electron#4539]
I'm encountering a weird situation. When I was inputting characters in Chinese, the IME window would appear at top left of the app first, and then in a normal position for the consecutive letters. Please see the snapshot below.

Maybe @zcbenz you can view this issue.

![qq20160218-0 2x](https://cloud.githubusercontent.com/assets/7262715/13143194/3cb382de-d67d-11e5-9fbf-ca42a62db68a.png)
- Electron Version: v0.36.7
- OS: Latest Mac OS X, 10.0.2 as far as I can recall

Issue reproduced every time on several machines.

There is a webview tag in my app. Could this be the cause?

**Comment by paulcbetts** [comment]
We see this bug even with the diacritics menu, it seems to be related to WebView tags. To repro:

1. Create a webview tag with an input box
1. On an English keyboard layout, hold the letter A
1. Diacritics menu is positioned way off, like the screenshot shows

**Comment by zcbenz** [comment]
Atom has the same problem too. It is not using the webview tag though, but moving the input tag dynamically.

It would be great if you can create a reproducible example with Chrome apps and then report it to [Chromium's issues list](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by geeeeeeeeek** [comment]
@zcbenz I'm sure it has nothing to do with Chromium. Open a site without webview in electron cannot reproduce this issue. And I use atom everyday and never saw this kind of wierd situation.

**Comment by zcbenz** [comment]
Chrome apps can also use webview tag, and Electron is sharing the same code of webview with Chrome.

**Comment by geeeeeeeeek** [comment]
@zcbenz okay, I'll check it out.

**Comment by mnquintana** [comment]
We also encounter this with the Emoji / Symbols picker on OS X, also with `webview`s.

**Comment by paulcbetts** [comment]
This is https://bugs.chromium.org/p/chromium/issues/detail?id=593134#

**Comment by hankbao** [comment]
This is really annoying for users using a CJK input method. It looks like the issue only shows up on OS X.  Could Electron provide any workaround?

**Comment by javan** [comment]
The source of the problem seems to be selection and/or focus related. The IME position is anchored to the host page's selection or activeElement, which is generally the `<body>`. Because `<webview>`s have their own content window, they each maintain their own selection ([example](https://cloud.githubusercontent.com/assets/5355/19023234/6b090cde-88b7-11e6-9faf-db21b03fb98a.png)) and this seems to confuse Chrome.

I encountered this issue when building the Basecamp 3 app (we use a lot of emoji) and worked around it by ensuring the active `<webview>` is the only view with a selection. In hopes of pushing this issue forward, I've put together an example app that demonstrates the problem and includes my workaround: https://github.com/javan/electron-webview-ime-fix. 

Hopefully the Chromium team will fix things up. In the meantime, perhaps Electron could build in a similar fix?

**Comment by paulcbetts** [comment]
Holy shit, great debugging @javan - I'm going to work on this next week (i.e. actually working on a Chromium fix) but in the meantime this seems like a good workaround

**Comment by hankbao** [comment]
Should we update this issue on the Chromium side?

**Comment by steakknife** [comment]
Btw: WebKit/Chromium could use a `-webkit-character-accent-menu: none;` or similar style to disable the macOS character accent menu (restoring key repeat). Adding event handlers isn't always possible/desirable in modular apps, and it would simplify the atom codebase also.

**Comment by javan** [comment]
@paulcbetts did you end up looking in to this one? My workaround isn't bulletproof and it'd be awesome to resolve this. Possibly related: https://github.com/electron/electron/issues/6357, https://github.com/electron/electron/issues/5900

**Comment by paulcbetts** [comment]
@javan It's pretty high on our list too, but not yet

**Comment by hankbao** [comment]
Sadly, the counterpart of this issue on the Chromium issues list has been archived.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
