### ISSUE TITLE
Maximized frameless window has border on Windows 10

### ISSUE THREAD

**Issue by N1xx1** [electron/electron#4573]
* Electron version: v0.36.8
* Operating system: Windows 10

I'm trying to make a frameless window that still has the native functionality (double click to maximize, for example), but for some reason when I maximize using the double click or `BrowserWindow.maximize()` it shows a blue border like in this image:

![image](https://cloud.githubusercontent.com/assets/680445/13219983/9bcf47c8-d973-11e5-8f8d-9c05cacdd1b9.png)

However when I maximize by dragging the window to the top of the screen the border is still here but black. That's the same border that appears when the web contents lag during the resize.
Apparently [Discord](https://discordapp.com) "solved" this issue (their border is dark gray so it blends better with the application), but I don't know how they actually did it.

**Comment by N1xx1** [comment]
For reference, here's what happens during the resize:

![image](https://cloud.githubusercontent.com/assets/680445/13220476/abc64d90-d976-11e5-8caa-3e02680663f2.png)

**Comment by N1xx1** [comment]
Hello, has anyone taken a look into this yet? Actually it would be enough to have some sort of method to change the border color for the time being.

**Comment by N1xx1** [comment]
This didn't solve my issue, unfortunately. Disabling the thickframe will have the same effects of a transparent window, no native resize. I think the problem is that the web view is not correctly overlayed when the app is full screen.

Thanks.

**Comment by bsclifton** [comment]
I know it's been a while, but I wanted to share that we are running into this issue also w/ our fork of Electron in Brave.  We're tracking it with https://github.com/brave/browser-laptop/issues/6258

The problem happens:
- with Chromium 54 (I believe we are using 54.0.2840.100)
- when the frameless window is maximized (fullscreen is fine)

Originally, I only noticed this issue happening with DPI at 100% and fixed it here:
https://github.com/brave/muon/pull/134/files

The fix works because the border was being added during WM_NCCALCSIZE.  I've updated the code since then with a better approach: listen for the WM_NCCALCSIZE and WM_NCPAINT events where `has_frame()` is false and set result as 0 and return true (prevent DefWindowProc from firing).

Even with these fixes in place, borders are added (only during maximized; not fullscreen) when DPI is greater than 100%.  Something odd I noted (which didn't change- it was this way in Chromium 53) is that the window will have a negative X/Y equal to what the frame should be (~7px) and the window will be wider/taller by 2x that value.  This appears to be intentional:
https://blogs.msdn.microsoft.com/oldnewthing/20120326-00/?p=8003

I haven't found a solution, but wanted to share some information while it's fresh :smile:

**Comment by bsclifton** [comment]
Solution found :smile: 
https://github.com/brave/muon/commit/30fd6ff5ac772cb645b0d4be78fae49d84fbbb19

I'll work on upstreaming a patch

**Comment by N1xx1** [comment]
@bsclifton Awesome work, thank you!
I will most definitely check it out as soon as I can.

**Comment by bsclifton** [comment]
@N1xx1 patch is here if you'd like to try it:
https://github.com/electron/electron/pull/8404
