### ISSUE TITLE
Vertical offset for OS X dialog sheets (dialog.showMessageBox)

### ISSUE THREAD

**Issue by davej** [electron/electron#4679]
It's really nice to have dialog sheets. But because custom app GUIs in Electron are generally done in HTML, it would be nice to have a vertical offset property (in options) for recreating a native-like approach. Here is what a sheet looks like in the preferences window of an app I'm working on:

<img width="662" alt="screen shot 2016-03-04 at 23 46 31" src="https://cloud.githubusercontent.com/assets/26971/13543534/0dc9d0f2-e264-11e5-91fb-3fc2c9dbb2c6.png">

The sheet should appear on the lower border of the toolbar to behave like a native sheet. Specifying a vertical offset in pixels would allow me to recreate this effect. [It looks to be possible according to the developer docs](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Sheets/Tasks/PositioningSheets.html) but I don't know enough about Cocoa to know for sure.

**Comment by davej** [comment]
I guess this option could also be applied to open/save dialogs.

**Comment by bengotow** [comment]
+1 for this one—we use sheets in Nylas N1 and they always appear like this:

![image](https://cloud.githubusercontent.com/assets/1037212/13620097/04b165f8-e542-11e5-9f5c-70fce865a81a.png)

**Comment by bengotow** [comment]
After thinking about this a bit and looking at the Mac OS X docs, I think we should add a new option to `BrowserWindow`:

- `titleBarHeight: <pixels from top of window>`

This would be the vertical offset at which sheets should be positioned. I'd also like to change the behavior of `titleBarStyle` (an existing option) on Mac OS X. The current behavior is:

- `titleBarStyle`: `hidden` results in a hidden title bar and a full size content window, yet the title bar still has the standard window controls ("traffic lights") in the top left.

- `titleBarStyle`: `hidden-inset` results in a hidden title bar with an alternative look where the traffic light buttons are slightly more inset from the window edge.

The problem is that "slightly more inset" is not quite right for our app which uses a Safari-sized toolbar that is 38px tall. (They're too far down) I think we should deprecate the `hidden-inset` option and instead make `hidden` automatically position the window controls so they are centered within the `titleBarHeight` if it's provided. So for example, `titleBarStyle:hidden, titleBarHeight: 80` would center the buttons 40px from the top of the window and display sheets 80px from the top of the window.

**Comment by davej** [comment]
@bengotow Have a look at my screenshot in the first comment. I don't think your approach would work for that use case (Preferences like this are a reasonably common screen on OS X).

I think it's best to decouple the offset of the sheets from the offset of the buttons if at all possible. If you want to couple them then it's trivial to do it in Javascript. Perhaps I'm missing some of the reasoning behind this decision though.

**Comment by bengotow** [comment]
Ahh you're definitely right—if there are other controls beneath (like the tabs) you really need to specify them separately... We can definitely make them different config settings, but I really wish we could keep the BrowserWindow config from becoming a mess! Maybe `titleBarHeight` is still the right property name, we just won't change the positioning of the window controls?

**Comment by davej** [comment]
`titleBarHeight` sounds nice and declarative but it also seems a bit implicit if the only effect of the property is to offset sheet dialogs. If this is the case I would probably be in favour of something more explicit like `sheetVerticalOffset` but not strongly so.

I take your point about the BrowserWindow config becoming a bit of a mess. Another possibility is to move the option to `dialog.showX()` instead? I'm not sure how I feel about that but it does add more flexibility [1] when you define the sheet offset directly at the call site. I don't really have an opinion on this but it's worth considering.

[1] e.g. if the titlebar height changes on the UI or you want to do something crazy like a sheet within a sheet.

**Comment by zcbenz** [comment]
I think making it an option of `dialog.showMessageBox` and its friends would be a good idea, it is much easier to use when the UI can be dynamically changed.

**Comment by bengotow** [comment]
Hmm good point. I agree it'd be ideal for this to be dynamic. Our top bar height can change based on the user's theme, so it'd be great to query the DOM for a boundingClientRect right before showing the dialog and pass the height as a param. I'll look into implementing this soon.

**Comment by zcbenz** [comment]
Closed with #4922.
