### ISSUE TITLE
Get and specify the program to open the item when using shell.openItem

### ISSUE THREAD

**Issue by zg2013** [electron/electron#4815]
- Electron version: all
- Operating system: all

Can't get the file launcher,So open the program is actually not know.
I want to get the initiator's path, so the use of selective "open appPath filePath" open way, rather than having to default.

Excuse me, can you provide relevant interface to obtain the default launcher path？

**Comment by kevinsawicki** [comment]
There isn't currently any API for this I believe in Electron

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
