### ISSUE TITLE
FeatureRequest: API to add custom windows jump list category

### ISSUE THREAD

**Issue by juturu** [electron/electron#4852]
* Electron version: 0.37.2
* Operating system: Windows

API to add custom windows jump list category. This change will be similar to AddUserTasks which already exists in electron/atom/browser/browser_win.cc. Need to use [AppendCategory](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378396(v=vs.85).aspx) and expose this API.

Can you please help in adding this? For these kind of feature request, what is the typical time line when electron will be updated with this?

**Comment by felixrieseberg** [comment]
While it's great that you're interested in Electron, please understand that not every feature request actually makes it into the code base; and that most feature requests make it into Electron because the person who actually needs it provides a pull request.

So, if you have a use case that needs said feature, it'd be awesome if you get a pull request going - I'd be happy to help you out with directions and code reviews.

**Comment by kevinsawicki** [comment]
I believe this is now supported via #6826, closing this out.
