### ISSUE TITLE
Can support modular?

### ISSUE THREAD

**Issue by icode** [electron/electron#4961]
Like JDK 9 [JEP 201](http://openjdk.java.net/jeps/201)

Best use npm manager

**Comment by kevinsawicki** [comment]
Can you add more details to the issue body? I'm not sure what you are asking for based on that link.

**Comment by icode** [comment]
like i not need 3d transform , i can remove all about 3d module.

**Comment by puranjayjain** [comment]
@icode I got your query you mean to say is carry only the components of electron that are required to render a desired set of properties or attributes you want (e.g you don't want to use css 3d transforms so you will remove it from the renderer). 

If you are considering it because of the size of the app bundle, removing a small pool of code won't make much of a difference anyway and secondly removing it might have breaking changes to your rendering.

If you still want to do so I suggest you follow the build instructions [here](difference) according to your platform and make a custom build of electron for your own use.

Hope this solves your problem :smiley:

**Comment by zcbenz** [comment]
Electron is based on Chromium and unfortunately Chromium is not designed to be modular, it just ships everything with only a few features can be turned off.
