### ISSUE TITLE
autoUpdater does not work when have authenticated proxy

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5020]
- Electron version: `0.36.7`
- Operating system: Windows

The `autoUpdater` module in electron does not appear to be attempting to update all my users on windows from `3.0.1` to `3.1.0`.  It took a clean reinstall of the application on a few computers that I am aware of before it decided there was an update too download.

Upon sniffing out the traffic I could see that an update check request was being sent to fetch the [RELEASES](http://update.googleplaymusicdesktopplayer.com/update/win/3.0.1/RELEASES) file and then didn't attempt to download the obviously available update.

I don't see how it can work for around 80% of users (that number is a guestimate) and not work for the rest.

The update server is here http://update.googleplaymusicdesktopplayer.com/update/{platform}/{version} 
The update code is here https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/autoUpdater.js

**Comment by kevinsawicki** [comment]
What version of squirrel on windows is your installer using?

**Comment by MarshallOfSound** [comment]
Whichever version is packaged with `grunt-electron-installer` version `1.2.3`

I can see that that repository received a major version bump recently to `2.0.0`, is that bump at all related to this issue?

**Comment by kevinsawicki** [comment]
>  is that bump at all related to this issue?

No, that major bump was for a new underlying library that was used.

**Comment by MarshallOfSound** [comment]
> No, that major bump was for a new underlying library that was used.

Bit of a long shot hope :laughing: 

I'm trying to find a way to accurately replicate this issue but it appears to be completely random :cry:

**Comment by kevinsawicki** [comment]
Are you able to get the squirrel logs off any of the machines that are experiencing the issue?

**Comment by MarshallOfSound** [comment]
I'll grab them as soon as I can make it do this again.  Completely uninstalling and reinstalling to replicate is time consuming when there is only a small chance it fails :smile:

**Comment by MarshallOfSound** [comment]
@kevinsawicki It appears as though there is some release notes parsing error https://gist.github.com/MarshallOfSound/7c6616b032a2499afd56de71186ef451 but then it still (eventually) starts building the full package and my app receives an update notification.

Still trying to make it not update :disappointed:

**Comment by MarshallOfSound** [comment]
@kevinsawicki I managed to get a log from someone else's PC experiencing this issue.  
https://gist.github.com/rickwastaken/c659c5a9fe75ecb3db274222bf6c288c  

From what I can see they are having really strange DNS issues, which used to happen a lot (as an example https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/301)

However when the user accesses `update.googleplaymusicdesktopplayer.com` in there browser.  It resolves the address fine (as seen [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/213)

Any reason why C#'s WebClient wouldn't resolve the name but a browser would?

**Comment by kevinsawicki** [comment]
> Any reason why C#'s WebClient wouldn't resolve the name but a browser would?

No idea, not sure if @paulcbetts might know 🔦

**Comment by paulcbetts** [comment]
> Any reason why C#'s WebClient wouldn't resolve the name but a browser would?

If it's using an authenticated proxy

**Comment by MarshallOfSound** [comment]
@paulcbetts Is there any way around this?  Or any way for me to detect that proxy from within electron and tell the user they won't be able to get updates?

**Comment by MarshallOfSound** [comment]
@paulcbetts Or maybe implementing this https://msdn.microsoft.com/en-us/library/system.net.webrequest.defaultwebproxy.aspx  in Squirrel.Windows

**Comment by baconface** [comment]
@MarshallOfSound There are several NPM packages that let you detect a proxy. Or you could write your own solution in Node.js to detect a proxy. Could you do that without needing changes in Squirrel for Windows? Because there would be cases where someone would want to update via a proxy.

Ideally I would skip all the above together and either check to see if the file could be reached and notify the user if not or attempt to download the file and notify the user if the download fails. This is how most updaters handle this.

If none of the above works for you I guess I don't completely understand your case.

**Comment by paulcbetts** [comment]
So, the problem at the end of the day is, if you have an authenticated proxy on Windows, you need to pop UI to prompt for username/passwords at *the time of request* (i.e. not just in a system settings dialog). This is deeply stupid, but it is what it is.

To mitigate this, you _could_ download RELEASES and the latest NuPkg file yourself with Chromium (as well as implement the login callback to actually show UI in-app), then point your updater URL to that temp folder. This is deeply obnoxious, but so are proxy servers.

**Comment by MarshallOfSound** [comment]
@paulcbetts Out of interest do you know how / if atom handles this problem?  Downloading the RELEASES and `nupkg` files from electron seems a bit silly to me but it seems like I need to somehow bypass a network connection all together so I'm not sure.... :cry:

**Comment by paulcbetts** [comment]
@MarshallOfSound It almost certainly doesn't solve it at all

**Comment by chandrachivukula** [comment]
@MarshallOfSound, have you found a way to get the autoUpdater to work with an authenticated proxy?

(for a separate issue) We've added headers option to setFeedUrl which if you can set the headers, and call checkForUpdates(), it should work. could you try this out and let us know?

**Comment by vadim-ch** [comment]
> (for a separate issue) We've added headers option to setFeedUrl which if you can set the headers, and call checkForUpdates(), it should work. could you try this out and let us know?

**Comment by vadim-ch** [comment]
> (for a separate issue) We've added headers option to setFeedUrl which if you can set the headers, and call checkForUpdates(), it should work. could you try this out and let us know?

**Comment by vadim-ch** [comment]
> (for a separate issue) We've added headers option to setFeedUrl which if you can set the headers, and call checkForUpdates(), it should work. could you try this out and let us know?

As seen from the code heades are not transferred - https://github.com/electron/electron/blob/master/lib/browser/api/auto-updater/auto-updater-win.js#L21

**Comment by MarshallOfSound** [comment]
@vadim-ch As in the documentation the headers param is macOS only

**Comment by vadim-ch** [comment]
@MarshallOfSound Yes. It's very bad. I am sad. I'm looking for any workaround.

**Comment by vadim-ch** [comment]
Hello. For myself, I found a solution.

First step:
Request the latest version available. (For example using [Electron Release Server](https://github.com/ArekSredzki/electron-release-server) you can get a list of versions - http://download.myapp.com/api/version)

Second step:
Compare the current version and available.

Third step:
Download file available version to a temporary folder(temporaryDirPath) - http://download.myapp.com/download/${availableVersion}/windows_64/MyApp-0.1.1-full.nupkg

Fourth step:
UptoUpdater set the path, but not url. And checkForUpdates.
```
autoUpdater.setFeedURL(temporaryDirPath);
autoUpdater.checkForUpdates();
```

**Comment by scottrippey** [comment]
@vadim-ch Thank you for listing out your steps!  This has certainly helped me develop a solution, where no other approach worked!
We require an authentication header for our release server, so we've had a hard time figuring out how to achieve this.  I'm following your approach -- manually downloading the `RELEASES` and `app-0.0.0-full.nupkg`  to a temporary folder (with proper auth creds), then calling `setFeedUrl(tempPath)`.  
So far it seems to be working!  Thanks for this approach!

**Comment by scottrippey** [comment]
However, now, I am actually trying to solve this "proxy authentication" issue.
Within my app, I have added a `app.on("login", ...` handler, which prompts the user for credentials. It works great, except for the `autoUpdater`. 

I was hoping that autoUpdater was using ` electron.net`, so that it would fire the `login` event, but it does not fire.
I get the impression that the updater runs outside of Electron.

The good news is, my "temporary folder" solution actually handles this just fine on Windows, because it uses `electron-fetch` to download the update.

So, the only solution I can think of for macOS is to try the "temporary folder" approach too. I'm first curious if Squirrel for Mac even allows "update from folder" the same way that Squirrel for Windows does? 
Or, if it doesn't, how much work would it be to get the autoUpdater to use the `electron.net` lib?

**Comment by joshuapinter** [comment]
@scottrippey did you ever get a chance to open-source this? I'm running into the same issue on Windows.

**Comment by scottrippey** [comment]
Sorry @joshuapinter , there's just too much on our roadmap at work to open-source this.  I've been working with management to support "free days", where we work on projects like this, so hopefully that will come around soon!  
Also, I've been engaged with the Electron team directly, documenting the troubles with  the current AutoUpdater and how some of these changes could be incorporated upstream.  

Unfortunately, though, the only current solution is to roll-your-own solution.

**Comment by scottrippey** [comment]
I don't mind sharing some snippets, though!

On Mac, I create a temp folder, and in it I put `app-name-1.2.3-mac.zip`, and I generate a `feed.json` that points to it.
On Windows, I create a temp folder, and in it I put `app-name-1.2.3-full.nuget` and I generate a `RELEASES` that points to it.
To _generate_ the `RELEASES` file, it requires a certain format; here's a snippet of how I do that:
```
import hasha from 'hasha';
import fse from 'fs-extra';
import temp from 'temp';
import path from 'path';
...
        const tempFolder = temp.track().mkdirSync('name-of-app-update-');
        const tempFilename = 'name-of-app-1.2.3-full.nuget';
        const tempFilePath = path.join(tempFolder, tempFilename);
        // On Windows, autoUpdater will check the feedURL for a 'RELEASES' manifest:
        const checksum = await hasha.fromFile(tempFilePath, { algorithm: 'sha1', encoding: 'hex' });
        const filesize = (await fse.stat(tempFilePath)).size;
        const RELEASES = `${checksum} ${tempFilename} ${filesize}`;
        await fse.writeFile(path.join(tempFolder, 'RELEASES'), RELEASES);
```
Then I call `autoUpdater.setFeedUrl(tempFolder); autoUpdater.checkForUpdates()` and it picks it up!

**Comment by joshuapinter** [comment]
@scottrippey I know that struggle! Thanks so much for sharing your snippets and advice!

I was able to test a file download using Electron at the problem customer site in question and it worked great, so I think we'll have to do the very same thing you did and just handle it ourselves, passing the autoUpdate the local file once downloaded to take it from there. 

Will likely take an additional week of rewriting but at least there's a way to do it and we're not alone on this.

Thanks again for your help!

**Comment by joshuapinter** [comment]
Hey @scottrippey, I'll be working on this all week. Quick question: what does the `feed.json` look like? 

Here's what mine looks like now: 

```json
{
  "name": "v0.1.7",
  "notes": null,
  "url": "file:///var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/CNTRAL Desktop-darwin-x64-0.1.7.zip"
}
```

And I'm getting this error: 

```
error: Update check failed. The server sent an invalid JSON response. Try again later.
```

Depending on how this all goes, would be interested in co-authoring a npm package for this at some point?

**Comment by joshuapinter** [comment]
Just looking around the docs a bit more, does it have to be like [this](https://github.com/Squirrel/Squirrel.Mac#update-file-json-format):

```json
{
	"currentRelease": "1.2.3",
	"releases": [
		{
			"version": "1.2.1",
			"updateTo": {
				"version": "1.2.1",
				"pub_date": "2013-09-18T12:29:53+01:00",
				"notes": "Theses are some release notes innit",
				"name": "1.2.1",
				"url": "https://mycompany.example.com/myapp/releases/myrelease"
			}
		},
		{
			"version": "1.2.3",
			"updateTo": {
				"version": "1.2.3",
				"pub_date": "2014-09-18T12:29:53+01:00",
				"notes": "Theses are some more release notes innit",
				"name": "1.2.3",
				"url": "https://mycompany.example.com/myapp/releases/myrelease3"
			}
		}
	]
}
```

**Comment by joshuapinter** [comment]
I finally got everything working so I just wanted to report back here quickly while I'm waiting for a release to build.

To corroborate @scottrippey's comments, here are the basic steps for using `autoUpdater` with a local directory for Mac (`darwin`) and Windows (`win32`): 

### Mac (`darwin`)

1. Create a temp directory to store your update files: 

    ```js
    import { app } from "electron";
    import path from "path";
    import fs from "fs";

    // Set global temporary directory for things like auto update downloads, creating it if it doesn't exist already.
    global.tempPath = path.join( app.getPath( "temp" ), "NTWRK" );
    if ( !fs.existsSync( global.tempPath ) ) fs.mkdirSync( global.tempPath );
    ```

2. Download `.zip` file containing the updated `.app`. 

    _This **needs** to be the `.zip` file. It's what `autoUpdater` is expecting on the `darwin` platform._

    ```js
    download( mainWindow, urlToZipFile, {
      directory: global.tempPath,
      onProgress: progress => mainWindow.webContents.send( "downloadProgress", progress )
    } );
    ```

    _The above should help get you started, but you'll need to flesh the rest of the download out, especially receiving progress from the Renderer thread._

3. Create a `feed.json` file in the `global.tempPath` directory with a `url` key that points to our downloaded `.zip` file: 

    ```js
    import fs from "fs";

    // We need to manually create a feed.json file with a `url` key that points to our local `.zip` update file.
    const json = { url: `file://${ global.tempPath }/${ downloadedZipFilename }` };

    fs.writeFileSync( global.tempPath + "/feed.json", JSON.stringify( json ) );
    ```

    _Note the file path has to be prefaced with `file://` on `darwin`. Not so with `win32`. Great find @scottrippey!_

4. Set `FeedURL` of `autoUpdater` to that `feed.json` file:

    ```js
    feedURL = `file://${ global.tempPath }/feed.json`;

    autoUpdater.setFeedURL( feedURL );
    ```

    _Note the file path has to be prefaced with `file://` on `darwin`. Not so with `win32`. Great find @scottrippey!_

5. Check for updates via `autoUpdater`: 

    ```js
    autoUpdater.checkForUpdates();
    ```

### Windows (`win32`)

1. Create a temp directory to store your update files: 

    ```js
    import { app } from "electron";
    import path from "path";
    import fs from "fs";

    // Set global temporary directory for things like auto update downloads, creating it if it doesn't exist already.
    global.tempPath = path.join( app.getPath( "temp" ), "NTWRK" );
    if ( !fs.existsSync( global.tempPath ) ) fs.mkdirSync( global.tempPath );
    ```

2. Download `.nupkg` file. 

    _This **needs** to be the `.nupkg` file. It's what `autoUpdater` is expecting on the `win32` platform._

    ```js
    download( mainWindow, urlToNupkg, {
      directory: global.tempPath,
      onProgress: progress => mainWindow.webContents.send( "downloadProgress", progress )
    } );
    ```

    _The above should help get you started, but you'll need to flesh the rest of the download out, especially receiving progress from the Renderer thread._

3. Download or generate a `RELEASES` file.

    _If you look above, @scottrippey outlines how to create this file yourself. In our case, we're using `electron-forge` and it is automatically generated and published to our release server so we only needed to download it._

    ```js
    download( mainWindow, urlToRELEASES, {
      directory: global.tempPath,
      onProgress: progress => mainWindow.webContents.send( "downloadProgress", progress )
    } );
    ```

    _The above should help get you started, but you'll need to flesh the rest of the download out, especially receiving progress from the Renderer thread._

4. Set `FeedURL` of `autoUpdater` to the `global.tempPath` directory where both the `.nupkg` and `RELEASES` files are:

    ```js
    feedURL = global.tempPath;

    autoUpdater.setFeedURL( feedURL );
    ```

    _Note that on `win32` you do not need to preface the `feedURL` with `file://`. Great discovery @scottrippey!_

5. Check for updates via `autoUpdater`: 

    ```js
    autoUpdater.checkForUpdates();
    ```



### Party

You now have a way to get around network proxies, pass your own headers and even get download progress. So dance!

![80s kid dancing](https://user-images.githubusercontent.com/180819/55168422-68378c00-5138-11e9-8b72-72b52a685fd5.gif)

**Comment by scottrippey** [comment]
Great work @joshuapinter ! I left a lot of "gaps" but it looks like you nailed it.
To summarize the main differences between Mac/Windows:
1. On Windows, both URLs can be file paths. On Mac, both must be `file://` URLs.
2. On Windows, you must have a `RELEASES` file that points to a `-full.nuget` file. On Mac, you must have a `feed.json` file that points to a `.zip` file.
3. On Windows, you call `setFeedUrl(tempPath)` and it finds the `RELEASES` file. On Mac, you call `setFeedUrl(path.join(tempPath, 'feed.json')`.

**Comment by scottrippey** [comment]
One other really important piece of information, regarding "rollbacks".
On Windows, the `-full.nuget` filename is actually important.  When reading the `RELEASES` file, it parses the filenames to extract the version numbers.  It determines the highest version number, and only installs it if it's higher than the current number.
For example, if you have `1.9.0` installed, then the file must be named something like `app-name-1.9.1-full.nuget`.  You cannot name it `app-name-full.nuget` nor `app-name-1.8.0-full.nuget` because Squirrel will NOT like those.

This posed a serious issue with our deployment strategy, particularly because we require the ability to do "rollbacks".  This works perfectly for Mac, because Squirrel for Mac is great -- it lets the server decide.  So rollbacks are easy.  But since Squirrel for Windows has this client-side logic, it prevents a rollback.
Our solution was, first, to *detect if an upgrade was a rollback* -- by parsing the `-full.nuget` filename and the app's path.  If so, we actually "spoofed" a new version number that was _greater_ than the current, and renamed the file.
For example, if we were on version `2.0.0`, but then needed to do a rollback to `1.9.9`, we would rename `app-1.9.9-full.nuget` to `app-2.0.1-ROLLBACK_1_9_9-full.nuget` and install it.  

Sorry, again, for such "half baked" information, but hopefully it might guide you if you encounter similar pitfalls!

I'm still working with management to make this solution open-source, I'm sure they'll approve at some point!

**Comment by joshuapinter** [comment]
@scottrippey Excellent summary and additional piece of detail regarding the "rollbacks". Thankfully, we don't need, or shouldn't need, that functionality. Whew.

Yeah, I might wrap this up into a nice library but we'll see if time permits. If I do, I'll post back here.

Cheers for all your help!

**Comment by sregger** [comment]
I'm confused by this behaviour as the updater cannot get through a **Basic** proxy but it can go through an **NTLM** or **Negotiate** proxy that uses the OS credentials.

**Comment by sregger** [comment]
I've found an alternative solution that works for basic proxies.

> Within my app, I have added a `app.on("login", ...` handler, which prompts the user for credentials. It works great, except for the `autoUpdater`.
> 
> I was hoping that autoUpdater was using ` electron.net`, so that it would fire the `login` event, but it does not fire.
> I get the impression that the updater runs outside of Electron.

This is true however you can listen for the autoUpdater `login` event instead. See https://www.electron.build/auto-update#updatersignal

      autoUpdater.on('login', async (authInfo, callback) => {
        const [username, password] = ...... // prompt on UI, use cache, other solution to acquire credentials
        callback(username, password)
      })
      autoUpdater.requestHeaders = {'User-Agent': userAgent}
      const {info, provider} = await autoUpdater.getUpdateInfoAndProvider()
      const updateAvailable = await autoUpdater.isUpdateAvailable(info)

**Comment by hosnar** [comment]
@joshuapinter did you have any issues with file protocol when implementing local feed auto update? I can't get this to work, because I keep getting error "_Error: Protocol "file:" not supported_".

**Comment by joshuapinter** [comment]
@hosnar I don't recall seeing that error message but it was over a year ago since I've looked at it.

**Comment by Thepphrit** [comment]
www.networking.co.th[www.google.co.th](https://google.com) @gmail.com @theptook45@gmail.com

**Comment by fengxiangge** [comment]
> I've found an alternative solution that works for basic proxies.
> 
> > Within my app, I have added a `app.on("login", ...` handler, which prompts the user for credentials. It works great, except for the `autoUpdater`.
> > I was hoping that autoUpdater was using ` electron.net`, so that it would fire the `login` event, but it does not fire. I get the impression that the updater runs outside of Electron.
> 
> This is true however you can listen for the autoUpdater `login` event instead. See https://www.electron.build/auto-update#updatersignal
> 
> ```
> autoUpdater.on('login', async (authInfo, callback) => {
>   const [username, password] = ...... // prompt on UI, use cache, other solution to acquire credentials
>   callback(username, password)
> })
> autoUpdater.requestHeaders = {'User-Agent': userAgent}
> // Will cause a login event
> const {info, provider} = await autoUpdater.getUpdateInfoAndProvider()
> const updateAvailable = await autoUpdater.isUpdateAvailable(info)
> ```

This was really worked. I have been success.

**Comment by Kemal48** [comment]
Hello ![image](https://user-images.githubusercontent.com/47145614/109001196-5278cb80-76ad-11eb-9067-93b2dfbd5171.jpeg)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by NookieGrey** [comment]
>    ```js
>    download( mainWindow, urlToNupkg, {
>      directory: global.tempPath,
>      onProgress: progress => mainWindow.webContents.send( "downloadProgress", progress )
>    } );
>    ```

Sorry, where is download function's location?

**Comment by sploders101** [comment]
@NookieGrey You'll probably have to write it yourself. Judging by the fact that they're passing a BrowserView to the function, I'd imagine it's an RPC call running through electron's IPC into a preload script in the frontend. You'll probably have to set up a set of events to transfer back and forth between the frontend and backend to make this work, and use something like Axios in the frontend to fetch the file.

**Comment by sploders101** [comment]
I just wanted to throw an idea out there that I'm using to satisfy a requirement for an internal tool for work. We don't necessarily need to download the files ourselves. We just need to add things to redirect the request to another location that can resolve them. My problem isn't quite the same, as I just need to have a password on my update server, which of course, squirrel for Windows doesn't support (even with the credentials in the URL as per http scheme spec). I'd be happy to release a POC example once I've finished and tested it, but what if instead of parsing and downloading packages ourselves, effectively eliminating the elegance and speed of delta updates, we just create a proxy on localhost. Then, when squirrel goes looking for an update, we receive all of its requests, and can do with them what we wish. In my case, I can simply inject an authorization header, rewrite the host, and voila! Authentication headers are now added to the request before they reach the update server.

Side note:
According to my research, it looks like squirrel is an external program that runs on-demand when electron asks for it. It does not appear that squirrel makes any requests outside of the app's lifecycle, because it only kills the app when it's already downloaded and ready to start the new version, so there's no reason the app couldn't be its own update server. Only the URL makes it into squirrel, and it doesn't support basic auth, so there's no hope of getting squirrel to make the requests properly (this term is used loosely, since this *is* kind of an edge case). However, electron has an http server, and squirrel can request via HTTP, which means the application can be squirrel's update server and it doesn't matter if squirrel supports the protocols used on the public-facing server. I'm not sure if this works or not for authenticated proxies, since squirrel would need to bypass them, but maybe there's an exception if it's sending requests to localhost?

**Comment by sploders101** [comment]
I have finished and tested my authentication proxy example and am happy to report that it works! Unfortunately, it's not the most secure thing in the world, but I'd say it's about as secure as bundling your update password with the application, which you'd probably have to do anyway unless you were to prompt the user for it on every launch. You could also start the server just long enough to get an update in order to mitigate the risk.

https://gist.github.com/sploders101/23719534c683216baf76b816098e614b

Ultimately, I think the most useful way to go about this would be to implement an RPC-esque proxy on stdin/out on both squirrel and electron, which could be handled on the JS side similarly to HTTP requests, and could be enabled via a command line flag on the squirrel exe, but I'm not sure how likely that is to be implemented.

**Comment by FCF-Releases** [comment]
hi all, everything seems to be working fine for me on this except that it never seems to trigger the autoUpdate.on('update-downloaded') event? Anyone experienced this?

**Comment by FCF-Releases** [comment]
Fingers crossed someone sees this! I was using this successfully and now it appears to not recognize the feedURL or at least autoUpdater.checkForUpdates() does not trigger anymore. Has anything changed in the AutoUpdater for electron?

**Comment by sploders101** [comment]
> Fingers crossed someone sees this! I was using this successfully and now it appears to not recognize the feedURL or at least autoUpdater.checkForUpdates() does not trigger anymore. Has anything changed in the AutoUpdater for electron? 

Are you using the built-in updater the npm module?

Unfortunately, I don't believe the built-in updater has supported this for quite some time, which is why I posted the in-app HTTP proxy method above. The updater runs outside the JavaScript context, so unless they add support for this, I don't think it's going to work. Someone please correct me if I'm wrong.

**Comment by christianblandford** [comment]
I have created a package to abstract all of this. It is not perfect, but it works. It uses a combination of a custom event emitter and intercepting the default autoUpdater events. It allows for passing a github token and a few other config items. The README.md is not currently 100% up-to-date, but it should be close. I am happy to help with any questions, and very much open to suggestions.

https://github.com/christianblandford/electron-github-autoupdater

**Comment by qiqetes** [comment]
I'm trying to Manually handle updates.

I download the update from s3 bucket whenever there's an available update. And then I create a `feed.json` file with the format:```js
{"url": "file:///var/temp/aofsdjaodsijf/update.zip"}
```
Then I set the ```js
autoUpdater.setFeedUrl("file:///var/temp/aofsdjaodsijf/feed.json");
autoUpdater.checkUpdates();
```
But I get this error: 
`Error: Could not locate update bundle for com.github.Electron within file:///Users/X/Library/Caches/com.github.Electron.ShipIt/update.SrmZwAy/` that looks nothing like the "url" that I passed...

I'm very stuck on this, some help would be very appreciated.

**Comment by zschreur** [comment]
@qiqetes Using the `url` package could help ensure the URL is properly formatted.

```
const URL = require('url');

...

const createFeedUrlFile = async (updateCache, zipFile) => {
   const json = {
      url: Url.pathToFileURL(zipFile).href
   }

   const feedUrlFile = path.join(updateCache, 'feed.json');

   await fs.promises.writeFile(feedUrlFile, JSON.stringify(json));

   return feedUrlFile;
}

...

autoUpdater.setFeedURL({
   url: Url.pathToFileURL(feedUrlFile).href
});
```

**Comment by qiqetes** [comment]
> 

Thanks for the reply. Seems like the urls are fine. (tried with your method, same error raises).
<img width="262" alt="image" src="https://user-images.githubusercontent.com/16906059/176198325-f4f09f85-d7c3-42dd-8eb9-b92904193520.png">

**Comment by saibhavateja1** [comment]
> I'm trying to Manually handle updates.
> 
> I download the update from s3 bucket whenever there's an available update. And then I create a `feed.json` file with the format:
> 
> ```js
> {"url": "file:///var/temp/aofsdjaodsijf/update.zip"}
> ```
> 
> Then I set the
> 
> ```js
> autoUpdater.setFeedUrl("file:///var/temp/aofsdjaodsijf/feed.json");
> autoUpdater.checkUpdates();
> ```
> 
> But I get this error: `Error: Could not locate update bundle for com.github.Electron within file:///Users/X/Library/Caches/com.github.Electron.ShipIt/update.SrmZwAy/` that looks nothing like the "url" that I passed...
> 
> I'm very stuck on this, some help would be very appreciated.

@qiqetes Did you figure out a way to solve this? Looks like autoUpdater creates update.*** before downloading. Since we are skipping that part and doing it ourselves, this file/dir seems to be missing. 

@joshuapinter How did you get this to work?

**Comment by qiqetes** [comment]
```ts
  const tempPath = path.join(app.getPath("temp"), "updateVersion");

  const setAutoUpdaterMac = () => {
    // We need to manually create a feed.json file with a `url` key that points to our local `.zip` update file.
    const json = {
      url: url.pathToFileURL(path.join(tempPath, "update.zip")).href,
    };

    fs.writeFileSync(tempPath + "/feed.json", JSON.stringify(json));
    console.log("file://" + tempPath + "/feed.json");

    autoUpdater.setFeedURL({
      url: url.pathToFileURL(path.join(tempPath, "feed.json")).href,
    });
```
I don't remember it too much, what I have now and it's working is that piece of code.

**Comment by saibhavateja1** [comment]
@qiqetes Thank you for the snippet. Do you mind sharing which version of electron you are using today? 
Also is the autoUpdater from electron module?

**Comment by qiqetes** [comment]
> @qiqetes Thank you for the snippet. Do you mind sharing which version of electron you are using today? Also is the autoUpdater from electron module?

Latest version, and yes, autoUpdater comes from the electron module;

**Comment by saibhavateja1** [comment]
@qiqetes Thank you. The issue's resolved now. The reason is – I am downloading a .dmg and feeding that to the autoUpdater when instead I should be feeding a zip file of .app 

One other thing that I would like to bring up is, I am being prompted with a message saying "Application is downloaded from the internet. Are you sure you want to open it?" This is happening every time an update is downloaded and installed. Any idea why this happens?

**Comment by voyager-gold** [comment]
Is nupkg file still required for auto update on Windows?
I found squirrel.windows, which is used for generating nupkg file, is [deprecated](https://www.electron.build/configuration/squirrel-windows#:~:text=Squirrel.Windows%20target%20is%20maintained%2C%20but%20deprecated.%20Please%20use%20nsis%20instead.) and can't see the latest update from its [repository](https://github.com/Squirrel/Squirrel.Windows).
On the other hand, I found squirrel.windows is still a solution to auto update an electron app on Windows.
https://www.electronjs.org/docs/latest/api/auto-updater#windows
What is the best way to implement auto update on windows?
@joshuapinter @scottrippey

**Comment by lockiechen** [comment]
how can i add query token when download the windows pkg
