### ISSUE TITLE
new Buffer cause the page disconnected and disappear

### ISSUE THREAD

**Issue by Moonshell** [electron/electron#5028]
* Electron version:3.7.4
* Operating system:Windows 7 (x64)

Hello, I just update electron from 3.6.9 to 3.7.4, and found that my app lose control when I try to parse a long string to buffer.
And I tested in the DevTools console, found that:
```javascript
new Buffer(new Array(1000).join(' '));    // normal
new Buffer(new Array(10000).join(' '));  // disconnected...
```

**Comment by Moonshell** [comment]
```javascript
new Buffer(new Array(4096).join(' '));    // less than 4K
new Buffer(new Array(4097).join(' '));    // 4K, disconnected
```

**Comment by feross** [comment]
I can also reproduce this. Electron 3.7.4. This did not happen on Electron 3.7.3.

**Comment by zcbenz** [comment]
I'm merging this to #5003.

**Comment by demogoran** [comment]
Got same bug today, when had try to send response over express(string is converted to buffer inside res.send). Error occurs, when you try to get Buffer from string with more that 4096 length.

Temporary fix you can use in your project is next one:

var encoder = new TextEncoder()
res.send(new Buffer(encoder.encode(LONG_LONG_STRING))); 

This could get array of characters codes to your buffer instead of string directly. 


Also it's seems to be electron-specific bug, node doesn't crash on it.
