### ISSUE TITLE
Window's minimum height isn't 0 on Windows

### ISSUE THREAD

**Issue by AnnGuden** [electron/electron#5053]
* Electron version: v0.36.7, v0.37.4
* Operating system: Windows 7, Windows 8

The window's height couldn't be set to the value less than 39px. I'm creating a window with the following options:
win = new BrowserWindow({
   width: 170,
   height: 30,
   frame: false,
   skipTaskbar: true
});
But the return values of win.getSize() are [170,39].
39 is the value of WINDOWS_WINDOW_TITLE_BAR_HEIGHT. 

Since the titleBarStyle option is only supported on OS X, how can I reduce the window's height to 30px on Windows?

**Comment by baconface** [comment]
I don't think you can. I believe Windows does this by design. Even [non Electron apps](https://github.com/MahApps/MahApps.Metro/issues/2066) will replicate this behavior. I would like to think a work around exists but I am unsure of one. The only thing I can find in the upstream is [this test](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/cocoa/browser_window_controller_unittest.mm&q=39px&sq=package:chromium&type=cs&l=490). Yet nothing actually causing this behavior.

**Comment by zcbenz** [comment]
Windows forces a size limitation when you create a new window, but you can change the window to arbitrary size after creating it with `setSize`.

**Comment by FushimiYuki** [comment]
> Windows forces a size limitation when you create a new window, but you can change the window to arbitrary size after creating it with `setSize`.

hi, I tried this but not work. Here's the code.
```typescript
let windowTray: BrowserWindow = null;

trayWindowSize = { width: 188, height: 35 }
windowTray.setContentSize(trayWindowSize.width, trayWindowSize.height);
console.log(windowTray.getSize());
```
I tried `setSize`, `setContentSize`, `setBounds`. But it print "188, 39" all the time.
