### ISSUE TITLE
Remote require a module from a dependency.

### ISSUE THREAD

**Issue by parro-it** [electron/electron#5090]
* Electron version: 0.37.5
* Operating system: OSX

I have an app with these dependency chain:

```
App ---depends--> A  ---depends--> B
```

I am writing module A, and I need to remote-require module B from it.
Using NPM3 the remote require works, but if I use NPM2, I get this error:

```
 Error: Cannot find module 'b'(…)(anonymous function)
```

I guess this is because NPM3 flats dependencies while NPM2 don't, and Electron is searching the dependency as a top level one.

This is particularly weird, because if that's not possible, I should impose to my library users to install library B by themselves.

[Here is a test repository](https://github.com/ewnd9/electron-remote-require-investigation) for the use case.

**Comment by bengotow** [comment]
Hi @parro-it — by `remote-require`, you mean saying `require('electron').remote.require....`?

When you require through the remote module, node no longer knows that `require` is being called from a path within your module, so `node_modules/A/node_modules` is no longer in the search path. I think you're correct that it works in NPM 3 because it happens to flatten everything into the top level node_modules directory. (Providing that no other node module in the project required the same file.)

I think there are a couple ways to fix this. You could require that the user of your node module add a few lines to their main process code to require B and put it on global scope. Then you could use it via `require('electron').remote.getGlobal('B')`.

You could also call require with the absolute path to load rather than the global module name. This is tricky because you'd have to find the module first, but might be something like: `require('electron').remote.require(path.join(__dirname,'..', 'node_modules', 'B'))`

**Comment by parro-it** [comment]
> Hi @parro-it — by remote-require, you mean saying require('electron').remote.require....?

Yes, exactly that.

> You could also call require with the absolute path to load rather than the global module name. This is > tricky because you'd have to find the module first, but might be something like:  require('electron').remote.require(path.join(__dirname,'..', 'node_modules', 'B'))

This could be automated using `require.resolve` in renderer. I think it could be useful if electron provides this solution automatically.

**Comment by zcbenz** [comment]
`remote.require` means calling `require` in the main process, so it will search for modules in the search paths of the main process. If we change this behavior unexpected things may happen, like `remote.require` returning different things from the `require` in the main process.

**Comment by parro-it** [comment]
Thank you @zcbenz. 
I'm not convinced this would be "unexpected", I think the actual implementation is a bit surprising (at least to me).

Anyway, this could be easy to solve within user code, by providing module full path as @bengotow suggested. 

One last question: where does the search paths of the main process starts from? It's the path of the first loaded module? Or the `package.json`? Or other one?

thank you
