### ISSUE TITLE
Question: Electron Origins

### ISSUE THREAD

**Issue by sevin7676** [electron/electron#5172]
A quick question to clarify an answer on [StackOverflow](http://stackoverflow.com/a/29966094/1571103):

Is Electron originally forked from NW.js, or is it just inspired by NW.js (if so, is it a fork of any existing repository) ?

**Comment by luigiplr** [comment]
If memory serves Electron was formally known as atom-shell, and built by the @github team for [Atom](https://atom.io/). Open sourced late 2013/Early 2014? & renamed in 2015. 
Whereas the NW.js project was open sourced around 2011.

As far as i recall Electron is not a fork of a pre-exsisting project.

**Comment by zcbenz** [comment]
Electron is not a fork of NW.js, it was rewritten from scratch. Electron was created because the architecture of NW.js was not suitable to construct GitHub's Atom editor, and rewriting everything is easier than forking.

Also I wouldn't see Electron is inspired by NW.js, because I wrote almost everything of NW.js 2.x and 3.x before the move to Electron, and it was basically the prototype of what NW.js is today.

**Comment by sevin7676** [comment]
thank you

**Comment by GnorTech** [comment]
As a co-maintainer of node-webkit and NW.js project, I can share the other side of story here:

Back in late 2012 or early 2013, the founding member @nathansobo of Atom project from Github contacted us to learn how we integrated Node into Chromium, at that time @zcbenz was an intern at Intel who is working on node-webkit  with @rogerwang. Shortly after that @zcbenz was hired by Github, left Intel and node-webkit project.

The code of what we've written for node-webkit project spans across multiple repositories, mostly in chromium repo, Node.js repo and the node-webkit repo. Only the last one is known by most people. Before @zcbenz  joined the project, the Node integration was done with CEF in the Chromium repo. What @zcbenz did for the project was mostly for the native GUI library according to [a (Chinese) interview of Roger](http://www.csdn.net/article/2014-01-08/2818066-Node-Webkit) . For the sake of easy implementation for the native GUI library, Cheng proposed and moved the code to Content layer, this part of code was a large part of the node-webkit repo.

At least atom-shell is a derivative work of node-webkit: the code was written following the same idea and steps, though in a tweaked way. Some lines of code are even identical, unique key components are very similar (see the bottom of this post). They changed the Node integration from 1 thread to a 2 threads model and referred to ours as "buggy": https://github.com/electron/electron/issues/4862#issuecomment-203760256

Thanks,
Kevin.

Identical lines in question:
https://github.com/nwjs/nw.js/blob/v0.3.7/src/api/bindings_common.cc#L39
https://github.com/electron/electron/blob/17cf6ffbd47e6744537ab6122dfd4bf23edd35bd/atom/renderer/api/atom_api_renderer_ipc.cc#L21

https://github.com/nwjs/nw.js/blob/v0.3.7/src/api/dispatcher.cc#L52
https://github.com/electron/electron/blob/17cf6ffbd47e6744537ab6122dfd4bf23edd35bd/atom/renderer/atom_render_view_observer.cc#L52

Unique key component for native GUI API binding:
https://github.com/nwjs/node/blob/nw0.8/src/nw/node_id_weak_map.cc
https://github.com/electron/electron/blob/cd93b9412c2620aa01ab5534a94620d9d01f2738/atom/common/id_weak_map.cc

**Comment by zcbenz** [comment]
I don't want to debate the authorship, git keeps history and you can easily track the source of every line.  All of identical lines and components you referenced were actually written by me, even though some author information in nw.js got lost in the rebase commit.

**Comment by paulcbetts** [comment]
Effectively the biggest difference afaik is that nw.js ends up working directly in Chromium's code far more often, which makes certain things easier, but also is a barrier to entry for contributors because they now have to download and clone all of nw.js, and every release of Chromium is now a huge amount of work because they're trying to merge upstream changes more

Electron on the other hand, tries as hard as possible to use Chromium as-is with minimal patches, which means you can build Electron w/o building Chromium which is good, but on the other hand, things that require libchromiumcontent changes are now much harder for Electron to accomplish than nw.js

**Comment by GnorTech** [comment]
@zcbenz it's not about the authorship. The copyright belongs to Intel and the copyright notice should be preserved when you copy code from one project to another and make derivative work. Regarding the misinformation in your blog post, here is the statement from node-webkit project creator: https://groups.google.com/d/msg/nwjs-general/LIrC7zHtQdo/6Gd5MXVsCAAJ

**Comment by GnorTech** [comment]
As this issue of copyright notice removal is still not handled and @zcbenz keeps practicing copyright infringement in the same way in other project (https://github.com/yue/help/issues/4), I just raised an issue in the BEIPA repo and called for attention from GitHub management.

**Comment by zcbenz** [comment]
Regarding the duplicate code between NW.js and Electron, most identical code were actually from Chromium instead of NW.js, for example the code referenced in the GitHub comment: `bindings_common.cc` and `dispatcher.cc`. Since both projects were using code from the same source, they end up having identical code for some parts.

However there is one component that I just copied from my old code in NW.js: `id_weak_map`,  for that component I had already deleted it in Electron and rewrote a new one from scratch, after @GnorTech pointed it out. The rewrote one is `atom_api_key_weak_map` in Electron.

So to clarify it, recent versions of Electron have no code copied or translated from NW.js, and I'm sorry my previous comment was inappropriate.
