### ISSUE TITLE
keyup event not firing on OS X when the Meta key is pressed

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5188]
* Electron version: `0.37.6`
* Operating system: OS X

Run the following code on any webpage

```js
window.addEventListener('keydown', (e) => console.log('down', e.key))
window.addEventListener('keyup', (e) => console.log('up', e.key))
```

Then perform a select all shortcut (Command + A) or any key with the `Command` key.  You will get a pattern like this.

```
down Meta
down a
up Meta
```

The `up` event for the a key is not fired.  This only occurs on OS X and when the meta (Command) key is down.

**Comment by DannyvanderJagt** [comment]
@MarshallOfSound I did a quick test on Chrome (v49.0.2623.112) and Safari (v9.0.3) on OS X (10.11.3) and it looks like it is default behaviour. I think it has something to do with the fact that the command key the primary key for shortcuts on OS X. If you want to use the combination (command + a, or any other combination with command) in your OS X app you should use electrons [globalShortcut](http://electron.atom.io/docs/v0.37.6/api/global-shortcut/).

I don't think electron should create a workaround because it looks like this is a browser standaard.

I hope it clarifies things :)

**Comment by zcbenz** [comment]
I agree with @DannyvanderJagt, this is a limitation of OS X that we can not work around.

**Comment by MarshallOfSound** [comment]
@zcbenz In that case (fair enough call), is there any way you could suggest to allow a user to input a hotkey combination?

**Comment by DannyvanderJagt** [comment]
@MarshallOfSound I did some research and I found the library [Mousetrap.js](https://github.com/mousetrap-js/mousetrap). With this library (with some modifications) you can record shortcut combinations (including Command + A). I quickly created a [pen](http://codepen.io/DannyvanderJagt/pen/BKVNGb/) which should be what you are looking for.

**Comment by MarshallOfSound** [comment]
@DannyvanderJagt Yeah, I've looked into mousetrap, the problem is that it is quite laggy (Performing the combination and receiving the callback is quite slow).  It might have to suffice though as a fallback for OS X
