### ISSUE TITLE
Can i change icon after launch app?

### ISSUE THREAD

**Issue by rgetValue** [electron/electron#5189]
Hello, i set icon app like this:
`var window = new BrowserWindow({icon: '/Users/somebody/images/window.png'});`
Can i change this icon, like this:
`setInterval(() => { window.icon = 'new_icon.ico' }, 3000)`

**Comment by DannyvanderJagt** [comment]
@rgetValue That won't work because it only changes the value in javascript. 

You should properly not change the icon because it can confuse your users. However I did a quick look around in the docs and I couldn't find an option to change the icon once the browserWindow is created. The only thing that you can use if you are developing for OS X is [`app.dock.setIcon(image)`](http://electron.atom.io/docs/v0.37.6/api/app/#appdockseticonimage-os-x). This will change the dock icon instead of the browserWindow icon.

**Comment by rgetValue** [comment]
@DannyvanderJagt thanx for your answer.
Ye, i think, it was bad idea to change icon when program started.

**Comment by DannyvanderJagt** [comment]
You are welcome :)

Can you close this issue if you think it is resolved.

**Comment by rgetValue** [comment]
close
