### ISSUE TITLE
Cancel window control events (beforeminimize, beforemaximize, etc)

### ISSUE THREAD

**Issue by cossacksman** [electron/electron#5201]
* Electron Version: 0.32.12
* Operation System: Windows 10, Arch Linux 4.4.5 (2016.04.01)

As a simple edit, in the methods you're using for maximize, minimize and close can we get an early event that is fired in-case we wish to cancel the window control event? I've come across the need to cancel the user being able to double click the titlebar (frameless window, custom titlebar) to maximize however (I believe) the `-webkit-user-select: none;` property means that the window.onclick event is not fired when interacting with this custom frame. 

I've currently had to resort to something a little ugly in my opinion as it bugs the window a little when used very fast: 
```
loginWindow.on('maximize', (event) => {
    loginWindow.unmaximize();
});
```

Apologies if this already exists, I've searched around but maybe I just didn't hit the right keywords, if so please disregard this.

**Comment by DannyvanderJagt** [comment]
@cossacksman You can disable/enable user based window controls for events like `maximize` with [`setMinimizable`](http://electron.atom.io/docs/v0.37.6/api/browser-window/#winsetminimizableminimizable-os-x-windows), [`setMaximizable`](http://electron.atom.io/docs/v0.37.6/api/browser-window/#winsetmaximizablemaximizable-os-x-windows), [`setClosable`](http://electron.atom.io/docs/v0.37.6/api/browser-window/#winsetclosableclosable-os-x-windows) and [`setFullScreenable`](http://electron.atom.io/docs/v0.37.6/api/browser-window/#winsetfullscreenablefullscreenable).

However you can't prevent `maximize` events that are fired programmatically. You should prevent this by improving your code or by creating a central piece of code who decides if you can `maximize` the current window. 

I don't know if by setting `setMaximizable` to `false` prevents the window from maximizing when you click the titlebar on Windows, because i'm on OSX, but you could try and I would like to know the result :)

I understand what you are trying to do with the `beforemaximize` events and i could see use cases where that would be helpfull (for example: 'are you sure you want to close this unsaved file?')

I would like to know what others are thinking about those events.

**Comment by zcbenz** [comment]
The `setXxxxable` methods are the right way to go.

However implementing events like `beforemaximize` are not possible on many platforms, it is a platform limitation that we can not work around in Electron.

**Comment by cossacksman** [comment]
That's fair enough and thanks for the input, the problem I had was that the setXxxxable methods are only for OSX and Windows; I never programmed my window to maximize on double click so I'm not sure where the root of that lays..

**Comment by DannyvanderJagt** [comment]
@cossacksman I not sure either why you custom title bar has that kind of behaviour. If you want to disable to clicking on that area completely you can try: `pointer-events: none;`

**Comment by cossacksman** [comment]
Sadly I can't just disable pointer events on the window decoration else users might get confused where else to drag their windows from; and I'm assuming that would affect children as well such as the window control buttons inside that element but thanks for the suggestion.

This topic does sound rather pedantic but for windows that most certainly should not be maximizable it is pretty tedious.. The reason I haven't just set whether the window can be maximizable for each window is because I only handle all windows with one channel from IPC:

```
ipc.on('maximize', () => {
    let focusedWindow = BrowserWindow.getFocusedWindow();

    if (focusedWindow.isMaximized()) {
        focusedWindow.unmaximize();
    } else {
        focusedWindow.maximize();
    }
});
```

Another solution might be to have the window store an empty object, which you can populate with custom properties? That would be easy to make checks when manipulating a window like this, and plenty of other things.
