### ISSUE TITLE
Using `fetch` API `referrer` option with different origin throws `TypeError`

### ISSUE THREAD

**Issue by preco21** [electron/electron#5234]
* Electron version: 0.37.6
* Operating system: Windows 10

Original issue by [kexu on slack](https://atomio.slack.com/archives/electron/p1461199600000440)

When I attempt to use built-in `fetch` API with different origin of `referrer` option, it throws `TypeError` like:

![image 003](https://cloud.githubusercontent.com/assets/4936201/14696700/4339c214-07b8-11e6-85a7-ce0ef8da575a.png)

Also, I disabled `webSecurity` and put other options to api options as long as I can:

`index.js`:
```javascript
...
new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    webSecurity: false
  }
});
```

`app.js`:
```javascript
...
fetch('http://google.com', {
  method: 'GET',
  referrer: 'http://qq.com/',
  referrerPolicy: 'unsafe-url',
  mode: 'no-cors'
}).then((response) => {
  console.log(response);
});
```

I expected it should work on Electron without any configurations.
Any ideas?

**Note:** But it just works if I strip the `referrer` option.

**Comment by zcbenz** [comment]
This is weird, I would expect `no-cors` to bypass the CORS checking for referrer. I suggest reporting this to Chromium's issues list instead, since it is likely a bug of blink.

I'm closing this since the rules of CORS are hard coded in blink, and we are not able to work around this on Electron's side.
