### ISSUE TITLE
Drag and Drop not working when application is ran as an Administrator in Windows

### ISSUE THREAD

**Issue by jviotti** [electron/electron#5243]
This is reproducible with the default application that's opened when running `electron`.

When running from a normal `cmd.exe`, drag and drop works as expected, however if I run `electron` from an administrator `cmd.exe`, drag and drop doesn't work and no error is logged.

***

* Electron version: 0.37.6
* Operating system: Windows 10 x64

**Comment by Acenth** [comment]
This is actually the expected behavior for Windows and you'll see it with basically all UI apps on Windows that are running as administrator. For example, try running Paint as admin and drag and image from Explorer into the app - nothing happens. Dragging same image with non-elevated Paint works.

It is probably best to not elevate your UI process and instead have a worker process that does the elevated tasks.

**Comment by zcbenz** [comment]
@Acenth Thanks for answering this! I'm closing now.

**Comment by moeinrahimi** [comment]
@Acenth can you give an example how to do that ?
