### ISSUE TITLE
Map Command to Control?

### ISSUE THREAD

**Issue by trusktr** [electron/electron#5261]
Is it possible to map all key presses of Command to Control? iTerm has an option for this, so I can press `cmd+c` instead of `ctrl+c`, for example.

Here's what it looks like in iTerm, where I've mapped Left Command to Control:

![screen shot 2016-04-22 at 3 27 03 pm](https://cloud.githubusercontent.com/assets/297678/14756516/b8c5564c-089e-11e6-925d-05e2bd3360b6.png)

**Comment by bengotow** [comment]
I think Electron's menu API is the only one that interprets modifier keys, and most apps (like Atom, et.) build on top of it significantly to implement their own keybinding and menu management. I imagine this is something best done in the application layer, rather than as an option in Electron itself?

**Comment by zeke** [comment]
Related: https://github.com/zeke/electron-shortcut-normalizer

**Comment by trusktr** [comment]
Interesting to note that when I've turned Command into Control in iTerm, all the Command shortcuts in the app menu stop working, as the Command key now sends Control. This is what I'd like to have in Electron.

**Comment by zcbenz** [comment]
You write a function to convert the accelerators before creating the menu, like `app.setApplicationMenu(YourHookConvertsCommandToControl(menu))`.
