### ISSUE TITLE
How to disable gpu other than command line argument?

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#5297]
* Electron version: 0.37.7
* Operating system: Linux

I would like to be able to disable the gpu in my application code, not by having to pass an argument to electron.

I tried using both of these and neither work.

```javascript
app.commandLine.appendSwitch("disable-gpu")
app.commandLine.appendArgument("disable-gpu")
```

Is there any other way to disable-gpu instead of passing this argument directly as `electron ./my-project --disable-gpu` ?

**Comment by MarshallOfSound** [comment]
I am interested in this aswell.  For some reason this flag is required when accessing the Google Sign In page in a webview on linux.  (Strange use case but something breaks without this flag)

**Comment by zcbenz** [comment]
It seems that `app.commandLine.appendSwitch("disable-cpu")` stopped working recently, probably because Chrome started to detect the switch earlier than we run JavaScript.

We can probably add a `app.disableHardwareAcceleration()` API for this.

Refs:
https://code.google.com/p/chromium/codesearch#chromium/src/content/public/browser/gpu_data_manager.h&sq=package:chromium&type=cs

**Comment by brian-mann** [comment]
How is this coming along? Anything I can do on my end?

**Comment by paulcbetts** [comment]
@brian-mann Looks pretty straightforward, submit a PR!

**Comment by brian-mann** [comment]
@paulcbetts I looked into this but do not possess the knowledge to extend Electron's interface to attach to this method. I could probably figure it out but am struggling. :-(

**Comment by brian-mann** [comment]
@zcbenz Any guidance would be helpful unless you want to knock this one out yourself :P
