### ISSUE TITLE
When served over a custom protocol, only protocol absolute urls trigger a download when parsed

### ISSUE THREAD

**Issue by retrohacker** [electron/electron#5303]
* Electron version: all
* Operating system: all

When an HTML document is served over a custom protocol, only url's starting with a protocol will trigger a request for an asset.

I.E. the following triggers a request

```html
<img src='peer://foo/bar/buzz/bazz.png'>
```

While the following do not

```html
<img src='/bar/buzz/bazz.png'>
<img src='./bar/buzz/bazz.png'>
<img src='//bar/buzz/bazz.png'>
```

This effectively breaks serving websites over custom protocols.

I created a set of unit tests that demonstrate this here: https://github.com/retrohacker/electron/blob/protocol_request/spec/api-protocol-spec.js#L108-L194

**Comment by deepak1556** [comment]
Registering the scheme as standard should fix this. `protocol.registerStandardSchemes` doesnt work (confirmed on linux),because  the initialisation happens at a early stage. For now users can pass the flag on commandline `app.exe --register-standard-schemes="app,test"`, any idea on how to fix this @zcbenz ?

**Comment by zcbenz** [comment]
I think the only option left for us is to patch Chromium to allow adding scheme as standard scheme after `url::LockSchemeRegistries` gets called, and then let users call `protocol.registerStandardSchemes` before the `ready` event.
