### ISSUE TITLE
web view doesn't inherit zoom level

### ISSUE THREAD

**Issue by jrieken** [electron/electron#5312]
* Electron version: 0.37.6
* Operating system: OS X, 10.11.4

A web view seems to not catch up with the zoom level when created, steps:

* run electron app
* use the [BrowerWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) api to set the zoom level to 2
* create a web view
* ⚡ It is not zoomed
* Change browser window zoom level and web view recovers

**Comment by vwvww** [comment]
Is it right that you use the BrowserWindow api to set zoomFactor to 2 in order to set the webview's zoom level to 2? I'm newbie on electron but there is no zoomLevel related api in BrowserWindow api document...

Maybe we can insert a code: when a web view is initialized, check the BrowserWindow's zoomFactor and set the web view's zoomLevel to inherit zoomFactor.

**Comment by vwvww** [comment]
1. It was not right that BrowserWindow api only handles zoomFactor. It also handles zoomLevel.
2. I tried to modify WebViewImpl to inherit zoomLevel from webFrame, but webFrame's zoomLevel was set to 0, not inheriting zoomLevel from BrowserWindow.
