### ISSUE TITLE
Videos not playing in headless mode?

### ISSUE THREAD

**Issue by digitalnature** [electron/electron#5317]
By "headless" I mean running with `xvfb` or `xdummy`.
How do I know they are not playing if electron is running under a virtual display? I'm taking screenshots 
using `capturePage` and the video doesn't show up :)
It does show up if I use the Windows distribution with the GUI.
 
I thought it's because xvfb doesn't support opengl but then I installed xdummy and virtualgl and video still doesn't show up.

Is there any specific requirement by electron to make the videos play on a virtual display as well?

* Electron version: 0.37.7
* Operating system: Ubuntu 14.04.4 LTS

**Comment by zcbenz** [comment]
Hmm I can not see why it doesn't work with xvfb. Electron just uses Chromium for displaying the page and playing the video, so I suggest reporting this in [Chromium's issues list](https://bugs.chromium.org/p/chromium/issues/list) instead, the Chrome team should have a better view of this. I'm closing this since we are not able to solve this on ELectron's side.
