### ISSUE TITLE
Additional instance starts in wrong virtual desktop

### ISSUE THREAD

**Issue by rojepp** [electron/electron#5326]
* Electron version: Whatever comes with Atom 1.7.2 and VSCode 1.0
* Operating system: Windows 7

I'm using desktops.exe from SysInternals to add virtual desktops to Windows 7.
When having an open instance of code in a not active desktop, starting an additional instance will not start on the currently active desktop.

Steps to Reproduce:

Open VSCode in desktop 1
Switch to desktop 2
Start another VSCode instance: code .. The new instance starts in desktop 1

Bug originally reported here https://github.com/Microsoft/vscode/issues/5876 and marked upstream

**Comment by MarshallOfSound** [comment]
@rojepp This kind of thing is probably a bug / lacking feature in SysInternals implementation of the virtual desktop environment.  I don't think it is up to electron to (not sure they even can) handle a 3rd party application such as this.

Just out of interest though, if you open a chrome browser and move it to the second virtual desktop, what happens when you open a new window, where does it go?

**Comment by paulcbetts** [comment]
I don't think this is worth fixing, you should move to Windows 10 where virtual desktops are built-in

**Comment by rojepp** [comment]
@MarshallOfSound Most applications seem to work without any special support for it. I can't try Chrome in that env right now as I am not at work. @paulcbetts Windows 7 here is a work constraint, as I am sure it is for many people. I tend to agree though, it's not worth a huge effort.
