### ISSUE TITLE
Remote methods with callbacks fail when the window reloads

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5344]
* Electron version: `0.37.8`
* Operating system: Windows

If you use the `remote.getGlobal()` method to assign a callback, the callback fails with an error if the BrowserWindow has been reloaded or destroyed.  This shouldn't cause an error rather silently fail or better yet unhook the callback.

**Comment by zcbenz** [comment]
This behavior has been documented in the remote module:
http://electron.atom.io/docs/v0.37.8/api/remote/#passing-callbacks-to-the-main-process

For unhooking the callback automatically, it is basically impossible to implement since we can never how the callback is going to be used, for example a simple case like: `win.on('event', => remoteCallback)`.

And I don't think failing silently is an acceptable solution, it is just ignoring the problem.

**Comment by MarshallOfSound** [comment]
I was aware the behaviour was documented I just don't believe the behaviour is correct or expected.  As an example there are always two ways of callbacks in the main process triggering actions in the renderer process.

1. From the renderer process
```js
remote.getGlobal('Thing').on('action' () => {
    // Do magic
});
```

2.  From the main process
```js
Thing.on('action', () => {
    mainWindow.webContents.send('action-happened')
});
```

The first one is broken by reloading the window.  The second one is not.  Can this be reopened to address that issue, I.E. the callback handling logic should attach itself to the BrowserWjndow and at call time fetch webContents.  Not at hook time.

Sorry if this isn't clear, typed it up on my phone

**Comment by zcbenz** [comment]
Using your code as example, I think the biggest trouble is how to handle `action-happened` in renderer process, since page is reloaded the original function is gone forever, how is it possible to figure out which function in the new page to be called?

**Comment by MarshallOfSound** [comment]
@zcbenz Hmm, I see your point.  In the second example on reload you would have defined a new `ipcRenderer` listener for `action-happened` so the code would work as expected.

However by that logic in the first example you would have also called the `remote` listener code again.  So you will have one call that will succeed and the old one which will fail.

Could we simply check if the target `webContents` is destroyed or not before attempting to call a callback on it.  I can't come up with a viable reason to even try call a method on a destroyed webContents and based on these two example that solution would fix the issue and remove the need for a whole load of

```js
window.onbeforeunload = () => {
    remote.getGlobal('Thing').unbind(...);
    remote.getGlobal('Thing').unbind(...);
    remote.getGlobal('Thing').unbind(...);
};
```

**Comment by zcbenz** [comment]
`EventEmitter.on` is not the only case that would involve remote callbacks, for other examples like `dialog .showMessageBox`, `win.capturePage`, `webRequest.beforeRequest` or when you pass `Promise`s, it is impossible to just uninstall the listeners.

It is possible to just not call the callback when the page is gone, but I don't think we should do that, otherwise every time you reload the page you will leave a bunch of zombie callbacks in the main process which never get cleaned up.
