### ISSUE TITLE
`app.getLocale()` inconsistent with chromium documented supported locales

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5363]
* Electron version: `0.37.8`
* Operating system: Windows

When calling `app.getLocale()` I get the value `"en-GB"`.  Although this is technically correct, chromiums [list of locales](https://developer.chrome.com/webstore/i18n#localeTable) indicates it should be `en_GB`.

This breaks certain locale and translation packages that I was looking at using, although the fix on my end was a simple `.replace('-', '_')` I'm wondering why the inconstency with chromium API when as far as I can tell from the [relevant code](https://github.com/electron/electron/blob/d9db23185cba1bc7cedc3b73a56af3093812a726/atom/browser/api/atom_api_app.cc#L375) we are only calling chromium's built in locale lookup?

**Comment by zcbenz** [comment]
The locale returned by `app.getLocale` is actually the one used by Chromium internally, which has the same format with `NavigatorLanguage.language`. I don't know why Chromium chose a different format for its `i18n` API.

I think we should make this explicit in documents, changing the behavior may not be a good idea since it will break apps that rely on `app.getLocale`.

**Comment by MarshallOfSound** [comment]
@zcbenz Would your preferred solution to this be to simply document all the possible values of `app.getLocale()` in the `docs` folder and explain the difference between it and the chrome API?

**Comment by zcbenz** [comment]
@MarshallOfSound Yeah, that would be perfect.
