### ISSUE TITLE
Crashes Skype when started during screen share

### ISSUE THREAD

**Issue by rdickert** [electron/electron#5376]
* Electron version: 0.36.7
* Operating system: osx 10.11.4
* Skype version: 7.21 (350)

Trying to demo something for a client, I found that Skype would crash every time I started my Electron app if I was sharing my screen (thunderbolt monitor with no other screens). I checked Atom, and this happens with Atom as well, so it's not specific to my app. No effect if you are not sharing your screen.

**Comment by MarshallOfSound** [comment]
@rdickert I can't replicate this crash.  I have tried numerous Electron based applications while sharing my screen on Skype and none cause any noticeable errors or crashes.

**Comment by baconface** [comment]
This isn't an Electron issue. It is a [Skype issue](https://community.skype.com/t5/Modern-on-Windows-RT/Screen-sharing-causes-Skype-to-crash/td-p/3940019). Additionally if this is the case then it would be regression since [Skype has tried to patch this in the past](https://community.skype.com/t5/Mac-archive/Skype-7-6-Repeated-Crashing-on-Screen-Share/td-p/3906113).

**Comment by rdickert** [comment]
@baconface Thanks for the link to the Skype issue.
