### ISSUE TITLE
Document fs.statSyncNoException and fs.lstatSyncNoException

### ISSUE THREAD

**Issue by mnquintana** [electron/electron#5433]
* Electron version: 0.37.8
* Operating system: N/A

After some investigation, I found that Electron patches in `statSyncNoException` and `lstatSyncNoException` to the built-in `fs` module, which we use quite extensively, but both methods are currently totally undocumented. It would be great if we could document these. 😄  📝

**Comment by zcbenz** [comment]
They should not be documented, and we should not encourage people to rely on our Node patches, we will eventually remove all patches in our Node fork. If people really wants to use `stat` without exceptions, they can use `process.binding('fs').internalModuleStat` instead, which is available in recent versions of Node.

They are still there because we haven't replaced the usages in Atom yet.

**Comment by mnquintana** [comment]
Ah thanks for the clarification @zcbenz! I'll close this out then and get to work removing our usage of these methods 😄
