### ISSUE TITLE
Add `acceleratorLabel` option to `MenuItem`

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5448]
The native accelerator has many limitations: https://github.com/electron/electron/issues/5398 https://github.com/electron/electron/issues/5256. Sometimes you just need to use DOM keyboard events instead. The downside with using DOM keyboard events is that the keyboard shortcut is not shown in the menu item. I propose adding a `acceleratorLabel` option, where you can write anything and it's shown as an accelerator in the menu item.

This might not be the best solution, but the problem is valid, so if there's a better solution I'm not seeing, please comment.

http://electron.atom.io/docs/v0.37.8/api/menu-item/#new-menuitemoptions

-

* Electron version: 0.37.8
* Operating system: OS X 10.11.4

**Comment by zcbenz** [comment]
This is a very good idea, the only problem is it is too hard to implement, especially on OS X. To implement this there are three major tasks:

1. Extend our native and JavaScript menu model code to accept `acceleratorLabel`;
2. Patch Chromium's menu implementation to allow drawing custom accelerator on Linux and Windows;
3. Rewrite the menu implementation on OS X to draw custom menu items.

The (3) is particularly hard to implement since we have to rewrite the drawing code of the menu item from scratch and follow system's default behavior precisely.

So I'm closing this issue as won't fix, because considering the difficulty of it, I don't think it worths the efforts. However if anyone wants to challenge this, pull requests are welcomed.

**Comment by sindresorhus** [comment]
That's fair. Thanks for explaining :)
