### ISSUE TITLE
electron.exe.pdb not found on symbols server

### ISSUE THREAD

**Issue by bennyn** [electron/electron#5456]
* Electron version: 0.37.2
* Operating system: Win 10 Home

I read "[Using the symbol server in Visual Studio](https://github.com/electron/electron/blob/master/docs/development/setting-up-symbol-server.md#using-the-symbol-server-in-visual-studio)" and tried to setup the symbols Server in VS 2015 (Community Edition) but unfortunately my VS cannot find the symbols for my app (built on Electron v0.37.2).

**Screenshot:**

![screenshot](https://cloud.githubusercontent.com/assets/469989/15115509/914ecc88-15ff-11e6-865c-4e0e1b469005.PNG)

Is there anything I did wrong?

**Comment by felicienfrancois** [comment]
I also ran into this issue. This is probably because the exe version have been altered (`2.06.0.0`) and as a result VS fail in finding the corresponding pdb.

I managed to open a crash report with source using [windbg](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063%28v=vs.85%29.aspx) and following instructions from [this comment](https://github.com/electron/electron/issues/3208#issuecomment-150979822) but it remains tricky.

You have to checkout and [build electron](https://github.com/electron/electron/blob/master/docs/development/build-instructions-windows.md) in Release mode with the same arch.
Then open the crash dump in WinDbg
And finally type this in windbg command
```
.symfix
.symopt+ 0x40
.sympath+ C:\Path\to\electron\out\R
!analyze -v
```

Then good luck to extract any understandable information from the stack and memory dump :S.

There is also a [debug instructions doc](https://github.com/electron/electron/blob/master/docs/development/debug-instructions-windows.md) but I'm not sure it solves your issue.

**Comment by felicienfrancois** [comment]
Also, I'm not sure the symbol server address is still valid.
@zcbenz Is the symbol server url still `http://54.249.141.255:8086/atom-shell/symbols`?

I'm getting error electron.exe.pdb not found (HTTP_STATUS_NOT_FOUND) even with untouched binary.

**Comment by zcbenz** [comment]
The ability to upload symbols had been broken for sometime, the symbols server will serve symbols from next release.
