### ISSUE TITLE
'OK' button showed when 'buttons' array is empty in 'showMessageBox' on Windows

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5464]
...when an empty array is passed to the `buttons` option.

<img width="378" alt="screen shot 2016-05-10 at 18 05 56" src="https://cloud.githubusercontent.com/assets/170270/15144486/e6af8b2e-16d9-11e6-8240-65a1481bf9a0.png">

I'm trying to use the box to just show some info. The user can already click away the box using the top-right `X`, so no point in having an OK button there.

Can be reproduced with:

```js
const electron = require('electron');

electron.app.on('ready', () => {
	electron.dialog.showMessageBox({
		title: 'foo',
		buttons: []
	});
});
```

-

* Electron version: 0.37.8
* Operating system: Windows 10

**Comment by zcbenz** [comment]
This is unfortunately the behavior of the native `TaskDialogIndirect` API, I don't see any way to work around this. We should definitely document it though.

**Comment by OlsonDev** [comment]
What about this... show the `OK` button, don't show the `X`? That seems more user friendly to me: `OK` is focused by default (and thus can be dismissed with spacebar), `OK` means "I accept this information" instead of "Get this information out of here", and it's a bigger click target for mouse users. Seems like you can do it by following [this StackOverflow answer](http://stackoverflow.com/a/13191205).

**Comment by felixrieseberg** [comment]
While I agree with you, I'm not sure that it's in line with how other apps on Windows operate - most of Microsof's apps would have both the X and the OK button, as an example.

@zcbenz can make the call here - if he wants me to add an option to exclude the X, I can do that.

**Comment by sindresorhus** [comment]
@felixrieseberg I agree. Better to follow the convention.

**Comment by zcbenz** [comment]
@felixrieseberg I'm good merging it if someone created a pull request, but I don't like it.
