### ISSUE TITLE
Improving 'Sources' Tab Navigation In DevTools

### ISSUE THREAD

**Issue by francoislaberge** [electron/electron#5492]
* Electron version:
Any version I've tried about 0.29.0
* Operating system:
Observed on Windows/OSX

Often when trying to debug electron apps I've made much of our source files end up in the extremely long list of files under the `(nodomain)` group in the devtools, this includes everything in node_modules as well as our code but flattened into an extremely long list. This makes for a terrible debugging experience hunting and pecking finding the file you want to put a breakpoint in. Most of our team just injects `debugger` keywords to find the file they are interested in via their own IDEs.

**See example of the non ideal behavior:**
![worse](https://cloud.githubusercontent.com/assets/1845/15177187/dce7ba36-173c-11e6-8ba0-538b50a0562f.png)

**I've noticed sometimes things don't behave as badly. Like in Atom it is more elegant. I'm not sure if it's because Atom maybe copies package folders into somewhere closer to it's electron exe, versus our electron based robot simulator where we use an electron-prebuilt instance in a cli to load an arbitrary electron app elsewhere. Sometimes sourcemaps help as well as in this projects results:**
![better](https://cloud.githubusercontent.com/assets/1845/15177178/d44ce018-173c-11e6-9899-1c7207f5361a.png)

Any ideas on how exactly this works?

**Comment by francoislaberge** [comment]
On further exploration it looks like when any file is includes using a relative path in the entry point .html file it gets put into the `no domain` tab with the whole other pile of files.

**Comment by zcbenz** [comment]
Unfortunately this is not something we can fix, the names you saw in Sources panel are decided by how they are loaded. For modules that loaded from filesystem, they will be put under `(no domain)`, and the names showed there are their absolute paths. For Node's built-in modules, their filenames will show because they are loaded from memory instead of filesystem. We can't change because that's how Node's module system works.

Some files of Atom are showed in `file://` because those files are loaded with script tag instead of `require`, and devtools does a good job categorizing them.

The only possible way to make things better, is to make devtools recognize file paths in the Sources panel.

**Comment by francoislaberge** [comment]
Thanks Cheng!
