### ISSUE TITLE
Error appears when prune=true

### ISSUE THREAD

**Issue by bebensiganteng** [electron/electron#5547]
* Electron version: 0.37.8
* Operating system: MacOS 10.11.4

Hi,

Still a beginner here, I'm using the electron-compile to build the app, but when I set prune=true, this error appeared.

![screen shot 2016-05-16 at 16 50 00](https://cloud.githubusercontent.com/assets/188012/15283935/10434ca6-1b89-11e6-9909-711565f2da1a.png)

```
var packager  = require('electron-packager');
var config       = require('./package.json');

packager({

  dir: './',
  out: './dist',
  name: 'sample',
  platform: 'darwin,win32',
  arch: 'all',        
  version: '0.37.8',  
  overwrite: true,  
  asar: true,       
  prune: true,   
  ignore: "node_modules/(electron-packager|electron-prebuilt|\.bin)|release\.js",

}, function done (err, appPath) {

  if(err) {
    throw new Error(err);
  }
});
```

Thank you.

**Comment by paulcbetts** [comment]
So, the by-far easiest way to do this is to use the electron-packager wrapper that ships with electron-compile to package your app. You're getting this error because you haven't precompiled your app in production - https://github.com/electron/electron-compile#how-can-i-precompile-my-code-for-release-time for more details.

Also, please file electron-compile bugs over at https://github.com/electron/electron-compile (nbd on this one though!)

**Comment by zcbenz** [comment]
Closing since it is not an issue of Electron.
