### ISSUE TITLE
Force Touch

### ISSUE THREAD

**Issue by Bouzmine** [electron/electron#5570]
I'd like Electron to support Force Touch mainly for what is described here : atom/atom#11776.

API should have function to receive Force Click/levels of pressure and to send Force Feedback.

**Comment by zcbenz** [comment]
This is currently tracked in upstream Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=568727

We can not easily just add an API in Electron, because the force touch needs to interactive with DOM events, and it would need work on both Chromium and blink, and probably need time to work out a spec. I'm closing this since we are not able to solve this on Electron's side.
