### ISSUE TITLE
Change of `titleBarStyle` behaviors is unreasonable

### ISSUE THREAD

**Issue by geeeeeeeeek** [electron/electron#5660]
* Electron version: v1.1.1
* Operating system: OS X

In previous versions, if title bar style was set to `hidden-inset`, we could drag the top of window to move that. However in v1.1.1, the top of window is no longer draggable (#5557).

The previous behaviour has been used for a long time. And I think a sudden change of implementation is not a good thing. At least you should provide an option like `draggable` for that. Considering the scenario of using `hidden-inset`, developers are usually intended to create their custom title bar. If it's not draggable, it would be very inconvenient to implement one of our own.

Besides, the behavior of `hidden` is also changed. Previously, there were no traffic lights. And that's what I understand the meaning of `hidden`. But now traffic lights turn up even if it's set to hidden.

Present:
![image](https://cloud.githubusercontent.com/assets/7262715/15478254/fb315cc2-214b-11e6-9a1f-691adc328a94.png)

Previous:
![image](https://cloud.githubusercontent.com/assets/7262715/15478276/1e10226e-214c-11e6-869c-6bafec9b4ced.png)

**Comment by danhp** [comment]
The previous version of `hidden-inset` had undesired side effects so it needed to be changed. To get the drag feature back, you can refer to https://github.com/electron/electron/blob/master/docs/api/frameless-window.md

**Comment by geeeeeeeeek** [comment]
@danhp Well, that's really hacky. My app is a third-party client loading content from where I can not control. `draggable-region` would be a nice workaround. But I still think the previous behaviour is more natural. 

@zcbenz And what's wrong with `hidden`?

**Comment by danhp** [comment]
@geeeeeeeeek Nor sure why you see this as hacky... you can easily implement this for third party clients.  See our patch [here](https://github.com/sindresorhus/anatine/commit/67c418426e6b4de562c2c540a2e529ad54f9762d).

**Comment by geeeeeeeeek** [comment]
@danhp By hacky I mean I need to inject css for some certain elements. That's not the problem. In my app, there is no such an element that can be directly mapped into the title bar. And I just want to drap the top region to move. So what am I supposed to do? In old veraions, it just worked.

You can find the snapshot of my app here:
https://github.com/geeeeeeeeek/electronic-wechat/blob/master/README.md

**Comment by danhp** [comment]
That's the nature of being a third party client... everything is kind of a patch work.

**Comment by zcbenz** [comment]
You probably misunderstood the purpose of `titleBarStyle `, this flag is used to hide the titlebar but keep traffic lights. It was [a bug](https://github.com/electron/electron/issues/3009) that the top of the window can be draggable when using `titleBarStyle`, it was never meant to be expected behavior. You can see it from all past complaints.

The reason we should keep current behavior is, this makes it possible to implement a window that has other elements in the titlebar, like Safari:

![screen shot 2016-05-24 at 10 54 53 am](https://cloud.githubusercontent.com/assets/639601/15489822/fd588974-219d-11e6-8573-865420b074b5.png)

Having the top of window always draggable makes it impossible.

> Besides, the behavior of hidden is also changed. Previously, there were no traffic lights. And that's what I understand the meaning of hidden. But now traffic lights turn up even if it's set to hidden.

You probably encountered a bug, `hidden` doesn't mean to hide the traffic lights, the difference between `hidden` and `hidden-inset` is the position of traffic lights.

For hiding the titlebar and traffic lights completely, the correct way is to use `frame: false` and do no set `titleBarStyle`.

**Comment by geeeeeeeeek** [comment]
@zcbenz Sorry, I was wrong about `hidden`.

```javascript
    this.splashWindow = new BrowserWindow({
      width: Common.WINDOW_SIZE_LOADING.width,
      height: Common.WINDOW_SIZE_LOADING.height,
      title: Common.ELECTRONIC_WECHAT,
      resizable: false,
      center: true,
      show: true,
      frame: false,
      autoHideMenuBar: true,
      alwaysOnTop: true,
      icon: 'assets/icon.png',
      titleBarStyle: 'hidden'
    });
```

I've set it to be frameless but got the snapshots in my original post. This change appears after upgrading from 1.1.0 to 1.1.1.

And thanks for your nice reply.

**Comment by zcbenz** [comment]
@geeeeeeeeek Removing `titleBarStyle` should work for you, `frame` and `titleBarStyle` should not be used together.
