### ISSUE TITLE
Electron 1.1.2 uses wrong icon size in windows bar

### ISSUE THREAD

**Issue by leshow** [electron/electron#5741]
* Electron version: 1.1.2 arch=ia32
* Operating system: Windows 7x64

Electron is using the largest icon available in the .ico file for the windows bar.  I set the icon in my main window with `createWindow('main', { ...icon: icon_path })`

You can reproduce this with an icon that displays the size: (click 'test icon with several images' to download)
https://bugzilla.gnome.org/show_bug.cgi?id=551026

here is a screenshot of the wrong icon being used (should be 32x icon):

![wrong-icon](https://cloud.githubusercontent.com/assets/1128302/15620020/cce93d12-2425-11e6-8af4-ce6330aed1c9.png)

**Comment by danhp** [comment]
I'm not sure I see the real problem here... The icon is sized correctly.

**Comment by OlsonDev** [comment]
I believe OP is saying it's selecting the wrong icon from a `.ico` file. Many times designers will bundle subtly different images into a `.ico` because they know details will be lost/mangled when downsized. For example, here are **some** of the images contained in *GitHub for Desktop*'s `.ico` file:

![app-0](https://cloud.githubusercontent.com/assets/308072/15622526/2deebffc-242f-11e6-8ca6-9a2cc24bcf17.png)

![app-3](https://cloud.githubusercontent.com/assets/308072/15622530/33d196ce-242f-11e6-9b7c-b27ae64236d5.png)

![app-4](https://cloud.githubusercontent.com/assets/308072/15622532/3663f1b6-242f-11e6-960e-7cb1af57d729.png)

Note how the last one drops details because they just won't look good at that resolution.

**Comment by danhp** [comment]
Ahhh that makes it much clearer.

**Comment by leshow** [comment]
Correct, it appears to just be selecting the largest icon in the bundle. We have different icons for different sizes.

**Comment by zcbenz** [comment]
I think it is correct behavior to choose the largest icon for the taskbar? Otherwise the icon would be blurred.

**Comment by OlsonDev** [comment]
@zcbenz I don't think it's correct behavior at all. See my comment above. Ideally Windows is given the properly sized icon and doesn't have to do any resizing itself.

**Comment by zcbenz** [comment]
Yeah you are right, after some testings with Windows, it seems that Windows would choose icon with size of `SM_CXICON` by default for task bars.
