### ISSUE TITLE
GPU/CPU usage is unexpectedly high when playing video in a hidden window until the window is shown and then hidden again

### ISSUE THREAD

**Issue by chrisyuska** [electron/electron#5831]
* Electron version: 1.2.1
* Operating system: Ubuntu 14.04

GPU (or CPU if using embedded graphics) usage for initially hidden windows is identical to visible windows, when one would expect it to be lower since nothing needs to be rendered.  Cycling  `show()` and `hide()` causes it to drop to a normal amount though. e.g:

```node
win = new BrowserWindow({
  show: false,
});
// GPU usage: 25% (identical to visible window even though window is hidden)

win.show();
// GPU usage: 25%

win.hide();
// GPU usage: 0%
```

I've created a demo app with more information and step-by-step directions for reproducing the issue here: https://github.com/chrisyuska/electron-video-gpu-cpu-bug-demo

**Comment by zcbenz** [comment]
We would like to have this fixed, but this problem is essentially a bug of Chromium's GPU acceleration, and we are not able to fix it on Electron's side, so I'm closing this as won't fix. I suggest reporting this to Chromium's issues list instead, the Chromium developers would have a much better idea of this issue.
