### ISSUE TITLE
bundle v8 that is compatible with bundled node

### ISSUE THREAD

**Issue by juliangruber** [electron/electron#5851]
This is `process.versions` in electron 1.2.0:

``` json
{
  "http_parser": "2.7.0",
  "node": "6.1.0",
  "v8": "5.1.281.47",
  "uv": "1.9.0",
  "zlib": "1.2.8",
  "ares": "1.10.1-DEV",
  "modules": "48",
  "openssl": "1.0.2h",
  "electron": "1.2.0",
  "atom-shell": "1.2.0",
  "chrome": "51.0.2704.63"
}
```

v8 5.1 is _not_ abi compatible with 5.0, which node 6 ships with. So, `.modules=48` is incorrect. The way to fix this (I guess) would be to bundle a chrome version that comes with v8 that is compatible with the bundled node version.

See https://github.com/nodejs/nan/issues/578 for answers from node, nan and v8 maintainers.

**Comment by zcbenz** [comment]
We usually use the same version of `NODE_MODULE_VERSION` with Node, so NAN can work with Electron without modifications. But there hasn't been a Node release with V8 5.1, and NAN has not been prepared for V8 5.1, it is then not safe for us to change `NODE_MODULE_VERSION` on our side.

I think the only thing we can do is to wait for Node to release a new version that uses V8 5.1.

**Comment by juliangruber** [comment]
What about reverting the v8 upgrade then? The problem with the current situation that I and others like @0x00A are facing is that native modules that do work with node, don't work with electron.

It's not a big deal for me personally to just use electron 1.1.3, but from that point of view you could consider 1.2.0 to be "broken".

**Comment by paulcbetts** [comment]
@juliangruber Did you rebuild them?

**Comment by juliangruber** [comment]
@paulatbipsync yes, same results as with the prebuilt binaries

**Comment by paulcbetts** [comment]
That's surprising, are you sure that your package isn't doing some kind of node-pre-gyp stuff where it's no-op'ing the build?

**Comment by juliangruber** [comment]
(And yes, I manually rebuilt and changed stuff around to verify it's not a problem with prebuilts)

**Comment by paulcbetts** [comment]
Sure, but ABI doesn't matter if you're building from source

**Comment by mgol** [comment]
V8 5.1 is interesting in that it has only ABI breakages from 5.0 and it seems the Node team plans to apply an API compatibililty layer and merge V8 5.1 to Node 6.

What's the Electron plan to deal with this compatibility layer? NAN will most likely assume the layer is present as Node.js 6 will have it.

**Comment by paulcbetts** [comment]
I feel as if some people on this thread are misusing ABI vs API breaking? Does everyone understand what an ABI-but-not-API breaking change is?

Like, this change breaks ABI but _not_ API:

```c
// In v1.0.0
struct Foo {
   int bar;
   char[25] baz;
};

// In v1.0.1
struct Foo {
   char[32] baz;
   int bar;
};

// In v1.0.0 this located at +0 from the beginning of the struct, in v1.0.1 this is at +0x20
// Compiling this code from source works in both v1.0.0 and v1.0.1, it is not an API break
// but it _is_ an ABI break.
myFoo->bar = 5;

**Comment by kkoopa** [comment]
Being a header-only library, NAN itself does not care about the ABI. As far as I know, there have been no significant API breakage in V8 5.1 either. Moreover, if NAN did not work, it would almost surely refuse to compile. Thus, NAN is almost surely compatible with V8 5.1. However, none of this applies when using prebuilt binaries of incompatible ABIs.

I am fairly certain that the problem here is ABI related and that the alleged rebuild does not properly build against the V8 version included in Electron, which for all I know could still be different from what is picked up by node-gyp operating on the bundled Node, which does not seem to use its bundled V8 under Electron. That the observed problem could not be reproduced on Windows, which does not support prebuild, points towards this.

There is no apparent reason why `Nan::Null`, which does nothing but forward to `v8::Null` would evaluate to `true`. It simply makes no sense, unless there is an ABI incompatibility. One possibility is that the attempts to rebuild the Node addon were built against the V8 version bundled in the bundled Node, which is not what Electron uses. It could also have been built against some other V8 version on the local file system. Who knows.

**Comment by juliangruber** [comment]
@kkoopa i recompiled with a patch that returns a string instead of that `Nan::Null` and I got the string as expected, but if i recompiled with the original source that returns the `Nan::Null`, it was returning again `true` instead. Idk if that helps.

I haven't yet verified whether my rebuild process was using the v8 version electron bundles with as a target, but the problem already starts with electron advertising it's shipping with ABI `48`, but breaking the 48 abi due to the newer v8 version.

**Comment by kkoopa** [comment]
@juliangruber It does not bring any clarity to me.
The [code](https://github.com/nodejs/nan/blob/master/nan.h#L526-533) in question hardly does anything.
```c++
inline v8::Local<v8::Primitive> Null() {
  return v8::Null(v8::Isolate::GetCurrent());
}
```
So the most likely source of error is indeed an ABI incompatibility.

`v8::Null` is defined [here](https://github.com/v8/v8/blob/5.1.281/include/v8.h#L8509-8515)
```c++
Local<Primitive> Null(Isolate* isolate) {
  typedef internal::Object* S;
  typedef internal::Internals I;
  I::CheckInitialized(isolate);
  S* slot = I::GetRoot(isolate, I::kNullValueRootIndex);
  return Local<Primitive>(reinterpret_cast<Primitive*>(slot));
}
```
`v8::True` is defined [here](https://github.com/v8/v8/blob/5.1.281/include/v8.h#L8518-8524)
```c++
Local<Boolean> True(Isolate* isolate) {
  typedef internal::Object* S;
  typedef internal::Internals I;
  I::CheckInitialized(isolate);
  S* slot = I::GetRoot(isolate, I::kTrueValueRootIndex);
  return Local<Boolean>(reinterpret_cast<Boolean*>(slot));
}
```

`v8::Boolean` is a `v8::Primitive`, so the only significant difference between the two functions is ` I::kNullValueRootIndex` vs ` I::kTrueValueRootIndex`.

In [V8 5.0.71](https://github.com/v8/v8/blob/5.0.71/include/v8.h#L7159-7160), we have
```c++
  static const int kNullValueRootIndex = 7;
  static const int kTrueValueRootIndex = 8;
```

In [V8 5.1.281](https://github.com/v8/v8/blob/5.1.281/include/v8.h#L7337-7338), we have
```c++
  static const int kNullValueRootIndex = 6;
  static const int kTrueValueRootIndex = 7;
```
So, the ABI incompatiblity is obvious: the precompiled addon, correctly using the ABI for V8 5.0.71 calls `v8::Null`, which returns the field at index 7. When using the wrong V8 version, like Electron does, this ends up returning `true` instead of `null`, since the ABI changed and `true` is now located at index 7.

**Comment by paulcbetts** [comment]
Yeah, so this isn't so bad - folx just need to run electron-rebuild and somehow invent a time machine to stop Mapbox from inventing node-pre-gyp

**Comment by rvagg** [comment]
> invent a time machine to stop Mapbox from inventing node-pre-gyp

You're underestimating the pain that precompiled addons solve for users of platforms without easily (or default) installable compilers (Windows) or where compiling is a large cost (slower ARM devices). We (Node core) value this shift in the Node ecosystem because it eases a lot of user pain and take ABI stability very seriously as a result. Breaking ABI while not changing the `NODE_MODULE_VERSION` number undoes all of that value.

We're going to be shipping a patched version of V8 in Node.js v6 that has stable ABI to deal exactly with this problem. The patches aren't going to be upstreamed to V8 (probably) so Electron will miss out. This is going to be a new norm for Node in its "Current" release lines so Electron is going to need a strategy for dealing with this going forward. Above all `NODE_MODULE_VERSION` needs to point to the same ABI as Node's does or you're going to get a _lot_ more issues filed here from upset users.

**Comment by zcbenz** [comment]
@kkoopa @rvagg Thanks for the details and sharing Node's plan, I'll make sure Electron follow what Node does (increase `NODE_MODULE_VERSION` or patch V8), so users don't have to worry about the differences.

**Comment by rvagg** [comment]
I meant to link to https://github.com/nodejs/node/pull/7016, @zcbenz you might want to keep an eye on that one, it'll probably land soon and be in a new Node v6. I have a blog post to write about this policy change, we decided it months ago but never properly communicated it so I'm sure it'll be a surprise to many.

**Comment by paulcbetts** [comment]
> You're underestimating the pain that precompiled addons solve for users of platforms without easily (or default) installable compilers (Windows) or where compiling is a large cost (slower ARM devices). 

I agree with everything you're saying, but the problem is that node-pre-gyp is untenable - originally for Electron which has always moved super fast wrt V8 versions, but now for node.js as well. When everyone in the world used 0.12, it was reasonable to precompile it for every OS, but now that there is an explosion of different node versions (and by proxy, different `NODE_MODULE_VERSION`s), as well as different platforms that are not 100% ABI compatible with node.js (nw.js, electron), the likelihood that you will actually have a working binary that is pre-shipped is pretty low.

**Comment by rvagg** [comment]
> originally for Electron which has always moved super fast wrt V8 versions

Agreed, and just like Node.js, and io.js (where we tried to move fast but got burnt by this problem) I think Electron is going to have to come to terms with the cost of speed and come up with some stability policies, perhaps including an LTS policy.

> but now that there is an explosion of different node versions (and by proxy, different `NODE_MODULE_VERSION`s)

It may seem that way but we have a very explicit and strict policy now of keeping ABI stable between major versions and we only bump major (and therefore `NODE_MODULE_VERSION`) every 6 months. It's true that over time there will continue to be multiple overlapping Node.js versions to support but that will simplify even further later this year when 0.10 and 0.12 reach EOL.

> as well as different platforms that are not 100% ABI compatible with node.js (nw.js, electron),

This is what `NODE_MODULE_VERSION` is supposed to solve. Electron was, originally, using a totally different `NODE_MODULE_VERSION` (by adding >100 to it) and I think nw.js might still be. The problem here is that Electron has moved back to the same number as Node which is precisely why this problem is coming up. Either we need to bridge some of the gaps between Node and Electron (which I'm _very_ keen to do fwiw) or Electron needs to use a different number so that this isn't a problem. The only reason you're identifying node-pre-gyp as a problem in this particular instance is because of this numbering, it's indicating an ABI compatibility while it's actually incompatible. We just need to fix that one way or another. The two obvious paths are for Electron and Node to move in lock-step in ABI compatibility or for Electron to use a different `NODE_MODULE_VERSION` .. of course introducing yet another `NODE_MODULE_VERSION` gets back to the problem you identified of version proliferation and I think, at this stage at least, Electron would lose out, with addon developers shipping binaries for the Node suite but not for Electron, and Electron users being forced to compile. But at least they wouldn't have an ABI conflict which is usually more difficult for users to grok.

**Comment by mafintosh** [comment]
I was just bitting by this again because https://github.com/mafintosh/utp-native was behaving weirdly in electron >1.1.3 because of the v8 change. If a fix isn't imminent we should really add a note to the README telling people to beware of this.

**Comment by paulcbetts** [comment]
@mafintosh Stupid question, but are you sure that you rebuilt modules? I saw some SUPER weird behavior the other day, where if I built node-spellchecker with 1.1.2 but used it on 1.2.0, it would 100% load perfectly no segfaults, but return `true` for every invocation of `isMisspelled`. This was surprising and Bad and terrifying

**Comment by mafintosh** [comment]
@paulcbetts it was using a prebuild that was suppose to be abi compliant with electron. i was experiencing exactly the kind of issues you were mentioning (spent multiple hours this morning scratching my head hehe). my point is that if prebuilds doesn't work with electron because it isn't abi compliant with node we need to write it down in a prominent position in the readme. this was kinda terrible to debug.

**Comment by paulcbetts** [comment]
@mafintosh Agree, this is a super bad issue, though I suspect that rolling back V8 (or rolling it forward) will probably be a super painful proposition in the Chromium codebase :(  A strange game. The only winning move is not to play. How about a nice game of chess?

**Comment by mafintosh** [comment]
@paulcbetts ... and now i need to watch wargames again hehe. what about just bumping the abi to some large number for now then as a tmp workaround? that'll make prebuilders recompile.

**Comment by cdaringe** [comment]
we have been fighting this as well.

> will probably be a super painful proposition in the Chromium codebase

@paulcbetts, I don't understand ^^ remark.  can you clarify?

**Comment by paulcbetts** [comment]
@cdaringe Chromium almost certainly interacts with the native V8 API, if we just blindly patch it down to a previous version, we will have to patch all of those parts of Chromium too

**Comment by rvagg** [comment]
@ofrobots & @targos do you have any idea how the work you've done in https://github.com/nodejs/node/pull/7016 might interact with the rest of Chromium? If Electron was to float the same changes over V8 is there any likely problem that you can see in the way Chromium uses V8 that may cause grief here? This is may have to be something we take into account with our new V8 upgrade policy, which will unfortunately make it harder to _do_ mid-major upgrades if we take it seriously which will in turn force greater division with Electron and continue to cause these problems if the ABI # is the same...

**Comment by paulcbetts** [comment]
@rvagg If the changes are solely to massage ABI compatibility (or are fairly minor), we can probably cover that, since we build everything from source anyways, though @zcbenz is the expert.

The most foolproof seems as if the node ABI/API and the V8 ABI/API would be expressed in separate numbers (i.e. declare a certain `NODE_MODULE_VERSION` to be The Last One and from then on it's `V8_MODULE_VERSION` and `NODEAPI_MODULE_VERSION`). This would make intent easier to express in places like nan.

**Comment by rvagg** [comment]
I don't really see how multiple ABI numbers make sense within a single binary, it either _is_ compatible or _isn't_. One tactic could be for Electron to mirror Node's ABI numbers where there is compatibility and then jump to a different range when there isn't. e.g. Node is currently @ `48` and Electron used that when it was on V8 5.0 but now it's moved to 5.1 it could jump up to `148` but _if_ it ends up being ABI compatible again by floating the same patches as Node then it could go back down to `48`.

However ... that's just for pure Node addons. Is there such a thing as an Electron addon that pulls in more parts of the Chromium and Electron API than just what Node exposes?

**Comment by paulcbetts** [comment]
> However ... that's just for pure Node addons. Is there such a thing as an Electron addon that pulls in more parts of the Chromium and Electron API than just what Node exposes?

No, there's no way currently to link to libchromiumcontent from extensions, if you want to do that you basically have to include it in core

**Comment by rvagg** [comment]
Good to know, so native addons are our shared problem, lets come up with a shared solution so we can move forward without stepping on eachothers or users toes.

**Comment by ofrobots** [comment]
@rvagg 
> @ofrobots & @targos do you have any idea how the work you've done in nodejs/node#7016 might interact with the rest of Chromium?

Since the changes in nodejs/node#7016 are ABI-only, and API compatible, as long as Chromium is built from source along with the V8 + ABI changes, I think it should work.

**Comment by paulcbetts** [comment]
@ofrobots It generally does, until node-pre-gyp comes along and throws a spanner in the works

**Comment by rvagg** [comment]
node-pre-gyp will be perfectly happy once the ABI patches land both here and in Node, existing v6 binaries everywhere _should_ be able to work again in the current version of Electron.

**Comment by swashcap** [comment]
@cdaringe and I are battling with build-related problems due to this issue in our app 💻🔥. Anything we can do to help?

**Comment by paulcbetts** [comment]
@swashcap Do you need 1.2.x? It might be easier to downgrade to 1.1.x

**Comment by zcbenz** [comment]
To work around this, you can instruct node-pre-gyp to build the modules from source by setting `npm_config_build_from_source`:

```bash
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=1.2.2
export npm_config_arch=x64
export npm_config_runtime=electron
export npm_config_build_from_source=true
HOME=~/.electron-gyp npm install module-name
```

**Comment by swashcap** [comment]
@paulcbetts We unfortunately need bug fixes that happened in 1.2.x. Thanks for the suggestion.

@zcbenz Hmm, looks promising. Where could I get the `.electron-gyp`?

**Comment by paulcbetts** [comment]
@swashcap You just need to make an empty folder, so that the headers that node-gyp downloads don't end up stomping your node.js headers

**Comment by 0x00A** [comment]
Unfortunately, `npm_config_build_from_source` doesn't work for me since there are a whole host of modules, specifically [`level`](https://github.com/level) that don't know what to do with an error of type "`true`". For now I've downgraded to 1.1.3 :(

**Comment by mafintosh** [comment]
@paulcbetts whats the reason for not just releasing a patch update to electron that sets ABI to 200 or something for now?

**Comment by paulcbetts** [comment]
@mafintosh This might be the best solution tbh, I'd personally rather that everyone just compile modules from source

**Comment by 0x00A** [comment]
@paulcbetts hey, maybe im missing something. I'm compiling from source (using the workaround mentioned by @zcbenz), but im still having a problem (as initially described [`here`](https://github.com/nodejs/nan/issues/578#issue-157658324)). Is there some other way to approach compiling from source that will somehow fix this?

**Comment by mafintosh** [comment]
@paulcbetts yea thats what i'm thinking as well.

**Comment by juliangruber** [comment]
@0x00A you're probably building from source for the wrong abi, resulting in the same(-ish) binary as prebuild would give you. this works for me: https://github.com/juliangruber/dat-desktop/blob/master/package.json#L26. Make sure you're on latest prebuild and level* for that.

**Comment by 0x00A** [comment]
@juliangruber is there some secret sauce in the plist? because otherwise we are doing the same thing (the only difference is that im using `electron-packager` from node as a build script instead of a npm script)

**Comment by juliangruber** [comment]
@0x00A oops yeah fixed the link

**Comment by pfraze** [comment]
@0x00A I pulled this from @zcbenz's comment, and it worked for me:

```
npm rebuild --runtime=electron --target=1.2.5 --disturl=https://atom.io/download/atom-shell --build-from-source
```

**Comment by qianjiahao** [comment]
@pfraze thanks a lot , it worked on me!

my project version

node v6.2.2
npm v3.9.5
electron-prebuilt 1.2.6

1 install package from npm

    npm install

2 rebuild by electron

    npm rebuild --runtime=electron --target=1.2.5 --disturl=https://atom.io/download/atom-shell --build-from-source

3 start your electron

    electron main.js

right, start your project~

**Comment by 0x00A** [comment]
just specifying `--abi=48` worked for me.

**Comment by TheAlphaNerd** [comment]
node v6 now ships with an abi compatible V8 5.1 🎉

**Comment by xzyfer** [comment]
@TheAlphaNerd does this mean an upcoming release of Node 6 with have different module version?

**Comment by TheAlphaNerd** [comment]
node v6.5.0 was shipped with a patched version of V8 5.1 that is abi
compatible with 5.0

we did extensive testing to ensure this. as such there was no bump to
module version number

node v7 will likely ship with 5.4 which will come with a module version
bump

**Comment by addaleax** [comment]
@TheAlphaNerd I’ll try to think of it when the time comes, but we should probably bump NODE_MODULE_VERSION from 48 to 50 because electron uses 49 for its own unmodified V8 5.1.

**Comment by zcbenz** [comment]
Electron 1.4.0 is going to be published with V8 5.3 soon, and it is unlikely that we would backport the module version fix for 1.2.x release.

**Comment by rgbkrk** [comment]
While I'm sad, thank you so much for Electron and all the superb work you put into it. :smile:

**Comment by davej** [comment]
Can anybody summarise the current situation in practical terms. Will Electron 1.4.x now 'just work'? Will pre-built binaries work providing that they have been built against Node ^6.5.0? Or are there still a few steps that we will need to take?

**Comment by TheAlphaNerd** [comment]
So just a few minutes ago we had a [green CI run](https://github.com/nodejs/node/pull/8317#issuecomment-246389446) for V8 5.4 on the nodejs master branch. Our current plan, as long as we don't notice any unexpected regressions, is to ship node V7 with it.

Seeing as how in node v6 we bumped V8 5.0 to 5.1, I don't think it unreasonable to expect us to continue to have a modern V8 in all upcoming node releases, assuming we can do so without breaking ABI. At the very least we will be attempting to have the latest V8 in every semver major release.

I would really love to see if node + electron can collaborate on this to see if we can avoid have mismatches in `node module version`.

There is of course the possibility that this is not exactly tenable based on the pace that ya'll need to keep chromium updated, but perhaps some sort of more reasonable cadence can help keep the delta between the electron node and upstream smaller.

**Comment by addaleax** [comment]
@davej Sorry, no. Maybe a future electron version that uses V8 5.4 could work.

@zcbenz Sorry if I’m asking too many questions, but how soon is “soon”? Would you be using a `NODE_MODULE_VERSION` of `50`? That would be good to know, because in that case, Node.js would need to skip that number, too.

**Comment by rgbkrk** [comment]
> This might be the best solution tbh, I'd personally rather that everyone just compile modules from source and using a bananas high ABI would do that

@paulcbetts The main reason we rely on prebuilts is so that our components can cleanly install in Atom and in Electron. With Atom likely to update to a newer Electron soon, that's about to be pain there too.

**Comment by zcbenz** [comment]
@addaleax It will come out in a few days, and it uses `50` as `NODE_MODULE_VERSION`. 

I appreciate the efforts on making Node and Electron match node module version. For the foreseeable future Electron is going to bump the node module version for every stable Chrome/V8 release, so future node module versions in Electron are predictable:

| Electron Version | NODE_MODULE_VERSION | V8 Version |
|------------------|---------------------|------------|
| 1.2.0            | 48                  | 5.1        |
| 1.3.0            | 49                  | 5.2        |
| 1.4.0            | 50                  | 5.3        |
| 1.5.0            | 51                  | 5.4        |

And Electron bumps the minor version usually within a short time after a new Chrome stable releases, so when Electron bumps the node module version can be predicted by using Chrome's release calendar: https://www.chromium.org/developers/calendar.

**Comment by targos** [comment]
What about using the same NODE_MODULE_VERSION as the corresponding Chrome / V8 version  number ?

So if V8 version is 5.4, NODE_MODULE_VERSION would be 54.

**Comment by ofrobots** [comment]
I the (hopefully near) future the [new Node.js native API](https://github.com/nodejs/api) is going to mature enough, and at that point the expectation would be that the V8 version no longer dictates the `NODE_MODULE_VERSION`. It would be best to avoid tight coupling between V8 version and `NODE_MODULE_VERSION`.

**Comment by targos** [comment]
@ofrobots I totally agree with that, but in the mean time I think it's easier for us to couple our `NODE_MODULE_VERSION` with V8's version rather than with Electron's roadmap.

**Comment by addaleax** [comment]
> and at that point the expectation would be that the V8 version no longer dictates the `NODE_MODULE_VERSION`. It would be best to avoid tight coupling between V8 version and `NODE_MODULE_VERSION`.

At the very least, there’s going to be a transition time in which many addons don’t use the new native API. It might make more sense to just start another counter that can be incremented specifically when the new ABI/API changes?

**Comment by zeke** [comment]
I'm not sure if it solves this issue, but Node 8 has this new thing:

> The N-API is an API for building native addons. It is independent of the underlying JavaScript runtime and is maintained as part of Node.js itself. The goal of this project is to keep the Application Binary Interface (ABI) stable across different Node.js versions.

> The purpose of N-API is to separate add-ons from changes in the underlying JavaScript engine so that native add-ons can run with different Node.js versions without recompilation.

https://nodejs.org/dist/latest-v7.x/docs/api/n-api.html

**Comment by MylesBorins** [comment]
@zeke the N-API is definitely the thing that will eventually help solve this. in 8.x it is behind a flag as it is experimental.

It is also worth mentioning that it cannot be relied on until userland modules can build on top of

**Comment by codebytere** [comment]
At present (after v1.8) V8 versions should be exactly the same for both Node.js and Chromium!
