### ISSUE TITLE
Maybe add toggleMaximized()

### ISSUE THREAD

**Issue by littleguga** [electron/electron#5871]
Instead of using:
``` js
        if (appWin.isMaximized()) {
            appWin.unmaximize()
        } else {
            appWin.maximize()
        }
```

``` js
appWin.toggleMaximized()
```

I think I can make PR, but not sure what files are need to be upgraded(only .cc?)

**Comment by enlight** [comment]
Or you could just write

```js
appWin.isMaximized() ? appWin.unmaximize() : appWin.maximize()
```

**Comment by littleguga** [comment]
@enlight yep, but It is 3 functions instead of one.

There is `appWin.webContents.toggleDevTools()`, why not to create toggleMaximized()?

**Comment by zcbenz** [comment]
We don't add built-in APIs for `toggleXXX`, since it can be simply achieved with existing APIs. For frameworks it is usually bad to have many ways to do the same thing.

For `toggleDevTools`, it exists only because we implemented it before `isDevToolsOpened` and `openDevTools`, it is was a design mistake a few years ago when we started Electron project.
