### ISSUE TITLE
Flash video-player tvthek.orf.at 

### ISSUE THREAD

**Issue by GeorgS** [electron/electron#598]
I need to load the following page http://tvthek.orf.at inside an iframe.
I'm trying to move away from node-webkit, but the video-player on the page doesn't work with the Flash 15 beta NPAPI plugin on atom-shell, but it does on node-webkit.

To reproduce the error, create a window with disabled `node-integration` and `plugins` set to `true`.
Load a page like http://tvthek.orf.at/program/ZIB-Magazin/5521881/ZIB-Magazin/8325486.
There are no errors in the console but the video doesn't play.

**Comment by hollowdoor** [comment]
In a Gtk Webkit webview even flash video plays in the video tag.

Sorry for posting on an old issue. I don't know if this needs a new issue. I just wanted to get this out there. I don't even know if this should be considered a bug, or a feature request.

I've been working with the video tag in electron, and it has not been what I expected. In my opinion if it's a video it should play. ffmpeg itself does support flv videos. I don't even know if there is a codec ffmpeg doesn't support. I'd go so far to say electron video tags should support all codecs that aren't hampered by licenses.

It would be great to do:

```html
<video src="any_video.type"></video>
```
I'm not affiliated with [playback](https://github.com/mafintosh/playback), but wide video support would help that project too. I hate to see great potential wasted because of limited media support.
