### ISSUE TITLE
API to restore window state

### ISSUE THREAD

**Issue by xywz** [electron/electron#5993]
> The Resume feature, in OS X v10.7 and later, saves the state of your app’s windows and restores them during subsequent launches of your app. Saving the state of your windows enables you to return your app to the state it was in when the user last used it.

https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26
- Operating system: OS X

**Comment by paulcbetts** [comment]
The best way to implement this is probably via an API like:

```js
myBrowserWindow.enableWindowRestoration();

myBrowserWindow.on('saveWindowState', () => {
  // TODO: Developer writes their state to local storage or whatever
});
```

**Comment by zcbenz** [comment]
If we are going to implement this in Electron, I think we should implement this with existing APIs of Electron instead of using the native API provided by OS X. This feature has to be implemented across platforms, so having a common implementation will make the maintenance much easier.

There are also implementation details to consider:

* What should we do when user sets an initial position and window size;
* If we allow saving custom states, when should when let users read and write the custom states;
* How to precisely save and restore minimized/maximized state;
* How state restoring should work when `show` option is `false` and `true`.

**Comment by DeerMichel** [comment]
Closing this issue since there has not been any recent activity or plans made to implement such feature. I think you can also get the desired functionality by saving/restoring window state during an appropriate [event](https://github.com/electron/electron/blob/master/docs/api/app.md#events).
