### ISSUE TITLE
Prevent taskbar from showing on focus [overlay for fullscreen application]

### ISSUE THREAD

**Issue by sklink** [electron/electron#5994]
* Electron version: 1.2.2
* Operating system: Windows 10, x64

The application I am building acts as an in-game overlay. Similar to what you might find through [Overwolf](http://www.overwolf.com/). Using:
```
transparent: true, 
alwaysOnTop: true, 
frameless: false, 
skipTaskbar: true
```
I can create what looks like an interface laid over the full screen game (Dota 2). However, when the electron window gains focus the task bar shows up, breaking the continuity of the experience.

The [BrowserWindow docs](http://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag) mention that a:
> toolbox window [...] can not be focused on

I'm not sure if creating a `toolbox window` would solve the issue... since *can not be focused* might also mean it can't receive input.

1. Is it possible to create a `toolbox window` like it mentions?
2. Can an electron window receive clicks without taking focus? 
3. Can an electron window take focus without bringing up the taskbar?

It seems like this could apply to other electron apps with `skipTaskbar: true` set.

[Stackoverflow Link](http://stackoverflow.com/questions/37713180/electron-browserwindow-shows-taskbar-when-focused)

**Comment by zcbenz** [comment]
It is impossible to make the window receive mouse events while not taking focus, for your use case you can create a global mouse hook that captures mouse events from the game, or you can just make electron window take focus and then send mouse event to the game.

Electron doesn't support either way, otherwise it would be easily be marked as virus by security softwares. But you can write a native node module for it.
