### ISSUE TITLE
win.setSize ignores window's minWidth/minHeight on OS X

### ISSUE THREAD

**Issue by sergeybekrin** [electron/electron#6004]
* Electron version: 1.2.2
* Operating system: OS X El Captian 10.11.2

Currently `win.setSize` behaves different under OSX and Windows 10.

So OS X allows to set values less than `minWidth` and `minHeight`, while Windows 10 checks limits  and prevents resize. I guess same happens with `maxWidth` and `maxHeight`.

**Comment by zcbenz** [comment]
The `minWidth`/`minHeight` only applies to users, if you sets a minimum size but then breaks it in your code, it is your own responsibility for what will happen.

In Electron the requests are passed to system directly, so you got different results because OS X and Window do not agree on how the window should resize. We can enforce the same behavior in Electron by doing an extra check, but 1) it is extra code and adds burden to maintenance, and 2) we should not pay for developer's fault. So I'm closing this as won't fix.

**Comment by sergeybekrin** [comment]
@zcbenz I agree. Do you think it should be documented in [docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetsizewidth-height-animate)?
