### ISSUE TITLE
Cannot use REPL on Windows

### ISSUE THREAD

**Issue by stelcheck** [electron/electron#6025]
* Electron version: 1.2.2
* Operating system: Windows 10

With the following code on the renderer side:

```
const electron = require('electron')
const app = electron.app

app.on('ready', function () { 
	require('repl').start({
		prompt: 'hello'
	}).on('exit', function () {
		app.exit(0)
	})
})
```

This code as intended on OS X, but for some reason, `repl.on('exit')` is triggered here and the app just exits. I checked whether this was a Node.js issue, but it doesn't seem to be the case.

**Comment by kevinsawicki** [comment]
I believe this is due to https://github.com/electron/electron/blob/c422613169cc08f3c7970db92128dff91a70fb2a/lib/browser/init.js#L43-L49 and based on https://github.com/electron/electron/issues/4218#issuecomment-174455758 it does not seem like this will be possible.

This option should probably be removed on Windows until it can be supported.

**Comment by zcbenz** [comment]
I'm closing this as won't fix since it doesn't seem possible, more technical details can be found at https://github.com/electron/electron/pull/5776.
