### ISSUE TITLE
ERR_ABORTED during download

### ISSUE THREAD

**Issue by rosshinkley** [electron/electron#6054]
* Electron version: ^1.2.0
* Operating system: Ubuntu 14.04

It seems that `did-get-response-details` that have attachments in them trip `did-fail-load` with `ERR_ABORTED`.  It looks suspiciously close to #4396, but I can also see where this _might_ be legitimate.  Going back and running against versions as far back as 0.35.0, Electron still presents with this behavior, making me think it might be expected, albeit undocumented.

For what it's worth, I've thrown together a [gist](https://gist.github.com/rosshinkley/bfd73776fa9b3b30b7ea758780471d07) that shows the behavior.  (Note that pulling straight from codeload skips the Github redirect, sidestepping the problem in #4396.)  

My cursory look through the issues didn't yield much.  Is this an expected behavior?  If so, why?

**Comment by zcbenz** [comment]
I'm merging this to #4396 since they are essentially the same bug.

It is actually sort of expected behavior in Chromium, for downloading as example, first you navigated to a location, after received headers Chromium found it is a download and then aborted the navigation.

Though it totally makes sense, I think we should not emit `ERR_ABORTED` for this kind of abortion.
