### ISSUE TITLE
Resize transparent window

### ISSUE THREAD

**Issue by nickdima** [electron/electron#6107]
* Electron version: 1.2.2
* Operating system: Windows 10

I'm testing an app with a transparent window (and always on top enabled) on both Mac OS  and Windows. On Mac the window can be resized without problem but on Windows the resize cursor doesn't show up when hovering the edge of the window.
I noticed that in the documentation resizing a window could be problematic on some platforms but I was curious to learn more on this. Or even be pointed in the right direction for how to make this work by contributing to Electron.

**Comment by zcbenz** [comment]
On Windows resizing a window relies on the existence of window frame, i.e. the `WS_THICKFRAME` style, and we can not set it for transparent window because the window frame would show under the transparent window.

A possible way to is to capture the mouse events and implement the resizing from ground up.

I'm closing this as won't fix since the behavior has been explicitly warned, and we don't have any plan on this.

**Comment by xiaodoulala** [comment]
https://www.jianshu.com/p/9944825870d5
