### ISSUE TITLE
webContents.findInPage searches the shadow DOM

### ISSUE THREAD

**Issue by erkyrath** [electron/electron#6138]
* Electron version: 1.2.3
* Operating system: MacOS 10.11.5

When you invoke findInPage, you get yellow highlights in elements in the shadow DOM as well as the main DOM.

Maybe this is intended, but it seems against the spirit of shadow-DOMing. There should at least be an option to exclude shadow DOM from search.

(My particular problem is that I want to put a search control in the window. The user enters search text into an input field, but I don't want it to find the text in that very input field!)

(I see a discussion (https://discuss.atom.io/t/using-webcontents-findinpage-to-implement-typical-find-function/25309) which indicates that I could use a webview tag instead of a shadow DOM input. I will try that next, but this request stands.)

**Comment by zcbenz** [comment]
This is actually a feature of Chromium, and unfortunately it doesn't provide any option for this:
https://bugs.chromium.org/p/chromium/issues/detail?id=244955
https://bugs.chromium.org/p/chromium/issues/detail?id=353430

I suggest creating an issue at Chromium's issues list to request an option to exclude shadow DOM form searching. I'm closing this since it is a hard-coded feature of Chromium, and we are not able to fix it alone on Electron's side.

**Comment by erkyrath** [comment]
Ok, thanks.
