### ISSUE TITLE
blur event fired twice when clicking taskbar icon to minimize

### ISSUE THREAD

**Issue by MetalCar** [electron/electron#6203]
I hope this is the right place for this issue.
I'm using electron-prebuilt 0.38.7 for a desktop application.
I figured out, that the 'blur' event is fired twice, when I'm clicking on the icon in the taskbar.
Also, I figured out, that `BrowserWindow.inFocused()` sometimes responds with true, while the window isn't focused.

This is the code I used.

``` js
mainWindow.on('blur', function() {
    saveWindowState(bounds_info_path, mainWindow);

    if (mainWindow.isFocused()) {
      console.log('is focused');
    } else {
      console.log('is not focused');
    }
  });
```

Am I doing something wrong, or is there a bug? I also tried it with electron-prebuilt version 1.0.2. Same issue as described above.

I posted issue this under electron-prebuilt issues, but they told me, to post it here.

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by MetalCar** [comment]
I'm using windows 7 64-bit

**Comment by Naiba01** [comment]
Is this problem resolve.Electron 1.2.6 still has this matter.

**Comment by codebytere** [comment]
https://github.com/electron/electron/issues/5345

**Comment by CydeSwype** [comment]
I'm dealing with this now but it's not quite as described.  I think the underlying issue is that clicking the tray icon counts as a blur event.  This creates a challenge when wanting to "toggle" the window state (creates a race condition) since there's a simultaneous tray click event.  Depending on the code execution, the tray click event fires after the blur event (resulting in the window being hidden from the blur and then immediately shown again due to the tray click event being caught).
