### ISSUE TITLE
Question: why aren't frameless windows on Mac implemented using NSBorderlessWindowMask

### ISSUE THREAD

**Issue by miniak** [electron/electron#6232]
The code in `NativeWindowMac::InstallView` looks weird. Instead of just using NSBorderlessWindowMask style, the standard window buttons are being hidden and the actual content view is being resized to cover the titlebar. Why is that?

**Comment by kevinsawicki** [comment]
Not sure, perhaps because it is deprecated? https://developer.apple.com/reference/appkit/nsborderlesswindowmask?language=objc

**Comment by miniak** [comment]
Hm, it must have been deprecated in the 10.12 SDK

**Comment by miniak** [comment]
@kevinsawicki I was actually investigating how to implement the titleBarStyle: 'hidden' for OS X 10.9. In a native Cocoa app, with an NSWindow with NSBorderlessWindowMask, you can create the "semaphore" buttons using [NSWindow standardWindowButton:forStyleMask:] + some trickery instead of using 10.10+ titleVisibility property.

In Electron, as the NSBorderlessWindowMask is not being used, this could be implemented by just keeping the buttons visible and in correct position.

**Comment by zcbenz** [comment]
`NSBorderlessWindowMask` unfortunately has lots of unexpected behaviors, like not having a shadow like other normal windows, and not able to have rounded window corners. If we want to make the frameless window work like a normal window, it is not going to work.

For making `titleBarStyle: 'hidden'` work on OS X 10.9, I think it has already been supported with current implementation, we just need to remove the OS version check when reading the option.

We didn't turn it on for  OS X 10.9 because the original implementation relied on `NSFullSizeContentViewWindowMask`, which is 10.10 only, until recently #5557 was introduced.
