### ISSUE TITLE
Some electron apps make wingpanel crash on elementaryOS Loki

### ISSUE THREAD

**Issue by Maccer1** [electron/electron#6240]
I first posted  a bug [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1215) about a crash using GPMDP. They told me to post it here since they think it's a library issue.

Here is the log about the crash:

>Jun 25 18:56:20 Maccer-PC gnome-session[1172]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3a00001 (Google Pla)
Jun 25 18:56:37 Maccer-PC kernel: [ 7339.623540] show_signal_msg: 31 callbacks suppressed
Jun 25 18:56:37 Maccer-PC kernel: [ 7339.623547] wingpanel[1509]: segfault at 0 ip 00007f03eda8a770 sp 00007ffcc8ebf3d8 error 4 in libglib-2.0.so.0.4800.1[7f03eda51000+10f000]
Jun 25 18:56:38 Maccer-PC gnome-session[1172]:  Message: ProcessWrapper.vala:99: Process 'wingpanel' watch exit

There's more info on the link posted at the beginning.

**Comment by zcbenz** [comment]
The "Window manager warning: Buggy client" warning comes from gnome-session and it happens for lots of popular apps. The real problem is wingpanel crashed, and I think you should report the bug to wingpanel, even though it may be caused by Electron sending wrong messages. Sorry for keep you reporting this to different repos.
