### ISSUE TITLE
Flashing when updating tray icon on Linux

### ISSUE THREAD

**Issue by Silvercast** [electron/electron#6301]
- Electron version: 0.37.3, 1.2.5
- Operating system: Linux Ubuntu 16.04 LTS

I've tried many possibilities: different sets of icons, rename icon file names, latest 1.2.5 Electron version, installing `libappindicator1` , etc. Still flashing every time `tray.setImage` is invoked. 

I read [#1473](https://github.com/electron/electron/issues/1473) but it's not related. Not sure if we are supposed to update or animate a spinning icon on tray app indicator.

**Comment by averissimo** [comment]
(from #8582)

* Electron version: 1.4.15
* Operating system: Ubuntu 17.05 (also reported in 16.10)

### Expected behavior

Tray icon changes without an intermediate image/artifact

### Actual behavior

![outphkfc5l8rt](https://cloud.githubusercontent.com/assets/211358/22598140/5e2aa21e-ea2a-11e6-93dd-fa742397a475.gif)


### How to reproduce

Checkout https://github.com/averissimo/electron-boilerplate/tree/refresh (branch refresh)

And run electron app (it will update tray icon every second to demonstrate bug)

```
$ git clone git@github.com:averissimo/electron-boilerplate.git
$ cd electron-boilerplate
$ git checkout refresh
$ cd boilerplate
$ npm install
$ npm start
```

This is also reproducible in the renderer (where it first was reported: https://github.com/yakyak/yakyak/issues/575 )

_edit_: added npm install step

**Comment by sofianguy** [comment]
Thanks for contributing!

This is an old version that we are no longer releasing bug fixes for. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
