### ISSUE TITLE
Using webContents.sendInputEvent to send Command+C does not trigger the "copy" action on macOS (but it works on Windows)

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#6338]
I'm throwing together a small testing framework based on webContents.sendInputEvent. It has been quite helpful. I'm testing clipboard functionality. After selecting some text, I can send this event on Windows:

```
webContents.sendInputEvent({
	type: 'keyDown',
	keyCode: 'c',
	modifiers: ['control'],
});
```

The code above will trigger a copy event, similar to `document.execCommand('copy')`. Unfortunately, this code does not work on macOS:

```
webContents.sendInputEvent({
	type: 'keyDown',
	keyCode: 'c',
	modifiers: ['meta'],
});
```

I did quite a bit of testing to figure out if I could get macOS to trigger a copy event, sending `keyDown`, `keyUp`, and `char` events in various combinations with no luck. One thing I did find is that the `keyDown` and `keyUp` events actually send a `C` instead of a `c` to the webContents. The `char` event sends the correct lowercase `c`. I'm thinking this could be the reason macOS isn't performing the copy, perhaps it wants a `c` and not a `C`. I did some digging to see if I could make `keyDown` send a lowercase `c` with no luck. Documenting my experience here in case anyone else runs into it or knows of a possible fix.

* Electron version: 1.2.5
* Operating system: macOS

**Comment by zcbenz** [comment]
The copy command on macOS is a bit different from other platforms, for Windows and Linux the ctrl-c event is translated to copy command directly, however for macOS, the cmd+c would trigger the `copy:` action on the webview, which then sends a copy command.

But `sendInputEvent` sends the event to DOM directly, and skips the `copy:` action, which should be why it doesn't emit the copy command.

I'm closing this since it is how Chromium's input system is designed.

**Comment by kirkouimet** [comment]
Thanks @zcbenz, good to know this about macOS.
