### ISSUE TITLE
Calling setSize can override minimum width values

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6347]
* Electron version: `1.2.3`
* Operating system: macOS

If you define a `minWidth` and then call `setSize` on a BrowserWindow with a width less than the `minWidth`, the window will be resized temporarily but any attempt to resize it will immediately return it to the minWidth.

```js
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const b = new BrowserWindow({
    minWidth: 300,
    maxWidth: 300,
    width: 300,
  });

  setTimeout(() => {
    b.setSize(100, 500);
  }, 1000);
})
```

`setSize` should be a noop for dimension changes that put the dimensions smaller than the `minWidth` or larger than the `maxWidth`

**Comment by zcbenz** [comment]
For most GUI frameworks, the maximum/minimum size only constrains the actions of users, if developers set a maximum/minimum size and then break it themselves, the framework will not stop them.

Electron is thin wrapper of the native GUI APIs on each platform for creating windows, that's why you see this behavior, Cocoa allows developers to break window's size constrains.

Adding our own checks for `setSize` and other APIs is possible, but it adds code complexity and does not really follow the convention for GUI frameworks. So I think we should just follow operating system's default behaviors when developers break things themselves.

I'm closing this as won't fix.

**Comment by MarshallOfSound** [comment]
@zcbenz I get that we are just a thin wrapper over native GUI APIs but this is proving a rather annoying issue for us in automated testing.

We are using spectron and calling `setSize` on Windows the test passes as the size is truncated at the minimum and max values.

On macOS it fails, this inconsistency is a bit annoying.  Can this be handled inside electron in anyway or do you think that test should be disabled on macOS?

**Comment by zcbenz** [comment]
Ah I didn't realize the behavior is inconsistent between platforms, in this case we should keep the same behavior on macOS.
