### ISSUE TITLE
shell.MoveItemToTrash uses gvfs-trash, which is not installed by default on debian

### ISSUE THREAD

**Issue by olmokramer** [electron/electron#637]
On line 69 of [platform_util_linux.cc](https://github.com/atom/atom-shell/blob/master/atom/common/platform_util_linux.cc) it shows that when a file is moved to trash by using `require("shell").moveItemToTrash(path)`, the gvfs-trash program is called to accomplish this. This program is, however, not installed by default on my debian (and maybe other linux distros, although I did not test this). So when calling the method, nothing happens, not even an error or warning.

**Comment by flying-sheep** [comment]
OK, ways to put things into trash:

* `kioclient5 move -- "$url" trash:/` (KDE Plasma 5)
* `kioclient  move -- "$url" trash:/` (KDE 4)
* `gvfs-trash -- "$url"` (GNOME)
* `trash -- "$url"` (trash-cli)

(i added `--` everywhere because it allows files staring with `-` to be handled)

> `gvfs-trash` is already the safest guess

because most people use GNOME? i don’t, and i had to spend time on google to find out why “Move to Trash” does nothing in Atom.

safest guess is to detect if any of those things is installed, use that if it’s the case, and show an info window when trying to trash stuff without any backend installed instead of failing silently.

i really like Atom and this was the only WTF moment i ever encountered with it! keep up the good work! :smile:
