### ISSUE TITLE
Can't run packaged windows app

### ISSUE THREAD

**Issue by cutbko** [electron/electron#6506]
* Electron version: not sure, I am using latest electron-react-boilerplate
* Operating system: Win8

Please help, the issue may be in webpack, not sure. When I run app in dev mode it loads just fine but when I run "npm run package" and open compiled exe file it fails to import some components: http://prntscr.com/bswb0z

I attached the code where it is reproducible for me, just run npm install -> npm run dev (to see that dev is working) -> npm run package (to see the issue. I also enabled dev tools in production mode)

[tracker.zip](https://github.com/chentsulin/electron-react-boilerplate/files/364363/tracker.zip)

**Comment by kevinsawicki** [comment]
Closing this out here since it is being tracked at https://github.com/chentsulin/electron-react-boilerplate/issues/278

It looks like the module is not found which means for some reason it isn't being included in the bundled application when it is build. That suggests it is a packaging issue with the app itself.
