### ISSUE TITLE
Setting audio output device does not work for a particular device

### ISSUE THREAD

**Issue by zuzanqa** [electron/electron#6507]
* Electron version: 1.2.7
* Operating system: Windows 10 

We are having an issue when setting the audio output device to a Plantronics headset (specifically the Savi w440, but also for others in the 4xx line). When switched to this device no audio output can be heard. 

The audio input on this same headset works fine. Both audio output and audio input work fine for this headset on other operating systems (including earlier versions of Windows).  Everything works fine for other headsets that we have tried. The device drivers are up to date. No errors appear in dev tools.

**Comment by enlight** [comment]
Does Chrome exhibit the same issue?

**Comment by zuzanqa** [comment]
No it does not. Tested on chrome v 51

**Comment by MarshallOfSound** [comment]
@zuzanqa Which exact version of v51 did you try on.  Electron is currently sitting on `51.0.2704.106`

**Comment by zuzanqa** [comment]
@MarshallOfSound @enlight Yes, I tried it on chrome 51.0.2704.106 and the audio output through the headset was fine.

**Comment by zuzanqa** [comment]
The Electron application with the sound output does not show up in the Volume Mixer for the Plantronics device either, if that helps at all.

**Comment by zcbenz** [comment]
@zuzanqa Electron not showing int the Volume Mixer may indicate that this is a problem with the driver, I know some audio hardware have problems with Chrome browser and they solved it by doing some whitelist thing for chrome.exe. Since Electron is just using the audio code of Chrome browser, I'm afraid this is not a thing we can fix.

**Comment by zuzanqa** [comment]
@zcbenz Do you think it is a problem with Chrome browser in the case where everything works as expected with Chrome (that is it shows up in volume mixer and audio comes out as normal)? I tested it on the same version of Chrome on which Electron is running and it worked just fine. The only time I run into issues is in Electron applications.

**Comment by zuzanqa** [comment]
Hi there again, @zcbenz @enlight @MarshallOfSound 

thanks everyone for your response. We have so far not been able to resolve the issue, but I do have further information about it. 
The same situation occurs whenever any headsets using DECT are connected - the issue is not limited to the plantronics device, but we were able to replicate it with any DECT devices...
Is there any advice/help you could offer on that? 

Thank you so much!

**Comment by zuzanqa** [comment]
Hi again everyone @zcbenz @enlight @MarshallOfSound .
Has there been any progress on this issue? anyone else reporting issues with DECT devices and electron?

**Comment by zcbenz** [comment]
This is the first and only issue we received about DECT devices. I'm closing this because we are not able to solve this on Electron's side, it is very likely an issue with the device's drivers, only developers of Chrome's audio system may be able to solve this but apparently none of them are Electron contributors.
