### ISSUE TITLE
app.getPath('userData') doesn't return %APPDATA% + plus app name

### ISSUE THREAD

**Issue by SimplyAhmazing** [electron/electron#6628]
* Electron version: v1.3.1
* Operating system: Windows 10

When I call `app.getPath('userData')` on my Mac I get the proper directory of `~/Library/Application Support + <my app's name>` .

However, when I make this same call from my app on Windows 10 I get the path to the `app.asar` -- the asar file for my application. According to the [docs](http://electron.atom.io/docs/api/app/#appgetpathname) this call should return the value of `%APPDATA%`.

I can get the value of `%APPDATA%` from `process.env.APPDATA` as a temporary work around.

I'm not sure why my `app.getPath('userData')` isn't working the same on windows as it does on Mac...

**Comment by kevinsawicki** [comment]
@SimplyAhmazing are you sure your app isn't calling `app.setPath` anywhere and that might be how it is getting changed on Windows?

**Comment by SimplyAhmazing** [comment]
@kevinsawicki Just found my error while grepping for `app.setPath`. I realized that I was actually calling `app.getAppPath('userData')` instead of `app.getPath('userData')` -- Small typo and I wasn't cognizant of what I typed.. Oops and thanks!

On another note, I tried to find the source for `app.getPath` when I thought it wasn't behaving properly for me and found [this](https://github.com/electron/electron/blob/28e2058ff108a20dd395ebe5374403381b6d3ff2/atom/common/api/atom_api_asar.cc#L34) Given that I'm not a C++ developer, I have no idea how to make sense of how that works -- but I'd love a quick intro or resources to grok this (fyi -- my only C++ experience is 2 OOP classes in undergrad :/ )

**Comment by kevinsawicki** [comment]
> On another note, I tried to find the source for app.getPath when I thought it wasn't behaving properly for me and found this Given that I'm not a C++ developer, I have no idea how to make sense of how that works

`app.getPath` is implemented at https://github.com/electron/electron/blob/b790ad6c1abdb3baa6b365dd96829046dbb5b39f/atom/browser/api/atom_api_app.cc#L378-L387

This method is mapped from C++ to JavaScript at https://github.com/electron/electron/blob/b790ad6c1abdb3baa6b365dd96829046dbb5b39f/atom/browser/api/atom_api_app.cc#L579

This is how many of Electron's API are implemented, you may want to read https://nodejs.org/api/addons.html#addons_hello_world for more details about exposing C++ functions via JavaScript.

You can also check out http://electron.atom.io/docs/development/source-code-directory-structure/ to see more details on the C++ and JavaScript code layout.

Lastly, you may want to check out https://github.com/electron/electron/blob/b790ad6c1abdb3baa6b365dd96829046dbb5b39f/lib/browser/api/app.js#L3 which shows how the C++ `app` APIs are retrieved and further extended to have certain APIs implemented completely in JavaScript.

**Comment by SimplyAhmazing** [comment]
Thanks @kevinsawicki this is awesome, i'll look more into these reads!

**Comment by MxMaster** [comment]
I know this is resolved, but I'll just write this here. I'm on a mac btw. When I run Electron app from within VSCode, the `app.getPath("userData")` returns a weird result: `"/var/root/Library/..."`, but when I run it from terminal, I get the correct `"/Users/..."`. BTW, I am running VSCode with `sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron` and that's because I am using Jitsi in my app and that needs Media permission on mac and VSCode's inner Terminal has issues with that. But that's a whole different story!!!

**Comment by bennyschmidt** [comment]
> BTW, I am running VSCode with `sudo /Applications

Found this searching for cross-platform `app.getPath("userData")` - think it is expected if running with `sudo` from the package vs running in user space that `userData` will return the root preferences location (e.g. `/var/root/Library`) instead of a user specific `Library` location.

The user specific `~/Library` was originally meant for their system preferences at the user level, butat some point people started saying "Oh that's where that user's apps go" and apps started using it as such. 

I digress... this might help someone:

```javascript
      const getUserDataPath = () => {
        if (
          !process?.platform ||
          !['win32', 'linux', 'darwin'].includes(process.platform) ||
          process.env.NODE_ENV === 'development'
        ) return './';

        switch (process.platform) {
          case 'darwin':
            return `/Users/${process.env.USER}/Library/Application\ Support/${APP_NAME}`;

          case 'linux':
            return `~/.cache/${APP_NAME}`;

          case 'win32':
            return `${process.env.LOCALAPPDATA}\\${APP_NAME}-installer\\`;
        }
      };
```

I only just discovered that only on Windows 11, it seems to suffix `-installer`. So that's fun.
