### ISSUE TITLE
chromium compatibility

### ISSUE THREAD

**Issue by bridiver** [electron/electron#6640]
I have been thinking about issues with node, v8 and chromium versions and I wanted to get some feedback on adding a chromium compatibility layer somewhat similar to nan for node. I was talking to @paulcbetts about the idea of doing something similar inside node for v8 and he said they were already talking about it. The general idea is to create a stable API on top of chromium that Electron would use instead of using the chromium API directly. This should allow you to run the same Electron code against different versions of chromium without changes. The same thing would apply to V8 and Node. New methods could be added to the compatibility layer, but methods would only be deprecated in very rare circumstances where maintaining compatibility was simply not possible. I think most of those situations can be avoided by providing slightly higher-level functionality vs more of a proxy API. Thoughts?

**Comment by zcbenz** [comment]
CEF is a very good example for wrapping Chromium APIs, and we used it to implement node-webkit and Atom editor before atom-shell, but eventually we moved to use Chromium content module because we needed to access details of Chromium API and we even had to patch Chromium to expose certain features.

And we then developed the brightray library to abstract certain parts of Chromium to make it easier for constructing apps based on Chromium, and it had been used by a few internal apps and the Breach browser, but all of those projects are dead now.

I think it is a good idea to have a compatibility layer for Chromium, but it would take too much efforts to construct one that can meet Electron's usages, I would expect a 5 people Chromium experts team spending two months to get a prototype working.

**Comment by rvagg** [comment]
Check out the recent issues and content of https://github.com/nodejs/api to see some of the progress. There's some real promising work going on prototyping an API layer, a lot of it is happening here: https://github.com/ianwjhalliday/node/tree/api-opaque-prototype

**Comment by zcbenz** [comment]
I'm closing this since apparently non of us have resources to implement compatibility layer upon Chromium.
