### ISSUE TITLE
autoUpdater re-download the same update if checkForUpdates() is called more than once

### ISSUE THREAD

**Issue by KSKS** [electron/electron#6655]
When an update is available, the first call of autoUpdater.checkForUpdates() would download the update as expected, but subsequent calls of checkForUpdates() would re-download the same update, when no newer update is available.

Expected: After the first update is downloaded, subsequent calls of checkForUpdates() would not re-download the same update, but still emit the same events 'update-available' and 'update-downloaded'.

This only happens on Mac. Same scenario on Windows has bug #6647 .

* Electron version: 1.2.6
* Operating system: OSX

**Comment by joshaber** [comment]
This should have been fixed in Squirrel 0.2.1, used in Electron 1.2.5+. See https://github.com/Squirrel/Squirrel.Mac/pull/171.

Note that it requires that your update server respect .tags.

**Comment by KSKS** [comment]
I am using the nuts server. A quick look at it doesn't seem like it uses etags, but I just started using it so I can't say for sure.

**Comment by MarshallOfSound** [comment]
@KSKS Considering the last commit to nuts (I use it as well) was before this was fixed in Squirrel.Mac there is no way Squirrel MAC supports it yet.

You should probably raise an issue over at https://github.com/GitbookIO/nuts/issues

@zcbenz I think it's safe to consider this an update server requirement and not an issue with Electron itself?
