### ISSUE TITLE
RSS feed or any digest about new apps on electron

### ISSUE THREAD

**Issue by Alexey-Panov** [electron/electron#6665]
Greetings!

I love your engine and your app (atom) of course! And love most of apps which used electron under the hood. ;)

But it's so difficult to find what's new apps added to page:
* http://electron.atom.io/apps/ (they are not A-Z sorted or "new on top")

So maybe you can add RSS for that page or make some weekend (monthly) digest where you can review new apps or just notice us about that. Or just add new app on top of these list. Please. I think I'm not alone with that.

Thank you for your job!

**Comment by vsemozhetbyt** [comment]
@Alexey-Panov In addition, you can watch [awesome-electron](https://github.com/sindresorhus/awesome-electron) or subscribe to [its commits RSS](https://github.com/sindresorhus/awesome-electron/commits/master.atom).

**Comment by jlord** [comment]
The apps are in order of when they were added, but with the newest additions on the bottom rather than the top. 

> weekend (monthly) digest where you can review new apps or just notice us about that

That's a good idea. We can't add an RSS feed to the page itself, but monthly we can do a blog post listing the apps added that month 👍  

I'll close this out—subscribe to the [the blog RSS](http://electron.atom.io/feed.xml) <img src="https://s3.amazonaws.com/digitalmarketer-downloads/wp-content/uploads/2016/07/RSS-IconLarge.png" width="15"> and keep an eye out for the roundup.

**Comment by Slamology2** [comment]
Some of my applications might be affected due to my contacts but by logging into certain public domains can kickstart your apps to work properties.
