### ISSUE TITLE
Problems with offscreen mode

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#6704]
I tired with the offscreen mode and here are the problems I found:

* [x] <del>The `data` of `paint` event is empty when loading simple local pages.</del>
* [x] The size of `data` is wrong, current implement uses the size of pointer (`sizeof(bitmap_pixels)`).
* [x] Crashes when opening devtools for offscreen window.
* [x] We should probably show a dummy view indicating it is offscreen instead of provide NULL.
* [x] The offscreen window is affecting the rendering of other windows. Try running `./script/test.py -g offscreen` and then refreshing the window.

/cc @gerhardberger @brenca

**Comment by gerhardberger** [comment]
> The `data` of `paint` event is empty when loading simple local pages.

What kind of page did you check? I couldn't reproduce it and also in the tests there is a local page that is being loaded.

> The size of `data` is wrong, current implement uses the size of pointer (`sizeof(bitmap_pixels)`).

Fixed in #6713 

> Crashes when opening devtools for offscreen window.

This is because devtools by default appears as a guest content in the browser window's webcontents and we haven't implemented guest contents yet. That's why the `<webview>` tag isn't working either yet. However the devtools works properly in detached state.

> We should probably show a dummy view indicating it is offscreen instead of provide NULL.

What exactly do you mean by that? The browser window's `NativeWindow` appears as a blank view now, it could be considered as a dummy view.

> The offscreen window is affecting the rendering of other windows. Try running `./script/test.py -g offscreen` and then refreshing the window.

Yeah, I'm still investigating this issue, but it seems the problem is somehow, that we create the browser windows from the renderer process with `remote.require('electron').BrowserWindow` and this way it tries to create the webContents in GPU enabled mode though it is disabled.

**Comment by gerhardberger** [comment]
@zcbenz I'm trying to figure out the last marked issue, where for a refresh the test window goes blank, but I haven't been able to solve it yet.

What I did notice though and it may be related, that if I disable hardware acceleration (with `app.disableHardwareAcceleration()`) to use the software path, and I create a browser window (not necessarily offscreen) and I destroy it (with `w.destroy`), after that when I create an offscreen browser window it won't run with a software output device, but it will use the GPU path. Any idea why this could be?

Note, that both of the above issues are only happening on macOS. On Windows it works fine.

**Comment by zcbenz** [comment]
All of the problems solved.
