### ISSUE TITLE
macOS: Window title not visible in fullscreen mode when titleBarStyle: 'hidden-inset'

### ISSUE THREAD

**Issue by miniak** [electron/electron#6715]
* Electron version: 1.3.2
* Operating system: OS X 10.10.6

When I use `titleBarStyle: 'hidden'`, the window title is visible in fullscreen mode in the floating titlebar appearing when mouse is moved to the top of the screen, but when I use `titleBarStyle: 'hidden-inset'`, the title is not visible.

**Comment by zcbenz** [comment]
`titleBarStyle: 'hidden'` should have title hidden, can you paste a screenshot? And what's the options used for creating window?

**Comment by miniak** [comment]
@zcbenz Sorry for the misleading description. I meant the window title, which appears when you move the mous cursor to the top of the screen, when the floating toolbar/titlebar appears.

**Comment by zcbenz** [comment]
This is intentional, showing window title for `hidden-inset` would result in an ugly titlebar, because the titlebar is tall and the title text is small. Usually Mac apps would show a toolbar in titlebar, however since Electron doesn't support creating native toolbars, leaving an empty titlebar is the only option that does not look ugly.

I'm closing this since it is a limitation of Electron.

**Comment by miniak** [comment]
Sounds reasonable.
