### ISSUE TITLE
Packaged App only works when run as admnistator

### ISSUE THREAD

**Issue by RilRil** [electron/electron#6730]
* Electron version: 1.2.5
* Operating system: windows 10 32bits and Windows 8 32bits

Hello, 

I npm install and build my app on windows 10 32bits : on this machine everything works correctly.
Then, I go on an other machine which is windows 8 32bits. When I execute my packaged app as a basic user I get an error :  **%1 is not a valid Win32 application** 
but when I execute it as Administrator it works ! 

Some has had this problem already ?

**Comment by zcbenz** [comment]
This error comes from loading native modules, you might want to start by investigating why that module doesn't load without administrator access. I'm closing this since the issues list is only for bug reports and feature requests, for further questions I suggest seeking help from [the community](https://github.com/electron/electron#community).
