### ISSUE TITLE
fetch for custom protocols

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#6802]
- Electron version: 1.3.x
- Operating system: Win10

trying to do

``` js
fetch('media://foo')
```

I get

```
Fetch API cannot load media://foo/. URL scheme must be "http" or "https" for CORS request.
```

and trying to do

``` js
fetch('media://foo', { mode: 'no-cors' })
```

gives me

```
Fetch API cannot load media://foo/. URL scheme "media" is not supported.
```

In both cases I did

``` js
protocol.registerStandardSchemes(['media']);
```

in main process

**Comment by MarshallOfSound** [comment]
See

https://github.com/electron/electron/issues/6749#issuecomment-238023155

**Comment by YurySolovyov** [comment]
Thanks, my bad, overlooked it on search

**Comment by YurySolovyov** [comment]
@MarshallOfSound I'd be happy to Improve docs to better link these methods, do you think it is worth it?

**Comment by MarshallOfSound** [comment]
@YurySolovyov All for improving the docs if you think it will help 👍

**Comment by phanmn** [comment]
For Electron 6.
I'm using these lines to fix this issue:
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      secure: true,
      standard: true,
      supportFetchAPI: true,
    },
  },
]);

**Comment by stevebauman** [comment]
Thank you @phanmn!!! You've saved me hours and hours of debugging ❤️ 

I needed to enable `supportFetchAPI` 👍

**Comment by richardo2016x** [comment]
> Thank you @phanmn!!! You've saved me hours and hours of debugging ❤️
> 
> I needed to enable `supportFetchAPI` 👍

it's valid in Electron@21.0.0 but seems to be invalid in Electron 22.0.0

**Comment by pie6k** [comment]
Seems it does not work.

Weird thing is that it works in development, but not in production build (using electron builder)

I tried pretty much every possible and reasonable combination of privileges with `protocol.registerSchemesAsPrivileged` and tried with every possible protocol type `registerStreamProtocol`, etc. 

I tried never resolving protocols (that never call callback), etc.

It works correctly in development (aka app name is "Electron"), but does not in prodcution, I always get the error 

```
Fetch API cannot load my-protocol://fooo. URL scheme "my-protocol" is not supported.
(anonymous) @ index-dd457f44.js:73
(anonymous) @ VM27:1
Promise {<rejected>: TypeError: Failed to fetch
    at file:///Users/adam/dev/projects/aaa/app/electron-dist/ma…}
index-dd457f44.js:73    Uncaught (in promise) TypeError: Failed to fetch
    at index-dd457f44.js:73:368
    at <anonymous>:1:1
```

**Comment by richardo2016x** [comment]
@YurySolovyov Hi, according to [report](https://github.com/electron/electron/issues/6802#issuecomment-1495503520) from @pie6k , maybe we should re-open this issue and try to fix that.

**Comment by richardo2016x** [comment]
Hey Guys, I found maybe it's undocumented requirement to call `protocol.registerSchemesAsPrivileged` **AFTER** `app.setPath('userData', ...)`.

I wrap my `protocol.registerSchemesAsPrivileged` as one function and call it **AFTER** `app.setPath('userData', ...)`.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/104543757/230629818-4426a9b9-81aa-4dcb-bc71-333119f512a4.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/104543757/230630525-24575710-07ec-4030-964b-8549608f1a42.png">

Then I found it works to enable `supportFetchAPI` for custom protocol!

**How do I found that**

Recently I found my `BrowserView` don't support fetch API, which works OK before. I do some google/stackoverflow search but no any dicussion/answer helps. 

After putting it aside for a while, today I suddenly realized that in the lifecycle of an Electron app, the result of executing `protocol.registerSchemesAsPrivileged` might be persisted in the disk cache, and subsequent behavior related to a custom scheme may all be read from the disk cache.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/104543757/230633961-60509257-adc5-4b59-a349-d5445d0eb440.png">

How Electron determine the location where persisted data stored? It's just  **`app.getPath('userData')`.** (see pic above, its content of app's userData path)

Just like @pie6k said, 

> ...
> It works correctly in development (aka app name is "Electron"), but does not in prodcution
> ...

In general, we use some build tools (such as `electron-builder`), which read package's name from `package.json` and set it as electron app's package name. (you can also set it by calling `app.setName()`)

By default, app's name would affect the value of `app.getPath('userData')`, except you set it manually by calling `app.setPath('userData', ...)`, what I did in my electron app.

Finally, I remembered, recently I adjusted the order of those executions from `b -> a` to `a->b`
a. `protocol.registerSchemesAsPrivileged`
b `app.setPath('userData', ...)`

So I recover the order, and my problem resolved! fetch API works fine in my custom scheme.

---

@YurySolovyov I'm not sure it is the truth. If it's requirement to call `protocol.registerSchemesAsPrivileged` **AFTER** app's userData path setup in one lifecycle of electron app, we should modify document rather than code.

**Comment by RewriteH** [comment]
> Seems it does not work.
> 
> Weird thing is that it works in development, but not in production build (using electron builder)
> 
> I tried pretty much every possible and reasonable combination of privileges with `protocol.registerSchemesAsPrivileged` and tried with every possible protocol type `registerStreamProtocol`, etc.
> 
> I tried never resolving protocols (that never call callback), etc.
> 
> It works correctly in development (aka app name is "Electron"), but does not in prodcution, I always get the error
> 
> ```
> Fetch API cannot load my-protocol://fooo. URL scheme "my-protocol" is not supported.
> (anonymous) @ index-dd457f44.js:73
> (anonymous) @ VM27:1
> Promise {<rejected>: TypeError: Failed to fetch
>     at file:///Users/adam/dev/projects/aaa/app/electron-dist/ma…}
> index-dd457f44.js:73    Uncaught (in promise) TypeError: Failed to fetch
>     at index-dd457f44.js:73:368
>     at <anonymous>:1:1
> ```

Faced same problem. Seems like Sentry (error tracker we are using) is calling `registerSchemesAsPrivileged` under the hood which cause to lost previous `registerSchemesAsPrivileged` call, if you calling it before Sentry initialization.

**Comment by RewriteH** [comment]
> Seems it does not work.
> 
> Weird thing is that it works in development, but not in production build (using electron builder)
> 
> I tried pretty much every possible and reasonable combination of privileges with `protocol.registerSchemesAsPrivileged` and tried with every possible protocol type `registerStreamProtocol`, etc.
> 
> I tried never resolving protocols (that never call callback), etc.
> 
> It works correctly in development (aka app name is "Electron"), but does not in prodcution, I always get the error
> 
> ```
> Fetch API cannot load my-protocol://fooo. URL scheme "my-protocol" is not supported.
> (anonymous) @ index-dd457f44.js:73
> (anonymous) @ VM27:1
> Promise {<rejected>: TypeError: Failed to fetch
>     at file:///Users/adam/dev/projects/aaa/app/electron-dist/ma…}
> index-dd457f44.js:73    Uncaught (in promise) TypeError: Failed to fetch
>     at index-dd457f44.js:73:368
>     at <anonymous>:1:1
> ```

Faced same problem. Seems like Sentry (error tracker we are using) is calling registerSchemesAsPrivileged under the hood which cause to lost previous registerSchemesAsPrivileged call, if you calling it before Sentry initialization.

**Comment by pie6k** [comment]
The actual issue is that "registerSchemesAsPrivileged" is overwriting all previous calls instead of being additive. 

Because of that, there is some hazard that if some library you use is calling it - depending on who's first, some protocols will get lost.

That was the case with Sentry. And it is also why it was working in development but not in production (because I only initialize Sentry in production).

The only solution that worked for me was to check Sentry source code and "overwrite" protocols with both my protocols and theirs at once.

At the very least - it would be good if the function would warn if calling it is erasing some previously registered protocol. With that it would be instantly clear what happens.

**Comment by Jonovono** [comment]
@pie6k it's crazy this is still an issue. Just spent hours debugging why my electron app custom protocol was working in dev, but not in production. Turned out like you said, sentry... and then aptabase.

Is there a recommended way to deal with this?

**Comment by Jonovono** [comment]
Doing something like this seems to be working:

```
    yield* Effect.sync(() => {
      // Register all protocols as privileged
      protocol.registerSchemesAsPrivileged(DEFAULT_SSR_PROTOCOLS)

      // Store a reference to our protocols that we want to ensure are always registered
      const ourProtocols = [...DEFAULT_SSR_PROTOCOLS]

      // Proxy the registerSchemesAsPrivileged function to ensure our protocols are always included
      // This prevents libraries like Sentry from overwriting our protocols
      const originalRegisterSchemesAsPrivileged = protocol.registerSchemesAsPrivileged

      console.log('🔄 Original registerSchemesAsPrivileged', originalRegisterSchemesAsPrivileged)

      // Override the function with our proxy
      // @ts-ignore - Type issues with Proxy in this context
      protocol.registerSchemesAsPrivileged = function (customSchemes: CustomScheme[]) {
        console.log('🔄 Registering custom schemes', customSchemes)
        // Get unique schemes by merging our protocols with the new ones
        const existingSchemes = ourProtocols.map((p) => p.scheme)
        const filteredNewSchemes = customSchemes.filter((p) => !existingSchemes.includes(p.scheme))
        const combinedSchemes = [...ourProtocols, ...filteredNewSchemes]

        // Call the original function with the combined schemes
        return originalRegisterSchemesAsPrivileged.call(this, combinedSchemes)
      }
    })
```

Got this from sentry source code:

```
function configureProtocol(client, options) {
    if (electron.app.isReady()) {
        throw new Error("Sentry SDK should be initialized before the Electron app 'ready' event is fired");
    }
    electron.protocol.registerSchemesAsPrivileged([SENTRY_CUSTOM_SCHEME]);
    // We Proxy this function so that later user calls to registerSchemesAsPrivileged don't overwrite our custom scheme
    // eslint-disable-next-line @typescript-eslint/unbound-method
    electron.protocol.registerSchemesAsPrivileged = new Proxy(electron.protocol.registerSchemesAsPrivileged, {
        apply: (target, __, args) => {
            target([...args[0], SENTRY_CUSTOM_SCHEME]);
        },
    });
```

**Comment by dnets** [comment]
That fixed it for me (following example is for static:// protocol)
import { protocol } from "electron"

protocol.registerSchemesAsPrivileged([
    { scheme: "static", privileges: { supportFetchAPI: true } },
]);
