### ISSUE TITLE
Content of offscreen rendering window is not resized

### ISSUE THREAD

**Issue by vinebrancho** [electron/electron#6807]
- Electron version: 1.3.3
- Operating system: Linux

Hello, 

I am checking offscreen rendering feature, which started to be supported from 1.3.3.
When I resize app window of offscreen rendering type, the app window is resized well and resize event is also emitted well.
But its content is not resized like the following and innerWidth and innerHeight of 'window' object is also not changed.

![nemo_kakaotalk_20160811_173205814](https://cloud.githubusercontent.com/assets/7057512/17583028/e75b5ab8-5fe9-11e6-97ed-1d7fda2cab1f.jpg)
(I didn't capture image of app due to my system issue, so just took a picture)

Is it desired behavior of Offscreen Rendering in electron?

**Comment by gerhardberger** [comment]
are you running offscreen rendering in GPU-accelerated mode? because in that case, the dummy window we show, displays the offscreen-rendered website instead of the default text shown on macOS or in software output mode, that's why it doesn't respond to resize events.

when you use offscreen-render you should hide this browser window, because its purpose is that it renders into bitmaps you can access through the `'paint'` event on `WebContents`. it is just a side effect that on Windows in GPU mode it shows the website too.

**Comment by zcbenz** [comment]
I'm closing this since the behavior is expected.
