### ISSUE TITLE
Allow positioning title bar style on Mac

### ISSUE THREAD

**Issue by natew** [electron/electron#6821]
We currently have a header that is taller than average, and titlebar style inset looks like this:

![image](https://cloud.githubusercontent.com/assets/12100/17607839/4fec8a3c-5fdd-11e6-856e-58b6a7089fe9.png)

Proposal: Allow passing in coordinates to position the titlebar controls. Don't have a patch yet for you, but if interested I could start on it.

**Comment by zcbenz** [comment]
The APIs provided by macOS only allow us to set the titlebar in two styles, i.e. `hidden` and `hidden-inset`, I don't know a way to perfectly reposition the buttons to arbitrary place, and I'm closing this as won't fix since it is very difficult to implement and we will not work on this.

But it you have an idea on implement this, feel free to send a pull request and we would be happy to merge.
