### ISSUE TITLE
How to capture stdout?

### ISSUE THREAD

**Issue by rgl** [electron/electron#683]
I'm trying to capture stdout/stderr but for some reason it does not really work:

  atom-shell-v0.17.1-win32-ia32/atom.exe --version 2>/dev/null 2>&1

I can still see the output... what is going on? how can I make it work correctly?

**Comment by mikkorantalainen** [comment]
I'm not sure which command shell you're using but at least POSIX shells interpret `executable 2>/dev/null 2>&1` to mean that default stderr should be redirected to /dev/null and then default stderr should be connected to stdout. That is, you're redirecting the stderr twice which results to the latter setting to remain effective. If you want to make the program fully silent, you want `... > /dev/null 2>&1` which first redirects *stdout* to /dev/null and then connects stderr to stdout (to be exact, the current end point of stdout which is /dev/null). If you want to capture all output to a file, just use real file instead of /dev/null.

**Comment by zeke** [comment]
Related: https://github.com/juliangruber/electron-stream by @juliangruber
