### ISSUE TITLE
webfontloader in BrowserWindow doesn't work

### ISSUE THREAD

**Issue by kreck** [electron/electron#6884]
* Electron version: v1.3.3
* Operating system: Mac OS X El Capitan 10.11.3

I couldn't find anything on the web, in the issues or anywhere else, so an issue it is.

**Situation**: I'm running an Angular 1 application in an Electron BrowserWindow. What i need to do is dynamic font loading, so i opted for [WebFontLoader](https://github.com/typekit/webfontloader).

**Issue** WebFontloader does not work in the BrowswerWindow, throwing `Uncaught ReferenceError: WebFont is not defined` when i try to access `WebFont`

**What i tried**
- Check that WebFontLoader works in Chrome, Safari and Firefox, both when loading from CDN or from disk (bower package).  It does in all cases and scenarios.
- Make sure that the library is loaded correctly and that the issue is not due to asynchronous loading of the library
- Adjust the BrowserWindow `webPreferences` and `webSecurity` settings, basically allowing anything. Didn't help.
- Check if the --enable-logging command line switch gives some helpful insights. It didn't.

Any help resolving this is much appreciated.

**Comment by kevinsawicki** [comment]
Have you tried disabling `nodeIntegration` on the `BrowserWindow`?

It looks like `WebFont` does not set globals when required in a node context.

https://github.com/typekit/webfontloader/blob/da5faa9f5262188e33000b33b0b9dfc271b5e97c/src/core/initialize.js#L89-L91

You can either disable `nodeIntegration` on `webPreferences` or bundle `WebFontLoader` directly in your app and do `window.WebFont = require('./vendor/webfont')` in a `preload` script to make it global.

This is very similar to #254, closing this out since this is a `WebFontLoader` issue.

**Comment by kreck** [comment]
@kevinsawicki thanks a lot. Disabling node integration does the trick. However, as i **need node integration** my solution is as follows (if anyone ever has the same problem):

1. install WebFontLoader via npm
2. in your BrowserWindow's JavaScript
```javascript
var WebFont = require('webfontloader');
window.WebFont = WebFont;
````
3. Be happy and access `WebFont` in your `BrowserWindow` context

As you mentioned the solution similar to the one for #254
