### ISSUE TITLE
DonwloadItem fires "done" event with state "completed" on aborted transfer

### ISSUE THREAD

**Issue by bodewig** [electron/electron#6943]
* Electron version: 1.3.2
* Operating system: Win7, Mac OS X 10.10

When I cut the network connection while a download is in progress I expect to receive an `updated` event with state `interrupted` - and in fact this seem to happen on Win10. On Win7 and Mac OS I receive a `done` event with state `completed` instead.

**Comment by zcbenz** [comment]
Whether the connection is interrupted is defined by the operating system, for apps there is no reliable to way to know whether the download is really completed or caused by network abort. Electron is just returning the result got from Chromium, there is probably a way to improve on this, but I suggest reporting it to Chromium's issues list instead.

**Comment by bodewig** [comment]
Opened https://bugs.chromium.org/p/chromium/issues/detail?id=648249
