### ISSUE TITLE
Provide a way to detect when app is launched via an OS X open

### ISSUE THREAD

**Issue by rgbkrk** [electron/electron#7037]
* Electron version: 1.1.3
* Operating system: OS X

We're running into an issue where command line parameter behavior is different when packaged vs. run in dev mode. When running locally in dev mode, arguments come the standard argv way which means we handle them in the `ready` event.

When packaged, arguments end up going to the  `open-file` event (cool!), yet we still end up with the `ready` event being fired and processing the argv. Our default mode is to open a fresh new file. At this point, we don't know if the `open-file` event is going to happen later as a result of running it from the command line.

Are we missing a way of handling this or does it need adaptation in Electron?

**Comment by zcbenz** [comment]
From application side there is not much information we can know on how the application is started. So if the app is launched because user wants to open a file with it, the `open-file` event will be emitted before the `ready` event, otherwise it would be emitted after.

I recommend reading Atom's code on opening file, it shows how to handle `open-file` and `process.argv` at the same time:
https://github.com/atom/atom/blob/master/src/main-process/main.js

**Comment by rgbkrk** [comment]
Thank you @zcbenz!
