### ISSUE TITLE
[Custom protocol] Can't access to file on C:/ with ajax

### ISSUE THREAD

**Issue by Sential** [electron/electron#7055]
* Electron version: 1.3.4
* Operating system: Windows 10
Hi, I'm writing my internet browser, and I need to read C:/userdata/history.json from custom protocol. It's loading all resources like js and css files. My code to register custom protocol in main process:
```
protocol.registerStandardSchemes(['webexpress'])
app.on('ready', function() {
    protocol.registerFileProtocol('webexpress', (request, callback) => {
        var url = request.url.substr(13)
        var lastChar = url.substr(url.length - 1)
        var s = url.split("/");
        if (lastChar != "/") {
            url = url.replace(s[0], "")
        }
        if (lastChar == "/") {
            url = url.substring(0, url.length - 1)
            url += ".html"
        }
        console.log(request);
        callback({
            path: path.normalize(`${__dirname}/${url}`)
        })
    }, (error) => {
        if (error) console.error('Failed to register protocol')
    })
    createWindow();
});
```

code to history.js (webexpress://history)
```
$.ajax({
    type: "GET",
    url: "/userdata/history.json",
    success: function(data) {
     ...
     }
});

```

The error is `Failed to load resource: net::ERR_FILE_NOT_FOUND: webexpress://history/userdata/history.json `

**Comment by nathanjdawson** [comment]
Does this not belong at a help website like Stackoverflow? Doesn't seem like an inherent problem with Electrons codebase.

**Comment by MarshallOfSound** [comment]
Questions should go to the Discussion Forums or to Slack.  Electron's github issues are meant for bugs.

**Comment by MarshallOfSound** [comment]
Should point out I closed this as it appears to be the users code that is buggy / incorrect not a flaw / bug inside electron.

**Comment by phpmaps** [comment]
@MarshallOfSound can this actually be a topic in Electron documentation?  I too am pained by this subject and think @Sential a 15 year old vet programmer and myself cannot be too off base.  I would even say the above code is not too buggy and flawed; rather suspect JS libs which commonly help make AJAX data requests may not be cut our for custom protocols and there are things that need to be considered, right?

**Comment by nathanjdawson** [comment]
@phpmaps that's satire, right?

**Comment by phpmaps** [comment]
@nathanjdawson - No.  When making AJAX requests to a custom protocol from a [long standing JS lib](https://developers.arcgis.com/javascript/3/) (around since before electron) - I discovered an issue in its ```request module``` where the lib was interrogating the URL and based on some business logic changing it to

```http://atom://``` or ```https://atom://```

this was solved by patching the dojo based JS lib.

```
aspect.before(urlUtils, "hasSameOrigin", (url1, url2, ignoreProtocol) => {
  if (url2.substring(0, 15) === "http://globe://") { //Fixes bug which prevents xhr requests to custom protocals   
    url2 = url2.substring(7, url2.length)
  }
  return [url1, url2, ignoreProtocol];
});
```

The more electron relevant issue, had to do with understanding where Electron proc runs in development and production mode and creating proper paths to the files being served.  

```
if (process.env.NODE_ENV === 'development') {
            this._resourcePath = path.join(__dirname, '..', 'resource', 'users.json')
}
```

In dev mode Electron runs from some place in the ```node_modules``` folder.  This is sometimes tricky because the resource being served via the custom protocol may or may not be on the path you think (may be up one folder).  Who pays attention to whats in the node_modules folder.

I do believe Electron does document the path which it executes from in ```node_modules``` but at the time I completely forgot.  Hence, the ugly ``` Failed to load resource: net::ERR_FILE_NOT_FOUND.```

Also I think there may be CORS considerations.  If a request lib, requires a JS developer to register CORS enabled devices I think this too played into some of the hurdles I faced at the time.
