### ISSUE TITLE
Buffer is globally available when node integration is disabled

### ISSUE THREAD

**Issue by eric-naguras** [electron/electron#7081]
[Archive.zip](https://github.com/electron/electron/files/453259/Archive.zip)
- Electron version:  1.3.4 ( same in 0.37.8)
- Operating system: OSX 10.11.6

From one day to another my Electron app cannot load and display a specific web page anymore.
The page https://ctoption.com/ does load some scripts but does not contain any useful HTML. 

The page does load normally in Chromium so something is different from the Electron version of the browser.

This is related to issue #7047. The solution there did not work. I opened a new issue instead of reopening because my question in #7047 was apparently not really the problem.

I need to display the page in a _webview_ as my app has more pages, all inside a _webview_.

This problem is breaking my existing Electron app so any hacks, work-arounds or other means to show this web page would be very appreciated.

Added zip with a sample app.

**main.js**

```
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL(`file://${__dirname}/index.html`)

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}
app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

**index.html**

```
<!DOCTYPE html>
 <html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>

    <h1>Hello World!</h1>
    <webview partition="CTO" preload="./somefile.js" src="https://ctoption.com/" plugins</webview>

    <script src="renderer.js"></script>
  </body>
</html>
```

**Comment by MarshallOfSound** [comment]
Can you provide a minimal app that reproduces the issue?  I know you provided some small code but there is no way anyone is going to dig through the source code of that minified site to try figure out what it is doing to help you. 😢 

From what I can see something must be failing inside your site's JS code that's causing it not to load.  Interestingly in Chrome I get this warning

```
Navigator.pointerEnabled is a non-standard API added for experiments only. It will be removed in near future.
```

When checking inside electron `navigator.pointerEnabled` is indeed `undefined` instead of a `Boolean` as the API indicates it should be.  In other words it looks like you are using a depreceated / unofficial navigator API.

This might not be the issue, and I have no idea what is.  But whatever it is, it is almost certainly an issue with your site and not with Electron.  So as mentioned before without narrowing down what **exactly** on your site is causing the issue there is now way anyone can help you.

I've done the standard check for crashes / error logs and as far as I can tell your site is deciding not to do anything.

**Comment by eric-naguras** [comment]
@MarshallOfSound Thanks for your reply.
I edited my question and added a zip with a sample app that shows the problem.
Cheers.

**Comment by MarshallOfSound** [comment]
@eric-naguras I think you misunderstood.  That isn't a minimal reproduction example as the issue is undoubtedly being caused by the content of https://ctoption.com/ which is minified and unreadable so I have no idea what's going on there.

You need to track down on that site exactly what is causing the issue (I'm assuming that site is yours).

**Comment by eric-naguras** [comment]
@MarshallOfSound https://ctoption.com/  is not my site. There are a few related sites that have the same problem. I was hoping someone would know a work-around.
I did a quick check and the problem does not exist in NW.
So it has to do with the way Electron is using Chromium I guess.
In my Chromium browser (on a Mac) there is also no problem.

This issue is screwing up my app so I might need to port to NW which I really don't like to do but I don't have much choice as there users who can't use my app anymore.

**Comment by MarshallOfSound** [comment]
@eric-naguras Is there another website that perhaps doens't have minified JS that has the issue.

I want to help but crawling through minified JS for the issue isn't something I look forward too 😆

**Comment by eric-naguras** [comment]
@MarshallOfSound All the sites that don't work are using the same platform and have minified javascript. Isn't it possible to see if there are any errors on the Electron side?

Is there anything I can do to help?

**Comment by MarshallOfSound** [comment]
I can't get any errors out of Electron but maybe someone else might have more luck.

> All the sites that don't work are using the same platform 

Which platform is this?

**Comment by eric-naguras** [comment]
It's a platform for binary option brokers called Panda http://pandats.com/
I am not a broker, I created an app to automate trading on brokers web sites.
But suddenly this ctoption.com (and a few others) won't load anymore.

It must have something to with the way their server sees the request.
If you switch off javascript in Chromium (on my Mac) then you will have the same effect in a desktop browser.

**Comment by eric-naguras** [comment]
Hmm, strange. Today I am able to load the web site in Chromium with Javascript switched off.
Yesterday I had the exact same issue as in Electron.

**Comment by deepak1556** [comment]
After verifying the net-log traces between chromium and electron, the site seems to expect a cookie set initially by the document for further requests. Apparently this cookie is not set in electron, need to dig through the site's code. The following is temporary workaround.

```
session.defaultSession.webRequest.onBeforeSendHeaders((details, callback) => {
    if (details.url == 'https://ctoption.com/') {
      details.requestHeaders.cookie = 'rbzid=RkVMYzhOTC9mMDBPQzZFaVN2L1lXb2piUlNDbWNzZzJHNHhKUEtaaU1QdDZwWFM4bi9hUWNwSGVPZnhVTHpRZnFZL0kzTkxsOFk5clNIdTRVanJDZjQrRXM5Q1JGVUl2UGVrMVBoWFhMVWs1U0ZySEpSaVJ1bHZiR2JZZWFMYzdCYXNrRHltYzJBc0xLRjNua2hGOXFEenNHZmFZaHgxK0lvOE55cnozbUFpTTAzVnRXaUxHUVYzWWRiWXp3d1cyMXg4dmNVRjdHaHZNaC9xNnZiUllOUT09QEBANEBAQC00MDc0MDc0MDM3MA--; _icl_current_language=en; _ga=GA1.2.1237818777.1472901637; __lc.visitor_id.2550231=S1472901640.5fbea76541; lc_window_state=minimized'
      callback({requestHeaders: details.requestHeaders})
    } else {
      callback({cancel: false})
    }
  })
```

**Comment by MarshallOfSound** [comment]
@deepak1556 @eric-naguras I have good news I tracked it down to one line of code inside the minified logic on their website.

```js
window.Buffer
```

Basically they are not setting the initial cookies if certain things exist on the window object, one of those things is `window.Buffer`

Calling `window.Buffer = null` in the preload script makes the website load correctly 👍 

Considering this is website specific code (nothing to do with Electron) I think we should close this issue out @deepak1556 ?

FWIW @eric-naguras It looks like that code is being used to identify if the website is running in a test suite or not.  I made that assumption because it checks for the following things

```js
var U = "domAutomationController";
var b = "domAutomation";
var D = "webdriver";
var k = "spawn";
var Q = "emit";
var H = "Buffer";
var y = "__phantomas";
var o = "callPhantom";
var M = "_phantom";
```

**Comment by deepak1556** [comment]
@MarshallOfSound awesome, thanks for tracking it down! I think its safe to close this issue now.

**Comment by eric-naguras** [comment]
@MarshallOfSound and @deepak1556 thank you so much for helping out.
Just out of curiosity, why do the desktop versions of most browsers (including Chromium) have no problem loading the page but Electron does.

**Comment by MarshallOfSound** [comment]
@eric-naguras Electron creates a `window.Buffer` object for some reason.  No idea why, but Chrome and Firefox and such don't

**Comment by deepak1556** [comment]
Even with `nodeIntegration: false` the Buffer object is present, I think this might be a bug. Sorry for closing it early. Will defer to others for thoughts.

**Comment by MarshallOfSound** [comment]
@deepak1556 It looks like it is used in quite a few places

https://github.com/electron/electron/blob/master/lib/common/asar.js#L40
https://github.com/electron/electron/blob/master/lib/common/asar.js#L466
https://github.com/electron/electron/blob/master/lib/browser/rpc-server.js#L94
https://github.com/electron/electron/blob/master/lib/browser/chrome-extension.js#L85

Just to list a few.  I don't think we can decouple `Buffer` from the window object.  Is having Buffer globally available a concern with `nodeIntergration` set to false?

**Comment by deepak1556** [comment]
> Is having Buffer globally available a concern with nodeIntergration set to false?

Just that without nodeIntegration it shouldn't affect a site which loads without concern on chromium.

**Comment by MarshallOfSound** [comment]
> Just that without nodeIntegration it shouldn't affect a site which loads without concern on chromium.

Fair enough, I updated the issue so it's more obvious what needs to be fixed.  Not sure how we could fix it though, might have to dig into why Buffer is global 👍
