### ISSUE TITLE
 Sending Ctrl+Z keyboard event

### ISSUE THREAD

**Issue by Planeshifter** [electron/electron#7089]
I would like to use the `sendInputEvent` method to send `Ctrl+Z`. According to the [docs](https://github.com/electron/electron/blob/master/docs/api/web-contents.md),  I thought that the following should work, but it does not:

``` javascript
browserWindow.webContents.sendInputEvent({
	type: 'keyUp',
	keyCode: 'Z',
	modifiers: [ 'control' ]
});
browserWindow.webContents.sendInputEvent({
	type: 'keyDown',
	keyCode: 'Z',
	modifiers: [ 'control' ]
});
```
Sending characters works fine, but I have trouble as soon as I start using the `modifiers` option. For example, I would expect that the following code would send a `R` character, but I only get `r`.

``` javascript
browserWindow.webContents.sendInputEvent({
	type: 'char',
	keyCode: 'r',
	modifiers: [ 'shift' ]
});
```

Am I doing something wrong or is `modifiers`  not fully supported yet?

I am on Ubuntu and use the latest Electron release `1.3.5`.

**Comment by brenca** [comment]
Chromium actually needs events for the modifier keys too (which is closer to what actually happens when you press `Ctrl+Z`)

``` JavaScript
browserWindow.webContents.sendInputEvent({
    type: 'keyDown',
    keyCode: 'Ctrl'
});

browserWindow.webContents.sendInputEvent({
    type: 'keyDown',
    keyCode: 'Z',
    modifiers: [ 'control' ]
});

browserWindow.webContents.sendInputEvent({
    type: 'keyUp',
    keyCode: 'Z',
    modifiers: [ 'control' ]
});

browserWindow.webContents.sendInputEvent({
    type: 'keyUp',
    keyCode: 'Ctrl'
});
```

We're forwarding events from SDL, but this should work. (This is what comes in and is being sent 1:1, and I could revert text in an input with this)

The `char` type events expect the actual "string" you want to send, since keyboard layouts can have other stuff on the same key when you press shift, and detecting the keyboard layout is not easy.

I owe you guys a tutorial about sending input events, I'll create one and post it when I have time :)

**Comment by Planeshifter** [comment]
Thank you very much for the fast response! I can confirm that everything works when sending the events for the modifier keys. Closing this issue now, thanks again!
