### ISSUE TITLE
Should electron apps remember full screen state on exit/re-open?

### ISSUE THREAD

**Issue by amancevice** [electron/electron#7106]
* Electron version: N/A
* Operating system: OS X

As a user, I expect OS X apps to remember their window state on exit -- namely whether they are full screen, or if not, what size the window was on exit. When re-opening the app I think it's natural for a user to expect the state to be restored to how he/she left it on exit.

Atom is an example of an electron app that behaves this way. Chrome and iTunes are examples of other apps that also follow this pattern. I believe it should be the default behavior apps built on electron. I welcome discussion & dissent.

**Comment by bengotow** [comment]
It would be interesting to make this default behavior. I don't think we could use it out of the box in N1 because certain actions, like opening additional windows, cause the app to "pop" out of fullscreen or span multiple spaces. (So your application code needs to be aware that it's in fullscreen mode.) Seems like it would likely work for the majority of Electron apps, though.

**Comment by lee-dohm** [comment]
There are a number of things that Electron doesn't do for application authors that are considered "standard practice" for some types of applications on some platforms. For reference, see [all the comments in the sample code in the Quick Start guide](http://electron.atom.io/docs/tutorial/quick-start/#write-your-first-electron-app). Because we can't know ahead of time what type of application people have in mind, we don't feel it is appropriate to make those decisions on behalf of application authors.

Additionally, it is common for application frameworks to not do this on behalf of application authors. Even OS X applications have to [do this for themselves](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/WinPanel/Tasks/SavingWindowPosition.html), it doesn't happen by default.

As such, as was [stated previously](https://github.com/electron/electron/issues/526), we have no API for this and no plans to create one.

Thanks very much for your feedback and interest in Electron!

**Comment by amancevice** [comment]
Thanks @lee-dohm I had not seen issue #526 in my searches for previously filed issues. If I had I wouldn't have opened this one. I appreciate the response!
