### ISSUE TITLE
beginFrameSubscription cropped for WebView WebContents on HiDPI screens

### ISSUE THREAD

**Issue by IsaiahJTurner** [electron/electron#7158]
This issue can be reproduced in the latest Electron version on a Retina device. Essentially, only the top left fourth of the screen's pixels are returned on retina screens.

I presume this happens because beginFrameSubscription, even on mainWindow, does not return retina pixel data ever.

Issue arrises after: https://github.com/electron/libchromiumcontent/pull/227

Issue description: https://github.com/electron/electron/issues/5665#issuecomment-245813684

**Comment by gerhardberger** [comment]
I created a PR with the fix.

I only tested it on macOS, so Windows needs testing. cc @brenca 

Note that I also changed the API so the callback passes a [NativeImage](https://github.com/electron/electron/blob/master/docs/api/native-image.md) instead of a `Buffer`, but I think it's just makes it easier for you too.

**Comment by brenca** [comment]
I don't have a HighDPI screen, but the code does compile and the size of the returned image seems alright. Thanks @gerhardberger for fixing this! We shall split the original bounty, if that's okay with @IsaiahJTurner.

**Comment by zcbenz** [comment]
Fixed with #7163.
