### ISSUE TITLE
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window'

### ISSUE THREAD

**Issue by drFabio** [electron/electron#7161]
* Electron version:  1.3.4 
* Operating system: Windows 7
This error happened inside a preload with the following format:
```javaScript
process.once('loaded', () => {
   //Other code
    localStorage.setItem('SOME_PROPERTY',data)
})
````
This preload works on my machine (and several others) but on a specific machine it's showing that on console.

I did a little bit of research and it is a [chromium configuration](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document). Does the global chrome configuration can affect electron.
Can this be something regarding a proxy or antiVirus or something like that?

Thanks in advance

**Comment by deepak1556** [comment]
> Does the global chrome configuration can affect electron.

Nope, Electron does not follow the content settings configuration of chrome.

> Can this be something regarding a proxy

Can't say for sure without logs, you could provide `log-net-log` trace. Also `loaded` event of process doesn't gurantee successful page load, the error is most likely caused by failure in page load which you can verify with `did-fail-load` event.

Closing this out since its not a bug in Electron, can reopen if you think its a bug with reproducible example.

**Comment by drFabio** [comment]
I guess it's not an error on electron . Thanks will check the event
