### ISSUE TITLE
showDefinitionForSelection offset in webview

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#7164]
- Electron version: Any
- Operating system: macOS
1. Create a webview tag and offset it horizontally or vertically (using `position: relative` or `flex` or really anything).
2. Call `showDefinitionForSelection` on some text content in the `webview`.

The overlay appears offset from the word, and that offset is equal to the offset applied to the webview:

![](https://cloud.githubusercontent.com/assets/1791449/17414494/8390f9ac-5a3a-11e6-875c-f6f958c1d50a.png)

**Comment by tborychowski** [comment]
this happens to me too. seems to be caused by the `webview` offset from the main (parent) window. If the `webview` starts in 0,0 px, it works.
I've hacked it by positioning my `webview` like that, and then setting the padding of the loaded html to offset my sidebar. But this is far from ideal.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
