### ISSUE TITLE
Apps looks like no using video aceleration 

### ISSUE THREAD

**Issue by Pollito001** [electron/electron#7194]
* Electron version: 1.3  
* Operating system: Manjaro Linux

**Comment by MarshallOfSound** [comment]
> Apps looks like no using video acceleration

Lot's of apps specifically disable hardware acceleration.  Do you have any examples / evidence that show Electron isn't using hardware acceleration?

**Comment by Pollito001** [comment]
I mean when use nativefier, apps look tearing and slow.

**Comment by zcbenz** [comment]
nativefier is using an old version of Electron and that's probably the reason. If you got nativefier to use a more recent version and the problem is still there, please report back with following information:

* How dose chromium-browser behave on your machine.
* Does the electron-prebuilt package have the same problem.
