### ISSUE TITLE
Arrow keys don't work in open/save file sheet when defined as menu accelerators

### ISSUE THREAD

**Issue by yishn** [electron/electron#7248]
* Electron version: v1.4.0
* Operating system: macOS 10.11.6

If you set 'Up', 'Down', 'Left' or 'Right' as menu item accelerators in the application menu, the corresponding arrow keys won't work in the native open/save file sheet for navigating. By 'sheet' I mean they are attached to the window. Other accelerators, like 'Command+F', are working as expected, even if defined as menu item accelerators.

**Comment by zcbenz** [comment]
Those accelerators are handled inside the sheet view and do not rely on menus to work.

I tried to run `remote.dialog.showOpenDialog(remote.getCurrentWindow())` in devtools of the default app, and arrow keys work there.

**Comment by yishn** [comment]
You may have misunderstood me. To replicate my issue, add the following menu item to, say, the 'View' menu of the default app:

~~~js
{
  label: 'Blah',
  accelerator: 'Up',
  click() {
    // Some code I want to execute if the user presses the up key
  }
}
~~~

Then run `remote.dialog.showOpenDialog(remote.getCurrentWindow())` in devtools of the default app and notice that the up arrow doesn't work as expected.

**Comment by zcbenz** [comment]
That's expected behavior, your menu item has captured the key event and now the dialog view is no longer to respond to the event. It can not be solved with our current API, even if you use Cocoa to write a native app it would still be very nasty to solve.

The correct way to do this is to handle the arrow keys with DOM events, so it does not mess up with other native components.
