### ISSUE TITLE
Example of using webContents.beginFrameSubscription

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#7250]
I'm having trouble using the `webContents.beginFrameSubscription` API.

I get the buffer but have been unable to find a way to convert this to something usable like a `jpg` or `png`, or by creating a video by piping to `ffmpeg`.

Any ideas?

**Comment by gerhardberger** [comment]
As I can see, there is no way currently to turn a bitmap buffer into a `NativeImage` object as it only tries to decode PNG or JPEG buffers in `createFromBuffer`.

We could extend the capabilities of `nativeImage.createFromBuffer` to handle bitmap buffers, or add a different method like `createFromBitmap` to `NativeImage`. In the future frame subscription will emit a `NativeImage` object by default (maybe we could make it optionally available sooner) though.

Maybe you could use offscreen rendering, because that emits `NativeImage` objects by default and much better performance-wise, especially if you want to create video from it.

**Comment by brian-mann** [comment]
Using offscreen rendering did indeed satisfy my requirements. I'm able to pipe the frames to `ffmpeg` and it works great.

I noticed a couple things however: using `image.toPNG` is much more expensive than `image.toJPEG`.

Also it seems `image.getBitmap` is definitely the fastest but I was unable to figure out a way to get that buffer into `ffmpeg` happily.

I know that they are 32bit BGRA but setting `pix_fmt=bgra` didn't work.

**Comment by super-ienien** [comment]
Try pix_fmt=rgb32

**Comment by lklepner** [comment]
@brian-mann could you provide an example of how you are passing the buffer to ffmpeg?

**Comment by fractalawareness** [comment]
@brian-mann can you provide an example?

**Comment by dotansimha** [comment]
@brian-mann can you please share a working example? :)

**Comment by JayFish** [comment]
> @brian-mann can you please share a working example? :)

This is old but I once had to go very deep to get this to work and I couldn't find answer back then so here it is: I send png image captures from renderer thru main to ffmpeg process's stdin like this:

"ffmpeg -f rawvideo -pixel_format rgba -s <frame size> -r <frame rate> -i -" <add output stuff>
