### ISSUE TITLE
webContents.send slow for large objects

### ISSUE THREAD

**Issue by obecny** [electron/electron#7286]
- Electron version: from 1.3.4 to 1.4.0
- Operating system: osx, windows 10

When I try to send the bigger object from "main" to "renderer" and if this object has any circular dependancy etc. the whole app simply hangs.
However It is working fine in ver 1.3.3 

`...webContents.send("myEventName", bigObjWithCircularDep);`

I think this should either work as in 1.3.3 or should raise some error about circular dependency or it should simply remove the circular dependancy. Any solution would be better then allowing for hanging the whole app.

thank you

**Comment by kevinsawicki** [comment]
Can you include an example object (perhaps as a json snippet) that worked well in 1.3.3 but is slower in 1.3.4 and beyond?

There were changes in 1.3.4 and 1.3.5 to better detect cycles in objects so that objects and arrays weren't incorrectly nulled out when referenced multiple times but not cyclical.

https://github.com/electron/electron/pull/6776 and https://github.com/electron/electron/pull/6977 are the two relevant pull requests.

These changes did cause more fields that could be serialized to be included in the payload sent over IPC instead of just omitting them. Previously these values were just nulled out which caused confusion and unpredictability about what would get sent over.

**Comment by obecny** [comment]
here it is:
https://gist.github.com/obecny/ccd5c0cf52d3a30109172aabad0cf6bc#file-electron_send_test

**Comment by Mr0grog** [comment]
It looks like some users of Nightmare (an automated browser based on Electron) are also hitting this issue: https://github.com/segmentio/nightmare/issues/862 (in the example there, attempting to send an object with an AngularJS `$scope` object attached to it over IPC is causing the hang).

If it helps, the raw Electron code that matches the linked Nightmare issue is:

```js
const electron = require('electron');

electron.app.on('ready', function() {
  mainWindow = new electron.BrowserWindow({
    show: true,
    webPreferences: {
      nodeIntegration: false
    }
  });
  mainWindow.webContents.loadURL('http://www.muzeroom.com/');
  mainWindow.webContents.on('did-finish-load', function() {
    setTimeout(() => {
      console.log('Attempting to log an AngularJS $scope object...');
      mainWindow.webContents.executeJavaScript(
        `var element = document.querySelectorAll('.story-list-item')[0];
        Object.getOwnPropertyNames(element).map(name => element[name]);`,
        function (result) {
          console.log('DONE:', result);
          process.exit(0);
        });
    }, 1000);
  });
});
```

The above is fine in 1.3.4 and earlier, but hangs in versions after 1.3.5.

**Comment by obecny** [comment]
@kevinsawicki I have posted the gist long time ago but this issue is still marked as `more-information-needed` what else do you need then ? thx

**Comment by zcbenz** [comment]
Sending a large object via IPC is slow and there is no way to improve that, a common solution is to use shared memory but that's another story.

It was not slow for certain objects because they were simply stripped, and that was a bug. Since the only way to improve the situation is to revert the fix, I'm afraid I have to close this as won't fix.

As work around, I suggest stripping the object before sending it via IPC.

**Comment by Mr0grog** [comment]
@zcbenz is there any feasible way to detect that an object will be too big and throw an exception? (Or at the very least log a warning?) In the example above, the entire process hangs for *minutes* as a result of the JS call and it is not clear to most people why. I have trouble imagining the scenario where that's useful. I think, for many users, it's very unclear what's going wrong when they wind up in this situation.
