### ISSUE TITLE
process.stderr.write("string") writes true to console

### ISSUE THREAD

**Issue by s-a** [electron/electron#7360]
* Electron version: 1..4.1
* Operating system: Windows 10

ref.: https://github.com/s-a/iron-node/issues/115

**Comment by kevinsawicki** [comment]
I believe this is expected behavior when running `process.stderr.write()` from the Console tab of the dev tools.

`process.stderr` is a `WritableStream` and the return value of `WritableStream.write` is a boolean which is why you see `true` displayed. You can reproduce this in node as well by running `node -e "console.log(process.stderr.write(''))"` from a Terminal which produces the output of `true`.

https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_writable_write_chunk_encoding_callback

Closing this out.
