### ISSUE TITLE
STL files are unselectable on open dialog on linux

### ISSUE THREAD

**Issue by CoDanny** [electron/electron#7368]
* Electron version: 1.4.1
* Operating system: Ubuntu

I'm launching an open file dialog like this:

```
    const result = dialog.showOpenDialog(
      this.mainWindow,
      {
        title: 'Select your model file',
        filters: [
            {name: '3D Models', extensions: ['stl','apf']},
            {name: '3D Print Files', extensions: ['gcode', 'gco', 'g', 'x3g']}
        ],
        properties: [ 'openFile', 'openDirectory' ]
      }
    );
```

The files are shown but are unselectable.

![4b4d7f54-7a86-11e6-8ff1-aff6edaf3f9b](https://cloud.githubusercontent.com/assets/542760/18893769/89136b80-850f-11e6-8a41-80d57a8036c8.gif)

It only happens in Linux. Works on Mac and Windows.

**Comment by kevinsawicki** [comment]
What version of Ubuntu are you using?

**Comment by CoDanny** [comment]
I have tried in Ubuntu 14.04 and Elementary OS

**Comment by kevinsawicki** [comment]
I think the issue is that you are specifying both `openFile` and `openDirectory`.

Dialogs can't be both on Windows and Linux and default to directories when both are specified on those platforms. I was able to get the filter working by just using `openFile` in the `properties`.

See the note on http://electron.atom.io/docs/api/dialog/#dialogshowopendialogbrowserwindow-options-callback for more details.
