### ISSUE TITLE
Developer DesignView

### ISSUE THREAD

**Issue by DrMabuse23** [electron/electron#738]
Hey Guys,

I trying out the Developer Feature http://etoxin.net/blog/2014/06/25/chrome-38-introduces-a-responsive-design-view/ and still is not working. Any plans in future about that ?

**Comment by codebytere** [comment]
This issue hasn't been touched in about three years, so in service of pruning down the issues tab to a more clear and immediate roadmap for the team i'm going to go ahead and close it. If more activity should arise, however, I can potentially reopen.

**Comment by bscriptsource** [comment]
Hello!!

Greetings of the day.

I have a Web Design & Web Development company and have 8+ years of experience.

Let me know if you have any web design and web development project as well as.
I am ready to start work on your project and gave you 100% quality assured work.

Thanks

**Comment by metal-gabe** [comment]
Just leaving a comment to say that this issue is still happening in Mar/Apr 2021. Ideally, it would be nice to have this re-opened/resolved as those of us who still have smaller monitors (blasphemy! I know...) (but use multiple) could benefit from undocked dev tools to help utilize screen space efficiently. 

Stuff: 
- Electron v9.4.4 
- macOS Big Sur v11.2.3
