### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by makeitcount** [electron/electron#7405]
* Electron version: 1.4.1
* Operating system: Windows
* Electron-builder : 7.9.0

I am facing this frustrating issue for last 1 week. Everything was working fine earlier.
Issue is that when I build executable and run it, the app installs correctly and starts on first instance. When I close the app and start it again, it doesn't work, app does not get launched.

- App works fine when run in development i.e. `electron .`
- There's no exception (I catch uncaughtexception and write that to file)
- I have tried uninstalling app completely and then again installing apps running executable, issue persists
- Have tried earlier version which were working fine earlier, issue persists

Based on above clues I can say that it's not happening because of the app code. On the other hand the app just never starts in Linux. I believe this has something to do with operating system itself.

I have checked task manager, it does not show the app.

What could be the possible reason? How can I figure this one out?

Edit: Squirrel logs, when I try to start the app but it doesn't
```
2016-09-29 17:44:44> Program: Starting Squirrel Updater: --processStart MyElectron App.exe
2016-09-29 17:44:44> Program: Want to launch 'C:\Users\u\AppData\Local\MyElectronApp\app-0.0.45\MyElectron App.exe'
2016-09-29 17:44:44> Program: About to launch: 'C:\Users\u\AppData\Local\MyElectronApp\app-0.0.45\MyElectron App.exe': 
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions / support requests about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

This appears to be a question / issue with the Electron application in question rather than Electron itself.

> I am facing this frustrating issue for last 1 week. Everything was working fine earlier.

Look through your commit log for the last week, a good trick is to just diff 1 week ago to today and see what has changed.   Look for any added `app.exit`, `app.quit` or `process.exit` calls that you may have added.  Things don't just magically stop working there is always a reason 👍 

> What could be the possible reason? How can I figure this one out?

For more advanced debugging try setting the following environment variables and launching from command line
```bash
set ELECTRON_ENABLE_LOGGING=true
set ELECTRON_ENABLE_STACK_DUMPING=true
C:\Users\u\AppData\Local\MyElectronApp\app-0.0.45\MyElectron App.exe
```

**Comment by makeitcount** [comment]
[Solved] 
Thanks @MarshallOfSound , it's fixed now as below
When receiving window closing event, close all the app windows(including hidden one). then call app.quit()
