### ISSUE TITLE
Allow cancelling the navigation in will-navigate events

### ISSUE THREAD

**Issue by Mossop** [electron/electron#7501]
* Electron version: 1.4.2
* Operating system: All

There should be some way to cancel navigation when the will-navigate event fires. As an example in some cases it would be good to open navigations that take the user away from a certain site in a new webview or just block them entirely and there doesn't seem to be a way to do that right now.

**Comment by zcbenz** [comment]
Calling `event.preventDefault()` can cancel the navigation, however we currently don't support it for `<webview>` yet, which is tracked at #1378.

And I'm afraid that issues is not going to be fixed in near future because it is a limitation of Chromium. The only workaround is to get the `WebContents` object of `<webview>` in the main process and handle the event there.
