### ISSUE TITLE
document size not following fullscreen animation when using remote.getCurrentWindow().setFullscreen()

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#7556]
The following way to enter/exit fullscreen behave correctly (html document/body size follows fullscreen animation):
- Entering/exiting fullscreen using the app menu
- Entering/exiting fullscreen using the 3rd of the *window 3 dots* (maximize/fullscreen control)
- Entering/exiting fullscreen using `myBrowserWindow.setFullscreen(true)` in the main process

Here is how it looks like:
https://cl.ly/0Y0f0O0v0L0E (red is a fixed 100% 100% div, grey is the browser-window backgroundColor)

Now, when using `remote.getCurrentWindow().setFullscreen(true)` in a renderer window, here is how it looks like:
https://cl.ly/011l2g3j420q
**The div that should always be filling the window does not *follow* the fullscreen animation when entering (or exiting)**

---

* Electron version: 1.4.3
* Operating system: macOS 10.12 (Sierra)

**Comment by kevinsawicki** [comment]
> The div that should always be filling the window does not follow the fullscreen animation when entering (or exiting)

This is probably expected since using `remote` does a synchronous method call to the main process and the renderer process is blocked until that method returns. Since it is blocked, it probably can't handle events occurring while it is waiting for the main process to return.

Have you tried using the `ipcRenderer`/`ipcMain` modules to send a message to the main process to ask it to go to full screen and then run `setFullScreen` there when that message is sent so that it isn't blocking the renderer process.

**Comment by romaincointepas** [comment]
Using `ipcRenderer / ipcMain` doesn't have this problem indeed, I will switch to this. I always tend to forget that `remote` is sync.

Thanks!
