### ISSUE TITLE
Yosemite toolbar support

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#761]
Just wondering if Yosemite style toolbars could be supported by Atom shell like the new Safari uses.

![screen shot 2014-10-31 at 9 16 33 am](https://cloud.githubusercontent.com/assets/671378/4864072/851a722e-6119-11e4-933d-53f35f620a40.png)

**Comment by max** [comment]
Could we use [indragiek/INAppStoreWindow](https://github.com/indragiek/INAppStoreWindow)? Right now one of the biggest "tells" for non-native Mac apps is the inability to customize `NSWindow`. This could bridge the gap even further.

**Comment by max** [comment]
If the appearance @kevinsawicki suggests isn't possible what about:

![image](https://cloud.githubusercontent.com/assets/111631/7696900/35f1e6c4-fdb7-11e4-8fd4-3a4a52f83105.png)

**Comment by waynebloss** [comment]
I really like the idea of being able to access as much native stuff as possible in Electron. It would be really awesome to have native toolbars in Windows too as well as other native controls like tree views, list views, data grids, etc. If it doesn't get done in the core Electron project, I'm sure somebody will find a way. Edge.js would be one way to integrate higher level UI bindings via .NET/Mono so you could mix Electron with .NET+WinForms/WPF on Windows and Mono+Cocoa on OS X.

@max could you explain what you mean by "inability to customize `NSToolbar`"? Do you mean the developers inability to customize it or the end-user?

The image that you attached looks like it could be done with HTML since it's not drawing in the reserved area (title bar) of the window. (But I'm with you - I really don't want to emulate native stuff in HTML if I don't have to because it's a moving target and breaks easily.)

**Comment by max** [comment]
@waynebloss On the developers side. But now that you mention it, rearranging the toolbar as an end-user would be the :cherries: on top.

Yes, good point. It would be possible to redraw the second screenshot I posted (provided I can get rid of the 1px shadow stroke that the toolbar usually throws). Might give that a shot and report back.

**Comment by joshaber** [comment]
As of 10.10 there are APIs to, e.g., put the toolbar up in the title bar, use a transparent title bar, etc.

So it's certainly *possible* to do these things. I suppose it's a question of whether Electron would want to expose those things, ideologically-speaking, and if so, what the API would look like.
