### ISSUE TITLE
Prerender link relation type not working

### ISSUE THREAD

**Issue by davej** [electron/electron#7624]
* Electron version: 1.4.3
* Operating system: macOS Sierra

The [`prerender` link relation type](https://www.w3.org/TR/resource-hints/#dfn-prerender) doesn't work. Here is a simple reproducible test case: https://gist.github.com/davej/7d9a72ef870263b0879cb14771e6e193

It works as expected when you open it in Chrome 53 but does not prerender in Electron. I tried it with both `http://` urls and `file://` urls, both fail to prerender in Electron.

It would be neat if the prerendered resources were accessible across the entire Electron app and not just from links but I'll create another issue for that (edit: here it is #7625).

**Comment by zcbenz** [comment]
According to the https://www.chromium.org/developers/design-documents/prerender, implementing this in Electron would be very nasty, for example, it is hard to decide how should `will-navigate` event work for prerendering pages, we probably have to add a whole new set of APIs to support it without breaking existing apps.

So I'm closing this as won't fix since it gains us too little compared to the relatively large work.
