### ISSUE TITLE
Uncaught Error: Module did not self-register. source : ELECTRON_ASAR.js

### ISSUE THREAD

**Issue by harivasista** [electron/electron#7693]
* Electron version:1.4.4
* Operating system:Windows 7 x64
I am trying to use edge module to run C# code on electron app. I have built the module using node-gyp and electron-rebuild. Everything is built without any errors. But when I run the application I get the above error in console. Any help regarding this would be appreciated. Thanks.

**Comment by enlight** [comment]
`electron-rebuild` probably rebuilt the module for the wrong Electron version, this can happen if you install `electron` globally instead of locally. Either remove the global installation of Electron and reinstall it locally, or specify the target version when running `electron-rebuild`. 

If the issue persists I suggest seeking help from the [community](https://github.com/electron/electron/blob/master/README.md#community) since this is not an issue with Electron itself.
