### ISSUE TITLE
Add support for chrome 54

### ISSUE THREAD

**Issue by andypham** [electron/electron#7744]
* Electron version: 1.4
* Operating system: Mac OSX 10.10.5

**Comment by MarshallOfSound** [comment]
> The Chrome version of Electron is usually bumped within one or two weeks after a new stable Chrome version gets released. This estimate is not guaranteed and depends on the amount of work involved with upgrading.

http://electron.atom.io/docs/faq/#when-will-electron-upgrade-to-latest-chrome

Chrome 54 is a much larger jump that previous bumps as Chromium moved from `gyp` to `gn` so it will take longer than usual.

You can monitor progress here https://github.com/electron/electron/projects/2

**Comment by WriterDuet** [comment]
Chrome 53 and possibly Chrome 54 had a serious error that resulted in crashes when users were writing in Chinese. It's unclear to me if this has been fixed in Chrome 55, but my users who are on our Electron app are still reporting it, but it is no longer being reported on Chrome 55.

I know you didn't have a specific timeline, but can you give us any insight into the progress of updating to Chrome 54 and then 55. We're now a couple months behind Chrome, and version 55 apparently had huge memory optimizations. See http://v8project.blogspot.ca/2016/10/fall-cleaning-optimizing-v8-memory.html and https://www.prerender.cloud/blog/2016/12/03/chrome-memory-54-vs-55

**Comment by kevinsawicki** [comment]
> I know you didn't have a specific timeline, but can you give us any insight into the progress of updating to Chrome 54 and then 55. 

The specs on all platforms are passing in #7909 so the 54 release should happen in January unless some severe regressions are discovered during testing.

After that release we will then start the process of going to 55.

**Comment by WriterDuet** [comment]
Thank you!!

**Comment by juanlizarazo** [comment]
Woo hoo! beta is coming up

> electron/pull/8406 (...) Going to release this as a beta 1.5.0 to npm now
