### ISSUE TITLE
Garbage collect closed/released functions after window close

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#7771]
* Electron version: 1.4.4
* Operating system: All

It would ease a lot of developers if Electron garbage collected/unreferenced functions that are released. This can happen every time a window is closed because this is when functions can get hanging without being released (and eventually throw errors).

I image this could be implementing by just looping through EventEmitter objects in main process that are exposed in the renderer process and going through their event handlers and checking if a function is closed/released and have the potential to throw an error. If the condition is true then a simple removeEventListener could be performed on the reference.

Currently this is a struggle in Electron development as you should manually do something that could be automated.

**Comment by MarshallOfSound** [comment]
> Currently this is a struggle in Electron development as you should manually do something that could be automated.

I disagree, you should clean up after yourself and ensure you remove your own event listeners.

You can see #5344 (which I actually rose originally) which goes through a discussion regarding this.

You can also read up on #7648 where I'm trying to come up with a way to ignore some of these errors that **can't** be handled manually.

The TLDR of it all is normally you can remove the event listener yourself (and you should) or you can restructure your app so instead of having a cross-process function listener you can have the event listener in your main process that fires IPC events to the renderer process.
