### ISSUE TITLE
Notification icons are being refused due to CSP since electron 1.3.0 on Windows

### ISSUE THREAD

**Issue by gregor** [electron/electron#7772]
- Electron version: 1.3.0 and newer
- Operating system: Windows

The notification on Windows no longer show an icon since electron updated to Chrome 52 with the release `1.3.0`. The issue still exists with the latest build we are using internally, which is `1.4.3`.

A CSP header warning can be found in the browser console, whenever a notification is triggered even after adding the 'filesystem:' keyword to the `img-src` header.

![wrapper_csp](https://cloud.githubusercontent.com/assets/10243309/19771031/cac9acb0-9c61-11e6-907c-18e2eacf42c5.png)

If you want to see it in action, you can build the app from https://github.com/wireapp/wire-desktop

We have previously rolled back to electron `1.2.8` but with Chrome 54 on the horizon this is starting to become a blocking issue for us at Wire. Any ideas what's causing this?

**Comment by kevinsawicki** [comment]
I'm not sure why this stopped working in Chrome 52/Electron 1.3.0 and above but there are at least two different options to get it working again in your app:

1. Add `file:` to your CSP policy
2. Add `require('electron').webFrame.registerURLSchemeAsBypassingCSP('file')` to your preload  script.

Closing this out since this does seem to be the expected behavior in Chrome for the current CSP you are using.

**Comment by gregor** [comment]
@kevinsawicki But according to https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-remote-script the correct keyword to use is `filesystem:` not `file:`. And we have that in place. Will try to register the bypass in our electron app.

**Comment by deepak1556** [comment]
@kevinsawicki not sure of the root cause, will look into it but this seems more like a permanent change on the notification resource fetch path, so users will have to resort to the workarounds you have specified.

@gregor `filesystem:` and `file:` are different schemes, they don't affect each other.

**Comment by deepak1556** [comment]
https://codereview.chromium.org/1847863002 caused the change in notification resource load which now does a CSP check.

**Comment by kevinsawicki** [comment]
> https://codereview.chromium.org/1847863002 caused the change in notification resource load which now does a CSP check.

Good to know, thanks so much for digging this up 👍
