### ISSUE TITLE
Windows created while Moom window manager is active will be transparent

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#7836]
* Electron version: 1.3.8+
* Operating system: macOS

There's probably not much we can do about this (might even be a bug on [Moom](https://manytricks.com/moom/)), but it seems that, for some reason, windows created while this window manager is active always appear transparent. Only their backdrop is visible:

![image](https://cloud.githubusercontent.com/assets/1865957/19899856/c657fc84-a01e-11e6-8ab1-9c3cb6e2d65c.png)

**Comment by zcbenz** [comment]
According to Moom's release notes, they are doing workarounds for Chrome browser:
https://manytricks.com/moom/releasenotes/

So it is very likely that Moom is not compatible with Chrome, and the only solution to solve this is to ask Moom to add your app to its workaround list.

Closing since we can not fix it on our side.
