### ISSUE TITLE
Add event for vetoing SSL certificate validation

### ISSUE THREAD

**Issue by gregnolle** [electron/electron#7891]
I need to be able to apply a whitelist of certificate authorities that my app will support, but then accept any certificate that those CAs have signed.

Currently I'm doing this by using `session.setCertificateVerifyProc` with a function that checks for a whitelisted CA (I've exposed the whole chain in my PR #7889) and then doing full verification of the rest of the chain.

The trouble with this is that the options to do the chain verification aren't great. I can fork a process to an OpenSSL binary (or create a native bridge to OpenSSL) or use the node-forge library. The latter doesn't support ECC certificates though and in both cases I have to worry about certificate revocation checking.

It would be much more preferable if I can allow Chromium to do its normal verification (including its CRLSets checking) but have an event emitted by Electron that allows me to veto a certificate that Chromium is otherwise happy with. This would basically be the reverse of the existing "certificate-error" event (e.g. "certificate-verified" perhaps).

If somebody can give me some pointers on where to emit such a new event then I would be happy to work on a PR myself for this.

**Comment by deepak1556** [comment]
Currently we let `AtomCertVerifier` default to chromium cert verification code path when `session.setCertificateVerifyProc` does not provide a custom callback. Instead of providing a `certificate-verified` event which does not interest users other than those performing custom cert verification, we could default to chromium verification first and respond to custom callback with the result along with other existing arguments. Sounds good ?

/cc @zcbenz
