### ISSUE TITLE
Middle mouse click on program icon in Windows taskbar doesn't open a new instance

### ISSUE THREAD

**Issue by cozzbp** [electron/electron#7937]
* Electron version: 1.4.1
* Operating system: Windows 10 Anniversary

### Expected behavior

When most apps in windows are middle mouse clicked in the taskbar, it opens a new instance of the application

### Actual behavior

When an electron app is clicked on with the middle mouse button, nothing happens

**Comment by MarshallOfSound** [comment]
This is interesting, the default Electron application does not do anything when you middle click.

**But...** my application which is built on Electron opens itself and triggers the `makeSingleInstance` callback 😕 

I shall look into this more

**Comment by MarshallOfSound** [comment]
OK so my application opens every time because it is packaged with Squirrel and middle clicking launches the `Update.exe --processStart="foo.exe"` shortcut every time which launches my `foo.exe` every time.  I can't find any docs on a window message for middle clicking the taskbar so I'm not sure if there is anything we can do for this if you aren't using the Squirrel trampoline (which does it for you).

**Comment by cozzbp** [comment]
Oh so by packaging with squirrel and setting that flag, it opens a new instance (similar to the behavior of chrome for example) every time?

**Comment by MarshallOfSound** [comment]
See #7952

**Comment by the-ress** [comment]
Note about #7952: When there's a shortcut in start menu or desktop that has the same AppUserModelID as the window, Windows will use the shortcut instead of the `RelaunchCommand` value. I currently don't know any way around this. (Microsoft/vscode#13905)

**Comment by zcbenz** [comment]
I'm closing this since there is already an API to do it, the remaining problem looks more like Windows issue than Electron issue to me.
