### ISSUE TITLE
sendSyncToHost into Webview

### ISSUE THREAD

**Issue by AdrianoPatrizio** [electron/electron#7957]
It would useful add sendSyncToHost method into Webviev for request-response ipc messaging.

**Comment by MarshallOfSound** [comment]
Someone will have to confirm this but I don't believe this is actually technically possible.  Currently the `sendToHost` method bounces through the main process (I believe).  So although the communication to the main process could be synchronous, the bounce back to the parent renderer processes can not be synchronous (as that could block the entire main process which is super bad idea).

IMO you shouldn't be using `sendSync` anyway (as it introduces stutter / lag / framedrops) because it literally blocks the entire process while it waits for a response.  You should use an asynchronous request-response technique using `event.sender.send` 👍

**Comment by AdrianoPatrizio** [comment]
@MarshallOfSound Thank you for response and explanations. :+1:

**Comment by kevinsawicki** [comment]
Closing this out, using the existing async `sendToHost` is the right way to go for a performant application.
