### ISSUE TITLE
state of web worker support?

### ISSUE THREAD

**Issue by mark-hahn** [electron/electron#797]
I possibly have a need for web workers.  I ran into the security problem at https://github.com/atom/atom-shell/issues/600 so I can't try them out right now. 

Do web workers in atom-shell work exactly the same as in a web page or chromium?  In other words is there any support for node modules such as `fs` in a web worker?

I've googled like crazy and there is no mention of web worker support in node or vice versa.

**Comment by jprichardson** [comment]
@mark-hahn what solution did you come up with? I'm currently deciding between web workers, process forking, permanent webview, etc.

**Comment by bu2** [comment]
@jprichardson,

I just built a prototype with a BrowserWindow and a background worker which does heavy computations.

I tried hard to use web workers (to comply with standards, and because  Electron benefits from Chrome support of Web Workers) BUT be aware that in Web Workers you don't have node.js APIs and modules anymore ! 

So I read Electron's documentation related to IPC and I came up with this architecture :

- my BrowserWindow do an IPC call to the main process asking for the launch of a background task

- the main process receive the IPC message and fork a sub process to launch the big computation

- the subprocess notify the main process of task progress

- the main process transmit the notification to the BrowserWindow

- then the BrowserWindow display something 

And it seems there a big advantage following this way: my computation is so big, that when I run it directly in a BrowserWindow, the UI freeze, the computation takes about 1 hour to complete but crash because it use all the memory (more than 12Go :-$). When doing the same thing in my background worker, the UI doesn't freeze, the computation takes the same time to finish and use only 1Go of memory. I believe the reason is: in the first case I was running in a Browser-based JavaScript thread optimized for UI (and with memory-hungry settings concerning garbage collection), in the second case I am running in a Node-based JavaScript thread which does a better usage of the garbage collector...

Regards,

Bruno.

**Comment by jprichardson** [comment]
@bru2 thanks for sharing!

My tasks are relatively light-weight (approx 250 ms), so a web worker may still work better.  I only considered forking the Renderer or actually running the code in the Main.  But I had never considered forking the Main process, that's a good strategy in some scenarios, especially like what you presented. Thanks again for taking the time to share :)

**Comment by mark-hahn** [comment]
> @mark-hahn what solution did you come up with

I ended up with simple child-processes running from node as @paulcbetts suggested.

**Comment by bitwombat** [comment]
@bu2 thanks for getting me on the right track!  Let's hear it for archives.  

Turns out there's no reason the main process has to be involved.  JavaScript loaded by the page (ie. running in the renderer process) can require('child_process') and cp.fork things as well (I just implemented this for a search feature).  There's still IPC between the originating js and the child process, but it's simpler communication:

- User action causes an onclick which is caught by js already loaded by that page
- That js (search) cp.forks a time-consuming process (search-worker).
- search sends search-worker whatever it needs via .send() calls.
- search and search-worker communicate results and status via .on() and .send() calls.

**Comment by marceln** [comment]
@bitwombat thanks, that sounds like a good way. Have you measured the resource usage - mainly CPU and RAM - of doing so? 

I need to do something similar and I was toying with the idea of just letting a child run indefinitely, even when there's no work to do - mainly because there's a good chance that there's always something to do. I was thinking I could eliminate the overhead of spawning child processes.

**Comment by bitwombat** [comment]
>Have you measured the resource usage -  mainly CPU and RAM - of doing so? 

Have not.

**Comment by Programming4life** [comment]
@bitwombat You should check out https://github.com/substack/dnode it's rpc communication but for node. It makes everything much easier.

**Comment by jsnar** [comment]
I don't understand why Electron has no plan on this feature, while nw.js just released Node.js support for Web workers: http://nwjs.io/blog/v0.18.4/

**Comment by trusktr** [comment]
Nevermind, `require` inside a Worker works!

I made a bare minimal example here: https://github.com/trusktr/electron-web-worker-example.

There must be something wrong in my actual project (which is huge compared to that example, and is doing some custom TypeScript transpilation).
