### ISSUE TITLE
cant setup electron please help !

### ISSUE THREAD

**Issue by qaiswahabzada** [electron/electron#8034]
" mkdir demo && cd to demo
npm init
npm install electron --save-dev "

after the last command nothing happens and I get bellow message:

" electron@1.4.7 postinstall C:\Users\NAME\Desktop\Electron\node_modules\electron
 node install.js "

is there any other way to offline get electron to project.
windows 10 enterprise.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW if you download zip file for the version, platform and arch of Electron you want from [the releases section](https://github.com/electron/electron/releases) into `C:\Users\NAME\.electron` it will skip the download during install.

**Comment by qaiswahabzada** [comment]
dear marshal , I took "electron-v1.4.7-win32-x64.zip" but there is two more files one -pdb.zip and -symbols.zip , do i need them as well should I put them as zip file or I need to extract them.

**Comment by MarshallOfSound** [comment]
You don't need the pdb or symbols zip.

**Comment by qaiswahabzada** [comment]
and should i put as zip file or I need to extract and if I did extract do I need copy the content inside folder or only take that extracted folder there.

**Comment by qaiswahabzada** [comment]
after doing all these do I need to run 'npm install electron --dev-save ' again .

**Comment by qaiswahabzada** [comment]
dear marshal how should i be sure all **node module** installed properly and i have them is there such way to get them manually as well

**Comment by frankhale** [comment]
If you are running Node 7.1 on Windows you're likely seeing a widespread problem with the 7.1 release on Windows. You will not be able to install Electron and many other node modules because of this bug. There should be a new release tomorrow of Node to resolve the issue. In the interim you can downgrade Node to 7.0 or earlier release and you'll be able to npm install Electron.

If you go the route of downloading Electron manually from the release page here on Github then all you need is the win32-x64.zip file (eg. `electron-v1.4.7-win32-x64.zip`). If you download that you won't need to npm install Electron. You can simply unzip it and put your app in a folder called `app` that is located in the Electron folder under the resources folder.
