### ISSUE TITLE
Rotated JPGs in electron’s BrowserWindow

### ISSUE THREAD

**Issue by straz** [electron/electron#8059]
* Electron version: 1.4.7
* Operating system: Mac OS X 10.10.5
_Same topic also posted to [discuss.atom.io](https://discuss.atom.io/t/rotated-jpgs-in-electrons-browserwindow/36200)_

I have enclosed an image below (chair.jpg).
The EXIF data in this image shows `Orientation==6` (rotated 90° CCW). 

### Expected behavior
The `orientation` EXIF property should be honored when rendering a JPEG in an IMG tag.
In all my apps (desktop, Chrome, Safari, Firefox, Preview) viewing my sample picture (see below) the green tag is at the top of the picture, and the wooden bars are vertical - i.e. normal.

Download the enclosed picture, and then open it in a new Chrome browser window. It displays properly for me.

### Actual behavior
In my electron app, the green tag is on the left edge, and the wooden bars are horizontal - i.e. it's displayed sideways.

### How to reproduce
In my electron app, I display the enclosed image using `<img src="chair.jpg">` in the DOM.
The error is also reproducible with CSS: `background-image: url(chair.jpg)`

![chair](https://cloud.githubusercontent.com/assets/740407/20548808/b146c8e8-b0f4-11e6-8841-be11adfb6842.jpg)

**Comment by deepak1556** [comment]
Electron does not handle the rendering, it is handled by blink same engine for chrome. The current behavior is consistent with chrome. Loading the image as a top level content will honor the exif value, but not in `<img>` currently. In Electron you can test it out with `window.loadURL`. There is work in standards for fixing this problem. Closing this out, since there is nothing we can do to fix it.

https://www.w3.org/Bugs/Public/show_bug.cgi?id=25508 
https://bugs.chromium.org/p/chromium/issues/detail?id=158753
