### ISSUE TITLE
Allow create application menu for Linux

### ISSUE THREAD

**Issue by popod** [electron/electron#8118]
Provide an option to set application menu for linux as for macOS. Now, with [setApplicationMenu()](http://electron.atom.io/docs/all/#menusetapplicationmenumenu) used on Linux, the application is set for each window.

Note I test on Ubuntu and there is well an application menu set. Should the doc be improve with this info ?

**Comment by kevinsawicki** [comment]
> Should the doc be improve with this info ?

So you are seeing a application menu on ubuntu?

There is an environment variable to force it to be in the window on Linux, http://electron.atom.io/docs/api/environment-variables/#electronforcewindowmenubar-linux

**Comment by kevinsawicki** [comment]
> So I don't know if this is the case with all linux distribution, but i think this should be documented.

Agreed, please feel free to open a pull request to the docs if you are interested in making this change.

**Comment by rijann** [comment]
Hey! I would like to help. Can y'all help me get started?

**Comment by zcbenz** [comment]
On Linux there is no application menu, it is called global menu bar which places current window's menu bar on top of the screen. A application menu is a single menu that shared by all windows, which is not supported by Linux.

For Linux `Menu.setApplicationMenu` just sets the same menu bar for all windows, so for desktop environments that support global menu bar, it looks like that the application has a single application menu, while they are actually differently menu bars.

This difference is very important, because for desktop environments that do not support global menu bar, the menu set by `Menu.setApplicationMenu` would be showed as menu bar inside each window.
