### ISSUE TITLE
Ubuntu - MoveItemToTrash() don't work

### ISSUE THREAD

**Issue by popod** [electron/electron#8132]
* Electron version: 1.4.10
* Operating system: Ubuntu 16.4

### Error
When trying to delete a file with `shell.MoveItemToTrash()` on Ubuntu, I get the following error in the console logs:
```
Error trashing file: Unable to find or create trash directory
```

Possible solution #7178.. But why not automatically check which lib is used and use it without using env vars ?

**Comment by kevinsawicki** [comment]
Is `gvfs-trash` on your machine?

**Comment by popod** [comment]
Yes, it is installed.

**Comment by KSXGitHub** [comment]
I notice that neither `gvfs-trash` (deprecated) nor `gio trash` (gnome new recommendation) works with files that contain spaces in their path:

**Example 1**

```bash
mkdir -p 'foo/bar/Folder with Spaces in it'
cd 'foo/bar/Folder with Spaces in it'
touch file.txt
gvfs-trash file.txt && echo 'it works' || echo 'it does not work' # Spoiler: it does not work
```
**Example 2**

```bash
mkdir -p 'foo/bar/Folder with Spaces in it'
touch 'foo/bar/Folder with Spaces in it/file.txt'
gvfs-trash 'foo/bar/Folder with Spaces in it/file.txt' && echo 'it works' || echo 'it does not work' # Spoiler: it does not work
```

------

I recommend using [trash-cli](https://www.archlinux.org/packages/community/any/trash-cli/) or [trash-cli](https://github.com/andreafrancia/trash-cli)

```bash
trash 'foo/bar/Folder with Spaces in it/file.txt'
```

**Comment by zcbenz** [comment]
Since `gvfs-trash` has been successfully called, I'm afraid this is a bug of `gvfs-trash`, please report to that project's tracker instead.

**Comment by KSXGitHub** [comment]
@zcbenz Let me make it clear:

1. `gvfs-trash` is officially **deprecated** (i.e. _dead_) by its creator. Why would anyone fix something that is already dead?

2. Although `gio trash` is recommended as a replacement of `gvfs-trash`, `gio trash` has the same issue. Furthermore, both `gio trash` and `gvfs-trash` are **GNOME exclusive**, so non-gnome users won't be able to use "Move to Trash" feature out-of-the-box.

3. Most popular Linux distros has trash-cli **by default**, so it makes sense to use command `trash`.

4. In order to overcome this issue, electron apps developer can do some workarounds (e.g. try-catch for each 3 commands: `gvfs-trash`, `gio trash`, and `trash`). Almost (if not all) developers expect their apps to work right out-of-the-box so they must do it themselves instead of calling `moveItemToTrash`. Therefore, it makes sense to include these workarounds right in electron.

5. I could report this bug to gvfs-trash. However, the difference between gvfs-trash and electron is: I could list `electron` as a `devDependencies`, so when electron fix this bug, I'll just increase electron version; I cannot specify gvfs-trash version.
