### ISSUE TITLE
Helper Application requires permissions

### ISSUE THREAD

**Issue by martinheidegger** [electron/electron#8191]
* Electron version: 1.3.13 (the one used by Atom)
* Operating system: Mac OS X

### Actual behavior

Electron (or rather the end-user app: Atom, Brave, etc.) ask a non-admin user several times (over the period of a week, sorry: didn't understand the correct rhythm) to install a helper and for that it requests "admin privileges".

### Expected behavior

Electron should not ask for permissions for a helper when the user is not an admin user. I want the end-user app to run within the given permissions of a user and never get need or meaning to install something as admin user. Which also means that during installation it should ask **once** for an admin password when installing the App (moving to /Applications) 

### How to reproduce

1. Install Brave and/or Atom on a Mac. 
2. Run the mac as a non-admin. 
3. See the "requires admin privileges"-dialog for the Helper pop up several times over the duration of a week/month

**Comment by paulcbetts** [comment]
> Electron (or rather the end-user app: Atom, Brave, etc.) ask a non-admin user several times (over the period of a week, sorry: didn't understand the correct rhythm) to install a helper and for that it requests "admin privileges".

This is Squirrel.Mac not being able to update because permissions are too restrictive, we're seeing this at Slack too. The bug is that letting it have Administrator doesn't solve the issue - the app doesn't update and the user keeps getting the Helper dialog. /cc @joshaber

**Comment by joshaber** [comment]
This sounds like https://github.com/Squirrel/Squirrel.Mac/issues/131.

**Comment by zcbenz** [comment]
I'm closing this since there is already an issue tracking it.

**Comment by zanemcca** [comment]
Just wondering if you guys have pulled in the patched version for this yet? Looks like it was patched here https://github.com/Squirrel/Squirrel.Mac/pull/207 but we have received a report about this issue happening for one of our users.

**Comment by numbsafari** [comment]
Squirrel.Mac hasn't be updated since 2017. This is a bug affecting every single Electron app that wants to auto update on Mac OS. The only solution is to disable auto updates, but not every app allows this to happen (glaring at you, Slack.app).

Electron is allowing a potential major security issue to fester because it is bundling 6-years-since-abandoned frameworks that are demanding escalated permissions.

This bug should be reopened, and Squirrel.Mac replaced.

**Comment by MarshallOfSound** [comment]
> Squirrel.Mac hasn't be updated since 2017.

This is simply incorrect, the core Squirrel.Mac repo was last updated in 2021 by me.  At which point we then decided future Electron changes would land in this repo as [patches](https://github.com/electron/electron/tree/main/patches/squirrel.mac) rather than updating the upstream repo each time, the last fix/change being 2 months ago.

> This is a bug affecting every single Electron app that wants to auto update on Mac OS.

This is not a bug, it's a feature, without it updates can not be installed by unprivileged users.  That's how filesystems works... If you don't like it, either disable application updates or fix the filesystem permissions on your managed devices such that regular users can actually update the application.

> but not every app allows this to happen (glaring at you, Slack.app).

There is literally an entire help centre page on how to do this with Slack... [Old instructions](https://slack.com/help/articles/360035635174-Deploy-Slack-for-macOS#disable-automatic-updates), and then [newer cooler instructions](https://slack.com/help/articles/11906214948755-Manage-desktop-app-configurations).
