### ISSUE TITLE
How to get currently selected text from other application?

### ISSUE THREAD

**Issue by bot4343** [electron/electron#8195]
I am building a desktop application with Electron. As a part of its functionality I want to get text that is **currently selected** in other application (editor). This text can be any where - webpage, pdf, sublime etc.

Is there any way I can do this?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron APIs should be directed to [the community](https://github.com/electron/electron#community).

Electron doesn't provide any API to do what you want, and OS vendors generally don't make this easy to do with the native platform APIs either due to the security implications.

**Comment by mikhail-yurin** [comment]
I did it with:
```
// On X Window systems, there is also a selection clipboard. To manipulate it you need to pass selection to each method:

const { clipboard } = require('electron')
clipboard.writeText('Example String', 'selection')
console.log(clipboard.readText('selection'))
```
Check this [](https://electronjs.org/docs/api/clipboard)
