### ISSUE TITLE
clipboard.readImage() retrieving scaled images on macOS

### ISSUE THREAD

**Issue by mkwng** [electron/electron#8210]
* Electron version: 1.4.11
* Operating system: macOS (Retina MBP)

### Expected behavior

When clipboard contains a screenshot taken with macOS's screenshot (ctrl+cmd+shift+4), `clipboard.readImage()` returns a NativeImage of the actual, retina (@2x) pixels.

### Actual behavior

The NativeImage object that is returned is a scaled down version, to the "real" (@1x) pixel count without regard to pixel density, resulting in a blurry image on high resolution/retina devices.

Is there a way to retrieve the actual pixels from the clipboard? It definitely exists, as pasting into any image editing software will retrieve actual, non-scaled images.

**Comment by mkwng** [comment]
Related (?) Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=355477

**Comment by kevinsawicki** [comment]
@mkwng looks related, can check after Electron upgrades to Chrome 54 via #7909

**Comment by kevinsawicki** [comment]
>  can check after Electron upgrades to Chrome 54

Looks like this landed in Chrome 55, not 54

**Comment by kevinsawicki** [comment]
This appears fixed in 1.6.0 which runs on Chrome 56:

Screenshot image read off clipboard in 1.6.0:


![test](https://cloud.githubusercontent.com/assets/671378/22839194/535abe20-ef7d-11e6-9b32-e870dfb06864.png)

Screenshot image read off clipboard in 1.5.1:

![test2](https://cloud.githubusercontent.com/assets/671378/22839193/5355039a-ef7d-11e6-8aac-64d4c1ca848d.png)

Closing this out.
