### ISSUE TITLE
WebGL not supported on Macbook Pro (Intel Graphic HD 3000)

### ISSUE THREAD

**Issue by nantas** [electron/electron#8217]
* Electron version: 1.4.3, 1.4.12
* Operating system: macOS 10.11.6

### Expected behavior

User's machine can open a browser window that supports WebGL with Electron.

### Actual behavior

Our user ran the following commands in DevTool console of a Electron default app:

```js
var electron = require('electron');
var win = new electron.remote.BrowserWindow({width:800, height: 600});
win.loadURL('https://get.webgl.org/')
```

The result:

![image](https://cloud.githubusercontent.com/assets/344547/21255372/7ddd7c80-c3a6-11e6-8f9d-8725cefd5268.png)

### Other reference

User's system info:

![image](https://cloud.githubusercontent.com/assets/344547/21255384/8c9a8772-c3a6-11e6-8683-fcfa8b257557.png)

With the same system we also tried Electron 1.3.3 and it works fine with WebGL support test.

**Comment by enlight** [comment]
WebGL is disabled on that system because Chromium blacklisted the Intel HD 3000 on macOS [a few months back](https://codereview.chromium.org/2076443002/), there's also a [related issue](https://bugs.chromium.org/p/chromium/issues/detail?id=644091) in the Chromium bug tracker. You could try running the app with the `--ignore-gpu-blacklist` [Chromium switch](http://electron.atom.io/docs/api/chrome-command-line-switches/), e.g.

```
app.commandLine.appendSwitch("ignore-gpu-blacklist")
```

**Comment by nh2** [comment]
WebGL on HD 3000, macOS 10.12.6, MacBook Air 13-inch Mid 2011, is enabled working and working on Google Chrome 70.0.3524.0, but not in Electron.

Is this because Electron's Chromium version is older?

**Comment by nikolas** [comment]
I'm seeing a similar problem with the same graphics card on a mac mini with MacOS 10.13.6: https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chrome/co6w-9D1ZWo/PkVV2yMsBQAJ

**Comment by gormonn** [comment]
@enlight 
Unfortunately this only works through passing an argument at startup. See electron/electron#15339
