### ISSUE TITLE
A BrowserWindow with show:false still appears under MacOS Window, as "Electron"

### ISSUE THREAD

**Issue by paulshapiro** [electron/electron#8221]
* Electron version:
1.4.1
* Operating system:
MacOS 10.11
### Expected behavior

Expected show:false to mean totally invisible to the user. I have to use a show:false window because that's what's recommended by users as the better way in Electron to implement background processes that do not block either the app's entire main thread or the render process.

### Actual behavior

The invisible window will show up in the Window menu as "Electron", and selecting it does nothing.

### How to reproduce

Simply instantiate a `BrowserWindow` with the option `show` set to `false`.

Thanks!

**Comment by MarshallOfSound** [comment]
As far as I am aware this is entirely expected behavior, if you want to launch a different process to perform background tasks on you should look into something like [`electron-workers`](https://www.npmjs.com/package/electron-workers) or implement something similar yourself.

The trick is forking your process with `ELECTRON_RUN_AS_NODE=true` 👍 

If you open a window and then hide it, it is still technically a window and I don't think we should be hiding it from that window menu (if it is even possible to do so)

**Comment by enlight** [comment]
> The trick is forking your process with ELECTRON_RUN_AS_NODE=true

Electron does this automatically when you use [`child_process.fork()`](https://github.com/electron/node/blob/811cfe3fcd360179d3dd436e3d80e1b045adf633/lib/child_process.js#L61), but you will need to set that env var yourself if you use `child_process.spawn()`.

**Comment by paulshapiro** [comment]
@MarshallOfSound @enlight Thanks for the info.

Not sure if you guys are on the electron team but in case you are: IMO, it should be stated in the docs that using background windows, despite being recommended by various old articles, is not a best practice. Many man-hours could be saved!
