### ISSUE TITLE
Progress bar and intermediate file for downloading items on macOS

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#8288]
* Electron version: 1.4.7
* Operating system: macOS

When downloading item with Chrome on macOS, the downloaded file is first saved as a intermediate file that can't be opened (`*.crdownload`) and showing a progress bar and a cancel icon.

![3asicc1e9b](https://cloud.githubusercontent.com/assets/687961/21502012/06d5be36-cc4d-11e6-91df-e82a2f0e8ca2.gif)

I was looking for means to implement similar behavior in an electron-based application.

After some research:
- it does not look to me that's doable from user-land as it seems tied to internal machinery of downloading — even if the intermediate file trick can be hacked
- I think I isolated the implementation of progress bar in Chromium [here](https://chromium.googlesource.com/experimental/chromium/src/+/master/chrome/browser/download/download_status_updater_mac.mm#125) using [NSProgress](https://developer.apple.com/reference/foundation/progress) class, but I don't understand why this part is not used by Electron

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our roadmap. If you'd like to make a PR for this request we would welcome that, but in the meantime I'm going to go ahead and close this.

**Comment by alexstrat** [comment]
Totally understood!
As a side note, I played with [NodObjC](https://github.com/TooTallNate/NodObjC) and came up with this: https://github.com/alexstrat/node-macos-download-progress
