### ISSUE TITLE
Border renders wrong when using Vibrancy

### ISSUE THREAD

**Issue by gielcobben** [electron/electron#8305]
I'm using the settings below to create my MainWindow (notice the Vibrancy). 
In my index.html I have a header component which has a white background color. As you can see in the image below it renders wrong. Is there anything I can do to fix this?

**Settings:**
```
    mainWindow = new BrowserWindow({
        center: true,
        show: false,
        width: 360,
        height: 440,
        minWidth: 300,
        minHeight: 300,
        vibrancy: 'ultra-dark',
        frame: false,
        transparent: true
    });
```

**Image:**
![image](https://cloud.githubusercontent.com/assets/2663212/21548205/4a91297c-cdeb-11e6-8b39-cc783cbfd996.png)

**Comment by matt3224** [comment]
I'm also having this type of issue:

![screen shot 2017-01-02 at 11 45 45](https://cloud.githubusercontent.com/assets/2401925/21588643/1595282e-d0e1-11e6-80ea-84ca0ac0e321.png)

and: 

![screen shot 2017-01-02 at 11 46 10](https://cloud.githubusercontent.com/assets/2401925/21588644/15b0525c-d0e1-11e6-86b0-9589483b395c.png)

**Comment by kevinsawicki** [comment]
@gerhardberger any ideas on this one?

**Comment by gerhardberger** [comment]
@kevinsawicki my first guess is that it is not the border, but vibrancy view showing through around the edges. I will look into it more in the coming days.

**Comment by gerhardberger** [comment]
So I found the issue is that the corners of a vibrant view (more specifically `NSVisualEffectView`) doesn't use antialiasing so the pixelated corners showed through.

I found a solution with a mask image that involves overriding an undocumented method of `NSWindow`. Hopefully Apple will fix this and it won't be needed in the future. I submitted a PR with the solution.

Here is a window without a vibrant view behind the page:
![screen shot 2017-01-06 at 2 08 40 pm](https://cloud.githubusercontent.com/assets/1059699/21719460/416ed2ca-d41e-11e6-8627-96072d308fd9.png)

And here is one with a `dark` vibrant view behind:
![screen shot 2017-01-06 at 2 30 23 pm](https://cloud.githubusercontent.com/assets/1059699/21719462/46ce3a76-d41e-11e6-81d2-72646e0e4a64.png)

**Comment by natew** [comment]
@gerhardberger did you rebuild electron with this patch? Have the source available somewhere?

**Comment by sergeysova** [comment]
What about this:





![2018-04-24 18 39 55](https://user-images.githubusercontent.com/5620073/39198113-e80e8428-47ee-11e8-9d3b-9dff1006c170.jpg)

**Comment by christianscheuer** [comment]
Any news on this?

**Comment by nickensoul** [comment]
Any news please?
![image](https://user-images.githubusercontent.com/14836054/67583500-64aec680-f754-11e9-95fb-181ec389b25b.png)
