### ISSUE TITLE
DownloadItem use getSavePath  or getFilename get value not actual filename

### ISSUE THREAD

**Issue by boneyao** [electron/electron#8331]
* Electron version: v1.4.13
* Operating system: macOS Sierra 10.12.2

### Expected behavior
`downloadItem.getSavePath() == python (1).crm`

### Actual behavior
`downloadItem.getSavePath() == python.crm`

### How to reproduce
if filename exisit use `downloadItem.setSavePath(filename)`

**Comment by hokein** [comment]
The expected behaviour you mentioned above is a chromium browser feature.

However, it is a bit different in electron. If the filename exists, electron will overwrite it with new downloaded content, and this behaviour is intended (I think we should clarify it in `DownloadItem` document). From the API perspective, `getSavePath` should always return the path which is passed to `setSavePath`, otherwise it is wired for developers to see the result from `downloadItem.getSavePath()` is different than the save path they set to `downloadItem`.

If you want to align with chromium's behaviour, you can implement on your own (check whether the filename exists before setting save path).
