### ISSUE TITLE
Google's reCAPTCHA gives "Invalid domain for site key" error.

### ISSUE THREAD

**Issue by bjdash** [electron/electron#8345]
I have added Googles reCAPTCHA into my application. But when I run it through electron, it gives me "Invalid domain for site key" error. Possibly because no **referrer** header is sent when the captcha is loaded.

**Comment by MarshallOfSound** [comment]
@bjdash Are you attempting to use reCAPTCHA from a `file://` url, I do not believe it can work that way.

**Comment by bjdash** [comment]
Thats correct. I opened the developer console and saw files are loaded as **file:///**. I am sunning it as `electron ./`.  Is there any solution for loading reCAPTCHA?

**Comment by alvarolb** [comment]
I have managed to load the recaptcha frame inside an electron APP by disabling the domain validation. However, it fails on verification with this error:

Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "file://".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "file". Protocols must match.

Any way to disable this checking?

**Comment by kevinsawicki** [comment]
@alvarolb have you tried a custom protocol? See the example in #8414  for more details.

>   Is there any solution for loading reCAPTCHA?

I think it will work if you load the page using a custom protocol or http/https.

There are several issues/topics out there about this:

https://github.com/google/recaptcha/issues/96
https://groups.google.com/forum/#!topic/recaptcha/AuN2f7JrZTA
https://groups.google.com/forum/#!msg/recaptcha/tnosY9BulRs/vBhsmAvqCV4J
https://developers.google.com/recaptcha/docs/domain_validation

Closing this out here since this isn't something that can't be fixed directly in Electron, this is a recaptcha limitation that can be addressed in that library or by working around the protocol issues by using the http://electron.atom.io/docs/api/protocol API.

**Comment by sijorsijo** [comment]
reCaptcha not shown in both  localhost and ip (127.0.0.1)

**Comment by marcelobcortes** [comment]
I had successfully implemented custom protocol and disabled domain check (works on development) but "Invalid domain for site key" persists.

**Comment by k-sai-kiranmayee** [comment]
Hello!
I know the discussion on this was stopped a long time ago, but anyone has got any apt solution, please?
Any Cordova plugin that has a workaround for this
> @bjdash Are you attempting to use reCAPTCHA from a file:// url? I do not believe it can work that way.

Thank you.

**Comment by bierzorutas** [comment]
Same problem here

**Comment by singhparminder02** [comment]
For anyone stumbling on this thread in 2023 or later, I've tried the recommendation at the following link and it works well for us in the electron app (in the unpackaged as well as packaged mode).

https://github.com/electron/electron/issues/17182#issuecomment-530940011
