### ISSUE TITLE
Bundle a command-line program without Chromium and other bloat?

### ISSUE THREAD

**Issue by fidian** [electron/electron#8368]
First off, thanks for keeping this project alive.  I love that the maintainers respond to people who submit tickets and attempt to eliminate problems to help everyone.

I would like to build a cli program.  It performs a pretty boring task and it's written in Node because the team finds JavaScript to be the best language out there.  We use some custom modules and, unfortunately, one native module as well.  One of the developers is looking into how this program can be offered as a standalone, "precompiled" command-line tool.

Other packages don't really offer this functionality.  They fall short in different ways:

* Argument processing is unexpected.  You'd have to write `my-command -- --option1`, where that `--` is mandatory.
* They extract to a local folder and expect it to always be there.
* They don't support native modules.

Electron looks like a great option, but we don't need the overhead of Chromium and other libraries added.  I can't seem to locate any documentation explaining if stripped down command-line tools are possible to build, so I instead ask the developers.

We'd like to be able to go into a Node repository, run something to build the app, and then get builds for various platforms.  If we need to run the build on all of the platforms ourselves, that is an option but we'd prefer to avoid it when possible.

If this sort of thing is not possible, would it be something that the developers would consider adding, either themselves or via pull requests?

Thanks again for this very interesting project!

**Comment by enlight** [comment]
No, you can't build a stripped down Electron without Chromium. Sounds like you need a packaging tool for your Node app, something like http://enclosejs.com/

**Comment by fidian** [comment]
Thanks for pointing out that project.  It was brought up by the team as well, but nobody in the office likes using software that isn't open source.  Also there is [Nexe](https://github.com/jaredallard/nexe) that doesn't support dynamic require statements.  [Disclose](https://github.com/pmq20/disclose) looks like it just bundles arbitrary files together and untars them in some folder before running them. [Nar](https://github.com/h2non/nar) has the terrible argument processing.  [JXCore](https://github.com/jxcore/jxcore/) doesn't look maintained.  [Node2exe](https://github.com/areve/node2exe) looks old and may have problems with native libraries, though it is possible that we could work around those issues.

I'm also open to other alternatives if people want to recommend them.

**Comment by kevinsawicki** [comment]
> If this sort of thing is not possible, would it be something that the developers would consider adding, either themselves or via pull requests?

Electron is designed for building desktop apps using HTML, JavaScript, and CSS. Bundling and integrating with Chromium enables that. It isn't an ideal fit for command line applications with no GUIs and probably won't ever be.

Many applications do ship a command line wrapper for their apps that launches the UI version (like Atom, VSCode, etc.). We are interested and committed to supporting this use-case because it enables apps to have solid terminal integration to launch and manage their GUIs.

I'd recommend just using Node directly for this and recompile it for the application you are building to include all necessary modules, dependencies, etc.

**Comment by levrik** [comment]
@fidian Did you already tried that? https://github.com/pmq20/node-compiler

**Comment by fidian** [comment]
I'm asking another developer to evaluate that tool.  I don't have high hopes because the documentation is sketchy, download links are missing, the build is failing, there's a broken image for the latest broken build and finally there's no discussion about how it bundles files nor if it handles native binaries.

**Comment by MarshallOfSound** [comment]
> One of the developers is looking into how this program can be offered as a standalone, "precompiled" command-line tool.

@fidian I would suggest you look into how `yarn` does it (they are the best example that comes to mind).

They ship through `brew` for macOS, a custom MSI for windows and an install script (that basically downloads the binary) for linux.  If you look into how their builds work you might find an easy answer.  They have a reasonably active discord chat so you might be able to ask for pointers there.

**Comment by fidian** [comment]
@MarshallOfSound As I understand it, I would need to install `yarn`, which is not what I'm hoping to do.  The idea is to use JavaScript to build a command-line tool and then bundle the whole thing as a single, platform-specific executable file.  Similar to compiling it with Go or C.

If I were to use another approach, I guess I would have everyone install node and use npm to install packages.  The goal is to not force people to install any software (node included) prior to running the tool.

**Comment by MarshallOfSound** [comment]
@fidian No, I'm saying yarn has already solved this problem.  Yarn is fundamentally written in JS, runs on node, but needs to run outside of the NPM ecosystem as a CLI application.

They ship their own binaries for each OS.  I was suggesting you look into how they generate their binaries and implement something similar.

**Comment by fidian** [comment]
@MarshallOfSound Please let me reiterate: I do not want an installer.  I can make an installer that installs node and my software, similar to what `yarn` does.  That is not the goal.  Put another way, I want a portable application that doesn't need any additional software in order to run.  Portable meaning it can run off a jump drive and is self-contained, leaving no cruft on the system after it executes.

**Comment by levrik** [comment]
@fidian I think Javascript is not the right technology for that then. Just to name some, I think Go, C, C++ or C# would fit better.

**Comment by fidian** [comment]
@levrik I fail to see your point.  Could you elaborate and explain why JavaScript is the right technology when bundling Chromium as well, but not the right technology for command-line tools?  Wouldn't your statement suggest that Electron is also going about this in the wrong manner?

Many of my goals align to what Electron provides, from my understanding.  If I am wrong, please correct me.

* Bundles up a bunch of JavaScript.
* Can be made into a single executable.
* No need to install Node or anything else first.
* Works for native modules.

The bit that I don't need is several megabytes of Chromium.

**Comment by kevinsawicki** [comment]
> Can be made into a single executable.

This is not true on macOS, Electron builds as a `.app` with several Frameworks inside it. Node on the other hand builds as a single executable on macOS.

**Comment by baconface** [comment]
> Could you elaborate and explain why JavaScript is the right technology when bundling Chromium as well, but not the right technology for command-line tools? Wouldn't your statement suggest that Electron is also going about this in the wrong manner?

Electron is not going the wrong way and it is great technology for command-line tools. It is just what you are expecting of JavaScript for your purpose is only possible through projects like EncloseJS which you seem to have rejected. If you are not finding any other workaround then he is not suggesting JavaScript isn't a right technology but he is suggesting it is not the right technology for _your purpose_. Hence he suggested Go, C, C++, etc which allow you to create a self contained command line tool, with minimal file size, and no dependencies. Electron just simply doesn't fit your particular purpose and it's scope will never fit that purpose.

**Comment by levrik** [comment]
Thanks @baconface. That was exactly what I wanted to say.

**Comment by fidian** [comment]
@kevinsawicki Is it inaccurate when I say that Electron builds a single "thing" that can be executed directly?  I don't know about `.app` files on MacOS, but I thought they didn't always require installation in order to execute.  If it's treated as a single thing and can run it directly, I don't really care if it extracts into memory and runs or if it is just a single executable.  My goals align with ease of installation and leaving little to nothing behind after being ran.

@baconface Is the scope of Electron documented somewhere?  I would have expected a statement regarding scope to come from one of the members of the project.  Granted, you are a contributor and have a far better understanding of Electron than I do and your statement carries some weight.  However, I've seen many contributors fall short of the communal knowledge and internal direction that maintainers preferred and would like confirmation, which would probably also mean closing this ticket.

And a bit for everyone:

I'm very glad that so many people are taking an interest in this discussion.  I thank you for your continually helpful posts to other tools and further questions.  However, I feel that the conversation has diverged from the original intent.  My initial post asked a question that I don't believe was adequately addressed by an authoritative member.  I apologize if I had missed it or if @baconface is truly a member of the organization - I do not mean to speak out of turn.

The question was thus:

> If this sort of thing is not possible, would it be something that the developers would consider adding, either themselves or via pull requests?

It's true that several comments related to clarification about what I meant by a single executable and people have suggested techniques where I would not quite meet my goals.  It's also possible that my goals are unreasonable, but that discussion should be outside the scope of this issue.  The point was to see if this type of thing could be accomplished in Electron currently as it stands.  If not, would the project be willing to go in that direction or be willing to accept pull requests that add options to tools that lie in that direction.

**Comment by levrik** [comment]
@fidian That a .app file is a single file on macros is right. But if you want to go cross platform it is not possible. You cannot build an Electron app to a single file like an EXE on Windows. Besides that I don't think that it would be a good idea to build a version of Electron without Chromium (I also think it's not really possible). But that's my opinion and maybe does not match with these of the maintainers.

**Comment by TimNZ** [comment]
Hi @fidian I'll add my raw 2 cents because I can - your question has been very extensively answered.

Electron is not the tool for what you want to do, and I don't even understand why you continue to think it is.   Perhaps you don't have enough technical knowledge to evaluate the clear concise answers you are being given.

Electron is Node JS + Chromium for web apps on the desktop.

Node JS and a packager is the combo you should be looking at if you want access to Node stuff.

**Comment by baconface** [comment]
> Is the scope of Electron documented somewhere? 

@fidian For full disclosure I do not maintain Electron or have any control of it's direction. I simply contribute like anyone else can. But it's scope basically stems from it's description and mission posted just about everywhere stating "Build cross platform desktop apps with JavaScript, HTML, and CSS". So the purpose is to build desktop app using web technologies. As a result Chromium becomes a core component of the project. Basically the foundation of how it all works. And at this point removing Chromium basically breaks the project. So to ask that Chromium be removed it can no longer serve it's mission making your request out of this scope.

I am not trying to be rude. I was just putting in my 2 cents this wouldn't meet your needs since Chromium was a deal breaker.

**Comment by kevinsawicki** [comment]
> The point was to see if this type of thing could be accomplished in Electron currently as it stands. If not, would the project be willing to go in that direction or be willing to accept pull requests that add options to tools that lie in that direction.

Electron is designed for UI applications and not for command-line applications.

Shipping a version of Electron without Chromium would essentially mean just shipping Node since almost all of the API Electron provides build on top of APIs that Chromium provides. The APIs listed on http://electron.atom.io/docs/api/ are dependent on Chromium so it isn't feasible to build/ship a version of Electron without Chromium because it wouldn't enable you to build desktop applications using JavaScript, HTML, and CSS which is the core mission of Electron.

Rebuilding/rebranding/redistributing Node is a great way to build a CLI application that supports JavaScript, native extensions, and an event loop on lots of platforms and architectures.

As I mentioned previously, we would be interested in pull requests and APIs that better enable people to build/ship command line wrappers around Electron apps since it is a common use case where people want to interact with apps from both the terminal and the dock.

I'm going to close this out, thanks to everyone who participated.

**Comment by firatkucuk** [comment]
I know this issue is closed but i couldn't find a nodejs packager which supports cross compilation and ARM architecture. So electron works like a charm for web like apps but we need the console app to be packed. Basically I tried all other packagers most of them cannot support ARM architecture and the others cannot support cross compilation. Is there any easy way to use asar and electron-packager for console based apps?

**Comment by howdoicomputer** [comment]
@fidian @firatkucuk I know this is a super old, closed issue. But you can pack native extension into a Nexe produced executable and then unpack it using your application as part of an install process.
