### ISSUE TITLE
Disable MacOS help topics

### ISSUE THREAD

**Issue by roblourens** [electron/electron#8431]
An electron app on MacOS shows the help menu in the menu bar. If you search in the Help menu, it will show you general Mac help topics:

![image](https://cloud.githubusercontent.com/assets/323878/22047411/c415c0d8-dcdb-11e6-93de-17f3f911d098.png)

It's not obvious that these aren't provided by the app. Is there any way to disable this, or replace it to only show my own help topics?

**Comment by kevinsawicki** [comment]
> Is there any way to disable this, or replace it to only show my own help topics?

Looks like this can be configured in the `.plist` file, from my testing if you add an any value then the default help topics aren't displayed.

Example taken from https://developer.apple.com/library/content/documentation/Carbon/Conceptual/ProvidingUserAssitAppleHelp/registering_help/registering_help.html#//apple_ref/doc/uid/TP30000903-CH207-CHDGHHDF

```xml
<key>CFBundleHelpBookFolder</key>
<string>SurfWriter.Help</string>
<key>CFBundleHelpBookName</key>
<string>com.mycompany.surfwriter.help</string>
```

With those values:

<img width="753" alt="screen shot 2017-01-24 at 3 50 57 pm" src="https://cloud.githubusercontent.com/assets/671378/22272084/fe500486-e24c-11e6-942f-bcaf709aed88.png">

Without those values:

<img width="685" alt="screen shot 2017-01-24 at 3 51 11 pm" src="https://cloud.githubusercontent.com/assets/671378/22272086/02a54b90-e24d-11e6-8e53-17c669b35c3c.png">


So VSCode can tweak their plist to remove these, closing this out since this doesn't require an Electron change.

**Comment by roblourens** [comment]
Thanks!
