### ISSUE TITLE
Close button mac os, after app don't opened

### ISSUE THREAD

**Issue by joinjoohny** [electron/electron#8436]
When I clicked close button, window app is closed, but I want opening app in dock, nothing happens.
I see, that the electron in this event it makes the window null. Thx.
How can I solve this problem?
Electron 1.4.14
Mac OS 10.11.6
```javascript
  mainWindow.on('closed', () => {
    mainWindow = null;
  });

**Comment by kevinsawicki** [comment]
Are you running your packaged app or via the `electron` command line?

The `electron` command line launcher quits the app when the all windows are closed: https://github.com/electron/electron/blob/71512ad244d5aa9e82af2e57cc89b31d0729a7ff/default_app/default_app.js#L7-L9

This will not be the behavior when your app is packaged since that code will not be running.

http://electron.atom.io/docs/api/app/#event-window-all-closed

You can use the `activate` event on the app module to know when the dock is clicked and your app should relaunch a window.

http://electron.atom.io/docs/api/app/#event-activate-macos
