### ISSUE TITLE
Oversized maximized window

### ISSUE THREAD

**Issue by HitomiTenshi** [electron/electron#8454]
* Electron version: 1.4.15
* Operating system: Windows 10 Pro x64

### Expected behavior

Maximized window should not oversize.

### Actual behavior

Maximized window is oversized.

### How to reproduce

Clone following repository:
https://github.com/tonyganch/electron-oversized-test.git

and follow the `README.md`.

#### Unmaximized frameless
![electron_2017-01-20_10-24-19](https://cloud.githubusercontent.com/assets/7304212/22143620/f6c83026-defa-11e6-8ef0-ec196619c775.png)

#### Maximized frameless
![electron_2017-01-20_10-27-39](https://cloud.githubusercontent.com/assets/7304212/22143662/174cb556-defb-11e6-8e13-359dc6d60194.png)

#### Unmaximized with frame
![electron_2017-01-20_10-30-14](https://cloud.githubusercontent.com/assets/7304212/22143749/7607bb22-defb-11e6-8b02-877b75e40603.png)

#### Maximized with frame
![electron_2017-01-20_10-30-43](https://cloud.githubusercontent.com/assets/7304212/22143770/877b15ac-defb-11e6-8ee7-37226c858ff5.png)

**Comment by kevinsawicki** [comment]
@liusy182 do you think this is related to the changed in https://github.com/electron/electron/pull/7765

**Comment by HitomiTenshi** [comment]
@kevinsawicki I don't know. What's the last version without this change?

By the way, I noticed that it only oversizes about 5px at the top. The sides and the bottom are unaffacted and display as they should.

**Comment by kevinsawicki** [comment]
@HitomiTenshi can you confirm that it works as expected in 1.4.13?

**Comment by HitomiTenshi** [comment]
1.4.13 eats away only 2px instead of 5px. But yes, it happens somewhat.

![zucvwvw](https://cloud.githubusercontent.com/assets/7304212/22163072/ab7c4a88-df51-11e6-8092-6ca235075e2e.png)

**Comment by liusy182** [comment]
@kevinsawicki It doesn't look related from the first look. Changes in #7765 should not affect framed window, but this bug happens to both frame / frameless window. I will take a closer look to see what I can find.

**Comment by kevinsawicki** [comment]
> I will take a closer look to see what I can find.

Thanks for looking into this 👍

**Comment by liusy182** [comment]
After some investigation, I believe this bahavior is expected in Windows. 

Explanation below:

The pixels that got missed out after resize is the value of `GetSystemrics(SM_CYSIZEFRAME)` From [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724385(v=vs.85).aspx):
> SM_CYSIZEFRAME: The thickness of the sizing border around the perimeter of a window that can be resized, in pixels. SM_CXSIZEFRAME is the width of the horizontal border, and SM_CYSIZEFRAME is the height of the vertical border.

On my windows 7 machine, this value is `4px` which is close to the `5px` reported in this bug.

If you notice Windows File Explorer, the resizable frame portion of the window gets hidden after the window is maximized. This is to prevent the window from being resized by drag-drop the border after it is maximized. On frameless window, this should work the same because frameless window also has a resizable border of around 4px.

The border will be shown completely if we disable `resize` of the window. Example below will show the full pixels.
```
var win = new BrowserWindow({
    width: 800, 
    height: 600,
    frame: false,
    resizable: false
  });
  win.maximize();
```

**Comment by HitomiTenshi** [comment]
It bugs me that the resize border is inset when creating a frameless window. I have to set non draggable borders around the resizable area, to keep the resize functionality. Shouldn't frameless work exactly the same as `resizable: false`, just with the actual resize functionality? Maybe that's why it keeps oversizing...

Try using this:

in index.js:

```
var win = new BrowserWindow({
    width: 800, 
    height: 600,
    frame: false
});
```

in some css file:
```
body {
  -webkit-app-region: drag;
}
```

You will notice, that you can't resize the window anymore, because the resize border is inset and is being overwritten by the dragable area. Shouldn't it still be resizable? I believe that the inset resize border might cause this bug.

On a side note: I tried using `resizable: false` but for some reason it breaks `win.isMaximized()`. It doesn't return `true` anymore.

**Comment by liusy182** [comment]
>You will notice, that you can't resize the window anymore, because the resize border is inset and is being overwritten by the dragable area. Shouldn't it still be resizable? I believe that the inset resize border might cause this bug.

I am encountering exactly the same issue. This can be workarounded by giving a top margin to the draggable region so that they do not overlap.



> On a side note: I tried using resizable: false but for some reason it breaks win.isMaximized(). It doesn't return true anymore.

I am not sure if this is considered as a bug. If we just look at the current behavior, when a window is not resizable, maximizing it is essentially setting the window size to the screen size without actually 'maximizing' it. If you try `win.isMaximizable()` is will return false.

**Comment by HitomiTenshi** [comment]
> I am encountering exactly the same issue. This can be workarounded by giving a top margin to the draggable region so that they do not overlap.

So will this get fixed? I think this is the issue that's also causing the window to oversize.

**Comment by HitomiTenshi** [comment]
@kevinsawicki I'm still having this issue with electron v1.5 😞 using v1.4.13 hides fewer pixels at the top when maximizing.

**Comment by tonyganch** [comment]
I've git-bisected the repo to see that the line causing the issue is this one:
https://github.com/electron/electron/blob/master/atom/browser/ui/win/atom_desktop_window_tree_host_win.cc#L33

When I remove that, windows with both `frame: false` and `frame: true` behave okay on my Windows 10 machine.
I see that it's been added in this commit (https://github.com/electron/electron/commit/9e0547b98f8b7f3a572aa1cf9770f434c8fdeed9) as part of this PR (https://github.com/electron/electron/pull/8404).
Can someone please explain why we need that method/line?

I've also created a test repo with colourful background to make it easier to see how many pixels are missing:
https://github.com/tonyganch/electron-oversized-test

**Comment by HitomiTenshi** [comment]
@tonyganch I made you a PR for easier project setup, please accept it.

This issue is still bothering me with `electron v1.6.1`, I would be glad if this issue finally gets fixed.

**Comment by Sential** [comment]
#9017

**Comment by kevinsawicki** [comment]
Even though #8728 is newer, I'm going to merge this issue into that one since it has very detailed discussions and a targeted pull request, thanks @HitomiTenshi for all the details you posted here.
