### ISSUE TITLE
Chrome update to 55?

### ISSUE THREAD

**Issue by bernex** [electron/electron#8461]
Hi, do you have plan to update to 55 or 54? Thank you!

**Comment by MarshallOfSound** [comment]
A beta `1.5.0` (including Chromium 54) is on it's way.

https://github.com/electron/electron/pull/8406#issuecomment-273905591

The official word regarding updating the internal Chromium version can be found here

http://electron.atom.io/docs/faq/#when-will-electron-upgrade-to-latest-chrome

> The Chrome version of Electron is usually bumped within one or two weeks after a new stable Chrome version gets released. This estimate is not guaranteed and depends on the amount of work involved with upgrading.

It is worth noting that updating to Chromium 54 took a significant amount of time due to the complex nature of the upgrade.  (The build system Chromium uses changed).

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
