### ISSUE TITLE
How to make connection between JS and Java backend servlet in Electron

### ISSUE THREAD

**Issue by HegdeSach** [electron/electron#8543]
I have an application which has HTML+JS as frontend and a Java servlet as backend to perform some file operation.

As an eclipse project I had web.xml as a connector between JS and Java servlet and the project I was running on tomcat server.

But in electron frontend will not be on server. However i tried keeping servlet on seperate tomcat server and I am getting 403 (Forbidden) error.

I have even tried connecting with a servlet sitting on real server (not localhost) and I got succeeded.

But in my desktop application I need to access the local servlet (if it is on localhost is also fine) not the servlet on real server.

**Comment by kevinsawicki** [comment]
You should be able to connect to the local server the same way as you would in a standalone browser like Chrome.

Does your Java servlet require any authentication?

**Comment by groundwater** [comment]
Assigned offtopic because this doesn't sound like a bug, or a feature request at the moment. I'm going to close it, but that doesn't prevent you and @kevinsawicki from hashing out some more details. If this turns out to be a bug, you're welcome and encouraged to re-open or file a new issue with a repro case. Thanks!
