### ISSUE TITLE
SORT OUT the files. Such as *.dll to "lib" folder, *.pak to "assets" folder, etc.

### ISSUE THREAD

**Issue by anyxgit** [electron/electron#8593]
As the title

**Comment by felixrieseberg** [comment]
Hey, thanks for opening an issue! Sadly, in its current state, the issue is neither actionable nor helpful - please take a moment to review our [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md). If you have any questions about them, feel free to reach out ℹ️
