### ISSUE TITLE
App created using electron + angularjs2 wont invoke asprise scanner js UI or native scanner UI

### ISSUE THREAD

**Issue by sy-naveen** [electron/electron#8646]
App created using electron + angularjs2 wont invoke asprise scanner js UI or native scanner UI

Electron version: 1.3.3
OS : windows 10

Expected behavior : 

 It has to show this window
![acbc7f90a07e4d35a5a7570c45846e64](https://cloud.githubusercontent.com/assets/23548303/22796827/ed5083ea-ef21-11e6-9c26-ed74251d2b53.png)

Actual behavior :
This is working fine, with just angular2. If we combine it with electron the asprise scanner UI wont show.

Reproduce:
 You can watch the demo [here]( http://htmlpreview.github.io/?https://github.com/Asprise/scannerjs.javascript-scanner-access-in-browsers-chrome-ie.scanner.js/blob/master/demo-01-scan-display-jpg.htm) in browser its showing the asprise UI. But in electron app it wont show

**Comment by kevinsawicki** [comment]
@sy-naveen this looks to be because having node integration on that page some how causes the JavaScript running on it to fail to load:

```
Uncaught ReferenceError: scanner is not defined
    at scanner.js:1
```

If you create the `BrowserWindow` like:

```js
new BrowserWindow({
  webPreferences: {
    nodeIntegration: false
  } 
})
```

Then the UI does load:

<img width="1388" alt="screen shot 2017-02-10 at 10 27 01 am" src="https://cloud.githubusercontent.com/assets/671378/22838778/7d1ac1c6-ef7b-11e6-971a-69cad8523e14.png">


Closing this out since this doesn't appear to be an Electron issue, but an issue with that `scanner.js` when certain node globals are set in a browser context.
