### ISSUE TITLE
[Question] What is release strategy for beta versions?

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#8701]
I'd like to test beta versions but now you have 2 beta versions available 1.5.1 and 1.6.0.
Both versions will be released? Do you have schedule for releases?.

Just din't want to waste time with testing 1.5.1, if 1.6.0 will be released in short time.

**Comment by kevinsawicki** [comment]
> Both versions will be released?

There probably won't be another 1.5.x release since we upgraded quickly to Chrome 56 in 1.6 and we bump the minor in ever major Chrome upgrade.

There will be another 1.6 release in the next week to the beta channel, if all goes well with it we may promote to stable or release further betas.

I'd recommend ignoring the 1.5 line and focus your testing on 1.6.x.

> Do you have schedule for releases?.

We don't have a formal release schedule, we try to release every week except in certain circumstances and we try to upgrade Chrome as quickly as possible once a new release hits stable.

**Comment by cumajkeee** [comment]
@kevinsawicki thanks for the info.
