### ISSUE TITLE
`executeJavaScript` cannot get result when Promise overridden by content page.

### ISSUE THREAD

**Issue by binux** [electron/electron#8752]
* Electron version: 1.6.0
* Operating system: macOS

### Expected behavior

print "2" and quit

### Actual behavior

never quit

### How to reproduce

Running following code:

```
const {app, BrowserWindow} = require('electron')

app.on('ready', () => {
  let win = new BrowserWindow();
  //win.loadURL('data:text/html,<html>');
  win.loadURL('data:text/html,<script>window.Promise=null</script>');
  win.webContents.executeJavaScript('1+1', (result) => {
    console.log(result);
    app.quit();
  });
});
```

Or with a real case: `win.loadURL('https://www.tumblr.com/');`

### Possible solution

The Promise in [this line](https://github.com/electron/electron/blob/8e203592e25db081dc68db086938157d0847f169/lib/renderer/init.js#L42) could be overridden by content page, which cause 

```
 Uncaught TypeError: Promise.resolve is not a function TypeError: Promise.resolve is not a function
 at Function.responseCallback (Electron.app/Contents/Resources/electron.asar/renderer/init.js:42:13)
 at EventEmitter.electron.ipcRenderer.on (Electron.app/Contents/Resources/electron.asar/renderer/init.js:51:28)
```

import `Promise` into the scope can solve this.

**Comment by MarshallOfSound** [comment]
I'm not sure if this is actually a bug, technically any page can do something funky like override `Function.prototype.call` and ruin your day.

If you want a safety net I believe the `contextIsolation: true` would help ( @kevinsawicki ?)

We can protect against this particular case by saving the original value of `Promise` but it feels weird 😕

**Comment by binux** [comment]
Unfortunately `contextIsolation: true` doesn't work for my use case.

For example the lib [nightmare](https://github.com/segmentio/nightmare) I'm using, [override `console.log`](https://github.com/segmentio/nightmare/blob/master/lib/preload.js#L35) in order to
capture the log from loaded page. With `contextIsolation: true`, `preload.js` cannot replace the methods in loaded page either.

I know the solution cannot prevent every, at least that will solve the tumblr case for me. (or I can only `electron.ipcRenderer.removeAllListeners("ELECTRON_INTERNAL_RENDERER_ASYNC_WEB_FRAME_METHOD")` and install another listener, which is more ugly...)

**Comment by kevinsawicki** [comment]
> If you want a safety net I believe the contextIsolation: true would help

Yup, this should address this issue because the `Promise` global will be sandboxed in each JS context.

> We can protect against this particular case by saving the original value of Promise but it feels weird 

Yeah, we typically only do this to in cases where we want to prevent tampering for code that runs in both the isolated context and main context like here: https://github.com/electron/electron/blob/cc688d7fa6a48e5133735eb67d665f5d193ec94f/lib/renderer/window-setup.js#L26

People may want to override `Promise` for debugging, better implementation, etc. so preventing that doesn't feel the right move without a good reason.

`contextIsolation` prevents any built-ins used by the Electron page from being tampered with by the loaded page.

How does this sound to you @binux?

**Comment by kevinsawicki** [comment]
>  With contextIsolation: true, preload.js cannot replace the methods in loaded page either.

You should be able to replace these methods using `webFrame.executeJavaScript` which runs in the main page's context. http://electron.atom.io/docs/api/web-frame/#webframeexecutejavascriptcode-usergesture-callback

**Comment by binux** [comment]
> You should be able to replace these methods using webFrame.executeJavaScript

But it cannot export ipc into the context to forward the message back. I guess.

**Comment by kevinsawicki** [comment]
So from `preload.js`:

```js
webFrame.executeJavaScript('console.log = function (message) { alert(message) };')
```

**Comment by binux** [comment]
So I can receive the message via `anything.on('alert')` ? But I saw nightmare also overridden `window.alert` [ref](https://github.com/segmentio/nightmare/blob/master/lib/preload.js#L56), I suppose there is no such event?

**Comment by kevinsawicki** [comment]
> So I can receive the message via anything.on('alert') ? But I saw nightmare also overridden window.alert ref, I suppose there is no such event?

So nightmare could support context isolation by using `window.postMessage` to forward messages across contexts to perform the action(s) from a `window.addEventListener('message', function () {})` listener.

I'm okay moving `Promise` to a constant in the meantime since `contextIsolation` is pretty new still, but others things still may break since, as @MarshallOfSound mentioned, the page shares built-ins with the Electron API and can therefore tamper with and delete many of the built-ins the API relies on.
