### ISSUE TITLE
atom-shell how to do support PDF Viewer?

### ISSUE THREAD

**Issue by jimtang9527** [electron/electron#879]
in atom-shell ,chrome PDF Viewer disabled. how to do can support PDF Viewer? thanks

**Comment by m1ga** [comment]
since the latest build includes a pdf.dll shoulnd't it be possible to open a pdf viewer in an iframe? It says couldn't load plugin when I try it. Do I have to add anything special? I have a html5 app running in a browser windows (pages, mp4 videos, etc. is running fine). Just want to add a pdf viewer (iframe with pdf file as src)

**Comment by hokein** [comment]
@m1ga 
The code of PDF Viewer plugin is very complicated and integrated with Chromium's browser and extension code, so we won't support it in Electron.
