### ISSUE TITLE
Build Windows 7 Problem

### ISSUE THREAD

**Issue by rafadsm20** [electron/electron#8798]
I'm using the latest version available for the electron
I am using Windows 7 Ultimate (x64)
I follow the build tutoria inl website: [build-instructions-windows](https://electron.atom.io/docs/development/build-instructions-windows) , but I could not build

I tried with Cygwin and Windows Terminal, but I have the same mistakes

Image: [here](https://www.imageupload.co.uk/images/2017/02/28/e.e.png)

Commandline: bootstrap.py --msvs

```
$ /cygdrive/c/Python27/python.exe script/bootstrap.py --msvs
Cloning into 'C:/Users/Administrador/Desktop/GIT/electron/electron/vendor/reques                                                                                                    ts'...
Submodule path 'vendor/boto': checked out 'f7574aa6cc2c819430c1f05e9a1a1a666ef81                                                                                                    69b'
Submodule path 'vendor/depot_tools': checked out '4fa73b8ca6899bc69577932b80145a                                                                                                    6bf07e4424'
fatal: Needed a single revision
Unable to find current revision in submodule path 'vendor/node'

Traceback (most recent call last):
  File "script/bootstrap.py", line 264, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 34, in main
    update_submodules()
  File "script/bootstrap.py", line 128, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\Users\Administrador\desktop\GIT\electron\electron\script\lib\util.py"                                                                                                    , line 182, in execute_stdout
    execute(argv, env)
  File "C:\Users\Administrador\desktop\GIT\electron\electron\script\lib\util.py"                                                                                                    , line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init',                                                                                                     '--recursive']' returned non-zero exit status 1
```

**Comment by groundwater** [comment]
Hi @rafadsm20. Can you let us know what branch you're building from?

**Comment by rafadsm20** [comment]
I'm trying on a master

**Comment by alespergl** [comment]
@rafadsm20 
> `fatal: Needed a single revision`

That is odd. You're basically getting an error from `git` when trying to check out the submodules, which indicates a problem in your main electron checkout.

Since you've checked out `master`, you may have gotten a revision which doesn't have correct submodule mapping. Please try building from a tagged revision first, e.g. [v1.6.1](https://github.com/electron/electron/tree/v1.6.1).

If that doesn't work...

1. Have you done a clean checkout of electron, or do you have some local changes?
2. I personally have never used Cygwin to build Electron, so I suggest you stick to `cmd.exe`. Also make sure you have the latest version of Git.
3. There might be something in your environment interfering with the build script. Please try these basic steps first:
  - Open new command prompt and type `set`. Check the output for sensitive information, remove it, and share the rest here (let us know if you _have_ removed something).
  - `cd` into an empty directory and clone the repo again: `git clone https://github.com/electron/electron.git`
  - Type `cd electron` and then `git submodule update --init --recursive`. What's the output?
4. I noticed you have a non-English version of Windows. If all else fails, you could try to temporarily set your locale to en-US and see if it helps.

**Comment by cifratila** [comment]
@rafadsm20 

This issue happens usually if you have had checked before another branch of electron and tried to bootstrap it. Has happened to me several times. Basically, you will end up with mismatched submodules. One easy fix is to run deinit on all modules and then run the bootstrap script once more.

`git submodule deinit -f --all`

Or just remove the electron repo and clone the master branch once more.

I have tried building directly from master, so the submodules are correctly mapped.

**Comment by cifratila** [comment]
@rafadsm20 Everything good here? Could we close?

**Comment by zcbenz** [comment]
Closing since the problem seems to have been solved.
