### ISSUE TITLE
BrowserWindow support MDI mode

### ISSUE THREAD

**Issue by tkggusraqk** [electron/electron#8820]
Recently used electron, need to use MDI mode, in a window to manage Page. Found not support MDI, so use webview instead. But there are problems in the two webview, the program will appear for a long time does not operate, resulting in the program can not respond to the problem, so far did not find the reason.

electron-version:1.4.15
node-version:6.2.0

**Comment by enlight** [comment]
It's unclear what you're actually asking. Is this a feature request?

**Comment by tkggusraqk** [comment]
@enlight Just want to know will not support MDI, because webview with some really inconvenient。

**Comment by kevinsawicki** [comment]
> Just want to know will support MDI?

There is work going on for a new `BrowserView` class in Electron (#9166) that may help with this as well as ongoing improvements in Chrome to make `<webview>` tags better (https://www.chromium.org/developers/design-documents/oop-iframes).

Closing this out since this seems like more of a general question.
