### ISSUE TITLE
Widevine fails with release builds since 1.5.x

### ISSUE THREAD

**Issue by L-P** [electron/electron#8824]
Hi,

I'm trying to get Electron to play some Widevine content, everything is set up
as described in the [docs](https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md).

It won't work. The Widevine lib comes from the exact same Chrome version
Electron uses, calling `navigator.plugins` as mentioned in #6516
does not change anything, the result is the same in both Win32 x64 and Linux x86_64.

The plugin is loaded, it is detected by Shaka and the Bitmovin demo, but trying
to use it will result in the following error:

`Shaka Error DRM.FAILED_TO_CREATE_CDM (Unable to create the CDM for the key system com.widevine.alpha.)`

I don't know where the bug is, stand-alone Chrome has no problem reading
Widevine contents so I guess it's somewhere in Electron but I don't know where
to start to debug it.

* Electron version:
```
electron@^1.6.1:
  version "1.6.2"
  resolved "https://registry.yarnpkg.com/electron/-/electron-1.6.2.tgz#b0ccd7703f86d09c4d2a7273455c3f993f158994"
```

* Operating system: Lubuntu 16.04 x86_64 / Windows 10

### Expected behavior

Widevine content should play.

### Actual behavior
![widevine_failure](https://cloud.githubusercontent.com/assets/947312/23548495/1197401c-0008-11e7-8e2c-c26271363a47.png)

Widevine is unavailable.

### How to reproduce

`yarn install && ./run`
[repro.zip](https://github.com/electron/electron/files/816542/repro.zip)

**Comment by webnard** [comment]
Same issue here

Chrome-reported libwidevine.so version: 1.4.8.962

a232e95450e12e773ed39b985aa841f8  /opt/google/chrome/libwidevinecdmadapter.so
a649358a9749c346c39f6bf0dec11337  /opt/google/chrome/libwidevinecdm.so

```bash
$ electron --version
v1.6.1
```

Failing code:

```javascript
'use strict';                                                                   
const {app, BrowserWindow } = require('electron');                              
                                                                                
app.commandLine.appendSwitch('widevine-cdm-path',
  '/opt/google/chrome/libwidevinecdmadapter.so');

app.commandLine.appendSwitch('widevine-cdm-version',
  '1.4.8.962');

app.on('ready', () => {
  const win = new BrowserWindow({                                                                                                     
    webPreferences: {                                             
      plugins: true,
    },                                                                          
  });                                                                           
  //const url = 'https://netflix.com';                                          
  const url = 'https://shaka-player-demo.appspot.com/demo/';                    
  win.loadURL(url);                                                             
});
```

**Comment by willnix** [comment]
I am experiencing the same behavior on ArchLinux running the exact software versions @webnard mentioned.
Just wanted to add that I had no issues getting the examples to work on a Windows machine.

**Comment by willnix** [comment]
Just a little more info:
If I call ``navigator.plugins.item()`` as suggested in #6516 the shaka demo detects the plugin.
But trying to load a widevine profile fails with ``DRM.LICENSE_REQUEST_FAILED``.
The issue seems to be caused by an empty body of the license request which is empty because the CDM seems to return nothing, when it should be returning a license request message.

**Comment by webnard** [comment]
@willnix How did you get it working in Windows? I'm running into the same problem on Windows 7 with the latest version of Widevine and Electron 1.6.2. What are your Windows versions of electron, Widevine, and Chrome?

**Comment by willnix** [comment]
I can't tell you for sure because I don't have access to my windows machine atm, but I will check tonight.
What I definitely do remember is the widevine version was the same I used on Linux: 1.4.8.962
And I updated electron and chrome to the latest versions just before trying it, so I'm pretty sure we're talking about 1.6.2 and 56.0.2924.87.
The only apparent difference I could find is, that more recent versions of widevine include a signature for the library file. The chrome windows builds already ship with a "widevinecdm.dll.sig" whereas on linux you can find the signed version only in the chrome unstable builds.
On Windows I therefore made sure my folder contained "widevinecdm.dll", "widevinecdm.dll.sig" and "widevinecdmadapter.dll".

**Comment by deepak1556** [comment]
I am able to reproduce this on arch linux, accessing `navigator.plugins` and reloading the shaka player demo fixes the problem. Is that consistent for you @willnix @webnard ?

> The chrome windows builds already ship with a "widevinecdm.dll.sig" whereas on linux you can find the signed version only in the chrome unstable builds.

@willnix The chrome stable build on linux runs shaka player just fine, so I don't think the signature file is the problem. But just to be sure, does removing the signature file on windows creates any problem ?

**Comment by willnix** [comment]
@deepak1556 Unfortunately reloading after accessing  ``navigator.plugins`` only lets the demo detect the plugin but it still behaves as [described](https://github.com/electron/electron/issues/8824#issuecomment-285114744). I attached a screenshot ![screenshot](https://cloud.githubusercontent.com/assets/807270/23750972/a05c5352-04cf-11e7-8931-8cb2784bee9a.png) of the situation.


Regarding the signatur file:
I agree that that's probably not an issue on Linux because the 1.4.8.962 Linux version in chrome works fine without it.
I'm just saying the Windows version might already require it, as future Linux versions probably will.
I will try and let you know what happens if I remove the file on windows.

**Comment by deepak1556** [comment]
@willnix I am using the test case provided by @webnard , but once reloaded the player plays fine. I don't see the http request fail. Is the license request consistently failing for you on linux ?

**Comment by willnix** [comment]
I tried it on two different systems both running up to date ArchLinux. Giving me consistently the above error with the failed request.

The widevine docs state a 400 response is the appropriate response if a license request is denied.
Which is to be the expected result because the request body should contain a valid license request but in my case is empty.
If I run the shaka demo on the same system in the very chrome version I got the .so files from, the requests body is not empty and the response is not 400 but a valid DRM license.

**Comment by webnard** [comment]
@deepak1556 I am also running Arch Linux and see the same error message pop up. The Star Trek intro plays for about 8 seconds before the Shaka player forces it to pause. 
Netflix fails as well (but I have to set `nodeIntegration: false` to even log in).

The Widevine format works without fail in Chrome on the same system, as with @willnix.

Here's what I get from Netflix:

![screenshot from 2017-03-09 08-50-02](https://cloud.githubusercontent.com/assets/1213808/23752941/6ee7d064-04a5-11e7-82be-1de5a5009e30.png)

**Comment by deepak1556** [comment]
> The widevine docs state a 400 response is the appropriate response if a license request is denied.
Which is to be the expected result because the request body should contain a valid license request but in my case is empty.

Yup, but in my case the request body is available and it succeeds. A little digging shows the request body is based on mediaKeys.createSession not sure why it fails for you, but it is definitely linked to the original issue of plugin not loaded on first run with error `DOMException: Unable to create the CDM for the key system com.widevine.alpha.`

> The Star Trek intro plays for about 8 seconds before the Shaka player forces it to pause.

Hmm, the video played for me completely. No error once reloaded, my arch linux version 4.9.8-1, let me check if updating to latest.

**Comment by webnard** [comment]
@deepak1556 FWIW, I'm on 4.9.11-1-ARCH x86_64

**Comment by deepak1556** [comment]
I tested with 1.6.2 and I am able to reproduce the license request fail after the reloading. I was previously testing with the debug build of electron.

**Comment by willnix** [comment]
Thank you!
I can confirm that checking out the current electron master and building it leads to a working Debug build and a broken Release build.
