### ISSUE TITLE
touchbar issue  

### ISSUE THREAD

**Issue by Enivel** [electron/electron#8904]
can we  hide macos  right control strip.  

thks guys.

**Comment by MarshallOfSound** [comment]
As per the Apple docs for [`NSTouchBar`](https://developer.apple.com/reference/appkit/nstouchbar)

> The user controls the width of the Control Strip and can choose to hide it, and the system is in charge of the nesting of NSTouchBar instances (for the bars you make eligible for composition). As a result, the available display width for your bars can vary. There is no API for you to obtain the current available display width.

The user can choose to hide it, we can not hide it programmatically.  However as also mentioned in the docs

> If you need more horizontal space than might be available, use a popover item, a scrubber, or a scroll view—as they fit your design needs, but in that, descending, order of preference.

We currently support "PopOver" touch bar items so that would be your best option if you want the full width 👍

**Comment by Enivel** [comment]
Cool  Thanks for you work.
but PopOver show type like this? 

![image](https://cloud.githubusercontent.com/assets/1982819/23822521/308b2844-0689-11e7-9970-b405bce5ccdc.png)
