### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by paul321** [electron/electron#8925]
Just tested 1.6.3 beta and i keep getting a lots of warnings, any ideas?

* Electron version: 1.6.3
* Operating system: Windows

(node:9244) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
process.on @ internal/process/warning.js:21
emitOne @ events.js:96
emit @ events.js:188
process.nextTick @ internal/process/warning.js:47
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

**Comment by kevinsawicki** [comment]
You should be able to set `process.throwDeprecation = true` early on and then it will throw instead of log for deprecations and you'll see the full stack trace of the calling code.

This is the result of calling an async `fs` API without a callback, https://github.com/nodejs/node/blob/5bfd13b81e38b60a7b9f346fbfcb216192cf0974/lib/fs.js#L94-L97 like:

```js
require('fs').readFile('/path/to/file.json')
```

Can you try setting `process.throwDeprecation` and confirm whether these are from core Electron code or your app's code?

**Comment by paul321** [comment]
Yes it was a forgotten callback param from fs.appendFile

**Comment by kevinsawicki** [comment]
> Yes it was a forgotten callback param from fs.appendFile

Thanks for the update, closing this out.
