### ISSUE TITLE
autoUpdater.checkForUpdates executes main after `update-downloaded`

### ISSUE THREAD

**Issue by rynz** [electron/electron#8943]
* Electron version: 1.6.2
* Operating system: Windows 10 64-bit

### Expected behavior

`autoUpdater.checkForUpdates` not re-run main when an update has been downloaded, main should only be run after `autoUpdater.quitAndInstall()`.

### Actual behavior

`autoUpdater.checkForUpdates` after downloading an update re-runs main, causing `process.argv[1]` to be `--squirrel-updated` and any shortcut code `app.quit` etc after that without manually running `autoUpdater.quitAndInstall()`

### How to reproduce

```
this.autoUpdater = require('electron').autoUpdater;
this.autoUpdater.setFeedURL(UPDATE_URL);
this.autoUpdater.checkForUpdates();
```

**Comment by kevinsawicki** [comment]
> autoUpdater.checkForUpdates after downloading an update re-runs main, causing process.argv[1] to be --squirrel-updated

I believe this is the expected behavior, while the update is being installed the new app is spawned with that CLI so that it can update any shortcuts, registry keys, etc.

`quitAndInstall` just restarts the app to the new version, but it is already installed on Windows when that happens.

Do you think that is what you are seeing?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
