### ISSUE TITLE
nameFieldLabel in dialog is getting cut off

### ISSUE THREAD

**Issue by roypardi** [electron/electron#8949]
Electron 1.6.3
OSX 10.11.16

Using the code below to create a "Save" dialog, the `nameFieldLabel` is getting cut off: I specified "Directory Name" but only "Directory" shows. If a longer string is used ("ThisIsALongName") then the string will get cut in the middle. Don't know if this is an OSX or Electron issue (or "as designed")

---
<img width="300" alt="screen shot 2017-03-17 at 9 54 39 am" src="https://cloud.githubusercontent.com/assets/9053196/24046618/849253d0-0af9-11e7-8f6f-c6311473cfd1.png">

```
ipcMain.on('sync', (event, arg) => {

    switch (arg) {
        case "createProjectDirectory":
            var options = {
                title: "Create Project Directory",
                message: "Create Project Directory",
                nameFieldLabel: "Directory Name"
            }
            dialog.showSaveDialog(mainWindow, options, createDirectoryCallback);
            break;
    }
});
```

**Comment by kevinsawicki** [comment]
>  Don't know if this is an OSX or Electron issue (or "as designed")

I'm not seeing anything in the docs about this, https://developer.apple.com/reference/appkit/nssavepanel?language=objc so I don't think this is possible to configure or override.

So I'm going to close this out since it doesn't look like there are APIs currently to change this behavior.

Can reopen if `NSSavePanel` expands support for this.
