### ISSUE TITLE
Electron.app cannot be copied with node.js

### ISSUE THREAD

**Issue by mk010101** [electron/electron#8951]
My Electron app needs to create other Electron-based stand-alone apps.

It fails at the first step when I try to copy the original Electron.app using fs-extra. It appears the copying process fails when it reaches **default_app.asar** or **electron.asar** inside **Electron.app/Contents/Resources/electron.asar**

I tried zipping Electron.app, copying the zip file and the unzipping with gulp-unzip, but unzip fails apparently for the same reason!

How can I reliably copy Electron.app using node.js?
-----------------
* Electron version: 1.6.2
* Operating system: OSX

**Comment by MarshallOfSound** [comment]
@mk010101 If you need to treat an ASAR as a file and not as a fake directory (default behavior inside electron).  You need to either use `fs-original` instead of `fs` or set `process.noAsar` to `true`.

https://github.com/electron/electron/blob/master/docs/api/process.md#processnoasar

Make sure you set it to `false` again afterwards or bad things might happen 👍

**Comment by mk010101** [comment]
Awesome! It solves the issue. 
One question though: what's the danger of disabling ASAR?

**Comment by MarshallOfSound** [comment]
@mk010101 `fs` operations inside the ASAR file will fail 👍
