### ISSUE TITLE
Loading a URL and passing a variable into the new window

### ISSUE THREAD

**Issue by mikekok** [electron/electron#8976]
* Electron version: 1.6.2
* Operating system: Windows 10 (64-bit)

### Expected behavior

I'm trying to load a URL and pass a variable to the new window using synchronous messages.
This is the code I'm using in my renderer:
```
$("#movies").on("click", ".movie", function() {
        var imdb = $(this).children('input').val(); // the value I want to pass
        const reply = ipc.sendSync('load-movie', imdb);
        $('#imdb').text(reply); // trying to set the text of my div to this value
});
```

And this is the code in my main:
```
ipc.on('load-movie', function(event, arg) {
        mainWindow.loadURL('file://' + __dirname + '/movie.html?imdb=${arg}'); //loading the new URL
        event.returnValue = ${arg}; //returning the imdb id in order to set it to my div's text
})
```

### Actual behavior

The window loads but nothing is happening after that. No value is returned.

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

Electron restarts the renderer process on navigation, which is why you never see the reply.
