### ISSUE TITLE
TouchBarLabel disappears when the text overflows 

### ISSUE THREAD

**Issue by salomvary** [electron/electron#9009]
* Electron version: 1.6.4
* Operating system: macOS 10.12.3 (16D32)
* TouchBar simulator from XCode 8.2.1 (8C1002)

Given a TouchBar like this:

```js
  new TouchBar([
    new TouchBarButton({
      label: 'btn'
    }),
    new TouchBarLabel({
      label: 'hello'
    })
  ])
```

### Expected behavior

The text of `TouchBarLabel` should always be visible on the touch bar no matter how long it is (text might be cropped).

### Actual behavior

If the (visual) length of the label text on `TouchBarLabel` exceeds the available space the label text completely disappears. 

### How to reproduce

```
git clone git@github.com:salomvary/electron-touchbar-bug.git
cd electron-touchbar-bug
npm install
npm start
```
Move the slider to set a shorter/longer label text.

Interestingly the issue does not occur if the `TouchBarLabel` is not preceded by a `TouchBarButton`.

**Comment by MarshallOfSound** [comment]
@salomvary This sounds suspiciously like a macOS issue (if the label only gets cut off when preceded by a button), touch bar items shouldn't affect other touch bar items.

I'll look into this when I get a change 👍

**Comment by MarshallOfSound** [comment]
As far as I can tell this is part of the spec for the TouchBar, if any item would exceed the available space it is either cropped or hidden.  Why it chooses to hide vs crop in some cases I can not explain, apple either made it like that or it is a bug in macOS 🤷‍♂️ 

A possible workaround to this is implementing a new touch bar item which contains a [`NSScrollView`](https://developer.apple.com/reference/appkit/nsscrollview?language=objc) so that long labels can just be scrollable 👍

**Comment by salomvary** [comment]
That might make sense. Proactively and space-efficiently trimming the text to avoid accidental and uncertain hiding of TouchBarLabel is nearly impossible. Neither the available space is known nor is it straightforward to calculate the pixel-width of the to-be-rendered text.

**Comment by zcbenz** [comment]
Closing since it is a behavior of macOS.
