### ISSUE TITLE
Indicator icon missing in Ubuntu 17.04

### ISSUE THREAD

**Issue by mcg** [electron/electron#9046]
* Electron version: multiple
* Operating system: Ubuntu 17.04

### Expected behavior

Electron based apps that provide an indicator icon display the icon

### Actual behavior

Indicator icon is not displayed

### How to reproduce

I have this issue in several up to date Electron based applications. Such as: Slack, Google Desktop Music Manager, Skype, etc...

The work around of `export XDG_CURRENT_DESKTOP=Unity`, mentioned in some older issues does work to fix the issue.

**Comment by mcg** [comment]
Possibly related Ubuntu bug https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1629251

**Comment by Thomas101** [comment]
We're seeing the same too :(

**Comment by mcg** [comment]
FWIW With the impending end of Unity, I've switched back to Ubuntu GNOME. Same desktop as before but Electron tray icons show up fine in the GNOME `legacy tray icon` strip.

**Comment by orschiro** [comment]
The same for me. I switched from Unity to MATE and there the indicator icons as well as the legacy tray ones show up.

**Comment by UserContributer** [comment]
Ah, the joys of non LTS, you get to see issues occur before they even had a chance to be fixed!  Kidding, this crap is getting annoying, why did they bother to change anything in Unity 7 if they were trying to replace it, it's just stupid.

**Comment by luispabon** [comment]
Workaround here: http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html

**Comment by Spurlos** [comment]
So it looks like all electron apps are suffering this bug due to variable name change in Ubuntu 17.04. Workaround isn't the best way to launch all those apps. Seems that electron needs to update their framework, and app developers need to use the updated version. Any ETA on that? I'm kinda affected with this bug a lot, because i use a lot of electron build apps.

**Comment by UserContributer** [comment]
I noticed it when I tried to launch Discord shortly after upgrading my system (so I searched the internet to find this bug, and within a day or two, sure enough, it was mentioned).

**Comment by MarshallOfSound** [comment]
Seems like a simple enough fix if someone wants to take this one on.  Basically just need to add another if condition to this workaround

https://github.com/electron/electron/blob/d0643250f717a9e5d9d4869f72fd5437c88e862f/lib/browser/init.js#L166

Something like:

```js
if (process.platform === 'linux' && ['Pantheon', 'Unity:Unity7'].indexOf(process.env.XDG_CURRENT_DESKTOP) !== -1) {
  process.env.XDG_CURRENT_DESKTOP = 'Unity'
}
```

I don't have a 17.04 VM and don't have the time rn to set one up, if someone with 17.04 can test that fix and PR it in (if it works) that would be great 👍

**Comment by mfonville** [comment]
@MarshallOfSound I think the correct way to be actually check if any of the values in the variable, that are colon-separated, matches `Unity` also see https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1554878

**Comment by MarshallOfSound** [comment]
@mfonville That seems more risky someone who is a lot more familiar with possible values for that environment variable should make that call.  I don't want to come across a situation where someone has the env var set to something silly like `Unity:MyCustomBuildFrom2002` and we try enable something that won't work 🤔 

IMO going the safe route is better unless someone can categorically say the above kind of situation won't happen

**Comment by UserContributer** [comment]
I found another workaround, where you could use the original .desktop shortcuts.

Edit ~/.profile with this line added to the end:
```
export XDG_CURRENT_DESKTOP=Unity
```

It should work for about any application that stopped showing an indicator in Ubuntu 17.04 till this problem gets sorted.

**Comment by UserContributer** [comment]
I discovered it by accident (that you could load environment variables into every app at once under your username via .profile) when I tried to get gtk themes to display on qt apps.

**Comment by molotovbliss** [comment]
How I resolved fixing the missing icons from windows buttons XFCE4 panel... mostly. 

By using `seticon`, `xwininfo` in a bash script which really does nothing much but use `xwininfo` to find the window title, and use a predefined icon path to pass to the window ID returned by `xwininfo`.  NOTE: the seticon `get-seticon.sh` portion of the script isn't tested, as installing `seticon` was difficult to install, until finding this gist from github user **unhammer** thanks a bunch! `xwininfo` should be already available, if not it's easy to install.

...and by mostly sometimes the `.desktop` file overrides the `/bin/bash ~/bin/fix-termius-icon.sh` and back to broken icon usually on reboots it seems, but if annoys enough just running the bash script after it's annoyed me enough.  Electron hopefully saves everyone's sanity, soon. 

Specs:
Ubuntu 16.04, XFCE4 Win Buttons panel, Slack and Termius SSH ugly default icons.

```
# configure
WIN_NAME="Termius";
APP_EXEC="/snap/bin/termius-app";
APP_ICON="/snap/termius-app/current/meta/gui/icon.png";

# how long to wait before looking for window title
TIME_WAIT_FOR_WINDOW=3;

$APP_EXEC &
sleep $TIME_WAIT_FOR_WINDOW;
env BAMF_DESKTOP_FILE_HINT="/var/lib/snapd/desktop/applications/termius-app_termius-app.desktop";
ID=$(xwininfo -name "$WIN_NAME"|grep xwininfo|cut -d ' ' -f 4);
xseticon -id $ID $APP_ICON;

```
If it doesn't work, bash it! Full script: :hammer: :rescue_worker_helmet: :penguin: 
- https://gist.github.com/molotovbliss/67c54e628c55c48891fd322983c2011a

**Comment by ostapch** [comment]
I also need this bug fix, cause I'm using enough programs based on electron and can't see their tray icons

**Comment by dakira** [comment]
@MarshallOfSound s [solution](https://github.com/electron/electron/issues/9046#issuecomment-296169661) above looks right. Can't test it myself, though.

**Comment by antelle** [comment]
@MarshallOfSound tested on latest ubuntu, it works actually, thanks

**Comment by ostapch** [comment]
So can anyone make PR?

**Comment by dakira** [comment]
Here is your PR.

**Comment by caneraydinbey** [comment]
I have also this

I just installed 17.04 server and then desktop but I have only those icons (this is not actually my setting, but it is broken the same way)

[![https://i.stack.imgur.com/jCM8h.jpg][1]][1]

I tried these command in an attempt to solve it:

sudo apt-get install ubuntu-desktop
sudo apt-get remove unity-control-center
sudo apt-get install unity-control-center
sudo apt-get install ubuntu-desktop
sudo apt-get install unity-control-center
sudo apt-get install unity-control-center-signon gnome-control-center-unity
sudo apt-get update --fix-missing
sudo apt-get -f install
But I did not manage to solve it. Can you suggest any ways to solve my problem?

i reinstalled ubuntu desktop notihng changed sudo apt-get install --reinstall ubuntu-desktop 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.

https://i.stack.imgur.com/jCM8h.jpg

I did this also

https://askubuntu.com/a/621874/694849

but it also added only one icon. online accounts.

They are lots of still missing icons like power.

When i write gnome-control -center, i t brings lots of icons but when i click for example display, console shows:

➜  ~ gnome-control-center

** (gnome-control-center:11997): WARNING **: Ignoring launcher gufw (missing desktop file)

** (gnome-control-center:11997): WARNING **: Ignoring launcher landscape-client-settings (missing desktop file)

** (gnome-control-center:11997): WARNING **: Ignoring launcher ubuntuone-installer (missing desktop file)

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunset data, using 16.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunrise data, using 8.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunset data, using 16.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunrise data, using 8.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunset data, using 16.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunrise data, using 8.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunset data, using 16.00

(gnome-control-center:11997): display-cc-panel-WARNING **: no sunrise data, using 8.00
And this did nothing

sudo apt-get install unity-control-center-signon gnome-control-center-unity
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'unity-control-center' instead of 'gnome-control-center-unity'
unity-control-center is already the newest version (15.04.0+17.04.20170402.6-0ubuntu1).
unity-control-center-signon is already the newest version (0.1.9+16.10.20160825-0ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-22 linux-headers-4.10.0-22-generic
  linux-image-4.10.0-22-generic linux-image-extra-4.10.0-22-generic
  linux-signed-image-4.10.0-22-generic
Use 'sudo apt autoremove' to remove them.
Also this did not do anything

sudo apt-get update
sudo apt-get install --reinstall ubuntu-desktop
sudo apt-get install unity
sudo shutdown -r now
see

➜  ~ sudo apt-get update
sudo apt-get install --reinstall ubuntu-desktop
sudo apt-get install unity
Hit:1 http://repo.steampowered.com/steam precise InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease        
Hit:3 http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu zesty InRelease
Hit:4 http://repository.spotify.com stable InRelease                
Hit:5 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu zesty InRelease
Hit:6 http://dl.google.com/linux/chrome/deb stable Release          
Hit:7 http://us.archive.ubuntu.com/ubuntu zesty InRelease           
Hit:8 https://deb.nodesource.com/node_6.x yakkety InRelease         
Hit:9 http://ppa.launchpad.net/papirus/papirus/ubuntu zesty InRelease
Hit:10 https://download.docker.com/linux/ubuntu zesty InRelease     
Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu zesty InRelease
Hit:12 https://packages.microsoft.com/repos/vscode stable InRelease 
Get:14 http://us.archive.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]
Ign:15 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 InRelease
Hit:16 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 Release
Get:18 http://us.archive.ubuntu.com/ubuntu zesty-updates InRelease [89.2 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu zesty-security/main amd64 DEP-11 Metadata [5,812 B]
Get:20 http://us.archive.ubuntu.com/ubuntu zesty-security/universe amd64 DEP-11 Metadata [8,904 B]
Get:21 http://us.archive.ubuntu.com/ubuntu zesty-security/universe DEP-11 64x64 Icons [27.0 kB]
Get:22 http://us.archive.ubuntu.com/ubuntu zesty-updates/main amd64 DEP-11 Metadata [41.8 kB]
Get:23 http://us.archive.ubuntu.com/ubuntu zesty-updates/main DEP-11 64x64 Icons [14.0 kB]
Get:24 http://us.archive.ubuntu.com/ubuntu zesty-updates/universe amd64 DEP-11 Metadata [57.5 kB]
Get:25 http://us.archive.ubuntu.com/ubuntu zesty-updates/universe DEP-11 64x64 Icons [58.7 kB]
Fetched 392 kB in 1s (228 kB/s)                                     
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-22 linux-headers-4.10.0-22-generic
  linux-image-4.10.0-22-generic linux-image-extra-4.10.0-22-generic
  linux-signed-image-4.10.0-22-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/3,612 B of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 356900 files and directories currently installed.)
Preparing to unpack .../ubuntu-desktop_1.379_amd64.deb ...
Unpacking ubuntu-desktop (1.379) over (1.379) ...
Setting up ubuntu-desktop (1.379) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
unity is already the newest version (7.5.0+17.04.20170407.1-0ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-22 linux-headers-4.10.0-22-generic
  linux-image-4.10.0-22-generic linux-image-extra-4.10.0-22-generic
  linux-signed-image-4.10.0-22-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by gmribas** [comment]
This workaround works for me:
http://www.dangtrinh.com/2017/04/fix-slacks-icon-tray-missing-in-ubuntu.html

**Comment by MEGApixel23** [comment]
Any updates on this? Is this bug going to be fixed in the nearest future?
Thanks.

**Comment by ivan-pinatti** [comment]
The information on the link that @gmribas shared solved the issue.

**Comment by MEGApixel23** [comment]
@ivan-pinatti Mentioned post looks like a workaround rather than resolving an issue.

**Comment by mcg** [comment]
Of course this issue is different on Ubuntu 17.10 where we have GNOME now and Ubuntu is using it's own Indicator GNOME extension and current Electron apps are not able to show an icon.

**Comment by ldartez** [comment]
@gmribas's workaround *does not* work for me. It has virtually no effect. :( 

            .-/+oossssoo+/-.               louis@xi
        `:+ssssssssssssssssss+:`           --------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 17.04 x86_64
    .ossssssssssssssssssdMMMNysssso.       Model: Blade 6.06
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.10.0-35-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 29 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2222
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.7
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Unity:Unity7
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Compiz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Ambiance
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Ambiance [GTK2/3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Ubuntu-mono-dark [GTK2/3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: x-terminal-emul
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-7700HQ (8) @ 3.8GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel Kabylake GT2
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce GTX 1060 Mobile
        `:+ssssssssssssssssss+:`           Memory: 4577MiB / 15932MiB
            .-/+oossssoo+/-.

**Comment by whitethunder** [comment]
In 17.10 and above, @gmribas's link works if I edit this file:

`~/.local/share/applications/slack.desktop`

Changing the `Exec` line to read:

`Exec=env XDG_CURRENT_DESKTOP=Unity /usr/lib/slack/slack`

**Comment by damianobarbati** [comment]
@whitethunder do you have your app tray icon working on Linux (appimage)? I can't see anything.

**Comment by jayarjo** [comment]
Neither do I.

**Comment by Botono** [comment]
The `XDG_CURRENT_DESKTOP=Unity` fix does not work for me with some apps in Ubuntu 18.04. Slack's icon appears, but not Plexamp.

**Comment by jayarjo** [comment]
@Botono do you fulfill the following requirement?

> On Linux platform, only supports Unity desktop environment, you need to specify the *.desktop file name to desktopName field in package.json. By default, it will assume {app.name}.desktop.

**Comment by jenciso** [comment]
I had this problem in Ubuntu 22.04 and Unity 7 in the new slacks version. I was able to resolve the issue using the same workaround.

echo "XDG_CURRENT_DESKTOP=Unity7" >> ~/.profile
