### ISSUE TITLE
Built for node v6.5.0

### ISSUE THREAD

**Issue by radencode** [electron/electron#9070]
I cannot build electron for node v6.5.0, it always comes out to be node v7.4.0.0 How can I build it for v6.5.0?

**Comment by kevinsawicki** [comment]
The version of node included with Electron is built via the `vendor/node` submodule in this repository.

Node is upgraded when Chrome is upgraded so that they use the same v8 versions and are compatible with each other. You may experience issues if trying to use a different node version than the one Electron is built and tested against.

If you need to build Electron against a different version of node, you can change the `vendor/node` submodule to check out the version you want to build against.

Closing this out.
