### ISSUE TITLE
Better error message for loading non-existent local URLs

### ISSUE THREAD

**Issue by popey456963** [electron/electron#9085]
* Electron version: v1.6.2
* Operating system: Windows 7

### Expected behavior

Attempting to load a URL which doesn't exist ("file://${__dirname}/main.html" for example) should return a useful error message.

### Actual behavior

Attempting to load said URL returns an error about not being allowed to open it, "Not allowed to load local resource".

### How to reproduce

Attempt to load any URL that does not exist within the ready state of the app:

```javascript
app.on('ready', () => {
	mainWindow = createWindow('main', {
		width: 600,
		height: 400
	});

	mainWindow.loadURL(`file://${__dirname}/this_does_not_exist/main.html`);
	mainWindow.on('closed', onClosed);
});
```

**Comment by deepak1556** [comment]
The error occurs when we are violating a security origin policy during navigation and it happens because initial navigation will end up with `data:text/html,chromewebdata` and when devtools is opened it sees origin violation. There is nothing we can do in this case, the behavior is same with chrome.
* Open new-tab
* navigate to non-existent local url
* open devtools

You can listen to `did-fail-load` event of webContents for better error messages.
