### ISSUE TITLE
Strut properties on X11

### ISSUE THREAD

**Issue by koterpillar** [electron/electron#9087]
I want to dock an Electron app to a side of (X11) display. To do this, X11 provides [_NET_WM_STRUT](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm140130317566832). Can it be exposed in Electron as `window.setStrut` or similar?

**Comment by zcbenz** [comment]
Not all window managers support hints like this, and some expect `_NET_WM_WINDOW_TYPE_DOCK` while some expect `_NET_WM_WINDOW_TYPE`, so for implementing the dock feature I doubt setting `_NET_WM_STRUT` would be enough.

I suggest working out a demo C program that implements docking yourself, and if it really works, we can integrate it into Electron.

Closing since it is a much larger task than it sounds, and the team does not have enough resources to study into it.

**Comment by Caellian** [comment]
All window managers support `_NET_*` atoms because they're required by the spec. `_NET_WM_WINDOW_TYPE_DOCK` is a value for `_NET_WM_WINDOW_TYPE` atom, and there's exactly one way to set it which is supported by all WMs because it's required by the spec. The only reason for it not working is implementation error or the WM explicitly not supporting dock-like applications (can't think of any that don't).

Stumbled across this while triaging issues. Just adding details to make X11 more approachable because it's obscure enough as it is.

But this issue should remain closed - because electron wasn't designed for dock applications on any platform. Each platform has vastly different implementation, requirements and restriction for this kind of functionality. So I concur it is a somewhat large task.
