### ISSUE TITLE
Screen draw issues on OS X in Parallels VM

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#9109]
* Electron version: 1.6.x
* Operating system: OS X 10.12.4 (Host), 10.11, 10.12 (Guest)
* Parallels: 12.1.3 (latest)

What can I do to help with this?

### Expected behavior
Screen draws properly
### Actual behavior
Screen doesn't draw properly on 1.6.x
Works as expected on 1.4.15

As per screenshots.  If I try highlighting content on the page it's there and randomly appears.

### How to reproduce
1. Extract example
2. npm install in root
3. cd app
4. npm install
5. cd into root
6. npm start

Change electron version between 1.4.15 and 1.6.x and see screen draw difference, as per screenshots

Screen draws ok on 1.4.1.5
![screen shot 2017-04-05 at 11 09 17 am](https://cloud.githubusercontent.com/assets/1051701/24682923/584638ea-19f0-11e7-8c83-2c67e7b1c50f.png)

1.6.x  - I have highlighted content until some of it displays

![screen shot 2017-04-05 at 10 28 24 am](https://cloud.githubusercontent.com/assets/1051701/24682992/a9307be4-19f0-11e7-8dc4-d7c93482720e.png)
[example.zip](https://github.com/electron/electron/files/894767/example.zip)

**Comment by TimNZ** [comment]
Also resizing the window for 1.6.x the DevTools refreshes very slowly resulting in short term layout 'corruption'.  Snappy in 1.4.15

**Comment by tarruda** [comment]
> /cc @tarruda was this what you were seeing yesterday?

Yes, apparently it is a chrome issue related to gpu acceleration and video drivers used in OSX virtual machines. I tested and reproduced in all chrome versions between 53 and 58. I don't know why it only affects electron 1.6.0 which is based on chrome 56, maybe some extra chrome code that causes this issue was added in 1.6.0?

The workaround for this issue is to disable gpu acceleration with `--disable-gpu` or [`app.disableHardwareAcceleration`](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration). Unfortunately that's not a viable option in all situations, especially if your app uses webgl.

I found a few chrome issues that seem related. Even though the rendering bug doesn't seem to be the same, all those bugs are fixed by disabling gpu acceleration.
- https://bugs.chromium.org/p/chromium/issues/detail?id=528349
- https://bugs.chromium.org/p/chromium/issues/detail?id=542873
- https://bugs.chromium.org/p/chromium/issues/detail?id=527556

**Comment by TimNZ** [comment]
Thanks.  

It should be pretty rare for my user base to be running the app in a VM so not a blocker.

**Comment by jessica-pixvana** [comment]
Is there a way to query to see if I'm in a VM so I can conditionally disable acceleration?

**Comment by jarek-foksa** [comment]
This also occurs on older hardware, not just inside virtual machines. I just received a very similar bug report from MacBook Pro 2012 user and `--disable-gpu` flag solved the problem for him.

I think Chrome has a blacklist of untested/unsupported/legacy GPUs which is used to determine whether hardware acceleration should be enabled. Perhaps Electron could use the same approach?
