### ISSUE TITLE
Cannot add height/width parameters to a function that creates a new BrowserWindow

### ISSUE THREAD

**Issue by vKepler** [electron/electron#9135]
* Electron version: 1.6.2
* Operating system: Microsoft Windows 10 Pro

### Expected behavior

I would be able to put height and width parameters in a function called createWindow() that would dictate the size of a new BrowserWindow. For example:
`function createWindow(height, width) {
  win = new BrowserWindow({height, width, icon: __dirname + '/img/ha-logo.png'});
}
`
And I would be able to call it later like so..
`
app.on('ready', createWindow(600, 800));
`

And he app would run just fine.
### Actual behavior
I get an error saying "Uncaught Exception: Error: Cannot create BrowserWindow before app is ready"

### How to reproduce

Create a main.js file and create a function called createWindow with the parameters height and width. Inside the function, instantiate a new instance of BrowserWindow calling the objects height and width that you passed as parameters.

Call the function inside of the `app.on()` function when the app has entered the ready state..

Final code..

`let win;

function createWindow(height, width) {
  win = new BrowserWindow({height, width, icon: __dirname + '/img/ha-logo.png'});
  win.focus();
}

app.on('ready', createWindow(600, 800));`

**Comment by MarshallOfSound** [comment]
You aren't adding createWindow as an event listener.  You are calling it immediately and adding it's return value as an event listener.  It needs to be like this instead.

```js
app.on('ready', () => createWindow(600, 800))
```

**Comment by vKepler** [comment]
@MarshallOfSound callbacks aren't event listeners but ok bro

**Comment by MarshallOfSound** [comment]
@vKepler Sorry if I didn't explain clear enough.

The `app` object is an [`EventEmitter`](https://nodejs.org/api/events.html), this means that calling `.on` adds an event listener.  See [`emitter.on`](https://nodejs.org/api/events.html#events_emitter_on_eventname_listener).  The syntax for that function is

```js
emitter.on(eventName, listenerFunction)
```

Where `listenerFunction` is a function, in your code you provide the event name correctly, but instead of providing a function you provide the **result** of the function (in this case your function returns `undefined`.

In order to fix this you simply make an anonymous function as I described so that the event listener is a function and not undefined

```js
app.on('ready', () => createWindow(600, 800))
```

**Comment by vKepler** [comment]
@MarshallOfSound Sorry for my response, I probably should have researched more before opening an issue on Git.. That makes sense. To be so honest I wasn't even sure where .on() was coming from or what the API was doing there. I refactored my code with these changes and it works, Thanks bro.
