### ISSUE TITLE
Uncaught TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by blksheep93** [electron/electron#9152]
Sorry if this a basic question ubt I've been working it for a a couple days and can't figure it out. All online solutions I found pointed to a versioning problem, so I updated everything and it still persists. Would love to be able to make http calls to carry out login auth.

Electron v1.6.2
Node v6.10.2
npm v4.4.4

**What I've done:**

- npm cache clean
- Moved electron to global and deleted all node_managers in folders levels up from app.
- Updated electron ,node, and npm
- Required current version of electron in dev dependancies/

**main.js file**
```

const electron = **require('electron')**
// Module to control application life.
const app = **electron.app**
// Module to create native browser window.
const BrowserWindow = **electron.BrowserWindow**
```

**Offending code**

```
function login(){
var username = document.getElementById('username').value;
var password = document.getElementById('password').value;
//Dubtel_ajax(link', 'login_response', 'login_response');
var test = httpGet('link');
console.log(test);

var form_string = null;
form_string= "/username="+ username + "&password=" + password;

const {net} = require('electron');
const request = electron.net.request({
	method: 'GET',
	protocol: 'http:',
	hostname: 'link',
	path: form_string
});
console.log("request: " + request);

request.on('response', (response) => {
 console.log(`STATUS: ${response.statusCode}`);
  response.on('error', (error) => {
    console.log(`ERROR: ${JSON.stringify(error)}`)
  })
});

request.on('login', (authInfo, callback) =>{
	//callback('username', 'password')
});

request.end();
};
```

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

It would appear the offending code is running in the renderer process (since it accesses the DOM), there is no `net` module in the renderer process, it's only available in the main process. In the renderer process you should use standard HTML5 APIs to fetch remote resources.
