### ISSUE TITLE
on xp can not run

### ISSUE THREAD

**Issue by fov42550564** [electron/electron#917]
![Uploading image.png . . .]()

**Comment by quentindemetz** [comment]
Hi,

As I can't comment on #691 (locked) and I am interested in this issue, could you point me in a couple directions to see what would be needed to get this to work on XP ? I would imagine using a Chromium build from earlier this year should fix part of the issues you mentioned in #691. 

@thomasjo @paulcbetts I'm not asking for an implementation, I would like to estimate what amount of work is required to get electron working on XP. I have a real business need to build a desktop application compatible with Windows XP (50+% of my 1000+ customers are on XP), and it sounds like it might be worth the effort for me to try to fork and backport electron to XP, rather than implement all the electron features myself before building my application. 

Thanks for your help and congrats on building such an awesome framework !

**Comment by tonny-zhang** [comment]
@quentindemetz is there a way to run electron on xp?

**Comment by tonny-zhang** [comment]
@quentindemetz I have the same trouble, and 60+% of my customers are on XP.

 Thanks for your help

**Comment by lashanchenqi** [comment]
So sad about not support for Windows XP. So Electron is invalid in china as most of chinese (60 percent or more) are still using XP.
