### ISSUE TITLE
nodeintegration causes some scripts to not load

### ISSUE THREAD

**Issue by dok** [electron/electron#9200]
* Electron version: 1.6.2
* Operating system: MacOS El Capitan 10.11.5

### Issue Description
Adding the attribute "nodeintegration" to a webview tag causes some script tags in the guest page to not load. However, the script tags are retrieved successfully, they are just not being run.

### Expected behavior
Expect adding the "nodeintegration" to a webview tag shouldn't cause some scripts to not run. I would expect the attribute to not affect how a webview treats javascript files that are requested by the guest page. It seems more like a side-affect issue.

### Actual behavior

Actual behavior causes some applications in the webview to fail since it does not have the necessary dependencies that it is expecting. If I remove the "nodeintegration" tag, the guest page behaves normally and runs the scripts.

#### I'm able to reproduce this behavior by cloning a fresh copy of a [boilerplate](https://github.com/szwacz/electron-boilerplate.git) app and then adding a webview add with the "nodeintegration" attribute added into it.

Here is the snippet from [app.html](https://github.com/szwacz/electron-boilerplate/blob/master/app/app.html#L10):

<img width="1128" alt="screen shot 2017-04-15 at 7 11 38 pm 1" src="https://cloud.githubusercontent.com/assets/1214868/25063175/f938f112-220f-11e7-9692-e6f1fd872dd9.png">

Here is the guest page's dev tools view:

<img width="602" alt="screen shot 2017-04-15 at 7 14 59 pm" src="https://cloud.githubusercontent.com/assets/1214868/25063179/00b83fc4-2210-11e7-9c87-2047132ec605.png">

**Comment by MarshallOfSound** [comment]
First off, this is entirely expected behavior.  By enabling `nodeIntegration` you are injecting globals into this page including `module` and `require`.  Lot's of libraries, most notably jQuery use these globals to determine whether to inject itself into `window.$` or to export on `module.exports`.  This means that with `nodeIntegration` enabled these loaders act differently and to use jQuery you need to do `window.$ = require('jquery')`.

But really you shouldn't be doing this, enabled `nodeIntegration` while loading a remote site in a webview is a **really** unsafe thing to do, you're giving uncontrolled remote code complete un-restricted access to your users machine.  PLEASE don't do this 👍

**Comment by MarshallOfSound** [comment]
This is a good read 👍 
https://github.com/electron/electron/blob/master/docs/tutorial/security.md

**Comment by dok** [comment]
@MarshallOfSound thanks for the clarification
