### ISSUE TITLE
No setting referrer when clicking on an anchor with target='_blank'

### ISSUE THREAD

**Issue by eyyubovkamran** [electron/electron#9205]
* Electron version: 1.6.2
* Operating system: Windows 7

### Expected behavior

Click on a link with `target=_blank` attribute should open a new browser window and open the clicked url with referrer header set to the original window's url.

### Actual behavior

No referrer header is sent with request on created browser window

### How to reproduce
Put this in any public or local domain
index.php
```
  <a href='/' target='_blank'>Link</a>
  <pre><?php print_r(getallheaders()); ?></pre>

```

**Comment by zcbenz** [comment]
For security purpose referrer is hidden when it is from a `file://` URL, this is the behavior used by all browsers.

**Comment by deepak1556** [comment]
@zcbenz the issue is not specific to file protocol, this will happen only for new windows opened without sandbox or nativeWindowOpen option, as we don't pass the referrer information from [AtomBrowserClient::CanCreateWindow](https://github.com/electron/electron/blob/master/atom/browser/atom_browser_client.cc#L340) to our `guest_window_manager`. The fix is really simple, didn't get to it as I was working on other tasks. Can we reopen the issue ? Thanks!
