### ISSUE TITLE
session deleted because of page crashfrom tab crashed 

### ISSUE THREAD

**Issue by rameshrc** [electron/electron#9369]
Issue Description:
Electron Client sometimes crashes when launched.
We use C# selenium codebasev2.53.0, Chromium.ChromeDriver version="2.29", Electron 1.4.15, 

Let's say Out of 100 test, 5 test fail due to this error. Its random in nature.

Assert.Fail failed. unknown error: session deleted because of page crashfrom tab crashed  (Session info: content shell=)  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.10586 x86_64)   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)   at OpenQA.Selenium.Remote.RemoteWebDriver.get_Title()

Windows 10
.NET 4.6.2

**Comment by rameshrc** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1795#c2

**Comment by zcbenz** [comment]
Can you get the stack trace when crash happens?

**Comment by rameshrc** [comment]
Could you tell me how to get a stack trace/ logs from electron client?

**Comment by Sandeep-5791** [comment]
Hi I face the same issue this is the stack trace of my program.
I am using electron to give a desktop look and feel to my web application which runs on chrome.
Using selenium I am able to launch my application only intermittently most of the time my tests fails with the following msg: 

unknown error: session deleted because of page crash
from tab crashed
  (Session info: content shell=)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 29 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'PC-S30BUILD', ip: '172.24.9.93', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_111'
Driver info: com.pilz.ie.s30.automation.driver.S30WebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41), userDataDir=C:\Users\BC5A0~1.TES\AppData\Local\Temp\scoped_dir3464_16219}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 9b483a84aa9e67f97a859c465d7c80cb
*** Element info: {Using=id, value=pilzheaderimage}
Stacktrace

java.lang.AssertionError: 
unknown error: session deleted because of page crash
from tab crashed
  (Session info: content shell=)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 29 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'PC-S30BUILD', ip: '172.24.9.93', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_111'
Driver info: com.pilz.ie.s30.automation.driver.S30WebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41), userDataDir=C:\Users\BC5A0~1.TES\AppData\Local\Temp\scoped_dir3464_16219}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 9b483a84aa9e67f97a859c465d7c80cb
*** Element info: {Using=id, value=pilzheaderimage}

**Comment by Sandeep-5791** [comment]
For our Java-based Selenium test we used this trial & error technique in a common setup method.We normally close the Driver in a common @AfterClass method.  Hope it may help:
  

  
   @Before
   public void setup()
   {
      boolean isDriverReady = false;
      int trials = 1;
      while (!isDriverReady && trials <= MAX_NUMBER_OF_TRIALS)
      {
         logger.info("setup: Trial number " + trials);
         try
         {
            // Driver initialization entry point
           // If Driver has been initialized returns it, otherwise initialize it
            WebDriver driver = getDriver();
            // test the driver is working fine by waiting for an element in the page
            waitForElementById(driver, [...]);
            isDriverReady = true;
            logger.info("setup successful at trial number " + trials);

         }
         catch (WebDriverException e)
         {
            trials ++;
            logger.error("setup: Failed to initialize the driver " + e, e);
              // close the driver
            S30WebDriver.closeDriver();
            // give a bit of sleep for the driver to recover
            sleep();
         }
         catch (Exception e)
         {
            logger.error("setup: Generic Error " + e, e);
            fail("setup: Generic Error " + e);

         }
      }
      if (!isDriverReady) {
         fail ("setup: Can' initialize the driver after " + MAX_NUMBER_OF_TRIALS + " trials");
      }

   }

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by achingbrain** [comment]
I see the same thing intermittently on Windows.

Electron 1.7.5
Selenium-Webdriver: 3.6.0

Stack trace:

```
Backtrace:
        uv_async_init [0x00007FF97CE51F85+37]
        node::inspector::Agent::Agent [0x00007FF97C375F9C+396]
        node::inspector::Agent::Agent [0x00007FF97C375E4B+59]
        v8::ArrayBuffer::Allocator::Allocator [0x00007FF97C31E1E9+297]
        node::CreateEnvironment [0x00007FF97C327AB1+125]
        (No symbol) [0x00007FF75E434FD5]
        (No symbol) [0x00007FF75E3DEE77]
        (No symbol) [0x00007FF75E4B3697]
        GetHandleVerifier [0x00007FF75E918B2A+2788154]
        IsSandboxedProcess [0x00007FF7604B4E2D+28257717]
        IsSandboxedProcess [0x00007FF760848692+32007706]
        IsSandboxedProcess [0x00007FF7604B0AFB+28240515]
        IsSandboxedProcess [0x00007FF7605197CA+28669778]
        IsSandboxedProcess [0x00007FF760519CFC+28671108]
        IsSandboxedProcess [0x00007FF76051961A+28669346]
        IsSandboxedProcess [0x00007FF76051ADCE+28675414]
        IsSandboxedProcess [0x00007FF7605198AE+28670006]
        IsSandboxedProcess [0x00007FF76091E5EA+32884082]
        IsSandboxedProcess [0x00007FF75EBD374D+2168533]
        IsSandboxedProcess [0x00007FF75EBD37EB+2168691]
        IsSandboxedProcess [0x00007FF75EF33882+5707786]
        IsSandboxedProcess [0x00007FF75EF313BD+5698373]
        IsSandboxedProcess [0x00007FF75EF32E54+5705180]
        IsSandboxedProcess [0x00007FF75EF335DC+5707108]
        IsSandboxedProcess [0x00007FF75EF3634D+5718741]
        IsSandboxedProcess [0x00007FF75EF35C32+5716922]
        GetHandleVerifier [0x00007FF75E7147FD+673805]
        IsSandboxedProcess [0x00007FF760C5E351+36291289]
        IsSandboxedProcess [0x00007FF760C5D1CB+36286803]
        IsSandboxedProcess [0x00007FF760C5AC4D+36277205]
        (No symbol) [0x00007FF75E48B863]
        GetHandleVerifier [0x00007FF75E7147FD+673805]
        GetHandleVerifier [0x00007FF75E6B59A6+285110]
        GetHandleVerifier [0x00007FF75E6B427A+279178]
        GetHandleVerifier [0x00007FF75E7166EE+681726]
        GetHandleVerifier [0x00007FF75E6B19FE+268814]
        IsSandboxedProcess [0x00007FF75ED580EF+3760247]
        GetHandleVerifier [0x00007FF75E9C0FED+3477501]
        GetHandleVerifier [0x00007FF75E9C0EE4+3477236]
        GetHandleVerifier [0x00007FF75E7697BC+1021900]
        (No symbol) [0x00007FF75E3C7E5B]
        IsSandboxedProcess [0x00007FF76163A87B+46630915]
        BaseThreadInitThunk [0x00007FF9ADC78364+20]
        RtlUserThreadStart [0x00007FF9AFA970D1+33]
WebDriverError: unknown error: session deleted because of page crash from tab crashed
  (Session info: content shell=)
  (Driver info: chromedriver=2.27 (44a803957cb27610c38f7e859016ac257959aeb5),platform=Windows NT 10.0.14393 x86_64)
```
