### ISSUE TITLE
Default Location of Crash Reporter Log Files

### ISSUE THREAD

**Issue by VikasShashidhar** [electron/electron#9407]
Was trying to check what the default location on Mac and Windows where the Electron Crash Reporter log files are stored before they are uploaded to the server.

Can anyone please help?

**Comment by kevinsawicki** [comment]
They should be in the temp directory.

Something like:

```js
path.join(app.getPath('temp'), app.getName() + ' Crashes')
```

The `productName` specified to the crash reporter will be used instead of `app.getName()` if present.

You can see the code at https://github.com/electron/electron/blob/e708a45496b9a9621e6c1f16aa039f700a2aba14/lib/common/api/crash-reporter.js#L81-L84

**Comment by VishwasShashidhar** [comment]
@kevinsawicki I was going through the docs for setting a custom crash directory, as per the docs, looks like it is supported. However, the code doesn't seem to support it.

I'm using electron 1.7.5, is this support something new and post 1.7.5?

**Comment by jasonxia23** [comment]
@VishwasShashidhar According to the document:

> `crashesDirectory` String (optional) - Directory to store the crashreports temporarily (only used when the crash reporter is started via `process.crashReporter.start`).
