### ISSUE TITLE
Zoom issue between 1.4.x and 1.6.x

### ISSUE THREAD

**Issue by samvloeberghs** [electron/electron#9417]
* Electron version: 1.4.14 and 1.6.6
* Operating system: Windows

### Expected behavior
It should have the same size in window etc

### Actual behavior
When I upgraded from 1.4.14 to 1.6.6 I saw that the window has zoomed up ( zoom: 0.8 on the body fixes it ). Is there any known issue related to this? Or is it expected behavior in some way?

**Comment by sedwards2009** [comment]
I also noticed a difference here, but I don't think it is zooming of the whole interface. It just looks like the conversion from pt to px is now being done slightly differently such that all fonts render a bit bigger than before.

I saw this on Linux too.

**Comment by KagamiChan** [comment]
I guess you're using windows 10 and have a system hiDPI scale setting of 125%, is that right? On windows, this is due to upstream Chrome's behaviour change, it now "respects" the system-wide HiDPI settings.

I can think out 2 solutions:
- disable this behaviour by setting chrome flags, use some code like this in your `app.js`:
```
if (process.platform === 'win32') {
  app.commandLine.appendSwitch('high-dpi-support', 'true')
  app.commandLine.appendSwitch('force-device-scale-factor', '1')
}
```

- adapt your app with this new change, e.g. setting your browser's own scale, make your app content more responsive.

p.s. I don't know exactly if the same happens on Linux, if so, the above code should also work (and don't forget to change the platform check)

**Comment by samvloeberghs** [comment]
will try this approach.. It requires me some time to check :) thanks!

**Comment by samvloeberghs** [comment]
@KagamiChan it seems to resolve it, thanks!
