### ISSUE TITLE
How to wait to complete asynchronous functions during Windows shutdown?

### ISSUE THREAD

**Issue by akihitofujiwara** [electron/electron#9433]
* Electron version: 1.6.8
* Operating system: Windows

### Expected behavior
I want to wait to complete processing asynchronous functions during Windows shutdown.

### Actual behavior
I tried prevent Windows shutdown until all asynchronous funcitions completed.
But, the followings don't work.
`app.on('will-quit', event => event.preventDefault())`
`app.on('before-quit', event => event.preventDefault())`

I would appreciate if you could answer it.
Please feel free to ask me if you have any questions.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW `before-quit` is the event you are looking for, just be sure you don't `preventDefault` all the time, otherwise the app will never quit.

**Comment by akihitofujiwara** [comment]
@MarshallOfSound 
Thank you for your support.
I got it.

**Comment by trickpattyFH20** [comment]
@akihitofujiwara how did you achieve this? I'm looking to do the same thing

**Comment by brenthompson** [comment]
@MarshallOfSound the docs for `before-quit` say "Note: On Windows, this event will not be emitted if the app is closed due to a shutdown/restart of the system or a user logout"...?

**Comment by nuryagdym** [comment]
on electron v0.2.4 I needed to send http request to backend right before app closes. 
When I tried 'before-quit', request started, but because it aborts (I am just guessing) http requests, the backend side also behaves like it did not receive this request.
Also, tried 'window-all-closed`  but it did not run at all.

**Comment by bugii** [comment]
@nuryagdym I just had the same problem and figured I would share my solution with you.

```
let asyncOperationDone = false;

app.on("before-quit", async (e) => {
  if (!asyncOperationDone) {
    e.preventDefault();
    await asyncOperation();
    asyncOperationDone = true;
    console.log("async operation done, quitting");
    app.quit();
  }
});
```

This way the first time "before-quit" is called, the app will not quit because the async operation has not yet finished. As soon as it finished, we change the global flag and manually call quit() again. This time we don't enter the if loop and thus do not prevent quitting the app.

**Comment by KatoakDR** [comment]
Thanks @bugii for [your solution](https://github.com/electron/electron/issues/9433#issuecomment-960635576)! I totally didn't think about the `e.preventDefault()` method 😄 

In my typescript project, I used a 3-state enum so that I didn't kick off my before quit operations more than once, which could happen if another quit request came in while my async actions were running.

```ts
/**
 * Trick to await async operations before quitting.
 * https://github.com/electron/electron/issues/9433#issuecomment-960635576
 */
enum BeforeQuitActionStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

let beforeQuitActionStatus = BeforeQuitActionStatus.NOT_STARTED;

app.on('before-quit', (event: Event): void => {
  switch (beforeQuitActionStatus) {
    case BeforeQuitActionStatus.NOT_STARTED:
      // don't quit yet, start our async before-quit operations instead
      event.preventDefault();
      beforeQuitActionStatus = BeforeQuitActionStatus.IN_PROGRESS;
      await yourAsyncBeforeQuitOperations();
      beforeQuitActionStatus = BeforeQuitActionStatus.COMPLETED;
      app.quit();
      break;
    case BeforeQuitActionStatus.IN_PROGRESS:
      // don't quit yet, we are still awaiting our before-quit operations
      event.preventDefault();
      break;
    case BeforeQuitActionStatus.COMPLETED:
      // no further action needed, continue to quit the app like normal
      break;
  }
});
```

**Comment by Cholicer** [comment]
wth the docs for before-quit say "Note: On Windows, this event will not be emitted if the app is closed due to a shutdown/restart of the system or a user logout"...?
