### ISSUE TITLE
menu.popup() should accept a callback when running async

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9441]
This is a feature request to make `menu.popup()` accept a `callback` to solve two issues:
* makes it clear that the menu is opening `async` (as opposed to having this as a `async: true` option)
* calls into the `callback` when the menu is closed (either by picking an item or by not picking an item, e.g. pressing ESC).

/cc @kevinsawicki

**Comment by sindresorhus** [comment]
Changing the behavior when specifying a callback would be more surprising than an explicit `async` option. I also think the better way forward would be to return a promise so it works with async/await.

**Comment by bpasero** [comment]
@sindresorhus I disagree, we have the same in other API like [`dialog.showMessageBox`](https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options-callback)

**Comment by sindresorhus** [comment]
That doesn't mean it's a good API practice. Say you supply the callback based on user input. Then it will result in different behavior if the user accidentally passes in `undefined` instead of a function. Better to be explicit about it.

If there were no backwards-compatibility concerns, IMHO the correct way to solve this would be to have two functions:

- `menu.popup()`, which is asynchronous and returns a promise.
- `menu.popupSync()`, which is synchronous.

This is how all the APIs in Node.js and the community works.

Could always go the other way though and add `menu.popupAsync()`, which would be a backwards-compatible.

**Comment by bpasero** [comment]
I like how node.js does it. I do not like to have inconsistent APIs. Either way the solution imho should be consistent.

**Comment by tonyganch** [comment]
I think that returning a promise is a cleaner solution that will be also more obvious to new developers.
If that's not possible (for example, because of backwards compatibility), i would vote for a callback, because having a consistent API within a project in my opinion is more important than doing it "right".

**Comment by bsclifton** [comment]
This would be a great one- particularly for being able to call destroy after it finishes

**Comment by UziTech** [comment]
@tonyganch I agree as long as it is in the works to do it "right" (i.e. change everything to promises in v2)

![image](https://cloud.githubusercontent.com/assets/97994/26433197/c9ceb97c-40c6-11e7-86c3-398d298cbacb.png)

**Comment by codebytere** [comment]
This has been merged, so i'll go ahead and close it!

**Comment by alexeykuzmin** [comment]
@codebytere 
It's a feature request ) nothing has been done here. Reopend.

**Comment by codebytere** [comment]
@alexeykuzmin my bad, i thought i saw a PR that completed it. thanks for reopening!
