### ISSUE TITLE
Any way to make a BrowserWindow fully unminimizable?

### ISSUE THREAD

**Issue by krosscode** [electron/electron#9451]
### Specs

* Electron version: 1.6.7
* Operating system: Windows 10

### The Problem

I have a BrowserWindow which is the size of the users primary monitor, and is basically supposed to be a replacement desktop. My problem is this:

When the user presses the Windows 7-10 peek button, the app is hidden ( I have it set to minimizable: false, but it doesn't count as minimizing )

### Problematic "Fix"

The only "fix" I have found, is to make the BrowserWindow always on top, which I do not want, as it's supposed to be a desktop replacement.

I know of type: desktop, but that is for Linux and OS X.

Thanks, in advance :)

### <3

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
