### ISSUE TITLE
Confusion about the recent release number

### ISSUE THREAD

**Issue by hackjutsu** [electron/electron#9479]
Why the latest release number is `v1.3.15` while we have `v1.6.x` released before?

**Comment by kevinsawicki** [comment]
@hackjutsu the latest stable release is 1.6.7. The 1.6.8, 1.6.9 and 1.7.0 releases are in beta.

The https://github.com/electron/electron/releases page lists releases by date, there isn't a way to control the sorting, it is based off the git tag timestamp.

We still backport certain fixes to old release branches like 1.3.x and 1.4.x, 1.3.15 was a backported bug fix for the Atom team since they still run on the 1.3.x line. 1.3.15 came out after 1.6.7 was initially released so that is why is it showing as the "latest release" on the GitHub releases page.

https://electron.atom.io/releases/ will show the correct order, apologies for any confusion.

**Comment by hackjutsu** [comment]
@kevinsawicki Thank you for explanation:)
