### ISSUE TITLE
A way to cancel app.relaunch

### ISSUE THREAD

**Issue by cberescu** [electron/electron#9542]
* Electron version: 1.6.2
* Operating system:Win 10

### Expected behavior
After calling app.relaunch a way to cancel it.

### Actual behavior

After calling app.relaunch there is no way to cancel it. Or i didn't find anything in the documentation.

**Comment by MarshallOfSound** [comment]
@cberescu `app.relaunch` is an instantaneous (or basically instantaneous action).  At what point do you what to prevent it?

**Comment by cberescu** [comment]
well, i wanted to use it if electron crashes . From what i saw i am not required to exit the main app after using app.relaunch. It just stays waiting for the main app to exit. In case it is a normal exit i would like to be able to disable the relaunch.

**Comment by cberescu** [comment]
@MarshallOfSound do you need any extra info ?

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by camhart** [comment]
I could use this as well.  I want my application to recover under certain circumstances.  I'm finding I can't rely on events like  `app.on('quit'...` because they aren't always called depending on how the application is closed (or killed).  However under other circumstances I do want it to die and actually stay dead :D.
