### ISSUE TITLE
Semi-transparent window

### ISSUE THREAD

**Issue by GeorgeBgk** [electron/electron#9574]
* Electron version: Node.js 7.4.0, Chromium 56.0.2924.87, and Electron 1.6.8.
* Operating system: macOS 10.12.5

There is a beautiful effect of semi-transparency and background blur in macOS

![screen shot 2017-05-24 at 11 00 15](https://cloud.githubusercontent.com/assets/11464592/26392709/349679a4-4070-11e7-86f3-dc056b9ea50e.png)

Is there any API/Workaround/Library that can apply such effect to Electron windows and control it using CSS?

**Comment by ahallicks** [comment]
If you have your Window set to `transparent: true` you can then control the transparency in CSS by setting the background colour of the HTML to something with transparency. I use this.

The blur effect is not quite so easy, but I'm wondering if you could use a pseudo-element on the HTML tag with a blur filter and sit it under the Window. Something like:
https://tympanus.net/Development/ModalWindowEffects/

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
