### ISSUE TITLE
Downloading file - file extension is missing

### ISSUE THREAD

**Issue by JanBN** [electron/electron#9593]
Hi,

I have a problem with saving files from web using electron. They don't have file extension (like *.pdf, *.xls). I run electron as chrome client with **node integration set to false**. 

* Electron version: 1.6.10
* Operating system: Windows 10

### Expected behavior
When I click on a file, the save file dialog should be prompt also with file extension (e.g sample.pdf)

### Actual behavior
When I click on a file, the save file dialog has no filled extension only filename (e.g sample)

### How to reproduce
This is the repo with reproduced bug: https://github.com/JanBN/electron-quick-start (forked from electron quick start)
```
  $ git clone https://github.com/JanBN/electron-quick-start.git
  $ npm install
  $ npm start || electron .
```

this is main.js file. It only loads url: http://www.pdfpdf.com/samples.html
```
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
const path = require('path');
const url = require('url');
const fs = require('fs');

const Menu = electron.Menu;
const MenuItem = electron.MenuItem;

let mainWindow;



function createWindow() {
  mainWindow = new BrowserWindow(
    {
      width: 800,
      height: 600,
      webPreferences: {
        nodeIntegration: false,
        nativeWindowOpen: true,
      },
    });

  mainWindow.loadURL("http://www.pdfpdf.com/samples.html");
  mainWindow.setMenu(null);
  mainWindow.on('closed', function () {
    mainWindow = null
  });
}

app.on('ready', createWindow);
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow();
  }
});
```

**Comment by Dhaval8087** [comment]
You need to use the will-download method for the issue like 

mainWindow.webContents.session.on('will-download', (event, downloadItem, webContents) => {

    var fileName = dialog.showSaveDialog({
      defaultPath: defaultFileName,
      filters: [
        { name: 'Excel', extensions: ['pdf'] }]
    });

    if (typeof fileName == "undefined") {
      downloadItem.cancel()
    }
    else {
      downloadItem.setSavePath(fileName);
    }
  });

**Comment by JanBN** [comment]
Awesome.
Thank you very much ;)

**Comment by theuniverse** [comment]
This discussion can be merged into #10121.

**Comment by mattridley** [comment]
Just bringing this back to the surface - this isn't fixed in Windows 10 in 1.7.10 or 1.8.2-beta3. It has the same issue as #10121 (in so much that it displays an extension if you have "Show extensions for known file types" enabled in the explorer options) but wasn't resolved by the fix for macOS.

**Comment by BONDbATIF** [comment]
@mattridley 
I am also facing problem in mac .Is this resolved ?

**Comment by BONDbATIF** [comment]
@Dhaval8087 @JanBN 
Hi Dhaval ,
I gone through you solution .Currently I am working with Angular 4 .I am using 'ngx-electron' servic to send request to index.js file (electron where my mainWindow object resides). And trying to get mainWindow object in angular component using ipc render 
 **let mainWindowRef=this._electronService.ipcRenderer.sendSync('mainWindowRef');**
but after getting response , it is throwing error " Converting circular structure to JSON
" .
https://stackoverflow.com/questions/4816099/chrome-sendrequest-error-typeerror-converting-circular-structure-to-json
I want to open my file dialog form Angular 4 .
![dom_circular](https://user-images.githubusercontent.com/5045450/41201780-14c979ac-6cdc-11e8-9d1c-a91cf1c04aee.JPG)

Is any way to achieve in Angular instead of index.js ?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
