### ISSUE TITLE
Sandbox option doesn't work on webview

### ISSUE THREAD

**Issue by juturu** [electron/electron#9611]
* Electron version: 1.7.1
* Operating system: Windows

### Expected behavior
Able to enable sandbox on webview

### Actual behavior
Sandbox option doesn't work on webview

### How to reproduce

Create webview with sandbox option set to true 
<webview src="https://www.google.com" webpreferences="sandbox=yes, nodeIntegration=no"/>

webview process will not have sandbox enabled. 

See the command line options set on the webview process

electron.exe" --type=renderer **--no-sandbox** --primordial-pipe-token=19883710511F93F2300EF53454123946 --lang=en-US --app-path="c:\Repos\electron-quick-start" **--node-integration=false --enable-sandbox** --guest-instance-id=1 --enable-blink-features 

I think we should unset --no-sandbox in the if statement @ [IsSandboxed
](https://github.com/electron/electron/blob/8ae36c250c456b7a334c00109ec9f5f01beab0a4/atom/browser/web_contents_preferences.cc#L114).

@tarruda @kevinsawicki if you guys think this suggestion makes sense, i can send out a PR for the fix.

Repros
  $ git clone https://github.com/juturu/electron-quick-start.git -b webview-sandbox
  $ npm install
  $ npm start || electron .

**Comment by tarruda** [comment]
I have a branch where webview/sandbox integration is working, but to get `window.open` working inside sandbox I had to use some chromium internal API, which is why I haven't sent a PR yet.

Feel free to play with it, and if you come up with a better solution, please send a PR: https://github.com/tarruda/electron/tree/enable-webview-on-sandbox.

**Comment by juturu** [comment]
In my scenario BrowerWindow doesn't have sandbox option set. Can we at least make web view open in sandbox without window.open working? This at least will make some scenarios working.

**Comment by juturu** [comment]
Essentially can we push your commit @ https://github.com/tarruda/electron/commit/5bedc0c1f84eb4a64e5a860dc78d53635ec7f2bc to get this issue resolved?

**Comment by tarruda** [comment]
> In my scenario BrowerWindow doesn't have sandbox option set. Can we at least make web view open in sandbox without window.open working? This at least will make some scenarios working.

I hope to eventually get it fully working, but maybe @kevinsawicki and @zcbenz are ok with a partial implementation.

> Essentially can we push your commit @ tarruda/electron@5bedc0c to get this issue resolved?

If only enabling sandbox on webview without the window.open patch, you also would need to replace the `window.open` API with a stub or it could crash electron.

**Comment by juturu** [comment]
> Essentially can we push your commit @ tarruda/electron@5bedc0c to get this issue resolved?

This change is not enabling the sandbox on the webview as --no-sandbox is not removed. Am i missing anything?

**Comment by bpasero** [comment]
Would be interested in having a way of enabling sandbox only for webview within the application, but without having to add any command line arguments to the application on startup and without enabling sandbox for any other renderer 👍

**Comment by juturu** [comment]
@kevinsawicki @zcbenz what do you guys think on the proposal above? And removing --no-sandbox on webview to get the webview sandbox working.

**Comment by kevinsawicki** [comment]
> And removing --no-sandbox on webview to get the webview sandbox working.

Removing this flag when the sandbox is enabled sounds fine to me 👍

**Comment by tarruda** [comment]
> Would be interested in having a way of enabling sandbox only for webview within the application (even limited without window.open functionality), but without having to add any command line arguments to the application on startup and without enabling sandbox for any other renderer

AFAIK this is not possible. Chromium sandbox is either enabled for all processes or for none. The `sandbox` option implemented in electron(and in my patch for webview) is simply telling electron to disable node.js on renderer process, but the OS-level sandbox can only be enabled at startup.

> This change is not enabling the sandbox on the webview as --no-sandbox is not removed. Am i missing anything?

It enables the `sandbox` attribute for webview, eg: `<webview sandbox=true>`. When this attribute is passed, the webview renderer will have `--no-sandbox` removed.

**Comment by bpasero** [comment]
That is sad to hear (the fact that true sandboxing can only be enabled for all processes).

(I posted this to chat but we should maybe keep the discussion here):

I find it very confusing that you need to run `electron --enable-sandbox` to enable true sandboxing but if you forget to pass this argument you can still create windows with `sandbox: true` and the behaviour is almost the same (though probably fundamentally different in terms of security). 

If we cannot avoid having to use `--enable-sandbox` then I think creating a window with `sandbox: true` should cause an error. 

Ideally though we would never even have to pass in `--enable-sandbox`. imho it is quite fragile to rely on this argument to be passed to the application to enable security

Once webviews can use sandboxing I would think that by default webviews will run with `sandbox: true` and you do not need to pass in `--enable-sandbox`. today we already set `nodeIntegration: false` by default for webviews and this just works independent from any command line flags.

**Comment by tarruda** [comment]
> I find it very confusing that you need to run electron --enable-sandbox to enable true sandboxing but if you forget to pass this argument you can still create windows with sandbox: true and the behaviour is almost the same (though probably fundamentally different in terms of security).

Unfortunately, this is a limitation of chromium sandbox. I think to make sandbox compatible across all platforms, it needs to be enabled for all processes.

> If we cannot avoid having to use --enable-sandbox then I think creating a window with sandbox: true should cause an error.

Think about `sandbox: true` as a way to start a renderer that is compatible with chromium sandbox. Electron default renderer is not compatible because it starts a true node.js runtime which requires network/filesystem access. The way chromium sandbox is designed is that all renderers should delegate system access through the main process, so `sandbox: true` tells electron to completely disable node.js(not just `nodeIntegration`) and delegate everything to the main process.

Note that `nodeIntegration: false` is not the same as `sandbox: true`. Even with `nodeIntegration: false` you still have node.js enabled for preload environment, so any `require()` calls will use the filesystem to load modules during startup.

With `sandbox: true`, the startup modules are actually bundled into the executable with browserify, and the stub `require` function is exposed to the user's preload so it can use some of electron's builtin modules. In the end it is possible to have an environment very similar to what non-sandboxed renderers have since browserify does very good node.js emulation.

Also, even with OS-level sandbox disabled, `sandbox: true` is still required to allow debugging via crash dumps(remember, no filesystem access means the renderer can't write minidump to disk).

> Ideally though we would never even have to pass in --enable-sandbox. imho it is quite fragile to rely on this argument to be passed to the application to enable security

It is unfortunate but necessary for now. The problem is that the code which enables/disables sandbox is executed before electron initial javascript, so we can't simply use `app.commandLine.appendSwitch` to add this switch. Maybe it is possible to implement a workaround similar to `app.disableHardwareAcceleration()`(ref: https://github.com/electron/electron/issues/5297#issuecomment-214950253) but I haven't investigated much.

Note that by default sandbox is enabled for chromium, but since electron can't use it, we need to have an explicit opt-in argument.

> Once webviews can use sandboxing I would think that by default webviews will run with sandbox: true and you do not need to pass in --enable-sandbox. today we already set nodeIntegration: false by default for webviews and this just works independent from any command line flags.

Even if we could get true OS-level sandboxing enabled for individual webviews, it would still be unwise to run untrusted code in it. The problem is that even though sandboxing would block filesystem/network access from the renderer, electron allows full unfiltered access to the system via IPC. For example, it is possible to load/execute any node.js module via the IPC calls that implement the `remote` module. There's still a lot of work to be done before electron can be considered secure as chromium for running untrusted content.

**Comment by bpasero** [comment]
Thanks for all the clarification 👍 

re IPC: if a webview is sandboxed and node integration is disabled, how can a renderer still use IPC to run malicious code on the non-sandboxed side?

**Comment by tarruda** [comment]
> re IPC: if a webview is sandboxed and node integration is disabled, how can a renderer still use IPC to run malicious code on the non-sandboxed side?

If some malicious code manages to take over the renderer, or just finds a way to send arbitrary IPC messages, it can do anything in electron. Normally(in chrome) this is would not be a big problem since only a specific set of IPC are allowed, so the malicious code would only be able to do what is normally possible through javascript, eg: send network http requests or maybe access IPCs for html 5 filesystem API(which is confined to the current origin)

The problem is that electron uses a very generic IPC message to handle any messages from the renderer. Since the `electron.remote` module is essentially a wrapper around a bunch of messages electron sends to the browser, it would be possible for the malicious code to emulate anything that can be done by `electron.remote` API. (eg: `electron.remote.require('fs').unlinkSync`).

**Comment by bpasero** [comment]
Makes sense, so on top of sandbox we also need a "safe" way of sending IPC from sandbox to host.

**Comment by tarruda** [comment]
Yes, I already considered some options but didn't start any work yet.

One idea is that each webContents would have an ipc filter(callback) to only allow certain messages, so a top-level window would have full access and children would be restricted.

**Comment by bpasero** [comment]
Would it not be better to rename the `sandbox` option in the renderer/webview so that people do not confuse it with the real Chrome sandbox model? As far as I hear, what `sandbox: true` does is to disable node integration in preload scripts, so maybe it should be moved into the `nodeIntegration` option and we then have:
* `on`
* `onInPreload`
* `off`
