### ISSUE TITLE
Is there any reason why we can't use Win32 SendMessage APIs?

### ISSUE THREAD

**Issue by sancarn** [electron/electron#9652]
I find it a bit odd how we can use win.hookWindowMessage(message, callback) and manipulate messages but we can't use Send/Post message to other windows. It is quite common for a process to reply to a received message with some data however with these callbacks I'm not sure that is possible? If not, SendMessage / PostMessage APIs would be very helpful (unless there is a reason for them not to be used)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by sancarn** [comment]
You didn't even read the question... If anything it's a feature request, not a question...?
