### ISSUE TITLE
Lock event on macOS

### ISSUE THREAD

**Issue by antelle** [electron/electron#9653]
Electron supports `session-end` for Windows. It would be great to be able to have the same for macOS, probably for these system events:
- `com.apple.screenIsLocked`
- `com.apple.screensaver.didstart`

**Comment by shubham2892** [comment]
@antelle : You might be able to listen to the system events using:

```
  const {systemPreferences} = require('electron')
  systemPreferences.subscribeNotification('com.apple.screensaver.didstart', () => {
       console.log('Screen Saver Starts')
  })

```

**Comment by antelle** [comment]
@shubham2892 wow that's cool! Both events are working, thanks for the tip!
However, it would be great to have a common lock event for all OS'es, so I'll leave it open.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the foreseeable future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
