### ISSUE TITLE
AtExit hook for native modules

### ISSUE THREAD

**Issue by grigorryev** [electron/electron#9673]
Hi!
I'm trying to perform some uninitialization within my C++ native module in the moment before electron main process is finished.
I tried to use Node AtExit hook, as suggested in Node documentation (https://nodejs.org/api/addons.html#addons_atexit_hooks), but it doesn't work.
Is there any way to do this in electron?

**Comment by miniak** [comment]
@grigorryev are you loading the module into the main process or renderer?

**Comment by asherkin** [comment]
I'm loading into the renderer in my case, seeing the same behaviour.

**Comment by grigorryev** [comment]
Is it possible to load a native module to renderer process? Anyway, I'm loading to main.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by asherkin** [comment]
This is an issue, AtExit not working is a problem that should be addressed or documented to not work.

**Comment by brenca** [comment]
This might be related to #11299

**Comment by vyunikov** [comment]
Is there any progress on this issue? Seems to be a problem with Electron 6.0 as well
