### ISSUE TITLE
OnMouseLeave and OnMouseOut not firing when element is leaved from RIGHT side

### ISSUE THREAD

**Issue by NahroTo** [electron/electron#9676]
OnMouseLeave and OnMouseOut are not firing if the mouse leaves the element from the RIGHT side. Very annoying bug.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
