### ISSUE TITLE
Issue in the documentation of types for DesktopCapturer.getSources() function 

### ISSUE THREAD

**Issue by Nykkolas** [electron/electron#9677]
Hello,

* Electron version: v1.6.10
* Operating system: macOS 10.12.5

I believe that there is an issue in electron-api.json for DesktopCapturer.getSources() function.
In the options arguments, types is declared as String but, according to the documentation, it should be an Array of Strings. 

It causes issues when using it with Hate externs (https://github.com/fponticelli/hxelectron).

Thanks and have a nice day !

**Comment by kevinsawicki** [comment]
It looks correct for the latest release, https://github.com/electron/electron/releases/download/v1.7.2/electron-api.json

It is marked as a `type: 'String'` with `collection: true`. This seems to be how other string arrays are represented in other Electron APIs.

It looks like other `String[]` APIs are also wrong in the `hxelectron` docs, https://github.com/fponticelli/hxelectron/blob/04d908d46be3e64758cbf9ea16bf9465b4b3ec1c/src/electron/Clipboard.hx#L45

Closing this out since this seems like an `hxelectron` issue that should be reported there since it looks like it isn't parsing the `electron-api.json` file correctly.
