### ISSUE TITLE
electron width socket.io error

### ISSUE THREAD

**Issue by crylg** [electron/electron#9702]
WebSocket connection to 'ws://120.76.235.149:8000/socket.io/?EIO=3&transport=websocket&sid=RimiajuKN-wN5JrhAAAh' failed: Error during WebSocket handshake: Unexpected response code: 400

client.js

Global.SOCKET = io('http://120.76.235.149:8000');

it is strange that.., 
 1.There is no error in the socket.io intranet server 
2. before the client is packaged by electron-package, there is no error in accessing the extranet 3.http://amritb.github.io/socketio-client-tool/#url=aHR0cDovLzEyMC43Ni4yMzUuMTQ5OjgwMDA=&opt=&events= log->show:6:32:51:332 Connected

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
