### ISSUE TITLE
Support --openssl-config cli argument?

### ISSUE THREAD

**Issue by algv** [electron/electron#9714]
I want use node: --openssl-config cli argument (https://github.com/nodejs/node/commit/1ea0358a91)

How use it from command line for electron?

If build from source, can see wat openssl_config in InitCryptoOnce() always null.

* Electron version: ^1.6.6
* Operating system: Ubuntu 16

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
