### ISSUE TITLE
how to emulate mobile page in electron ？

### ISSUE THREAD

**Issue by ydcoming** [electron/electron#9774]
I want the electron analog phone rendering the page, just like the android simulator.how to emulate mobile page in electron ？ tks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
