### ISSUE TITLE
App doesn't restart on relaunch() call

### ISSUE THREAD

**Issue by lonja** [electron/electron#9787]
* Electron version: 1.3.15
* Operating system: Ubuntu 14.04

The following code only closes the app but not starts it again.
```
var app = require('electron').remote.app;
app.relaunch();
app.quit();
```
How can I restart the application on Ubuntu?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
