### ISSUE TITLE
Cookies from webview do not persist when the app is restarted.

### ISSUE THREAD

**Issue by paul321** [electron/electron#9807]
* Electron version: 1.7.3
* Operating system: MacOS, Windows

In our app cookies that comes from viewview using defaultSession do not persist when the app is restarted, also devtools stores the cookies under file:// and when the app is restarted we do not see anything in cookies file:// 

Expected behavior is for cookies that share defaultSession and from webview to persist across app restarts and we need to see cookies that were saved with ajax requests which doesn't happen.

Are we doing something wrong with the webviews?

Thanks

**Comment by deepak1556** [comment]
If the page is loaded over `file` scheme then this is expected behavior, cookies are not stored for file scheme in Electron (same behavior as chrome). If you are using custom protocol, then the protocol needs to be registered as standard scheme using [protocol.registerStandardSchemes](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterstandardschemesschemes-options) .

**Comment by jondwillis** [comment]
I was able to get cookies working by adding a `partition` to my webview tag.

`<webview id="target"  ... partition="target">`

**Comment by loretoparisi** [comment]
@deepak1556 what happens if my application is loading the page from https (hence non local)? I'm using default configuration and it seems it is loosing cookies as well.
