### ISSUE TITLE
Force integrated GPU

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#9842]
* Electron version: 1.7.3
* Operating system: macOS 10.12.5

### Problem

[My app](https://github.com/sindresorhus/caprine) uses the discrete GPU constantly which has a negative impact on battery life (https://github.com/sindresorhus/caprine/issues/238). I would like to be able to force my app to only use the integrated GPU if available. Chrome has a flag for this: `--force_discrete_gpu=0`. This is different from the `app.disableHardwareAcceleration()` method as I don't want to disable hardware acceleration, just use the more power efficient GPU.

### Solution

Support it with `app.commandLine.appendSwitch()` or as a separate method `app.forceIntegratedGPU()`.

**Comment by RobertWHurst** [comment]
I second this. Having the ability to restrict the application to use integrated graphics would be great. We use Electron to host a UI and driver for a POS pin pad. We then start and execute transactions from a web service connected to the agent via a web socket. It's quite a nice solution as we can start transactions from any device via a web browser but If election is sucking back a lot of power then it may limit the experience. Any efficiency gains here would be awesome. It would enable our clients to be more mobile with their business.

**Comment by MarshallOfSound** [comment]
This actually sounds like a super useful flag to support, if I get a change I'll look at where / what this flag activates and how we can integrate it here.

**Comment by miniak** [comment]
@sindresorhus is your app using WebGL?

**Comment by sindresorhus** [comment]
No, but many other things seems to trigger the discrete GPU.

**Comment by LukePulverenti** [comment]
I think a better question is why doesn't Electron just match the behavior of Chrome when choosing which GPU to utilize? Chrome generally seems to make the right choice. 

Somewhere along the way after 1.4.X, this behavior changed and as a result if you have an app that is animation heavy, it may not be performing optimally on some systems with newer Electron versions.

I have an app that is unfortunately staying behind on 1.4.16 because with anything newer, some of our users report higher CPU usage and decreased animation performance. I could disable the GPU altogether but that is not ideal for all environments. That's why I would rather just have Electron use the same out of box decision making as Chrome.

**Comment by robatwilliams** [comment]
My observations are that Electron does match the behaviour of Chrome when choosing which GPU to use. Tested with Electron 4 (Chromium 69) vs. Chrome 71.

On my setup (desktop machine with integrated & discrete GPUs), the decision is made based on which GPU the Windows designated "main monitor" is connected to.

**Comment by robatwilliams** [comment]
I propose that this issue be re-titled to include the ability to force use of the discrete GPU - maintaining what the command line flag can do depending on the presence of `=0`. This wouldn't be possible with the proposed `app.forceIntegratedGPU()`.

The use case is demanding applications running on multiple (e.g. 6) monitors, where we want to use the most powerful GPU available.

**Comment by arvenil** [comment]
The problem is that those electron apps require high gpu when there is no monitor connected and even on battery power. This is broken at a basic level. No need for complicated environments, just run the app under macbook pro with discrete card. I just verified running facebook messenger with Franz and Chrome. With Franz, requires high perf GPU, with Chrome, it doesn't. With messenger one of franz helper processes/threads requires high perf gpu. Kill it and everything works smooth like butter - app works perfectly fine.

**Comment by enviziion** [comment]
Any progress on this? I'd like to actually see the inverse as well, because in my case its using integrated when I need the dedicated GPU

**Comment by pavelserbajlo** [comment]
There are more things to consider here. Eg Macbook Pro typically ship with Intel integrated GPU and AMD Radeon discrete GPU. While radeon is generally better/faster, it’s really not the case with H.264 encoding/decoding. Integrated Intel GPUs are extremely well optimized for this task and are always a better choice for WebRTC apps. Electron always chooses the discrete card for us, though, and we don’t have any control over this which is causing unreasonable battery drain during active calls.

My take on this is, that it shouldn’t be Electron maintainers burden to try to think about all the possible use-cases, but rather give the developers the freedom to choose if there’s a choice possible (and available through dedicated Crhomium flag for this).

**Comment by Kelt** [comment]
I second the comment above, seeing high battery drain in our app, using WebRTC, on discrete... Exposing chrome flag via `app.commandLine.appendSwitch()` would mean that each app can utilize whichever HW suits the most, without affecting electron framework as such.

**Comment by azukaar** [comment]
+1 even on Chrome the behaviour is sometime broken because it also depends on Nvidia/AMD’s drivers.
For NVidia there’s a Chrome flag to force the power GPU to strike: --disable-gpu-driver-bug-workarounds

I’m developing a webgl app and the nvidia isnt used consistently across all devices unless I set this flag

**Comment by 2emoore4** [comment]
+1

also working on a webgl app and need to force the high-performance gpu

currently looking into making an electron app installer that sets a flag on the exe. however I can't find out how to create an installer with flags, and can't even find a flag that would force windows to run the exe with the high-performance gpu.

there are ways to force the high-performance gpu through windows' control panel, and through nvidia's control panel, but I'm primarily looking for executable flags

I know this is an issue tracker and not a forum, but I'll update if I can find anything, because I know all of ya are interested

**Comment by 2emoore4** [comment]
we found that this environment variable seems to reliably force a specific gpu: https://superuser.com/questions/1074495/batch-run-with-gpu-command

the link shows two different values: one for integrated gpu and one for discrete gpu

windows-only unfortunately :(

**Comment by kwint** [comment]
Not completely relevant here, but maybe useful for other lost googlers: I also want to force the GPU on our electron app (stand alone, so no chrome). I did this by adding the electron.exe to the Nvidia control panel and forcing the external GPU. The exe is located in `project_dir\node_modules\electron\dist\electron.exe`

**Comment by oguimbal** [comment]
For the record, this feature would be quite useful for "convertible laptops" such as Surface Books.
Those have a GPU integrated in the main base (in the keyboard part), and a CPU+integrated GPU in the screen part.
When starting an Electron app while the screen is plugged on the keyboard, it may run on GPU. If the user then tries to unplug his laptop screen to switch to tablet mode, Windows complains about the Electron app preventing to dettach it. This is quite annoying (the only workaround I found was to prevent my app from using GPU directly in NVidia driver settings, which is not scalable).

**Comment by CipSoft-Components** [comment]
The following workaround worked for me, where the process will be silently restarted with environment variables set, to use the dedicated GPU.
[https://stackoverflow.com/a/63668188/9788473](https://stackoverflow.com/a/63668188/9788473)

**Comment by zcbenz** [comment]
After checking Chromium's source code, I found 2 command line switches that can achieve this:

```
--force_high_performance_gpu
--force_low_power_gpu
```

I don't know if they work on Windows, reading from the code it seems that they only work on macOS. It would be appreciated if someone could verify if they also work on Windows.

Passing them via `app.commandLine.appendSwitch` works on macOS so I'll not add new APIs for them, I'll document the flags instead.

**Comment by mycroftcanner** [comment]
The energy impact of Electron apps is scandalous! 😠😠😠 

The people at Electron have no regard  at all for the environment! @jkleinsc

**Comment by jkleinsc** [comment]
@mycroftcanner your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Please do not interact with the project for 24 hours.** After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.

**Comment by aleksey-hoffman** [comment]
@zcbenz is there still no way to force high performance GPU on Windows? 

The docs for `--force_high_performance_gpu` doesn't mention that it's MacOS-only, but this flag doesn't seem to work on Windows:

```
electron.app.commandLine.appendSwitch('force_high_performance_gpu')
```

**Comment by baxxos** [comment]
It's been 4 years - any updates on this?

**Comment by bierzorutas** [comment]
For me the same amazing problem: Chrome uses correctly the dedicated GPU, electron, dont ! It shows incorrectly glRenderer:
ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4550) and there is not way to force NVIDIA...
Can be reproduced opening in chrome and opening in electron this url https://webglreport.com/?v=2 and seen in Unmasked Renderer

**Comment by fabianhugo** [comment]
I have a dual graphics(Intel HD4000 + AMD) Ubuntu 20.04 graphics system and had to start apps with --disable-gpu for quite a while. And I just noticed that the reason was that I had `export MESA_GL_VERSION_OVERRIDE=4.5 `defined to fix a wine problem earlier. Maybe this helps someone to either fix or reproduce.
