### ISSUE TITLE
electron work with displayswitch

### ISSUE THREAD

**Issue by keyiis** [electron/electron#9846]
* Electron version:1.6.5
* Operating system:win10 x64

### Expected behavior

I opened two BrowserWindow in main process,I want the second BrowserWindow display to second monitor automatically,I can open extend monitor by `DisplaySwitch.exe /extend`,but how to send the second BrowserWindow to second monitor by code?
![qq 20170625163908](https://user-images.githubusercontent.com/7766085/27514704-fe003ad8-59c4-11e7-82e7-f050507013b7.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
