### ISSUE TITLE
add folder to favorites sidebar on mac

### ISSUE THREAD

**Issue by jorangreef** [electron/electron#9927]
Would Electron be able to provide a method to add a folder to Favorites in the Finder sidebar on macOS?

**Comment by jorangreef** [comment]
From El Capitan onwards, one can use this on the command line:

```
/usr/bin/sfltool add-item com.apple.LSSharedFileList.FavoriteItems "file:///Users/$USER/path/to/folder"
```

Would there be a better way to do this from c++?

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime i'm going to go ahead and close this.
