### ISSUE TITLE
Can not  atanimate svg element

### ISSUE THREAD

**Issue by vulgardispaly** [electron/electron#9955]
```
  <svg id="boravakForm" style="visibility: visible; background-color: lightblue; position: fixed; left: 400px; 
            top: 0px; width: 400px; height: 950px;">
      <animateTransform attributeName="transform" type="translate" from="0 0" to="-300 0" begin="0s" 
                  dur="0.05s" fill="freeze"></animateTransform>
  </svg>
```

This animation is working in chrome but it does not workes in electron, I dont know why.
So if anybody could help me I would appreciate it.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
