### ISSUE TITLE
FeatureRequest: OpenDevTools size

### ISSUE THREAD

**Issue by sancarn** [electron/electron#9960]
So currently we have:

contents.openDevTools([options])

where options can contain a `mode` property (left,right,bottom,top,window)

It would also be nice to be able to change the size which it opens and maybe the position (if it is a window)

```
contents.openDevTools({mode: "window", frame: {x: 10, y: 10, width:300, height:300})
```

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime i'm going to go ahead and close this.
