### ISSUE TITLE
e.returnValue = 'false' on 'beforeunload' event does not work

### ISSUE THREAD

**Issue by kochizufan** [electron/electron#9966]
* Electron version: 1.6.11
* Operating system: MacOS Sierra 10.12.5

### Expected behavior

To prevent page transition, I wrote the code like this:

```javascript
window.addEventListener('beforeunload', function(e) {
    if (!confirm('Page closing, OK?')) {
        e.returnValue = 'false';
        return false;
    }
});
```
By this coding, I expect to prevent page transition if user choose "Cancel" ondialog.

### Actual behavior

This code works if I show DevTools window for debugging.
But once I close DevTools window, this code not works and page transition occurs.

### How to reproduce

1. Create project with 2 pages (page A, page B).
2. Add above code on page A.
3. Add the link to page B on page A.
4. Run electron
5. Show DevTools Window and click the link. Then dialog shows, press cancel. Page transition is canceled.
6. Close DevTools and click the link. Transition occurs even if cancel is selected.

**Comment by Emanuele-Spatola** [comment]
+1

**Comment by dwt** [comment]
@maintainers: any reason this is hard to fix?

It's quite annoying that Sabaki for example cannot exit immediately when it still has a document open.

**Comment by binaryfunt** [comment]
I can reproduce this issue, but even worse. (Electron 2.0.5, Windows 10 [1803])

In `main.js`

```javascript
window.onbeforeunload = (e) => {
    e.returnValue = false;
};
```

does absolutely nothing when `window.close()` occurs, with and without the dev tools open. The window just closes.

However, `window.on('close', (e) => {e.preventDefault();}) does work.

**Comment by binaryfunt** [comment]
I would also like to add that the `window.on('close', …)` method **must be in `main.js`**

**Comment by jhg** [comment]
I have same issue when from a IPC sync return value after show a dialog, but if I return false and open dialog async then after dialog close or not (based on dialog options) it works.

It looks like if main process need to wait for a dialog then when return the value to render process and render use that value to avoid close or not then it always close.

Maybe there is a good reason, maybe try to force async to avoid block main process. To use close event maybe can to be other way but the problem is when you need to receive some value from render process just when it'll close but waiting user choose what to do. And some solution in electron could to be useful to make simple the way to open a save dialog, etc; just when user will close and it's posible to cancel (and then not to close).

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by yishn** [comment]
I can still reproduce this issue in Electron v6.0.1 on Windows 10 with developer tools closed.

**Comment by niklauslee** [comment]
I have same problem with __Electron v7.1.0__ on macOS (Catalina 10.15.1)

**Comment by d4mr** [comment]
+1
does not work on Ubuntu 20.04 **Electron v9.0.3**

**Comment by yy923683900** [comment]
same problem

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
can anyone still repro with Electron 12? I can't, but not sure if my test isn't correct. In any case, `confirm` won't work in Electron
