### ISSUE TITLE
Video streaming from webview

### ISSUE THREAD

**Issue by stigrv** [electron/electron#9976]
Add support for streaming video from a webview element. For some usecases it is desirable to stream video from a webview element through WebRTC or for viewing onto a WebGL texture.

There are already a desktopCapturer interface for streaming from a screen or a window, but this implementation requires that the window is in the foreground in order for the video to not return a black image. The window containing the source would not neccessary be in front, as the view viewing the result might be in front, as in the WebGL case.

On the webview element there is a capturePage method which could be used, but on a 1920x1080 resolution, you'll end up with 3-4 images per second at best, which is too choppy when things are moving within the webview, when viewing an animation or playing back video.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team
will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime i'm going to go ahead and close this.

**Comment by giovanni-bertoncelli** [comment]
For those who are wAndering in 2024, take a look to this answer: https://stackoverflow.com/a/78919372/7387126
